In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os
import re
import time
from selenium import webdriver

In [2]:
teams = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/teams.csv')
matches = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/all_matches.csv')

In [3]:
base = 'https://ftc-events.firstinspires.org/2022/team/'

In [4]:
teams

      Team Number                   Team Name
0            5951                    Mustangs
1            8990  Mile High Academy Mustangs
2           11020                     SKI SKY
3           15931                   Tin Heads
4           16899                 CPUsaders_T
...           ...                         ...
5908        23150                      Dragon
5909        23152                       飞虎创学队
5910        23153                         梦之队
5911        23155                        37中队
5912        23160                     Robodes

[5913 rows x 2 columns]

In [5]:
matches.head(10)

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
5,USMITCOS2,MI TC West Remote Event,USA,2023-05-07 00:00:00,2023-05-13 00:00:00
6,USMIKIOS,Kingsford Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
7,USMIRCOS,Reed City Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
8,USMIJAOS,Jackson FTC Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
9,USORROOS,OR Spring Showcase,USA,2023-05-13 00:00:00,2023-05-13 00:00:00

In [6]:
url = 'http://ftc-api.firstinspires.org/v2.0/2022/matches/'
headers = {'Authorization': 'Basic szj2024:F370ADBF-DC4B-4364-807E-F56673B369BC'}

In [7]:
r = requests.get(url + matches.iat[1,0], auth=('szj2024', 'F370ADBF-DC4B-4364-807E-F56673B369BC'))

In [8]:
r.json()

{'matches': [{'actualStartTime': '2023-05-06T10:58:07.074',
   'description': 'Qualification 1',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 1,
   'scoreRedFinal': 37,
   'scoreRedFoul': 0,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 39,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 4,
   'postResultTime': '2023-05-06T11:03:25.453',
   'teams': [{'teamNumber': 22373,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 16523, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15353, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 7065, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.418'},
  {'actualStartTime': '2023-05-06T11:05:08.389',
   'description': 'Qualification 2',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 2,
   'scoreRedFinal': 75,
   'scoreRedFoul': 30,
   'scoreRedAuto': 20,
   'scoreBlueFinal': 133,
   'scoreBlueFoul': 10,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T11:10:00.321',
   'teams': [{'teamNumber': 9931,
     'station': 'Red2',
     'dq': False,
     'onField': True},
    {'teamNumber': 15004, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 17768, 'station': 'Blue2', 'dq': False, 'onField': True},
    {'teamNumber': 7305, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.315'},
  {'actualStartTime': '2023-05-06T11:11:53.367',
   'description': 'Qualification 3',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 3,
   'scoreRedFinal': 32,
   'scoreRedFoul': 0,
   'scoreRedAuto': 20,
   'scoreBlueFinal': 182,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 27,
   'postResultTime': '2023-05-06T11:18:24.163',
   'teams': [{'teamNumber': 7048,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 12862, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15104, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 6482, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.651'},
  {'actualStartTime': '2023-05-06T11:18:56.497',
   'description': 'Qualification 4',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 4,
   'scoreRedFinal': 77,
   'scoreRedFoul': 0,
   'scoreRedAuto': 10,
   'scoreBlueFinal': 79,
   'scoreBlueFoul': 10,
   'scoreBlueAuto': 30,
   'postResultTime': '2023-05-06T11:23:28.858',
   'teams': [{'teamNumber': 22300,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 19429, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 9933, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 8603, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.641'},
  {'actualStartTime': '2023-05-06T11:24:09.87',
   'description': 'Qualification 5',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 5,
   'scoreRedFinal': 63,
   'scoreRedFoul': 0,
   'scoreRedAuto': 20,
   'scoreBlueFinal': 19,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T11:28:33.984',
   'teams': [{'teamNumber': 15397,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17975, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 5292, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15301, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.609'},
  {'actualStartTime': '2023-05-06T11:28:51.063',
   'description': 'Qualification 6',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 6,
   'scoreRedFinal': 59,
   'scoreRedFoul': 0,
   'scoreRedAuto': 29,
   'scoreBlueFinal': 4,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 2,
   'postResultTime': '2023-05-06T11:33:50.889',
   'teams': [{'teamNumber': 14649,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17155, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 11691, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 10477, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.575'},
  {'actualStartTime': '2023-05-06T11:35:16.393',
   'description': 'Qualification 7',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 7,
   'scoreRedFinal': 204,
   'scoreRedFoul': 10,
   'scoreRedAuto': 67,
   'scoreBlueFinal': 42,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T11:39:38.259',
   'teams': [{'teamNumber': 15353,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 7305, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15104, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 11618, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.542'},
  {'actualStartTime': '2023-05-06T11:40:06.487',
   'description': 'Qualification 8',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 8,
   'scoreRedFinal': 6,
   'scoreRedFoul': 0,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 72,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 3,
   'postResultTime': '2023-05-06T11:44:15.115',
   'teams': [{'teamNumber': 8603,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 6482, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15004, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 7065, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.506'},
  {'actualStartTime': '2023-05-06T11:49:59.73',
   'description': 'Qualification 9',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 9,
   'scoreRedFinal': 115,
   'scoreRedFoul': 0,
   'scoreRedAuto': 36,
   'scoreBlueFinal': 26,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T11:54:27.868',
   'teams': [{'teamNumber': 15397,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17768, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 19429, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 16523, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.494'},
  {'actualStartTime': '2023-05-06T11:54:45.442',
   'description': 'Qualification 10',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 10,
   'scoreRedFinal': 82,
   'scoreRedFoul': 0,
   'scoreRedAuto': 23,
   'scoreBlueFinal': 55,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 20,
   'postResultTime': '2023-05-06T11:59:12.465',
   'teams': [{'teamNumber': 9933,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 5292, 'station': 'Blue2', 'dq': False, 'onField': True},
    {'teamNumber': 22373, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 11691, 'station': 'Red2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.482'},
  {'actualStartTime': '2023-05-06T12:01:49.683',
   'description': 'Qualification 11',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 11,
   'scoreRedFinal': 105,
   'scoreRedFoul': 0,
   'scoreRedAuto': 47,
   'scoreBlueFinal': 83,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 5,
   'postResultTime': '2023-05-06T12:10:35.511',
   'teams': [{'teamNumber': 11618,
     'station': 'Red2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17155, 'station': 'Red1', 'dq': False, 'onField': True},
    {'teamNumber': 15301, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 7048, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.471'},
  {'actualStartTime': '2023-05-06T12:07:18.31',
   'description': 'Qualification 12',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 12,
   'scoreRedFinal': 95,
   'scoreRedFoul': 0,
   'scoreRedAuto': 44,
   'scoreBlueFinal': 17,
   'scoreBlueFoul': 10,
   'scoreBlueAuto': 10,
   'postResultTime': '2023-05-06T12:10:56.972',
   'teams': [{'teamNumber': 22300,
     'station': 'Blue1',
     'dq': False,
     'onField': True},
    {'teamNumber': 10477, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 9931, 'station': 'Red1', 'dq': False, 'onField': True},
    {'teamNumber': 12862, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.46'},
  {'actualStartTime': '2023-05-06T13:10:13.17',
   'description': 'Qualification 13',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 13,
   'scoreRedFinal': 146,
   'scoreRedFoul': 0,
   'scoreRedAuto': 42,
   'scoreBlueFinal': 29,
   'scoreBlueFoul': 10,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T13:14:10.895',
   'teams': [{'teamNumber': 7065,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17975, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 19429, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 14649, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.45'},
  {'actualStartTime': '2023-05-06T13:17:09.831',
   'description': 'Qualification 14',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 14,
   'scoreRedFinal': 49,
   'scoreRedFoul': 0,
   'scoreRedAuto': 23,
   'scoreBlueFinal': 125,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 24,
   'postResultTime': '2023-05-06T13:21:10.282',
   'teams': [{'teamNumber': 22373,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 17768, 'station': 'Red1', 'dq': False, 'onField': True},
    {'teamNumber': 6482, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15104, 'station': 'Blue1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.439'},
  {'actualStartTime': '2023-05-06T13:22:39.26',
   'description': 'Qualification 15',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 15,
   'scoreRedFinal': 67,
   'scoreRedFoul': 0,
   'scoreRedAuto': 24,
   'scoreBlueFinal': 9,
   'scoreBlueFoul': 10,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T13:27:21.689',
   'teams': [{'teamNumber': 7305,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 5292, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 17155, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 8603, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.429'},
  {'actualStartTime': '2023-05-06T13:28:20.617',
   'description': 'Qualification 16',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 16,
   'scoreRedFinal': 151,
   'scoreRedFoul': 0,
   'scoreRedAuto': 24,
   'scoreBlueFinal': 117,
   'scoreBlueFoul': 40,
   'scoreBlueAuto': 49,
   'postResultTime': '2023-05-06T13:32:19.764',
   'teams': [{'teamNumber': 7048,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 16523, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 11691, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 9931, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.407'},
  {'actualStartTime': '2023-05-06T13:33:47.281',
   'description': 'Qualification 17',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 17,
   'scoreRedFinal': 93,
   'scoreRedFoul': 40,
   'scoreRedAuto': 48,
   'scoreBlueFinal': 98,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 10,
   'postResultTime': '2023-05-06T13:38:49.795',
   'teams': [{'teamNumber': 10477,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 9933, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15353, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15301, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.63'},
  {'actualStartTime': '2023-05-06T13:44:25.665',
   'description': 'Qualification 18',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 18,
   'scoreRedFinal': 10,
   'scoreRedFoul': 0,
   'scoreRedAuto': 10,
   'scoreBlueFinal': 130,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 43,
   'postResultTime': '2023-05-06T13:49:19.349',
   'teams': [{'teamNumber': 22300,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 17975, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15004, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 11618, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.396'},
  {'actualStartTime': '2023-05-06T13:51:27.247',
   'description': 'Qualification 19',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 19,
   'scoreRedFinal': 46,
   'scoreRedFoul': 0,
   'scoreRedAuto': 10,
   'scoreBlueFinal': 16,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T13:55:52.789',
   'teams': [{'teamNumber': 8603,
     'station': 'Blue2',
     'dq': False,
     'onField': True},
    {'teamNumber': 12862, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15397, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 14649, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.62'},
  {'actualStartTime': '2023-05-06T13:59:53.343',
   'description': 'Qualification 20',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 20,
   'scoreRedFinal': 196,
   'scoreRedFoul': 0,
   'scoreRedAuto': 44,
   'scoreBlueFinal': 29,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T14:09:03.539',
   'teams': [{'teamNumber': 9931,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 15104, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 5292, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 7065, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.384'},
  {'actualStartTime': '2023-05-06T14:04:46.719',
   'description': 'Qualification 21',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 21,
   'scoreRedFinal': 26,
   'scoreRedFoul': 20,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 205,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 71,
   'postResultTime': '2023-05-06T14:09:24.102',
   'teams': [{'teamNumber': 22373,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 7305, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 19429, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 10477, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.598'},
  {'actualStartTime': '2023-05-06T14:11:55.704',
   'description': 'Qualification 22',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 22,
   'scoreRedFinal': 60,
   'scoreRedFoul': 0,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 78,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 20,
   'postResultTime': '2023-05-06T14:19:58.368',
   'teams': [{'teamNumber': 17975,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 9933, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 17155, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 17768, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.372'},
  {'actualStartTime': '2023-05-06T14:16:42.464',
   'description': 'Qualification 23',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 23,
   'scoreRedFinal': 81,
   'scoreRedFoul': 10,
   'scoreRedAuto': 34,
   'scoreBlueFinal': 18,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 0,
   'postResultTime': '2023-05-06T14:20:17.716',
   'teams': [{'teamNumber': 15353,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 7048, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 15397, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 22300, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.586'},
  {'actualStartTime': '2023-05-06T14:21:33.042',
   'description': 'Qualification 24',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 24,
   'scoreRedFinal': 80,
   'scoreRedFoul': 0,
   'scoreRedAuto': 30,
   'scoreBlueFinal': 123,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 47,
   'postResultTime': '2023-05-06T14:26:31.698',
   'teams': [{'teamNumber': 6482,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 14649, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 11618, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 16523, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.361'},
  {'actualStartTime': '2023-05-06T14:30:04.14',
   'description': 'Qualification 25',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 25,
   'scoreRedFinal': 48,
   'scoreRedFoul': 0,
   'scoreRedAuto': 10,
   'scoreBlueFinal': 179,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 46,
   'postResultTime': '2023-05-06T14:34:28.43',
   'teams': [{'teamNumber': 15301,
     'station': 'Red2',
     'dq': False,
     'onField': True},
    {'teamNumber': 12862, 'station': 'Red1', 'dq': False, 'onField': True},
    {'teamNumber': 11691, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 15004, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.564'},
  {'actualStartTime': '2023-05-06T14:36:49.293',
   'description': 'Qualification 26',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 26,
   'scoreRedFinal': 24,
   'scoreRedFoul': 0,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 108,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 29,
   'postResultTime': '2023-05-06T14:41:29.985',
   'teams': [{'teamNumber': 22373,
     'station': 'Red1',
     'dq': False,
     'onField': True},
    {'teamNumber': 17975, 'station': 'Red2', 'dq': False, 'onField': True},
    {'teamNumber': 8603, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 9931, 'station': 'Blue2', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.35'},
  {'actualStartTime': '2023-05-06T14:41:45.558',
   'description': 'Qualification 27',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 27,
   'scoreRedFinal': 29,
   'scoreRedFoul': 0,
   'scoreRedAuto': 0,
   'scoreBlueFinal': 86,
   'scoreBlueFoul': 0,
   'scoreBlueAuto': 25,
   'postResultTime': '2023-05-06T14:45:25.895',
   'teams': [{'teamNumber': 7065,
     'station': 'Red2',
     'dq': False,
     'onField': True},
    {'teamNumber': 10477, 'station': 'Blue2', 'dq': False, 'onField': True},
    {'teamNumber': 7048, 'station': 'Blue1', 'dq': False, 'onField': True},
    {'teamNumber': 17768, 'station': 'Red1', 'dq': False, 'onField': True}],
   'modifiedOn': '2023-05-06T21:33:31.553'},
  {'actualStartTime': '2023-05-06T14:46:52.225',
   'description': 'Qualification 28',
   'tournamentLevel': 'QUALIFICATION',
   'series': 0,
   'matchNumber': 28,
   'scoreRedFinal': 74,
   'scoreRedFoul': 10,
   'scoreRedAuto': 4,
   'scoreBlueFinal': 197,
   'scoreBlueFoul': 20,
   'scoreBlueAuto': 56,
   'postResultTime': '2023-05-06T14:51:16.212',

In [11]:
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""
FTC Team Statistics Calculator
@author: owsorber

OPR = Offensive Power Rating
CCWM = Calculated Contribution to Winning Margin
"""

import numpy # has matrix calculations

class Alliance:
    def __init__(self, team1, team2, score, auto, col):
        self.team1 = team1
        self.team2 = team2
        self.score = score
        self.auto = auto
        self.col = col
        if (self.auto > self.score):
            raise ValueError("Autonomous score cannot be higher than Overall score.")
    
    def __str__(self):
        return self.col + " Alliance: " + str(self.team1) + ", " + (self.team2)

class Match:
    def __init__(self, num, redAlliance, blueAlliance):
        self.num = num
        self.redAlliance = redAlliance
        self.blueAlliance = blueAlliance
    
    def __str__(self):
        return "Match # " + str(self.num) + ": (" + str(self.redAlliance.team1.num) + " & " + str(self.redAlliance.team2.num) + ") " + str(self.redAlliance.score) + " - " + str(self.blueAlliance.score) + " (" + str(self.blueAlliance.team1.num) + " & " +  str(self.blueAlliance.team2.num) + ")"


""" 
Loads the teams of an FTC event into a dictionary from an external txt file.
The dictionary maps a team number to a team name.
"""
def loadTeams(filename):
    teams = {}
    
    f = open(filename, 'r')
    
    for line in f:
#         print(line)
        line_data = line.split(', ')
#         print(line_data)
        teams[int(line_data[0])] = line_data[1][0:len(line_data[1]) - 1]
    
    return teams

""" 
Loads the match data of an FTC event into a list from an external txt file.
Assumes the format of each line in the txt file is:
red1, red2, redscore, redauto, blue1, blue2, bluescore, blueauto
"""
def loadMatches(filename):
    matches = []
    
    f = open(filename, 'r')
    
    matchNum = 1
    for line in f:
        line_data = line.split(' ')
        red1 = int(line_data[0])
        red2 = int(line_data[1])
        redscore = int(line_data[2])
        redauto = int(line_data[3])
        redAlliance = Alliance(red1, red2, redscore, redauto, "Red")
        
        blue1 = int(line_data[4])
        blue2 = int(line_data[5])
        bluescore = int(line_data[6])
        blueauto = int(line_data[7])
        blueAlliance = Alliance(blue1, blue2, bluescore, blueauto, "Blue")
        
        matches.append(Match(matchNum, redAlliance, blueAlliance))
        matchNum += 1
    
    return matches

# Converts any stat represented by a matrix into a list, used later for sorting
def convertToList(statMatrix):
    l = []
    for val in statMatrix:
        l.append(round(float(val), 3))
    return l

def calcs(match):
    # Load teams and matches from txt files
    teams = loadTeams("teams-"+match+".txt")
    matches = loadMatches("matches-"+match+".txt")

    """ 
    Build M, a matrix of alliances x teams, where each row indicates the teams in that alliance.
    A value of 1 means the team was in that alliance and a value of 0 means the team was not.
    First loop through each red alliance and then loop through each blue alliance.
    The resulting matrix should have 2 * len(matches) rows.
    """
    M = []
    for match in matches:
        r = []
        for team in teams:
            if match.redAlliance.team1 == team or match.redAlliance.team2 == team:
                r.append(1)
            else:
                r.append(0)
        M.append(r)

        b = []
        for team in teams:
            if match.blueAlliance.team1 == team or match.blueAlliance.team2 == team:
                b.append(1)
            else:
                b.append(0)
        M.append(b)

    """
    Build Scores, a matrix of alliances x 1, where each row indicates the score of that alliance.
    Build Autos, a matrix of alliances x 1, where each row indicates the autonomous score of that alliance.
    Build Margins, a matrix of alliances x 1, where each row indicates the margin of victory/loss 
    of that alliance (e.g. if an alliance wins 60-50, the value is +10).
    The alliance represented by each row corresponds to the alliance represented by each row
    in the matrix M.
    """
    Scores = []
    Autos = []
    Margins = []
    for match in matches:
        Scores.append([match.redAlliance.score])
        Scores.append([match.blueAlliance.score])
        Autos.append([match.redAlliance.auto])
        Autos.append([match.blueAlliance.auto])
        Margins.append([match.redAlliance.score - match.blueAlliance.score])
        Margins.append([match.blueAlliance.score - match.redAlliance.score])


    # Convert all matrices from type list to type matrix using numpy
    M = numpy.matrix(M)
    Scores = numpy.matrix(Scores)
    Autos = numpy.matrix(Autos)
    Margins = numpy.matrix(Margins)

    """ 
    Find the pseudoinverse of the matrix M. Multiplying this by a results matrix will find the
    solution to the overdetermined system of equations.
    """
    pseudoinverse = numpy.linalg.pinv(M)
    OPRs = numpy.matmul(pseudoinverse, Scores)
    AUTOs = numpy.matmul(pseudoinverse, Autos)
    CCWMs = numpy.matmul(pseudoinverse, Margins)
    
    """ Sort the teams by OPR. Created sortedTeams, sortedOPR, and sortedCCWM accordingly. """
    teamsList = [] # unsorted list of teams
    sortedTeams = []
    sortedOPR = []
    sortedAuto = []
    sortedCCWM = []

    for team in teams:
        teamsList.append(team)

    while len(sortedTeams) < len(teamsList):
        oprs = convertToList(OPRs)
        autos = convertToList(AUTOs)
        ccwms = convertToList(CCWMs)

        # Get the first team not already sorted to compare all the other teams to that team
        for i in range(len(teamsList)):
            if teamsList[i] not in sortedTeams:
                bestTeam = teamsList[i]
                bestOPR = oprs[i]
                bestAUTO = autos[i]
                bestCCWM = ccwms[i]
                break

        # Loop through teamsList to find next best team
        for i in range(len(teamsList)):
            if oprs[i] > bestOPR and teamsList[i] not in sortedTeams:
                bestTeam = teamsList[i]
                bestOPR = oprs[i]
                bestAUTO = autos[i]
                bestCCWM = ccwms[i]
        sortedTeams.append(bestTeam)
        sortedOPR.append(bestOPR)
        sortedAuto.append(bestAUTO)
        sortedCCWM.append(bestCCWM)
        
    ret = []
    
    """ Print the data to the screen """
#     print("\nTEAM\t\tOPR\t\tAuto\t\tCCWM\t\tTeam Name")
    for i in range(len(teamsList)):
        teamNum = sortedTeams[i]
        d = {}
        d['TeamNum'] = teamNum
        d['OPR'] = sortedOPR[i]
        d['Auto'] = sortedAuto[i]
        d['CCWM'] = sortedCCWM[i]
        d['TeamName'] = teams[teamNum]
        
        ret.append(d)
    print(ret)
        
    return ret

In [12]:
from csv import writer

In [13]:
base = 'https://ftc-events.firstinspires.org/2022/'

In [46]:
base2 = 'https://ftc-events.firstinspires.org'
def getQuals(match_link):#base2 + match_link+'/qualifications'
    soup = BeautifulSoup(requests.get(match_link).content, 'html.parser')
    
    quals = soup.find('tbody', {'id' : 'match-results'}).find_all('a', string = re.compile('Qualification .*'))
    
    return quals

In [47]:
def getTeams(match_link):
    soup = BeautifulSoup(requests.get(match_link.replace('/qualifications', '')).content, 'html.parser')
    
#     print(soup)
    
    table = soup.find_all('tr', {'class': ""})
    
    tl = set()
    
    for elem in table:
        e =elem.find('a', string = re.compile('\d*'))
        try:
            tl.add(e.text.strip())
        except Exception as e:
            continue
    return tl

In [48]:
def getTeamsQual(href):
    soup = BeautifulSoup(requests.get(href).content, 'html.parser')
    s = soup.find_all('div', {'class':"col-xs-6 pp-teams"})
    
    return[[s[0].find('a').text.strip(), s[1].find('a').text.strip()], [s[2].find('a').text.strip(), s[3].find('a').text.strip()]]

In [49]:
def getScores(href):
    soup = BeautifulSoup(requests.get(href).content, 'html.parser')
    bs = soup.find('div', {'class':"col-xs-4 col-md-2 pp-scoreboard-totalpoints-blue"}).text.strip()
    ba = soup.find_all('div', {'class':"pp-results-score-left col-xs-2"})[0].text.strip()
    rs = soup.find('div', {'class':"col-xs-4 col-md-2 pp-scoreboard-totalpoints-red"}).text.strip()
    ra = soup.find_all('div', {'class':"pp-results-score-right col-xs-2"})[0].text.strip()
    
    
    return [[bs, ba], [rs, ra]]

In [14]:
matches

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
...,...,...,...,...,...
1135,USTXSOBEOS,FIRST in Texas UIL State 5A,USA,2023-03-24 00:00:00,2023-03-24 00:00:00
1136,CNDIS,Dianjian Peony Cup,China,2023-04-01 00:00:00,2023-04-02 00:00:00
1137,GBREQ,GB Remote Regional,United Kingdom,2023-03-23 00:00:00,2023-03-29 00:00:00
1138,USTXCECCS,TX-Central Buc Days 2023 Robot Rodeo,USA,2023-05-13 00:00:00,2023-05-13 00:00:00
1139,FTCCMP1,FIRST Championship - Houston - World Champions...,USA,2023-04-18 00:00:00,2023-04-22 00:00:00

In [32]:
# 0 to 10
for i in range(matches.shape[0]):
    print("i "+str(i))
    row = matches.iloc[i]
    link = row['Link']

    try:
        tset = getTeams(link)    
    
        match_list = getQuals(link)
    except Exception as e:
        continue
    
    if len(tset)==0 or len(match_list)==0:
        continue
    
    with open("./matches-"+row['Link']+".txt", "a") as mfile:
        for i in range(len(match_list)):
            curr_m = match_list[i]['href']
            team_list = getTeamsQual(curr_m)

            red = team_list[1]
            blue = team_list[0]

            res = getScores(curr_m)

            #match file
            mfile.write(str(red[0]) + " " + str(red[1]) + " " + str(res[1][0]) + " "+ str(res[1][1])+ " "+
                        str(blue[0]) + " "+ str(blue[1]) + " " + str(res[0][0]) + " " + str(res[0][1])+"\n"
                       )
    with open("./teams-"+row['Link']+".txt","a") as tfile:
        for t in tset:
            tfile.write(str(t) + ", " + teams[teams['Team Number']==int(t)].iloc[0,1]+ "\n")
        
    
    
    print(tset)
    
    results = calcs(row['Link'])
    print(row['Link'])
    
    print(results)
    
    for team_result in results:
        yes = False
        if not os.path.exists(os.getcwd().replace("scripts", "data/team_data/"+str(team_result['TeamNum'])+".csv")):
            yes = True
        with open(os.getcwd().replace("scripts", "data/team_data/"+str(team_result['TeamNum'])+".csv"), 'a') as f_object:
            writer_object = writer(f_object)
            if yes:
                writer_object.writerow(['ID', 'OPR', 'Auto', 'CCWM'])
        
                
            writer_object.writerow([row['Link'], team_result['OPR'], team_result['Auto'], team_result['CCWM']])

        f_object.close()

    
    tfile.close()
    mfile.close()
#     rmdir("teams-"+match+".txt")
#     rmdir("matches-"+match+".txt")

i 799
{'16917', '20150', '14931', '22110', '14521', '11409', '22161', '22162', '17178', '19706', '22178', '11873', '17008', '19542', '13546', '9617', '14561', '10075'}
[{'TeamNum': 22161, 'OPR': 98.998, 'Auto': 8.425, 'CCWM': 57.032, 'TeamName': 'M-TECH Dark Matter'}, {'TeamNum': 19706, 'OPR': 85.952, 'Auto': 16.623, 'CCWM': 46.101, 'TeamName': 'Potential Energy'}, {'TeamNum': 11873, 'OPR': 84.465, 'Auto': 28.55, 'CCWM': 57.282, 'TeamName': 'Element Unknown'}, {'TeamNum': 16917, 'OPR': 83.585, 'Auto': 6.988, 'CCWM': 39.162, 'TeamName': 'Gear Wizards'}, {'TeamNum': 22162, 'OPR': 81.406, 'Auto': 25.593, 'CCWM': 33.946, 'TeamName': 'M-TECH ProtoPlazma'}, {'TeamNum': 19542, 'OPR': 44.606, 'Auto': 7.858, 'CCWM': 6.257, 'TeamName': 'The CIA'}, {'TeamNum': 10075, 'OPR': 40.274, 'Auto': 5.606, 'CCWM': -7.293, 'TeamName': 'Tech Turtles'}, {'TeamNum': 22178, 'OPR': 39.676, 'Auto': 1.257, 'CCWM': -12.095, 'TeamName': 'Infrared'}, {'TeamNum': 14561, 'OPR': 37.111, 'Auto': 7.308, 'CCWM': -12.167, 'TeamName': 'Tech Tigers'}, {'TeamNum': 9617, 'OPR': 35.003, 'Auto': 0.927, 'CCWM': -4.061, 'TeamName': 'Loose Screws'}, {'TeamNum': 17008, 'OPR': 29.904, 'Auto': 11.619, 'CCWM': -4.672, 'TeamName': 'PioNerds Green'}, {'TeamNum': 20150, 'OPR': 28.766, 'Auto': 2.505, 'CCWM': -27.076, 'TeamName': 'The Broken Hexagon'}, {'TeamNum': 13546, 'OPR': 27.71, 'Auto': 15.277, 'CCWM': -12.852, 'TeamName': 'Shifting Gears'}, {'TeamNum': 14931, 'OPR': 21.477, 'Auto': 8.403, 'CCWM': -14.983, 'TeamName': 'PioNerds Black'}, {'TeamNum': 22110, 'OPR': 15.24, 'Auto': -0.54, 'CCWM': -30.389, 'TeamName': 'AL2'}, {'TeamNum': 17178, 'OPR': 9.736, 'Auto': 2.076, 'CCWM': -59.595, 'TeamName': 'Phantom Warriors'}, {'TeamNum': 11409, 'OPR': 9.422, 'Auto': -2.651, 'CCWM': -4.677, 'TeamName': 'Robofobixx'}, {'TeamNum': 14521, 'OPR': 8.337, 'Auto': 5.677, 'CCWM': -49.919, 'TeamName': 'Excalibur'}]
USMNLLT2
[{'TeamNum': 22161, 'OPR': 98.998, 'Auto': 8.425, 'CCWM': 57.032, 'TeamName': 'M-TECH Dark Matter'}, {'TeamNum': 19706, 'OPR': 85.952, 'Auto': 16.623, 'CCWM': 46.101, 'TeamName': 'Potential Energy'}, {'TeamNum': 11873, 'OPR': 84.465, 'Auto': 28.55, 'CCWM': 57.282, 'TeamName': 'Element Unknown'}, {'TeamNum': 16917, 'OPR': 83.585, 'Auto': 6.988, 'CCWM': 39.162, 'TeamName': 'Gear Wizards'}, {'TeamNum': 22162, 'OPR': 81.406, 'Auto': 25.593, 'CCWM': 33.946, 'TeamName': 'M-TECH ProtoPlazma'}, {'TeamNum': 19542, 'OPR': 44.606, 'Auto': 7.858, 'CCWM': 6.257, 'TeamName': 'The CIA'}, {'TeamNum': 10075, 'OPR': 40.274, 'Auto': 5.606, 'CCWM': -7.293, 'TeamName': 'Tech Turtles'}, {'TeamNum': 22178, 'OPR': 39.676, 'Auto': 1.257, 'CCWM': -12.095, 'TeamName': 'Infrared'}, {'TeamNum': 14561, 'OPR': 37.111, 'Auto': 7.308, 'CCWM': -12.167, 'TeamName': 'Tech Tigers'}, {'TeamNum': 9617, 'OPR': 35.003, 'Auto': 0.927, 'CCWM': -4.061, 'TeamName': 'Loose Screws'}, {'TeamNum': 17008, 'OPR': 29.904, 'Auto': 11.619, 'CCWM': -4.672, 'TeamName': 'PioNerds Green'}, {'TeamNum': 20150, 'OPR': 28.766, 'Auto': 2.505, 'CCWM': -27.076, 'TeamName': 'The Broken Hexagon'}, {'TeamNum': 13546, 'OPR': 27.71, 'Auto': 15.277, 'CCWM': -12.852, 'TeamName': 'Shifting Gears'}, {'TeamNum': 14931, 'OPR': 21.477, 'Auto': 8.403, 'CCWM': -14.983, 'TeamName': 'PioNerds Black'}, {'TeamNum': 22110, 'OPR': 15.24, 'Auto': -0.54, 'CCWM': -30.389, 'TeamName': 'AL2'}, {'TeamNum': 17178, 'OPR': 9.736, 'Auto': 2.076, 'CCWM': -59.595, 'TeamName': 'Phantom Warriors'}, {'TeamNum': 11409, 'OPR': 9.422, 'Auto': -2.651, 'CCWM': -4.677, 'TeamName': 'Robofobixx'}, {'TeamNum': 14521, 'OPR': 8.337, 'Auto': 5.677, 'CCWM': -49.919, 'TeamName': 'Excalibur'}]
i 800
{'7139', '9579', '7961', '18292', '4194', '20378', '17214', '4193', '3665', '11965', '17560'}
[{'TeamNum': 7139, 'OPR': 84.875, 'Auto': 18.426, 'CCWM': 69.553, 'TeamName': 'KHS Robotics'}, {'TeamNum': 4193, 'OPR': 66.044, 'Auto': 15.483, 'CCWM': 37.451, 'TeamName': 'Those Guys'}, {'TeamNum': 7961, 'OPR': 51.925, 'Auto': 11.677, 'CCWM': 42.864, 'TeamName': 'MotorDame'}, {'TeamNum': 3665, 'OPR': 49.063, 'Auto': 5.403, 'CCWM': 39.127, 'TeamName': 'Leopold GearHeads'}, {'TeamNum': 9579, 'OPR': 42.686, 'Auto': 16.876, 'CCWM': 2.296, 'TeamName': 'Poplar Bluff Iron Mules'}, {'TeamNum': 20378, 'OPR': 34.293, 'Auto': 10.695, 'CCWM': 7.714, 'TeamName': 'Perryville Pirates'}, {'TeamNum': 18292, 'OPR': 25.035, 'Auto': 4.565, 'CCWM': -3.021, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 4194, 'OPR': 15.495, 'Auto': 7.631, 'CCWM': -27.388, 'TeamName': 'Silent Reign'}, {'TeamNum': 11965, 'OPR': 14.199, 'Auto': 2.743, 'CCWM': -28.162, 'TeamName': 'Steampunks'}, {'TeamNum': 17560, 'OPR': -1.508, 'Auto': 2.042, 'CCWM': -65.908, 'TeamName': 'Central Junior High TigerTECH'}, {'TeamNum': 17214, 'OPR': -11.93, 'Auto': -3.668, 'CCWM': -73.814, 'TeamName': 'Cape Central Tiger Bytes'}]
USMOKSSEM3
[{'TeamNum': 7139, 'OPR': 84.875, 'Auto': 18.426, 'CCWM': 69.553, 'TeamName': 'KHS Robotics'}, {'TeamNum': 4193, 'OPR': 66.044, 'Auto': 15.483, 'CCWM': 37.451, 'TeamName': 'Those Guys'}, {'TeamNum': 7961, 'OPR': 51.925, 'Auto': 11.677, 'CCWM': 42.864, 'TeamName': 'MotorDame'}, {'TeamNum': 3665, 'OPR': 49.063, 'Auto': 5.403, 'CCWM': 39.127, 'TeamName': 'Leopold GearHeads'}, {'TeamNum': 9579, 'OPR': 42.686, 'Auto': 16.876, 'CCWM': 2.296, 'TeamName': 'Poplar Bluff Iron Mules'}, {'TeamNum': 20378, 'OPR': 34.293, 'Auto': 10.695, 'CCWM': 7.714, 'TeamName': 'Perryville Pirates'}, {'TeamNum': 18292, 'OPR': 25.035, 'Auto': 4.565, 'CCWM': -3.021, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 4194, 'OPR': 15.495, 'Auto': 7.631, 'CCWM': -27.388, 'TeamName': 'Silent Reign'}, {'TeamNum': 11965, 'OPR': 14.199, 'Auto': 2.743, 'CCWM': -28.162, 'TeamName': 'Steampunks'}, {'TeamNum': 17560, 'OPR': -1.508, 'Auto': 2.042, 'CCWM': -65.908, 'TeamName': 'Central Junior High TigerTECH'}, {'TeamNum': 17214, 'OPR': -11.93, 'Auto': -3.668, 'CCWM': -73.814, 'TeamName': 'Cape Central Tiger Bytes'}]
i 801
{'17206', '20298', '11659', '7678', '13092', '20323', '21586', '4964', '5893', '13132', '11678', '13337', '6168'}
[{'TeamNum': 5893, 'OPR': 89.348, 'Auto': 17.755, 'CCWM': 42.012, 'TeamName': 'Direct Current'}, {'TeamNum': 20323, 'OPR': 74.087, 'Auto': 23.93, 'CCWM': 51.949, 'TeamName': 'Sigma'}, {'TeamNum': 4964, 'OPR': 71.454, 'Auto': 19.906, 'CCWM': 43.578, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 7678, 'OPR': 53.527, 'Auto': 8.438, 'CCWM': -18.798, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 13337, 'OPR': 49.417, 'Auto': 12.802, 'CCWM': 3.536, 'TeamName': 'ROBOZARK'}, {'TeamNum': 17206, 'OPR': 49.099, 'Auto': 1.066, 'CCWM': 17.686, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 13132, 'OPR': 47.769, 'Auto': 1.587, 'CCWM': -17.67, 'TeamName': 'Miner Clue'}, {'TeamNum': 13092, 'OPR': 36.043, 'Auto': 1.921, 'CCWM': 12.342, 'TeamName': 'Central Processing Units'}, {'TeamNum': 20298, 'OPR': 31.832, 'Auto': 2.899, 'CCWM': 1.366, 'TeamName': 'Nvizable Robotix'}, {'TeamNum': 11678, 'OPR': 28.089, 'Auto': 1.616, 'CCWM': -30.572, 'TeamName': 'Arrow Flight '}, {'TeamNum': 6168, 'OPR': 26.776, 'Auto': 5.268, 'CCWM': -42.603, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 11659, 'OPR': 24.576, 'Auto': 18.144, 'CCWM': -33.886, 'TeamName': 'Wheaton Robodogs'}, {'TeamNum': 21586, 'OPR': 21.33, 'Auto': -1.919, 'CCWM': -24.073, 'TeamName': 'Broken Arrow'}]
USMOKSSWMIM7
[{'TeamNum': 5893, 'OPR': 89.348, 'Auto': 17.755, 'CCWM': 42.012, 'TeamName': 'Direct Current'}, {'TeamNum': 20323, 'OPR': 74.087, 'Auto': 23.93, 'CCWM': 51.949, 'TeamName': 'Sigma'}, {'TeamNum': 4964, 'OPR': 71.454, 'Auto': 19.906, 'CCWM': 43.578, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 7678, 'OPR': 53.527, 'Auto': 8.438, 'CCWM': -18.798, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 13337, 'OPR': 49.417, 'Auto': 12.802, 'CCWM': 3.536, 'TeamName': 'ROBOZARK'}, {'TeamNum': 17206, 'OPR': 49.099, 'Auto': 1.066, 'CCWM': 17.686, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 13132, 'OPR': 47.769, 'Auto': 1.587, 'CCWM': -17.67, 'TeamName': 'Miner Clue'}, {'TeamNum': 13092, 'OPR': 36.043, 'Auto': 1.921, 'CCWM': 12.342, 'TeamName': 'Central Processing Units'}, {'TeamNum': 20298, 'OPR': 31.832, 'Auto': 2.899, 'CCWM': 1.366, 'TeamName': 'Nvizable Robotix'}, {'TeamNum': 11678, 'OPR': 28.089, 'Auto': 1.616, 'CCWM': -30.572, 'TeamName': 'Arrow Flight '}, {'TeamNum': 6168, 'OPR': 26.776, 'Auto': 5.268, 'CCWM': -42.603, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 11659, 'OPR': 24.576, 'Auto': 18.144, 'CCWM': -33.886, 'TeamName': 'Wheaton Robodogs'}, {'TeamNum': 21586, 'OPR': 21.33, 'Auto': -1.919, 'CCWM': -24.073, 'TeamName': 'Broken Arrow'}]

i 802
{'5227', '16309', '11102', '21806', '13498', '18775', '21858', '19815', '10127', '15583', '9960', '3409'}
[{'TeamNum': 5227, 'OPR': 77.878, 'Auto': 20.284, 'CCWM': 44.353, 'TeamName': 'Galactech'}, {'TeamNum': 16309, 'OPR': 73.512, 'Auto': 22.594, 'CCWM': 27.845, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 21858, 'OPR': 70.674, 'Auto': 10.79, 'CCWM': 35.429, 'TeamName': 'Red Shift Rovers'}, {'TeamNum': 11102, 'OPR': 69.741, 'Auto': 13.919, 'CCWM': 34.318, 'TeamName': 'Team M.O.R.E. (Marshall Owls Robotics & Engineering)'}, {'TeamNum': 3409, 'OPR': 53.099, 'Auto': 2.425, 'CCWM': 4.014, 'TeamName': 'Astromechs'}, {'TeamNum': 10127, 'OPR': 47.436, 'Auto': 9.518, 'CCWM': -11.293, 'TeamName': "Tesla's Knights"}, {'TeamNum': 9960, 'OPR': 43.285, 'Auto': 7.203, 'CCWM': 2.004, 'TeamName': 'N.E.R.D.S'}, {'TeamNum': 19815, 'OPR': 42.997, 'Auto': 17.365, 'CCWM': -0.274, 'TeamName': 'The Law'}, {'TeamNum': 13498, 'OPR': 32.663, 'Auto': -1.049, 'CCWM': -14.24, 'TeamName': 'Robo Hawks'}, {'TeamNum': 18775, 'OPR': 27.139, 'Auto': 0.164, 'CCWM': -38.725, 'TeamName': 'St. Joe Circuit Breakers'}, {'TeamNum': 21806, 'OPR': 22.38, 'Auto': 8.626, 'CCWM': -27.989, 'TeamName': 'Eighty Seven and Running'}, {'TeamNum': 15583, 'OPR': 7.528, 'Auto': -1.006, 'CCWM': -55.443, 'TeamName': 'Electric Eagles'}]
USMOKSKCEM5
[{'TeamNum': 5227, 'OPR': 77.878, 'Auto': 20.284, 'CCWM': 44.353, 'TeamName': 'Galactech'}, {'TeamNum': 16309, 'OPR': 73.512, 'Auto': 22.594, 'CCWM': 27.845, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 21858, 'OPR': 70.674, 'Auto': 10.79, 'CCWM': 35.429, 'TeamName': 'Red Shift Rovers'}, {'TeamNum': 11102, 'OPR': 69.741, 'Auto': 13.919, 'CCWM': 34.318, 'TeamName': 'Team M.O.R.E. (Marshall Owls Robotics & Engineering)'}, {'TeamNum': 3409, 'OPR': 53.099, 'Auto': 2.425, 'CCWM': 4.014, 'TeamName': 'Astromechs'}, {'TeamNum': 10127, 'OPR': 47.436, 'Auto': 9.518, 'CCWM': -11.293, 'TeamName': "Tesla's Knights"}, {'TeamNum': 9960, 'OPR': 43.285, 'Auto': 7.203, 'CCWM': 2.004, 'TeamName': 'N.E.R.D.S'}, {'TeamNum': 19815, 'OPR': 42.997, 'Auto': 17.365, 'CCWM': -0.274, 'TeamName': 'The Law'}, {'TeamNum': 13498, 'OPR': 32.663, 'Auto': -1.049, 'CCWM': -14.24, 'TeamName': 'Robo Hawks'}, {'TeamNum': 18775, 'OPR': 27.139, 'Auto': 0.164, 'CCWM': -38.725, 'TeamName': 'St. Joe Circuit Breakers'}, {'TeamNum': 21806, 'OPR': 22.38, 'Auto': 8.626, 'CCWM': -27.989, 'TeamName': 'Eighty Seven and Running'}, {'TeamNum': 15583, 'OPR': 7.528, 'Auto': -1.006, 'CCWM': -55.443, 'TeamName': 'Electric Eagles'}]
i 803
{'11908', '10173', '9808', '14959', '9103', '9034', '9102', '14919', '20391', '22363', '18415', '16225'}
[{'TeamNum': 10173, 'OPR': 82.215, 'Auto': 20.654, 'CCWM': 60.148, 'TeamName': 'Ravonics Gemini'}, {'TeamNum': 9102, 'OPR': 60.073, 'Auto': 15.534, 'CCWM': 34.694, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 9103, 'OPR': 57.585, 'Auto': 19.009, 'CCWM': 46.997, 'TeamName': 'Ravonics Rover'}, {'TeamNum': 9808, 'OPR': 53.426, 'Auto': 16.866, 'CCWM': 34.154, 'TeamName': 'Team Chargers'}, {'TeamNum': 9034, 'OPR': 46.024, 'Auto': 24.176, 'CCWM': 5.325, 'TeamName': 'Mustangs '}, {'TeamNum': 20391, 'OPR': 41.903, 'Auto': 2.206, 'CCWM': -8.106, 'TeamName': 'Tungsten Tigers'}, {'TeamNum': 14959, 'OPR': 32.602, 'Auto': 1.831, 'CCWM': -1.537, 'TeamName': 'Steel Wolves'}, {'TeamNum': 22363, 'OPR': 25.025, 'Auto': 7.707, 'CCWM': -19.422, 'TeamName': 'Patton Junior High 1'}, {'TeamNum': 18415, 'OPR': 24.965, 'Auto': 1.852, 'CCWM': -34.432, 'TeamName': 'The Hoplites'}, {'TeamNum': 14919, 'OPR': 8.659, 'Auto': -1.315, 'CCWM': -49.103, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 11908, 'OPR': 5.697, 'Auto': -1.153, 'CCWM': -29.985, 'TeamName': 'GEAR'}, {'TeamNum': 16225, 'OPR': -0.175, 'Auto': 0.799, 'CCWM': -38.733, 'TeamName': 'The Button Bucks'}]
USMOKSKCWM5
[{'TeamNum': 10173, 'OPR': 82.215, 'Auto': 20.654, 'CCWM': 60.148, 'TeamName': 'Ravonics Gemini'}, {'TeamNum': 9102, 'OPR': 60.073, 'Auto': 15.534, 'CCWM': 34.694, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 9103, 'OPR': 57.585, 'Auto': 19.009, 'CCWM': 46.997, 'TeamName': 'Ravonics Rover'}, {'TeamNum': 9808, 'OPR': 53.426, 'Auto': 16.866, 'CCWM': 34.154, 'TeamName': 'Team Chargers'}, {'TeamNum': 9034, 'OPR': 46.024, 'Auto': 24.176, 'CCWM': 5.325, 'TeamName': 'Mustangs '}, {'TeamNum': 20391, 'OPR': 41.903, 'Auto': 2.206, 'CCWM': -8.106, 'TeamName': 'Tungsten Tigers'}, {'TeamNum': 14959, 'OPR': 32.602, 'Auto': 1.831, 'CCWM': -1.537, 'TeamName': 'Steel Wolves'}, {'TeamNum': 22363, 'OPR': 25.025, 'Auto': 7.707, 'CCWM': -19.422, 'TeamName': 'Patton Junior High 1'}, {'TeamNum': 18415, 'OPR': 24.965, 'Auto': 1.852, 'CCWM': -34.432, 'TeamName': 'The Hoplites'}, {'TeamNum': 14919, 'OPR': 8.659, 'Auto': -1.315, 'CCWM': -49.103, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 11908, 'OPR': 5.697, 'Auto': -1.153, 'CCWM': -29.985, 'TeamName': 'GEAR'}, {'TeamNum': 16225, 'OPR': -0.175, 'Auto': 0.799, 'CCWM': -38.733, 'TeamName': 'The Button Bucks'}]
i 804
{'11191', '19838', '3592', '10265', '3658', '12427', '19448', '18118', '9905', '11203', '5155'}
[{'TeamNum': 3658, 'OPR': 141.854, 'Auto': 41.461, 'CCWM': 122.992, 'TeamName': 'The BOSONS'}, {'TeamNum': 19448, 'OPR': 84.477, 'Auto': 18.19, 'CCWM': 40.293, 'TeamName': 'X BOTS'}, {'TeamNum': 10265, 'OPR': 77.819, 'Auto': 11.649, 'CCWM': 67.095, 'TeamName': 'Force Green'}, {'TeamNum': 9905, 'OPR': 47.387, 'Auto': 13.087, 'CCWM': 4.301, 'TeamName': 'Rampire'}, {'TeamNum': 5155, 'OPR': 42.167, 'Auto': 19.725, 'CCWM': -30.798, 'TeamName': 'Ramifications'}, {'TeamNum': 18118, 'OPR': 41.066, 'Auto': 7.406, 'CCWM': -7.399, 'TeamName': 'Mindstorm Troopers'}, {'TeamNum': 12427, 'OPR': 34.664, 'Auto': 2.238, 'CCWM': -36.776, 'TeamName': 'Bot of Steel'}, {'TeamNum': 11191, 'OPR': 29.992, 'Auto': 1.891, 'CCWM': -36.263, 'TeamName': 'Red Vectors'}, {'TeamNum': 19838, 'OPR': 27.658, 'Auto': 9.103, 'CCWM': -36.759, 'TeamName': 'Brute Force'}, {'TeamNum': 3592, 'OPR': 16.755, 'Auto': -0.677, 'CCWM': -31.612, 'TeamName': 'The MESONS'}, {'TeamNum': 11203, 'OPR': 16.514, 'Auto': 0.917, 'CCWM': -65.024, 'TeamName': 'DURT (DeSmet Ultimate Robotics Team)'}]
USMOKSSTLMM4
[{'TeamNum': 3658, 'OPR': 141.854, 'Auto': 41.461, 'CCWM': 122.992, 'TeamName': 'The BOSONS'}, {'TeamNum': 19448, 'OPR': 84.477, 'Auto': 18.19, 'CCWM': 40.293, 'TeamName': 'X BOTS'}, {'TeamNum': 10265, 'OPR': 77.819, 'Auto': 11.649, 'CCWM': 67.095, 'TeamName': 'Force Green'}, {'TeamNum': 9905, 'OPR': 47.387, 'Auto': 13.087, 'CCWM': 4.301, 'TeamName': 'Rampire'}, {'TeamNum': 5155, 'OPR': 42.167, 'Auto': 19.725, 'CCWM': -30.798, 'TeamName': 'Ramifications'}, {'TeamNum': 18118, 'OPR': 41.066, 'Auto': 7.406, 'CCWM': -7.399, 'TeamName': 'Mindstorm Troopers'}, {'TeamNum': 12427, 'OPR': 34.664, 'Auto': 2.238, 'CCWM': -36.776, 'TeamName': 'Bot of Steel'}, {'TeamNum': 11191, 'OPR': 29.992, 'Auto': 1.891, 'CCWM': -36.263, 'TeamName': 'Red Vectors'}, {'TeamNum': 19838, 'OPR': 27.658, 'Auto': 9.103, 'CCWM': -36.759, 'TeamName': 'Brute Force'}, {'TeamNum': 3592, 'OPR': 16.755, 'Auto': -0.677, 'CCWM': -31.612, 'TeamName': 'The MESONS'}, {'TeamNum': 11203, 'OPR': 16.514, 'Auto': 0.917, 'CCWM': -65.024, 'TeamName': 'DURT (DeSmet Ultimate Robotics Team)'}]
i 805
{'6387', '406', '7951', '10588', '3591', '10106', '14867', '5439', '5248', '5118', '3505', '5119'}
[{'TeamNum': 7951, 'OPR': 63.196, 'Auto': 15.459, 'CCWM': 16.715, 'TeamName': 'The KAONS'}, {'TeamNum': 5248, 'OPR': 60.547, 'Auto': 16.301, 'CCWM': 58.561, 'TeamName': 'The FERMIONS'}, {'TeamNum': 5439, 'OPR': 54.088, 'Auto': 17.495, 'CCWM': 9.144, 'TeamName': 'The GLUONS'}, {'TeamNum': 406, 'OPR': 53.584, 'Auto': 5.779, 'CCWM': 30.668, 'TeamName': "Boulson's Revenge"}, {'TeamNum': 3591, 'OPR': 42.847, 'Auto': 25.595, 'CCWM': -10.023, 'TeamName': 'The QUARKS'}, {'TeamNum': 5119, 'OPR': 42.547, 'Auto': 10.112, 'CCWM': 34.377, 'TeamName': 'The BARYONS'}, {'TeamNum': 14867, 'OPR': 42.532, 'Auto': 19.543, 'CCWM': 10.259, 'TeamName': 'Cougar Bots'}, {'TeamNum': 10106, 'OPR': 36.839, 'Auto': 3.803, 'CCWM': -22.565, 'TeamName': 'CBC Robotics'}, {'TeamNum': 3505, 'OPR': 34.652, 'Auto': 8.996, 'CCWM': -24.099, 'TeamName': 'Cadet Bot Crew'}, {'TeamNum': 5118, 'OPR': 31.474, 'Auto': 1.415, 'CCWM': -6.01, 'TeamName': 'The HADRONS'}, {'TeamNum': 6387, 'OPR': 27.01, 'Auto': 0.519, 'CCWM': -32.922, 'TeamName': 'Brobots'}, {'TeamNum': 10588, 'OPR': 8.018, 'Auto': -6.683, 'CCWM': -64.107, 'TeamName': 'The LUXONS'}]
USMOKSSTLMM5
[{'TeamNum': 7951, 'OPR': 63.196, 'Auto': 15.459, 'CCWM': 16.715, 'TeamName': 'The KAONS'}, {'TeamNum': 5248, 'OPR': 60.547, 'Auto': 16.301, 'CCWM': 58.561, 'TeamName': 'The FERMIONS'}, {'TeamNum': 5439, 'OPR': 54.088, 'Auto': 17.495, 'CCWM': 9.144, 'TeamName': 'The GLUONS'}, {'TeamNum': 406, 'OPR': 53.584, 'Auto': 5.779, 'CCWM': 30.668, 'TeamName': "Boulson's Revenge"}, {'TeamNum': 3591, 'OPR': 42.847, 'Auto': 25.595, 'CCWM': -10.023, 'TeamName': 'The QUARKS'}, {'TeamNum': 5119, 'OPR': 42.547, 'Auto': 10.112, 'CCWM': 34.377, 'TeamName': 'The BARYONS'}, {'TeamNum': 14867, 'OPR': 42.532, 'Auto': 19.543, 'CCWM': 10.259, 'TeamName': 'Cougar Bots'}, {'TeamNum': 10106, 'OPR': 36.839, 'Auto': 3.803, 'CCWM': -22.565, 'TeamName': 'CBC Robotics'}, {'TeamNum': 3505, 'OPR': 34.652, 'Auto': 8.996, 'CCWM': -24.099, 'TeamName': 'Cadet Bot Crew'}, {'TeamNum': 5118, 'OPR': 31.474, 'Auto': 1.415, 'CCWM': -6.01, 'TeamName': 'The HADRONS'}, {'TeamNum': 6387, 'OPR': 27.01, 'Auto': 0.519, 'CCWM': -32.922, 'TeamName': 'Brobots'}, {'TeamNum': 10588, 'OPR': 8.018, 'Auto': -6.683, 'CCWM': -64.107, 'TeamName': 'The LUXONS'}]
i 806

{'17637', '8895', '8905', '9027', '5404', '7525', '6285', '11539', '14186', '4982', '14257', '5703', '13051'}
[{'TeamNum': 14186, 'OPR': 73.007, 'Auto': 19.176, 'CCWM': 63.036, 'TeamName': 'P3'}, {'TeamNum': 7525, 'OPR': 66.547, 'Auto': 16.531, 'CCWM': 53.501, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 8895, 'OPR': 36.223, 'Auto': 16.489, 'CCWM': 27.215, 'TeamName': 'Loose Screws'}, {'TeamNum': 4982, 'OPR': 29.43, 'Auto': -0.001, 'CCWM': 28.422, 'TeamName': 'Cafe Bot'}, {'TeamNum': 14257, 'OPR': 28.675, 'Auto': 5.048, 'CCWM': 26.373, 'TeamName': 'REBELBOTS'}, {'TeamNum': 9027, 'OPR': 18.8, 'Auto': 2.862, 'CCWM': -7.029, 'TeamName': 'Synergistic Effect'}, {'TeamNum': 11539, 'OPR': 12.17, 'Auto': -0.891, 'CCWM': -25.231, 'TeamName': 'Team Voltage'}, {'TeamNum': 8905, 'OPR': 11.096, 'Auto': 4.105, 'CCWM': -20.162, 'TeamName': 'Statesbots- Orange'}, {'TeamNum': 5404, 'OPR': 10.868, 'Auto': 1.319, 'CCWM': -27.016, 'TeamName': 'Titanium Titans'}, {'TeamNum': 5703, 'OPR': 10.775, 'Auto': 7.631, 'CCWM': -27.989, 'TeamName': 'Doppler Effect'}, {'TeamNum': 6285, 'OPR': 7.383, 'Auto': -2.551, 'CCWM': -19.185, 'TeamName': 'Statesbots - Black'}, {'TeamNum': 17637, 'OPR': 7.363, 'Auto': 3.271, 'CCWM': -39.787, 'TeamName': 'Z-Botz'}, {'TeamNum': 13051, 'OPR': -3.083, 'Auto': 4.026, 'CCWM': -35.372, 'TeamName': 'Servo Stressors'}]
USMOKSSTLSM4
[{'TeamNum': 14186, 'OPR': 73.007, 'Auto': 19.176, 'CCWM': 63.036, 'TeamName': 'P3'}, {'TeamNum': 7525, 'OPR': 66.547, 'Auto': 16.531, 'CCWM': 53.501, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 8895, 'OPR': 36.223, 'Auto': 16.489, 'CCWM': 27.215, 'TeamName': 'Loose Screws'}, {'TeamNum': 4982, 'OPR': 29.43, 'Auto': -0.001, 'CCWM': 28.422, 'TeamName': 'Cafe Bot'}, {'TeamNum': 14257, 'OPR': 28.675, 'Auto': 5.048, 'CCWM': 26.373, 'TeamName': 'REBELBOTS'}, {'TeamNum': 9027, 'OPR': 18.8, 'Auto': 2.862, 'CCWM': -7.029, 'TeamName': 'Synergistic Effect'}, {'TeamNum': 11539, 'OPR': 12.17, 'Auto': -0.891, 'CCWM': -25.231, 'TeamName': 'Team Voltage'}, {'TeamNum': 8905, 'OPR': 11.096, 'Auto': 4.105, 'CCWM': -20.162, 'TeamName': 'Statesbots- Orange'}, {'TeamNum': 5404, 'OPR': 10.868, 'Auto': 1.319, 'CCWM': -27.016, 'TeamName': 'Titanium Titans'}, {'TeamNum': 5703, 'OPR': 10.775, 'Auto': 7.631, 'CCWM': -27.989, 'TeamName': 'Doppler Effect'}, {'TeamNum': 6285, 'OPR': 7.383, 'Auto': -2.551, 'CCWM': -19.185, 'TeamName': 'Statesbots - Black'}, {'TeamNum': 17637, 'OPR': 7.363, 'Auto': 3.271, 'CCWM': -39.787, 'TeamName': 'Z-Botz'}, {'TeamNum': 13051, 'OPR': -3.083, 'Auto': 4.026, 'CCWM': -35.372, 'TeamName': 'Servo Stressors'}]
i 807
{'8690', '14800', '6273', '22426', '16151', '17341', '10191', '8772', '12272'}
[{'TeamNum': 16151, 'OPR': 94.852, 'Auto': 22.585, 'CCWM': 62.447, 'TeamName': 'R U Serious'}, {'TeamNum': 10191, 'OPR': 91.017, 'Auto': 12.226, 'CCWM': 43.538, 'TeamName': 'Trial and Error Robotics'}, {'TeamNum': 6273, 'OPR': 81.194, 'Auto': 20.686, 'CCWM': 41.592, 'TeamName': 'Technocats'}, {'TeamNum': 12272, 'OPR': 51.511, 'Auto': 12.244, 'CCWM': -13.886, 'TeamName': 'Team Lightning'}, {'TeamNum': 22426, 'OPR': 31.684, 'Auto': 2.867, 'CCWM': -5.374, 'TeamName': 'Gigabiters'}, {'TeamNum': 8772, 'OPR': 30.778, 'Auto': 0.516, 'CCWM': -0.504, 'TeamName': 'RoboWildcats'}, {'TeamNum': 17341, 'OPR': 27.431, 'Auto': 9.84, 'CCWM': -32.672, 'TeamName': 'Team Thunder'}, {'TeamNum': 8690, 'OPR': 13.227, 'Auto': -0.578, 'CCWM': -36.337, 'TeamName': 'Twisted Circuits'}, {'TeamNum': 14800, 'OPR': -2.374, 'Auto': -5.053, 'CCWM': -63.156, 'TeamName': 'Cyberdine'}]
USMSMEQ2
[{'TeamNum': 16151, 'OPR': 94.852, 'Auto': 22.585, 'CCWM': 62.447, 'TeamName': 'R U Serious'}, {'TeamNum': 10191, 'OPR': 91.017, 'Auto': 12.226, 'CCWM': 43.538, 'TeamName': 'Trial and Error Robotics'}, {'TeamNum': 6273, 'OPR': 81.194, 'Auto': 20.686, 'CCWM': 41.592, 'TeamName': 'Technocats'}, {'TeamNum': 12272, 'OPR': 51.511, 'Auto': 12.244, 'CCWM': -13.886, 'TeamName': 'Team Lightning'}, {'TeamNum': 22426, 'OPR': 31.684, 'Auto': 2.867, 'CCWM': -5.374, 'TeamName': 'Gigabiters'}, {'TeamNum': 8772, 'OPR': 30.778, 'Auto': 0.516, 'CCWM': -0.504, 'TeamName': 'RoboWildcats'}, {'TeamNum': 17341, 'OPR': 27.431, 'Auto': 9.84, 'CCWM': -32.672, 'TeamName': 'Team Thunder'}, {'TeamNum': 8690, 'OPR': 13.227, 'Auto': -0.578, 'CCWM': -36.337, 'TeamName': 'Twisted Circuits'}, {'TeamNum': 14800, 'OPR': -2.374, 'Auto': -5.053, 'CCWM': -63.156, 'TeamName': 'Cyberdine'}]
i 808
{'21869', '16072', '21490', '13883', '12733', '16250', '7989', '731', '5309', '19971', '8947', '19410', '21502', '15707', '10195', '18994', '19768', '21910', '22830', '15830', '21360', '20056'}
[{'TeamNum': 5309, 'OPR': 101.15, 'Auto': 31.305, 'CCWM': 103.872, 'TeamName': 'Plan B'}, {'TeamNum': 15707, 'OPR': 89.221, 'Auto': 25.908, 'CCWM': 27.277, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 18994, 'OPR': 73.969, 'Auto': 22.096, 'CCWM': 84.786, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 15830, 'OPR': 71.145, 'Auto': 4.943, 'CCWM': 20.217, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 19768, 'OPR': 68.707, 'Auto': 12.086, 'CCWM': 8.435, 'TeamName': 'Overclocked'}, {'TeamNum': 19410, 'OPR': 66.865, 'Auto': 18.924, 'CCWM': 30.516, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 21910, 'OPR': 63.678, 'Auto': 20.35, 'CCWM': 8.266, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 21502, 'OPR': 57.07, 'Auto': 21.693, 'CCWM': 58.806, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 21490, 'OPR': 42.832, 'Auto': 25.004, 'CCWM': 1.549, 'TeamName': 'The Boltiverse'}, {'TeamNum': 7989, 'OPR': 39.151, 'Auto': 3.544, 'CCWM': 12.908, 'TeamName': 'Autonomous Rex'}, {'TeamNum': 16072, 'OPR': 37.05, 'Auto': 0.815, 'CCWM': -47.886, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 16250, 'OPR': 32.637, 'Auto': 10.316, 'CCWM': -1.998, 'TeamName': 'Currently Unnamed'}, {'TeamNum': 12733, 'OPR': 32.348, 'Auto': 1.222, 'CCWM': 34.022, 'TeamName': 'Pirates of the Neuse (formerly NUSA)'}, {'TeamNum': 21360, 'OPR': 26.417, 'Auto': -2.224, 'CCWM': -26.664, 'TeamName': 'ThunderBolts'}, {'TeamNum': 21869, 'OPR': 19.642, 'Auto': 3.16, 'CCWM': -48.641, 'TeamName': 'Mecha Masters'}, {'TeamNum': 10195, 'OPR': 16.813, 'Auto': -2.281, 'CCWM': 7.211, 'TeamName': 'Night Owls'}, {'TeamNum': 13883, 'OPR': 14.68, 'Auto': 1.5, 'CCWM': -14.236, 'TeamName': 'The Razzle Dazzle of Fantazzmagazzles'}, {'TeamNum': 22830, 'OPR': 11.886, 'Auto': -0.232, 'CCWM': -66.313, 'TeamName': 'Coyotebots'}, {'TeamNum': 8947, 'OPR': 10.371, 'Auto': 7.987, 'CCWM': -44.481, 'TeamName': 'Techtonics'}, {'TeamNum': 20056, 'OPR': 7.403, 'Auto': -9.768, 'CCWM': -51.124, 'TeamName': 'Syntax Terror'}, {'TeamNum': 731, 'OPR': 5.501, 'Auto': 1.013, 'CCWM': -55.392, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 19971, 'OPR': -1.997, 'Auto': -3.495, 'CCWM': -42.383, 'TeamName': 'The Icosahedrons'}]
USNCSMQ
[{'TeamNum': 5309, 'OPR': 101.15, 'Auto': 31.305, 'CCWM': 103.872, 'TeamName': 'Plan B'}, {'TeamNum': 15707, 'OPR': 89.221, 'Auto': 25.908, 'CCWM': 27.277, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 18994, 'OPR': 73.969, 'Auto': 22.096, 'CCWM': 84.786, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 15830, 'OPR': 71.145, 'Auto': 4.943, 'CCWM': 20.217, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 19768, 'OPR': 68.707, 'Auto': 12.086, 'CCWM': 8.435, 'TeamName': 'Overclocked'}, {'TeamNum': 19410, 'OPR': 66.865, 'Auto': 18.924, 'CCWM': 30.516, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 21910, 'OPR': 63.678, 'Auto': 20.35, 'CCWM': 8.266, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 21502, 'OPR': 57.07, 'Auto': 21.693, 'CCWM': 58.806, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 21490, 'OPR': 42.832, 'Auto': 25.004, 'CCWM': 1.549, 'TeamName': 'The Boltiverse'}, {'TeamNum': 7989, 'OPR': 39.151, 'Auto': 3.544, 'CCWM': 12.908, 'TeamName': 'Autonomous Rex'}, {'TeamNum': 16072, 'OPR': 37.05, 'Auto': 0.815, 'CCWM': -47.886, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 16250, 'OPR': 32.637, 'Auto': 10.316, 'CCWM': -1.998, 'TeamName': 'Currently Unnamed'}, {'TeamNum': 12733, 'OPR': 32.348, 'Auto': 1.222, 'CCWM': 34.022, 'TeamName': 'Pirates of the Neuse (formerly NUSA)'}, {'TeamNum': 21360, 'OPR': 26.417, 'Auto': -2.224, 'CCWM': -26.664, 'TeamName': 'ThunderBolts'}, {'TeamNum': 21869, 'OPR': 19.642, 'Auto': 3.16, 'CCWM': -48.641, 'TeamName': 'Mecha Masters'}, {'TeamNum': 10195, 'OPR': 16.813, 'Auto': -2.281, 'CCWM': 7.211, 'TeamName': 'Night Owls'}, {'TeamNum': 13883, 'OPR': 14.68, 'Auto': 1.5, 'CCWM': -14.236, 'TeamName': 'The Razzle Dazzle of Fantazzmagazzles'}, {'TeamNum': 22830, 'OPR': 11.886, 'Auto': -0.232, 'CCWM': -66.313, 'TeamName': 'Coyotebots'}, {'TeamNum': 8947, 'OPR': 10.371, 'Auto': 7.987, 'CCWM': -44.481, 'TeamName': 'Techtonics'}, {'TeamNum': 20056, 'OPR': 7.403, 'Auto': -9.768, 'CCWM': -51.124, 'TeamName': 'Syntax Terror'}, {'TeamNum': 731, 'OPR': 5.501, 'Auto': 1.013, 'CCWM': -55.392, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 19971, 'OPR': -1.997, 'Auto': -3.495, 'CCWM': -42.383, 'TeamName': 'The Icosahedrons'}]

i 809
{'19921', '21501', '21734', '5270', '11528', '22733', '8569', '21724', '12010', '15680', '21836', '12828', '9076', '20434', '3916', '16447', '7083', '3587', '9581', '13735', '11588', '22377', '2827', '2901'}
[{'TeamNum': 22377, 'OPR': 138.684, 'Auto': 42.751, 'CCWM': 114.995, 'TeamName': 'SigmaCorns'}, {'TeamNum': 11528, 'OPR': 88.498, 'Auto': 17.408, 'CCWM': 52.224, 'TeamName': 'Bots of Prey'}, {'TeamNum': 20434, 'OPR': 74.27, 'Auto': 17.938, 'CCWM': 51.098, 'TeamName': 'Binding Energy'}, {'TeamNum': 12828, 'OPR': 70.884, 'Auto': 22.282, 'CCWM': 46.577, 'TeamName': 'Critical Overload'}, {'TeamNum': 19921, 'OPR': 60.772, 'Auto': 17.195, 'CCWM': 37.556, 'TeamName': 'Space Invaders'}, {'TeamNum': 21501, 'OPR': 58.358, 'Auto': 6.393, 'CCWM': 46.937, 'TeamName': 'Ohms'}, {'TeamNum': 7083, 'OPR': 58.085, 'Auto': 19.216, 'CCWM': 13.26, 'TeamName': 'TundraBots'}, {'TeamNum': 3587, 'OPR': 53.18, 'Auto': 8.94, 'CCWM': 54.64, 'TeamName': 'Unparalleled Processing'}, {'TeamNum': 13735, 'OPR': 47.541, 'Auto': 0.454, 'CCWM': 5.394, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 8569, 'OPR': 46.59, 'Auto': 15.9, 'CCWM': -6.225, 'TeamName': 'RoboKnights'}, {'TeamNum': 21836, 'OPR': 43.905, 'Auto': 11.59, 'CCWM': -29.361, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 5270, 'OPR': 43.344, 'Auto': 2.462, 'CCWM': -20.301, 'TeamName': 'Q'}, {'TeamNum': 21724, 'OPR': 41.88, 'Auto': 6.441, 'CCWM': -34.854, 'TeamName': 'Pitt Parrots'}, {'TeamNum': 2901, 'OPR': 41.034, 'Auto': 2.173, 'CCWM': 26.722, 'TeamName': 'Purple Gears'}, {'TeamNum': 9581, 'OPR': 38.033, 'Auto': 18.548, 'CCWM': -30.907, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 11588, 'OPR': 37.757, 'Auto': 10.633, 'CCWM': -18.399, 'TeamName': 'Carpe Diem'}, {'TeamNum': 15680, 'OPR': 31.745, 'Auto': -1.532, 'CCWM': -24.38, 'TeamName': 'Techno Tigers'}, {'TeamNum': 2827, 'OPR': 24.044, 'Auto': 1.322, 'CCWM': -43.282, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 16447, 'OPR': 20.141, 'Auto': -5.547, 'CCWM': -8.85, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 21734, 'OPR': 19.531, 'Auto': 8.762, 'CCWM': -44.474, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 22733, 'OPR': 16.884, 'Auto': 5.171, 'CCWM': -55.288, 'TeamName': 'Ghost'}, {'TeamNum': 3916, 'OPR': 16.387, 'Auto': 0.946, 'CCWM': -71.537, 'TeamName': 'Apex Robotics'}, {'TeamNum': 12010, 'OPR': 15.12, 'Auto': 3.242, 'CCWM': -25.313, 'TeamName': 'ChargerBots'}, {'TeamNum': 9076, 'OPR': 10.332, 'Auto': 4.111, 'CCWM': -36.232, 'TeamName': 'Sketchy Engineering'}]
USNCROQ
[{'TeamNum': 22377, 'OPR': 138.684, 'Auto': 42.751, 'CCWM': 114.995, 'TeamName': 'SigmaCorns'}, {'TeamNum': 11528, 'OPR': 88.498, 'Auto': 17.408, 'CCWM': 52.224, 'TeamName': 'Bots of Prey'}, {'TeamNum': 20434, 'OPR': 74.27, 'Auto': 17.938, 'CCWM': 51.098, 'TeamName': 'Binding Energy'}, {'TeamNum': 12828, 'OPR': 70.884, 'Auto': 22.282, 'CCWM': 46.577, 'TeamName': 'Critical Overload'}, {'TeamNum': 19921, 'OPR': 60.772, 'Auto': 17.195, 'CCWM': 37.556, 'TeamName': 'Space Invaders'}, {'TeamNum': 21501, 'OPR': 58.358, 'Auto': 6.393, 'CCWM': 46.937, 'TeamName': 'Ohms'}, {'TeamNum': 7083, 'OPR': 58.085, 'Auto': 19.216, 'CCWM': 13.26, 'TeamName': 'TundraBots'}, {'TeamNum': 3587, 'OPR': 53.18, 'Auto': 8.94, 'CCWM': 54.64, 'TeamName': 'Unparalleled Processing'}, {'TeamNum': 13735, 'OPR': 47.541, 'Auto': 0.454, 'CCWM': 5.394, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 8569, 'OPR': 46.59, 'Auto': 15.9, 'CCWM': -6.225, 'TeamName': 'RoboKnights'}, {'TeamNum': 21836, 'OPR': 43.905, 'Auto': 11.59, 'CCWM': -29.361, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 5270, 'OPR': 43.344, 'Auto': 2.462, 'CCWM': -20.301, 'TeamName': 'Q'}, {'TeamNum': 21724, 'OPR': 41.88, 'Auto': 6.441, 'CCWM': -34.854, 'TeamName': 'Pitt Parrots'}, {'TeamNum': 2901, 'OPR': 41.034, 'Auto': 2.173, 'CCWM': 26.722, 'TeamName': 'Purple Gears'}, {'TeamNum': 9581, 'OPR': 38.033, 'Auto': 18.548, 'CCWM': -30.907, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 11588, 'OPR': 37.757, 'Auto': 10.633, 'CCWM': -18.399, 'TeamName': 'Carpe Diem'}, {'TeamNum': 15680, 'OPR': 31.745, 'Auto': -1.532, 'CCWM': -24.38, 'TeamName': 'Techno Tigers'}, {'TeamNum': 2827, 'OPR': 24.044, 'Auto': 1.322, 'CCWM': -43.282, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 16447, 'OPR': 20.141, 'Auto': -5.547, 'CCWM': -8.85, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 21734, 'OPR': 19.531, 'Auto': 8.762, 'CCWM': -44.474, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 22733, 'OPR': 16.884, 'Auto': 5.171, 'CCWM': -55.288, 'TeamName': 'Ghost'}, {'TeamNum': 3916, 'OPR': 16.387, 'Auto': 0.946, 'CCWM': -71.537, 'TeamName': 'Apex Robotics'}, {'TeamNum': 12010, 'OPR': 15.12, 'Auto': 3.242, 'CCWM': -25.313, 'TeamName': 'ChargerBots'}, {'TeamNum': 9076, 'OPR': 10.332, 'Auto': 4.111, 'CCWM': -36.232, 'TeamName': 'Sketchy Engineering'}]
i 810
{'15886', '15931', '16127', '16630', '16266', '6645', '21772', '9707', '21460', '9473', '21883', '13178', '20782', '15672', '10798', '9963', '9505'}
[{'TeamNum': 15886, 'OPR': 104.97, 'Auto': 12.706, 'CCWM': 93.635, 'TeamName': 'Shiloh Stud Muffins'}, {'TeamNum': 16127, 'OPR': 75.103, 'Auto': 21.053, 'CCWM': 44.479, 'TeamName': 'Rogue Robot '}, {'TeamNum': 6645, 'OPR': 64.477, 'Auto': 7.282, 'CCWM': 57.878, 'TeamName': 'Roboticus Maximus'}, {'TeamNum': 16266, 'OPR': 57.486, 'Auto': 2.482, 'CCWM': 52.751, 'TeamName': 'Killdeer Robotics'}, {'TeamNum': 9707, 'OPR': 33.858, 'Auto': 16.614, 'CCWM': -8.578, 'TeamName': "St. Mary's Robotic Saints"}, {'TeamNum': 9505, 'OPR': 26.794, 'Auto': 2.54, 'CCWM': 3.521, 'TeamName': 'The Bot Patrol'}, {'TeamNum': 15931, 'OPR': 23.558, 'Auto': 3.606, 'CCWM': -20.692, 'TeamName': 'Tin Heads'}, {'TeamNum': 20782, 'OPR': 22.613, 'Auto': 0.729, 'CCWM': 5.935, 'TeamName': 'Jedi tech'}, {'TeamNum': 9963, 'OPR': 20.84, 'Auto': 2.011, 'CCWM': -38.065, 'TeamName': 'Comets '}, {'TeamNum': 16630, 'OPR': 15.79, 'Auto': 8.939, 'CCWM': 17.936, 'TeamName': 'T3- Tioga Tech Team'}, {'TeamNum': 13178, 'OPR': 14.913, 'Auto': 3.781, 'CCWM': -26.988, 'TeamName': 'Roncalli Robo-Cavs'}, {'TeamNum': 15672, 'OPR': 13.596, 'Auto': -2.392, 'CCWM': 4.941, 'TeamName': 'Code Splicers'}, {'TeamNum': 21772, 'OPR': 7.38, 'Auto': -2.679, 'CCWM': -45.399, 'TeamName': 'Gear Heads'}, {'TeamNum': 21460, 'OPR': 5.368, 'Auto': 0.166, 'CCWM': -9.301, 'TeamName': 'Astronomical Blueprint'}, {'TeamNum': 21883, 'OPR': 2.484, 'Auto': 6.479, 'CCWM': -8.578, 'TeamName': 'Magic Thunder 1 FTC'}, {'TeamNum': 10798, 'OPR': 1.829, 'Auto': 2.415, 'CCWM': -59.452, 'TeamName': 'Hazen Bison'}, {'TeamNum': 9473, 'OPR': -10.712, 'Auto': -0.483, 'CCWM': -71.761, 'TeamName': 'Crocobots'}]
USNDBIQ
[{'TeamNum': 15886, 'OPR': 104.97, 'Auto': 12.706, 'CCWM': 93.635, 'TeamName': 'Shiloh Stud Muffins'}, {'TeamNum': 16127, 'OPR': 75.103, 'Auto': 21.053, 'CCWM': 44.479, 'TeamName': 'Rogue Robot '}, {'TeamNum': 6645, 'OPR': 64.477, 'Auto': 7.282, 'CCWM': 57.878, 'TeamName': 'Roboticus Maximus'}, {'TeamNum': 16266, 'OPR': 57.486, 'Auto': 2.482, 'CCWM': 52.751, 'TeamName': 'Killdeer Robotics'}, {'TeamNum': 9707, 'OPR': 33.858, 'Auto': 16.614, 'CCWM': -8.578, 'TeamName': "St. Mary's Robotic Saints"}, {'TeamNum': 9505, 'OPR': 26.794, 'Auto': 2.54, 'CCWM': 3.521, 'TeamName': 'The Bot Patrol'}, {'TeamNum': 15931, 'OPR': 23.558, 'Auto': 3.606, 'CCWM': -20.692, 'TeamName': 'Tin Heads'}, {'TeamNum': 20782, 'OPR': 22.613, 'Auto': 0.729, 'CCWM': 5.935, 'TeamName': 'Jedi tech'}, {'TeamNum': 9963, 'OPR': 20.84, 'Auto': 2.011, 'CCWM': -38.065, 'TeamName': 'Comets '}, {'TeamNum': 16630, 'OPR': 15.79, 'Auto': 8.939, 'CCWM': 17.936, 'TeamName': 'T3- Tioga Tech Team'}, {'TeamNum': 13178, 'OPR': 14.913, 'Auto': 3.781, 'CCWM': -26.988, 'TeamName': 'Roncalli Robo-Cavs'}, {'TeamNum': 15672, 'OPR': 13.596, 'Auto': -2.392, 'CCWM': 4.941, 'TeamName': 'Code Splicers'}, {'TeamNum': 21772, 'OPR': 7.38, 'Auto': -2.679, 'CCWM': -45.399, 'TeamName': 'Gear Heads'}, {'TeamNum': 21460, 'OPR': 5.368, 'Auto': 0.166, 'CCWM': -9.301, 'TeamName': 'Astronomical Blueprint'}, {'TeamNum': 21883, 'OPR': 2.484, 'Auto': 6.479, 'CCWM': -8.578, 'TeamName': 'Magic Thunder 1 FTC'}, {'TeamNum': 10798, 'OPR': 1.829, 'Auto': 2.415, 'CCWM': -59.452, 'TeamName': 'Hazen Bison'}, {'TeamNum': 9473, 'OPR': -10.712, 'Auto': -0.483, 'CCWM': -71.761, 'TeamName': 'Crocobots'}]

i 811
{'8888', '21689', '22879', '12622', '7135', '19695', '14590', '20910', '22345', '17630', '13738', '11536', '15343', '15534', '12758', '17455', '22880', '19643', '22346', '20099'}
[{'TeamNum': 12758, 'OPR': 89.029, 'Auto': 18.219, 'CCWM': 67.341, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 15343, 'OPR': 86.801, 'Auto': 23.147, 'CCWM': 18.904, 'TeamName': 'Blue VIII'}, {'TeamNum': 15534, 'OPR': 65.322, 'Auto': 10.043, 'CCWM': 49.912, 'TeamName': 'VERTEX'}, {'TeamNum': 19695, 'OPR': 61.458, 'Auto': 27.723, 'CCWM': 32.589, 'TeamName': 'Flying Screwdrivers'}, {'TeamNum': 11536, 'OPR': 60.7, 'Auto': 19.371, 'CCWM': 35.812, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 19643, 'OPR': 55.335, 'Auto': 18.024, 'CCWM': 18.051, 'TeamName': 'Dragon Droids'}, {'TeamNum': 17455, 'OPR': 44.47, 'Auto': 16.355, 'CCWM': -12.634, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 20910, 'OPR': 35.685, 'Auto': 6.427, 'CCWM': 21.384, 'TeamName': 'Hornets 2'}, {'TeamNum': 17630, 'OPR': 30.919, 'Auto': 8.339, 'CCWM': -37.744, 'TeamName': 'Hot Wings'}, {'TeamNum': 8888, 'OPR': 29.356, 'Auto': 9.34, 'CCWM': 9.418, 'TeamName': 'Infinity Factor'}, {'TeamNum': 21689, 'OPR': 28.293, 'Auto': 10.903, 'CCWM': 6.849, 'TeamName': 'A.J.A.Y Robotics '}, {'TeamNum': 22345, 'OPR': 25.825, 'Auto': 1.15, 'CCWM': 4.299, 'TeamName': 'SURFACE'}, {'TeamNum': 22880, 'OPR': 22.238, 'Auto': 5.005, 'CCWM': -9.412, 'TeamName': 'Hornets 3'}, {'TeamNum': 22879, 'OPR': 20.46, 'Auto': 3.386, 'CCWM': -11.552, 'TeamName': 'Red Spark Beta'}, {'TeamNum': 12622, 'OPR': 19.458, 'Auto': -3.064, 'CCWM': -42.598, 'TeamName': 'Red Spark Alpha'}, {'TeamNum': 22346, 'OPR': 8.317, 'Auto': -0.35, 'CCWM': -24.096, 'TeamName': 'EDGE'}, {'TeamNum': 20099, 'OPR': 8.161, 'Auto': -0.435, 'CCWM': -33.392, 'TeamName': 'Team Inconceivable!'}, {'TeamNum': 14590, 'OPR': 5.784, 'Auto': -4.966, 'CCWM': -38.574, 'TeamName': 'Prometheus'}, {'TeamNum': 13738, 'OPR': 0.469, 'Auto': -6.825, 'CCWM': -16.031, 'TeamName': ' Alvirne Robotics'}, {'TeamNum': 7135, 'OPR': -1.883, 'Auto': -2.392, 'CCWM': -38.525, 'TeamName': 'Hornets'}]
USNHWIQ
[{'TeamNum': 12758, 'OPR': 89.029, 'Auto': 18.219, 'CCWM': 67.341, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 15343, 'OPR': 86.801, 'Auto': 23.147, 'CCWM': 18.904, 'TeamName': 'Blue VIII'}, {'TeamNum': 15534, 'OPR': 65.322, 'Auto': 10.043, 'CCWM': 49.912, 'TeamName': 'VERTEX'}, {'TeamNum': 19695, 'OPR': 61.458, 'Auto': 27.723, 'CCWM': 32.589, 'TeamName': 'Flying Screwdrivers'}, {'TeamNum': 11536, 'OPR': 60.7, 'Auto': 19.371, 'CCWM': 35.812, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 19643, 'OPR': 55.335, 'Auto': 18.024, 'CCWM': 18.051, 'TeamName': 'Dragon Droids'}, {'TeamNum': 17455, 'OPR': 44.47, 'Auto': 16.355, 'CCWM': -12.634, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 20910, 'OPR': 35.685, 'Auto': 6.427, 'CCWM': 21.384, 'TeamName': 'Hornets 2'}, {'TeamNum': 17630, 'OPR': 30.919, 'Auto': 8.339, 'CCWM': -37.744, 'TeamName': 'Hot Wings'}, {'TeamNum': 8888, 'OPR': 29.356, 'Auto': 9.34, 'CCWM': 9.418, 'TeamName': 'Infinity Factor'}, {'TeamNum': 21689, 'OPR': 28.293, 'Auto': 10.903, 'CCWM': 6.849, 'TeamName': 'A.J.A.Y Robotics '}, {'TeamNum': 22345, 'OPR': 25.825, 'Auto': 1.15, 'CCWM': 4.299, 'TeamName': 'SURFACE'}, {'TeamNum': 22880, 'OPR': 22.238, 'Auto': 5.005, 'CCWM': -9.412, 'TeamName': 'Hornets 3'}, {'TeamNum': 22879, 'OPR': 20.46, 'Auto': 3.386, 'CCWM': -11.552, 'TeamName': 'Red Spark Beta'}, {'TeamNum': 12622, 'OPR': 19.458, 'Auto': -3.064, 'CCWM': -42.598, 'TeamName': 'Red Spark Alpha'}, {'TeamNum': 22346, 'OPR': 8.317, 'Auto': -0.35, 'CCWM': -24.096, 'TeamName': 'EDGE'}, {'TeamNum': 20099, 'OPR': 8.161, 'Auto': -0.435, 'CCWM': -33.392, 'TeamName': 'Team Inconceivable!'}, {'TeamNum': 14590, 'OPR': 5.784, 'Auto': -4.966, 'CCWM': -38.574, 'TeamName': 'Prometheus'}, {'TeamNum': 13738, 'OPR': 0.469, 'Auto': -6.825, 'CCWM': -16.031, 'TeamName': ' Alvirne Robotics'}, {'TeamNum': 7135, 'OPR': -1.883, 'Auto': -2.392, 'CCWM': -38.525, 'TeamName': 'Hornets'}]
i 812
{'14481', '609', '755', '21226', '12116', '6102', '17009', '21630', '9889', '8421', '21767', '6101', '11754', '17496', '18671', '22810', '15589', '21505', '20255', '18061', '9853', '11248', '17497'}
[{'TeamNum': 9889, 'OPR': 132.345, 'Auto': 29.2, 'CCWM': 67.755, 'TeamName': 'Cruise Control'}, {'TeamNum': 14481, 'OPR': 100.901, 'Auto': 24.791, 'CCWM': 51.23, 'TeamName': "Don't Blink"}, {'TeamNum': 21226, 'OPR': 73.532, 'Auto': 25.558, 'CCWM': 3.384, 'TeamName': 'RoboRaiders'}, {'TeamNum': 755, 'OPR': 72.235, 'Auto': 21.78, 'CCWM': 7.788, 'TeamName': 'Delbotics'}, {'TeamNum': 18061, 'OPR': 63.694, 'Auto': 7.698, 'CCWM': 35.561, 'TeamName': 'Simply Complex 18061'}, {'TeamNum': 11248, 'OPR': 55.268, 'Auto': 18.317, 'CCWM': 46.761, 'TeamName': '//Cougars'}, {'TeamNum': 11754, 'OPR': 52.249, 'Auto': 14.325, 'CCWM': 14.743, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 9853, 'OPR': 48.859, 'Auto': 9.651, 'CCWM': 27.412, 'TeamName': 'Chatham Cougars'}, {'TeamNum': 6102, 'OPR': 48.326, 'Auto': 4.606, 'CCWM': 22.743, 'TeamName': 'E=MK2'}, {'TeamNum': 18671, 'OPR': 46.102, 'Auto': 27.722, 'CCWM': -21.185, 'TeamName': 'Faraday'}, {'TeamNum': 21630, 'OPR': 45.86, 'Auto': 12.072, 'CCWM': 4.236, 'TeamName': 'Argonauts'}, {'TeamNum': 21505, 'OPR': 45.637, 'Auto': 6.18, 'CCWM': 24.12, 'TeamName': 'RaidersBots'}, {'TeamNum': 20255, 'OPR': 36.724, 'Auto': 9.415, 'CCWM': -7.582, 'TeamName': "Falcon's Nest"}, {'TeamNum': 12116, 'OPR': 36.207, 'Auto': 4.106, 'CCWM': 43.242, 'TeamName': 'Redbots'}, {'TeamNum': 17009, 'OPR': 34.566, 'Auto': -0.632, 'CCWM': -48.808, 'TeamName': 'Steel Magnolias'}, {'TeamNum': 609, 'OPR': 32.383, 'Auto': 1.37, 'CCWM': -41.138, 'TeamName': 'Cougars'}, {'TeamNum': 6101, 'OPR': 25.148, 'Auto': -0.854, 'CCWM': -28.606, 'TeamName': 'Energized Hazard'}, {'TeamNum': 22810, 'OPR': 21.609, 'Auto': 0.941, 'CCWM': -29.663, 'TeamName': 'Pequaautobots'}, {'TeamNum': 17496, 'OPR': 21.581, 'Auto': 12.167, 'CCWM': -38.197, 'TeamName': 'The Knight Shift'}, {'TeamNum': 21767, 'OPR': 16.803, 'Auto': -5.273, 'CCWM': -3.313, 'TeamName': 'Quadra'}, {'TeamNum': 15589, 'OPR': 9.678, 'Auto': 9.074, 'CCWM': -58.174, 'TeamName': 'TecHawks'}, {'TeamNum': 17497, 'OPR': 9.537, 'Auto': 2.517, 'CCWM': -60.684, 'TeamName': 'Knight Riders'}, {'TeamNum': 8421, 'OPR': 9.289, 'Auto': 10.028, 'CCWM': -25.175, 'TeamName': 'Tigers'}]
USNJUCM6
[{'TeamNum': 9889, 'OPR': 132.345, 'Auto': 29.2, 'CCWM': 67.755, 'TeamName': 'Cruise Control'}, {'TeamNum': 14481, 'OPR': 100.901, 'Auto': 24.791, 'CCWM': 51.23, 'TeamName': "Don't Blink"}, {'TeamNum': 21226, 'OPR': 73.532, 'Auto': 25.558, 'CCWM': 3.384, 'TeamName': 'RoboRaiders'}, {'TeamNum': 755, 'OPR': 72.235, 'Auto': 21.78, 'CCWM': 7.788, 'TeamName': 'Delbotics'}, {'TeamNum': 18061, 'OPR': 63.694, 'Auto': 7.698, 'CCWM': 35.561, 'TeamName': 'Simply Complex 18061'}, {'TeamNum': 11248, 'OPR': 55.268, 'Auto': 18.317, 'CCWM': 46.761, 'TeamName': '//Cougars'}, {'TeamNum': 11754, 'OPR': 52.249, 'Auto': 14.325, 'CCWM': 14.743, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 9853, 'OPR': 48.859, 'Auto': 9.651, 'CCWM': 27.412, 'TeamName': 'Chatham Cougars'}, {'TeamNum': 6102, 'OPR': 48.326, 'Auto': 4.606, 'CCWM': 22.743, 'TeamName': 'E=MK2'}, {'TeamNum': 18671, 'OPR': 46.102, 'Auto': 27.722, 'CCWM': -21.185, 'TeamName': 'Faraday'}, {'TeamNum': 21630, 'OPR': 45.86, 'Auto': 12.072, 'CCWM': 4.236, 'TeamName': 'Argonauts'}, {'TeamNum': 21505, 'OPR': 45.637, 'Auto': 6.18, 'CCWM': 24.12, 'TeamName': 'RaidersBots'}, {'TeamNum': 20255, 'OPR': 36.724, 'Auto': 9.415, 'CCWM': -7.582, 'TeamName': "Falcon's Nest"}, {'TeamNum': 12116, 'OPR': 36.207, 'Auto': 4.106, 'CCWM': 43.242, 'TeamName': 'Redbots'}, {'TeamNum': 17009, 'OPR': 34.566, 'Auto': -0.632, 'CCWM': -48.808, 'TeamName': 'Steel Magnolias'}, {'TeamNum': 609, 'OPR': 32.383, 'Auto': 1.37, 'CCWM': -41.138, 'TeamName': 'Cougars'}, {'TeamNum': 6101, 'OPR': 25.148, 'Auto': -0.854, 'CCWM': -28.606, 'TeamName': 'Energized Hazard'}, {'TeamNum': 22810, 'OPR': 21.609, 'Auto': 0.941, 'CCWM': -29.663, 'TeamName': 'Pequaautobots'}, {'TeamNum': 17496, 'OPR': 21.581, 'Auto': 12.167, 'CCWM': -38.197, 'TeamName': 'The Knight Shift'}, {'TeamNum': 21767, 'OPR': 16.803, 'Auto': -5.273, 'CCWM': -3.313, 'TeamName': 'Quadra'}, {'TeamNum': 15589, 'OPR': 9.678, 'Auto': 9.074, 'CCWM': -58.174, 'TeamName': 'TecHawks'}, {'TeamNum': 17497, 'OPR': 9.537, 'Auto': 2.517, 'CCWM': -60.684, 'TeamName': 'Knight Riders'}, {'TeamNum': 8421, 'OPR': 9.289, 'Auto': 10.028, 'CCWM': -25.175, 'TeamName': 'Tigers'}]

i 813
{'18757', '13103', '15891', '18758', '12636', '7026', '12309', '247', '18759', '207', '13048', '4328', '13105', '13107', '11456', '18760', '15762', '15715', '248', '9244', '10243', '15887', '10603', '3777'}
[{'TeamNum': 12309, 'OPR': 104.521, 'Auto': 8.644, 'CCWM': 54.177, 'TeamName': 'Wood-Ridge Spartans'}, {'TeamNum': 11456, 'OPR': 101.697, 'Auto': 19.571, 'CCWM': 12.657, 'TeamName': 'Blair Academy'}, {'TeamNum': 13048, 'OPR': 91.886, 'Auto': 13.474, 'CCWM': 56.254, 'TeamName': 'Absolute Zero'}, {'TeamNum': 7026, 'OPR': 72.185, 'Auto': 11.865, 'CCWM': 23.124, 'TeamName': 'JDroids'}, {'TeamNum': 12636, 'OPR': 65.551, 'Auto': 26.193, 'CCWM': 72.091, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 248, 'OPR': 63.709, 'Auto': 16.331, 'CCWM': 46.826, 'TeamName': 'Fatal Error'}, {'TeamNum': 207, 'OPR': 58.955, 'Auto': 21.767, 'CCWM': 41.046, 'TeamName': 'Critical Mass'}, {'TeamNum': 18759, 'OPR': 58.738, 'Auto': 24.743, 'CCWM': 6.269, 'TeamName': 'Ironmen Tau'}, {'TeamNum': 13107, 'OPR': 55.063, 'Auto': 22.374, 'CCWM': 12.961, 'TeamName': 'Ironmen Pi'}, {'TeamNum': 15887, 'OPR': 53.113, 'Auto': 6.33, 'CCWM': 0.006, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 15891, 'OPR': 49.267, 'Auto': 10.013, 'CCWM': -70.308, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 18758, 'OPR': 47.598, 'Auto': 15.283, 'CCWM': 15.058, 'TeamName': 'Ironmen Sigma'}, {'TeamNum': 15762, 'OPR': 45.499, 'Auto': -4.965, 'CCWM': -5.026, 'TeamName': 'Frisch CouGears'}, {'TeamNum': 13103, 'OPR': 39.163, 'Auto': 14.921, 'CCWM': -7.027, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 18757, 'OPR': 33.91, 'Auto': 14.868, 'CCWM': -3.319, 'TeamName': 'Ironmen Rho'}, {'TeamNum': 247, 'OPR': 27.73, 'Auto': 8.182, 'CCWM': -41.911, 'TeamName': 'Reboot'}, {'TeamNum': 10603, 'OPR': 25.275, 'Auto': 9.621, 'CCWM': -1.706, 'TeamName': 'WOOD-CHIPS'}, {'TeamNum': 18760, 'OPR': 21.046, 'Auto': 22.929, 'CCWM': -15.804, 'TeamName': 'Ironmen Upsilon'}, {'TeamNum': 9244, 'OPR': 9.955, 'Auto': -5.88, 'CCWM': -50.182, 'TeamName': 'Lenape Valley Robotics'}, {'TeamNum': 3777, 'OPR': 9.253, 'Auto': 6.305, 'CCWM': -15.38, 'TeamName': 'Mecha Lion'}, {'TeamNum': 15715, 'OPR': 7.111, 'Auto': 4.264, 'CCWM': -38.703, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 13105, 'OPR': 3.714, 'Auto': 7.987, 'CCWM': -56.189, 'TeamName': 'Ironmen Omicron'}, {'TeamNum': 4328, 'OPR': 3.487, 'Auto': -4.329, 'CCWM': -19.079, 'TeamName': "C'est la vie"}, {'TeamNum': 10243, 'OPR': -5.025, 'Auto': 12.909, 'CCWM': -15.838, 'TeamName': 'Ramsey Ramblers'}]
USNJNOM6
[{'TeamNum': 12309, 'OPR': 104.521, 'Auto': 8.644, 'CCWM': 54.177, 'TeamName': 'Wood-Ridge Spartans'}, {'TeamNum': 11456, 'OPR': 101.697, 'Auto': 19.571, 'CCWM': 12.657, 'TeamName': 'Blair Academy'}, {'TeamNum': 13048, 'OPR': 91.886, 'Auto': 13.474, 'CCWM': 56.254, 'TeamName': 'Absolute Zero'}, {'TeamNum': 7026, 'OPR': 72.185, 'Auto': 11.865, 'CCWM': 23.124, 'TeamName': 'JDroids'}, {'TeamNum': 12636, 'OPR': 65.551, 'Auto': 26.193, 'CCWM': 72.091, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 248, 'OPR': 63.709, 'Auto': 16.331, 'CCWM': 46.826, 'TeamName': 'Fatal Error'}, {'TeamNum': 207, 'OPR': 58.955, 'Auto': 21.767, 'CCWM': 41.046, 'TeamName': 'Critical Mass'}, {'TeamNum': 18759, 'OPR': 58.738, 'Auto': 24.743, 'CCWM': 6.269, 'TeamName': 'Ironmen Tau'}, {'TeamNum': 13107, 'OPR': 55.063, 'Auto': 22.374, 'CCWM': 12.961, 'TeamName': 'Ironmen Pi'}, {'TeamNum': 15887, 'OPR': 53.113, 'Auto': 6.33, 'CCWM': 0.006, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 15891, 'OPR': 49.267, 'Auto': 10.013, 'CCWM': -70.308, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 18758, 'OPR': 47.598, 'Auto': 15.283, 'CCWM': 15.058, 'TeamName': 'Ironmen Sigma'}, {'TeamNum': 15762, 'OPR': 45.499, 'Auto': -4.965, 'CCWM': -5.026, 'TeamName': 'Frisch CouGears'}, {'TeamNum': 13103, 'OPR': 39.163, 'Auto': 14.921, 'CCWM': -7.027, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 18757, 'OPR': 33.91, 'Auto': 14.868, 'CCWM': -3.319, 'TeamName': 'Ironmen Rho'}, {'TeamNum': 247, 'OPR': 27.73, 'Auto': 8.182, 'CCWM': -41.911, 'TeamName': 'Reboot'}, {'TeamNum': 10603, 'OPR': 25.275, 'Auto': 9.621, 'CCWM': -1.706, 'TeamName': 'WOOD-CHIPS'}, {'TeamNum': 18760, 'OPR': 21.046, 'Auto': 22.929, 'CCWM': -15.804, 'TeamName': 'Ironmen Upsilon'}, {'TeamNum': 9244, 'OPR': 9.955, 'Auto': -5.88, 'CCWM': -50.182, 'TeamName': 'Lenape Valley Robotics'}, {'TeamNum': 3777, 'OPR': 9.253, 'Auto': 6.305, 'CCWM': -15.38, 'TeamName': 'Mecha Lion'}, {'TeamNum': 15715, 'OPR': 7.111, 'Auto': 4.264, 'CCWM': -38.703, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 13105, 'OPR': 3.714, 'Auto': 7.987, 'CCWM': -56.189, 'TeamName': 'Ironmen Omicron'}, {'TeamNum': 4328, 'OPR': 3.487, 'Auto': -4.329, 'CCWM': -19.079, 'TeamName': "C'est la vie"}, {'TeamNum': 10243, 'OPR': -5.025, 'Auto': 12.909, 'CCWM': -15.838, 'TeamName': 'Ramsey Ramblers'}]
i 814
{'11574', '18419', '21238', '21217', '20681', '20948', '21897', '18203', '16158', '22774', '21621'}
[{'TeamNum': 16158, 'OPR': 138.039, 'Auto': 35.574, 'CCWM': 128.349, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 18203, 'OPR': 63.328, 'Auto': 23.594, 'CCWM': 41.981, 'TeamName': 'MCII'}, {'TeamNum': 20681, 'OPR': 47.636, 'Auto': 5.528, 'CCWM': 5.515, 'TeamName': 'Giga Bite'}, {'TeamNum': 21238, 'OPR': 28.611, 'Auto': 7.445, 'CCWM': -27.904, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 21217, 'OPR': 25.464, 'Auto': 20.84, 'CCWM': 8.74, 'TeamName': 'The Phoenixes'}, {'TeamNum': 11574, 'OPR': 24.681, 'Auto': -5.302, 'CCWM': 9.517, 'TeamName': 'Incognito'}, {'TeamNum': 18419, 'OPR': 23.982, 'Auto': 3.368, 'CCWM': -11.527, 'TeamName': 'Comstock Coders'}, {'TeamNum': 20948, 'OPR': 16.851, 'Auto': 2.202, 'CCWM': -43.669, 'TeamName': 'Hug HS'}, {'TeamNum': 22774, 'OPR': 7.897, 'Auto': -4.043, 'CCWM': -65.753, 'TeamName': 'URSA Major'}, {'TeamNum': 21621, 'OPR': 4.767, 'Auto': -3.175, 'CCWM': -8.936, 'TeamName': 'Zoomies'}, {'TeamNum': 21897, 'OPR': 3.622, 'Auto': -2.322, 'CCWM': -30.732, 'TeamName': 'Oasis Academy'}]
USNVNOM4N
[{'TeamNum': 16158, 'OPR': 138.039, 'Auto': 35.574, 'CCWM': 128.349, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 18203, 'OPR': 63.328, 'Auto': 23.594, 'CCWM': 41.981, 'TeamName': 'MCII'}, {'TeamNum': 20681, 'OPR': 47.636, 'Auto': 5.528, 'CCWM': 5.515, 'TeamName': 'Giga Bite'}, {'TeamNum': 21238, 'OPR': 28.611, 'Auto': 7.445, 'CCWM': -27.904, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 21217, 'OPR': 25.464, 'Auto': 20.84, 'CCWM': 8.74, 'TeamName': 'The Phoenixes'}, {'TeamNum': 11574, 'OPR': 24.681, 'Auto': -5.302, 'CCWM': 9.517, 'TeamName': 'Incognito'}, {'TeamNum': 18419, 'OPR': 23.982, 'Auto': 3.368, 'CCWM': -11.527, 'TeamName': 'Comstock Coders'}, {'TeamNum': 20948, 'OPR': 16.851, 'Auto': 2.202, 'CCWM': -43.669, 'TeamName': 'Hug HS'}, {'TeamNum': 22774, 'OPR': 7.897, 'Auto': -4.043, 'CCWM': -65.753, 'TeamName': 'URSA Major'}, {'TeamNum': 21621, 'OPR': 4.767, 'Auto': -3.175, 'CCWM': -8.936, 'TeamName': 'Zoomies'}, {'TeamNum': 21897, 'OPR': 3.622, 'Auto': -2.322, 'CCWM': -30.732, 'TeamName': 'Oasis Academy'}]
i 815
{'18419', '22317', '21707', '17506', '21217', '22832', '20681', '18203', '16158', '11183', '15903', '21632', '16118'}
[{'TeamNum': 16158, 'OPR': 108.855, 'Auto': 34.059, 'CCWM': 100.774, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 18203, 'OPR': 58.895, 'Auto': 13.132, 'CCWM': 14.679, 'TeamName': 'MCII'}, {'TeamNum': 21707, 'OPR': 45.259, 'Auto': 4.723, 'CCWM': -1.074, 'TeamName': 'MinerBots'}, {'TeamNum': 21217, 'OPR': 44.34, 'Auto': 21.9, 'CCWM': -21.248, 'TeamName': 'The Phoenixes'}, {'TeamNum': 15903, 'OPR': 42.234, 'Auto': 15.22, 'CCWM': 12.476, 'TeamName': 'Chaos'}, {'TeamNum': 17506, 'OPR': 39.769, 'Auto': 2.457, 'CCWM': 15.489, 'TeamName': 'Wolverines'}, {'TeamNum': 16118, 'OPR': 39.09, 'Auto': 1.694, 'CCWM': 0.647, 'TeamName': '52! McQueen HS'}, {'TeamNum': 20681, 'OPR': 31.143, 'Auto': 1.258, 'CCWM': -4.876, 'TeamName': 'Giga Bite'}, {'TeamNum': 21632, 'OPR': 16.763, 'Auto': -1.767, 'CCWM': -9.786, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 22317, 'OPR': 12.076, 'Auto': -0.289, 'CCWM': -5.599, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 11183, 'OPR': 7.5, 'Auto': 3.573, 'CCWM': -29.146, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 18419, 'OPR': 6.088, 'Auto': -0.927, 'CCWM': -28.113, 'TeamName': 'Comstock Coders'}, {'TeamNum': 22832, 'OPR': 0.568, 'Auto': 3.39, 'CCWM': -45.987, 'TeamName': 'Tech Nation: Boys & Girls Club of Reno'}]
USNVNOM3N
[{'TeamNum': 16158, 'OPR': 108.855, 'Auto': 34.059, 'CCWM': 100.774, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 18203, 'OPR': 58.895, 'Auto': 13.132, 'CCWM': 14.679, 'TeamName': 'MCII'}, {'TeamNum': 21707, 'OPR': 45.259, 'Auto': 4.723, 'CCWM': -1.074, 'TeamName': 'MinerBots'}, {'TeamNum': 21217, 'OPR': 44.34, 'Auto': 21.9, 'CCWM': -21.248, 'TeamName': 'The Phoenixes'}, {'TeamNum': 15903, 'OPR': 42.234, 'Auto': 15.22, 'CCWM': 12.476, 'TeamName': 'Chaos'}, {'TeamNum': 17506, 'OPR': 39.769, 'Auto': 2.457, 'CCWM': 15.489, 'TeamName': 'Wolverines'}, {'TeamNum': 16118, 'OPR': 39.09, 'Auto': 1.694, 'CCWM': 0.647, 'TeamName': '52! McQueen HS'}, {'TeamNum': 20681, 'OPR': 31.143, 'Auto': 1.258, 'CCWM': -4.876, 'TeamName': 'Giga Bite'}, {'TeamNum': 21632, 'OPR': 16.763, 'Auto': -1.767, 'CCWM': -9.786, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 22317, 'OPR': 12.076, 'Auto': -0.289, 'CCWM': -5.599, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 11183, 'OPR': 7.5, 'Auto': 3.573, 'CCWM': -29.146, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 18419, 'OPR': 6.088, 'Auto': -0.927, 'CCWM': -28.113, 'TeamName': 'Comstock Coders'}, {'TeamNum': 22832, 'OPR': 0.568, 'Auto': 3.39, 'CCWM': -45.987, 'TeamName': 'Tech Nation: Boys & Girls Club of Reno'}]
i 816

{'21517', '18682', '11665', '18858', '17280', '12991', '19792', '14841', '20253', '18815', '21787', '18850', '15889'}
[{'TeamNum': 14841, 'OPR': 48.548, 'Auto': 1.857, 'CCWM': 22.524, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 21517, 'OPR': 47.172, 'Auto': 4.526, 'CCWM': 26.56, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 12991, 'OPR': 45.549, 'Auto': 16.007, 'CCWM': 17.301, 'TeamName': 'Awkward Silence'}, {'TeamNum': 17280, 'OPR': 35.299, 'Auto': -0.499, 'CCWM': 12.638, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 19792, 'OPR': 35.219, 'Auto': 5.895, 'CCWM': -2.233, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 21787, 'OPR': 25.521, 'Auto': 8.58, 'CCWM': 8.096, 'TeamName': 'ARC - White'}, {'TeamNum': 20253, 'OPR': 22.589, 'Auto': 4.804, 'CCWM': -15.827, 'TeamName': 'Robotic Tigers'}, {'TeamNum': 15889, 'OPR': 22.397, 'Auto': 6.205, 'CCWM': -9.78, 'TeamName': 'RoboDawgs'}, {'TeamNum': 18858, 'OPR': 20.823, 'Auto': 2.891, 'CCWM': -2.104, 'TeamName': 'ARC - Blue'}, {'TeamNum': 18850, 'OPR': 14.974, 'Auto': 10.428, 'CCWM': -2.782, 'TeamName': 'Kill Switch'}, {'TeamNum': 18815, 'OPR': 8.165, 'Auto': 0.836, 'CCWM': -20.688, 'TeamName': 'LANV Logic'}, {'TeamNum': 11665, 'OPR': 7.629, 'Auto': -0.792, 'CCWM': -10.525, 'TeamName': 'Iron Falcons'}, {'TeamNum': 18682, 'OPR': 2.068, 'Auto': 0.007, 'CCWM': -25.165, 'TeamName': 'Cyber Nights'}]
USNVSOM3S
[{'TeamNum': 14841, 'OPR': 48.548, 'Auto': 1.857, 'CCWM': 22.524, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 21517, 'OPR': 47.172, 'Auto': 4.526, 'CCWM': 26.56, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 12991, 'OPR': 45.549, 'Auto': 16.007, 'CCWM': 17.301, 'TeamName': 'Awkward Silence'}, {'TeamNum': 17280, 'OPR': 35.299, 'Auto': -0.499, 'CCWM': 12.638, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 19792, 'OPR': 35.219, 'Auto': 5.895, 'CCWM': -2.233, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 21787, 'OPR': 25.521, 'Auto': 8.58, 'CCWM': 8.096, 'TeamName': 'ARC - White'}, {'TeamNum': 20253, 'OPR': 22.589, 'Auto': 4.804, 'CCWM': -15.827, 'TeamName': 'Robotic Tigers'}, {'TeamNum': 15889, 'OPR': 22.397, 'Auto': 6.205, 'CCWM': -9.78, 'TeamName': 'RoboDawgs'}, {'TeamNum': 18858, 'OPR': 20.823, 'Auto': 2.891, 'CCWM': -2.104, 'TeamName': 'ARC - Blue'}, {'TeamNum': 18850, 'OPR': 14.974, 'Auto': 10.428, 'CCWM': -2.782, 'TeamName': 'Kill Switch'}, {'TeamNum': 18815, 'OPR': 8.165, 'Auto': 0.836, 'CCWM': -20.688, 'TeamName': 'LANV Logic'}, {'TeamNum': 11665, 'OPR': 7.629, 'Auto': -0.792, 'CCWM': -10.525, 'TeamName': 'Iron Falcons'}, {'TeamNum': 18682, 'OPR': 2.068, 'Auto': 0.007, 'CCWM': -25.165, 'TeamName': 'Cyber Nights'}]
i 817
{'21517', '22157', '12777', '3050', '22159', '12991', '14532', '15569', '18815'}
[{'TeamNum': 12991, 'OPR': 76.834, 'Auto': 20.417, 'CCWM': 65.058, 'TeamName': 'Awkward Silence'}, {'TeamNum': 21517, 'OPR': 62.206, 'Auto': 8.19, 'CCWM': 47.336, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 3050, 'OPR': 52.985, 'Auto': 16.609, 'CCWM': 50.546, 'TeamName': 'G-Bots'}, {'TeamNum': 15569, 'OPR': 49.762, 'Auto': 17.364, 'CCWM': 29.821, 'TeamName': 'RoboRattlers'}, {'TeamNum': 18815, 'OPR': 16.09, 'Auto': 2.858, 'CCWM': -11.911, 'TeamName': 'LANV Logic'}, {'TeamNum': 12777, 'OPR': 7.303, 'Auto': -2.837, 'CCWM': -42.184, 'TeamName': 'Boulder City SuperBots'}, {'TeamNum': 22157, 'OPR': 0.316, 'Auto': 0.553, 'CCWM': -41.969, 'TeamName': 'Gear Guys'}, {'TeamNum': 14532, 'OPR': -7.469, 'Auto': 0.963, 'CCWM': -62.721, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 22159, 'OPR': -11.439, 'Auto': -4.798, 'CCWM': -47.024, 'TeamName': 'Vulcans'}]
USNVSOM4S
[{'TeamNum': 12991, 'OPR': 76.834, 'Auto': 20.417, 'CCWM': 65.058, 'TeamName': 'Awkward Silence'}, {'TeamNum': 21517, 'OPR': 62.206, 'Auto': 8.19, 'CCWM': 47.336, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 3050, 'OPR': 52.985, 'Auto': 16.609, 'CCWM': 50.546, 'TeamName': 'G-Bots'}, {'TeamNum': 15569, 'OPR': 49.762, 'Auto': 17.364, 'CCWM': 29.821, 'TeamName': 'RoboRattlers'}, {'TeamNum': 18815, 'OPR': 16.09, 'Auto': 2.858, 'CCWM': -11.911, 'TeamName': 'LANV Logic'}, {'TeamNum': 12777, 'OPR': 7.303, 'Auto': -2.837, 'CCWM': -42.184, 'TeamName': 'Boulder City SuperBots'}, {'TeamNum': 22157, 'OPR': 0.316, 'Auto': 0.553, 'CCWM': -41.969, 'TeamName': 'Gear Guys'}, {'TeamNum': 14532, 'OPR': -7.469, 'Auto': 0.963, 'CCWM': -62.721, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 22159, 'OPR': -11.439, 'Auto': -4.798, 'CCWM': -47.024, 'TeamName': 'Vulcans'}]
i 818
{'14669', '17222', '13357', '12737', '4957', '13510', '4809', '21302', '14054', '12736', '5485', '8863', '13359', '6996', '16096', '4654', '22612', '13364', '5484', '13371', '7230', '18516', '22240'}
[{'TeamNum': 5485, 'OPR': 101.914, 'Auto': 28.853, 'CCWM': 80.235, 'TeamName': 'GorillaBots'}, {'TeamNum': 12737, 'OPR': 92.444, 'Auto': 26.53, 'CCWM': 64.639, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 14054, 'OPR': 81.598, 'Auto': 22.444, 'CCWM': 4.995, 'TeamName': 'IR Thunder'}, {'TeamNum': 17222, 'OPR': 80.088, 'Auto': 16.859, 'CCWM': 30.029, 'TeamName': 'PROTA'}, {'TeamNum': 22240, 'OPR': 74.82, 'Auto': 11.334, 'CCWM': 40.539, 'TeamName': 'Rough Estimate '}, {'TeamNum': 6996, 'OPR': 67.358, 'Auto': 22.666, 'CCWM': 20.729, 'TeamName': 'Oncoming Storm'}, {'TeamNum': 4654, 'OPR': 65.065, 'Auto': 5.171, 'CCWM': -15.002, 'TeamName': 'Jellyfish '}, {'TeamNum': 13357, 'OPR': 62.782, 'Auto': 19.982, 'CCWM': -8.122, 'TeamName': 'IR Lightning'}, {'TeamNum': 12736, 'OPR': 61.995, 'Auto': 21.359, 'CCWM': -13.071, 'TeamName': 'Electric Mayhem Green'}, {'TeamNum': 13371, 'OPR': 57.896, 'Auto': 8.69, 'CCWM': 3.214, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 8863, 'OPR': 49.402, 'Auto': 8.01, 'CCWM': 2.832, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 13359, 'OPR': 43.37, 'Auto': 14.869, 'CCWM': -14.816, 'TeamName': 'St. Lawrence Stingerz'}, {'TeamNum': 4957, 'OPR': 41.738, 'Auto': 14.518, 'CCWM': -15.973, 'TeamName': 'FM Robotics Team'}, {'TeamNum': 5484, 'OPR': 35.186, 'Auto': 17.589, 'CCWM': 8.541, 'TeamName': 'The EnderBots'}, {'TeamNum': 4809, 'OPR': 35.082, 'Auto': 5.123, 'CCWM': 3.767, 'TeamName': 'Botman'}, {'TeamNum': 13510, 'OPR': 27.669, 'Auto': -8.174, 'CCWM': -1.626, 'TeamName': 'MUCCBots!'}, {'TeamNum': 21302, 'OPR': 27.048, 'Auto': 3.568, 'CCWM': 11.684, 'TeamName': 'HCS Robotics (CLEOB@ya)'}, {'TeamNum': 22612, 'OPR': 26.067, 'Auto': 1.648, 'CCWM': -13.822, 'TeamName': 'New Wave'}, {'TeamNum': 13364, 'OPR': 22.777, 'Auto': 9.344, 'CCWM': -58.215, 'TeamName': 'Linear Lions'}, {'TeamNum': 7230, 'OPR': 21.343, 'Auto': -0.176, 'CCWM': -25.339, 'TeamName': 'SAS Atoms'}, {'TeamNum': 16096, 'OPR': 16.499, 'Auto': 8.496, 'CCWM': -18.53, 'TeamName': 'Raider Bots'}, {'TeamNum': 18516, 'OPR': 10.286, 'Auto': -1.401, 'CCWM': -32.049, 'TeamName': "Ragin' Rumble Ponies "}, {'TeamNum': 14669, 'OPR': -1.299, 'Auto': -0.868, 'CCWM': -49.569, 'TeamName': 'Vortex'}]
USNYEXUTQ
[{'TeamNum': 5485, 'OPR': 101.914, 'Auto': 28.853, 'CCWM': 80.235, 'TeamName': 'GorillaBots'}, {'TeamNum': 12737, 'OPR': 92.444, 'Auto': 26.53, 'CCWM': 64.639, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 14054, 'OPR': 81.598, 'Auto': 22.444, 'CCWM': 4.995, 'TeamName': 'IR Thunder'}, {'TeamNum': 17222, 'OPR': 80.088, 'Auto': 16.859, 'CCWM': 30.029, 'TeamName': 'PROTA'}, {'TeamNum': 22240, 'OPR': 74.82, 'Auto': 11.334, 'CCWM': 40.539, 'TeamName': 'Rough Estimate '}, {'TeamNum': 6996, 'OPR': 67.358, 'Auto': 22.666, 'CCWM': 20.729, 'TeamName': 'Oncoming Storm'}, {'TeamNum': 4654, 'OPR': 65.065, 'Auto': 5.171, 'CCWM': -15.002, 'TeamName': 'Jellyfish '}, {'TeamNum': 13357, 'OPR': 62.782, 'Auto': 19.982, 'CCWM': -8.122, 'TeamName': 'IR Lightning'}, {'TeamNum': 12736, 'OPR': 61.995, 'Auto': 21.359, 'CCWM': -13.071, 'TeamName': 'Electric Mayhem Green'}, {'TeamNum': 13371, 'OPR': 57.896, 'Auto': 8.69, 'CCWM': 3.214, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 8863, 'OPR': 49.402, 'Auto': 8.01, 'CCWM': 2.832, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 13359, 'OPR': 43.37, 'Auto': 14.869, 'CCWM': -14.816, 'TeamName': 'St. Lawrence Stingerz'}, {'TeamNum': 4957, 'OPR': 41.738, 'Auto': 14.518, 'CCWM': -15.973, 'TeamName': 'FM Robotics Team'}, {'TeamNum': 5484, 'OPR': 35.186, 'Auto': 17.589, 'CCWM': 8.541, 'TeamName': 'The EnderBots'}, {'TeamNum': 4809, 'OPR': 35.082, 'Auto': 5.123, 'CCWM': 3.767, 'TeamName': 'Botman'}, {'TeamNum': 13510, 'OPR': 27.669, 'Auto': -8.174, 'CCWM': -1.626, 'TeamName': 'MUCCBots!'}, {'TeamNum': 21302, 'OPR': 27.048, 'Auto': 3.568, 'CCWM': 11.684, 'TeamName': 'HCS Robotics (CLEOB@ya)'}, {'TeamNum': 22612, 'OPR': 26.067, 'Auto': 1.648, 'CCWM': -13.822, 'TeamName': 'New Wave'}, {'TeamNum': 13364, 'OPR': 22.777, 'Auto': 9.344, 'CCWM': -58.215, 'TeamName': 'Linear Lions'}, {'TeamNum': 7230, 'OPR': 21.343, 'Auto': -0.176, 'CCWM': -25.339, 'TeamName': 'SAS Atoms'}, {'TeamNum': 16096, 'OPR': 16.499, 'Auto': 8.496, 'CCWM': -18.53, 'TeamName': 'Raider Bots'}, {'TeamNum': 18516, 'OPR': 10.286, 'Auto': -1.401, 'CCWM': -32.049, 'TeamName': "Ragin' Rumble Ponies "}, {'TeamNum': 14669, 'OPR': -1.299, 'Auto': -0.868, 'CCWM': -49.569, 'TeamName': 'Vortex'}]

i 819
{'16426', '10355', '21523', '18274', '18410', '19668', '19901', '5553', '22561', '11572', '5044', '18802', '21810', '14134'}
[{'TeamNum': 5553, 'OPR': 104.125, 'Auto': 24.069, 'CCWM': 85.863, 'TeamName': 'RoboComets'}, {'TeamNum': 19668, 'OPR': 86.181, 'Auto': 14.892, 'CCWM': 72.892, 'TeamName': 'HiveMind'}, {'TeamNum': 18274, 'OPR': 80.062, 'Auto': 14.57, 'CCWM': 66.763, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 11572, 'OPR': 67.692, 'Auto': 17.307, 'CCWM': 35.47, 'TeamName': 'Mouse Spit'}, {'TeamNum': 10355, 'OPR': 63.946, 'Auto': 11.555, 'CCWM': 33.997, 'TeamName': 'Project Peacock'}, {'TeamNum': 19901, 'OPR': 56.694, 'Auto': 6.486, 'CCWM': 41.249, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 16426, 'OPR': 34.778, 'Auto': 7.164, 'CCWM': -39.622, 'TeamName': 'Absolute Zero'}, {'TeamNum': 18410, 'OPR': 26.062, 'Auto': 12.865, 'CCWM': -12.292, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 18802, 'OPR': 21.841, 'Auto': -4.17, 'CCWM': -56.213, 'TeamName': 'Robo Renegades'}, {'TeamNum': 21810, 'OPR': 19.75, 'Auto': 7.369, 'CCWM': -7.789, 'TeamName': 'Collinsville Middle School'}, {'TeamNum': 21523, 'OPR': 15.505, 'Auto': 2.363, 'CCWM': -42.06, 'TeamName': 'Team Phoenix '}, {'TeamNum': 5044, 'OPR': 12.151, 'Auto': -1.748, 'CCWM': -42.703, 'TeamName': 'Black Pearl Robotics'}, {'TeamNum': 14134, 'OPR': 1.012, 'Auto': 0.787, 'CCWM': -56.059, 'TeamName': 'N.E.W.T.'}, {'TeamNum': 22561, 'OPR': -8.791, 'Auto': -0.92, 'CCWM': -86.149, 'TeamName': 'Rana'}]
USOKOKLAM12
[{'TeamNum': 5553, 'OPR': 104.125, 'Auto': 24.069, 'CCWM': 85.863, 'TeamName': 'RoboComets'}, {'TeamNum': 19668, 'OPR': 86.181, 'Auto': 14.892, 'CCWM': 72.892, 'TeamName': 'HiveMind'}, {'TeamNum': 18274, 'OPR': 80.062, 'Auto': 14.57, 'CCWM': 66.763, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 11572, 'OPR': 67.692, 'Auto': 17.307, 'CCWM': 35.47, 'TeamName': 'Mouse Spit'}, {'TeamNum': 10355, 'OPR': 63.946, 'Auto': 11.555, 'CCWM': 33.997, 'TeamName': 'Project Peacock'}, {'TeamNum': 19901, 'OPR': 56.694, 'Auto': 6.486, 'CCWM': 41.249, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 16426, 'OPR': 34.778, 'Auto': 7.164, 'CCWM': -39.622, 'TeamName': 'Absolute Zero'}, {'TeamNum': 18410, 'OPR': 26.062, 'Auto': 12.865, 'CCWM': -12.292, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 18802, 'OPR': 21.841, 'Auto': -4.17, 'CCWM': -56.213, 'TeamName': 'Robo Renegades'}, {'TeamNum': 21810, 'OPR': 19.75, 'Auto': 7.369, 'CCWM': -7.789, 'TeamName': 'Collinsville Middle School'}, {'TeamNum': 21523, 'OPR': 15.505, 'Auto': 2.363, 'CCWM': -42.06, 'TeamName': 'Team Phoenix '}, {'TeamNum': 5044, 'OPR': 12.151, 'Auto': -1.748, 'CCWM': -42.703, 'TeamName': 'Black Pearl Robotics'}, {'TeamNum': 14134, 'OPR': 1.012, 'Auto': 0.787, 'CCWM': -56.059, 'TeamName': 'N.E.W.T.'}, {'TeamNum': 22561, 'OPR': -8.791, 'Auto': -0.92, 'CCWM': -86.149, 'TeamName': 'Rana'}]
i 820
{'22804', '8866', '19563', '8825', '22015', '17025', '21901', '7506', '4250', '22814', '10368'}
[{'TeamNum': 8825, 'OPR': 79.963, 'Auto': 22.265, 'CCWM': 64.901, 'TeamName': 'CADfish'}, {'TeamNum': 8866, 'OPR': 79.394, 'Auto': 21.475, 'CCWM': 44.227, 'TeamName': 'Cybernetics'}, {'TeamNum': 4250, 'OPR': 77.25, 'Auto': 24.636, 'CCWM': 63.821, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 7506, 'OPR': 62.088, 'Auto': 12.289, 'CCWM': 16.935, 'TeamName': 'System Overload'}, {'TeamNum': 22814, 'OPR': 39.606, 'Auto': 19.155, 'CCWM': -25.241, 'TeamName': 'FS Bulldogs'}, {'TeamNum': 22804, 'OPR': 27.568, 'Auto': -0.417, 'CCWM': -14.722, 'TeamName': 'Lions'}, {'TeamNum': 10368, 'OPR': 23.385, 'Auto': 5.597, 'CCWM': -24.901, 'TeamName': 'The Level Ups'}, {'TeamNum': 21901, 'OPR': 12.748, 'Auto': -0.647, 'CCWM': -6.823, 'TeamName': 'ERR0R_405'}, {'TeamNum': 19563, 'OPR': 11.589, 'Auto': 1.446, 'CCWM': -36.999, 'TeamName': 'Boise City BattleCats'}, {'TeamNum': 22015, 'OPR': 10.847, 'Auto': -3.881, 'CCWM': -26.245, 'TeamName': 'The Robo-Trojans'}, {'TeamNum': 17025, 'OPR': 1.284, 'Auto': -1.437, 'CCWM': -49.971, 'TeamName': 'Iron Talons           17025'}]
USOKOKLAM15
[{'TeamNum': 8825, 'OPR': 79.963, 'Auto': 22.265, 'CCWM': 64.901, 'TeamName': 'CADfish'}, {'TeamNum': 8866, 'OPR': 79.394, 'Auto': 21.475, 'CCWM': 44.227, 'TeamName': 'Cybernetics'}, {'TeamNum': 4250, 'OPR': 77.25, 'Auto': 24.636, 'CCWM': 63.821, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 7506, 'OPR': 62.088, 'Auto': 12.289, 'CCWM': 16.935, 'TeamName': 'System Overload'}, {'TeamNum': 22814, 'OPR': 39.606, 'Auto': 19.155, 'CCWM': -25.241, 'TeamName': 'FS Bulldogs'}, {'TeamNum': 22804, 'OPR': 27.568, 'Auto': -0.417, 'CCWM': -14.722, 'TeamName': 'Lions'}, {'TeamNum': 10368, 'OPR': 23.385, 'Auto': 5.597, 'CCWM': -24.901, 'TeamName': 'The Level Ups'}, {'TeamNum': 21901, 'OPR': 12.748, 'Auto': -0.647, 'CCWM': -6.823, 'TeamName': 'ERR0R_405'}, {'TeamNum': 19563, 'OPR': 11.589, 'Auto': 1.446, 'CCWM': -36.999, 'TeamName': 'Boise City BattleCats'}, {'TeamNum': 22015, 'OPR': 10.847, 'Auto': -3.881, 'CCWM': -26.245, 'TeamName': 'The Robo-Trojans'}, {'TeamNum': 17025, 'OPR': 1.284, 'Auto': -1.437, 'CCWM': -49.971, 'TeamName': 'Iron Talons           17025'}]
i 821
{'15562', '3963', '7878', '12721', '15365', '10428', '6727', '12599', '22293', '5627', '14126', '22167', '9044', '13439', '18127', '22168', '3093', '14876'}
[{'TeamNum': 12599, 'OPR': 187.131, 'Auto': 46.801, 'CCWM': 187.743, 'TeamName': 'Overcharged'}, {'TeamNum': 18127, 'OPR': 103.148, 'Auto': 13.347, 'CCWM': 64.872, 'TeamName': 'All Hands on Tech'}, {'TeamNum': 22167, 'OPR': 74.006, 'Auto': 27.719, 'CCWM': 46.502, 'TeamName': 'Infinity Angles'}, {'TeamNum': 14126, 'OPR': 68.2, 'Auto': -0.298, 'CCWM': 47.237, 'TeamName': 'Fibonacci'}, {'TeamNum': 5627, 'OPR': 61.074, 'Auto': 11.135, 'CCWM': 18.663, 'TeamName': 'Robotics Quasar Alliance'}, {'TeamNum': 13439, 'OPR': 56.531, 'Auto': 9.265, 'CCWM': 36.045, 'TeamName': 'The Atomic Paperclips'}, {'TeamNum': 3093, 'OPR': 41.129, 'Auto': 9.856, 'CCWM': 24.922, 'TeamName': 'The Metal Mercenaries'}, {'TeamNum': 15562, 'OPR': 33.835, 'Auto': 4.444, 'CCWM': -9.969, 'TeamName': 'Lightning 43'}, {'TeamNum': 22168, 'OPR': 32.171, 'Auto': 7.874, 'CCWM': -37.594, 'TeamName': 'Capybearings'}, {'TeamNum': 10428, 'OPR': 29.69, 'Auto': 6.057, 'CCWM': -32.897, 'TeamName': 'Ace Of Spades'}, {'TeamNum': 14876, 'OPR': 25.642, 'Auto': 6.02, 'CCWM': -74.689, 'TeamName': 'TRA3N REX'}, {'TeamNum': 7878, 'OPR': 23.032, 'Auto': 9.11, 'CCWM': -11.515, 'TeamName': 'Cougarbots'}, {'TeamNum': 12721, 'OPR': 22.521, 'Auto': 0.3, 'CCWM': -18.13, 'TeamName': 'Apollo'}, {'TeamNum': 9044, 'OPR': 8.343, 'Auto': 5.413, 'CCWM': -21.742, 'TeamName': "NERD-Hinsin's Legacy"}, {'TeamNum': 22293, 'OPR': 7.449, 'Auto': 3.076, 'CCWM': -58.251, 'TeamName': 'NERD-Airship'}, {'TeamNum': 3963, 'OPR': 5.36, 'Auto': -0.09, 'CCWM': -49.882, 'TeamName': 'Iron Legion'}, {'TeamNum': 6727, 'OPR': 2.789, 'Auto': 3.111, 'CCWM': -54.453, 'TeamName': 'Aluminumati'}, {'TeamNum': 15365, 'OPR': -2.381, 'Auto': -2.963, 'CCWM': -69.054, 'TeamName': 'Lightning 42'}]
USORWVLT
[{'TeamNum': 12599, 'OPR': 187.131, 'Auto': 46.801, 'CCWM': 187.743, 'TeamName': 'Overcharged'}, {'TeamNum': 18127, 'OPR': 103.148, 'Auto': 13.347, 'CCWM': 64.872, 'TeamName': 'All Hands on Tech'}, {'TeamNum': 22167, 'OPR': 74.006, 'Auto': 27.719, 'CCWM': 46.502, 'TeamName': 'Infinity Angles'}, {'TeamNum': 14126, 'OPR': 68.2, 'Auto': -0.298, 'CCWM': 47.237, 'TeamName': 'Fibonacci'}, {'TeamNum': 5627, 'OPR': 61.074, 'Auto': 11.135, 'CCWM': 18.663, 'TeamName': 'Robotics Quasar Alliance'}, {'TeamNum': 13439, 'OPR': 56.531, 'Auto': 9.265, 'CCWM': 36.045, 'TeamName': 'The Atomic Paperclips'}, {'TeamNum': 3093, 'OPR': 41.129, 'Auto': 9.856, 'CCWM': 24.922, 'TeamName': 'The Metal Mercenaries'}, {'TeamNum': 15562, 'OPR': 33.835, 'Auto': 4.444, 'CCWM': -9.969, 'TeamName': 'Lightning 43'}, {'TeamNum': 22168, 'OPR': 32.171, 'Auto': 7.874, 'CCWM': -37.594, 'TeamName': 'Capybearings'}, {'TeamNum': 10428, 'OPR': 29.69, 'Auto': 6.057, 'CCWM': -32.897, 'TeamName': 'Ace Of Spades'}, {'TeamNum': 14876, 'OPR': 25.642, 'Auto': 6.02, 'CCWM': -74.689, 'TeamName': 'TRA3N REX'}, {'TeamNum': 7878, 'OPR': 23.032, 'Auto': 9.11, 'CCWM': -11.515, 'TeamName': 'Cougarbots'}, {'TeamNum': 12721, 'OPR': 22.521, 'Auto': 0.3, 'CCWM': -18.13, 'TeamName': 'Apollo'}, {'TeamNum': 9044, 'OPR': 8.343, 'Auto': 5.413, 'CCWM': -21.742, 'TeamName': "NERD-Hinsin's Legacy"}, {'TeamNum': 22293, 'OPR': 7.449, 'Auto': 3.076, 'CCWM': -58.251, 'TeamName': 'NERD-Airship'}, {'TeamNum': 3963, 'OPR': 5.36, 'Auto': -0.09, 'CCWM': -49.882, 'TeamName': 'Iron Legion'}, {'TeamNum': 6727, 'OPR': 2.789, 'Auto': 3.111, 'CCWM': -54.453, 'TeamName': 'Aluminumati'}, {'TeamNum': 15365, 'OPR': -2.381, 'Auto': -2.963, 'CCWM': -69.054, 'TeamName': 'Lightning 42'}]

i 822
{'21237', '12180', '12179', '14687', '17082', '11703', '12215', '4239'}
[{'TeamNum': 4239, 'OPR': 77.771, 'Auto': 17.621, 'CCWM': 48.774, 'TeamName': 'Viridescent Vipers'}, {'TeamNum': 11703, 'OPR': 68.604, 'Auto': 28.854, 'CCWM': 57.19, 'TeamName': 'Tacos In Kool Hats'}, {'TeamNum': 12179, 'OPR': 39.479, 'Auto': 12.032, 'CCWM': 20.905, 'TeamName': 'Tachanka'}, {'TeamNum': 21237, 'OPR': 31.646, 'Auto': 6.193, 'CCWM': 14.988, 'TeamName': 'Mtn. Dudez'}, {'TeamNum': 12215, 'OPR': 23.979, 'Auto': 0.318, 'CCWM': -17.238, 'TeamName': 'Lab Rats'}, {'TeamNum': 14687, 'OPR': 23.146, 'Auto': 10.907, 'CCWM': -21.155, 'TeamName': 'Cybernetic Chaos'}, {'TeamNum': 17082, 'OPR': 15.271, 'Auto': 0.479, 'CCWM': -52.94, 'TeamName': 'Lathos'}, {'TeamNum': 12180, 'OPR': 0.104, 'Auto': -3.004, 'CCWM': -50.524, 'TeamName': 'Chicken Destruction'}]
USORNCLT
[{'TeamNum': 4239, 'OPR': 77.771, 'Auto': 17.621, 'CCWM': 48.774, 'TeamName': 'Viridescent Vipers'}, {'TeamNum': 11703, 'OPR': 68.604, 'Auto': 28.854, 'CCWM': 57.19, 'TeamName': 'Tacos In Kool Hats'}, {'TeamNum': 12179, 'OPR': 39.479, 'Auto': 12.032, 'CCWM': 20.905, 'TeamName': 'Tachanka'}, {'TeamNum': 21237, 'OPR': 31.646, 'Auto': 6.193, 'CCWM': 14.988, 'TeamName': 'Mtn. Dudez'}, {'TeamNum': 12215, 'OPR': 23.979, 'Auto': 0.318, 'CCWM': -17.238, 'TeamName': 'Lab Rats'}, {'TeamNum': 14687, 'OPR': 23.146, 'Auto': 10.907, 'CCWM': -21.155, 'TeamName': 'Cybernetic Chaos'}, {'TeamNum': 17082, 'OPR': 15.271, 'Auto': 0.479, 'CCWM': -52.94, 'TeamName': 'Lathos'}, {'TeamNum': 12180, 'OPR': 0.104, 'Auto': -3.004, 'CCWM': -50.524, 'TeamName': 'Chicken Destruction'}]
i 823
{'16844', '20177', '20300', '22488', '16843', '13909', '8153', '13908', '15036', '10531', '13907'}
[{'TeamNum': 20300, 'OPR': 71.543, 'Auto': 18.715, 'CCWM': 61.395, 'TeamName': 'Cove 3'}, {'TeamNum': 15036, 'OPR': 51.658, 'Auto': 19.678, 'CCWM': 45.654, 'TeamName': 'JavaDaHutt'}, {'TeamNum': 20177, 'OPR': 37.195, 'Auto': 10.036, 'CCWM': 1.493, 'TeamName': 'High Velocity'}, {'TeamNum': 22488, 'OPR': 37.11, 'Auto': 0.083, 'CCWM': 22.395, 'TeamName': 'Pilot Rock'}, {'TeamNum': 8153, 'OPR': 24.101, 'Auto': 2.152, 'CCWM': 15.137, 'TeamName': 'Team #8153'}, {'TeamNum': 16844, 'OPR': 15.845, 'Auto': 1.332, 'CCWM': 6.994, 'TeamName': 'Team #16844'}, {'TeamNum': 13908, 'OPR': 6.517, 'Auto': 1.431, 'CCWM': -22.178, 'TeamName': 'FBI'}, {'TeamNum': 13909, 'OPR': 5.131, 'Auto': -2.383, 'CCWM': -33.335, 'TeamName': 'Team #13909'}, {'TeamNum': 16843, 'OPR': 0.646, 'Auto': -2.607, 'CCWM': -34.968, 'TeamName': 'Team #16843'}, {'TeamNum': 13907, 'OPR': -6.405, 'Auto': -3.989, 'CCWM': -27.952, 'TeamName': 'GREMLINS '}, {'TeamNum': 10531, 'OPR': -8.646, 'Auto': -0.535, 'CCWM': -30.201, 'TeamName': 'Team #10531'}]
USORCBM3
[{'TeamNum': 20300, 'OPR': 71.543, 'Auto': 18.715, 'CCWM': 61.395, 'TeamName': 'Cove 3'}, {'TeamNum': 15036, 'OPR': 51.658, 'Auto': 19.678, 'CCWM': 45.654, 'TeamName': 'JavaDaHutt'}, {'TeamNum': 20177, 'OPR': 37.195, 'Auto': 10.036, 'CCWM': 1.493, 'TeamName': 'High Velocity'}, {'TeamNum': 22488, 'OPR': 37.11, 'Auto': 0.083, 'CCWM': 22.395, 'TeamName': 'Pilot Rock'}, {'TeamNum': 8153, 'OPR': 24.101, 'Auto': 2.152, 'CCWM': 15.137, 'TeamName': 'Team #8153'}, {'TeamNum': 16844, 'OPR': 15.845, 'Auto': 1.332, 'CCWM': 6.994, 'TeamName': 'Team #16844'}, {'TeamNum': 13908, 'OPR': 6.517, 'Auto': 1.431, 'CCWM': -22.178, 'TeamName': 'FBI'}, {'TeamNum': 13909, 'OPR': 5.131, 'Auto': -2.383, 'CCWM': -33.335, 'TeamName': 'Team #13909'}, {'TeamNum': 16843, 'OPR': 0.646, 'Auto': -2.607, 'CCWM': -34.968, 'TeamName': 'Team #16843'}, {'TeamNum': 13907, 'OPR': -6.405, 'Auto': -3.989, 'CCWM': -27.952, 'TeamName': 'GREMLINS '}, {'TeamNum': 10531, 'OPR': -8.646, 'Auto': -0.535, 'CCWM': -30.201, 'TeamName': 'Team #10531'}]
i 824
{'9242', '16776', '18603', '21324', '14133', '21357', '16606', '6378', '17334', '11319', '8509', '10333', '13474', '20153', '21437', '9791', '11349', '8468', '11208', '10771', '14464', '10353', '8645', '21441'}
[{'TeamNum': 20153, 'OPR': 119.35, 'Auto': 29.847, 'CCWM': 76.377, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8645, 'OPR': 103.066, 'Auto': 20.676, 'CCWM': 89.059, 'TeamName': 'Robotic Doges'}, {'TeamNum': 8468, 'OPR': 101.668, 'Auto': 19.732, 'CCWM': 69.185, 'TeamName': 'The Javengers'}, {'TeamNum': 11349, 'OPR': 88.937, 'Auto': 19.261, 'CCWM': 32.044, 'TeamName': 'VorTech'}, {'TeamNum': 9242, 'OPR': 85.899, 'Auto': 14.643, 'CCWM': 35.241, 'TeamName': 'GearHounds'}, {'TeamNum': 8509, 'OPR': 75.864, 'Auto': 9.967, 'CCWM': 29.94, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 21437, 'OPR': 62.249, 'Auto': 7.084, 'CCWM': -3.779, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 21357, 'OPR': 58.815, 'Auto': 20.659, 'CCWM': 21.838, 'TeamName': 'ROGO (Robotics Offering Girls Opportunities)'}, {'TeamNum': 16776, 'OPR': 58.349, 'Auto': -4.447, 'CCWM': 54.319, 'TeamName': 'MARS: Opportunity S.T.E.A.M. punk!'}, {'TeamNum': 10333, 'OPR': 57.339, 'Auto': 16.369, 'CCWM': -7.697, 'TeamName': 'TechSpark'}, {'TeamNum': 14464, 'OPR': 55.86, 'Auto': 24.066, 'CCWM': -3.652, 'TeamName': 'BotBusters'}, {'TeamNum': 17334, 'OPR': 49.659, 'Auto': 10.349, 'CCWM': -18.39, 'TeamName': 'Panthera Robotica'}, {'TeamNum': 11208, 'OPR': 48.034, 'Auto': 10.906, 'CCWM': -24.734, 'TeamName': 'Kardia Robotics'}, {'TeamNum': 16606, 'OPR': 47.551, 'Auto': 17.163, 'CCWM': 8.133, 'TeamName': 'Tech-Knight Robotics'}, {'TeamNum': 21441, 'OPR': 43.843, 'Auto': 28.084, 'CCWM': -21.79, 'TeamName': 'The Little Red Pony'}, {'TeamNum': 14133, 'OPR': 43.79, 'Auto': 13.343, 'CCWM': -24.597, 'TeamName': 'Lansdale Catholic Cyber Crusaders'}, {'TeamNum': 21324, 'OPR': 40.348, 'Auto': 9.853, 'CCWM': -4.739, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 18603, 'OPR': 30.861, 'Auto': 16.893, 'CCWM': -6.826, 'TeamName': 'TeraBridges'}, {'TeamNum': 6378, 'OPR': 29.93, 'Auto': 4.987, 'CCWM': -31.156, 'TeamName': 'JayBots'}, {'TeamNum': 10353, 'OPR': 23.493, 'Auto': 6.798, 'CCWM': -32.109, 'TeamName': 'Metal Works'}, {'TeamNum': 11319, 'OPR': 21.863, 'Auto': 6.97, 'CCWM': -67.466, 'TeamName': 'Explorer Robotics'}, {'TeamNum': 13474, 'OPR': 15.096, 'Auto': 7.051, 'CCWM': -44.7, 'TeamName': 'MARS: Curiosity?'}, {'TeamNum': 10771, 'OPR': 13.929, 'Auto': -5.311, 'CCWM': -18.088, 'TeamName': 'Le Pamplemousse'}, {'TeamNum': 9791, 'OPR': 0.808, 'Auto': 0.858, 'CCWM': -106.412, 'TeamName': 'Divide by Zero'}]
USPAYOQ2
[{'TeamNum': 20153, 'OPR': 119.35, 'Auto': 29.847, 'CCWM': 76.377, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8645, 'OPR': 103.066, 'Auto': 20.676, 'CCWM': 89.059, 'TeamName': 'Robotic Doges'}, {'TeamNum': 8468, 'OPR': 101.668, 'Auto': 19.732, 'CCWM': 69.185, 'TeamName': 'The Javengers'}, {'TeamNum': 11349, 'OPR': 88.937, 'Auto': 19.261, 'CCWM': 32.044, 'TeamName': 'VorTech'}, {'TeamNum': 9242, 'OPR': 85.899, 'Auto': 14.643, 'CCWM': 35.241, 'TeamName': 'GearHounds'}, {'TeamNum': 8509, 'OPR': 75.864, 'Auto': 9.967, 'CCWM': 29.94, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 21437, 'OPR': 62.249, 'Auto': 7.084, 'CCWM': -3.779, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 21357, 'OPR': 58.815, 'Auto': 20.659, 'CCWM': 21.838, 'TeamName': 'ROGO (Robotics Offering Girls Opportunities)'}, {'TeamNum': 16776, 'OPR': 58.349, 'Auto': -4.447, 'CCWM': 54.319, 'TeamName': 'MARS: Opportunity S.T.E.A.M. punk!'}, {'TeamNum': 10333, 'OPR': 57.339, 'Auto': 16.369, 'CCWM': -7.697, 'TeamName': 'TechSpark'}, {'TeamNum': 14464, 'OPR': 55.86, 'Auto': 24.066, 'CCWM': -3.652, 'TeamName': 'BotBusters'}, {'TeamNum': 17334, 'OPR': 49.659, 'Auto': 10.349, 'CCWM': -18.39, 'TeamName': 'Panthera Robotica'}, {'TeamNum': 11208, 'OPR': 48.034, 'Auto': 10.906, 'CCWM': -24.734, 'TeamName': 'Kardia Robotics'}, {'TeamNum': 16606, 'OPR': 47.551, 'Auto': 17.163, 'CCWM': 8.133, 'TeamName': 'Tech-Knight Robotics'}, {'TeamNum': 21441, 'OPR': 43.843, 'Auto': 28.084, 'CCWM': -21.79, 'TeamName': 'The Little Red Pony'}, {'TeamNum': 14133, 'OPR': 43.79, 'Auto': 13.343, 'CCWM': -24.597, 'TeamName': 'Lansdale Catholic Cyber Crusaders'}, {'TeamNum': 21324, 'OPR': 40.348, 'Auto': 9.853, 'CCWM': -4.739, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 18603, 'OPR': 30.861, 'Auto': 16.893, 'CCWM': -6.826, 'TeamName': 'TeraBridges'}, {'TeamNum': 6378, 'OPR': 29.93, 'Auto': 4.987, 'CCWM': -31.156, 'TeamName': 'JayBots'}, {'TeamNum': 10353, 'OPR': 23.493, 'Auto': 6.798, 'CCWM': -32.109, 'TeamName': 'Metal Works'}, {'TeamNum': 11319, 'OPR': 21.863, 'Auto': 6.97, 'CCWM': -67.466, 'TeamName': 'Explorer Robotics'}, {'TeamNum': 13474, 'OPR': 15.096, 'Auto': 7.051, 'CCWM': -44.7, 'TeamName': 'MARS: Curiosity?'}, {'TeamNum': 10771, 'OPR': 13.929, 'Auto': -5.311, 'CCWM': -18.088, 'TeamName': 'Le Pamplemousse'}, {'TeamNum': 9791, 'OPR': 0.808, 'Auto': 0.858, 'CCWM': -106.412, 'TeamName': 'Divide by Zero'}]

i 825
{'9242', '3795', '7416', '18035', '11830', '12792', '14130', '16354', '7786', '7244', '21928', '21324', '21916', '16269', '16466', '17596', '14382', '20152', '22311', '8509', '5440', '21458', '20201', '4185', '21727', '19844', '14464', '14842', '10098', '21728'}
[{'TeamNum': 20152, 'OPR': 85.227, 'Auto': 23.82, 'CCWM': 21.901, 'TeamName': 'Battle Bots'}, {'TeamNum': 7244, 'OPR': 78.38, 'Auto': 20.533, 'CCWM': 21.755, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 21324, 'OPR': 76.061, 'Auto': 20.185, 'CCWM': 35.427, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 8509, 'OPR': 75.786, 'Auto': 17.119, 'CCWM': 50.75, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 20201, 'OPR': 63.311, 'Auto': 21.67, 'CCWM': 43.306, 'TeamName': 'Centre county 4H Robotics- The Mighty Ducks'}, {'TeamNum': 16269, 'OPR': 61.972, 'Auto': 10.144, 'CCWM': 64.387, 'TeamName': 'Guthrie Geeks'}, {'TeamNum': 9242, 'OPR': 61.067, 'Auto': 12.063, 'CCWM': 34.651, 'TeamName': 'GearHounds'}, {'TeamNum': 19844, 'OPR': 60.377, 'Auto': 17.71, 'CCWM': 45.948, 'TeamName': 'ElectroCorns'}, {'TeamNum': 14382, 'OPR': 58.417, 'Auto': 9.514, 'CCWM': 31.932, 'TeamName': 'CC4H Robotics - Flex Force 1'}, {'TeamNum': 5440, 'OPR': 51.181, 'Auto': 4.351, 'CCWM': 19.595, 'TeamName': "Blazin' Circuits"}, {'TeamNum': 10098, 'OPR': 50.948, 'Auto': 20.638, 'CCWM': 3.332, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 12792, 'OPR': 48.372, 'Auto': 11.88, 'CCWM': 12.452, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 22311, 'OPR': 45.725, 'Auto': 19.637, 'CCWM': 4.239, 'TeamName': 'CC4H Robotics - Robocougars'}, {'TeamNum': 18035, 'OPR': 40.971, 'Auto': 3.614, 'CCWM': -28.956, 'TeamName': 'Reconnecting...'}, {'TeamNum': 14130, 'OPR': 39.86, 'Auto': 5.161, 'CCWM': -12.18, 'TeamName': 'To Be Determined'}, {'TeamNum': 21728, 'OPR': 38.952, 'Auto': 9.752, 'CCWM': -14.978, 'TeamName': 'TechniCorns'}, {'TeamNum': 16466, 'OPR': 34.712, 'Auto': 4.848, 'CCWM': -16.685, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 21458, 'OPR': 34.067, 'Auto': -1.16, 'CCWM': -9.194, 'TeamName': 'Broken Blueberries'}, {'TeamNum': 14842, 'OPR': 31.103, 'Auto': 7.473, 'CCWM': -25.303, 'TeamName': 'SPYGEARS'}, {'TeamNum': 11830, 'OPR': 29.692, 'Auto': 5.163, 'CCWM': -10.704, 'TeamName': 'RarBots'}, {'TeamNum': 14464, 'OPR': 27.867, 'Auto': 13.062, 'CCWM': -24.63, 'TeamName': 'BotBusters'}, {'TeamNum': 21916, 'OPR': 26.019, 'Auto': 13.62, 'CCWM': -31.431, 'TeamName': 'Hive Voltage'}, {'TeamNum': 7786, 'OPR': 24.56, 'Auto': 6.553, 'CCWM': -10.47, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 4185, 'OPR': 24.401, 'Auto': -1.254, 'CCWM': -21.144, 'TeamName': 'Silver Soldiers'}, {'TeamNum': 21928, 'OPR': 23.711, 'Auto': 5.626, 'CCWM': -22.257, 'TeamName': 'TeleCorns'}, {'TeamNum': 16354, 'OPR': 21.027, 'Auto': 1.83, 'CCWM': 18.487, 'TeamName': 'Phobos Ares Robotics Team'}, {'TeamNum': 21727, 'OPR': 16.339, 'Auto': 5.378, 'CCWM': -29.16, 'TeamName': 'AutoCorns'}, {'TeamNum': 7416, 'OPR': 14.412, 'Auto': 2.636, 'CCWM': -67.625, 'TeamName': 'Silver Spartans'}, {'TeamNum': 17596, 'OPR': 8.195, 'Auto': -2.464, 'CCWM': -42.407, 'TeamName': 'Maneframe'}, {'TeamNum': 3795, 'OPR': -0.968, 'Auto': 1.919, 'CCWM': -52.344, 'TeamName': 'JagWired'}]
USPAYOQ1
[{'TeamNum': 20152, 'OPR': 85.227, 'Auto': 23.82, 'CCWM': 21.901, 'TeamName': 'Battle Bots'}, {'TeamNum': 7244, 'OPR': 78.38, 'Auto': 20.533, 'CCWM': 21.755, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 21324, 'OPR': 76.061, 'Auto': 20.185, 'CCWM': 35.427, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 8509, 'OPR': 75.786, 'Auto': 17.119, 'CCWM': 50.75, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 20201, 'OPR': 63.311, 'Auto': 21.67, 'CCWM': 43.306, 'TeamName': 'Centre county 4H Robotics- The Mighty Ducks'}, {'TeamNum': 16269, 'OPR': 61.972, 'Auto': 10.144, 'CCWM': 64.387, 'TeamName': 'Guthrie Geeks'}, {'TeamNum': 9242, 'OPR': 61.067, 'Auto': 12.063, 'CCWM': 34.651, 'TeamName': 'GearHounds'}, {'TeamNum': 19844, 'OPR': 60.377, 'Auto': 17.71, 'CCWM': 45.948, 'TeamName': 'ElectroCorns'}, {'TeamNum': 14382, 'OPR': 58.417, 'Auto': 9.514, 'CCWM': 31.932, 'TeamName': 'CC4H Robotics - Flex Force 1'}, {'TeamNum': 5440, 'OPR': 51.181, 'Auto': 4.351, 'CCWM': 19.595, 'TeamName': "Blazin' Circuits"}, {'TeamNum': 10098, 'OPR': 50.948, 'Auto': 20.638, 'CCWM': 3.332, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 12792, 'OPR': 48.372, 'Auto': 11.88, 'CCWM': 12.452, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 22311, 'OPR': 45.725, 'Auto': 19.637, 'CCWM': 4.239, 'TeamName': 'CC4H Robotics - Robocougars'}, {'TeamNum': 18035, 'OPR': 40.971, 'Auto': 3.614, 'CCWM': -28.956, 'TeamName': 'Reconnecting...'}, {'TeamNum': 14130, 'OPR': 39.86, 'Auto': 5.161, 'CCWM': -12.18, 'TeamName': 'To Be Determined'}, {'TeamNum': 21728, 'OPR': 38.952, 'Auto': 9.752, 'CCWM': -14.978, 'TeamName': 'TechniCorns'}, {'TeamNum': 16466, 'OPR': 34.712, 'Auto': 4.848, 'CCWM': -16.685, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 21458, 'OPR': 34.067, 'Auto': -1.16, 'CCWM': -9.194, 'TeamName': 'Broken Blueberries'}, {'TeamNum': 14842, 'OPR': 31.103, 'Auto': 7.473, 'CCWM': -25.303, 'TeamName': 'SPYGEARS'}, {'TeamNum': 11830, 'OPR': 29.692, 'Auto': 5.163, 'CCWM': -10.704, 'TeamName': 'RarBots'}, {'TeamNum': 14464, 'OPR': 27.867, 'Auto': 13.062, 'CCWM': -24.63, 'TeamName': 'BotBusters'}, {'TeamNum': 21916, 'OPR': 26.019, 'Auto': 13.62, 'CCWM': -31.431, 'TeamName': 'Hive Voltage'}, {'TeamNum': 7786, 'OPR': 24.56, 'Auto': 6.553, 'CCWM': -10.47, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 4185, 'OPR': 24.401, 'Auto': -1.254, 'CCWM': -21.144, 'TeamName': 'Silver Soldiers'}, {'TeamNum': 21928, 'OPR': 23.711, 'Auto': 5.626, 'CCWM': -22.257, 'TeamName': 'TeleCorns'}, {'TeamNum': 16354, 'OPR': 21.027, 'Auto': 1.83, 'CCWM': 18.487, 'TeamName': 'Phobos Ares Robotics Team'}, {'TeamNum': 21727, 'OPR': 16.339, 'Auto': 5.378, 'CCWM': -29.16, 'TeamName': 'AutoCorns'}, {'TeamNum': 7416, 'OPR': 14.412, 'Auto': 2.636, 'CCWM': -67.625, 'TeamName': 'Silver Spartans'}, {'TeamNum': 17596, 'OPR': 8.195, 'Auto': -2.464, 'CCWM': -42.407, 'TeamName': 'Maneframe'}, {'TeamNum': 3795, 'OPR': -0.968, 'Auto': 1.919, 'CCWM': -52.344, 'TeamName': 'JagWired'}]
i 826
{'9219', '9128', '22142', '22671', '3032', '22141', '701', '10773', '20772', '7093', '18209', '8129', '20763'}
[{'TeamNum': 7093, 'OPR': 70.814, 'Auto': 17.516, 'CCWM': 58.797, 'TeamName': 'RaiderBots'}, {'TeamNum': 701, 'OPR': 47.235, 'Auto': 5.513, 'CCWM': 23.917, 'TeamName': 'The GONKa Trucks'}, {'TeamNum': 20763, 'OPR': 47.172, 'Auto': 17.219, 'CCWM': 28.901, 'TeamName': 'Iron Lions'}, {'TeamNum': 22141, 'OPR': 44.568, 'Auto': 14.685, 'CCWM': 6.111, 'TeamName': 'Seal Team Seven'}, {'TeamNum': 10773, 'OPR': 44.423, 'Auto': 12.16, 'CCWM': 22.151, 'TeamName': 'Chariho Chargers'}, {'TeamNum': 3032, 'OPR': 43.924, 'Auto': 11.955, 'CCWM': 6.965, 'TeamName': 'Hyperion'}, {'TeamNum': 22142, 'OPR': 36.356, 'Auto': 6.72, 'CCWM': 9.43, 'TeamName': 'Echo X'}, {'TeamNum': 9219, 'OPR': 27.536, 'Auto': 14.048, 'CCWM': -29.601, 'TeamName': "If It Ain't Broke"}, {'TeamNum': 18209, 'OPR': 26.588, 'Auto': 4.437, 'CCWM': -22.163, 'TeamName': 'Full Stop'}, {'TeamNum': 8129, 'OPR': 24.548, 'Auto': 15.346, 'CCWM': -27.857, 'TeamName': 'Sons of Liberty'}, {'TeamNum': 22671, 'OPR': 14.759, 'Auto': -0.456, 'CCWM': -21.06, 'TeamName': 'Ellipsis'}, {'TeamNum': 20772, 'OPR': 11.661, 'Auto': 4.396, 'CCWM': -26.579, 'TeamName': 'Patriots 3901'}, {'TeamNum': 9128, 'OPR': 6.348, 'Auto': -5.161, 'CCWM': -37.814, 'TeamName': 'Mounties'}]
USRIWOQ
[{'TeamNum': 7093, 'OPR': 70.814, 'Auto': 17.516, 'CCWM': 58.797, 'TeamName': 'RaiderBots'}, {'TeamNum': 701, 'OPR': 47.235, 'Auto': 5.513, 'CCWM': 23.917, 'TeamName': 'The GONKa Trucks'}, {'TeamNum': 20763, 'OPR': 47.172, 'Auto': 17.219, 'CCWM': 28.901, 'TeamName': 'Iron Lions'}, {'TeamNum': 22141, 'OPR': 44.568, 'Auto': 14.685, 'CCWM': 6.111, 'TeamName': 'Seal Team Seven'}, {'TeamNum': 10773, 'OPR': 44.423, 'Auto': 12.16, 'CCWM': 22.151, 'TeamName': 'Chariho Chargers'}, {'TeamNum': 3032, 'OPR': 43.924, 'Auto': 11.955, 'CCWM': 6.965, 'TeamName': 'Hyperion'}, {'TeamNum': 22142, 'OPR': 36.356, 'Auto': 6.72, 'CCWM': 9.43, 'TeamName': 'Echo X'}, {'TeamNum': 9219, 'OPR': 27.536, 'Auto': 14.048, 'CCWM': -29.601, 'TeamName': "If It Ain't Broke"}, {'TeamNum': 18209, 'OPR': 26.588, 'Auto': 4.437, 'CCWM': -22.163, 'TeamName': 'Full Stop'}, {'TeamNum': 8129, 'OPR': 24.548, 'Auto': 15.346, 'CCWM': -27.857, 'TeamName': 'Sons of Liberty'}, {'TeamNum': 22671, 'OPR': 14.759, 'Auto': -0.456, 'CCWM': -21.06, 'TeamName': 'Ellipsis'}, {'TeamNum': 20772, 'OPR': 11.661, 'Auto': 4.396, 'CCWM': -26.579, 'TeamName': 'Patriots 3901'}, {'TeamNum': 9128, 'OPR': 6.348, 'Auto': -5.161, 'CCWM': -37.814, 'TeamName': 'Mounties'}]
i 827

{'22851', '673', '753', '10021', '18308', '15773', '13661'}
[{'TeamNum': 18308, 'OPR': 25.86, 'Auto': 1.506, 'CCWM': 18.416, 'TeamName': ' Team RocketForge'}, {'TeamNum': 13661, 'OPR': 18.624, 'Auto': 4.797, 'CCWM': 1.978, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 673, 'OPR': 14.729, 'Auto': -1.576, 'CCWM': 3.352, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 753, 'OPR': 12.129, 'Auto': 0.424, 'CCWM': -1.648, 'TeamName': 'The GreenVillains'}, {'TeamNum': 15773, 'OPR': 11.482, 'Auto': 3.082, 'CCWM': 2.264, 'TeamName': 'Robodogs'}, {'TeamNum': 22851, 'OPR': 9.003, 'Auto': 1.221, 'CCWM': -7.87, 'TeamName': 'FC^2 Robotics'}, {'TeamNum': 10021, 'OPR': -3.471, 'Auto': -1.576, 'CCWM': -18.248, 'TeamName': 'The Red Legion'}]
USSCRHS
[{'TeamNum': 18308, 'OPR': 25.86, 'Auto': 1.506, 'CCWM': 18.416, 'TeamName': ' Team RocketForge'}, {'TeamNum': 13661, 'OPR': 18.624, 'Auto': 4.797, 'CCWM': 1.978, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 673, 'OPR': 14.729, 'Auto': -1.576, 'CCWM': 3.352, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 753, 'OPR': 12.129, 'Auto': 0.424, 'CCWM': -1.648, 'TeamName': 'The GreenVillains'}, {'TeamNum': 15773, 'OPR': 11.482, 'Auto': 3.082, 'CCWM': 2.264, 'TeamName': 'Robodogs'}, {'TeamNum': 22851, 'OPR': 9.003, 'Auto': 1.221, 'CCWM': -7.87, 'TeamName': 'FC^2 Robotics'}, {'TeamNum': 10021, 'OPR': -3.471, 'Auto': -1.576, 'CCWM': -18.248, 'TeamName': 'The Red Legion'}]
i 828
i 829
{'19707', '22199', '13196', '3641', '18069', '7021', '18984', '13900', '15296'}
[{'TeamNum': 13900, 'OPR': 33.415, 'Auto': 12.548, 'CCWM': 26.267, 'TeamName': 'Iron Horses'}, {'TeamNum': 18984, 'OPR': 28.91, 'Auto': 17.185, 'CCWM': 15.52, 'TeamName': 'Hurricanes505'}, {'TeamNum': 3641, 'OPR': 18.329, 'Auto': -0.555, 'CCWM': 4.876, 'TeamName': 'PPS Robotics'}, {'TeamNum': 19707, 'OPR': 15.582, 'Auto': 7.133, 'CCWM': 11.973, 'TeamName': 'NanoHawks'}, {'TeamNum': 15296, 'OPR': 12.567, 'Auto': 1.23, 'CCWM': -5.885, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 13196, 'OPR': 7.65, 'Auto': 2.061, 'CCWM': -9.498, 'TeamName': 'BA Robotics'}, {'TeamNum': 7021, 'OPR': 6.973, 'Auto': 3.293, 'CCWM': -7.626, 'TeamName': 'RoboEagles'}, {'TeamNum': 22199, 'OPR': 2.498, 'Auto': 0.109, 'CCWM': -13.893, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 18069, 'OPR': 0.151, 'Auto': -0.575, 'CCWM': -22.459, 'TeamName': 'Java Dragons'}]
USSCNLCS3
[{'TeamNum': 13900, 'OPR': 33.415, 'Auto': 12.548, 'CCWM': 26.267, 'TeamName': 'Iron Horses'}, {'TeamNum': 18984, 'OPR': 28.91, 'Auto': 17.185, 'CCWM': 15.52, 'TeamName': 'Hurricanes505'}, {'TeamNum': 3641, 'OPR': 18.329, 'Auto': -0.555, 'CCWM': 4.876, 'TeamName': 'PPS Robotics'}, {'TeamNum': 19707, 'OPR': 15.582, 'Auto': 7.133, 'CCWM': 11.973, 'TeamName': 'NanoHawks'}, {'TeamNum': 15296, 'OPR': 12.567, 'Auto': 1.23, 'CCWM': -5.885, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 13196, 'OPR': 7.65, 'Auto': 2.061, 'CCWM': -9.498, 'TeamName': 'BA Robotics'}, {'TeamNum': 7021, 'OPR': 6.973, 'Auto': 3.293, 'CCWM': -7.626, 'TeamName': 'RoboEagles'}, {'TeamNum': 22199, 'OPR': 2.498, 'Auto': 0.109, 'CCWM': -13.893, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 18069, 'OPR': 0.151, 'Auto': -0.575, 'CCWM': -22.459, 'TeamName': 'Java Dragons'}]
i 830
i 831
{'11030', '4745', '18270', '15226', '11978', '8291', '9161', '21921', '20325', '9054', '21330', '20039', '16012', '16412', '20051', '18327', '21533', '21607', '13657', '13811', '14445', '9045', '13472', '4705', '18072', '20313', '16802', '17658', '18227', '20040', '18310', '6566', '6169', '22539'}
[{'TeamNum': 18227, 'OPR': 124.907, 'Auto': 28.647, 'CCWM': 86.312, 'TeamName': 'Area 52'}, {'TeamNum': 21330, 'OPR': 106.499, 'Auto': 27.561, 'CCWM': 94.266, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 18270, 'OPR': 97.987, 'Auto': 35.114, 'CCWM': 46.893, 'TeamName': 'RoboPlayers'}, {'TeamNum': 16412, 'OPR': 71.24, 'Auto': 17.505, 'CCWM': 47.293, 'TeamName': 'Triad Robotics'}, {'TeamNum': 13472, 'OPR': 69.826, 'Auto': 20.318, 'CCWM': 2.549, 'TeamName': 'The Dork Side'}, {'TeamNum': 20325, 'OPR': 67.993, 'Auto': 13.613, 'CCWM': 13.528, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 13811, 'OPR': 67.188, 'Auto': 15.681, 'CCWM': 17.013, 'TeamName': 'High Voltage'}, {'TeamNum': 16802, 'OPR': 64.528, 'Auto': 12.492, 'CCWM': 60.202, 'TeamName': 'Hollibots'}, {'TeamNum': 9045, 'OPR': 50.926, 'Auto': 16.473, 'CCWM': 32.065, 'TeamName': 'Motorhead'}, {'TeamNum': 21607, 'OPR': 50.788, 'Auto': 24.317, 'CCWM': -33.304, 'TeamName': 'Kcalians'}, {'TeamNum': 15226, 'OPR': 49.361, 'Auto': 6.883, 'CCWM': -2.589, 'TeamName': 'Salamancas'}, {'TeamNum': 20313, 'OPR': 48.885, 'Auto': 11.241, 'CCWM': 35.655, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 9161, 'OPR': 47.34, 'Auto': 12.838, 'CCWM': -24.381, 'TeamName': 'Overload'}, {'TeamNum': 20051, 'OPR': 42.518, 'Auto': 5.394, 'CCWM': 27.942, 'TeamName': 'Code Red'}, {'TeamNum': 17658, 'OPR': 42.191, 'Auto': 1.021, 'CCWM': 0.474, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 18072, 'OPR': 41.023, 'Auto': 16.273, 'CCWM': 0.763, 'TeamName': 'BCS Battery Acid'}, {'TeamNum': 21533, 'OPR': 27.596, 'Auto': 19.151, 'CCWM': 2.303, 'TeamName': 'Keller Fusion FTC'}, {'TeamNum': 4745, 'OPR': 25.717, 'Auto': -5.628, 'CCWM': -32.579, 'TeamName': 'Grand Tech Automation'}, {'TeamNum': 6566, 'OPR': 24.836, 'Auto': 5.328, 'CCWM': 4.336, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 11030, 'OPR': 23.229, 'Auto': 11.348, 'CCWM': 2.348, 'TeamName': 'Metal Jackets'}, {'TeamNum': 16012, 'OPR': 19.443, 'Auto': -1.722, 'CCWM': -74.048, 'TeamName': 'Blazing Bots'}, {'TeamNum': 22539, 'OPR': 18.71, 'Auto': -2.458, 'CCWM': 29.31, 'TeamName': 'Trial and Error'}, {'TeamNum': 4705, 'OPR': 17.971, 'Auto': 4.186, 'CCWM': -16.754, 'TeamName': 'Adamas Robotics'}, {'TeamNum': 20040, 'OPR': 17.579, 'Auto': -4.617, 'CCWM': 24.437, 'TeamName': 'Work In Progress'}, {'TeamNum': 9054, 'OPR': 16.503, 'Auto': 7.828, 'CCWM': -40.844, 'TeamName': 'Viridian Robotics'}, {'TeamNum': 6169, 'OPR': 16.438, 'Auto': -4.208, 'CCWM': -18.893, 'TeamName': 'System Surfers'}, {'TeamNum': 14445, 'OPR': 15.234, 'Auto': 3.767, 'CCWM': 0.282, 'TeamName': 'Poseidons'}, {'TeamNum': 18327, 'OPR': 9.311, 'Auto': 8.567, 'CCWM': -70.204, 'TeamName': 'Wheat Squad'}, {'TeamNum': 20039, 'OPR': 7.257, 'Auto': 0.817, 'CCWM': -18.704, 'TeamName': '1 Byte @-a-Time'}, {'TeamNum': 18310, 'OPR': 6.571, 'Auto': 1.217, 'CCWM': -36.899, 'TeamName': 'Smith Squad'}, {'TeamNum': 8291, 'OPR': 4.619, 'Auto': 2.292, 'CCWM': -48.98, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 13657, 'OPR': 2.475, 'Auto': 1.412, 'CCWM': -21.89, 'TeamName': 'Satellite Squad'}, {'TeamNum': 21921, 'OPR': 0.241, 'Auto': -2.208, 'CCWM': -71.281, 'TeamName': 'GEARS Buccaneers'}, {'TeamNum': 11978, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Ca1cu1at3d Chaos'}]
USTXNOBTLT
[{'TeamNum': 18227, 'OPR': 124.907, 'Auto': 28.647, 'CCWM': 86.312, 'TeamName': 'Area 52'}, {'TeamNum': 21330, 'OPR': 106.499, 'Auto': 27.561, 'CCWM': 94.266, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 18270, 'OPR': 97.987, 'Auto': 35.114, 'CCWM': 46.893, 'TeamName': 'RoboPlayers'}, {'TeamNum': 16412, 'OPR': 71.24, 'Auto': 17.505, 'CCWM': 47.293, 'TeamName': 'Triad Robotics'}, {'TeamNum': 13472, 'OPR': 69.826, 'Auto': 20.318, 'CCWM': 2.549, 'TeamName': 'The Dork Side'}, {'TeamNum': 20325, 'OPR': 67.993, 'Auto': 13.613, 'CCWM': 13.528, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 13811, 'OPR': 67.188, 'Auto': 15.681, 'CCWM': 17.013, 'TeamName': 'High Voltage'}, {'TeamNum': 16802, 'OPR': 64.528, 'Auto': 12.492, 'CCWM': 60.202, 'TeamName': 'Hollibots'}, {'TeamNum': 9045, 'OPR': 50.926, 'Auto': 16.473, 'CCWM': 32.065, 'TeamName': 'Motorhead'}, {'TeamNum': 21607, 'OPR': 50.788, 'Auto': 24.317, 'CCWM': -33.304, 'TeamName': 'Kcalians'}, {'TeamNum': 15226, 'OPR': 49.361, 'Auto': 6.883, 'CCWM': -2.589, 'TeamName': 'Salamancas'}, {'TeamNum': 20313, 'OPR': 48.885, 'Auto': 11.241, 'CCWM': 35.655, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 9161, 'OPR': 47.34, 'Auto': 12.838, 'CCWM': -24.381, 'TeamName': 'Overload'}, {'TeamNum': 20051, 'OPR': 42.518, 'Auto': 5.394, 'CCWM': 27.942, 'TeamName': 'Code Red'}, {'TeamNum': 17658, 'OPR': 42.191, 'Auto': 1.021, 'CCWM': 0.474, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 18072, 'OPR': 41.023, 'Auto': 16.273, 'CCWM': 0.763, 'TeamName': 'BCS Battery Acid'}, {'TeamNum': 21533, 'OPR': 27.596, 'Auto': 19.151, 'CCWM': 2.303, 'TeamName': 'Keller Fusion FTC'}, {'TeamNum': 4745, 'OPR': 25.717, 'Auto': -5.628, 'CCWM': -32.579, 'TeamName': 'Grand Tech Automation'}, {'TeamNum': 6566, 'OPR': 24.836, 'Auto': 5.328, 'CCWM': 4.336, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 11030, 'OPR': 23.229, 'Auto': 11.348, 'CCWM': 2.348, 'TeamName': 'Metal Jackets'}, {'TeamNum': 16012, 'OPR': 19.443, 'Auto': -1.722, 'CCWM': -74.048, 'TeamName': 'Blazing Bots'}, {'TeamNum': 22539, 'OPR': 18.71, 'Auto': -2.458, 'CCWM': 29.31, 'TeamName': 'Trial and Error'}, {'TeamNum': 4705, 'OPR': 17.971, 'Auto': 4.186, 'CCWM': -16.754, 'TeamName': 'Adamas Robotics'}, {'TeamNum': 20040, 'OPR': 17.579, 'Auto': -4.617, 'CCWM': 24.437, 'TeamName': 'Work In Progress'}, {'TeamNum': 9054, 'OPR': 16.503, 'Auto': 7.828, 'CCWM': -40.844, 'TeamName': 'Viridian Robotics'}, {'TeamNum': 6169, 'OPR': 16.438, 'Auto': -4.208, 'CCWM': -18.893, 'TeamName': 'System Surfers'}, {'TeamNum': 14445, 'OPR': 15.234, 'Auto': 3.767, 'CCWM': 0.282, 'TeamName': 'Poseidons'}, {'TeamNum': 18327, 'OPR': 9.311, 'Auto': 8.567, 'CCWM': -70.204, 'TeamName': 'Wheat Squad'}, {'TeamNum': 20039, 'OPR': 7.257, 'Auto': 0.817, 'CCWM': -18.704, 'TeamName': '1 Byte @-a-Time'}, {'TeamNum': 18310, 'OPR': 6.571, 'Auto': 1.217, 'CCWM': -36.899, 'TeamName': 'Smith Squad'}, {'TeamNum': 8291, 'OPR': 4.619, 'Auto': 2.292, 'CCWM': -48.98, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 13657, 'OPR': 2.475, 'Auto': 1.412, 'CCWM': -21.89, 'TeamName': 'Satellite Squad'}, {'TeamNum': 21921, 'OPR': 0.241, 'Auto': -2.208, 'CCWM': -71.281, 'TeamName': 'GEARS Buccaneers'}, {'TeamNum': 11978, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Ca1cu1at3d Chaos'}]

i 832
{'20249', '19947', '22895', '11947', '10055', '22236', '13822', '21386', '22045', '14503', '12456', '22717', '20394', '16685', '10354'}
[{'TeamNum': 14503, 'OPR': 93.46, 'Auto': 30.74, 'CCWM': 105.613, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 20394, 'OPR': 81.235, 'Auto': 19.227, 'CCWM': 57.017, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 10354, 'OPR': 71.246, 'Auto': 16.902, 'CCWM': 58.305, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 22236, 'OPR': 35.546, 'Auto': 11.279, 'CCWM': -0.887, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 13822, 'OPR': 35.027, 'Auto': 6.868, 'CCWM': 13.364, 'TeamName': 'RoboVikings'}, {'TeamNum': 16685, 'OPR': 32.249, 'Auto': 4.476, 'CCWM': 1.16, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 10055, 'OPR': 30.774, 'Auto': 0.7, 'CCWM': 7.592, 'TeamName': 'Momentum'}, {'TeamNum': 11947, 'OPR': 23.058, 'Auto': 7.672, 'CCWM': 3.249, 'TeamName': 'Stafford Middle School Spartan Robotics'}, {'TeamNum': 12456, 'OPR': 17.25, 'Auto': -1.796, 'CCWM': 12.154, 'TeamName': 'Big Red'}, {'TeamNum': 22045, 'OPR': 14.261, 'Auto': -2.137, 'CCWM': -37.801, 'TeamName': 'Power Breakers'}, {'TeamNum': 19947, 'OPR': 6.47, 'Auto': 7.449, 'CCWM': -34.086, 'TeamName': 'Nano Trojans'}, {'TeamNum': 20249, 'OPR': 4.934, 'Auto': 1.909, 'CCWM': -48.688, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 21386, 'OPR': 2.113, 'Auto': -5.255, 'CCWM': -43.83, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 22895, 'OPR': -2.063, 'Auto': 2.551, 'CCWM': -31.718, 'TeamName': 'RoboLions'}, {'TeamNum': 22717, 'OPR': -5.007, 'Auto': -7.631, 'CCWM': -72.846, 'TeamName': 'Robotic Radicals'}]
USTXHOSWM2
[{'TeamNum': 14503, 'OPR': 93.46, 'Auto': 30.74, 'CCWM': 105.613, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 20394, 'OPR': 81.235, 'Auto': 19.227, 'CCWM': 57.017, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 10354, 'OPR': 71.246, 'Auto': 16.902, 'CCWM': 58.305, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 22236, 'OPR': 35.546, 'Auto': 11.279, 'CCWM': -0.887, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 13822, 'OPR': 35.027, 'Auto': 6.868, 'CCWM': 13.364, 'TeamName': 'RoboVikings'}, {'TeamNum': 16685, 'OPR': 32.249, 'Auto': 4.476, 'CCWM': 1.16, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 10055, 'OPR': 30.774, 'Auto': 0.7, 'CCWM': 7.592, 'TeamName': 'Momentum'}, {'TeamNum': 11947, 'OPR': 23.058, 'Auto': 7.672, 'CCWM': 3.249, 'TeamName': 'Stafford Middle School Spartan Robotics'}, {'TeamNum': 12456, 'OPR': 17.25, 'Auto': -1.796, 'CCWM': 12.154, 'TeamName': 'Big Red'}, {'TeamNum': 22045, 'OPR': 14.261, 'Auto': -2.137, 'CCWM': -37.801, 'TeamName': 'Power Breakers'}, {'TeamNum': 19947, 'OPR': 6.47, 'Auto': 7.449, 'CCWM': -34.086, 'TeamName': 'Nano Trojans'}, {'TeamNum': 20249, 'OPR': 4.934, 'Auto': 1.909, 'CCWM': -48.688, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 21386, 'OPR': 2.113, 'Auto': -5.255, 'CCWM': -43.83, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 22895, 'OPR': -2.063, 'Auto': 2.551, 'CCWM': -31.718, 'TeamName': 'RoboLions'}, {'TeamNum': 22717, 'OPR': -5.007, 'Auto': -7.631, 'CCWM': -72.846, 'TeamName': 'Robotic Radicals'}]
i 833
{'17802', '11472', '15083', '11341', '18238', '12106', '12927', '14523', '18698', '21822', '11339', '20838', '13072', '9626', '17294', '12900', '21354', '21462', '21127', '22703', '22123', '12977', '8565', '18860', '15524', '14524', '15084', '10143', '16176', '17338', '11425', '12926', '16405', '22071', '20754', '7904'}
[{'TeamNum': 14524, 'OPR': 107.089, 'Auto': 27.499, 'CCWM': 67.138, 'TeamName': 'PESH Bots'}, {'TeamNum': 8565, 'OPR': 103.232, 'Auto': 35.07, 'CCWM': 39.437, 'TeamName': 'TechnicBots'}, {'TeamNum': 17294, 'OPR': 94.539, 'Auto': 26.503, 'CCWM': 26.388, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 14523, 'OPR': 88.062, 'Auto': 13.587, 'CCWM': 16.062, 'TeamName': 'Free of Charge'}, {'TeamNum': 12926, 'OPR': 87.526, 'Auto': 18.634, 'CCWM': 48.628, 'TeamName': 'Panther Robotics'}, {'TeamNum': 13072, 'OPR': 86.781, 'Auto': 22.138, 'CCWM': 26.304, 'TeamName': 'Fellowship of the Robot'}, {'TeamNum': 12977, 'OPR': 74.285, 'Auto': 26.252, 'CCWM': 24.801, 'TeamName': 'Rust In Peace'}, {'TeamNum': 21127, 'OPR': 72.343, 'Auto': 16.054, 'CCWM': 22.763, 'TeamName': 'Marvels of Irving'}, {'TeamNum': 12900, 'OPR': 64.215, 'Auto': 19.399, 'CCWM': 27.891, 'TeamName': 'Quantum Claw'}, {'TeamNum': 16176, 'OPR': 63.698, 'Auto': 7.862, 'CCWM': 32.741, 'TeamName': 'CDA Lions '}, {'TeamNum': 20838, 'OPR': 57.665, 'Auto': 11.521, 'CCWM': 3.113, 'TeamName': 'Tech No Logic'}, {'TeamNum': 17802, 'OPR': 56.637, 'Auto': 15.496, 'CCWM': 22.945, 'TeamName': 'Logic No Tech'}, {'TeamNum': 9626, 'OPR': 54.524, 'Auto': 3.555, 'CCWM': 19.741, 'TeamName': 'Hockabots'}, {'TeamNum': 15083, 'OPR': 48.711, 'Auto': 2.629, 'CCWM': 56.979, 'TeamName': 'Antagonists'}, {'TeamNum': 15524, 'OPR': 48.473, 'Auto': 20.567, 'CCWM': 1.666, 'TeamName': 'Cardinalbots'}, {'TeamNum': 21462, 'OPR': 45.382, 'Auto': 11.645, 'CCWM': -10.672, 'TeamName': 'Data Not Found'}, {'TeamNum': 11472, 'OPR': 42.066, 'Auto': 25.805, 'CCWM': -3.753, 'TeamName': 'RavenClaw Robotics'}, {'TeamNum': 11339, 'OPR': 40.43, 'Auto': -2.538, 'CCWM': 6.205, 'TeamName': 'Williams Warrior Robotics'}, {'TeamNum': 16405, 'OPR': 40.301, 'Auto': 19.585, 'CCWM': 11.931, 'TeamName': 'Federal Bot Institute'}, {'TeamNum': 15084, 'OPR': 39.175, 'Auto': 8.293, 'CCWM': -28.811, 'TeamName': 'Water Coolers'}, {'TeamNum': 17338, 'OPR': 29.318, 'Auto': 8.861, 'CCWM': -7.865, 'TeamName': 'Murphy Robotics-The Sequel'}, {'TeamNum': 12106, 'OPR': 28.293, 'Auto': 8.355, 'CCWM': -10.417, 'TeamName': 'Eagle Apollo'}, {'TeamNum': 21822, 'OPR': 26.366, 'Auto': 8.819, 'CCWM': -8.927, 'TeamName': ' Astro'}, {'TeamNum': 20754, 'OPR': 25.178, 'Auto': -1.405, 'CCWM': -36.343, 'TeamName': 'Hephaestus'}, {'TeamNum': 12927, 'OPR': 24.875, 'Auto': 7.65, 'CCWM': -53.166, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 22123, 'OPR': 22.223, 'Auto': 4.55, 'CCWM': 15.371, 'TeamName': 'Stallion Robotics'}, {'TeamNum': 18860, 'OPR': 21.096, 'Auto': 14.283, 'CCWM': -5.541, 'TeamName': 'RavenStorm Robotics'}, {'TeamNum': 21354, 'OPR': 19.999, 'Auto': 7.058, 'CCWM': -15.426, 'TeamName': 'EPIC Expedition'}, {'TeamNum': 10143, 'OPR': 19.2, 'Auto': 4.648, 'CCWM': -50.627, 'TeamName': 'Aero'}, {'TeamNum': 22703, 'OPR': 18.815, 'Auto': 15.156, 'CCWM': -29.616, 'TeamName': 'Tech Titans'}, {'TeamNum': 7904, 'OPR': 17.982, 'Auto': 5.112, 'CCWM': -6.456, 'TeamName': 'Robotigers'}, {'TeamNum': 18698, 'OPR': 16.451, 'Auto': 8.462, 'CCWM': -30.46, 'TeamName': 'Error 504'}, {'TeamNum': 11425, 'OPR': 15.401, 'Auto': -1.41, 'CCWM': -57.697, 'TeamName': 'Murphy Mavbots Robotics Team'}, {'TeamNum': 11341, 'OPR': 12.3, 'Auto': 7.677, 'CCWM': -71.853, 'TeamName': 'ViBøTs '}, {'TeamNum': 18238, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Frankford FTC Bots'}, {'TeamNum': 22071, 'OPR': -13.5, 'Auto': -8.582, 'CCWM': -47.027, 'TeamName': 'Technical Analysis'}]
USTXNOFMLT
[{'TeamNum': 14524, 'OPR': 107.089, 'Auto': 27.499, 'CCWM': 67.138, 'TeamName': 'PESH Bots'}, {'TeamNum': 8565, 'OPR': 103.232, 'Auto': 35.07, 'CCWM': 39.437, 'TeamName': 'TechnicBots'}, {'TeamNum': 17294, 'OPR': 94.539, 'Auto': 26.503, 'CCWM': 26.388, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 14523, 'OPR': 88.062, 'Auto': 13.587, 'CCWM': 16.062, 'TeamName': 'Free of Charge'}, {'TeamNum': 12926, 'OPR': 87.526, 'Auto': 18.634, 'CCWM': 48.628, 'TeamName': 'Panther Robotics'}, {'TeamNum': 13072, 'OPR': 86.781, 'Auto': 22.138, 'CCWM': 26.304, 'TeamName': 'Fellowship of the Robot'}, {'TeamNum': 12977, 'OPR': 74.285, 'Auto': 26.252, 'CCWM': 24.801, 'TeamName': 'Rust In Peace'}, {'TeamNum': 21127, 'OPR': 72.343, 'Auto': 16.054, 'CCWM': 22.763, 'TeamName': 'Marvels of Irving'}, {'TeamNum': 12900, 'OPR': 64.215, 'Auto': 19.399, 'CCWM': 27.891, 'TeamName': 'Quantum Claw'}, {'TeamNum': 16176, 'OPR': 63.698, 'Auto': 7.862, 'CCWM': 32.741, 'TeamName': 'CDA Lions '}, {'TeamNum': 20838, 'OPR': 57.665, 'Auto': 11.521, 'CCWM': 3.113, 'TeamName': 'Tech No Logic'}, {'TeamNum': 17802, 'OPR': 56.637, 'Auto': 15.496, 'CCWM': 22.945, 'TeamName': 'Logic No Tech'}, {'TeamNum': 9626, 'OPR': 54.524, 'Auto': 3.555, 'CCWM': 19.741, 'TeamName': 'Hockabots'}, {'TeamNum': 15083, 'OPR': 48.711, 'Auto': 2.629, 'CCWM': 56.979, 'TeamName': 'Antagonists'}, {'TeamNum': 15524, 'OPR': 48.473, 'Auto': 20.567, 'CCWM': 1.666, 'TeamName': 'Cardinalbots'}, {'TeamNum': 21462, 'OPR': 45.382, 'Auto': 11.645, 'CCWM': -10.672, 'TeamName': 'Data Not Found'}, {'TeamNum': 11472, 'OPR': 42.066, 'Auto': 25.805, 'CCWM': -3.753, 'TeamName': 'RavenClaw Robotics'}, {'TeamNum': 11339, 'OPR': 40.43, 'Auto': -2.538, 'CCWM': 6.205, 'TeamName': 'Williams Warrior Robotics'}, {'TeamNum': 16405, 'OPR': 40.301, 'Auto': 19.585, 'CCWM': 11.931, 'TeamName': 'Federal Bot Institute'}, {'TeamNum': 15084, 'OPR': 39.175, 'Auto': 8.293, 'CCWM': -28.811, 'TeamName': 'Water Coolers'}, {'TeamNum': 17338, 'OPR': 29.318, 'Auto': 8.861, 'CCWM': -7.865, 'TeamName': 'Murphy Robotics-The Sequel'}, {'TeamNum': 12106, 'OPR': 28.293, 'Auto': 8.355, 'CCWM': -10.417, 'TeamName': 'Eagle Apollo'}, {'TeamNum': 21822, 'OPR': 26.366, 'Auto': 8.819, 'CCWM': -8.927, 'TeamName': ' Astro'}, {'TeamNum': 20754, 'OPR': 25.178, 'Auto': -1.405, 'CCWM': -36.343, 'TeamName': 'Hephaestus'}, {'TeamNum': 12927, 'OPR': 24.875, 'Auto': 7.65, 'CCWM': -53.166, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 22123, 'OPR': 22.223, 'Auto': 4.55, 'CCWM': 15.371, 'TeamName': 'Stallion Robotics'}, {'TeamNum': 18860, 'OPR': 21.096, 'Auto': 14.283, 'CCWM': -5.541, 'TeamName': 'RavenStorm Robotics'}, {'TeamNum': 21354, 'OPR': 19.999, 'Auto': 7.058, 'CCWM': -15.426, 'TeamName': 'EPIC Expedition'}, {'TeamNum': 10143, 'OPR': 19.2, 'Auto': 4.648, 'CCWM': -50.627, 'TeamName': 'Aero'}, {'TeamNum': 22703, 'OPR': 18.815, 'Auto': 15.156, 'CCWM': -29.616, 'TeamName': 'Tech Titans'}, {'TeamNum': 7904, 'OPR': 17.982, 'Auto': 5.112, 'CCWM': -6.456, 'TeamName': 'Robotigers'}, {'TeamNum': 18698, 'OPR': 16.451, 'Auto': 8.462, 'CCWM': -30.46, 'TeamName': 'Error 504'}, {'TeamNum': 11425, 'OPR': 15.401, 'Auto': -1.41, 'CCWM': -57.697, 'TeamName': 'Murphy Mavbots Robotics Team'}, {'TeamNum': 11341, 'OPR': 12.3, 'Auto': 7.677, 'CCWM': -71.853, 'TeamName': 'ViBøTs '}, {'TeamNum': 18238, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Frankford FTC Bots'}, {'TeamNum': 22071, 'OPR': -13.5, 'Auto': -8.582, 'CCWM': -47.027, 'TeamName': 'Technical Analysis'}]

i 834
{'10971', '20741', '6221', '15703', '4416', '21346', '7615', '13670', '21321', '22371', '10902', '19918', '15024', '4602', '4008', '18094', '21233', '12798', '20316', '13388', '16458', '22857', '6976', '10518', '6407', '16320', '8295', '22370', '18519', '10973', '3296', '22185', '20739'}
[{'TeamNum': 16458, 'OPR': 142.771, 'Auto': 44.9, 'CCWM': 124.107, 'TeamName': 'TechnoWizards'}, {'TeamNum': 15703, 'OPR': 86.527, 'Auto': 15.901, 'CCWM': 69.008, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 15024, 'OPR': 58.422, 'Auto': 14.267, 'CCWM': 15.074, 'TeamName': 'Cougarbots Bravo'}, {'TeamNum': 20739, 'OPR': 53.956, 'Auto': 10.56, 'CCWM': 18.065, 'TeamName': 'Coding Chaos'}, {'TeamNum': 20741, 'OPR': 44.602, 'Auto': 8.727, 'CCWM': 16.467, 'TeamName': 'Checkmate'}, {'TeamNum': 13670, 'OPR': 44.278, 'Auto': 2.494, 'CCWM': 27.818, 'TeamName': 'Barons Builders'}, {'TeamNum': 10902, 'OPR': 43.113, 'Auto': 12.126, 'CCWM': 5.787, 'TeamName': 'Techno Pirates'}, {'TeamNum': 21346, 'OPR': 42.61, 'Auto': 3.035, 'CCWM': 25.169, 'TeamName': 'BASIS Some Assembly Required'}, {'TeamNum': 20316, 'OPR': 39.318, 'Auto': 5.022, 'CCWM': 1.805, 'TeamName': 'Crimson Comets'}, {'TeamNum': 21233, 'OPR': 38.57, 'Auto': 13.73, 'CCWM': 16.173, 'TeamName': 'Tech Syndicate'}, {'TeamNum': 7615, 'OPR': 37.98, 'Auto': 1.493, 'CCWM': -0.846, 'TeamName': 'Mechanical Mustangs Affirmed'}, {'TeamNum': 4008, 'OPR': 32.821, 'Auto': 4.443, 'CCWM': 6.314, 'TeamName': 'Bronc Botz - Atlas'}, {'TeamNum': 6221, 'OPR': 31.265, 'Auto': 8.977, 'CCWM': -0.098, 'TeamName': 'Panther Bots Alpha'}, {'TeamNum': 10518, 'OPR': 30.525, 'Auto': 12.147, 'CCWM': -7.312, 'TeamName': 'Cougarbots Alpha'}, {'TeamNum': 21321, 'OPR': 29.941, 'Auto': 9.401, 'CCWM': -13.875, 'TeamName': 'Mechanical Mustangs Justify'}, {'TeamNum': 12798, 'OPR': 28.736, 'Auto': 1.387, 'CCWM': -11.22, 'TeamName': 'Gateway Robotics'}, {'TeamNum': 6407, 'OPR': 28.586, 'Auto': -2.319, 'CCWM': -7.023, 'TeamName': 'Mechanical Mustangs Secretariat'}, {'TeamNum': 22185, 'OPR': 26.737, 'Auto': 6.779, 'CCWM': -33.538, 'TeamName': 'Mecha Bots'}, {'TeamNum': 22370, 'OPR': 25.856, 'Auto': -1.55, 'CCWM': 4.232, 'TeamName': 'The Seths'}, {'TeamNum': 18519, 'OPR': 25.227, 'Auto': 11.366, 'CCWM': 4.305, 'TeamName': 'Team Marvel-us'}, {'TeamNum': 10971, 'OPR': 22.775, 'Auto': 2.39, 'CCWM': -39.74, 'TeamName': 'Somerset Bulldogs 2'}, {'TeamNum': 18094, 'OPR': 19.803, 'Auto': 0.972, 'CCWM': 6.018, 'TeamName': 'BASIS Batteries Not Included'}, {'TeamNum': 8295, 'OPR': 19.179, 'Auto': 4.412, 'CCWM': 17.653, 'TeamName': 'Baron Alpha'}, {'TeamNum': 16320, 'OPR': 18.011, 'Auto': 1.561, 'CCWM': -6.233, 'TeamName': 'Gilded Gears'}, {'TeamNum': 13388, 'OPR': 16.937, 'Auto': 5.044, 'CCWM': -21.638, 'TeamName': 'Warrior Warheads'}, {'TeamNum': 22371, 'OPR': 16.262, 'Auto': -1.179, 'CCWM': -38.185, 'TeamName': 'Alphabots'}, {'TeamNum': 6976, 'OPR': 13.095, 'Auto': 11.273, 'CCWM': -2.898, 'TeamName': 'Bronc Botz '}, {'TeamNum': 19918, 'OPR': 9.943, 'Auto': 1.985, 'CCWM': -9.353, 'TeamName': 'Robo-Eagles'}, {'TeamNum': 10973, 'OPR': 9.77, 'Auto': 3.198, 'CCWM': -52.859, 'TeamName': 'Somerset Bulldogs 1'}, {'TeamNum': 22857, 'OPR': 6.834, 'Auto': -2.841, 'CCWM': -20.095, 'TeamName': 'Mechanical Mustangs Citation'}, {'TeamNum': 4416, 'OPR': 3.767, 'Auto': 1.727, 'CCWM': -26.316, 'TeamName': 'Steel Stallions'}, {'TeamNum': 3296, 'OPR': -0.758, 'Auto': -2.865, 'CCWM': -20.483, 'TeamName': 'Bots in Blue'}, {'TeamNum': 4602, 'OPR': -5.122, 'Auto': -10.753, 'CCWM': -35.575, 'TeamName': 'Bronc Botz - Prometheus'}]
USTXCENSALT
[{'TeamNum': 16458, 'OPR': 142.771, 'Auto': 44.9, 'CCWM': 124.107, 'TeamName': 'TechnoWizards'}, {'TeamNum': 15703, 'OPR': 86.527, 'Auto': 15.901, 'CCWM': 69.008, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 15024, 'OPR': 58.422, 'Auto': 14.267, 'CCWM': 15.074, 'TeamName': 'Cougarbots Bravo'}, {'TeamNum': 20739, 'OPR': 53.956, 'Auto': 10.56, 'CCWM': 18.065, 'TeamName': 'Coding Chaos'}, {'TeamNum': 20741, 'OPR': 44.602, 'Auto': 8.727, 'CCWM': 16.467, 'TeamName': 'Checkmate'}, {'TeamNum': 13670, 'OPR': 44.278, 'Auto': 2.494, 'CCWM': 27.818, 'TeamName': 'Barons Builders'}, {'TeamNum': 10902, 'OPR': 43.113, 'Auto': 12.126, 'CCWM': 5.787, 'TeamName': 'Techno Pirates'}, {'TeamNum': 21346, 'OPR': 42.61, 'Auto': 3.035, 'CCWM': 25.169, 'TeamName': 'BASIS Some Assembly Required'}, {'TeamNum': 20316, 'OPR': 39.318, 'Auto': 5.022, 'CCWM': 1.805, 'TeamName': 'Crimson Comets'}, {'TeamNum': 21233, 'OPR': 38.57, 'Auto': 13.73, 'CCWM': 16.173, 'TeamName': 'Tech Syndicate'}, {'TeamNum': 7615, 'OPR': 37.98, 'Auto': 1.493, 'CCWM': -0.846, 'TeamName': 'Mechanical Mustangs Affirmed'}, {'TeamNum': 4008, 'OPR': 32.821, 'Auto': 4.443, 'CCWM': 6.314, 'TeamName': 'Bronc Botz - Atlas'}, {'TeamNum': 6221, 'OPR': 31.265, 'Auto': 8.977, 'CCWM': -0.098, 'TeamName': 'Panther Bots Alpha'}, {'TeamNum': 10518, 'OPR': 30.525, 'Auto': 12.147, 'CCWM': -7.312, 'TeamName': 'Cougarbots Alpha'}, {'TeamNum': 21321, 'OPR': 29.941, 'Auto': 9.401, 'CCWM': -13.875, 'TeamName': 'Mechanical Mustangs Justify'}, {'TeamNum': 12798, 'OPR': 28.736, 'Auto': 1.387, 'CCWM': -11.22, 'TeamName': 'Gateway Robotics'}, {'TeamNum': 6407, 'OPR': 28.586, 'Auto': -2.319, 'CCWM': -7.023, 'TeamName': 'Mechanical Mustangs Secretariat'}, {'TeamNum': 22185, 'OPR': 26.737, 'Auto': 6.779, 'CCWM': -33.538, 'TeamName': 'Mecha Bots'}, {'TeamNum': 22370, 'OPR': 25.856, 'Auto': -1.55, 'CCWM': 4.232, 'TeamName': 'The Seths'}, {'TeamNum': 18519, 'OPR': 25.227, 'Auto': 11.366, 'CCWM': 4.305, 'TeamName': 'Team Marvel-us'}, {'TeamNum': 10971, 'OPR': 22.775, 'Auto': 2.39, 'CCWM': -39.74, 'TeamName': 'Somerset Bulldogs 2'}, {'TeamNum': 18094, 'OPR': 19.803, 'Auto': 0.972, 'CCWM': 6.018, 'TeamName': 'BASIS Batteries Not Included'}, {'TeamNum': 8295, 'OPR': 19.179, 'Auto': 4.412, 'CCWM': 17.653, 'TeamName': 'Baron Alpha'}, {'TeamNum': 16320, 'OPR': 18.011, 'Auto': 1.561, 'CCWM': -6.233, 'TeamName': 'Gilded Gears'}, {'TeamNum': 13388, 'OPR': 16.937, 'Auto': 5.044, 'CCWM': -21.638, 'TeamName': 'Warrior Warheads'}, {'TeamNum': 22371, 'OPR': 16.262, 'Auto': -1.179, 'CCWM': -38.185, 'TeamName': 'Alphabots'}, {'TeamNum': 6976, 'OPR': 13.095, 'Auto': 11.273, 'CCWM': -2.898, 'TeamName': 'Bronc Botz '}, {'TeamNum': 19918, 'OPR': 9.943, 'Auto': 1.985, 'CCWM': -9.353, 'TeamName': 'Robo-Eagles'}, {'TeamNum': 10973, 'OPR': 9.77, 'Auto': 3.198, 'CCWM': -52.859, 'TeamName': 'Somerset Bulldogs 1'}, {'TeamNum': 22857, 'OPR': 6.834, 'Auto': -2.841, 'CCWM': -20.095, 'TeamName': 'Mechanical Mustangs Citation'}, {'TeamNum': 4416, 'OPR': 3.767, 'Auto': 1.727, 'CCWM': -26.316, 'TeamName': 'Steel Stallions'}, {'TeamNum': 3296, 'OPR': -0.758, 'Auto': -2.865, 'CCWM': -20.483, 'TeamName': 'Bots in Blue'}, {'TeamNum': 4602, 'OPR': -5.122, 'Auto': -10.753, 'CCWM': -35.575, 'TeamName': 'Bronc Botz - Prometheus'}]
i 835
{'20764', '8406', '20347', '9010', '20410', '22191', '3734', '6832', '15373', '8626', '10437', '17499', '21963', '22344', '14904', '14962', '11676'}
[{'TeamNum': 8406, 'OPR': 51.016, 'Auto': 11.87, 'CCWM': 34.696, 'TeamName': 'The Horde'}, {'TeamNum': 20410, 'OPR': 47.724, 'Auto': 2.983, 'CCWM': 11.868, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 6832, 'OPR': 39.816, 'Auto': 13.32, 'CCWM': 16.88, 'TeamName': 'Iron Reign'}, {'TeamNum': 22191, 'OPR': 39.483, 'Auto': 5.373, 'CCWM': 26.399, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 11676, 'OPR': 37.353, 'Auto': 4.053, 'CCWM': 6.695, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 14962, 'OPR': 31.077, 'Auto': 0.264, 'CCWM': 8.437, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 20347, 'OPR': 30.034, 'Auto': -3.843, 'CCWM': 12.996, 'TeamName': '[INSERT_NAME_HERE]'}, {'TeamNum': 10437, 'OPR': 29.223, 'Auto': 3.191, 'CCWM': -19.191, 'TeamName': 'The Rusty Nuts'}, {'TeamNum': 15373, 'OPR': 25.306, 'Auto': 3.914, 'CCWM': -1.288, 'TeamName': 'Iron Core'}, {'TeamNum': 9010, 'OPR': 19.707, 'Auto': -2.444, 'CCWM': -12.053, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 21963, 'OPR': 19.16, 'Auto': 4.402, 'CCWM': -6.327, 'TeamName': 'The Multiversal Coders'}, {'TeamNum': 8626, 'OPR': 12.906, 'Auto': 7.23, 'CCWM': -12.282, 'TeamName': 'ProtoSurge'}, {'TeamNum': 3734, 'OPR': 12.725, 'Auto': -0.311, 'CCWM': 8.354, 'TeamName': 'Iron Giant'}, {'TeamNum': 22344, 'OPR': 10.141, 'Auto': -1.275, 'CCWM': -19.232, 'TeamName': 'Newman Gibbins 2'}, {'TeamNum': 14904, 'OPR': 3.686, 'Auto': 1.329, 'CCWM': -38.982, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 20764, 'OPR': 2.618, 'Auto': -4.97, 'CCWM': 2.23, 'TeamName': 'UltraBots'}, {'TeamNum': 17499, 'OPR': 1.661, 'Auto': 0.202, 'CCWM': -23.929, 'TeamName': 'Athena Circuit Breakers'}]
USTXNOULM3
[{'TeamNum': 8406, 'OPR': 51.016, 'Auto': 11.87, 'CCWM': 34.696, 'TeamName': 'The Horde'}, {'TeamNum': 20410, 'OPR': 47.724, 'Auto': 2.983, 'CCWM': 11.868, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 6832, 'OPR': 39.816, 'Auto': 13.32, 'CCWM': 16.88, 'TeamName': 'Iron Reign'}, {'TeamNum': 22191, 'OPR': 39.483, 'Auto': 5.373, 'CCWM': 26.399, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 11676, 'OPR': 37.353, 'Auto': 4.053, 'CCWM': 6.695, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 14962, 'OPR': 31.077, 'Auto': 0.264, 'CCWM': 8.437, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 20347, 'OPR': 30.034, 'Auto': -3.843, 'CCWM': 12.996, 'TeamName': '[INSERT_NAME_HERE]'}, {'TeamNum': 10437, 'OPR': 29.223, 'Auto': 3.191, 'CCWM': -19.191, 'TeamName': 'The Rusty Nuts'}, {'TeamNum': 15373, 'OPR': 25.306, 'Auto': 3.914, 'CCWM': -1.288, 'TeamName': 'Iron Core'}, {'TeamNum': 9010, 'OPR': 19.707, 'Auto': -2.444, 'CCWM': -12.053, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 21963, 'OPR': 19.16, 'Auto': 4.402, 'CCWM': -6.327, 'TeamName': 'The Multiversal Coders'}, {'TeamNum': 8626, 'OPR': 12.906, 'Auto': 7.23, 'CCWM': -12.282, 'TeamName': 'ProtoSurge'}, {'TeamNum': 3734, 'OPR': 12.725, 'Auto': -0.311, 'CCWM': 8.354, 'TeamName': 'Iron Giant'}, {'TeamNum': 22344, 'OPR': 10.141, 'Auto': -1.275, 'CCWM': -19.232, 'TeamName': 'Newman Gibbins 2'}, {'TeamNum': 14904, 'OPR': 3.686, 'Auto': 1.329, 'CCWM': -38.982, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 20764, 'OPR': 2.618, 'Auto': -4.97, 'CCWM': 2.23, 'TeamName': 'UltraBots'}, {'TeamNum': 17499, 'OPR': 1.661, 'Auto': 0.202, 'CCWM': -23.929, 'TeamName': 'Athena Circuit Breakers'}]

i 836
{'14762', '13073', '10095', '22614', '7788', '10802', '18515', '19420', '22495', '16840', '17320', '19398', '4641'}
[{'TeamNum': 10095, 'OPR': 56.287, 'Auto': 7.674, 'CCWM': 41.037, 'TeamName': 'Revelation'}, {'TeamNum': 4641, 'OPR': 35.633, 'Auto': 10.093, 'CCWM': 23.927, 'TeamName': 'RoboSharks'}, {'TeamNum': 13073, 'OPR': 31.476, 'Auto': 3.974, 'CCWM': -10.972, 'TeamName': 'Texas Toast'}, {'TeamNum': 10802, 'OPR': 30.638, 'Auto': 3.089, 'CCWM': 1.965, 'TeamName': 'Brazosport Robotics Red'}, {'TeamNum': 22495, 'OPR': 26.65, 'Auto': 3.086, 'CCWM': 20.611, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 19398, 'OPR': 26.59, 'Auto': 4.351, 'CCWM': -8.473, 'TeamName': 'Genesis'}, {'TeamNum': 7788, 'OPR': 23.023, 'Auto': 2.643, 'CCWM': 2.27, 'TeamName': 'Travis Fiddlerbots'}, {'TeamNum': 16840, 'OPR': 16.864, 'Auto': 2.756, 'CCWM': -3.621, 'TeamName': 'Brazosport Robotics Blue'}, {'TeamNum': 22614, 'OPR': 15.987, 'Auto': 3.396, 'CCWM': 1.879, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 18515, 'OPR': 15.569, 'Auto': -0.957, 'CCWM': -6.468, 'TeamName': 'Junior Sharks 1'}, {'TeamNum': 14762, 'OPR': 14.779, 'Auto': -2.161, 'CCWM': 3.941, 'TeamName': 'Robo Panthers'}, {'TeamNum': 17320, 'OPR': 3.94, 'Auto': 2.409, 'CCWM': -24.707, 'TeamName': 'Clute Robotics: Aries'}, {'TeamNum': 19420, 'OPR': 0.774, 'Auto': 3.557, 'CCWM': -37.279, 'TeamName': 'BAYRAT TECHB0TZ'}]
USTXHOSLM3
[{'TeamNum': 10095, 'OPR': 56.287, 'Auto': 7.674, 'CCWM': 41.037, 'TeamName': 'Revelation'}, {'TeamNum': 4641, 'OPR': 35.633, 'Auto': 10.093, 'CCWM': 23.927, 'TeamName': 'RoboSharks'}, {'TeamNum': 13073, 'OPR': 31.476, 'Auto': 3.974, 'CCWM': -10.972, 'TeamName': 'Texas Toast'}, {'TeamNum': 10802, 'OPR': 30.638, 'Auto': 3.089, 'CCWM': 1.965, 'TeamName': 'Brazosport Robotics Red'}, {'TeamNum': 22495, 'OPR': 26.65, 'Auto': 3.086, 'CCWM': 20.611, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 19398, 'OPR': 26.59, 'Auto': 4.351, 'CCWM': -8.473, 'TeamName': 'Genesis'}, {'TeamNum': 7788, 'OPR': 23.023, 'Auto': 2.643, 'CCWM': 2.27, 'TeamName': 'Travis Fiddlerbots'}, {'TeamNum': 16840, 'OPR': 16.864, 'Auto': 2.756, 'CCWM': -3.621, 'TeamName': 'Brazosport Robotics Blue'}, {'TeamNum': 22614, 'OPR': 15.987, 'Auto': 3.396, 'CCWM': 1.879, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 18515, 'OPR': 15.569, 'Auto': -0.957, 'CCWM': -6.468, 'TeamName': 'Junior Sharks 1'}, {'TeamNum': 14762, 'OPR': 14.779, 'Auto': -2.161, 'CCWM': 3.941, 'TeamName': 'Robo Panthers'}, {'TeamNum': 17320, 'OPR': 3.94, 'Auto': 2.409, 'CCWM': -24.707, 'TeamName': 'Clute Robotics: Aries'}, {'TeamNum': 19420, 'OPR': 0.774, 'Auto': 3.557, 'CCWM': -37.279, 'TeamName': 'BAYRAT TECHB0TZ'}]
i 837
{'13466', '12973', '12597', '4798', '4707', '5683', '4812', '21375', '21899', '8203', '9377', '13053'}
[{'TeamNum': 4707, 'OPR': 89.368, 'Auto': 23.502, 'CCWM': 58.328, 'TeamName': 'Midway Predators'}, {'TeamNum': 13053, 'OPR': 88.017, 'Auto': 18.158, 'CCWM': 79.494, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 12973, 'OPR': 82.69, 'Auto': 17.836, 'CCWM': 37.9, 'TeamName': 'Reicher Robotics'}, {'TeamNum': 12597, 'OPR': 70.603, 'Auto': 18.894, 'CCWM': 36.861, 'TeamName': 'RAGNAROK ROBOTICS'}, {'TeamNum': 21375, 'OPR': 37.606, 'Auto': 13.659, 'CCWM': -27.884, 'TeamName': 'YGGDRASIL ROBOTICS'}, {'TeamNum': 21899, 'OPR': 34.803, 'Auto': 5.064, 'CCWM': -26.659, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 5683, 'OPR': 31.5, 'Auto': 9.361, 'CCWM': -29.298, 'TeamName': 'Midway Robotics'}, {'TeamNum': 13466, 'OPR': 26.607, 'Auto': 12.316, 'CCWM': -36.077, 'TeamName': 'Gwama Robotics'}, {'TeamNum': 8203, 'OPR': 24.641, 'Auto': 10.389, 'CCWM': -8.7, 'TeamName': "Lil' Gibbies"}, {'TeamNum': 9377, 'OPR': 23.493, 'Auto': 6.344, 'CCWM': -26.151, 'TeamName': 'ROBUFFS Yellow Submarine 9377'}, {'TeamNum': 4812, 'OPR': 17.431, 'Auto': -3.729, 'CCWM': -16.566, 'TeamName': 'ROBUFFS Rangers 4812'}, {'TeamNum': 4798, 'OPR': 9.241, 'Auto': 0.607, 'CCWM': -41.248, 'TeamName': 'ROBUFFS Dough Boys 4798'}]
USTXCEWALT
[{'TeamNum': 4707, 'OPR': 89.368, 'Auto': 23.502, 'CCWM': 58.328, 'TeamName': 'Midway Predators'}, {'TeamNum': 13053, 'OPR': 88.017, 'Auto': 18.158, 'CCWM': 79.494, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 12973, 'OPR': 82.69, 'Auto': 17.836, 'CCWM': 37.9, 'TeamName': 'Reicher Robotics'}, {'TeamNum': 12597, 'OPR': 70.603, 'Auto': 18.894, 'CCWM': 36.861, 'TeamName': 'RAGNAROK ROBOTICS'}, {'TeamNum': 21375, 'OPR': 37.606, 'Auto': 13.659, 'CCWM': -27.884, 'TeamName': 'YGGDRASIL ROBOTICS'}, {'TeamNum': 21899, 'OPR': 34.803, 'Auto': 5.064, 'CCWM': -26.659, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 5683, 'OPR': 31.5, 'Auto': 9.361, 'CCWM': -29.298, 'TeamName': 'Midway Robotics'}, {'TeamNum': 13466, 'OPR': 26.607, 'Auto': 12.316, 'CCWM': -36.077, 'TeamName': 'Gwama Robotics'}, {'TeamNum': 8203, 'OPR': 24.641, 'Auto': 10.389, 'CCWM': -8.7, 'TeamName': "Lil' Gibbies"}, {'TeamNum': 9377, 'OPR': 23.493, 'Auto': 6.344, 'CCWM': -26.151, 'TeamName': 'ROBUFFS Yellow Submarine 9377'}, {'TeamNum': 4812, 'OPR': 17.431, 'Auto': -3.729, 'CCWM': -16.566, 'TeamName': 'ROBUFFS Rangers 4812'}, {'TeamNum': 4798, 'OPR': 9.241, 'Auto': 0.607, 'CCWM': -41.248, 'TeamName': 'ROBUFFS Dough Boys 4798'}]
i 838
{'10528', '13263', '21898', '20238', '21714', '4906', '20109', '9735', '4897', '10860', '13805', '9362', '21713', '22856', '15491', '19801', '16867', '21711', '11902', '17481', '9381', '17480', '13249', '17307', '11004', '17306', '14952', '4885', '10861', '17304', '22014', '14905', '14145', '4886', '10529', '15493'}
[{'TeamNum': 4906, 'OPR': 82.473, 'Auto': 19.333, 'CCWM': 64.618, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 4886, 'OPR': 68.86, 'Auto': 12.662, 'CCWM': 58.379, 'TeamName': 'Robo Junkies'}, {'TeamNum': 15491, 'OPR': 52.665, 'Auto': 21.416, 'CCWM': 14.229, 'TeamName': 'Venom Robotics'}, {'TeamNum': 11004, 'OPR': 52.261, 'Auto': 16.889, 'CCWM': 58.374, 'TeamName': 'Cantina Crew'}, {'TeamNum': 21711, 'OPR': 43.297, 'Auto': 3.702, 'CCWM': 23.603, 'TeamName': 'The McQueens'}, {'TeamNum': 9362, 'OPR': 42.54, 'Auto': -0.293, 'CCWM': 50.285, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 13805, 'OPR': 42.014, 'Auto': 10.611, 'CCWM': 1.625, 'TeamName': 'Robotic Chaos'}, {'TeamNum': 15493, 'OPR': 38.706, 'Auto': 24.615, 'CCWM': 12.317, 'TeamName': 'The Misfits'}, {'TeamNum': 10861, 'OPR': 34.983, 'Auto': 19.443, 'CCWM': -28.244, 'TeamName': 'Stumble Bots'}, {'TeamNum': 4885, 'OPR': 33.552, 'Auto': 10.116, 'CCWM': -24.523, 'TeamName': 'OmegaBotz'}, {'TeamNum': 17304, 'OPR': 31.949, 'Auto': 13.182, 'CCWM': 12.491, 'TeamName': 'A Perfect Remix'}, {'TeamNum': 13263, 'OPR': 31.347, 'Auto': 0.578, 'CCWM': 17.235, 'TeamName': 'Wyld Stallyns'}, {'TeamNum': 11902, 'OPR': 29.031, 'Auto': 0.687, 'CCWM': 8.211, 'TeamName': 'KillSwitch Robotics'}, {'TeamNum': 21898, 'OPR': 26.611, 'Auto': 4.587, 'CCWM': 11.464, 'TeamName': 'Braves'}, {'TeamNum': 10528, 'OPR': 26.195, 'Auto': 3.046, 'CCWM': 17.271, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 10860, 'OPR': 25.155, 'Auto': 13.58, 'CCWM': 1.176, 'TeamName': 'Squid Gear'}, {'TeamNum': 21713, 'OPR': 24.71, 'Auto': 2.683, 'CCWM': -5.721, 'TeamName': 'Nova Edge'}, {'TeamNum': 17480, 'OPR': 23.803, 'Auto': 7.678, 'CCWM': 11.284, 'TeamName': 'CIA - Cats In Action'}, {'TeamNum': 16867, 'OPR': 22.812, 'Auto': -1.427, 'CCWM': -16.226, 'TeamName': 'Trinity Chargers'}, {'TeamNum': 22014, 'OPR': 19.955, 'Auto': 13.132, 'CCWM': -19.131, 'TeamName': 'Lions'}, {'TeamNum': 13249, 'OPR': 19.763, 'Auto': 8.904, 'CCWM': 13.22, 'TeamName': 'Nova Robotics'}, {'TeamNum': 9381, 'OPR': 19.639, 'Auto': 3.946, 'CCWM': 1.462, 'TeamName': 'Hot Bots '}, {'TeamNum': 19801, 'OPR': 18.116, 'Auto': 2.287, 'CCWM': -16.143, 'TeamName': 'Rogue Robotics'}, {'TeamNum': 10529, 'OPR': 17.96, 'Auto': 5.115, 'CCWM': -43.103, 'TeamName': 'DinoBots'}, {'TeamNum': 14905, 'OPR': 10.677, 'Auto': -2.311, 'CCWM': -26.95, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 21714, 'OPR': 10.535, 'Auto': -3.658, 'CCWM': -2.946, 'TeamName': 'Revolting'}, {'TeamNum': 20238, 'OPR': 9.23, 'Auto': 5.365, 'CCWM': -18.588, 'TeamName': 'Rapture Raptors'}, {'TeamNum': 20109, 'OPR': 8.283, 'Auto': -0.47, 'CCWM': -31.494, 'TeamName': 'Iron Lions'}, {'TeamNum': 14952, 'OPR': 7.196, 'Auto': -1.019, 'CCWM': -1.23, 'TeamName': 'Beskar Bots'}, {'TeamNum': 17481, 'OPR': 5.646, 'Auto': -1.017, 'CCWM': -5.461, 'TeamName': 'Talk Nerdy to Me'}, {'TeamNum': 9735, 'OPR': 4.459, 'Auto': 2.764, 'CCWM': -21.406, 'TeamName': 'Canis Major'}, {'TeamNum': 14145, 'OPR': 4.269, 'Auto': 0.284, 'CCWM': -30.78, 'TeamName': 'Lions'}, {'TeamNum': 22856, 'OPR': 4.21, 'Auto': -5.604, 'CCWM': -7.481, 'TeamName': 'Bots That Knock'}, {'TeamNum': 17307, 'OPR': 2.003, 'Auto': -7.166, 'CCWM': -27.112, 'TeamName': 'The Magnificent Seven'}, {'TeamNum': 17306, 'OPR': -0.81, 'Auto': 1.169, 'CCWM': -22.391, 'TeamName': 'Humble Motiv8ors'}, {'TeamNum': 4897, 'OPR': -2.094, 'Auto': -1.609, 'CCWM': -28.312, 'TeamName': 'Bodacious Bulldawgs'}]
USTXWPMDM3
[{'TeamNum': 4906, 'OPR': 82.473, 'Auto': 19.333, 'CCWM': 64.618, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 4886, 'OPR': 68.86, 'Auto': 12.662, 'CCWM': 58.379, 'TeamName': 'Robo Junkies'}, {'TeamNum': 15491, 'OPR': 52.665, 'Auto': 21.416, 'CCWM': 14.229, 'TeamName': 'Venom Robotics'}, {'TeamNum': 11004, 'OPR': 52.261, 'Auto': 16.889, 'CCWM': 58.374, 'TeamName': 'Cantina Crew'}, {'TeamNum': 21711, 'OPR': 43.297, 'Auto': 3.702, 'CCWM': 23.603, 'TeamName': 'The McQueens'}, {'TeamNum': 9362, 'OPR': 42.54, 'Auto': -0.293, 'CCWM': 50.285, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 13805, 'OPR': 42.014, 'Auto': 10.611, 'CCWM': 1.625, 'TeamName': 'Robotic Chaos'}, {'TeamNum': 15493, 'OPR': 38.706, 'Auto': 24.615, 'CCWM': 12.317, 'TeamName': 'The Misfits'}, {'TeamNum': 10861, 'OPR': 34.983, 'Auto': 19.443, 'CCWM': -28.244, 'TeamName': 'Stumble Bots'}, {'TeamNum': 4885, 'OPR': 33.552, 'Auto': 10.116, 'CCWM': -24.523, 'TeamName': 'OmegaBotz'}, {'TeamNum': 17304, 'OPR': 31.949, 'Auto': 13.182, 'CCWM': 12.491, 'TeamName': 'A Perfect Remix'}, {'TeamNum': 13263, 'OPR': 31.347, 'Auto': 0.578, 'CCWM': 17.235, 'TeamName': 'Wyld Stallyns'}, {'TeamNum': 11902, 'OPR': 29.031, 'Auto': 0.687, 'CCWM': 8.211, 'TeamName': 'KillSwitch Robotics'}, {'TeamNum': 21898, 'OPR': 26.611, 'Auto': 4.587, 'CCWM': 11.464, 'TeamName': 'Braves'}, {'TeamNum': 10528, 'OPR': 26.195, 'Auto': 3.046, 'CCWM': 17.271, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 10860, 'OPR': 25.155, 'Auto': 13.58, 'CCWM': 1.176, 'TeamName': 'Squid Gear'}, {'TeamNum': 21713, 'OPR': 24.71, 'Auto': 2.683, 'CCWM': -5.721, 'TeamName': 'Nova Edge'}, {'TeamNum': 17480, 'OPR': 23.803, 'Auto': 7.678, 'CCWM': 11.284, 'TeamName': 'CIA - Cats In Action'}, {'TeamNum': 16867, 'OPR': 22.812, 'Auto': -1.427, 'CCWM': -16.226, 'TeamName': 'Trinity Chargers'}, {'TeamNum': 22014, 'OPR': 19.955, 'Auto': 13.132, 'CCWM': -19.131, 'TeamName': 'Lions'}, {'TeamNum': 13249, 'OPR': 19.763, 'Auto': 8.904, 'CCWM': 13.22, 'TeamName': 'Nova Robotics'}, {'TeamNum': 9381, 'OPR': 19.639, 'Auto': 3.946, 'CCWM': 1.462, 'TeamName': 'Hot Bots '}, {'TeamNum': 19801, 'OPR': 18.116, 'Auto': 2.287, 'CCWM': -16.143, 'TeamName': 'Rogue Robotics'}, {'TeamNum': 10529, 'OPR': 17.96, 'Auto': 5.115, 'CCWM': -43.103, 'TeamName': 'DinoBots'}, {'TeamNum': 14905, 'OPR': 10.677, 'Auto': -2.311, 'CCWM': -26.95, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 21714, 'OPR': 10.535, 'Auto': -3.658, 'CCWM': -2.946, 'TeamName': 'Revolting'}, {'TeamNum': 20238, 'OPR': 9.23, 'Auto': 5.365, 'CCWM': -18.588, 'TeamName': 'Rapture Raptors'}, {'TeamNum': 20109, 'OPR': 8.283, 'Auto': -0.47, 'CCWM': -31.494, 'TeamName': 'Iron Lions'}, {'TeamNum': 14952, 'OPR': 7.196, 'Auto': -1.019, 'CCWM': -1.23, 'TeamName': 'Beskar Bots'}, {'TeamNum': 17481, 'OPR': 5.646, 'Auto': -1.017, 'CCWM': -5.461, 'TeamName': 'Talk Nerdy to Me'}, {'TeamNum': 9735, 'OPR': 4.459, 'Auto': 2.764, 'CCWM': -21.406, 'TeamName': 'Canis Major'}, {'TeamNum': 14145, 'OPR': 4.269, 'Auto': 0.284, 'CCWM': -30.78, 'TeamName': 'Lions'}, {'TeamNum': 22856, 'OPR': 4.21, 'Auto': -5.604, 'CCWM': -7.481, 'TeamName': 'Bots That Knock'}, {'TeamNum': 17307, 'OPR': 2.003, 'Auto': -7.166, 'CCWM': -27.112, 'TeamName': 'The Magnificent Seven'}, {'TeamNum': 17306, 'OPR': -0.81, 'Auto': 1.169, 'CCWM': -22.391, 'TeamName': 'Humble Motiv8ors'}, {'TeamNum': 4897, 'OPR': -2.094, 'Auto': -1.609, 'CCWM': -28.312, 'TeamName': 'Bodacious Bulldawgs'}]
i 839

{'17640', '13523', '22501', '17573', '21732', '15640', '12448', '22320', '19884', '13109', '13269', '18629', '18630', '13584', '13580', '12397', '14679', '21825', '12394', '13512', '18260', '17072', '16962', '13714', '14675', '17203', '12393', '12453', '13265', '13581', '22622', '14676', '21733'}
[{'TeamNum': 12397, 'OPR': 103.367, 'Auto': 23.587, 'CCWM': 83.612, 'TeamName': 'High Voltage Rattlers'}, {'TeamNum': 21733, 'OPR': 95.253, 'Auto': 16.288, 'CCWM': 74.67, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 21732, 'OPR': 88.838, 'Auto': 25.47, 'CCWM': 77.838, 'TeamName': 'Cyber Knights'}, {'TeamNum': 12453, 'OPR': 84.5, 'Auto': 13.453, 'CCWM': 38.041, 'TeamName': 'Phoenix - Patriot Engineering'}, {'TeamNum': 13109, 'OPR': 83.971, 'Auto': 23.382, 'CCWM': 52.963, 'TeamName': 'Team Koopa'}, {'TeamNum': 22320, 'OPR': 83.027, 'Auto': 13.711, 'CCWM': 53.216, 'TeamName': 'ROGUE-RANGERS Vengeance'}, {'TeamNum': 13512, 'OPR': 72.535, 'Auto': 24.981, 'CCWM': 38.65, 'TeamName': 'Falcon ROBO-RANGERS'}, {'TeamNum': 13265, 'OPR': 71.176, 'Auto': 25.12, 'CCWM': 24.042, 'TeamName': 'Osiris'}, {'TeamNum': 13714, 'OPR': 60.366, 'Auto': 21.044, 'CCWM': -7.882, 'TeamName': 'Juarez Lincoln High School'}, {'TeamNum': 12448, 'OPR': 59.801, 'Auto': 18.324, 'CCWM': 11.172, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 19884, 'OPR': 59.064, 'Auto': 16.923, 'CCWM': 28.412, 'TeamName': 'JLHS Huskies Engineering and Robotics 1'}, {'TeamNum': 18629, 'OPR': 58.318, 'Auto': 15.681, 'CCWM': -22.341, 'TeamName': 'Collegiate GigaKnights'}, {'TeamNum': 12393, 'OPR': 52.461, 'Auto': 22.142, 'CCWM': -21.986, 'TeamName': 'Pioneer Pi-Thons'}, {'TeamNum': 22622, 'OPR': 50.207, 'Auto': 19.276, 'CCWM': 12.381, 'TeamName': 'Motor Knights'}, {'TeamNum': 13523, 'OPR': 50.2, 'Auto': 9.332, 'CCWM': 19.656, 'TeamName': 'Lady ROBO-RANGERS'}, {'TeamNum': 18630, 'OPR': 46.157, 'Auto': 1.428, 'CCWM': 1.596, 'TeamName': 'Collegiate MegaKnights'}, {'TeamNum': 17072, 'OPR': 46.045, 'Auto': 5.881, 'CCWM': -12.369, 'TeamName': 'WLA Vernon Middle School: Robo-Scorpions 17072'}, {'TeamNum': 13581, 'OPR': 46.024, 'Auto': 18.365, 'CCWM': -8.704, 'TeamName': 'Fang Gang'}, {'TeamNum': 16962, 'OPR': 41.61, 'Auto': 2.866, 'CCWM': -19.342, 'TeamName': 'Gray Fangs'}, {'TeamNum': 13269, 'OPR': 39.832, 'Auto': 13.432, 'CCWM': 21.514, 'TeamName': 'Mustang MegaBytes'}, {'TeamNum': 17573, 'OPR': 39.667, 'Auto': 3.113, 'CCWM': 2.925, 'TeamName': 'Achieve Jagwires'}, {'TeamNum': 17203, 'OPR': 36.423, 'Auto': 7.88, 'CCWM': -27.811, 'TeamName': 'ATHENA'}, {'TeamNum': 12394, 'OPR': 22.873, 'Auto': 15.777, 'CCWM': -20.247, 'TeamName': 'Pioneer Diamondbacks'}, {'TeamNum': 13580, 'OPR': 21.444, 'Auto': 3.098, 'CCWM': -13.672, 'TeamName': 'Tech Serpents'}, {'TeamNum': 14679, 'OPR': 21.128, 'Auto': 4.485, 'CCWM': -24.992, 'TeamName': 'Valkyries'}, {'TeamNum': 22501, 'OPR': 19.191, 'Auto': -3.503, 'CCWM': -27.546, 'TeamName': 'Weslaco Panther Robotics'}, {'TeamNum': 14675, 'OPR': 15.404, 'Auto': -2.784, 'CCWM': -55.781, 'TeamName': 'Vikings'}, {'TeamNum': 15640, 'OPR': 15.271, 'Auto': -4.444, 'CCWM': -45.553, 'TeamName': 'Rembrandt Spartans'}, {'TeamNum': 18260, 'OPR': 14.907, 'Auto': 5.541, 'CCWM': -53.334, 'TeamName': 'RoboJags'}, {'TeamNum': 21825, 'OPR': 11.455, 'Auto': 0.391, 'CCWM': -34.855, 'TeamName': 'Tznotic'}, {'TeamNum': 13584, 'OPR': 9.114, 'Auto': 2.408, 'CCWM': -41.261, 'TeamName': 'X Reckless Robotics '}, {'TeamNum': 17640, 'OPR': 4.365, 'Auto': -6.58, 'CCWM': -66.907, 'TeamName': 'Odd Squad'}, {'TeamNum': 14676, 'OPR': -2.157, 'Auto': -5.042, 'CCWM': -29.508, 'TeamName': 'AzTECHS'}]
USTXSOHALT
[{'TeamNum': 12397, 'OPR': 103.367, 'Auto': 23.587, 'CCWM': 83.612, 'TeamName': 'High Voltage Rattlers'}, {'TeamNum': 21733, 'OPR': 95.253, 'Auto': 16.288, 'CCWM': 74.67, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 21732, 'OPR': 88.838, 'Auto': 25.47, 'CCWM': 77.838, 'TeamName': 'Cyber Knights'}, {'TeamNum': 12453, 'OPR': 84.5, 'Auto': 13.453, 'CCWM': 38.041, 'TeamName': 'Phoenix - Patriot Engineering'}, {'TeamNum': 13109, 'OPR': 83.971, 'Auto': 23.382, 'CCWM': 52.963, 'TeamName': 'Team Koopa'}, {'TeamNum': 22320, 'OPR': 83.027, 'Auto': 13.711, 'CCWM': 53.216, 'TeamName': 'ROGUE-RANGERS Vengeance'}, {'TeamNum': 13512, 'OPR': 72.535, 'Auto': 24.981, 'CCWM': 38.65, 'TeamName': 'Falcon ROBO-RANGERS'}, {'TeamNum': 13265, 'OPR': 71.176, 'Auto': 25.12, 'CCWM': 24.042, 'TeamName': 'Osiris'}, {'TeamNum': 13714, 'OPR': 60.366, 'Auto': 21.044, 'CCWM': -7.882, 'TeamName': 'Juarez Lincoln High School'}, {'TeamNum': 12448, 'OPR': 59.801, 'Auto': 18.324, 'CCWM': 11.172, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 19884, 'OPR': 59.064, 'Auto': 16.923, 'CCWM': 28.412, 'TeamName': 'JLHS Huskies Engineering and Robotics 1'}, {'TeamNum': 18629, 'OPR': 58.318, 'Auto': 15.681, 'CCWM': -22.341, 'TeamName': 'Collegiate GigaKnights'}, {'TeamNum': 12393, 'OPR': 52.461, 'Auto': 22.142, 'CCWM': -21.986, 'TeamName': 'Pioneer Pi-Thons'}, {'TeamNum': 22622, 'OPR': 50.207, 'Auto': 19.276, 'CCWM': 12.381, 'TeamName': 'Motor Knights'}, {'TeamNum': 13523, 'OPR': 50.2, 'Auto': 9.332, 'CCWM': 19.656, 'TeamName': 'Lady ROBO-RANGERS'}, {'TeamNum': 18630, 'OPR': 46.157, 'Auto': 1.428, 'CCWM': 1.596, 'TeamName': 'Collegiate MegaKnights'}, {'TeamNum': 17072, 'OPR': 46.045, 'Auto': 5.881, 'CCWM': -12.369, 'TeamName': 'WLA Vernon Middle School: Robo-Scorpions 17072'}, {'TeamNum': 13581, 'OPR': 46.024, 'Auto': 18.365, 'CCWM': -8.704, 'TeamName': 'Fang Gang'}, {'TeamNum': 16962, 'OPR': 41.61, 'Auto': 2.866, 'CCWM': -19.342, 'TeamName': 'Gray Fangs'}, {'TeamNum': 13269, 'OPR': 39.832, 'Auto': 13.432, 'CCWM': 21.514, 'TeamName': 'Mustang MegaBytes'}, {'TeamNum': 17573, 'OPR': 39.667, 'Auto': 3.113, 'CCWM': 2.925, 'TeamName': 'Achieve Jagwires'}, {'TeamNum': 17203, 'OPR': 36.423, 'Auto': 7.88, 'CCWM': -27.811, 'TeamName': 'ATHENA'}, {'TeamNum': 12394, 'OPR': 22.873, 'Auto': 15.777, 'CCWM': -20.247, 'TeamName': 'Pioneer Diamondbacks'}, {'TeamNum': 13580, 'OPR': 21.444, 'Auto': 3.098, 'CCWM': -13.672, 'TeamName': 'Tech Serpents'}, {'TeamNum': 14679, 'OPR': 21.128, 'Auto': 4.485, 'CCWM': -24.992, 'TeamName': 'Valkyries'}, {'TeamNum': 22501, 'OPR': 19.191, 'Auto': -3.503, 'CCWM': -27.546, 'TeamName': 'Weslaco Panther Robotics'}, {'TeamNum': 14675, 'OPR': 15.404, 'Auto': -2.784, 'CCWM': -55.781, 'TeamName': 'Vikings'}, {'TeamNum': 15640, 'OPR': 15.271, 'Auto': -4.444, 'CCWM': -45.553, 'TeamName': 'Rembrandt Spartans'}, {'TeamNum': 18260, 'OPR': 14.907, 'Auto': 5.541, 'CCWM': -53.334, 'TeamName': 'RoboJags'}, {'TeamNum': 21825, 'OPR': 11.455, 'Auto': 0.391, 'CCWM': -34.855, 'TeamName': 'Tznotic'}, {'TeamNum': 13584, 'OPR': 9.114, 'Auto': 2.408, 'CCWM': -41.261, 'TeamName': 'X Reckless Robotics '}, {'TeamNum': 17640, 'OPR': 4.365, 'Auto': -6.58, 'CCWM': -66.907, 'TeamName': 'Odd Squad'}, {'TeamNum': 14676, 'OPR': -2.157, 'Auto': -5.042, 'CCWM': -29.508, 'TeamName': 'AzTECHS'}]
i 840
{'18996', '20369', '16774', '17150', '17430', '17774', '6652', '11534', '12838', '19876', '19873', '12882', '392', '22255', '20447', '6383', '9202', '12655', '13621', '15317', '14691', '8094', '519', '14169', '10442', '6010', '4419', '354', '5262', '17160', '4970', '19994', '21317', '4924', '1885', '4634', '6341'}
[{'TeamNum': 1885, 'OPR': 91.62, 'Auto': 20.298, 'CCWM': 43.684, 'TeamName': 'ILITE - The Legacy'}, {'TeamNum': 17774, 'OPR': 90.012, 'Auto': 22.946, 'CCWM': 38.362, 'TeamName': 'Monroe Robotics'}, {'TeamNum': 20447, 'OPR': 87.372, 'Auto': 20.615, 'CCWM': 48.387, 'TeamName': 'Turing Squad'}, {'TeamNum': 4634, 'OPR': 87.057, 'Auto': 7.917, 'CCWM': 69.054, 'TeamName': 'FROGbots - Purple'}, {'TeamNum': 19994, 'OPR': 83.295, 'Auto': 24.586, 'CCWM': 46.468, 'TeamName': 'Andromeda '}, {'TeamNum': 19876, 'OPR': 79.037, 'Auto': 26.804, 'CCWM': 13.355, 'TeamName': 'N-1'}, {'TeamNum': 13621, 'OPR': 72.723, 'Auto': 26.919, 'CCWM': 28.259, 'TeamName': 'Cable Management'}, {'TeamNum': 21317, 'OPR': 66.587, 'Auto': 21.802, 'CCWM': 25.414, 'TeamName': 'Q-Tech'}, {'TeamNum': 6341, 'OPR': 63.902, 'Auto': 13.493, 'CCWM': 40.605, 'TeamName': 'OOPS'}, {'TeamNum': 11534, 'OPR': 60.587, 'Auto': 20.934, 'CCWM': 13.955, 'TeamName': 'Bot Brigade Quartic'}, {'TeamNum': 10442, 'OPR': 57.808, 'Auto': 9.837, 'CCWM': 2.737, 'TeamName': 'Metro Mechanics'}, {'TeamNum': 6010, 'OPR': 55.542, 'Auto': 11.006, 'CCWM': 6.798, 'TeamName': 'Thunder Stone'}, {'TeamNum': 15317, 'OPR': 55.407, 'Auto': 15.025, 'CCWM': -4.712, 'TeamName': 'HHS Robotics - Error Code 404'}, {'TeamNum': 519, 'OPR': 48.565, 'Auto': 13.733, 'CCWM': 12.206, 'TeamName': 'Epsilon Delta Too'}, {'TeamNum': 17430, 'OPR': 48.083, 'Auto': 16.12, 'CCWM': 5.687, 'TeamName': 'Seismic Waves'}, {'TeamNum': 8094, 'OPR': 46.597, 'Auto': 22.708, 'CCWM': -46.612, 'TeamName': 'Robotic Rampage'}, {'TeamNum': 14169, 'OPR': 44.583, 'Auto': 15.528, 'CCWM': 11.858, 'TeamName': 'BC4H  Partytime ^s'}, {'TeamNum': 12838, 'OPR': 40.262, 'Auto': 20.051, 'CCWM': 32.039, 'TeamName': 'Lancaster Kinetic Storm'}, {'TeamNum': 20369, 'OPR': 37.49, 'Auto': -1.399, 'CCWM': -11.959, 'TeamName': 'EMCTEAMTECH'}, {'TeamNum': 19873, 'OPR': 35.745, 'Auto': 16.275, 'CCWM': -7.576, 'TeamName': 'HHS Robotics - Error Code 502'}, {'TeamNum': 4419, 'OPR': 34.517, 'Auto': 11.067, 'CCWM': -2.208, 'TeamName': 'Pokèbots'}, {'TeamNum': 14691, 'OPR': 33.001, 'Auto': 22.945, 'CCWM': -15.977, 'TeamName': 'Mechanical Mafia'}, {'TeamNum': 22255, 'OPR': 28.57, 'Auto': 0.736, 'CCWM': -23.815, 'TeamName': 'Labradabradors'}, {'TeamNum': 4924, 'OPR': 27.508, 'Auto': 13.582, 'CCWM': -52.944, 'TeamName': 'Red Beard Pandas'}, {'TeamNum': 4970, 'OPR': 26.094, 'Auto': 5.33, 'CCWM': 14.95, 'TeamName': 'Loose Screws'}, {'TeamNum': 6383, 'OPR': 25.763, 'Auto': 3.933, 'CCWM': -37.565, 'TeamName': 'HHS Robotics - Error Code 301'}, {'TeamNum': 17160, 'OPR': 24.093, 'Auto': 13.385, 'CCWM': -13.344, 'TeamName': 'FROGbots - Green'}, {'TeamNum': 392, 'OPR': 23.179, 'Auto': 4.303, 'CCWM': -13.685, 'TeamName': 'ILITE - Imagination'}, {'TeamNum': 6652, 'OPR': 22.672, 'Auto': -10.131, 'CCWM': 19.975, 'TeamName': 'Cone Nappers'}, {'TeamNum': 12655, 'OPR': 22.33, 'Auto': 12.566, 'CCWM': -12.368, 'TeamName': 'North Cross Raider Robotics'}, {'TeamNum': 12882, 'OPR': 19.969, 'Auto': -5.919, 'CCWM': -33.949, 'TeamName': 'Hypergaints'}, {'TeamNum': 5262, 'OPR': 19.685, 'Auto': -1.193, 'CCWM': -9.828, 'TeamName': 'ILITE - Innovation'}, {'TeamNum': 17150, 'OPR': 17.435, 'Auto': 12.683, 'CCWM': -59.357, 'TeamName': 'Trojans'}, {'TeamNum': 18996, 'OPR': 16.091, 'Auto': 0.885, 'CCWM': -23.458, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 354, 'OPR': 13.942, 'Auto': 2.93, 'CCWM': -28.001, 'TeamName': 'ILITE - Inspiration'}, {'TeamNum': 16774, 'OPR': 6.857, 'Auto': -1.711, 'CCWM': -69.297, 'TeamName': 'Raider Robotics'}, {'TeamNum': 9202, 'OPR': 1.009, 'Auto': -7.147, 'CCWM': -25.355, 'TeamName': "Her Majesty's Engineers"}]
USCHSHAQ1
[{'TeamNum': 1885, 'OPR': 91.62, 'Auto': 20.298, 'CCWM': 43.684, 'TeamName': 'ILITE - The Legacy'}, {'TeamNum': 17774, 'OPR': 90.012, 'Auto': 22.946, 'CCWM': 38.362, 'TeamName': 'Monroe Robotics'}, {'TeamNum': 20447, 'OPR': 87.372, 'Auto': 20.615, 'CCWM': 48.387, 'TeamName': 'Turing Squad'}, {'TeamNum': 4634, 'OPR': 87.057, 'Auto': 7.917, 'CCWM': 69.054, 'TeamName': 'FROGbots - Purple'}, {'TeamNum': 19994, 'OPR': 83.295, 'Auto': 24.586, 'CCWM': 46.468, 'TeamName': 'Andromeda '}, {'TeamNum': 19876, 'OPR': 79.037, 'Auto': 26.804, 'CCWM': 13.355, 'TeamName': 'N-1'}, {'TeamNum': 13621, 'OPR': 72.723, 'Auto': 26.919, 'CCWM': 28.259, 'TeamName': 'Cable Management'}, {'TeamNum': 21317, 'OPR': 66.587, 'Auto': 21.802, 'CCWM': 25.414, 'TeamName': 'Q-Tech'}, {'TeamNum': 6341, 'OPR': 63.902, 'Auto': 13.493, 'CCWM': 40.605, 'TeamName': 'OOPS'}, {'TeamNum': 11534, 'OPR': 60.587, 'Auto': 20.934, 'CCWM': 13.955, 'TeamName': 'Bot Brigade Quartic'}, {'TeamNum': 10442, 'OPR': 57.808, 'Auto': 9.837, 'CCWM': 2.737, 'TeamName': 'Metro Mechanics'}, {'TeamNum': 6010, 'OPR': 55.542, 'Auto': 11.006, 'CCWM': 6.798, 'TeamName': 'Thunder Stone'}, {'TeamNum': 15317, 'OPR': 55.407, 'Auto': 15.025, 'CCWM': -4.712, 'TeamName': 'HHS Robotics - Error Code 404'}, {'TeamNum': 519, 'OPR': 48.565, 'Auto': 13.733, 'CCWM': 12.206, 'TeamName': 'Epsilon Delta Too'}, {'TeamNum': 17430, 'OPR': 48.083, 'Auto': 16.12, 'CCWM': 5.687, 'TeamName': 'Seismic Waves'}, {'TeamNum': 8094, 'OPR': 46.597, 'Auto': 22.708, 'CCWM': -46.612, 'TeamName': 'Robotic Rampage'}, {'TeamNum': 14169, 'OPR': 44.583, 'Auto': 15.528, 'CCWM': 11.858, 'TeamName': 'BC4H  Partytime ^s'}, {'TeamNum': 12838, 'OPR': 40.262, 'Auto': 20.051, 'CCWM': 32.039, 'TeamName': 'Lancaster Kinetic Storm'}, {'TeamNum': 20369, 'OPR': 37.49, 'Auto': -1.399, 'CCWM': -11.959, 'TeamName': 'EMCTEAMTECH'}, {'TeamNum': 19873, 'OPR': 35.745, 'Auto': 16.275, 'CCWM': -7.576, 'TeamName': 'HHS Robotics - Error Code 502'}, {'TeamNum': 4419, 'OPR': 34.517, 'Auto': 11.067, 'CCWM': -2.208, 'TeamName': 'Pokèbots'}, {'TeamNum': 14691, 'OPR': 33.001, 'Auto': 22.945, 'CCWM': -15.977, 'TeamName': 'Mechanical Mafia'}, {'TeamNum': 22255, 'OPR': 28.57, 'Auto': 0.736, 'CCWM': -23.815, 'TeamName': 'Labradabradors'}, {'TeamNum': 4924, 'OPR': 27.508, 'Auto': 13.582, 'CCWM': -52.944, 'TeamName': 'Red Beard Pandas'}, {'TeamNum': 4970, 'OPR': 26.094, 'Auto': 5.33, 'CCWM': 14.95, 'TeamName': 'Loose Screws'}, {'TeamNum': 6383, 'OPR': 25.763, 'Auto': 3.933, 'CCWM': -37.565, 'TeamName': 'HHS Robotics - Error Code 301'}, {'TeamNum': 17160, 'OPR': 24.093, 'Auto': 13.385, 'CCWM': -13.344, 'TeamName': 'FROGbots - Green'}, {'TeamNum': 392, 'OPR': 23.179, 'Auto': 4.303, 'CCWM': -13.685, 'TeamName': 'ILITE - Imagination'}, {'TeamNum': 6652, 'OPR': 22.672, 'Auto': -10.131, 'CCWM': 19.975, 'TeamName': 'Cone Nappers'}, {'TeamNum': 12655, 'OPR': 22.33, 'Auto': 12.566, 'CCWM': -12.368, 'TeamName': 'North Cross Raider Robotics'}, {'TeamNum': 12882, 'OPR': 19.969, 'Auto': -5.919, 'CCWM': -33.949, 'TeamName': 'Hypergaints'}, {'TeamNum': 5262, 'OPR': 19.685, 'Auto': -1.193, 'CCWM': -9.828, 'TeamName': 'ILITE - Innovation'}, {'TeamNum': 17150, 'OPR': 17.435, 'Auto': 12.683, 'CCWM': -59.357, 'TeamName': 'Trojans'}, {'TeamNum': 18996, 'OPR': 16.091, 'Auto': 0.885, 'CCWM': -23.458, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 354, 'OPR': 13.942, 'Auto': 2.93, 'CCWM': -28.001, 'TeamName': 'ILITE - Inspiration'}, {'TeamNum': 16774, 'OPR': 6.857, 'Auto': -1.711, 'CCWM': -69.297, 'TeamName': 'Raider Robotics'}, {'TeamNum': 9202, 'OPR': 1.009, 'Auto': -7.147, 'CCWM': -25.355, 'TeamName': "Her Majesty's Engineers"}]

i 841
{'17682', '20369', '10358', '19434', '19458', '22685', '12096', '16862', '21774', '12882', '20721', '11804', '9830', '22202', '22200', '16829', '9450', '13353', '16439', '19753', '20714', '3804', '22742', '15167', '10515', '21886', '8702', '7'}
[{'TeamNum': 19458, 'OPR': 156.197, 'Auto': 38.38, 'CCWM': 154.603, 'TeamName': 'Equilibrium.exe '}, {'TeamNum': 22202, 'OPR': 113.217, 'Auto': 29.744, 'CCWM': 59.59, 'TeamName': 'Infinity.exe'}, {'TeamNum': 7, 'OPR': 108.601, 'Auto': 38.958, 'CCWM': 118.998, 'TeamName': 'Tactical Sheep'}, {'TeamNum': 19434, 'OPR': 103.37, 'Auto': 21.096, 'CCWM': 30.979, 'TeamName': 'Redstone.exe'}, {'TeamNum': 21774, 'OPR': 92.086, 'Auto': 16.996, 'CCWM': 36.55, 'TeamName': 'Supernova.exe'}, {'TeamNum': 12096, 'OPR': 87.208, 'Auto': 12.8, 'CCWM': 39.097, 'TeamName': 'Absolute Zero'}, {'TeamNum': 8702, 'OPR': 83.438, 'Auto': 14.035, 'CCWM': 52.997, 'TeamName': 'Innovotics'}, {'TeamNum': 15167, 'OPR': 80.972, 'Auto': 11.292, 'CCWM': 30.951, 'TeamName': 'Robo Troopers'}, {'TeamNum': 16829, 'OPR': 69.166, 'Auto': 20.421, 'CCWM': 89.797, 'TeamName': 'Radioactive'}, {'TeamNum': 13353, 'OPR': 68.116, 'Auto': 20.863, 'CCWM': -16.495, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 10515, 'OPR': 66.434, 'Auto': 25.668, 'CCWM': -13.348, 'TeamName': 'Xtreme Voltage'}, {'TeamNum': 16862, 'OPR': 55.283, 'Auto': 12.292, 'CCWM': 37.867, 'TeamName': 'Terabyte Triceratops'}, {'TeamNum': 16439, 'OPR': 53.795, 'Auto': 12.486, 'CCWM': -50.975, 'TeamName': 'AlphaGo'}, {'TeamNum': 12882, 'OPR': 49.563, 'Auto': 10.908, 'CCWM': -38.469, 'TeamName': 'Hypergaints'}, {'TeamNum': 10358, 'OPR': 47.329, 'Auto': 15.159, 'CCWM': 2.378, 'TeamName': 'Squatch Watch'}, {'TeamNum': 9450, 'OPR': 43.275, 'Auto': 18.182, 'CCWM': -44.973, 'TeamName': 'Phoenix'}, {'TeamNum': 17682, 'OPR': 39.779, 'Auto': 10.473, 'CCWM': -20.621, 'TeamName': 'TimberX'}, {'TeamNum': 22200, 'OPR': 36.75, 'Auto': 6.139, 'CCWM': -79.351, 'TeamName': 'Power Potatoes'}, {'TeamNum': 9830, 'OPR': 31.983, 'Auto': 1.756, 'CCWM': -15.479, 'TeamName': 'RobotLits'}, {'TeamNum': 20369, 'OPR': 28.271, 'Auto': 8.718, 'CCWM': -66.606, 'TeamName': 'EMCTEAMTECH'}, {'TeamNum': 19753, 'OPR': 27.802, 'Auto': 1.816, 'CCWM': -34.86, 'TeamName': 'StarStruck'}, {'TeamNum': 22685, 'OPR': 22.838, 'Auto': 1.204, 'CCWM': -28.796, 'TeamName': 'chosenconquerors'}, {'TeamNum': 20714, 'OPR': 18.078, 'Auto': -0.727, 'CCWM': -58.74, 'TeamName': 'FloCo BuffBots1 '}, {'TeamNum': 11804, 'OPR': 8.337, 'Auto': -1.581, 'CCWM': 6.022, 'TeamName': 'Stick-Shift'}, {'TeamNum': 3804, 'OPR': 7.765, 'Auto': -3.589, 'CCWM': -42.145, 'TeamName': 'Team Snuffleupagus'}, {'TeamNum': 22742, 'OPR': 7.547, 'Auto': 1.071, 'CCWM': -39.33, 'TeamName': 'HCLS ROBOTICS CLUB'}, {'TeamNum': 20721, 'OPR': -1.426, 'Auto': -0.549, 'CCWM': -46.078, 'TeamName': 'FloCo BuffBots2'}, {'TeamNum': 21886, 'OPR': -11.974, 'Auto': -3.813, 'CCWM': -63.561, 'TeamName': 'Lithium'}]
USCHSHAQ2
[{'TeamNum': 19458, 'OPR': 156.197, 'Auto': 38.38, 'CCWM': 154.603, 'TeamName': 'Equilibrium.exe '}, {'TeamNum': 22202, 'OPR': 113.217, 'Auto': 29.744, 'CCWM': 59.59, 'TeamName': 'Infinity.exe'}, {'TeamNum': 7, 'OPR': 108.601, 'Auto': 38.958, 'CCWM': 118.998, 'TeamName': 'Tactical Sheep'}, {'TeamNum': 19434, 'OPR': 103.37, 'Auto': 21.096, 'CCWM': 30.979, 'TeamName': 'Redstone.exe'}, {'TeamNum': 21774, 'OPR': 92.086, 'Auto': 16.996, 'CCWM': 36.55, 'TeamName': 'Supernova.exe'}, {'TeamNum': 12096, 'OPR': 87.208, 'Auto': 12.8, 'CCWM': 39.097, 'TeamName': 'Absolute Zero'}, {'TeamNum': 8702, 'OPR': 83.438, 'Auto': 14.035, 'CCWM': 52.997, 'TeamName': 'Innovotics'}, {'TeamNum': 15167, 'OPR': 80.972, 'Auto': 11.292, 'CCWM': 30.951, 'TeamName': 'Robo Troopers'}, {'TeamNum': 16829, 'OPR': 69.166, 'Auto': 20.421, 'CCWM': 89.797, 'TeamName': 'Radioactive'}, {'TeamNum': 13353, 'OPR': 68.116, 'Auto': 20.863, 'CCWM': -16.495, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 10515, 'OPR': 66.434, 'Auto': 25.668, 'CCWM': -13.348, 'TeamName': 'Xtreme Voltage'}, {'TeamNum': 16862, 'OPR': 55.283, 'Auto': 12.292, 'CCWM': 37.867, 'TeamName': 'Terabyte Triceratops'}, {'TeamNum': 16439, 'OPR': 53.795, 'Auto': 12.486, 'CCWM': -50.975, 'TeamName': 'AlphaGo'}, {'TeamNum': 12882, 'OPR': 49.563, 'Auto': 10.908, 'CCWM': -38.469, 'TeamName': 'Hypergaints'}, {'TeamNum': 10358, 'OPR': 47.329, 'Auto': 15.159, 'CCWM': 2.378, 'TeamName': 'Squatch Watch'}, {'TeamNum': 9450, 'OPR': 43.275, 'Auto': 18.182, 'CCWM': -44.973, 'TeamName': 'Phoenix'}, {'TeamNum': 17682, 'OPR': 39.779, 'Auto': 10.473, 'CCWM': -20.621, 'TeamName': 'TimberX'}, {'TeamNum': 22200, 'OPR': 36.75, 'Auto': 6.139, 'CCWM': -79.351, 'TeamName': 'Power Potatoes'}, {'TeamNum': 9830, 'OPR': 31.983, 'Auto': 1.756, 'CCWM': -15.479, 'TeamName': 'RobotLits'}, {'TeamNum': 20369, 'OPR': 28.271, 'Auto': 8.718, 'CCWM': -66.606, 'TeamName': 'EMCTEAMTECH'}, {'TeamNum': 19753, 'OPR': 27.802, 'Auto': 1.816, 'CCWM': -34.86, 'TeamName': 'StarStruck'}, {'TeamNum': 22685, 'OPR': 22.838, 'Auto': 1.204, 'CCWM': -28.796, 'TeamName': 'chosenconquerors'}, {'TeamNum': 20714, 'OPR': 18.078, 'Auto': -0.727, 'CCWM': -58.74, 'TeamName': 'FloCo BuffBots1 '}, {'TeamNum': 11804, 'OPR': 8.337, 'Auto': -1.581, 'CCWM': 6.022, 'TeamName': 'Stick-Shift'}, {'TeamNum': 3804, 'OPR': 7.765, 'Auto': -3.589, 'CCWM': -42.145, 'TeamName': 'Team Snuffleupagus'}, {'TeamNum': 22742, 'OPR': 7.547, 'Auto': 1.071, 'CCWM': -39.33, 'TeamName': 'HCLS ROBOTICS CLUB'}, {'TeamNum': 20721, 'OPR': -1.426, 'Auto': -0.549, 'CCWM': -46.078, 'TeamName': 'FloCo BuffBots2'}, {'TeamNum': 21886, 'OPR': -11.974, 'Auto': -3.813, 'CCWM': -63.561, 'TeamName': 'Lithium'}]
i 842
i 843
{'16750', '19708', '22556', '14343', '18225', '21336', '417', '12808', '15337', '8923', '20403', '11138', '11970', '20345', '19669', '17077', '6220', '21301', '8693', '17595'}
[{'TeamNum': 12808, 'OPR': 137.617, 'Auto': 41.388, 'CCWM': 102.793, 'TeamName': 'RevAmped Robotics'}, {'TeamNum': 11970, 'OPR': 136.174, 'Auto': 44.471, 'CCWM': 140.83, 'TeamName': 'Titanium Talons '}, {'TeamNum': 19708, 'OPR': 107.295, 'Auto': 24.037, 'CCWM': 82.396, 'TeamName': 'The Emerald Bots'}, {'TeamNum': 15337, 'OPR': 106.728, 'Auto': 26.564, 'CCWM': 34.572, 'TeamName': 'Alpha Intelligence'}, {'TeamNum': 20345, 'OPR': 92.24, 'Auto': 15.225, 'CCWM': 14.952, 'TeamName': 'Kobalt Klaws'}, {'TeamNum': 17595, 'OPR': 85.81, 'Auto': 23.615, 'CCWM': -3.997, 'TeamName': 'Beta Bionix'}, {'TeamNum': 18225, 'OPR': 78.986, 'Auto': 22.243, 'CCWM': -11.824, 'TeamName': 'High Definition '}, {'TeamNum': 21301, 'OPR': 77.825, 'Auto': 7.401, 'CCWM': 5.036, 'TeamName': 'Electric Wolves'}, {'TeamNum': 21336, 'OPR': 73.511, 'Auto': 24.899, 'CCWM': 3.723, 'TeamName': 'I Forgot'}, {'TeamNum': 14343, 'OPR': 71.823, 'Auto': 5.782, 'CCWM': -12.108, 'TeamName': 'Escape Velocity'}, {'TeamNum': 417, 'OPR': 71.186, 'Auto': 23.348, 'CCWM': -11.03, 'TeamName': 'S.K.I.D. (Space Koalas In Disguise)'}, {'TeamNum': 17077, 'OPR': 65.256, 'Auto': 4.611, 'CCWM': -27.569, 'TeamName': 'Adna Robotics'}, {'TeamNum': 6220, 'OPR': 64.264, 'Auto': -2.939, 'CCWM': -10.888, 'TeamName': 'DRIFT (Dinosaurs Racing in Food Trucks)'}, {'TeamNum': 11138, 'OPR': 56.491, 'Auto': 2.493, 'CCWM': -38.451, 'TeamName': 'Robo Eclipse'}, {'TeamNum': 19669, 'OPR': 46.66, 'Auto': 10.945, 'CCWM': -12.847, 'TeamName': 'Systematic Chaos'}, {'TeamNum': 22556, 'OPR': 39.636, 'Auto': 12.113, 'CCWM': -46.259, 'TeamName': 'Rush Job'}, {'TeamNum': 8923, 'OPR': 35.238, 'Auto': 13.599, 'CCWM': -52.417, 'TeamName': 'TWIST'}, {'TeamNum': 20403, 'OPR': 30.196, 'Auto': 18.575, 'CCWM': -36.876, 'TeamName': 'Technototes 2'}, {'TeamNum': 16750, 'OPR': 27.692, 'Auto': -8.188, 'CCWM': -41.214, 'TeamName': 'Technototes'}, {'TeamNum': 8693, 'OPR': 7.174, 'Auto': 5.218, 'CCWM': -78.819, 'TeamName': 'Scarabs'}]
USWABES4
[{'TeamNum': 12808, 'OPR': 137.617, 'Auto': 41.388, 'CCWM': 102.793, 'TeamName': 'RevAmped Robotics'}, {'TeamNum': 11970, 'OPR': 136.174, 'Auto': 44.471, 'CCWM': 140.83, 'TeamName': 'Titanium Talons '}, {'TeamNum': 19708, 'OPR': 107.295, 'Auto': 24.037, 'CCWM': 82.396, 'TeamName': 'The Emerald Bots'}, {'TeamNum': 15337, 'OPR': 106.728, 'Auto': 26.564, 'CCWM': 34.572, 'TeamName': 'Alpha Intelligence'}, {'TeamNum': 20345, 'OPR': 92.24, 'Auto': 15.225, 'CCWM': 14.952, 'TeamName': 'Kobalt Klaws'}, {'TeamNum': 17595, 'OPR': 85.81, 'Auto': 23.615, 'CCWM': -3.997, 'TeamName': 'Beta Bionix'}, {'TeamNum': 18225, 'OPR': 78.986, 'Auto': 22.243, 'CCWM': -11.824, 'TeamName': 'High Definition '}, {'TeamNum': 21301, 'OPR': 77.825, 'Auto': 7.401, 'CCWM': 5.036, 'TeamName': 'Electric Wolves'}, {'TeamNum': 21336, 'OPR': 73.511, 'Auto': 24.899, 'CCWM': 3.723, 'TeamName': 'I Forgot'}, {'TeamNum': 14343, 'OPR': 71.823, 'Auto': 5.782, 'CCWM': -12.108, 'TeamName': 'Escape Velocity'}, {'TeamNum': 417, 'OPR': 71.186, 'Auto': 23.348, 'CCWM': -11.03, 'TeamName': 'S.K.I.D. (Space Koalas In Disguise)'}, {'TeamNum': 17077, 'OPR': 65.256, 'Auto': 4.611, 'CCWM': -27.569, 'TeamName': 'Adna Robotics'}, {'TeamNum': 6220, 'OPR': 64.264, 'Auto': -2.939, 'CCWM': -10.888, 'TeamName': 'DRIFT (Dinosaurs Racing in Food Trucks)'}, {'TeamNum': 11138, 'OPR': 56.491, 'Auto': 2.493, 'CCWM': -38.451, 'TeamName': 'Robo Eclipse'}, {'TeamNum': 19669, 'OPR': 46.66, 'Auto': 10.945, 'CCWM': -12.847, 'TeamName': 'Systematic Chaos'}, {'TeamNum': 22556, 'OPR': 39.636, 'Auto': 12.113, 'CCWM': -46.259, 'TeamName': 'Rush Job'}, {'TeamNum': 8923, 'OPR': 35.238, 'Auto': 13.599, 'CCWM': -52.417, 'TeamName': 'TWIST'}, {'TeamNum': 20403, 'OPR': 30.196, 'Auto': 18.575, 'CCWM': -36.876, 'TeamName': 'Technototes 2'}, {'TeamNum': 16750, 'OPR': 27.692, 'Auto': -8.188, 'CCWM': -41.214, 'TeamName': 'Technototes'}, {'TeamNum': 8693, 'OPR': 7.174, 'Auto': 5.218, 'CCWM': -78.819, 'TeamName': 'Scarabs'}]
i 844

{'4267', '20058', '20293', '20256', '265', '18339', '19367', '8823', '11570', '15266', '17223', '10760', '6914', '4116', '22355', '21923', '21355', '18740', '16956', '10824', '19417', '9224', '21180', '15382'}
[{'TeamNum': 21180, 'OPR': 135.991, 'Auto': 29.477, 'CCWM': 120.875, 'TeamName': 'Error 418'}, {'TeamNum': 20293, 'OPR': 85.926, 'Auto': 10.336, 'CCWM': 33.199, 'TeamName': 'Laser Bots'}, {'TeamNum': 10760, 'OPR': 61.923, 'Auto': 12.417, 'CCWM': 40.855, 'TeamName': 'TBD'}, {'TeamNum': 11570, 'OPR': 61.183, 'Auto': 11.665, 'CCWM': 60.725, 'TeamName': 'Étude Engineers'}, {'TeamNum': 10824, 'OPR': 57.109, 'Auto': 17.094, 'CCWM': 15.08, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 4116, 'OPR': 56.445, 'Auto': 16.81, 'CCWM': 13.97, 'TeamName': 'Volta Robotics'}, {'TeamNum': 19367, 'OPR': 56.42, 'Auto': 16.31, 'CCWM': 60.23, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 265, 'OPR': 50.448, 'Auto': 18.282, 'CCWM': 15.234, 'TeamName': 'Viking Robotics '}, {'TeamNum': 19417, 'OPR': 49.837, 'Auto': 7.7, 'CCWM': 31.717, 'TeamName': 'Superstellar'}, {'TeamNum': 15382, 'OPR': 41.078, 'Auto': 0.304, 'CCWM': 27.433, 'TeamName': "I'm Not A Robot"}, {'TeamNum': 20256, 'OPR': 39.487, 'Auto': 19.463, 'CCWM': -47.764, 'TeamName': 'Greendale Robotics:  Storm'}, {'TeamNum': 9224, 'OPR': 36.943, 'Auto': 12.709, 'CCWM': -11.456, 'TeamName': 'Techno G.O.A.T.S.'}, {'TeamNum': 21355, 'OPR': 35.818, 'Auto': 11.497, 'CCWM': -23.164, 'TeamName': 'Turtle TEK'}, {'TeamNum': 6914, 'OPR': 32.679, 'Auto': 4.851, 'CCWM': 22.059, 'TeamName': 'Charging Chaos'}, {'TeamNum': 16956, 'OPR': 27.261, 'Auto': 2.234, 'CCWM': 23.953, 'TeamName': 'The TechCrew'}, {'TeamNum': 22355, 'OPR': 16.907, 'Auto': -0.497, 'CCWM': 4.668, 'TeamName': 'The Metal Manipulators'}, {'TeamNum': 20058, 'OPR': 14.43, 'Auto': 7.887, 'CCWM': -30.101, 'TeamName': 'Upskill'}, {'TeamNum': 15266, 'OPR': 13.596, 'Auto': 0.606, 'CCWM': -79.802, 'TeamName': 'Kohler Robotics'}, {'TeamNum': 18740, 'OPR': 12.401, 'Auto': 1.923, 'CCWM': -16.061, 'TeamName': 'The Ghost Monkeys'}, {'TeamNum': 8823, 'OPR': 9.351, 'Auto': -5.047, 'CCWM': -67.464, 'TeamName': 'Mariner Mayhem'}, {'TeamNum': 18339, 'OPR': 9.21, 'Auto': 1.37, 'CCWM': -40.697, 'TeamName': 'Super Servos'}, {'TeamNum': 21923, 'OPR': 2.825, 'Auto': 7.27, 'CCWM': -29.673, 'TeamName': 'Greendale Robotics:  Neptune'}, {'TeamNum': 17223, 'OPR': 2.475, 'Auto': -0.283, 'CCWM': -66.057, 'TeamName': 'Oxidizers'}, {'TeamNum': 4267, 'OPR': 2.459, 'Auto': -0.376, 'CCWM': -57.758, 'TeamName': 'RoboChix'}]
USWINBQ
[{'TeamNum': 21180, 'OPR': 135.991, 'Auto': 29.477, 'CCWM': 120.875, 'TeamName': 'Error 418'}, {'TeamNum': 20293, 'OPR': 85.926, 'Auto': 10.336, 'CCWM': 33.199, 'TeamName': 'Laser Bots'}, {'TeamNum': 10760, 'OPR': 61.923, 'Auto': 12.417, 'CCWM': 40.855, 'TeamName': 'TBD'}, {'TeamNum': 11570, 'OPR': 61.183, 'Auto': 11.665, 'CCWM': 60.725, 'TeamName': 'Étude Engineers'}, {'TeamNum': 10824, 'OPR': 57.109, 'Auto': 17.094, 'CCWM': 15.08, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 4116, 'OPR': 56.445, 'Auto': 16.81, 'CCWM': 13.97, 'TeamName': 'Volta Robotics'}, {'TeamNum': 19367, 'OPR': 56.42, 'Auto': 16.31, 'CCWM': 60.23, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 265, 'OPR': 50.448, 'Auto': 18.282, 'CCWM': 15.234, 'TeamName': 'Viking Robotics '}, {'TeamNum': 19417, 'OPR': 49.837, 'Auto': 7.7, 'CCWM': 31.717, 'TeamName': 'Superstellar'}, {'TeamNum': 15382, 'OPR': 41.078, 'Auto': 0.304, 'CCWM': 27.433, 'TeamName': "I'm Not A Robot"}, {'TeamNum': 20256, 'OPR': 39.487, 'Auto': 19.463, 'CCWM': -47.764, 'TeamName': 'Greendale Robotics:  Storm'}, {'TeamNum': 9224, 'OPR': 36.943, 'Auto': 12.709, 'CCWM': -11.456, 'TeamName': 'Techno G.O.A.T.S.'}, {'TeamNum': 21355, 'OPR': 35.818, 'Auto': 11.497, 'CCWM': -23.164, 'TeamName': 'Turtle TEK'}, {'TeamNum': 6914, 'OPR': 32.679, 'Auto': 4.851, 'CCWM': 22.059, 'TeamName': 'Charging Chaos'}, {'TeamNum': 16956, 'OPR': 27.261, 'Auto': 2.234, 'CCWM': 23.953, 'TeamName': 'The TechCrew'}, {'TeamNum': 22355, 'OPR': 16.907, 'Auto': -0.497, 'CCWM': 4.668, 'TeamName': 'The Metal Manipulators'}, {'TeamNum': 20058, 'OPR': 14.43, 'Auto': 7.887, 'CCWM': -30.101, 'TeamName': 'Upskill'}, {'TeamNum': 15266, 'OPR': 13.596, 'Auto': 0.606, 'CCWM': -79.802, 'TeamName': 'Kohler Robotics'}, {'TeamNum': 18740, 'OPR': 12.401, 'Auto': 1.923, 'CCWM': -16.061, 'TeamName': 'The Ghost Monkeys'}, {'TeamNum': 8823, 'OPR': 9.351, 'Auto': -5.047, 'CCWM': -67.464, 'TeamName': 'Mariner Mayhem'}, {'TeamNum': 18339, 'OPR': 9.21, 'Auto': 1.37, 'CCWM': -40.697, 'TeamName': 'Super Servos'}, {'TeamNum': 21923, 'OPR': 2.825, 'Auto': 7.27, 'CCWM': -29.673, 'TeamName': 'Greendale Robotics:  Neptune'}, {'TeamNum': 17223, 'OPR': 2.475, 'Auto': -0.283, 'CCWM': -66.057, 'TeamName': 'Oxidizers'}, {'TeamNum': 4267, 'OPR': 2.459, 'Auto': -0.376, 'CCWM': -57.758, 'TeamName': 'RoboChix'}]
i 845
{'16932', '14022', '18450', '20125', '21736', '22029', '10015', '22873', '14021', '18444', '20168', '14023', '14718', '22531', '18634', '22188', '16596'}
[{'TeamNum': 18450, 'OPR': 70.577, 'Auto': 25.292, 'CCWM': 34.237, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 20125, 'OPR': 68.764, 'Auto': 20.383, 'CCWM': 28.036, 'TeamName': 'Webber Robocats'}, {'TeamNum': 10015, 'OPR': 68.173, 'Auto': 12.197, 'CCWM': 30.812, 'TeamName': 'Hyper Droid'}, {'TeamNum': 22029, 'OPR': 65.722, 'Auto': 19.054, 'CCWM': 45.703, 'TeamName': 'ASAP'}, {'TeamNum': 14023, 'OPR': 55.218, 'Auto': 5.949, 'CCWM': -6.881, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 16932, 'OPR': 55.104, 'Auto': 16.005, 'CCWM': 36.659, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22873, 'OPR': 44.557, 'Auto': 9.353, 'CCWM': 37.717, 'TeamName': "I'myanistsitapikoan"}, {'TeamNum': 14718, 'OPR': 42.629, 'Auto': 6.426, 'CCWM': -7.494, 'TeamName': 'Timberbots'}, {'TeamNum': 14021, 'OPR': 36.125, 'Auto': -4.993, 'CCWM': 2.682, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 21736, 'OPR': 33.799, 'Auto': 5.912, 'CCWM': -20.036, 'TeamName': 'Neo Robotics'}, {'TeamNum': 22531, 'OPR': 32.847, 'Auto': 0.513, 'CCWM': -2.877, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 16596, 'OPR': 30.821, 'Auto': -1.504, 'CCWM': 6.465, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 22188, 'OPR': 30.139, 'Auto': 5.374, 'CCWM': -8.454, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 18444, 'OPR': 16.143, 'Auto': 5.404, 'CCWM': -35.613, 'TeamName': 'STS Robotics 18444'}, {'TeamNum': 20168, 'OPR': 7.212, 'Auto': 2.631, 'CCWM': -66.01, 'TeamName': 'STS Robotics 20168'}, {'TeamNum': 18634, 'OPR': 6.332, 'Auto': 3.793, 'CCWM': -48.561, 'TeamName': 'Webber Academy Cosmic Cats'}, {'TeamNum': 14022, 'OPR': 2.243, 'Auto': 2.398, 'CCWM': -32.135, 'TeamName': 'SCHS Robotic Team - SRT 2'}]
CAABABSAM4
[{'TeamNum': 18450, 'OPR': 70.577, 'Auto': 25.292, 'CCWM': 34.237, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 20125, 'OPR': 68.764, 'Auto': 20.383, 'CCWM': 28.036, 'TeamName': 'Webber Robocats'}, {'TeamNum': 10015, 'OPR': 68.173, 'Auto': 12.197, 'CCWM': 30.812, 'TeamName': 'Hyper Droid'}, {'TeamNum': 22029, 'OPR': 65.722, 'Auto': 19.054, 'CCWM': 45.703, 'TeamName': 'ASAP'}, {'TeamNum': 14023, 'OPR': 55.218, 'Auto': 5.949, 'CCWM': -6.881, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 16932, 'OPR': 55.104, 'Auto': 16.005, 'CCWM': 36.659, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22873, 'OPR': 44.557, 'Auto': 9.353, 'CCWM': 37.717, 'TeamName': "I'myanistsitapikoan"}, {'TeamNum': 14718, 'OPR': 42.629, 'Auto': 6.426, 'CCWM': -7.494, 'TeamName': 'Timberbots'}, {'TeamNum': 14021, 'OPR': 36.125, 'Auto': -4.993, 'CCWM': 2.682, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 21736, 'OPR': 33.799, 'Auto': 5.912, 'CCWM': -20.036, 'TeamName': 'Neo Robotics'}, {'TeamNum': 22531, 'OPR': 32.847, 'Auto': 0.513, 'CCWM': -2.877, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 16596, 'OPR': 30.821, 'Auto': -1.504, 'CCWM': 6.465, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 22188, 'OPR': 30.139, 'Auto': 5.374, 'CCWM': -8.454, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 18444, 'OPR': 16.143, 'Auto': 5.404, 'CCWM': -35.613, 'TeamName': 'STS Robotics 18444'}, {'TeamNum': 20168, 'OPR': 7.212, 'Auto': 2.631, 'CCWM': -66.01, 'TeamName': 'STS Robotics 20168'}, {'TeamNum': 18634, 'OPR': 6.332, 'Auto': 3.793, 'CCWM': -48.561, 'TeamName': 'Webber Academy Cosmic Cats'}, {'TeamNum': 14022, 'OPR': 2.243, 'Auto': 2.398, 'CCWM': -32.135, 'TeamName': 'SCHS Robotic Team - SRT 2'}]

i 846
{'3491', '13459', '22557', '15013', '20025', '16353', '17453', '15479', '18840', '22263', '16195', '21603'}
[{'TeamNum': 16195, 'OPR': 96.549, 'Auto': 23.53, 'CCWM': 49.539, 'TeamName': 'Guild of Builders'}, {'TeamNum': 18840, 'OPR': 83.104, 'Auto': 28.551, 'CCWM': 28.22, 'TeamName': 'Reynolds Roborunners'}, {'TeamNum': 16353, 'OPR': 65.739, 'Auto': 9.883, 'CCWM': 24.524, 'TeamName': 'Reynolds Reybots'}, {'TeamNum': 3491, 'OPR': 55.363, 'Auto': 15.032, 'CCWM': 35.063, 'TeamName': 'FIX IT'}, {'TeamNum': 22557, 'OPR': 49.212, 'Auto': 15.978, 'CCWM': -15.188, 'TeamName': 'Mount Douglas Robotics Team'}, {'TeamNum': 20025, 'OPR': 44.355, 'Auto': 18.527, 'CCWM': 15.109, 'TeamName': 'Esquimalt Atom Smashers'}, {'TeamNum': 17453, 'OPR': 27.156, 'Auto': 3.923, 'CCWM': 3.964, 'TeamName': "Dudley's Troopers"}, {'TeamNum': 13459, 'OPR': 24.318, 'Auto': 1.137, 'CCWM': -14.723, 'TeamName': 'M.A.R.G.'}, {'TeamNum': 15013, 'OPR': 22.467, 'Auto': 4.758, 'CCWM': -22.967, 'TeamName': 'Friction'}, {'TeamNum': 15479, 'OPR': 22.395, 'Auto': -4.75, 'CCWM': -49.59, 'TeamName': 'KP Timberwolves'}, {'TeamNum': 22263, 'OPR': 20.522, 'Auto': 1.925, 'CCWM': -33.731, 'TeamName': 'More Thunderbots'}, {'TeamNum': 21603, 'OPR': 8.821, 'Auto': 1.905, 'CCWM': -20.221, 'TeamName': 'ThunderBots'}]
CABCVIQ
[{'TeamNum': 16195, 'OPR': 96.549, 'Auto': 23.53, 'CCWM': 49.539, 'TeamName': 'Guild of Builders'}, {'TeamNum': 18840, 'OPR': 83.104, 'Auto': 28.551, 'CCWM': 28.22, 'TeamName': 'Reynolds Roborunners'}, {'TeamNum': 16353, 'OPR': 65.739, 'Auto': 9.883, 'CCWM': 24.524, 'TeamName': 'Reynolds Reybots'}, {'TeamNum': 3491, 'OPR': 55.363, 'Auto': 15.032, 'CCWM': 35.063, 'TeamName': 'FIX IT'}, {'TeamNum': 22557, 'OPR': 49.212, 'Auto': 15.978, 'CCWM': -15.188, 'TeamName': 'Mount Douglas Robotics Team'}, {'TeamNum': 20025, 'OPR': 44.355, 'Auto': 18.527, 'CCWM': 15.109, 'TeamName': 'Esquimalt Atom Smashers'}, {'TeamNum': 17453, 'OPR': 27.156, 'Auto': 3.923, 'CCWM': 3.964, 'TeamName': "Dudley's Troopers"}, {'TeamNum': 13459, 'OPR': 24.318, 'Auto': 1.137, 'CCWM': -14.723, 'TeamName': 'M.A.R.G.'}, {'TeamNum': 15013, 'OPR': 22.467, 'Auto': 4.758, 'CCWM': -22.967, 'TeamName': 'Friction'}, {'TeamNum': 15479, 'OPR': 22.395, 'Auto': -4.75, 'CCWM': -49.59, 'TeamName': 'KP Timberwolves'}, {'TeamNum': 22263, 'OPR': 20.522, 'Auto': 1.925, 'CCWM': -33.731, 'TeamName': 'More Thunderbots'}, {'TeamNum': 21603, 'OPR': 8.821, 'Auto': 1.905, 'CCWM': -20.221, 'TeamName': 'ThunderBots'}]
i 847
{'22829', '22648', '19461', '16031', '19995', '18799', '18589', '16448', '20266', '14316', '20174', '22111', '16503', '16205', '16267', '18841', '19443', '22817', '16504', '15639'}
[{'TeamNum': 16448, 'OPR': 78.64, 'Auto': 17.804, 'CCWM': 50.813, 'TeamName': 'A.I.M. Bot Robotics'}, {'TeamNum': 20266, 'OPR': 78.312, 'Auto': 17.498, 'CCWM': 32.964, 'TeamName': 'Prince of Wales Engineering and Robotics '}, {'TeamNum': 19995, 'OPR': 75.506, 'Auto': 16.131, 'CCWM': 25.309, 'TeamName': 'Eclipse'}, {'TeamNum': 16503, 'OPR': 75.093, 'Auto': 6.445, 'CCWM': 42.537, 'TeamName': 'MDR QED Robotics'}, {'TeamNum': 16267, 'OPR': 70.45, 'Auto': 22.918, 'CCWM': 48.702, 'TeamName': 'Forces Unknown'}, {'TeamNum': 22111, 'OPR': 67.246, 'Auto': 19.18, 'CCWM': 38.092, 'TeamName': 'Matheson Mecha Mustangs'}, {'TeamNum': 18841, 'OPR': 50.714, 'Auto': 25.967, 'CCWM': 30.66, 'TeamName': 'KSS ONE'}, {'TeamNum': 19461, 'OPR': 44.342, 'Auto': 4.744, 'CCWM': -13.253, 'TeamName': 'MDR Epsilon'}, {'TeamNum': 16205, 'OPR': 44.086, 'Auto': 8.931, 'CCWM': 16.333, 'TeamName': 'Lightning Bots'}, {'TeamNum': 16031, 'OPR': 44.085, 'Auto': 22.143, 'CCWM': -5.532, 'TeamName': 'PARABELLUM'}, {'TeamNum': 14316, 'OPR': 35.358, 'Auto': 2.239, 'CCWM': -19.449, 'TeamName': 'MDR Entradox'}, {'TeamNum': 18799, 'OPR': 30.651, 'Auto': 5.617, 'CCWM': -2.125, 'TeamName': 'Clean-Up Crew Robotics'}, {'TeamNum': 16504, 'OPR': 29.54, 'Auto': 5.775, 'CCWM': -36.493, 'TeamName': 'MDR Dynaco'}, {'TeamNum': 22829, 'OPR': 23.207, 'Auto': 11.303, 'CCWM': -36.17, 'TeamName': 'INERTIA'}, {'TeamNum': 22648, 'OPR': 21.396, 'Auto': 1.655, 'CCWM': -5.011, 'TeamName': 'Robotic Raiders'}, {'TeamNum': 20174, 'OPR': 11.263, 'Auto': -4.344, 'CCWM': -14.073, 'TeamName': 'MDR Maximum Entropy'}, {'TeamNum': 22817, 'OPR': 7.155, 'Auto': -10.645, 'CCWM': -31.815, 'TeamName': 'Killarney Robotics Team 2'}, {'TeamNum': 19443, 'OPR': 6.882, 'Auto': 4.888, 'CCWM': -22.44, 'TeamName': 'MDR Valkyrie'}, {'TeamNum': 15639, 'OPR': 6.444, 'Auto': -0.572, 'CCWM': -61.975, 'TeamName': 'MDR Cheeze Blox'}, {'TeamNum': 18589, 'OPR': 3.031, 'Auto': 0.122, 'CCWM': -37.072, 'TeamName': "St. Pat's Celtic Silverfish"}]
CABCSUQ
[{'TeamNum': 16448, 'OPR': 78.64, 'Auto': 17.804, 'CCWM': 50.813, 'TeamName': 'A.I.M. Bot Robotics'}, {'TeamNum': 20266, 'OPR': 78.312, 'Auto': 17.498, 'CCWM': 32.964, 'TeamName': 'Prince of Wales Engineering and Robotics '}, {'TeamNum': 19995, 'OPR': 75.506, 'Auto': 16.131, 'CCWM': 25.309, 'TeamName': 'Eclipse'}, {'TeamNum': 16503, 'OPR': 75.093, 'Auto': 6.445, 'CCWM': 42.537, 'TeamName': 'MDR QED Robotics'}, {'TeamNum': 16267, 'OPR': 70.45, 'Auto': 22.918, 'CCWM': 48.702, 'TeamName': 'Forces Unknown'}, {'TeamNum': 22111, 'OPR': 67.246, 'Auto': 19.18, 'CCWM': 38.092, 'TeamName': 'Matheson Mecha Mustangs'}, {'TeamNum': 18841, 'OPR': 50.714, 'Auto': 25.967, 'CCWM': 30.66, 'TeamName': 'KSS ONE'}, {'TeamNum': 19461, 'OPR': 44.342, 'Auto': 4.744, 'CCWM': -13.253, 'TeamName': 'MDR Epsilon'}, {'TeamNum': 16205, 'OPR': 44.086, 'Auto': 8.931, 'CCWM': 16.333, 'TeamName': 'Lightning Bots'}, {'TeamNum': 16031, 'OPR': 44.085, 'Auto': 22.143, 'CCWM': -5.532, 'TeamName': 'PARABELLUM'}, {'TeamNum': 14316, 'OPR': 35.358, 'Auto': 2.239, 'CCWM': -19.449, 'TeamName': 'MDR Entradox'}, {'TeamNum': 18799, 'OPR': 30.651, 'Auto': 5.617, 'CCWM': -2.125, 'TeamName': 'Clean-Up Crew Robotics'}, {'TeamNum': 16504, 'OPR': 29.54, 'Auto': 5.775, 'CCWM': -36.493, 'TeamName': 'MDR Dynaco'}, {'TeamNum': 22829, 'OPR': 23.207, 'Auto': 11.303, 'CCWM': -36.17, 'TeamName': 'INERTIA'}, {'TeamNum': 22648, 'OPR': 21.396, 'Auto': 1.655, 'CCWM': -5.011, 'TeamName': 'Robotic Raiders'}, {'TeamNum': 20174, 'OPR': 11.263, 'Auto': -4.344, 'CCWM': -14.073, 'TeamName': 'MDR Maximum Entropy'}, {'TeamNum': 22817, 'OPR': 7.155, 'Auto': -10.645, 'CCWM': -31.815, 'TeamName': 'Killarney Robotics Team 2'}, {'TeamNum': 19443, 'OPR': 6.882, 'Auto': 4.888, 'CCWM': -22.44, 'TeamName': 'MDR Valkyrie'}, {'TeamNum': 15639, 'OPR': 6.444, 'Auto': -0.572, 'CCWM': -61.975, 'TeamName': 'MDR Cheeze Blox'}, {'TeamNum': 18589, 'OPR': 3.031, 'Auto': 0.122, 'CCWM': -37.072, 'TeamName': "St. Pat's Celtic Silverfish"}]
i 848
i 849
i 850
{'20273', '22319', '21754', '20272', '22611', '20761', '22812', '20117', '22838', '20270', '21423', '20280', '20268', '21756', '22354', '21757', '20274', '20183', '17070', '21760', '21421', '20281', '18013', '20279', '20277', '20084', '21397', '20278', '21759', '20267', '20276', '21422', '18017', '20269', '20271'}
[{'TeamNum': 21397, 'OPR': 110.88, 'Auto': 21.374, 'CCWM': 89.653, 'TeamName': 'Sonic Rover'}, {'TeamNum': 20278, 'OPR': 85.173, 'Auto': 14.208, 'CCWM': 82.808, 'TeamName': "Neurobots du Collège de l'Assomption "}, {'TeamNum': 20277, 'OPR': 77.645, 'Auto': 16.748, 'CCWM': 79.326, 'TeamName': 'Tornades Chasers'}, {'TeamNum': 18017, 'OPR': 69.137, 'Auto': 1.896, 'CCWM': 49.065, 'TeamName': 'Pionniers'}, {'TeamNum': 20279, 'OPR': 69.062, 'Auto': 21.6, 'CCWM': 56.377, 'TeamName': 'Les Dragons'}, {'TeamNum': 20280, 'OPR': 68.755, 'Auto': 20.801, 'CCWM': 85.629, 'TeamName': 'Scarabot'}, {'TeamNum': 22838, 'OPR': 67.02, 'Auto': 19.702, 'CCWM': 6.668, 'TeamName': 'Alpha Lab'}, {'TeamNum': 20267, 'OPR': 60.526, 'Auto': 22.502, 'CCWM': 11.023, 'TeamName': 'Gravity'}, {'TeamNum': 18013, 'OPR': 54.548, 'Auto': 19.819, 'CCWM': 10.614, 'TeamName': 'Cuivre & Or'}, {'TeamNum': 22319, 'OPR': 54.445, 'Auto': 4.692, 'CCWM': 59.862, 'TeamName': 'Scarabetter'}, {'TeamNum': 20274, 'OPR': 53.438, 'Auto': 6.59, 'CCWM': 40.246, 'TeamName': 'Spartiates'}, {'TeamNum': 20272, 'OPR': 46.926, 'Auto': 4.15, 'CCWM': 20.162, 'TeamName': 'Express-O'}, {'TeamNum': 20117, 'OPR': 41.65, 'Auto': 6.388, 'CCWM': -27.472, 'TeamName': 'Astro bots'}, {'TeamNum': 20273, 'OPR': 36.45, 'Auto': 3.9, 'CCWM': 16.962, 'TeamName': 'TechnoDynamo'}, {'TeamNum': 20761, 'OPR': 33.541, 'Auto': -1.538, 'CCWM': 15.041, 'TeamName': 'Evolution 2'}, {'TeamNum': 17070, 'OPR': 31.693, 'Auto': 0.723, 'CCWM': -24.38, 'TeamName': 'EVOLUTION'}, {'TeamNum': 20271, 'OPR': 29.632, 'Auto': 3.203, 'CCWM': -24.602, 'TeamName': 'Fenix'}, {'TeamNum': 20084, 'OPR': 29.243, 'Auto': 0.961, 'CCWM': -53.265, 'TeamName': 'The Concept'}, {'TeamNum': 22812, 'OPR': 26.279, 'Auto': 1.98, 'CCWM': 1.586, 'TeamName': 'MaestroTech'}, {'TeamNum': 20281, 'OPR': 22.634, 'Auto': -2.314, 'CCWM': -17.027, 'TeamName': 'les LOUPS'}, {'TeamNum': 21759, 'OPR': 22.308, 'Auto': 4.072, 'CCWM': -4.739, 'TeamName': 'Stamina'}, {'TeamNum': 21423, 'OPR': 22.039, 'Auto': -3.123, 'CCWM': 1.842, 'TeamName': 'Waves'}, {'TeamNum': 21754, 'OPR': 21.235, 'Auto': 2.535, 'CCWM': -21.106, 'TeamName': 'Ookpik'}, {'TeamNum': 20183, 'OPR': 19.913, 'Auto': 8.001, 'CCWM': -41.176, 'TeamName': 'Infinity'}, {'TeamNum': 22354, 'OPR': 19.342, 'Auto': 0.209, 'CCWM': 32.392, 'TeamName': 'Technomaniacs'}, {'TeamNum': 21756, 'OPR': 18.957, 'Auto': 1.005, 'CCWM': -16.813, 'TeamName': 'Cappuccin-O'}, {'TeamNum': 20269, 'OPR': 18.064, 'Auto': 5.122, 'CCWM': 10.027, 'TeamName': 'Maestro'}, {'TeamNum': 20270, 'OPR': 12.159, 'Auto': -0.364, 'CCWM': -9.762, 'TeamName': 'Technomatrix'}, {'TeamNum': 21760, 'OPR': 7.637, 'Auto': 3.08, 'CCWM': 13.737, 'TeamName': 'Tech Master'}, {'TeamNum': 21421, 'OPR': 6.424, 'Auto': 0.415, 'CCWM': -87.239, 'TeamName': 'Eternity'}, {'TeamNum': 20268, 'OPR': 5.524, 'Auto': -2.282, 'CCWM': -65.52, 'TeamName': 'Actinium 450 team 1'}, {'TeamNum': 21422, 'OPR': 2.796, 'Auto': 0.366, 'CCWM': -49.785, 'TeamName': 'Qwerty dynasty'}, {'TeamNum': 21757, 'OPR': -0.019, 'Auto': -1.334, 'CCWM': -70.406, 'TeamName': 'PolyBot'}, {'TeamNum': 20276, 'OPR': -6.729, 'Auto': -3.077, 'CCWM': -75.767, 'TeamName': 'Mecha-logical'}, {'TeamNum': 22611, 'OPR': -9.636, 'Auto': 2.847, 'CCWM': -80.858, 'TeamName': 'Actinium 450 team 2'}]
CAQCCMP
[{'TeamNum': 21397, 'OPR': 110.88, 'Auto': 21.374, 'CCWM': 89.653, 'TeamName': 'Sonic Rover'}, {'TeamNum': 20278, 'OPR': 85.173, 'Auto': 14.208, 'CCWM': 82.808, 'TeamName': "Neurobots du Collège de l'Assomption "}, {'TeamNum': 20277, 'OPR': 77.645, 'Auto': 16.748, 'CCWM': 79.326, 'TeamName': 'Tornades Chasers'}, {'TeamNum': 18017, 'OPR': 69.137, 'Auto': 1.896, 'CCWM': 49.065, 'TeamName': 'Pionniers'}, {'TeamNum': 20279, 'OPR': 69.062, 'Auto': 21.6, 'CCWM': 56.377, 'TeamName': 'Les Dragons'}, {'TeamNum': 20280, 'OPR': 68.755, 'Auto': 20.801, 'CCWM': 85.629, 'TeamName': 'Scarabot'}, {'TeamNum': 22838, 'OPR': 67.02, 'Auto': 19.702, 'CCWM': 6.668, 'TeamName': 'Alpha Lab'}, {'TeamNum': 20267, 'OPR': 60.526, 'Auto': 22.502, 'CCWM': 11.023, 'TeamName': 'Gravity'}, {'TeamNum': 18013, 'OPR': 54.548, 'Auto': 19.819, 'CCWM': 10.614, 'TeamName': 'Cuivre & Or'}, {'TeamNum': 22319, 'OPR': 54.445, 'Auto': 4.692, 'CCWM': 59.862, 'TeamName': 'Scarabetter'}, {'TeamNum': 20274, 'OPR': 53.438, 'Auto': 6.59, 'CCWM': 40.246, 'TeamName': 'Spartiates'}, {'TeamNum': 20272, 'OPR': 46.926, 'Auto': 4.15, 'CCWM': 20.162, 'TeamName': 'Express-O'}, {'TeamNum': 20117, 'OPR': 41.65, 'Auto': 6.388, 'CCWM': -27.472, 'TeamName': 'Astro bots'}, {'TeamNum': 20273, 'OPR': 36.45, 'Auto': 3.9, 'CCWM': 16.962, 'TeamName': 'TechnoDynamo'}, {'TeamNum': 20761, 'OPR': 33.541, 'Auto': -1.538, 'CCWM': 15.041, 'TeamName': 'Evolution 2'}, {'TeamNum': 17070, 'OPR': 31.693, 'Auto': 0.723, 'CCWM': -24.38, 'TeamName': 'EVOLUTION'}, {'TeamNum': 20271, 'OPR': 29.632, 'Auto': 3.203, 'CCWM': -24.602, 'TeamName': 'Fenix'}, {'TeamNum': 20084, 'OPR': 29.243, 'Auto': 0.961, 'CCWM': -53.265, 'TeamName': 'The Concept'}, {'TeamNum': 22812, 'OPR': 26.279, 'Auto': 1.98, 'CCWM': 1.586, 'TeamName': 'MaestroTech'}, {'TeamNum': 20281, 'OPR': 22.634, 'Auto': -2.314, 'CCWM': -17.027, 'TeamName': 'les LOUPS'}, {'TeamNum': 21759, 'OPR': 22.308, 'Auto': 4.072, 'CCWM': -4.739, 'TeamName': 'Stamina'}, {'TeamNum': 21423, 'OPR': 22.039, 'Auto': -3.123, 'CCWM': 1.842, 'TeamName': 'Waves'}, {'TeamNum': 21754, 'OPR': 21.235, 'Auto': 2.535, 'CCWM': -21.106, 'TeamName': 'Ookpik'}, {'TeamNum': 20183, 'OPR': 19.913, 'Auto': 8.001, 'CCWM': -41.176, 'TeamName': 'Infinity'}, {'TeamNum': 22354, 'OPR': 19.342, 'Auto': 0.209, 'CCWM': 32.392, 'TeamName': 'Technomaniacs'}, {'TeamNum': 21756, 'OPR': 18.957, 'Auto': 1.005, 'CCWM': -16.813, 'TeamName': 'Cappuccin-O'}, {'TeamNum': 20269, 'OPR': 18.064, 'Auto': 5.122, 'CCWM': 10.027, 'TeamName': 'Maestro'}, {'TeamNum': 20270, 'OPR': 12.159, 'Auto': -0.364, 'CCWM': -9.762, 'TeamName': 'Technomatrix'}, {'TeamNum': 21760, 'OPR': 7.637, 'Auto': 3.08, 'CCWM': 13.737, 'TeamName': 'Tech Master'}, {'TeamNum': 21421, 'OPR': 6.424, 'Auto': 0.415, 'CCWM': -87.239, 'TeamName': 'Eternity'}, {'TeamNum': 20268, 'OPR': 5.524, 'Auto': -2.282, 'CCWM': -65.52, 'TeamName': 'Actinium 450 team 1'}, {'TeamNum': 21422, 'OPR': 2.796, 'Auto': 0.366, 'CCWM': -49.785, 'TeamName': 'Qwerty dynasty'}, {'TeamNum': 21757, 'OPR': -0.019, 'Auto': -1.334, 'CCWM': -70.406, 'TeamName': 'PolyBot'}, {'TeamNum': 20276, 'OPR': -6.729, 'Auto': -3.077, 'CCWM': -75.767, 'TeamName': 'Mecha-logical'}, {'TeamNum': 22611, 'OPR': -9.636, 'Auto': 2.847, 'CCWM': -80.858, 'TeamName': 'Actinium 450 team 2'}]
i 851

{'17019', '14029', '11567', '13146', '19000', '17056', '12363', '14872', '21770', '19967', '12817', '21957', '15298', '20669', '15811', '21850', '22646', '21656', '21796', '14028', '11226', '17182', '12016', '22144', '15637', '12989', '17106'}
[{'TeamNum': 15637, 'OPR': 125.095, 'Auto': 27.37, 'CCWM': 139.997, 'TeamName': 'Fata Morgana'}, {'TeamNum': 12016, 'OPR': 124.938, 'Auto': 25.421, 'CCWM': 82.796, 'TeamName': 'Mish Mash'}, {'TeamNum': 14029, 'OPR': 104.013, 'Auto': 14.637, 'CCWM': 80.467, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 22144, 'OPR': 87.882, 'Auto': 29.885, 'CCWM': 72.24, 'TeamName': 'Deagles'}, {'TeamNum': 15811, 'OPR': 83.798, 'Auto': 18.135, 'CCWM': 11.074, 'TeamName': 'boosteam'}, {'TeamNum': 11567, 'OPR': 82.114, 'Auto': 11.838, 'CCWM': 58.53, 'TeamName': 'Supernova'}, {'TeamNum': 15298, 'OPR': 78.706, 'Auto': 3.698, 'CCWM': 18.119, 'TeamName': 'RoboTen'}, {'TeamNum': 17019, 'OPR': 68.928, 'Auto': 21.665, 'CCWM': 2.651, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 21656, 'OPR': 62.402, 'Auto': 14.402, 'CCWM': -2.377, 'TeamName': 'Fireflies'}, {'TeamNum': 12363, 'OPR': 59.327, 'Auto': 8.973, 'CCWM': 23.207, 'TeamName': 'OrangeFox'}, {'TeamNum': 13146, 'OPR': 55.653, 'Auto': 19.878, 'CCWM': 28.533, 'TeamName': 'Makers Assemble'}, {'TeamNum': 14028, 'OPR': 53.773, 'Auto': 13.734, 'CCWM': -6.082, 'TeamName': 'Orbit 10'}, {'TeamNum': 14872, 'OPR': 39.237, 'Auto': 2.526, 'CCWM': -53.607, 'TeamName': 'Orbit 9'}, {'TeamNum': 22646, 'OPR': 35.975, 'Auto': 2.094, 'CCWM': -28.875, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 20669, 'OPR': 25.346, 'Auto': -0.2, 'CCWM': -63.91, 'TeamName': 'Build for Change'}, {'TeamNum': 19967, 'OPR': 25.243, 'Auto': 3.318, 'CCWM': -52.17, 'TeamName': 'AIS Talons'}, {'TeamNum': 21957, 'OPR': 24.437, 'Auto': 2.501, 'CCWM': -23.765, 'TeamName': 'Goblin Mode'}, {'TeamNum': 12989, 'OPR': 22.626, 'Auto': 8.578, 'CCWM': -22.477, 'TeamName': 'Super Cow'}, {'TeamNum': 17056, 'OPR': 18.836, 'Auto': -4.262, 'CCWM': 9.212, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 21850, 'OPR': 17.678, 'Auto': -3.687, 'CCWM': -45.015, 'TeamName': 'ATRobotics'}, {'TeamNum': 17106, 'OPR': 14.028, 'Auto': -1.02, 'CCWM': -23.115, 'TeamName': 'PlanTech'}, {'TeamNum': 21796, 'OPR': 10.237, 'Auto': 2.697, 'CCWM': 11.2, 'TeamName': 'ECLIPSE'}, {'TeamNum': 17182, 'OPR': 10.203, 'Auto': -1.151, 'CCWM': -15.219, 'TeamName': 'Red Mask'}, {'TeamNum': 11226, 'OPR': 5.995, 'Auto': -2.829, 'CCWM': -82.371, 'TeamName': 'Black Thunder'}, {'TeamNum': 19000, 'OPR': 3.725, 'Auto': -2.455, 'CCWM': -20.069, 'TeamName': 'Everglow'}, {'TeamNum': 12817, 'OPR': 2.698, 'Auto': 4.559, 'CCWM': -55.136, 'TeamName': 'Everest'}, {'TeamNum': 21770, 'OPR': -7.441, 'Auto': -12.013, 'CCWM': -39.825, 'TeamName': 'HFS'}]
ILSDS2
[{'TeamNum': 15637, 'OPR': 125.095, 'Auto': 27.37, 'CCWM': 139.997, 'TeamName': 'Fata Morgana'}, {'TeamNum': 12016, 'OPR': 124.938, 'Auto': 25.421, 'CCWM': 82.796, 'TeamName': 'Mish Mash'}, {'TeamNum': 14029, 'OPR': 104.013, 'Auto': 14.637, 'CCWM': 80.467, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 22144, 'OPR': 87.882, 'Auto': 29.885, 'CCWM': 72.24, 'TeamName': 'Deagles'}, {'TeamNum': 15811, 'OPR': 83.798, 'Auto': 18.135, 'CCWM': 11.074, 'TeamName': 'boosteam'}, {'TeamNum': 11567, 'OPR': 82.114, 'Auto': 11.838, 'CCWM': 58.53, 'TeamName': 'Supernova'}, {'TeamNum': 15298, 'OPR': 78.706, 'Auto': 3.698, 'CCWM': 18.119, 'TeamName': 'RoboTen'}, {'TeamNum': 17019, 'OPR': 68.928, 'Auto': 21.665, 'CCWM': 2.651, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 21656, 'OPR': 62.402, 'Auto': 14.402, 'CCWM': -2.377, 'TeamName': 'Fireflies'}, {'TeamNum': 12363, 'OPR': 59.327, 'Auto': 8.973, 'CCWM': 23.207, 'TeamName': 'OrangeFox'}, {'TeamNum': 13146, 'OPR': 55.653, 'Auto': 19.878, 'CCWM': 28.533, 'TeamName': 'Makers Assemble'}, {'TeamNum': 14028, 'OPR': 53.773, 'Auto': 13.734, 'CCWM': -6.082, 'TeamName': 'Orbit 10'}, {'TeamNum': 14872, 'OPR': 39.237, 'Auto': 2.526, 'CCWM': -53.607, 'TeamName': 'Orbit 9'}, {'TeamNum': 22646, 'OPR': 35.975, 'Auto': 2.094, 'CCWM': -28.875, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 20669, 'OPR': 25.346, 'Auto': -0.2, 'CCWM': -63.91, 'TeamName': 'Build for Change'}, {'TeamNum': 19967, 'OPR': 25.243, 'Auto': 3.318, 'CCWM': -52.17, 'TeamName': 'AIS Talons'}, {'TeamNum': 21957, 'OPR': 24.437, 'Auto': 2.501, 'CCWM': -23.765, 'TeamName': 'Goblin Mode'}, {'TeamNum': 12989, 'OPR': 22.626, 'Auto': 8.578, 'CCWM': -22.477, 'TeamName': 'Super Cow'}, {'TeamNum': 17056, 'OPR': 18.836, 'Auto': -4.262, 'CCWM': 9.212, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 21850, 'OPR': 17.678, 'Auto': -3.687, 'CCWM': -45.015, 'TeamName': 'ATRobotics'}, {'TeamNum': 17106, 'OPR': 14.028, 'Auto': -1.02, 'CCWM': -23.115, 'TeamName': 'PlanTech'}, {'TeamNum': 21796, 'OPR': 10.237, 'Auto': 2.697, 'CCWM': 11.2, 'TeamName': 'ECLIPSE'}, {'TeamNum': 17182, 'OPR': 10.203, 'Auto': -1.151, 'CCWM': -15.219, 'TeamName': 'Red Mask'}, {'TeamNum': 11226, 'OPR': 5.995, 'Auto': -2.829, 'CCWM': -82.371, 'TeamName': 'Black Thunder'}, {'TeamNum': 19000, 'OPR': 3.725, 'Auto': -2.455, 'CCWM': -20.069, 'TeamName': 'Everglow'}, {'TeamNum': 12817, 'OPR': 2.698, 'Auto': 4.559, 'CCWM': -55.136, 'TeamName': 'Everest'}, {'TeamNum': 21770, 'OPR': -7.441, 'Auto': -12.013, 'CCWM': -39.825, 'TeamName': 'HFS'}]
i 852
{'13452', '11443', '22947', '11808', '9662', '12363', '21770', '19766', '11635', '12201', '16473', '18833', '20669', '14869', '15811', '12797', '22764', '21850', '22646', '11192', '18735', '11803', '12016', '15141', '22144', '15637', '12989'}
[{'TeamNum': 22144, 'OPR': 127.522, 'Auto': 34.055, 'CCWM': 65.773, 'TeamName': 'Deagles'}, {'TeamNum': 15637, 'OPR': 118.525, 'Auto': 25.048, 'CCWM': 77.331, 'TeamName': 'Fata Morgana'}, {'TeamNum': 12201, 'OPR': 95.873, 'Auto': 20.09, 'CCWM': 55.956, 'TeamName': 'TATOOINE'}, {'TeamNum': 11192, 'OPR': 66.196, 'Auto': 6.703, 'CCWM': 31.197, 'TeamName': 'Black Tigers'}, {'TeamNum': 15811, 'OPR': 61.055, 'Auto': 17.684, 'CCWM': 38.481, 'TeamName': 'boosteam'}, {'TeamNum': 11808, 'OPR': 53.94, 'Auto': 12.322, 'CCWM': -12.47, 'TeamName': 'Connection'}, {'TeamNum': 11443, 'OPR': 52.95, 'Auto': -0.673, 'CCWM': 46.087, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 13452, 'OPR': 42.823, 'Auto': 8.983, 'CCWM': 55.854, 'TeamName': 'BTJ'}, {'TeamNum': 15141, 'OPR': 42.759, 'Auto': 4.184, 'CCWM': 58.389, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 11803, 'OPR': 40.617, 'Auto': 7.143, 'CCWM': 9.553, 'TeamName': 'PHOENIX'}, {'TeamNum': 22764, 'OPR': 38.095, 'Auto': 2.327, 'CCWM': -59.99, 'TeamName': 'BAGHEERA'}, {'TeamNum': 18735, 'OPR': 37.952, 'Auto': 7.559, 'CCWM': -3.746, 'TeamName': 'RinGoStar'}, {'TeamNum': 18833, 'OPR': 35.966, 'Auto': 2.291, 'CCWM': -21.144, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 9662, 'OPR': 33.32, 'Auto': 8.808, 'CCWM': 27.625, 'TeamName': 'Apollo'}, {'TeamNum': 20669, 'OPR': 32.359, 'Auto': 3.389, 'CCWM': 26.353, 'TeamName': 'Build for Change'}, {'TeamNum': 12016, 'OPR': 27.456, 'Auto': 19.808, 'CCWM': 6.777, 'TeamName': 'Mish Mash'}, {'TeamNum': 16473, 'OPR': 24.924, 'Auto': -4.991, 'CCWM': 5.603, 'TeamName': 'SciFighters'}, {'TeamNum': 21850, 'OPR': 20.429, 'Auto': -5.494, 'CCWM': -17.222, 'TeamName': 'ATRobotics'}, {'TeamNum': 22947, 'OPR': 20.054, 'Auto': 0.119, 'CCWM': -3.908, 'TeamName': 'Hydra'}, {'TeamNum': 12363, 'OPR': 15.86, 'Auto': -2.944, 'CCWM': -56.706, 'TeamName': 'OrangeFox'}, {'TeamNum': 11635, 'OPR': 15.518, 'Auto': -6.716, 'CCWM': -25.907, 'TeamName': 'Quack Attack'}, {'TeamNum': 22646, 'OPR': 14.316, 'Auto': 2.548, 'CCWM': -85.674, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 19766, 'OPR': 11.312, 'Auto': 7.259, 'CCWM': -29.661, 'TeamName': 'Velocity'}, {'TeamNum': 14869, 'OPR': 9.305, 'Auto': -2.277, 'CCWM': -44.095, 'TeamName': 'Bomba'}, {'TeamNum': 12797, 'OPR': 6.64, 'Auto': 8.944, 'CCWM': -40.3, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 21770, 'OPR': 4.665, 'Auto': -3.169, 'CCWM': -71.219, 'TeamName': 'HFS'}, {'TeamNum': 12989, 'OPR': -7.526, 'Auto': -3.501, 'CCWM': -27.448, 'TeamName': 'Super Cow'}]
ILMES
[{'TeamNum': 22144, 'OPR': 127.522, 'Auto': 34.055, 'CCWM': 65.773, 'TeamName': 'Deagles'}, {'TeamNum': 15637, 'OPR': 118.525, 'Auto': 25.048, 'CCWM': 77.331, 'TeamName': 'Fata Morgana'}, {'TeamNum': 12201, 'OPR': 95.873, 'Auto': 20.09, 'CCWM': 55.956, 'TeamName': 'TATOOINE'}, {'TeamNum': 11192, 'OPR': 66.196, 'Auto': 6.703, 'CCWM': 31.197, 'TeamName': 'Black Tigers'}, {'TeamNum': 15811, 'OPR': 61.055, 'Auto': 17.684, 'CCWM': 38.481, 'TeamName': 'boosteam'}, {'TeamNum': 11808, 'OPR': 53.94, 'Auto': 12.322, 'CCWM': -12.47, 'TeamName': 'Connection'}, {'TeamNum': 11443, 'OPR': 52.95, 'Auto': -0.673, 'CCWM': 46.087, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 13452, 'OPR': 42.823, 'Auto': 8.983, 'CCWM': 55.854, 'TeamName': 'BTJ'}, {'TeamNum': 15141, 'OPR': 42.759, 'Auto': 4.184, 'CCWM': 58.389, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 11803, 'OPR': 40.617, 'Auto': 7.143, 'CCWM': 9.553, 'TeamName': 'PHOENIX'}, {'TeamNum': 22764, 'OPR': 38.095, 'Auto': 2.327, 'CCWM': -59.99, 'TeamName': 'BAGHEERA'}, {'TeamNum': 18735, 'OPR': 37.952, 'Auto': 7.559, 'CCWM': -3.746, 'TeamName': 'RinGoStar'}, {'TeamNum': 18833, 'OPR': 35.966, 'Auto': 2.291, 'CCWM': -21.144, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 9662, 'OPR': 33.32, 'Auto': 8.808, 'CCWM': 27.625, 'TeamName': 'Apollo'}, {'TeamNum': 20669, 'OPR': 32.359, 'Auto': 3.389, 'CCWM': 26.353, 'TeamName': 'Build for Change'}, {'TeamNum': 12016, 'OPR': 27.456, 'Auto': 19.808, 'CCWM': 6.777, 'TeamName': 'Mish Mash'}, {'TeamNum': 16473, 'OPR': 24.924, 'Auto': -4.991, 'CCWM': 5.603, 'TeamName': 'SciFighters'}, {'TeamNum': 21850, 'OPR': 20.429, 'Auto': -5.494, 'CCWM': -17.222, 'TeamName': 'ATRobotics'}, {'TeamNum': 22947, 'OPR': 20.054, 'Auto': 0.119, 'CCWM': -3.908, 'TeamName': 'Hydra'}, {'TeamNum': 12363, 'OPR': 15.86, 'Auto': -2.944, 'CCWM': -56.706, 'TeamName': 'OrangeFox'}, {'TeamNum': 11635, 'OPR': 15.518, 'Auto': -6.716, 'CCWM': -25.907, 'TeamName': 'Quack Attack'}, {'TeamNum': 22646, 'OPR': 14.316, 'Auto': 2.548, 'CCWM': -85.674, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 19766, 'OPR': 11.312, 'Auto': 7.259, 'CCWM': -29.661, 'TeamName': 'Velocity'}, {'TeamNum': 14869, 'OPR': 9.305, 'Auto': -2.277, 'CCWM': -44.095, 'TeamName': 'Bomba'}, {'TeamNum': 12797, 'OPR': 6.64, 'Auto': 8.944, 'CCWM': -40.3, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 21770, 'OPR': 4.665, 'Auto': -3.169, 'CCWM': -71.219, 'TeamName': 'HFS'}, {'TeamNum': 12989, 'OPR': -7.526, 'Auto': -3.501, 'CCWM': -27.448, 'TeamName': 'Super Cow'}]
i 853

i 854
{'16388', '16818', '21827', '22322', '21704', '22466', '21837', '20746', '21735', '22372', '22413', '22458', '22815', '22842', '22728', '6584'}
[{'TeamNum': 21735, 'OPR': 54.649, 'Auto': 4.605, 'CCWM': 29.38, 'TeamName': 'Nautilus'}, {'TeamNum': 6584, 'OPR': 50.316, 'Auto': 6.968, 'CCWM': 37.539, 'TeamName': 'Rhinos'}, {'TeamNum': 16388, 'OPR': 44.977, 'Auto': 16.965, 'CCWM': 14.692, 'TeamName': 'PrepaTec - Megabyte'}, {'TeamNum': 21827, 'OPR': 43.413, 'Auto': -1.478, 'CCWM': 19.805, 'TeamName': 'Sputnik'}, {'TeamNum': 22815, 'OPR': 40.812, 'Auto': 1.828, 'CCWM': 5.766, 'TeamName': 'Taman Keet'}, {'TeamNum': 21837, 'OPR': 38.889, 'Auto': 0.354, 'CCWM': 6.238, 'TeamName': 'DonkPink II'}, {'TeamNum': 22322, 'OPR': 31.584, 'Auto': -2.248, 'CCWM': 17.753, 'TeamName': 'BearsRobotics'}, {'TeamNum': 22372, 'OPR': 27.807, 'Auto': 3.596, 'CCWM': -19.064, 'TeamName': 'PrepaTec - Resistors'}, {'TeamNum': 16818, 'OPR': 25.26, 'Auto': 8.083, 'CCWM': 9.006, 'TeamName': 'Hype-Birds'}, {'TeamNum': 21704, 'OPR': 24.563, 'Auto': -1.042, 'CCWM': -1.841, 'TeamName': 'Lobos Negros'}, {'TeamNum': 22842, 'OPR': 21.771, 'Auto': 1.66, 'CCWM': -10.37, 'TeamName': 'Hype-Xolotls'}, {'TeamNum': 22458, 'OPR': 20.012, 'Auto': -2.927, 'CCWM': 9.221, 'TeamName': 'BEAVERS'}, {'TeamNum': 22413, 'OPR': 14.134, 'Auto': 0.0, 'CCWM': -11.476, 'TeamName': 'Tecmilenio Robotics'}, {'TeamNum': 20746, 'OPR': 11.655, 'Auto': -1.479, 'CCWM': -42.322, 'TeamName': 'Humanitree School'}, {'TeamNum': 22728, 'OPR': 11.266, 'Auto': -1.11, 'CCWM': -38.304, 'TeamName': 'JM RHINOS '}, {'TeamNum': 22466, 'OPR': 7.692, 'Auto': 2.223, 'CCWM': -26.024, 'TeamName': 'Rhinos UP!'}]
MXCMSQ
[{'TeamNum': 21735, 'OPR': 54.649, 'Auto': 4.605, 'CCWM': 29.38, 'TeamName': 'Nautilus'}, {'TeamNum': 6584, 'OPR': 50.316, 'Auto': 6.968, 'CCWM': 37.539, 'TeamName': 'Rhinos'}, {'TeamNum': 16388, 'OPR': 44.977, 'Auto': 16.965, 'CCWM': 14.692, 'TeamName': 'PrepaTec - Megabyte'}, {'TeamNum': 21827, 'OPR': 43.413, 'Auto': -1.478, 'CCWM': 19.805, 'TeamName': 'Sputnik'}, {'TeamNum': 22815, 'OPR': 40.812, 'Auto': 1.828, 'CCWM': 5.766, 'TeamName': 'Taman Keet'}, {'TeamNum': 21837, 'OPR': 38.889, 'Auto': 0.354, 'CCWM': 6.238, 'TeamName': 'DonkPink II'}, {'TeamNum': 22322, 'OPR': 31.584, 'Auto': -2.248, 'CCWM': 17.753, 'TeamName': 'BearsRobotics'}, {'TeamNum': 22372, 'OPR': 27.807, 'Auto': 3.596, 'CCWM': -19.064, 'TeamName': 'PrepaTec - Resistors'}, {'TeamNum': 16818, 'OPR': 25.26, 'Auto': 8.083, 'CCWM': 9.006, 'TeamName': 'Hype-Birds'}, {'TeamNum': 21704, 'OPR': 24.563, 'Auto': -1.042, 'CCWM': -1.841, 'TeamName': 'Lobos Negros'}, {'TeamNum': 22842, 'OPR': 21.771, 'Auto': 1.66, 'CCWM': -10.37, 'TeamName': 'Hype-Xolotls'}, {'TeamNum': 22458, 'OPR': 20.012, 'Auto': -2.927, 'CCWM': 9.221, 'TeamName': 'BEAVERS'}, {'TeamNum': 22413, 'OPR': 14.134, 'Auto': 0.0, 'CCWM': -11.476, 'TeamName': 'Tecmilenio Robotics'}, {'TeamNum': 20746, 'OPR': 11.655, 'Auto': -1.479, 'CCWM': -42.322, 'TeamName': 'Humanitree School'}, {'TeamNum': 22728, 'OPR': 11.266, 'Auto': -1.11, 'CCWM': -38.304, 'TeamName': 'JM RHINOS '}, {'TeamNum': 22466, 'OPR': 7.692, 'Auto': 2.223, 'CCWM': -26.024, 'TeamName': 'Rhinos UP!'}]
i 855
{'18859', '21651', '10918', '3954', '21905', '22227', '18710', '21658', '21904', '16410', '22042', '16441', '17652', '21349', '22020', '17258', '18700'}
[{'TeamNum': 10918, 'OPR': 83.251, 'Auto': 19.115, 'CCWM': 52.181, 'TeamName': 'SPACE'}, {'TeamNum': 22042, 'OPR': 79.147, 'Auto': 25.296, 'CCWM': 50.362, 'TeamName': 'Lituanica X'}, {'TeamNum': 18710, 'OPR': 72.362, 'Auto': 16.313, 'CCWM': 35.491, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 16410, 'OPR': 60.539, 'Auto': 3.108, 'CCWM': 52.979, 'TeamName': 'GentleBotz'}, {'TeamNum': 16441, 'OPR': 46.039, 'Auto': 6.122, 'CCWM': 26.762, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 3954, 'OPR': 43.412, 'Auto': 14.404, 'CCWM': 3.169, 'TeamName': 'Pink to the Future'}, {'TeamNum': 21658, 'OPR': 41.128, 'Auto': 5.839, 'CCWM': 0.004, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 22020, 'OPR': 30.953, 'Auto': 8.493, 'CCWM': 3.291, 'TeamName': 'Gymnasium Haganum'}, {'TeamNum': 21905, 'OPR': 24.769, 'Auto': 1.261, 'CCWM': -30.282, 'TeamName': 'BCS Vikings '}, {'TeamNum': 17652, 'OPR': 21.825, 'Auto': 12.883, 'CCWM': -20.49, 'TeamName': 'Delta'}, {'TeamNum': 22227, 'OPR': 20.259, 'Auto': 5.095, 'CCWM': -26.635, 'TeamName': 'Cyber Bears'}, {'TeamNum': 18859, 'OPR': 17.254, 'Auto': -7.204, 'CCWM': 2.403, 'TeamName': 'Stanislas Tech Team'}, {'TeamNum': 18700, 'OPR': 16.842, 'Auto': 0.912, 'CCWM': -21.316, 'TeamName': 'Iactate Altius'}, {'TeamNum': 21349, 'OPR': 16.161, 'Auto': -2.16, 'CCWM': -17.77, 'TeamName': 'Screw Looose Scientists'}, {'TeamNum': 21651, 'OPR': 13.516, 'Auto': 2.703, 'CCWM': -27.007, 'TeamName': 'Thunder Kites'}, {'TeamNum': 21904, 'OPR': 11.631, 'Auto': -0.049, 'CCWM': -49.141, 'TeamName': 'HighLand'}, {'TeamNum': 17258, 'OPR': 10.762, 'Auto': 5.187, 'CCWM': -28.953, 'TeamName': 'The Scrapyard-Warriors'}]
NLNLM5
[{'TeamNum': 10918, 'OPR': 83.251, 'Auto': 19.115, 'CCWM': 52.181, 'TeamName': 'SPACE'}, {'TeamNum': 22042, 'OPR': 79.147, 'Auto': 25.296, 'CCWM': 50.362, 'TeamName': 'Lituanica X'}, {'TeamNum': 18710, 'OPR': 72.362, 'Auto': 16.313, 'CCWM': 35.491, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 16410, 'OPR': 60.539, 'Auto': 3.108, 'CCWM': 52.979, 'TeamName': 'GentleBotz'}, {'TeamNum': 16441, 'OPR': 46.039, 'Auto': 6.122, 'CCWM': 26.762, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 3954, 'OPR': 43.412, 'Auto': 14.404, 'CCWM': 3.169, 'TeamName': 'Pink to the Future'}, {'TeamNum': 21658, 'OPR': 41.128, 'Auto': 5.839, 'CCWM': 0.004, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 22020, 'OPR': 30.953, 'Auto': 8.493, 'CCWM': 3.291, 'TeamName': 'Gymnasium Haganum'}, {'TeamNum': 21905, 'OPR': 24.769, 'Auto': 1.261, 'CCWM': -30.282, 'TeamName': 'BCS Vikings '}, {'TeamNum': 17652, 'OPR': 21.825, 'Auto': 12.883, 'CCWM': -20.49, 'TeamName': 'Delta'}, {'TeamNum': 22227, 'OPR': 20.259, 'Auto': 5.095, 'CCWM': -26.635, 'TeamName': 'Cyber Bears'}, {'TeamNum': 18859, 'OPR': 17.254, 'Auto': -7.204, 'CCWM': 2.403, 'TeamName': 'Stanislas Tech Team'}, {'TeamNum': 18700, 'OPR': 16.842, 'Auto': 0.912, 'CCWM': -21.316, 'TeamName': 'Iactate Altius'}, {'TeamNum': 21349, 'OPR': 16.161, 'Auto': -2.16, 'CCWM': -17.77, 'TeamName': 'Screw Looose Scientists'}, {'TeamNum': 21651, 'OPR': 13.516, 'Auto': 2.703, 'CCWM': -27.007, 'TeamName': 'Thunder Kites'}, {'TeamNum': 21904, 'OPR': 11.631, 'Auto': -0.049, 'CCWM': -49.141, 'TeamName': 'HighLand'}, {'TeamNum': 17258, 'OPR': 10.762, 'Auto': 5.187, 'CCWM': -28.953, 'TeamName': 'The Scrapyard-Warriors'}]
i 856
i 857
{'12791', '11542', '17423', '20979', '19564', '21394', '14491', '18664', '21171'}
[{'TeamNum': 14491, 'OPR': 89.368, 'Auto': 18.263, 'CCWM': 38.48, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 21394, 'OPR': 47.868, 'Auto': -1.237, 'CCWM': 71.105, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 20979, 'OPR': 39.921, 'Auto': 3.658, 'CCWM': -8.487, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 19564, 'OPR': 37.263, 'Auto': 7.474, 'CCWM': 22.664, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 18664, 'OPR': 34.395, 'Auto': 6.711, 'CCWM': 35.934, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 11542, 'OPR': 31.763, 'Auto': -0.026, 'CCWM': -11.461, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 21171, 'OPR': 29.921, 'Auto': 16.658, 'CCWM': -38.237, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 17423, 'OPR': 10.526, 'Auto': -4.053, 'CCWM': -55.046, 'TeamName': 'FTC Gigawatts'}, {'TeamNum': 12791, 'OPR': -0.895, 'Auto': 23.789, 'CCWM': -82.309, 'TeamName': 'Iterative Intentions'}]
USALFPS
[{'TeamNum': 14491, 'OPR': 89.368, 'Auto': 18.263, 'CCWM': 38.48, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 21394, 'OPR': 47.868, 'Auto': -1.237, 'CCWM': 71.105, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 20979, 'OPR': 39.921, 'Auto': 3.658, 'CCWM': -8.487, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 19564, 'OPR': 37.263, 'Auto': 7.474, 'CCWM': 22.664, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 18664, 'OPR': 34.395, 'Auto': 6.711, 'CCWM': 35.934, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 11542, 'OPR': 31.763, 'Auto': -0.026, 'CCWM': -11.461, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 21171, 'OPR': 29.921, 'Auto': 16.658, 'CCWM': -38.237, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 17423, 'OPR': 10.526, 'Auto': -4.053, 'CCWM': -55.046, 'TeamName': 'FTC Gigawatts'}, {'TeamNum': 12791, 'OPR': -0.895, 'Auto': 23.789, 'CCWM': -82.309, 'TeamName': 'Iterative Intentions'}]
i 858

{'22257', '7716', '22120', '10369', '22265', '3666', '20098', '14624', '12241', '11980', '15135', '18421', '10111', '22256', '20679', '22081', '20775', '15058', '19816', '18420', '22258', '10246', '13968', '15477'}
[{'TeamNum': 18420, 'OPR': 99.748, 'Auto': 18.044, 'CCWM': 86.648, 'TeamName': 'Metal Masters'}, {'TeamNum': 3666, 'OPR': 64.494, 'Auto': 9.306, 'CCWM': 37.996, 'TeamName': 'Hawks Robotics'}, {'TeamNum': 18421, 'OPR': 64.355, 'Auto': 23.981, 'CCWM': 58.781, 'TeamName': 'Unscheduled Disassembly'}, {'TeamNum': 15477, 'OPR': 56.465, 'Auto': 18.95, 'CCWM': 45.957, 'TeamName': 'Robo-Assemblers'}, {'TeamNum': 22120, 'OPR': 55.401, 'Auto': 21.968, 'CCWM': 37.125, 'TeamName': 'Foothills Cat - 3'}, {'TeamNum': 10246, 'OPR': 48.071, 'Auto': -3.799, 'CCWM': 25.705, 'TeamName': 'The Midnight Cicadas'}, {'TeamNum': 15135, 'OPR': 37.043, 'Auto': 11.395, 'CCWM': -0.47, 'TeamName': 'Venom'}, {'TeamNum': 19816, 'OPR': 35.642, 'Auto': 1.723, 'CCWM': -10.503, 'TeamName': 'IronEagles '}, {'TeamNum': 14624, 'OPR': 32.647, 'Auto': 2.633, 'CCWM': 7.258, 'TeamName': 'Cat-astrophic Byte - Jaguar Robotics'}, {'TeamNum': 12241, 'OPR': 27.284, 'Auto': -0.408, 'CCWM': 2.881, 'TeamName': 'Panther Robotics'}, {'TeamNum': 10369, 'OPR': 26.015, 'Auto': 4.183, 'CCWM': -11.665, 'TeamName': 'Robosapiens'}, {'TeamNum': 11980, 'OPR': 25.65, 'Auto': 5.445, 'CCWM': -5.216, 'TeamName': 'Team Viper'}, {'TeamNum': 22257, 'OPR': 23.972, 'Auto': 5.751, 'CCWM': -23.265, 'TeamName': 'Herobotix Spar-Tech'}, {'TeamNum': 7716, 'OPR': 21.507, 'Auto': 2.185, 'CCWM': -13.694, 'TeamName': 'Knight Tech Robotics'}, {'TeamNum': 22258, 'OPR': 20.057, 'Auto': 1.481, 'CCWM': -18.313, 'TeamName': 'Herobotix Beanie Bots'}, {'TeamNum': 20098, 'OPR': 19.916, 'Auto': 2.697, 'CCWM': -1.922, 'TeamName': 'Knight Tech Robotics 2'}, {'TeamNum': 10111, 'OPR': 13.51, 'Auto': 0.657, 'CCWM': -25.415, 'TeamName': 'Herberger Javelinas'}, {'TeamNum': 20775, 'OPR': 12.447, 'Auto': 2.608, 'CCWM': -11.269, 'TeamName': 'Pinnacle Robotics'}, {'TeamNum': 15058, 'OPR': 10.624, 'Auto': 3.02, 'CCWM': -22.112, 'TeamName': 'RoboJags'}, {'TeamNum': 13968, 'OPR': 8.521, 'Auto': 3.618, 'CCWM': -42.164, 'TeamName': 'Herberger Howlers'}, {'TeamNum': 22256, 'OPR': 8.466, 'Auto': -4.316, 'CCWM': -18.05, 'TeamName': 'Herobotix C.I.S.'}, {'TeamNum': 20679, 'OPR': 5.773, 'Auto': 11.515, 'CCWM': -30.049, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 22265, 'OPR': 2.464, 'Auto': 2.62, 'CCWM': -28.715, 'TeamName': 'Gear Hounds'}, {'TeamNum': 22081, 'OPR': -2.47, 'Auto': -4.858, 'CCWM': -39.529, 'TeamName': 'Knight Tech Robotics 3'}]
USAZQCQ
[{'TeamNum': 18420, 'OPR': 99.748, 'Auto': 18.044, 'CCWM': 86.648, 'TeamName': 'Metal Masters'}, {'TeamNum': 3666, 'OPR': 64.494, 'Auto': 9.306, 'CCWM': 37.996, 'TeamName': 'Hawks Robotics'}, {'TeamNum': 18421, 'OPR': 64.355, 'Auto': 23.981, 'CCWM': 58.781, 'TeamName': 'Unscheduled Disassembly'}, {'TeamNum': 15477, 'OPR': 56.465, 'Auto': 18.95, 'CCWM': 45.957, 'TeamName': 'Robo-Assemblers'}, {'TeamNum': 22120, 'OPR': 55.401, 'Auto': 21.968, 'CCWM': 37.125, 'TeamName': 'Foothills Cat - 3'}, {'TeamNum': 10246, 'OPR': 48.071, 'Auto': -3.799, 'CCWM': 25.705, 'TeamName': 'The Midnight Cicadas'}, {'TeamNum': 15135, 'OPR': 37.043, 'Auto': 11.395, 'CCWM': -0.47, 'TeamName': 'Venom'}, {'TeamNum': 19816, 'OPR': 35.642, 'Auto': 1.723, 'CCWM': -10.503, 'TeamName': 'IronEagles '}, {'TeamNum': 14624, 'OPR': 32.647, 'Auto': 2.633, 'CCWM': 7.258, 'TeamName': 'Cat-astrophic Byte - Jaguar Robotics'}, {'TeamNum': 12241, 'OPR': 27.284, 'Auto': -0.408, 'CCWM': 2.881, 'TeamName': 'Panther Robotics'}, {'TeamNum': 10369, 'OPR': 26.015, 'Auto': 4.183, 'CCWM': -11.665, 'TeamName': 'Robosapiens'}, {'TeamNum': 11980, 'OPR': 25.65, 'Auto': 5.445, 'CCWM': -5.216, 'TeamName': 'Team Viper'}, {'TeamNum': 22257, 'OPR': 23.972, 'Auto': 5.751, 'CCWM': -23.265, 'TeamName': 'Herobotix Spar-Tech'}, {'TeamNum': 7716, 'OPR': 21.507, 'Auto': 2.185, 'CCWM': -13.694, 'TeamName': 'Knight Tech Robotics'}, {'TeamNum': 22258, 'OPR': 20.057, 'Auto': 1.481, 'CCWM': -18.313, 'TeamName': 'Herobotix Beanie Bots'}, {'TeamNum': 20098, 'OPR': 19.916, 'Auto': 2.697, 'CCWM': -1.922, 'TeamName': 'Knight Tech Robotics 2'}, {'TeamNum': 10111, 'OPR': 13.51, 'Auto': 0.657, 'CCWM': -25.415, 'TeamName': 'Herberger Javelinas'}, {'TeamNum': 20775, 'OPR': 12.447, 'Auto': 2.608, 'CCWM': -11.269, 'TeamName': 'Pinnacle Robotics'}, {'TeamNum': 15058, 'OPR': 10.624, 'Auto': 3.02, 'CCWM': -22.112, 'TeamName': 'RoboJags'}, {'TeamNum': 13968, 'OPR': 8.521, 'Auto': 3.618, 'CCWM': -42.164, 'TeamName': 'Herberger Howlers'}, {'TeamNum': 22256, 'OPR': 8.466, 'Auto': -4.316, 'CCWM': -18.05, 'TeamName': 'Herobotix C.I.S.'}, {'TeamNum': 20679, 'OPR': 5.773, 'Auto': 11.515, 'CCWM': -30.049, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 22265, 'OPR': 2.464, 'Auto': 2.62, 'CCWM': -28.715, 'TeamName': 'Gear Hounds'}, {'TeamNum': 22081, 'OPR': -2.47, 'Auto': -4.858, 'CCWM': -39.529, 'TeamName': 'Knight Tech Robotics 3'}]
i 859
{'8081', '201', '13910', '15186', '16817', '17062', '18312', '202', '21329', '22295', '7156', '14835', '18445', '7613', '19728', '12604', '5661'}
[{'TeamNum': 21329, 'OPR': 108.369, 'Auto': 24.47, 'CCWM': 71.999, 'TeamName': 'Squires of the Lab Table'}, {'TeamNum': 14835, 'OPR': 76.246, 'Auto': 24.359, 'CCWM': 59.91, 'TeamName': 'Tie-Dye Samurai'}, {'TeamNum': 19728, 'OPR': 66.698, 'Auto': 2.385, 'CCWM': 44.321, 'TeamName': 'Carbo-Knights'}, {'TeamNum': 8081, 'OPR': 55.857, 'Auto': 14.893, 'CCWM': 4.566, 'TeamName': 'Knights of the Lab Table'}, {'TeamNum': 17062, 'OPR': 46.533, 'Auto': 15.391, 'CCWM': 3.386, 'TeamName': 'Girls in Tech / Girl Scout - Techalongs'}, {'TeamNum': 22295, 'OPR': 42.816, 'Auto': 0.488, 'CCWM': 6.967, 'TeamName': 'Power Outage'}, {'TeamNum': 16817, 'OPR': 37.496, 'Auto': -3.537, 'CCWM': -5.508, 'TeamName': 'Rocksisaan Tech'}, {'TeamNum': 202, 'OPR': 37.114, 'Auto': 0.925, 'CCWM': 22.338, 'TeamName': 'BroncoBotsTOO'}, {'TeamNum': 13910, 'OPR': 30.772, 'Auto': 2.066, 'CCWM': 18.175, 'TeamName': 'Voltage'}, {'TeamNum': 7156, 'OPR': 29.471, 'Auto': 7.007, 'CCWM': 4.096, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 7613, 'OPR': 20.911, 'Auto': 3.79, 'CCWM': 8.054, 'TeamName': 'Sinagua Robotics'}, {'TeamNum': 15186, 'OPR': 15.267, 'Auto': 2.364, 'CCWM': -38.004, 'TeamName': 'Falcon Robotics'}, {'TeamNum': 5661, 'OPR': 15.026, 'Auto': -2.144, 'CCWM': -37.303, 'TeamName': 'Wolves Robotics 1'}, {'TeamNum': 201, 'OPR': 6.403, 'Auto': 13.281, 'CCWM': -17.352, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 18445, 'OPR': 2.136, 'Auto': -2.908, 'CCWM': -49.536, 'TeamName': 'BinaryBots'}, {'TeamNum': 18312, 'OPR': -5.709, 'Auto': -2.83, 'CCWM': -65.455, 'TeamName': 'Da Geese of Freedom'}, {'TeamNum': 12604, 'OPR': -7.383, 'Auto': 1.36, 'CCWM': -49.433, 'TeamName': 'Tiger Blue'}]
USAZCHQ2
[{'TeamNum': 21329, 'OPR': 108.369, 'Auto': 24.47, 'CCWM': 71.999, 'TeamName': 'Squires of the Lab Table'}, {'TeamNum': 14835, 'OPR': 76.246, 'Auto': 24.359, 'CCWM': 59.91, 'TeamName': 'Tie-Dye Samurai'}, {'TeamNum': 19728, 'OPR': 66.698, 'Auto': 2.385, 'CCWM': 44.321, 'TeamName': 'Carbo-Knights'}, {'TeamNum': 8081, 'OPR': 55.857, 'Auto': 14.893, 'CCWM': 4.566, 'TeamName': 'Knights of the Lab Table'}, {'TeamNum': 17062, 'OPR': 46.533, 'Auto': 15.391, 'CCWM': 3.386, 'TeamName': 'Girls in Tech / Girl Scout - Techalongs'}, {'TeamNum': 22295, 'OPR': 42.816, 'Auto': 0.488, 'CCWM': 6.967, 'TeamName': 'Power Outage'}, {'TeamNum': 16817, 'OPR': 37.496, 'Auto': -3.537, 'CCWM': -5.508, 'TeamName': 'Rocksisaan Tech'}, {'TeamNum': 202, 'OPR': 37.114, 'Auto': 0.925, 'CCWM': 22.338, 'TeamName': 'BroncoBotsTOO'}, {'TeamNum': 13910, 'OPR': 30.772, 'Auto': 2.066, 'CCWM': 18.175, 'TeamName': 'Voltage'}, {'TeamNum': 7156, 'OPR': 29.471, 'Auto': 7.007, 'CCWM': 4.096, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 7613, 'OPR': 20.911, 'Auto': 3.79, 'CCWM': 8.054, 'TeamName': 'Sinagua Robotics'}, {'TeamNum': 15186, 'OPR': 15.267, 'Auto': 2.364, 'CCWM': -38.004, 'TeamName': 'Falcon Robotics'}, {'TeamNum': 5661, 'OPR': 15.026, 'Auto': -2.144, 'CCWM': -37.303, 'TeamName': 'Wolves Robotics 1'}, {'TeamNum': 201, 'OPR': 6.403, 'Auto': 13.281, 'CCWM': -17.352, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 18445, 'OPR': 2.136, 'Auto': -2.908, 'CCWM': -49.536, 'TeamName': 'BinaryBots'}, {'TeamNum': 18312, 'OPR': -5.709, 'Auto': -2.83, 'CCWM': -65.455, 'TeamName': 'Da Geese of Freedom'}, {'TeamNum': 12604, 'OPR': -7.383, 'Auto': 1.36, 'CCWM': -49.433, 'TeamName': 'Tiger Blue'}]
i 860

{'20599', '20540', '20507', '20580', '20597', '20560', '20563', '20541', '20616', '22007', '20629'}
[{'TeamNum': 22007, 'OPR': 46.187, 'Auto': 6.217, 'CCWM': 46.881, 'TeamName': 'Romanoid 20489'}, {'TeamNum': 20540, 'OPR': 30.202, 'Auto': 6.114, 'CCWM': 24.418, 'TeamName': 'John C. Fremont H.S. 2'}, {'TeamNum': 20629, 'OPR': 22.394, 'Auto': 3.623, 'CCWM': 19.784, 'TeamName': 'Rancho Dominguez Preparatory School'}, {'TeamNum': 20580, 'OPR': 16.026, 'Auto': 3.636, 'CCWM': -3.49, 'TeamName': 'Girls Academic Leadership Academy 1'}, {'TeamNum': 20599, 'OPR': 13.819, 'Auto': 1.252, 'CCWM': -1.627, 'TeamName': 'Palms Gifted / High Ability Magnet 2'}, {'TeamNum': 20597, 'OPR': 12.205, 'Auto': -0.236, 'CCWM': -6.223, 'TeamName': 'Palms Gifted / High Ability Magnet 1'}, {'TeamNum': 20563, 'OPR': 12.101, 'Auto': 4.119, 'CCWM': -7.802, 'TeamName': 'Alexander Hamilton 2'}, {'TeamNum': 20560, 'OPR': 11.225, 'Auto': -1.736, 'CCWM': -9.855, 'TeamName': 'Alexander Hamilton 1'}, {'TeamNum': 20541, 'OPR': 10.066, 'Auto': 1.093, 'CCWM': -12.318, 'TeamName': 'John C. Fremont H.S. 1'}, {'TeamNum': 20507, 'OPR': 8.26, 'Auto': -3.465, 'CCWM': -18.531, 'TeamName': 'Joseph Le Conte Middle School 1'}, {'TeamNum': 20616, 'OPR': -5.726, 'Auto': -3.768, 'CCWM': -29.993, 'TeamName': 'Nathaniel Narbonne High School'}]
USCALSLAQ3
[{'TeamNum': 22007, 'OPR': 46.187, 'Auto': 6.217, 'CCWM': 46.881, 'TeamName': 'Romanoid 20489'}, {'TeamNum': 20540, 'OPR': 30.202, 'Auto': 6.114, 'CCWM': 24.418, 'TeamName': 'John C. Fremont H.S. 2'}, {'TeamNum': 20629, 'OPR': 22.394, 'Auto': 3.623, 'CCWM': 19.784, 'TeamName': 'Rancho Dominguez Preparatory School'}, {'TeamNum': 20580, 'OPR': 16.026, 'Auto': 3.636, 'CCWM': -3.49, 'TeamName': 'Girls Academic Leadership Academy 1'}, {'TeamNum': 20599, 'OPR': 13.819, 'Auto': 1.252, 'CCWM': -1.627, 'TeamName': 'Palms Gifted / High Ability Magnet 2'}, {'TeamNum': 20597, 'OPR': 12.205, 'Auto': -0.236, 'CCWM': -6.223, 'TeamName': 'Palms Gifted / High Ability Magnet 1'}, {'TeamNum': 20563, 'OPR': 12.101, 'Auto': 4.119, 'CCWM': -7.802, 'TeamName': 'Alexander Hamilton 2'}, {'TeamNum': 20560, 'OPR': 11.225, 'Auto': -1.736, 'CCWM': -9.855, 'TeamName': 'Alexander Hamilton 1'}, {'TeamNum': 20541, 'OPR': 10.066, 'Auto': 1.093, 'CCWM': -12.318, 'TeamName': 'John C. Fremont H.S. 1'}, {'TeamNum': 20507, 'OPR': 8.26, 'Auto': -3.465, 'CCWM': -18.531, 'TeamName': 'Joseph Le Conte Middle School 1'}, {'TeamNum': 20616, 'OPR': -5.726, 'Auto': -3.768, 'CCWM': -29.993, 'TeamName': 'Nathaniel Narbonne High School'}]
i 861
{'14493', '8625', '6949', '16278', '8367', '16481', '21776', '21964', '4998', '22025', '16944', '6286'}
[{'TeamNum': 21776, 'OPR': 75.923, 'Auto': 17.932, 'CCWM': 42.215, 'TeamName': 'TechnoCali'}, {'TeamNum': 14493, 'OPR': 62.816, 'Auto': 8.681, 'CCWM': 42.261, 'TeamName': 'Comet BOTs'}, {'TeamNum': 16481, 'OPR': 50.599, 'Auto': 14.479, 'CCWM': 3.318, 'TeamName': 'Robo Racers'}, {'TeamNum': 6286, 'OPR': 43.558, 'Auto': 12.604, 'CCWM': -6.187, 'TeamName': 'Falcon Hi Flyers'}, {'TeamNum': 16944, 'OPR': 26.483, 'Auto': 12.29, 'CCWM': -17.803, 'TeamName': 'FM493RS'}, {'TeamNum': 21964, 'OPR': 25.247, 'Auto': 3.347, 'CCWM': 17.5, 'TeamName': 'The Reavers'}, {'TeamNum': 8625, 'OPR': 24.244, 'Auto': 4.804, 'CCWM': -3.628, 'TeamName': 'RHS Robotix'}, {'TeamNum': 8367, 'OPR': 21.804, 'Auto': 2.927, 'CCWM': -7.3, 'TeamName': 'ACME Robotics'}, {'TeamNum': 4998, 'OPR': 17.883, 'Auto': 1.09, 'CCWM': -5.203, 'TeamName': 'SPQR - Senātus Populusque Rōboticus'}, {'TeamNum': 6949, 'OPR': 15.073, 'Auto': -0.319, 'CCWM': -24.327, 'TeamName': 'Einstein Eagles'}, {'TeamNum': 22025, 'OPR': 14.096, 'Auto': -0.428, 'CCWM': -20.028, 'TeamName': 'Team Rrooar 2022'}, {'TeamNum': 16278, 'OPR': 4.476, 'Auto': 0.793, 'CCWM': -20.82, 'TeamName': 'LogiLift'}]
USCANONELT
[{'TeamNum': 21776, 'OPR': 75.923, 'Auto': 17.932, 'CCWM': 42.215, 'TeamName': 'TechnoCali'}, {'TeamNum': 14493, 'OPR': 62.816, 'Auto': 8.681, 'CCWM': 42.261, 'TeamName': 'Comet BOTs'}, {'TeamNum': 16481, 'OPR': 50.599, 'Auto': 14.479, 'CCWM': 3.318, 'TeamName': 'Robo Racers'}, {'TeamNum': 6286, 'OPR': 43.558, 'Auto': 12.604, 'CCWM': -6.187, 'TeamName': 'Falcon Hi Flyers'}, {'TeamNum': 16944, 'OPR': 26.483, 'Auto': 12.29, 'CCWM': -17.803, 'TeamName': 'FM493RS'}, {'TeamNum': 21964, 'OPR': 25.247, 'Auto': 3.347, 'CCWM': 17.5, 'TeamName': 'The Reavers'}, {'TeamNum': 8625, 'OPR': 24.244, 'Auto': 4.804, 'CCWM': -3.628, 'TeamName': 'RHS Robotix'}, {'TeamNum': 8367, 'OPR': 21.804, 'Auto': 2.927, 'CCWM': -7.3, 'TeamName': 'ACME Robotics'}, {'TeamNum': 4998, 'OPR': 17.883, 'Auto': 1.09, 'CCWM': -5.203, 'TeamName': 'SPQR - Senātus Populusque Rōboticus'}, {'TeamNum': 6949, 'OPR': 15.073, 'Auto': -0.319, 'CCWM': -24.327, 'TeamName': 'Einstein Eagles'}, {'TeamNum': 22025, 'OPR': 14.096, 'Auto': -0.428, 'CCWM': -20.028, 'TeamName': 'Team Rrooar 2022'}, {'TeamNum': 16278, 'OPR': 4.476, 'Auto': 0.793, 'CCWM': -20.82, 'TeamName': 'LogiLift'}]
i 862
{'20539', '22117', '22863', '20556', '20530', '20593', '20538', '20520', '20442', '20594', '20617', '20526', '20598', '20519'}
[{'TeamNum': 20520, 'OPR': 39.622, 'Auto': -0.025, 'CCWM': 36.95, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 2'}, {'TeamNum': 20556, 'OPR': 35.284, 'Auto': -0.211, 'CCWM': 24.248, 'TeamName': 'Dr. Maya Angelou Community High School'}, {'TeamNum': 20519, 'OPR': 25.414, 'Auto': -0.255, 'CCWM': 19.317, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 1'}, {'TeamNum': 22117, 'OPR': 21.18, 'Auto': 1.916, 'CCWM': -1.075, 'TeamName': 'Mekanica'}, {'TeamNum': 20539, 'OPR': 20.903, 'Auto': 0.189, 'CCWM': 9.615, 'TeamName': 'El Sereno MS 2'}, {'TeamNum': 20530, 'OPR': 16.691, 'Auto': 0.817, 'CCWM': -4.622, 'TeamName': 'Lincoln High School 2'}, {'TeamNum': 20526, 'OPR': 15.563, 'Auto': 0.537, 'CCWM': 1.075, 'TeamName': 'Lincoln High School 1'}, {'TeamNum': 20594, 'OPR': 13.691, 'Auto': 0.423, 'CCWM': -1.459, 'TeamName': 'Maywood Center for Enriched Studies 1'}, {'TeamNum': 22863, 'OPR': 12.126, 'Auto': -0.225, 'CCWM': 0.829, 'TeamName': 'Huntington Park HS STEAM Magnet'}, {'TeamNum': 20538, 'OPR': 7.427, 'Auto': 0.623, 'CCWM': -19.936, 'TeamName': 'El Sereno MS 1'}, {'TeamNum': 20617, 'OPR': 6.156, 'Auto': 0.027, 'CCWM': -13.382, 'TeamName': 'Nava College Preparatory Academy 1'}, {'TeamNum': 20593, 'OPR': 5.864, 'Auto': -0.209, 'CCWM': -23.514, 'TeamName': 'Maywood Center for Enriched Studies 2'}, {'TeamNum': 20442, 'OPR': 5.757, 'Auto': 0.299, 'CCWM': -14.401, 'TeamName': 'MAYWOOD ACADEMY HIGH SCHOOL'}, {'TeamNum': 20598, 'OPR': 1.155, 'Auto': 0.426, 'CCWM': -13.645, 'TeamName': 'Pacoima Middle School'}]
USCALSLAQ2
[{'TeamNum': 20520, 'OPR': 39.622, 'Auto': -0.025, 'CCWM': 36.95, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 2'}, {'TeamNum': 20556, 'OPR': 35.284, 'Auto': -0.211, 'CCWM': 24.248, 'TeamName': 'Dr. Maya Angelou Community High School'}, {'TeamNum': 20519, 'OPR': 25.414, 'Auto': -0.255, 'CCWM': 19.317, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 1'}, {'TeamNum': 22117, 'OPR': 21.18, 'Auto': 1.916, 'CCWM': -1.075, 'TeamName': 'Mekanica'}, {'TeamNum': 20539, 'OPR': 20.903, 'Auto': 0.189, 'CCWM': 9.615, 'TeamName': 'El Sereno MS 2'}, {'TeamNum': 20530, 'OPR': 16.691, 'Auto': 0.817, 'CCWM': -4.622, 'TeamName': 'Lincoln High School 2'}, {'TeamNum': 20526, 'OPR': 15.563, 'Auto': 0.537, 'CCWM': 1.075, 'TeamName': 'Lincoln High School 1'}, {'TeamNum': 20594, 'OPR': 13.691, 'Auto': 0.423, 'CCWM': -1.459, 'TeamName': 'Maywood Center for Enriched Studies 1'}, {'TeamNum': 22863, 'OPR': 12.126, 'Auto': -0.225, 'CCWM': 0.829, 'TeamName': 'Huntington Park HS STEAM Magnet'}, {'TeamNum': 20538, 'OPR': 7.427, 'Auto': 0.623, 'CCWM': -19.936, 'TeamName': 'El Sereno MS 1'}, {'TeamNum': 20617, 'OPR': 6.156, 'Auto': 0.027, 'CCWM': -13.382, 'TeamName': 'Nava College Preparatory Academy 1'}, {'TeamNum': 20593, 'OPR': 5.864, 'Auto': -0.209, 'CCWM': -23.514, 'TeamName': 'Maywood Center for Enriched Studies 2'}, {'TeamNum': 20442, 'OPR': 5.757, 'Auto': 0.299, 'CCWM': -14.401, 'TeamName': 'MAYWOOD ACADEMY HIGH SCHOOL'}, {'TeamNum': 20598, 'OPR': 1.155, 'Auto': 0.426, 'CCWM': -13.645, 'TeamName': 'Pacoima Middle School'}]
i 863

{'11334', '11386', '11337', '21611', '22535', '22549', '11336', '16400', '16401', '11333', '16235', '16234', '11332', '11335', '11385'}
[{'TeamNum': 11337, 'OPR': 103.929, 'Auto': 20.847, 'CCWM': 87.914, 'TeamName': 'Robonauts'}, {'TeamNum': 11336, 'OPR': 47.389, 'Auto': 13.612, 'CCWM': 8.961, 'TeamName': 'Red Snow Robotics'}, {'TeamNum': 16234, 'OPR': 44.377, 'Auto': 2.511, 'CCWM': 15.18, 'TeamName': 'Tekriot'}, {'TeamNum': 16235, 'OPR': 44.209, 'Auto': 17.658, 'CCWM': 13.732, 'TeamName': 'Judicator '}, {'TeamNum': 11334, 'OPR': 40.428, 'Auto': 7.389, 'CCWM': -2.421, 'TeamName': 'Alpha Tech'}, {'TeamNum': 16400, 'OPR': 39.216, 'Auto': 5.543, 'CCWM': 11.884, 'TeamName': 'Rising Phoenix'}, {'TeamNum': 22549, 'OPR': 33.327, 'Auto': 8.381, 'CCWM': -5.513, 'TeamName': 'EVE'}, {'TeamNum': 22535, 'OPR': 27.734, 'Auto': -0.184, 'CCWM': 10.953, 'TeamName': 'Generation BOT'}, {'TeamNum': 11332, 'OPR': 26.506, 'Auto': 6.112, 'CCWM': -5.523, 'TeamName': 'LASERS'}, {'TeamNum': 16401, 'OPR': 25.029, 'Auto': 4.112, 'CCWM': -19.13, 'TeamName': 'The Krakens'}, {'TeamNum': 11335, 'OPR': 22.015, 'Auto': -3.129, 'CCWM': -13.32, 'TeamName': 'Delta Tech'}, {'TeamNum': 11333, 'OPR': 21.19, 'Auto': 9.352, 'CCWM': -42.035, 'TeamName': 'Samurai'}, {'TeamNum': 11386, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Anon0mous'}, {'TeamNum': 11385, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'ChidoriBots'}, {'TeamNum': 21611, 'OPR': -0.213, 'Auto': 0.793, 'CCWM': -46.459, 'TeamName': 'General B'}]
USCALABM3
[{'TeamNum': 11337, 'OPR': 103.929, 'Auto': 20.847, 'CCWM': 87.914, 'TeamName': 'Robonauts'}, {'TeamNum': 11336, 'OPR': 47.389, 'Auto': 13.612, 'CCWM': 8.961, 'TeamName': 'Red Snow Robotics'}, {'TeamNum': 16234, 'OPR': 44.377, 'Auto': 2.511, 'CCWM': 15.18, 'TeamName': 'Tekriot'}, {'TeamNum': 16235, 'OPR': 44.209, 'Auto': 17.658, 'CCWM': 13.732, 'TeamName': 'Judicator '}, {'TeamNum': 11334, 'OPR': 40.428, 'Auto': 7.389, 'CCWM': -2.421, 'TeamName': 'Alpha Tech'}, {'TeamNum': 16400, 'OPR': 39.216, 'Auto': 5.543, 'CCWM': 11.884, 'TeamName': 'Rising Phoenix'}, {'TeamNum': 22549, 'OPR': 33.327, 'Auto': 8.381, 'CCWM': -5.513, 'TeamName': 'EVE'}, {'TeamNum': 22535, 'OPR': 27.734, 'Auto': -0.184, 'CCWM': 10.953, 'TeamName': 'Generation BOT'}, {'TeamNum': 11332, 'OPR': 26.506, 'Auto': 6.112, 'CCWM': -5.523, 'TeamName': 'LASERS'}, {'TeamNum': 16401, 'OPR': 25.029, 'Auto': 4.112, 'CCWM': -19.13, 'TeamName': 'The Krakens'}, {'TeamNum': 11335, 'OPR': 22.015, 'Auto': -3.129, 'CCWM': -13.32, 'TeamName': 'Delta Tech'}, {'TeamNum': 11333, 'OPR': 21.19, 'Auto': 9.352, 'CCWM': -42.035, 'TeamName': 'Samurai'}, {'TeamNum': 11386, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Anon0mous'}, {'TeamNum': 11385, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'ChidoriBots'}, {'TeamNum': 21611, 'OPR': -0.213, 'Auto': 0.793, 'CCWM': -46.459, 'TeamName': 'General B'}]
i 864
{'11898', '16778', '16177', '21666', '16194', '22994', '13216', '6165', '21861', '16247', '19819', '18466', '4943', '21463', '6357', '10320'}
[{'TeamNum': 6165, 'OPR': 127.99, 'Auto': 15.223, 'CCWM': 154.2, 'TeamName': 'MSET CuttleFish'}, {'TeamNum': 19819, 'OPR': 88.569, 'Auto': 14.481, 'CCWM': 34.756, 'TeamName': 'AstroBruins'}, {'TeamNum': 13216, 'OPR': 79.538, 'Auto': 16.277, 'CCWM': 72.43, 'TeamName': 'Deja Vu'}, {'TeamNum': 16778, 'OPR': 70.725, 'Auto': 26.323, 'CCWM': 38.856, 'TeamName': 'Cyber Wizards'}, {'TeamNum': 18466, 'OPR': 70.125, 'Auto': 29.768, 'CCWM': 40.591, 'TeamName': 'Mastermindz'}, {'TeamNum': 6357, 'OPR': 46.158, 'Auto': 26.635, 'CCWM': -21.838, 'TeamName': 'Top Dogs'}, {'TeamNum': 22994, 'OPR': 42.78, 'Auto': 9.043, 'CCWM': 0.952, 'TeamName': 'MateoBotics'}, {'TeamNum': 4943, 'OPR': 33.78, 'Auto': 6.857, 'CCWM': -22.382, 'TeamName': 'RoboFusion'}, {'TeamNum': 16247, 'OPR': 32.63, 'Auto': 6.135, 'CCWM': -27.641, 'TeamName': 'Thor Bots'}, {'TeamNum': 10320, 'OPR': 31.675, 'Auto': 4.621, 'CCWM': 9.351, 'TeamName': 'Project Bulldog'}, {'TeamNum': 21463, 'OPR': 26.373, 'Auto': 5.6, 'CCWM': -8.429, 'TeamName': 'Delta Robotics'}, {'TeamNum': 16177, 'OPR': 26.345, 'Auto': -2.637, 'CCWM': -9.477, 'TeamName': 'Acmatic'}, {'TeamNum': 11898, 'OPR': 26.173, 'Auto': -6.079, 'CCWM': -77.504, 'TeamName': 'Newark Memorial Robuckets'}, {'TeamNum': 16194, 'OPR': 22.517, 'Auto': -0.009, 'CCWM': -31.324, 'TeamName': 'Roses & Rivets'}, {'TeamNum': 21861, 'OPR': -7.283, 'Auto': 5.336, 'CCWM': -58.952, 'TeamName': 'AAA Robotic '}, {'TeamNum': 21666, 'OPR': -7.897, 'Auto': -2.774, 'CCWM': -93.589, 'TeamName': 'HD1_Canis_Hopkins'}]
USCANOFOQ
[{'TeamNum': 6165, 'OPR': 127.99, 'Auto': 15.223, 'CCWM': 154.2, 'TeamName': 'MSET CuttleFish'}, {'TeamNum': 19819, 'OPR': 88.569, 'Auto': 14.481, 'CCWM': 34.756, 'TeamName': 'AstroBruins'}, {'TeamNum': 13216, 'OPR': 79.538, 'Auto': 16.277, 'CCWM': 72.43, 'TeamName': 'Deja Vu'}, {'TeamNum': 16778, 'OPR': 70.725, 'Auto': 26.323, 'CCWM': 38.856, 'TeamName': 'Cyber Wizards'}, {'TeamNum': 18466, 'OPR': 70.125, 'Auto': 29.768, 'CCWM': 40.591, 'TeamName': 'Mastermindz'}, {'TeamNum': 6357, 'OPR': 46.158, 'Auto': 26.635, 'CCWM': -21.838, 'TeamName': 'Top Dogs'}, {'TeamNum': 22994, 'OPR': 42.78, 'Auto': 9.043, 'CCWM': 0.952, 'TeamName': 'MateoBotics'}, {'TeamNum': 4943, 'OPR': 33.78, 'Auto': 6.857, 'CCWM': -22.382, 'TeamName': 'RoboFusion'}, {'TeamNum': 16247, 'OPR': 32.63, 'Auto': 6.135, 'CCWM': -27.641, 'TeamName': 'Thor Bots'}, {'TeamNum': 10320, 'OPR': 31.675, 'Auto': 4.621, 'CCWM': 9.351, 'TeamName': 'Project Bulldog'}, {'TeamNum': 21463, 'OPR': 26.373, 'Auto': 5.6, 'CCWM': -8.429, 'TeamName': 'Delta Robotics'}, {'TeamNum': 16177, 'OPR': 26.345, 'Auto': -2.637, 'CCWM': -9.477, 'TeamName': 'Acmatic'}, {'TeamNum': 11898, 'OPR': 26.173, 'Auto': -6.079, 'CCWM': -77.504, 'TeamName': 'Newark Memorial Robuckets'}, {'TeamNum': 16194, 'OPR': 22.517, 'Auto': -0.009, 'CCWM': -31.324, 'TeamName': 'Roses & Rivets'}, {'TeamNum': 21861, 'OPR': -7.283, 'Auto': 5.336, 'CCWM': -58.952, 'TeamName': 'AAA Robotic '}, {'TeamNum': 21666, 'OPR': -7.897, 'Auto': -2.774, 'CCWM': -93.589, 'TeamName': 'HD1_Canis_Hopkins'}]
i 865
{'5196', '21731', '18660', '13271', '18793', '17302', '16629', '21519', '8641', '7224', '21819', '16975', '17190', '15289', '13879', '21818', '15755', '17300'}
[{'TeamNum': 8641, 'OPR': 66.713, 'Auto': 21.953, 'CCWM': 55.824, 'TeamName': 'The Masters'}, {'TeamNum': 17300, 'OPR': 36.808, 'Auto': 17.15, 'CCWM': -3.543, 'TeamName': 'MPHS TerraMech'}, {'TeamNum': 5196, 'OPR': 31.512, 'Auto': -0.691, 'CCWM': 12.294, 'TeamName': 'Robo Yetis'}, {'TeamNum': 15755, 'OPR': 30.613, 'Auto': 3.128, 'CCWM': 2.293, 'TeamName': 'Conductivity'}, {'TeamNum': 16629, 'OPR': 29.439, 'Auto': 1.664, 'CCWM': 26.469, 'TeamName': 'Box Canyon Bots'}, {'TeamNum': 17190, 'OPR': 29.352, 'Auto': -1.292, 'CCWM': 15.776, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 17302, 'OPR': 29.089, 'Auto': 0.167, 'CCWM': -0.939, 'TeamName': 'Max Resistance'}, {'TeamNum': 7224, 'OPR': 26.947, 'Auto': 0.522, 'CCWM': 8.605, 'TeamName': 'West Grand Robotics-Mechanical Mustangs 1.0'}, {'TeamNum': 13271, 'OPR': 22.943, 'Auto': 0.252, 'CCWM': -4.181, 'TeamName': 'Cowboy Code   "Redneck Robotics"'}, {'TeamNum': 16975, 'OPR': 20.497, 'Auto': 0.794, 'CCWM': -8.881, 'TeamName': 'Brainy Banana Bunch'}, {'TeamNum': 21819, 'OPR': 17.252, 'Auto': 1.813, 'CCWM': -17.658, 'TeamName': 'Durango High School FTC2'}, {'TeamNum': 21731, 'OPR': 16.035, 'Auto': 0.448, 'CCWM': -15.333, 'TeamName': 'Palisade Purussaurus'}, {'TeamNum': 18793, 'OPR': 13.217, 'Auto': 0.19, 'CCWM': -15.722, 'TeamName': 'Mechanical Masters'}, {'TeamNum': 21818, 'OPR': 12.169, 'Auto': -0.323, 'CCWM': -3.236, 'TeamName': 'Durango High School FTC1'}, {'TeamNum': 21519, 'OPR': 10.635, 'Auto': 0.974, 'CCWM': -30.193, 'TeamName': 'Norwood Robotic Masters'}, {'TeamNum': 18660, 'OPR': 9.245, 'Auto': 0.975, 'CCWM': -9.198, 'TeamName': 'RobotoCardinals'}, {'TeamNum': 13879, 'OPR': 8.433, 'Auto': -1.959, 'CCWM': 8.132, 'TeamName': 'EGMS Metal Minds'}, {'TeamNum': 15289, 'OPR': 1.768, 'Auto': 3.736, 'CCWM': -20.509, 'TeamName': 'EGMS Gadgetron'}]
USCOGSQ
[{'TeamNum': 8641, 'OPR': 66.713, 'Auto': 21.953, 'CCWM': 55.824, 'TeamName': 'The Masters'}, {'TeamNum': 17300, 'OPR': 36.808, 'Auto': 17.15, 'CCWM': -3.543, 'TeamName': 'MPHS TerraMech'}, {'TeamNum': 5196, 'OPR': 31.512, 'Auto': -0.691, 'CCWM': 12.294, 'TeamName': 'Robo Yetis'}, {'TeamNum': 15755, 'OPR': 30.613, 'Auto': 3.128, 'CCWM': 2.293, 'TeamName': 'Conductivity'}, {'TeamNum': 16629, 'OPR': 29.439, 'Auto': 1.664, 'CCWM': 26.469, 'TeamName': 'Box Canyon Bots'}, {'TeamNum': 17190, 'OPR': 29.352, 'Auto': -1.292, 'CCWM': 15.776, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 17302, 'OPR': 29.089, 'Auto': 0.167, 'CCWM': -0.939, 'TeamName': 'Max Resistance'}, {'TeamNum': 7224, 'OPR': 26.947, 'Auto': 0.522, 'CCWM': 8.605, 'TeamName': 'West Grand Robotics-Mechanical Mustangs 1.0'}, {'TeamNum': 13271, 'OPR': 22.943, 'Auto': 0.252, 'CCWM': -4.181, 'TeamName': 'Cowboy Code   "Redneck Robotics"'}, {'TeamNum': 16975, 'OPR': 20.497, 'Auto': 0.794, 'CCWM': -8.881, 'TeamName': 'Brainy Banana Bunch'}, {'TeamNum': 21819, 'OPR': 17.252, 'Auto': 1.813, 'CCWM': -17.658, 'TeamName': 'Durango High School FTC2'}, {'TeamNum': 21731, 'OPR': 16.035, 'Auto': 0.448, 'CCWM': -15.333, 'TeamName': 'Palisade Purussaurus'}, {'TeamNum': 18793, 'OPR': 13.217, 'Auto': 0.19, 'CCWM': -15.722, 'TeamName': 'Mechanical Masters'}, {'TeamNum': 21818, 'OPR': 12.169, 'Auto': -0.323, 'CCWM': -3.236, 'TeamName': 'Durango High School FTC1'}, {'TeamNum': 21519, 'OPR': 10.635, 'Auto': 0.974, 'CCWM': -30.193, 'TeamName': 'Norwood Robotic Masters'}, {'TeamNum': 18660, 'OPR': 9.245, 'Auto': 0.975, 'CCWM': -9.198, 'TeamName': 'RobotoCardinals'}, {'TeamNum': 13879, 'OPR': 8.433, 'Auto': -1.959, 'CCWM': 8.132, 'TeamName': 'EGMS Metal Minds'}, {'TeamNum': 15289, 'OPR': 1.768, 'Auto': 3.736, 'CCWM': -20.509, 'TeamName': 'EGMS Gadgetron'}]

i 866
i 867
{'16290', '7341', '20016', '8617', '20574', '22604', '20013', '6323', '22140', '14976', '9013', '4717', '19885', '4227', '18172', '7592', '19785', '19400', '18747', '17197', '19997', '21771', '18258', '7477', '20014', '21588', '14673', '4228'}
[{'TeamNum': 7592, 'OPR': 104.161, 'Auto': 25.774, 'CCWM': 91.767, 'TeamName': 'Roarbots'}, {'TeamNum': 18172, 'OPR': 85.46, 'Auto': 14.011, 'CCWM': 46.188, 'TeamName': 'Uplift Robotics'}, {'TeamNum': 4228, 'OPR': 84.59, 'Auto': 22.634, 'CCWM': 65.907, 'TeamName': 'Gears Of Other Dimensions'}, {'TeamNum': 4227, 'OPR': 80.613, 'Auto': 19.665, 'CCWM': 49.731, 'TeamName': 'Metal Morphosis'}, {'TeamNum': 8617, 'OPR': 72.941, 'Auto': 22.703, 'CCWM': 16.303, 'TeamName': 'Techno Tigers'}, {'TeamNum': 19400, 'OPR': 69.786, 'Auto': 10.654, 'CCWM': 21.307, 'TeamName': 'Titans 1'}, {'TeamNum': 7341, 'OPR': 57.763, 'Auto': 16.844, 'CCWM': 26.352, 'TeamName': 'F.R.E.N.C.H. F.R.I.E.S.'}, {'TeamNum': 21588, 'OPR': 57.427, 'Auto': 13.746, 'CCWM': 35.351, 'TeamName': 'The Garlic Knots'}, {'TeamNum': 7477, 'OPR': 57.359, 'Auto': 7.998, 'CCWM': 2.363, 'TeamName': 'Super 7'}, {'TeamNum': 6323, 'OPR': 52.653, 'Auto': 5.153, 'CCWM': 0.696, 'TeamName': 'The Pink Team'}, {'TeamNum': 9013, 'OPR': 45.528, 'Auto': 6.484, 'CCWM': -13.66, 'TeamName': 'Matrix'}, {'TeamNum': 16290, 'OPR': 45.349, 'Auto': 11.931, 'CCWM': 4.01, 'TeamName': 'Z.I.P Ties'}, {'TeamNum': 18258, 'OPR': 40.369, 'Auto': 5.076, 'CCWM': -3.528, 'TeamName': 'Doomba'}, {'TeamNum': 4717, 'OPR': 35.815, 'Auto': 7.405, 'CCWM': 2.077, 'TeamName': 'Mechromancers'}, {'TeamNum': 20014, 'OPR': 34.333, 'Auto': -0.218, 'CCWM': 20.054, 'TeamName': 'THE VOID'}, {'TeamNum': 17197, 'OPR': 30.171, 'Auto': 7.652, 'CCWM': -17.149, 'TeamName': 'High Rollers'}, {'TeamNum': 14976, 'OPR': 29.659, 'Auto': 4.238, 'CCWM': 2.467, 'TeamName': 'PAC RATS'}, {'TeamNum': 20016, 'OPR': 19.465, 'Auto': -1.411, 'CCWM': 2.471, 'TeamName': 'R.A.V.E.'}, {'TeamNum': 19785, 'OPR': 17.489, 'Auto': 2.676, 'CCWM': -25.883, 'TeamName': 'Rust N’ Combustion'}, {'TeamNum': 20574, 'OPR': 15.433, 'Auto': 3.653, 'CCWM': -49.853, 'TeamName': 'Potential Energy'}, {'TeamNum': 20013, 'OPR': 15.301, 'Auto': -6.976, 'CCWM': -11.931, 'TeamName': 'Big Schmoney'}, {'TeamNum': 19997, 'OPR': 11.799, 'Auto': 0.102, 'CCWM': -15.422, 'TeamName': 'Trouble Bubble'}, {'TeamNum': 19885, 'OPR': 10.427, 'Auto': 2.435, 'CCWM': -37.764, 'TeamName': 'Phantom Panthers '}, {'TeamNum': 22604, 'OPR': 10.333, 'Auto': -0.107, 'CCWM': -38.72, 'TeamName': 'Lazer Point'}, {'TeamNum': 14673, 'OPR': 9.45, 'Auto': -2.263, 'CCWM': -68.593, 'TeamName': 'Odyssey One'}, {'TeamNum': 21771, 'OPR': 8.925, 'Auto': -3.926, 'CCWM': -41.529, 'TeamName': 'Paint Can'}, {'TeamNum': 22140, 'OPR': -3.539, 'Auto': -3.981, 'CCWM': -54.687, 'TeamName': 'AlphaSteel'}, {'TeamNum': 18747, 'OPR': -5.726, 'Auto': -0.95, 'CCWM': -8.324, 'TeamName': 'Instrumentality'}]
USFLFLSPLT
[{'TeamNum': 7592, 'OPR': 104.161, 'Auto': 25.774, 'CCWM': 91.767, 'TeamName': 'Roarbots'}, {'TeamNum': 18172, 'OPR': 85.46, 'Auto': 14.011, 'CCWM': 46.188, 'TeamName': 'Uplift Robotics'}, {'TeamNum': 4228, 'OPR': 84.59, 'Auto': 22.634, 'CCWM': 65.907, 'TeamName': 'Gears Of Other Dimensions'}, {'TeamNum': 4227, 'OPR': 80.613, 'Auto': 19.665, 'CCWM': 49.731, 'TeamName': 'Metal Morphosis'}, {'TeamNum': 8617, 'OPR': 72.941, 'Auto': 22.703, 'CCWM': 16.303, 'TeamName': 'Techno Tigers'}, {'TeamNum': 19400, 'OPR': 69.786, 'Auto': 10.654, 'CCWM': 21.307, 'TeamName': 'Titans 1'}, {'TeamNum': 7341, 'OPR': 57.763, 'Auto': 16.844, 'CCWM': 26.352, 'TeamName': 'F.R.E.N.C.H. F.R.I.E.S.'}, {'TeamNum': 21588, 'OPR': 57.427, 'Auto': 13.746, 'CCWM': 35.351, 'TeamName': 'The Garlic Knots'}, {'TeamNum': 7477, 'OPR': 57.359, 'Auto': 7.998, 'CCWM': 2.363, 'TeamName': 'Super 7'}, {'TeamNum': 6323, 'OPR': 52.653, 'Auto': 5.153, 'CCWM': 0.696, 'TeamName': 'The Pink Team'}, {'TeamNum': 9013, 'OPR': 45.528, 'Auto': 6.484, 'CCWM': -13.66, 'TeamName': 'Matrix'}, {'TeamNum': 16290, 'OPR': 45.349, 'Auto': 11.931, 'CCWM': 4.01, 'TeamName': 'Z.I.P Ties'}, {'TeamNum': 18258, 'OPR': 40.369, 'Auto': 5.076, 'CCWM': -3.528, 'TeamName': 'Doomba'}, {'TeamNum': 4717, 'OPR': 35.815, 'Auto': 7.405, 'CCWM': 2.077, 'TeamName': 'Mechromancers'}, {'TeamNum': 20014, 'OPR': 34.333, 'Auto': -0.218, 'CCWM': 20.054, 'TeamName': 'THE VOID'}, {'TeamNum': 17197, 'OPR': 30.171, 'Auto': 7.652, 'CCWM': -17.149, 'TeamName': 'High Rollers'}, {'TeamNum': 14976, 'OPR': 29.659, 'Auto': 4.238, 'CCWM': 2.467, 'TeamName': 'PAC RATS'}, {'TeamNum': 20016, 'OPR': 19.465, 'Auto': -1.411, 'CCWM': 2.471, 'TeamName': 'R.A.V.E.'}, {'TeamNum': 19785, 'OPR': 17.489, 'Auto': 2.676, 'CCWM': -25.883, 'TeamName': 'Rust N’ Combustion'}, {'TeamNum': 20574, 'OPR': 15.433, 'Auto': 3.653, 'CCWM': -49.853, 'TeamName': 'Potential Energy'}, {'TeamNum': 20013, 'OPR': 15.301, 'Auto': -6.976, 'CCWM': -11.931, 'TeamName': 'Big Schmoney'}, {'TeamNum': 19997, 'OPR': 11.799, 'Auto': 0.102, 'CCWM': -15.422, 'TeamName': 'Trouble Bubble'}, {'TeamNum': 19885, 'OPR': 10.427, 'Auto': 2.435, 'CCWM': -37.764, 'TeamName': 'Phantom Panthers '}, {'TeamNum': 22604, 'OPR': 10.333, 'Auto': -0.107, 'CCWM': -38.72, 'TeamName': 'Lazer Point'}, {'TeamNum': 14673, 'OPR': 9.45, 'Auto': -2.263, 'CCWM': -68.593, 'TeamName': 'Odyssey One'}, {'TeamNum': 21771, 'OPR': 8.925, 'Auto': -3.926, 'CCWM': -41.529, 'TeamName': 'Paint Can'}, {'TeamNum': 22140, 'OPR': -3.539, 'Auto': -3.981, 'CCWM': -54.687, 'TeamName': 'AlphaSteel'}, {'TeamNum': 18747, 'OPR': -5.726, 'Auto': -0.95, 'CCWM': -8.324, 'TeamName': 'Instrumentality'}]
i 868
{'14707', '10179', '21896', '22218', '18147', '16626', '15297', '18699', '14708'}
[{'TeamNum': 10179, 'OPR': 90.336, 'Auto': 22.927, 'CCWM': 53.456, 'TeamName': 'Tech Turtles'}, {'TeamNum': 16626, 'OPR': 89.913, 'Auto': 18.139, 'CCWM': 47.773, 'TeamName': 'Radical Raiders'}, {'TeamNum': 18147, 'OPR': 87.384, 'Auto': 14.192, 'CCWM': 41.316, 'TeamName': 'The Imposters'}, {'TeamNum': 14707, 'OPR': 70.755, 'Auto': 10.605, 'CCWM': 5.346, 'TeamName': 'Zero Logic'}, {'TeamNum': 15297, 'OPR': 60.949, 'Auto': 23.01, 'CCWM': -7.434, 'TeamName': 'Legacy'}, {'TeamNum': 22218, 'OPR': 55.642, 'Auto': 22.159, 'CCWM': -7.704, 'TeamName': 'Dog Bytes'}, {'TeamNum': 18699, 'OPR': 48.57, 'Auto': 14.847, 'CCWM': 6.841, 'TeamName': 'The Purple Axolotls'}, {'TeamNum': 21896, 'OPR': 20.761, 'Auto': 2.903, 'CCWM': -62.093, 'TeamName': 'Eagle Bots'}, {'TeamNum': 14708, 'OPR': 15.131, 'Auto': 8.766, 'CCWM': -71.804, 'TeamName': 'Short Circuits'}]
USFLFLACLT
[{'TeamNum': 10179, 'OPR': 90.336, 'Auto': 22.927, 'CCWM': 53.456, 'TeamName': 'Tech Turtles'}, {'TeamNum': 16626, 'OPR': 89.913, 'Auto': 18.139, 'CCWM': 47.773, 'TeamName': 'Radical Raiders'}, {'TeamNum': 18147, 'OPR': 87.384, 'Auto': 14.192, 'CCWM': 41.316, 'TeamName': 'The Imposters'}, {'TeamNum': 14707, 'OPR': 70.755, 'Auto': 10.605, 'CCWM': 5.346, 'TeamName': 'Zero Logic'}, {'TeamNum': 15297, 'OPR': 60.949, 'Auto': 23.01, 'CCWM': -7.434, 'TeamName': 'Legacy'}, {'TeamNum': 22218, 'OPR': 55.642, 'Auto': 22.159, 'CCWM': -7.704, 'TeamName': 'Dog Bytes'}, {'TeamNum': 18699, 'OPR': 48.57, 'Auto': 14.847, 'CCWM': 6.841, 'TeamName': 'The Purple Axolotls'}, {'TeamNum': 21896, 'OPR': 20.761, 'Auto': 2.903, 'CCWM': -62.093, 'TeamName': 'Eagle Bots'}, {'TeamNum': 14708, 'OPR': 15.131, 'Auto': 8.766, 'CCWM': -71.804, 'TeamName': 'Short Circuits'}]
i 869
{'8678', '13245', '19571', '17005', '15173', '21915', '21183', '4327', '12864', '10458', '19987', '1002', '12020', '12995', '14165', '17456', '20172', '10219', '18009', '22581', '11347', '21184', '12961', '11127', '7482', '9686', '14750', '9785'}
[{'TeamNum': 1002, 'OPR': 114.435, 'Auto': 30.728, 'CCWM': 70.159, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 13245, 'OPR': 103.597, 'Auto': 26.486, 'CCWM': 92.631, 'TeamName': 'Arcturus '}, {'TeamNum': 15173, 'OPR': 88.4, 'Auto': 16.466, 'CCWM': 22.154, 'TeamName': 'Robotic Eagles'}, {'TeamNum': 19571, 'OPR': 77.495, 'Auto': 22.444, 'CCWM': 38.325, 'TeamName': 'The Robo Brigade'}, {'TeamNum': 11347, 'OPR': 74.331, 'Auto': 21.278, 'CCWM': 21.621, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 11127, 'OPR': 65.413, 'Auto': 10.563, 'CCWM': 31.987, 'TeamName': 'Whitefield Robotics'}, {'TeamNum': 10219, 'OPR': 59.442, 'Auto': 21.847, 'CCWM': 41.44, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 9785, 'OPR': 54.452, 'Auto': 15.238, 'CCWM': 33.674, 'TeamName': 'Cronos'}, {'TeamNum': 12995, 'OPR': 52.442, 'Auto': 18.195, 'CCWM': 32.268, 'TeamName': 'Monkey Wrench Robotics'}, {'TeamNum': 4327, 'OPR': 44.661, 'Auto': 20.749, 'CCWM': 12.073, 'TeamName': 'Silver Titans'}, {'TeamNum': 20172, 'OPR': 40.424, 'Auto': 5.373, 'CCWM': -37.365, 'TeamName': 'Prometheus'}, {'TeamNum': 14165, 'OPR': 40.224, 'Auto': 7.026, 'CCWM': -5.58, 'TeamName': 'Pebblebrook OG Team'}, {'TeamNum': 12961, 'OPR': 38.237, 'Auto': 16.825, 'CCWM': -17.821, 'TeamName': 'Checkmate'}, {'TeamNum': 18009, 'OPR': 36.821, 'Auto': 10.781, 'CCWM': -19.681, 'TeamName': 'AGS Eye of the Storm'}, {'TeamNum': 17456, 'OPR': 36.189, 'Auto': 3.398, 'CCWM': -10.454, 'TeamName': 'Atlantis'}, {'TeamNum': 19987, 'OPR': 36.156, 'Auto': 14.643, 'CCWM': -41.074, 'TeamName': 'Black Screen of Death'}, {'TeamNum': 9686, 'OPR': 33.672, 'Auto': 23.447, 'CCWM': -19.511, 'TeamName': 'Raiders of the ARC- Black'}, {'TeamNum': 21915, 'OPR': 29.606, 'Auto': -3.054, 'CCWM': -17.322, 'TeamName': 'SMA Bobcats'}, {'TeamNum': 12864, 'OPR': 28.144, 'Auto': 4.167, 'CCWM': 3.544, 'TeamName': 'Raiders of the ARC- Crimson'}, {'TeamNum': 22581, 'OPR': 27.238, 'Auto': -3.254, 'CCWM': -20.802, 'TeamName': 'Technologically Driven'}, {'TeamNum': 21184, 'OPR': 25.518, 'Auto': 6.164, 'CCWM': -8.256, 'TeamName': 'Walton Robotics - Blue'}, {'TeamNum': 8678, 'OPR': 16.181, 'Auto': 4.116, 'CCWM': -14.755, 'TeamName': 'BATteries'}, {'TeamNum': 12020, 'OPR': 16.093, 'Auto': 3.086, 'CCWM': -65.922, 'TeamName': 'STEAMsport FTC Codebots 1 '}, {'TeamNum': 14750, 'OPR': 13.457, 'Auto': 0.085, 'CCWM': 7.451, 'TeamName': 'ATOM'}, {'TeamNum': 7482, 'OPR': 13.445, 'Auto': 3.854, 'CCWM': -45.342, 'TeamName': 'Axel-otls'}, {'TeamNum': 21183, 'OPR': 12.946, 'Auto': 2.569, 'CCWM': -41.351, 'TeamName': 'Walton Robotics - RED'}, {'TeamNum': 10458, 'OPR': 12.78, 'Auto': 0.6, 'CCWM': 16.763, 'TeamName': 'EVE Robotics FTC'}, {'TeamNum': 17005, 'OPR': -2.999, 'Auto': -4.021, 'CCWM': -58.853, 'TeamName': 'SAE Dragonbots'}]
USGAWESTLT
[{'TeamNum': 1002, 'OPR': 114.435, 'Auto': 30.728, 'CCWM': 70.159, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 13245, 'OPR': 103.597, 'Auto': 26.486, 'CCWM': 92.631, 'TeamName': 'Arcturus '}, {'TeamNum': 15173, 'OPR': 88.4, 'Auto': 16.466, 'CCWM': 22.154, 'TeamName': 'Robotic Eagles'}, {'TeamNum': 19571, 'OPR': 77.495, 'Auto': 22.444, 'CCWM': 38.325, 'TeamName': 'The Robo Brigade'}, {'TeamNum': 11347, 'OPR': 74.331, 'Auto': 21.278, 'CCWM': 21.621, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 11127, 'OPR': 65.413, 'Auto': 10.563, 'CCWM': 31.987, 'TeamName': 'Whitefield Robotics'}, {'TeamNum': 10219, 'OPR': 59.442, 'Auto': 21.847, 'CCWM': 41.44, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 9785, 'OPR': 54.452, 'Auto': 15.238, 'CCWM': 33.674, 'TeamName': 'Cronos'}, {'TeamNum': 12995, 'OPR': 52.442, 'Auto': 18.195, 'CCWM': 32.268, 'TeamName': 'Monkey Wrench Robotics'}, {'TeamNum': 4327, 'OPR': 44.661, 'Auto': 20.749, 'CCWM': 12.073, 'TeamName': 'Silver Titans'}, {'TeamNum': 20172, 'OPR': 40.424, 'Auto': 5.373, 'CCWM': -37.365, 'TeamName': 'Prometheus'}, {'TeamNum': 14165, 'OPR': 40.224, 'Auto': 7.026, 'CCWM': -5.58, 'TeamName': 'Pebblebrook OG Team'}, {'TeamNum': 12961, 'OPR': 38.237, 'Auto': 16.825, 'CCWM': -17.821, 'TeamName': 'Checkmate'}, {'TeamNum': 18009, 'OPR': 36.821, 'Auto': 10.781, 'CCWM': -19.681, 'TeamName': 'AGS Eye of the Storm'}, {'TeamNum': 17456, 'OPR': 36.189, 'Auto': 3.398, 'CCWM': -10.454, 'TeamName': 'Atlantis'}, {'TeamNum': 19987, 'OPR': 36.156, 'Auto': 14.643, 'CCWM': -41.074, 'TeamName': 'Black Screen of Death'}, {'TeamNum': 9686, 'OPR': 33.672, 'Auto': 23.447, 'CCWM': -19.511, 'TeamName': 'Raiders of the ARC- Black'}, {'TeamNum': 21915, 'OPR': 29.606, 'Auto': -3.054, 'CCWM': -17.322, 'TeamName': 'SMA Bobcats'}, {'TeamNum': 12864, 'OPR': 28.144, 'Auto': 4.167, 'CCWM': 3.544, 'TeamName': 'Raiders of the ARC- Crimson'}, {'TeamNum': 22581, 'OPR': 27.238, 'Auto': -3.254, 'CCWM': -20.802, 'TeamName': 'Technologically Driven'}, {'TeamNum': 21184, 'OPR': 25.518, 'Auto': 6.164, 'CCWM': -8.256, 'TeamName': 'Walton Robotics - Blue'}, {'TeamNum': 8678, 'OPR': 16.181, 'Auto': 4.116, 'CCWM': -14.755, 'TeamName': 'BATteries'}, {'TeamNum': 12020, 'OPR': 16.093, 'Auto': 3.086, 'CCWM': -65.922, 'TeamName': 'STEAMsport FTC Codebots 1 '}, {'TeamNum': 14750, 'OPR': 13.457, 'Auto': 0.085, 'CCWM': 7.451, 'TeamName': 'ATOM'}, {'TeamNum': 7482, 'OPR': 13.445, 'Auto': 3.854, 'CCWM': -45.342, 'TeamName': 'Axel-otls'}, {'TeamNum': 21183, 'OPR': 12.946, 'Auto': 2.569, 'CCWM': -41.351, 'TeamName': 'Walton Robotics - RED'}, {'TeamNum': 10458, 'OPR': 12.78, 'Auto': 0.6, 'CCWM': 16.763, 'TeamName': 'EVE Robotics FTC'}, {'TeamNum': 17005, 'OPR': -2.999, 'Auto': -4.021, 'CCWM': -58.853, 'TeamName': 'SAE Dragonbots'}]

i 870
{'21627', '8824', '17116', '15523', '18098', '8930', '16754', '12999', '20077', '9566', '20024', '17114', '18856', '11384', '16010', '19714', '19952', '18139', '17111'}
[{'TeamNum': 20077, 'OPR': 114.443, 'Auto': 30.113, 'CCWM': 78.403, 'TeamName': 'The Indubitables'}, {'TeamNum': 21627, 'OPR': 82.19, 'Auto': 4.093, 'CCWM': 35.015, 'TeamName': 'NinJava'}, {'TeamNum': 18139, 'OPR': 70.187, 'Auto': 15.314, 'CCWM': 33.136, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 8824, 'OPR': 65.776, 'Auto': 13.491, 'CCWM': 21.083, 'TeamName': 'N-Bots RoboStorm'}, {'TeamNum': 17111, 'OPR': 65.099, 'Auto': 4.87, 'CCWM': 31.339, 'TeamName': 'Quack Attack'}, {'TeamNum': 16010, 'OPR': 59.339, 'Auto': 12.235, 'CCWM': 15.125, 'TeamName': 'Vamp Kings'}, {'TeamNum': 11384, 'OPR': 54.866, 'Auto': 21.621, 'CCWM': 1.673, 'TeamName': 'Thunderstruck'}, {'TeamNum': 19952, 'OPR': 52.693, 'Auto': -5.626, 'CCWM': -10.44, 'TeamName': 'Area 51'}, {'TeamNum': 17116, 'OPR': 47.022, 'Auto': 4.758, 'CCWM': -5.215, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 18856, 'OPR': 46.361, 'Auto': 5.662, 'CCWM': -43.465, 'TeamName': 'Tech Bam2'}, {'TeamNum': 15523, 'OPR': 44.241, 'Auto': 9.394, 'CCWM': 24.947, 'TeamName': 'Diagonal HotSpots'}, {'TeamNum': 17114, 'OPR': 31.232, 'Auto': 1.818, 'CCWM': 7.771, 'TeamName': 'Pathfinders'}, {'TeamNum': 20024, 'OPR': 25.524, 'Auto': 13.891, 'CCWM': -31.589, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 16754, 'OPR': 24.918, 'Auto': 11.053, 'CCWM': -27.357, 'TeamName': 'Gear Death Experience '}, {'TeamNum': 19714, 'OPR': 24.353, 'Auto': 0.381, 'CCWM': -24.71, 'TeamName': 'Emerging Ladies Academy1'}, {'TeamNum': 12999, 'OPR': 23.939, 'Auto': 3.788, 'CCWM': -44.397, 'TeamName': 'Giraffic Spark   '}, {'TeamNum': 9566, 'OPR': 19.102, 'Auto': 0.335, 'CCWM': -44.052, 'TeamName': 'Tech Bam'}, {'TeamNum': 8930, 'OPR': 18.453, 'Auto': 3.4, 'CCWM': -23.823, 'TeamName': 'Tech-Nical Difficulties'}, {'TeamNum': 18098, 'OPR': 14.373, 'Auto': -9.015, 'CCWM': -9.125, 'TeamName': 'Hydraulic H0rnets'}]
USIACHLT
[{'TeamNum': 20077, 'OPR': 114.443, 'Auto': 30.113, 'CCWM': 78.403, 'TeamName': 'The Indubitables'}, {'TeamNum': 21627, 'OPR': 82.19, 'Auto': 4.093, 'CCWM': 35.015, 'TeamName': 'NinJava'}, {'TeamNum': 18139, 'OPR': 70.187, 'Auto': 15.314, 'CCWM': 33.136, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 8824, 'OPR': 65.776, 'Auto': 13.491, 'CCWM': 21.083, 'TeamName': 'N-Bots RoboStorm'}, {'TeamNum': 17111, 'OPR': 65.099, 'Auto': 4.87, 'CCWM': 31.339, 'TeamName': 'Quack Attack'}, {'TeamNum': 16010, 'OPR': 59.339, 'Auto': 12.235, 'CCWM': 15.125, 'TeamName': 'Vamp Kings'}, {'TeamNum': 11384, 'OPR': 54.866, 'Auto': 21.621, 'CCWM': 1.673, 'TeamName': 'Thunderstruck'}, {'TeamNum': 19952, 'OPR': 52.693, 'Auto': -5.626, 'CCWM': -10.44, 'TeamName': 'Area 51'}, {'TeamNum': 17116, 'OPR': 47.022, 'Auto': 4.758, 'CCWM': -5.215, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 18856, 'OPR': 46.361, 'Auto': 5.662, 'CCWM': -43.465, 'TeamName': 'Tech Bam2'}, {'TeamNum': 15523, 'OPR': 44.241, 'Auto': 9.394, 'CCWM': 24.947, 'TeamName': 'Diagonal HotSpots'}, {'TeamNum': 17114, 'OPR': 31.232, 'Auto': 1.818, 'CCWM': 7.771, 'TeamName': 'Pathfinders'}, {'TeamNum': 20024, 'OPR': 25.524, 'Auto': 13.891, 'CCWM': -31.589, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 16754, 'OPR': 24.918, 'Auto': 11.053, 'CCWM': -27.357, 'TeamName': 'Gear Death Experience '}, {'TeamNum': 19714, 'OPR': 24.353, 'Auto': 0.381, 'CCWM': -24.71, 'TeamName': 'Emerging Ladies Academy1'}, {'TeamNum': 12999, 'OPR': 23.939, 'Auto': 3.788, 'CCWM': -44.397, 'TeamName': 'Giraffic Spark   '}, {'TeamNum': 9566, 'OPR': 19.102, 'Auto': 0.335, 'CCWM': -44.052, 'TeamName': 'Tech Bam'}, {'TeamNum': 8930, 'OPR': 18.453, 'Auto': 3.4, 'CCWM': -23.823, 'TeamName': 'Tech-Nical Difficulties'}, {'TeamNum': 18098, 'OPR': 14.373, 'Auto': -9.015, 'CCWM': -9.125, 'TeamName': 'Hydraulic H0rnets'}]
i 871
{'6458', '6189', '9988', '4156', '21495', '6121', '8695', '5913', '4324', '9925', '6499', '10107', '4175', '4150', '13415', '5143', '8732', '5153', '20307', '9215', '7130', '7110', '11418', '15050', '13352', '10110', '22064', '12168', '3788'}
[{'TeamNum': 4324, 'OPR': 106.604, 'Auto': 22.012, 'CCWM': 76.05, 'TeamName': 'Lost In Time'}, {'TeamNum': 6189, 'OPR': 76.561, 'Auto': 9.603, 'CCWM': 24.818, 'TeamName': 'High Voltage'}, {'TeamNum': 4150, 'OPR': 72.439, 'Auto': 15.454, 'CCWM': -25.471, 'TeamName': 'Dark Matter'}, {'TeamNum': 10107, 'OPR': 70.521, 'Auto': 22.784, 'CCWM': 60.201, 'TeamName': 'ALoTO'}, {'TeamNum': 5143, 'OPR': 68.088, 'Auto': 18.641, 'CCWM': 55.998, 'TeamName': 'Xcentrics'}, {'TeamNum': 4156, 'OPR': 66.888, 'Auto': 18.473, 'CCWM': -2.383, 'TeamName': 'RoboCats Red'}, {'TeamNum': 12168, 'OPR': 63.71, 'Auto': 22.104, 'CCWM': -12.267, 'TeamName': 'Plainsmen Robotics'}, {'TeamNum': 9215, 'OPR': 60.848, 'Auto': 12.345, 'CCWM': 36.819, 'TeamName': 'Team Talos'}, {'TeamNum': 8695, 'OPR': 60.197, 'Auto': 22.98, 'CCWM': 5.578, 'TeamName': 'Tri Hards'}, {'TeamNum': 21495, 'OPR': 55.937, 'Auto': 12.813, 'CCWM': 41.73, 'TeamName': 'Forbidden Waffles'}, {'TeamNum': 7110, 'OPR': 53.117, 'Auto': 19.957, 'CCWM': -14.198, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 9925, 'OPR': 52.89, 'Auto': 22.142, 'CCWM': -4.581, 'TeamName': 'Delta Robotics'}, {'TeamNum': 20307, 'OPR': 50.767, 'Auto': 6.913, 'CCWM': 54.513, 'TeamName': 'Clipper Krakens'}, {'TeamNum': 4175, 'OPR': 46.053, 'Auto': 1.005, 'CCWM': 28.554, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 13415, 'OPR': 42.66, 'Auto': 21.308, 'CCWM': 3.106, 'TeamName': 'Electric Storm'}, {'TeamNum': 13352, 'OPR': 34.861, 'Auto': 4.906, 'CCWM': -17.495, 'TeamName': "Rosie's Riveters "}, {'TeamNum': 6499, 'OPR': 33.224, 'Auto': 3.062, 'CCWM': -16.909, 'TeamName': 'Warrior Bots'}, {'TeamNum': 6458, 'OPR': 30.764, 'Auto': 10.191, 'CCWM': -15.63, 'TeamName': 'Burgbots'}, {'TeamNum': 15050, 'OPR': 28.664, 'Auto': 5.636, 'CCWM': -17.614, 'TeamName': 'Lightning Bots'}, {'TeamNum': 9988, 'OPR': 25.403, 'Auto': 9.038, 'CCWM': 6.128, 'TeamName': 'Taft Robotics'}, {'TeamNum': 7130, 'OPR': 24.576, 'Auto': 0.099, 'CCWM': 4.116, 'TeamName': 'Royal Robots'}, {'TeamNum': 11418, 'OPR': 23.21, 'Auto': 2.793, 'CCWM': -35.488, 'TeamName': 'Clipper RoBoats'}, {'TeamNum': 5913, 'OPR': 23.148, 'Auto': 2.946, 'CCWM': -26.229, 'TeamName': "Drop It Like It's Bot"}, {'TeamNum': 6121, 'OPR': 21.301, 'Auto': 5.387, 'CCWM': -29.947, 'TeamName': 'Cougarbots'}, {'TeamNum': 22064, 'OPR': 20.298, 'Auto': 3.938, 'CCWM': -13.106, 'TeamName': 'ThunderBots'}, {'TeamNum': 10110, 'OPR': 12.635, 'Auto': 2.805, 'CCWM': -13.644, 'TeamName': 'Pixel Knights'}, {'TeamNum': 8732, 'OPR': 7.829, 'Auto': -1.073, 'CCWM': -25.933, 'TeamName': 'Thunderbotz'}, {'TeamNum': 5153, 'OPR': -3.036, 'Auto': -3.464, 'CCWM': -62.108, 'TeamName': 'R.O.A.R (Robots on a Rampage)'}, {'TeamNum': 3788, 'OPR': -12.942, 'Auto': -1.518, 'CCWM': -48.443, 'TeamName': 'C.A.T. S (Chaos Applied to Science)'}]
USIAGELT
[{'TeamNum': 4324, 'OPR': 106.604, 'Auto': 22.012, 'CCWM': 76.05, 'TeamName': 'Lost In Time'}, {'TeamNum': 6189, 'OPR': 76.561, 'Auto': 9.603, 'CCWM': 24.818, 'TeamName': 'High Voltage'}, {'TeamNum': 4150, 'OPR': 72.439, 'Auto': 15.454, 'CCWM': -25.471, 'TeamName': 'Dark Matter'}, {'TeamNum': 10107, 'OPR': 70.521, 'Auto': 22.784, 'CCWM': 60.201, 'TeamName': 'ALoTO'}, {'TeamNum': 5143, 'OPR': 68.088, 'Auto': 18.641, 'CCWM': 55.998, 'TeamName': 'Xcentrics'}, {'TeamNum': 4156, 'OPR': 66.888, 'Auto': 18.473, 'CCWM': -2.383, 'TeamName': 'RoboCats Red'}, {'TeamNum': 12168, 'OPR': 63.71, 'Auto': 22.104, 'CCWM': -12.267, 'TeamName': 'Plainsmen Robotics'}, {'TeamNum': 9215, 'OPR': 60.848, 'Auto': 12.345, 'CCWM': 36.819, 'TeamName': 'Team Talos'}, {'TeamNum': 8695, 'OPR': 60.197, 'Auto': 22.98, 'CCWM': 5.578, 'TeamName': 'Tri Hards'}, {'TeamNum': 21495, 'OPR': 55.937, 'Auto': 12.813, 'CCWM': 41.73, 'TeamName': 'Forbidden Waffles'}, {'TeamNum': 7110, 'OPR': 53.117, 'Auto': 19.957, 'CCWM': -14.198, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 9925, 'OPR': 52.89, 'Auto': 22.142, 'CCWM': -4.581, 'TeamName': 'Delta Robotics'}, {'TeamNum': 20307, 'OPR': 50.767, 'Auto': 6.913, 'CCWM': 54.513, 'TeamName': 'Clipper Krakens'}, {'TeamNum': 4175, 'OPR': 46.053, 'Auto': 1.005, 'CCWM': 28.554, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 13415, 'OPR': 42.66, 'Auto': 21.308, 'CCWM': 3.106, 'TeamName': 'Electric Storm'}, {'TeamNum': 13352, 'OPR': 34.861, 'Auto': 4.906, 'CCWM': -17.495, 'TeamName': "Rosie's Riveters "}, {'TeamNum': 6499, 'OPR': 33.224, 'Auto': 3.062, 'CCWM': -16.909, 'TeamName': 'Warrior Bots'}, {'TeamNum': 6458, 'OPR': 30.764, 'Auto': 10.191, 'CCWM': -15.63, 'TeamName': 'Burgbots'}, {'TeamNum': 15050, 'OPR': 28.664, 'Auto': 5.636, 'CCWM': -17.614, 'TeamName': 'Lightning Bots'}, {'TeamNum': 9988, 'OPR': 25.403, 'Auto': 9.038, 'CCWM': 6.128, 'TeamName': 'Taft Robotics'}, {'TeamNum': 7130, 'OPR': 24.576, 'Auto': 0.099, 'CCWM': 4.116, 'TeamName': 'Royal Robots'}, {'TeamNum': 11418, 'OPR': 23.21, 'Auto': 2.793, 'CCWM': -35.488, 'TeamName': 'Clipper RoBoats'}, {'TeamNum': 5913, 'OPR': 23.148, 'Auto': 2.946, 'CCWM': -26.229, 'TeamName': "Drop It Like It's Bot"}, {'TeamNum': 6121, 'OPR': 21.301, 'Auto': 5.387, 'CCWM': -29.947, 'TeamName': 'Cougarbots'}, {'TeamNum': 22064, 'OPR': 20.298, 'Auto': 3.938, 'CCWM': -13.106, 'TeamName': 'ThunderBots'}, {'TeamNum': 10110, 'OPR': 12.635, 'Auto': 2.805, 'CCWM': -13.644, 'TeamName': 'Pixel Knights'}, {'TeamNum': 8732, 'OPR': 7.829, 'Auto': -1.073, 'CCWM': -25.933, 'TeamName': 'Thunderbotz'}, {'TeamNum': 5153, 'OPR': -3.036, 'Auto': -3.464, 'CCWM': -62.108, 'TeamName': 'R.O.A.R (Robots on a Rampage)'}, {'TeamNum': 3788, 'OPR': -12.942, 'Auto': -1.518, 'CCWM': -48.443, 'TeamName': 'C.A.T. S (Chaos Applied to Science)'}]

i 872
{'17403', '19648', '4965', '22190', '9410', '22213', '22525', '13829', '7006', '9775', '14422', '3216', '15094', '3507', '14592', '13699', '20160'}
[{'TeamNum': 17403, 'OPR': 73.713, 'Auto': 22.649, 'CCWM': 38.257, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 9410, 'OPR': 69.168, 'Auto': 12.142, 'CCWM': 69.687, 'TeamName': "Frank's Garage"}, {'TeamNum': 3507, 'OPR': 68.227, 'Auto': 11.793, 'CCWM': 51.061, 'TeamName': 'Robotheosis'}, {'TeamNum': 13699, 'OPR': 65.909, 'Auto': 15.293, 'CCWM': 46.214, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 19648, 'OPR': 64.968, 'Auto': -0.813, 'CCWM': 51.451, 'TeamName': 'Eagle Robotics Works'}, {'TeamNum': 22213, 'OPR': 28.658, 'Auto': 5.705, 'CCWM': -28.691, 'TeamName': "I'm BOTman"}, {'TeamNum': 7006, 'OPR': 28.359, 'Auto': -0.331, 'CCWM': -1.99, 'TeamName': 'RoboTitans'}, {'TeamNum': 3216, 'OPR': 25.424, 'Auto': 4.76, 'CCWM': -20.241, 'TeamName': 'Robophins'}, {'TeamNum': 15094, 'OPR': 25.24, 'Auto': 8.545, 'CCWM': -13.105, 'TeamName': 'JCP Danger Chickens'}, {'TeamNum': 22525, 'OPR': 22.487, 'Auto': 4.968, 'CCWM': -37.54, 'TeamName': 'Richards'}, {'TeamNum': 13829, 'OPR': 19.785, 'Auto': 8.55, 'CCWM': -4.323, 'TeamName': 'Solorio Robotics'}, {'TeamNum': 20160, 'OPR': 17.341, 'Auto': 0.394, 'CCWM': -11.735, 'TeamName': 'Infinity'}, {'TeamNum': 14592, 'OPR': 16.816, 'Auto': 8.736, 'CCWM': 1.232, 'TeamName': 'Huskies'}, {'TeamNum': 14422, 'OPR': 10.624, 'Auto': 4.6, 'CCWM': -15.756, 'TeamName': 'Twisted Mettle'}, {'TeamNum': 4965, 'OPR': 10.051, 'Auto': 4.742, 'CCWM': -17.901, 'TeamName': 'Animatores Romani'}, {'TeamNum': 9775, 'OPR': 3.887, 'Auto': -5.951, 'CCWM': -59.445, 'TeamName': 'Intrinsic Schools Belmont Campus'}, {'TeamNum': 22190, 'OPR': -5.667, 'Auto': -0.109, 'CCWM': -65.583, 'TeamName': 'ITW David Speer Academy 2'}]
USILCMM3C
[{'TeamNum': 17403, 'OPR': 73.713, 'Auto': 22.649, 'CCWM': 38.257, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 9410, 'OPR': 69.168, 'Auto': 12.142, 'CCWM': 69.687, 'TeamName': "Frank's Garage"}, {'TeamNum': 3507, 'OPR': 68.227, 'Auto': 11.793, 'CCWM': 51.061, 'TeamName': 'Robotheosis'}, {'TeamNum': 13699, 'OPR': 65.909, 'Auto': 15.293, 'CCWM': 46.214, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 19648, 'OPR': 64.968, 'Auto': -0.813, 'CCWM': 51.451, 'TeamName': 'Eagle Robotics Works'}, {'TeamNum': 22213, 'OPR': 28.658, 'Auto': 5.705, 'CCWM': -28.691, 'TeamName': "I'm BOTman"}, {'TeamNum': 7006, 'OPR': 28.359, 'Auto': -0.331, 'CCWM': -1.99, 'TeamName': 'RoboTitans'}, {'TeamNum': 3216, 'OPR': 25.424, 'Auto': 4.76, 'CCWM': -20.241, 'TeamName': 'Robophins'}, {'TeamNum': 15094, 'OPR': 25.24, 'Auto': 8.545, 'CCWM': -13.105, 'TeamName': 'JCP Danger Chickens'}, {'TeamNum': 22525, 'OPR': 22.487, 'Auto': 4.968, 'CCWM': -37.54, 'TeamName': 'Richards'}, {'TeamNum': 13829, 'OPR': 19.785, 'Auto': 8.55, 'CCWM': -4.323, 'TeamName': 'Solorio Robotics'}, {'TeamNum': 20160, 'OPR': 17.341, 'Auto': 0.394, 'CCWM': -11.735, 'TeamName': 'Infinity'}, {'TeamNum': 14592, 'OPR': 16.816, 'Auto': 8.736, 'CCWM': 1.232, 'TeamName': 'Huskies'}, {'TeamNum': 14422, 'OPR': 10.624, 'Auto': 4.6, 'CCWM': -15.756, 'TeamName': 'Twisted Mettle'}, {'TeamNum': 4965, 'OPR': 10.051, 'Auto': 4.742, 'CCWM': -17.901, 'TeamName': 'Animatores Romani'}, {'TeamNum': 9775, 'OPR': 3.887, 'Auto': -5.951, 'CCWM': -59.445, 'TeamName': 'Intrinsic Schools Belmont Campus'}, {'TeamNum': 22190, 'OPR': -5.667, 'Auto': -0.109, 'CCWM': -65.583, 'TeamName': 'ITW David Speer Academy 2'}]
i 873
{'10091', '10415', '22398', '10630', '22667', '5495', '22896', '21667', '18766', '22397', '5072', '12051', '18523', '10138', '15118', '13413', '11139', '14475', '14614', '11848', '9113', '18529'}
[{'TeamNum': 14614, 'OPR': 146.067, 'Auto': 41.082, 'CCWM': 79.463, 'TeamName': 'Electro'}, {'TeamNum': 10091, 'OPR': 118.97, 'Auto': 28.858, 'CCWM': 101.829, 'TeamName': 'N.Y.A.N. Robotics - Not Your Average Nerds'}, {'TeamNum': 18529, 'OPR': 112.834, 'Auto': 35.648, 'CCWM': 10.331, 'TeamName': 'Rust In Piece Robotics'}, {'TeamNum': 10138, 'OPR': 100.366, 'Auto': 25.14, 'CCWM': 36.752, 'TeamName': 'Newton Busters'}, {'TeamNum': 21667, 'OPR': 92.572, 'Auto': 17.771, 'CCWM': 36.317, 'TeamName': 'Blåhaj Robotics'}, {'TeamNum': 11848, 'OPR': 69.024, 'Auto': 8.439, 'CCWM': 41.016, 'TeamName': 'Spare Parts Robotics'}, {'TeamNum': 12051, 'OPR': 66.59, 'Auto': 18.533, 'CCWM': -23.403, 'TeamName': 'N^3 Robotics - Not Not Nerds'}, {'TeamNum': 15118, 'OPR': 66.201, 'Auto': 16.99, 'CCWM': 3.319, 'TeamName': 'CogChamp'}, {'TeamNum': 10630, 'OPR': 64.886, 'Auto': 27.962, 'CCWM': -10.692, 'TeamName': 'Robunculous Chunkulous'}, {'TeamNum': 18523, 'OPR': 62.594, 'Auto': 8.063, 'CCWM': -47.749, 'TeamName': 'Vertigo'}, {'TeamNum': 11139, 'OPR': 60.398, 'Auto': 2.103, 'CCWM': 20.639, 'TeamName': 'Knight Owls'}, {'TeamNum': 22896, 'OPR': 55.6, 'Auto': 3.497, 'CCWM': 4.029, 'TeamName': 'Knightrogen'}, {'TeamNum': 10415, 'OPR': 54.906, 'Auto': 2.501, 'CCWM': -14.884, 'TeamName': 'Warbots'}, {'TeamNum': 18766, 'OPR': 52.85, 'Auto': 2.951, 'CCWM': -41.474, 'TeamName': 'TNT Robotics - Total Nerd Team'}, {'TeamNum': 14475, 'OPR': 46.176, 'Auto': 15.066, 'CCWM': 21.226, 'TeamName': "It's Gonna Blow"}, {'TeamNum': 22398, 'OPR': 42.18, 'Auto': 20.243, 'CCWM': -48.956, 'TeamName': 'Loose Screws'}, {'TeamNum': 5072, 'OPR': 30.727, 'Auto': 2.971, 'CCWM': 19.066, 'TeamName': 'Wildcats'}, {'TeamNum': 9113, 'OPR': 26.98, 'Auto': 2.627, 'CCWM': -19.892, 'TeamName': 'Minimum Cache'}, {'TeamNum': 13413, 'OPR': 20.935, 'Auto': -0.384, 'CCWM': -58.579, 'TeamName': 'Here For The Snacks'}, {'TeamNum': 22397, 'OPR': 20.346, 'Auto': 2.137, 'CCWM': -21.828, 'TeamName': 'G-Force'}, {'TeamNum': 5495, 'OPR': 13.739, 'Auto': -1.718, 'CCWM': -42.317, 'TeamName': 'Iron Eagles'}, {'TeamNum': 22667, 'OPR': 3.486, 'Auto': 1.049, 'CCWM': -61.601, 'TeamName': 'APMA Space Robotics'}]
USILCSNELT
[{'TeamNum': 14614, 'OPR': 146.067, 'Auto': 41.082, 'CCWM': 79.463, 'TeamName': 'Electro'}, {'TeamNum': 10091, 'OPR': 118.97, 'Auto': 28.858, 'CCWM': 101.829, 'TeamName': 'N.Y.A.N. Robotics - Not Your Average Nerds'}, {'TeamNum': 18529, 'OPR': 112.834, 'Auto': 35.648, 'CCWM': 10.331, 'TeamName': 'Rust In Piece Robotics'}, {'TeamNum': 10138, 'OPR': 100.366, 'Auto': 25.14, 'CCWM': 36.752, 'TeamName': 'Newton Busters'}, {'TeamNum': 21667, 'OPR': 92.572, 'Auto': 17.771, 'CCWM': 36.317, 'TeamName': 'Blåhaj Robotics'}, {'TeamNum': 11848, 'OPR': 69.024, 'Auto': 8.439, 'CCWM': 41.016, 'TeamName': 'Spare Parts Robotics'}, {'TeamNum': 12051, 'OPR': 66.59, 'Auto': 18.533, 'CCWM': -23.403, 'TeamName': 'N^3 Robotics - Not Not Nerds'}, {'TeamNum': 15118, 'OPR': 66.201, 'Auto': 16.99, 'CCWM': 3.319, 'TeamName': 'CogChamp'}, {'TeamNum': 10630, 'OPR': 64.886, 'Auto': 27.962, 'CCWM': -10.692, 'TeamName': 'Robunculous Chunkulous'}, {'TeamNum': 18523, 'OPR': 62.594, 'Auto': 8.063, 'CCWM': -47.749, 'TeamName': 'Vertigo'}, {'TeamNum': 11139, 'OPR': 60.398, 'Auto': 2.103, 'CCWM': 20.639, 'TeamName': 'Knight Owls'}, {'TeamNum': 22896, 'OPR': 55.6, 'Auto': 3.497, 'CCWM': 4.029, 'TeamName': 'Knightrogen'}, {'TeamNum': 10415, 'OPR': 54.906, 'Auto': 2.501, 'CCWM': -14.884, 'TeamName': 'Warbots'}, {'TeamNum': 18766, 'OPR': 52.85, 'Auto': 2.951, 'CCWM': -41.474, 'TeamName': 'TNT Robotics - Total Nerd Team'}, {'TeamNum': 14475, 'OPR': 46.176, 'Auto': 15.066, 'CCWM': 21.226, 'TeamName': "It's Gonna Blow"}, {'TeamNum': 22398, 'OPR': 42.18, 'Auto': 20.243, 'CCWM': -48.956, 'TeamName': 'Loose Screws'}, {'TeamNum': 5072, 'OPR': 30.727, 'Auto': 2.971, 'CCWM': 19.066, 'TeamName': 'Wildcats'}, {'TeamNum': 9113, 'OPR': 26.98, 'Auto': 2.627, 'CCWM': -19.892, 'TeamName': 'Minimum Cache'}, {'TeamNum': 13413, 'OPR': 20.935, 'Auto': -0.384, 'CCWM': -58.579, 'TeamName': 'Here For The Snacks'}, {'TeamNum': 22397, 'OPR': 20.346, 'Auto': 2.137, 'CCWM': -21.828, 'TeamName': 'G-Force'}, {'TeamNum': 5495, 'OPR': 13.739, 'Auto': -1.718, 'CCWM': -42.317, 'TeamName': 'Iron Eagles'}, {'TeamNum': 22667, 'OPR': 3.486, 'Auto': 1.049, 'CCWM': -61.601, 'TeamName': 'APMA Space Robotics'}]
i 874
{'8272', '12014', '11272', '22444', '22478', '13377', '11992', '11130', '22138', '14084', '535', '17012', '18638', '20689', '13750'}
[{'TeamNum': 13377, 'OPR': 107.077, 'Auto': 27.4, 'CCWM': 112.511, 'TeamName': 'Blackout'}, {'TeamNum': 22444, 'OPR': 105.564, 'Auto': 28.556, 'CCWM': 81.754, 'TeamName': 'Revelation'}, {'TeamNum': 11272, 'OPR': 67.04, 'Auto': 15.001, 'CCWM': 36.615, 'TeamName': 'Genesis '}, {'TeamNum': 11130, 'OPR': 51.484, 'Auto': 4.571, 'CCWM': -1.587, 'TeamName': 'Kokomo RoboKats'}, {'TeamNum': 17012, 'OPR': 50.691, 'Auto': 8.629, 'CCWM': 20.262, 'TeamName': 'Precision Guessworks'}, {'TeamNum': 11992, 'OPR': 47.014, 'Auto': 18.548, 'CCWM': -23.423, 'TeamName': 'Radioactivity'}, {'TeamNum': 13750, 'OPR': 45.066, 'Auto': 10.055, 'CCWM': 5.738, 'TeamName': 'The Lab Rats'}, {'TeamNum': 18638, 'OPR': 35.653, 'Auto': 4.184, 'CCWM': -30.132, 'TeamName': 'Giant Wacky Waving Inflatable Arm Flailing Tube Man'}, {'TeamNum': 20689, 'OPR': 34.94, 'Auto': 1.719, 'CCWM': -26.461, 'TeamName': 'Battle Ground Robotics'}, {'TeamNum': 12014, 'OPR': 27.97, 'Auto': 11.78, 'CCWM': -6.423, 'TeamName': 'FireWires'}, {'TeamNum': 535, 'OPR': 25.495, 'Auto': 5.54, 'CCWM': -19.783, 'TeamName': 'TOBOR'}, {'TeamNum': 14084, 'OPR': 16.556, 'Auto': 0.676, 'CCWM': -28.025, 'TeamName': '[Insert Name Here]'}, {'TeamNum': 22138, 'OPR': 16.176, 'Auto': 10.713, 'CCWM': -25.494, 'TeamName': 'Talos'}, {'TeamNum': 8272, 'OPR': 5.45, 'Auto': -2.859, 'CCWM': -49.645, 'TeamName': 'CC Sparks'}, {'TeamNum': 22478, 'OPR': -6.39, 'Auto': -2.523, 'CCWM': -47.054, 'TeamName': 'Trojan Thunder'}]
USINNWLT
[{'TeamNum': 13377, 'OPR': 107.077, 'Auto': 27.4, 'CCWM': 112.511, 'TeamName': 'Blackout'}, {'TeamNum': 22444, 'OPR': 105.564, 'Auto': 28.556, 'CCWM': 81.754, 'TeamName': 'Revelation'}, {'TeamNum': 11272, 'OPR': 67.04, 'Auto': 15.001, 'CCWM': 36.615, 'TeamName': 'Genesis '}, {'TeamNum': 11130, 'OPR': 51.484, 'Auto': 4.571, 'CCWM': -1.587, 'TeamName': 'Kokomo RoboKats'}, {'TeamNum': 17012, 'OPR': 50.691, 'Auto': 8.629, 'CCWM': 20.262, 'TeamName': 'Precision Guessworks'}, {'TeamNum': 11992, 'OPR': 47.014, 'Auto': 18.548, 'CCWM': -23.423, 'TeamName': 'Radioactivity'}, {'TeamNum': 13750, 'OPR': 45.066, 'Auto': 10.055, 'CCWM': 5.738, 'TeamName': 'The Lab Rats'}, {'TeamNum': 18638, 'OPR': 35.653, 'Auto': 4.184, 'CCWM': -30.132, 'TeamName': 'Giant Wacky Waving Inflatable Arm Flailing Tube Man'}, {'TeamNum': 20689, 'OPR': 34.94, 'Auto': 1.719, 'CCWM': -26.461, 'TeamName': 'Battle Ground Robotics'}, {'TeamNum': 12014, 'OPR': 27.97, 'Auto': 11.78, 'CCWM': -6.423, 'TeamName': 'FireWires'}, {'TeamNum': 535, 'OPR': 25.495, 'Auto': 5.54, 'CCWM': -19.783, 'TeamName': 'TOBOR'}, {'TeamNum': 14084, 'OPR': 16.556, 'Auto': 0.676, 'CCWM': -28.025, 'TeamName': '[Insert Name Here]'}, {'TeamNum': 22138, 'OPR': 16.176, 'Auto': 10.713, 'CCWM': -25.494, 'TeamName': 'Talos'}, {'TeamNum': 8272, 'OPR': 5.45, 'Auto': -2.859, 'CCWM': -49.645, 'TeamName': 'CC Sparks'}, {'TeamNum': 22478, 'OPR': -6.39, 'Auto': -2.523, 'CCWM': -47.054, 'TeamName': 'Trojan Thunder'}]

i 875
{'14709', '8417', '4444', '20694', '18208', '21623', '11225', '4537', '19841', '19989'}
[{'TeamNum': 20694, 'OPR': 83.021, 'Auto': 24.409, 'CCWM': 62.837, 'TeamName': 'Craft Coalition '}, {'TeamNum': 11225, 'OPR': 82.755, 'Auto': 19.582, 'CCWM': 50.867, 'TeamName': 'DELTA Robotics (Louisville Collegiate School)'}, {'TeamNum': 19841, 'OPR': 56.966, 'Auto': 12.641, 'CCWM': 21.941, 'TeamName': 'RAMbotics'}, {'TeamNum': 8417, 'OPR': 54.228, 'Auto': 10.377, 'CCWM': 14.125, 'TeamName': "'Lectric Legends"}, {'TeamNum': 4444, 'OPR': 45.246, 'Auto': 16.26, 'CCWM': -15.096, 'TeamName': 'Whitefield Robocats'}, {'TeamNum': 4537, 'OPR': 44.65, 'Auto': 11.453, 'CCWM': 14.657, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 18208, 'OPR': 29.039, 'Auto': 9.172, 'CCWM': -18.942, 'TeamName': 'Trinity Titans'}, {'TeamNum': 19989, 'OPR': 24.906, 'Auto': -5.181, 'CCWM': -33.08, 'TeamName': 'Wings of Steel'}, {'TeamNum': 21623, 'OPR': 23.478, 'Auto': 2.328, 'CCWM': -12.194, 'TeamName': 'Failing Formally'}, {'TeamNum': 14709, 'OPR': -3.166, 'Auto': -1.871, 'CCWM': -76.062, 'TeamName': 'Augusta Panthers'}]
USKYKYM1
[{'TeamNum': 20694, 'OPR': 83.021, 'Auto': 24.409, 'CCWM': 62.837, 'TeamName': 'Craft Coalition '}, {'TeamNum': 11225, 'OPR': 82.755, 'Auto': 19.582, 'CCWM': 50.867, 'TeamName': 'DELTA Robotics (Louisville Collegiate School)'}, {'TeamNum': 19841, 'OPR': 56.966, 'Auto': 12.641, 'CCWM': 21.941, 'TeamName': 'RAMbotics'}, {'TeamNum': 8417, 'OPR': 54.228, 'Auto': 10.377, 'CCWM': 14.125, 'TeamName': "'Lectric Legends"}, {'TeamNum': 4444, 'OPR': 45.246, 'Auto': 16.26, 'CCWM': -15.096, 'TeamName': 'Whitefield Robocats'}, {'TeamNum': 4537, 'OPR': 44.65, 'Auto': 11.453, 'CCWM': 14.657, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 18208, 'OPR': 29.039, 'Auto': 9.172, 'CCWM': -18.942, 'TeamName': 'Trinity Titans'}, {'TeamNum': 19989, 'OPR': 24.906, 'Auto': -5.181, 'CCWM': -33.08, 'TeamName': 'Wings of Steel'}, {'TeamNum': 21623, 'OPR': 23.478, 'Auto': 2.328, 'CCWM': -12.194, 'TeamName': 'Failing Formally'}, {'TeamNum': 14709, 'OPR': -3.166, 'Auto': -1.871, 'CCWM': -76.062, 'TeamName': 'Augusta Panthers'}]
i 876
{'18996', '18477', '6390', '20096', '15008', '21494', '16270', '21975', '19670', '21937', '5709', '18792', '18442', '17477', '21497', '8194', '17394', '7393', '12718', '2818', '14253', '9338', '20124', '4991', '20257', '8479', '21524', '11500', '15308', '607', '10719', '16922', '19069', '10001', '21496'}
[{'TeamNum': 19670, 'OPR': 122.531, 'Auto': 18.831, 'CCWM': 117.785, 'TeamName': 'Turtles Robotics'}, {'TeamNum': 2818, 'OPR': 120.633, 'Auto': 30.904, 'CCWM': 116.472, 'TeamName': 'G-FORCE'}, {'TeamNum': 21524, 'OPR': 111.957, 'Auto': 25.857, 'CCWM': 92.134, 'TeamName': 'Dolphins Robotics'}, {'TeamNum': 18442, 'OPR': 109.051, 'Auto': 29.978, 'CCWM': 79.137, 'TeamName': 'Gear Rotation'}, {'TeamNum': 21937, 'OPR': 99.337, 'Auto': 9.777, 'CCWM': 61.028, 'TeamName': 'Proboscis Monkey'}, {'TeamNum': 20096, 'OPR': 98.002, 'Auto': 21.338, 'CCWM': 34.951, 'TeamName': 'The Sentinels'}, {'TeamNum': 18996, 'OPR': 88.86, 'Auto': 23.227, 'CCWM': 62.197, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 18792, 'OPR': 84.662, 'Auto': 10.904, 'CCWM': 83.136, 'TeamName': 'Penguins Robotics '}, {'TeamNum': 21497, 'OPR': 79.798, 'Auto': 11.875, 'CCWM': 19.555, 'TeamName': 'Tigers Robotics'}, {'TeamNum': 7393, 'OPR': 79.135, 'Auto': 18.907, 'CCWM': 17.099, 'TeamName': 'electron Volts'}, {'TeamNum': 21494, 'OPR': 73.934, 'Auto': 19.495, 'CCWM': 3.652, 'TeamName': 'Solstice Robotics'}, {'TeamNum': 10001, 'OPR': 73.471, 'Auto': 19.334, 'CCWM': 15.855, 'TeamName': 'RoboCavs Silver'}, {'TeamNum': 15308, 'OPR': 70.244, 'Auto': 15.64, 'CCWM': 26.028, 'TeamName': 'FAIRY TAIL'}, {'TeamNum': 8479, 'OPR': 66.27, 'Auto': 17.456, 'CCWM': 32.086, 'TeamName': 'RoboCavs Gold'}, {'TeamNum': 21496, 'OPR': 64.981, 'Auto': 22.301, 'CCWM': 16.096, 'TeamName': 'Comet Robotics'}, {'TeamNum': 21975, 'OPR': 64.465, 'Auto': 19.148, 'CCWM': -7.796, 'TeamName': 'Energetic Engineers'}, {'TeamNum': 16270, 'OPR': 60.456, 'Auto': 17.746, 'CCWM': -27.903, 'TeamName': 'Gaelstrom'}, {'TeamNum': 12718, 'OPR': 57.457, 'Auto': 15.827, 'CCWM': 8.647, 'TeamName': 'Lions '}, {'TeamNum': 20124, 'OPR': 54.287, 'Auto': 9.479, 'CCWM': 4.148, 'TeamName': 'Epsilon'}, {'TeamNum': 6390, 'OPR': 51.693, 'Auto': 19.446, 'CCWM': -55.91, 'TeamName': 'Falcons'}, {'TeamNum': 10719, 'OPR': 45.69, 'Auto': 23.616, 'CCWM': -29.215, 'TeamName': 'Termigators'}, {'TeamNum': 16922, 'OPR': 44.888, 'Auto': 5.236, 'CCWM': 15.139, 'TeamName': 'The Queen Bees'}, {'TeamNum': 18477, 'OPR': 44.462, 'Auto': 12.854, 'CCWM': -34.3, 'TeamName': 'BIGBRAINBOTS'}, {'TeamNum': 17477, 'OPR': 44.217, 'Auto': 5.171, 'CCWM': -6.276, 'TeamName': 'Kettle 2 the Mettle'}, {'TeamNum': 17394, 'OPR': 30.563, 'Auto': 17.389, 'CCWM': -48.617, 'TeamName': 'Howard Robotics'}, {'TeamNum': 8194, 'OPR': 23.928, 'Auto': 14.13, 'CCWM': -22.614, 'TeamName': 'Digi-Gators'}, {'TeamNum': 4991, 'OPR': 20.95, 'Auto': 3.605, 'CCWM': -45.324, 'TeamName': 'Gear Freaks'}, {'TeamNum': 607, 'OPR': 20.281, 'Auto': 2.896, 'CCWM': -85.786, 'TeamName': 'Dragon Slayers'}, {'TeamNum': 5709, 'OPR': 19.685, 'Auto': 6.377, 'CCWM': -23.046, 'TeamName': 'Gators'}, {'TeamNum': 19069, 'OPR': 19.11, 'Auto': -0.738, 'CCWM': -39.73, 'TeamName': 'Ryken Robotics'}, {'TeamNum': 11500, 'OPR': 12.646, 'Auto': 0.103, 'CCWM': -45.226, 'TeamName': 'St. Mark Robotics'}, {'TeamNum': 20257, 'OPR': 11.084, 'Auto': 2.393, 'CCWM': -67.903, 'TeamName': 'The Team That Shall Not Be Named'}, {'TeamNum': 9338, 'OPR': 9.475, 'Auto': -2.717, 'CCWM': -64.147, 'TeamName': 'Lightning Coalition Robotics'}, {'TeamNum': 15008, 'OPR': 6.804, 'Auto': 0.25, 'CCWM': -79.748, 'TeamName': 'The Eclipse'}, {'TeamNum': 14253, 'OPR': -12.983, 'Auto': -2.483, 'CCWM': -124.632, 'TeamName': 'Magic School Bots'}]
USCHSUBQ
[{'TeamNum': 19670, 'OPR': 122.531, 'Auto': 18.831, 'CCWM': 117.785, 'TeamName': 'Turtles Robotics'}, {'TeamNum': 2818, 'OPR': 120.633, 'Auto': 30.904, 'CCWM': 116.472, 'TeamName': 'G-FORCE'}, {'TeamNum': 21524, 'OPR': 111.957, 'Auto': 25.857, 'CCWM': 92.134, 'TeamName': 'Dolphins Robotics'}, {'TeamNum': 18442, 'OPR': 109.051, 'Auto': 29.978, 'CCWM': 79.137, 'TeamName': 'Gear Rotation'}, {'TeamNum': 21937, 'OPR': 99.337, 'Auto': 9.777, 'CCWM': 61.028, 'TeamName': 'Proboscis Monkey'}, {'TeamNum': 20096, 'OPR': 98.002, 'Auto': 21.338, 'CCWM': 34.951, 'TeamName': 'The Sentinels'}, {'TeamNum': 18996, 'OPR': 88.86, 'Auto': 23.227, 'CCWM': 62.197, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 18792, 'OPR': 84.662, 'Auto': 10.904, 'CCWM': 83.136, 'TeamName': 'Penguins Robotics '}, {'TeamNum': 21497, 'OPR': 79.798, 'Auto': 11.875, 'CCWM': 19.555, 'TeamName': 'Tigers Robotics'}, {'TeamNum': 7393, 'OPR': 79.135, 'Auto': 18.907, 'CCWM': 17.099, 'TeamName': 'electron Volts'}, {'TeamNum': 21494, 'OPR': 73.934, 'Auto': 19.495, 'CCWM': 3.652, 'TeamName': 'Solstice Robotics'}, {'TeamNum': 10001, 'OPR': 73.471, 'Auto': 19.334, 'CCWM': 15.855, 'TeamName': 'RoboCavs Silver'}, {'TeamNum': 15308, 'OPR': 70.244, 'Auto': 15.64, 'CCWM': 26.028, 'TeamName': 'FAIRY TAIL'}, {'TeamNum': 8479, 'OPR': 66.27, 'Auto': 17.456, 'CCWM': 32.086, 'TeamName': 'RoboCavs Gold'}, {'TeamNum': 21496, 'OPR': 64.981, 'Auto': 22.301, 'CCWM': 16.096, 'TeamName': 'Comet Robotics'}, {'TeamNum': 21975, 'OPR': 64.465, 'Auto': 19.148, 'CCWM': -7.796, 'TeamName': 'Energetic Engineers'}, {'TeamNum': 16270, 'OPR': 60.456, 'Auto': 17.746, 'CCWM': -27.903, 'TeamName': 'Gaelstrom'}, {'TeamNum': 12718, 'OPR': 57.457, 'Auto': 15.827, 'CCWM': 8.647, 'TeamName': 'Lions '}, {'TeamNum': 20124, 'OPR': 54.287, 'Auto': 9.479, 'CCWM': 4.148, 'TeamName': 'Epsilon'}, {'TeamNum': 6390, 'OPR': 51.693, 'Auto': 19.446, 'CCWM': -55.91, 'TeamName': 'Falcons'}, {'TeamNum': 10719, 'OPR': 45.69, 'Auto': 23.616, 'CCWM': -29.215, 'TeamName': 'Termigators'}, {'TeamNum': 16922, 'OPR': 44.888, 'Auto': 5.236, 'CCWM': 15.139, 'TeamName': 'The Queen Bees'}, {'TeamNum': 18477, 'OPR': 44.462, 'Auto': 12.854, 'CCWM': -34.3, 'TeamName': 'BIGBRAINBOTS'}, {'TeamNum': 17477, 'OPR': 44.217, 'Auto': 5.171, 'CCWM': -6.276, 'TeamName': 'Kettle 2 the Mettle'}, {'TeamNum': 17394, 'OPR': 30.563, 'Auto': 17.389, 'CCWM': -48.617, 'TeamName': 'Howard Robotics'}, {'TeamNum': 8194, 'OPR': 23.928, 'Auto': 14.13, 'CCWM': -22.614, 'TeamName': 'Digi-Gators'}, {'TeamNum': 4991, 'OPR': 20.95, 'Auto': 3.605, 'CCWM': -45.324, 'TeamName': 'Gear Freaks'}, {'TeamNum': 607, 'OPR': 20.281, 'Auto': 2.896, 'CCWM': -85.786, 'TeamName': 'Dragon Slayers'}, {'TeamNum': 5709, 'OPR': 19.685, 'Auto': 6.377, 'CCWM': -23.046, 'TeamName': 'Gators'}, {'TeamNum': 19069, 'OPR': 19.11, 'Auto': -0.738, 'CCWM': -39.73, 'TeamName': 'Ryken Robotics'}, {'TeamNum': 11500, 'OPR': 12.646, 'Auto': 0.103, 'CCWM': -45.226, 'TeamName': 'St. Mark Robotics'}, {'TeamNum': 20257, 'OPR': 11.084, 'Auto': 2.393, 'CCWM': -67.903, 'TeamName': 'The Team That Shall Not Be Named'}, {'TeamNum': 9338, 'OPR': 9.475, 'Auto': -2.717, 'CCWM': -64.147, 'TeamName': 'Lightning Coalition Robotics'}, {'TeamNum': 15008, 'OPR': 6.804, 'Auto': 0.25, 'CCWM': -79.748, 'TeamName': 'The Eclipse'}, {'TeamNum': 14253, 'OPR': -12.983, 'Auto': -2.483, 'CCWM': -124.632, 'TeamName': 'Magic School Bots'}]

i 877
{'16939', '14963', '21984', '290', '21225', '16713', '18600', '2867', '291', '7424', '9856', '21433', '22005', '11514', '12565', '10868', '13032', '5108', '2408', '16708', '22083', '21682', '5481', '19950', '289', '2866', '14690'}
[{'TeamNum': 21225, 'OPR': 78.336, 'Auto': 17.218, 'CCWM': 36.533, 'TeamName': 'Shear Force'}, {'TeamNum': 14690, 'OPR': 77.713, 'Auto': 17.712, 'CCWM': 40.125, 'TeamName': 'Tech Titans'}, {'TeamNum': 10868, 'OPR': 72.767, 'Auto': 11.912, 'CCWM': 7.003, 'TeamName': 'Roboteers Cadets'}, {'TeamNum': 2866, 'OPR': 69.146, 'Auto': 17.885, 'CCWM': 19.089, 'TeamName': 'Territory of Stati'}, {'TeamNum': 11514, 'OPR': 60.741, 'Auto': 20.574, 'CCWM': 44.373, 'TeamName': 'Nexus'}, {'TeamNum': 9856, 'OPR': 59.242, 'Auto': 13.322, 'CCWM': 26.221, 'TeamName': 'Spaghettified'}, {'TeamNum': 7424, 'OPR': 58.617, 'Auto': 20.475, 'CCWM': 11.89, 'TeamName': 'Robotic Warriors'}, {'TeamNum': 5481, 'OPR': 54.746, 'Auto': 14.533, 'CCWM': 15.417, 'TeamName': 'Cerberus Robotics'}, {'TeamNum': 21984, 'OPR': 53.61, 'Auto': 16.639, 'CCWM': 16.894, 'TeamName': 'Robaddies'}, {'TeamNum': 22083, 'OPR': 53.216, 'Auto': 10.224, 'CCWM': 27.897, 'TeamName': 'Lefty Loosey'}, {'TeamNum': 5108, 'OPR': 48.342, 'Auto': 18.244, 'CCWM': 8.323, 'TeamName': 'Amish Electricians'}, {'TeamNum': 14963, 'OPR': 46.667, 'Auto': 8.447, 'CCWM': 13.64, 'TeamName': 'Automated Chivalry'}, {'TeamNum': 12565, 'OPR': 46.096, 'Auto': 0.748, 'CCWM': 30.671, 'TeamName': 'Medusa Serpentine Robotics'}, {'TeamNum': 21682, 'OPR': 31.491, 'Auto': -0.821, 'CCWM': 8.494, 'TeamName': 'Spartans'}, {'TeamNum': 19950, 'OPR': 25.812, 'Auto': -0.412, 'CCWM': -1.674, 'TeamName': 'YeeYee Institute of Technology'}, {'TeamNum': 291, 'OPR': 25.441, 'Auto': 4.113, 'CCWM': -10.173, 'TeamName': 'Robohawks 291'}, {'TeamNum': 2408, 'OPR': 22.175, 'Auto': -0.682, 'CCWM': -26.877, 'TeamName': 'Shrapnel Sergeants'}, {'TeamNum': 13032, 'OPR': 20.821, 'Auto': 6.81, 'CCWM': -21.395, 'TeamName': 'Ant Colony'}, {'TeamNum': 21433, 'OPR': 19.168, 'Auto': 2.996, 'CCWM': -19.666, 'TeamName': 'Epic Energetic Engineers'}, {'TeamNum': 2867, 'OPR': 17.932, 'Auto': -1.011, 'CCWM': -18.907, 'TeamName': 'Degrees of Freedo'}, {'TeamNum': 289, 'OPR': 17.82, 'Auto': 5.403, 'CCWM': -24.695, 'TeamName': 'Robohawks 289'}, {'TeamNum': 16708, 'OPR': 17.542, 'Auto': 5.466, 'CCWM': -36.219, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 18600, 'OPR': 17.343, 'Auto': 3.298, 'CCWM': -20.874, 'TeamName': "Lord Xenu's Fan Club"}, {'TeamNum': 16713, 'OPR': 15.119, 'Auto': 0.868, 'CCWM': -35.371, 'TeamName': "King Julien's Tech Squad"}, {'TeamNum': 290, 'OPR': 12.794, 'Auto': 7.584, 'CCWM': -24.083, 'TeamName': 'Robohawks 290'}, {'TeamNum': 22005, 'OPR': 10.324, 'Auto': 6.945, 'CCWM': -17.094, 'TeamName': 'Caution: Flammable'}, {'TeamNum': 16939, 'OPR': 4.233, 'Auto': -3.342, 'CCWM': -45.036, 'TeamName': 'Robo-Bulldogs'}]
USMOKSSTLNLT
[{'TeamNum': 21225, 'OPR': 78.336, 'Auto': 17.218, 'CCWM': 36.533, 'TeamName': 'Shear Force'}, {'TeamNum': 14690, 'OPR': 77.713, 'Auto': 17.712, 'CCWM': 40.125, 'TeamName': 'Tech Titans'}, {'TeamNum': 10868, 'OPR': 72.767, 'Auto': 11.912, 'CCWM': 7.003, 'TeamName': 'Roboteers Cadets'}, {'TeamNum': 2866, 'OPR': 69.146, 'Auto': 17.885, 'CCWM': 19.089, 'TeamName': 'Territory of Stati'}, {'TeamNum': 11514, 'OPR': 60.741, 'Auto': 20.574, 'CCWM': 44.373, 'TeamName': 'Nexus'}, {'TeamNum': 9856, 'OPR': 59.242, 'Auto': 13.322, 'CCWM': 26.221, 'TeamName': 'Spaghettified'}, {'TeamNum': 7424, 'OPR': 58.617, 'Auto': 20.475, 'CCWM': 11.89, 'TeamName': 'Robotic Warriors'}, {'TeamNum': 5481, 'OPR': 54.746, 'Auto': 14.533, 'CCWM': 15.417, 'TeamName': 'Cerberus Robotics'}, {'TeamNum': 21984, 'OPR': 53.61, 'Auto': 16.639, 'CCWM': 16.894, 'TeamName': 'Robaddies'}, {'TeamNum': 22083, 'OPR': 53.216, 'Auto': 10.224, 'CCWM': 27.897, 'TeamName': 'Lefty Loosey'}, {'TeamNum': 5108, 'OPR': 48.342, 'Auto': 18.244, 'CCWM': 8.323, 'TeamName': 'Amish Electricians'}, {'TeamNum': 14963, 'OPR': 46.667, 'Auto': 8.447, 'CCWM': 13.64, 'TeamName': 'Automated Chivalry'}, {'TeamNum': 12565, 'OPR': 46.096, 'Auto': 0.748, 'CCWM': 30.671, 'TeamName': 'Medusa Serpentine Robotics'}, {'TeamNum': 21682, 'OPR': 31.491, 'Auto': -0.821, 'CCWM': 8.494, 'TeamName': 'Spartans'}, {'TeamNum': 19950, 'OPR': 25.812, 'Auto': -0.412, 'CCWM': -1.674, 'TeamName': 'YeeYee Institute of Technology'}, {'TeamNum': 291, 'OPR': 25.441, 'Auto': 4.113, 'CCWM': -10.173, 'TeamName': 'Robohawks 291'}, {'TeamNum': 2408, 'OPR': 22.175, 'Auto': -0.682, 'CCWM': -26.877, 'TeamName': 'Shrapnel Sergeants'}, {'TeamNum': 13032, 'OPR': 20.821, 'Auto': 6.81, 'CCWM': -21.395, 'TeamName': 'Ant Colony'}, {'TeamNum': 21433, 'OPR': 19.168, 'Auto': 2.996, 'CCWM': -19.666, 'TeamName': 'Epic Energetic Engineers'}, {'TeamNum': 2867, 'OPR': 17.932, 'Auto': -1.011, 'CCWM': -18.907, 'TeamName': 'Degrees of Freedo'}, {'TeamNum': 289, 'OPR': 17.82, 'Auto': 5.403, 'CCWM': -24.695, 'TeamName': 'Robohawks 289'}, {'TeamNum': 16708, 'OPR': 17.542, 'Auto': 5.466, 'CCWM': -36.219, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 18600, 'OPR': 17.343, 'Auto': 3.298, 'CCWM': -20.874, 'TeamName': "Lord Xenu's Fan Club"}, {'TeamNum': 16713, 'OPR': 15.119, 'Auto': 0.868, 'CCWM': -35.371, 'TeamName': "King Julien's Tech Squad"}, {'TeamNum': 290, 'OPR': 12.794, 'Auto': 7.584, 'CCWM': -24.083, 'TeamName': 'Robohawks 290'}, {'TeamNum': 22005, 'OPR': 10.324, 'Auto': 6.945, 'CCWM': -17.094, 'TeamName': 'Caution: Flammable'}, {'TeamNum': 16939, 'OPR': 4.233, 'Auto': -3.342, 'CCWM': -45.036, 'TeamName': 'Robo-Bulldogs'}]
i 878
{'11659', '20323', '13132', '5905', '13337', '22551', '17206', '5907', '21586', '8461', '4964', '10123', '5906', '6168', '14742', '20298', '7678', '13092', '8856', '16303', '16180', '22090', '5893', '11678', '16207', '18063', '6889', '16506'}
[{'TeamNum': 20323, 'OPR': 91.587, 'Auto': 19.767, 'CCWM': 53.229, 'TeamName': 'Sigma'}, {'TeamNum': 13092, 'OPR': 89.7, 'Auto': 17.092, 'CCWM': 37.091, 'TeamName': 'Central Processing Units'}, {'TeamNum': 5893, 'OPR': 87.415, 'Auto': 13.047, 'CCWM': 57.622, 'TeamName': 'Direct Current'}, {'TeamNum': 6168, 'OPR': 86.785, 'Auto': 19.593, 'CCWM': 13.681, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 7678, 'OPR': 85.419, 'Auto': 21.543, 'CCWM': 16.55, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 4964, 'OPR': 74.91, 'Auto': 21.695, 'CCWM': 48.679, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 16180, 'OPR': 68.832, 'Auto': 15.201, 'CCWM': 38.019, 'TeamName': 'Springfield Robotics '}, {'TeamNum': 13337, 'OPR': 66.294, 'Auto': 15.89, 'CCWM': 22.669, 'TeamName': 'ROBOZARK'}, {'TeamNum': 8461, 'OPR': 62.953, 'Auto': 7.599, 'CCWM': 6.749, 'TeamName': 'Elementary  My Dear Botson'}, {'TeamNum': 5905, 'OPR': 58.575, 'Auto': 13.786, 'CCWM': -2.048, 'TeamName': 'Camdenton FTC  LASER Middle School #1'}, {'TeamNum': 5907, 'OPR': 56.992, 'Auto': 5.058, 'CCWM': -4.388, 'TeamName': 'Camdenton FTC LASER Middle School #3'}, {'TeamNum': 16506, 'OPR': 54.298, 'Auto': 10.106, 'CCWM': 27.092, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 21586, 'OPR': 48.008, 'Auto': 2.396, 'CCWM': -17.683, 'TeamName': 'Broken Arrow'}, {'TeamNum': 13132, 'OPR': 46.182, 'Auto': 2.393, 'CCWM': 9.847, 'TeamName': 'Miner Clue'}, {'TeamNum': 22090, 'OPR': 43.477, 'Auto': 0.782, 'CCWM': 15.983, 'TeamName': 'Neosho High School Robotics club'}, {'TeamNum': 5906, 'OPR': 42.186, 'Auto': 8.8, 'CCWM': 41.185, 'TeamName': 'Camdenton FTC LASER Middle School #2'}, {'TeamNum': 16303, 'OPR': 42.167, 'Auto': 2.849, 'CCWM': -28.857, 'TeamName': 'Wolves'}, {'TeamNum': 8856, 'OPR': 41.435, 'Auto': 5.179, 'CCWM': -11.473, 'TeamName': 'Springfield Robotics '}, {'TeamNum': 6889, 'OPR': 34.152, 'Auto': 6.734, 'CCWM': -11.759, 'TeamName': 'Robo Crusaders'}, {'TeamNum': 17206, 'OPR': 33.363, 'Auto': -1.744, 'CCWM': -5.912, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 11659, 'OPR': 29.775, 'Auto': 0.147, 'CCWM': -29.02, 'TeamName': 'Wheaton Robodogs'}, {'TeamNum': 18063, 'OPR': 28.826, 'Auto': 1.255, 'CCWM': -29.659, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 20298, 'OPR': 26.462, 'Auto': 0.258, 'CCWM': -35.748, 'TeamName': 'Nvizable Robotix'}, {'TeamNum': 11678, 'OPR': 24.574, 'Auto': 1.831, 'CCWM': -32.28, 'TeamName': 'Arrow Flight '}, {'TeamNum': 16207, 'OPR': 22.092, 'Auto': 2.255, 'CCWM': -28.336, 'TeamName': 'Neosho Gearcats'}, {'TeamNum': 14742, 'OPR': 14.325, 'Auto': -2.402, 'CCWM': -33.097, 'TeamName': 'Brobots'}, {'TeamNum': 22551, 'OPR': 10.609, 'Auto': 7.265, 'CCWM': -53.084, 'TeamName': 'Cavaliers23'}, {'TeamNum': 10123, 'OPR': 8.273, 'Auto': -3.71, 'CCWM': -65.052, 'TeamName': 'Springfield Robotics "The Riveters"'}]
USMOKSSWMILT1
[{'TeamNum': 20323, 'OPR': 91.587, 'Auto': 19.767, 'CCWM': 53.229, 'TeamName': 'Sigma'}, {'TeamNum': 13092, 'OPR': 89.7, 'Auto': 17.092, 'CCWM': 37.091, 'TeamName': 'Central Processing Units'}, {'TeamNum': 5893, 'OPR': 87.415, 'Auto': 13.047, 'CCWM': 57.622, 'TeamName': 'Direct Current'}, {'TeamNum': 6168, 'OPR': 86.785, 'Auto': 19.593, 'CCWM': 13.681, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 7678, 'OPR': 85.419, 'Auto': 21.543, 'CCWM': 16.55, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 4964, 'OPR': 74.91, 'Auto': 21.695, 'CCWM': 48.679, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 16180, 'OPR': 68.832, 'Auto': 15.201, 'CCWM': 38.019, 'TeamName': 'Springfield Robotics '}, {'TeamNum': 13337, 'OPR': 66.294, 'Auto': 15.89, 'CCWM': 22.669, 'TeamName': 'ROBOZARK'}, {'TeamNum': 8461, 'OPR': 62.953, 'Auto': 7.599, 'CCWM': 6.749, 'TeamName': 'Elementary  My Dear Botson'}, {'TeamNum': 5905, 'OPR': 58.575, 'Auto': 13.786, 'CCWM': -2.048, 'TeamName': 'Camdenton FTC  LASER Middle School #1'}, {'TeamNum': 5907, 'OPR': 56.992, 'Auto': 5.058, 'CCWM': -4.388, 'TeamName': 'Camdenton FTC LASER Middle School #3'}, {'TeamNum': 16506, 'OPR': 54.298, 'Auto': 10.106, 'CCWM': 27.092, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 21586, 'OPR': 48.008, 'Auto': 2.396, 'CCWM': -17.683, 'TeamName': 'Broken Arrow'}, {'TeamNum': 13132, 'OPR': 46.182, 'Auto': 2.393, 'CCWM': 9.847, 'TeamName': 'Miner Clue'}, {'TeamNum': 22090, 'OPR': 43.477, 'Auto': 0.782, 'CCWM': 15.983, 'TeamName': 'Neosho High School Robotics club'}, {'TeamNum': 5906, 'OPR': 42.186, 'Auto': 8.8, 'CCWM': 41.185, 'TeamName': 'Camdenton FTC LASER Middle School #2'}, {'TeamNum': 16303, 'OPR': 42.167, 'Auto': 2.849, 'CCWM': -28.857, 'TeamName': 'Wolves'}, {'TeamNum': 8856, 'OPR': 41.435, 'Auto': 5.179, 'CCWM': -11.473, 'TeamName': 'Springfield Robotics '}, {'TeamNum': 6889, 'OPR': 34.152, 'Auto': 6.734, 'CCWM': -11.759, 'TeamName': 'Robo Crusaders'}, {'TeamNum': 17206, 'OPR': 33.363, 'Auto': -1.744, 'CCWM': -5.912, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 11659, 'OPR': 29.775, 'Auto': 0.147, 'CCWM': -29.02, 'TeamName': 'Wheaton Robodogs'}, {'TeamNum': 18063, 'OPR': 28.826, 'Auto': 1.255, 'CCWM': -29.659, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 20298, 'OPR': 26.462, 'Auto': 0.258, 'CCWM': -35.748, 'TeamName': 'Nvizable Robotix'}, {'TeamNum': 11678, 'OPR': 24.574, 'Auto': 1.831, 'CCWM': -32.28, 'TeamName': 'Arrow Flight '}, {'TeamNum': 16207, 'OPR': 22.092, 'Auto': 2.255, 'CCWM': -28.336, 'TeamName': 'Neosho Gearcats'}, {'TeamNum': 14742, 'OPR': 14.325, 'Auto': -2.402, 'CCWM': -33.097, 'TeamName': 'Brobots'}, {'TeamNum': 22551, 'OPR': 10.609, 'Auto': 7.265, 'CCWM': -53.084, 'TeamName': 'Cavaliers23'}, {'TeamNum': 10123, 'OPR': 8.273, 'Auto': -3.71, 'CCWM': -65.052, 'TeamName': 'Springfield Robotics "The Riveters"'}]
i 879

{'6205', '6831', '6704', '21585', '6302', '8651', '14799', '19795', '17341', '20217', '12272', '13054', '18370', '11279', '6556'}
[{'TeamNum': 14799, 'OPR': 86.326, 'Auto': 23.727, 'CCWM': 65.383, 'TeamName': 'LCS Javawocky'}, {'TeamNum': 8651, 'OPR': 78.71, 'Auto': 13.136, 'CCWM': 33.562, 'TeamName': 'Wait For It...'}, {'TeamNum': 6302, 'OPR': 69.405, 'Auto': 20.324, 'CCWM': 8.892, 'TeamName': 'Odyssey'}, {'TeamNum': 11279, 'OPR': 64.731, 'Auto': 5.334, 'CCWM': 25.346, 'TeamName': 'Pure Imagination'}, {'TeamNum': 12272, 'OPR': 50.413, 'Auto': 7.825, 'CCWM': -20.683, 'TeamName': 'Team Lightning'}, {'TeamNum': 6556, 'OPR': 45.55, 'Auto': 7.691, 'CCWM': 1.092, 'TeamName': 'Tempest'}, {'TeamNum': 20217, 'OPR': 42.942, 'Auto': -2.968, 'CCWM': 23.481, 'TeamName': 'Surge'}, {'TeamNum': 6704, 'OPR': 40.334, 'Auto': 6.42, 'CCWM': 14.998, 'TeamName': 'Bot Shop'}, {'TeamNum': 17341, 'OPR': 36.453, 'Auto': 5.033, 'CCWM': -13.22, 'TeamName': 'Team Thunder'}, {'TeamNum': 6205, 'OPR': 33.496, 'Auto': 4.712, 'CCWM': 26.211, 'TeamName': 'SCARLET'}, {'TeamNum': 18370, 'OPR': 20.988, 'Auto': 5.425, 'CCWM': -22.103, 'TeamName': "Can't Stop Won't Stop"}, {'TeamNum': 21585, 'OPR': 19.127, 'Auto': -4.047, 'CCWM': -40.946, 'TeamName': 'Irish Storm'}, {'TeamNum': 6831, 'OPR': 16.713, 'Auto': -9.519, 'CCWM': -16.729, 'TeamName': 'Robo Bearcats'}, {'TeamNum': 19795, 'OPR': 3.976, 'Auto': -2.033, 'CCWM': -61.555, 'TeamName': 'Rockbotics'}, {'TeamNum': 13054, 'OPR': -4.227, 'Auto': -3.405, 'CCWM': -36.805, 'TeamName': 'Mechanical MasterMinds'}]
USMSBIQ5
[{'TeamNum': 14799, 'OPR': 86.326, 'Auto': 23.727, 'CCWM': 65.383, 'TeamName': 'LCS Javawocky'}, {'TeamNum': 8651, 'OPR': 78.71, 'Auto': 13.136, 'CCWM': 33.562, 'TeamName': 'Wait For It...'}, {'TeamNum': 6302, 'OPR': 69.405, 'Auto': 20.324, 'CCWM': 8.892, 'TeamName': 'Odyssey'}, {'TeamNum': 11279, 'OPR': 64.731, 'Auto': 5.334, 'CCWM': 25.346, 'TeamName': 'Pure Imagination'}, {'TeamNum': 12272, 'OPR': 50.413, 'Auto': 7.825, 'CCWM': -20.683, 'TeamName': 'Team Lightning'}, {'TeamNum': 6556, 'OPR': 45.55, 'Auto': 7.691, 'CCWM': 1.092, 'TeamName': 'Tempest'}, {'TeamNum': 20217, 'OPR': 42.942, 'Auto': -2.968, 'CCWM': 23.481, 'TeamName': 'Surge'}, {'TeamNum': 6704, 'OPR': 40.334, 'Auto': 6.42, 'CCWM': 14.998, 'TeamName': 'Bot Shop'}, {'TeamNum': 17341, 'OPR': 36.453, 'Auto': 5.033, 'CCWM': -13.22, 'TeamName': 'Team Thunder'}, {'TeamNum': 6205, 'OPR': 33.496, 'Auto': 4.712, 'CCWM': 26.211, 'TeamName': 'SCARLET'}, {'TeamNum': 18370, 'OPR': 20.988, 'Auto': 5.425, 'CCWM': -22.103, 'TeamName': "Can't Stop Won't Stop"}, {'TeamNum': 21585, 'OPR': 19.127, 'Auto': -4.047, 'CCWM': -40.946, 'TeamName': 'Irish Storm'}, {'TeamNum': 6831, 'OPR': 16.713, 'Auto': -9.519, 'CCWM': -16.729, 'TeamName': 'Robo Bearcats'}, {'TeamNum': 19795, 'OPR': 3.976, 'Auto': -2.033, 'CCWM': -61.555, 'TeamName': 'Rockbotics'}, {'TeamNum': 13054, 'OPR': -4.227, 'Auto': -3.405, 'CCWM': -36.805, 'TeamName': 'Mechanical MasterMinds'}]
i 880
{'4622', '9990', '9993', '6183', '2827', '16328', '19410', '7083', '19921', '21501', '21910', '21490', '3587', '20765', '9021', '17346'}
[{'TeamNum': 16328, 'OPR': 111.816, 'Auto': 11.068, 'CCWM': 77.416, 'TeamName': "Trial n' Error"}, {'TeamNum': 21910, 'OPR': 100.954, 'Auto': 19.853, 'CCWM': 50.395, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 21501, 'OPR': 85.538, 'Auto': 19.57, 'CCWM': 35.084, 'TeamName': 'Ohms'}, {'TeamNum': 3587, 'OPR': 81.007, 'Auto': 14.599, 'CCWM': -3.257, 'TeamName': 'Unparalleled Processing'}, {'TeamNum': 2827, 'OPR': 79.517, 'Auto': -3.031, 'CCWM': 34.882, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 19410, 'OPR': 71.062, 'Auto': 27.669, 'CCWM': 27.024, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 19921, 'OPR': 69.898, 'Auto': 22.499, 'CCWM': 55.731, 'TeamName': 'Space Invaders'}, {'TeamNum': 21490, 'OPR': 65.586, 'Auto': 25.604, 'CCWM': -7.786, 'TeamName': 'The Boltiverse'}, {'TeamNum': 7083, 'OPR': 57.761, 'Auto': 12.195, 'CCWM': 12.174, 'TeamName': 'TundraBots'}, {'TeamNum': 17346, 'OPR': 57.371, 'Auto': 22.442, 'CCWM': 13.905, 'TeamName': 'The Taco Terminators'}, {'TeamNum': 6183, 'OPR': 5.778, 'Auto': 3.886, 'CCWM': -44.814, 'TeamName': 'Thunderducks'}, {'TeamNum': 9990, 'OPR': 0.487, 'Auto': -0.008, 'CCWM': -11.067, 'TeamName': 'Robo Vikings'}, {'TeamNum': 20765, 'OPR': 0.369, 'Auto': -1.816, 'CCWM': -68.122, 'TeamName': 'Vikings for Technology'}, {'TeamNum': 9993, 'OPR': -2.321, 'Auto': -1.018, 'CCWM': -66.69, 'TeamName': 'StormBots'}, {'TeamNum': 9021, 'OPR': -7.698, 'Auto': -2.232, 'CCWM': -58.421, 'TeamName': 'TMSA Batteries'}, {'TeamNum': 4622, 'OPR': -11.326, 'Auto': 0.72, 'CCWM': -46.455, 'TeamName': 'L.O.C.S.'}]
USNCELQ
[{'TeamNum': 16328, 'OPR': 111.816, 'Auto': 11.068, 'CCWM': 77.416, 'TeamName': "Trial n' Error"}, {'TeamNum': 21910, 'OPR': 100.954, 'Auto': 19.853, 'CCWM': 50.395, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 21501, 'OPR': 85.538, 'Auto': 19.57, 'CCWM': 35.084, 'TeamName': 'Ohms'}, {'TeamNum': 3587, 'OPR': 81.007, 'Auto': 14.599, 'CCWM': -3.257, 'TeamName': 'Unparalleled Processing'}, {'TeamNum': 2827, 'OPR': 79.517, 'Auto': -3.031, 'CCWM': 34.882, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 19410, 'OPR': 71.062, 'Auto': 27.669, 'CCWM': 27.024, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 19921, 'OPR': 69.898, 'Auto': 22.499, 'CCWM': 55.731, 'TeamName': 'Space Invaders'}, {'TeamNum': 21490, 'OPR': 65.586, 'Auto': 25.604, 'CCWM': -7.786, 'TeamName': 'The Boltiverse'}, {'TeamNum': 7083, 'OPR': 57.761, 'Auto': 12.195, 'CCWM': 12.174, 'TeamName': 'TundraBots'}, {'TeamNum': 17346, 'OPR': 57.371, 'Auto': 22.442, 'CCWM': 13.905, 'TeamName': 'The Taco Terminators'}, {'TeamNum': 6183, 'OPR': 5.778, 'Auto': 3.886, 'CCWM': -44.814, 'TeamName': 'Thunderducks'}, {'TeamNum': 9990, 'OPR': 0.487, 'Auto': -0.008, 'CCWM': -11.067, 'TeamName': 'Robo Vikings'}, {'TeamNum': 20765, 'OPR': 0.369, 'Auto': -1.816, 'CCWM': -68.122, 'TeamName': 'Vikings for Technology'}, {'TeamNum': 9993, 'OPR': -2.321, 'Auto': -1.018, 'CCWM': -66.69, 'TeamName': 'StormBots'}, {'TeamNum': 9021, 'OPR': -7.698, 'Auto': -2.232, 'CCWM': -58.421, 'TeamName': 'TMSA Batteries'}, {'TeamNum': 4622, 'OPR': -11.326, 'Auto': 0.72, 'CCWM': -46.455, 'TeamName': 'L.O.C.S.'}]
i 881
{'18994', '3916', '21443', '18175', '13883', '7444', '21502', '7105', '8947', '11424', '15830', '21381', '6078', '15707', '19403', '21836'}
[{'TeamNum': 7105, 'OPR': 127.404, 'Auto': 25.369, 'CCWM': 63.419, 'TeamName': 'SWIFT Intergalactic Space Llamas'}, {'TeamNum': 18994, 'OPR': 101.836, 'Auto': 20.285, 'CCWM': 42.445, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 6078, 'OPR': 88.346, 'Auto': 21.484, 'CCWM': 27.314, 'TeamName': 'Cut the Red Wire'}, {'TeamNum': 15707, 'OPR': 85.049, 'Auto': 29.467, 'CCWM': -11.626, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 8947, 'OPR': 81.076, 'Auto': 34.816, 'CCWM': 25.006, 'TeamName': 'Techtonics'}, {'TeamNum': 18175, 'OPR': 78.877, 'Auto': 5.104, 'CCWM': 11.181, 'TeamName': 'Techies'}, {'TeamNum': 11424, 'OPR': 78.617, 'Auto': 10.631, 'CCWM': 7.149, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 21836, 'OPR': 70.468, 'Auto': 32.544, 'CCWM': 4.41, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 15830, 'OPR': 62.996, 'Auto': 13.785, 'CCWM': -1.489, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 21502, 'OPR': 50.281, 'Auto': 21.044, 'CCWM': -35.28, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 3916, 'OPR': 43.481, 'Auto': 7.74, 'CCWM': 4.18, 'TeamName': 'Apex Robotics'}, {'TeamNum': 13883, 'OPR': 28.705, 'Auto': 1.218, 'CCWM': -10.551, 'TeamName': 'The Razzle Dazzle of Fantazzmagazzles'}, {'TeamNum': 19403, 'OPR': 26.592, 'Auto': -1.537, 'CCWM': 4.954, 'TeamName': 'Ascend Aviators'}, {'TeamNum': 7444, 'OPR': 20.492, 'Auto': 13.368, 'CCWM': -43.657, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 21381, 'OPR': 8.283, 'Auto': -3.076, 'CCWM': -23.598, 'TeamName': 'Harmony Robotics'}, {'TeamNum': 21443, 'OPR': -2.703, 'Auto': 5.959, 'CCWM': -63.855, 'TeamName': 'Lever Up'}]
USNCSAQ
[{'TeamNum': 7105, 'OPR': 127.404, 'Auto': 25.369, 'CCWM': 63.419, 'TeamName': 'SWIFT Intergalactic Space Llamas'}, {'TeamNum': 18994, 'OPR': 101.836, 'Auto': 20.285, 'CCWM': 42.445, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 6078, 'OPR': 88.346, 'Auto': 21.484, 'CCWM': 27.314, 'TeamName': 'Cut the Red Wire'}, {'TeamNum': 15707, 'OPR': 85.049, 'Auto': 29.467, 'CCWM': -11.626, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 8947, 'OPR': 81.076, 'Auto': 34.816, 'CCWM': 25.006, 'TeamName': 'Techtonics'}, {'TeamNum': 18175, 'OPR': 78.877, 'Auto': 5.104, 'CCWM': 11.181, 'TeamName': 'Techies'}, {'TeamNum': 11424, 'OPR': 78.617, 'Auto': 10.631, 'CCWM': 7.149, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 21836, 'OPR': 70.468, 'Auto': 32.544, 'CCWM': 4.41, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 15830, 'OPR': 62.996, 'Auto': 13.785, 'CCWM': -1.489, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 21502, 'OPR': 50.281, 'Auto': 21.044, 'CCWM': -35.28, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 3916, 'OPR': 43.481, 'Auto': 7.74, 'CCWM': 4.18, 'TeamName': 'Apex Robotics'}, {'TeamNum': 13883, 'OPR': 28.705, 'Auto': 1.218, 'CCWM': -10.551, 'TeamName': 'The Razzle Dazzle of Fantazzmagazzles'}, {'TeamNum': 19403, 'OPR': 26.592, 'Auto': -1.537, 'CCWM': 4.954, 'TeamName': 'Ascend Aviators'}, {'TeamNum': 7444, 'OPR': 20.492, 'Auto': 13.368, 'CCWM': -43.657, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 21381, 'OPR': 8.283, 'Auto': -3.076, 'CCWM': -23.598, 'TeamName': 'Harmony Robotics'}, {'TeamNum': 21443, 'OPR': -2.703, 'Auto': 5.959, 'CCWM': -63.855, 'TeamName': 'Lever Up'}]

i 882
{'21869', '21734', '5270', '12733', '19539', '16250', '11528', '16563', '22733', '21724', '12010', '9063', '15680', '14200', '18251', '12828', '9076', '16447', '20708', '9581', '13735', '5795'}
[{'TeamNum': 5795, 'OPR': 97.485, 'Auto': 11.383, 'CCWM': 37.292, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 15680, 'OPR': 87.245, 'Auto': 31.772, 'CCWM': 41.771, 'TeamName': 'Techno Tigers'}, {'TeamNum': 9581, 'OPR': 80.583, 'Auto': 19.451, 'CCWM': 90.276, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 14200, 'OPR': 73.57, 'Auto': 23.087, 'CCWM': 19.812, 'TeamName': 'WASP - 12B'}, {'TeamNum': 16250, 'OPR': 65.865, 'Auto': 16.013, 'CCWM': 47.673, 'TeamName': 'Currently Unnamed'}, {'TeamNum': 12733, 'OPR': 64.387, 'Auto': 9.552, 'CCWM': -19.916, 'TeamName': 'Pirates of the Neuse (formerly NUSA)'}, {'TeamNum': 21734, 'OPR': 61.438, 'Auto': 8.308, 'CCWM': 53.772, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 12828, 'OPR': 61.359, 'Auto': 12.095, 'CCWM': 3.931, 'TeamName': 'Critical Overload'}, {'TeamNum': 16447, 'OPR': 57.798, 'Auto': 6.137, 'CCWM': 31.832, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 13735, 'OPR': 55.463, 'Auto': 14.949, 'CCWM': -3.47, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 21869, 'OPR': 50.363, 'Auto': 10.401, 'CCWM': 14.92, 'TeamName': 'Mecha Masters'}, {'TeamNum': 16563, 'OPR': 44.879, 'Auto': 15.816, 'CCWM': -14.447, 'TeamName': 'Dragon Droids'}, {'TeamNum': 11528, 'OPR': 44.41, 'Auto': 9.235, 'CCWM': -25.299, 'TeamName': 'Bots of Prey'}, {'TeamNum': 22733, 'OPR': 36.398, 'Auto': 9.112, 'CCWM': 1.561, 'TeamName': 'Ghost'}, {'TeamNum': 12010, 'OPR': 30.255, 'Auto': 2.935, 'CCWM': 19.693, 'TeamName': 'ChargerBots'}, {'TeamNum': 5270, 'OPR': 26.736, 'Auto': 5.586, 'CCWM': -58.045, 'TeamName': 'Q'}, {'TeamNum': 21724, 'OPR': 19.887, 'Auto': 2.591, 'CCWM': -49.58, 'TeamName': 'Pitt Parrots'}, {'TeamNum': 19539, 'OPR': 14.354, 'Auto': 5.395, 'CCWM': -70.726, 'TeamName': 'The Tele-Ops 19539'}, {'TeamNum': 9063, 'OPR': 4.996, 'Auto': 4.457, 'CCWM': -44.206, 'TeamName': 'Claws of Steel'}, {'TeamNum': 9076, 'OPR': 4.53, 'Auto': -8.075, 'CCWM': -76.846, 'TeamName': 'Sketchy Engineering'}, {'TeamNum': 18251, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Low Battery'}, {'TeamNum': 20708, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Nano Trojans'}]
USNCGRQ
[{'TeamNum': 5795, 'OPR': 97.485, 'Auto': 11.383, 'CCWM': 37.292, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 15680, 'OPR': 87.245, 'Auto': 31.772, 'CCWM': 41.771, 'TeamName': 'Techno Tigers'}, {'TeamNum': 9581, 'OPR': 80.583, 'Auto': 19.451, 'CCWM': 90.276, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 14200, 'OPR': 73.57, 'Auto': 23.087, 'CCWM': 19.812, 'TeamName': 'WASP - 12B'}, {'TeamNum': 16250, 'OPR': 65.865, 'Auto': 16.013, 'CCWM': 47.673, 'TeamName': 'Currently Unnamed'}, {'TeamNum': 12733, 'OPR': 64.387, 'Auto': 9.552, 'CCWM': -19.916, 'TeamName': 'Pirates of the Neuse (formerly NUSA)'}, {'TeamNum': 21734, 'OPR': 61.438, 'Auto': 8.308, 'CCWM': 53.772, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 12828, 'OPR': 61.359, 'Auto': 12.095, 'CCWM': 3.931, 'TeamName': 'Critical Overload'}, {'TeamNum': 16447, 'OPR': 57.798, 'Auto': 6.137, 'CCWM': 31.832, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 13735, 'OPR': 55.463, 'Auto': 14.949, 'CCWM': -3.47, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 21869, 'OPR': 50.363, 'Auto': 10.401, 'CCWM': 14.92, 'TeamName': 'Mecha Masters'}, {'TeamNum': 16563, 'OPR': 44.879, 'Auto': 15.816, 'CCWM': -14.447, 'TeamName': 'Dragon Droids'}, {'TeamNum': 11528, 'OPR': 44.41, 'Auto': 9.235, 'CCWM': -25.299, 'TeamName': 'Bots of Prey'}, {'TeamNum': 22733, 'OPR': 36.398, 'Auto': 9.112, 'CCWM': 1.561, 'TeamName': 'Ghost'}, {'TeamNum': 12010, 'OPR': 30.255, 'Auto': 2.935, 'CCWM': 19.693, 'TeamName': 'ChargerBots'}, {'TeamNum': 5270, 'OPR': 26.736, 'Auto': 5.586, 'CCWM': -58.045, 'TeamName': 'Q'}, {'TeamNum': 21724, 'OPR': 19.887, 'Auto': 2.591, 'CCWM': -49.58, 'TeamName': 'Pitt Parrots'}, {'TeamNum': 19539, 'OPR': 14.354, 'Auto': 5.395, 'CCWM': -70.726, 'TeamName': 'The Tele-Ops 19539'}, {'TeamNum': 9063, 'OPR': 4.996, 'Auto': 4.457, 'CCWM': -44.206, 'TeamName': 'Claws of Steel'}, {'TeamNum': 9076, 'OPR': 4.53, 'Auto': -8.075, 'CCWM': -76.846, 'TeamName': 'Sketchy Engineering'}, {'TeamNum': 18251, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Low Battery'}, {'TeamNum': 20708, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Nano Trojans'}]
i 883
{'8888', '22879', '7078', '19643', '12622', '19774', '20726', '10660', '8089', '13507', '14590', '17455', '22760', '16169', '11866', '17868', '17165', '11780'}
[{'TeamNum': 22760, 'OPR': 79.691, 'Auto': 14.998, 'CCWM': 58.84, 'TeamName': 'Navy Knights'}, {'TeamNum': 11780, 'OPR': 75.349, 'Auto': 19.107, 'CCWM': 24.892, 'TeamName': 'B.L.U.E Box'}, {'TeamNum': 17455, 'OPR': 65.841, 'Auto': 19.373, 'CCWM': 28.064, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 13507, 'OPR': 63.046, 'Auto': 12.305, 'CCWM': 25.544, 'TeamName': 'Banana Brigade'}, {'TeamNum': 10660, 'OPR': 59.615, 'Auto': 21.876, 'CCWM': 25.16, 'TeamName': 'HBMS Silver Knights 10660'}, {'TeamNum': 19774, 'OPR': 56.098, 'Auto': 28.704, 'CCWM': 21.774, 'TeamName': 'Torque'}, {'TeamNum': 11866, 'OPR': 54.218, 'Auto': 17.408, 'CCWM': 14.065, 'TeamName': 'HBMS Royal Knights 11866'}, {'TeamNum': 19643, 'OPR': 54.191, 'Auto': 3.634, 'CCWM': 35.076, 'TeamName': 'Dragon Droids'}, {'TeamNum': 17165, 'OPR': 51.632, 'Auto': 3.342, 'CCWM': 14.415, 'TeamName': 'WLC W4RR10R5'}, {'TeamNum': 14590, 'OPR': 43.949, 'Auto': 3.984, 'CCWM': 23.469, 'TeamName': 'Prometheus'}, {'TeamNum': 20726, 'OPR': 23.864, 'Auto': 4.591, 'CCWM': -21.432, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 17868, 'OPR': 23.101, 'Auto': 15.985, 'CCWM': -14.986, 'TeamName': 'GRS Cooperative'}, {'TeamNum': 22879, 'OPR': 22.959, 'Auto': -1.964, 'CCWM': -46.782, 'TeamName': 'Red Spark Beta'}, {'TeamNum': 16169, 'OPR': 21.927, 'Auto': 4.371, 'CCWM': -26.789, 'TeamName': 'Banana Box'}, {'TeamNum': 8089, 'OPR': 20.238, 'Auto': -0.447, 'CCWM': -25.14, 'TeamName': 'Mainframe Meltdown'}, {'TeamNum': 7078, 'OPR': 15.436, 'Auto': 2.658, 'CCWM': -41.055, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 8888, 'OPR': 10.573, 'Auto': 5.761, 'CCWM': -30.563, 'TeamName': 'Infinity Factor'}, {'TeamNum': 12622, 'OPR': 3.173, 'Auto': 1.487, 'CCWM': -53.081, 'TeamName': 'Red Spark Alpha'}]
USNHEXQ
[{'TeamNum': 22760, 'OPR': 79.691, 'Auto': 14.998, 'CCWM': 58.84, 'TeamName': 'Navy Knights'}, {'TeamNum': 11780, 'OPR': 75.349, 'Auto': 19.107, 'CCWM': 24.892, 'TeamName': 'B.L.U.E Box'}, {'TeamNum': 17455, 'OPR': 65.841, 'Auto': 19.373, 'CCWM': 28.064, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 13507, 'OPR': 63.046, 'Auto': 12.305, 'CCWM': 25.544, 'TeamName': 'Banana Brigade'}, {'TeamNum': 10660, 'OPR': 59.615, 'Auto': 21.876, 'CCWM': 25.16, 'TeamName': 'HBMS Silver Knights 10660'}, {'TeamNum': 19774, 'OPR': 56.098, 'Auto': 28.704, 'CCWM': 21.774, 'TeamName': 'Torque'}, {'TeamNum': 11866, 'OPR': 54.218, 'Auto': 17.408, 'CCWM': 14.065, 'TeamName': 'HBMS Royal Knights 11866'}, {'TeamNum': 19643, 'OPR': 54.191, 'Auto': 3.634, 'CCWM': 35.076, 'TeamName': 'Dragon Droids'}, {'TeamNum': 17165, 'OPR': 51.632, 'Auto': 3.342, 'CCWM': 14.415, 'TeamName': 'WLC W4RR10R5'}, {'TeamNum': 14590, 'OPR': 43.949, 'Auto': 3.984, 'CCWM': 23.469, 'TeamName': 'Prometheus'}, {'TeamNum': 20726, 'OPR': 23.864, 'Auto': 4.591, 'CCWM': -21.432, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 17868, 'OPR': 23.101, 'Auto': 15.985, 'CCWM': -14.986, 'TeamName': 'GRS Cooperative'}, {'TeamNum': 22879, 'OPR': 22.959, 'Auto': -1.964, 'CCWM': -46.782, 'TeamName': 'Red Spark Beta'}, {'TeamNum': 16169, 'OPR': 21.927, 'Auto': 4.371, 'CCWM': -26.789, 'TeamName': 'Banana Box'}, {'TeamNum': 8089, 'OPR': 20.238, 'Auto': -0.447, 'CCWM': -25.14, 'TeamName': 'Mainframe Meltdown'}, {'TeamNum': 7078, 'OPR': 15.436, 'Auto': 2.658, 'CCWM': -41.055, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 8888, 'OPR': 10.573, 'Auto': 5.761, 'CCWM': -30.563, 'TeamName': 'Infinity Factor'}, {'TeamNum': 12622, 'OPR': 3.173, 'Auto': 1.487, 'CCWM': -53.081, 'TeamName': 'Red Spark Alpha'}]
i 884
{'8405', '19823', '3415', '12806', '12968', '11180', '18051', '5573', '17670', '11450', '19871', '16953', '15484', '6936', '3774', '10553', '10669', '10582', '10874', '4890', '16557', '12875', '22704'}
[{'TeamNum': 11180, 'OPR': 109.511, 'Auto': 25.295, 'CCWM': 77.008, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 18051, 'OPR': 100.007, 'Auto': 29.695, 'CCWM': 78.179, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 8405, 'OPR': 70.665, 'Auto': 22.335, 'CCWM': 3.834, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 10553, 'OPR': 70.487, 'Auto': 16.551, 'CCWM': 58.24, 'TeamName': 'RaidX'}, {'TeamNum': 6936, 'OPR': 67.74, 'Auto': 25.867, 'CCWM': 8.319, 'TeamName': 'CodeRunners'}, {'TeamNum': 10669, 'OPR': 61.344, 'Auto': 21.984, 'CCWM': 27.372, 'TeamName': 'Clutch Squad'}, {'TeamNum': 11450, 'OPR': 58.358, 'Auto': 20.029, 'CCWM': -13.624, 'TeamName': 'Dickinson Rams'}, {'TeamNum': 4890, 'OPR': 57.328, 'Auto': 13.935, 'CCWM': -17.804, 'TeamName': 'AArcHive'}, {'TeamNum': 16557, 'OPR': 52.852, 'Auto': 17.714, 'CCWM': -23.277, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 12806, 'OPR': 43.938, 'Auto': 18.258, 'CCWM': 54.7, 'TeamName': 'Roboken'}, {'TeamNum': 5573, 'OPR': 41.513, 'Auto': 8.261, 'CCWM': -43.075, 'TeamName': 'Payne Bots 5573'}, {'TeamNum': 12968, 'OPR': 35.264, 'Auto': -1.771, 'CCWM': 33.48, 'TeamName': 'Bard RoboRaptors'}, {'TeamNum': 16953, 'OPR': 31.318, 'Auto': 18.274, 'CCWM': -27.699, 'TeamName': 'FIRE'}, {'TeamNum': 17670, 'OPR': 28.873, 'Auto': 2.246, 'CCWM': 26.826, 'TeamName': 'Raider Robotics'}, {'TeamNum': 19871, 'OPR': 24.645, 'Auto': -3.854, 'CCWM': -36.252, 'TeamName': 'Orange Tornadoes'}, {'TeamNum': 22704, 'OPR': 15.824, 'Auto': 0.765, 'CCWM': 6.054, 'TeamName': 'Robo-Redwings'}, {'TeamNum': 3415, 'OPR': 12.43, 'Auto': 0.666, 'CCWM': -18.879, 'TeamName': 'Lancers'}, {'TeamNum': 15484, 'OPR': 12.422, 'Auto': 6.603, 'CCWM': -22.018, 'TeamName': 'Central High School'}, {'TeamNum': 10582, 'OPR': 12.205, 'Auto': 1.957, 'CCWM': 17.406, 'TeamName': 'Emerald Knights'}, {'TeamNum': 3774, 'OPR': 10.663, 'Auto': -0.402, 'CCWM': -45.457, 'TeamName': 'Hive Voltage'}, {'TeamNum': 19823, 'OPR': 9.551, 'Auto': 1.502, 'CCWM': -29.988, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 10874, 'OPR': 6.513, 'Auto': 1.343, 'CCWM': -63.373, 'TeamName': 'LIONS'}, {'TeamNum': 12875, 'OPR': -4.323, 'Auto': -3.46, 'CCWM': -47.247, 'TeamName': 'Snyder High School Robotics'}]
USNJNEM6
[{'TeamNum': 11180, 'OPR': 109.511, 'Auto': 25.295, 'CCWM': 77.008, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 18051, 'OPR': 100.007, 'Auto': 29.695, 'CCWM': 78.179, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 8405, 'OPR': 70.665, 'Auto': 22.335, 'CCWM': 3.834, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 10553, 'OPR': 70.487, 'Auto': 16.551, 'CCWM': 58.24, 'TeamName': 'RaidX'}, {'TeamNum': 6936, 'OPR': 67.74, 'Auto': 25.867, 'CCWM': 8.319, 'TeamName': 'CodeRunners'}, {'TeamNum': 10669, 'OPR': 61.344, 'Auto': 21.984, 'CCWM': 27.372, 'TeamName': 'Clutch Squad'}, {'TeamNum': 11450, 'OPR': 58.358, 'Auto': 20.029, 'CCWM': -13.624, 'TeamName': 'Dickinson Rams'}, {'TeamNum': 4890, 'OPR': 57.328, 'Auto': 13.935, 'CCWM': -17.804, 'TeamName': 'AArcHive'}, {'TeamNum': 16557, 'OPR': 52.852, 'Auto': 17.714, 'CCWM': -23.277, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 12806, 'OPR': 43.938, 'Auto': 18.258, 'CCWM': 54.7, 'TeamName': 'Roboken'}, {'TeamNum': 5573, 'OPR': 41.513, 'Auto': 8.261, 'CCWM': -43.075, 'TeamName': 'Payne Bots 5573'}, {'TeamNum': 12968, 'OPR': 35.264, 'Auto': -1.771, 'CCWM': 33.48, 'TeamName': 'Bard RoboRaptors'}, {'TeamNum': 16953, 'OPR': 31.318, 'Auto': 18.274, 'CCWM': -27.699, 'TeamName': 'FIRE'}, {'TeamNum': 17670, 'OPR': 28.873, 'Auto': 2.246, 'CCWM': 26.826, 'TeamName': 'Raider Robotics'}, {'TeamNum': 19871, 'OPR': 24.645, 'Auto': -3.854, 'CCWM': -36.252, 'TeamName': 'Orange Tornadoes'}, {'TeamNum': 22704, 'OPR': 15.824, 'Auto': 0.765, 'CCWM': 6.054, 'TeamName': 'Robo-Redwings'}, {'TeamNum': 3415, 'OPR': 12.43, 'Auto': 0.666, 'CCWM': -18.879, 'TeamName': 'Lancers'}, {'TeamNum': 15484, 'OPR': 12.422, 'Auto': 6.603, 'CCWM': -22.018, 'TeamName': 'Central High School'}, {'TeamNum': 10582, 'OPR': 12.205, 'Auto': 1.957, 'CCWM': 17.406, 'TeamName': 'Emerald Knights'}, {'TeamNum': 3774, 'OPR': 10.663, 'Auto': -0.402, 'CCWM': -45.457, 'TeamName': 'Hive Voltage'}, {'TeamNum': 19823, 'OPR': 9.551, 'Auto': 1.502, 'CCWM': -29.988, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 10874, 'OPR': 6.513, 'Auto': 1.343, 'CCWM': -63.373, 'TeamName': 'LIONS'}, {'TeamNum': 12875, 'OPR': -4.323, 'Auto': -3.46, 'CCWM': -47.247, 'TeamName': 'Snyder High School Robotics'}]
i 885

{'22348', '12488', '19735', '9848', '15458', '20244', '3944', '11241', '21852', '10975', '16102', '13115', '17036', '4936', '22261', '17653', '20204', '13747', '18241', '20205', '10974', '11871', '5387', '12441'}
[{'TeamNum': 17036, 'OPR': 89.055, 'Auto': 18.151, 'CCWM': 68.967, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 12488, 'OPR': 77.408, 'Auto': 19.094, 'CCWM': 26.51, 'TeamName': 'Raidiators'}, {'TeamNum': 20204, 'OPR': 68.978, 'Auto': 12.239, 'CCWM': 44.967, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 22261, 'OPR': 64.713, 'Auto': 24.965, 'CCWM': 7.957, 'TeamName': 'Hornet Blue'}, {'TeamNum': 18241, 'OPR': 60.014, 'Auto': 17.321, 'CCWM': 8.818, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 12441, 'OPR': 57.657, 'Auto': 5.948, 'CCWM': 35.001, 'TeamName': 'C.V.T.D.'}, {'TeamNum': 22348, 'OPR': 48.975, 'Auto': 16.836, 'CCWM': 9.027, 'TeamName': 'REAPR'}, {'TeamNum': 16102, 'OPR': 46.904, 'Auto': 31.932, 'CCWM': -1.514, 'TeamName': 'The Short Circuits'}, {'TeamNum': 15458, 'OPR': 42.138, 'Auto': 7.672, 'CCWM': 13.102, 'TeamName': 'Green Machine'}, {'TeamNum': 9848, 'OPR': 36.42, 'Auto': 14.005, 'CCWM': 12.263, 'TeamName': 'GearView'}, {'TeamNum': 3944, 'OPR': 36.31, 'Auto': 12.286, 'CCWM': -16.338, 'TeamName': 'Team Mercury'}, {'TeamNum': 19735, 'OPR': 34.221, 'Auto': 17.184, 'CCWM': -39.869, 'TeamName': 'Hornet Silver'}, {'TeamNum': 5387, 'OPR': 28.854, 'Auto': 10.587, 'CCWM': -35.556, 'TeamName': 'TecHounds'}, {'TeamNum': 20205, 'OPR': 27.822, 'Auto': -3.875, 'CCWM': -8.143, 'TeamName': 'Chaotic Pioneers'}, {'TeamNum': 10975, 'OPR': 26.754, 'Auto': 15.075, 'CCWM': -6.628, 'TeamName': 'Raiders-ShortCircuits'}, {'TeamNum': 21852, 'OPR': 25.722, 'Auto': 5.509, 'CCWM': 8.381, 'TeamName': 'I swear it worked last night'}, {'TeamNum': 13747, 'OPR': 25.625, 'Auto': 15.434, 'CCWM': -6.365, 'TeamName': 'Techtronic Challengers'}, {'TeamNum': 11241, 'OPR': 25.165, 'Auto': 15.387, 'CCWM': -28.664, 'TeamName': 'Blue Steel'}, {'TeamNum': 13115, 'OPR': 25.155, 'Auto': 9.339, 'CCWM': -7.376, 'TeamName': 'Brave Robotics'}, {'TeamNum': 20244, 'OPR': 18.367, 'Auto': -1.781, 'CCWM': -14.193, 'TeamName': 'Liberty Lions'}, {'TeamNum': 4936, 'OPR': 13.192, 'Auto': 4.779, 'CCWM': -1.902, 'TeamName': 'Sparks'}, {'TeamNum': 11871, 'OPR': 8.416, 'Auto': -0.592, 'CCWM': -3.682, 'TeamName': 'Voltron'}, {'TeamNum': 17653, 'OPR': 7.116, 'Auto': -4.136, 'CCWM': -12.321, 'TeamName': "Lion's Pride"}, {'TeamNum': 10974, 'OPR': -0.781, 'Auto': -3.159, 'CCWM': -52.441, 'TeamName': 'IronMariners'}]
USNJSOM6
[{'TeamNum': 17036, 'OPR': 89.055, 'Auto': 18.151, 'CCWM': 68.967, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 12488, 'OPR': 77.408, 'Auto': 19.094, 'CCWM': 26.51, 'TeamName': 'Raidiators'}, {'TeamNum': 20204, 'OPR': 68.978, 'Auto': 12.239, 'CCWM': 44.967, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 22261, 'OPR': 64.713, 'Auto': 24.965, 'CCWM': 7.957, 'TeamName': 'Hornet Blue'}, {'TeamNum': 18241, 'OPR': 60.014, 'Auto': 17.321, 'CCWM': 8.818, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 12441, 'OPR': 57.657, 'Auto': 5.948, 'CCWM': 35.001, 'TeamName': 'C.V.T.D.'}, {'TeamNum': 22348, 'OPR': 48.975, 'Auto': 16.836, 'CCWM': 9.027, 'TeamName': 'REAPR'}, {'TeamNum': 16102, 'OPR': 46.904, 'Auto': 31.932, 'CCWM': -1.514, 'TeamName': 'The Short Circuits'}, {'TeamNum': 15458, 'OPR': 42.138, 'Auto': 7.672, 'CCWM': 13.102, 'TeamName': 'Green Machine'}, {'TeamNum': 9848, 'OPR': 36.42, 'Auto': 14.005, 'CCWM': 12.263, 'TeamName': 'GearView'}, {'TeamNum': 3944, 'OPR': 36.31, 'Auto': 12.286, 'CCWM': -16.338, 'TeamName': 'Team Mercury'}, {'TeamNum': 19735, 'OPR': 34.221, 'Auto': 17.184, 'CCWM': -39.869, 'TeamName': 'Hornet Silver'}, {'TeamNum': 5387, 'OPR': 28.854, 'Auto': 10.587, 'CCWM': -35.556, 'TeamName': 'TecHounds'}, {'TeamNum': 20205, 'OPR': 27.822, 'Auto': -3.875, 'CCWM': -8.143, 'TeamName': 'Chaotic Pioneers'}, {'TeamNum': 10975, 'OPR': 26.754, 'Auto': 15.075, 'CCWM': -6.628, 'TeamName': 'Raiders-ShortCircuits'}, {'TeamNum': 21852, 'OPR': 25.722, 'Auto': 5.509, 'CCWM': 8.381, 'TeamName': 'I swear it worked last night'}, {'TeamNum': 13747, 'OPR': 25.625, 'Auto': 15.434, 'CCWM': -6.365, 'TeamName': 'Techtronic Challengers'}, {'TeamNum': 11241, 'OPR': 25.165, 'Auto': 15.387, 'CCWM': -28.664, 'TeamName': 'Blue Steel'}, {'TeamNum': 13115, 'OPR': 25.155, 'Auto': 9.339, 'CCWM': -7.376, 'TeamName': 'Brave Robotics'}, {'TeamNum': 20244, 'OPR': 18.367, 'Auto': -1.781, 'CCWM': -14.193, 'TeamName': 'Liberty Lions'}, {'TeamNum': 4936, 'OPR': 13.192, 'Auto': 4.779, 'CCWM': -1.902, 'TeamName': 'Sparks'}, {'TeamNum': 11871, 'OPR': 8.416, 'Auto': -0.592, 'CCWM': -3.682, 'TeamName': 'Voltron'}, {'TeamNum': 17653, 'OPR': 7.116, 'Auto': -4.136, 'CCWM': -12.321, 'TeamName': "Lion's Pride"}, {'TeamNum': 10974, 'OPR': -0.781, 'Auto': -3.159, 'CCWM': -52.441, 'TeamName': 'IronMariners'}]
i 886
{'7172', '7813', '20515', '14179', '20334', '15789', '15909', '21330', '12518', '19010', '14442', '12275', '21749', '16379', '10092', '21797', '18341', '22743', '16265', '12887', '10348'}
[{'TeamNum': 14179, 'OPR': 152.821, 'Auto': 47.106, 'CCWM': 115.109, 'TeamName': 'Sushi Squad'}, {'TeamNum': 7172, 'OPR': 128.434, 'Auto': 37.433, 'CCWM': 55.376, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 12887, 'OPR': 126.579, 'Auto': 31.661, 'CCWM': 87.586, 'TeamName': 'Devolt Phobos'}, {'TeamNum': 18341, 'OPR': 108.764, 'Auto': 31.401, 'CCWM': 67.7, 'TeamName': 'MechRams'}, {'TeamNum': 16379, 'OPR': 96.718, 'Auto': 37.183, 'CCWM': 32.41, 'TeamName': 'KookyBotz'}, {'TeamNum': 7813, 'OPR': 82.338, 'Auto': 16.831, 'CCWM': 67.715, 'TeamName': 'Alpha Hawks'}, {'TeamNum': 21330, 'OPR': 77.86, 'Auto': 21.335, 'CCWM': 5.46, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 21797, 'OPR': 76.496, 'Auto': 18.393, 'CCWM': 48.046, 'TeamName': 'Hack City'}, {'TeamNum': 22743, 'OPR': 74.025, 'Auto': 25.753, 'CCWM': -46.104, 'TeamName': 'ENIGMA Too'}, {'TeamNum': 16265, 'OPR': 73.943, 'Auto': 15.401, 'CCWM': 3.507, 'TeamName': 'ENIGMA'}, {'TeamNum': 10092, 'OPR': 67.729, 'Auto': 34.602, 'CCWM': -7.64, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 20515, 'OPR': 67.364, 'Auto': 5.502, 'CCWM': 17.225, 'TeamName': 'Cubed ETs'}, {'TeamNum': 10348, 'OPR': 64.882, 'Auto': 18.615, 'CCWM': -66.439, 'TeamName': 'Gear Masters'}, {'TeamNum': 15789, 'OPR': 62.03, 'Auto': 19.239, 'CCWM': 2.455, 'TeamName': 'Lovington RoboCats'}, {'TeamNum': 14442, 'OPR': 43.112, 'Auto': 9.11, 'CCWM': -39.283, 'TeamName': 'Neutrons'}, {'TeamNum': 21749, 'OPR': 41.456, 'Auto': 5.51, 'CCWM': -31.03, 'TeamName': 'Out of the Bot Robotics'}, {'TeamNum': 20334, 'OPR': 34.92, 'Auto': 15.438, 'CCWM': -46.822, 'TeamName': 'Geared Up!'}, {'TeamNum': 15909, 'OPR': 31.398, 'Auto': 17.942, 'CCWM': -39.207, 'TeamName': 'Devolt Deimos'}, {'TeamNum': 19010, 'OPR': 20.412, 'Auto': -0.116, 'CCWM': -74.286, 'TeamName': 'A.S.T.R.O. Scorpions'}, {'TeamNum': 12518, 'OPR': 9.321, 'Auto': 4.333, 'CCWM': -88.525, 'TeamName': 'Almond Robotics'}, {'TeamNum': 12275, 'OPR': 2.837, 'Auto': -5.348, 'CCWM': -58.758, 'TeamName': 'High Country Robotics'}]
USNMCMP
[{'TeamNum': 14179, 'OPR': 152.821, 'Auto': 47.106, 'CCWM': 115.109, 'TeamName': 'Sushi Squad'}, {'TeamNum': 7172, 'OPR': 128.434, 'Auto': 37.433, 'CCWM': 55.376, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 12887, 'OPR': 126.579, 'Auto': 31.661, 'CCWM': 87.586, 'TeamName': 'Devolt Phobos'}, {'TeamNum': 18341, 'OPR': 108.764, 'Auto': 31.401, 'CCWM': 67.7, 'TeamName': 'MechRams'}, {'TeamNum': 16379, 'OPR': 96.718, 'Auto': 37.183, 'CCWM': 32.41, 'TeamName': 'KookyBotz'}, {'TeamNum': 7813, 'OPR': 82.338, 'Auto': 16.831, 'CCWM': 67.715, 'TeamName': 'Alpha Hawks'}, {'TeamNum': 21330, 'OPR': 77.86, 'Auto': 21.335, 'CCWM': 5.46, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 21797, 'OPR': 76.496, 'Auto': 18.393, 'CCWM': 48.046, 'TeamName': 'Hack City'}, {'TeamNum': 22743, 'OPR': 74.025, 'Auto': 25.753, 'CCWM': -46.104, 'TeamName': 'ENIGMA Too'}, {'TeamNum': 16265, 'OPR': 73.943, 'Auto': 15.401, 'CCWM': 3.507, 'TeamName': 'ENIGMA'}, {'TeamNum': 10092, 'OPR': 67.729, 'Auto': 34.602, 'CCWM': -7.64, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 20515, 'OPR': 67.364, 'Auto': 5.502, 'CCWM': 17.225, 'TeamName': 'Cubed ETs'}, {'TeamNum': 10348, 'OPR': 64.882, 'Auto': 18.615, 'CCWM': -66.439, 'TeamName': 'Gear Masters'}, {'TeamNum': 15789, 'OPR': 62.03, 'Auto': 19.239, 'CCWM': 2.455, 'TeamName': 'Lovington RoboCats'}, {'TeamNum': 14442, 'OPR': 43.112, 'Auto': 9.11, 'CCWM': -39.283, 'TeamName': 'Neutrons'}, {'TeamNum': 21749, 'OPR': 41.456, 'Auto': 5.51, 'CCWM': -31.03, 'TeamName': 'Out of the Bot Robotics'}, {'TeamNum': 20334, 'OPR': 34.92, 'Auto': 15.438, 'CCWM': -46.822, 'TeamName': 'Geared Up!'}, {'TeamNum': 15909, 'OPR': 31.398, 'Auto': 17.942, 'CCWM': -39.207, 'TeamName': 'Devolt Deimos'}, {'TeamNum': 19010, 'OPR': 20.412, 'Auto': -0.116, 'CCWM': -74.286, 'TeamName': 'A.S.T.R.O. Scorpions'}, {'TeamNum': 12518, 'OPR': 9.321, 'Auto': 4.333, 'CCWM': -88.525, 'TeamName': 'Almond Robotics'}, {'TeamNum': 12275, 'OPR': 2.837, 'Auto': -5.348, 'CCWM': -58.758, 'TeamName': 'High Country Robotics'}]
i 887

{'11574', '22317', '20285', '21238', '21217', '22832', '20681', '20948', '18959', '15492', '18203', '9507', '22774', '11183', '21621', '21632', '16118'}
[{'TeamNum': 18203, 'OPR': 73.329, 'Auto': 24.195, 'CCWM': 56.592, 'TeamName': 'MCII'}, {'TeamNum': 11574, 'OPR': 54.028, 'Auto': 1.142, 'CCWM': 27.151, 'TeamName': 'Incognito'}, {'TeamNum': 20681, 'OPR': 52.038, 'Auto': 3.907, 'CCWM': 41.871, 'TeamName': 'Giga Bite'}, {'TeamNum': 20285, 'OPR': 39.619, 'Auto': 2.175, 'CCWM': 18.516, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 18959, 'OPR': 34.686, 'Auto': 0.673, 'CCWM': 6.073, 'TeamName': 'North Valleys High School RoboPanthers'}, {'TeamNum': 11183, 'OPR': 31.143, 'Auto': 2.916, 'CCWM': 7.515, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 22317, 'OPR': 24.885, 'Auto': 6.348, 'CCWM': -13.9, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 21217, 'OPR': 22.875, 'Auto': 7.159, 'CCWM': 6.413, 'TeamName': 'The Phoenixes'}, {'TeamNum': 22832, 'OPR': 22.652, 'Auto': 8.186, 'CCWM': -3.173, 'TeamName': 'Tech Nation: Boys & Girls Club of Reno'}, {'TeamNum': 22774, 'OPR': 20.348, 'Auto': 0.244, 'CCWM': 8.748, 'TeamName': 'URSA Major'}, {'TeamNum': 21632, 'OPR': 19.539, 'Auto': 13.002, 'CCWM': -16.093, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 16118, 'OPR': 16.28, 'Auto': 0.766, 'CCWM': -0.986, 'TeamName': '52! McQueen HS'}, {'TeamNum': 15492, 'OPR': 13.549, 'Auto': 0.273, 'CCWM': -32.217, 'TeamName': 'ELrobotiKO'}, {'TeamNum': 21621, 'OPR': 13.226, 'Auto': -1.854, 'CCWM': -40.037, 'TeamName': 'Zoomies'}, {'TeamNum': 20948, 'OPR': 8.525, 'Auto': -3.415, 'CCWM': -15.983, 'TeamName': 'Hug HS'}, {'TeamNum': 21238, 'OPR': 3.27, 'Auto': 11.952, 'CCWM': -44.325, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 9507, 'OPR': 1.262, 'Auto': -5.288, 'CCWM': -9.598, 'TeamName': 'Rubber Ducks Reedbotics'}]
USNVNOM5N
[{'TeamNum': 18203, 'OPR': 73.329, 'Auto': 24.195, 'CCWM': 56.592, 'TeamName': 'MCII'}, {'TeamNum': 11574, 'OPR': 54.028, 'Auto': 1.142, 'CCWM': 27.151, 'TeamName': 'Incognito'}, {'TeamNum': 20681, 'OPR': 52.038, 'Auto': 3.907, 'CCWM': 41.871, 'TeamName': 'Giga Bite'}, {'TeamNum': 20285, 'OPR': 39.619, 'Auto': 2.175, 'CCWM': 18.516, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 18959, 'OPR': 34.686, 'Auto': 0.673, 'CCWM': 6.073, 'TeamName': 'North Valleys High School RoboPanthers'}, {'TeamNum': 11183, 'OPR': 31.143, 'Auto': 2.916, 'CCWM': 7.515, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 22317, 'OPR': 24.885, 'Auto': 6.348, 'CCWM': -13.9, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 21217, 'OPR': 22.875, 'Auto': 7.159, 'CCWM': 6.413, 'TeamName': 'The Phoenixes'}, {'TeamNum': 22832, 'OPR': 22.652, 'Auto': 8.186, 'CCWM': -3.173, 'TeamName': 'Tech Nation: Boys & Girls Club of Reno'}, {'TeamNum': 22774, 'OPR': 20.348, 'Auto': 0.244, 'CCWM': 8.748, 'TeamName': 'URSA Major'}, {'TeamNum': 21632, 'OPR': 19.539, 'Auto': 13.002, 'CCWM': -16.093, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 16118, 'OPR': 16.28, 'Auto': 0.766, 'CCWM': -0.986, 'TeamName': '52! McQueen HS'}, {'TeamNum': 15492, 'OPR': 13.549, 'Auto': 0.273, 'CCWM': -32.217, 'TeamName': 'ELrobotiKO'}, {'TeamNum': 21621, 'OPR': 13.226, 'Auto': -1.854, 'CCWM': -40.037, 'TeamName': 'Zoomies'}, {'TeamNum': 20948, 'OPR': 8.525, 'Auto': -3.415, 'CCWM': -15.983, 'TeamName': 'Hug HS'}, {'TeamNum': 21238, 'OPR': 3.27, 'Auto': 11.952, 'CCWM': -44.325, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 9507, 'OPR': 1.262, 'Auto': -5.288, 'CCWM': -9.598, 'TeamName': 'Rubber Ducks Reedbotics'}]
i 888
{'22818', '21535', '3050', '16384', '12991', '14841', '14532', '15884', '15569', '21726', '21629', '21794', '18850'}
[{'TeamNum': 14841, 'OPR': 99.017, 'Auto': 23.959, 'CCWM': 96.477, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 12991, 'OPR': 89.429, 'Auto': 24.156, 'CCWM': 33.576, 'TeamName': 'Awkward Silence'}, {'TeamNum': 3050, 'OPR': 84.452, 'Auto': 18.122, 'CCWM': 58.1, 'TeamName': 'G-Bots'}, {'TeamNum': 15569, 'OPR': 46.318, 'Auto': 10.454, 'CCWM': 30.628, 'TeamName': 'RoboRattlers'}, {'TeamNum': 18850, 'OPR': 42.675, 'Auto': 2.749, 'CCWM': 27.782, 'TeamName': 'Kill Switch'}, {'TeamNum': 15884, 'OPR': 30.727, 'Auto': 8.302, 'CCWM': -17.113, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 21535, 'OPR': 27.255, 'Auto': 5.659, 'CCWM': 0.376, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 21629, 'OPR': 17.538, 'Auto': 0.93, 'CCWM': 0.064, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 14532, 'OPR': 13.701, 'Auto': 0.22, 'CCWM': -32.101, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 21726, 'OPR': 6.982, 'Auto': -3.264, 'CCWM': -38.143, 'TeamName': 'Laughlin Jr/Sr HS'}, {'TeamNum': 16384, 'OPR': 6.854, 'Auto': 1.453, 'CCWM': -49.399, 'TeamName': 'GREAT Bots'}, {'TeamNum': 22818, 'OPR': -0.51, 'Auto': 5.891, 'CCWM': -76.302, 'TeamName': 'Archer Bots'}, {'TeamNum': 21794, 'OPR': -3.694, 'Auto': -3.87, 'CCWM': -49.831, 'TeamName': 'Laughlin Jr/Sr HS 2'}]
USNVSOM6S
[{'TeamNum': 14841, 'OPR': 99.017, 'Auto': 23.959, 'CCWM': 96.477, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 12991, 'OPR': 89.429, 'Auto': 24.156, 'CCWM': 33.576, 'TeamName': 'Awkward Silence'}, {'TeamNum': 3050, 'OPR': 84.452, 'Auto': 18.122, 'CCWM': 58.1, 'TeamName': 'G-Bots'}, {'TeamNum': 15569, 'OPR': 46.318, 'Auto': 10.454, 'CCWM': 30.628, 'TeamName': 'RoboRattlers'}, {'TeamNum': 18850, 'OPR': 42.675, 'Auto': 2.749, 'CCWM': 27.782, 'TeamName': 'Kill Switch'}, {'TeamNum': 15884, 'OPR': 30.727, 'Auto': 8.302, 'CCWM': -17.113, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 21535, 'OPR': 27.255, 'Auto': 5.659, 'CCWM': 0.376, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 21629, 'OPR': 17.538, 'Auto': 0.93, 'CCWM': 0.064, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 14532, 'OPR': 13.701, 'Auto': 0.22, 'CCWM': -32.101, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 21726, 'OPR': 6.982, 'Auto': -3.264, 'CCWM': -38.143, 'TeamName': 'Laughlin Jr/Sr HS'}, {'TeamNum': 16384, 'OPR': 6.854, 'Auto': 1.453, 'CCWM': -49.399, 'TeamName': 'GREAT Bots'}, {'TeamNum': 22818, 'OPR': -0.51, 'Auto': 5.891, 'CCWM': -76.302, 'TeamName': 'Archer Bots'}, {'TeamNum': 21794, 'OPR': -3.694, 'Auto': -3.87, 'CCWM': -49.831, 'TeamName': 'Laughlin Jr/Sr HS 2'}]
i 889
{'21535', '11665', '18858', '12991', '19792', '14841', '14532', '15884', '21629', '21787', '18850'}
[{'TeamNum': 14841, 'OPR': 86.329, 'Auto': 17.271, 'CCWM': 80.813, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 12991, 'OPR': 69.169, 'Auto': 13.727, 'CCWM': 51.813, 'TeamName': 'Awkward Silence'}, {'TeamNum': 18858, 'OPR': 37.881, 'Auto': 18.113, 'CCWM': -3.701, 'TeamName': 'ARC - Blue'}, {'TeamNum': 15884, 'OPR': 37.097, 'Auto': 6.347, 'CCWM': 22.552, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 19792, 'OPR': 36.168, 'Auto': 3.722, 'CCWM': 15.711, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 11665, 'OPR': 16.979, 'Auto': -1.333, 'CCWM': -29.267, 'TeamName': 'Iron Falcons'}, {'TeamNum': 21787, 'OPR': 13.314, 'Auto': -0.85, 'CCWM': -33.707, 'TeamName': 'ARC - White'}, {'TeamNum': 18850, 'OPR': 12.109, 'Auto': 5.452, 'CCWM': -40.334, 'TeamName': 'Kill Switch'}, {'TeamNum': 21629, 'OPR': 9.724, 'Auto': 1.454, 'CCWM': -29.309, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 21535, 'OPR': 5.295, 'Auto': 2.3, 'CCWM': -20.874, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 14532, 'OPR': 4.269, 'Auto': -4.257, 'CCWM': -29.861, 'TeamName': 'Splitting Atoms'}]
USNVSOM5S
[{'TeamNum': 14841, 'OPR': 86.329, 'Auto': 17.271, 'CCWM': 80.813, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 12991, 'OPR': 69.169, 'Auto': 13.727, 'CCWM': 51.813, 'TeamName': 'Awkward Silence'}, {'TeamNum': 18858, 'OPR': 37.881, 'Auto': 18.113, 'CCWM': -3.701, 'TeamName': 'ARC - Blue'}, {'TeamNum': 15884, 'OPR': 37.097, 'Auto': 6.347, 'CCWM': 22.552, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 19792, 'OPR': 36.168, 'Auto': 3.722, 'CCWM': 15.711, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 11665, 'OPR': 16.979, 'Auto': -1.333, 'CCWM': -29.267, 'TeamName': 'Iron Falcons'}, {'TeamNum': 21787, 'OPR': 13.314, 'Auto': -0.85, 'CCWM': -33.707, 'TeamName': 'ARC - White'}, {'TeamNum': 18850, 'OPR': 12.109, 'Auto': 5.452, 'CCWM': -40.334, 'TeamName': 'Kill Switch'}, {'TeamNum': 21629, 'OPR': 9.724, 'Auto': 1.454, 'CCWM': -29.309, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 21535, 'OPR': 5.295, 'Auto': 2.3, 'CCWM': -20.874, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 14532, 'OPR': 4.269, 'Auto': -4.257, 'CCWM': -29.861, 'TeamName': 'Splitting Atoms'}]
i 890

{'12833', '22277', '17022', '6454', '12915', '6460', '6347', '11393', '12399', '12870', '14281', '16700', '20018', '18773', '7420', '4809', '10161', '6567', '20807', '10475', '8397', '21429', '14903', '11607', '7486', '6945', '21428'}
[{'TeamNum': 8397, 'OPR': 108.654, 'Auto': 28.055, 'CCWM': 65.925, 'TeamName': 'Beta'}, {'TeamNum': 12833, 'OPR': 106.468, 'Auto': 22.595, 'CCWM': 51.964, 'TeamName': 'Mechanical Meltdown'}, {'TeamNum': 6567, 'OPR': 78.981, 'Auto': 19.751, 'CCWM': 8.412, 'TeamName': 'Roboraiders'}, {'TeamNum': 14903, 'OPR': 72.389, 'Auto': 17.232, 'CCWM': 0.647, 'TeamName': 'SharkBots'}, {'TeamNum': 7420, 'OPR': 70.438, 'Auto': 20.516, 'CCWM': 27.378, 'TeamName': 'MechaSpartans'}, {'TeamNum': 18773, 'OPR': 69.172, 'Auto': 12.153, 'CCWM': 40.291, 'TeamName': 'Team Gambit'}, {'TeamNum': 21428, 'OPR': 66.086, 'Auto': 9.789, 'CCWM': 36.57, 'TeamName': 'Silver Eagles'}, {'TeamNum': 14281, 'OPR': 56.708, 'Auto': 22.203, 'CCWM': 51.663, 'TeamName': 'Ravena-Coeymans-Selkirk '}, {'TeamNum': 22277, 'OPR': 55.274, 'Auto': 25.902, 'CCWM': 37.719, 'TeamName': 'Deep Fried Wires'}, {'TeamNum': 10475, 'OPR': 46.155, 'Auto': 10.696, 'CCWM': 39.97, 'TeamName': 'The Spartan Bots'}, {'TeamNum': 11393, 'OPR': 41.762, 'Auto': 14.244, 'CCWM': -23.357, 'TeamName': 'BraveBots'}, {'TeamNum': 12399, 'OPR': 38.988, 'Auto': 2.78, 'CCWM': 27.503, 'TeamName': 'Mechanical Devils'}, {'TeamNum': 21429, 'OPR': 35.781, 'Auto': 10.425, 'CCWM': -24.698, 'TeamName': 'Golden Eagles'}, {'TeamNum': 6460, 'OPR': 35.178, 'Auto': 12.024, 'CCWM': -59.562, 'TeamName': 'RoboWarriors'}, {'TeamNum': 4809, 'OPR': 33.767, 'Auto': 12.714, 'CCWM': -1.68, 'TeamName': 'Botman'}, {'TeamNum': 7486, 'OPR': 30.944, 'Auto': 13.335, 'CCWM': 17.107, 'TeamName': 'Suffern Robotics'}, {'TeamNum': 12915, 'OPR': 29.113, 'Auto': 7.992, 'CCWM': 4.578, 'TeamName': 'System Override'}, {'TeamNum': 6347, 'OPR': 28.343, 'Auto': 2.083, 'CCWM': -37.51, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 6945, 'OPR': 22.214, 'Auto': -2.094, 'CCWM': -20.002, 'TeamName': 'System Overload'}, {'TeamNum': 16700, 'OPR': 22.146, 'Auto': 17.083, 'CCWM': -49.994, 'TeamName': 'JAYBOTS'}, {'TeamNum': 6454, 'OPR': 20.863, 'Auto': 9.067, 'CCWM': -42.69, 'TeamName': 'Saints Robotics'}, {'TeamNum': 11607, 'OPR': 20.328, 'Auto': 4.902, 'CCWM': -19.197, 'TeamName': 'HazMatrix'}, {'TeamNum': 20807, 'OPR': 19.558, 'Auto': -1.66, 'CCWM': -19.13, 'TeamName': 'Phoenix Robotics'}, {'TeamNum': 20018, 'OPR': 10.553, 'Auto': 2.881, 'CCWM': -29.158, 'TeamName': 'Berlin InvenTeam'}, {'TeamNum': 17022, 'OPR': 5.208, 'Auto': 2.57, 'CCWM': -22.816, 'TeamName': 'Middiebots'}, {'TeamNum': 10161, 'OPR': 3.649, 'Auto': 2.809, 'CCWM': -29.826, 'TeamName': 'Fayetteville Free Library Suits'}, {'TeamNum': 12870, 'OPR': -0.275, 'Auto': 3.609, 'CCWM': -29.772, 'TeamName': 'ScottieBots'}]
USNYEXBRQ
[{'TeamNum': 8397, 'OPR': 108.654, 'Auto': 28.055, 'CCWM': 65.925, 'TeamName': 'Beta'}, {'TeamNum': 12833, 'OPR': 106.468, 'Auto': 22.595, 'CCWM': 51.964, 'TeamName': 'Mechanical Meltdown'}, {'TeamNum': 6567, 'OPR': 78.981, 'Auto': 19.751, 'CCWM': 8.412, 'TeamName': 'Roboraiders'}, {'TeamNum': 14903, 'OPR': 72.389, 'Auto': 17.232, 'CCWM': 0.647, 'TeamName': 'SharkBots'}, {'TeamNum': 7420, 'OPR': 70.438, 'Auto': 20.516, 'CCWM': 27.378, 'TeamName': 'MechaSpartans'}, {'TeamNum': 18773, 'OPR': 69.172, 'Auto': 12.153, 'CCWM': 40.291, 'TeamName': 'Team Gambit'}, {'TeamNum': 21428, 'OPR': 66.086, 'Auto': 9.789, 'CCWM': 36.57, 'TeamName': 'Silver Eagles'}, {'TeamNum': 14281, 'OPR': 56.708, 'Auto': 22.203, 'CCWM': 51.663, 'TeamName': 'Ravena-Coeymans-Selkirk '}, {'TeamNum': 22277, 'OPR': 55.274, 'Auto': 25.902, 'CCWM': 37.719, 'TeamName': 'Deep Fried Wires'}, {'TeamNum': 10475, 'OPR': 46.155, 'Auto': 10.696, 'CCWM': 39.97, 'TeamName': 'The Spartan Bots'}, {'TeamNum': 11393, 'OPR': 41.762, 'Auto': 14.244, 'CCWM': -23.357, 'TeamName': 'BraveBots'}, {'TeamNum': 12399, 'OPR': 38.988, 'Auto': 2.78, 'CCWM': 27.503, 'TeamName': 'Mechanical Devils'}, {'TeamNum': 21429, 'OPR': 35.781, 'Auto': 10.425, 'CCWM': -24.698, 'TeamName': 'Golden Eagles'}, {'TeamNum': 6460, 'OPR': 35.178, 'Auto': 12.024, 'CCWM': -59.562, 'TeamName': 'RoboWarriors'}, {'TeamNum': 4809, 'OPR': 33.767, 'Auto': 12.714, 'CCWM': -1.68, 'TeamName': 'Botman'}, {'TeamNum': 7486, 'OPR': 30.944, 'Auto': 13.335, 'CCWM': 17.107, 'TeamName': 'Suffern Robotics'}, {'TeamNum': 12915, 'OPR': 29.113, 'Auto': 7.992, 'CCWM': 4.578, 'TeamName': 'System Override'}, {'TeamNum': 6347, 'OPR': 28.343, 'Auto': 2.083, 'CCWM': -37.51, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 6945, 'OPR': 22.214, 'Auto': -2.094, 'CCWM': -20.002, 'TeamName': 'System Overload'}, {'TeamNum': 16700, 'OPR': 22.146, 'Auto': 17.083, 'CCWM': -49.994, 'TeamName': 'JAYBOTS'}, {'TeamNum': 6454, 'OPR': 20.863, 'Auto': 9.067, 'CCWM': -42.69, 'TeamName': 'Saints Robotics'}, {'TeamNum': 11607, 'OPR': 20.328, 'Auto': 4.902, 'CCWM': -19.197, 'TeamName': 'HazMatrix'}, {'TeamNum': 20807, 'OPR': 19.558, 'Auto': -1.66, 'CCWM': -19.13, 'TeamName': 'Phoenix Robotics'}, {'TeamNum': 20018, 'OPR': 10.553, 'Auto': 2.881, 'CCWM': -29.158, 'TeamName': 'Berlin InvenTeam'}, {'TeamNum': 17022, 'OPR': 5.208, 'Auto': 2.57, 'CCWM': -22.816, 'TeamName': 'Middiebots'}, {'TeamNum': 10161, 'OPR': 3.649, 'Auto': 2.809, 'CCWM': -29.826, 'TeamName': 'Fayetteville Free Library Suits'}, {'TeamNum': 12870, 'OPR': -0.275, 'Auto': 3.609, 'CCWM': -29.772, 'TeamName': 'ScottieBots'}]
i 891
{'18826', '7164', '7662', '8818', '17384', '22942', '5477', '16145', '13867', '8013', '6942', '14461', '3540', '21605', '7120', '7417', '19506', '21361', '4017', '11649', '22692', '10738'}
[{'TeamNum': 4017, 'OPR': 75.655, 'Auto': 24.115, 'CCWM': 23.021, 'TeamName': 'RoboPandas'}, {'TeamNum': 8818, 'OPR': 71.799, 'Auto': 21.583, 'CCWM': 7.332, 'TeamName': 'Portledge Hit the Switch!'}, {'TeamNum': 14461, 'OPR': 65.892, 'Auto': 9.04, 'CCWM': 33.165, 'TeamName': 'RoboHawks'}, {'TeamNum': 21605, 'OPR': 61.053, 'Auto': 8.05, 'CCWM': 33.096, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 11649, 'OPR': 53.105, 'Auto': 16.365, 'CCWM': -8.155, 'TeamName': 'Portledge Robo Time'}, {'TeamNum': 10738, 'OPR': 51.613, 'Auto': 8.174, 'CCWM': 20.733, 'TeamName': 'SBS  Bears'}, {'TeamNum': 5477, 'OPR': 50.791, 'Auto': 22.03, 'CCWM': 5.22, 'TeamName': 'Innovo'}, {'TeamNum': 16145, 'OPR': 50.741, 'Auto': 9.325, 'CCWM': 21.098, 'TeamName': 'Sea Lions'}, {'TeamNum': 22692, 'OPR': 49.346, 'Auto': 14.017, 'CCWM': 6.643, 'TeamName': 'Portledge Duct Tape and Pizza Bots'}, {'TeamNum': 22942, 'OPR': 45.76, 'Auto': 9.83, 'CCWM': 7.828, 'TeamName': 'Iron Phoenix '}, {'TeamNum': 17384, 'OPR': 43.565, 'Auto': 23.372, 'CCWM': 13.714, 'TeamName': 'Rambam Rambots'}, {'TeamNum': 7120, 'OPR': 41.679, 'Auto': 12.218, 'CCWM': -3.431, 'TeamName': 'Bionica'}, {'TeamNum': 8013, 'OPR': 41.464, 'Auto': 9.121, 'CCWM': -3.964, 'TeamName': 'Team Kuiper'}, {'TeamNum': 7164, 'OPR': 40.912, 'Auto': -1.472, 'CCWM': 0.886, 'TeamName': 'FalconBots'}, {'TeamNum': 7417, 'OPR': 35.508, 'Auto': 4.376, 'CCWM': 25.707, 'TeamName': 'Portledge Robotics'}, {'TeamNum': 18826, 'OPR': 24.864, 'Auto': 13.117, 'CCWM': -26.752, 'TeamName': 'Elevated Creations'}, {'TeamNum': 3540, 'OPR': 24.319, 'Auto': 18.171, 'CCWM': 9.497, 'TeamName': 'RoboBoogie'}, {'TeamNum': 6942, 'OPR': 23.791, 'Auto': -3.232, 'CCWM': -19.152, 'TeamName': 'Pandemonium'}, {'TeamNum': 19506, 'OPR': 21.728, 'Auto': 1.588, 'CCWM': -25.815, 'TeamName': 'Chickenators'}, {'TeamNum': 13867, 'OPR': 18.078, 'Auto': 7.158, 'CCWM': -10.907, 'TeamName': 'BayBots'}, {'TeamNum': 7662, 'OPR': 5.973, 'Auto': -9.996, 'CCWM': -51.785, 'TeamName': 'Dragons'}, {'TeamNum': 21361, 'OPR': -5.226, 'Auto': 0.594, 'CCWM': -50.446, 'TeamName': 'Mustangs'}]
USNYLILVQ
[{'TeamNum': 4017, 'OPR': 75.655, 'Auto': 24.115, 'CCWM': 23.021, 'TeamName': 'RoboPandas'}, {'TeamNum': 8818, 'OPR': 71.799, 'Auto': 21.583, 'CCWM': 7.332, 'TeamName': 'Portledge Hit the Switch!'}, {'TeamNum': 14461, 'OPR': 65.892, 'Auto': 9.04, 'CCWM': 33.165, 'TeamName': 'RoboHawks'}, {'TeamNum': 21605, 'OPR': 61.053, 'Auto': 8.05, 'CCWM': 33.096, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 11649, 'OPR': 53.105, 'Auto': 16.365, 'CCWM': -8.155, 'TeamName': 'Portledge Robo Time'}, {'TeamNum': 10738, 'OPR': 51.613, 'Auto': 8.174, 'CCWM': 20.733, 'TeamName': 'SBS  Bears'}, {'TeamNum': 5477, 'OPR': 50.791, 'Auto': 22.03, 'CCWM': 5.22, 'TeamName': 'Innovo'}, {'TeamNum': 16145, 'OPR': 50.741, 'Auto': 9.325, 'CCWM': 21.098, 'TeamName': 'Sea Lions'}, {'TeamNum': 22692, 'OPR': 49.346, 'Auto': 14.017, 'CCWM': 6.643, 'TeamName': 'Portledge Duct Tape and Pizza Bots'}, {'TeamNum': 22942, 'OPR': 45.76, 'Auto': 9.83, 'CCWM': 7.828, 'TeamName': 'Iron Phoenix '}, {'TeamNum': 17384, 'OPR': 43.565, 'Auto': 23.372, 'CCWM': 13.714, 'TeamName': 'Rambam Rambots'}, {'TeamNum': 7120, 'OPR': 41.679, 'Auto': 12.218, 'CCWM': -3.431, 'TeamName': 'Bionica'}, {'TeamNum': 8013, 'OPR': 41.464, 'Auto': 9.121, 'CCWM': -3.964, 'TeamName': 'Team Kuiper'}, {'TeamNum': 7164, 'OPR': 40.912, 'Auto': -1.472, 'CCWM': 0.886, 'TeamName': 'FalconBots'}, {'TeamNum': 7417, 'OPR': 35.508, 'Auto': 4.376, 'CCWM': 25.707, 'TeamName': 'Portledge Robotics'}, {'TeamNum': 18826, 'OPR': 24.864, 'Auto': 13.117, 'CCWM': -26.752, 'TeamName': 'Elevated Creations'}, {'TeamNum': 3540, 'OPR': 24.319, 'Auto': 18.171, 'CCWM': 9.497, 'TeamName': 'RoboBoogie'}, {'TeamNum': 6942, 'OPR': 23.791, 'Auto': -3.232, 'CCWM': -19.152, 'TeamName': 'Pandemonium'}, {'TeamNum': 19506, 'OPR': 21.728, 'Auto': 1.588, 'CCWM': -25.815, 'TeamName': 'Chickenators'}, {'TeamNum': 13867, 'OPR': 18.078, 'Auto': 7.158, 'CCWM': -10.907, 'TeamName': 'BayBots'}, {'TeamNum': 7662, 'OPR': 5.973, 'Auto': -9.996, 'CCWM': -51.785, 'TeamName': 'Dragons'}, {'TeamNum': 21361, 'OPR': -5.226, 'Auto': 0.594, 'CCWM': -50.446, 'TeamName': 'Mustangs'}]

i 892
{'19778', '21865', '6085', '5140', '6298', '5501', '14174', '8642', '20744', '8581', '11580', '14261', '12166', '12211', '20116', '12802', '17246', '10211', '11187', '19804', '14279', '7324', '10117'}
[{'TeamNum': 8642, 'OPR': 112.252, 'Auto': 32.788, 'CCWM': 67.692, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 19804, 'OPR': 78.347, 'Auto': 26.023, 'CCWM': 58.203, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 14261, 'OPR': 69.986, 'Auto': 12.041, 'CCWM': 32.148, 'TeamName': 'Wreck Less'}, {'TeamNum': 20116, 'OPR': 61.672, 'Auto': 8.341, 'CCWM': 2.235, 'TeamName': "Where's The Tape Measure? "}, {'TeamNum': 14174, 'OPR': 61.318, 'Auto': 18.421, 'CCWM': 6.289, 'TeamName': 'Cougar Robotics'}, {'TeamNum': 7324, 'OPR': 54.518, 'Auto': 7.667, 'CCWM': 39.558, 'TeamName': 'Oxymorons'}, {'TeamNum': 20744, 'OPR': 48.821, 'Auto': 12.957, 'CCWM': 28.092, 'TeamName': '24 Karat'}, {'TeamNum': 5140, 'OPR': 48.778, 'Auto': 4.15, 'CCWM': -2.586, 'TeamName': 'WACO Aerobotics'}, {'TeamNum': 17246, 'OPR': 45.965, 'Auto': 11.186, 'CCWM': -13.15, 'TeamName': 'Cyborg Puppies'}, {'TeamNum': 19778, 'OPR': 40.547, 'Auto': 14.407, 'CCWM': 1.662, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 5501, 'OPR': 39.745, 'Auto': 2.723, 'CCWM': -2.349, 'TeamName': 'VW Robotics'}, {'TeamNum': 21865, 'OPR': 34.337, 'Auto': 11.244, 'CCWM': 2.527, 'TeamName': 'Fe2O3'}, {'TeamNum': 6085, 'OPR': 33.299, 'Auto': 4.434, 'CCWM': 3.818, 'TeamName': 'Electro/Mechanically Controlled Chaos'}, {'TeamNum': 8581, 'OPR': 32.712, 'Auto': 14.473, 'CCWM': 3.582, 'TeamName': 'Ædificatores'}, {'TeamNum': 12166, 'OPR': 32.361, 'Auto': -4.983, 'CCWM': 7.667, 'TeamName': 'New Bremen Techno Birds'}, {'TeamNum': 11187, 'OPR': 27.704, 'Auto': 17.175, 'CCWM': -26.304, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 6298, 'OPR': 24.01, 'Auto': 2.365, 'CCWM': -25.651, 'TeamName': 'Tech Titans'}, {'TeamNum': 12802, 'OPR': 23.718, 'Auto': 2.648, 'CCWM': -12.391, 'TeamName': 'We Will Bot You'}, {'TeamNum': 11580, 'OPR': 19.192, 'Auto': 3.839, 'CCWM': -32.318, 'TeamName': 'EagleBots'}, {'TeamNum': 12211, 'OPR': 15.806, 'Auto': -4.506, 'CCWM': -18.57, 'TeamName': 'Trial & Error'}, {'TeamNum': 10211, 'OPR': 11.185, 'Auto': 3.406, 'CCWM': -48.457, 'TeamName': 'Team Hercules'}, {'TeamNum': 14279, 'OPR': 5.219, 'Auto': -4.59, 'CCWM': -33.8, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 10117, 'OPR': 1.597, 'Auto': -0.689, 'CCWM': -38.232, 'TeamName': 'Party Pandas'}]
USOHVWQ
[{'TeamNum': 8642, 'OPR': 112.252, 'Auto': 32.788, 'CCWM': 67.692, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 19804, 'OPR': 78.347, 'Auto': 26.023, 'CCWM': 58.203, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 14261, 'OPR': 69.986, 'Auto': 12.041, 'CCWM': 32.148, 'TeamName': 'Wreck Less'}, {'TeamNum': 20116, 'OPR': 61.672, 'Auto': 8.341, 'CCWM': 2.235, 'TeamName': "Where's The Tape Measure? "}, {'TeamNum': 14174, 'OPR': 61.318, 'Auto': 18.421, 'CCWM': 6.289, 'TeamName': 'Cougar Robotics'}, {'TeamNum': 7324, 'OPR': 54.518, 'Auto': 7.667, 'CCWM': 39.558, 'TeamName': 'Oxymorons'}, {'TeamNum': 20744, 'OPR': 48.821, 'Auto': 12.957, 'CCWM': 28.092, 'TeamName': '24 Karat'}, {'TeamNum': 5140, 'OPR': 48.778, 'Auto': 4.15, 'CCWM': -2.586, 'TeamName': 'WACO Aerobotics'}, {'TeamNum': 17246, 'OPR': 45.965, 'Auto': 11.186, 'CCWM': -13.15, 'TeamName': 'Cyborg Puppies'}, {'TeamNum': 19778, 'OPR': 40.547, 'Auto': 14.407, 'CCWM': 1.662, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 5501, 'OPR': 39.745, 'Auto': 2.723, 'CCWM': -2.349, 'TeamName': 'VW Robotics'}, {'TeamNum': 21865, 'OPR': 34.337, 'Auto': 11.244, 'CCWM': 2.527, 'TeamName': 'Fe2O3'}, {'TeamNum': 6085, 'OPR': 33.299, 'Auto': 4.434, 'CCWM': 3.818, 'TeamName': 'Electro/Mechanically Controlled Chaos'}, {'TeamNum': 8581, 'OPR': 32.712, 'Auto': 14.473, 'CCWM': 3.582, 'TeamName': 'Ædificatores'}, {'TeamNum': 12166, 'OPR': 32.361, 'Auto': -4.983, 'CCWM': 7.667, 'TeamName': 'New Bremen Techno Birds'}, {'TeamNum': 11187, 'OPR': 27.704, 'Auto': 17.175, 'CCWM': -26.304, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 6298, 'OPR': 24.01, 'Auto': 2.365, 'CCWM': -25.651, 'TeamName': 'Tech Titans'}, {'TeamNum': 12802, 'OPR': 23.718, 'Auto': 2.648, 'CCWM': -12.391, 'TeamName': 'We Will Bot You'}, {'TeamNum': 11580, 'OPR': 19.192, 'Auto': 3.839, 'CCWM': -32.318, 'TeamName': 'EagleBots'}, {'TeamNum': 12211, 'OPR': 15.806, 'Auto': -4.506, 'CCWM': -18.57, 'TeamName': 'Trial & Error'}, {'TeamNum': 10211, 'OPR': 11.185, 'Auto': 3.406, 'CCWM': -48.457, 'TeamName': 'Team Hercules'}, {'TeamNum': 14279, 'OPR': 5.219, 'Auto': -4.59, 'CCWM': -33.8, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 10117, 'OPR': 1.597, 'Auto': -0.689, 'CCWM': -38.232, 'TeamName': 'Party Pandas'}]
i 893
{'14365', '17978', '22564', '18386', '22448', '16414', '12056', '20317', '7136', '16749', '18275', '16892', '4969', '10464', '5040', '6133', '20322', '8719', '16284', '9952', '12768', '11781', '20104'}
[{'TeamNum': 7136, 'OPR': 102.039, 'Auto': 28.044, 'CCWM': 55.264, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 18275, 'OPR': 95.936, 'Auto': 17.016, 'CCWM': 37.007, 'TeamName': 'SubZero'}, {'TeamNum': 17978, 'OPR': 88.931, 'Auto': 19.504, 'CCWM': 39.037, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 6133, 'OPR': 83.237, 'Auto': 13.159, 'CCWM': 41.492, 'TeamName': 'The "NUTS!"'}, {'TeamNum': 4969, 'OPR': 69.495, 'Auto': 4.144, 'CCWM': 32.282, 'TeamName': 'Robot-X'}, {'TeamNum': 5040, 'OPR': 65.924, 'Auto': 14.48, 'CCWM': 26.583, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 14365, 'OPR': 65.271, 'Auto': 9.013, 'CCWM': 17.948, 'TeamName': 'Summit Knights'}, {'TeamNum': 8719, 'OPR': 50.347, 'Auto': 7.173, 'CCWM': 7.329, 'TeamName': 'Quantum Leap'}, {'TeamNum': 16749, 'OPR': 49.177, 'Auto': 10.168, 'CCWM': 23.813, 'TeamName': 'Thunder Bolts'}, {'TeamNum': 9952, 'OPR': 47.849, 'Auto': 8.065, 'CCWM': -2.31, 'TeamName': 'CHCA Beak Squad 7-8'}, {'TeamNum': 16284, 'OPR': 41.262, 'Auto': 2.476, 'CCWM': -3.359, 'TeamName': '8 Bit Bandits'}, {'TeamNum': 20317, 'OPR': 32.557, 'Auto': 4.675, 'CCWM': -34.889, 'TeamName': 'Ursuline Academy - Cincinnati'}, {'TeamNum': 22564, 'OPR': 30.135, 'Auto': -1.199, 'CCWM': -15.382, 'TeamName': 'The Talawanda Tubers'}, {'TeamNum': 18386, 'OPR': 28.583, 'Auto': 2.291, 'CCWM': 6.685, 'TeamName': 'Parallax Robotics'}, {'TeamNum': 20322, 'OPR': 28.383, 'Auto': 7.114, 'CCWM': -14.084, 'TeamName': 'Big Blue Bytes'}, {'TeamNum': 16892, 'OPR': 22.735, 'Auto': 9.032, 'CCWM': -0.279, 'TeamName': 'ENVISION: The Electric Warriors'}, {'TeamNum': 11781, 'OPR': 20.665, 'Auto': 0.618, 'CCWM': -65.275, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 20104, 'OPR': 20.159, 'Auto': -3.393, 'CCWM': -33.955, 'TeamName': '(INSERT_NAME_HERE)'}, {'TeamNum': 10464, 'OPR': 18.42, 'Auto': 2.586, 'CCWM': -5.803, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 12768, 'OPR': 18.14, 'Auto': -3.052, 'CCWM': -49.508, 'TeamName': 'INNOV-8'}, {'TeamNum': 16414, 'OPR': 16.786, 'Auto': -4.347, 'CCWM': -6.142, 'TeamName': 'Hot Cup of Java'}, {'TeamNum': 12056, 'OPR': 14.115, 'Auto': 0.132, 'CCWM': -18.586, 'TeamName': 'Aves Ablaze'}, {'TeamNum': 22448, 'OPR': 2.661, 'Auto': -1.14, 'CCWM': -49.215, 'TeamName': 'R.A.T.S. (Robotics and Technology Squad)'}]
USOHCIQ
[{'TeamNum': 7136, 'OPR': 102.039, 'Auto': 28.044, 'CCWM': 55.264, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 18275, 'OPR': 95.936, 'Auto': 17.016, 'CCWM': 37.007, 'TeamName': 'SubZero'}, {'TeamNum': 17978, 'OPR': 88.931, 'Auto': 19.504, 'CCWM': 39.037, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 6133, 'OPR': 83.237, 'Auto': 13.159, 'CCWM': 41.492, 'TeamName': 'The "NUTS!"'}, {'TeamNum': 4969, 'OPR': 69.495, 'Auto': 4.144, 'CCWM': 32.282, 'TeamName': 'Robot-X'}, {'TeamNum': 5040, 'OPR': 65.924, 'Auto': 14.48, 'CCWM': 26.583, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 14365, 'OPR': 65.271, 'Auto': 9.013, 'CCWM': 17.948, 'TeamName': 'Summit Knights'}, {'TeamNum': 8719, 'OPR': 50.347, 'Auto': 7.173, 'CCWM': 7.329, 'TeamName': 'Quantum Leap'}, {'TeamNum': 16749, 'OPR': 49.177, 'Auto': 10.168, 'CCWM': 23.813, 'TeamName': 'Thunder Bolts'}, {'TeamNum': 9952, 'OPR': 47.849, 'Auto': 8.065, 'CCWM': -2.31, 'TeamName': 'CHCA Beak Squad 7-8'}, {'TeamNum': 16284, 'OPR': 41.262, 'Auto': 2.476, 'CCWM': -3.359, 'TeamName': '8 Bit Bandits'}, {'TeamNum': 20317, 'OPR': 32.557, 'Auto': 4.675, 'CCWM': -34.889, 'TeamName': 'Ursuline Academy - Cincinnati'}, {'TeamNum': 22564, 'OPR': 30.135, 'Auto': -1.199, 'CCWM': -15.382, 'TeamName': 'The Talawanda Tubers'}, {'TeamNum': 18386, 'OPR': 28.583, 'Auto': 2.291, 'CCWM': 6.685, 'TeamName': 'Parallax Robotics'}, {'TeamNum': 20322, 'OPR': 28.383, 'Auto': 7.114, 'CCWM': -14.084, 'TeamName': 'Big Blue Bytes'}, {'TeamNum': 16892, 'OPR': 22.735, 'Auto': 9.032, 'CCWM': -0.279, 'TeamName': 'ENVISION: The Electric Warriors'}, {'TeamNum': 11781, 'OPR': 20.665, 'Auto': 0.618, 'CCWM': -65.275, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 20104, 'OPR': 20.159, 'Auto': -3.393, 'CCWM': -33.955, 'TeamName': '(INSERT_NAME_HERE)'}, {'TeamNum': 10464, 'OPR': 18.42, 'Auto': 2.586, 'CCWM': -5.803, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 12768, 'OPR': 18.14, 'Auto': -3.052, 'CCWM': -49.508, 'TeamName': 'INNOV-8'}, {'TeamNum': 16414, 'OPR': 16.786, 'Auto': -4.347, 'CCWM': -6.142, 'TeamName': 'Hot Cup of Java'}, {'TeamNum': 12056, 'OPR': 14.115, 'Auto': 0.132, 'CCWM': -18.586, 'TeamName': 'Aves Ablaze'}, {'TeamNum': 22448, 'OPR': 2.661, 'Auto': -1.14, 'CCWM': -49.215, 'TeamName': 'R.A.T.S. (Robotics and Technology Squad)'}]

i 894
{'13727', '4097', '18119', '750', '19856', '4511', '12808', '187', '3965', '22506', '19439', '3058', '12000', '267', '8610', '11556', '18108'}
[{'TeamNum': 12808, 'OPR': 141.339, 'Auto': 26.754, 'CCWM': 98.584, 'TeamName': 'RevAmped Robotics'}, {'TeamNum': 8610, 'OPR': 113.395, 'Auto': 30.832, 'CCWM': 56.307, 'TeamName': 'ToborTech'}, {'TeamNum': 18108, 'OPR': 90.136, 'Auto': 22.686, 'CCWM': 34.685, 'TeamName': 'High Voltage'}, {'TeamNum': 19439, 'OPR': 87.953, 'Auto': 19.136, 'CCWM': 43.225, 'TeamName': 'Disconnect '}, {'TeamNum': 18119, 'OPR': 80.224, 'Auto': 27.864, 'CCWM': 34.663, 'TeamName': 'Mostly Operational'}, {'TeamNum': 187, 'OPR': 72.766, 'Auto': 20.342, 'CCWM': 34.645, 'TeamName': 'Phoenix'}, {'TeamNum': 4097, 'OPR': 63.22, 'Auto': 15.319, 'CCWM': 6.546, 'TeamName': 'The Pac-Bots'}, {'TeamNum': 12000, 'OPR': 53.145, 'Auto': 12.861, 'CCWM': -16.944, 'TeamName': 'Professional Bodgers'}, {'TeamNum': 4511, 'OPR': 49.827, 'Auto': 1.402, 'CCWM': -17.909, 'TeamName': 'Maker Industries'}, {'TeamNum': 750, 'OPR': 44.434, 'Auto': 16.76, 'CCWM': 10.695, 'TeamName': 'Gears in Motion'}, {'TeamNum': 3058, 'OPR': 44.305, 'Auto': 8.289, 'CCWM': -4.528, 'TeamName': 'Live Wire'}, {'TeamNum': 22506, 'OPR': 35.469, 'Auto': 11.641, 'CCWM': 18.351, 'TeamName': 'JagWires'}, {'TeamNum': 19856, 'OPR': 29.106, 'Auto': 8.792, 'CCWM': -16.59, 'TeamName': 'Almost Reliable Robotics'}, {'TeamNum': 13727, 'OPR': 17.29, 'Auto': 1.266, 'CCWM': -71.314, 'TeamName': 'Juntos Unidos'}, {'TeamNum': 3965, 'OPR': 14.631, 'Auto': 4.306, 'CCWM': -55.855, 'TeamName': 'Twisted Metal'}, {'TeamNum': 267, 'OPR': 10.675, 'Auto': -9.706, 'CCWM': -77.22, 'TeamName': 'EMP'}, {'TeamNum': 11556, 'OPR': -8.798, 'Auto': 2.999, 'CCWM': -81.69, 'TeamName': 'Valley Catholic Robotics'}]
USORSFLT
[{'TeamNum': 12808, 'OPR': 141.339, 'Auto': 26.754, 'CCWM': 98.584, 'TeamName': 'RevAmped Robotics'}, {'TeamNum': 8610, 'OPR': 113.395, 'Auto': 30.832, 'CCWM': 56.307, 'TeamName': 'ToborTech'}, {'TeamNum': 18108, 'OPR': 90.136, 'Auto': 22.686, 'CCWM': 34.685, 'TeamName': 'High Voltage'}, {'TeamNum': 19439, 'OPR': 87.953, 'Auto': 19.136, 'CCWM': 43.225, 'TeamName': 'Disconnect '}, {'TeamNum': 18119, 'OPR': 80.224, 'Auto': 27.864, 'CCWM': 34.663, 'TeamName': 'Mostly Operational'}, {'TeamNum': 187, 'OPR': 72.766, 'Auto': 20.342, 'CCWM': 34.645, 'TeamName': 'Phoenix'}, {'TeamNum': 4097, 'OPR': 63.22, 'Auto': 15.319, 'CCWM': 6.546, 'TeamName': 'The Pac-Bots'}, {'TeamNum': 12000, 'OPR': 53.145, 'Auto': 12.861, 'CCWM': -16.944, 'TeamName': 'Professional Bodgers'}, {'TeamNum': 4511, 'OPR': 49.827, 'Auto': 1.402, 'CCWM': -17.909, 'TeamName': 'Maker Industries'}, {'TeamNum': 750, 'OPR': 44.434, 'Auto': 16.76, 'CCWM': 10.695, 'TeamName': 'Gears in Motion'}, {'TeamNum': 3058, 'OPR': 44.305, 'Auto': 8.289, 'CCWM': -4.528, 'TeamName': 'Live Wire'}, {'TeamNum': 22506, 'OPR': 35.469, 'Auto': 11.641, 'CCWM': 18.351, 'TeamName': 'JagWires'}, {'TeamNum': 19856, 'OPR': 29.106, 'Auto': 8.792, 'CCWM': -16.59, 'TeamName': 'Almost Reliable Robotics'}, {'TeamNum': 13727, 'OPR': 17.29, 'Auto': 1.266, 'CCWM': -71.314, 'TeamName': 'Juntos Unidos'}, {'TeamNum': 3965, 'OPR': 14.631, 'Auto': 4.306, 'CCWM': -55.855, 'TeamName': 'Twisted Metal'}, {'TeamNum': 267, 'OPR': 10.675, 'Auto': -9.706, 'CCWM': -77.22, 'TeamName': 'EMP'}, {'TeamNum': 11556, 'OPR': -8.798, 'Auto': 2.999, 'CCWM': -81.69, 'TeamName': 'Valley Catholic Robotics'}]
i 895
{'21609', '7604', '13784', '8188', '8132', '7100', '5198', '11547', '8892', '20790'}
[{'TeamNum': 8132, 'OPR': 49.825, 'Auto': 8.784, 'CCWM': 26.97, 'TeamName': 'Gear Heads'}, {'TeamNum': 7604, 'OPR': 43.183, 'Auto': 24.269, 'CCWM': 8.724, 'TeamName': 'DWAI'}, {'TeamNum': 8892, 'OPR': 29.447, 'Auto': 17.962, 'CCWM': 15.509, 'TeamName': 'PHRED'}, {'TeamNum': 13784, 'OPR': 29.28, 'Auto': -2.06, 'CCWM': 3.562, 'TeamName': 'Lightning'}, {'TeamNum': 8188, 'OPR': 28.688, 'Auto': -1.404, 'CCWM': 0.576, 'TeamName': 'Gear Heads'}, {'TeamNum': 21609, 'OPR': 27.508, 'Auto': 3.778, 'CCWM': 12.041, 'TeamName': 'PDX OPPS'}, {'TeamNum': 7100, 'OPR': 20.297, 'Auto': 1.203, 'CCWM': 0.81, 'TeamName': 'Good Enough'}, {'TeamNum': 20790, 'OPR': 14.756, 'Auto': 1.304, 'CCWM': -15.7, 'TeamName': 'Hawkbot1cs'}, {'TeamNum': 11547, 'OPR': 10.536, 'Auto': 1.738, 'CCWM': -14.614, 'TeamName': 'Tech No Logic'}, {'TeamNum': 5198, 'OPR': 8.312, 'Auto': 1.237, 'CCWM': -35.118, 'TeamName': 'Wingnuts'}]
USORPAQ
[{'TeamNum': 8132, 'OPR': 49.825, 'Auto': 8.784, 'CCWM': 26.97, 'TeamName': 'Gear Heads'}, {'TeamNum': 7604, 'OPR': 43.183, 'Auto': 24.269, 'CCWM': 8.724, 'TeamName': 'DWAI'}, {'TeamNum': 8892, 'OPR': 29.447, 'Auto': 17.962, 'CCWM': 15.509, 'TeamName': 'PHRED'}, {'TeamNum': 13784, 'OPR': 29.28, 'Auto': -2.06, 'CCWM': 3.562, 'TeamName': 'Lightning'}, {'TeamNum': 8188, 'OPR': 28.688, 'Auto': -1.404, 'CCWM': 0.576, 'TeamName': 'Gear Heads'}, {'TeamNum': 21609, 'OPR': 27.508, 'Auto': 3.778, 'CCWM': 12.041, 'TeamName': 'PDX OPPS'}, {'TeamNum': 7100, 'OPR': 20.297, 'Auto': 1.203, 'CCWM': 0.81, 'TeamName': 'Good Enough'}, {'TeamNum': 20790, 'OPR': 14.756, 'Auto': 1.304, 'CCWM': -15.7, 'TeamName': 'Hawkbot1cs'}, {'TeamNum': 11547, 'OPR': 10.536, 'Auto': 1.738, 'CCWM': -14.614, 'TeamName': 'Tech No Logic'}, {'TeamNum': 5198, 'OPR': 8.312, 'Auto': 1.237, 'CCWM': -35.118, 'TeamName': 'Wingnuts'}]
i 896
{'9060', '15436', '17365', '17367', '7497', '7474', '7496', '7470', '7473', '7498', '17366', '17368', '7499'}
[{'TeamNum': 7470, 'OPR': 15.867, 'Auto': 4.154, 'CCWM': 10.926, 'TeamName': 'Quicker-Picker-Upper'}, {'TeamNum': 17368, 'OPR': 15.78, 'Auto': -0.772, 'CCWM': 7.682, 'TeamName': 'The Scavengers'}, {'TeamNum': 7498, 'OPR': 15.269, 'Auto': 1.425, 'CCWM': 13.742, 'TeamName': 'The Wild Childs'}, {'TeamNum': 15436, 'OPR': 12.114, 'Auto': -2.116, 'CCWM': 11.022, 'TeamName': 'Johnny'}, {'TeamNum': 7473, 'OPR': 11.847, 'Auto': 0.466, 'CCWM': -5.338, 'TeamName': 'Rusty Russells'}, {'TeamNum': 7496, 'OPR': 10.432, 'Auto': 0.322, 'CCWM': 4.928, 'TeamName': 'Masked Mustaches'}, {'TeamNum': 7474, 'OPR': 8.4, 'Auto': 0.759, 'CCWM': -3.368, 'TeamName': 'Sippy Sipes'}, {'TeamNum': 17365, 'OPR': 7.455, 'Auto': 1.587, 'CCWM': -0.603, 'TeamName': 'Munship'}, {'TeamNum': 17367, 'OPR': 5.995, 'Auto': 4.681, 'CCWM': 6.161, 'TeamName': 'Say yes to the Robot'}, {'TeamNum': 17366, 'OPR': 0.807, 'Auto': -1.383, 'CCWM': -13.719, 'TeamName': 'Building Kings'}, {'TeamNum': 7497, 'OPR': -0.278, 'Auto': -0.417, 'CCWM': 6.628, 'TeamName': 'Ravenous White Parrots '}, {'TeamNum': 7499, 'OPR': -1.013, 'Auto': 2.208, 'CCWM': -18.178, 'TeamName': 'Nerdy Girls'}, {'TeamNum': 9060, 'OPR': -3.092, 'Auto': 2.032, 'CCWM': -20.231, 'TeamName': 'Smarties'}]
USORUMQ
[{'TeamNum': 7470, 'OPR': 15.867, 'Auto': 4.154, 'CCWM': 10.926, 'TeamName': 'Quicker-Picker-Upper'}, {'TeamNum': 17368, 'OPR': 15.78, 'Auto': -0.772, 'CCWM': 7.682, 'TeamName': 'The Scavengers'}, {'TeamNum': 7498, 'OPR': 15.269, 'Auto': 1.425, 'CCWM': 13.742, 'TeamName': 'The Wild Childs'}, {'TeamNum': 15436, 'OPR': 12.114, 'Auto': -2.116, 'CCWM': 11.022, 'TeamName': 'Johnny'}, {'TeamNum': 7473, 'OPR': 11.847, 'Auto': 0.466, 'CCWM': -5.338, 'TeamName': 'Rusty Russells'}, {'TeamNum': 7496, 'OPR': 10.432, 'Auto': 0.322, 'CCWM': 4.928, 'TeamName': 'Masked Mustaches'}, {'TeamNum': 7474, 'OPR': 8.4, 'Auto': 0.759, 'CCWM': -3.368, 'TeamName': 'Sippy Sipes'}, {'TeamNum': 17365, 'OPR': 7.455, 'Auto': 1.587, 'CCWM': -0.603, 'TeamName': 'Munship'}, {'TeamNum': 17367, 'OPR': 5.995, 'Auto': 4.681, 'CCWM': 6.161, 'TeamName': 'Say yes to the Robot'}, {'TeamNum': 17366, 'OPR': 0.807, 'Auto': -1.383, 'CCWM': -13.719, 'TeamName': 'Building Kings'}, {'TeamNum': 7497, 'OPR': -0.278, 'Auto': -0.417, 'CCWM': 6.628, 'TeamName': 'Ravenous White Parrots '}, {'TeamNum': 7499, 'OPR': -1.013, 'Auto': 2.208, 'CCWM': -18.178, 'TeamName': 'Nerdy Girls'}, {'TeamNum': 9060, 'OPR': -3.092, 'Auto': 2.032, 'CCWM': -20.231, 'TeamName': 'Smarties'}]
i 897
{'9121', '12517', '22534', '11444', '772', '327', '14914', '22972', '11841', '11454'}
[{'TeamNum': 11841, 'OPR': 54.611, 'Auto': 17.617, 'CCWM': 38.548, 'TeamName': 'STEAM Punks'}, {'TeamNum': 11444, 'OPR': 47.074, 'Auto': 2.769, 'CCWM': 41.516, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 22534, 'OPR': 41.485, 'Auto': 14.067, 'CCWM': 16.613, 'TeamName': 'Area 52.1'}, {'TeamNum': 22972, 'OPR': 40.681, 'Auto': 6.845, 'CCWM': 18.683, 'TeamName': 'White Rice '}, {'TeamNum': 772, 'OPR': 29.756, 'Auto': 13.576, 'CCWM': -4.587, 'TeamName': 'Golden Govies'}, {'TeamNum': 14914, 'OPR': 21.417, 'Auto': -1.272, 'CCWM': 0.199, 'TeamName': 'Phoenix Phorge'}, {'TeamNum': 9121, 'OPR': 14.093, 'Auto': 0.877, 'CCWM': -17.832, 'TeamName': 'Falcon Force'}, {'TeamNum': 327, 'OPR': 6.411, 'Auto': -2.783, 'CCWM': -24.652, 'TeamName': 'The Lobotomists'}, {'TeamNum': 12517, 'OPR': 1.556, 'Auto': -2.424, 'CCWM': -26.187, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 11454, 'OPR': 1.25, 'Auto': -1.439, 'CCWM': -42.301, 'TeamName': 'Penguineers'}]
USSCHAS3
[{'TeamNum': 11841, 'OPR': 54.611, 'Auto': 17.617, 'CCWM': 38.548, 'TeamName': 'STEAM Punks'}, {'TeamNum': 11444, 'OPR': 47.074, 'Auto': 2.769, 'CCWM': 41.516, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 22534, 'OPR': 41.485, 'Auto': 14.067, 'CCWM': 16.613, 'TeamName': 'Area 52.1'}, {'TeamNum': 22972, 'OPR': 40.681, 'Auto': 6.845, 'CCWM': 18.683, 'TeamName': 'White Rice '}, {'TeamNum': 772, 'OPR': 29.756, 'Auto': 13.576, 'CCWM': -4.587, 'TeamName': 'Golden Govies'}, {'TeamNum': 14914, 'OPR': 21.417, 'Auto': -1.272, 'CCWM': 0.199, 'TeamName': 'Phoenix Phorge'}, {'TeamNum': 9121, 'OPR': 14.093, 'Auto': 0.877, 'CCWM': -17.832, 'TeamName': 'Falcon Force'}, {'TeamNum': 327, 'OPR': 6.411, 'Auto': -2.783, 'CCWM': -24.652, 'TeamName': 'The Lobotomists'}, {'TeamNum': 12517, 'OPR': 1.556, 'Auto': -2.424, 'CCWM': -26.187, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 11454, 'OPR': 1.25, 'Auto': -1.439, 'CCWM': -42.301, 'TeamName': 'Penguineers'}]
i 898

{'20485', '11719', '19738', '19574', '19592', '19734', '15546', '14637', '15553', '21889', '21792', '19733', '15549', '21888', '19741', '19739', '18483', '18900', '19779', '18484', '15550', '19736', '21685', '19737'}
[{'TeamNum': 14637, 'OPR': 110.167, 'Auto': 29.602, 'CCWM': 88.401, 'TeamName': 'Aquanauts'}, {'TeamNum': 18900, 'OPR': 98.259, 'Auto': 30.493, 'CCWM': 89.755, 'TeamName': 'Sea No Evil'}, {'TeamNum': 15546, 'OPR': 90.523, 'Auto': 28.839, 'CCWM': 93.368, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 18484, 'OPR': 75.804, 'Auto': 18.158, 'CCWM': 47.609, 'TeamName': 'p0gg3r$'}, {'TeamNum': 15549, 'OPR': 60.183, 'Auto': 16.879, 'CCWM': 53.839, 'TeamName': 'Mustang Maniacs'}, {'TeamNum': 11719, 'OPR': 52.563, 'Auto': 3.407, 'CCWM': 3.267, 'TeamName': 'Iron Hook'}, {'TeamNum': 15553, 'OPR': 51.244, 'Auto': 6.731, 'CCWM': 32.142, 'TeamName': 'Grumpy Avians'}, {'TeamNum': 18483, 'OPR': 43.813, 'Auto': 2.006, 'CCWM': 26.606, 'TeamName': 'Buckar00s'}, {'TeamNum': 19779, 'OPR': 43.487, 'Auto': 13.167, 'CCWM': 37.213, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 21685, 'OPR': 34.813, 'Auto': 3.0, 'CCWM': 13.003, 'TeamName': 'LCMS FTC Pirate Robotics: Red Sea'}, {'TeamNum': 20485, 'OPR': 31.027, 'Auto': -1.436, 'CCWM': -7.123, 'TeamName': 'LCMS FTC Pirate Robotics: The Core Set'}, {'TeamNum': 19738, 'OPR': 30.192, 'Auto': 5.586, 'CCWM': -1.816, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 15550, 'OPR': 22.299, 'Auto': 2.008, 'CCWM': -9.485, 'TeamName': 'Mustang 50'}, {'TeamNum': 19737, 'OPR': 20.961, 'Auto': -0.808, 'CCWM': -34.913, 'TeamName': 'TI At0mic Mighty Ducks'}, {'TeamNum': 21889, 'OPR': 20.137, 'Auto': 1.353, 'CCWM': -23.163, 'TeamName': 'Floydada Collegiate Team B'}, {'TeamNum': 19739, 'OPR': 14.37, 'Auto': 0.148, 'CCWM': -10.553, 'TeamName': 'TIm1nat0rs'}, {'TeamNum': 19733, 'OPR': 13.119, 'Auto': -0.173, 'CCWM': -32.571, 'TeamName': 'Frenship Middle School 1'}, {'TeamNum': 19736, 'OPR': 8.714, 'Auto': 0.527, 'CCWM': -29.171, 'TeamName': 'Frenship Middle School 3'}, {'TeamNum': 19592, 'OPR': 8.682, 'Auto': 3.158, 'CCWM': -44.704, 'TeamName': 'Knight Owls'}, {'TeamNum': 19741, 'OPR': 8.061, 'Auto': -0.27, 'CCWM': -53.07, 'TeamName': 'L0w r1D3R'}, {'TeamNum': 19574, 'OPR': 7.944, 'Auto': 0.973, 'CCWM': -57.789, 'TeamName': 'LCMS FTC Pirate Robotics: Dynamite Ducks'}, {'TeamNum': 21792, 'OPR': 7.736, 'Auto': 1.431, 'CCWM': -58.076, 'TeamName': 'CEN-Unified'}, {'TeamNum': 21888, 'OPR': -11.911, 'Auto': -6.225, 'CCWM': -44.348, 'TeamName': 'Floydada Collegiate Team A'}, {'TeamNum': 19734, 'OPR': -22.788, 'Auto': -9.151, 'CCWM': -78.42, 'TeamName': 'Frenship Middle School 2'}]
USTXWPLBM3
[{'TeamNum': 14637, 'OPR': 110.167, 'Auto': 29.602, 'CCWM': 88.401, 'TeamName': 'Aquanauts'}, {'TeamNum': 18900, 'OPR': 98.259, 'Auto': 30.493, 'CCWM': 89.755, 'TeamName': 'Sea No Evil'}, {'TeamNum': 15546, 'OPR': 90.523, 'Auto': 28.839, 'CCWM': 93.368, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 18484, 'OPR': 75.804, 'Auto': 18.158, 'CCWM': 47.609, 'TeamName': 'p0gg3r$'}, {'TeamNum': 15549, 'OPR': 60.183, 'Auto': 16.879, 'CCWM': 53.839, 'TeamName': 'Mustang Maniacs'}, {'TeamNum': 11719, 'OPR': 52.563, 'Auto': 3.407, 'CCWM': 3.267, 'TeamName': 'Iron Hook'}, {'TeamNum': 15553, 'OPR': 51.244, 'Auto': 6.731, 'CCWM': 32.142, 'TeamName': 'Grumpy Avians'}, {'TeamNum': 18483, 'OPR': 43.813, 'Auto': 2.006, 'CCWM': 26.606, 'TeamName': 'Buckar00s'}, {'TeamNum': 19779, 'OPR': 43.487, 'Auto': 13.167, 'CCWM': 37.213, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 21685, 'OPR': 34.813, 'Auto': 3.0, 'CCWM': 13.003, 'TeamName': 'LCMS FTC Pirate Robotics: Red Sea'}, {'TeamNum': 20485, 'OPR': 31.027, 'Auto': -1.436, 'CCWM': -7.123, 'TeamName': 'LCMS FTC Pirate Robotics: The Core Set'}, {'TeamNum': 19738, 'OPR': 30.192, 'Auto': 5.586, 'CCWM': -1.816, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 15550, 'OPR': 22.299, 'Auto': 2.008, 'CCWM': -9.485, 'TeamName': 'Mustang 50'}, {'TeamNum': 19737, 'OPR': 20.961, 'Auto': -0.808, 'CCWM': -34.913, 'TeamName': 'TI At0mic Mighty Ducks'}, {'TeamNum': 21889, 'OPR': 20.137, 'Auto': 1.353, 'CCWM': -23.163, 'TeamName': 'Floydada Collegiate Team B'}, {'TeamNum': 19739, 'OPR': 14.37, 'Auto': 0.148, 'CCWM': -10.553, 'TeamName': 'TIm1nat0rs'}, {'TeamNum': 19733, 'OPR': 13.119, 'Auto': -0.173, 'CCWM': -32.571, 'TeamName': 'Frenship Middle School 1'}, {'TeamNum': 19736, 'OPR': 8.714, 'Auto': 0.527, 'CCWM': -29.171, 'TeamName': 'Frenship Middle School 3'}, {'TeamNum': 19592, 'OPR': 8.682, 'Auto': 3.158, 'CCWM': -44.704, 'TeamName': 'Knight Owls'}, {'TeamNum': 19741, 'OPR': 8.061, 'Auto': -0.27, 'CCWM': -53.07, 'TeamName': 'L0w r1D3R'}, {'TeamNum': 19574, 'OPR': 7.944, 'Auto': 0.973, 'CCWM': -57.789, 'TeamName': 'LCMS FTC Pirate Robotics: Dynamite Ducks'}, {'TeamNum': 21792, 'OPR': 7.736, 'Auto': 1.431, 'CCWM': -58.076, 'TeamName': 'CEN-Unified'}, {'TeamNum': 21888, 'OPR': -11.911, 'Auto': -6.225, 'CCWM': -44.348, 'TeamName': 'Floydada Collegiate Team A'}, {'TeamNum': 19734, 'OPR': -22.788, 'Auto': -9.151, 'CCWM': -78.42, 'TeamName': 'Frenship Middle School 2'}]
i 899
{'10528', '15663', '13263', '21898', '20238', '21714', '4906', '20109', '9735', '4897', '10860', '13805', '9362', '21713', '22856', '15491', '19801', '16867', '21711', '11902', '17481', '9381', '17480', '13249', '17307', '11004', '17306', '14952', '4885', '10861', '17304', '15662', '22014', '14905', '14145', '4886', '10529', '15493'}
[{'TeamNum': 4886, 'OPR': 96.357, 'Auto': 12.277, 'CCWM': 92.517, 'TeamName': 'Robo Junkies'}, {'TeamNum': 19801, 'OPR': 78.848, 'Auto': 8.339, 'CCWM': 70.598, 'TeamName': 'Rogue Robotics'}, {'TeamNum': 4885, 'OPR': 74.619, 'Auto': 20.643, 'CCWM': 48.057, 'TeamName': 'OmegaBotz'}, {'TeamNum': 11004, 'OPR': 71.189, 'Auto': 15.863, 'CCWM': 57.93, 'TeamName': 'Cantina Crew'}, {'TeamNum': 4906, 'OPR': 68.386, 'Auto': 24.091, 'CCWM': 44.668, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 13805, 'OPR': 58.506, 'Auto': 4.906, 'CCWM': 67.472, 'TeamName': 'Robotic Chaos'}, {'TeamNum': 9381, 'OPR': 54.888, 'Auto': 25.395, 'CCWM': -7.98, 'TeamName': 'Hot Bots '}, {'TeamNum': 9362, 'OPR': 51.201, 'Auto': 13.928, 'CCWM': 37.512, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 10861, 'OPR': 36.065, 'Auto': 14.892, 'CCWM': -7.22, 'TeamName': 'Stumble Bots'}, {'TeamNum': 15493, 'OPR': 35.543, 'Auto': 20.458, 'CCWM': -6.686, 'TeamName': 'The Misfits'}, {'TeamNum': 21714, 'OPR': 32.735, 'Auto': 2.575, 'CCWM': -2.157, 'TeamName': 'Revolting'}, {'TeamNum': 15491, 'OPR': 32.443, 'Auto': 10.993, 'CCWM': 2.24, 'TeamName': 'Venom Robotics'}, {'TeamNum': 10860, 'OPR': 26.712, 'Auto': 15.543, 'CCWM': 12.141, 'TeamName': 'Squid Gear'}, {'TeamNum': 9735, 'OPR': 26.639, 'Auto': 6.785, 'CCWM': -6.889, 'TeamName': 'Canis Major'}, {'TeamNum': 13263, 'OPR': 26.61, 'Auto': -7.31, 'CCWM': -8.462, 'TeamName': 'Wyld Stallyns'}, {'TeamNum': 17481, 'OPR': 26.339, 'Auto': 1.835, 'CCWM': -30.646, 'TeamName': 'Talk Nerdy to Me'}, {'TeamNum': 21713, 'OPR': 25.871, 'Auto': 3.125, 'CCWM': 10.103, 'TeamName': 'Nova Edge'}, {'TeamNum': 17306, 'OPR': 25.87, 'Auto': 13.234, 'CCWM': -10.478, 'TeamName': 'Humble Motiv8ors'}, {'TeamNum': 14145, 'OPR': 22.602, 'Auto': 3.728, 'CCWM': -51.887, 'TeamName': 'Lions'}, {'TeamNum': 16867, 'OPR': 21.878, 'Auto': 11.958, 'CCWM': -1.108, 'TeamName': 'Trinity Chargers'}, {'TeamNum': 14952, 'OPR': 20.698, 'Auto': 4.701, 'CCWM': 31.246, 'TeamName': 'Beskar Bots'}, {'TeamNum': 21711, 'OPR': 19.263, 'Auto': -1.116, 'CCWM': -4.865, 'TeamName': 'The McQueens'}, {'TeamNum': 22014, 'OPR': 18.08, 'Auto': 8.725, 'CCWM': -45.199, 'TeamName': 'Lions'}, {'TeamNum': 20238, 'OPR': 17.957, 'Auto': 11.044, 'CCWM': 6.343, 'TeamName': 'Rapture Raptors'}, {'TeamNum': 17480, 'OPR': 16.784, 'Auto': 6.75, 'CCWM': -36.09, 'TeamName': 'CIA - Cats In Action'}, {'TeamNum': 10529, 'OPR': 15.676, 'Auto': -3.892, 'CCWM': -16.745, 'TeamName': 'DinoBots'}, {'TeamNum': 17304, 'OPR': 14.558, 'Auto': 14.277, 'CCWM': -6.398, 'TeamName': 'A Perfect Remix'}, {'TeamNum': 14905, 'OPR': 14.098, 'Auto': 1.22, 'CCWM': -28.761, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 10528, 'OPR': 13.215, 'Auto': 0.394, 'CCWM': 21.756, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 4897, 'OPR': 11.135, 'Auto': 2.703, 'CCWM': 28.352, 'TeamName': 'Bodacious Bulldawgs'}, {'TeamNum': 21898, 'OPR': 10.714, 'Auto': -3.248, 'CCWM': -4.475, 'TeamName': 'Braves'}, {'TeamNum': 20109, 'OPR': 8.511, 'Auto': -1.517, 'CCWM': -14.364, 'TeamName': 'Iron Lions'}, {'TeamNum': 15662, 'OPR': 6.766, 'Auto': -1.685, 'CCWM': -31.073, 'TeamName': 'Starbucks'}, {'TeamNum': 13249, 'OPR': 5.662, 'Auto': 3.751, 'CCWM': -31.299, 'TeamName': 'Nova Robotics'}, {'TeamNum': 17307, 'OPR': 4.015, 'Auto': 2.365, 'CCWM': -41.578, 'TeamName': 'The Magnificent Seven'}, {'TeamNum': 22856, 'OPR': 2.542, 'Auto': -4.672, 'CCWM': -18.017, 'TeamName': 'Bots That Knock'}, {'TeamNum': 15663, 'OPR': 1.787, 'Auto': 3.475, 'CCWM': -53.602, 'TeamName': 'Buckineers'}, {'TeamNum': 11902, 'OPR': -3.947, 'Auto': 6.203, 'CCWM': -55.813, 'TeamName': 'KillSwitch Robotics'}]
USTXWPMDLT
[{'TeamNum': 4886, 'OPR': 96.357, 'Auto': 12.277, 'CCWM': 92.517, 'TeamName': 'Robo Junkies'}, {'TeamNum': 19801, 'OPR': 78.848, 'Auto': 8.339, 'CCWM': 70.598, 'TeamName': 'Rogue Robotics'}, {'TeamNum': 4885, 'OPR': 74.619, 'Auto': 20.643, 'CCWM': 48.057, 'TeamName': 'OmegaBotz'}, {'TeamNum': 11004, 'OPR': 71.189, 'Auto': 15.863, 'CCWM': 57.93, 'TeamName': 'Cantina Crew'}, {'TeamNum': 4906, 'OPR': 68.386, 'Auto': 24.091, 'CCWM': 44.668, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 13805, 'OPR': 58.506, 'Auto': 4.906, 'CCWM': 67.472, 'TeamName': 'Robotic Chaos'}, {'TeamNum': 9381, 'OPR': 54.888, 'Auto': 25.395, 'CCWM': -7.98, 'TeamName': 'Hot Bots '}, {'TeamNum': 9362, 'OPR': 51.201, 'Auto': 13.928, 'CCWM': 37.512, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 10861, 'OPR': 36.065, 'Auto': 14.892, 'CCWM': -7.22, 'TeamName': 'Stumble Bots'}, {'TeamNum': 15493, 'OPR': 35.543, 'Auto': 20.458, 'CCWM': -6.686, 'TeamName': 'The Misfits'}, {'TeamNum': 21714, 'OPR': 32.735, 'Auto': 2.575, 'CCWM': -2.157, 'TeamName': 'Revolting'}, {'TeamNum': 15491, 'OPR': 32.443, 'Auto': 10.993, 'CCWM': 2.24, 'TeamName': 'Venom Robotics'}, {'TeamNum': 10860, 'OPR': 26.712, 'Auto': 15.543, 'CCWM': 12.141, 'TeamName': 'Squid Gear'}, {'TeamNum': 9735, 'OPR': 26.639, 'Auto': 6.785, 'CCWM': -6.889, 'TeamName': 'Canis Major'}, {'TeamNum': 13263, 'OPR': 26.61, 'Auto': -7.31, 'CCWM': -8.462, 'TeamName': 'Wyld Stallyns'}, {'TeamNum': 17481, 'OPR': 26.339, 'Auto': 1.835, 'CCWM': -30.646, 'TeamName': 'Talk Nerdy to Me'}, {'TeamNum': 21713, 'OPR': 25.871, 'Auto': 3.125, 'CCWM': 10.103, 'TeamName': 'Nova Edge'}, {'TeamNum': 17306, 'OPR': 25.87, 'Auto': 13.234, 'CCWM': -10.478, 'TeamName': 'Humble Motiv8ors'}, {'TeamNum': 14145, 'OPR': 22.602, 'Auto': 3.728, 'CCWM': -51.887, 'TeamName': 'Lions'}, {'TeamNum': 16867, 'OPR': 21.878, 'Auto': 11.958, 'CCWM': -1.108, 'TeamName': 'Trinity Chargers'}, {'TeamNum': 14952, 'OPR': 20.698, 'Auto': 4.701, 'CCWM': 31.246, 'TeamName': 'Beskar Bots'}, {'TeamNum': 21711, 'OPR': 19.263, 'Auto': -1.116, 'CCWM': -4.865, 'TeamName': 'The McQueens'}, {'TeamNum': 22014, 'OPR': 18.08, 'Auto': 8.725, 'CCWM': -45.199, 'TeamName': 'Lions'}, {'TeamNum': 20238, 'OPR': 17.957, 'Auto': 11.044, 'CCWM': 6.343, 'TeamName': 'Rapture Raptors'}, {'TeamNum': 17480, 'OPR': 16.784, 'Auto': 6.75, 'CCWM': -36.09, 'TeamName': 'CIA - Cats In Action'}, {'TeamNum': 10529, 'OPR': 15.676, 'Auto': -3.892, 'CCWM': -16.745, 'TeamName': 'DinoBots'}, {'TeamNum': 17304, 'OPR': 14.558, 'Auto': 14.277, 'CCWM': -6.398, 'TeamName': 'A Perfect Remix'}, {'TeamNum': 14905, 'OPR': 14.098, 'Auto': 1.22, 'CCWM': -28.761, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 10528, 'OPR': 13.215, 'Auto': 0.394, 'CCWM': 21.756, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 4897, 'OPR': 11.135, 'Auto': 2.703, 'CCWM': 28.352, 'TeamName': 'Bodacious Bulldawgs'}, {'TeamNum': 21898, 'OPR': 10.714, 'Auto': -3.248, 'CCWM': -4.475, 'TeamName': 'Braves'}, {'TeamNum': 20109, 'OPR': 8.511, 'Auto': -1.517, 'CCWM': -14.364, 'TeamName': 'Iron Lions'}, {'TeamNum': 15662, 'OPR': 6.766, 'Auto': -1.685, 'CCWM': -31.073, 'TeamName': 'Starbucks'}, {'TeamNum': 13249, 'OPR': 5.662, 'Auto': 3.751, 'CCWM': -31.299, 'TeamName': 'Nova Robotics'}, {'TeamNum': 17307, 'OPR': 4.015, 'Auto': 2.365, 'CCWM': -41.578, 'TeamName': 'The Magnificent Seven'}, {'TeamNum': 22856, 'OPR': 2.542, 'Auto': -4.672, 'CCWM': -18.017, 'TeamName': 'Bots That Knock'}, {'TeamNum': 15663, 'OPR': 1.787, 'Auto': 3.475, 'CCWM': -53.602, 'TeamName': 'Buckineers'}, {'TeamNum': 11902, 'OPR': -3.947, 'Auto': 6.203, 'CCWM': -55.813, 'TeamName': 'KillSwitch Robotics'}]

i 900
{'6210', '20020', '20250', '7161', '16556', '18030', '19696', '13329', '8424', '8886', '4545', '8541', '18244', '22057', '3708', '11918', '21337', '6272', '12928', '19412', '19452', '16555', '6209', '12126', '21816'}
[{'TeamNum': 6272, 'OPR': 128.692, 'Auto': 35.87, 'CCWM': 62.247, 'TeamName': 'Iron Eagles Prime'}, {'TeamNum': 7161, 'OPR': 102.368, 'Auto': 31.704, 'CCWM': 73.734, 'TeamName': 'ViperBots Hydra'}, {'TeamNum': 19696, 'OPR': 93.064, 'Auto': 21.386, 'CCWM': 73.78, 'TeamName': 'B.O.T.S.'}, {'TeamNum': 18244, 'OPR': 88.423, 'Auto': 27.35, 'CCWM': 28.492, 'TeamName': 'Hestia'}, {'TeamNum': 12928, 'OPR': 87.47, 'Auto': 20.506, 'CCWM': 22.123, 'TeamName': 'LightSaders'}, {'TeamNum': 3708, 'OPR': 83.793, 'Auto': 25.903, 'CCWM': -29.831, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 8424, 'OPR': 82.227, 'Auto': 21.956, 'CCWM': 9.954, 'TeamName': 'Cyber Eagles'}, {'TeamNum': 6209, 'OPR': 79.605, 'Auto': 5.124, 'CCWM': 29.699, 'TeamName': 'ViperBots Venom'}, {'TeamNum': 8886, 'OPR': 71.966, 'Auto': 4.533, 'CCWM': 33.42, 'TeamName': 'Saber Robotics'}, {'TeamNum': 6210, 'OPR': 70.88, 'Auto': 11.31, 'CCWM': 32.489, 'TeamName': 'ViperBots  Stryke'}, {'TeamNum': 16555, 'OPR': 69.383, 'Auto': 27.901, 'CCWM': 9.501, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 16556, 'OPR': 68.539, 'Auto': 20.294, 'CCWM': 24.91, 'TeamName': 'Steminists'}, {'TeamNum': 4545, 'OPR': 68.025, 'Auto': -3.939, 'CCWM': 23.43, 'TeamName': 'ViperBots Ouroboros'}, {'TeamNum': 21816, 'OPR': 63.74, 'Auto': 5.315, 'CCWM': -28.441, 'TeamName': 'Robo Eagles'}, {'TeamNum': 22057, 'OPR': 63.092, 'Auto': 20.949, 'CCWM': -35.05, 'TeamName': 'The Prototypes'}, {'TeamNum': 19452, 'OPR': 59.025, 'Auto': 11.877, 'CCWM': -2.344, 'TeamName': 'Robocats'}, {'TeamNum': 12126, 'OPR': 51.556, 'Auto': -3.577, 'CCWM': 5.251, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 20020, 'OPR': 51.455, 'Auto': 11.521, 'CCWM': -11.472, 'TeamName': 'ScrewIt'}, {'TeamNum': 21337, 'OPR': 44.873, 'Auto': 12.271, 'CCWM': -22.722, 'TeamName': 'Dinobyte'}, {'TeamNum': 19412, 'OPR': 43.072, 'Auto': 15.042, 'CCWM': -23.96, 'TeamName': 'Archytas'}, {'TeamNum': 20250, 'OPR': 38.927, 'Auto': 5.121, 'CCWM': -26.269, 'TeamName': 'Stampede'}, {'TeamNum': 8541, 'OPR': 36.463, 'Auto': 13.741, 'CCWM': -59.278, 'TeamName': 'Blue Chargerbots'}, {'TeamNum': 18030, 'OPR': 30.843, 'Auto': 15.192, 'CCWM': -69.608, 'TeamName': 'ViperBots Leviathan'}, {'TeamNum': 13329, 'OPR': 17.523, 'Auto': -1.866, 'CCWM': -45.737, 'TeamName': 'Cedar Creek HS EagleBots 2'}, {'TeamNum': 11918, 'OPR': 3.655, 'Auto': -5.503, 'CCWM': -74.381, 'TeamName': 'Grizzly Bots'}]
USTXCEXSTLT1
[{'TeamNum': 6272, 'OPR': 128.692, 'Auto': 35.87, 'CCWM': 62.247, 'TeamName': 'Iron Eagles Prime'}, {'TeamNum': 7161, 'OPR': 102.368, 'Auto': 31.704, 'CCWM': 73.734, 'TeamName': 'ViperBots Hydra'}, {'TeamNum': 19696, 'OPR': 93.064, 'Auto': 21.386, 'CCWM': 73.78, 'TeamName': 'B.O.T.S.'}, {'TeamNum': 18244, 'OPR': 88.423, 'Auto': 27.35, 'CCWM': 28.492, 'TeamName': 'Hestia'}, {'TeamNum': 12928, 'OPR': 87.47, 'Auto': 20.506, 'CCWM': 22.123, 'TeamName': 'LightSaders'}, {'TeamNum': 3708, 'OPR': 83.793, 'Auto': 25.903, 'CCWM': -29.831, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 8424, 'OPR': 82.227, 'Auto': 21.956, 'CCWM': 9.954, 'TeamName': 'Cyber Eagles'}, {'TeamNum': 6209, 'OPR': 79.605, 'Auto': 5.124, 'CCWM': 29.699, 'TeamName': 'ViperBots Venom'}, {'TeamNum': 8886, 'OPR': 71.966, 'Auto': 4.533, 'CCWM': 33.42, 'TeamName': 'Saber Robotics'}, {'TeamNum': 6210, 'OPR': 70.88, 'Auto': 11.31, 'CCWM': 32.489, 'TeamName': 'ViperBots  Stryke'}, {'TeamNum': 16555, 'OPR': 69.383, 'Auto': 27.901, 'CCWM': 9.501, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 16556, 'OPR': 68.539, 'Auto': 20.294, 'CCWM': 24.91, 'TeamName': 'Steminists'}, {'TeamNum': 4545, 'OPR': 68.025, 'Auto': -3.939, 'CCWM': 23.43, 'TeamName': 'ViperBots Ouroboros'}, {'TeamNum': 21816, 'OPR': 63.74, 'Auto': 5.315, 'CCWM': -28.441, 'TeamName': 'Robo Eagles'}, {'TeamNum': 22057, 'OPR': 63.092, 'Auto': 20.949, 'CCWM': -35.05, 'TeamName': 'The Prototypes'}, {'TeamNum': 19452, 'OPR': 59.025, 'Auto': 11.877, 'CCWM': -2.344, 'TeamName': 'Robocats'}, {'TeamNum': 12126, 'OPR': 51.556, 'Auto': -3.577, 'CCWM': 5.251, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 20020, 'OPR': 51.455, 'Auto': 11.521, 'CCWM': -11.472, 'TeamName': 'ScrewIt'}, {'TeamNum': 21337, 'OPR': 44.873, 'Auto': 12.271, 'CCWM': -22.722, 'TeamName': 'Dinobyte'}, {'TeamNum': 19412, 'OPR': 43.072, 'Auto': 15.042, 'CCWM': -23.96, 'TeamName': 'Archytas'}, {'TeamNum': 20250, 'OPR': 38.927, 'Auto': 5.121, 'CCWM': -26.269, 'TeamName': 'Stampede'}, {'TeamNum': 8541, 'OPR': 36.463, 'Auto': 13.741, 'CCWM': -59.278, 'TeamName': 'Blue Chargerbots'}, {'TeamNum': 18030, 'OPR': 30.843, 'Auto': 15.192, 'CCWM': -69.608, 'TeamName': 'ViperBots Leviathan'}, {'TeamNum': 13329, 'OPR': 17.523, 'Auto': -1.866, 'CCWM': -45.737, 'TeamName': 'Cedar Creek HS EagleBots 2'}, {'TeamNum': 11918, 'OPR': 3.655, 'Auto': -5.503, 'CCWM': -74.381, 'TeamName': 'Grizzly Bots'}]
i 901
{'17594', '10862', '15930', '16251', '15654', '12359', '13833', '16828', '17796', '11924', '9923', '12339', '13266', '13744', '6901', '12202', '16832', '18458', '16029', '16831', '12302', '4902', '15725'}
[{'TeamNum': 15725, 'OPR': 85.101, 'Auto': 19.451, 'CCWM': 45.61, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 12302, 'OPR': 81.798, 'Auto': 9.316, 'CCWM': 61.823, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 13266, 'OPR': 67.546, 'Auto': 22.297, 'CCWM': 8.804, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 10862, 'OPR': 63.504, 'Auto': 10.786, 'CCWM': 31.905, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 11924, 'OPR': 52.702, 'Auto': 10.136, 'CCWM': 25.128, 'TeamName': 'Martin Robots'}, {'TeamNum': 4902, 'OPR': 50.979, 'Auto': 11.171, 'CCWM': 13.556, 'TeamName': 'Team Novabots'}, {'TeamNum': 15930, 'OPR': 48.707, 'Auto': 12.844, 'CCWM': 5.738, 'TeamName': 'Pirates'}, {'TeamNum': 18458, 'OPR': 44.475, 'Auto': -5.05, 'CCWM': 43.074, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 12202, 'OPR': 41.615, 'Auto': 7.668, 'CCWM': -13.087, 'TeamName': 'Gaga for Robots'}, {'TeamNum': 17796, 'OPR': 40.47, 'Auto': 8.815, 'CCWM': -30.655, 'TeamName': 'Caffeinated  Mechanics'}, {'TeamNum': 16251, 'OPR': 36.736, 'Auto': 1.621, 'CCWM': 27.642, 'TeamName': 'Robo Pirates'}, {'TeamNum': 16828, 'OPR': 34.557, 'Auto': 12.663, 'CCWM': -15.901, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 9923, 'OPR': 32.711, 'Auto': 5.613, 'CCWM': -14.974, 'TeamName': 'Team AAA'}, {'TeamNum': 12359, 'OPR': 31.931, 'Auto': 21.374, 'CCWM': -27.229, 'TeamName': 'Sharp Sharks'}, {'TeamNum': 16832, 'OPR': 24.463, 'Auto': 5.117, 'CCWM': -0.319, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 15654, 'OPR': 23.497, 'Auto': 4.428, 'CCWM': 13.033, 'TeamName': 'Nanoknights'}, {'TeamNum': 13833, 'OPR': 19.315, 'Auto': 8.753, 'CCWM': 13.286, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 17594, 'OPR': 17.698, 'Auto': -0.501, 'CCWM': 0.467, 'TeamName': 'West Oso Junior High Bears '}, {'TeamNum': 16029, 'OPR': 16.958, 'Auto': -0.433, 'CCWM': 4.551, 'TeamName': 'Software Pirates'}, {'TeamNum': 16831, 'OPR': 13.859, 'Auto': -0.059, 'CCWM': -33.045, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 13744, 'OPR': 13.457, 'Auto': 4.925, 'CCWM': -44.847, 'TeamName': 'Enginerds'}, {'TeamNum': 12339, 'OPR': 9.002, 'Auto': -0.32, 'CCWM': -63.217, 'TeamName': 'CSP'}, {'TeamNum': 6901, 'OPR': 7.346, 'Auto': -0.804, 'CCWM': -44.732, 'TeamName': 'Droid Rage - Phantom'}]
USTXCEGCLT
[{'TeamNum': 15725, 'OPR': 85.101, 'Auto': 19.451, 'CCWM': 45.61, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 12302, 'OPR': 81.798, 'Auto': 9.316, 'CCWM': 61.823, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 13266, 'OPR': 67.546, 'Auto': 22.297, 'CCWM': 8.804, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 10862, 'OPR': 63.504, 'Auto': 10.786, 'CCWM': 31.905, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 11924, 'OPR': 52.702, 'Auto': 10.136, 'CCWM': 25.128, 'TeamName': 'Martin Robots'}, {'TeamNum': 4902, 'OPR': 50.979, 'Auto': 11.171, 'CCWM': 13.556, 'TeamName': 'Team Novabots'}, {'TeamNum': 15930, 'OPR': 48.707, 'Auto': 12.844, 'CCWM': 5.738, 'TeamName': 'Pirates'}, {'TeamNum': 18458, 'OPR': 44.475, 'Auto': -5.05, 'CCWM': 43.074, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 12202, 'OPR': 41.615, 'Auto': 7.668, 'CCWM': -13.087, 'TeamName': 'Gaga for Robots'}, {'TeamNum': 17796, 'OPR': 40.47, 'Auto': 8.815, 'CCWM': -30.655, 'TeamName': 'Caffeinated  Mechanics'}, {'TeamNum': 16251, 'OPR': 36.736, 'Auto': 1.621, 'CCWM': 27.642, 'TeamName': 'Robo Pirates'}, {'TeamNum': 16828, 'OPR': 34.557, 'Auto': 12.663, 'CCWM': -15.901, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 9923, 'OPR': 32.711, 'Auto': 5.613, 'CCWM': -14.974, 'TeamName': 'Team AAA'}, {'TeamNum': 12359, 'OPR': 31.931, 'Auto': 21.374, 'CCWM': -27.229, 'TeamName': 'Sharp Sharks'}, {'TeamNum': 16832, 'OPR': 24.463, 'Auto': 5.117, 'CCWM': -0.319, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 15654, 'OPR': 23.497, 'Auto': 4.428, 'CCWM': 13.033, 'TeamName': 'Nanoknights'}, {'TeamNum': 13833, 'OPR': 19.315, 'Auto': 8.753, 'CCWM': 13.286, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 17594, 'OPR': 17.698, 'Auto': -0.501, 'CCWM': 0.467, 'TeamName': 'West Oso Junior High Bears '}, {'TeamNum': 16029, 'OPR': 16.958, 'Auto': -0.433, 'CCWM': 4.551, 'TeamName': 'Software Pirates'}, {'TeamNum': 16831, 'OPR': 13.859, 'Auto': -0.059, 'CCWM': -33.045, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 13744, 'OPR': 13.457, 'Auto': 4.925, 'CCWM': -44.847, 'TeamName': 'Enginerds'}, {'TeamNum': 12339, 'OPR': 9.002, 'Auto': -0.32, 'CCWM': -63.217, 'TeamName': 'CSP'}, {'TeamNum': 6901, 'OPR': 7.346, 'Auto': -0.804, 'CCWM': -44.732, 'TeamName': 'Droid Rage - Phantom'}]

i 902
{'22393', '22133', '22176', '22745', '22714', '22744', '5175', '22852', '22853', '22135', '21338', '18514', '10405'}
[{'TeamNum': 18514, 'OPR': 37.162, 'Auto': 13.945, 'CCWM': 29.416, 'TeamName': 'STORM Masters'}, {'TeamNum': 10405, 'OPR': 26.149, 'Auto': 2.146, 'CCWM': 23.59, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 18.526, 'Auto': 4.195, 'CCWM': 4.695, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22393, 'OPR': 15.354, 'Auto': 6.628, 'CCWM': 1.388, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 21338, 'OPR': 13.79, 'Auto': 2.016, 'CCWM': 1.121, 'TeamName': 'Innovators'}, {'TeamNum': 22176, 'OPR': 10.343, 'Auto': -0.721, 'CCWM': 0.187, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22852, 'OPR': 9.684, 'Auto': 3.076, 'CCWM': 4.638, 'TeamName': 'RoboFalcons'}, {'TeamNum': 22133, 'OPR': 8.345, 'Auto': -2.575, 'CCWM': 3.329, 'TeamName': 'Infinity'}, {'TeamNum': 22744, 'OPR': 1.593, 'Auto': 2.139, 'CCWM': -4.575, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 22853, 'OPR': 0.475, 'Auto': -2.178, 'CCWM': -26.668, 'TeamName': 'Falconers'}, {'TeamNum': 22135, 'OPR': -0.984, 'Auto': 3.129, 'CCWM': -6.558, 'TeamName': '7Teenzz'}, {'TeamNum': 22745, 'OPR': -5.261, 'Auto': -2.037, 'CCWM': -26.547, 'TeamName': 'Jack Bots'}, {'TeamNum': 22714, 'OPR': -6.54, 'Auto': -2.668, 'CCWM': -5.834, 'TeamName': 'The Scanners'}]
USTXHOELM2
[{'TeamNum': 18514, 'OPR': 37.162, 'Auto': 13.945, 'CCWM': 29.416, 'TeamName': 'STORM Masters'}, {'TeamNum': 10405, 'OPR': 26.149, 'Auto': 2.146, 'CCWM': 23.59, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 18.526, 'Auto': 4.195, 'CCWM': 4.695, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22393, 'OPR': 15.354, 'Auto': 6.628, 'CCWM': 1.388, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 21338, 'OPR': 13.79, 'Auto': 2.016, 'CCWM': 1.121, 'TeamName': 'Innovators'}, {'TeamNum': 22176, 'OPR': 10.343, 'Auto': -0.721, 'CCWM': 0.187, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22852, 'OPR': 9.684, 'Auto': 3.076, 'CCWM': 4.638, 'TeamName': 'RoboFalcons'}, {'TeamNum': 22133, 'OPR': 8.345, 'Auto': -2.575, 'CCWM': 3.329, 'TeamName': 'Infinity'}, {'TeamNum': 22744, 'OPR': 1.593, 'Auto': 2.139, 'CCWM': -4.575, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 22853, 'OPR': 0.475, 'Auto': -2.178, 'CCWM': -26.668, 'TeamName': 'Falconers'}, {'TeamNum': 22135, 'OPR': -0.984, 'Auto': 3.129, 'CCWM': -6.558, 'TeamName': '7Teenzz'}, {'TeamNum': 22745, 'OPR': -5.261, 'Auto': -2.037, 'CCWM': -26.547, 'TeamName': 'Jack Bots'}, {'TeamNum': 22714, 'OPR': -6.54, 'Auto': -2.668, 'CCWM': -5.834, 'TeamName': 'The Scanners'}]
i 903
{'20776', '4849', '12347', '15359', '8284', '18908', '22514', '12305', '6892', '12313', '15221', '22087', '4848', '22513'}
[{'TeamNum': 18908, 'OPR': 101.976, 'Auto': 19.587, 'CCWM': 58.829, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 4848, 'OPR': 93.232, 'Auto': 25.891, 'CCWM': 18.326, 'TeamName': 'Chaos'}, {'TeamNum': 15221, 'OPR': 90.408, 'Auto': 25.159, 'CCWM': 18.969, 'TeamName': 'Astro Hawks'}, {'TeamNum': 15359, 'OPR': 89.27, 'Auto': 22.062, 'CCWM': 47.545, 'TeamName': 'Rage Against the Machine'}, {'TeamNum': 8284, 'OPR': 89.225, 'Auto': 15.483, 'CCWM': 60.663, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 6892, 'OPR': 89.11, 'Auto': 18.957, 'CCWM': 16.828, 'TeamName': 'The Waterboys'}, {'TeamNum': 12313, 'OPR': 81.448, 'Auto': 20.356, 'CCWM': 25.155, 'TeamName': 'Hotdawgs'}, {'TeamNum': 4849, 'OPR': 70.097, 'Auto': 17.986, 'CCWM': -1.869, 'TeamName': 'Sabotage'}, {'TeamNum': 12305, 'OPR': 63.162, 'Auto': 13.963, 'CCWM': -15.57, 'TeamName': 'Ro-baddies'}, {'TeamNum': 12347, 'OPR': 54.032, 'Auto': 9.018, 'CCWM': 2.812, 'TeamName': 'Gears of Thrones'}, {'TeamNum': 22514, 'OPR': 45.279, 'Auto': 5.482, 'CCWM': -67.733, 'TeamName': 'U S Thunder Cats'}, {'TeamNum': 22087, 'OPR': 39.249, 'Auto': 19.764, 'CCWM': -56.927, 'TeamName': 'Bad 2 the Bone'}, {'TeamNum': 20776, 'OPR': 13.594, 'Auto': 0.245, 'CCWM': -41.098, 'TeamName': 'South Haulers'}, {'TeamNum': 22513, 'OPR': 1.596, 'Auto': 2.583, 'CCWM': -67.845, 'TeamName': 'South Side Robotics'}]
USTXSOTELT
[{'TeamNum': 18908, 'OPR': 101.976, 'Auto': 19.587, 'CCWM': 58.829, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 4848, 'OPR': 93.232, 'Auto': 25.891, 'CCWM': 18.326, 'TeamName': 'Chaos'}, {'TeamNum': 15221, 'OPR': 90.408, 'Auto': 25.159, 'CCWM': 18.969, 'TeamName': 'Astro Hawks'}, {'TeamNum': 15359, 'OPR': 89.27, 'Auto': 22.062, 'CCWM': 47.545, 'TeamName': 'Rage Against the Machine'}, {'TeamNum': 8284, 'OPR': 89.225, 'Auto': 15.483, 'CCWM': 60.663, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 6892, 'OPR': 89.11, 'Auto': 18.957, 'CCWM': 16.828, 'TeamName': 'The Waterboys'}, {'TeamNum': 12313, 'OPR': 81.448, 'Auto': 20.356, 'CCWM': 25.155, 'TeamName': 'Hotdawgs'}, {'TeamNum': 4849, 'OPR': 70.097, 'Auto': 17.986, 'CCWM': -1.869, 'TeamName': 'Sabotage'}, {'TeamNum': 12305, 'OPR': 63.162, 'Auto': 13.963, 'CCWM': -15.57, 'TeamName': 'Ro-baddies'}, {'TeamNum': 12347, 'OPR': 54.032, 'Auto': 9.018, 'CCWM': 2.812, 'TeamName': 'Gears of Thrones'}, {'TeamNum': 22514, 'OPR': 45.279, 'Auto': 5.482, 'CCWM': -67.733, 'TeamName': 'U S Thunder Cats'}, {'TeamNum': 22087, 'OPR': 39.249, 'Auto': 19.764, 'CCWM': -56.927, 'TeamName': 'Bad 2 the Bone'}, {'TeamNum': 20776, 'OPR': 13.594, 'Auto': 0.245, 'CCWM': -41.098, 'TeamName': 'South Haulers'}, {'TeamNum': 22513, 'OPR': 1.596, 'Auto': 2.583, 'CCWM': -67.845, 'TeamName': 'South Side Robotics'}]
i 904
{'20350', '21448', '12820', '16597', '13348', '11312', '16377', '22563', '12717', '12563', '19886', '11338', '22746'}
[{'TeamNum': 16377, 'OPR': 98.714, 'Auto': 16.393, 'CCWM': 81.226, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 16597, 'OPR': 88.497, 'Auto': 30.157, 'CCWM': 80.692, 'TeamName': 'Fulminata'}, {'TeamNum': 12820, 'OPR': 54.421, 'Auto': 5.057, 'CCWM': 24.236, 'TeamName': 'Wagner TRILOBYTES'}, {'TeamNum': 22563, 'OPR': 38.281, 'Auto': 0.295, 'CCWM': 3.277, 'TeamName': 'BOTS OF STEELE'}, {'TeamNum': 12563, 'OPR': 27.694, 'Auto': -0.217, 'CCWM': -4.163, 'TeamName': 'Bots of Glory'}, {'TeamNum': 13348, 'OPR': 23.981, 'Auto': 1.264, 'CCWM': 9.615, 'TeamName': 'ERA'}, {'TeamNum': 12717, 'OPR': 22.892, 'Auto': 4.557, 'CCWM': -6.962, 'TeamName': 'JagBotics'}, {'TeamNum': 20350, 'OPR': 18.96, 'Auto': 1.608, 'CCWM': -10.888, 'TeamName': 'Aviation Ai '}, {'TeamNum': 11338, 'OPR': 17.018, 'Auto': -0.551, 'CCWM': -22.276, 'TeamName': 'JSTEM Lightning: McQueens'}, {'TeamNum': 11312, 'OPR': 16.275, 'Auto': 4.598, 'CCWM': -36.188, 'TeamName': 'JSTEM Lightning: Bolts'}, {'TeamNum': 21448, 'OPR': 11.015, 'Auto': 0.331, 'CCWM': -16.592, 'TeamName': 'Fire Hazard'}, {'TeamNum': 19886, 'OPR': 6.565, 'Auto': 1.565, 'CCWM': -32.952, 'TeamName': 'Bionic Bengals'}, {'TeamNum': 22746, 'OPR': 1.998, 'Auto': 0.854, 'CCWM': -61.05, 'TeamName': 'Jamaican Bananas'}]
USTXCEKWLT1
[{'TeamNum': 16377, 'OPR': 98.714, 'Auto': 16.393, 'CCWM': 81.226, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 16597, 'OPR': 88.497, 'Auto': 30.157, 'CCWM': 80.692, 'TeamName': 'Fulminata'}, {'TeamNum': 12820, 'OPR': 54.421, 'Auto': 5.057, 'CCWM': 24.236, 'TeamName': 'Wagner TRILOBYTES'}, {'TeamNum': 22563, 'OPR': 38.281, 'Auto': 0.295, 'CCWM': 3.277, 'TeamName': 'BOTS OF STEELE'}, {'TeamNum': 12563, 'OPR': 27.694, 'Auto': -0.217, 'CCWM': -4.163, 'TeamName': 'Bots of Glory'}, {'TeamNum': 13348, 'OPR': 23.981, 'Auto': 1.264, 'CCWM': 9.615, 'TeamName': 'ERA'}, {'TeamNum': 12717, 'OPR': 22.892, 'Auto': 4.557, 'CCWM': -6.962, 'TeamName': 'JagBotics'}, {'TeamNum': 20350, 'OPR': 18.96, 'Auto': 1.608, 'CCWM': -10.888, 'TeamName': 'Aviation Ai '}, {'TeamNum': 11338, 'OPR': 17.018, 'Auto': -0.551, 'CCWM': -22.276, 'TeamName': 'JSTEM Lightning: McQueens'}, {'TeamNum': 11312, 'OPR': 16.275, 'Auto': 4.598, 'CCWM': -36.188, 'TeamName': 'JSTEM Lightning: Bolts'}, {'TeamNum': 21448, 'OPR': 11.015, 'Auto': 0.331, 'CCWM': -16.592, 'TeamName': 'Fire Hazard'}, {'TeamNum': 19886, 'OPR': 6.565, 'Auto': 1.565, 'CCWM': -32.952, 'TeamName': 'Bionic Bengals'}, {'TeamNum': 22746, 'OPR': 1.998, 'Auto': 0.854, 'CCWM': -61.05, 'TeamName': 'Jamaican Bananas'}]
i 905
{'12115', '13893', '5189', '22629', '19935', '15758', '5188', '4721', '20778', '4720', '22541', '3033', '21352', '21879', '13895', '5681', '4719', '17121', '17329', '13896', '10632', '22540'}
[{'TeamNum': 12115, 'OPR': 82.534, 'Auto': 12.432, 'CCWM': 43.441, 'TeamName': 'Phoen-X'}, {'TeamNum': 21879, 'OPR': 67.818, 'Auto': 11.906, 'CCWM': 64.515, 'TeamName': 'Checkmate'}, {'TeamNum': 3033, 'OPR': 53.348, 'Auto': 13.007, 'CCWM': 19.619, 'TeamName': 'Techno Riderz'}, {'TeamNum': 15758, 'OPR': 41.45, 'Auto': 2.259, 'CCWM': -25.863, 'TeamName': 'PiRate Brigade'}, {'TeamNum': 4720, 'OPR': 31.31, 'Auto': 8.849, 'CCWM': 1.952, 'TeamName': 'STEAM Newton'}, {'TeamNum': 22541, 'OPR': 29.735, 'Auto': -3.976, 'CCWM': 11.764, 'TeamName': 'Ram Jamz'}, {'TeamNum': 5681, 'OPR': 28.956, 'Auto': 4.395, 'CCWM': -0.262, 'TeamName': 'Robo Pirates'}, {'TeamNum': 22629, 'OPR': 27.13, 'Auto': 6.699, 'CCWM': 4.979, 'TeamName': 'Morales Jr High'}, {'TeamNum': 5188, 'OPR': 26.629, 'Auto': 8.952, 'CCWM': 17.178, 'TeamName': 'Team Phoenix'}, {'TeamNum': 10632, 'OPR': 25.602, 'Auto': 7.177, 'CCWM': 2.404, 'TeamName': 'JECA RoboRaptors'}, {'TeamNum': 21352, 'OPR': 25.142, 'Auto': 3.481, 'CCWM': -20.997, 'TeamName': 'Team FireBots'}, {'TeamNum': 22540, 'OPR': 25.089, 'Auto': 0.983, 'CCWM': 4.364, 'TeamName': 'Royal Ramz'}, {'TeamNum': 4719, 'OPR': 23.701, 'Auto': -0.929, 'CCWM': 0.113, 'TeamName': 'STEAM Galileo'}, {'TeamNum': 4721, 'OPR': 22.201, 'Auto': 0.692, 'CCWM': 9.884, 'TeamName': 'STEAM Einstein'}, {'TeamNum': 13895, 'OPR': 21.663, 'Auto': 4.282, 'CCWM': -8.375, 'TeamName': 'Team LiveWire'}, {'TeamNum': 17121, 'OPR': 20.714, 'Auto': -2.377, 'CCWM': -10.319, 'TeamName': 'Ronald Reagan Robotics'}, {'TeamNum': 20778, 'OPR': 19.497, 'Auto': 2.062, 'CCWM': 18.08, 'TeamName': 'Brentwood Bots'}, {'TeamNum': 5189, 'OPR': 13.131, 'Auto': -0.148, 'CCWM': -29.632, 'TeamName': 'Team Wolves'}, {'TeamNum': 13893, 'OPR': 11.802, 'Auto': 2.516, 'CCWM': -23.436, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 13896, 'OPR': 7.02, 'Auto': 5.337, 'CCWM': -19.142, 'TeamName': 'Team Battle Stallions'}, {'TeamNum': 19935, 'OPR': 5.227, 'Auto': 0.751, 'CCWM': -39.494, 'TeamName': 'UHS Dynamics'}, {'TeamNum': 17329, 'OPR': 1.577, 'Auto': -2.687, 'CCWM': -19.044, 'TeamName': 'Team Stingray Dynamics'}]
USTXCE90STLT
[{'TeamNum': 12115, 'OPR': 82.534, 'Auto': 12.432, 'CCWM': 43.441, 'TeamName': 'Phoen-X'}, {'TeamNum': 21879, 'OPR': 67.818, 'Auto': 11.906, 'CCWM': 64.515, 'TeamName': 'Checkmate'}, {'TeamNum': 3033, 'OPR': 53.348, 'Auto': 13.007, 'CCWM': 19.619, 'TeamName': 'Techno Riderz'}, {'TeamNum': 15758, 'OPR': 41.45, 'Auto': 2.259, 'CCWM': -25.863, 'TeamName': 'PiRate Brigade'}, {'TeamNum': 4720, 'OPR': 31.31, 'Auto': 8.849, 'CCWM': 1.952, 'TeamName': 'STEAM Newton'}, {'TeamNum': 22541, 'OPR': 29.735, 'Auto': -3.976, 'CCWM': 11.764, 'TeamName': 'Ram Jamz'}, {'TeamNum': 5681, 'OPR': 28.956, 'Auto': 4.395, 'CCWM': -0.262, 'TeamName': 'Robo Pirates'}, {'TeamNum': 22629, 'OPR': 27.13, 'Auto': 6.699, 'CCWM': 4.979, 'TeamName': 'Morales Jr High'}, {'TeamNum': 5188, 'OPR': 26.629, 'Auto': 8.952, 'CCWM': 17.178, 'TeamName': 'Team Phoenix'}, {'TeamNum': 10632, 'OPR': 25.602, 'Auto': 7.177, 'CCWM': 2.404, 'TeamName': 'JECA RoboRaptors'}, {'TeamNum': 21352, 'OPR': 25.142, 'Auto': 3.481, 'CCWM': -20.997, 'TeamName': 'Team FireBots'}, {'TeamNum': 22540, 'OPR': 25.089, 'Auto': 0.983, 'CCWM': 4.364, 'TeamName': 'Royal Ramz'}, {'TeamNum': 4719, 'OPR': 23.701, 'Auto': -0.929, 'CCWM': 0.113, 'TeamName': 'STEAM Galileo'}, {'TeamNum': 4721, 'OPR': 22.201, 'Auto': 0.692, 'CCWM': 9.884, 'TeamName': 'STEAM Einstein'}, {'TeamNum': 13895, 'OPR': 21.663, 'Auto': 4.282, 'CCWM': -8.375, 'TeamName': 'Team LiveWire'}, {'TeamNum': 17121, 'OPR': 20.714, 'Auto': -2.377, 'CCWM': -10.319, 'TeamName': 'Ronald Reagan Robotics'}, {'TeamNum': 20778, 'OPR': 19.497, 'Auto': 2.062, 'CCWM': 18.08, 'TeamName': 'Brentwood Bots'}, {'TeamNum': 5189, 'OPR': 13.131, 'Auto': -0.148, 'CCWM': -29.632, 'TeamName': 'Team Wolves'}, {'TeamNum': 13893, 'OPR': 11.802, 'Auto': 2.516, 'CCWM': -23.436, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 13896, 'OPR': 7.02, 'Auto': 5.337, 'CCWM': -19.142, 'TeamName': 'Team Battle Stallions'}, {'TeamNum': 19935, 'OPR': 5.227, 'Auto': 0.751, 'CCWM': -39.494, 'TeamName': 'UHS Dynamics'}, {'TeamNum': 17329, 'OPR': 1.577, 'Auto': -2.687, 'CCWM': -19.044, 'TeamName': 'Team Stingray Dynamics'}]
i 906

{'20764', '22008', '21235', '22496', '13783', '3734', '22191', '8626', '13227', '14904', '11419', '20347', '10526', '9256', '20410', '6832', '17499', '10437', '21963', '8406', '8514', '14962', '127', '19897', '10577', '8811', '11085', '9010', '15372', '22344', '19587', '22011', '15373', '11676'}
[{'TeamNum': 19897, 'OPR': 105.106, 'Auto': 20.561, 'CCWM': 62.693, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 8811, 'OPR': 83.927, 'Auto': 16.197, 'CCWM': 53.242, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 11085, 'OPR': 68.159, 'Auto': 19.995, 'CCWM': -2.986, 'TeamName': 'MHS Mad Hackers'}, {'TeamNum': 19587, 'OPR': 67.294, 'Auto': 11.092, 'CCWM': 41.588, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 127, 'OPR': 65.009, 'Auto': 16.874, 'CCWM': 15.726, 'TeamName': 'The Fighting Pickles'}, {'TeamNum': 11419, 'OPR': 57.842, 'Auto': 19.118, 'CCWM': 7.549, 'TeamName': 'Jasper Jaguar Robotics Green'}, {'TeamNum': 22191, 'OPR': 57.022, 'Auto': 14.378, 'CCWM': 13.64, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 8406, 'OPR': 54.399, 'Auto': 13.236, 'CCWM': 51.4, 'TeamName': 'The Horde'}, {'TeamNum': 9256, 'OPR': 53.029, 'Auto': 3.108, 'CCWM': 8.351, 'TeamName': 'Robo*Bison Esfuerzo'}, {'TeamNum': 13227, 'OPR': 48.572, 'Auto': 10.216, 'CCWM': 12.357, 'TeamName': 'Mechanicats'}, {'TeamNum': 15373, 'OPR': 44.556, 'Auto': 8.729, 'CCWM': -15.958, 'TeamName': 'Iron Core'}, {'TeamNum': 20410, 'OPR': 43.352, 'Auto': -3.267, 'CCWM': 20.377, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 10437, 'OPR': 41.324, 'Auto': 3.891, 'CCWM': -18.82, 'TeamName': 'The Rusty Nuts'}, {'TeamNum': 14962, 'OPR': 39.677, 'Auto': 12.798, 'CCWM': 28.077, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 10577, 'OPR': 39.358, 'Auto': 12.555, 'CCWM': -6.481, 'TeamName': 'Thunder Chicks'}, {'TeamNum': 8626, 'OPR': 36.659, 'Auto': 4.136, 'CCWM': -8.856, 'TeamName': 'ProtoSurge'}, {'TeamNum': 20764, 'OPR': 32.543, 'Auto': 2.945, 'CCWM': -13.468, 'TeamName': 'UltraBots'}, {'TeamNum': 21235, 'OPR': 31.949, 'Auto': 13.848, 'CCWM': -18.711, 'TeamName': 'SHARK!'}, {'TeamNum': 11676, 'OPR': 31.6, 'Auto': -1.068, 'CCWM': -4.798, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 14904, 'OPR': 29.564, 'Auto': 9.315, 'CCWM': 16.965, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 9010, 'OPR': 26.106, 'Auto': 8.373, 'CCWM': -44.589, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 10526, 'OPR': 25.944, 'Auto': 5.975, 'CCWM': 11.394, 'TeamName': 'BA BLACK: µicroBotixs'}, {'TeamNum': 17499, 'OPR': 25.597, 'Auto': 5.416, 'CCWM': -2.683, 'TeamName': 'Athena Circuit Breakers'}, {'TeamNum': 20347, 'OPR': 24.448, 'Auto': 10.475, 'CCWM': -22.171, 'TeamName': '[INSERT_NAME_HERE]'}, {'TeamNum': 21963, 'OPR': 22.98, 'Auto': 7.648, 'CCWM': 6.005, 'TeamName': 'The Multiversal Coders'}, {'TeamNum': 22344, 'OPR': 20.895, 'Auto': 10.094, 'CCWM': -34.016, 'TeamName': 'Newman Gibbins 2'}, {'TeamNum': 13783, 'OPR': 20.338, 'Auto': -4.387, 'CCWM': -20.08, 'TeamName': 'ThunderChicksToo'}, {'TeamNum': 15372, 'OPR': 18.819, 'Auto': -0.679, 'CCWM': -32.378, 'TeamName': 'ThunderChicksTambién'}, {'TeamNum': 6832, 'OPR': 17.585, 'Auto': 4.366, 'CCWM': -23.866, 'TeamName': 'Iron Reign'}, {'TeamNum': 22011, 'OPR': 13.564, 'Auto': -1.795, 'CCWM': -3.017, 'TeamName': 'Sunset Robotics 4'}, {'TeamNum': 22008, 'OPR': 12.757, 'Auto': -3.256, 'CCWM': -26.556, 'TeamName': 'Sunset Robotics 3'}, {'TeamNum': 8514, 'OPR': 9.258, 'Auto': 1.904, 'CCWM': -39.958, 'TeamName': 'BA GREEN: Robotonics'}, {'TeamNum': 3734, 'OPR': 7.665, 'Auto': 0.547, 'CCWM': -11.749, 'TeamName': 'Iron Giant'}, {'TeamNum': 22496, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Early College Garza Robotics'}]
USTXNODULT1
[{'TeamNum': 19897, 'OPR': 105.106, 'Auto': 20.561, 'CCWM': 62.693, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 8811, 'OPR': 83.927, 'Auto': 16.197, 'CCWM': 53.242, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 11085, 'OPR': 68.159, 'Auto': 19.995, 'CCWM': -2.986, 'TeamName': 'MHS Mad Hackers'}, {'TeamNum': 19587, 'OPR': 67.294, 'Auto': 11.092, 'CCWM': 41.588, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 127, 'OPR': 65.009, 'Auto': 16.874, 'CCWM': 15.726, 'TeamName': 'The Fighting Pickles'}, {'TeamNum': 11419, 'OPR': 57.842, 'Auto': 19.118, 'CCWM': 7.549, 'TeamName': 'Jasper Jaguar Robotics Green'}, {'TeamNum': 22191, 'OPR': 57.022, 'Auto': 14.378, 'CCWM': 13.64, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 8406, 'OPR': 54.399, 'Auto': 13.236, 'CCWM': 51.4, 'TeamName': 'The Horde'}, {'TeamNum': 9256, 'OPR': 53.029, 'Auto': 3.108, 'CCWM': 8.351, 'TeamName': 'Robo*Bison Esfuerzo'}, {'TeamNum': 13227, 'OPR': 48.572, 'Auto': 10.216, 'CCWM': 12.357, 'TeamName': 'Mechanicats'}, {'TeamNum': 15373, 'OPR': 44.556, 'Auto': 8.729, 'CCWM': -15.958, 'TeamName': 'Iron Core'}, {'TeamNum': 20410, 'OPR': 43.352, 'Auto': -3.267, 'CCWM': 20.377, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 10437, 'OPR': 41.324, 'Auto': 3.891, 'CCWM': -18.82, 'TeamName': 'The Rusty Nuts'}, {'TeamNum': 14962, 'OPR': 39.677, 'Auto': 12.798, 'CCWM': 28.077, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 10577, 'OPR': 39.358, 'Auto': 12.555, 'CCWM': -6.481, 'TeamName': 'Thunder Chicks'}, {'TeamNum': 8626, 'OPR': 36.659, 'Auto': 4.136, 'CCWM': -8.856, 'TeamName': 'ProtoSurge'}, {'TeamNum': 20764, 'OPR': 32.543, 'Auto': 2.945, 'CCWM': -13.468, 'TeamName': 'UltraBots'}, {'TeamNum': 21235, 'OPR': 31.949, 'Auto': 13.848, 'CCWM': -18.711, 'TeamName': 'SHARK!'}, {'TeamNum': 11676, 'OPR': 31.6, 'Auto': -1.068, 'CCWM': -4.798, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 14904, 'OPR': 29.564, 'Auto': 9.315, 'CCWM': 16.965, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 9010, 'OPR': 26.106, 'Auto': 8.373, 'CCWM': -44.589, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 10526, 'OPR': 25.944, 'Auto': 5.975, 'CCWM': 11.394, 'TeamName': 'BA BLACK: µicroBotixs'}, {'TeamNum': 17499, 'OPR': 25.597, 'Auto': 5.416, 'CCWM': -2.683, 'TeamName': 'Athena Circuit Breakers'}, {'TeamNum': 20347, 'OPR': 24.448, 'Auto': 10.475, 'CCWM': -22.171, 'TeamName': '[INSERT_NAME_HERE]'}, {'TeamNum': 21963, 'OPR': 22.98, 'Auto': 7.648, 'CCWM': 6.005, 'TeamName': 'The Multiversal Coders'}, {'TeamNum': 22344, 'OPR': 20.895, 'Auto': 10.094, 'CCWM': -34.016, 'TeamName': 'Newman Gibbins 2'}, {'TeamNum': 13783, 'OPR': 20.338, 'Auto': -4.387, 'CCWM': -20.08, 'TeamName': 'ThunderChicksToo'}, {'TeamNum': 15372, 'OPR': 18.819, 'Auto': -0.679, 'CCWM': -32.378, 'TeamName': 'ThunderChicksTambién'}, {'TeamNum': 6832, 'OPR': 17.585, 'Auto': 4.366, 'CCWM': -23.866, 'TeamName': 'Iron Reign'}, {'TeamNum': 22011, 'OPR': 13.564, 'Auto': -1.795, 'CCWM': -3.017, 'TeamName': 'Sunset Robotics 4'}, {'TeamNum': 22008, 'OPR': 12.757, 'Auto': -3.256, 'CCWM': -26.556, 'TeamName': 'Sunset Robotics 3'}, {'TeamNum': 8514, 'OPR': 9.258, 'Auto': 1.904, 'CCWM': -39.958, 'TeamName': 'BA GREEN: Robotonics'}, {'TeamNum': 3734, 'OPR': 7.665, 'Auto': 0.547, 'CCWM': -11.749, 'TeamName': 'Iron Giant'}, {'TeamNum': 22496, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Early College Garza Robotics'}]
i 907
{'5628', '7079', '14363', '11093', '14361', '9527', '19746', '21438', '4546', '20716', '16525', '19853', '12596', '21323', '21432', '7064', '21893', '18886', '16311', '18884', '11503', '6299', '7797', '19591', '3781', '17315', '19380', '17264', '22394', '6990', '20240', '17113', '12670', '19852'}
[{'TeamNum': 19746, 'OPR': 158.478, 'Auto': 50.235, 'CCWM': 93.68, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 11093, 'OPR': 118.633, 'Auto': 32.076, 'CCWM': 47.291, 'TeamName': 'MegaKnytes'}, {'TeamNum': 6299, 'OPR': 103.964, 'Auto': 17.977, 'CCWM': 22.514, 'TeamName': 'ViperBots QuadX'}, {'TeamNum': 14361, 'OPR': 102.776, 'Auto': 24.019, 'CCWM': 28.071, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 7797, 'OPR': 98.963, 'Auto': 29.246, 'CCWM': 1.829, 'TeamName': 'Victorian Voltage'}, {'TeamNum': 3781, 'OPR': 94.814, 'Auto': 13.478, 'CCWM': 22.681, 'TeamName': 'Pi-Rho Maniacs'}, {'TeamNum': 14363, 'OPR': 94.017, 'Auto': 21.133, 'CCWM': 35.672, 'TeamName': 'CPHS ROBOLOBOS WHITE'}, {'TeamNum': 21438, 'OPR': 90.88, 'Auto': 33.547, 'CCWM': 19.176, 'TeamName': 'Chaotic Current'}, {'TeamNum': 17113, 'OPR': 82.835, 'Auto': 22.193, 'CCWM': 35.241, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 9527, 'OPR': 82.597, 'Auto': 32.281, 'CCWM': 40.991, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 21323, 'OPR': 79.737, 'Auto': 30.478, 'CCWM': 31.063, 'TeamName': 'TrinityBots'}, {'TeamNum': 17315, 'OPR': 79.216, 'Auto': 18.459, 'CCWM': 64.473, 'TeamName': 'Westwood Tomahawk'}, {'TeamNum': 16311, 'OPR': 77.243, 'Auto': 18.477, 'CCWM': 27.71, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 7079, 'OPR': 67.525, 'Auto': 7.74, 'CCWM': 3.06, 'TeamName': 'FalTech'}, {'TeamNum': 19853, 'OPR': 67.263, 'Auto': 13.599, 'CCWM': -7.883, 'TeamName': 'Roboteers'}, {'TeamNum': 5628, 'OPR': 64.045, 'Auto': 10.905, 'CCWM': -32.582, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 17264, 'OPR': 57.506, 'Auto': 16.423, 'CCWM': -12.106, 'TeamName': 'Westwood Arrowhead'}, {'TeamNum': 4546, 'OPR': 56.975, 'Auto': 6.769, 'CCWM': -13.515, 'TeamName': 'ViperBots SnakeByte'}, {'TeamNum': 22394, 'OPR': 53.486, 'Auto': 15.033, 'CCWM': -14.78, 'TeamName': 'Rouse Radians'}, {'TeamNum': 11503, 'OPR': 51.535, 'Auto': 15.837, 'CCWM': -43.753, 'TeamName': 'ViperBots HyperFang'}, {'TeamNum': 19852, 'OPR': 48.52, 'Auto': -3.729, 'CCWM': -8.357, 'TeamName': 'Platinum Platoon'}, {'TeamNum': 19591, 'OPR': 47.016, 'Auto': 17.258, 'CCWM': -63.99, 'TeamName': 'Some Assembly Required'}, {'TeamNum': 20716, 'OPR': 46.205, 'Auto': 26.163, 'CCWM': -29.419, 'TeamName': 'BeauBots'}, {'TeamNum': 21432, 'OPR': 44.147, 'Auto': 3.495, 'CCWM': 0.898, 'TeamName': 'Short Circuits'}, {'TeamNum': 18886, 'OPR': 42.548, 'Auto': -5.41, 'CCWM': 3.719, 'TeamName': 'Westwood Atlatl'}, {'TeamNum': 12670, 'OPR': 41.94, 'Auto': 6.422, 'CCWM': -6.442, 'TeamName': 'Eclipse 12670'}, {'TeamNum': 12596, 'OPR': 40.318, 'Auto': 0.305, 'CCWM': -13.861, 'TeamName': 'ViperBots Copperhead'}, {'TeamNum': 18884, 'OPR': 36.258, 'Auto': 8.856, 'CCWM': -31.956, 'TeamName': 'Westwood Boomerang'}, {'TeamNum': 21893, 'OPR': 35.1, 'Auto': 17.345, 'CCWM': -4.723, 'TeamName': 'Ursa Major'}, {'TeamNum': 6990, 'OPR': 34.307, 'Auto': 4.342, 'CCWM': -4.921, 'TeamName': 'Static Void'}, {'TeamNum': 16525, 'OPR': 30.334, 'Auto': -2.767, 'CCWM': -24.439, 'TeamName': 'SkyRise Robotics'}, {'TeamNum': 19380, 'OPR': 30.237, 'Auto': 5.543, 'CCWM': -41.093, 'TeamName': 'Millennium Falcons'}, {'TeamNum': 20240, 'OPR': 28.182, 'Auto': 8.355, 'CCWM': -55.572, 'TeamName': 'Westwood Slingshot'}, {'TeamNum': 7064, 'OPR': -13.588, 'Auto': -0.61, 'CCWM': -69.007, 'TeamName': 'R-Cubed'}]
USTXCEGMLT
[{'TeamNum': 19746, 'OPR': 158.478, 'Auto': 50.235, 'CCWM': 93.68, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 11093, 'OPR': 118.633, 'Auto': 32.076, 'CCWM': 47.291, 'TeamName': 'MegaKnytes'}, {'TeamNum': 6299, 'OPR': 103.964, 'Auto': 17.977, 'CCWM': 22.514, 'TeamName': 'ViperBots QuadX'}, {'TeamNum': 14361, 'OPR': 102.776, 'Auto': 24.019, 'CCWM': 28.071, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 7797, 'OPR': 98.963, 'Auto': 29.246, 'CCWM': 1.829, 'TeamName': 'Victorian Voltage'}, {'TeamNum': 3781, 'OPR': 94.814, 'Auto': 13.478, 'CCWM': 22.681, 'TeamName': 'Pi-Rho Maniacs'}, {'TeamNum': 14363, 'OPR': 94.017, 'Auto': 21.133, 'CCWM': 35.672, 'TeamName': 'CPHS ROBOLOBOS WHITE'}, {'TeamNum': 21438, 'OPR': 90.88, 'Auto': 33.547, 'CCWM': 19.176, 'TeamName': 'Chaotic Current'}, {'TeamNum': 17113, 'OPR': 82.835, 'Auto': 22.193, 'CCWM': 35.241, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 9527, 'OPR': 82.597, 'Auto': 32.281, 'CCWM': 40.991, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 21323, 'OPR': 79.737, 'Auto': 30.478, 'CCWM': 31.063, 'TeamName': 'TrinityBots'}, {'TeamNum': 17315, 'OPR': 79.216, 'Auto': 18.459, 'CCWM': 64.473, 'TeamName': 'Westwood Tomahawk'}, {'TeamNum': 16311, 'OPR': 77.243, 'Auto': 18.477, 'CCWM': 27.71, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 7079, 'OPR': 67.525, 'Auto': 7.74, 'CCWM': 3.06, 'TeamName': 'FalTech'}, {'TeamNum': 19853, 'OPR': 67.263, 'Auto': 13.599, 'CCWM': -7.883, 'TeamName': 'Roboteers'}, {'TeamNum': 5628, 'OPR': 64.045, 'Auto': 10.905, 'CCWM': -32.582, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 17264, 'OPR': 57.506, 'Auto': 16.423, 'CCWM': -12.106, 'TeamName': 'Westwood Arrowhead'}, {'TeamNum': 4546, 'OPR': 56.975, 'Auto': 6.769, 'CCWM': -13.515, 'TeamName': 'ViperBots SnakeByte'}, {'TeamNum': 22394, 'OPR': 53.486, 'Auto': 15.033, 'CCWM': -14.78, 'TeamName': 'Rouse Radians'}, {'TeamNum': 11503, 'OPR': 51.535, 'Auto': 15.837, 'CCWM': -43.753, 'TeamName': 'ViperBots HyperFang'}, {'TeamNum': 19852, 'OPR': 48.52, 'Auto': -3.729, 'CCWM': -8.357, 'TeamName': 'Platinum Platoon'}, {'TeamNum': 19591, 'OPR': 47.016, 'Auto': 17.258, 'CCWM': -63.99, 'TeamName': 'Some Assembly Required'}, {'TeamNum': 20716, 'OPR': 46.205, 'Auto': 26.163, 'CCWM': -29.419, 'TeamName': 'BeauBots'}, {'TeamNum': 21432, 'OPR': 44.147, 'Auto': 3.495, 'CCWM': 0.898, 'TeamName': 'Short Circuits'}, {'TeamNum': 18886, 'OPR': 42.548, 'Auto': -5.41, 'CCWM': 3.719, 'TeamName': 'Westwood Atlatl'}, {'TeamNum': 12670, 'OPR': 41.94, 'Auto': 6.422, 'CCWM': -6.442, 'TeamName': 'Eclipse 12670'}, {'TeamNum': 12596, 'OPR': 40.318, 'Auto': 0.305, 'CCWM': -13.861, 'TeamName': 'ViperBots Copperhead'}, {'TeamNum': 18884, 'OPR': 36.258, 'Auto': 8.856, 'CCWM': -31.956, 'TeamName': 'Westwood Boomerang'}, {'TeamNum': 21893, 'OPR': 35.1, 'Auto': 17.345, 'CCWM': -4.723, 'TeamName': 'Ursa Major'}, {'TeamNum': 6990, 'OPR': 34.307, 'Auto': 4.342, 'CCWM': -4.921, 'TeamName': 'Static Void'}, {'TeamNum': 16525, 'OPR': 30.334, 'Auto': -2.767, 'CCWM': -24.439, 'TeamName': 'SkyRise Robotics'}, {'TeamNum': 19380, 'OPR': 30.237, 'Auto': 5.543, 'CCWM': -41.093, 'TeamName': 'Millennium Falcons'}, {'TeamNum': 20240, 'OPR': 28.182, 'Auto': 8.355, 'CCWM': -55.572, 'TeamName': 'Westwood Slingshot'}, {'TeamNum': 7064, 'OPR': -13.588, 'Auto': -0.61, 'CCWM': -69.007, 'TeamName': 'R-Cubed'}]

i 908
{'16215', '22104', '14238', '17719', '16226', '16212', '17717', '16216', '22693', '20335'}
[{'TeamNum': 16212, 'OPR': 52.005, 'Auto': 9.55, 'CCWM': 40.197, 'TeamName': 'Tech-No-Logic'}, {'TeamNum': 16215, 'OPR': 37.739, 'Auto': 21.875, 'CCWM': 28.884, 'TeamName': 'Mystery Machine'}, {'TeamNum': 20335, 'OPR': 33.498, 'Auto': 4.688, 'CCWM': 6.21, 'TeamName': 'LIONBOTS'}, {'TeamNum': 16216, 'OPR': 32.489, 'Auto': 7.125, 'CCWM': 2.196, 'TeamName': 'System Overload'}, {'TeamNum': 14238, 'OPR': 32.155, 'Auto': 8.2, 'CCWM': 13.559, 'TeamName': 'Robo Lions (FTC)'}, {'TeamNum': 22104, 'OPR': 31.655, 'Auto': 1.2, 'CCWM': 10.684, 'TeamName': 'Douglass Dorks'}, {'TeamNum': 16226, 'OPR': 23.005, 'Auto': 7.05, 'CCWM': 6.447, 'TeamName': 'True Damage'}, {'TeamNum': 22693, 'OPR': 12.706, 'Auto': -4.938, 'CCWM': -26.426, 'TeamName': 'CEN--Pirates'}, {'TeamNum': 17719, 'OPR': 1.581, 'Auto': 4.438, 'CCWM': -30.082, 'TeamName': 'Cleveland Lady Indians'}, {'TeamNum': 17717, 'OPR': -1.877, 'Auto': -2.188, 'CCWM': -57.884, 'TeamName': 'Cleveland ISD Fearsome Donuts'}]
USTXHONEM3
[{'TeamNum': 16212, 'OPR': 52.005, 'Auto': 9.55, 'CCWM': 40.197, 'TeamName': 'Tech-No-Logic'}, {'TeamNum': 16215, 'OPR': 37.739, 'Auto': 21.875, 'CCWM': 28.884, 'TeamName': 'Mystery Machine'}, {'TeamNum': 20335, 'OPR': 33.498, 'Auto': 4.688, 'CCWM': 6.21, 'TeamName': 'LIONBOTS'}, {'TeamNum': 16216, 'OPR': 32.489, 'Auto': 7.125, 'CCWM': 2.196, 'TeamName': 'System Overload'}, {'TeamNum': 14238, 'OPR': 32.155, 'Auto': 8.2, 'CCWM': 13.559, 'TeamName': 'Robo Lions (FTC)'}, {'TeamNum': 22104, 'OPR': 31.655, 'Auto': 1.2, 'CCWM': 10.684, 'TeamName': 'Douglass Dorks'}, {'TeamNum': 16226, 'OPR': 23.005, 'Auto': 7.05, 'CCWM': 6.447, 'TeamName': 'True Damage'}, {'TeamNum': 22693, 'OPR': 12.706, 'Auto': -4.938, 'CCWM': -26.426, 'TeamName': 'CEN--Pirates'}, {'TeamNum': 17719, 'OPR': 1.581, 'Auto': 4.438, 'CCWM': -30.082, 'TeamName': 'Cleveland Lady Indians'}, {'TeamNum': 17717, 'OPR': -1.877, 'Auto': -2.188, 'CCWM': -57.884, 'TeamName': 'Cleveland ISD Fearsome Donuts'}]
i 909
{'17150', '17824', '22682', '8644', '18305', '20241', '19941', '19969', '15371', '16067', '9803', '7039', '293', '20005', '16537', '16439', '3804', '7278', '8095', '19832', '13389', '3116'}
[{'TeamNum': 8644, 'OPR': 152.624, 'Auto': 27.533, 'CCWM': 122.849, 'TeamName': 'The Brainstormers'}, {'TeamNum': 16537, 'OPR': 91.819, 'Auto': 25.857, 'CCWM': 19.105, 'TeamName': 'LOGICoyote'}, {'TeamNum': 16439, 'OPR': 85.21, 'Auto': 13.723, 'CCWM': 44.94, 'TeamName': 'AlphaGo'}, {'TeamNum': 8095, 'OPR': 66.708, 'Auto': 32.216, 'CCWM': 64.616, 'TeamName': 'NAnobots'}, {'TeamNum': 293, 'OPR': 53.093, 'Auto': 6.988, 'CCWM': 45.153, 'TeamName': 'Medium Builders'}, {'TeamNum': 3804, 'OPR': 46.199, 'Auto': 5.002, 'CCWM': 48.09, 'TeamName': 'Team Snuffleupagus'}, {'TeamNum': 19941, 'OPR': 45.078, 'Auto': 10.981, 'CCWM': 16.435, 'TeamName': 'M&M (Metal Masterminds).exe'}, {'TeamNum': 7039, 'OPR': 31.538, 'Auto': 2.728, 'CCWM': 23.81, 'TeamName': 'Lord of the Bricks'}, {'TeamNum': 18305, 'OPR': 28.89, 'Auto': 8.737, 'CCWM': -43.52, 'TeamName': 'Singularity'}, {'TeamNum': 20005, 'OPR': 28.434, 'Auto': 3.727, 'CCWM': -9.351, 'TeamName': 'BucketBots'}, {'TeamNum': 16067, 'OPR': 26.112, 'Auto': 8.091, 'CCWM': -19.605, 'TeamName': 'Retronic Lions'}, {'TeamNum': 17824, 'OPR': 23.241, 'Auto': 6.207, 'CCWM': 12.274, 'TeamName': 'Tiger Byte'}, {'TeamNum': 15371, 'OPR': 19.529, 'Auto': -1.539, 'CCWM': 4.507, 'TeamName': 'O.A.K.S.'}, {'TeamNum': 19832, 'OPR': 13.251, 'Auto': -2.201, 'CCWM': -36.905, 'TeamName': 'SBS R0b0tics'}, {'TeamNum': 13389, 'OPR': 11.912, 'Auto': 2.654, 'CCWM': -20.437, 'TeamName': 'Mallard Robotics'}, {'TeamNum': 9803, 'OPR': 6.825, 'Auto': 6.416, 'CCWM': -19.854, 'TeamName': 'Orange County High School Hornets'}, {'TeamNum': 17150, 'OPR': 6.174, 'Auto': -0.969, 'CCWM': -44.103, 'TeamName': 'Trojans'}, {'TeamNum': 22682, 'OPR': 4.974, 'Auto': 1.158, 'CCWM': -56.198, 'TeamName': 'Da Bananas'}, {'TeamNum': 7278, 'OPR': 4.826, 'Auto': -4.804, 'CCWM': -19.675, 'TeamName': 'LibraryBots'}, {'TeamNum': 19969, 'OPR': 4.094, 'Auto': -7.776, 'CCWM': -68.876, 'TeamName': 'Artificial Unintelligence'}, {'TeamNum': 3116, 'OPR': 2.961, 'Auto': 6.011, 'CCWM': -34.171, 'TeamName': 'Robo Warriors'}, {'TeamNum': 20241, 'OPR': 1.436, 'Auto': -4.323, 'CCWM': -29.912, 'TeamName': 'Roaring Robotics'}]
USCHSNOQ
[{'TeamNum': 8644, 'OPR': 152.624, 'Auto': 27.533, 'CCWM': 122.849, 'TeamName': 'The Brainstormers'}, {'TeamNum': 16537, 'OPR': 91.819, 'Auto': 25.857, 'CCWM': 19.105, 'TeamName': 'LOGICoyote'}, {'TeamNum': 16439, 'OPR': 85.21, 'Auto': 13.723, 'CCWM': 44.94, 'TeamName': 'AlphaGo'}, {'TeamNum': 8095, 'OPR': 66.708, 'Auto': 32.216, 'CCWM': 64.616, 'TeamName': 'NAnobots'}, {'TeamNum': 293, 'OPR': 53.093, 'Auto': 6.988, 'CCWM': 45.153, 'TeamName': 'Medium Builders'}, {'TeamNum': 3804, 'OPR': 46.199, 'Auto': 5.002, 'CCWM': 48.09, 'TeamName': 'Team Snuffleupagus'}, {'TeamNum': 19941, 'OPR': 45.078, 'Auto': 10.981, 'CCWM': 16.435, 'TeamName': 'M&M (Metal Masterminds).exe'}, {'TeamNum': 7039, 'OPR': 31.538, 'Auto': 2.728, 'CCWM': 23.81, 'TeamName': 'Lord of the Bricks'}, {'TeamNum': 18305, 'OPR': 28.89, 'Auto': 8.737, 'CCWM': -43.52, 'TeamName': 'Singularity'}, {'TeamNum': 20005, 'OPR': 28.434, 'Auto': 3.727, 'CCWM': -9.351, 'TeamName': 'BucketBots'}, {'TeamNum': 16067, 'OPR': 26.112, 'Auto': 8.091, 'CCWM': -19.605, 'TeamName': 'Retronic Lions'}, {'TeamNum': 17824, 'OPR': 23.241, 'Auto': 6.207, 'CCWM': 12.274, 'TeamName': 'Tiger Byte'}, {'TeamNum': 15371, 'OPR': 19.529, 'Auto': -1.539, 'CCWM': 4.507, 'TeamName': 'O.A.K.S.'}, {'TeamNum': 19832, 'OPR': 13.251, 'Auto': -2.201, 'CCWM': -36.905, 'TeamName': 'SBS R0b0tics'}, {'TeamNum': 13389, 'OPR': 11.912, 'Auto': 2.654, 'CCWM': -20.437, 'TeamName': 'Mallard Robotics'}, {'TeamNum': 9803, 'OPR': 6.825, 'Auto': 6.416, 'CCWM': -19.854, 'TeamName': 'Orange County High School Hornets'}, {'TeamNum': 17150, 'OPR': 6.174, 'Auto': -0.969, 'CCWM': -44.103, 'TeamName': 'Trojans'}, {'TeamNum': 22682, 'OPR': 4.974, 'Auto': 1.158, 'CCWM': -56.198, 'TeamName': 'Da Bananas'}, {'TeamNum': 7278, 'OPR': 4.826, 'Auto': -4.804, 'CCWM': -19.675, 'TeamName': 'LibraryBots'}, {'TeamNum': 19969, 'OPR': 4.094, 'Auto': -7.776, 'CCWM': -68.876, 'TeamName': 'Artificial Unintelligence'}, {'TeamNum': 3116, 'OPR': 2.961, 'Auto': 6.011, 'CCWM': -34.171, 'TeamName': 'Robo Warriors'}, {'TeamNum': 20241, 'OPR': 1.436, 'Auto': -4.323, 'CCWM': -29.912, 'TeamName': 'Roaring Robotics'}]
i 910
{'226', '13270', '3583', '8395', '16598', '7631', '12096', '14607', '22685', '11695', '14575', '369', '20337', '21310', '7518', '14315', '21232', '18103', '18381', '22022', '21814', '7519', '6010', '4234', '21929', '4451', '15167', '5178', '389', '19640', '3796', '13599', '5225', '12888', '21886', '11112', '18230', '5014'}
[{'TeamNum': 12096, 'OPR': 118.494, 'Auto': 36.246, 'CCWM': 80.94, 'TeamName': 'Absolute Zero'}, {'TeamNum': 11112, 'OPR': 99.403, 'Auto': 18.062, 'CCWM': 80.3, 'TeamName': 'RoboLords'}, {'TeamNum': 21232, 'OPR': 78.249, 'Auto': 17.048, 'CCWM': 30.756, 'TeamName': 'no team'}, {'TeamNum': 18381, 'OPR': 76.088, 'Auto': 15.353, 'CCWM': 29.619, 'TeamName': 'RAM Eaters'}, {'TeamNum': 14607, 'OPR': 73.01, 'Auto': 16.785, 'CCWM': 25.604, 'TeamName': 'Robot Uprising'}, {'TeamNum': 11695, 'OPR': 69.847, 'Auto': 27.698, 'CCWM': 42.179, 'TeamName': 'DeJava'}, {'TeamNum': 14575, 'OPR': 68.887, 'Auto': 13.593, 'CCWM': 34.275, 'TeamName': 'Capital Bots'}, {'TeamNum': 13599, 'OPR': 67.153, 'Auto': 27.026, 'CCWM': 45.232, 'TeamName': 'BruinBots'}, {'TeamNum': 6010, 'OPR': 66.597, 'Auto': 21.123, 'CCWM': 9.049, 'TeamName': 'Thunder Stone'}, {'TeamNum': 226, 'OPR': 65.337, 'Auto': 26.797, 'CCWM': 36.281, 'TeamName': 'Oakton Cougar Robotics 226'}, {'TeamNum': 15167, 'OPR': 61.131, 'Auto': 12.963, 'CCWM': 39.657, 'TeamName': 'Robo Troopers'}, {'TeamNum': 21814, 'OPR': 60.273, 'Auto': 11.173, 'CCWM': 3.754, 'TeamName': 'Robots on Roids'}, {'TeamNum': 13270, 'OPR': 57.294, 'Auto': 3.048, 'CCWM': 16.817, 'TeamName': 'Electric Slide'}, {'TeamNum': 5014, 'OPR': 55.094, 'Auto': 12.222, 'CCWM': 11.718, 'TeamName': 'Future Gadget Lab'}, {'TeamNum': 389, 'OPR': 54.304, 'Auto': 5.973, 'CCWM': 6.855, 'TeamName': 'The Swarm'}, {'TeamNum': 22685, 'OPR': 53.597, 'Auto': 25.777, 'CCWM': 12.049, 'TeamName': 'chosenconquerors'}, {'TeamNum': 3583, 'OPR': 52.459, 'Auto': 23.028, 'CCWM': 21.015, 'TeamName': 'Cybirds'}, {'TeamNum': 18103, 'OPR': 47.215, 'Auto': 7.305, 'CCWM': 11.212, 'TeamName': 'Nth Degree'}, {'TeamNum': 20337, 'OPR': 46.706, 'Auto': 14.584, 'CCWM': -24.821, 'TeamName': 'Say Watt?'}, {'TeamNum': 5225, 'OPR': 46.102, 'Auto': 13.824, 'CCWM': -0.184, 'TeamName': 'Sidwell Varsity'}, {'TeamNum': 8395, 'OPR': 43.651, 'Auto': 14.535, 'CCWM': -33.967, 'TeamName': 'The A-Team'}, {'TeamNum': 21310, 'OPR': 42.826, 'Auto': -6.43, 'CCWM': 8.013, 'TeamName': 'nexUs'}, {'TeamNum': 4234, 'OPR': 42.686, 'Auto': 6.455, 'CCWM': -4.326, 'TeamName': 'Engineered Chaos'}, {'TeamNum': 7631, 'OPR': 41.965, 'Auto': -4.87, 'CCWM': 2.138, 'TeamName': 'Instant Oats'}, {'TeamNum': 14315, 'OPR': 41.695, 'Auto': 3.181, 'CCWM': -23.494, 'TeamName': 'mobiUs'}, {'TeamNum': 16598, 'OPR': 40.961, 'Auto': 15.788, 'CCWM': -11.244, 'TeamName': 'Fairfax Roarbotics'}, {'TeamNum': 3796, 'OPR': 39.743, 'Auto': 27.059, 'CCWM': -22.277, 'TeamName': 'Talons'}, {'TeamNum': 7519, 'OPR': 37.892, 'Auto': 1.129, 'CCWM': -4.157, 'TeamName': 'QO CougarBotics'}, {'TeamNum': 18230, 'OPR': 36.003, 'Auto': 18.32, 'CCWM': -34.693, 'TeamName': 'luminUs'}, {'TeamNum': 7518, 'OPR': 34.709, 'Auto': 0.881, 'CCWM': 10.981, 'TeamName': 'QO CouGears'}, {'TeamNum': 4451, 'OPR': 34.704, 'Auto': 2.09, 'CCWM': -50.889, 'TeamName': 'FireFoxes'}, {'TeamNum': 21929, 'OPR': 32.671, 'Auto': 11.524, 'CCWM': 14.081, 'TeamName': 'Profound Pythons'}, {'TeamNum': 21886, 'OPR': 30.457, 'Auto': 8.842, 'CCWM': -15.041, 'TeamName': 'Lithium'}, {'TeamNum': 22022, 'OPR': 28.545, 'Auto': 10.296, 'CCWM': -37.236, 'TeamName': 'Electric Eagles'}, {'TeamNum': 12888, 'OPR': 21.173, 'Auto': 8.744, 'CCWM': -53.595, 'TeamName': 'The Stingers'}, {'TeamNum': 19640, 'OPR': -1.82, 'Auto': 0.204, 'CCWM': -94.434, 'TeamName': 'Foxcroft'}, {'TeamNum': 369, 'OPR': -7.55, 'Auto': -10.794, 'CCWM': -75.556, 'TeamName': 'Oakton Cougar Robotics 369'}, {'TeamNum': 5178, 'OPR': -9.197, 'Auto': -8.915, 'CCWM': -81.629, 'TeamName': 'Mech Hawks'}]
USCHSHEQ
[{'TeamNum': 12096, 'OPR': 118.494, 'Auto': 36.246, 'CCWM': 80.94, 'TeamName': 'Absolute Zero'}, {'TeamNum': 11112, 'OPR': 99.403, 'Auto': 18.062, 'CCWM': 80.3, 'TeamName': 'RoboLords'}, {'TeamNum': 21232, 'OPR': 78.249, 'Auto': 17.048, 'CCWM': 30.756, 'TeamName': 'no team'}, {'TeamNum': 18381, 'OPR': 76.088, 'Auto': 15.353, 'CCWM': 29.619, 'TeamName': 'RAM Eaters'}, {'TeamNum': 14607, 'OPR': 73.01, 'Auto': 16.785, 'CCWM': 25.604, 'TeamName': 'Robot Uprising'}, {'TeamNum': 11695, 'OPR': 69.847, 'Auto': 27.698, 'CCWM': 42.179, 'TeamName': 'DeJava'}, {'TeamNum': 14575, 'OPR': 68.887, 'Auto': 13.593, 'CCWM': 34.275, 'TeamName': 'Capital Bots'}, {'TeamNum': 13599, 'OPR': 67.153, 'Auto': 27.026, 'CCWM': 45.232, 'TeamName': 'BruinBots'}, {'TeamNum': 6010, 'OPR': 66.597, 'Auto': 21.123, 'CCWM': 9.049, 'TeamName': 'Thunder Stone'}, {'TeamNum': 226, 'OPR': 65.337, 'Auto': 26.797, 'CCWM': 36.281, 'TeamName': 'Oakton Cougar Robotics 226'}, {'TeamNum': 15167, 'OPR': 61.131, 'Auto': 12.963, 'CCWM': 39.657, 'TeamName': 'Robo Troopers'}, {'TeamNum': 21814, 'OPR': 60.273, 'Auto': 11.173, 'CCWM': 3.754, 'TeamName': 'Robots on Roids'}, {'TeamNum': 13270, 'OPR': 57.294, 'Auto': 3.048, 'CCWM': 16.817, 'TeamName': 'Electric Slide'}, {'TeamNum': 5014, 'OPR': 55.094, 'Auto': 12.222, 'CCWM': 11.718, 'TeamName': 'Future Gadget Lab'}, {'TeamNum': 389, 'OPR': 54.304, 'Auto': 5.973, 'CCWM': 6.855, 'TeamName': 'The Swarm'}, {'TeamNum': 22685, 'OPR': 53.597, 'Auto': 25.777, 'CCWM': 12.049, 'TeamName': 'chosenconquerors'}, {'TeamNum': 3583, 'OPR': 52.459, 'Auto': 23.028, 'CCWM': 21.015, 'TeamName': 'Cybirds'}, {'TeamNum': 18103, 'OPR': 47.215, 'Auto': 7.305, 'CCWM': 11.212, 'TeamName': 'Nth Degree'}, {'TeamNum': 20337, 'OPR': 46.706, 'Auto': 14.584, 'CCWM': -24.821, 'TeamName': 'Say Watt?'}, {'TeamNum': 5225, 'OPR': 46.102, 'Auto': 13.824, 'CCWM': -0.184, 'TeamName': 'Sidwell Varsity'}, {'TeamNum': 8395, 'OPR': 43.651, 'Auto': 14.535, 'CCWM': -33.967, 'TeamName': 'The A-Team'}, {'TeamNum': 21310, 'OPR': 42.826, 'Auto': -6.43, 'CCWM': 8.013, 'TeamName': 'nexUs'}, {'TeamNum': 4234, 'OPR': 42.686, 'Auto': 6.455, 'CCWM': -4.326, 'TeamName': 'Engineered Chaos'}, {'TeamNum': 7631, 'OPR': 41.965, 'Auto': -4.87, 'CCWM': 2.138, 'TeamName': 'Instant Oats'}, {'TeamNum': 14315, 'OPR': 41.695, 'Auto': 3.181, 'CCWM': -23.494, 'TeamName': 'mobiUs'}, {'TeamNum': 16598, 'OPR': 40.961, 'Auto': 15.788, 'CCWM': -11.244, 'TeamName': 'Fairfax Roarbotics'}, {'TeamNum': 3796, 'OPR': 39.743, 'Auto': 27.059, 'CCWM': -22.277, 'TeamName': 'Talons'}, {'TeamNum': 7519, 'OPR': 37.892, 'Auto': 1.129, 'CCWM': -4.157, 'TeamName': 'QO CougarBotics'}, {'TeamNum': 18230, 'OPR': 36.003, 'Auto': 18.32, 'CCWM': -34.693, 'TeamName': 'luminUs'}, {'TeamNum': 7518, 'OPR': 34.709, 'Auto': 0.881, 'CCWM': 10.981, 'TeamName': 'QO CouGears'}, {'TeamNum': 4451, 'OPR': 34.704, 'Auto': 2.09, 'CCWM': -50.889, 'TeamName': 'FireFoxes'}, {'TeamNum': 21929, 'OPR': 32.671, 'Auto': 11.524, 'CCWM': 14.081, 'TeamName': 'Profound Pythons'}, {'TeamNum': 21886, 'OPR': 30.457, 'Auto': 8.842, 'CCWM': -15.041, 'TeamName': 'Lithium'}, {'TeamNum': 22022, 'OPR': 28.545, 'Auto': 10.296, 'CCWM': -37.236, 'TeamName': 'Electric Eagles'}, {'TeamNum': 12888, 'OPR': 21.173, 'Auto': 8.744, 'CCWM': -53.595, 'TeamName': 'The Stingers'}, {'TeamNum': 19640, 'OPR': -1.82, 'Auto': 0.204, 'CCWM': -94.434, 'TeamName': 'Foxcroft'}, {'TeamNum': 369, 'OPR': -7.55, 'Auto': -10.794, 'CCWM': -75.556, 'TeamName': 'Oakton Cougar Robotics 369'}, {'TeamNum': 5178, 'OPR': -9.197, 'Auto': -8.915, 'CCWM': -81.629, 'TeamName': 'Mech Hawks'}]

i 911
{'16750', '19708', '7759', '11186', '14343', '14179', '18225', '8099', '21336', '417', '11990', '6424', '16451', '21230', '15337', '19589', '11138', '6188', '11970', '19745', '5604', '18079', '20345', '14563', '21229', '6220', '8548', '3805', '16942', '21370', '17103', '6559', '8693', '17595'}
[{'TeamNum': 21229, 'OPR': 160.785, 'Auto': 43.27, 'CCWM': 74.9, 'TeamName': 'Quality Control'}, {'TeamNum': 17595, 'OPR': 145.61, 'Auto': 26.735, 'CCWM': 60.61, 'TeamName': 'Beta Bionix'}, {'TeamNum': 19708, 'OPR': 133.6, 'Auto': 38.97, 'CCWM': 57.486, 'TeamName': 'The Emerald Bots'}, {'TeamNum': 14343, 'OPR': 132.115, 'Auto': 27.399, 'CCWM': 96.128, 'TeamName': 'Escape Velocity'}, {'TeamNum': 3805, 'OPR': 128.192, 'Auto': 38.184, 'CCWM': 70.725, 'TeamName': 'Atomic Robotics'}, {'TeamNum': 16942, 'OPR': 118.219, 'Auto': 23.367, 'CCWM': 30.185, 'TeamName': 'Minutemen'}, {'TeamNum': 15337, 'OPR': 109.458, 'Auto': 18.062, 'CCWM': 75.622, 'TeamName': 'Alpha Intelligence'}, {'TeamNum': 417, 'OPR': 104.747, 'Auto': 21.081, 'CCWM': 24.248, 'TeamName': 'S.K.I.D. (Space Koalas In Disguise)'}, {'TeamNum': 11970, 'OPR': 94.073, 'Auto': 14.086, 'CCWM': 47.781, 'TeamName': 'Titanium Talons '}, {'TeamNum': 5604, 'OPR': 93.308, 'Auto': 20.002, 'CCWM': 26.334, 'TeamName': 'Thunderbots'}, {'TeamNum': 6220, 'OPR': 90.241, 'Auto': 26.939, 'CCWM': 36.116, 'TeamName': 'DRIFT (Dinosaurs Racing in Food Trucks)'}, {'TeamNum': 11138, 'OPR': 87.742, 'Auto': 23.243, 'CCWM': 19.966, 'TeamName': 'Robo Eclipse'}, {'TeamNum': 7759, 'OPR': 83.151, 'Auto': 22.068, 'CCWM': -18.239, 'TeamName': 'Autonomous Prime'}, {'TeamNum': 21336, 'OPR': 75.241, 'Auto': 14.903, 'CCWM': -6.419, 'TeamName': 'I Forgot'}, {'TeamNum': 18225, 'OPR': 69.897, 'Auto': 15.361, 'CCWM': -6.933, 'TeamName': 'High Definition '}, {'TeamNum': 21370, 'OPR': 64.605, 'Auto': -2.59, 'CCWM': -18.594, 'TeamName': 'Built-Different'}, {'TeamNum': 11186, 'OPR': 57.995, 'Auto': 22.032, 'CCWM': 3.496, 'TeamName': 'Mecha-Mules'}, {'TeamNum': 20345, 'OPR': 57.541, 'Auto': 15.892, 'CCWM': -18.859, 'TeamName': 'Kobalt Klaws'}, {'TeamNum': 21230, 'OPR': 50.438, 'Auto': 17.096, 'CCWM': -14.15, 'TeamName': 'TechnoPhoenix'}, {'TeamNum': 18079, 'OPR': 48.283, 'Auto': 5.13, 'CCWM': 4.773, 'TeamName': 'Accidental Success'}, {'TeamNum': 14563, 'OPR': 48.212, 'Auto': 19.625, 'CCWM': -38.463, 'TeamName': 'Teriffic Tech Bots'}, {'TeamNum': 8693, 'OPR': 45.038, 'Auto': 12.464, 'CCWM': -35.908, 'TeamName': 'Scarabs'}, {'TeamNum': 19589, 'OPR': 43.106, 'Auto': 12.846, 'CCWM': -33.059, 'TeamName': 'Falcons Robotics - Green'}, {'TeamNum': 16451, 'OPR': 40.655, 'Auto': 7.82, 'CCWM': -19.35, 'TeamName': 'Foundation'}, {'TeamNum': 6559, 'OPR': 39.366, 'Auto': 3.356, 'CCWM': -69.881, 'TeamName': 'Geared Reaction'}, {'TeamNum': 8548, 'OPR': 37.305, 'Auto': -4.291, 'CCWM': -20.194, 'TeamName': 'Bearly Functioning'}, {'TeamNum': 19745, 'OPR': 36.206, 'Auto': 5.6, 'CCWM': 2.677, 'TeamName': 'Turtle Walkers'}, {'TeamNum': 11990, 'OPR': 34.665, 'Auto': 2.404, 'CCWM': -81.817, 'TeamName': 'Run_Kano'}, {'TeamNum': 6424, 'OPR': 29.491, 'Auto': 5.984, 'CCWM': -54.573, 'TeamName': 'Oly Cow'}, {'TeamNum': 17103, 'OPR': 22.576, 'Auto': -2.466, 'CCWM': -69.335, 'TeamName': 'Falcon Gold'}, {'TeamNum': 16750, 'OPR': 16.882, 'Auto': 2.736, 'CCWM': -112.172, 'TeamName': 'Technototes'}, {'TeamNum': 8099, 'OPR': 13.857, 'Auto': 4.691, 'CCWM': -13.102, 'TeamName': 'Hanford Falcons'}, {'TeamNum': 14179, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Sushi Squad'}, {'TeamNum': 6188, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'SiBorgs'}]
USWACMP
[{'TeamNum': 21229, 'OPR': 160.785, 'Auto': 43.27, 'CCWM': 74.9, 'TeamName': 'Quality Control'}, {'TeamNum': 17595, 'OPR': 145.61, 'Auto': 26.735, 'CCWM': 60.61, 'TeamName': 'Beta Bionix'}, {'TeamNum': 19708, 'OPR': 133.6, 'Auto': 38.97, 'CCWM': 57.486, 'TeamName': 'The Emerald Bots'}, {'TeamNum': 14343, 'OPR': 132.115, 'Auto': 27.399, 'CCWM': 96.128, 'TeamName': 'Escape Velocity'}, {'TeamNum': 3805, 'OPR': 128.192, 'Auto': 38.184, 'CCWM': 70.725, 'TeamName': 'Atomic Robotics'}, {'TeamNum': 16942, 'OPR': 118.219, 'Auto': 23.367, 'CCWM': 30.185, 'TeamName': 'Minutemen'}, {'TeamNum': 15337, 'OPR': 109.458, 'Auto': 18.062, 'CCWM': 75.622, 'TeamName': 'Alpha Intelligence'}, {'TeamNum': 417, 'OPR': 104.747, 'Auto': 21.081, 'CCWM': 24.248, 'TeamName': 'S.K.I.D. (Space Koalas In Disguise)'}, {'TeamNum': 11970, 'OPR': 94.073, 'Auto': 14.086, 'CCWM': 47.781, 'TeamName': 'Titanium Talons '}, {'TeamNum': 5604, 'OPR': 93.308, 'Auto': 20.002, 'CCWM': 26.334, 'TeamName': 'Thunderbots'}, {'TeamNum': 6220, 'OPR': 90.241, 'Auto': 26.939, 'CCWM': 36.116, 'TeamName': 'DRIFT (Dinosaurs Racing in Food Trucks)'}, {'TeamNum': 11138, 'OPR': 87.742, 'Auto': 23.243, 'CCWM': 19.966, 'TeamName': 'Robo Eclipse'}, {'TeamNum': 7759, 'OPR': 83.151, 'Auto': 22.068, 'CCWM': -18.239, 'TeamName': 'Autonomous Prime'}, {'TeamNum': 21336, 'OPR': 75.241, 'Auto': 14.903, 'CCWM': -6.419, 'TeamName': 'I Forgot'}, {'TeamNum': 18225, 'OPR': 69.897, 'Auto': 15.361, 'CCWM': -6.933, 'TeamName': 'High Definition '}, {'TeamNum': 21370, 'OPR': 64.605, 'Auto': -2.59, 'CCWM': -18.594, 'TeamName': 'Built-Different'}, {'TeamNum': 11186, 'OPR': 57.995, 'Auto': 22.032, 'CCWM': 3.496, 'TeamName': 'Mecha-Mules'}, {'TeamNum': 20345, 'OPR': 57.541, 'Auto': 15.892, 'CCWM': -18.859, 'TeamName': 'Kobalt Klaws'}, {'TeamNum': 21230, 'OPR': 50.438, 'Auto': 17.096, 'CCWM': -14.15, 'TeamName': 'TechnoPhoenix'}, {'TeamNum': 18079, 'OPR': 48.283, 'Auto': 5.13, 'CCWM': 4.773, 'TeamName': 'Accidental Success'}, {'TeamNum': 14563, 'OPR': 48.212, 'Auto': 19.625, 'CCWM': -38.463, 'TeamName': 'Teriffic Tech Bots'}, {'TeamNum': 8693, 'OPR': 45.038, 'Auto': 12.464, 'CCWM': -35.908, 'TeamName': 'Scarabs'}, {'TeamNum': 19589, 'OPR': 43.106, 'Auto': 12.846, 'CCWM': -33.059, 'TeamName': 'Falcons Robotics - Green'}, {'TeamNum': 16451, 'OPR': 40.655, 'Auto': 7.82, 'CCWM': -19.35, 'TeamName': 'Foundation'}, {'TeamNum': 6559, 'OPR': 39.366, 'Auto': 3.356, 'CCWM': -69.881, 'TeamName': 'Geared Reaction'}, {'TeamNum': 8548, 'OPR': 37.305, 'Auto': -4.291, 'CCWM': -20.194, 'TeamName': 'Bearly Functioning'}, {'TeamNum': 19745, 'OPR': 36.206, 'Auto': 5.6, 'CCWM': 2.677, 'TeamName': 'Turtle Walkers'}, {'TeamNum': 11990, 'OPR': 34.665, 'Auto': 2.404, 'CCWM': -81.817, 'TeamName': 'Run_Kano'}, {'TeamNum': 6424, 'OPR': 29.491, 'Auto': 5.984, 'CCWM': -54.573, 'TeamName': 'Oly Cow'}, {'TeamNum': 17103, 'OPR': 22.576, 'Auto': -2.466, 'CCWM': -69.335, 'TeamName': 'Falcon Gold'}, {'TeamNum': 16750, 'OPR': 16.882, 'Auto': 2.736, 'CCWM': -112.172, 'TeamName': 'Technototes'}, {'TeamNum': 8099, 'OPR': 13.857, 'Auto': 4.691, 'CCWM': -13.102, 'TeamName': 'Hanford Falcons'}, {'TeamNum': 14179, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Sushi Squad'}, {'TeamNum': 6188, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'SiBorgs'}]
i 912
{'21385', '22672', '21867', '19796', '16252', '13828', '14631', '17322', '8755', '4116', '16310', '22548', '7974', '16001', '22526', '12966', '19417', '21737', '9224', '13201', '16460', '11353', '17235', '6985'}
[{'TeamNum': 14631, 'OPR': 124.155, 'Auto': 35.616, 'CCWM': 72.287, 'TeamName': 'Laser Tech'}, {'TeamNum': 8755, 'OPR': 115.893, 'Auto': 31.468, 'CCWM': 55.968, 'TeamName': 'E-Storm'}, {'TeamNum': 4116, 'OPR': 94.685, 'Auto': 23.998, 'CCWM': 36.934, 'TeamName': 'Volta Robotics'}, {'TeamNum': 16252, 'OPR': 71.396, 'Auto': 14.22, 'CCWM': 71.458, 'TeamName': 'Ruh-Roh Robotics'}, {'TeamNum': 21737, 'OPR': 64.352, 'Auto': 18.419, 'CCWM': 2.612, 'TeamName': 'Green Eggs and Program'}, {'TeamNum': 17235, 'OPR': 62.221, 'Auto': 3.958, 'CCWM': 27.498, 'TeamName': 'MR. COD'}, {'TeamNum': 16310, 'OPR': 61.026, 'Auto': 22.261, 'CCWM': 16.751, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 16460, 'OPR': 60.734, 'Auto': 5.218, 'CCWM': 27.103, 'TeamName': 'GEarheads'}, {'TeamNum': 13201, 'OPR': 58.404, 'Auto': 20.115, 'CCWM': 6.454, 'TeamName': 'Team Hazmat'}, {'TeamNum': 6985, 'OPR': 52.247, 'Auto': 17.134, 'CCWM': 33.921, 'TeamName': 'Droid Rage Rewired'}, {'TeamNum': 12966, 'OPR': 50.97, 'Auto': 4.166, 'CCWM': -22.344, 'TeamName': 'C-GULL ROBOTICS'}, {'TeamNum': 13828, 'OPR': 43.923, 'Auto': 19.375, 'CCWM': -6.446, 'TeamName': 'Java Jokers'}, {'TeamNum': 7974, 'OPR': 42.596, 'Auto': 4.264, 'CCWM': 27.95, 'TeamName': 'Great Scott!'}, {'TeamNum': 22526, 'OPR': 39.237, 'Auto': 2.066, 'CCWM': 23.533, 'TeamName': 'FSA Gear Grinders'}, {'TeamNum': 19417, 'OPR': 38.018, 'Auto': 25.256, 'CCWM': -40.183, 'TeamName': 'Superstellar'}, {'TeamNum': 22548, 'OPR': 34.791, 'Auto': 5.208, 'CCWM': -18.446, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 22672, 'OPR': 34.15, 'Auto': -2.649, 'CCWM': -60.973, 'TeamName': 'Absolute Hack'}, {'TeamNum': 21385, 'OPR': 29.212, 'Auto': -0.454, 'CCWM': -75.275, 'TeamName': "Nuclear Fishin'"}, {'TeamNum': 16001, 'OPR': 25.817, 'Auto': 12.993, 'CCWM': -57.536, 'TeamName': 'Robo Dons'}, {'TeamNum': 17322, 'OPR': 25.35, 'Auto': 0.699, 'CCWM': -29.928, 'TeamName': 'ML Spartronics'}, {'TeamNum': 9224, 'OPR': 22.976, 'Auto': 14.101, 'CCWM': -48.898, 'TeamName': 'Techno G.O.A.T.S.'}, {'TeamNum': 21867, 'OPR': 18.171, 'Auto': -1.976, 'CCWM': -27.722, 'TeamName': 'Door of Hope'}, {'TeamNum': 19796, 'OPR': 5.686, 'Auto': 2.09, 'CCWM': -28.207, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 11353, 'OPR': 3.789, 'Auto': 1.055, 'CCWM': 13.491, 'TeamName': 'Lightning Robotics'}]
USWIHAQ
[{'TeamNum': 14631, 'OPR': 124.155, 'Auto': 35.616, 'CCWM': 72.287, 'TeamName': 'Laser Tech'}, {'TeamNum': 8755, 'OPR': 115.893, 'Auto': 31.468, 'CCWM': 55.968, 'TeamName': 'E-Storm'}, {'TeamNum': 4116, 'OPR': 94.685, 'Auto': 23.998, 'CCWM': 36.934, 'TeamName': 'Volta Robotics'}, {'TeamNum': 16252, 'OPR': 71.396, 'Auto': 14.22, 'CCWM': 71.458, 'TeamName': 'Ruh-Roh Robotics'}, {'TeamNum': 21737, 'OPR': 64.352, 'Auto': 18.419, 'CCWM': 2.612, 'TeamName': 'Green Eggs and Program'}, {'TeamNum': 17235, 'OPR': 62.221, 'Auto': 3.958, 'CCWM': 27.498, 'TeamName': 'MR. COD'}, {'TeamNum': 16310, 'OPR': 61.026, 'Auto': 22.261, 'CCWM': 16.751, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 16460, 'OPR': 60.734, 'Auto': 5.218, 'CCWM': 27.103, 'TeamName': 'GEarheads'}, {'TeamNum': 13201, 'OPR': 58.404, 'Auto': 20.115, 'CCWM': 6.454, 'TeamName': 'Team Hazmat'}, {'TeamNum': 6985, 'OPR': 52.247, 'Auto': 17.134, 'CCWM': 33.921, 'TeamName': 'Droid Rage Rewired'}, {'TeamNum': 12966, 'OPR': 50.97, 'Auto': 4.166, 'CCWM': -22.344, 'TeamName': 'C-GULL ROBOTICS'}, {'TeamNum': 13828, 'OPR': 43.923, 'Auto': 19.375, 'CCWM': -6.446, 'TeamName': 'Java Jokers'}, {'TeamNum': 7974, 'OPR': 42.596, 'Auto': 4.264, 'CCWM': 27.95, 'TeamName': 'Great Scott!'}, {'TeamNum': 22526, 'OPR': 39.237, 'Auto': 2.066, 'CCWM': 23.533, 'TeamName': 'FSA Gear Grinders'}, {'TeamNum': 19417, 'OPR': 38.018, 'Auto': 25.256, 'CCWM': -40.183, 'TeamName': 'Superstellar'}, {'TeamNum': 22548, 'OPR': 34.791, 'Auto': 5.208, 'CCWM': -18.446, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 22672, 'OPR': 34.15, 'Auto': -2.649, 'CCWM': -60.973, 'TeamName': 'Absolute Hack'}, {'TeamNum': 21385, 'OPR': 29.212, 'Auto': -0.454, 'CCWM': -75.275, 'TeamName': "Nuclear Fishin'"}, {'TeamNum': 16001, 'OPR': 25.817, 'Auto': 12.993, 'CCWM': -57.536, 'TeamName': 'Robo Dons'}, {'TeamNum': 17322, 'OPR': 25.35, 'Auto': 0.699, 'CCWM': -29.928, 'TeamName': 'ML Spartronics'}, {'TeamNum': 9224, 'OPR': 22.976, 'Auto': 14.101, 'CCWM': -48.898, 'TeamName': 'Techno G.O.A.T.S.'}, {'TeamNum': 21867, 'OPR': 18.171, 'Auto': -1.976, 'CCWM': -27.722, 'TeamName': 'Door of Hope'}, {'TeamNum': 19796, 'OPR': 5.686, 'Auto': 2.09, 'CCWM': -28.207, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 11353, 'OPR': 3.789, 'Auto': 1.055, 'CCWM': 13.491, 'TeamName': 'Lightning Robotics'}]

i 913
{'21481', '5009', '20190', '21872', '10544', '20085', '12094', '20251', '22459', '21339', '21395', '22460', '22092', '15254', '4169', '20693', '12265', '16494', '12513'}
[{'TeamNum': 10544, 'OPR': 72.081, 'Auto': 10.838, 'CCWM': 53.82, 'TeamName': 'Cyber Eagles - Silver'}, {'TeamNum': 12265, 'OPR': 65.07, 'Auto': 24.718, 'CCWM': 49.19, 'TeamName': 'GearHeads'}, {'TeamNum': 15254, 'OPR': 58.703, 'Auto': 25.682, 'CCWM': 37.807, 'TeamName': 'Facey Robotics'}, {'TeamNum': 4169, 'OPR': 57.943, 'Auto': 21.377, 'CCWM': 23.559, 'TeamName': 'H.A.R.I.S.H.'}, {'TeamNum': 22092, 'OPR': 55.072, 'Auto': 15.557, 'CCWM': 29.275, 'TeamName': 'Cyber Eagles - Jade'}, {'TeamNum': 5009, 'OPR': 52.666, 'Auto': 20.039, 'CCWM': 22.23, 'TeamName': 'Hélios'}, {'TeamNum': 16494, 'OPR': 40.352, 'Auto': 14.959, 'CCWM': 2.5, 'TeamName': 'Raiders - Red'}, {'TeamNum': 21339, 'OPR': 39.246, 'Auto': 4.235, 'CCWM': 3.684, 'TeamName': 'Salisbury Robotics'}, {'TeamNum': 21872, 'OPR': 38.7, 'Auto': 12.504, 'CCWM': 7.208, 'TeamName': 'PowerRangers'}, {'TeamNum': 20085, 'OPR': 36.816, 'Auto': 11.499, 'CCWM': -6.232, 'TeamName': 'Pumabotics'}, {'TeamNum': 20693, 'OPR': 33.939, 'Auto': 6.051, 'CCWM': -1.07, 'TeamName': 'Raiders - White'}, {'TeamNum': 21481, 'OPR': 20.449, 'Auto': 11.149, 'CCWM': -24.68, 'TeamName': 'SEES'}, {'TeamNum': 12094, 'OPR': 19.978, 'Auto': -3.576, 'CCWM': -24.905, 'TeamName': 'Team TWOSE'}, {'TeamNum': 12513, 'OPR': 19.369, 'Auto': 9.122, 'CCWM': -17.703, 'TeamName': 'Les Scorpions'}, {'TeamNum': 22459, 'OPR': 17.04, 'Auto': 1.796, 'CCWM': -4.66, 'TeamName': 'SJHS Falcons - Grey_2'}, {'TeamNum': 22460, 'OPR': 14.883, 'Auto': 7.96, 'CCWM': -50.997, 'TeamName': 'SJHS Falcons - B_Blue'}, {'TeamNum': 21395, 'OPR': 10.812, 'Auto': 0.857, 'CCWM': -35.856, 'TeamName': 'AlBaqir Academy'}, {'TeamNum': 20251, 'OPR': 3.216, 'Auto': -2.182, 'CCWM': -33.887, 'TeamName': 'Raiders - Black'}, {'TeamNum': 20190, 'OPR': 2.682, 'Auto': -2.476, 'CCWM': -37.215, 'TeamName': 'SJHS Falcons - The Unhinged'}]
CAABABNALT
[{'TeamNum': 10544, 'OPR': 72.081, 'Auto': 10.838, 'CCWM': 53.82, 'TeamName': 'Cyber Eagles - Silver'}, {'TeamNum': 12265, 'OPR': 65.07, 'Auto': 24.718, 'CCWM': 49.19, 'TeamName': 'GearHeads'}, {'TeamNum': 15254, 'OPR': 58.703, 'Auto': 25.682, 'CCWM': 37.807, 'TeamName': 'Facey Robotics'}, {'TeamNum': 4169, 'OPR': 57.943, 'Auto': 21.377, 'CCWM': 23.559, 'TeamName': 'H.A.R.I.S.H.'}, {'TeamNum': 22092, 'OPR': 55.072, 'Auto': 15.557, 'CCWM': 29.275, 'TeamName': 'Cyber Eagles - Jade'}, {'TeamNum': 5009, 'OPR': 52.666, 'Auto': 20.039, 'CCWM': 22.23, 'TeamName': 'Hélios'}, {'TeamNum': 16494, 'OPR': 40.352, 'Auto': 14.959, 'CCWM': 2.5, 'TeamName': 'Raiders - Red'}, {'TeamNum': 21339, 'OPR': 39.246, 'Auto': 4.235, 'CCWM': 3.684, 'TeamName': 'Salisbury Robotics'}, {'TeamNum': 21872, 'OPR': 38.7, 'Auto': 12.504, 'CCWM': 7.208, 'TeamName': 'PowerRangers'}, {'TeamNum': 20085, 'OPR': 36.816, 'Auto': 11.499, 'CCWM': -6.232, 'TeamName': 'Pumabotics'}, {'TeamNum': 20693, 'OPR': 33.939, 'Auto': 6.051, 'CCWM': -1.07, 'TeamName': 'Raiders - White'}, {'TeamNum': 21481, 'OPR': 20.449, 'Auto': 11.149, 'CCWM': -24.68, 'TeamName': 'SEES'}, {'TeamNum': 12094, 'OPR': 19.978, 'Auto': -3.576, 'CCWM': -24.905, 'TeamName': 'Team TWOSE'}, {'TeamNum': 12513, 'OPR': 19.369, 'Auto': 9.122, 'CCWM': -17.703, 'TeamName': 'Les Scorpions'}, {'TeamNum': 22459, 'OPR': 17.04, 'Auto': 1.796, 'CCWM': -4.66, 'TeamName': 'SJHS Falcons - Grey_2'}, {'TeamNum': 22460, 'OPR': 14.883, 'Auto': 7.96, 'CCWM': -50.997, 'TeamName': 'SJHS Falcons - B_Blue'}, {'TeamNum': 21395, 'OPR': 10.812, 'Auto': 0.857, 'CCWM': -35.856, 'TeamName': 'AlBaqir Academy'}, {'TeamNum': 20251, 'OPR': 3.216, 'Auto': -2.182, 'CCWM': -33.887, 'TeamName': 'Raiders - Black'}, {'TeamNum': 20190, 'OPR': 2.682, 'Auto': -2.476, 'CCWM': -37.215, 'TeamName': 'SJHS Falcons - The Unhinged'}]
i 914
{'17019', '13452', '14029', '11443', '11567', '13146', '19000', '11808', '9662', '17056', '14872', '22681', '19967', '12817', '11635', '22644', '12201', '21957', '15298', '16473', '18833', '12797', '22764', '22734', '21796', '11192', '14028', '18735', '11226', '17182', '15141', '17106', '18268'}
[{'TeamNum': 14029, 'OPR': 128.332, 'Auto': 19.014, 'CCWM': 112.214, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 11192, 'OPR': 87.254, 'Auto': 10.055, 'CCWM': 52.871, 'TeamName': 'Black Tigers'}, {'TeamNum': 16473, 'OPR': 78.602, 'Auto': 14.726, 'CCWM': 60.854, 'TeamName': 'SciFighters'}, {'TeamNum': 12797, 'OPR': 74.006, 'Auto': 16.399, 'CCWM': 14.162, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 11808, 'OPR': 72.617, 'Auto': 6.882, 'CCWM': 46.189, 'TeamName': 'Connection'}, {'TeamNum': 12201, 'OPR': 64.169, 'Auto': 18.367, 'CCWM': 27.054, 'TeamName': 'TATOOINE'}, {'TeamNum': 14028, 'OPR': 64.145, 'Auto': 11.139, 'CCWM': 12.989, 'TeamName': 'Orbit 10'}, {'TeamNum': 13146, 'OPR': 63.538, 'Auto': 10.373, 'CCWM': 1.37, 'TeamName': 'Makers Assemble'}, {'TeamNum': 14872, 'OPR': 61.388, 'Auto': 2.05, 'CCWM': 39.927, 'TeamName': 'Orbit 9'}, {'TeamNum': 15298, 'OPR': 59.043, 'Auto': 13.392, 'CCWM': 31.662, 'TeamName': 'RoboTen'}, {'TeamNum': 21957, 'OPR': 53.356, 'Auto': 20.248, 'CCWM': -1.309, 'TeamName': 'Goblin Mode'}, {'TeamNum': 13452, 'OPR': 53.091, 'Auto': 2.076, 'CCWM': 9.592, 'TeamName': 'BTJ'}, {'TeamNum': 17019, 'OPR': 51.458, 'Auto': 1.995, 'CCWM': 8.595, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 15141, 'OPR': 50.62, 'Auto': 1.416, 'CCWM': 29.43, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 22734, 'OPR': 50.608, 'Auto': 0.817, 'CCWM': 17.988, 'TeamName': 'Jotunheim '}, {'TeamNum': 18833, 'OPR': 47.106, 'Auto': 20.066, 'CCWM': -1.824, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 11443, 'OPR': 44.805, 'Auto': -0.436, 'CCWM': 3.845, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 11567, 'OPR': 38.869, 'Auto': 15.057, 'CCWM': 0.219, 'TeamName': 'Supernova'}, {'TeamNum': 19967, 'OPR': 33.37, 'Auto': 3.198, 'CCWM': -33.11, 'TeamName': 'AIS Talons'}, {'TeamNum': 11226, 'OPR': 32.805, 'Auto': 4.612, 'CCWM': 37.835, 'TeamName': 'Black Thunder'}, {'TeamNum': 17106, 'OPR': 29.226, 'Auto': 11.989, 'CCWM': 6.18, 'TeamName': 'PlanTech'}, {'TeamNum': 9662, 'OPR': 28.049, 'Auto': 8.298, 'CCWM': -32.19, 'TeamName': 'Apollo'}, {'TeamNum': 18735, 'OPR': 24.624, 'Auto': 7.544, 'CCWM': -16.188, 'TeamName': 'RinGoStar'}, {'TeamNum': 22764, 'OPR': 24.448, 'Auto': 9.16, 'CCWM': -65.575, 'TeamName': 'BAGHEERA'}, {'TeamNum': 17056, 'OPR': 17.678, 'Auto': -4.515, 'CCWM': -37.683, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 17182, 'OPR': 16.916, 'Auto': 0.403, 'CCWM': -45.439, 'TeamName': 'Red Mask'}, {'TeamNum': 12817, 'OPR': 16.434, 'Auto': 3.64, 'CCWM': -21.102, 'TeamName': 'Everest'}, {'TeamNum': 21796, 'OPR': 13.475, 'Auto': 3.042, 'CCWM': -37.461, 'TeamName': 'ECLIPSE'}, {'TeamNum': 19000, 'OPR': 11.519, 'Auto': -1.155, 'CCWM': -36.46, 'TeamName': 'Everglow'}, {'TeamNum': 22644, 'OPR': 9.245, 'Auto': -1.744, 'CCWM': -31.691, 'TeamName': 'RayLadies'}, {'TeamNum': 22681, 'OPR': 4.29, 'Auto': -2.939, 'CCWM': -28.952, 'TeamName': 'Amal Space  and Aviation Maale Adumim the Kings'}, {'TeamNum': 11635, 'OPR': 4.06, 'Auto': -4.129, 'CCWM': -58.618, 'TeamName': 'Quack Attack'}, {'TeamNum': 18268, 'OPR': -14.362, 'Auto': -3.28, 'CCWM': -83.477, 'TeamName': 'SYCATECH'}]
ILSHS3
[{'TeamNum': 14029, 'OPR': 128.332, 'Auto': 19.014, 'CCWM': 112.214, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 11192, 'OPR': 87.254, 'Auto': 10.055, 'CCWM': 52.871, 'TeamName': 'Black Tigers'}, {'TeamNum': 16473, 'OPR': 78.602, 'Auto': 14.726, 'CCWM': 60.854, 'TeamName': 'SciFighters'}, {'TeamNum': 12797, 'OPR': 74.006, 'Auto': 16.399, 'CCWM': 14.162, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 11808, 'OPR': 72.617, 'Auto': 6.882, 'CCWM': 46.189, 'TeamName': 'Connection'}, {'TeamNum': 12201, 'OPR': 64.169, 'Auto': 18.367, 'CCWM': 27.054, 'TeamName': 'TATOOINE'}, {'TeamNum': 14028, 'OPR': 64.145, 'Auto': 11.139, 'CCWM': 12.989, 'TeamName': 'Orbit 10'}, {'TeamNum': 13146, 'OPR': 63.538, 'Auto': 10.373, 'CCWM': 1.37, 'TeamName': 'Makers Assemble'}, {'TeamNum': 14872, 'OPR': 61.388, 'Auto': 2.05, 'CCWM': 39.927, 'TeamName': 'Orbit 9'}, {'TeamNum': 15298, 'OPR': 59.043, 'Auto': 13.392, 'CCWM': 31.662, 'TeamName': 'RoboTen'}, {'TeamNum': 21957, 'OPR': 53.356, 'Auto': 20.248, 'CCWM': -1.309, 'TeamName': 'Goblin Mode'}, {'TeamNum': 13452, 'OPR': 53.091, 'Auto': 2.076, 'CCWM': 9.592, 'TeamName': 'BTJ'}, {'TeamNum': 17019, 'OPR': 51.458, 'Auto': 1.995, 'CCWM': 8.595, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 15141, 'OPR': 50.62, 'Auto': 1.416, 'CCWM': 29.43, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 22734, 'OPR': 50.608, 'Auto': 0.817, 'CCWM': 17.988, 'TeamName': 'Jotunheim '}, {'TeamNum': 18833, 'OPR': 47.106, 'Auto': 20.066, 'CCWM': -1.824, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 11443, 'OPR': 44.805, 'Auto': -0.436, 'CCWM': 3.845, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 11567, 'OPR': 38.869, 'Auto': 15.057, 'CCWM': 0.219, 'TeamName': 'Supernova'}, {'TeamNum': 19967, 'OPR': 33.37, 'Auto': 3.198, 'CCWM': -33.11, 'TeamName': 'AIS Talons'}, {'TeamNum': 11226, 'OPR': 32.805, 'Auto': 4.612, 'CCWM': 37.835, 'TeamName': 'Black Thunder'}, {'TeamNum': 17106, 'OPR': 29.226, 'Auto': 11.989, 'CCWM': 6.18, 'TeamName': 'PlanTech'}, {'TeamNum': 9662, 'OPR': 28.049, 'Auto': 8.298, 'CCWM': -32.19, 'TeamName': 'Apollo'}, {'TeamNum': 18735, 'OPR': 24.624, 'Auto': 7.544, 'CCWM': -16.188, 'TeamName': 'RinGoStar'}, {'TeamNum': 22764, 'OPR': 24.448, 'Auto': 9.16, 'CCWM': -65.575, 'TeamName': 'BAGHEERA'}, {'TeamNum': 17056, 'OPR': 17.678, 'Auto': -4.515, 'CCWM': -37.683, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 17182, 'OPR': 16.916, 'Auto': 0.403, 'CCWM': -45.439, 'TeamName': 'Red Mask'}, {'TeamNum': 12817, 'OPR': 16.434, 'Auto': 3.64, 'CCWM': -21.102, 'TeamName': 'Everest'}, {'TeamNum': 21796, 'OPR': 13.475, 'Auto': 3.042, 'CCWM': -37.461, 'TeamName': 'ECLIPSE'}, {'TeamNum': 19000, 'OPR': 11.519, 'Auto': -1.155, 'CCWM': -36.46, 'TeamName': 'Everglow'}, {'TeamNum': 22644, 'OPR': 9.245, 'Auto': -1.744, 'CCWM': -31.691, 'TeamName': 'RayLadies'}, {'TeamNum': 22681, 'OPR': 4.29, 'Auto': -2.939, 'CCWM': -28.952, 'TeamName': 'Amal Space  and Aviation Maale Adumim the Kings'}, {'TeamNum': 11635, 'OPR': 4.06, 'Auto': -4.129, 'CCWM': -58.618, 'TeamName': 'Quack Attack'}, {'TeamNum': 18268, 'OPR': -14.362, 'Auto': -3.28, 'CCWM': -83.477, 'TeamName': 'SYCATECH'}]

i 915
i 916
i 917
{'11347', '12611', '11542', '6417', '20979', '12518', '21394', '19587', '1002', '14491', '18664', '11161', '21229', '21232', '7842'}
[{'TeamNum': 1002, 'OPR': 116.931, 'Auto': 33.274, 'CCWM': 80.19, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 12611, 'OPR': 92.315, 'Auto': 28.164, 'CCWM': 40.617, 'TeamName': 'TechNova'}, {'TeamNum': 14491, 'OPR': 84.005, 'Auto': 24.759, 'CCWM': 37.713, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 21232, 'OPR': 65.079, 'Auto': 1.158, 'CCWM': -2.498, 'TeamName': 'no team'}, {'TeamNum': 6417, 'OPR': 53.839, 'Auto': 15.493, 'CCWM': 8.15, 'TeamName': 'Blu Cru'}, {'TeamNum': 7842, 'OPR': 50.953, 'Auto': 16.518, 'CCWM': 14.869, 'TeamName': 'Browncoats'}, {'TeamNum': 11347, 'OPR': 46.822, 'Auto': 3.312, 'CCWM': -8.612, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 21394, 'OPR': 46.121, 'Auto': 23.505, 'CCWM': 0.555, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 11542, 'OPR': 43.001, 'Auto': 12.281, 'CCWM': 6.301, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 18664, 'OPR': 36.473, 'Auto': 0.179, 'CCWM': -15.771, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 11161, 'OPR': 35.057, 'Auto': -0.113, 'CCWM': 3.088, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 19587, 'OPR': 34.115, 'Auto': 13.27, 'CCWM': -12.904, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 21229, 'OPR': 20.81, 'Auto': 1.578, 'CCWM': -44.793, 'TeamName': 'Quality Control'}, {'TeamNum': 12518, 'OPR': 8.743, 'Auto': -1.692, 'CCWM': -38.293, 'TeamName': 'Almond Robotics'}, {'TeamNum': 20979, 'OPR': 3.771, 'Auto': 2.799, 'CCWM': -59.65, 'TeamName': 'Redstone Robotics'}]
USALHUS3
[{'TeamNum': 1002, 'OPR': 116.931, 'Auto': 33.274, 'CCWM': 80.19, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 12611, 'OPR': 92.315, 'Auto': 28.164, 'CCWM': 40.617, 'TeamName': 'TechNova'}, {'TeamNum': 14491, 'OPR': 84.005, 'Auto': 24.759, 'CCWM': 37.713, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 21232, 'OPR': 65.079, 'Auto': 1.158, 'CCWM': -2.498, 'TeamName': 'no team'}, {'TeamNum': 6417, 'OPR': 53.839, 'Auto': 15.493, 'CCWM': 8.15, 'TeamName': 'Blu Cru'}, {'TeamNum': 7842, 'OPR': 50.953, 'Auto': 16.518, 'CCWM': 14.869, 'TeamName': 'Browncoats'}, {'TeamNum': 11347, 'OPR': 46.822, 'Auto': 3.312, 'CCWM': -8.612, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 21394, 'OPR': 46.121, 'Auto': 23.505, 'CCWM': 0.555, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 11542, 'OPR': 43.001, 'Auto': 12.281, 'CCWM': 6.301, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 18664, 'OPR': 36.473, 'Auto': 0.179, 'CCWM': -15.771, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 11161, 'OPR': 35.057, 'Auto': -0.113, 'CCWM': 3.088, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 19587, 'OPR': 34.115, 'Auto': 13.27, 'CCWM': -12.904, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 21229, 'OPR': 20.81, 'Auto': 1.578, 'CCWM': -44.793, 'TeamName': 'Quality Control'}, {'TeamNum': 12518, 'OPR': 8.743, 'Auto': -1.692, 'CCWM': -38.293, 'TeamName': 'Almond Robotics'}, {'TeamNum': 20979, 'OPR': 3.771, 'Auto': 2.799, 'CCWM': -59.65, 'TeamName': 'Redstone Robotics'}]
i 918
{'2844', '11794', '14254', '18538', '22265', '10984', '15461', '7156', '6174', '9743', '20679', '14855', '18625', '12841', '202', '18291', '16647', '17460', '22076', '5661', '201', '12889', '8499', '9695', '22821', '11365', '10523'}
[{'TeamNum': 18625, 'OPR': 89.08, 'Auto': 25.775, 'CCWM': 53.27, 'TeamName': 'Trivium Knightmares'}, {'TeamNum': 12841, 'OPR': 71.068, 'Auto': 14.527, 'CCWM': 34.174, 'TeamName': 'Plus +3 Robotics'}, {'TeamNum': 11794, 'OPR': 62.014, 'Auto': 6.163, 'CCWM': 53.185, 'TeamName': 'Sunrise Koolbotics'}, {'TeamNum': 10523, 'OPR': 61.715, 'Auto': 2.784, 'CCWM': -3.58, 'TeamName': 'Dragons'}, {'TeamNum': 18291, 'OPR': 58.274, 'Auto': 21.369, 'CCWM': 37.639, 'TeamName': 'Mech Warriors'}, {'TeamNum': 202, 'OPR': 51.051, 'Auto': 11.472, 'CCWM': 13.278, 'TeamName': 'BroncoBotsTOO'}, {'TeamNum': 17460, 'OPR': 48.428, 'Auto': 7.482, 'CCWM': 26.945, 'TeamName': 'Technical Terrors'}, {'TeamNum': 10984, 'OPR': 47.972, 'Auto': 0.822, 'CCWM': 1.708, 'TeamName': 'Beep Patrol'}, {'TeamNum': 20679, 'OPR': 46.96, 'Auto': 9.29, 'CCWM': 23.711, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 15461, 'OPR': 45.518, 'Auto': 21.222, 'CCWM': 21.699, 'TeamName': 'Nutz and Bolts'}, {'TeamNum': 2844, 'OPR': 45.107, 'Auto': 18.787, 'CCWM': 18.56, 'TeamName': 'Valley X Robotics'}, {'TeamNum': 6174, 'OPR': 44.233, 'Auto': 17.436, 'CCWM': 7.517, 'TeamName': 'Automatons'}, {'TeamNum': 14254, 'OPR': 42.805, 'Auto': 16.431, 'CCWM': -3.075, 'TeamName': 'Trivium Knight Lights'}, {'TeamNum': 12889, 'OPR': 39.931, 'Auto': 14.444, 'CCWM': 15.436, 'TeamName': 'Wyverns'}, {'TeamNum': 22076, 'OPR': 33.478, 'Auto': 2.782, 'CCWM': -22.806, 'TeamName': 'Unknown Robotics'}, {'TeamNum': 201, 'OPR': 29.166, 'Auto': 2.17, 'CCWM': -17.357, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 7156, 'OPR': 28.081, 'Auto': 9.802, 'CCWM': 16.626, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 16647, 'OPR': 23.193, 'Auto': 12.314, 'CCWM': -30.956, 'TeamName': 'Trivium Undefined'}, {'TeamNum': 5661, 'OPR': 21.687, 'Auto': -5.934, 'CCWM': -12.924, 'TeamName': 'Wolves Robotics 1'}, {'TeamNum': 8499, 'OPR': 21.336, 'Auto': 2.431, 'CCWM': -19.293, 'TeamName': 'Robo Hawks'}, {'TeamNum': 9743, 'OPR': 19.414, 'Auto': 5.748, 'CCWM': -21.263, 'TeamName': 'Stinger Robotics'}, {'TeamNum': 14855, 'OPR': 16.644, 'Auto': 9.531, 'CCWM': -14.837, 'TeamName': 'Shamrocks'}, {'TeamNum': 22265, 'OPR': 13.761, 'Auto': 4.33, 'CCWM': -34.413, 'TeamName': 'Gear Hounds'}, {'TeamNum': 22821, 'OPR': 13.136, 'Auto': -4.91, 'CCWM': -41.49, 'TeamName': 'BlackHawks'}, {'TeamNum': 9695, 'OPR': 12.255, 'Auto': 4.685, 'CCWM': -37.428, 'TeamName': 'BCHS Electric Eagles'}, {'TeamNum': 11365, 'OPR': 9.296, 'Auto': -0.83, 'CCWM': -59.622, 'TeamName': 'Ticket To Paradise'}, {'TeamNum': 18538, 'OPR': 6.781, 'Auto': 0.172, 'CCWM': -11.537, 'TeamName': 'BASIS Java Beans'}]
USAZWAQ
[{'TeamNum': 18625, 'OPR': 89.08, 'Auto': 25.775, 'CCWM': 53.27, 'TeamName': 'Trivium Knightmares'}, {'TeamNum': 12841, 'OPR': 71.068, 'Auto': 14.527, 'CCWM': 34.174, 'TeamName': 'Plus +3 Robotics'}, {'TeamNum': 11794, 'OPR': 62.014, 'Auto': 6.163, 'CCWM': 53.185, 'TeamName': 'Sunrise Koolbotics'}, {'TeamNum': 10523, 'OPR': 61.715, 'Auto': 2.784, 'CCWM': -3.58, 'TeamName': 'Dragons'}, {'TeamNum': 18291, 'OPR': 58.274, 'Auto': 21.369, 'CCWM': 37.639, 'TeamName': 'Mech Warriors'}, {'TeamNum': 202, 'OPR': 51.051, 'Auto': 11.472, 'CCWM': 13.278, 'TeamName': 'BroncoBotsTOO'}, {'TeamNum': 17460, 'OPR': 48.428, 'Auto': 7.482, 'CCWM': 26.945, 'TeamName': 'Technical Terrors'}, {'TeamNum': 10984, 'OPR': 47.972, 'Auto': 0.822, 'CCWM': 1.708, 'TeamName': 'Beep Patrol'}, {'TeamNum': 20679, 'OPR': 46.96, 'Auto': 9.29, 'CCWM': 23.711, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 15461, 'OPR': 45.518, 'Auto': 21.222, 'CCWM': 21.699, 'TeamName': 'Nutz and Bolts'}, {'TeamNum': 2844, 'OPR': 45.107, 'Auto': 18.787, 'CCWM': 18.56, 'TeamName': 'Valley X Robotics'}, {'TeamNum': 6174, 'OPR': 44.233, 'Auto': 17.436, 'CCWM': 7.517, 'TeamName': 'Automatons'}, {'TeamNum': 14254, 'OPR': 42.805, 'Auto': 16.431, 'CCWM': -3.075, 'TeamName': 'Trivium Knight Lights'}, {'TeamNum': 12889, 'OPR': 39.931, 'Auto': 14.444, 'CCWM': 15.436, 'TeamName': 'Wyverns'}, {'TeamNum': 22076, 'OPR': 33.478, 'Auto': 2.782, 'CCWM': -22.806, 'TeamName': 'Unknown Robotics'}, {'TeamNum': 201, 'OPR': 29.166, 'Auto': 2.17, 'CCWM': -17.357, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 7156, 'OPR': 28.081, 'Auto': 9.802, 'CCWM': 16.626, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 16647, 'OPR': 23.193, 'Auto': 12.314, 'CCWM': -30.956, 'TeamName': 'Trivium Undefined'}, {'TeamNum': 5661, 'OPR': 21.687, 'Auto': -5.934, 'CCWM': -12.924, 'TeamName': 'Wolves Robotics 1'}, {'TeamNum': 8499, 'OPR': 21.336, 'Auto': 2.431, 'CCWM': -19.293, 'TeamName': 'Robo Hawks'}, {'TeamNum': 9743, 'OPR': 19.414, 'Auto': 5.748, 'CCWM': -21.263, 'TeamName': 'Stinger Robotics'}, {'TeamNum': 14855, 'OPR': 16.644, 'Auto': 9.531, 'CCWM': -14.837, 'TeamName': 'Shamrocks'}, {'TeamNum': 22265, 'OPR': 13.761, 'Auto': 4.33, 'CCWM': -34.413, 'TeamName': 'Gear Hounds'}, {'TeamNum': 22821, 'OPR': 13.136, 'Auto': -4.91, 'CCWM': -41.49, 'TeamName': 'BlackHawks'}, {'TeamNum': 9695, 'OPR': 12.255, 'Auto': 4.685, 'CCWM': -37.428, 'TeamName': 'BCHS Electric Eagles'}, {'TeamNum': 11365, 'OPR': 9.296, 'Auto': -0.83, 'CCWM': -59.622, 'TeamName': 'Ticket To Paradise'}, {'TeamNum': 18538, 'OPR': 6.781, 'Auto': 0.172, 'CCWM': -11.537, 'TeamName': 'BASIS Java Beans'}]

i 919
{'21980', '20331', '13303', '14996', '22898', '19510', '22669', '20353', '21990', '13277', '9433', '5828', '14377', '9040', '19516', '22343', '22670', '13171', '15305', '20360', '21982', '12765', '14295', '7835', '9432', '17600', '19812', '18882'}
[{'TeamNum': 21980, 'OPR': 106.04, 'Auto': 24.629, 'CCWM': 62.838, 'TeamName': 'Bread Pandas'}, {'TeamNum': 14996, 'OPR': 103.412, 'Auto': 23.586, 'CCWM': 74.566, 'TeamName': 'Omega Squad'}, {'TeamNum': 20331, 'OPR': 89.962, 'Auto': 20.103, 'CCWM': 40.797, 'TeamName': 'BISON BOTS'}, {'TeamNum': 14295, 'OPR': 80.648, 'Auto': 15.999, 'CCWM': 43.45, 'TeamName': 'Operation T.A.C.'}, {'TeamNum': 13171, 'OPR': 77.611, 'Auto': 12.92, 'CCWM': 3.823, 'TeamName': 'Polyisoprene Mallards'}, {'TeamNum': 17600, 'OPR': 70.506, 'Auto': 14.265, 'CCWM': 20.702, 'TeamName': 'MoVal Robotics'}, {'TeamNum': 9433, 'OPR': 67.71, 'Auto': 18.827, 'CCWM': 18.323, 'TeamName': 'Twisted Metal'}, {'TeamNum': 9432, 'OPR': 64.992, 'Auto': 15.9, 'CCWM': 23.072, 'TeamName': 'Bloo'}, {'TeamNum': 21982, 'OPR': 62.863, 'Auto': 10.912, 'CCWM': -7.255, 'TeamName': 'Inkineers'}, {'TeamNum': 19516, 'OPR': 62.735, 'Auto': 14.446, 'CCWM': 14.932, 'TeamName': 'The Huskyteers'}, {'TeamNum': 15305, 'OPR': 62.552, 'Auto': 17.679, 'CCWM': 35.879, 'TeamName': 'Cerritos Dons'}, {'TeamNum': 19510, 'OPR': 58.259, 'Auto': 7.645, 'CCWM': 27.781, 'TeamName': 'VolTech'}, {'TeamNum': 20360, 'OPR': 52.973, 'Auto': 7.578, 'CCWM': 1.817, 'TeamName': 'The Sus Bois'}, {'TeamNum': 18882, 'OPR': 49.957, 'Auto': 20.924, 'CCWM': -13.855, 'TeamName': 'Mater Dei Minions'}, {'TeamNum': 12765, 'OPR': 44.314, 'Auto': 3.916, 'CCWM': -20.867, 'TeamName': 'Phoenix'}, {'TeamNum': 9040, 'OPR': 44.257, 'Auto': 11.657, 'CCWM': 35.978, 'TeamName': 'STEAMpunks Alpha'}, {'TeamNum': 22670, 'OPR': 35.301, 'Auto': 5.194, 'CCWM': -5.234, 'TeamName': 'RoboAntics'}, {'TeamNum': 13277, 'OPR': 35.25, 'Auto': 4.75, 'CCWM': -3.492, 'TeamName': 'STEAMpunks Bravo'}, {'TeamNum': 20353, 'OPR': 32.893, 'Auto': 19.478, 'CCWM': -15.361, 'TeamName': 'LIBERTY & JUSTICE'}, {'TeamNum': 21990, 'OPR': 31.332, 'Auto': 6.168, 'CCWM': -39.016, 'TeamName': 'Roots Robotics'}, {'TeamNum': 14377, 'OPR': 31.29, 'Auto': 8.051, 'CCWM': 16.773, 'TeamName': 'RoboPanthers'}, {'TeamNum': 19812, 'OPR': 29.382, 'Auto': 14.728, 'CCWM': -25.49, 'TeamName': 'Quantum Leap'}, {'TeamNum': 13303, 'OPR': 25.341, 'Auto': 5.044, 'CCWM': -14.336, 'TeamName': 'SMES Robotics'}, {'TeamNum': 5828, 'OPR': 20.963, 'Auto': 0.797, 'CCWM': -52.589, 'TeamName': 'E.M.P. Chaos'}, {'TeamNum': 22898, 'OPR': 12.686, 'Auto': -1.702, 'CCWM': -56.223, 'TeamName': 'reVisionaries '}, {'TeamNum': 22343, 'OPR': 8.968, 'Auto': 7.175, 'CCWM': -24.392, 'TeamName': 'MONSTERA'}, {'TeamNum': 22669, 'OPR': 5.76, 'Auto': 1.835, 'CCWM': -60.046, 'TeamName': 'Stella-Fonix'}, {'TeamNum': 7835, 'OPR': -9.354, 'Auto': -9.505, 'CCWM': -82.575, 'TeamName': 'VEXX'}]
USCALAROQ1
[{'TeamNum': 21980, 'OPR': 106.04, 'Auto': 24.629, 'CCWM': 62.838, 'TeamName': 'Bread Pandas'}, {'TeamNum': 14996, 'OPR': 103.412, 'Auto': 23.586, 'CCWM': 74.566, 'TeamName': 'Omega Squad'}, {'TeamNum': 20331, 'OPR': 89.962, 'Auto': 20.103, 'CCWM': 40.797, 'TeamName': 'BISON BOTS'}, {'TeamNum': 14295, 'OPR': 80.648, 'Auto': 15.999, 'CCWM': 43.45, 'TeamName': 'Operation T.A.C.'}, {'TeamNum': 13171, 'OPR': 77.611, 'Auto': 12.92, 'CCWM': 3.823, 'TeamName': 'Polyisoprene Mallards'}, {'TeamNum': 17600, 'OPR': 70.506, 'Auto': 14.265, 'CCWM': 20.702, 'TeamName': 'MoVal Robotics'}, {'TeamNum': 9433, 'OPR': 67.71, 'Auto': 18.827, 'CCWM': 18.323, 'TeamName': 'Twisted Metal'}, {'TeamNum': 9432, 'OPR': 64.992, 'Auto': 15.9, 'CCWM': 23.072, 'TeamName': 'Bloo'}, {'TeamNum': 21982, 'OPR': 62.863, 'Auto': 10.912, 'CCWM': -7.255, 'TeamName': 'Inkineers'}, {'TeamNum': 19516, 'OPR': 62.735, 'Auto': 14.446, 'CCWM': 14.932, 'TeamName': 'The Huskyteers'}, {'TeamNum': 15305, 'OPR': 62.552, 'Auto': 17.679, 'CCWM': 35.879, 'TeamName': 'Cerritos Dons'}, {'TeamNum': 19510, 'OPR': 58.259, 'Auto': 7.645, 'CCWM': 27.781, 'TeamName': 'VolTech'}, {'TeamNum': 20360, 'OPR': 52.973, 'Auto': 7.578, 'CCWM': 1.817, 'TeamName': 'The Sus Bois'}, {'TeamNum': 18882, 'OPR': 49.957, 'Auto': 20.924, 'CCWM': -13.855, 'TeamName': 'Mater Dei Minions'}, {'TeamNum': 12765, 'OPR': 44.314, 'Auto': 3.916, 'CCWM': -20.867, 'TeamName': 'Phoenix'}, {'TeamNum': 9040, 'OPR': 44.257, 'Auto': 11.657, 'CCWM': 35.978, 'TeamName': 'STEAMpunks Alpha'}, {'TeamNum': 22670, 'OPR': 35.301, 'Auto': 5.194, 'CCWM': -5.234, 'TeamName': 'RoboAntics'}, {'TeamNum': 13277, 'OPR': 35.25, 'Auto': 4.75, 'CCWM': -3.492, 'TeamName': 'STEAMpunks Bravo'}, {'TeamNum': 20353, 'OPR': 32.893, 'Auto': 19.478, 'CCWM': -15.361, 'TeamName': 'LIBERTY & JUSTICE'}, {'TeamNum': 21990, 'OPR': 31.332, 'Auto': 6.168, 'CCWM': -39.016, 'TeamName': 'Roots Robotics'}, {'TeamNum': 14377, 'OPR': 31.29, 'Auto': 8.051, 'CCWM': 16.773, 'TeamName': 'RoboPanthers'}, {'TeamNum': 19812, 'OPR': 29.382, 'Auto': 14.728, 'CCWM': -25.49, 'TeamName': 'Quantum Leap'}, {'TeamNum': 13303, 'OPR': 25.341, 'Auto': 5.044, 'CCWM': -14.336, 'TeamName': 'SMES Robotics'}, {'TeamNum': 5828, 'OPR': 20.963, 'Auto': 0.797, 'CCWM': -52.589, 'TeamName': 'E.M.P. Chaos'}, {'TeamNum': 22898, 'OPR': 12.686, 'Auto': -1.702, 'CCWM': -56.223, 'TeamName': 'reVisionaries '}, {'TeamNum': 22343, 'OPR': 8.968, 'Auto': 7.175, 'CCWM': -24.392, 'TeamName': 'MONSTERA'}, {'TeamNum': 22669, 'OPR': 5.76, 'Auto': 1.835, 'CCWM': -60.046, 'TeamName': 'Stella-Fonix'}, {'TeamNum': 7835, 'OPR': -9.354, 'Auto': -9.505, 'CCWM': -82.575, 'TeamName': 'VEXX'}]
i 920
{'16283', '21419', '16276', '21376', '18247', '21626', '15453', '21666', '13050', '22079', '22943', '16688', '21663', '22330', '21979', '21516'}
[{'TeamNum': 22330, 'OPR': 60.626, 'Auto': 14.005, 'CCWM': 37.793, 'TeamName': 'Monkê'}, {'TeamNum': 15453, 'OPR': 60.604, 'Auto': 8.574, 'CCWM': 27.077, 'TeamName': 'RaiderBots'}, {'TeamNum': 16283, 'OPR': 60.289, 'Auto': -1.524, 'CCWM': 50.775, 'TeamName': 'Milk'}, {'TeamNum': 21516, 'OPR': 50.187, 'Auto': 19.46, 'CCWM': -10.384, 'TeamName': 'RoboTitans'}, {'TeamNum': 21376, 'OPR': 48.04, 'Auto': 2.165, 'CCWM': 35.837, 'TeamName': 'BOOM SHAKA LAKA'}, {'TeamNum': 16276, 'OPR': 47.004, 'Auto': 4.079, 'CCWM': 17.689, 'TeamName': 'Fard Odor Company'}, {'TeamNum': 18247, 'OPR': 46.435, 'Auto': 3.848, 'CCWM': 0.072, 'TeamName': 'Build-A-Bot'}, {'TeamNum': 21626, 'OPR': 39.585, 'Auto': 16.071, 'CCWM': -16.243, 'TeamName': 'Sparkle Botz'}, {'TeamNum': 16688, 'OPR': 30.68, 'Auto': 3.428, 'CCWM': -11.338, 'TeamName': 'Wolfbotics'}, {'TeamNum': 22943, 'OPR': 27.049, 'Auto': -1.065, 'CCWM': -3.492, 'TeamName': 'The Robonks'}, {'TeamNum': 22079, 'OPR': 23.059, 'Auto': -2.745, 'CCWM': -2.705, 'TeamName': 'Cyclone'}, {'TeamNum': 21979, 'OPR': 20.611, 'Auto': -4.095, 'CCWM': -18.253, 'TeamName': 'Cobratics'}, {'TeamNum': 21666, 'OPR': 17.114, 'Auto': 0.328, 'CCWM': -25.276, 'TeamName': 'HD1_Canis_Hopkins'}, {'TeamNum': 21663, 'OPR': 13.615, 'Auto': 3.285, 'CCWM': -6.008, 'TeamName': 'WALL-E'}, {'TeamNum': 21419, 'OPR': 9.489, 'Auto': 5.378, 'CCWM': -19.903, 'TeamName': 'Power Rangers'}, {'TeamNum': 13050, 'OPR': -2.987, 'Auto': 1.607, 'CCWM': -55.641, 'TeamName': 'SharkBytes'}]
USCANOSJQ
[{'TeamNum': 22330, 'OPR': 60.626, 'Auto': 14.005, 'CCWM': 37.793, 'TeamName': 'Monkê'}, {'TeamNum': 15453, 'OPR': 60.604, 'Auto': 8.574, 'CCWM': 27.077, 'TeamName': 'RaiderBots'}, {'TeamNum': 16283, 'OPR': 60.289, 'Auto': -1.524, 'CCWM': 50.775, 'TeamName': 'Milk'}, {'TeamNum': 21516, 'OPR': 50.187, 'Auto': 19.46, 'CCWM': -10.384, 'TeamName': 'RoboTitans'}, {'TeamNum': 21376, 'OPR': 48.04, 'Auto': 2.165, 'CCWM': 35.837, 'TeamName': 'BOOM SHAKA LAKA'}, {'TeamNum': 16276, 'OPR': 47.004, 'Auto': 4.079, 'CCWM': 17.689, 'TeamName': 'Fard Odor Company'}, {'TeamNum': 18247, 'OPR': 46.435, 'Auto': 3.848, 'CCWM': 0.072, 'TeamName': 'Build-A-Bot'}, {'TeamNum': 21626, 'OPR': 39.585, 'Auto': 16.071, 'CCWM': -16.243, 'TeamName': 'Sparkle Botz'}, {'TeamNum': 16688, 'OPR': 30.68, 'Auto': 3.428, 'CCWM': -11.338, 'TeamName': 'Wolfbotics'}, {'TeamNum': 22943, 'OPR': 27.049, 'Auto': -1.065, 'CCWM': -3.492, 'TeamName': 'The Robonks'}, {'TeamNum': 22079, 'OPR': 23.059, 'Auto': -2.745, 'CCWM': -2.705, 'TeamName': 'Cyclone'}, {'TeamNum': 21979, 'OPR': 20.611, 'Auto': -4.095, 'CCWM': -18.253, 'TeamName': 'Cobratics'}, {'TeamNum': 21666, 'OPR': 17.114, 'Auto': 0.328, 'CCWM': -25.276, 'TeamName': 'HD1_Canis_Hopkins'}, {'TeamNum': 21663, 'OPR': 13.615, 'Auto': 3.285, 'CCWM': -6.008, 'TeamName': 'WALL-E'}, {'TeamNum': 21419, 'OPR': 9.489, 'Auto': 5.378, 'CCWM': -19.903, 'TeamName': 'Power Rangers'}, {'TeamNum': 13050, 'OPR': -2.987, 'Auto': 1.607, 'CCWM': -55.641, 'TeamName': 'SharkBytes'}]
i 921

{'7834', '9887', '19198', '7460', '8039', '8472', '14863', '22813', '22675', '16795', '22342', '9220', '18395', '22082', '16326', '22676', '21936', '22533', '22030', '16321', '6371', '20799', '6373', '22031', '22740', '18819', '22472', '6372'}
[{'TeamNum': 21936, 'OPR': 113.66, 'Auto': 31.399, 'CCWM': 88.943, 'TeamName': 'SaMoTech'}, {'TeamNum': 16321, 'OPR': 92.172, 'Auto': 13.386, 'CCWM': 52.074, 'TeamName': 'X Drive'}, {'TeamNum': 9887, 'OPR': 79.024, 'Auto': 22.731, 'CCWM': 48.614, 'TeamName': 'CyberDragons Marvinette'}, {'TeamNum': 22472, 'OPR': 70.755, 'Auto': 26.234, 'CCWM': 30.662, 'TeamName': 'Mighty Bugs'}, {'TeamNum': 7460, 'OPR': 67.675, 'Auto': 20.037, 'CCWM': 45.129, 'TeamName': 'Thunder'}, {'TeamNum': 22740, 'OPR': 66.444, 'Auto': 30.353, 'CCWM': 25.055, 'TeamName': 'Bot Bot'}, {'TeamNum': 6373, 'OPR': 62.44, 'Auto': 8.455, 'CCWM': 33.938, 'TeamName': 'SuperBots'}, {'TeamNum': 19198, 'OPR': 51.724, 'Auto': 16.878, 'CCWM': -4.982, 'TeamName': 'Roborunners'}, {'TeamNum': 22342, 'OPR': 51.129, 'Auto': 9.279, 'CCWM': -2.086, 'TeamName': 'STAMPEDE MACHINES'}, {'TeamNum': 22030, 'OPR': 50.821, 'Auto': 14.139, 'CCWM': -23.466, 'TeamName': 'RobTot'}, {'TeamNum': 14863, 'OPR': 46.728, 'Auto': 14.179, 'CCWM': -11.757, 'TeamName': 'RGB'}, {'TeamNum': 22082, 'OPR': 45.352, 'Auto': 7.087, 'CCWM': 16.603, 'TeamName': 'Ziptide'}, {'TeamNum': 22533, 'OPR': 44.756, 'Auto': 11.735, 'CCWM': 4.838, 'TeamName': 'Crossroads Inc.'}, {'TeamNum': 20799, 'OPR': 41.289, 'Auto': 0.368, 'CCWM': 31.412, 'TeamName': 'CyberDragons King Bob'}, {'TeamNum': 16795, 'OPR': 40.357, 'Auto': 0.733, 'CCWM': -0.271, 'TeamName': 'Galaxy'}, {'TeamNum': 18819, 'OPR': 39.438, 'Auto': 11.585, 'CCWM': 6.669, 'TeamName': 'T-Bird TECH'}, {'TeamNum': 16326, 'OPR': 37.688, 'Auto': 10.985, 'CCWM': 26.934, 'TeamName': 'XBOTS'}, {'TeamNum': 22676, 'OPR': 30.893, 'Auto': 6.16, 'CCWM': -24.129, 'TeamName': 'The Creators'}, {'TeamNum': 8472, 'OPR': 30.044, 'Auto': 6.892, 'CCWM': -16.639, 'TeamName': 'Dinomite'}, {'TeamNum': 22031, 'OPR': 28.834, 'Auto': 2.164, 'CCWM': -26.265, 'TeamName': 'Spiraling Circuits'}, {'TeamNum': 22813, 'OPR': 22.641, 'Auto': 5.977, 'CCWM': -16.063, 'TeamName': 'The Kids Next Door'}, {'TeamNum': 6371, 'OPR': 22.603, 'Auto': 8.043, 'CCWM': -50.884, 'TeamName': 'Machine Kings'}, {'TeamNum': 6372, 'OPR': 15.91, 'Auto': 17.812, 'CCWM': -44.452, 'TeamName': 'Patriotic Robotics'}, {'TeamNum': 9220, 'OPR': 15.218, 'Auto': 5.467, 'CCWM': -8.15, 'TeamName': 'Rancho Rebel Robotics'}, {'TeamNum': 22675, 'OPR': 10.673, 'Auto': 4.519, 'CCWM': -37.308, 'TeamName': 'The Swifties'}, {'TeamNum': 18395, 'OPR': 7.55, 'Auto': 2.69, 'CCWM': -47.428, 'TeamName': 'Sojourner1'}, {'TeamNum': 8039, 'OPR': 2.648, 'Auto': -4.71, 'CCWM': -31.396, 'TeamName': 'Mechanical Menace'}, {'TeamNum': 7834, 'OPR': -3.066, 'Auto': -5.174, 'CCWM': -65.597, 'TeamName': 'Drastic Measures'}]
USCALAROQ2
[{'TeamNum': 21936, 'OPR': 113.66, 'Auto': 31.399, 'CCWM': 88.943, 'TeamName': 'SaMoTech'}, {'TeamNum': 16321, 'OPR': 92.172, 'Auto': 13.386, 'CCWM': 52.074, 'TeamName': 'X Drive'}, {'TeamNum': 9887, 'OPR': 79.024, 'Auto': 22.731, 'CCWM': 48.614, 'TeamName': 'CyberDragons Marvinette'}, {'TeamNum': 22472, 'OPR': 70.755, 'Auto': 26.234, 'CCWM': 30.662, 'TeamName': 'Mighty Bugs'}, {'TeamNum': 7460, 'OPR': 67.675, 'Auto': 20.037, 'CCWM': 45.129, 'TeamName': 'Thunder'}, {'TeamNum': 22740, 'OPR': 66.444, 'Auto': 30.353, 'CCWM': 25.055, 'TeamName': 'Bot Bot'}, {'TeamNum': 6373, 'OPR': 62.44, 'Auto': 8.455, 'CCWM': 33.938, 'TeamName': 'SuperBots'}, {'TeamNum': 19198, 'OPR': 51.724, 'Auto': 16.878, 'CCWM': -4.982, 'TeamName': 'Roborunners'}, {'TeamNum': 22342, 'OPR': 51.129, 'Auto': 9.279, 'CCWM': -2.086, 'TeamName': 'STAMPEDE MACHINES'}, {'TeamNum': 22030, 'OPR': 50.821, 'Auto': 14.139, 'CCWM': -23.466, 'TeamName': 'RobTot'}, {'TeamNum': 14863, 'OPR': 46.728, 'Auto': 14.179, 'CCWM': -11.757, 'TeamName': 'RGB'}, {'TeamNum': 22082, 'OPR': 45.352, 'Auto': 7.087, 'CCWM': 16.603, 'TeamName': 'Ziptide'}, {'TeamNum': 22533, 'OPR': 44.756, 'Auto': 11.735, 'CCWM': 4.838, 'TeamName': 'Crossroads Inc.'}, {'TeamNum': 20799, 'OPR': 41.289, 'Auto': 0.368, 'CCWM': 31.412, 'TeamName': 'CyberDragons King Bob'}, {'TeamNum': 16795, 'OPR': 40.357, 'Auto': 0.733, 'CCWM': -0.271, 'TeamName': 'Galaxy'}, {'TeamNum': 18819, 'OPR': 39.438, 'Auto': 11.585, 'CCWM': 6.669, 'TeamName': 'T-Bird TECH'}, {'TeamNum': 16326, 'OPR': 37.688, 'Auto': 10.985, 'CCWM': 26.934, 'TeamName': 'XBOTS'}, {'TeamNum': 22676, 'OPR': 30.893, 'Auto': 6.16, 'CCWM': -24.129, 'TeamName': 'The Creators'}, {'TeamNum': 8472, 'OPR': 30.044, 'Auto': 6.892, 'CCWM': -16.639, 'TeamName': 'Dinomite'}, {'TeamNum': 22031, 'OPR': 28.834, 'Auto': 2.164, 'CCWM': -26.265, 'TeamName': 'Spiraling Circuits'}, {'TeamNum': 22813, 'OPR': 22.641, 'Auto': 5.977, 'CCWM': -16.063, 'TeamName': 'The Kids Next Door'}, {'TeamNum': 6371, 'OPR': 22.603, 'Auto': 8.043, 'CCWM': -50.884, 'TeamName': 'Machine Kings'}, {'TeamNum': 6372, 'OPR': 15.91, 'Auto': 17.812, 'CCWM': -44.452, 'TeamName': 'Patriotic Robotics'}, {'TeamNum': 9220, 'OPR': 15.218, 'Auto': 5.467, 'CCWM': -8.15, 'TeamName': 'Rancho Rebel Robotics'}, {'TeamNum': 22675, 'OPR': 10.673, 'Auto': 4.519, 'CCWM': -37.308, 'TeamName': 'The Swifties'}, {'TeamNum': 18395, 'OPR': 7.55, 'Auto': 2.69, 'CCWM': -47.428, 'TeamName': 'Sojourner1'}, {'TeamNum': 8039, 'OPR': 2.648, 'Auto': -4.71, 'CCWM': -31.396, 'TeamName': 'Mechanical Menace'}, {'TeamNum': 7834, 'OPR': -3.066, 'Auto': -5.174, 'CCWM': -65.597, 'TeamName': 'Drastic Measures'}]
i 922
{'4345', '21366', '3791', '7593', '8381', '22177', '14969', '9784', '8375', '4475', '18233', '14417'}
[{'TeamNum': 21366, 'OPR': 104.689, 'Auto': 25.974, 'CCWM': 73.734, 'TeamName': 'Maringineers'}, {'TeamNum': 9784, 'OPR': 102.447, 'Auto': 33.748, 'CCWM': 108.964, 'TeamName': 'Dry Ice'}, {'TeamNum': 8381, 'OPR': 101.572, 'Auto': 27.651, 'CCWM': 65.113, 'TeamName': 'M'}, {'TeamNum': 14417, 'OPR': 62.715, 'Auto': 12.967, 'CCWM': 28.244, 'TeamName': 'TryHard Robotics'}, {'TeamNum': 8375, 'OPR': 60.636, 'Auto': 2.841, 'CCWM': -5.524, 'TeamName': 'Vulcan Robotics'}, {'TeamNum': 14969, 'OPR': 59.932, 'Auto': 19.716, 'CCWM': 23.948, 'TeamName': 'Vortex'}, {'TeamNum': 18233, 'OPR': 45.177, 'Auto': 15.087, 'CCWM': -38.929, 'TeamName': 'Mercy Mechs'}, {'TeamNum': 4475, 'OPR': 37.054, 'Auto': 5.18, 'CCWM': -30.731, 'TeamName': 'Purple Reign'}, {'TeamNum': 3791, 'OPR': 36.309, 'Auto': 14.052, 'CCWM': -55.377, 'TeamName': 'Ziptiez'}, {'TeamNum': 22177, 'OPR': 35.629, 'Auto': 3.999, 'CCWM': -24.56, 'TeamName': 'Janky Ducks'}, {'TeamNum': 4345, 'OPR': 31.747, 'Auto': -4.642, 'CCWM': -19.152, 'TeamName': 'Aragon Robotics'}, {'TeamNum': 7593, 'OPR': -13.707, 'Auto': -5.774, 'CCWM': -125.73, 'TeamName': 'TigerBots'}]
USCANOPNLT
[{'TeamNum': 21366, 'OPR': 104.689, 'Auto': 25.974, 'CCWM': 73.734, 'TeamName': 'Maringineers'}, {'TeamNum': 9784, 'OPR': 102.447, 'Auto': 33.748, 'CCWM': 108.964, 'TeamName': 'Dry Ice'}, {'TeamNum': 8381, 'OPR': 101.572, 'Auto': 27.651, 'CCWM': 65.113, 'TeamName': 'M'}, {'TeamNum': 14417, 'OPR': 62.715, 'Auto': 12.967, 'CCWM': 28.244, 'TeamName': 'TryHard Robotics'}, {'TeamNum': 8375, 'OPR': 60.636, 'Auto': 2.841, 'CCWM': -5.524, 'TeamName': 'Vulcan Robotics'}, {'TeamNum': 14969, 'OPR': 59.932, 'Auto': 19.716, 'CCWM': 23.948, 'TeamName': 'Vortex'}, {'TeamNum': 18233, 'OPR': 45.177, 'Auto': 15.087, 'CCWM': -38.929, 'TeamName': 'Mercy Mechs'}, {'TeamNum': 4475, 'OPR': 37.054, 'Auto': 5.18, 'CCWM': -30.731, 'TeamName': 'Purple Reign'}, {'TeamNum': 3791, 'OPR': 36.309, 'Auto': 14.052, 'CCWM': -55.377, 'TeamName': 'Ziptiez'}, {'TeamNum': 22177, 'OPR': 35.629, 'Auto': 3.999, 'CCWM': -24.56, 'TeamName': 'Janky Ducks'}, {'TeamNum': 4345, 'OPR': 31.747, 'Auto': -4.642, 'CCWM': -19.152, 'TeamName': 'Aragon Robotics'}, {'TeamNum': 7593, 'OPR': -13.707, 'Auto': -5.774, 'CCWM': -125.73, 'TeamName': 'TigerBots'}]
i 923
{'5196', '11308', '13271', '5899', '13835', '11561', '18211', '21430', '20771', '17969', '11260', '14953', '15289', '3479', '15677', '21618', '17300', '18793', '17973', '15403', '16222', '22399', '17190', '15689', '8969', '19970', '13022', '19541', '16253', '16292', '22579', '22436', '17153', '17483', '13879', '19942'}
[{'TeamNum': 11260, 'OPR': 113.384, 'Auto': 37.987, 'CCWM': 29.363, 'TeamName': 'Up-A-Creek Robotics '}, {'TeamNum': 17969, 'OPR': 108.897, 'Auto': 29.842, 'CCWM': 34.054, 'TeamName': 'MECH'}, {'TeamNum': 17483, 'OPR': 97.03, 'Auto': 17.3, 'CCWM': 72.414, 'TeamName': 'Blackout'}, {'TeamNum': 15403, 'OPR': 77.144, 'Auto': 12.262, 'CCWM': 26.255, 'TeamName': 'Vision Robotics'}, {'TeamNum': 20771, 'OPR': 69.833, 'Auto': 20.626, 'CCWM': 12.381, 'TeamName': 'Bearbotics Sigma'}, {'TeamNum': 21430, 'OPR': 61.976, 'Auto': 18.293, 'CCWM': -9.825, 'TeamName': 'BroomBots'}, {'TeamNum': 5899, 'OPR': 57.865, 'Auto': 5.613, 'CCWM': 40.001, 'TeamName': 'L.A.S.E.R.'}, {'TeamNum': 5196, 'OPR': 57.77, 'Auto': 10.385, 'CCWM': 26.874, 'TeamName': 'Robo Yetis'}, {'TeamNum': 11561, 'OPR': 56.352, 'Auto': 22.888, 'CCWM': 13.205, 'TeamName': 'The Headless Horsemen'}, {'TeamNum': 8969, 'OPR': 53.754, 'Auto': 7.499, 'CCWM': 28.831, 'TeamName': 'Custom Settings'}, {'TeamNum': 19541, 'OPR': 51.275, 'Auto': 10.349, 'CCWM': 32.674, 'TeamName': 'Bearbotics Alpha'}, {'TeamNum': 17153, 'OPR': 49.508, 'Auto': 9.991, 'CCWM': 35.828, 'TeamName': 'Squid Squad'}, {'TeamNum': 11308, 'OPR': 49.116, 'Auto': 7.146, 'CCWM': 0.512, 'TeamName': 'YISE'}, {'TeamNum': 13835, 'OPR': 48.505, 'Auto': 2.95, 'CCWM': 19.025, 'TeamName': 'Enigma'}, {'TeamNum': 17190, 'OPR': 45.987, 'Auto': 5.194, 'CCWM': 40.032, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 16253, 'OPR': 44.966, 'Auto': 6.44, 'CCWM': -4.842, 'TeamName': 'BEAST Robotics'}, {'TeamNum': 21618, 'OPR': 44.903, 'Auto': 7.471, 'CCWM': 13.008, 'TeamName': 'Circuit Breakers 4-H Robotics'}, {'TeamNum': 13022, 'OPR': 40.682, 'Auto': 10.808, 'CCWM': -3.73, 'TeamName': 'Ridgeview Hoplites'}, {'TeamNum': 15677, 'OPR': 40.114, 'Auto': 6.212, 'CCWM': -5.349, 'TeamName': 'ctrl+z'}, {'TeamNum': 19970, 'OPR': 37.966, 'Auto': 7.446, 'CCWM': -45.999, 'TeamName': 'Bearbotics Beta'}, {'TeamNum': 16222, 'OPR': 32.43, 'Auto': 3.038, 'CCWM': -11.242, 'TeamName': 'Thunderbots FTC'}, {'TeamNum': 17973, 'OPR': 31.67, 'Auto': 5.826, 'CCWM': -21.082, 'TeamName': 'Techno Trees'}, {'TeamNum': 16292, 'OPR': 26.827, 'Auto': 8.752, 'CCWM': 16.691, 'TeamName': "Mike's Dream"}, {'TeamNum': 3479, 'OPR': 26.736, 'Auto': 4.739, 'CCWM': -4.392, 'TeamName': 'Generals'}, {'TeamNum': 18793, 'OPR': 25.19, 'Auto': 0.991, 'CCWM': -27.224, 'TeamName': 'Mechanical Masters'}, {'TeamNum': 13271, 'OPR': 24.763, 'Auto': 2.952, 'CCWM': -16.703, 'TeamName': 'Cowboy Code   "Redneck Robotics"'}, {'TeamNum': 14953, 'OPR': 24.307, 'Auto': 7.943, 'CCWM': 39.025, 'TeamName': 'Ridgeview Hoplites II'}, {'TeamNum': 17300, 'OPR': 23.61, 'Auto': 12.004, 'CCWM': -13.637, 'TeamName': 'MPHS TerraMech'}, {'TeamNum': 15689, 'OPR': 19.312, 'Auto': 11.847, 'CCWM': -37.173, 'TeamName': 'Cyborg Rubber Ducks'}, {'TeamNum': 15289, 'OPR': 18.486, 'Auto': 2.126, 'CCWM': 2.26, 'TeamName': 'EGMS Gadgetron'}, {'TeamNum': 22399, 'OPR': 12.188, 'Auto': 4.951, 'CCWM': -52.307, 'TeamName': 'Cyber Samosas'}, {'TeamNum': 22579, 'OPR': 11.816, 'Auto': -1.672, 'CCWM': -64.627, 'TeamName': 'Space Alpacas'}, {'TeamNum': 19942, 'OPR': 8.03, 'Auto': 0.153, 'CCWM': -32.557, 'TeamName': 'Rusty Ducks Robotics'}, {'TeamNum': 22436, 'OPR': 7.65, 'Auto': 9.639, 'CCWM': -21.332, 'TeamName': 'Hulstrom All Stars #1'}, {'TeamNum': 18211, 'OPR': 3.602, 'Auto': 1.375, 'CCWM': -58.241, 'TeamName': 'The CMS Office Supplies'}, {'TeamNum': 13879, 'OPR': -2.844, 'Auto': -5.769, 'CCWM': -52.17, 'TeamName': 'EGMS Metal Minds'}]
USCOLIQ
[{'TeamNum': 11260, 'OPR': 113.384, 'Auto': 37.987, 'CCWM': 29.363, 'TeamName': 'Up-A-Creek Robotics '}, {'TeamNum': 17969, 'OPR': 108.897, 'Auto': 29.842, 'CCWM': 34.054, 'TeamName': 'MECH'}, {'TeamNum': 17483, 'OPR': 97.03, 'Auto': 17.3, 'CCWM': 72.414, 'TeamName': 'Blackout'}, {'TeamNum': 15403, 'OPR': 77.144, 'Auto': 12.262, 'CCWM': 26.255, 'TeamName': 'Vision Robotics'}, {'TeamNum': 20771, 'OPR': 69.833, 'Auto': 20.626, 'CCWM': 12.381, 'TeamName': 'Bearbotics Sigma'}, {'TeamNum': 21430, 'OPR': 61.976, 'Auto': 18.293, 'CCWM': -9.825, 'TeamName': 'BroomBots'}, {'TeamNum': 5899, 'OPR': 57.865, 'Auto': 5.613, 'CCWM': 40.001, 'TeamName': 'L.A.S.E.R.'}, {'TeamNum': 5196, 'OPR': 57.77, 'Auto': 10.385, 'CCWM': 26.874, 'TeamName': 'Robo Yetis'}, {'TeamNum': 11561, 'OPR': 56.352, 'Auto': 22.888, 'CCWM': 13.205, 'TeamName': 'The Headless Horsemen'}, {'TeamNum': 8969, 'OPR': 53.754, 'Auto': 7.499, 'CCWM': 28.831, 'TeamName': 'Custom Settings'}, {'TeamNum': 19541, 'OPR': 51.275, 'Auto': 10.349, 'CCWM': 32.674, 'TeamName': 'Bearbotics Alpha'}, {'TeamNum': 17153, 'OPR': 49.508, 'Auto': 9.991, 'CCWM': 35.828, 'TeamName': 'Squid Squad'}, {'TeamNum': 11308, 'OPR': 49.116, 'Auto': 7.146, 'CCWM': 0.512, 'TeamName': 'YISE'}, {'TeamNum': 13835, 'OPR': 48.505, 'Auto': 2.95, 'CCWM': 19.025, 'TeamName': 'Enigma'}, {'TeamNum': 17190, 'OPR': 45.987, 'Auto': 5.194, 'CCWM': 40.032, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 16253, 'OPR': 44.966, 'Auto': 6.44, 'CCWM': -4.842, 'TeamName': 'BEAST Robotics'}, {'TeamNum': 21618, 'OPR': 44.903, 'Auto': 7.471, 'CCWM': 13.008, 'TeamName': 'Circuit Breakers 4-H Robotics'}, {'TeamNum': 13022, 'OPR': 40.682, 'Auto': 10.808, 'CCWM': -3.73, 'TeamName': 'Ridgeview Hoplites'}, {'TeamNum': 15677, 'OPR': 40.114, 'Auto': 6.212, 'CCWM': -5.349, 'TeamName': 'ctrl+z'}, {'TeamNum': 19970, 'OPR': 37.966, 'Auto': 7.446, 'CCWM': -45.999, 'TeamName': 'Bearbotics Beta'}, {'TeamNum': 16222, 'OPR': 32.43, 'Auto': 3.038, 'CCWM': -11.242, 'TeamName': 'Thunderbots FTC'}, {'TeamNum': 17973, 'OPR': 31.67, 'Auto': 5.826, 'CCWM': -21.082, 'TeamName': 'Techno Trees'}, {'TeamNum': 16292, 'OPR': 26.827, 'Auto': 8.752, 'CCWM': 16.691, 'TeamName': "Mike's Dream"}, {'TeamNum': 3479, 'OPR': 26.736, 'Auto': 4.739, 'CCWM': -4.392, 'TeamName': 'Generals'}, {'TeamNum': 18793, 'OPR': 25.19, 'Auto': 0.991, 'CCWM': -27.224, 'TeamName': 'Mechanical Masters'}, {'TeamNum': 13271, 'OPR': 24.763, 'Auto': 2.952, 'CCWM': -16.703, 'TeamName': 'Cowboy Code   "Redneck Robotics"'}, {'TeamNum': 14953, 'OPR': 24.307, 'Auto': 7.943, 'CCWM': 39.025, 'TeamName': 'Ridgeview Hoplites II'}, {'TeamNum': 17300, 'OPR': 23.61, 'Auto': 12.004, 'CCWM': -13.637, 'TeamName': 'MPHS TerraMech'}, {'TeamNum': 15689, 'OPR': 19.312, 'Auto': 11.847, 'CCWM': -37.173, 'TeamName': 'Cyborg Rubber Ducks'}, {'TeamNum': 15289, 'OPR': 18.486, 'Auto': 2.126, 'CCWM': 2.26, 'TeamName': 'EGMS Gadgetron'}, {'TeamNum': 22399, 'OPR': 12.188, 'Auto': 4.951, 'CCWM': -52.307, 'TeamName': 'Cyber Samosas'}, {'TeamNum': 22579, 'OPR': 11.816, 'Auto': -1.672, 'CCWM': -64.627, 'TeamName': 'Space Alpacas'}, {'TeamNum': 19942, 'OPR': 8.03, 'Auto': 0.153, 'CCWM': -32.557, 'TeamName': 'Rusty Ducks Robotics'}, {'TeamNum': 22436, 'OPR': 7.65, 'Auto': 9.639, 'CCWM': -21.332, 'TeamName': 'Hulstrom All Stars #1'}, {'TeamNum': 18211, 'OPR': 3.602, 'Auto': 1.375, 'CCWM': -58.241, 'TeamName': 'The CMS Office Supplies'}, {'TeamNum': 13879, 'OPR': -2.844, 'Auto': -5.769, 'CCWM': -52.17, 'TeamName': 'EGMS Metal Minds'}]

i 924
{'10820', '22984', '130', '20301', '18978', '12377', '4774', '8699', '9650', '15668', '18221', '21503', '16008', '18843', '20189', '4286', '7034', '13965', '22803'}
[{'TeamNum': 22984, 'OPR': 76.507, 'Auto': 29.016, 'CCWM': 19.704, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 18221, 'OPR': 73.858, 'Auto': 18.503, 'CCWM': 52.308, 'TeamName': 'Meta^Infinity'}, {'TeamNum': 16008, 'OPR': 71.022, 'Auto': 20.134, 'CCWM': 41.365, 'TeamName': 'Armored Artemises'}, {'TeamNum': 130, 'OPR': 68.757, 'Auto': 8.115, 'CCWM': 30.135, 'TeamName': 'Blazing Spirits'}, {'TeamNum': 10820, 'OPR': 62.941, 'Auto': 17.127, 'CCWM': 45.732, 'TeamName': 'Cyber Dragons'}, {'TeamNum': 13965, 'OPR': 62.674, 'Auto': 14.934, 'CCWM': 45.128, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 7034, 'OPR': 61.935, 'Auto': 21.516, 'CCWM': -1.565, 'TeamName': 'Singularity Technology 7034'}, {'TeamNum': 20189, 'OPR': 55.782, 'Auto': 13.842, 'CCWM': -6.491, 'TeamName': 'Hotchkiss EFX Gearcats B'}, {'TeamNum': 4286, 'OPR': 49.89, 'Auto': -1.233, 'CCWM': -0.536, 'TeamName': 'Dragonoids'}, {'TeamNum': 12377, 'OPR': 49.638, 'Auto': 28.169, 'CCWM': -8.8, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 18843, 'OPR': 38.699, 'Auto': 12.478, 'CCWM': 11.097, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 21503, 'OPR': 38.415, 'Auto': 15.407, 'CCWM': 13.569, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 20301, 'OPR': 32.76, 'Auto': -6.039, 'CCWM': -34.661, 'TeamName': 'VIKINGBOTS'}, {'TeamNum': 8699, 'OPR': 26.273, 'Auto': 6.177, 'CCWM': -19.903, 'TeamName': 'The League of Extraordinary Roboticist '}, {'TeamNum': 9650, 'OPR': 24.264, 'Auto': 8.628, 'CCWM': -30.063, 'TeamName': 'Machine Maniacs'}, {'TeamNum': 22803, 'OPR': 23.588, 'Auto': 0.92, 'CCWM': -32.185, 'TeamName': 'WHSROBO'}, {'TeamNum': 4774, 'OPR': 23.327, 'Auto': 6.615, 'CCWM': -16.048, 'TeamName': 'Fairfield Prep JesuBots '}, {'TeamNum': 15668, 'OPR': 16.162, 'Auto': 6.318, 'CCWM': -44.398, 'TeamName': 'FullMetal Kestrels'}, {'TeamNum': 18978, 'OPR': 4.855, 'Auto': -4.461, 'CCWM': -60.409, 'TeamName': 'SemiPlatinum Penguins'}]
USCTWIQ
[{'TeamNum': 22984, 'OPR': 76.507, 'Auto': 29.016, 'CCWM': 19.704, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 18221, 'OPR': 73.858, 'Auto': 18.503, 'CCWM': 52.308, 'TeamName': 'Meta^Infinity'}, {'TeamNum': 16008, 'OPR': 71.022, 'Auto': 20.134, 'CCWM': 41.365, 'TeamName': 'Armored Artemises'}, {'TeamNum': 130, 'OPR': 68.757, 'Auto': 8.115, 'CCWM': 30.135, 'TeamName': 'Blazing Spirits'}, {'TeamNum': 10820, 'OPR': 62.941, 'Auto': 17.127, 'CCWM': 45.732, 'TeamName': 'Cyber Dragons'}, {'TeamNum': 13965, 'OPR': 62.674, 'Auto': 14.934, 'CCWM': 45.128, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 7034, 'OPR': 61.935, 'Auto': 21.516, 'CCWM': -1.565, 'TeamName': 'Singularity Technology 7034'}, {'TeamNum': 20189, 'OPR': 55.782, 'Auto': 13.842, 'CCWM': -6.491, 'TeamName': 'Hotchkiss EFX Gearcats B'}, {'TeamNum': 4286, 'OPR': 49.89, 'Auto': -1.233, 'CCWM': -0.536, 'TeamName': 'Dragonoids'}, {'TeamNum': 12377, 'OPR': 49.638, 'Auto': 28.169, 'CCWM': -8.8, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 18843, 'OPR': 38.699, 'Auto': 12.478, 'CCWM': 11.097, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 21503, 'OPR': 38.415, 'Auto': 15.407, 'CCWM': 13.569, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 20301, 'OPR': 32.76, 'Auto': -6.039, 'CCWM': -34.661, 'TeamName': 'VIKINGBOTS'}, {'TeamNum': 8699, 'OPR': 26.273, 'Auto': 6.177, 'CCWM': -19.903, 'TeamName': 'The League of Extraordinary Roboticist '}, {'TeamNum': 9650, 'OPR': 24.264, 'Auto': 8.628, 'CCWM': -30.063, 'TeamName': 'Machine Maniacs'}, {'TeamNum': 22803, 'OPR': 23.588, 'Auto': 0.92, 'CCWM': -32.185, 'TeamName': 'WHSROBO'}, {'TeamNum': 4774, 'OPR': 23.327, 'Auto': 6.615, 'CCWM': -16.048, 'TeamName': 'Fairfield Prep JesuBots '}, {'TeamNum': 15668, 'OPR': 16.162, 'Auto': 6.318, 'CCWM': -44.398, 'TeamName': 'FullMetal Kestrels'}, {'TeamNum': 18978, 'OPR': 4.855, 'Auto': -4.461, 'CCWM': -60.409, 'TeamName': 'SemiPlatinum Penguins'}]
i 925
i 926
{'18619', '13233', '21498', '5125', '6322', '450', '10022', '20022', '20723', '3888', '9110', '6321', '21922', '10366', '10130', '10830', '14431', '16759', '16333', '16724', '17156', '21882', '12731', '16484', '21382', '19786', '11204', '19441', '19442', '9987', '16391', '641', '9986', '21884', '5467'}
[{'TeamNum': 641, 'OPR': 104.143, 'Auto': 18.635, 'CCWM': 60.448, 'TeamName': 'Roboscotia'}, {'TeamNum': 16391, 'OPR': 86.45, 'Auto': 17.76, 'CCWM': 42.039, 'TeamName': 'Rising Ninjas '}, {'TeamNum': 3888, 'OPR': 84.393, 'Auto': 23.772, 'CCWM': -15.468, 'TeamName': 'Greased Lightning'}, {'TeamNum': 10130, 'OPR': 84.118, 'Auto': 17.681, 'CCWM': 8.665, 'TeamName': 'Crown Joules'}, {'TeamNum': 20022, 'OPR': 74.759, 'Auto': 8.146, 'CCWM': 7.537, 'TeamName': 'RoBOCAts'}, {'TeamNum': 16333, 'OPR': 73.54, 'Auto': 21.862, 'CCWM': 34.331, 'TeamName': 'Astrobots'}, {'TeamNum': 12731, 'OPR': 72.486, 'Auto': 27.575, 'CCWM': 6.297, 'TeamName': 'B3'}, {'TeamNum': 21922, 'OPR': 67.16, 'Auto': 14.343, 'CCWM': 17.29, 'TeamName': 'ΔΨΝΑΜΙCΣ (Dynamics)'}, {'TeamNum': 10022, 'OPR': 67.003, 'Auto': 22.044, 'CCWM': 29.439, 'TeamName': 'WiredCats Gen 3'}, {'TeamNum': 16759, 'OPR': 63.708, 'Auto': 8.733, 'CCWM': 43.683, 'TeamName': 'Wyld Stallyns UNTAMED'}, {'TeamNum': 5467, 'OPR': 54.432, 'Auto': 8.171, 'CCWM': -9.6, 'TeamName': '1.21 Gigawatts'}, {'TeamNum': 6321, 'OPR': 51.824, 'Auto': 14.647, 'CCWM': 10.006, 'TeamName': 'RoboRaiders'}, {'TeamNum': 10830, 'OPR': 51.413, 'Auto': 16.923, 'CCWM': -17.8, 'TeamName': 'AJAX'}, {'TeamNum': 21884, 'OPR': 50.825, 'Auto': 4.489, 'CCWM': -17.799, 'TeamName': 'Bionic Spartans'}, {'TeamNum': 9986, 'OPR': 47.261, 'Auto': 5.743, 'CCWM': 31.845, 'TeamName': 'Eaglebotics Navy'}, {'TeamNum': 21498, 'OPR': 46.264, 'Auto': 1.884, 'CCWM': -4.77, 'TeamName': 'iPrep Pythons'}, {'TeamNum': 16724, 'OPR': 44.309, 'Auto': 6.385, 'CCWM': 20.53, 'TeamName': 'Blue Blazerz'}, {'TeamNum': 21882, 'OPR': 43.296, 'Auto': 10.813, 'CCWM': 20.078, 'TeamName': 'Cyber Spartans'}, {'TeamNum': 13233, 'OPR': 40.276, 'Auto': 4.322, 'CCWM': -7.897, 'TeamName': 'Cyber Knights'}, {'TeamNum': 16484, 'OPR': 38.4, 'Auto': 14.044, 'CCWM': -24.522, 'TeamName': 'ROBOCANES'}, {'TeamNum': 19442, 'OPR': 36.819, 'Auto': 9.321, 'CCWM': 19.421, 'TeamName': 'Wolverine Robotics'}, {'TeamNum': 5125, 'OPR': 32.961, 'Auto': 1.622, 'CCWM': 1.882, 'TeamName': 'Raiderbots'}, {'TeamNum': 19786, 'OPR': 29.796, 'Auto': 11.331, 'CCWM': 28.417, 'TeamName': 'Isotopes'}, {'TeamNum': 11204, 'OPR': 28.703, 'Auto': 8.987, 'CCWM': 18.295, 'TeamName': 'Shark A-Tech'}, {'TeamNum': 17156, 'OPR': 27.417, 'Auto': 17.583, 'CCWM': -29.013, 'TeamName': 'scotsOverflow'}, {'TeamNum': 14431, 'OPR': 25.105, 'Auto': 8.785, 'CCWM': -27.307, 'TeamName': 'Pyrites'}, {'TeamNum': 20723, 'OPR': 23.057, 'Auto': 5.075, 'CCWM': -10.929, 'TeamName': 'Ignatian Industries'}, {'TeamNum': 21382, 'OPR': 22.835, 'Auto': 2.508, 'CCWM': -9.21, 'TeamName': 'Marcus1'}, {'TeamNum': 18619, 'OPR': 22.765, 'Auto': 4.304, 'CCWM': -38.013, 'TeamName': 'BuccaNEERS'}, {'TeamNum': 9110, 'OPR': 19.75, 'Auto': -4.277, 'CCWM': -19.567, 'TeamName': 'WiredCats Omega'}, {'TeamNum': 450, 'OPR': 15.399, 'Auto': 5.744, 'CCWM': -5.434, 'TeamName': 'Children of the Swamp'}, {'TeamNum': 6322, 'OPR': 13.832, 'Auto': 20.841, 'CCWM': -24.544, 'TeamName': 'WiredCats Origin'}, {'TeamNum': 9987, 'OPR': 7.323, 'Auto': 1.822, 'CCWM': -30.895, 'TeamName': 'Eaglebotics Gold'}, {'TeamNum': 10366, 'OPR': -7.6, 'Auto': -10.12, 'CCWM': -26.321, 'TeamName': 'WiredCats Future'}, {'TeamNum': 19441, 'OPR': -19.503, 'Auto': -8.847, 'CCWM': -80.027, 'TeamName': 'Verbiest Vehicles'}]
USFLFLSFLT
[{'TeamNum': 641, 'OPR': 104.143, 'Auto': 18.635, 'CCWM': 60.448, 'TeamName': 'Roboscotia'}, {'TeamNum': 16391, 'OPR': 86.45, 'Auto': 17.76, 'CCWM': 42.039, 'TeamName': 'Rising Ninjas '}, {'TeamNum': 3888, 'OPR': 84.393, 'Auto': 23.772, 'CCWM': -15.468, 'TeamName': 'Greased Lightning'}, {'TeamNum': 10130, 'OPR': 84.118, 'Auto': 17.681, 'CCWM': 8.665, 'TeamName': 'Crown Joules'}, {'TeamNum': 20022, 'OPR': 74.759, 'Auto': 8.146, 'CCWM': 7.537, 'TeamName': 'RoBOCAts'}, {'TeamNum': 16333, 'OPR': 73.54, 'Auto': 21.862, 'CCWM': 34.331, 'TeamName': 'Astrobots'}, {'TeamNum': 12731, 'OPR': 72.486, 'Auto': 27.575, 'CCWM': 6.297, 'TeamName': 'B3'}, {'TeamNum': 21922, 'OPR': 67.16, 'Auto': 14.343, 'CCWM': 17.29, 'TeamName': 'ΔΨΝΑΜΙCΣ (Dynamics)'}, {'TeamNum': 10022, 'OPR': 67.003, 'Auto': 22.044, 'CCWM': 29.439, 'TeamName': 'WiredCats Gen 3'}, {'TeamNum': 16759, 'OPR': 63.708, 'Auto': 8.733, 'CCWM': 43.683, 'TeamName': 'Wyld Stallyns UNTAMED'}, {'TeamNum': 5467, 'OPR': 54.432, 'Auto': 8.171, 'CCWM': -9.6, 'TeamName': '1.21 Gigawatts'}, {'TeamNum': 6321, 'OPR': 51.824, 'Auto': 14.647, 'CCWM': 10.006, 'TeamName': 'RoboRaiders'}, {'TeamNum': 10830, 'OPR': 51.413, 'Auto': 16.923, 'CCWM': -17.8, 'TeamName': 'AJAX'}, {'TeamNum': 21884, 'OPR': 50.825, 'Auto': 4.489, 'CCWM': -17.799, 'TeamName': 'Bionic Spartans'}, {'TeamNum': 9986, 'OPR': 47.261, 'Auto': 5.743, 'CCWM': 31.845, 'TeamName': 'Eaglebotics Navy'}, {'TeamNum': 21498, 'OPR': 46.264, 'Auto': 1.884, 'CCWM': -4.77, 'TeamName': 'iPrep Pythons'}, {'TeamNum': 16724, 'OPR': 44.309, 'Auto': 6.385, 'CCWM': 20.53, 'TeamName': 'Blue Blazerz'}, {'TeamNum': 21882, 'OPR': 43.296, 'Auto': 10.813, 'CCWM': 20.078, 'TeamName': 'Cyber Spartans'}, {'TeamNum': 13233, 'OPR': 40.276, 'Auto': 4.322, 'CCWM': -7.897, 'TeamName': 'Cyber Knights'}, {'TeamNum': 16484, 'OPR': 38.4, 'Auto': 14.044, 'CCWM': -24.522, 'TeamName': 'ROBOCANES'}, {'TeamNum': 19442, 'OPR': 36.819, 'Auto': 9.321, 'CCWM': 19.421, 'TeamName': 'Wolverine Robotics'}, {'TeamNum': 5125, 'OPR': 32.961, 'Auto': 1.622, 'CCWM': 1.882, 'TeamName': 'Raiderbots'}, {'TeamNum': 19786, 'OPR': 29.796, 'Auto': 11.331, 'CCWM': 28.417, 'TeamName': 'Isotopes'}, {'TeamNum': 11204, 'OPR': 28.703, 'Auto': 8.987, 'CCWM': 18.295, 'TeamName': 'Shark A-Tech'}, {'TeamNum': 17156, 'OPR': 27.417, 'Auto': 17.583, 'CCWM': -29.013, 'TeamName': 'scotsOverflow'}, {'TeamNum': 14431, 'OPR': 25.105, 'Auto': 8.785, 'CCWM': -27.307, 'TeamName': 'Pyrites'}, {'TeamNum': 20723, 'OPR': 23.057, 'Auto': 5.075, 'CCWM': -10.929, 'TeamName': 'Ignatian Industries'}, {'TeamNum': 21382, 'OPR': 22.835, 'Auto': 2.508, 'CCWM': -9.21, 'TeamName': 'Marcus1'}, {'TeamNum': 18619, 'OPR': 22.765, 'Auto': 4.304, 'CCWM': -38.013, 'TeamName': 'BuccaNEERS'}, {'TeamNum': 9110, 'OPR': 19.75, 'Auto': -4.277, 'CCWM': -19.567, 'TeamName': 'WiredCats Omega'}, {'TeamNum': 450, 'OPR': 15.399, 'Auto': 5.744, 'CCWM': -5.434, 'TeamName': 'Children of the Swamp'}, {'TeamNum': 6322, 'OPR': 13.832, 'Auto': 20.841, 'CCWM': -24.544, 'TeamName': 'WiredCats Origin'}, {'TeamNum': 9987, 'OPR': 7.323, 'Auto': 1.822, 'CCWM': -30.895, 'TeamName': 'Eaglebotics Gold'}, {'TeamNum': 10366, 'OPR': -7.6, 'Auto': -10.12, 'CCWM': -26.321, 'TeamName': 'WiredCats Future'}, {'TeamNum': 19441, 'OPR': -19.503, 'Auto': -8.847, 'CCWM': -80.027, 'TeamName': 'Verbiest Vehicles'}]

i 927
{'20397', '19803', '11892', '20357', '18385', '12585', '10276', '18317', '16465', '17986', '19762', '22158', '17593', '19916', '11774', '11172', '19388', '15052', '22238', '14384', '9944', '14447', '16271', '20324', '20358', '22127', '20865', '16312', '18145'}
[{'TeamNum': 11172, 'OPR': 120.884, 'Auto': 30.014, 'CCWM': 87.878, 'TeamName': 'Static Discharge'}, {'TeamNum': 10276, 'OPR': 100.989, 'Auto': 27.748, 'CCWM': 49.688, 'TeamName': 'Storm Troopers'}, {'TeamNum': 18385, 'OPR': 82.591, 'Auto': 27.729, 'CCWM': 47.705, 'TeamName': 'SHIVA Atomatrons'}, {'TeamNum': 19388, 'OPR': 81.179, 'Auto': 6.623, 'CCWM': 59.584, 'TeamName': 'Metal Mavericks'}, {'TeamNum': 18317, 'OPR': 77.347, 'Auto': 26.923, 'CCWM': 23.271, 'TeamName': 'Steel Eels'}, {'TeamNum': 16312, 'OPR': 70.129, 'Auto': 29.556, 'CCWM': 21.854, 'TeamName': 'Sandman'}, {'TeamNum': 22238, 'OPR': 66.9, 'Auto': 21.428, 'CCWM': 9.618, 'TeamName': 'Screw It'}, {'TeamNum': 22127, 'OPR': 64.299, 'Auto': 2.147, 'CCWM': 32.464, 'TeamName': 'Mischievous Mechanics'}, {'TeamNum': 14384, 'OPR': 62.255, 'Auto': 28.449, 'CCWM': 22.595, 'TeamName': 'Patent Pending'}, {'TeamNum': 19916, 'OPR': 60.527, 'Auto': 19.567, 'CCWM': 46.771, 'TeamName': 'The Wolf Pack Robotics Club'}, {'TeamNum': 9944, 'OPR': 51.264, 'Auto': 10.468, 'CCWM': 7.359, 'TeamName': 'SATURN #9944'}, {'TeamNum': 15052, 'OPR': 49.045, 'Auto': 7.414, 'CCWM': -15.583, 'TeamName': 'Space Engineers'}, {'TeamNum': 16465, 'OPR': 45.78, 'Auto': 11.443, 'CCWM': -18.241, 'TeamName': 'Servo Stallions'}, {'TeamNum': 20865, 'OPR': 44.936, 'Auto': 5.117, 'CCWM': 28.321, 'TeamName': 'Atlantic Coast Gamma Rays'}, {'TeamNum': 16271, 'OPR': 41.277, 'Auto': 3.569, 'CCWM': -11.058, 'TeamName': 'Flying Tigers'}, {'TeamNum': 11774, 'OPR': 35.465, 'Auto': 8.568, 'CCWM': -32.557, 'TeamName': 'Palatka High School Robo-Panthers'}, {'TeamNum': 20397, 'OPR': 32.772, 'Auto': 7.517, 'CCWM': -5.331, 'TeamName': ' Flashes'}, {'TeamNum': 19803, 'OPR': 30.949, 'Auto': -2.664, 'CCWM': -1.782, 'TeamName': 'A. Philip Randolph 1'}, {'TeamNum': 18145, 'OPR': 30.232, 'Auto': 21.234, 'CCWM': -45.905, 'TeamName': 'Men in Black Jax'}, {'TeamNum': 19762, 'OPR': 28.477, 'Auto': 1.76, 'CCWM': -6.718, 'TeamName': 'Electrical Mayhem'}, {'TeamNum': 14447, 'OPR': 27.333, 'Auto': -3.668, 'CCWM': -19.913, 'TeamName': 'CyberVikings'}, {'TeamNum': 12585, 'OPR': 22.792, 'Auto': 2.365, 'CCWM': 11.765, 'TeamName': 'BK Crusaders'}, {'TeamNum': 17593, 'OPR': 18.426, 'Auto': -7.35, 'CCWM': -22.893, 'TeamName': 'Mechanical Menaces'}, {'TeamNum': 11892, 'OPR': 16.382, 'Auto': -5.556, 'CCWM': -29.481, 'TeamName': 'The Flash Drives'}, {'TeamNum': 22158, 'OPR': 15.7, 'Auto': 9.453, 'CCWM': -39.877, 'TeamName': 'Tocoi Creek Thunder Chickens'}, {'TeamNum': 20358, 'OPR': 14.379, 'Auto': -1.2, 'CCWM': -71.861, 'TeamName': 'Tocoi Creek Robo Toros'}, {'TeamNum': 17986, 'OPR': 13.894, 'Auto': 2.331, 'CCWM': -20.706, 'TeamName': '904 Robo Eagles'}, {'TeamNum': 20357, 'OPR': 11.671, 'Auto': -3.493, 'CCWM': -25.229, 'TeamName': 'Tocoi Creek Los Toros Loco'}, {'TeamNum': 20324, 'OPR': -4.723, 'Auto': 4.718, 'CCWM': -86.683, 'TeamName': 'Greenwood Mechanical Eagles'}]
USFLFLNELT
[{'TeamNum': 11172, 'OPR': 120.884, 'Auto': 30.014, 'CCWM': 87.878, 'TeamName': 'Static Discharge'}, {'TeamNum': 10276, 'OPR': 100.989, 'Auto': 27.748, 'CCWM': 49.688, 'TeamName': 'Storm Troopers'}, {'TeamNum': 18385, 'OPR': 82.591, 'Auto': 27.729, 'CCWM': 47.705, 'TeamName': 'SHIVA Atomatrons'}, {'TeamNum': 19388, 'OPR': 81.179, 'Auto': 6.623, 'CCWM': 59.584, 'TeamName': 'Metal Mavericks'}, {'TeamNum': 18317, 'OPR': 77.347, 'Auto': 26.923, 'CCWM': 23.271, 'TeamName': 'Steel Eels'}, {'TeamNum': 16312, 'OPR': 70.129, 'Auto': 29.556, 'CCWM': 21.854, 'TeamName': 'Sandman'}, {'TeamNum': 22238, 'OPR': 66.9, 'Auto': 21.428, 'CCWM': 9.618, 'TeamName': 'Screw It'}, {'TeamNum': 22127, 'OPR': 64.299, 'Auto': 2.147, 'CCWM': 32.464, 'TeamName': 'Mischievous Mechanics'}, {'TeamNum': 14384, 'OPR': 62.255, 'Auto': 28.449, 'CCWM': 22.595, 'TeamName': 'Patent Pending'}, {'TeamNum': 19916, 'OPR': 60.527, 'Auto': 19.567, 'CCWM': 46.771, 'TeamName': 'The Wolf Pack Robotics Club'}, {'TeamNum': 9944, 'OPR': 51.264, 'Auto': 10.468, 'CCWM': 7.359, 'TeamName': 'SATURN #9944'}, {'TeamNum': 15052, 'OPR': 49.045, 'Auto': 7.414, 'CCWM': -15.583, 'TeamName': 'Space Engineers'}, {'TeamNum': 16465, 'OPR': 45.78, 'Auto': 11.443, 'CCWM': -18.241, 'TeamName': 'Servo Stallions'}, {'TeamNum': 20865, 'OPR': 44.936, 'Auto': 5.117, 'CCWM': 28.321, 'TeamName': 'Atlantic Coast Gamma Rays'}, {'TeamNum': 16271, 'OPR': 41.277, 'Auto': 3.569, 'CCWM': -11.058, 'TeamName': 'Flying Tigers'}, {'TeamNum': 11774, 'OPR': 35.465, 'Auto': 8.568, 'CCWM': -32.557, 'TeamName': 'Palatka High School Robo-Panthers'}, {'TeamNum': 20397, 'OPR': 32.772, 'Auto': 7.517, 'CCWM': -5.331, 'TeamName': ' Flashes'}, {'TeamNum': 19803, 'OPR': 30.949, 'Auto': -2.664, 'CCWM': -1.782, 'TeamName': 'A. Philip Randolph 1'}, {'TeamNum': 18145, 'OPR': 30.232, 'Auto': 21.234, 'CCWM': -45.905, 'TeamName': 'Men in Black Jax'}, {'TeamNum': 19762, 'OPR': 28.477, 'Auto': 1.76, 'CCWM': -6.718, 'TeamName': 'Electrical Mayhem'}, {'TeamNum': 14447, 'OPR': 27.333, 'Auto': -3.668, 'CCWM': -19.913, 'TeamName': 'CyberVikings'}, {'TeamNum': 12585, 'OPR': 22.792, 'Auto': 2.365, 'CCWM': 11.765, 'TeamName': 'BK Crusaders'}, {'TeamNum': 17593, 'OPR': 18.426, 'Auto': -7.35, 'CCWM': -22.893, 'TeamName': 'Mechanical Menaces'}, {'TeamNum': 11892, 'OPR': 16.382, 'Auto': -5.556, 'CCWM': -29.481, 'TeamName': 'The Flash Drives'}, {'TeamNum': 22158, 'OPR': 15.7, 'Auto': 9.453, 'CCWM': -39.877, 'TeamName': 'Tocoi Creek Thunder Chickens'}, {'TeamNum': 20358, 'OPR': 14.379, 'Auto': -1.2, 'CCWM': -71.861, 'TeamName': 'Tocoi Creek Robo Toros'}, {'TeamNum': 17986, 'OPR': 13.894, 'Auto': 2.331, 'CCWM': -20.706, 'TeamName': '904 Robo Eagles'}, {'TeamNum': 20357, 'OPR': 11.671, 'Auto': -3.493, 'CCWM': -25.229, 'TeamName': 'Tocoi Creek Los Toros Loco'}, {'TeamNum': 20324, 'OPR': -4.723, 'Auto': 4.718, 'CCWM': -86.683, 'TeamName': 'Greenwood Mechanical Eagles'}]
i 928
{'8796', '10284', '10168', '10584', '13675', '9214', '8797', '10583', '20673', '8798', '8799', '8859', '10768'}
[{'TeamNum': 10583, 'OPR': 52.394, 'Auto': 17.411, 'CCWM': 25.656, 'TeamName': 'The Robotic Gladiators'}, {'TeamNum': 10584, 'OPR': 52.197, 'Auto': 21.79, 'CCWM': 8.814, 'TeamName': 'KH Roba Fett'}, {'TeamNum': 8859, 'OPR': 46.624, 'Auto': 18.618, 'CCWM': 27.505, 'TeamName': 'RaiderTek'}, {'TeamNum': 9214, 'OPR': 45.802, 'Auto': 14.173, 'CCWM': 33.698, 'TeamName': 'R²'}, {'TeamNum': 10168, 'OPR': 44.969, 'Auto': 14.926, 'CCWM': 23.635, 'TeamName': 'LJH Gator Techs'}, {'TeamNum': 20673, 'OPR': 40.71, 'Auto': 7.98, 'CCWM': 4.846, 'TeamName': 'LJH Tech Lizards'}, {'TeamNum': 13675, 'OPR': 20.768, 'Auto': 4.98, 'CCWM': 8.108, 'TeamName': 'Talon Techs'}, {'TeamNum': 10768, 'OPR': 19.843, 'Auto': 3.204, 'CCWM': -25.154, 'TeamName': 'Middleburg High School'}, {'TeamNum': 10284, 'OPR': 15.108, 'Auto': 1.91, 'CCWM': -39.495, 'TeamName': 'Team R.O.B.O.T. (Really Obsessed Builders Of Tomorrow)'}, {'TeamNum': 8796, 'OPR': 11.155, 'Auto': -4.103, 'CCWM': -10.644, 'TeamName': 'Clay '}, {'TeamNum': 8797, 'OPR': 10.953, 'Auto': -3.382, 'CCWM': -0.506, 'TeamName': 'Oakleaf High School'}, {'TeamNum': 8798, 'OPR': 9.703, 'Auto': 1.944, 'CCWM': -22.323, 'TeamName': 'Aluminati Industries'}, {'TeamNum': 8799, 'OPR': 8.831, 'Auto': 0.289, 'CCWM': -30.334, 'TeamName': 'Robo Tigers'}]
USFLFLOCLT
[{'TeamNum': 10583, 'OPR': 52.394, 'Auto': 17.411, 'CCWM': 25.656, 'TeamName': 'The Robotic Gladiators'}, {'TeamNum': 10584, 'OPR': 52.197, 'Auto': 21.79, 'CCWM': 8.814, 'TeamName': 'KH Roba Fett'}, {'TeamNum': 8859, 'OPR': 46.624, 'Auto': 18.618, 'CCWM': 27.505, 'TeamName': 'RaiderTek'}, {'TeamNum': 9214, 'OPR': 45.802, 'Auto': 14.173, 'CCWM': 33.698, 'TeamName': 'R²'}, {'TeamNum': 10168, 'OPR': 44.969, 'Auto': 14.926, 'CCWM': 23.635, 'TeamName': 'LJH Gator Techs'}, {'TeamNum': 20673, 'OPR': 40.71, 'Auto': 7.98, 'CCWM': 4.846, 'TeamName': 'LJH Tech Lizards'}, {'TeamNum': 13675, 'OPR': 20.768, 'Auto': 4.98, 'CCWM': 8.108, 'TeamName': 'Talon Techs'}, {'TeamNum': 10768, 'OPR': 19.843, 'Auto': 3.204, 'CCWM': -25.154, 'TeamName': 'Middleburg High School'}, {'TeamNum': 10284, 'OPR': 15.108, 'Auto': 1.91, 'CCWM': -39.495, 'TeamName': 'Team R.O.B.O.T. (Really Obsessed Builders Of Tomorrow)'}, {'TeamNum': 8796, 'OPR': 11.155, 'Auto': -4.103, 'CCWM': -10.644, 'TeamName': 'Clay '}, {'TeamNum': 8797, 'OPR': 10.953, 'Auto': -3.382, 'CCWM': -0.506, 'TeamName': 'Oakleaf High School'}, {'TeamNum': 8798, 'OPR': 9.703, 'Auto': 1.944, 'CCWM': -22.323, 'TeamName': 'Aluminati Industries'}, {'TeamNum': 8799, 'OPR': 8.831, 'Auto': 0.289, 'CCWM': -30.334, 'TeamName': 'Robo Tigers'}]
i 929

{'19954', '12600', '14850', '19895', '21584', '2425', '11619', '16716', '18518', '4997', '2845', '6433', '21477', '13624', '7017', '7719', '9175', '3846'}
[{'TeamNum': 16716, 'OPR': 97.097, 'Auto': 20.968, 'CCWM': 69.499, 'TeamName': 'IvyWarriors'}, {'TeamNum': 7719, 'OPR': 91.168, 'Auto': 21.138, 'CCWM': 56.099, 'TeamName': 'RISE'}, {'TeamNum': 12600, 'OPR': 74.195, 'Auto': 18.991, 'CCWM': 2.882, 'TeamName': 'Hadron Knights'}, {'TeamNum': 7017, 'OPR': 72.864, 'Auto': 15.199, 'CCWM': 37.037, 'TeamName': 'Robotic Fallout'}, {'TeamNum': 2425, 'OPR': 68.254, 'Auto': 19.991, 'CCWM': 36.236, 'TeamName': 'Hydra'}, {'TeamNum': 19954, 'OPR': 64.181, 'Auto': 12.547, 'CCWM': 11.503, 'TeamName': "Mario's Mechanics"}, {'TeamNum': 14850, 'OPR': 61.431, 'Auto': 20.128, 'CCWM': 41.734, 'TeamName': 'Donkey Kog'}, {'TeamNum': 2845, 'OPR': 57.888, 'Auto': 15.829, 'CCWM': -0.803, 'TeamName': 'Team Duct Tape'}, {'TeamNum': 13624, 'OPR': 57.321, 'Auto': 2.423, 'CCWM': 17.718, 'TeamName': 'Subway Servos'}, {'TeamNum': 18518, 'OPR': 49.709, 'Auto': 9.901, 'CCWM': 8.611, 'TeamName': 'Super Smash Bots'}, {'TeamNum': 9175, 'OPR': 47.683, 'Auto': 7.931, 'CCWM': 2.355, 'TeamName': 'Warrior Bots'}, {'TeamNum': 6433, 'OPR': 47.633, 'Auto': 9.838, 'CCWM': -25.265, 'TeamName': 'Neutrinos'}, {'TeamNum': 19895, 'OPR': 29.979, 'Auto': 22.435, 'CCWM': -12.527, 'TeamName': 'Dragomight'}, {'TeamNum': 11619, 'OPR': 27.825, 'Auto': 12.483, 'CCWM': -26.77, 'TeamName': 'Red Dead Invention'}, {'TeamNum': 21584, 'OPR': 16.032, 'Auto': 6.65, 'CCWM': -41.849, 'TeamName': 'Spare Parts '}, {'TeamNum': 3846, 'OPR': 13.296, 'Auto': 9.544, 'CCWM': -61.764, 'TeamName': 'Maelstrom'}, {'TeamNum': 21477, 'OPR': 12.219, 'Auto': 1.163, 'CCWM': -60.146, 'TeamName': 'KRAK3N'}, {'TeamNum': 4997, 'OPR': 0.889, 'Auto': 1.838, 'CCWM': -54.549, 'TeamName': 'Masquerade'}]
USFLFLROLT
[{'TeamNum': 16716, 'OPR': 97.097, 'Auto': 20.968, 'CCWM': 69.499, 'TeamName': 'IvyWarriors'}, {'TeamNum': 7719, 'OPR': 91.168, 'Auto': 21.138, 'CCWM': 56.099, 'TeamName': 'RISE'}, {'TeamNum': 12600, 'OPR': 74.195, 'Auto': 18.991, 'CCWM': 2.882, 'TeamName': 'Hadron Knights'}, {'TeamNum': 7017, 'OPR': 72.864, 'Auto': 15.199, 'CCWM': 37.037, 'TeamName': 'Robotic Fallout'}, {'TeamNum': 2425, 'OPR': 68.254, 'Auto': 19.991, 'CCWM': 36.236, 'TeamName': 'Hydra'}, {'TeamNum': 19954, 'OPR': 64.181, 'Auto': 12.547, 'CCWM': 11.503, 'TeamName': "Mario's Mechanics"}, {'TeamNum': 14850, 'OPR': 61.431, 'Auto': 20.128, 'CCWM': 41.734, 'TeamName': 'Donkey Kog'}, {'TeamNum': 2845, 'OPR': 57.888, 'Auto': 15.829, 'CCWM': -0.803, 'TeamName': 'Team Duct Tape'}, {'TeamNum': 13624, 'OPR': 57.321, 'Auto': 2.423, 'CCWM': 17.718, 'TeamName': 'Subway Servos'}, {'TeamNum': 18518, 'OPR': 49.709, 'Auto': 9.901, 'CCWM': 8.611, 'TeamName': 'Super Smash Bots'}, {'TeamNum': 9175, 'OPR': 47.683, 'Auto': 7.931, 'CCWM': 2.355, 'TeamName': 'Warrior Bots'}, {'TeamNum': 6433, 'OPR': 47.633, 'Auto': 9.838, 'CCWM': -25.265, 'TeamName': 'Neutrinos'}, {'TeamNum': 19895, 'OPR': 29.979, 'Auto': 22.435, 'CCWM': -12.527, 'TeamName': 'Dragomight'}, {'TeamNum': 11619, 'OPR': 27.825, 'Auto': 12.483, 'CCWM': -26.77, 'TeamName': 'Red Dead Invention'}, {'TeamNum': 21584, 'OPR': 16.032, 'Auto': 6.65, 'CCWM': -41.849, 'TeamName': 'Spare Parts '}, {'TeamNum': 3846, 'OPR': 13.296, 'Auto': 9.544, 'CCWM': -61.764, 'TeamName': 'Maelstrom'}, {'TeamNum': 21477, 'OPR': 12.219, 'Auto': 1.163, 'CCWM': -60.146, 'TeamName': 'KRAK3N'}, {'TeamNum': 4997, 'OPR': 0.889, 'Auto': 1.838, 'CCWM': -54.549, 'TeamName': 'Masquerade'}]
i 930
{'21944', '15006', '3830', '22944', '516', '16389', '3736', '14725', '506', '22366', '3101', '22367', '22690', '22474', '14226', '17015', '22473', '17115', '3123', '3839', '22365', '22532', '13093', '20012', '15858'}
[{'TeamNum': 14725, 'OPR': 125.496, 'Auto': 33.244, 'CCWM': 106.467, 'TeamName': 'Java the Hutts'}, {'TeamNum': 15006, 'OPR': 125.088, 'Auto': 42.206, 'CCWM': 73.573, 'TeamName': 'Nerdvana'}, {'TeamNum': 13093, 'OPR': 122.652, 'Auto': 24.436, 'CCWM': 61.466, 'TeamName': 'Golden Fish'}, {'TeamNum': 17015, 'OPR': 110.535, 'Auto': 26.314, 'CCWM': 75.903, 'TeamName': 'KING TARP'}, {'TeamNum': 22690, 'OPR': 102.103, 'Auto': 26.748, 'CCWM': 40.652, 'TeamName': 'Quantum Bots'}, {'TeamNum': 3830, 'OPR': 83.21, 'Auto': 19.657, 'CCWM': 59.296, 'TeamName': 'Violet Fusion'}, {'TeamNum': 516, 'OPR': 74.549, 'Auto': 12.499, 'CCWM': 25.737, 'TeamName': 'Gears of Fire'}, {'TeamNum': 3101, 'OPR': 74.441, 'Auto': 20.038, 'CCWM': 62.508, 'TeamName': 'Boom Bots'}, {'TeamNum': 506, 'OPR': 72.825, 'Auto': 20.961, 'CCWM': 45.742, 'TeamName': 'Pandara'}, {'TeamNum': 20012, 'OPR': 70.682, 'Auto': 21.514, 'CCWM': 22.285, 'TeamName': 'Cadastrophe'}, {'TeamNum': 3123, 'OPR': 61.512, 'Auto': 13.835, 'CCWM': 8.852, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 3839, 'OPR': 48.259, 'Auto': 0.705, 'CCWM': -5.211, 'TeamName': 'Mechanical Geniuses'}, {'TeamNum': 16389, 'OPR': 45.728, 'Auto': 10.876, 'CCWM': -9.594, 'TeamName': 'CyDroids of Cypress Lake'}, {'TeamNum': 22944, 'OPR': 45.28, 'Auto': 17.716, 'CCWM': -15.067, 'TeamName': 'MechTech 22944'}, {'TeamNum': 14226, 'OPR': 38.864, 'Auto': 15.614, 'CCWM': 0.451, 'TeamName': 'Ironic'}, {'TeamNum': 22474, 'OPR': 33.204, 'Auto': 4.632, 'CCWM': -29.48, 'TeamName': 'AMIKids Future Masterminds'}, {'TeamNum': 22365, 'OPR': 32.153, 'Auto': 1.375, 'CCWM': -35.463, 'TeamName': 'Black & Gold Warriors'}, {'TeamNum': 21944, 'OPR': 29.861, 'Auto': 5.412, 'CCWM': -43.208, 'TeamName': 'RNDOPS'}, {'TeamNum': 22366, 'OPR': 24.976, 'Auto': 2.516, 'CCWM': -50.381, 'TeamName': 'Nerds Inc.'}, {'TeamNum': 22473, 'OPR': 21.921, 'Auto': 2.697, 'CCWM': -39.874, 'TeamName': 'AMIKids Motion'}, {'TeamNum': 17115, 'OPR': 14.994, 'Auto': -2.368, 'CCWM': -72.974, 'TeamName': 'Patriots'}, {'TeamNum': 22367, 'OPR': 8.86, 'Auto': -4.599, 'CCWM': -18.158, 'TeamName': 'Vero-bots'}, {'TeamNum': 22532, 'OPR': 0.569, 'Auto': -1.399, 'CCWM': -114.86, 'TeamName': 'The Phantom Menace'}, {'TeamNum': 3736, 'OPR': -5.448, 'Auto': -3.051, 'CCWM': -95.949, 'TeamName': 'Serious Business'}, {'TeamNum': 15858, 'OPR': -8.197, 'Auto': -2.384, 'CCWM': -60.062, 'TeamName': 'e=mc Hammer'}]
USFLFLGCLT
[{'TeamNum': 14725, 'OPR': 125.496, 'Auto': 33.244, 'CCWM': 106.467, 'TeamName': 'Java the Hutts'}, {'TeamNum': 15006, 'OPR': 125.088, 'Auto': 42.206, 'CCWM': 73.573, 'TeamName': 'Nerdvana'}, {'TeamNum': 13093, 'OPR': 122.652, 'Auto': 24.436, 'CCWM': 61.466, 'TeamName': 'Golden Fish'}, {'TeamNum': 17015, 'OPR': 110.535, 'Auto': 26.314, 'CCWM': 75.903, 'TeamName': 'KING TARP'}, {'TeamNum': 22690, 'OPR': 102.103, 'Auto': 26.748, 'CCWM': 40.652, 'TeamName': 'Quantum Bots'}, {'TeamNum': 3830, 'OPR': 83.21, 'Auto': 19.657, 'CCWM': 59.296, 'TeamName': 'Violet Fusion'}, {'TeamNum': 516, 'OPR': 74.549, 'Auto': 12.499, 'CCWM': 25.737, 'TeamName': 'Gears of Fire'}, {'TeamNum': 3101, 'OPR': 74.441, 'Auto': 20.038, 'CCWM': 62.508, 'TeamName': 'Boom Bots'}, {'TeamNum': 506, 'OPR': 72.825, 'Auto': 20.961, 'CCWM': 45.742, 'TeamName': 'Pandara'}, {'TeamNum': 20012, 'OPR': 70.682, 'Auto': 21.514, 'CCWM': 22.285, 'TeamName': 'Cadastrophe'}, {'TeamNum': 3123, 'OPR': 61.512, 'Auto': 13.835, 'CCWM': 8.852, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 3839, 'OPR': 48.259, 'Auto': 0.705, 'CCWM': -5.211, 'TeamName': 'Mechanical Geniuses'}, {'TeamNum': 16389, 'OPR': 45.728, 'Auto': 10.876, 'CCWM': -9.594, 'TeamName': 'CyDroids of Cypress Lake'}, {'TeamNum': 22944, 'OPR': 45.28, 'Auto': 17.716, 'CCWM': -15.067, 'TeamName': 'MechTech 22944'}, {'TeamNum': 14226, 'OPR': 38.864, 'Auto': 15.614, 'CCWM': 0.451, 'TeamName': 'Ironic'}, {'TeamNum': 22474, 'OPR': 33.204, 'Auto': 4.632, 'CCWM': -29.48, 'TeamName': 'AMIKids Future Masterminds'}, {'TeamNum': 22365, 'OPR': 32.153, 'Auto': 1.375, 'CCWM': -35.463, 'TeamName': 'Black & Gold Warriors'}, {'TeamNum': 21944, 'OPR': 29.861, 'Auto': 5.412, 'CCWM': -43.208, 'TeamName': 'RNDOPS'}, {'TeamNum': 22366, 'OPR': 24.976, 'Auto': 2.516, 'CCWM': -50.381, 'TeamName': 'Nerds Inc.'}, {'TeamNum': 22473, 'OPR': 21.921, 'Auto': 2.697, 'CCWM': -39.874, 'TeamName': 'AMIKids Motion'}, {'TeamNum': 17115, 'OPR': 14.994, 'Auto': -2.368, 'CCWM': -72.974, 'TeamName': 'Patriots'}, {'TeamNum': 22367, 'OPR': 8.86, 'Auto': -4.599, 'CCWM': -18.158, 'TeamName': 'Vero-bots'}, {'TeamNum': 22532, 'OPR': 0.569, 'Auto': -1.399, 'CCWM': -114.86, 'TeamName': 'The Phantom Menace'}, {'TeamNum': 3736, 'OPR': -5.448, 'Auto': -3.051, 'CCWM': -95.949, 'TeamName': 'Serious Business'}, {'TeamNum': 15858, 'OPR': -8.197, 'Auto': -2.384, 'CCWM': -60.062, 'TeamName': 'e=mc Hammer'}]

i 931
{'17288', '22378', '5070', '10650', '22012', '15033', '9800', '21527', '21528', '21510', '21440', '9277', '9930', '16249', '20344', '14765', '17305', '15065'}
[{'TeamNum': 10650, 'OPR': 108.859, 'Auto': 35.632, 'CCWM': 57.584, 'TeamName': 'Hazmat Robotics Biohazards'}, {'TeamNum': 9930, 'OPR': 87.966, 'Auto': 31.319, 'CCWM': 34.334, 'TeamName': 'Robo-Knights'}, {'TeamNum': 20344, 'OPR': 83.464, 'Auto': 13.107, 'CCWM': 45.475, 'TeamName': 'Cattlebots '}, {'TeamNum': 21528, 'OPR': 62.35, 'Auto': 14.049, 'CCWM': 27.063, 'TeamName': 'TechnoSaints B'}, {'TeamNum': 5070, 'OPR': 59.487, 'Auto': 20.042, 'CCWM': 10.501, 'TeamName': 'N.U.T.S.'}, {'TeamNum': 16249, 'OPR': 52.524, 'Auto': 16.055, 'CCWM': 11.749, 'TeamName': 'Excaliper'}, {'TeamNum': 22012, 'OPR': 51.161, 'Auto': 10.814, 'CCWM': 19.409, 'TeamName': 'OSS Loose Screws'}, {'TeamNum': 17288, 'OPR': 49.748, 'Auto': 21.932, 'CCWM': -9.728, 'TeamName': 'Rubber Bandits'}, {'TeamNum': 15065, 'OPR': 45.144, 'Auto': 4.931, 'CCWM': 21.426, 'TeamName': 'A Byte Irrational'}, {'TeamNum': 21527, 'OPR': 44.921, 'Auto': 19.449, 'CCWM': -5.921, 'TeamName': 'TechnoSaints C'}, {'TeamNum': 17305, 'OPR': 40.449, 'Auto': 6.299, 'CCWM': -1.366, 'TeamName': 'Ducks in a Row'}, {'TeamNum': 9277, 'OPR': 31.685, 'Auto': 6.811, 'CCWM': 1.173, 'TeamName': 'Hazmat Robotics Explosives'}, {'TeamNum': 9800, 'OPR': 28.783, 'Auto': -3.004, 'CCWM': 1.347, 'TeamName': 'TechnoSaints A'}, {'TeamNum': 22378, 'OPR': 27.192, 'Auto': 2.266, 'CCWM': -35.477, 'TeamName': 'N.E.R.D.S.'}, {'TeamNum': 21510, 'OPR': 18.618, 'Auto': -0.762, 'CCWM': -25.715, 'TeamName': 'Ducks of the Round Table'}, {'TeamNum': 15033, 'OPR': 12.444, 'Auto': -5.805, 'CCWM': -24.78, 'TeamName': 'Bug Bytes'}, {'TeamNum': 21440, 'OPR': 8.449, 'Auto': 2.715, 'CCWM': -61.086, 'TeamName': 'Fried Circuits'}, {'TeamNum': 14765, 'OPR': -1.578, 'Auto': -9.684, 'CCWM': -65.989, 'TeamName': 'Mechatronic Mustangs'}]
USFLFLOLLT
[{'TeamNum': 10650, 'OPR': 108.859, 'Auto': 35.632, 'CCWM': 57.584, 'TeamName': 'Hazmat Robotics Biohazards'}, {'TeamNum': 9930, 'OPR': 87.966, 'Auto': 31.319, 'CCWM': 34.334, 'TeamName': 'Robo-Knights'}, {'TeamNum': 20344, 'OPR': 83.464, 'Auto': 13.107, 'CCWM': 45.475, 'TeamName': 'Cattlebots '}, {'TeamNum': 21528, 'OPR': 62.35, 'Auto': 14.049, 'CCWM': 27.063, 'TeamName': 'TechnoSaints B'}, {'TeamNum': 5070, 'OPR': 59.487, 'Auto': 20.042, 'CCWM': 10.501, 'TeamName': 'N.U.T.S.'}, {'TeamNum': 16249, 'OPR': 52.524, 'Auto': 16.055, 'CCWM': 11.749, 'TeamName': 'Excaliper'}, {'TeamNum': 22012, 'OPR': 51.161, 'Auto': 10.814, 'CCWM': 19.409, 'TeamName': 'OSS Loose Screws'}, {'TeamNum': 17288, 'OPR': 49.748, 'Auto': 21.932, 'CCWM': -9.728, 'TeamName': 'Rubber Bandits'}, {'TeamNum': 15065, 'OPR': 45.144, 'Auto': 4.931, 'CCWM': 21.426, 'TeamName': 'A Byte Irrational'}, {'TeamNum': 21527, 'OPR': 44.921, 'Auto': 19.449, 'CCWM': -5.921, 'TeamName': 'TechnoSaints C'}, {'TeamNum': 17305, 'OPR': 40.449, 'Auto': 6.299, 'CCWM': -1.366, 'TeamName': 'Ducks in a Row'}, {'TeamNum': 9277, 'OPR': 31.685, 'Auto': 6.811, 'CCWM': 1.173, 'TeamName': 'Hazmat Robotics Explosives'}, {'TeamNum': 9800, 'OPR': 28.783, 'Auto': -3.004, 'CCWM': 1.347, 'TeamName': 'TechnoSaints A'}, {'TeamNum': 22378, 'OPR': 27.192, 'Auto': 2.266, 'CCWM': -35.477, 'TeamName': 'N.E.R.D.S.'}, {'TeamNum': 21510, 'OPR': 18.618, 'Auto': -0.762, 'CCWM': -25.715, 'TeamName': 'Ducks of the Round Table'}, {'TeamNum': 15033, 'OPR': 12.444, 'Auto': -5.805, 'CCWM': -24.78, 'TeamName': 'Bug Bytes'}, {'TeamNum': 21440, 'OPR': 8.449, 'Auto': 2.715, 'CCWM': -61.086, 'TeamName': 'Fried Circuits'}, {'TeamNum': 14765, 'OPR': -1.578, 'Auto': -9.684, 'CCWM': -65.989, 'TeamName': 'Mechatronic Mustangs'}]
i 932
{'2993', '14682', '17421', '14778', '16796', '18434', '2858', '9206', '19751', '21721', '14756', '10158', '21947', '22160', '3819', '6278', '10537', '14887', '18597'}
[{'TeamNum': 2858, 'OPR': 106.959, 'Auto': 19.753, 'CCWM': 49.523, 'TeamName': 'Sparbot'}, {'TeamNum': 17421, 'OPR': 100.561, 'Auto': 29.317, 'CCWM': 45.078, 'TeamName': 'East Jackson Eagles'}, {'TeamNum': 14778, 'OPR': 99.047, 'Auto': 16.3, 'CCWM': 51.617, 'TeamName': 'Autonomous Anonymous '}, {'TeamNum': 10158, 'OPR': 94.3, 'Auto': 21.515, 'CCWM': 25.248, 'TeamName': "Scott's Bots"}, {'TeamNum': 18434, 'OPR': 93.76, 'Auto': 15.226, 'CCWM': 65.714, 'TeamName': 'East Jackson Blue Eagles'}, {'TeamNum': 18597, 'OPR': 73.762, 'Auto': 17.142, 'CCWM': 19.883, 'TeamName': 'RoboClovers'}, {'TeamNum': 10537, 'OPR': 70.839, 'Auto': 13.082, 'CCWM': 29.63, 'TeamName': 'Brobotix'}, {'TeamNum': 14682, 'OPR': 69.682, 'Auto': 12.127, 'CCWM': 29.398, 'TeamName': 'Gears & Spears'}, {'TeamNum': 9206, 'OPR': 61.806, 'Auto': 8.782, 'CCWM': 32.527, 'TeamName': 'iRobotics'}, {'TeamNum': 22160, 'OPR': 43.212, 'Auto': 8.809, 'CCWM': -15.319, 'TeamName': 'Nuts and Bolts'}, {'TeamNum': 2993, 'OPR': 39.777, 'Auto': 9.972, 'CCWM': -64.195, 'TeamName': 'Blue RoboDragons'}, {'TeamNum': 21721, 'OPR': 37.949, 'Auto': 9.539, 'CCWM': -0.362, 'TeamName': 'RoboClovers JV'}, {'TeamNum': 16796, 'OPR': 37.548, 'Auto': 6.785, 'CCWM': -29.481, 'TeamName': 'Red Robodragons'}, {'TeamNum': 3819, 'OPR': 33.204, 'Auto': 0.99, 'CCWM': 1.905, 'TeamName': 'Green RoboDragons'}, {'TeamNum': 21947, 'OPR': 32.539, 'Auto': 9.608, 'CCWM': -41.492, 'TeamName': 'Sparbot'}, {'TeamNum': 14887, 'OPR': 23.63, 'Auto': -0.849, 'CCWM': 0.063, 'TeamName': 'RoboRaiders'}, {'TeamNum': 14756, 'OPR': 20.616, 'Auto': 4.213, 'CCWM': -49.453, 'TeamName': 'Sparbot'}, {'TeamNum': 6278, 'OPR': 16.637, 'Auto': 6.726, 'CCWM': -86.707, 'TeamName': 'Dwayne'}, {'TeamNum': 19751, 'OPR': -13.191, 'Auto': -7.794, 'CCWM': -70.085, 'TeamName': 'Empower 2'}]
USGANELT
[{'TeamNum': 2858, 'OPR': 106.959, 'Auto': 19.753, 'CCWM': 49.523, 'TeamName': 'Sparbot'}, {'TeamNum': 17421, 'OPR': 100.561, 'Auto': 29.317, 'CCWM': 45.078, 'TeamName': 'East Jackson Eagles'}, {'TeamNum': 14778, 'OPR': 99.047, 'Auto': 16.3, 'CCWM': 51.617, 'TeamName': 'Autonomous Anonymous '}, {'TeamNum': 10158, 'OPR': 94.3, 'Auto': 21.515, 'CCWM': 25.248, 'TeamName': "Scott's Bots"}, {'TeamNum': 18434, 'OPR': 93.76, 'Auto': 15.226, 'CCWM': 65.714, 'TeamName': 'East Jackson Blue Eagles'}, {'TeamNum': 18597, 'OPR': 73.762, 'Auto': 17.142, 'CCWM': 19.883, 'TeamName': 'RoboClovers'}, {'TeamNum': 10537, 'OPR': 70.839, 'Auto': 13.082, 'CCWM': 29.63, 'TeamName': 'Brobotix'}, {'TeamNum': 14682, 'OPR': 69.682, 'Auto': 12.127, 'CCWM': 29.398, 'TeamName': 'Gears & Spears'}, {'TeamNum': 9206, 'OPR': 61.806, 'Auto': 8.782, 'CCWM': 32.527, 'TeamName': 'iRobotics'}, {'TeamNum': 22160, 'OPR': 43.212, 'Auto': 8.809, 'CCWM': -15.319, 'TeamName': 'Nuts and Bolts'}, {'TeamNum': 2993, 'OPR': 39.777, 'Auto': 9.972, 'CCWM': -64.195, 'TeamName': 'Blue RoboDragons'}, {'TeamNum': 21721, 'OPR': 37.949, 'Auto': 9.539, 'CCWM': -0.362, 'TeamName': 'RoboClovers JV'}, {'TeamNum': 16796, 'OPR': 37.548, 'Auto': 6.785, 'CCWM': -29.481, 'TeamName': 'Red Robodragons'}, {'TeamNum': 3819, 'OPR': 33.204, 'Auto': 0.99, 'CCWM': 1.905, 'TeamName': 'Green RoboDragons'}, {'TeamNum': 21947, 'OPR': 32.539, 'Auto': 9.608, 'CCWM': -41.492, 'TeamName': 'Sparbot'}, {'TeamNum': 14887, 'OPR': 23.63, 'Auto': -0.849, 'CCWM': 0.063, 'TeamName': 'RoboRaiders'}, {'TeamNum': 14756, 'OPR': 20.616, 'Auto': 4.213, 'CCWM': -49.453, 'TeamName': 'Sparbot'}, {'TeamNum': 6278, 'OPR': 16.637, 'Auto': 6.726, 'CCWM': -86.707, 'TeamName': 'Dwayne'}, {'TeamNum': 19751, 'OPR': -13.191, 'Auto': -7.794, 'CCWM': -70.085, 'TeamName': 'Empower 2'}]
i 933
i 934
{'8698', '6199', '8709', '16033', '13193', '20196', '6200', '15321', '19575', '22139', '16971', '6198', '10505', '5037', '7715', '17023', '5199', '8907', '18255', '7627', '12682', '17301'}
[{'TeamNum': 18255, 'OPR': 137.612, 'Auto': 29.094, 'CCWM': 69.566, 'TeamName': 'Stealth Robotics'}, {'TeamNum': 12682, 'OPR': 106.906, 'Auto': 19.557, 'CCWM': 60.413, 'TeamName': 'The Golden Ratio'}, {'TeamNum': 17301, 'OPR': 94.213, 'Auto': 26.634, 'CCWM': 73.463, 'TeamName': 'Royal Rumble'}, {'TeamNum': 15321, 'OPR': 76.903, 'Auto': 13.124, 'CCWM': 4.195, 'TeamName': 'Green Machine (CLS Robotics)'}, {'TeamNum': 17023, 'OPR': 73.817, 'Auto': 20.225, 'CCWM': -4.572, 'TeamName': 'Swamp Bots (CLS Robotics)'}, {'TeamNum': 5037, 'OPR': 70.228, 'Auto': 17.414, 'CCWM': -2.227, 'TeamName': 'got robot?'}, {'TeamNum': 13193, 'OPR': 69.539, 'Auto': 15.761, 'CCWM': 7.363, 'TeamName': 'Code Blue'}, {'TeamNum': 8698, 'OPR': 67.044, 'Auto': 18.932, 'CCWM': 20.008, 'TeamName': 'Guilford RoboVikings'}, {'TeamNum': 6200, 'OPR': 66.017, 'Auto': 11.7, 'CCWM': 24.504, 'TeamName': 'Despicable Machine '}, {'TeamNum': 8907, 'OPR': 60.121, 'Auto': 19.358, 'CCWM': 2.707, 'TeamName': 'Blue Box Bots'}, {'TeamNum': 7715, 'OPR': 54.681, 'Auto': 18.09, 'CCWM': -16.778, 'TeamName': 'Robotic Lions'}, {'TeamNum': 10505, 'OPR': 48.031, 'Auto': 10.455, 'CCWM': -26.861, 'TeamName': 'Minivation'}, {'TeamNum': 5199, 'OPR': 44.0, 'Auto': 3.059, 'CCWM': -7.426, 'TeamName': 'Duct Tape and a Prayer'}, {'TeamNum': 20196, 'OPR': 43.137, 'Auto': 5.512, 'CCWM': -22.688, 'TeamName': 'Royal Robots'}, {'TeamNum': 22139, 'OPR': 37.854, 'Auto': 4.304, 'CCWM': -33.136, 'TeamName': 'Golden Gators (CLS Robotics)'}, {'TeamNum': 6199, 'OPR': 33.175, 'Auto': 3.834, 'CCWM': -38.274, 'TeamName': 'Crash Test Dummies'}, {'TeamNum': 16033, 'OPR': 32.688, 'Auto': 11.018, 'CCWM': 15.524, 'TeamName': 'Robo Wolves'}, {'TeamNum': 19575, 'OPR': 29.25, 'Auto': 0.8, 'CCWM': 17.6, 'TeamName': 'HCA Lions'}, {'TeamNum': 6198, 'OPR': 21.726, 'Auto': 11.464, 'CCWM': -33.138, 'TeamName': 'Bread Admirers'}, {'TeamNum': 7627, 'OPR': 16.504, 'Auto': 7.774, 'CCWM': -28.468, 'TeamName': 'Breaking Bot 7627'}, {'TeamNum': 16971, 'OPR': 16.175, 'Auto': -12.2, 'CCWM': -24.882, 'TeamName': 'TiGears(CLC Robotics)'}, {'TeamNum': 8709, 'OPR': -7.705, 'Auto': -9.43, 'CCWM': -55.435, 'TeamName': 'Roosevelt High School '}]
USILCSNWLT
[{'TeamNum': 18255, 'OPR': 137.612, 'Auto': 29.094, 'CCWM': 69.566, 'TeamName': 'Stealth Robotics'}, {'TeamNum': 12682, 'OPR': 106.906, 'Auto': 19.557, 'CCWM': 60.413, 'TeamName': 'The Golden Ratio'}, {'TeamNum': 17301, 'OPR': 94.213, 'Auto': 26.634, 'CCWM': 73.463, 'TeamName': 'Royal Rumble'}, {'TeamNum': 15321, 'OPR': 76.903, 'Auto': 13.124, 'CCWM': 4.195, 'TeamName': 'Green Machine (CLS Robotics)'}, {'TeamNum': 17023, 'OPR': 73.817, 'Auto': 20.225, 'CCWM': -4.572, 'TeamName': 'Swamp Bots (CLS Robotics)'}, {'TeamNum': 5037, 'OPR': 70.228, 'Auto': 17.414, 'CCWM': -2.227, 'TeamName': 'got robot?'}, {'TeamNum': 13193, 'OPR': 69.539, 'Auto': 15.761, 'CCWM': 7.363, 'TeamName': 'Code Blue'}, {'TeamNum': 8698, 'OPR': 67.044, 'Auto': 18.932, 'CCWM': 20.008, 'TeamName': 'Guilford RoboVikings'}, {'TeamNum': 6200, 'OPR': 66.017, 'Auto': 11.7, 'CCWM': 24.504, 'TeamName': 'Despicable Machine '}, {'TeamNum': 8907, 'OPR': 60.121, 'Auto': 19.358, 'CCWM': 2.707, 'TeamName': 'Blue Box Bots'}, {'TeamNum': 7715, 'OPR': 54.681, 'Auto': 18.09, 'CCWM': -16.778, 'TeamName': 'Robotic Lions'}, {'TeamNum': 10505, 'OPR': 48.031, 'Auto': 10.455, 'CCWM': -26.861, 'TeamName': 'Minivation'}, {'TeamNum': 5199, 'OPR': 44.0, 'Auto': 3.059, 'CCWM': -7.426, 'TeamName': 'Duct Tape and a Prayer'}, {'TeamNum': 20196, 'OPR': 43.137, 'Auto': 5.512, 'CCWM': -22.688, 'TeamName': 'Royal Robots'}, {'TeamNum': 22139, 'OPR': 37.854, 'Auto': 4.304, 'CCWM': -33.136, 'TeamName': 'Golden Gators (CLS Robotics)'}, {'TeamNum': 6199, 'OPR': 33.175, 'Auto': 3.834, 'CCWM': -38.274, 'TeamName': 'Crash Test Dummies'}, {'TeamNum': 16033, 'OPR': 32.688, 'Auto': 11.018, 'CCWM': 15.524, 'TeamName': 'Robo Wolves'}, {'TeamNum': 19575, 'OPR': 29.25, 'Auto': 0.8, 'CCWM': 17.6, 'TeamName': 'HCA Lions'}, {'TeamNum': 6198, 'OPR': 21.726, 'Auto': 11.464, 'CCWM': -33.138, 'TeamName': 'Bread Admirers'}, {'TeamNum': 7627, 'OPR': 16.504, 'Auto': 7.774, 'CCWM': -28.468, 'TeamName': 'Breaking Bot 7627'}, {'TeamNum': 16971, 'OPR': 16.175, 'Auto': -12.2, 'CCWM': -24.882, 'TeamName': 'TiGears(CLC Robotics)'}, {'TeamNum': 8709, 'OPR': -7.705, 'Auto': -9.43, 'CCWM': -55.435, 'TeamName': 'Roosevelt High School '}]

i 935
{'14360', '15159', '22542', '19646', '20674', '20676', '15282', '10253', '22275', '9775', '14401', '22268', '7030', '20208', '22267', '17403', '21866', '11822', '20296', '14592'}
[{'TeamNum': 14360, 'OPR': 107.015, 'Auto': 21.101, 'CCWM': 81.711, 'TeamName': 'Sprockets & Screws'}, {'TeamNum': 15159, 'OPR': 73.885, 'Auto': 12.406, 'CCWM': 62.658, 'TeamName': 'We Byte'}, {'TeamNum': 17403, 'OPR': 71.55, 'Auto': 15.026, 'CCWM': -10.794, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 20674, 'OPR': 48.522, 'Auto': 15.395, 'CCWM': 14.638, 'TeamName': 'Ogden Varsity'}, {'TeamNum': 19646, 'OPR': 38.094, 'Auto': 9.325, 'CCWM': -33.758, 'TeamName': 'Phoenix'}, {'TeamNum': 20296, 'OPR': 37.563, 'Auto': 0.773, 'CCWM': 30.484, 'TeamName': 'Powerpuff Robots'}, {'TeamNum': 15282, 'OPR': 37.174, 'Auto': 15.599, 'CCWM': -6.353, 'TeamName': 'Bobcats Robotics Varsity'}, {'TeamNum': 14401, 'OPR': 35.196, 'Auto': 15.146, 'CCWM': -25.245, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 20208, 'OPR': 34.534, 'Auto': -3.187, 'CCWM': 2.793, 'TeamName': 'Ignite Inventors'}, {'TeamNum': 22275, 'OPR': 33.685, 'Auto': 4.662, 'CCWM': 30.038, 'TeamName': 'Farragut'}, {'TeamNum': 20676, 'OPR': 30.629, 'Auto': 6.526, 'CCWM': 4.71, 'TeamName': 'Ogden JV'}, {'TeamNum': 22268, 'OPR': 27.887, 'Auto': 7.905, 'CCWM': -29.455, 'TeamName': 'Brooks'}, {'TeamNum': 14592, 'OPR': 21.784, 'Auto': 3.813, 'CCWM': 28.293, 'TeamName': 'Huskies'}, {'TeamNum': 7030, 'OPR': 18.983, 'Auto': -1.088, 'CCWM': 9.553, 'TeamName': 'RoboMinds'}, {'TeamNum': 22542, 'OPR': 6.733, 'Auto': -2.085, 'CCWM': 8.819, 'TeamName': 'Leopard Bots'}, {'TeamNum': 10253, 'OPR': 6.255, 'Auto': 1.572, 'CCWM': -29.615, 'TeamName': 'Bobcats Robotics Junior Varsity'}, {'TeamNum': 21866, 'OPR': 4.03, 'Auto': -1.93, 'CCWM': -41.045, 'TeamName': 'LEO'}, {'TeamNum': 11822, 'OPR': 0.391, 'Auto': -5.033, 'CCWM': -0.761, 'TeamName': 'S.T.E.M. - Bulldogs'}, {'TeamNum': 9775, 'OPR': -6.365, 'Auto': 2.656, 'CCWM': -25.276, 'TeamName': 'Intrinsic Schools Belmont Campus'}, {'TeamNum': 22267, 'OPR': -11.146, 'Auto': -4.383, 'CCWM': -71.396, 'TeamName': 'Bogan'}]
USILCMLTA
[{'TeamNum': 14360, 'OPR': 107.015, 'Auto': 21.101, 'CCWM': 81.711, 'TeamName': 'Sprockets & Screws'}, {'TeamNum': 15159, 'OPR': 73.885, 'Auto': 12.406, 'CCWM': 62.658, 'TeamName': 'We Byte'}, {'TeamNum': 17403, 'OPR': 71.55, 'Auto': 15.026, 'CCWM': -10.794, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 20674, 'OPR': 48.522, 'Auto': 15.395, 'CCWM': 14.638, 'TeamName': 'Ogden Varsity'}, {'TeamNum': 19646, 'OPR': 38.094, 'Auto': 9.325, 'CCWM': -33.758, 'TeamName': 'Phoenix'}, {'TeamNum': 20296, 'OPR': 37.563, 'Auto': 0.773, 'CCWM': 30.484, 'TeamName': 'Powerpuff Robots'}, {'TeamNum': 15282, 'OPR': 37.174, 'Auto': 15.599, 'CCWM': -6.353, 'TeamName': 'Bobcats Robotics Varsity'}, {'TeamNum': 14401, 'OPR': 35.196, 'Auto': 15.146, 'CCWM': -25.245, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 20208, 'OPR': 34.534, 'Auto': -3.187, 'CCWM': 2.793, 'TeamName': 'Ignite Inventors'}, {'TeamNum': 22275, 'OPR': 33.685, 'Auto': 4.662, 'CCWM': 30.038, 'TeamName': 'Farragut'}, {'TeamNum': 20676, 'OPR': 30.629, 'Auto': 6.526, 'CCWM': 4.71, 'TeamName': 'Ogden JV'}, {'TeamNum': 22268, 'OPR': 27.887, 'Auto': 7.905, 'CCWM': -29.455, 'TeamName': 'Brooks'}, {'TeamNum': 14592, 'OPR': 21.784, 'Auto': 3.813, 'CCWM': 28.293, 'TeamName': 'Huskies'}, {'TeamNum': 7030, 'OPR': 18.983, 'Auto': -1.088, 'CCWM': 9.553, 'TeamName': 'RoboMinds'}, {'TeamNum': 22542, 'OPR': 6.733, 'Auto': -2.085, 'CCWM': 8.819, 'TeamName': 'Leopard Bots'}, {'TeamNum': 10253, 'OPR': 6.255, 'Auto': 1.572, 'CCWM': -29.615, 'TeamName': 'Bobcats Robotics Junior Varsity'}, {'TeamNum': 21866, 'OPR': 4.03, 'Auto': -1.93, 'CCWM': -41.045, 'TeamName': 'LEO'}, {'TeamNum': 11822, 'OPR': 0.391, 'Auto': -5.033, 'CCWM': -0.761, 'TeamName': 'S.T.E.M. - Bulldogs'}, {'TeamNum': 9775, 'OPR': -6.365, 'Auto': 2.656, 'CCWM': -25.276, 'TeamName': 'Intrinsic Schools Belmont Campus'}, {'TeamNum': 22267, 'OPR': -11.146, 'Auto': -4.383, 'CCWM': -71.396, 'TeamName': 'Bogan'}]
i 936
{'13594', '16277', '11235', '3640', '8899', '15356', '21592', '21930', '14167', '15005', '21824', '15387', '16244', '14469', '9189', '6596', '10101', '9788', '14723', '11177', '8648'}
[{'TeamNum': 15005, 'OPR': 135.149, 'Auto': 22.319, 'CCWM': 84.001, 'TeamName': 'Technophobia'}, {'TeamNum': 14469, 'OPR': 127.459, 'Auto': 37.191, 'CCWM': 48.064, 'TeamName': 'HOW'}, {'TeamNum': 6596, 'OPR': 111.454, 'Auto': 24.191, 'CCWM': 60.66, 'TeamName': 'Robotic Rams'}, {'TeamNum': 16244, 'OPR': 108.65, 'Auto': 21.382, 'CCWM': 2.923, 'TeamName': 'The TrailBlazers'}, {'TeamNum': 10101, 'OPR': 96.037, 'Auto': 21.038, 'CCWM': 49.262, 'TeamName': 'Binary Bullets'}, {'TeamNum': 9189, 'OPR': 68.097, 'Auto': 25.85, 'CCWM': 17.584, 'TeamName': 'All Charged Up'}, {'TeamNum': 8899, 'OPR': 65.548, 'Auto': 26.899, 'CCWM': 27.081, 'TeamName': 'EP Robo Raiders'}, {'TeamNum': 11235, 'OPR': 65.027, 'Auto': 24.042, 'CCWM': -30.531, 'TeamName': 'Retro Robotics'}, {'TeamNum': 16277, 'OPR': 62.445, 'Auto': 21.723, 'CCWM': -16.363, 'TeamName': 'Tekon'}, {'TeamNum': 14167, 'OPR': 60.429, 'Auto': 4.734, 'CCWM': 1.557, 'TeamName': 'The Savage Penguins'}, {'TeamNum': 21592, 'OPR': 49.221, 'Auto': 15.459, 'CCWM': -0.753, 'TeamName': 'FAST BUT NOT FURIOUS'}, {'TeamNum': 15356, 'OPR': 49.116, 'Auto': 8.102, 'CCWM': -17.134, 'TeamName': 'BEASTBOTZ'}, {'TeamNum': 13594, 'OPR': 48.625, 'Auto': 14.734, 'CCWM': -28.28, 'TeamName': 'Sherrard TiGEARS'}, {'TeamNum': 11177, 'OPR': 44.769, 'Auto': 18.323, 'CCWM': 19.328, 'TeamName': 'Gear Grinders'}, {'TeamNum': 3640, 'OPR': 40.071, 'Auto': 1.955, 'CCWM': -24.75, 'TeamName': 'The BoilerBots'}, {'TeamNum': 14723, 'OPR': 38.417, 'Auto': 0.934, 'CCWM': 9.231, 'TeamName': 'Chesterton Robots'}, {'TeamNum': 15387, 'OPR': 36.215, 'Auto': 8.76, 'CCWM': 15.275, 'TeamName': 'Moline Robo Squad'}, {'TeamNum': 8648, 'OPR': 34.026, 'Auto': 8.986, 'CCWM': -37.528, 'TeamName': 'Manual High School RoboRams'}, {'TeamNum': 21930, 'OPR': 28.919, 'Auto': 8.231, 'CCWM': -45.551, 'TeamName': 'Code Cowboys'}, {'TeamNum': 21824, 'OPR': 15.146, 'Auto': 6.15, 'CCWM': -61.55, 'TeamName': 'Quest Gators'}, {'TeamNum': 9788, 'OPR': 12.529, 'Auto': -1.223, 'CCWM': -63.044, 'TeamName': 'Manual High School RoboRams II'}]
USILPWLT
[{'TeamNum': 15005, 'OPR': 135.149, 'Auto': 22.319, 'CCWM': 84.001, 'TeamName': 'Technophobia'}, {'TeamNum': 14469, 'OPR': 127.459, 'Auto': 37.191, 'CCWM': 48.064, 'TeamName': 'HOW'}, {'TeamNum': 6596, 'OPR': 111.454, 'Auto': 24.191, 'CCWM': 60.66, 'TeamName': 'Robotic Rams'}, {'TeamNum': 16244, 'OPR': 108.65, 'Auto': 21.382, 'CCWM': 2.923, 'TeamName': 'The TrailBlazers'}, {'TeamNum': 10101, 'OPR': 96.037, 'Auto': 21.038, 'CCWM': 49.262, 'TeamName': 'Binary Bullets'}, {'TeamNum': 9189, 'OPR': 68.097, 'Auto': 25.85, 'CCWM': 17.584, 'TeamName': 'All Charged Up'}, {'TeamNum': 8899, 'OPR': 65.548, 'Auto': 26.899, 'CCWM': 27.081, 'TeamName': 'EP Robo Raiders'}, {'TeamNum': 11235, 'OPR': 65.027, 'Auto': 24.042, 'CCWM': -30.531, 'TeamName': 'Retro Robotics'}, {'TeamNum': 16277, 'OPR': 62.445, 'Auto': 21.723, 'CCWM': -16.363, 'TeamName': 'Tekon'}, {'TeamNum': 14167, 'OPR': 60.429, 'Auto': 4.734, 'CCWM': 1.557, 'TeamName': 'The Savage Penguins'}, {'TeamNum': 21592, 'OPR': 49.221, 'Auto': 15.459, 'CCWM': -0.753, 'TeamName': 'FAST BUT NOT FURIOUS'}, {'TeamNum': 15356, 'OPR': 49.116, 'Auto': 8.102, 'CCWM': -17.134, 'TeamName': 'BEASTBOTZ'}, {'TeamNum': 13594, 'OPR': 48.625, 'Auto': 14.734, 'CCWM': -28.28, 'TeamName': 'Sherrard TiGEARS'}, {'TeamNum': 11177, 'OPR': 44.769, 'Auto': 18.323, 'CCWM': 19.328, 'TeamName': 'Gear Grinders'}, {'TeamNum': 3640, 'OPR': 40.071, 'Auto': 1.955, 'CCWM': -24.75, 'TeamName': 'The BoilerBots'}, {'TeamNum': 14723, 'OPR': 38.417, 'Auto': 0.934, 'CCWM': 9.231, 'TeamName': 'Chesterton Robots'}, {'TeamNum': 15387, 'OPR': 36.215, 'Auto': 8.76, 'CCWM': 15.275, 'TeamName': 'Moline Robo Squad'}, {'TeamNum': 8648, 'OPR': 34.026, 'Auto': 8.986, 'CCWM': -37.528, 'TeamName': 'Manual High School RoboRams'}, {'TeamNum': 21930, 'OPR': 28.919, 'Auto': 8.231, 'CCWM': -45.551, 'TeamName': 'Code Cowboys'}, {'TeamNum': 21824, 'OPR': 15.146, 'Auto': 6.15, 'CCWM': -61.55, 'TeamName': 'Quest Gators'}, {'TeamNum': 9788, 'OPR': 12.529, 'Auto': -1.223, 'CCWM': -63.044, 'TeamName': 'Manual High School RoboRams II'}]

i 937
{'2923', '12982', '9929', '11382', '10635', '12606', '19508', '17576', '21333', '10836', '19757', '12868', '9342', '10420', '11392', '19652', '9411', '18149', '19168', '22441', '17335', '10093', '15596', '12679', '10421', '22499', '14683', '18183', '15597', '19720', '21350'}
[{'TeamNum': 9929, 'OPR': 101.381, 'Auto': 23.674, 'CCWM': 85.16, 'TeamName': 'TNT (Tech Ninja Team)'}, {'TeamNum': 11392, 'OPR': 98.795, 'Auto': 29.186, 'CCWM': -18.479, 'TeamName': 'Defenestration'}, {'TeamNum': 12868, 'OPR': 95.225, 'Auto': 13.082, 'CCWM': 71.101, 'TeamName': 'Ironclad'}, {'TeamNum': 19508, 'OPR': 88.978, 'Auto': 15.437, 'CCWM': 17.13, 'TeamName': 'Quackology'}, {'TeamNum': 10635, 'OPR': 86.047, 'Auto': 15.418, 'CCWM': 50.924, 'TeamName': 'Unknown Element'}, {'TeamNum': 19652, 'OPR': 81.162, 'Auto': 12.897, 'CCWM': 82.918, 'TeamName': '7ech!neers'}, {'TeamNum': 19720, 'OPR': 72.99, 'Auto': 15.038, 'CCWM': 30.136, 'TeamName': 'Crowbotics FTC'}, {'TeamNum': 21333, 'OPR': 72.602, 'Auto': 21.978, 'CCWM': 23.127, 'TeamName': 'RoboKnights'}, {'TeamNum': 18183, 'OPR': 72.554, 'Auto': 14.324, 'CCWM': -12.792, 'TeamName': 'Rounded Cube'}, {'TeamNum': 10836, 'OPR': 68.933, 'Auto': 15.678, 'CCWM': 21.219, 'TeamName': 'STEMper Fi'}, {'TeamNum': 19168, 'OPR': 68.309, 'Auto': 14.642, 'CCWM': 24.506, 'TeamName': 'TOTUS 1 TUUS'}, {'TeamNum': 9411, 'OPR': 65.723, 'Auto': 4.637, 'CCWM': 10.701, 'TeamName': 'Rolling Thunder'}, {'TeamNum': 14683, 'OPR': 65.577, 'Auto': 21.347, 'CCWM': 1.568, 'TeamName': 'Lincoln-Way Central Robotics and Engineering Team'}, {'TeamNum': 19757, 'OPR': 62.923, 'Auto': 10.081, 'CCWM': 0.525, 'TeamName': 'WEGO Robotics'}, {'TeamNum': 12606, 'OPR': 61.615, 'Auto': 20.148, 'CCWM': 37.519, 'TeamName': 'WARHOG'}, {'TeamNum': 17335, 'OPR': 58.755, 'Auto': 12.075, 'CCWM': -11.863, 'TeamName': 'Griffins'}, {'TeamNum': 21350, 'OPR': 48.33, 'Auto': 14.784, 'CCWM': 18.383, 'TeamName': 'Team Rocket'}, {'TeamNum': 18149, 'OPR': 42.602, 'Auto': 12.898, 'CCWM': 8.554, 'TeamName': 'Cybernetic Squirrels'}, {'TeamNum': 2923, 'OPR': 38.746, 'Auto': 17.272, 'CCWM': 8.444, 'TeamName': 'Kaybots'}, {'TeamNum': 12679, 'OPR': 35.709, 'Auto': 9.577, 'CCWM': 18.2, 'TeamName': 'Vulcan 2'}, {'TeamNum': 10093, 'OPR': 32.254, 'Auto': 14.844, 'CCWM': -40.969, 'TeamName': 'RoboKays'}, {'TeamNum': 22441, 'OPR': 27.175, 'Auto': 4.01, 'CCWM': -56.411, 'TeamName': 'Blazer Bots'}, {'TeamNum': 12982, 'OPR': 25.711, 'Auto': 10.43, 'CCWM': -45.945, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 9342, 'OPR': 24.555, 'Auto': -1.301, 'CCWM': -35.61, 'TeamName': 'The Incredibots'}, {'TeamNum': 17576, 'OPR': 21.877, 'Auto': -3.644, 'CCWM': -53.27, 'TeamName': 'TITANS (Tomorrow’s Innovators and Thinkers Acquiring New Skills).'}, {'TeamNum': 10421, 'OPR': 21.348, 'Auto': -0.61, 'CCWM': -14.142, 'TeamName': 'Kay Tech'}, {'TeamNum': 22499, 'OPR': 14.642, 'Auto': -4.859, 'CCWM': -48.092, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 11382, 'OPR': 9.106, 'Auto': 5.739, 'CCWM': -109.872, 'TeamName': 'D92 Vulcan'}, {'TeamNum': 10420, 'OPR': 7.728, 'Auto': 11.328, 'CCWM': -57.422, 'TeamName': 'Mechanized Kay-OS'}, {'TeamNum': 15596, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Robo Wildcats'}, {'TeamNum': 15597, 'OPR': 0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Robo Wildcats'}]
USILCSSLT
[{'TeamNum': 9929, 'OPR': 101.381, 'Auto': 23.674, 'CCWM': 85.16, 'TeamName': 'TNT (Tech Ninja Team)'}, {'TeamNum': 11392, 'OPR': 98.795, 'Auto': 29.186, 'CCWM': -18.479, 'TeamName': 'Defenestration'}, {'TeamNum': 12868, 'OPR': 95.225, 'Auto': 13.082, 'CCWM': 71.101, 'TeamName': 'Ironclad'}, {'TeamNum': 19508, 'OPR': 88.978, 'Auto': 15.437, 'CCWM': 17.13, 'TeamName': 'Quackology'}, {'TeamNum': 10635, 'OPR': 86.047, 'Auto': 15.418, 'CCWM': 50.924, 'TeamName': 'Unknown Element'}, {'TeamNum': 19652, 'OPR': 81.162, 'Auto': 12.897, 'CCWM': 82.918, 'TeamName': '7ech!neers'}, {'TeamNum': 19720, 'OPR': 72.99, 'Auto': 15.038, 'CCWM': 30.136, 'TeamName': 'Crowbotics FTC'}, {'TeamNum': 21333, 'OPR': 72.602, 'Auto': 21.978, 'CCWM': 23.127, 'TeamName': 'RoboKnights'}, {'TeamNum': 18183, 'OPR': 72.554, 'Auto': 14.324, 'CCWM': -12.792, 'TeamName': 'Rounded Cube'}, {'TeamNum': 10836, 'OPR': 68.933, 'Auto': 15.678, 'CCWM': 21.219, 'TeamName': 'STEMper Fi'}, {'TeamNum': 19168, 'OPR': 68.309, 'Auto': 14.642, 'CCWM': 24.506, 'TeamName': 'TOTUS 1 TUUS'}, {'TeamNum': 9411, 'OPR': 65.723, 'Auto': 4.637, 'CCWM': 10.701, 'TeamName': 'Rolling Thunder'}, {'TeamNum': 14683, 'OPR': 65.577, 'Auto': 21.347, 'CCWM': 1.568, 'TeamName': 'Lincoln-Way Central Robotics and Engineering Team'}, {'TeamNum': 19757, 'OPR': 62.923, 'Auto': 10.081, 'CCWM': 0.525, 'TeamName': 'WEGO Robotics'}, {'TeamNum': 12606, 'OPR': 61.615, 'Auto': 20.148, 'CCWM': 37.519, 'TeamName': 'WARHOG'}, {'TeamNum': 17335, 'OPR': 58.755, 'Auto': 12.075, 'CCWM': -11.863, 'TeamName': 'Griffins'}, {'TeamNum': 21350, 'OPR': 48.33, 'Auto': 14.784, 'CCWM': 18.383, 'TeamName': 'Team Rocket'}, {'TeamNum': 18149, 'OPR': 42.602, 'Auto': 12.898, 'CCWM': 8.554, 'TeamName': 'Cybernetic Squirrels'}, {'TeamNum': 2923, 'OPR': 38.746, 'Auto': 17.272, 'CCWM': 8.444, 'TeamName': 'Kaybots'}, {'TeamNum': 12679, 'OPR': 35.709, 'Auto': 9.577, 'CCWM': 18.2, 'TeamName': 'Vulcan 2'}, {'TeamNum': 10093, 'OPR': 32.254, 'Auto': 14.844, 'CCWM': -40.969, 'TeamName': 'RoboKays'}, {'TeamNum': 22441, 'OPR': 27.175, 'Auto': 4.01, 'CCWM': -56.411, 'TeamName': 'Blazer Bots'}, {'TeamNum': 12982, 'OPR': 25.711, 'Auto': 10.43, 'CCWM': -45.945, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 9342, 'OPR': 24.555, 'Auto': -1.301, 'CCWM': -35.61, 'TeamName': 'The Incredibots'}, {'TeamNum': 17576, 'OPR': 21.877, 'Auto': -3.644, 'CCWM': -53.27, 'TeamName': 'TITANS (Tomorrow’s Innovators and Thinkers Acquiring New Skills).'}, {'TeamNum': 10421, 'OPR': 21.348, 'Auto': -0.61, 'CCWM': -14.142, 'TeamName': 'Kay Tech'}, {'TeamNum': 22499, 'OPR': 14.642, 'Auto': -4.859, 'CCWM': -48.092, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 11382, 'OPR': 9.106, 'Auto': 5.739, 'CCWM': -109.872, 'TeamName': 'D92 Vulcan'}, {'TeamNum': 10420, 'OPR': 7.728, 'Auto': 11.328, 'CCWM': -57.422, 'TeamName': 'Mechanized Kay-OS'}, {'TeamNum': 15596, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Robo Wildcats'}, {'TeamNum': 15597, 'OPR': 0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Robo Wildcats'}]
i 938
{'20430', '6518', '13402', '16501', '19932', '5300', '22331', '21931', '18686', '13414', '12130', '14596', '5543', '4366', '18174', '20045', '21624'}
[{'TeamNum': 14596, 'OPR': 114.751, 'Auto': 21.116, 'CCWM': 102.575, 'TeamName': 'XLR8'}, {'TeamNum': 16501, 'OPR': 103.891, 'Auto': 16.693, 'CCWM': 53.956, 'TeamName': 'Squirrel!'}, {'TeamNum': 20430, 'OPR': 100.125, 'Auto': 13.167, 'CCWM': 78.395, 'TeamName': 'Heroes'}, {'TeamNum': 18174, 'OPR': 85.367, 'Auto': 19.989, 'CCWM': 43.761, 'TeamName': 'MISHines'}, {'TeamNum': 4366, 'OPR': 46.651, 'Auto': 2.614, 'CCWM': 23.795, 'TeamName': 'Westside Gold'}, {'TeamNum': 13414, 'OPR': 38.383, 'Auto': 13.463, 'CCWM': -8.539, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 21931, 'OPR': 37.494, 'Auto': 10.434, 'CCWM': -21.135, 'TeamName': 'Westside Gray'}, {'TeamNum': 21624, 'OPR': 32.7, 'Auto': 2.093, 'CCWM': -30.416, 'TeamName': 'Titans'}, {'TeamNum': 19932, 'OPR': 23.947, 'Auto': 7.193, 'CCWM': -20.27, 'TeamName': 'Westside Red'}, {'TeamNum': 5543, 'OPR': 23.711, 'Auto': 3.269, 'CCWM': 14.572, 'TeamName': 'Team X'}, {'TeamNum': 22331, 'OPR': 21.443, 'Auto': 5.055, 'CCWM': -27.101, 'TeamName': 'random()'}, {'TeamNum': 12130, 'OPR': 17.89, 'Auto': -1.785, 'CCWM': -18.829, 'TeamName': 'Capy Bara'}, {'TeamNum': 5300, 'OPR': 17.21, 'Auto': 2.998, 'CCWM': -15.902, 'TeamName': 'The Dirty Dozen'}, {'TeamNum': 13402, 'OPR': 9.823, 'Auto': 3.375, 'CCWM': -65.085, 'TeamName': 'Team with No Name'}, {'TeamNum': 6518, 'OPR': 9.752, 'Auto': 3.303, 'CCWM': -27.77, 'TeamName': 'Westside Black'}, {'TeamNum': 20045, 'OPR': 6.784, 'Auto': -3.954, 'CCWM': -39.355, 'TeamName': 'Grey Fox'}, {'TeamNum': 18686, 'OPR': -3.719, 'Auto': -0.507, 'CCWM': -54.65, 'TeamName': 'Hog Riders'}]
USINNCLT
[{'TeamNum': 14596, 'OPR': 114.751, 'Auto': 21.116, 'CCWM': 102.575, 'TeamName': 'XLR8'}, {'TeamNum': 16501, 'OPR': 103.891, 'Auto': 16.693, 'CCWM': 53.956, 'TeamName': 'Squirrel!'}, {'TeamNum': 20430, 'OPR': 100.125, 'Auto': 13.167, 'CCWM': 78.395, 'TeamName': 'Heroes'}, {'TeamNum': 18174, 'OPR': 85.367, 'Auto': 19.989, 'CCWM': 43.761, 'TeamName': 'MISHines'}, {'TeamNum': 4366, 'OPR': 46.651, 'Auto': 2.614, 'CCWM': 23.795, 'TeamName': 'Westside Gold'}, {'TeamNum': 13414, 'OPR': 38.383, 'Auto': 13.463, 'CCWM': -8.539, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 21931, 'OPR': 37.494, 'Auto': 10.434, 'CCWM': -21.135, 'TeamName': 'Westside Gray'}, {'TeamNum': 21624, 'OPR': 32.7, 'Auto': 2.093, 'CCWM': -30.416, 'TeamName': 'Titans'}, {'TeamNum': 19932, 'OPR': 23.947, 'Auto': 7.193, 'CCWM': -20.27, 'TeamName': 'Westside Red'}, {'TeamNum': 5543, 'OPR': 23.711, 'Auto': 3.269, 'CCWM': 14.572, 'TeamName': 'Team X'}, {'TeamNum': 22331, 'OPR': 21.443, 'Auto': 5.055, 'CCWM': -27.101, 'TeamName': 'random()'}, {'TeamNum': 12130, 'OPR': 17.89, 'Auto': -1.785, 'CCWM': -18.829, 'TeamName': 'Capy Bara'}, {'TeamNum': 5300, 'OPR': 17.21, 'Auto': 2.998, 'CCWM': -15.902, 'TeamName': 'The Dirty Dozen'}, {'TeamNum': 13402, 'OPR': 9.823, 'Auto': 3.375, 'CCWM': -65.085, 'TeamName': 'Team with No Name'}, {'TeamNum': 6518, 'OPR': 9.752, 'Auto': 3.303, 'CCWM': -27.77, 'TeamName': 'Westside Black'}, {'TeamNum': 20045, 'OPR': 6.784, 'Auto': -3.954, 'CCWM': -39.355, 'TeamName': 'Grey Fox'}, {'TeamNum': 18686, 'OPR': -3.719, 'Auto': -0.507, 'CCWM': -54.65, 'TeamName': 'Hog Riders'}]

i 939
{'6448', '18380', '15284', '14374', '19137', '22013', '21821', '20143', '18280', '9768', '11200'}
[{'TeamNum': 18380, 'OPR': 92.722, 'Auto': 24.363, 'CCWM': 82.769, 'TeamName': 'Stinger Robotics Team Hive'}, {'TeamNum': 14374, 'OPR': 86.025, 'Auto': 13.414, 'CCWM': 74.009, 'TeamName': 'Dark Matter'}, {'TeamNum': 6448, 'OPR': 54.201, 'Auto': 22.244, 'CCWM': 33.212, 'TeamName': 'Blue Jays'}, {'TeamNum': 20143, 'OPR': 47.179, 'Auto': 14.892, 'CCWM': 18.393, 'TeamName': 'Stinger Robotics Team Swarm'}, {'TeamNum': 11200, 'OPR': 34.848, 'Auto': 3.103, 'CCWM': 9.349, 'TeamName': 'Phenomena'}, {'TeamNum': 9768, 'OPR': 33.133, 'Auto': 7.913, 'CCWM': 2.08, 'TeamName': 'Steel Eagles'}, {'TeamNum': 18280, 'OPR': 29.428, 'Auto': 4.483, 'CCWM': -29.041, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 19137, 'OPR': 13.12, 'Auto': -0.271, 'CCWM': -45.31, 'TeamName': 'CyberGriffs'}, {'TeamNum': 15284, 'OPR': 11.25, 'Auto': -0.239, 'CCWM': -35.742, 'TeamName': 'St. Thomas More Catholic High School'}, {'TeamNum': 21821, 'OPR': 4.822, 'Auto': -0.81, 'CCWM': -53.048, 'TeamName': 'SciPort Sci-bots'}, {'TeamNum': 22013, 'OPR': 1.367, 'Auto': -1.368, 'CCWM': -53.781, 'TeamName': 'ARC - Albany Robotics Club'}]
USLAALQ
[{'TeamNum': 18380, 'OPR': 92.722, 'Auto': 24.363, 'CCWM': 82.769, 'TeamName': 'Stinger Robotics Team Hive'}, {'TeamNum': 14374, 'OPR': 86.025, 'Auto': 13.414, 'CCWM': 74.009, 'TeamName': 'Dark Matter'}, {'TeamNum': 6448, 'OPR': 54.201, 'Auto': 22.244, 'CCWM': 33.212, 'TeamName': 'Blue Jays'}, {'TeamNum': 20143, 'OPR': 47.179, 'Auto': 14.892, 'CCWM': 18.393, 'TeamName': 'Stinger Robotics Team Swarm'}, {'TeamNum': 11200, 'OPR': 34.848, 'Auto': 3.103, 'CCWM': 9.349, 'TeamName': 'Phenomena'}, {'TeamNum': 9768, 'OPR': 33.133, 'Auto': 7.913, 'CCWM': 2.08, 'TeamName': 'Steel Eagles'}, {'TeamNum': 18280, 'OPR': 29.428, 'Auto': 4.483, 'CCWM': -29.041, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 19137, 'OPR': 13.12, 'Auto': -0.271, 'CCWM': -45.31, 'TeamName': 'CyberGriffs'}, {'TeamNum': 15284, 'OPR': 11.25, 'Auto': -0.239, 'CCWM': -35.742, 'TeamName': 'St. Thomas More Catholic High School'}, {'TeamNum': 21821, 'OPR': 4.822, 'Auto': -0.81, 'CCWM': -53.048, 'TeamName': 'SciPort Sci-bots'}, {'TeamNum': 22013, 'OPR': 1.367, 'Auto': -1.368, 'CCWM': -53.781, 'TeamName': 'ARC - Albany Robotics Club'}]
i 940
{'16704', '19667', '133', '14273', '17218', '20808', '16773', '3737', '1', '18489', '13620', '19556', '20409', '9725', '20613', '19460'}
[{'TeamNum': 14273, 'OPR': 71.859, 'Auto': 7.836, 'CCWM': 59.803, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 9725, 'OPR': 52.929, 'Auto': 4.795, 'CCWM': 12.208, 'TeamName': 'Clockwork Cardinals'}, {'TeamNum': 133, 'OPR': 41.673, 'Auto': 17.082, 'CCWM': 7.789, 'TeamName': 'Arrows'}, {'TeamNum': 16773, 'OPR': 38.46, 'Auto': 5.031, 'CCWM': 29.57, 'TeamName': 'LCA Li-ions'}, {'TeamNum': 19667, 'OPR': 38.411, 'Auto': 8.166, 'CCWM': -5.951, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 20808, 'OPR': 34.942, 'Auto': 14.087, 'CCWM': -12.982, 'TeamName': 'Spartans'}, {'TeamNum': 19460, 'OPR': 32.179, 'Auto': 1.791, 'CCWM': 16.983, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 1, 'OPR': 31.535, 'Auto': 0.381, 'CCWM': 3.964, 'TeamName': 'Team Unlimited'}, {'TeamNum': 13620, 'OPR': 31.313, 'Auto': 1.934, 'CCWM': 15.167, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 19556, 'OPR': 31.025, 'Auto': 10.843, 'CCWM': -0.001, 'TeamName': 'Arrow'}, {'TeamNum': 17218, 'OPR': 29.089, 'Auto': 5.818, 'CCWM': -6.696, 'TeamName': 'Brookline Bots'}, {'TeamNum': 3737, 'OPR': 27.381, 'Auto': -2.61, 'CCWM': -19.627, 'TeamName': "Hank's Tanks"}, {'TeamNum': 18489, 'OPR': 24.806, 'Auto': 9.349, 'CCWM': -43.36, 'TeamName': 'Bishop Connolly Cougars'}, {'TeamNum': 20409, 'OPR': 11.755, 'Auto': 1.151, 'CCWM': -42.299, 'TeamName': 'The Winsor Wirecats'}, {'TeamNum': 16704, 'OPR': 11.227, 'Auto': -6.193, 'CCWM': 6.548, 'TeamName': 'Nano Hornets'}, {'TeamNum': 20613, 'OPR': -0.25, 'Auto': -4.958, 'CCWM': -21.116, 'TeamName': 'Minnechaug Tech'}]
USMANEQ
[{'TeamNum': 14273, 'OPR': 71.859, 'Auto': 7.836, 'CCWM': 59.803, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 9725, 'OPR': 52.929, 'Auto': 4.795, 'CCWM': 12.208, 'TeamName': 'Clockwork Cardinals'}, {'TeamNum': 133, 'OPR': 41.673, 'Auto': 17.082, 'CCWM': 7.789, 'TeamName': 'Arrows'}, {'TeamNum': 16773, 'OPR': 38.46, 'Auto': 5.031, 'CCWM': 29.57, 'TeamName': 'LCA Li-ions'}, {'TeamNum': 19667, 'OPR': 38.411, 'Auto': 8.166, 'CCWM': -5.951, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 20808, 'OPR': 34.942, 'Auto': 14.087, 'CCWM': -12.982, 'TeamName': 'Spartans'}, {'TeamNum': 19460, 'OPR': 32.179, 'Auto': 1.791, 'CCWM': 16.983, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 1, 'OPR': 31.535, 'Auto': 0.381, 'CCWM': 3.964, 'TeamName': 'Team Unlimited'}, {'TeamNum': 13620, 'OPR': 31.313, 'Auto': 1.934, 'CCWM': 15.167, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 19556, 'OPR': 31.025, 'Auto': 10.843, 'CCWM': -0.001, 'TeamName': 'Arrow'}, {'TeamNum': 17218, 'OPR': 29.089, 'Auto': 5.818, 'CCWM': -6.696, 'TeamName': 'Brookline Bots'}, {'TeamNum': 3737, 'OPR': 27.381, 'Auto': -2.61, 'CCWM': -19.627, 'TeamName': "Hank's Tanks"}, {'TeamNum': 18489, 'OPR': 24.806, 'Auto': 9.349, 'CCWM': -43.36, 'TeamName': 'Bishop Connolly Cougars'}, {'TeamNum': 20409, 'OPR': 11.755, 'Auto': 1.151, 'CCWM': -42.299, 'TeamName': 'The Winsor Wirecats'}, {'TeamNum': 16704, 'OPR': 11.227, 'Auto': -6.193, 'CCWM': 6.548, 'TeamName': 'Nano Hornets'}, {'TeamNum': 20613, 'OPR': -0.25, 'Auto': -4.958, 'CCWM': -21.116, 'TeamName': 'Minnechaug Tech'}]
i 941
{'20696', '8644', '20290', '15643', '11723', '22618', '10560', '6040', '8379', '10331', '12956', '13848', '14864', '16921', '4029', '4410', '14666', '5273'}
[{'TeamNum': 8644, 'OPR': 165.261, 'Auto': 39.43, 'CCWM': 114.288, 'TeamName': 'The Brainstormers'}, {'TeamNum': 8379, 'OPR': 78.552, 'Auto': 14.593, 'CCWM': 40.912, 'TeamName': 'The Parity Bits'}, {'TeamNum': 4410, 'OPR': 57.754, 'Auto': 7.985, 'CCWM': 6.953, 'TeamName': 'ARC Lightning'}, {'TeamNum': 16921, 'OPR': 56.481, 'Auto': 19.934, 'CCWM': 20.398, 'TeamName': 'MS Wildcats Apollo'}, {'TeamNum': 4029, 'OPR': 53.768, 'Auto': 7.25, 'CCWM': 7.105, 'TeamName': '2 Bits and a Byte'}, {'TeamNum': 14666, 'OPR': 53.037, 'Auto': 2.159, 'CCWM': 12.909, 'TeamName': 'Inverse Polarity FTC'}, {'TeamNum': 20290, 'OPR': 47.191, 'Auto': 12.396, 'CCWM': -4.31, 'TeamName': 'Boston Basketbots'}, {'TeamNum': 22618, 'OPR': 44.308, 'Auto': -1.476, 'CCWM': 14.869, 'TeamName': 'MS Robotics Artemis'}, {'TeamNum': 5273, 'OPR': 32.342, 'Auto': 7.079, 'CCWM': 16.021, 'TeamName': 'ARC Thunder'}, {'TeamNum': 10560, 'OPR': 32.17, 'Auto': 6.819, 'CCWM': -2.553, 'TeamName': 'Robo Hawks'}, {'TeamNum': 13848, 'OPR': 30.542, 'Auto': 0.143, 'CCWM': -14.333, 'TeamName': "The 'Rock Bots 2.0"}, {'TeamNum': 11723, 'OPR': 21.886, 'Auto': 14.67, 'CCWM': -36.428, 'TeamName': 'Canton GearHounds'}, {'TeamNum': 15643, 'OPR': 21.752, 'Auto': 0.267, 'CCWM': -4.836, 'TeamName': "The 'Rock Bots"}, {'TeamNum': 12956, 'OPR': 21.057, 'Auto': 3.132, 'CCWM': -32.765, 'TeamName': 'Lakerbots'}, {'TeamNum': 20696, 'OPR': 16.817, 'Auto': -0.891, 'CCWM': -41.502, 'TeamName': 'Uxbridge Robotics'}, {'TeamNum': 6040, 'OPR': 16.146, 'Auto': -3.539, 'CCWM': 12.787, 'TeamName': 'Canton Robodogs'}, {'TeamNum': 14864, 'OPR': 11.842, 'Auto': 0.182, 'CCWM': -55.098, 'TeamName': 'Wilmington Wired WildCat'}, {'TeamNum': 10331, 'OPR': 6.262, 'Auto': 0.701, 'CCWM': -54.418, 'TeamName': 'ARC Hailstorm '}]
USMANEQ2
[{'TeamNum': 8644, 'OPR': 165.261, 'Auto': 39.43, 'CCWM': 114.288, 'TeamName': 'The Brainstormers'}, {'TeamNum': 8379, 'OPR': 78.552, 'Auto': 14.593, 'CCWM': 40.912, 'TeamName': 'The Parity Bits'}, {'TeamNum': 4410, 'OPR': 57.754, 'Auto': 7.985, 'CCWM': 6.953, 'TeamName': 'ARC Lightning'}, {'TeamNum': 16921, 'OPR': 56.481, 'Auto': 19.934, 'CCWM': 20.398, 'TeamName': 'MS Wildcats Apollo'}, {'TeamNum': 4029, 'OPR': 53.768, 'Auto': 7.25, 'CCWM': 7.105, 'TeamName': '2 Bits and a Byte'}, {'TeamNum': 14666, 'OPR': 53.037, 'Auto': 2.159, 'CCWM': 12.909, 'TeamName': 'Inverse Polarity FTC'}, {'TeamNum': 20290, 'OPR': 47.191, 'Auto': 12.396, 'CCWM': -4.31, 'TeamName': 'Boston Basketbots'}, {'TeamNum': 22618, 'OPR': 44.308, 'Auto': -1.476, 'CCWM': 14.869, 'TeamName': 'MS Robotics Artemis'}, {'TeamNum': 5273, 'OPR': 32.342, 'Auto': 7.079, 'CCWM': 16.021, 'TeamName': 'ARC Thunder'}, {'TeamNum': 10560, 'OPR': 32.17, 'Auto': 6.819, 'CCWM': -2.553, 'TeamName': 'Robo Hawks'}, {'TeamNum': 13848, 'OPR': 30.542, 'Auto': 0.143, 'CCWM': -14.333, 'TeamName': "The 'Rock Bots 2.0"}, {'TeamNum': 11723, 'OPR': 21.886, 'Auto': 14.67, 'CCWM': -36.428, 'TeamName': 'Canton GearHounds'}, {'TeamNum': 15643, 'OPR': 21.752, 'Auto': 0.267, 'CCWM': -4.836, 'TeamName': "The 'Rock Bots"}, {'TeamNum': 12956, 'OPR': 21.057, 'Auto': 3.132, 'CCWM': -32.765, 'TeamName': 'Lakerbots'}, {'TeamNum': 20696, 'OPR': 16.817, 'Auto': -0.891, 'CCWM': -41.502, 'TeamName': 'Uxbridge Robotics'}, {'TeamNum': 6040, 'OPR': 16.146, 'Auto': -3.539, 'CCWM': 12.787, 'TeamName': 'Canton Robodogs'}, {'TeamNum': 14864, 'OPR': 11.842, 'Auto': 0.182, 'CCWM': -55.098, 'TeamName': 'Wilmington Wired WildCat'}, {'TeamNum': 10331, 'OPR': 6.262, 'Auto': 0.701, 'CCWM': -54.418, 'TeamName': 'ARC Hailstorm '}]

i 942
{'8395', '13463', '20127', '7631', '14607', '21774', '5233', '20343', '18602', '21310', '21442', '7518', '20123', '14315', '10216', '6406', '14169', '17394', '9667', '9530', '17219', '19818', '21359', '7519', '11525', '16789', '21828', '4234', '17080', '4451', '5225', '19642', '22554', '18230', '12847', '5014'}
[{'TeamNum': 17080, 'OPR': 111.46, 'Auto': 40.589, 'CCWM': 74.961, 'TeamName': 'NewT.exe'}, {'TeamNum': 21774, 'OPR': 102.813, 'Auto': 21.985, 'CCWM': 84.401, 'TeamName': 'Supernova.exe'}, {'TeamNum': 5233, 'OPR': 85.3, 'Auto': 15.248, 'CCWM': 33.986, 'TeamName': 'Vector'}, {'TeamNum': 19818, 'OPR': 72.239, 'Auto': 10.44, 'CCWM': 4.104, 'TeamName': 'Jade Innovations'}, {'TeamNum': 18602, 'OPR': 71.866, 'Auto': 10.835, 'CCWM': -4.117, 'TeamName': 'Reboot'}, {'TeamNum': 21310, 'OPR': 64.878, 'Auto': 19.255, 'CCWM': 42.557, 'TeamName': 'nexUs'}, {'TeamNum': 14607, 'OPR': 63.918, 'Auto': 5.806, 'CCWM': 33.382, 'TeamName': 'Robot Uprising'}, {'TeamNum': 21359, 'OPR': 62.843, 'Auto': 12.147, 'CCWM': 9.39, 'TeamName': 'Stardroids'}, {'TeamNum': 4234, 'OPR': 61.52, 'Auto': 11.915, 'CCWM': 37.118, 'TeamName': 'Engineered Chaos'}, {'TeamNum': 9530, 'OPR': 60.673, 'Auto': 5.049, 'CCWM': 80.48, 'TeamName': 'Honey Nut Gearios'}, {'TeamNum': 17219, 'OPR': 60.156, 'Auto': -1.218, 'CCWM': 23.498, 'TeamName': 'SpiderBits'}, {'TeamNum': 8395, 'OPR': 57.491, 'Auto': 23.133, 'CCWM': -7.943, 'TeamName': 'The A-Team'}, {'TeamNum': 14169, 'OPR': 56.744, 'Auto': 11.843, 'CCWM': -16.683, 'TeamName': 'BC4H  Partytime ^s'}, {'TeamNum': 4451, 'OPR': 53.45, 'Auto': 8.181, 'CCWM': 32.717, 'TeamName': 'FireFoxes'}, {'TeamNum': 12847, 'OPR': 50.421, 'Auto': 15.883, 'CCWM': 1.356, 'TeamName': 'ERA'}, {'TeamNum': 5225, 'OPR': 48.221, 'Auto': 5.361, 'CCWM': 5.155, 'TeamName': 'Sidwell Varsity'}, {'TeamNum': 7631, 'OPR': 47.35, 'Auto': 11.631, 'CCWM': -14.96, 'TeamName': 'Instant Oats'}, {'TeamNum': 19642, 'OPR': 45.683, 'Auto': 11.817, 'CCWM': 9.235, 'TeamName': 'Eagles'}, {'TeamNum': 22554, 'OPR': 45.5, 'Auto': 21.77, 'CCWM': 29.853, 'TeamName': 'Bionic Bears'}, {'TeamNum': 5014, 'OPR': 43.669, 'Auto': 21.652, 'CCWM': -24.653, 'TeamName': 'Future Gadget Lab'}, {'TeamNum': 7518, 'OPR': 43.119, 'Auto': 7.041, 'CCWM': -14.536, 'TeamName': 'QO CouGears'}, {'TeamNum': 7519, 'OPR': 41.404, 'Auto': 3.749, 'CCWM': 4.485, 'TeamName': 'QO CougarBotics'}, {'TeamNum': 16789, 'OPR': 40.858, 'Auto': 13.791, 'CCWM': 40.232, 'TeamName': 'High Point 1st Robotics'}, {'TeamNum': 18230, 'OPR': 36.141, 'Auto': 13.04, 'CCWM': -8.42, 'TeamName': 'luminUs'}, {'TeamNum': 10216, 'OPR': 33.141, 'Auto': 9.943, 'CCWM': 5.507, 'TeamName': 'SpiderByte'}, {'TeamNum': 17394, 'OPR': 27.265, 'Auto': 19.345, 'CCWM': -14.811, 'TeamName': 'Howard Robotics'}, {'TeamNum': 6406, 'OPR': 26.435, 'Auto': 1.211, 'CCWM': -27.27, 'TeamName': 'First Tech Coyotes'}, {'TeamNum': 21828, 'OPR': 21.502, 'Auto': -0.73, 'CCWM': 6.943, 'TeamName': 'Deal Dynamos'}, {'TeamNum': 20123, 'OPR': 20.715, 'Auto': 3.509, 'CCWM': -43.431, 'TeamName': 'Cryptic'}, {'TeamNum': 11525, 'OPR': 20.543, 'Auto': -10.584, 'CCWM': -39.155, 'TeamName': "Minerva's Mechanics"}, {'TeamNum': 14315, 'OPR': 19.896, 'Auto': 11.308, 'CCWM': -65.024, 'TeamName': 'mobiUs'}, {'TeamNum': 20343, 'OPR': 15.039, 'Auto': -4.143, 'CCWM': -46.893, 'TeamName': 'R.I.P. (Robot in Pieces)'}, {'TeamNum': 13463, 'OPR': 12.453, 'Auto': 5.844, 'CCWM': -76.724, 'TeamName': 'Wildecats'}, {'TeamNum': 21442, 'OPR': 6.169, 'Auto': 1.337, 'CCWM': -9.849, 'TeamName': 'RoboX'}, {'TeamNum': 9667, 'OPR': 3.966, 'Auto': -3.329, 'CCWM': -57.521, 'TeamName': 'Bullis Robotics'}, {'TeamNum': 20127, 'OPR': -9.84, 'Auto': -1.453, 'CCWM': -87.369, 'TeamName': "Apollo's Architects"}]
USCHSPOQ
[{'TeamNum': 17080, 'OPR': 111.46, 'Auto': 40.589, 'CCWM': 74.961, 'TeamName': 'NewT.exe'}, {'TeamNum': 21774, 'OPR': 102.813, 'Auto': 21.985, 'CCWM': 84.401, 'TeamName': 'Supernova.exe'}, {'TeamNum': 5233, 'OPR': 85.3, 'Auto': 15.248, 'CCWM': 33.986, 'TeamName': 'Vector'}, {'TeamNum': 19818, 'OPR': 72.239, 'Auto': 10.44, 'CCWM': 4.104, 'TeamName': 'Jade Innovations'}, {'TeamNum': 18602, 'OPR': 71.866, 'Auto': 10.835, 'CCWM': -4.117, 'TeamName': 'Reboot'}, {'TeamNum': 21310, 'OPR': 64.878, 'Auto': 19.255, 'CCWM': 42.557, 'TeamName': 'nexUs'}, {'TeamNum': 14607, 'OPR': 63.918, 'Auto': 5.806, 'CCWM': 33.382, 'TeamName': 'Robot Uprising'}, {'TeamNum': 21359, 'OPR': 62.843, 'Auto': 12.147, 'CCWM': 9.39, 'TeamName': 'Stardroids'}, {'TeamNum': 4234, 'OPR': 61.52, 'Auto': 11.915, 'CCWM': 37.118, 'TeamName': 'Engineered Chaos'}, {'TeamNum': 9530, 'OPR': 60.673, 'Auto': 5.049, 'CCWM': 80.48, 'TeamName': 'Honey Nut Gearios'}, {'TeamNum': 17219, 'OPR': 60.156, 'Auto': -1.218, 'CCWM': 23.498, 'TeamName': 'SpiderBits'}, {'TeamNum': 8395, 'OPR': 57.491, 'Auto': 23.133, 'CCWM': -7.943, 'TeamName': 'The A-Team'}, {'TeamNum': 14169, 'OPR': 56.744, 'Auto': 11.843, 'CCWM': -16.683, 'TeamName': 'BC4H  Partytime ^s'}, {'TeamNum': 4451, 'OPR': 53.45, 'Auto': 8.181, 'CCWM': 32.717, 'TeamName': 'FireFoxes'}, {'TeamNum': 12847, 'OPR': 50.421, 'Auto': 15.883, 'CCWM': 1.356, 'TeamName': 'ERA'}, {'TeamNum': 5225, 'OPR': 48.221, 'Auto': 5.361, 'CCWM': 5.155, 'TeamName': 'Sidwell Varsity'}, {'TeamNum': 7631, 'OPR': 47.35, 'Auto': 11.631, 'CCWM': -14.96, 'TeamName': 'Instant Oats'}, {'TeamNum': 19642, 'OPR': 45.683, 'Auto': 11.817, 'CCWM': 9.235, 'TeamName': 'Eagles'}, {'TeamNum': 22554, 'OPR': 45.5, 'Auto': 21.77, 'CCWM': 29.853, 'TeamName': 'Bionic Bears'}, {'TeamNum': 5014, 'OPR': 43.669, 'Auto': 21.652, 'CCWM': -24.653, 'TeamName': 'Future Gadget Lab'}, {'TeamNum': 7518, 'OPR': 43.119, 'Auto': 7.041, 'CCWM': -14.536, 'TeamName': 'QO CouGears'}, {'TeamNum': 7519, 'OPR': 41.404, 'Auto': 3.749, 'CCWM': 4.485, 'TeamName': 'QO CougarBotics'}, {'TeamNum': 16789, 'OPR': 40.858, 'Auto': 13.791, 'CCWM': 40.232, 'TeamName': 'High Point 1st Robotics'}, {'TeamNum': 18230, 'OPR': 36.141, 'Auto': 13.04, 'CCWM': -8.42, 'TeamName': 'luminUs'}, {'TeamNum': 10216, 'OPR': 33.141, 'Auto': 9.943, 'CCWM': 5.507, 'TeamName': 'SpiderByte'}, {'TeamNum': 17394, 'OPR': 27.265, 'Auto': 19.345, 'CCWM': -14.811, 'TeamName': 'Howard Robotics'}, {'TeamNum': 6406, 'OPR': 26.435, 'Auto': 1.211, 'CCWM': -27.27, 'TeamName': 'First Tech Coyotes'}, {'TeamNum': 21828, 'OPR': 21.502, 'Auto': -0.73, 'CCWM': 6.943, 'TeamName': 'Deal Dynamos'}, {'TeamNum': 20123, 'OPR': 20.715, 'Auto': 3.509, 'CCWM': -43.431, 'TeamName': 'Cryptic'}, {'TeamNum': 11525, 'OPR': 20.543, 'Auto': -10.584, 'CCWM': -39.155, 'TeamName': "Minerva's Mechanics"}, {'TeamNum': 14315, 'OPR': 19.896, 'Auto': 11.308, 'CCWM': -65.024, 'TeamName': 'mobiUs'}, {'TeamNum': 20343, 'OPR': 15.039, 'Auto': -4.143, 'CCWM': -46.893, 'TeamName': 'R.I.P. (Robot in Pieces)'}, {'TeamNum': 13463, 'OPR': 12.453, 'Auto': 5.844, 'CCWM': -76.724, 'TeamName': 'Wildecats'}, {'TeamNum': 21442, 'OPR': 6.169, 'Auto': 1.337, 'CCWM': -9.849, 'TeamName': 'RoboX'}, {'TeamNum': 9667, 'OPR': 3.966, 'Auto': -3.329, 'CCWM': -57.521, 'TeamName': 'Bullis Robotics'}, {'TeamNum': 20127, 'OPR': -9.84, 'Auto': -1.453, 'CCWM': -87.369, 'TeamName': "Apollo's Architects"}]
i 943
{'9849', '16309', '11102', '21858', '18463', '19815', '18464', '13737', '13399', '5227', '22093', '21806', '20218', '18775', '8136', '10127', '21485', '3409', '15504', '13498', '21487', '13435', '12381', '7532', '15583', '9960'}
[{'TeamNum': 16309, 'OPR': 104.181, 'Auto': 25.087, 'CCWM': 73.127, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 10127, 'OPR': 95.055, 'Auto': 21.093, 'CCWM': 64.567, 'TeamName': "Tesla's Knights"}, {'TeamNum': 13737, 'OPR': 82.031, 'Auto': 4.095, 'CCWM': 6.367, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 18463, 'OPR': 79.147, 'Auto': 14.531, 'CCWM': 17.02, 'TeamName': 'Team Rocinante'}, {'TeamNum': 9849, 'OPR': 78.286, 'Auto': 12.054, 'CCWM': 17.565, 'TeamName': 'The Small Fries'}, {'TeamNum': 3409, 'OPR': 70.667, 'Auto': 13.234, 'CCWM': 41.811, 'TeamName': 'Astromechs'}, {'TeamNum': 5227, 'OPR': 68.254, 'Auto': 23.68, 'CCWM': 16.144, 'TeamName': 'Galactech'}, {'TeamNum': 9960, 'OPR': 66.983, 'Auto': 5.524, 'CCWM': -22.013, 'TeamName': 'N.E.R.D.S'}, {'TeamNum': 22093, 'OPR': 55.978, 'Auto': 0.698, 'CCWM': -3.708, 'TeamName': 'BisonBots-Green'}, {'TeamNum': 11102, 'OPR': 51.546, 'Auto': 14.328, 'CCWM': 1.189, 'TeamName': 'Team M.O.R.E. (Marshall Owls Robotics & Engineering)'}, {'TeamNum': 13399, 'OPR': 51.398, 'Auto': 6.661, 'CCWM': 8.29, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 19815, 'OPR': 50.63, 'Auto': 16.852, 'CCWM': 13.845, 'TeamName': 'The Law'}, {'TeamNum': 21858, 'OPR': 48.856, 'Auto': 10.034, 'CCWM': 39.192, 'TeamName': 'Red Shift Rovers'}, {'TeamNum': 21485, 'OPR': 48.169, 'Auto': 14.204, 'CCWM': -21.334, 'TeamName': 'ScrapHeads'}, {'TeamNum': 7532, 'OPR': 46.073, 'Auto': 6.729, 'CCWM': -7.632, 'TeamName': 'The Core in Blue'}, {'TeamNum': 13498, 'OPR': 41.073, 'Auto': 1.421, 'CCWM': -12.31, 'TeamName': 'Robo Hawks'}, {'TeamNum': 15583, 'OPR': 40.097, 'Auto': 4.152, 'CCWM': -24.95, 'TeamName': 'Electric Eagles'}, {'TeamNum': 21487, 'OPR': 36.455, 'Auto': 10.455, 'CCWM': -23.274, 'TeamName': 'BisonBots'}, {'TeamNum': 18464, 'OPR': 36.391, 'Auto': 2.499, 'CCWM': -29.868, 'TeamName': 'Team Serenity'}, {'TeamNum': 8136, 'OPR': 35.697, 'Auto': 10.139, 'CCWM': -21.861, 'TeamName': 'Fire and Ice'}, {'TeamNum': 12381, 'OPR': 34.649, 'Auto': 9.286, 'CCWM': -9.474, 'TeamName': 'Tiger_STEAM Black'}, {'TeamNum': 15504, 'OPR': 33.818, 'Auto': 3.049, 'CCWM': 27.93, 'TeamName': 'Black Drifters 1'}, {'TeamNum': 18775, 'OPR': 29.404, 'Auto': 8.424, 'CCWM': -27.122, 'TeamName': 'St. Joe Circuit Breakers'}, {'TeamNum': 13435, 'OPR': 24.036, 'Auto': 3.547, 'CCWM': -49.177, 'TeamName': 'Tiger_STEAM Gold'}, {'TeamNum': 20218, 'OPR': 20.89, 'Auto': -0.743, 'CCWM': -23.283, 'TeamName': 'Black Drifters 2'}, {'TeamNum': 21806, 'OPR': -3.766, 'Auto': -3.533, 'CCWM': -51.039, 'TeamName': 'Eighty Seven and Running'}]
USMOKSKCELT
[{'TeamNum': 16309, 'OPR': 104.181, 'Auto': 25.087, 'CCWM': 73.127, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 10127, 'OPR': 95.055, 'Auto': 21.093, 'CCWM': 64.567, 'TeamName': "Tesla's Knights"}, {'TeamNum': 13737, 'OPR': 82.031, 'Auto': 4.095, 'CCWM': 6.367, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 18463, 'OPR': 79.147, 'Auto': 14.531, 'CCWM': 17.02, 'TeamName': 'Team Rocinante'}, {'TeamNum': 9849, 'OPR': 78.286, 'Auto': 12.054, 'CCWM': 17.565, 'TeamName': 'The Small Fries'}, {'TeamNum': 3409, 'OPR': 70.667, 'Auto': 13.234, 'CCWM': 41.811, 'TeamName': 'Astromechs'}, {'TeamNum': 5227, 'OPR': 68.254, 'Auto': 23.68, 'CCWM': 16.144, 'TeamName': 'Galactech'}, {'TeamNum': 9960, 'OPR': 66.983, 'Auto': 5.524, 'CCWM': -22.013, 'TeamName': 'N.E.R.D.S'}, {'TeamNum': 22093, 'OPR': 55.978, 'Auto': 0.698, 'CCWM': -3.708, 'TeamName': 'BisonBots-Green'}, {'TeamNum': 11102, 'OPR': 51.546, 'Auto': 14.328, 'CCWM': 1.189, 'TeamName': 'Team M.O.R.E. (Marshall Owls Robotics & Engineering)'}, {'TeamNum': 13399, 'OPR': 51.398, 'Auto': 6.661, 'CCWM': 8.29, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 19815, 'OPR': 50.63, 'Auto': 16.852, 'CCWM': 13.845, 'TeamName': 'The Law'}, {'TeamNum': 21858, 'OPR': 48.856, 'Auto': 10.034, 'CCWM': 39.192, 'TeamName': 'Red Shift Rovers'}, {'TeamNum': 21485, 'OPR': 48.169, 'Auto': 14.204, 'CCWM': -21.334, 'TeamName': 'ScrapHeads'}, {'TeamNum': 7532, 'OPR': 46.073, 'Auto': 6.729, 'CCWM': -7.632, 'TeamName': 'The Core in Blue'}, {'TeamNum': 13498, 'OPR': 41.073, 'Auto': 1.421, 'CCWM': -12.31, 'TeamName': 'Robo Hawks'}, {'TeamNum': 15583, 'OPR': 40.097, 'Auto': 4.152, 'CCWM': -24.95, 'TeamName': 'Electric Eagles'}, {'TeamNum': 21487, 'OPR': 36.455, 'Auto': 10.455, 'CCWM': -23.274, 'TeamName': 'BisonBots'}, {'TeamNum': 18464, 'OPR': 36.391, 'Auto': 2.499, 'CCWM': -29.868, 'TeamName': 'Team Serenity'}, {'TeamNum': 8136, 'OPR': 35.697, 'Auto': 10.139, 'CCWM': -21.861, 'TeamName': 'Fire and Ice'}, {'TeamNum': 12381, 'OPR': 34.649, 'Auto': 9.286, 'CCWM': -9.474, 'TeamName': 'Tiger_STEAM Black'}, {'TeamNum': 15504, 'OPR': 33.818, 'Auto': 3.049, 'CCWM': 27.93, 'TeamName': 'Black Drifters 1'}, {'TeamNum': 18775, 'OPR': 29.404, 'Auto': 8.424, 'CCWM': -27.122, 'TeamName': 'St. Joe Circuit Breakers'}, {'TeamNum': 13435, 'OPR': 24.036, 'Auto': 3.547, 'CCWM': -49.177, 'TeamName': 'Tiger_STEAM Gold'}, {'TeamNum': 20218, 'OPR': 20.89, 'Auto': -0.743, 'CCWM': -23.283, 'TeamName': 'Black Drifters 2'}, {'TeamNum': 21806, 'OPR': -3.766, 'Auto': -3.533, 'CCWM': -51.039, 'TeamName': 'Eighty Seven and Running'}]

i 944
{'12719', '14257', '17637', '8895', '9027', '5404', '7547', '7525', '19968', '13051', '20182', '11684', '6285', '11539', '14186', '4982', '14199', '5703', '288', '8905', '13312', '9792'}
[{'TeamNum': 14186, 'OPR': 96.457, 'Auto': 24.939, 'CCWM': 32.647, 'TeamName': 'P3'}, {'TeamNum': 7525, 'OPR': 95.338, 'Auto': 27.122, 'CCWM': 50.707, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 288, 'OPR': 78.134, 'Auto': 20.112, 'CCWM': 36.907, 'TeamName': 'Spare Parts'}, {'TeamNum': 11684, 'OPR': 74.63, 'Auto': 24.144, 'CCWM': 25.587, 'TeamName': 'GSA Cardinals'}, {'TeamNum': 9027, 'OPR': 69.308, 'Auto': 20.538, 'CCWM': 17.59, 'TeamName': 'Synergistic Effect'}, {'TeamNum': 17637, 'OPR': 68.392, 'Auto': 10.093, 'CCWM': 51.041, 'TeamName': 'Z-Botz'}, {'TeamNum': 20182, 'OPR': 58.974, 'Auto': 19.815, 'CCWM': 25.286, 'TeamName': 'Luna-Techs'}, {'TeamNum': 11539, 'OPR': 46.55, 'Auto': -0.956, 'CCWM': 0.408, 'TeamName': 'Team Voltage'}, {'TeamNum': 9792, 'OPR': 42.702, 'Auto': 16.405, 'CCWM': 4.864, 'TeamName': 'GSA RoboNerds'}, {'TeamNum': 13312, 'OPR': 40.81, 'Auto': -3.351, 'CCWM': 4.97, 'TeamName': 'The Bombers'}, {'TeamNum': 5404, 'OPR': 30.561, 'Auto': 2.328, 'CCWM': -25.823, 'TeamName': 'Titanium Titans'}, {'TeamNum': 8895, 'OPR': 27.511, 'Auto': 12.945, 'CCWM': -33.934, 'TeamName': 'Loose Screws'}, {'TeamNum': 13051, 'OPR': 25.992, 'Auto': -0.812, 'CCWM': -1.532, 'TeamName': 'Servo Stressors'}, {'TeamNum': 5703, 'OPR': 25.25, 'Auto': 12.621, 'CCWM': -23.875, 'TeamName': 'Doppler Effect'}, {'TeamNum': 8905, 'OPR': 24.698, 'Auto': 2.218, 'CCWM': -24.986, 'TeamName': 'Statesbots- Orange'}, {'TeamNum': 19968, 'OPR': 24.574, 'Auto': 9.71, 'CCWM': -4.071, 'TeamName': 'Joebotics White'}, {'TeamNum': 6285, 'OPR': 23.194, 'Auto': 1.678, 'CCWM': -4.422, 'TeamName': 'Statesbots - Black'}, {'TeamNum': 14257, 'OPR': 21.146, 'Auto': 3.585, 'CCWM': -13.827, 'TeamName': 'REBELBOTS'}, {'TeamNum': 4982, 'OPR': 19.938, 'Auto': 1.887, 'CCWM': -3.222, 'TeamName': 'Cafe Bot'}, {'TeamNum': 14199, 'OPR': 19.427, 'Auto': -4.872, 'CCWM': -29.23, 'TeamName': 'FlyBots'}, {'TeamNum': 7547, 'OPR': 18.278, 'Auto': 0.668, 'CCWM': 5.59, 'TeamName': 'JoeBotics Green'}, {'TeamNum': 12719, 'OPR': 3.969, 'Auto': -2.152, 'CCWM': -90.676, 'TeamName': 'Team Titanium'}]
USMOKSSTLSLT
[{'TeamNum': 14186, 'OPR': 96.457, 'Auto': 24.939, 'CCWM': 32.647, 'TeamName': 'P3'}, {'TeamNum': 7525, 'OPR': 95.338, 'Auto': 27.122, 'CCWM': 50.707, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 288, 'OPR': 78.134, 'Auto': 20.112, 'CCWM': 36.907, 'TeamName': 'Spare Parts'}, {'TeamNum': 11684, 'OPR': 74.63, 'Auto': 24.144, 'CCWM': 25.587, 'TeamName': 'GSA Cardinals'}, {'TeamNum': 9027, 'OPR': 69.308, 'Auto': 20.538, 'CCWM': 17.59, 'TeamName': 'Synergistic Effect'}, {'TeamNum': 17637, 'OPR': 68.392, 'Auto': 10.093, 'CCWM': 51.041, 'TeamName': 'Z-Botz'}, {'TeamNum': 20182, 'OPR': 58.974, 'Auto': 19.815, 'CCWM': 25.286, 'TeamName': 'Luna-Techs'}, {'TeamNum': 11539, 'OPR': 46.55, 'Auto': -0.956, 'CCWM': 0.408, 'TeamName': 'Team Voltage'}, {'TeamNum': 9792, 'OPR': 42.702, 'Auto': 16.405, 'CCWM': 4.864, 'TeamName': 'GSA RoboNerds'}, {'TeamNum': 13312, 'OPR': 40.81, 'Auto': -3.351, 'CCWM': 4.97, 'TeamName': 'The Bombers'}, {'TeamNum': 5404, 'OPR': 30.561, 'Auto': 2.328, 'CCWM': -25.823, 'TeamName': 'Titanium Titans'}, {'TeamNum': 8895, 'OPR': 27.511, 'Auto': 12.945, 'CCWM': -33.934, 'TeamName': 'Loose Screws'}, {'TeamNum': 13051, 'OPR': 25.992, 'Auto': -0.812, 'CCWM': -1.532, 'TeamName': 'Servo Stressors'}, {'TeamNum': 5703, 'OPR': 25.25, 'Auto': 12.621, 'CCWM': -23.875, 'TeamName': 'Doppler Effect'}, {'TeamNum': 8905, 'OPR': 24.698, 'Auto': 2.218, 'CCWM': -24.986, 'TeamName': 'Statesbots- Orange'}, {'TeamNum': 19968, 'OPR': 24.574, 'Auto': 9.71, 'CCWM': -4.071, 'TeamName': 'Joebotics White'}, {'TeamNum': 6285, 'OPR': 23.194, 'Auto': 1.678, 'CCWM': -4.422, 'TeamName': 'Statesbots - Black'}, {'TeamNum': 14257, 'OPR': 21.146, 'Auto': 3.585, 'CCWM': -13.827, 'TeamName': 'REBELBOTS'}, {'TeamNum': 4982, 'OPR': 19.938, 'Auto': 1.887, 'CCWM': -3.222, 'TeamName': 'Cafe Bot'}, {'TeamNum': 14199, 'OPR': 19.427, 'Auto': -4.872, 'CCWM': -29.23, 'TeamName': 'FlyBots'}, {'TeamNum': 7547, 'OPR': 18.278, 'Auto': 0.668, 'CCWM': 5.59, 'TeamName': 'JoeBotics Green'}, {'TeamNum': 12719, 'OPR': 3.969, 'Auto': -2.152, 'CCWM': -90.676, 'TeamName': 'Team Titanium'}]
i 945
{'4813', '8717', '12793', '3189', '12114', '4273', '3188', '18240', '7002', '17125', '2879', '54', '6437', '10662', '10731', '22244', '5026', '22737', '4133', '22811', '8271', '16133', '12727', '22520', '19387', '17097', '724'}
[{'TeamNum': 4133, 'OPR': 102.555, 'Auto': 21.915, 'CCWM': 62.236, 'TeamName': 'Fusion'}, {'TeamNum': 5026, 'OPR': 92.349, 'Auto': 20.426, 'CCWM': 54.836, 'TeamName': 'Tesla Coils'}, {'TeamNum': 724, 'OPR': 88.134, 'Auto': 15.17, 'CCWM': 69.066, 'TeamName': 'RedNek Robotics Wun'}, {'TeamNum': 3189, 'OPR': 72.556, 'Auto': 17.444, 'CCWM': 12.929, 'TeamName': 'Rapid Unscheduled Disassembly'}, {'TeamNum': 10662, 'OPR': 72.325, 'Auto': 11.733, 'CCWM': 64.502, 'TeamName': 'Lazer Sharks in Space'}, {'TeamNum': 17097, 'OPR': 64.689, 'Auto': 10.959, 'CCWM': 27.361, 'TeamName': 'Protostars'}, {'TeamNum': 3188, 'OPR': 64.146, 'Auto': 16.858, 'CCWM': 34.029, 'TeamName': 'Squiggle Splat Bang'}, {'TeamNum': 8271, 'OPR': 57.243, 'Auto': -3.628, 'CCWM': 26.291, 'TeamName': 'E-Hackers'}, {'TeamNum': 6437, 'OPR': 54.134, 'Auto': 10.124, 'CCWM': 27.427, 'TeamName': 'Mad Hatters'}, {'TeamNum': 8717, 'OPR': 52.748, 'Auto': 11.175, 'CCWM': 22.325, 'TeamName': 'T Falls Robotics'}, {'TeamNum': 10731, 'OPR': 49.054, 'Auto': 24.394, 'CCWM': -9.748, 'TeamName': 'Radioactive'}, {'TeamNum': 7002, 'OPR': 45.954, 'Auto': 13.487, 'CCWM': 6.814, 'TeamName': 'Couch Potatoes'}, {'TeamNum': 54, 'OPR': 45.884, 'Auto': 17.358, 'CCWM': 0.807, 'TeamName': 'Gr3y Matt3r'}, {'TeamNum': 12114, 'OPR': 41.78, 'Auto': 13.839, 'CCWM': -13.382, 'TeamName': 'Husky Robotics'}, {'TeamNum': 4273, 'OPR': 41.248, 'Auto': 9.944, 'CCWM': -10.162, 'TeamName': 'Aluminati'}, {'TeamNum': 4813, 'OPR': 36.433, 'Auto': -0.74, 'CCWM': -0.791, 'TeamName': 'EngiNERDS'}, {'TeamNum': 18240, 'OPR': 33.39, 'Auto': 4.048, 'CCWM': -30.614, 'TeamName': 'RoboScout Squad'}, {'TeamNum': 22811, 'OPR': 28.866, 'Auto': 14.368, 'CCWM': -26.388, 'TeamName': "Panther's Robotics Team (PRT)"}, {'TeamNum': 22244, 'OPR': 28.645, 'Auto': 14.316, 'CCWM': -29.349, 'TeamName': 'Nebula'}, {'TeamNum': 17125, 'OPR': 17.035, 'Auto': 0.045, 'CCWM': -41.186, 'TeamName': 'Reboot'}, {'TeamNum': 19387, 'OPR': 16.73, 'Auto': -3.723, 'CCWM': -15.664, 'TeamName': 'Lodge Grass Tech Team 2'}, {'TeamNum': 12793, 'OPR': 15.75, 'Auto': 8.3, 'CCWM': -50.34, 'TeamName': 'FB3'}, {'TeamNum': 16133, 'OPR': 13.759, 'Auto': -7.354, 'CCWM': -11.105, 'TeamName': 'Talk NERDY 2 me'}, {'TeamNum': 12727, 'OPR': 10.81, 'Auto': -2.303, 'CCWM': -19.042, 'TeamName': 'Identity Crisis'}, {'TeamNum': 22520, 'OPR': 7.608, 'Auto': 2.902, 'CCWM': -43.066, 'TeamName': 'Prairie Boys Robotics'}, {'TeamNum': 22737, 'OPR': 3.457, 'Auto': -13.742, 'CCWM': -49.168, 'TeamName': 'Libby Loggers'}, {'TeamNum': 2879, 'OPR': 1.195, 'Auto': -7.492, 'CCWM': -50.002, 'TeamName': 'Technical Difficulty'}]
USMTCMP
[{'TeamNum': 4133, 'OPR': 102.555, 'Auto': 21.915, 'CCWM': 62.236, 'TeamName': 'Fusion'}, {'TeamNum': 5026, 'OPR': 92.349, 'Auto': 20.426, 'CCWM': 54.836, 'TeamName': 'Tesla Coils'}, {'TeamNum': 724, 'OPR': 88.134, 'Auto': 15.17, 'CCWM': 69.066, 'TeamName': 'RedNek Robotics Wun'}, {'TeamNum': 3189, 'OPR': 72.556, 'Auto': 17.444, 'CCWM': 12.929, 'TeamName': 'Rapid Unscheduled Disassembly'}, {'TeamNum': 10662, 'OPR': 72.325, 'Auto': 11.733, 'CCWM': 64.502, 'TeamName': 'Lazer Sharks in Space'}, {'TeamNum': 17097, 'OPR': 64.689, 'Auto': 10.959, 'CCWM': 27.361, 'TeamName': 'Protostars'}, {'TeamNum': 3188, 'OPR': 64.146, 'Auto': 16.858, 'CCWM': 34.029, 'TeamName': 'Squiggle Splat Bang'}, {'TeamNum': 8271, 'OPR': 57.243, 'Auto': -3.628, 'CCWM': 26.291, 'TeamName': 'E-Hackers'}, {'TeamNum': 6437, 'OPR': 54.134, 'Auto': 10.124, 'CCWM': 27.427, 'TeamName': 'Mad Hatters'}, {'TeamNum': 8717, 'OPR': 52.748, 'Auto': 11.175, 'CCWM': 22.325, 'TeamName': 'T Falls Robotics'}, {'TeamNum': 10731, 'OPR': 49.054, 'Auto': 24.394, 'CCWM': -9.748, 'TeamName': 'Radioactive'}, {'TeamNum': 7002, 'OPR': 45.954, 'Auto': 13.487, 'CCWM': 6.814, 'TeamName': 'Couch Potatoes'}, {'TeamNum': 54, 'OPR': 45.884, 'Auto': 17.358, 'CCWM': 0.807, 'TeamName': 'Gr3y Matt3r'}, {'TeamNum': 12114, 'OPR': 41.78, 'Auto': 13.839, 'CCWM': -13.382, 'TeamName': 'Husky Robotics'}, {'TeamNum': 4273, 'OPR': 41.248, 'Auto': 9.944, 'CCWM': -10.162, 'TeamName': 'Aluminati'}, {'TeamNum': 4813, 'OPR': 36.433, 'Auto': -0.74, 'CCWM': -0.791, 'TeamName': 'EngiNERDS'}, {'TeamNum': 18240, 'OPR': 33.39, 'Auto': 4.048, 'CCWM': -30.614, 'TeamName': 'RoboScout Squad'}, {'TeamNum': 22811, 'OPR': 28.866, 'Auto': 14.368, 'CCWM': -26.388, 'TeamName': "Panther's Robotics Team (PRT)"}, {'TeamNum': 22244, 'OPR': 28.645, 'Auto': 14.316, 'CCWM': -29.349, 'TeamName': 'Nebula'}, {'TeamNum': 17125, 'OPR': 17.035, 'Auto': 0.045, 'CCWM': -41.186, 'TeamName': 'Reboot'}, {'TeamNum': 19387, 'OPR': 16.73, 'Auto': -3.723, 'CCWM': -15.664, 'TeamName': 'Lodge Grass Tech Team 2'}, {'TeamNum': 12793, 'OPR': 15.75, 'Auto': 8.3, 'CCWM': -50.34, 'TeamName': 'FB3'}, {'TeamNum': 16133, 'OPR': 13.759, 'Auto': -7.354, 'CCWM': -11.105, 'TeamName': 'Talk NERDY 2 me'}, {'TeamNum': 12727, 'OPR': 10.81, 'Auto': -2.303, 'CCWM': -19.042, 'TeamName': 'Identity Crisis'}, {'TeamNum': 22520, 'OPR': 7.608, 'Auto': 2.902, 'CCWM': -43.066, 'TeamName': 'Prairie Boys Robotics'}, {'TeamNum': 22737, 'OPR': 3.457, 'Auto': -13.742, 'CCWM': -49.168, 'TeamName': 'Libby Loggers'}, {'TeamNum': 2879, 'OPR': 1.195, 'Auto': -7.492, 'CCWM': -50.002, 'TeamName': 'Technical Difficulty'}]
i 946

{'11424', '16072', '16461', '20765', '9993', '20766', '731', '5309', '7444', '5064', '20428', '9990', '6183', '16328', '15333', '2901', '21840', '10195', '21829', '11588', '14641', '4622', '22289', '21360', '5881', '5795'}
[{'TeamNum': 5064, 'OPR': 101.393, 'Auto': 26.281, 'CCWM': 75.089, 'TeamName': 'Aperture Science'}, {'TeamNum': 16461, 'OPR': 83.564, 'Auto': -1.897, 'CCWM': 35.917, 'TeamName': 'Infinite Turtles'}, {'TeamNum': 21360, 'OPR': 80.068, 'Auto': 25.782, 'CCWM': 27.647, 'TeamName': 'ThunderBolts'}, {'TeamNum': 16328, 'OPR': 74.703, 'Auto': 13.744, 'CCWM': 67.598, 'TeamName': "Trial n' Error"}, {'TeamNum': 11424, 'OPR': 74.333, 'Auto': 19.473, 'CCWM': 49.062, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 5309, 'OPR': 72.24, 'Auto': 22.152, 'CCWM': 17.145, 'TeamName': 'Plan B'}, {'TeamNum': 5795, 'OPR': 69.425, 'Auto': 25.896, 'CCWM': 2.709, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 16072, 'OPR': 55.924, 'Auto': 9.874, 'CCWM': 5.836, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 2901, 'OPR': 52.984, 'Auto': 3.941, 'CCWM': 20.407, 'TeamName': 'Purple Gears'}, {'TeamNum': 731, 'OPR': 45.488, 'Auto': 18.508, 'CCWM': 47.39, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 21840, 'OPR': 32.546, 'Auto': 0.664, 'CCWM': -18.986, 'TeamName': 'Kearns Robotics'}, {'TeamNum': 11588, 'OPR': 29.038, 'Auto': 5.868, 'CCWM': -21.612, 'TeamName': 'Carpe Diem'}, {'TeamNum': 20766, 'OPR': 26.244, 'Auto': 0.04, 'CCWM': 6.467, 'TeamName': 'Coding Vikings'}, {'TeamNum': 14641, 'OPR': 23.511, 'Auto': 4.659, 'CCWM': -1.411, 'TeamName': 'Panthers '}, {'TeamNum': 6183, 'OPR': 20.531, 'Auto': 8.891, 'CCWM': 5.674, 'TeamName': 'Thunderducks'}, {'TeamNum': 10195, 'OPR': 19.652, 'Auto': -1.275, 'CCWM': -39.973, 'TeamName': 'Night Owls'}, {'TeamNum': 21829, 'OPR': 19.319, 'Auto': -2.875, 'CCWM': -24.095, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 15333, 'OPR': 17.698, 'Auto': -0.664, 'CCWM': -50.584, 'TeamName': 'Code Sisters'}, {'TeamNum': 20428, 'OPR': 14.934, 'Auto': -0.456, 'CCWM': -13.307, 'TeamName': 'South Iredell High School - FUSE'}, {'TeamNum': 9990, 'OPR': 14.152, 'Auto': 0.205, 'CCWM': 0.615, 'TeamName': 'Robo Vikings'}, {'TeamNum': 7444, 'OPR': 9.597, 'Auto': 6.95, 'CCWM': -48.053, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 5881, 'OPR': 7.215, 'Auto': -9.194, 'CCWM': -18.608, 'TeamName': 'Tungsteel'}, {'TeamNum': 9993, 'OPR': 6.068, 'Auto': 10.359, 'CCWM': -47.404, 'TeamName': 'StormBots'}, {'TeamNum': 4622, 'OPR': 4.9, 'Auto': 7.189, 'CCWM': -21.104, 'TeamName': 'L.O.C.S.'}, {'TeamNum': 20765, 'OPR': -3.055, 'Auto': 0.345, 'CCWM': -15.925, 'TeamName': 'Vikings for Technology'}, {'TeamNum': 22289, 'OPR': -5.8, 'Auto': 2.805, 'CCWM': -36.578, 'TeamName': 'Robolobos'}]
USNCWSQ
[{'TeamNum': 5064, 'OPR': 101.393, 'Auto': 26.281, 'CCWM': 75.089, 'TeamName': 'Aperture Science'}, {'TeamNum': 16461, 'OPR': 83.564, 'Auto': -1.897, 'CCWM': 35.917, 'TeamName': 'Infinite Turtles'}, {'TeamNum': 21360, 'OPR': 80.068, 'Auto': 25.782, 'CCWM': 27.647, 'TeamName': 'ThunderBolts'}, {'TeamNum': 16328, 'OPR': 74.703, 'Auto': 13.744, 'CCWM': 67.598, 'TeamName': "Trial n' Error"}, {'TeamNum': 11424, 'OPR': 74.333, 'Auto': 19.473, 'CCWM': 49.062, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 5309, 'OPR': 72.24, 'Auto': 22.152, 'CCWM': 17.145, 'TeamName': 'Plan B'}, {'TeamNum': 5795, 'OPR': 69.425, 'Auto': 25.896, 'CCWM': 2.709, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 16072, 'OPR': 55.924, 'Auto': 9.874, 'CCWM': 5.836, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 2901, 'OPR': 52.984, 'Auto': 3.941, 'CCWM': 20.407, 'TeamName': 'Purple Gears'}, {'TeamNum': 731, 'OPR': 45.488, 'Auto': 18.508, 'CCWM': 47.39, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 21840, 'OPR': 32.546, 'Auto': 0.664, 'CCWM': -18.986, 'TeamName': 'Kearns Robotics'}, {'TeamNum': 11588, 'OPR': 29.038, 'Auto': 5.868, 'CCWM': -21.612, 'TeamName': 'Carpe Diem'}, {'TeamNum': 20766, 'OPR': 26.244, 'Auto': 0.04, 'CCWM': 6.467, 'TeamName': 'Coding Vikings'}, {'TeamNum': 14641, 'OPR': 23.511, 'Auto': 4.659, 'CCWM': -1.411, 'TeamName': 'Panthers '}, {'TeamNum': 6183, 'OPR': 20.531, 'Auto': 8.891, 'CCWM': 5.674, 'TeamName': 'Thunderducks'}, {'TeamNum': 10195, 'OPR': 19.652, 'Auto': -1.275, 'CCWM': -39.973, 'TeamName': 'Night Owls'}, {'TeamNum': 21829, 'OPR': 19.319, 'Auto': -2.875, 'CCWM': -24.095, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 15333, 'OPR': 17.698, 'Auto': -0.664, 'CCWM': -50.584, 'TeamName': 'Code Sisters'}, {'TeamNum': 20428, 'OPR': 14.934, 'Auto': -0.456, 'CCWM': -13.307, 'TeamName': 'South Iredell High School - FUSE'}, {'TeamNum': 9990, 'OPR': 14.152, 'Auto': 0.205, 'CCWM': 0.615, 'TeamName': 'Robo Vikings'}, {'TeamNum': 7444, 'OPR': 9.597, 'Auto': 6.95, 'CCWM': -48.053, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 5881, 'OPR': 7.215, 'Auto': -9.194, 'CCWM': -18.608, 'TeamName': 'Tungsteel'}, {'TeamNum': 9993, 'OPR': 6.068, 'Auto': 10.359, 'CCWM': -47.404, 'TeamName': 'StormBots'}, {'TeamNum': 4622, 'OPR': 4.9, 'Auto': 7.189, 'CCWM': -21.104, 'TeamName': 'L.O.C.S.'}, {'TeamNum': 20765, 'OPR': -3.055, 'Auto': 0.345, 'CCWM': -15.925, 'TeamName': 'Vikings for Technology'}, {'TeamNum': 22289, 'OPR': -5.8, 'Auto': 2.805, 'CCWM': -36.578, 'TeamName': 'Robolobos'}]
i 947
{'5549', '20081', '4949', '8569', '21401', '21465', '16582', '21381', '14200', '20086', '20434', '20683', '9021', '21351', '22759', '21601', '21404', '22377', '19768', '21318', '8300', '20056'}
[{'TeamNum': 21351, 'OPR': 119.779, 'Auto': 27.922, 'CCWM': 108.528, 'TeamName': 'Cybotz'}, {'TeamNum': 22377, 'OPR': 98.739, 'Auto': 34.438, 'CCWM': 49.469, 'TeamName': 'SigmaCorns'}, {'TeamNum': 8300, 'OPR': 91.607, 'Auto': 24.672, 'CCWM': 70.788, 'TeamName': 'Pi Rho Eagles'}, {'TeamNum': 19768, 'OPR': 85.7, 'Auto': 20.567, 'CCWM': 28.468, 'TeamName': 'Overclocked'}, {'TeamNum': 20434, 'OPR': 80.797, 'Auto': 23.696, 'CCWM': 16.728, 'TeamName': 'Binding Energy'}, {'TeamNum': 16582, 'OPR': 79.689, 'Auto': 26.971, 'CCWM': 2.554, 'TeamName': 'The Iron Dragons'}, {'TeamNum': 8569, 'OPR': 69.685, 'Auto': 15.448, 'CCWM': 63.052, 'TeamName': 'RoboKnights'}, {'TeamNum': 5549, 'OPR': 56.338, 'Auto': 12.247, 'CCWM': 18.417, 'TeamName': 'Blue Shift'}, {'TeamNum': 21318, 'OPR': 45.377, 'Auto': 4.163, 'CCWM': -6.774, 'TeamName': 'Leggo-CPC'}, {'TeamNum': 14200, 'OPR': 40.879, 'Auto': 14.961, 'CCWM': 26.679, 'TeamName': 'WASP - 12B'}, {'TeamNum': 20683, 'OPR': 33.566, 'Auto': 1.707, 'CCWM': -88.243, 'TeamName': 'CMPD RoboCops '}, {'TeamNum': 4949, 'OPR': 32.805, 'Auto': 4.075, 'CCWM': -50.928, 'TeamName': 'Warriors'}, {'TeamNum': 21381, 'OPR': 31.074, 'Auto': 17.25, 'CCWM': -49.187, 'TeamName': 'Harmony Robotics'}, {'TeamNum': 20056, 'OPR': 24.935, 'Auto': -7.159, 'CCWM': 8.669, 'TeamName': 'Syntax Terror'}, {'TeamNum': 21404, 'OPR': 22.578, 'Auto': 3.505, 'CCWM': -9.124, 'TeamName': 'Metal~Manipulators'}, {'TeamNum': 21465, 'OPR': 11.887, 'Auto': 1.726, 'CCWM': -28.083, 'TeamName': 'Nano~Gear'}, {'TeamNum': 20086, 'OPR': 10.738, 'Auto': 2.265, 'CCWM': -27.298, 'TeamName': 'Lake Norman Charter'}, {'TeamNum': 20081, 'OPR': 10.132, 'Auto': 6.494, 'CCWM': -18.336, 'TeamName': 'Smart Beacons'}, {'TeamNum': 22759, 'OPR': 9.414, 'Auto': 3.9, 'CCWM': -8.331, 'TeamName': 'CMPD RoboCops 2.0'}, {'TeamNum': 9021, 'OPR': 4.12, 'Auto': 1.164, 'CCWM': -18.202, 'TeamName': 'TMSA Batteries'}, {'TeamNum': 21601, 'OPR': -1.889, 'Auto': -3.269, 'CCWM': -28.54, 'TeamName': 'Robo Innovators'}, {'TeamNum': 21401, 'OPR': -5.248, 'Auto': -7.675, 'CCWM': -64.162, 'TeamName': 'Axolotls'}]
USNCASQ
[{'TeamNum': 21351, 'OPR': 119.779, 'Auto': 27.922, 'CCWM': 108.528, 'TeamName': 'Cybotz'}, {'TeamNum': 22377, 'OPR': 98.739, 'Auto': 34.438, 'CCWM': 49.469, 'TeamName': 'SigmaCorns'}, {'TeamNum': 8300, 'OPR': 91.607, 'Auto': 24.672, 'CCWM': 70.788, 'TeamName': 'Pi Rho Eagles'}, {'TeamNum': 19768, 'OPR': 85.7, 'Auto': 20.567, 'CCWM': 28.468, 'TeamName': 'Overclocked'}, {'TeamNum': 20434, 'OPR': 80.797, 'Auto': 23.696, 'CCWM': 16.728, 'TeamName': 'Binding Energy'}, {'TeamNum': 16582, 'OPR': 79.689, 'Auto': 26.971, 'CCWM': 2.554, 'TeamName': 'The Iron Dragons'}, {'TeamNum': 8569, 'OPR': 69.685, 'Auto': 15.448, 'CCWM': 63.052, 'TeamName': 'RoboKnights'}, {'TeamNum': 5549, 'OPR': 56.338, 'Auto': 12.247, 'CCWM': 18.417, 'TeamName': 'Blue Shift'}, {'TeamNum': 21318, 'OPR': 45.377, 'Auto': 4.163, 'CCWM': -6.774, 'TeamName': 'Leggo-CPC'}, {'TeamNum': 14200, 'OPR': 40.879, 'Auto': 14.961, 'CCWM': 26.679, 'TeamName': 'WASP - 12B'}, {'TeamNum': 20683, 'OPR': 33.566, 'Auto': 1.707, 'CCWM': -88.243, 'TeamName': 'CMPD RoboCops '}, {'TeamNum': 4949, 'OPR': 32.805, 'Auto': 4.075, 'CCWM': -50.928, 'TeamName': 'Warriors'}, {'TeamNum': 21381, 'OPR': 31.074, 'Auto': 17.25, 'CCWM': -49.187, 'TeamName': 'Harmony Robotics'}, {'TeamNum': 20056, 'OPR': 24.935, 'Auto': -7.159, 'CCWM': 8.669, 'TeamName': 'Syntax Terror'}, {'TeamNum': 21404, 'OPR': 22.578, 'Auto': 3.505, 'CCWM': -9.124, 'TeamName': 'Metal~Manipulators'}, {'TeamNum': 21465, 'OPR': 11.887, 'Auto': 1.726, 'CCWM': -28.083, 'TeamName': 'Nano~Gear'}, {'TeamNum': 20086, 'OPR': 10.738, 'Auto': 2.265, 'CCWM': -27.298, 'TeamName': 'Lake Norman Charter'}, {'TeamNum': 20081, 'OPR': 10.132, 'Auto': 6.494, 'CCWM': -18.336, 'TeamName': 'Smart Beacons'}, {'TeamNum': 22759, 'OPR': 9.414, 'Auto': 3.9, 'CCWM': -8.331, 'TeamName': 'CMPD RoboCops 2.0'}, {'TeamNum': 9021, 'OPR': 4.12, 'Auto': 1.164, 'CCWM': -18.202, 'TeamName': 'TMSA Batteries'}, {'TeamNum': 21601, 'OPR': -1.889, 'Auto': -3.269, 'CCWM': -28.54, 'TeamName': 'Robo Innovators'}, {'TeamNum': 21401, 'OPR': -5.248, 'Auto': -7.675, 'CCWM': -64.162, 'TeamName': 'Axolotls'}]

i 948
{'15886', '16127', '16630', '6645', '14793', '22411', '21460', '9473', '17628', '18045', '9963', '9505'}
[{'TeamNum': 15886, 'OPR': 76.767, 'Auto': 22.656, 'CCWM': 13.986, 'TeamName': 'Shiloh Stud Muffins'}, {'TeamNum': 17628, 'OPR': 63.78, 'Auto': 12.099, 'CCWM': 31.37, 'TeamName': 'Grover Robotics'}, {'TeamNum': 6645, 'OPR': 61.598, 'Auto': 6.364, 'CCWM': 17.585, 'TeamName': 'Roboticus Maximus'}, {'TeamNum': 16127, 'OPR': 43.99, 'Auto': 13.77, 'CCWM': 12.607, 'TeamName': 'Rogue Robot '}, {'TeamNum': 9963, 'OPR': 39.736, 'Auto': 3.203, 'CCWM': 23.931, 'TeamName': 'Comets '}, {'TeamNum': 18045, 'OPR': 36.57, 'Auto': 2.617, 'CCWM': -8.424, 'TeamName': 'Rusty Nail Robotics'}, {'TeamNum': 9505, 'OPR': 35.945, 'Auto': 1.933, 'CCWM': -24.026, 'TeamName': 'The Bot Patrol'}, {'TeamNum': 22411, 'OPR': 33.802, 'Auto': 8.41, 'CCWM': -8.58, 'TeamName': 'Wild Squirrels'}, {'TeamNum': 14793, 'OPR': 28.613, 'Auto': 1.026, 'CCWM': 0.145, 'TeamName': 'Pun-ishers'}, {'TeamNum': 16630, 'OPR': 28.269, 'Auto': 3.766, 'CCWM': -6.628, 'TeamName': 'T3- Tioga Tech Team'}, {'TeamNum': 9473, 'OPR': 24.957, 'Auto': 2.1, 'CCWM': -15.951, 'TeamName': 'Crocobots'}, {'TeamNum': 21460, 'OPR': 19.371, 'Auto': 4.458, 'CCWM': -36.014, 'TeamName': 'Astronomical Blueprint'}]
USNDCMP
[{'TeamNum': 15886, 'OPR': 76.767, 'Auto': 22.656, 'CCWM': 13.986, 'TeamName': 'Shiloh Stud Muffins'}, {'TeamNum': 17628, 'OPR': 63.78, 'Auto': 12.099, 'CCWM': 31.37, 'TeamName': 'Grover Robotics'}, {'TeamNum': 6645, 'OPR': 61.598, 'Auto': 6.364, 'CCWM': 17.585, 'TeamName': 'Roboticus Maximus'}, {'TeamNum': 16127, 'OPR': 43.99, 'Auto': 13.77, 'CCWM': 12.607, 'TeamName': 'Rogue Robot '}, {'TeamNum': 9963, 'OPR': 39.736, 'Auto': 3.203, 'CCWM': 23.931, 'TeamName': 'Comets '}, {'TeamNum': 18045, 'OPR': 36.57, 'Auto': 2.617, 'CCWM': -8.424, 'TeamName': 'Rusty Nail Robotics'}, {'TeamNum': 9505, 'OPR': 35.945, 'Auto': 1.933, 'CCWM': -24.026, 'TeamName': 'The Bot Patrol'}, {'TeamNum': 22411, 'OPR': 33.802, 'Auto': 8.41, 'CCWM': -8.58, 'TeamName': 'Wild Squirrels'}, {'TeamNum': 14793, 'OPR': 28.613, 'Auto': 1.026, 'CCWM': 0.145, 'TeamName': 'Pun-ishers'}, {'TeamNum': 16630, 'OPR': 28.269, 'Auto': 3.766, 'CCWM': -6.628, 'TeamName': 'T3- Tioga Tech Team'}, {'TeamNum': 9473, 'OPR': 24.957, 'Auto': 2.1, 'CCWM': -15.951, 'TeamName': 'Crocobots'}, {'TeamNum': 21460, 'OPR': 19.371, 'Auto': 4.458, 'CCWM': -36.014, 'TeamName': 'Astronomical Blueprint'}]
i 949
{'21627', '8824', '17116', '19394', '21900', '8807', '15523', '7259', '7229', '9978', '12999', '16754', '19687', '20077', '20024', '11384', '19984', '7258', '16010', '7841', '18139', '21903', '17111', '7924'}
[{'TeamNum': 20077, 'OPR': 117.636, 'Auto': 18.279, 'CCWM': 42.812, 'TeamName': 'The Indubitables'}, {'TeamNum': 7841, 'OPR': 90.747, 'Auto': 23.345, 'CCWM': 40.603, 'TeamName': 'Ballen Pretzels 2'}, {'TeamNum': 7259, 'OPR': 85.661, 'Auto': 14.959, 'CCWM': 29.248, 'TeamName': 'Void Robotics'}, {'TeamNum': 9978, 'OPR': 84.911, 'Auto': 18.719, 'CCWM': 43.259, 'TeamName': 'Avengers Tech'}, {'TeamNum': 7258, 'OPR': 82.095, 'Auto': 7.51, 'CCWM': -16.025, 'TeamName': 'Epsilon Robotics'}, {'TeamNum': 7229, 'OPR': 81.468, 'Auto': 8.703, 'CCWM': 21.375, 'TeamName': 'bzBots'}, {'TeamNum': 16010, 'OPR': 76.13, 'Auto': 15.672, 'CCWM': 53.375, 'TeamName': 'Vamp Kings'}, {'TeamNum': 19394, 'OPR': 76.073, 'Auto': 16.299, 'CCWM': -4.39, 'TeamName': 'Dutch Bots'}, {'TeamNum': 20024, 'OPR': 73.41, 'Auto': 16.304, 'CCWM': -24.2, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 17116, 'OPR': 71.966, 'Auto': 3.809, 'CCWM': 27.172, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 11384, 'OPR': 67.772, 'Auto': 10.865, 'CCWM': -8.094, 'TeamName': 'Thunderstruck'}, {'TeamNum': 17111, 'OPR': 63.652, 'Auto': 15.336, 'CCWM': 22.457, 'TeamName': 'Quack Attack'}, {'TeamNum': 7924, 'OPR': 61.371, 'Auto': 15.519, 'CCWM': -8.309, 'TeamName': 'Red Toques'}, {'TeamNum': 8824, 'OPR': 59.281, 'Auto': 12.046, 'CCWM': -18.448, 'TeamName': 'N-Bots RoboStorm'}, {'TeamNum': 18139, 'OPR': 50.752, 'Auto': 13.851, 'CCWM': -14.569, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 21903, 'OPR': 48.944, 'Auto': 8.707, 'CCWM': -30.879, 'TeamName': 'Analogue Clogs'}, {'TeamNum': 8807, 'OPR': 46.494, 'Auto': 6.781, 'CCWM': -0.51, 'TeamName': 'Molten Sprockets'}, {'TeamNum': 19984, 'OPR': 46.21, 'Auto': 16.82, 'CCWM': 21.809, 'TeamName': 'Hinton Short Circuits'}, {'TeamNum': 21627, 'OPR': 40.226, 'Auto': 2.647, 'CCWM': -13.386, 'TeamName': 'NinJava'}, {'TeamNum': 16754, 'OPR': 37.991, 'Auto': 9.233, 'CCWM': -45.382, 'TeamName': 'Gear Death Experience '}, {'TeamNum': 19687, 'OPR': 37.961, 'Auto': 3.365, 'CCWM': -24.142, 'TeamName': 'Cedar Bots 3'}, {'TeamNum': 21900, 'OPR': 36.682, 'Auto': 17.971, 'CCWM': -20.854, 'TeamName': 'MOC-atronics'}, {'TeamNum': 15523, 'OPR': 35.107, 'Auto': 17.509, 'CCWM': -18.845, 'TeamName': 'Diagonal HotSpots'}, {'TeamNum': 12999, 'OPR': 2.792, 'Auto': 2.751, 'CCWM': -54.076, 'TeamName': 'Giraffic Spark   '}]
USIATBSQ
[{'TeamNum': 20077, 'OPR': 117.636, 'Auto': 18.279, 'CCWM': 42.812, 'TeamName': 'The Indubitables'}, {'TeamNum': 7841, 'OPR': 90.747, 'Auto': 23.345, 'CCWM': 40.603, 'TeamName': 'Ballen Pretzels 2'}, {'TeamNum': 7259, 'OPR': 85.661, 'Auto': 14.959, 'CCWM': 29.248, 'TeamName': 'Void Robotics'}, {'TeamNum': 9978, 'OPR': 84.911, 'Auto': 18.719, 'CCWM': 43.259, 'TeamName': 'Avengers Tech'}, {'TeamNum': 7258, 'OPR': 82.095, 'Auto': 7.51, 'CCWM': -16.025, 'TeamName': 'Epsilon Robotics'}, {'TeamNum': 7229, 'OPR': 81.468, 'Auto': 8.703, 'CCWM': 21.375, 'TeamName': 'bzBots'}, {'TeamNum': 16010, 'OPR': 76.13, 'Auto': 15.672, 'CCWM': 53.375, 'TeamName': 'Vamp Kings'}, {'TeamNum': 19394, 'OPR': 76.073, 'Auto': 16.299, 'CCWM': -4.39, 'TeamName': 'Dutch Bots'}, {'TeamNum': 20024, 'OPR': 73.41, 'Auto': 16.304, 'CCWM': -24.2, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 17116, 'OPR': 71.966, 'Auto': 3.809, 'CCWM': 27.172, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 11384, 'OPR': 67.772, 'Auto': 10.865, 'CCWM': -8.094, 'TeamName': 'Thunderstruck'}, {'TeamNum': 17111, 'OPR': 63.652, 'Auto': 15.336, 'CCWM': 22.457, 'TeamName': 'Quack Attack'}, {'TeamNum': 7924, 'OPR': 61.371, 'Auto': 15.519, 'CCWM': -8.309, 'TeamName': 'Red Toques'}, {'TeamNum': 8824, 'OPR': 59.281, 'Auto': 12.046, 'CCWM': -18.448, 'TeamName': 'N-Bots RoboStorm'}, {'TeamNum': 18139, 'OPR': 50.752, 'Auto': 13.851, 'CCWM': -14.569, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 21903, 'OPR': 48.944, 'Auto': 8.707, 'CCWM': -30.879, 'TeamName': 'Analogue Clogs'}, {'TeamNum': 8807, 'OPR': 46.494, 'Auto': 6.781, 'CCWM': -0.51, 'TeamName': 'Molten Sprockets'}, {'TeamNum': 19984, 'OPR': 46.21, 'Auto': 16.82, 'CCWM': 21.809, 'TeamName': 'Hinton Short Circuits'}, {'TeamNum': 21627, 'OPR': 40.226, 'Auto': 2.647, 'CCWM': -13.386, 'TeamName': 'NinJava'}, {'TeamNum': 16754, 'OPR': 37.991, 'Auto': 9.233, 'CCWM': -45.382, 'TeamName': 'Gear Death Experience '}, {'TeamNum': 19687, 'OPR': 37.961, 'Auto': 3.365, 'CCWM': -24.142, 'TeamName': 'Cedar Bots 3'}, {'TeamNum': 21900, 'OPR': 36.682, 'Auto': 17.971, 'CCWM': -20.854, 'TeamName': 'MOC-atronics'}, {'TeamNum': 15523, 'OPR': 35.107, 'Auto': 17.509, 'CCWM': -18.845, 'TeamName': 'Diagonal HotSpots'}, {'TeamNum': 12999, 'OPR': 2.792, 'Auto': 2.751, 'CCWM': -54.076, 'TeamName': 'Giraffic Spark   '}]
i 950
{'21689', '7135', '20726', '12494', '17700', '20910', '12789', '22345', '17630', '18927', '11536', '15343', '15534', '12758', '7078', '22880', '22346', '16209', '18151'}
[{'TeamNum': 15534, 'OPR': 135.625, 'Auto': 28.329, 'CCWM': 114.113, 'TeamName': 'VERTEX'}, {'TeamNum': 15343, 'OPR': 101.626, 'Auto': 18.063, 'CCWM': 51.034, 'TeamName': 'Blue VIII'}, {'TeamNum': 12758, 'OPR': 100.287, 'Auto': 23.9, 'CCWM': 53.851, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 12789, 'OPR': 56.019, 'Auto': 19.004, 'CCWM': 6.443, 'TeamName': 'Hack-Gearz'}, {'TeamNum': 18151, 'OPR': 51.93, 'Auto': 5.554, 'CCWM': 8.358, 'TeamName': 'The Flux Capacitors'}, {'TeamNum': 22345, 'OPR': 50.746, 'Auto': -0.253, 'CCWM': 29.947, 'TeamName': 'SURFACE'}, {'TeamNum': 11536, 'OPR': 46.765, 'Auto': 10.544, 'CCWM': 23.37, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 16209, 'OPR': 46.004, 'Auto': 26.26, 'CCWM': -13.519, 'TeamName': 'The Dread Pirate Robots'}, {'TeamNum': 22346, 'OPR': 44.069, 'Auto': 24.235, 'CCWM': 0.182, 'TeamName': 'EDGE'}, {'TeamNum': 17630, 'OPR': 42.268, 'Auto': 6.061, 'CCWM': -20.245, 'TeamName': 'Hot Wings'}, {'TeamNum': 20726, 'OPR': 41.959, 'Auto': 9.087, 'CCWM': -23.005, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 17700, 'OPR': 35.288, 'Auto': 13.132, 'CCWM': -45.836, 'TeamName': 'Mechanical Vikings'}, {'TeamNum': 7078, 'OPR': 34.087, 'Auto': 11.4, 'CCWM': -3.005, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 21689, 'OPR': 29.466, 'Auto': 13.807, 'CCWM': -37.635, 'TeamName': 'A.J.A.Y Robotics '}, {'TeamNum': 20910, 'OPR': 26.527, 'Auto': 1.217, 'CCWM': -25.166, 'TeamName': 'Hornets 2'}, {'TeamNum': 7135, 'OPR': 19.778, 'Auto': -0.56, 'CCWM': -20.8, 'TeamName': 'Hornets'}, {'TeamNum': 22880, 'OPR': 18.662, 'Auto': -0.357, 'CCWM': -68.284, 'TeamName': 'Hornets 3'}, {'TeamNum': 12494, 'OPR': 17.146, 'Auto': -0.798, 'CCWM': -18.226, 'TeamName': 'Gear Grinders'}, {'TeamNum': 18927, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Dirty Birds'}]
USNHHUQ
[{'TeamNum': 15534, 'OPR': 135.625, 'Auto': 28.329, 'CCWM': 114.113, 'TeamName': 'VERTEX'}, {'TeamNum': 15343, 'OPR': 101.626, 'Auto': 18.063, 'CCWM': 51.034, 'TeamName': 'Blue VIII'}, {'TeamNum': 12758, 'OPR': 100.287, 'Auto': 23.9, 'CCWM': 53.851, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 12789, 'OPR': 56.019, 'Auto': 19.004, 'CCWM': 6.443, 'TeamName': 'Hack-Gearz'}, {'TeamNum': 18151, 'OPR': 51.93, 'Auto': 5.554, 'CCWM': 8.358, 'TeamName': 'The Flux Capacitors'}, {'TeamNum': 22345, 'OPR': 50.746, 'Auto': -0.253, 'CCWM': 29.947, 'TeamName': 'SURFACE'}, {'TeamNum': 11536, 'OPR': 46.765, 'Auto': 10.544, 'CCWM': 23.37, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 16209, 'OPR': 46.004, 'Auto': 26.26, 'CCWM': -13.519, 'TeamName': 'The Dread Pirate Robots'}, {'TeamNum': 22346, 'OPR': 44.069, 'Auto': 24.235, 'CCWM': 0.182, 'TeamName': 'EDGE'}, {'TeamNum': 17630, 'OPR': 42.268, 'Auto': 6.061, 'CCWM': -20.245, 'TeamName': 'Hot Wings'}, {'TeamNum': 20726, 'OPR': 41.959, 'Auto': 9.087, 'CCWM': -23.005, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 17700, 'OPR': 35.288, 'Auto': 13.132, 'CCWM': -45.836, 'TeamName': 'Mechanical Vikings'}, {'TeamNum': 7078, 'OPR': 34.087, 'Auto': 11.4, 'CCWM': -3.005, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 21689, 'OPR': 29.466, 'Auto': 13.807, 'CCWM': -37.635, 'TeamName': 'A.J.A.Y Robotics '}, {'TeamNum': 20910, 'OPR': 26.527, 'Auto': 1.217, 'CCWM': -25.166, 'TeamName': 'Hornets 2'}, {'TeamNum': 7135, 'OPR': 19.778, 'Auto': -0.56, 'CCWM': -20.8, 'TeamName': 'Hornets'}, {'TeamNum': 22880, 'OPR': 18.662, 'Auto': -0.357, 'CCWM': -68.284, 'TeamName': 'Hornets 3'}, {'TeamNum': 12494, 'OPR': 17.146, 'Auto': -0.798, 'CCWM': -18.226, 'TeamName': 'Gear Grinders'}, {'TeamNum': 18927, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Dirty Birds'}]
i 951

{'3415', '10343', '18051', '7414', '17584', '17670', '11450', '16953', '6936', '19227', '3774', '19784', '10553', '10669', '10582', '4890', '16557', '10785', '5968', '13302', '12875', '22704'}
[{'TeamNum': 18051, 'OPR': 126.646, 'Auto': 21.509, 'CCWM': 103.179, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 16557, 'OPR': 78.171, 'Auto': 17.954, 'CCWM': 19.914, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 4890, 'OPR': 75.283, 'Auto': 21.095, 'CCWM': 44.601, 'TeamName': 'AArcHive'}, {'TeamNum': 13302, 'OPR': 73.257, 'Auto': 13.355, 'CCWM': 48.486, 'TeamName': 'MKA Robotics'}, {'TeamNum': 6936, 'OPR': 69.646, 'Auto': 22.636, 'CCWM': 28.458, 'TeamName': 'CodeRunners'}, {'TeamNum': 10785, 'OPR': 58.892, 'Auto': 13.682, 'CCWM': 21.226, 'TeamName': 'Highlanders'}, {'TeamNum': 3774, 'OPR': 57.582, 'Auto': 26.149, 'CCWM': 20.164, 'TeamName': 'Hive Voltage'}, {'TeamNum': 10669, 'OPR': 57.49, 'Auto': 17.517, 'CCWM': 15.734, 'TeamName': 'Clutch Squad'}, {'TeamNum': 17670, 'OPR': 57.435, 'Auto': 8.352, 'CCWM': 21.26, 'TeamName': 'Raider Robotics'}, {'TeamNum': 5968, 'OPR': 37.909, 'Auto': 23.682, 'CCWM': 5.465, 'TeamName': 'WR That Hertz'}, {'TeamNum': 3415, 'OPR': 34.364, 'Auto': 24.038, 'CCWM': -19.744, 'TeamName': 'Lancers'}, {'TeamNum': 10553, 'OPR': 34.205, 'Auto': 16.582, 'CCWM': 4.141, 'TeamName': 'RaidX'}, {'TeamNum': 10582, 'OPR': 33.97, 'Auto': 1.415, 'CCWM': 12.229, 'TeamName': 'Emerald Knights'}, {'TeamNum': 16953, 'OPR': 30.322, 'Auto': 10.269, 'CCWM': -12.275, 'TeamName': 'FIRE'}, {'TeamNum': 7414, 'OPR': 27.257, 'Auto': 27.009, 'CCWM': -38.792, 'TeamName': 'Deceptibots'}, {'TeamNum': 17584, 'OPR': 25.835, 'Auto': -1.689, 'CCWM': -45.074, 'TeamName': 'Rambotics1'}, {'TeamNum': 11450, 'OPR': 22.898, 'Auto': 2.16, 'CCWM': -20.446, 'TeamName': 'Dickinson Rams'}, {'TeamNum': 19227, 'OPR': 22.822, 'Auto': 4.763, 'CCWM': -54.889, 'TeamName': 'The Brearley Bots'}, {'TeamNum': 22704, 'OPR': 17.422, 'Auto': 3.018, 'CCWM': -33.319, 'TeamName': 'Robo-Redwings'}, {'TeamNum': 10343, 'OPR': 8.654, 'Auto': 7.861, 'CCWM': -28.511, 'TeamName': 'WR Positive Charge'}, {'TeamNum': 19784, 'OPR': 6.112, 'Auto': -8.484, 'CCWM': -33.57, 'TeamName': 'Robotribe'}, {'TeamNum': 12875, 'OPR': 3.728, 'Auto': -1.839, 'CCWM': -63.364, 'TeamName': 'Snyder High School Robotics'}]
USNJNELT
[{'TeamNum': 18051, 'OPR': 126.646, 'Auto': 21.509, 'CCWM': 103.179, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 16557, 'OPR': 78.171, 'Auto': 17.954, 'CCWM': 19.914, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 4890, 'OPR': 75.283, 'Auto': 21.095, 'CCWM': 44.601, 'TeamName': 'AArcHive'}, {'TeamNum': 13302, 'OPR': 73.257, 'Auto': 13.355, 'CCWM': 48.486, 'TeamName': 'MKA Robotics'}, {'TeamNum': 6936, 'OPR': 69.646, 'Auto': 22.636, 'CCWM': 28.458, 'TeamName': 'CodeRunners'}, {'TeamNum': 10785, 'OPR': 58.892, 'Auto': 13.682, 'CCWM': 21.226, 'TeamName': 'Highlanders'}, {'TeamNum': 3774, 'OPR': 57.582, 'Auto': 26.149, 'CCWM': 20.164, 'TeamName': 'Hive Voltage'}, {'TeamNum': 10669, 'OPR': 57.49, 'Auto': 17.517, 'CCWM': 15.734, 'TeamName': 'Clutch Squad'}, {'TeamNum': 17670, 'OPR': 57.435, 'Auto': 8.352, 'CCWM': 21.26, 'TeamName': 'Raider Robotics'}, {'TeamNum': 5968, 'OPR': 37.909, 'Auto': 23.682, 'CCWM': 5.465, 'TeamName': 'WR That Hertz'}, {'TeamNum': 3415, 'OPR': 34.364, 'Auto': 24.038, 'CCWM': -19.744, 'TeamName': 'Lancers'}, {'TeamNum': 10553, 'OPR': 34.205, 'Auto': 16.582, 'CCWM': 4.141, 'TeamName': 'RaidX'}, {'TeamNum': 10582, 'OPR': 33.97, 'Auto': 1.415, 'CCWM': 12.229, 'TeamName': 'Emerald Knights'}, {'TeamNum': 16953, 'OPR': 30.322, 'Auto': 10.269, 'CCWM': -12.275, 'TeamName': 'FIRE'}, {'TeamNum': 7414, 'OPR': 27.257, 'Auto': 27.009, 'CCWM': -38.792, 'TeamName': 'Deceptibots'}, {'TeamNum': 17584, 'OPR': 25.835, 'Auto': -1.689, 'CCWM': -45.074, 'TeamName': 'Rambotics1'}, {'TeamNum': 11450, 'OPR': 22.898, 'Auto': 2.16, 'CCWM': -20.446, 'TeamName': 'Dickinson Rams'}, {'TeamNum': 19227, 'OPR': 22.822, 'Auto': 4.763, 'CCWM': -54.889, 'TeamName': 'The Brearley Bots'}, {'TeamNum': 22704, 'OPR': 17.422, 'Auto': 3.018, 'CCWM': -33.319, 'TeamName': 'Robo-Redwings'}, {'TeamNum': 10343, 'OPR': 8.654, 'Auto': 7.861, 'CCWM': -28.511, 'TeamName': 'WR Positive Charge'}, {'TeamNum': 19784, 'OPR': 6.112, 'Auto': -8.484, 'CCWM': -33.57, 'TeamName': 'Robotribe'}, {'TeamNum': 12875, 'OPR': 3.728, 'Auto': -1.839, 'CCWM': -63.364, 'TeamName': 'Snyder High School Robotics'}]
i 952
{'755', '12116', '6102', '17009', '8816', '9889', '4347', '8421', '10096', '6101', '16367', '10788', '17496', '17746', '22810', '15589', '9853', '11248', '17497'}
[{'TeamNum': 9889, 'OPR': 141.81, 'Auto': 22.375, 'CCWM': 113.337, 'TeamName': 'Cruise Control'}, {'TeamNum': 4347, 'OPR': 75.776, 'Auto': 31.163, 'CCWM': 36.664, 'TeamName': 'NanoGurus'}, {'TeamNum': 16367, 'OPR': 74.903, 'Auto': 19.696, 'CCWM': 52.972, 'TeamName': 'Krypton Warriors'}, {'TeamNum': 755, 'OPR': 66.505, 'Auto': 18.748, 'CCWM': -0.064, 'TeamName': 'Delbotics'}, {'TeamNum': 11248, 'OPR': 60.291, 'Auto': 17.368, 'CCWM': -1.844, 'TeamName': '//Cougars'}, {'TeamNum': 22810, 'OPR': 55.512, 'Auto': 7.999, 'CCWM': 16.796, 'TeamName': 'Pequaautobots'}, {'TeamNum': 9853, 'OPR': 51.956, 'Auto': 12.293, 'CCWM': -4.645, 'TeamName': 'Chatham Cougars'}, {'TeamNum': 12116, 'OPR': 50.025, 'Auto': 8.503, 'CCWM': 17.46, 'TeamName': 'Redbots'}, {'TeamNum': 17497, 'OPR': 47.27, 'Auto': 21.2, 'CCWM': 31.969, 'TeamName': 'Knight Riders'}, {'TeamNum': 8421, 'OPR': 46.187, 'Auto': 16.376, 'CCWM': 0.104, 'TeamName': 'Tigers'}, {'TeamNum': 6102, 'OPR': 42.554, 'Auto': 6.984, 'CCWM': -26.574, 'TeamName': 'E=MK2'}, {'TeamNum': 15589, 'OPR': 40.239, 'Auto': 8.727, 'CCWM': 2.119, 'TeamName': 'TecHawks'}, {'TeamNum': 8816, 'OPR': 31.37, 'Auto': 7.602, 'CCWM': -38.085, 'TeamName': '22nd Century Robotics'}, {'TeamNum': 10788, 'OPR': 29.116, 'Auto': 5.576, 'CCWM': -9.331, 'TeamName': 'Mountain Lakes Robotics'}, {'TeamNum': 10096, 'OPR': 25.3, 'Auto': 6.562, 'CCWM': -10.35, 'TeamName': 'Those Guys'}, {'TeamNum': 6101, 'OPR': 23.847, 'Auto': 4.489, 'CCWM': -38.121, 'TeamName': 'Energized Hazard'}, {'TeamNum': 17496, 'OPR': 22.809, 'Auto': 15.011, 'CCWM': -29.868, 'TeamName': 'The Knight Shift'}, {'TeamNum': 17009, 'OPR': 12.661, 'Auto': -1.532, 'CCWM': -38.204, 'TeamName': 'Steel Magnolias'}, {'TeamNum': 17746, 'OPR': 1.5, 'Auto': -3.636, 'CCWM': -66.709, 'TeamName': 'Hanover Park Online Computers'}]
USNJUCLT
[{'TeamNum': 9889, 'OPR': 141.81, 'Auto': 22.375, 'CCWM': 113.337, 'TeamName': 'Cruise Control'}, {'TeamNum': 4347, 'OPR': 75.776, 'Auto': 31.163, 'CCWM': 36.664, 'TeamName': 'NanoGurus'}, {'TeamNum': 16367, 'OPR': 74.903, 'Auto': 19.696, 'CCWM': 52.972, 'TeamName': 'Krypton Warriors'}, {'TeamNum': 755, 'OPR': 66.505, 'Auto': 18.748, 'CCWM': -0.064, 'TeamName': 'Delbotics'}, {'TeamNum': 11248, 'OPR': 60.291, 'Auto': 17.368, 'CCWM': -1.844, 'TeamName': '//Cougars'}, {'TeamNum': 22810, 'OPR': 55.512, 'Auto': 7.999, 'CCWM': 16.796, 'TeamName': 'Pequaautobots'}, {'TeamNum': 9853, 'OPR': 51.956, 'Auto': 12.293, 'CCWM': -4.645, 'TeamName': 'Chatham Cougars'}, {'TeamNum': 12116, 'OPR': 50.025, 'Auto': 8.503, 'CCWM': 17.46, 'TeamName': 'Redbots'}, {'TeamNum': 17497, 'OPR': 47.27, 'Auto': 21.2, 'CCWM': 31.969, 'TeamName': 'Knight Riders'}, {'TeamNum': 8421, 'OPR': 46.187, 'Auto': 16.376, 'CCWM': 0.104, 'TeamName': 'Tigers'}, {'TeamNum': 6102, 'OPR': 42.554, 'Auto': 6.984, 'CCWM': -26.574, 'TeamName': 'E=MK2'}, {'TeamNum': 15589, 'OPR': 40.239, 'Auto': 8.727, 'CCWM': 2.119, 'TeamName': 'TecHawks'}, {'TeamNum': 8816, 'OPR': 31.37, 'Auto': 7.602, 'CCWM': -38.085, 'TeamName': '22nd Century Robotics'}, {'TeamNum': 10788, 'OPR': 29.116, 'Auto': 5.576, 'CCWM': -9.331, 'TeamName': 'Mountain Lakes Robotics'}, {'TeamNum': 10096, 'OPR': 25.3, 'Auto': 6.562, 'CCWM': -10.35, 'TeamName': 'Those Guys'}, {'TeamNum': 6101, 'OPR': 23.847, 'Auto': 4.489, 'CCWM': -38.121, 'TeamName': 'Energized Hazard'}, {'TeamNum': 17496, 'OPR': 22.809, 'Auto': 15.011, 'CCWM': -29.868, 'TeamName': 'The Knight Shift'}, {'TeamNum': 17009, 'OPR': 12.661, 'Auto': -1.532, 'CCWM': -38.204, 'TeamName': 'Steel Magnolias'}, {'TeamNum': 17746, 'OPR': 1.5, 'Auto': -3.636, 'CCWM': -66.709, 'TeamName': 'Hanover Park Online Computers'}]
i 953
{'19426', '14212', '20712', '4174', '22434', '22206', '21690', '22204', '22211', '22207', '14413', '22433', '22716', '11997', '3922', '20233', '9371', '3006', '6051', '16622', '14156', '22335', '22437'}
[{'TeamNum': 14212, 'OPR': 139.584, 'Auto': 34.911, 'CCWM': 129.731, 'TeamName': 'Metrobotics'}, {'TeamNum': 3006, 'OPR': 64.143, 'Auto': 9.19, 'CCWM': 36.417, 'TeamName': 'TeraBots'}, {'TeamNum': 20233, 'OPR': 57.202, 'Auto': 8.956, 'CCWM': -32.816, 'TeamName': 'Blazing Bluebots'}, {'TeamNum': 21690, 'OPR': 49.641, 'Auto': -2.532, 'CCWM': -32.799, 'TeamName': 'Power Up'}, {'TeamNum': 11997, 'OPR': 48.509, 'Auto': 3.846, 'CCWM': 17.4, 'TeamName': 'Heights Techies'}, {'TeamNum': 22437, 'OPR': 44.476, 'Auto': 11.575, 'CCWM': 28.548, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 4174, 'OPR': 44.47, 'Auto': 16.412, 'CCWM': 25.29, 'TeamName': 'Atomic Theory'}, {'TeamNum': 20712, 'OPR': 43.095, 'Auto': 12.34, 'CCWM': 20.16, 'TeamName': 'Kenny Donuts'}, {'TeamNum': 19426, 'OPR': 37.125, 'Auto': 5.265, 'CCWM': 2.513, 'TeamName': 'QHSS Cardinal Robotics'}, {'TeamNum': 22206, 'OPR': 35.927, 'Auto': 1.053, 'CCWM': 10.7, 'TeamName': 'GT3 - The Jokers'}, {'TeamNum': 14413, 'OPR': 35.57, 'Auto': 6.307, 'CCWM': -16.626, 'TeamName': 'Trinity Tigers'}, {'TeamNum': 6051, 'OPR': 30.731, 'Auto': 18.992, 'CCWM': 21.704, 'TeamName': 'Quantum Mechanics'}, {'TeamNum': 22335, 'OPR': 27.211, 'Auto': 2.928, 'CCWM': -2.482, 'TeamName': 'Polymorphism '}, {'TeamNum': 9371, 'OPR': 27.191, 'Auto': 20.654, 'CCWM': -37.061, 'TeamName': 'General Relativity'}, {'TeamNum': 22204, 'OPR': 21.475, 'Auto': 4.041, 'CCWM': -35.787, 'TeamName': 'GT1 - Prime Aqua Bots'}, {'TeamNum': 16622, 'OPR': 18.979, 'Auto': -6.157, 'CCWM': -54.303, 'TeamName': 'KIPPNYC Bulldogs'}, {'TeamNum': 22433, 'OPR': 18.965, 'Auto': -0.984, 'CCWM': -0.208, 'TeamName': 'GT9 - Sewer Rats '}, {'TeamNum': 3922, 'OPR': 15.797, 'Auto': -6.82, 'CCWM': 8.066, 'TeamName': 'Modibot'}, {'TeamNum': 14156, 'OPR': 15.568, 'Auto': 3.789, 'CCWM': -13.554, 'TeamName': 'Packer Robotics'}, {'TeamNum': 22211, 'OPR': 15.376, 'Auto': -0.056, 'CCWM': -35.153, 'TeamName': 'GT8 - Dark Knights'}, {'TeamNum': 22716, 'OPR': 9.528, 'Auto': 1.234, 'CCWM': -5.118, 'TeamName': 'Team R.M.D.S.'}, {'TeamNum': 22434, 'OPR': 4.457, 'Auto': 9.194, 'CCWM': -6.133, 'TeamName': 'GT 10 - The Gotham Ducks'}, {'TeamNum': 22207, 'OPR': -1.534, 'Auto': 3.681, 'CCWM': -54.436, 'TeamName': 'GT4 - Gotham Gators'}]
USNYNYBRQ7
[{'TeamNum': 14212, 'OPR': 139.584, 'Auto': 34.911, 'CCWM': 129.731, 'TeamName': 'Metrobotics'}, {'TeamNum': 3006, 'OPR': 64.143, 'Auto': 9.19, 'CCWM': 36.417, 'TeamName': 'TeraBots'}, {'TeamNum': 20233, 'OPR': 57.202, 'Auto': 8.956, 'CCWM': -32.816, 'TeamName': 'Blazing Bluebots'}, {'TeamNum': 21690, 'OPR': 49.641, 'Auto': -2.532, 'CCWM': -32.799, 'TeamName': 'Power Up'}, {'TeamNum': 11997, 'OPR': 48.509, 'Auto': 3.846, 'CCWM': 17.4, 'TeamName': 'Heights Techies'}, {'TeamNum': 22437, 'OPR': 44.476, 'Auto': 11.575, 'CCWM': 28.548, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 4174, 'OPR': 44.47, 'Auto': 16.412, 'CCWM': 25.29, 'TeamName': 'Atomic Theory'}, {'TeamNum': 20712, 'OPR': 43.095, 'Auto': 12.34, 'CCWM': 20.16, 'TeamName': 'Kenny Donuts'}, {'TeamNum': 19426, 'OPR': 37.125, 'Auto': 5.265, 'CCWM': 2.513, 'TeamName': 'QHSS Cardinal Robotics'}, {'TeamNum': 22206, 'OPR': 35.927, 'Auto': 1.053, 'CCWM': 10.7, 'TeamName': 'GT3 - The Jokers'}, {'TeamNum': 14413, 'OPR': 35.57, 'Auto': 6.307, 'CCWM': -16.626, 'TeamName': 'Trinity Tigers'}, {'TeamNum': 6051, 'OPR': 30.731, 'Auto': 18.992, 'CCWM': 21.704, 'TeamName': 'Quantum Mechanics'}, {'TeamNum': 22335, 'OPR': 27.211, 'Auto': 2.928, 'CCWM': -2.482, 'TeamName': 'Polymorphism '}, {'TeamNum': 9371, 'OPR': 27.191, 'Auto': 20.654, 'CCWM': -37.061, 'TeamName': 'General Relativity'}, {'TeamNum': 22204, 'OPR': 21.475, 'Auto': 4.041, 'CCWM': -35.787, 'TeamName': 'GT1 - Prime Aqua Bots'}, {'TeamNum': 16622, 'OPR': 18.979, 'Auto': -6.157, 'CCWM': -54.303, 'TeamName': 'KIPPNYC Bulldogs'}, {'TeamNum': 22433, 'OPR': 18.965, 'Auto': -0.984, 'CCWM': -0.208, 'TeamName': 'GT9 - Sewer Rats '}, {'TeamNum': 3922, 'OPR': 15.797, 'Auto': -6.82, 'CCWM': 8.066, 'TeamName': 'Modibot'}, {'TeamNum': 14156, 'OPR': 15.568, 'Auto': 3.789, 'CCWM': -13.554, 'TeamName': 'Packer Robotics'}, {'TeamNum': 22211, 'OPR': 15.376, 'Auto': -0.056, 'CCWM': -35.153, 'TeamName': 'GT8 - Dark Knights'}, {'TeamNum': 22716, 'OPR': 9.528, 'Auto': 1.234, 'CCWM': -5.118, 'TeamName': 'Team R.M.D.S.'}, {'TeamNum': 22434, 'OPR': 4.457, 'Auto': 9.194, 'CCWM': -6.133, 'TeamName': 'GT 10 - The Gotham Ducks'}, {'TeamNum': 22207, 'OPR': -1.534, 'Auto': 3.681, 'CCWM': -54.436, 'TeamName': 'GT4 - Gotham Gators'}]

i 954
{'21377', '14639', '5361', '14803', '22053', '19167', '9681', '20789', '9385', '21464', '9384', '16568', '22519', '6496', '20731', '4326', '9137', '15740', '5919', '8500', '13334', '9372', '17126', '11453', '13475'}
[{'TeamNum': 15740, 'OPR': 93.996, 'Auto': 16.888, 'CCWM': 99.193, 'TeamName': 'SAR2-D2'}, {'TeamNum': 13475, 'OPR': 72.435, 'Auto': 4.969, 'CCWM': 57.748, 'TeamName': 'Lionotics 2'}, {'TeamNum': 8500, 'OPR': 60.621, 'Auto': 11.881, 'CCWM': 42.059, 'TeamName': 'The Generals'}, {'TeamNum': 14803, 'OPR': 48.186, 'Auto': 19.196, 'CCWM': 42.343, 'TeamName': 'uKnighted'}, {'TeamNum': 4326, 'OPR': 47.619, 'Auto': 11.266, 'CCWM': 24.751, 'TeamName': 'Basement Lions'}, {'TeamNum': 13334, 'OPR': 47.389, 'Auto': 22.49, 'CCWM': 14.179, 'TeamName': 'Spence Light Sabers'}, {'TeamNum': 19167, 'OPR': 47.303, 'Auto': 21.007, 'CCWM': -1.519, 'TeamName': 'Robo_Sapiens'}, {'TeamNum': 9384, 'OPR': 46.419, 'Auto': 19.489, 'CCWM': 26.59, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 20731, 'OPR': 43.106, 'Auto': 4.2, 'CCWM': -17.223, 'TeamName': 'Zombie Apocalypyse Counter Task Force'}, {'TeamNum': 5361, 'OPR': 41.767, 'Auto': 12.332, 'CCWM': 31.525, 'TeamName': 'Lionotics'}, {'TeamNum': 11453, 'OPR': 40.283, 'Auto': 3.875, 'CCWM': -43.687, 'TeamName': 'Uncertainty Principle'}, {'TeamNum': 6496, 'OPR': 37.341, 'Auto': 6.208, 'CCWM': -9.646, 'TeamName': 'SEP Bota-Bing-Bota-Bot'}, {'TeamNum': 22053, 'OPR': 34.906, 'Auto': 3.752, 'CCWM': 9.108, 'TeamName': 'Max Damage'}, {'TeamNum': 9681, 'OPR': 33.288, 'Auto': 5.67, 'CCWM': -2.365, 'TeamName': 'Parallel Lions'}, {'TeamNum': 14639, 'OPR': 23.47, 'Auto': 6.01, 'CCWM': 3.022, 'TeamName': 'Double X (B3VR)'}, {'TeamNum': 9372, 'OPR': 20.373, 'Auto': 2.16, 'CCWM': -21.337, 'TeamName': 'Standard Model'}, {'TeamNum': 22519, 'OPR': 14.605, 'Auto': 3.248, 'CCWM': 8.038, 'TeamName': 'Riptide Riders'}, {'TeamNum': 9137, 'OPR': 12.44, 'Auto': -3.094, 'CCWM': -5.573, 'TeamName': 'BECA Hexabots'}, {'TeamNum': 9385, 'OPR': 9.475, 'Auto': 6.502, 'CCWM': 3.015, 'TeamName': 'Team Leviathan '}, {'TeamNum': 17126, 'OPR': 7.306, 'Auto': -1.713, 'CCWM': -18.273, 'TeamName': 'Natural Selection'}, {'TeamNum': 21377, 'OPR': 4.404, 'Auto': -2.4, 'CCWM': -26.816, 'TeamName': 'Botsworth'}, {'TeamNum': 20789, 'OPR': 1.586, 'Auto': -0.055, 'CCWM': -47.898, 'TeamName': 'Paranoid-Androids-On-Steriods'}, {'TeamNum': 21464, 'OPR': 0.291, 'Auto': 4.44, 'CCWM': -47.186, 'TeamName': 'Ramaz Rambots'}, {'TeamNum': 5919, 'OPR': -0.968, 'Auto': -2.265, 'CCWM': -76.005, 'TeamName': 'RegisOwls'}, {'TeamNum': 16568, 'OPR': -5.451, 'Auto': -0.29, 'CCWM': -24.579, 'TeamName': 'Cybernetic Lions'}]
USNYNYBRQ8
[{'TeamNum': 15740, 'OPR': 93.996, 'Auto': 16.888, 'CCWM': 99.193, 'TeamName': 'SAR2-D2'}, {'TeamNum': 13475, 'OPR': 72.435, 'Auto': 4.969, 'CCWM': 57.748, 'TeamName': 'Lionotics 2'}, {'TeamNum': 8500, 'OPR': 60.621, 'Auto': 11.881, 'CCWM': 42.059, 'TeamName': 'The Generals'}, {'TeamNum': 14803, 'OPR': 48.186, 'Auto': 19.196, 'CCWM': 42.343, 'TeamName': 'uKnighted'}, {'TeamNum': 4326, 'OPR': 47.619, 'Auto': 11.266, 'CCWM': 24.751, 'TeamName': 'Basement Lions'}, {'TeamNum': 13334, 'OPR': 47.389, 'Auto': 22.49, 'CCWM': 14.179, 'TeamName': 'Spence Light Sabers'}, {'TeamNum': 19167, 'OPR': 47.303, 'Auto': 21.007, 'CCWM': -1.519, 'TeamName': 'Robo_Sapiens'}, {'TeamNum': 9384, 'OPR': 46.419, 'Auto': 19.489, 'CCWM': 26.59, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 20731, 'OPR': 43.106, 'Auto': 4.2, 'CCWM': -17.223, 'TeamName': 'Zombie Apocalypyse Counter Task Force'}, {'TeamNum': 5361, 'OPR': 41.767, 'Auto': 12.332, 'CCWM': 31.525, 'TeamName': 'Lionotics'}, {'TeamNum': 11453, 'OPR': 40.283, 'Auto': 3.875, 'CCWM': -43.687, 'TeamName': 'Uncertainty Principle'}, {'TeamNum': 6496, 'OPR': 37.341, 'Auto': 6.208, 'CCWM': -9.646, 'TeamName': 'SEP Bota-Bing-Bota-Bot'}, {'TeamNum': 22053, 'OPR': 34.906, 'Auto': 3.752, 'CCWM': 9.108, 'TeamName': 'Max Damage'}, {'TeamNum': 9681, 'OPR': 33.288, 'Auto': 5.67, 'CCWM': -2.365, 'TeamName': 'Parallel Lions'}, {'TeamNum': 14639, 'OPR': 23.47, 'Auto': 6.01, 'CCWM': 3.022, 'TeamName': 'Double X (B3VR)'}, {'TeamNum': 9372, 'OPR': 20.373, 'Auto': 2.16, 'CCWM': -21.337, 'TeamName': 'Standard Model'}, {'TeamNum': 22519, 'OPR': 14.605, 'Auto': 3.248, 'CCWM': 8.038, 'TeamName': 'Riptide Riders'}, {'TeamNum': 9137, 'OPR': 12.44, 'Auto': -3.094, 'CCWM': -5.573, 'TeamName': 'BECA Hexabots'}, {'TeamNum': 9385, 'OPR': 9.475, 'Auto': 6.502, 'CCWM': 3.015, 'TeamName': 'Team Leviathan '}, {'TeamNum': 17126, 'OPR': 7.306, 'Auto': -1.713, 'CCWM': -18.273, 'TeamName': 'Natural Selection'}, {'TeamNum': 21377, 'OPR': 4.404, 'Auto': -2.4, 'CCWM': -26.816, 'TeamName': 'Botsworth'}, {'TeamNum': 20789, 'OPR': 1.586, 'Auto': -0.055, 'CCWM': -47.898, 'TeamName': 'Paranoid-Androids-On-Steriods'}, {'TeamNum': 21464, 'OPR': 0.291, 'Auto': 4.44, 'CCWM': -47.186, 'TeamName': 'Ramaz Rambots'}, {'TeamNum': 5919, 'OPR': -0.968, 'Auto': -2.265, 'CCWM': -76.005, 'TeamName': 'RegisOwls'}, {'TeamNum': 16568, 'OPR': -5.451, 'Auto': -0.29, 'CCWM': -24.579, 'TeamName': 'Cybernetic Lions'}]
i 955
{'13366', '6347', '6460', '13357', '12737', '11975', '21302', '14054', '13362', '8863', '13359', '19251', '6955', '22612', '13364', '8527', '13371', '7230', '13360', '20297'}
[{'TeamNum': 12737, 'OPR': 94.824, 'Auto': 17.821, 'CCWM': 44.509, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 13371, 'OPR': 91.052, 'Auto': 20.98, 'CCWM': 20.976, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 8863, 'OPR': 75.304, 'Auto': 10.841, 'CCWM': 30.505, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 6955, 'OPR': 65.51, 'Auto': 27.376, 'CCWM': 14.912, 'TeamName': 'RoBovines'}, {'TeamNum': 13357, 'OPR': 61.707, 'Auto': 24.985, 'CCWM': 2.08, 'TeamName': 'IR Lightning'}, {'TeamNum': 14054, 'OPR': 61.395, 'Auto': 19.767, 'CCWM': 50.618, 'TeamName': 'IR Thunder'}, {'TeamNum': 20297, 'OPR': 59.555, 'Auto': 16.045, 'CCWM': 48.006, 'TeamName': 'SLCS Stormbots'}, {'TeamNum': 13359, 'OPR': 55.215, 'Auto': 15.791, 'CCWM': 25.971, 'TeamName': 'St. Lawrence Stingerz'}, {'TeamNum': 6460, 'OPR': 48.758, 'Auto': 22.52, 'CCWM': 26.921, 'TeamName': 'RoboWarriors'}, {'TeamNum': 21302, 'OPR': 47.79, 'Auto': -1.119, 'CCWM': -5.372, 'TeamName': 'HCS Robotics (CLEOB@ya)'}, {'TeamNum': 11975, 'OPR': 43.653, 'Auto': -3.079, 'CCWM': -23.106, 'TeamName': 'RoboFalcons (South Lewis HS)'}, {'TeamNum': 22612, 'OPR': 35.733, 'Auto': 2.869, 'CCWM': -15.495, 'TeamName': 'New Wave'}, {'TeamNum': 7230, 'OPR': 34.094, 'Auto': 3.128, 'CCWM': -8.957, 'TeamName': 'SAS Atoms'}, {'TeamNum': 6347, 'OPR': 25.071, 'Auto': 0.86, 'CCWM': -17.393, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 13360, 'OPR': 23.631, 'Auto': 6.253, 'CCWM': -66.695, 'TeamName': 'Franklin Academy'}, {'TeamNum': 13364, 'OPR': 20.845, 'Auto': 7.197, 'CCWM': -9.059, 'TeamName': 'Linear Lions'}, {'TeamNum': 13366, 'OPR': 11.635, 'Auto': 16.431, 'CCWM': -29.615, 'TeamName': 'Canton High School'}, {'TeamNum': 8527, 'OPR': 8.91, 'Auto': -3.74, 'CCWM': -18.402, 'TeamName': 'Bond Bots'}, {'TeamNum': 19251, 'OPR': 8.596, 'Auto': 6.703, 'CCWM': -50.186, 'TeamName': 'Code Panthers '}, {'TeamNum': 13362, 'OPR': 2.921, 'Auto': -1.428, 'CCWM': -20.217, 'TeamName': 'Loose Bolts'}]
USNYEXPOQ
[{'TeamNum': 12737, 'OPR': 94.824, 'Auto': 17.821, 'CCWM': 44.509, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 13371, 'OPR': 91.052, 'Auto': 20.98, 'CCWM': 20.976, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 8863, 'OPR': 75.304, 'Auto': 10.841, 'CCWM': 30.505, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 6955, 'OPR': 65.51, 'Auto': 27.376, 'CCWM': 14.912, 'TeamName': 'RoBovines'}, {'TeamNum': 13357, 'OPR': 61.707, 'Auto': 24.985, 'CCWM': 2.08, 'TeamName': 'IR Lightning'}, {'TeamNum': 14054, 'OPR': 61.395, 'Auto': 19.767, 'CCWM': 50.618, 'TeamName': 'IR Thunder'}, {'TeamNum': 20297, 'OPR': 59.555, 'Auto': 16.045, 'CCWM': 48.006, 'TeamName': 'SLCS Stormbots'}, {'TeamNum': 13359, 'OPR': 55.215, 'Auto': 15.791, 'CCWM': 25.971, 'TeamName': 'St. Lawrence Stingerz'}, {'TeamNum': 6460, 'OPR': 48.758, 'Auto': 22.52, 'CCWM': 26.921, 'TeamName': 'RoboWarriors'}, {'TeamNum': 21302, 'OPR': 47.79, 'Auto': -1.119, 'CCWM': -5.372, 'TeamName': 'HCS Robotics (CLEOB@ya)'}, {'TeamNum': 11975, 'OPR': 43.653, 'Auto': -3.079, 'CCWM': -23.106, 'TeamName': 'RoboFalcons (South Lewis HS)'}, {'TeamNum': 22612, 'OPR': 35.733, 'Auto': 2.869, 'CCWM': -15.495, 'TeamName': 'New Wave'}, {'TeamNum': 7230, 'OPR': 34.094, 'Auto': 3.128, 'CCWM': -8.957, 'TeamName': 'SAS Atoms'}, {'TeamNum': 6347, 'OPR': 25.071, 'Auto': 0.86, 'CCWM': -17.393, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 13360, 'OPR': 23.631, 'Auto': 6.253, 'CCWM': -66.695, 'TeamName': 'Franklin Academy'}, {'TeamNum': 13364, 'OPR': 20.845, 'Auto': 7.197, 'CCWM': -9.059, 'TeamName': 'Linear Lions'}, {'TeamNum': 13366, 'OPR': 11.635, 'Auto': 16.431, 'CCWM': -29.615, 'TeamName': 'Canton High School'}, {'TeamNum': 8527, 'OPR': 8.91, 'Auto': -3.74, 'CCWM': -18.402, 'TeamName': 'Bond Bots'}, {'TeamNum': 19251, 'OPR': 8.596, 'Auto': 6.703, 'CCWM': -50.186, 'TeamName': 'Code Panthers '}, {'TeamNum': 13362, 'OPR': 2.921, 'Auto': -1.428, 'CCWM': -20.217, 'TeamName': 'Loose Bolts'}]
i 956

{'21681', '12668', '6418', '22523', '10237', '8120', '7136', '11211', '6184', '8642', '20744', '8581', '11580', '14261', '14518', '13172', '10084', '19804', '20385', '1001', '7324', '12569'}
[{'TeamNum': 8642, 'OPR': 109.395, 'Auto': 29.687, 'CCWM': 57.629, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 7324, 'OPR': 84.602, 'Auto': 15.153, 'CCWM': 19.46, 'TeamName': 'Oxymorons'}, {'TeamNum': 6418, 'OPR': 82.658, 'Auto': 22.454, 'CCWM': 44.862, 'TeamName': 'NDCL Robotics'}, {'TeamNum': 10237, 'OPR': 71.865, 'Auto': 4.052, 'CCWM': 45.154, 'TeamName': 'US Robotics'}, {'TeamNum': 19804, 'OPR': 67.044, 'Auto': 31.28, 'CCWM': 27.091, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 1001, 'OPR': 65.652, 'Auto': 24.514, 'CCWM': 17.384, 'TeamName': 'Hacksaw'}, {'TeamNum': 11211, 'OPR': 63.301, 'Auto': 17.768, 'CCWM': 13.629, 'TeamName': 'Tiger Robotics'}, {'TeamNum': 20744, 'OPR': 62.429, 'Auto': 14.717, 'CCWM': 4.037, 'TeamName': '24 Karat'}, {'TeamNum': 7136, 'OPR': 59.658, 'Auto': 25.278, 'CCWM': -13.852, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 8120, 'OPR': 50.023, 'Auto': 14.466, 'CCWM': -8.034, 'TeamName': 'Electric Hornets'}, {'TeamNum': 13172, 'OPR': 49.557, 'Auto': 19.827, 'CCWM': -29.318, 'TeamName': 'Centipede'}, {'TeamNum': 12569, 'OPR': 48.979, 'Auto': 13.669, 'CCWM': -1.971, 'TeamName': 'STEMstangs'}, {'TeamNum': 10084, 'OPR': 48.738, 'Auto': 2.267, 'CCWM': 2.433, 'TeamName': 'Team Calamari'}, {'TeamNum': 22523, 'OPR': 46.031, 'Auto': 11.083, 'CCWM': 17.693, 'TeamName': 'CL0VERLEAF R0B0TICS'}, {'TeamNum': 8581, 'OPR': 42.731, 'Auto': 24.239, 'CCWM': 10.797, 'TeamName': 'Ædificatores'}, {'TeamNum': 20385, 'OPR': 40.762, 'Auto': 7.695, 'CCWM': -7.287, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 21681, 'OPR': 39.317, 'Auto': 14.588, 'CCWM': -26.492, 'TeamName': 'Moonshots'}, {'TeamNum': 6184, 'OPR': 34.612, 'Auto': 11.061, 'CCWM': -32.463, 'TeamName': 'MHS Tech Club'}, {'TeamNum': 14261, 'OPR': 30.077, 'Auto': 4.717, 'CCWM': -29.908, 'TeamName': 'Wreck Less'}, {'TeamNum': 14518, 'OPR': 29.818, 'Auto': 2.044, 'CCWM': -27.604, 'TeamName': 'RoboVikes'}, {'TeamNum': 12668, 'OPR': 21.98, 'Auto': 0.536, 'CCWM': -36.569, 'TeamName': 'BlueJays'}, {'TeamNum': 11580, 'OPR': 11.605, 'Auto': -6.095, 'CCWM': -46.671, 'TeamName': 'EagleBots'}]
USOHKEQ
[{'TeamNum': 8642, 'OPR': 109.395, 'Auto': 29.687, 'CCWM': 57.629, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 7324, 'OPR': 84.602, 'Auto': 15.153, 'CCWM': 19.46, 'TeamName': 'Oxymorons'}, {'TeamNum': 6418, 'OPR': 82.658, 'Auto': 22.454, 'CCWM': 44.862, 'TeamName': 'NDCL Robotics'}, {'TeamNum': 10237, 'OPR': 71.865, 'Auto': 4.052, 'CCWM': 45.154, 'TeamName': 'US Robotics'}, {'TeamNum': 19804, 'OPR': 67.044, 'Auto': 31.28, 'CCWM': 27.091, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 1001, 'OPR': 65.652, 'Auto': 24.514, 'CCWM': 17.384, 'TeamName': 'Hacksaw'}, {'TeamNum': 11211, 'OPR': 63.301, 'Auto': 17.768, 'CCWM': 13.629, 'TeamName': 'Tiger Robotics'}, {'TeamNum': 20744, 'OPR': 62.429, 'Auto': 14.717, 'CCWM': 4.037, 'TeamName': '24 Karat'}, {'TeamNum': 7136, 'OPR': 59.658, 'Auto': 25.278, 'CCWM': -13.852, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 8120, 'OPR': 50.023, 'Auto': 14.466, 'CCWM': -8.034, 'TeamName': 'Electric Hornets'}, {'TeamNum': 13172, 'OPR': 49.557, 'Auto': 19.827, 'CCWM': -29.318, 'TeamName': 'Centipede'}, {'TeamNum': 12569, 'OPR': 48.979, 'Auto': 13.669, 'CCWM': -1.971, 'TeamName': 'STEMstangs'}, {'TeamNum': 10084, 'OPR': 48.738, 'Auto': 2.267, 'CCWM': 2.433, 'TeamName': 'Team Calamari'}, {'TeamNum': 22523, 'OPR': 46.031, 'Auto': 11.083, 'CCWM': 17.693, 'TeamName': 'CL0VERLEAF R0B0TICS'}, {'TeamNum': 8581, 'OPR': 42.731, 'Auto': 24.239, 'CCWM': 10.797, 'TeamName': 'Ædificatores'}, {'TeamNum': 20385, 'OPR': 40.762, 'Auto': 7.695, 'CCWM': -7.287, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 21681, 'OPR': 39.317, 'Auto': 14.588, 'CCWM': -26.492, 'TeamName': 'Moonshots'}, {'TeamNum': 6184, 'OPR': 34.612, 'Auto': 11.061, 'CCWM': -32.463, 'TeamName': 'MHS Tech Club'}, {'TeamNum': 14261, 'OPR': 30.077, 'Auto': 4.717, 'CCWM': -29.908, 'TeamName': 'Wreck Less'}, {'TeamNum': 14518, 'OPR': 29.818, 'Auto': 2.044, 'CCWM': -27.604, 'TeamName': 'RoboVikes'}, {'TeamNum': 12668, 'OPR': 21.98, 'Auto': 0.536, 'CCWM': -36.569, 'TeamName': 'BlueJays'}, {'TeamNum': 11580, 'OPR': 11.605, 'Auto': -6.095, 'CCWM': -46.671, 'TeamName': 'EagleBots'}]
i 957
{'10851', '17978', '22483', '4537', '12056', '5140', '3311', '5501', '13020', '20197', '14174', '20116', '4360', '9828', '5754', '12802', '16449', '16284', '11187', '14279', '12099', '21874', '11781', '16657'}
[{'TeamNum': 5501, 'OPR': 77.517, 'Auto': 13.228, 'CCWM': 54.67, 'TeamName': 'VW Robotics'}, {'TeamNum': 4360, 'OPR': 74.213, 'Auto': 16.381, 'CCWM': 23.483, 'TeamName': 'Raider Robotics'}, {'TeamNum': 16449, 'OPR': 73.771, 'Auto': 19.734, 'CCWM': 48.078, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 12099, 'OPR': 73.67, 'Auto': 19.982, 'CCWM': 45.505, 'TeamName': 'Stars of the Galaxy'}, {'TeamNum': 17978, 'OPR': 70.063, 'Auto': 18.984, 'CCWM': 22.141, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 5754, 'OPR': 67.401, 'Auto': 16.691, 'CCWM': 40.612, 'TeamName': 'Marburn Academy Marbotics'}, {'TeamNum': 14279, 'OPR': 66.705, 'Auto': 9.268, 'CCWM': 42.57, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 14174, 'OPR': 62.887, 'Auto': 17.113, 'CCWM': 24.827, 'TeamName': 'Cougar Robotics'}, {'TeamNum': 16657, 'OPR': 58.768, 'Auto': 0.666, 'CCWM': 52.175, 'TeamName': 'We Did Start the Fire'}, {'TeamNum': 12802, 'OPR': 57.155, 'Auto': 15.188, 'CCWM': 12.153, 'TeamName': 'We Will Bot You'}, {'TeamNum': 11187, 'OPR': 54.535, 'Auto': 9.098, 'CCWM': 0.355, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 20116, 'OPR': 54.415, 'Auto': 13.338, 'CCWM': 27.063, 'TeamName': "Where's The Tape Measure? "}, {'TeamNum': 21874, 'OPR': 48.615, 'Auto': 20.992, 'CCWM': -13.587, 'TeamName': 'DRSS Discovery'}, {'TeamNum': 3311, 'OPR': 46.422, 'Auto': 7.921, 'CCWM': -25.482, 'TeamName': 'Innovators Robotics'}, {'TeamNum': 4537, 'OPR': 45.552, 'Auto': 13.917, 'CCWM': -14.903, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 5140, 'OPR': 40.017, 'Auto': 15.897, 'CCWM': 15.575, 'TeamName': 'WACO Aerobotics'}, {'TeamNum': 16284, 'OPR': 34.27, 'Auto': 9.092, 'CCWM': -19.158, 'TeamName': '8 Bit Bandits'}, {'TeamNum': 10851, 'OPR': 32.247, 'Auto': 19.094, 'CCWM': -39.72, 'TeamName': 'WASA'}, {'TeamNum': 20197, 'OPR': 26.488, 'Auto': 1.356, 'CCWM': -1.931, 'TeamName': 'OZoneJR8'}, {'TeamNum': 9828, 'OPR': 13.154, 'Auto': -2.482, 'CCWM': -33.311, 'TeamName': 'Ultron Unit '}, {'TeamNum': 12056, 'OPR': 10.118, 'Auto': -0.444, 'CCWM': -70.124, 'TeamName': 'Aves Ablaze'}, {'TeamNum': 11781, 'OPR': 5.465, 'Auto': 5.94, 'CCWM': -50.621, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 13020, 'OPR': 0.776, 'Auto': 0.758, 'CCWM': -71.763, 'TeamName': 'Golden Tiercelet'}, {'TeamNum': 22483, 'OPR': -10.388, 'Auto': -3.379, 'CCWM': -68.608, 'TeamName': 'OZoneJR7'}]
USOHWAQ
[{'TeamNum': 5501, 'OPR': 77.517, 'Auto': 13.228, 'CCWM': 54.67, 'TeamName': 'VW Robotics'}, {'TeamNum': 4360, 'OPR': 74.213, 'Auto': 16.381, 'CCWM': 23.483, 'TeamName': 'Raider Robotics'}, {'TeamNum': 16449, 'OPR': 73.771, 'Auto': 19.734, 'CCWM': 48.078, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 12099, 'OPR': 73.67, 'Auto': 19.982, 'CCWM': 45.505, 'TeamName': 'Stars of the Galaxy'}, {'TeamNum': 17978, 'OPR': 70.063, 'Auto': 18.984, 'CCWM': 22.141, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 5754, 'OPR': 67.401, 'Auto': 16.691, 'CCWM': 40.612, 'TeamName': 'Marburn Academy Marbotics'}, {'TeamNum': 14279, 'OPR': 66.705, 'Auto': 9.268, 'CCWM': 42.57, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 14174, 'OPR': 62.887, 'Auto': 17.113, 'CCWM': 24.827, 'TeamName': 'Cougar Robotics'}, {'TeamNum': 16657, 'OPR': 58.768, 'Auto': 0.666, 'CCWM': 52.175, 'TeamName': 'We Did Start the Fire'}, {'TeamNum': 12802, 'OPR': 57.155, 'Auto': 15.188, 'CCWM': 12.153, 'TeamName': 'We Will Bot You'}, {'TeamNum': 11187, 'OPR': 54.535, 'Auto': 9.098, 'CCWM': 0.355, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 20116, 'OPR': 54.415, 'Auto': 13.338, 'CCWM': 27.063, 'TeamName': "Where's The Tape Measure? "}, {'TeamNum': 21874, 'OPR': 48.615, 'Auto': 20.992, 'CCWM': -13.587, 'TeamName': 'DRSS Discovery'}, {'TeamNum': 3311, 'OPR': 46.422, 'Auto': 7.921, 'CCWM': -25.482, 'TeamName': 'Innovators Robotics'}, {'TeamNum': 4537, 'OPR': 45.552, 'Auto': 13.917, 'CCWM': -14.903, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 5140, 'OPR': 40.017, 'Auto': 15.897, 'CCWM': 15.575, 'TeamName': 'WACO Aerobotics'}, {'TeamNum': 16284, 'OPR': 34.27, 'Auto': 9.092, 'CCWM': -19.158, 'TeamName': '8 Bit Bandits'}, {'TeamNum': 10851, 'OPR': 32.247, 'Auto': 19.094, 'CCWM': -39.72, 'TeamName': 'WASA'}, {'TeamNum': 20197, 'OPR': 26.488, 'Auto': 1.356, 'CCWM': -1.931, 'TeamName': 'OZoneJR8'}, {'TeamNum': 9828, 'OPR': 13.154, 'Auto': -2.482, 'CCWM': -33.311, 'TeamName': 'Ultron Unit '}, {'TeamNum': 12056, 'OPR': 10.118, 'Auto': -0.444, 'CCWM': -70.124, 'TeamName': 'Aves Ablaze'}, {'TeamNum': 11781, 'OPR': 5.465, 'Auto': 5.94, 'CCWM': -50.621, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 13020, 'OPR': 0.776, 'Auto': 0.758, 'CCWM': -71.763, 'TeamName': 'Golden Tiercelet'}, {'TeamNum': 22483, 'OPR': -10.388, 'Auto': -3.379, 'CCWM': -68.608, 'TeamName': 'OZoneJR7'}]

i 958
{'22804', '21902', '18410', '17025', '7242', '5395', '6973', '14177', '17034', '13709', '22009', '11572', '11867', '11240', '10368', '10355', '22015', '8825', '3638', '7506', '17035', '4250', '11344', '22814', '16426', '4266', '5141', '8866', '19563', '21901', '6974', '21951'}
[{'TeamNum': 4250, 'OPR': 115.019, 'Auto': 18.263, 'CCWM': 111.64, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 7506, 'OPR': 113.241, 'Auto': 27.172, 'CCWM': 95.892, 'TeamName': 'System Overload'}, {'TeamNum': 7242, 'OPR': 109.995, 'Auto': 22.267, 'CCWM': 61.172, 'TeamName': 'BC Robocats'}, {'TeamNum': 10355, 'OPR': 90.927, 'Auto': 21.704, 'CCWM': 33.337, 'TeamName': 'Project Peacock'}, {'TeamNum': 3638, 'OPR': 84.074, 'Auto': 21.691, 'CCWM': 77.337, 'TeamName': 'Atomic Shock'}, {'TeamNum': 5141, 'OPR': 82.8, 'Auto': 15.691, 'CCWM': 66.694, 'TeamName': 'Warrior Bots'}, {'TeamNum': 11572, 'OPR': 82.306, 'Auto': 10.764, 'CCWM': 62.096, 'TeamName': 'Mouse Spit'}, {'TeamNum': 8866, 'OPR': 74.078, 'Auto': 20.832, 'CCWM': 29.024, 'TeamName': 'Cybernetics'}, {'TeamNum': 8825, 'OPR': 68.872, 'Auto': 13.538, 'CCWM': 24.008, 'TeamName': 'CADfish'}, {'TeamNum': 11240, 'OPR': 65.619, 'Auto': 0.123, 'CCWM': 65.785, 'TeamName': 'Blazing Bronc0s'}, {'TeamNum': 16426, 'OPR': 48.508, 'Auto': 0.212, 'CCWM': -14.193, 'TeamName': 'Absolute Zero'}, {'TeamNum': 22009, 'OPR': 42.611, 'Auto': 19.773, 'CCWM': 18.997, 'TeamName': 'Our Robot Overlords'}, {'TeamNum': 21951, 'OPR': 41.009, 'Auto': 11.601, 'CCWM': -2.032, 'TeamName': 'Spontanious Combustors'}, {'TeamNum': 4266, 'OPR': 37.362, 'Auto': -1.127, 'CCWM': -56.577, 'TeamName': "Makin' Stuff Move"}, {'TeamNum': 13709, 'OPR': 35.476, 'Auto': 12.315, 'CCWM': -5.638, 'TeamName': 'Null Sector'}, {'TeamNum': 14177, 'OPR': 33.885, 'Auto': 4.035, 'CCWM': -26.391, 'TeamName': 'Staticats'}, {'TeamNum': 22804, 'OPR': 32.642, 'Auto': -5.736, 'CCWM': 15.075, 'TeamName': 'Lions'}, {'TeamNum': 22015, 'OPR': 31.78, 'Auto': 11.806, 'CCWM': -2.692, 'TeamName': 'The Robo-Trojans'}, {'TeamNum': 19563, 'OPR': 30.878, 'Auto': 15.995, 'CCWM': -1.436, 'TeamName': 'Boise City BattleCats'}, {'TeamNum': 22814, 'OPR': 29.13, 'Auto': 7.602, 'CCWM': -24.841, 'TeamName': 'FS Bulldogs'}, {'TeamNum': 11867, 'OPR': 29.038, 'Auto': 0.195, 'CCWM': -18.947, 'TeamName': 'Steel Stallions'}, {'TeamNum': 17035, 'OPR': 25.235, 'Auto': 15.537, 'CCWM': -17.123, 'TeamName': 'Knightmares'}, {'TeamNum': 17034, 'OPR': 24.054, 'Auto': 8.848, 'CCWM': -69.313, 'TeamName': 'Gears of Liberty'}, {'TeamNum': 6974, 'OPR': 23.775, 'Auto': 3.946, 'CCWM': -32.615, 'TeamName': 'Monsters of Mechanics'}, {'TeamNum': 6973, 'OPR': 23.419, 'Auto': 7.529, 'CCWM': -54.494, 'TeamName': 'Radical Robotics'}, {'TeamNum': 5395, 'OPR': 22.997, 'Auto': 4.442, 'CCWM': -63.14, 'TeamName': 'Team Clutch'}, {'TeamNum': 21902, 'OPR': 19.456, 'Auto': 1.87, 'CCWM': -7.533, 'TeamName': 'Grandfather Alan'}, {'TeamNum': 11344, 'OPR': 15.83, 'Auto': 0.206, 'CCWM': -33.981, 'TeamName': 'Merritt Oilers'}, {'TeamNum': 18410, 'OPR': 11.77, 'Auto': -0.158, 'CCWM': -27.172, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 17025, 'OPR': 6.285, 'Auto': 1.593, 'CCWM': -75.808, 'TeamName': 'Iron Talons           17025'}, {'TeamNum': 10368, 'OPR': 0.126, 'Auto': -1.525, 'CCWM': -102.175, 'TeamName': 'The Level Ups'}, {'TeamNum': 21901, 'OPR': -4.998, 'Auto': -4.406, 'CCWM': -24.956, 'TeamName': 'ERR0R_405'}]
USOKOKLALT2
[{'TeamNum': 4250, 'OPR': 115.019, 'Auto': 18.263, 'CCWM': 111.64, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 7506, 'OPR': 113.241, 'Auto': 27.172, 'CCWM': 95.892, 'TeamName': 'System Overload'}, {'TeamNum': 7242, 'OPR': 109.995, 'Auto': 22.267, 'CCWM': 61.172, 'TeamName': 'BC Robocats'}, {'TeamNum': 10355, 'OPR': 90.927, 'Auto': 21.704, 'CCWM': 33.337, 'TeamName': 'Project Peacock'}, {'TeamNum': 3638, 'OPR': 84.074, 'Auto': 21.691, 'CCWM': 77.337, 'TeamName': 'Atomic Shock'}, {'TeamNum': 5141, 'OPR': 82.8, 'Auto': 15.691, 'CCWM': 66.694, 'TeamName': 'Warrior Bots'}, {'TeamNum': 11572, 'OPR': 82.306, 'Auto': 10.764, 'CCWM': 62.096, 'TeamName': 'Mouse Spit'}, {'TeamNum': 8866, 'OPR': 74.078, 'Auto': 20.832, 'CCWM': 29.024, 'TeamName': 'Cybernetics'}, {'TeamNum': 8825, 'OPR': 68.872, 'Auto': 13.538, 'CCWM': 24.008, 'TeamName': 'CADfish'}, {'TeamNum': 11240, 'OPR': 65.619, 'Auto': 0.123, 'CCWM': 65.785, 'TeamName': 'Blazing Bronc0s'}, {'TeamNum': 16426, 'OPR': 48.508, 'Auto': 0.212, 'CCWM': -14.193, 'TeamName': 'Absolute Zero'}, {'TeamNum': 22009, 'OPR': 42.611, 'Auto': 19.773, 'CCWM': 18.997, 'TeamName': 'Our Robot Overlords'}, {'TeamNum': 21951, 'OPR': 41.009, 'Auto': 11.601, 'CCWM': -2.032, 'TeamName': 'Spontanious Combustors'}, {'TeamNum': 4266, 'OPR': 37.362, 'Auto': -1.127, 'CCWM': -56.577, 'TeamName': "Makin' Stuff Move"}, {'TeamNum': 13709, 'OPR': 35.476, 'Auto': 12.315, 'CCWM': -5.638, 'TeamName': 'Null Sector'}, {'TeamNum': 14177, 'OPR': 33.885, 'Auto': 4.035, 'CCWM': -26.391, 'TeamName': 'Staticats'}, {'TeamNum': 22804, 'OPR': 32.642, 'Auto': -5.736, 'CCWM': 15.075, 'TeamName': 'Lions'}, {'TeamNum': 22015, 'OPR': 31.78, 'Auto': 11.806, 'CCWM': -2.692, 'TeamName': 'The Robo-Trojans'}, {'TeamNum': 19563, 'OPR': 30.878, 'Auto': 15.995, 'CCWM': -1.436, 'TeamName': 'Boise City BattleCats'}, {'TeamNum': 22814, 'OPR': 29.13, 'Auto': 7.602, 'CCWM': -24.841, 'TeamName': 'FS Bulldogs'}, {'TeamNum': 11867, 'OPR': 29.038, 'Auto': 0.195, 'CCWM': -18.947, 'TeamName': 'Steel Stallions'}, {'TeamNum': 17035, 'OPR': 25.235, 'Auto': 15.537, 'CCWM': -17.123, 'TeamName': 'Knightmares'}, {'TeamNum': 17034, 'OPR': 24.054, 'Auto': 8.848, 'CCWM': -69.313, 'TeamName': 'Gears of Liberty'}, {'TeamNum': 6974, 'OPR': 23.775, 'Auto': 3.946, 'CCWM': -32.615, 'TeamName': 'Monsters of Mechanics'}, {'TeamNum': 6973, 'OPR': 23.419, 'Auto': 7.529, 'CCWM': -54.494, 'TeamName': 'Radical Robotics'}, {'TeamNum': 5395, 'OPR': 22.997, 'Auto': 4.442, 'CCWM': -63.14, 'TeamName': 'Team Clutch'}, {'TeamNum': 21902, 'OPR': 19.456, 'Auto': 1.87, 'CCWM': -7.533, 'TeamName': 'Grandfather Alan'}, {'TeamNum': 11344, 'OPR': 15.83, 'Auto': 0.206, 'CCWM': -33.981, 'TeamName': 'Merritt Oilers'}, {'TeamNum': 18410, 'OPR': 11.77, 'Auto': -0.158, 'CCWM': -27.172, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 17025, 'OPR': 6.285, 'Auto': 1.593, 'CCWM': -75.808, 'TeamName': 'Iron Talons           17025'}, {'TeamNum': 10368, 'OPR': 0.126, 'Auto': -1.525, 'CCWM': -102.175, 'TeamName': 'The Level Ups'}, {'TeamNum': 21901, 'OPR': -4.998, 'Auto': -4.406, 'CCWM': -24.956, 'TeamName': 'ERR0R_405'}]
i 959
{'5039', '10274', '20229', '12076', '11545', '15341', '12693', '9487', '16433', '9567', '21231', '8161', '17520', '12695', '15342', '22503', '9339', '21739', '13189'}
[{'TeamNum': 17520, 'OPR': 100.425, 'Auto': 27.882, 'CCWM': 90.97, 'TeamName': 'Protocol 3'}, {'TeamNum': 9567, 'OPR': 88.681, 'Auto': 16.581, 'CCWM': 36.837, 'TeamName': 'Cybernetic Elks'}, {'TeamNum': 16433, 'OPR': 69.211, 'Auto': 21.59, 'CCWM': 57.692, 'TeamName': 'Quasar'}, {'TeamNum': 11545, 'OPR': 37.191, 'Auto': 15.408, 'CCWM': -7.664, 'TeamName': 'Dread Pirate Robots'}, {'TeamNum': 15342, 'OPR': 35.994, 'Auto': -5.536, 'CCWM': 2.787, 'TeamName': 'Aries'}, {'TeamNum': 9339, 'OPR': 35.819, 'Auto': 14.984, 'CCWM': -4.014, 'TeamName': 'Frog Force'}, {'TeamNum': 9487, 'OPR': 34.002, 'Auto': 1.784, 'CCWM': -1.244, 'TeamName': 'Code Red'}, {'TeamNum': 21231, 'OPR': 33.223, 'Auto': 1.274, 'CCWM': -10.372, 'TeamName': '42'}, {'TeamNum': 13189, 'OPR': 31.407, 'Auto': 3.564, 'CCWM': 17.28, 'TeamName': 'Scorpio'}, {'TeamNum': 12076, 'OPR': 29.652, 'Auto': 4.185, 'CCWM': 24.582, 'TeamName': 'Iron Hearts'}, {'TeamNum': 8161, 'OPR': 28.606, 'Auto': 8.846, 'CCWM': -0.415, 'TeamName': 'Robogoats'}, {'TeamNum': 21739, 'OPR': 28.181, 'Auto': -7.637, 'CCWM': -25.803, 'TeamName': 'Fiendriods'}, {'TeamNum': 15341, 'OPR': 27.507, 'Auto': 1.694, 'CCWM': -20.529, 'TeamName': 'Leo'}, {'TeamNum': 10274, 'OPR': 27.222, 'Auto': 11.819, 'CCWM': -39.821, 'TeamName': 'MPHS Botcats'}, {'TeamNum': 5039, 'OPR': 17.628, 'Auto': 11.02, 'CCWM': -26.235, 'TeamName': 'DevilBots'}, {'TeamNum': 22503, 'OPR': 11.561, 'Auto': 4.381, 'CCWM': -43.637, 'TeamName': 'Mixed Nuts'}, {'TeamNum': 12693, 'OPR': 10.904, 'Auto': 4.642, 'CCWM': -31.814, 'TeamName': 'Hydrogen Hammerhead'}, {'TeamNum': 12695, 'OPR': 6.081, 'Auto': 0.35, 'CCWM': -4.997, 'TeamName': 'Goonies'}, {'TeamNum': 20229, 'OPR': -2.738, 'Auto': -0.75, 'CCWM': -25.141, 'TeamName': 'CrabLads'}]
USORSOLT
[{'TeamNum': 17520, 'OPR': 100.425, 'Auto': 27.882, 'CCWM': 90.97, 'TeamName': 'Protocol 3'}, {'TeamNum': 9567, 'OPR': 88.681, 'Auto': 16.581, 'CCWM': 36.837, 'TeamName': 'Cybernetic Elks'}, {'TeamNum': 16433, 'OPR': 69.211, 'Auto': 21.59, 'CCWM': 57.692, 'TeamName': 'Quasar'}, {'TeamNum': 11545, 'OPR': 37.191, 'Auto': 15.408, 'CCWM': -7.664, 'TeamName': 'Dread Pirate Robots'}, {'TeamNum': 15342, 'OPR': 35.994, 'Auto': -5.536, 'CCWM': 2.787, 'TeamName': 'Aries'}, {'TeamNum': 9339, 'OPR': 35.819, 'Auto': 14.984, 'CCWM': -4.014, 'TeamName': 'Frog Force'}, {'TeamNum': 9487, 'OPR': 34.002, 'Auto': 1.784, 'CCWM': -1.244, 'TeamName': 'Code Red'}, {'TeamNum': 21231, 'OPR': 33.223, 'Auto': 1.274, 'CCWM': -10.372, 'TeamName': '42'}, {'TeamNum': 13189, 'OPR': 31.407, 'Auto': 3.564, 'CCWM': 17.28, 'TeamName': 'Scorpio'}, {'TeamNum': 12076, 'OPR': 29.652, 'Auto': 4.185, 'CCWM': 24.582, 'TeamName': 'Iron Hearts'}, {'TeamNum': 8161, 'OPR': 28.606, 'Auto': 8.846, 'CCWM': -0.415, 'TeamName': 'Robogoats'}, {'TeamNum': 21739, 'OPR': 28.181, 'Auto': -7.637, 'CCWM': -25.803, 'TeamName': 'Fiendriods'}, {'TeamNum': 15341, 'OPR': 27.507, 'Auto': 1.694, 'CCWM': -20.529, 'TeamName': 'Leo'}, {'TeamNum': 10274, 'OPR': 27.222, 'Auto': 11.819, 'CCWM': -39.821, 'TeamName': 'MPHS Botcats'}, {'TeamNum': 5039, 'OPR': 17.628, 'Auto': 11.02, 'CCWM': -26.235, 'TeamName': 'DevilBots'}, {'TeamNum': 22503, 'OPR': 11.561, 'Auto': 4.381, 'CCWM': -43.637, 'TeamName': 'Mixed Nuts'}, {'TeamNum': 12693, 'OPR': 10.904, 'Auto': 4.642, 'CCWM': -31.814, 'TeamName': 'Hydrogen Hammerhead'}, {'TeamNum': 12695, 'OPR': 6.081, 'Auto': 0.35, 'CCWM': -4.997, 'TeamName': 'Goonies'}, {'TeamNum': 20229, 'OPR': -2.738, 'Auto': -0.75, 'CCWM': -25.141, 'TeamName': 'CrabLads'}]

i 960
{'4711', '17564', '11591', '11441', '11890', '13749', '9470', '12110', '22515', '9357', '20304', '20855', '20431', '10332', '22516', '22559', '22649', '20288'}
[{'TeamNum': 20288, 'OPR': 89.066, 'Auto': 17.451, 'CCWM': 72.652, 'TeamName': 'Mechanical Mages'}, {'TeamNum': 11441, 'OPR': 46.151, 'Auto': -5.863, 'CCWM': 33.484, 'TeamName': 'Chronobreak'}, {'TeamNum': 12110, 'OPR': 45.14, 'Auto': 12.859, 'CCWM': 9.095, 'TeamName': 'SayWatt'}, {'TeamNum': 4711, 'OPR': 44.479, 'Auto': 14.863, 'CCWM': 4.46, 'TeamName': 'Ursa Mechanica'}, {'TeamNum': 9470, 'OPR': 41.009, 'Auto': 17.216, 'CCWM': 8.563, 'TeamName': 'The Mjoln-Gears'}, {'TeamNum': 9357, 'OPR': 28.59, 'Auto': 14.838, 'CCWM': 19.701, 'TeamName': 'Dolphines'}, {'TeamNum': 11591, 'OPR': 23.948, 'Auto': 5.167, 'CCWM': 9.805, 'TeamName': 'AEMBOT'}, {'TeamNum': 22559, 'OPR': 21.722, 'Auto': 1.638, 'CCWM': 12.704, 'TeamName': 'Winkiedinks'}, {'TeamNum': 11890, 'OPR': 17.415, 'Auto': 6.97, 'CCWM': -8.749, 'TeamName': 'ACMS Mad Machines'}, {'TeamNum': 17564, 'OPR': 14.902, 'Auto': 2.578, 'CCWM': -14.223, 'TeamName': 'ACMS Wild Wrenches'}, {'TeamNum': 10332, 'OPR': 13.274, 'Auto': 4.25, 'CCWM': -2.576, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 22516, 'OPR': 11.311, 'Auto': 5.155, 'CCWM': -0.434, 'TeamName': 'Infinity Circuit'}, {'TeamNum': 20855, 'OPR': 11.03, 'Auto': -3.208, 'CCWM': -13.863, 'TeamName': '01Cowboys'}, {'TeamNum': 20431, 'OPR': 10.288, 'Auto': 0.219, 'CCWM': -12.172, 'TeamName': 'X-RAID'}, {'TeamNum': 22515, 'OPR': 6.925, 'Auto': 1.989, 'CCWM': -14.298, 'TeamName': 'Mechanical Platypuses'}, {'TeamNum': 22649, 'OPR': -0.931, 'Auto': 0.136, 'CCWM': -20.729, 'TeamName': 'ACMS Super Servos'}, {'TeamNum': 13749, 'OPR': -1.59, 'Auto': -4.448, 'CCWM': -47.576, 'TeamName': 'EKG Pickle Pirates'}, {'TeamNum': 20304, 'OPR': -1.648, 'Auto': -7.418, 'CCWM': -41.498, 'TeamName': 'AEMDROID'}]
USORWIQ
[{'TeamNum': 20288, 'OPR': 89.066, 'Auto': 17.451, 'CCWM': 72.652, 'TeamName': 'Mechanical Mages'}, {'TeamNum': 11441, 'OPR': 46.151, 'Auto': -5.863, 'CCWM': 33.484, 'TeamName': 'Chronobreak'}, {'TeamNum': 12110, 'OPR': 45.14, 'Auto': 12.859, 'CCWM': 9.095, 'TeamName': 'SayWatt'}, {'TeamNum': 4711, 'OPR': 44.479, 'Auto': 14.863, 'CCWM': 4.46, 'TeamName': 'Ursa Mechanica'}, {'TeamNum': 9470, 'OPR': 41.009, 'Auto': 17.216, 'CCWM': 8.563, 'TeamName': 'The Mjoln-Gears'}, {'TeamNum': 9357, 'OPR': 28.59, 'Auto': 14.838, 'CCWM': 19.701, 'TeamName': 'Dolphines'}, {'TeamNum': 11591, 'OPR': 23.948, 'Auto': 5.167, 'CCWM': 9.805, 'TeamName': 'AEMBOT'}, {'TeamNum': 22559, 'OPR': 21.722, 'Auto': 1.638, 'CCWM': 12.704, 'TeamName': 'Winkiedinks'}, {'TeamNum': 11890, 'OPR': 17.415, 'Auto': 6.97, 'CCWM': -8.749, 'TeamName': 'ACMS Mad Machines'}, {'TeamNum': 17564, 'OPR': 14.902, 'Auto': 2.578, 'CCWM': -14.223, 'TeamName': 'ACMS Wild Wrenches'}, {'TeamNum': 10332, 'OPR': 13.274, 'Auto': 4.25, 'CCWM': -2.576, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 22516, 'OPR': 11.311, 'Auto': 5.155, 'CCWM': -0.434, 'TeamName': 'Infinity Circuit'}, {'TeamNum': 20855, 'OPR': 11.03, 'Auto': -3.208, 'CCWM': -13.863, 'TeamName': '01Cowboys'}, {'TeamNum': 20431, 'OPR': 10.288, 'Auto': 0.219, 'CCWM': -12.172, 'TeamName': 'X-RAID'}, {'TeamNum': 22515, 'OPR': 6.925, 'Auto': 1.989, 'CCWM': -14.298, 'TeamName': 'Mechanical Platypuses'}, {'TeamNum': 22649, 'OPR': -0.931, 'Auto': 0.136, 'CCWM': -20.729, 'TeamName': 'ACMS Super Servos'}, {'TeamNum': 13749, 'OPR': -1.59, 'Auto': -4.448, 'CCWM': -47.576, 'TeamName': 'EKG Pickle Pirates'}, {'TeamNum': 20304, 'OPR': -1.648, 'Auto': -7.418, 'CCWM': -41.498, 'TeamName': 'AEMDROID'}]
i 961
{'13347', '21680', '5321', '16664', '22280', '22245', '5488', '5320', '6676', '8480', '7883', '16941', '22285', '6606', '9854', '22247', '19688', '22284', '14738', '22246', '4914', '12308', '22283', '22279', '8730', '21864', '22281', '22282', '9570', '6552', '16800', '6540', '11493'}
[{'TeamNum': 16800, 'OPR': 69.559, 'Auto': 1.632, 'CCWM': 29.233, 'TeamName': 'Trial and Terror'}, {'TeamNum': 14738, 'OPR': 66.034, 'Auto': 13.441, 'CCWM': 41.322, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 22279, 'OPR': 55.674, 'Auto': 20.023, 'CCWM': 43.036, 'TeamName': 'SLAMtastic Squirrels'}, {'TeamNum': 22246, 'OPR': 47.934, 'Auto': 15.061, 'CCWM': 41.369, 'TeamName': 'RoboLancers Aubergine'}, {'TeamNum': 8730, 'OPR': 44.136, 'Auto': 8.846, 'CCWM': 27.554, 'TeamName': 'Robogriffins'}, {'TeamNum': 4914, 'OPR': 41.078, 'Auto': -2.883, 'CCWM': 17.137, 'TeamName': 'SCH FTC XCalibur'}, {'TeamNum': 6676, 'OPR': 40.901, 'Auto': -1.313, 'CCWM': 12.935, 'TeamName': 'RoboLancers Crimson'}, {'TeamNum': 21680, 'OPR': 37.279, 'Auto': 4.158, 'CCWM': 27.202, 'TeamName': 'Friends Select'}, {'TeamNum': 22280, 'OPR': 36.03, 'Auto': 0.448, 'CCWM': 20.275, 'TeamName': 'Into the SLAMmer'}, {'TeamNum': 22285, 'OPR': 34.335, 'Auto': 18.271, 'CCWM': 14.053, 'TeamName': 'SLAM SHADY'}, {'TeamNum': 22247, 'OPR': 33.691, 'Auto': 9.863, 'CCWM': 18.821, 'TeamName': 'RoboLancers Pumpkin'}, {'TeamNum': 16664, 'OPR': 33.682, 'Auto': 7.022, 'CCWM': 4.674, 'TeamName': 'GenBots'}, {'TeamNum': 6540, 'OPR': 32.915, 'Auto': -1.692, 'CCWM': -14.303, 'TeamName': 'Railsplitters'}, {'TeamNum': 22282, 'OPR': 26.117, 'Auto': 12.224, 'CCWM': -18.927, 'TeamName': 'SLAMPHIBIANS'}, {'TeamNum': 11493, 'OPR': 25.032, 'Auto': -0.237, 'CCWM': 8.553, 'TeamName': 'Eclipse'}, {'TeamNum': 22245, 'OPR': 24.761, 'Auto': 9.366, 'CCWM': -10.347, 'TeamName': 'RoboLancers Kale'}, {'TeamNum': 13347, 'OPR': 23.477, 'Auto': -2.17, 'CCWM': 7.624, 'TeamName': 'Project Home Robotics Team'}, {'TeamNum': 12308, 'OPR': 18.766, 'Auto': -2.575, 'CCWM': 12.646, 'TeamName': 'Bodine Ambassadors'}, {'TeamNum': 22284, 'OPR': 16.42, 'Auto': 2.155, 'CCWM': -2.822, 'TeamName': 'SLAM GREG'}, {'TeamNum': 9854, 'OPR': 16.175, 'Auto': -0.535, 'CCWM': 8.665, 'TeamName': 'Penn Charter Robotics'}, {'TeamNum': 5320, 'OPR': 15.542, 'Auto': 4.376, 'CCWM': -15.01, 'TeamName': 'RoboLancers Gold'}, {'TeamNum': 22281, 'OPR': 14.974, 'Auto': 3.384, 'CCWM': -11.699, 'TeamName': 'SLAMMMD'}, {'TeamNum': 7883, 'OPR': 13.799, 'Auto': 6.057, 'CCWM': -27.972, 'TeamName': 'Iron Patriots'}, {'TeamNum': 22283, 'OPR': 12.698, 'Auto': -0.833, 'CCWM': -12.266, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 8480, 'OPR': 11.644, 'Auto': 3.197, 'CCWM': -51.979, 'TeamName': 'Technabots'}, {'TeamNum': 6552, 'OPR': 11.127, 'Auto': 1.159, 'CCWM': -32.789, 'TeamName': 'Northeast High School'}, {'TeamNum': 6606, 'OPR': 9.636, 'Auto': -7.306, 'CCWM': -12.577, 'TeamName': 'Dobbins Force'}, {'TeamNum': 16941, 'OPR': 9.229, 'Auto': 2.394, 'CCWM': -14.553, 'TeamName': 'RoboLancers Cobalt'}, {'TeamNum': 5488, 'OPR': 8.554, 'Auto': -2.312, 'CCWM': -10.92, 'TeamName': 'Robo Dragons'}, {'TeamNum': 21864, 'OPR': 7.404, 'Auto': 0.031, 'CCWM': -35.528, 'TeamName': 'Wire Clippers'}, {'TeamNum': 19688, 'OPR': 6.111, 'Auto': 5.604, 'CCWM': -17.437, 'TeamName': 'Simply Machines'}, {'TeamNum': 9570, 'OPR': 3.479, 'Auto': -0.394, 'CCWM': -11.209, 'TeamName': 'GearGirls'}, {'TeamNum': 5321, 'OPR': 0.846, 'Auto': -1.933, 'CCWM': -40.585, 'TeamName': 'TechHeroes'}]
USPAPHQ
[{'TeamNum': 16800, 'OPR': 69.559, 'Auto': 1.632, 'CCWM': 29.233, 'TeamName': 'Trial and Terror'}, {'TeamNum': 14738, 'OPR': 66.034, 'Auto': 13.441, 'CCWM': 41.322, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 22279, 'OPR': 55.674, 'Auto': 20.023, 'CCWM': 43.036, 'TeamName': 'SLAMtastic Squirrels'}, {'TeamNum': 22246, 'OPR': 47.934, 'Auto': 15.061, 'CCWM': 41.369, 'TeamName': 'RoboLancers Aubergine'}, {'TeamNum': 8730, 'OPR': 44.136, 'Auto': 8.846, 'CCWM': 27.554, 'TeamName': 'Robogriffins'}, {'TeamNum': 4914, 'OPR': 41.078, 'Auto': -2.883, 'CCWM': 17.137, 'TeamName': 'SCH FTC XCalibur'}, {'TeamNum': 6676, 'OPR': 40.901, 'Auto': -1.313, 'CCWM': 12.935, 'TeamName': 'RoboLancers Crimson'}, {'TeamNum': 21680, 'OPR': 37.279, 'Auto': 4.158, 'CCWM': 27.202, 'TeamName': 'Friends Select'}, {'TeamNum': 22280, 'OPR': 36.03, 'Auto': 0.448, 'CCWM': 20.275, 'TeamName': 'Into the SLAMmer'}, {'TeamNum': 22285, 'OPR': 34.335, 'Auto': 18.271, 'CCWM': 14.053, 'TeamName': 'SLAM SHADY'}, {'TeamNum': 22247, 'OPR': 33.691, 'Auto': 9.863, 'CCWM': 18.821, 'TeamName': 'RoboLancers Pumpkin'}, {'TeamNum': 16664, 'OPR': 33.682, 'Auto': 7.022, 'CCWM': 4.674, 'TeamName': 'GenBots'}, {'TeamNum': 6540, 'OPR': 32.915, 'Auto': -1.692, 'CCWM': -14.303, 'TeamName': 'Railsplitters'}, {'TeamNum': 22282, 'OPR': 26.117, 'Auto': 12.224, 'CCWM': -18.927, 'TeamName': 'SLAMPHIBIANS'}, {'TeamNum': 11493, 'OPR': 25.032, 'Auto': -0.237, 'CCWM': 8.553, 'TeamName': 'Eclipse'}, {'TeamNum': 22245, 'OPR': 24.761, 'Auto': 9.366, 'CCWM': -10.347, 'TeamName': 'RoboLancers Kale'}, {'TeamNum': 13347, 'OPR': 23.477, 'Auto': -2.17, 'CCWM': 7.624, 'TeamName': 'Project Home Robotics Team'}, {'TeamNum': 12308, 'OPR': 18.766, 'Auto': -2.575, 'CCWM': 12.646, 'TeamName': 'Bodine Ambassadors'}, {'TeamNum': 22284, 'OPR': 16.42, 'Auto': 2.155, 'CCWM': -2.822, 'TeamName': 'SLAM GREG'}, {'TeamNum': 9854, 'OPR': 16.175, 'Auto': -0.535, 'CCWM': 8.665, 'TeamName': 'Penn Charter Robotics'}, {'TeamNum': 5320, 'OPR': 15.542, 'Auto': 4.376, 'CCWM': -15.01, 'TeamName': 'RoboLancers Gold'}, {'TeamNum': 22281, 'OPR': 14.974, 'Auto': 3.384, 'CCWM': -11.699, 'TeamName': 'SLAMMMD'}, {'TeamNum': 7883, 'OPR': 13.799, 'Auto': 6.057, 'CCWM': -27.972, 'TeamName': 'Iron Patriots'}, {'TeamNum': 22283, 'OPR': 12.698, 'Auto': -0.833, 'CCWM': -12.266, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 8480, 'OPR': 11.644, 'Auto': 3.197, 'CCWM': -51.979, 'TeamName': 'Technabots'}, {'TeamNum': 6552, 'OPR': 11.127, 'Auto': 1.159, 'CCWM': -32.789, 'TeamName': 'Northeast High School'}, {'TeamNum': 6606, 'OPR': 9.636, 'Auto': -7.306, 'CCWM': -12.577, 'TeamName': 'Dobbins Force'}, {'TeamNum': 16941, 'OPR': 9.229, 'Auto': 2.394, 'CCWM': -14.553, 'TeamName': 'RoboLancers Cobalt'}, {'TeamNum': 5488, 'OPR': 8.554, 'Auto': -2.312, 'CCWM': -10.92, 'TeamName': 'Robo Dragons'}, {'TeamNum': 21864, 'OPR': 7.404, 'Auto': 0.031, 'CCWM': -35.528, 'TeamName': 'Wire Clippers'}, {'TeamNum': 19688, 'OPR': 6.111, 'Auto': 5.604, 'CCWM': -17.437, 'TeamName': 'Simply Machines'}, {'TeamNum': 9570, 'OPR': 3.479, 'Auto': -0.394, 'CCWM': -11.209, 'TeamName': 'GearGirls'}, {'TeamNum': 5321, 'OPR': 0.846, 'Auto': -1.933, 'CCWM': -40.585, 'TeamName': 'TechHeroes'}]
i 962

{'22851', '673', '753', '11444', '17621', '10021', '21384', '208', '18308', '15773', '13661'}
[{'TeamNum': 17621, 'OPR': 61.658, 'Auto': 22.127, 'CCWM': 33.548, 'TeamName': 'Sea Dawgs'}, {'TeamNum': 11444, 'OPR': 61.221, 'Auto': 12.9, 'CCWM': 62.684, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 208, 'OPR': 49.556, 'Auto': 12.289, 'CCWM': 4.895, 'TeamName': 'Runic Robotics'}, {'TeamNum': 10021, 'OPR': 45.639, 'Auto': 15.616, 'CCWM': 1.081, 'TeamName': 'The Red Legion'}, {'TeamNum': 673, 'OPR': 45.406, 'Auto': 9.422, 'CCWM': 7.562, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 13661, 'OPR': 42.58, 'Auto': 17.178, 'CCWM': 3.979, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 753, 'OPR': 40.106, 'Auto': 16.591, 'CCWM': -9.784, 'TeamName': 'The GreenVillains'}, {'TeamNum': 18308, 'OPR': 29.544, 'Auto': 5.377, 'CCWM': -20.552, 'TeamName': ' Team RocketForge'}, {'TeamNum': 21384, 'OPR': 20.133, 'Auto': 3.803, 'CCWM': -19.825, 'TeamName': 'SDS Griffins'}, {'TeamNum': 15773, 'OPR': 10.544, 'Auto': 1.392, 'CCWM': -36.741, 'TeamName': 'Robodogs'}, {'TeamNum': 22851, 'OPR': 9.896, 'Auto': 0.016, 'CCWM': -32.622, 'TeamName': 'FC^2 Robotics'}]
USSCFIQ
[{'TeamNum': 17621, 'OPR': 61.658, 'Auto': 22.127, 'CCWM': 33.548, 'TeamName': 'Sea Dawgs'}, {'TeamNum': 11444, 'OPR': 61.221, 'Auto': 12.9, 'CCWM': 62.684, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 208, 'OPR': 49.556, 'Auto': 12.289, 'CCWM': 4.895, 'TeamName': 'Runic Robotics'}, {'TeamNum': 10021, 'OPR': 45.639, 'Auto': 15.616, 'CCWM': 1.081, 'TeamName': 'The Red Legion'}, {'TeamNum': 673, 'OPR': 45.406, 'Auto': 9.422, 'CCWM': 7.562, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 13661, 'OPR': 42.58, 'Auto': 17.178, 'CCWM': 3.979, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 753, 'OPR': 40.106, 'Auto': 16.591, 'CCWM': -9.784, 'TeamName': 'The GreenVillains'}, {'TeamNum': 18308, 'OPR': 29.544, 'Auto': 5.377, 'CCWM': -20.552, 'TeamName': ' Team RocketForge'}, {'TeamNum': 21384, 'OPR': 20.133, 'Auto': 3.803, 'CCWM': -19.825, 'TeamName': 'SDS Griffins'}, {'TeamNum': 15773, 'OPR': 10.544, 'Auto': 1.392, 'CCWM': -36.741, 'TeamName': 'Robodogs'}, {'TeamNum': 22851, 'OPR': 9.896, 'Auto': 0.016, 'CCWM': -32.622, 'TeamName': 'FC^2 Robotics'}]
i 963
{'5628', '6221', '15930', '21438', '9527', '16251', '8886', '22629', '4546', '7615', '20778', '12820', '4720', '11312', '3708', '19918', '21323', '5681', '17121', '21233', '16311', '20316', '11503', '3781', '11338', '19887', '12928', '19452', '12973', '16555', '12126', '7797', '21816', '21346', '21899'}
[{'TeamNum': 3708, 'OPR': 115.992, 'Auto': 27.401, 'CCWM': 63.048, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 9527, 'OPR': 104.004, 'Auto': 30.794, 'CCWM': 24.743, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 12928, 'OPR': 95.291, 'Auto': 30.345, 'CCWM': 48.256, 'TeamName': 'LightSaders'}, {'TeamNum': 19452, 'OPR': 94.746, 'Auto': 21.057, 'CCWM': 6.509, 'TeamName': 'Robocats'}, {'TeamNum': 8886, 'OPR': 92.519, 'Auto': 7.416, 'CCWM': 40.006, 'TeamName': 'Saber Robotics'}, {'TeamNum': 21816, 'OPR': 92.287, 'Auto': 21.239, 'CCWM': 37.333, 'TeamName': 'Robo Eagles'}, {'TeamNum': 7797, 'OPR': 87.652, 'Auto': 23.326, 'CCWM': 45.494, 'TeamName': 'Victorian Voltage'}, {'TeamNum': 16555, 'OPR': 76.587, 'Auto': 17.68, 'CCWM': -4.496, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 11503, 'OPR': 75.677, 'Auto': 22.493, 'CCWM': 12.846, 'TeamName': 'ViperBots HyperFang'}, {'TeamNum': 16311, 'OPR': 74.872, 'Auto': 13.664, 'CCWM': 23.805, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 3781, 'OPR': 72.544, 'Auto': 4.473, 'CCWM': 57.603, 'TeamName': 'Pi-Rho Maniacs'}, {'TeamNum': 4546, 'OPR': 70.368, 'Auto': 9.55, 'CCWM': 19.684, 'TeamName': 'ViperBots SnakeByte'}, {'TeamNum': 21323, 'OPR': 70.2, 'Auto': 24.847, 'CCWM': 12.284, 'TeamName': 'TrinityBots'}, {'TeamNum': 15930, 'OPR': 69.325, 'Auto': 15.54, 'CCWM': 21.944, 'TeamName': 'Pirates'}, {'TeamNum': 21438, 'OPR': 67.792, 'Auto': 18.466, 'CCWM': 7.704, 'TeamName': 'Chaotic Current'}, {'TeamNum': 7615, 'OPR': 63.672, 'Auto': 15.466, 'CCWM': -16.263, 'TeamName': 'Mechanical Mustangs Affirmed'}, {'TeamNum': 5628, 'OPR': 61.809, 'Auto': 28.24, 'CCWM': -0.535, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 20316, 'OPR': 55.875, 'Auto': 3.139, 'CCWM': -27.283, 'TeamName': 'Crimson Comets'}, {'TeamNum': 21233, 'OPR': 54.035, 'Auto': -6.858, 'CCWM': 4.686, 'TeamName': 'Tech Syndicate'}, {'TeamNum': 21899, 'OPR': 52.82, 'Auto': 1.944, 'CCWM': 8.849, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 12820, 'OPR': 50.741, 'Auto': 14.195, 'CCWM': 19.121, 'TeamName': 'Wagner TRILOBYTES'}, {'TeamNum': 19887, 'OPR': 43.476, 'Auto': 13.146, 'CCWM': -2.819, 'TeamName': 'Shiner St. Paul Cardinals'}, {'TeamNum': 22629, 'OPR': 41.213, 'Auto': 4.087, 'CCWM': -32.416, 'TeamName': 'Morales Jr High'}, {'TeamNum': 11312, 'OPR': 38.953, 'Auto': 0.446, 'CCWM': 4.297, 'TeamName': 'JSTEM Lightning: Bolts'}, {'TeamNum': 6221, 'OPR': 37.589, 'Auto': 2.212, 'CCWM': -29.877, 'TeamName': 'Panther Bots Alpha'}, {'TeamNum': 12973, 'OPR': 34.163, 'Auto': 10.618, 'CCWM': -3.537, 'TeamName': 'Reicher Robotics'}, {'TeamNum': 4720, 'OPR': 33.54, 'Auto': 1.539, 'CCWM': -22.372, 'TeamName': 'STEAM Newton'}, {'TeamNum': 12126, 'OPR': 30.305, 'Auto': -0.214, 'CCWM': -32.128, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 21346, 'OPR': 29.592, 'Auto': 20.392, 'CCWM': 1.927, 'TeamName': 'BASIS Some Assembly Required'}, {'TeamNum': 20778, 'OPR': 26.944, 'Auto': -2.913, 'CCWM': -52.642, 'TeamName': 'Brentwood Bots'}, {'TeamNum': 17121, 'OPR': 17.995, 'Auto': -2.885, 'CCWM': -0.052, 'TeamName': 'Ronald Reagan Robotics'}, {'TeamNum': 5681, 'OPR': 15.642, 'Auto': 7.566, 'CCWM': -39.409, 'TeamName': 'Robo Pirates'}, {'TeamNum': 16251, 'OPR': 15.605, 'Auto': 6.83, 'CCWM': -72.985, 'TeamName': 'Robo Pirates'}, {'TeamNum': 19918, 'OPR': 13.062, 'Auto': 4.047, 'CCWM': -40.621, 'TeamName': 'Robo-Eagles'}, {'TeamNum': 11338, 'OPR': 1.994, 'Auto': 0.272, 'CCWM': -76.731, 'TeamName': 'JSTEM Lightning: McQueens'}]
USTXCEBUSQ
[{'TeamNum': 3708, 'OPR': 115.992, 'Auto': 27.401, 'CCWM': 63.048, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 9527, 'OPR': 104.004, 'Auto': 30.794, 'CCWM': 24.743, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 12928, 'OPR': 95.291, 'Auto': 30.345, 'CCWM': 48.256, 'TeamName': 'LightSaders'}, {'TeamNum': 19452, 'OPR': 94.746, 'Auto': 21.057, 'CCWM': 6.509, 'TeamName': 'Robocats'}, {'TeamNum': 8886, 'OPR': 92.519, 'Auto': 7.416, 'CCWM': 40.006, 'TeamName': 'Saber Robotics'}, {'TeamNum': 21816, 'OPR': 92.287, 'Auto': 21.239, 'CCWM': 37.333, 'TeamName': 'Robo Eagles'}, {'TeamNum': 7797, 'OPR': 87.652, 'Auto': 23.326, 'CCWM': 45.494, 'TeamName': 'Victorian Voltage'}, {'TeamNum': 16555, 'OPR': 76.587, 'Auto': 17.68, 'CCWM': -4.496, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 11503, 'OPR': 75.677, 'Auto': 22.493, 'CCWM': 12.846, 'TeamName': 'ViperBots HyperFang'}, {'TeamNum': 16311, 'OPR': 74.872, 'Auto': 13.664, 'CCWM': 23.805, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 3781, 'OPR': 72.544, 'Auto': 4.473, 'CCWM': 57.603, 'TeamName': 'Pi-Rho Maniacs'}, {'TeamNum': 4546, 'OPR': 70.368, 'Auto': 9.55, 'CCWM': 19.684, 'TeamName': 'ViperBots SnakeByte'}, {'TeamNum': 21323, 'OPR': 70.2, 'Auto': 24.847, 'CCWM': 12.284, 'TeamName': 'TrinityBots'}, {'TeamNum': 15930, 'OPR': 69.325, 'Auto': 15.54, 'CCWM': 21.944, 'TeamName': 'Pirates'}, {'TeamNum': 21438, 'OPR': 67.792, 'Auto': 18.466, 'CCWM': 7.704, 'TeamName': 'Chaotic Current'}, {'TeamNum': 7615, 'OPR': 63.672, 'Auto': 15.466, 'CCWM': -16.263, 'TeamName': 'Mechanical Mustangs Affirmed'}, {'TeamNum': 5628, 'OPR': 61.809, 'Auto': 28.24, 'CCWM': -0.535, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 20316, 'OPR': 55.875, 'Auto': 3.139, 'CCWM': -27.283, 'TeamName': 'Crimson Comets'}, {'TeamNum': 21233, 'OPR': 54.035, 'Auto': -6.858, 'CCWM': 4.686, 'TeamName': 'Tech Syndicate'}, {'TeamNum': 21899, 'OPR': 52.82, 'Auto': 1.944, 'CCWM': 8.849, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 12820, 'OPR': 50.741, 'Auto': 14.195, 'CCWM': 19.121, 'TeamName': 'Wagner TRILOBYTES'}, {'TeamNum': 19887, 'OPR': 43.476, 'Auto': 13.146, 'CCWM': -2.819, 'TeamName': 'Shiner St. Paul Cardinals'}, {'TeamNum': 22629, 'OPR': 41.213, 'Auto': 4.087, 'CCWM': -32.416, 'TeamName': 'Morales Jr High'}, {'TeamNum': 11312, 'OPR': 38.953, 'Auto': 0.446, 'CCWM': 4.297, 'TeamName': 'JSTEM Lightning: Bolts'}, {'TeamNum': 6221, 'OPR': 37.589, 'Auto': 2.212, 'CCWM': -29.877, 'TeamName': 'Panther Bots Alpha'}, {'TeamNum': 12973, 'OPR': 34.163, 'Auto': 10.618, 'CCWM': -3.537, 'TeamName': 'Reicher Robotics'}, {'TeamNum': 4720, 'OPR': 33.54, 'Auto': 1.539, 'CCWM': -22.372, 'TeamName': 'STEAM Newton'}, {'TeamNum': 12126, 'OPR': 30.305, 'Auto': -0.214, 'CCWM': -32.128, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 21346, 'OPR': 29.592, 'Auto': 20.392, 'CCWM': 1.927, 'TeamName': 'BASIS Some Assembly Required'}, {'TeamNum': 20778, 'OPR': 26.944, 'Auto': -2.913, 'CCWM': -52.642, 'TeamName': 'Brentwood Bots'}, {'TeamNum': 17121, 'OPR': 17.995, 'Auto': -2.885, 'CCWM': -0.052, 'TeamName': 'Ronald Reagan Robotics'}, {'TeamNum': 5681, 'OPR': 15.642, 'Auto': 7.566, 'CCWM': -39.409, 'TeamName': 'Robo Pirates'}, {'TeamNum': 16251, 'OPR': 15.605, 'Auto': 6.83, 'CCWM': -72.985, 'TeamName': 'Robo Pirates'}, {'TeamNum': 19918, 'OPR': 13.062, 'Auto': 4.047, 'CCWM': -40.621, 'TeamName': 'Robo-Eagles'}, {'TeamNum': 11338, 'OPR': 1.994, 'Auto': 0.272, 'CCWM': -76.731, 'TeamName': 'JSTEM Lightning: McQueens'}]

i 964
{'13948', '21799', '22054', '11720', '12032', '19851', '20232', '21997', '5470', '17364', '21581', '15450', '20725', '22361', '22182', '21911', '16699', '14913', '22183', '5911'}
[{'TeamNum': 13948, 'OPR': 84.416, 'Auto': 18.286, 'CCWM': 102.803, 'TeamName': 'Cathedral Robotics'}, {'TeamNum': 14913, 'OPR': 73.169, 'Auto': 3.788, 'CCWM': 54.963, 'TeamName': 'Ram Jam'}, {'TeamNum': 5911, 'OPR': 71.414, 'Auto': 8.005, 'CCWM': 1.767, 'TeamName': 'Mean Green Machine'}, {'TeamNum': 15450, 'OPR': 68.689, 'Auto': 22.412, 'CCWM': 79.423, 'TeamName': 'Da Vinci Dragons Thunder'}, {'TeamNum': 12032, 'OPR': 64.517, 'Auto': 10.993, 'CCWM': 43.122, 'TeamName': 'SparTex'}, {'TeamNum': 22054, 'OPR': 54.46, 'Auto': -0.401, 'CCWM': 27.671, 'TeamName': 'Zapper Dragons'}, {'TeamNum': 5470, 'OPR': 48.374, 'Auto': 22.057, 'CCWM': 15.192, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 16699, 'OPR': 45.428, 'Auto': 7.272, 'CCWM': 38.954, 'TeamName': 'RoboMoose'}, {'TeamNum': 22182, 'OPR': 32.227, 'Auto': 10.197, 'CCWM': -27.018, 'TeamName': 'Da Vinci Dragons Lightning'}, {'TeamNum': 11720, 'OPR': 31.22, 'Auto': 4.33, 'CCWM': 20.208, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 21997, 'OPR': 21.471, 'Auto': -1.898, 'CCWM': -48.032, 'TeamName': 'RoboDragons Sabotage'}, {'TeamNum': 20232, 'OPR': 19.558, 'Auto': -0.471, 'CCWM': -21.346, 'TeamName': 'Spicy 27'}, {'TeamNum': 20725, 'OPR': 18.342, 'Auto': 0.054, 'CCWM': -44.706, 'TeamName': 'Aztec Robotics1'}, {'TeamNum': 19851, 'OPR': 17.838, 'Auto': 12.018, 'CCWM': 11.841, 'TeamName': 'Cyber Moose'}, {'TeamNum': 22183, 'OPR': 14.114, 'Auto': -1.745, 'CCWM': 0.571, 'TeamName': 'Robowolves'}, {'TeamNum': 22361, 'OPR': 9.298, 'Auto': -3.584, 'CCWM': -78.574, 'TeamName': 'Electro Moose'}, {'TeamNum': 17364, 'OPR': 5.411, 'Auto': 1.453, 'CCWM': 19.475, 'TeamName': 'TECHNO MOOSE'}, {'TeamNum': 21799, 'OPR': 3.667, 'Auto': 0.064, 'CCWM': -54.846, 'TeamName': 'CyberStallionz'}, {'TeamNum': 21581, 'OPR': 2.184, 'Auto': -6.641, 'CCWM': -52.538, 'TeamName': 'RISE'}, {'TeamNum': 21911, 'OPR': -18.195, 'Auto': -0.188, 'CCWM': -88.931, 'TeamName': 'Blazer Bots'}]
USTXWPEPLT
[{'TeamNum': 13948, 'OPR': 84.416, 'Auto': 18.286, 'CCWM': 102.803, 'TeamName': 'Cathedral Robotics'}, {'TeamNum': 14913, 'OPR': 73.169, 'Auto': 3.788, 'CCWM': 54.963, 'TeamName': 'Ram Jam'}, {'TeamNum': 5911, 'OPR': 71.414, 'Auto': 8.005, 'CCWM': 1.767, 'TeamName': 'Mean Green Machine'}, {'TeamNum': 15450, 'OPR': 68.689, 'Auto': 22.412, 'CCWM': 79.423, 'TeamName': 'Da Vinci Dragons Thunder'}, {'TeamNum': 12032, 'OPR': 64.517, 'Auto': 10.993, 'CCWM': 43.122, 'TeamName': 'SparTex'}, {'TeamNum': 22054, 'OPR': 54.46, 'Auto': -0.401, 'CCWM': 27.671, 'TeamName': 'Zapper Dragons'}, {'TeamNum': 5470, 'OPR': 48.374, 'Auto': 22.057, 'CCWM': 15.192, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 16699, 'OPR': 45.428, 'Auto': 7.272, 'CCWM': 38.954, 'TeamName': 'RoboMoose'}, {'TeamNum': 22182, 'OPR': 32.227, 'Auto': 10.197, 'CCWM': -27.018, 'TeamName': 'Da Vinci Dragons Lightning'}, {'TeamNum': 11720, 'OPR': 31.22, 'Auto': 4.33, 'CCWM': 20.208, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 21997, 'OPR': 21.471, 'Auto': -1.898, 'CCWM': -48.032, 'TeamName': 'RoboDragons Sabotage'}, {'TeamNum': 20232, 'OPR': 19.558, 'Auto': -0.471, 'CCWM': -21.346, 'TeamName': 'Spicy 27'}, {'TeamNum': 20725, 'OPR': 18.342, 'Auto': 0.054, 'CCWM': -44.706, 'TeamName': 'Aztec Robotics1'}, {'TeamNum': 19851, 'OPR': 17.838, 'Auto': 12.018, 'CCWM': 11.841, 'TeamName': 'Cyber Moose'}, {'TeamNum': 22183, 'OPR': 14.114, 'Auto': -1.745, 'CCWM': 0.571, 'TeamName': 'Robowolves'}, {'TeamNum': 22361, 'OPR': 9.298, 'Auto': -3.584, 'CCWM': -78.574, 'TeamName': 'Electro Moose'}, {'TeamNum': 17364, 'OPR': 5.411, 'Auto': 1.453, 'CCWM': 19.475, 'TeamName': 'TECHNO MOOSE'}, {'TeamNum': 21799, 'OPR': 3.667, 'Auto': 0.064, 'CCWM': -54.846, 'TeamName': 'CyberStallionz'}, {'TeamNum': 21581, 'OPR': 2.184, 'Auto': -6.641, 'CCWM': -52.538, 'TeamName': 'RISE'}, {'TeamNum': 21911, 'OPR': -18.195, 'Auto': -0.188, 'CCWM': -88.931, 'TeamName': 'Blazer Bots'}]
i 965
{'8080', '16335', '18071', '8790', '14785', '10064', '4454', '20000', '22058', '22336', '6455', '21962', '9840'}
[{'TeamNum': 9840, 'OPR': 68.111, 'Auto': 21.79, 'CCWM': 42.407, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 57.241, 'Auto': 17.293, 'CCWM': 36.049, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 8080, 'OPR': 42.984, 'Auto': -0.909, 'CCWM': 16.594, 'TeamName': 'Ironclad'}, {'TeamNum': 18071, 'OPR': 39.764, 'Auto': 1.471, 'CCWM': 24.869, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 14785, 'OPR': 35.481, 'Auto': 12.993, 'CCWM': 9.724, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 22058, 'OPR': 32.189, 'Auto': -1.173, 'CCWM': -3.509, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 4454, 'OPR': 29.547, 'Auto': 0.736, 'CCWM': -8.963, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 10064, 'OPR': 19.52, 'Auto': 2.656, 'CCWM': -14.875, 'TeamName': 'Lady Gears'}, {'TeamNum': 16335, 'OPR': 15.986, 'Auto': 1.203, 'CCWM': -0.336, 'TeamName': 'The Ruthless Robots 16335'}, {'TeamNum': 6455, 'OPR': 9.889, 'Auto': 2.423, 'CCWM': -2.445, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 8790, 'OPR': 6.652, 'Auto': 2.775, 'CCWM': -14.362, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 22336, 'OPR': 5.52, 'Auto': -4.609, 'CCWM': -47.453, 'TeamName': 'Steel Circuits'}, {'TeamNum': 20000, 'OPR': 0.063, 'Auto': -1.654, 'CCWM': -45.063, 'TeamName': 'Park Bots'}]
USTXHOWLM3
[{'TeamNum': 9840, 'OPR': 68.111, 'Auto': 21.79, 'CCWM': 42.407, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 57.241, 'Auto': 17.293, 'CCWM': 36.049, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 8080, 'OPR': 42.984, 'Auto': -0.909, 'CCWM': 16.594, 'TeamName': 'Ironclad'}, {'TeamNum': 18071, 'OPR': 39.764, 'Auto': 1.471, 'CCWM': 24.869, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 14785, 'OPR': 35.481, 'Auto': 12.993, 'CCWM': 9.724, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 22058, 'OPR': 32.189, 'Auto': -1.173, 'CCWM': -3.509, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 4454, 'OPR': 29.547, 'Auto': 0.736, 'CCWM': -8.963, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 10064, 'OPR': 19.52, 'Auto': 2.656, 'CCWM': -14.875, 'TeamName': 'Lady Gears'}, {'TeamNum': 16335, 'OPR': 15.986, 'Auto': 1.203, 'CCWM': -0.336, 'TeamName': 'The Ruthless Robots 16335'}, {'TeamNum': 6455, 'OPR': 9.889, 'Auto': 2.423, 'CCWM': -2.445, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 8790, 'OPR': 6.652, 'Auto': 2.775, 'CCWM': -14.362, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 22336, 'OPR': 5.52, 'Auto': -4.609, 'CCWM': -47.453, 'TeamName': 'Steel Circuits'}, {'TeamNum': 20000, 'OPR': 0.063, 'Auto': -1.654, 'CCWM': -45.063, 'TeamName': 'Park Bots'}]
i 966
{'21856', '5891', '19428', '17251', '22329', '17511', '15592', '17461', '4921', '4895', '12366', '4894', '22836', '10676', '13788', '21985', '18990', '18318', '4859', '19432', '17512', '19433', '13825'}
[{'TeamNum': 21856, 'OPR': 85.108, 'Auto': 18.082, 'CCWM': 58.839, 'TeamName': 'J-Bots'}, {'TeamNum': 4921, 'OPR': 64.735, 'Auto': 15.486, 'CCWM': 20.098, 'TeamName': 'The Dropouts'}, {'TeamNum': 4895, 'OPR': 46.909, 'Auto': 16.963, 'CCWM': 8.876, 'TeamName': 'The Dueling Westerners\t'}, {'TeamNum': 18318, 'OPR': 27.788, 'Auto': -0.054, 'CCWM': 25.107, 'TeamName': 'Matador Robotics'}, {'TeamNum': 22329, 'OPR': 25.931, 'Auto': -0.523, 'CCWM': -14.335, 'TeamName': 'Westernators'}, {'TeamNum': 18990, 'OPR': 25.333, 'Auto': -0.195, 'CCWM': 14.745, 'TeamName': 'Irons Team 4'}, {'TeamNum': 10676, 'OPR': 24.519, 'Auto': 1.5, 'CCWM': 11.719, 'TeamName': 'Lady Warbots'}, {'TeamNum': 17512, 'OPR': 23.606, 'Auto': 2.272, 'CCWM': 9.338, 'TeamName': 'Irons Team 1'}, {'TeamNum': 15592, 'OPR': 23.441, 'Auto': -2.679, 'CCWM': 29.114, 'TeamName': 'T-Force'}, {'TeamNum': 12366, 'OPR': 21.273, 'Auto': -0.69, 'CCWM': -0.501, 'TeamName': 'Houndbot'}, {'TeamNum': 17251, 'OPR': 20.454, 'Auto': 0.374, 'CCWM': -9.994, 'TeamName': 'Divide & Conquer'}, {'TeamNum': 4859, 'OPR': 18.718, 'Auto': -0.339, 'CCWM': -11.98, 'TeamName': 'Westerner Mechnoblades'}, {'TeamNum': 13825, 'OPR': 17.998, 'Auto': 2.886, 'CCWM': 1.846, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 21985, 'OPR': 15.823, 'Auto': 0.042, 'CCWM': 2.323, 'TeamName': 'Throckmorton Greyhounds'}, {'TeamNum': 13788, 'OPR': 13.4, 'Auto': 2.979, 'CCWM': -8.293, 'TeamName': 'Talkington Tinies'}, {'TeamNum': 17511, 'OPR': 9.305, 'Auto': 4.079, 'CCWM': -23.924, 'TeamName': 'Irons Team 2'}, {'TeamNum': 4894, 'OPR': 8.143, 'Auto': 2.697, 'CCWM': -16.589, 'TeamName': "Waggish Walen's Western Warblers\t"}, {'TeamNum': 19428, 'OPR': 7.128, 'Auto': 3.566, 'CCWM': -4.42, 'TeamName': 'Purple People Eaters'}, {'TeamNum': 17461, 'OPR': 6.421, 'Auto': 2.085, 'CCWM': -26.336, 'TeamName': 'Trial & Error'}, {'TeamNum': 5891, 'OPR': 5.425, 'Auto': 1.672, 'CCWM': -14.406, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 22836, 'OPR': 5.378, 'Auto': -0.332, 'CCWM': -12.581, 'TeamName': 'WILDCAT_ROBOTICS'}, {'TeamNum': 19432, 'OPR': 3.645, 'Auto': 0.04, 'CCWM': -21.979, 'TeamName': 'The Bobs'}, {'TeamNum': 19433, 'OPR': 2.354, 'Auto': 3.283, 'CCWM': -17.129, 'TeamName': 'Astros in the Ocean'}]
USTXWPLALTA
[{'TeamNum': 21856, 'OPR': 85.108, 'Auto': 18.082, 'CCWM': 58.839, 'TeamName': 'J-Bots'}, {'TeamNum': 4921, 'OPR': 64.735, 'Auto': 15.486, 'CCWM': 20.098, 'TeamName': 'The Dropouts'}, {'TeamNum': 4895, 'OPR': 46.909, 'Auto': 16.963, 'CCWM': 8.876, 'TeamName': 'The Dueling Westerners\t'}, {'TeamNum': 18318, 'OPR': 27.788, 'Auto': -0.054, 'CCWM': 25.107, 'TeamName': 'Matador Robotics'}, {'TeamNum': 22329, 'OPR': 25.931, 'Auto': -0.523, 'CCWM': -14.335, 'TeamName': 'Westernators'}, {'TeamNum': 18990, 'OPR': 25.333, 'Auto': -0.195, 'CCWM': 14.745, 'TeamName': 'Irons Team 4'}, {'TeamNum': 10676, 'OPR': 24.519, 'Auto': 1.5, 'CCWM': 11.719, 'TeamName': 'Lady Warbots'}, {'TeamNum': 17512, 'OPR': 23.606, 'Auto': 2.272, 'CCWM': 9.338, 'TeamName': 'Irons Team 1'}, {'TeamNum': 15592, 'OPR': 23.441, 'Auto': -2.679, 'CCWM': 29.114, 'TeamName': 'T-Force'}, {'TeamNum': 12366, 'OPR': 21.273, 'Auto': -0.69, 'CCWM': -0.501, 'TeamName': 'Houndbot'}, {'TeamNum': 17251, 'OPR': 20.454, 'Auto': 0.374, 'CCWM': -9.994, 'TeamName': 'Divide & Conquer'}, {'TeamNum': 4859, 'OPR': 18.718, 'Auto': -0.339, 'CCWM': -11.98, 'TeamName': 'Westerner Mechnoblades'}, {'TeamNum': 13825, 'OPR': 17.998, 'Auto': 2.886, 'CCWM': 1.846, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 21985, 'OPR': 15.823, 'Auto': 0.042, 'CCWM': 2.323, 'TeamName': 'Throckmorton Greyhounds'}, {'TeamNum': 13788, 'OPR': 13.4, 'Auto': 2.979, 'CCWM': -8.293, 'TeamName': 'Talkington Tinies'}, {'TeamNum': 17511, 'OPR': 9.305, 'Auto': 4.079, 'CCWM': -23.924, 'TeamName': 'Irons Team 2'}, {'TeamNum': 4894, 'OPR': 8.143, 'Auto': 2.697, 'CCWM': -16.589, 'TeamName': "Waggish Walen's Western Warblers\t"}, {'TeamNum': 19428, 'OPR': 7.128, 'Auto': 3.566, 'CCWM': -4.42, 'TeamName': 'Purple People Eaters'}, {'TeamNum': 17461, 'OPR': 6.421, 'Auto': 2.085, 'CCWM': -26.336, 'TeamName': 'Trial & Error'}, {'TeamNum': 5891, 'OPR': 5.425, 'Auto': 1.672, 'CCWM': -14.406, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 22836, 'OPR': 5.378, 'Auto': -0.332, 'CCWM': -12.581, 'TeamName': 'WILDCAT_ROBOTICS'}, {'TeamNum': 19432, 'OPR': 3.645, 'Auto': 0.04, 'CCWM': -21.979, 'TeamName': 'The Bobs'}, {'TeamNum': 19433, 'OPR': 2.354, 'Auto': 3.283, 'CCWM': -17.129, 'TeamName': 'Astros in the Ocean'}]

i 967
i 968
{'10752', '17318', '21891', '14069', '16930', '10963', '21890', '16816'}
[{'TeamNum': 16930, 'OPR': 102.37, 'Auto': 24.959, 'CCWM': 72.881, 'TeamName': 'Omen'}, {'TeamNum': 16816, 'OPR': 47.001, 'Auto': 3.745, 'CCWM': -14.952, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 17318, 'OPR': 40.715, 'Auto': 5.53, 'CCWM': 29.619, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 14069, 'OPR': 38.251, 'Auto': 1.12, 'CCWM': 8.762, 'TeamName': 'KnightBots'}, {'TeamNum': 21891, 'OPR': 35.965, 'Auto': 11.905, 'CCWM': -10.095, 'TeamName': 'Glowbotics'}, {'TeamNum': 21890, 'OPR': 30.692, 'Auto': -1.738, 'CCWM': 5.738, 'TeamName': "St. John's Robotics"}, {'TeamNum': 10963, 'OPR': 15.692, 'Auto': 2.762, 'CCWM': -1.405, 'TeamName': ' KI Falcons'}, {'TeamNum': 10752, 'OPR': -6.487, 'Auto': -2.684, 'CCWM': -90.548, 'TeamName': 'The Power Rangers'}]
USTXHOCLM2
[{'TeamNum': 16930, 'OPR': 102.37, 'Auto': 24.959, 'CCWM': 72.881, 'TeamName': 'Omen'}, {'TeamNum': 16816, 'OPR': 47.001, 'Auto': 3.745, 'CCWM': -14.952, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 17318, 'OPR': 40.715, 'Auto': 5.53, 'CCWM': 29.619, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 14069, 'OPR': 38.251, 'Auto': 1.12, 'CCWM': 8.762, 'TeamName': 'KnightBots'}, {'TeamNum': 21891, 'OPR': 35.965, 'Auto': 11.905, 'CCWM': -10.095, 'TeamName': 'Glowbotics'}, {'TeamNum': 21890, 'OPR': 30.692, 'Auto': -1.738, 'CCWM': 5.738, 'TeamName': "St. John's Robotics"}, {'TeamNum': 10963, 'OPR': 15.692, 'Auto': 2.762, 'CCWM': -1.405, 'TeamName': ' KI Falcons'}, {'TeamNum': 10752, 'OPR': -6.487, 'Auto': -2.684, 'CCWM': -90.548, 'TeamName': 'The Power Rangers'}]
i 969
{'12364', '10752', '12846', '17318', '21891', '14069', '16930', '10963', '21890', '16816'}
[{'TeamNum': 21891, 'OPR': 79.26, 'Auto': 10.068, 'CCWM': 49.476, 'TeamName': 'Glowbotics'}, {'TeamNum': 21890, 'OPR': 68.455, 'Auto': 3.167, 'CCWM': 71.035, 'TeamName': "St. John's Robotics"}, {'TeamNum': 16930, 'OPR': 65.176, 'Auto': 16.851, 'CCWM': 10.077, 'TeamName': 'Omen'}, {'TeamNum': 10963, 'OPR': 44.561, 'Auto': 4.259, 'CCWM': -5.223, 'TeamName': ' KI Falcons'}, {'TeamNum': 14069, 'OPR': 25.439, 'Auto': -2.939, 'CCWM': -24.608, 'TeamName': 'KnightBots'}, {'TeamNum': 17318, 'OPR': 24.089, 'Auto': -3.351, 'CCWM': 6.745, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 12364, 'OPR': 15.688, 'Auto': 6.355, 'CCWM': -19.481, 'TeamName': 'KNIGHTRON'}, {'TeamNum': 12846, 'OPR': 12.945, 'Auto': 4.015, 'CCWM': 0.897, 'TeamName': 'Dynamic Gears'}, {'TeamNum': 10752, 'OPR': 6.155, 'Auto': -3.101, 'CCWM': -4.19, 'TeamName': 'The Power Rangers'}, {'TeamNum': 16816, 'OPR': -11.666, 'Auto': -0.752, 'CCWM': -69.908, 'TeamName': 'IOKNIGHT'}]
USTXHOCLM3
[{'TeamNum': 21891, 'OPR': 79.26, 'Auto': 10.068, 'CCWM': 49.476, 'TeamName': 'Glowbotics'}, {'TeamNum': 21890, 'OPR': 68.455, 'Auto': 3.167, 'CCWM': 71.035, 'TeamName': "St. John's Robotics"}, {'TeamNum': 16930, 'OPR': 65.176, 'Auto': 16.851, 'CCWM': 10.077, 'TeamName': 'Omen'}, {'TeamNum': 10963, 'OPR': 44.561, 'Auto': 4.259, 'CCWM': -5.223, 'TeamName': ' KI Falcons'}, {'TeamNum': 14069, 'OPR': 25.439, 'Auto': -2.939, 'CCWM': -24.608, 'TeamName': 'KnightBots'}, {'TeamNum': 17318, 'OPR': 24.089, 'Auto': -3.351, 'CCWM': 6.745, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 12364, 'OPR': 15.688, 'Auto': 6.355, 'CCWM': -19.481, 'TeamName': 'KNIGHTRON'}, {'TeamNum': 12846, 'OPR': 12.945, 'Auto': 4.015, 'CCWM': 0.897, 'TeamName': 'Dynamic Gears'}, {'TeamNum': 10752, 'OPR': 6.155, 'Auto': -3.101, 'CCWM': -4.19, 'TeamName': 'The Power Rangers'}, {'TeamNum': 16816, 'OPR': -11.666, 'Auto': -0.752, 'CCWM': -69.908, 'TeamName': 'IOKNIGHT'}]
i 970
{'20249', '19947', '22895', '11947', '10055', '22236', '13822', '21386', '22045', '14503', '12456', '22717', '20394', '16685', '10354'}
[{'TeamNum': 14503, 'OPR': 109.518, 'Auto': 40.096, 'CCWM': 52.365, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 20394, 'OPR': 93.472, 'Auto': 6.35, 'CCWM': 49.482, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 19947, 'OPR': 70.652, 'Auto': 23.163, 'CCWM': 36.407, 'TeamName': 'Nano Trojans'}, {'TeamNum': 10354, 'OPR': 62.54, 'Auto': 6.03, 'CCWM': 8.842, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 10055, 'OPR': 58.86, 'Auto': 18.255, 'CCWM': 7.107, 'TeamName': 'Momentum'}, {'TeamNum': 22236, 'OPR': 50.759, 'Auto': 15.246, 'CCWM': 15.939, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 16685, 'OPR': 38.003, 'Auto': 16.904, 'CCWM': -33.514, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 22045, 'OPR': 34.571, 'Auto': 19.203, 'CCWM': -15.871, 'TeamName': 'Power Breakers'}, {'TeamNum': 21386, 'OPR': 34.433, 'Auto': 19.422, 'CCWM': 4.541, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 13822, 'OPR': 22.105, 'Auto': -4.674, 'CCWM': 3.691, 'TeamName': 'RoboVikings'}, {'TeamNum': 12456, 'OPR': 21.983, 'Auto': -3.562, 'CCWM': -14.625, 'TeamName': 'Big Red'}, {'TeamNum': 22895, 'OPR': 13.619, 'Auto': -0.108, 'CCWM': -45.738, 'TeamName': 'RoboLions'}, {'TeamNum': 20249, 'OPR': 9.142, 'Auto': 1.075, 'CCWM': 9.177, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 22717, 'OPR': -0.115, 'Auto': 1.11, 'CCWM': -32.841, 'TeamName': 'Robotic Radicals'}, {'TeamNum': 11947, 'OPR': -10.045, 'Auto': -5.331, 'CCWM': -55.436, 'TeamName': 'Stafford Middle School Spartan Robotics'}]
USTXHOSWM1
[{'TeamNum': 14503, 'OPR': 109.518, 'Auto': 40.096, 'CCWM': 52.365, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 20394, 'OPR': 93.472, 'Auto': 6.35, 'CCWM': 49.482, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 19947, 'OPR': 70.652, 'Auto': 23.163, 'CCWM': 36.407, 'TeamName': 'Nano Trojans'}, {'TeamNum': 10354, 'OPR': 62.54, 'Auto': 6.03, 'CCWM': 8.842, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 10055, 'OPR': 58.86, 'Auto': 18.255, 'CCWM': 7.107, 'TeamName': 'Momentum'}, {'TeamNum': 22236, 'OPR': 50.759, 'Auto': 15.246, 'CCWM': 15.939, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 16685, 'OPR': 38.003, 'Auto': 16.904, 'CCWM': -33.514, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 22045, 'OPR': 34.571, 'Auto': 19.203, 'CCWM': -15.871, 'TeamName': 'Power Breakers'}, {'TeamNum': 21386, 'OPR': 34.433, 'Auto': 19.422, 'CCWM': 4.541, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 13822, 'OPR': 22.105, 'Auto': -4.674, 'CCWM': 3.691, 'TeamName': 'RoboVikings'}, {'TeamNum': 12456, 'OPR': 21.983, 'Auto': -3.562, 'CCWM': -14.625, 'TeamName': 'Big Red'}, {'TeamNum': 22895, 'OPR': 13.619, 'Auto': -0.108, 'CCWM': -45.738, 'TeamName': 'RoboLions'}, {'TeamNum': 20249, 'OPR': 9.142, 'Auto': 1.075, 'CCWM': 9.177, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 22717, 'OPR': -0.115, 'Auto': 1.11, 'CCWM': -32.841, 'TeamName': 'Robotic Radicals'}, {'TeamNum': 11947, 'OPR': -10.045, 'Auto': -5.331, 'CCWM': -55.436, 'TeamName': 'Stafford Middle School Spartan Robotics'}]
i 971
{'12825', '17324', '15021', '12978', '16910', '16911', '20258', '18064', '21304', '12857', '16909', '9191', '16912', '21722', '21843', '22129', '18065', '18861'}
[{'TeamNum': 16912, 'OPR': 87.654, 'Auto': 20.772, 'CCWM': 35.465, 'TeamName': 'Linguine Pastabots'}, {'TeamNum': 12857, 'OPR': 86.219, 'Auto': 27.698, 'CCWM': 65.179, 'TeamName': 'Phantom'}, {'TeamNum': 16910, 'OPR': 84.097, 'Auto': 26.456, 'CCWM': 15.712, 'TeamName': 'Spaghetti Pastabots'}, {'TeamNum': 16911, 'OPR': 75.332, 'Auto': 19.083, 'CCWM': 45.471, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 16909, 'OPR': 75.143, 'Auto': 24.262, 'CCWM': 26.353, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 9191, 'OPR': 72.026, 'Auto': 20.591, 'CCWM': 15.305, 'TeamName': 'Beta Testers'}, {'TeamNum': 17324, 'OPR': 62.905, 'Auto': 19.774, 'CCWM': -13.032, 'TeamName': 'Green Machines'}, {'TeamNum': 18861, 'OPR': 60.099, 'Auto': 21.763, 'CCWM': 16.839, 'TeamName': 'Wasted Potential Energy'}, {'TeamNum': 12978, 'OPR': 59.138, 'Auto': 24.651, 'CCWM': -1.557, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 18065, 'OPR': 56.34, 'Auto': 13.389, 'CCWM': 38.444, 'TeamName': 'Repeat Error'}, {'TeamNum': 21843, 'OPR': 53.526, 'Auto': 13.389, 'CCWM': -9.059, 'TeamName': 'Prowler Robotics'}, {'TeamNum': 12825, 'OPR': 52.026, 'Auto': 12.917, 'CCWM': -41.761, 'TeamName': 'Wildkat Robotiks FTC'}, {'TeamNum': 18064, 'OPR': 46.443, 'Auto': 14.41, 'CCWM': 31.624, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 15021, 'OPR': 45.73, 'Auto': 2.993, 'CCWM': 12.978, 'TeamName': 'Ravioli Pastabots'}, {'TeamNum': 21722, 'OPR': 38.011, 'Auto': 20.134, 'CCWM': -45.046, 'TeamName': 'Macaroni Pastabots'}, {'TeamNum': 20258, 'OPR': 11.873, 'Auto': 5.644, 'CCWM': -73.645, 'TeamName': 'Mind Bombs'}, {'TeamNum': 22129, 'OPR': 0.68, 'Auto': -0.874, 'CCWM': -52.276, 'TeamName': 'System Error'}, {'TeamNum': 21304, 'OPR': -3.69, 'Auto': 3.727, 'CCWM': -69.826, 'TeamName': 'Tiger Robotics'}]
USTXHONLM3
[{'TeamNum': 16912, 'OPR': 87.654, 'Auto': 20.772, 'CCWM': 35.465, 'TeamName': 'Linguine Pastabots'}, {'TeamNum': 12857, 'OPR': 86.219, 'Auto': 27.698, 'CCWM': 65.179, 'TeamName': 'Phantom'}, {'TeamNum': 16910, 'OPR': 84.097, 'Auto': 26.456, 'CCWM': 15.712, 'TeamName': 'Spaghetti Pastabots'}, {'TeamNum': 16911, 'OPR': 75.332, 'Auto': 19.083, 'CCWM': 45.471, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 16909, 'OPR': 75.143, 'Auto': 24.262, 'CCWM': 26.353, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 9191, 'OPR': 72.026, 'Auto': 20.591, 'CCWM': 15.305, 'TeamName': 'Beta Testers'}, {'TeamNum': 17324, 'OPR': 62.905, 'Auto': 19.774, 'CCWM': -13.032, 'TeamName': 'Green Machines'}, {'TeamNum': 18861, 'OPR': 60.099, 'Auto': 21.763, 'CCWM': 16.839, 'TeamName': 'Wasted Potential Energy'}, {'TeamNum': 12978, 'OPR': 59.138, 'Auto': 24.651, 'CCWM': -1.557, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 18065, 'OPR': 56.34, 'Auto': 13.389, 'CCWM': 38.444, 'TeamName': 'Repeat Error'}, {'TeamNum': 21843, 'OPR': 53.526, 'Auto': 13.389, 'CCWM': -9.059, 'TeamName': 'Prowler Robotics'}, {'TeamNum': 12825, 'OPR': 52.026, 'Auto': 12.917, 'CCWM': -41.761, 'TeamName': 'Wildkat Robotiks FTC'}, {'TeamNum': 18064, 'OPR': 46.443, 'Auto': 14.41, 'CCWM': 31.624, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 15021, 'OPR': 45.73, 'Auto': 2.993, 'CCWM': 12.978, 'TeamName': 'Ravioli Pastabots'}, {'TeamNum': 21722, 'OPR': 38.011, 'Auto': 20.134, 'CCWM': -45.046, 'TeamName': 'Macaroni Pastabots'}, {'TeamNum': 20258, 'OPR': 11.873, 'Auto': 5.644, 'CCWM': -73.645, 'TeamName': 'Mind Bombs'}, {'TeamNum': 22129, 'OPR': 0.68, 'Auto': -0.874, 'CCWM': -52.276, 'TeamName': 'System Error'}, {'TeamNum': 21304, 'OPR': -3.69, 'Auto': 3.727, 'CCWM': -69.826, 'TeamName': 'Tiger Robotics'}]

i 972
{'22332', '7172', '12167', '9511', '8130', '21138', '19990', '21834', '22674', '21327', '21474', '21965', '22201', '8114', '12791', '19991', '14694', '19567', '11563', '22077', '22038', '22287', '19564', '22673', '16756', '21932', '21813', '15877', '20336', '21870'}
[{'TeamNum': 22038, 'OPR': 106.161, 'Auto': 29.57, 'CCWM': 70.682, 'TeamName': 'CaptainTech'}, {'TeamNum': 21932, 'OPR': 102.101, 'Auto': 18.021, 'CCWM': 77.194, 'TeamName': 'Forged In Iron'}, {'TeamNum': 19991, 'OPR': 80.692, 'Auto': 26.628, 'CCWM': 49.016, 'TeamName': 'Chuckleheads'}, {'TeamNum': 12791, 'OPR': 79.638, 'Auto': 18.291, 'CCWM': 56.671, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 7172, 'OPR': 78.439, 'Auto': 25.875, 'CCWM': 20.824, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 21138, 'OPR': 75.924, 'Auto': 23.286, 'CCWM': 14.919, 'TeamName': 'Kaizenite'}, {'TeamNum': 15877, 'OPR': 68.67, 'Auto': 14.011, 'CCWM': -24.955, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 19564, 'OPR': 63.06, 'Auto': 13.431, 'CCWM': -1.92, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 20336, 'OPR': 63.051, 'Auto': 16.587, 'CCWM': -1.854, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 16756, 'OPR': 58.938, 'Auto': 12.264, 'CCWM': 60.433, 'TeamName': 'Raider Prime'}, {'TeamNum': 21474, 'OPR': 58.387, 'Auto': 27.656, 'CCWM': -38.743, 'TeamName': 'SynTech'}, {'TeamNum': 14694, 'OPR': 58.371, 'Auto': 14.645, 'CCWM': -9.238, 'TeamName': 'RoboGuard'}, {'TeamNum': 21870, 'OPR': 56.87, 'Auto': 17.564, 'CCWM': 14.682, 'TeamName': 'Pro Pythons'}, {'TeamNum': 21813, 'OPR': 56.129, 'Auto': 16.316, 'CCWM': -7.828, 'TeamName': 'Pro2type'}, {'TeamNum': 22332, 'OPR': 55.311, 'Auto': 3.161, 'CCWM': -3.021, 'TeamName': 'Trojan Robotics'}, {'TeamNum': 19990, 'OPR': 48.355, 'Auto': 10.857, 'CCWM': 11.843, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 22077, 'OPR': 47.886, 'Auto': 7.648, 'CCWM': 8.469, 'TeamName': 'Marcus Minions'}, {'TeamNum': 21965, 'OPR': 40.717, 'Auto': -1.089, 'CCWM': -17.869, 'TeamName': 'Mainframe'}, {'TeamNum': 19567, 'OPR': 37.583, 'Auto': 15.098, 'CCWM': 4.699, 'TeamName': 'Tier1'}, {'TeamNum': 11563, 'OPR': 33.833, 'Auto': 10.793, 'CCWM': -21.901, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 8114, 'OPR': 21.77, 'Auto': 6.811, 'CCWM': -10.556, 'TeamName': 'Lewisville HS'}, {'TeamNum': 21327, 'OPR': 16.858, 'Auto': 2.624, 'CCWM': -41.176, 'TeamName': 'Java Nauts'}, {'TeamNum': 8130, 'OPR': 13.032, 'Auto': 3.103, 'CCWM': -26.888, 'TeamName': 'Vikings'}, {'TeamNum': 22673, 'OPR': 12.689, 'Auto': -2.797, 'CCWM': 8.099, 'TeamName': 'Error 422'}, {'TeamNum': 12167, 'OPR': 12.517, 'Auto': 6.313, 'CCWM': -42.746, 'TeamName': 'Husky Robotics'}, {'TeamNum': 22287, 'OPR': 12.463, 'Auto': -1.617, 'CCWM': -41.923, 'TeamName': 'Data Rejected'}, {'TeamNum': 22674, 'OPR': 7.485, 'Auto': 12.04, 'CCWM': -29.794, 'TeamName': 'Metal Manipulators'}, {'TeamNum': 9511, 'OPR': 6.928, 'Auto': 0.525, 'CCWM': -37.039, 'TeamName': 'Low Voltage'}, {'TeamNum': 21834, 'OPR': 5.781, 'Auto': -1.656, 'CCWM': -31.213, 'TeamName': 'EPIC Adventurer'}, {'TeamNum': 22201, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'TechieTurtles22'}]
USTXNOXMLLT
[{'TeamNum': 22038, 'OPR': 106.161, 'Auto': 29.57, 'CCWM': 70.682, 'TeamName': 'CaptainTech'}, {'TeamNum': 21932, 'OPR': 102.101, 'Auto': 18.021, 'CCWM': 77.194, 'TeamName': 'Forged In Iron'}, {'TeamNum': 19991, 'OPR': 80.692, 'Auto': 26.628, 'CCWM': 49.016, 'TeamName': 'Chuckleheads'}, {'TeamNum': 12791, 'OPR': 79.638, 'Auto': 18.291, 'CCWM': 56.671, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 7172, 'OPR': 78.439, 'Auto': 25.875, 'CCWM': 20.824, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 21138, 'OPR': 75.924, 'Auto': 23.286, 'CCWM': 14.919, 'TeamName': 'Kaizenite'}, {'TeamNum': 15877, 'OPR': 68.67, 'Auto': 14.011, 'CCWM': -24.955, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 19564, 'OPR': 63.06, 'Auto': 13.431, 'CCWM': -1.92, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 20336, 'OPR': 63.051, 'Auto': 16.587, 'CCWM': -1.854, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 16756, 'OPR': 58.938, 'Auto': 12.264, 'CCWM': 60.433, 'TeamName': 'Raider Prime'}, {'TeamNum': 21474, 'OPR': 58.387, 'Auto': 27.656, 'CCWM': -38.743, 'TeamName': 'SynTech'}, {'TeamNum': 14694, 'OPR': 58.371, 'Auto': 14.645, 'CCWM': -9.238, 'TeamName': 'RoboGuard'}, {'TeamNum': 21870, 'OPR': 56.87, 'Auto': 17.564, 'CCWM': 14.682, 'TeamName': 'Pro Pythons'}, {'TeamNum': 21813, 'OPR': 56.129, 'Auto': 16.316, 'CCWM': -7.828, 'TeamName': 'Pro2type'}, {'TeamNum': 22332, 'OPR': 55.311, 'Auto': 3.161, 'CCWM': -3.021, 'TeamName': 'Trojan Robotics'}, {'TeamNum': 19990, 'OPR': 48.355, 'Auto': 10.857, 'CCWM': 11.843, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 22077, 'OPR': 47.886, 'Auto': 7.648, 'CCWM': 8.469, 'TeamName': 'Marcus Minions'}, {'TeamNum': 21965, 'OPR': 40.717, 'Auto': -1.089, 'CCWM': -17.869, 'TeamName': 'Mainframe'}, {'TeamNum': 19567, 'OPR': 37.583, 'Auto': 15.098, 'CCWM': 4.699, 'TeamName': 'Tier1'}, {'TeamNum': 11563, 'OPR': 33.833, 'Auto': 10.793, 'CCWM': -21.901, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 8114, 'OPR': 21.77, 'Auto': 6.811, 'CCWM': -10.556, 'TeamName': 'Lewisville HS'}, {'TeamNum': 21327, 'OPR': 16.858, 'Auto': 2.624, 'CCWM': -41.176, 'TeamName': 'Java Nauts'}, {'TeamNum': 8130, 'OPR': 13.032, 'Auto': 3.103, 'CCWM': -26.888, 'TeamName': 'Vikings'}, {'TeamNum': 22673, 'OPR': 12.689, 'Auto': -2.797, 'CCWM': 8.099, 'TeamName': 'Error 422'}, {'TeamNum': 12167, 'OPR': 12.517, 'Auto': 6.313, 'CCWM': -42.746, 'TeamName': 'Husky Robotics'}, {'TeamNum': 22287, 'OPR': 12.463, 'Auto': -1.617, 'CCWM': -41.923, 'TeamName': 'Data Rejected'}, {'TeamNum': 22674, 'OPR': 7.485, 'Auto': 12.04, 'CCWM': -29.794, 'TeamName': 'Metal Manipulators'}, {'TeamNum': 9511, 'OPR': 6.928, 'Auto': 0.525, 'CCWM': -37.039, 'TeamName': 'Low Voltage'}, {'TeamNum': 21834, 'OPR': 5.781, 'Auto': -1.656, 'CCWM': -31.213, 'TeamName': 'EPIC Adventurer'}, {'TeamNum': 22201, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'TechieTurtles22'}]
i 973
{'8080', '16335', '18071', '16174', '8790', '14785', '10064', '4454', '22058', '22336', '6455', '21962', '9840'}
[{'TeamNum': 9840, 'OPR': 61.229, 'Auto': 19.755, 'CCWM': 46.347, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 52.375, 'Auto': 12.872, 'CCWM': 28.856, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 4454, 'OPR': 42.95, 'Auto': 0.81, 'CCWM': 32.845, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 22058, 'OPR': 38.909, 'Auto': -0.728, 'CCWM': 15.019, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 14785, 'OPR': 31.269, 'Auto': 7.366, 'CCWM': 17.923, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 18071, 'OPR': 27.834, 'Auto': -0.231, 'CCWM': 3.04, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 8080, 'OPR': 19.234, 'Auto': -2.013, 'CCWM': -4.768, 'TeamName': 'Ironclad'}, {'TeamNum': 22336, 'OPR': 16.03, 'Auto': 3.935, 'CCWM': 0.615, 'TeamName': 'Steel Circuits'}, {'TeamNum': 6455, 'OPR': 11.365, 'Auto': -1.556, 'CCWM': -22.269, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 16335, 'OPR': 10.488, 'Auto': -3.109, 'CCWM': -8.093, 'TeamName': 'The Ruthless Robots 16335'}, {'TeamNum': 8790, 'OPR': 7.345, 'Auto': 3.92, 'CCWM': -35.837, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 16174, 'OPR': -0.023, 'Auto': 0.649, 'CCWM': -42.837, 'TeamName': 'Loading.....'}, {'TeamNum': 10064, 'OPR': -2.138, 'Auto': 4.01, 'CCWM': -36.015, 'TeamName': 'Lady Gears'}]
USTXHOWLM1
[{'TeamNum': 9840, 'OPR': 61.229, 'Auto': 19.755, 'CCWM': 46.347, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 52.375, 'Auto': 12.872, 'CCWM': 28.856, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 4454, 'OPR': 42.95, 'Auto': 0.81, 'CCWM': 32.845, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 22058, 'OPR': 38.909, 'Auto': -0.728, 'CCWM': 15.019, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 14785, 'OPR': 31.269, 'Auto': 7.366, 'CCWM': 17.923, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 18071, 'OPR': 27.834, 'Auto': -0.231, 'CCWM': 3.04, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 8080, 'OPR': 19.234, 'Auto': -2.013, 'CCWM': -4.768, 'TeamName': 'Ironclad'}, {'TeamNum': 22336, 'OPR': 16.03, 'Auto': 3.935, 'CCWM': 0.615, 'TeamName': 'Steel Circuits'}, {'TeamNum': 6455, 'OPR': 11.365, 'Auto': -1.556, 'CCWM': -22.269, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 16335, 'OPR': 10.488, 'Auto': -3.109, 'CCWM': -8.093, 'TeamName': 'The Ruthless Robots 16335'}, {'TeamNum': 8790, 'OPR': 7.345, 'Auto': 3.92, 'CCWM': -35.837, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 16174, 'OPR': -0.023, 'Auto': 0.649, 'CCWM': -42.837, 'TeamName': 'Loading.....'}, {'TeamNum': 10064, 'OPR': -2.138, 'Auto': 4.01, 'CCWM': -36.015, 'TeamName': 'Lady Gears'}]
i 974

{'14762', '13073', '10095', '22614', '7788', '10802', '18515', '19420', '22495', '16840', '17320', '19398', '4641'}
[{'TeamNum': 10095, 'OPR': 72.626, 'Auto': 21.593, 'CCWM': 60.777, 'TeamName': 'Revelation'}, {'TeamNum': 13073, 'OPR': 51.366, 'Auto': 10.904, 'CCWM': 19.988, 'TeamName': 'Texas Toast'}, {'TeamNum': 22614, 'OPR': 41.323, 'Auto': 5.827, 'CCWM': 12.892, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 14762, 'OPR': 36.713, 'Auto': 4.002, 'CCWM': 11.43, 'TeamName': 'Robo Panthers'}, {'TeamNum': 10802, 'OPR': 34.985, 'Auto': 7.844, 'CCWM': 1.615, 'TeamName': 'Brazosport Robotics Red'}, {'TeamNum': 19420, 'OPR': 33.889, 'Auto': 4.822, 'CCWM': 2.452, 'TeamName': 'BAYRAT TECHB0TZ'}, {'TeamNum': 22495, 'OPR': 28.368, 'Auto': 1.664, 'CCWM': -5.39, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 7788, 'OPR': 25.817, 'Auto': -4.097, 'CCWM': -8.671, 'TeamName': 'Travis Fiddlerbots'}, {'TeamNum': 4641, 'OPR': 23.799, 'Auto': 6.788, 'CCWM': 20.018, 'TeamName': 'RoboSharks'}, {'TeamNum': 19398, 'OPR': 11.206, 'Auto': 14.732, 'CCWM': -13.671, 'TeamName': 'Genesis'}, {'TeamNum': 18515, 'OPR': 6.057, 'Auto': 1.844, 'CCWM': -54.033, 'TeamName': 'Junior Sharks 1'}, {'TeamNum': 17320, 'OPR': 5.362, 'Auto': -0.198, 'CCWM': -27.545, 'TeamName': 'Clute Robotics: Aries'}, {'TeamNum': 16840, 'OPR': 3.7, 'Auto': 2.222, 'CCWM': -34.919, 'TeamName': 'Brazosport Robotics Blue'}]
USTXHOSLLT1
[{'TeamNum': 10095, 'OPR': 72.626, 'Auto': 21.593, 'CCWM': 60.777, 'TeamName': 'Revelation'}, {'TeamNum': 13073, 'OPR': 51.366, 'Auto': 10.904, 'CCWM': 19.988, 'TeamName': 'Texas Toast'}, {'TeamNum': 22614, 'OPR': 41.323, 'Auto': 5.827, 'CCWM': 12.892, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 14762, 'OPR': 36.713, 'Auto': 4.002, 'CCWM': 11.43, 'TeamName': 'Robo Panthers'}, {'TeamNum': 10802, 'OPR': 34.985, 'Auto': 7.844, 'CCWM': 1.615, 'TeamName': 'Brazosport Robotics Red'}, {'TeamNum': 19420, 'OPR': 33.889, 'Auto': 4.822, 'CCWM': 2.452, 'TeamName': 'BAYRAT TECHB0TZ'}, {'TeamNum': 22495, 'OPR': 28.368, 'Auto': 1.664, 'CCWM': -5.39, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 7788, 'OPR': 25.817, 'Auto': -4.097, 'CCWM': -8.671, 'TeamName': 'Travis Fiddlerbots'}, {'TeamNum': 4641, 'OPR': 23.799, 'Auto': 6.788, 'CCWM': 20.018, 'TeamName': 'RoboSharks'}, {'TeamNum': 19398, 'OPR': 11.206, 'Auto': 14.732, 'CCWM': -13.671, 'TeamName': 'Genesis'}, {'TeamNum': 18515, 'OPR': 6.057, 'Auto': 1.844, 'CCWM': -54.033, 'TeamName': 'Junior Sharks 1'}, {'TeamNum': 17320, 'OPR': 5.362, 'Auto': -0.198, 'CCWM': -27.545, 'TeamName': 'Clute Robotics: Aries'}, {'TeamNum': 16840, 'OPR': 3.7, 'Auto': 2.222, 'CCWM': -34.919, 'TeamName': 'Brazosport Robotics Blue'}]
i 975
{'16163', '19502', '12209', '17426', '15661', '21436', '19572', '19891', '18140', '21693', '21479', '12218', '14714'}
[{'TeamNum': 19502, 'OPR': 116.784, 'Auto': 33.202, 'CCWM': 96.251, 'TeamName': 'The Moment Makers'}, {'TeamNum': 18140, 'OPR': 91.934, 'Auto': 23.976, 'CCWM': 42.706, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 19572, 'OPR': 65.252, 'Auto': 15.488, 'CCWM': 30.562, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 12209, 'OPR': 60.561, 'Auto': 17.547, 'CCWM': 10.783, 'TeamName': 'Blue Steel'}, {'TeamNum': 21693, 'OPR': 57.422, 'Auto': 7.426, 'CCWM': 31.143, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 12218, 'OPR': 48.894, 'Auto': 13.799, 'CCWM': 22.961, 'TeamName': 'Horsepower'}, {'TeamNum': 21479, 'OPR': 37.366, 'Auto': 11.955, 'CCWM': -33.992, 'TeamName': 'RoboDogs'}, {'TeamNum': 21436, 'OPR': 20.005, 'Auto': 2.101, 'CCWM': -0.501, 'TeamName': 'Pioneers3'}, {'TeamNum': 15661, 'OPR': 15.912, 'Auto': 1.555, 'CCWM': -25.25, 'TeamName': 'Pear-lettes'}, {'TeamNum': 17426, 'OPR': 14.2, 'Auto': -1.806, 'CCWM': -33.24, 'TeamName': 'Rustangs'}, {'TeamNum': 14714, 'OPR': 5.268, 'Auto': -2.825, 'CCWM': -33.3, 'TeamName': 'Pear-O-Botics'}, {'TeamNum': 16163, 'OPR': 2.156, 'Auto': 0.899, 'CCWM': -65.473, 'TeamName': 'Pioneers 1'}, {'TeamNum': 19891, 'OPR': 1.817, 'Auto': 2.507, 'CCWM': -37.94, 'TeamName': 'Pioneer 2'}]
USTXHOSELM3
[{'TeamNum': 19502, 'OPR': 116.784, 'Auto': 33.202, 'CCWM': 96.251, 'TeamName': 'The Moment Makers'}, {'TeamNum': 18140, 'OPR': 91.934, 'Auto': 23.976, 'CCWM': 42.706, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 19572, 'OPR': 65.252, 'Auto': 15.488, 'CCWM': 30.562, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 12209, 'OPR': 60.561, 'Auto': 17.547, 'CCWM': 10.783, 'TeamName': 'Blue Steel'}, {'TeamNum': 21693, 'OPR': 57.422, 'Auto': 7.426, 'CCWM': 31.143, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 12218, 'OPR': 48.894, 'Auto': 13.799, 'CCWM': 22.961, 'TeamName': 'Horsepower'}, {'TeamNum': 21479, 'OPR': 37.366, 'Auto': 11.955, 'CCWM': -33.992, 'TeamName': 'RoboDogs'}, {'TeamNum': 21436, 'OPR': 20.005, 'Auto': 2.101, 'CCWM': -0.501, 'TeamName': 'Pioneers3'}, {'TeamNum': 15661, 'OPR': 15.912, 'Auto': 1.555, 'CCWM': -25.25, 'TeamName': 'Pear-lettes'}, {'TeamNum': 17426, 'OPR': 14.2, 'Auto': -1.806, 'CCWM': -33.24, 'TeamName': 'Rustangs'}, {'TeamNum': 14714, 'OPR': 5.268, 'Auto': -2.825, 'CCWM': -33.3, 'TeamName': 'Pear-O-Botics'}, {'TeamNum': 16163, 'OPR': 2.156, 'Auto': 0.899, 'CCWM': -65.473, 'TeamName': 'Pioneers 1'}, {'TeamNum': 19891, 'OPR': 1.817, 'Auto': 2.507, 'CCWM': -37.94, 'TeamName': 'Pioneer 2'}]
i 976
{'10695', '19922', '16265', '5667', '12351', '19389', '16790', '12515', '20108', '20515', '21977', '16748', '16091', '8400', '8280', '21765', '16927'}
[{'TeamNum': 16265, 'OPR': 97.309, 'Auto': 24.063, 'CCWM': 54.114, 'TeamName': 'ENIGMA'}, {'TeamNum': 10695, 'OPR': 75.612, 'Auto': 25.966, 'CCWM': 36.303, 'TeamName': 'Theta Robotics'}, {'TeamNum': 16091, 'OPR': 71.058, 'Auto': 19.056, 'CCWM': 35.639, 'TeamName': 'T.W.C.A. (Team Without a Cool Acronym)'}, {'TeamNum': 20515, 'OPR': 60.095, 'Auto': 18.55, 'CCWM': 16.096, 'TeamName': 'Cubed ETs'}, {'TeamNum': 12351, 'OPR': 54.832, 'Auto': 30.077, 'CCWM': 32.043, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 16790, 'OPR': 45.627, 'Auto': 7.176, 'CCWM': -7.98, 'TeamName': 'WARP'}, {'TeamNum': 21977, 'OPR': 41.909, 'Auto': 6.507, 'CCWM': -18.985, 'TeamName': 'ElectroSloths'}, {'TeamNum': 5667, 'OPR': 36.806, 'Auto': 15.373, 'CCWM': -40.19, 'TeamName': 'Robominers'}, {'TeamNum': 16748, 'OPR': 35.119, 'Auto': 9.08, 'CCWM': 16.237, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 8280, 'OPR': 29.071, 'Auto': 14.558, 'CCWM': 14.726, 'TeamName': 'Calamity'}, {'TeamNum': 19389, 'OPR': 23.404, 'Auto': -5.988, 'CCWM': -33.063, 'TeamName': 'Angry Aliens'}, {'TeamNum': 21765, 'OPR': 20.039, 'Auto': 4.375, 'CCWM': 23.516, 'TeamName': 'Overclocked'}, {'TeamNum': 16927, 'OPR': 18.918, 'Auto': 8.849, 'CCWM': -38.207, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 12515, 'OPR': 12.147, 'Auto': 1.502, 'CCWM': -7.049, 'TeamName': 'Titanium Knights'}, {'TeamNum': 20108, 'OPR': 10.116, 'Auto': 1.62, 'CCWM': -70.221, 'TeamName': 'GOATs'}, {'TeamNum': 8400, 'OPR': 9.859, 'Auto': 2.539, 'CCWM': -6.932, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 19922, 'OPR': 6.419, 'Auto': 2.057, 'CCWM': -18.839, 'TeamName': 'Iron Lions'}]
USUTHUQ
[{'TeamNum': 16265, 'OPR': 97.309, 'Auto': 24.063, 'CCWM': 54.114, 'TeamName': 'ENIGMA'}, {'TeamNum': 10695, 'OPR': 75.612, 'Auto': 25.966, 'CCWM': 36.303, 'TeamName': 'Theta Robotics'}, {'TeamNum': 16091, 'OPR': 71.058, 'Auto': 19.056, 'CCWM': 35.639, 'TeamName': 'T.W.C.A. (Team Without a Cool Acronym)'}, {'TeamNum': 20515, 'OPR': 60.095, 'Auto': 18.55, 'CCWM': 16.096, 'TeamName': 'Cubed ETs'}, {'TeamNum': 12351, 'OPR': 54.832, 'Auto': 30.077, 'CCWM': 32.043, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 16790, 'OPR': 45.627, 'Auto': 7.176, 'CCWM': -7.98, 'TeamName': 'WARP'}, {'TeamNum': 21977, 'OPR': 41.909, 'Auto': 6.507, 'CCWM': -18.985, 'TeamName': 'ElectroSloths'}, {'TeamNum': 5667, 'OPR': 36.806, 'Auto': 15.373, 'CCWM': -40.19, 'TeamName': 'Robominers'}, {'TeamNum': 16748, 'OPR': 35.119, 'Auto': 9.08, 'CCWM': 16.237, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 8280, 'OPR': 29.071, 'Auto': 14.558, 'CCWM': 14.726, 'TeamName': 'Calamity'}, {'TeamNum': 19389, 'OPR': 23.404, 'Auto': -5.988, 'CCWM': -33.063, 'TeamName': 'Angry Aliens'}, {'TeamNum': 21765, 'OPR': 20.039, 'Auto': 4.375, 'CCWM': 23.516, 'TeamName': 'Overclocked'}, {'TeamNum': 16927, 'OPR': 18.918, 'Auto': 8.849, 'CCWM': -38.207, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 12515, 'OPR': 12.147, 'Auto': 1.502, 'CCWM': -7.049, 'TeamName': 'Titanium Knights'}, {'TeamNum': 20108, 'OPR': 10.116, 'Auto': 1.62, 'CCWM': -70.221, 'TeamName': 'GOATs'}, {'TeamNum': 8400, 'OPR': 9.859, 'Auto': 2.539, 'CCWM': -6.932, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 19922, 'OPR': 6.419, 'Auto': 2.057, 'CCWM': -18.839, 'TeamName': 'Iron Lions'}]

i 977
{'21079', '23061', '21083', '17728', '17729', '16055', '23055', '16054', '22708'}
[{'TeamNum': 17728, 'OPR': 64.142, 'Auto': 3.511, 'CCWM': 36.441, 'TeamName': 'BrainMachine'}, {'TeamNum': 23055, 'OPR': 57.381, 'Auto': 1.81, 'CCWM': 32.45, 'TeamName': 'Tech Fenix'}, {'TeamNum': 16055, 'OPR': 36.925, 'Auto': 0.465, 'CCWM': 2.456, 'TeamName': 'Starbots FTC'}, {'TeamNum': 23061, 'OPR': 31.674, 'Auto': -1.948, 'CCWM': 6.693, 'TeamName': 'Ragnarök'}, {'TeamNum': 21079, 'OPR': 31.513, 'Auto': -0.778, 'CCWM': -0.668, 'TeamName': 'Alpha Byte'}, {'TeamNum': 16054, 'OPR': 22.45, 'Auto': 1.756, 'CCWM': 0.836, 'TeamName': 'STORM TECH CANAÃ'}, {'TeamNum': 21083, 'OPR': 19.168, 'Auto': -0.553, 'CCWM': -17.814, 'TeamName': 'BAZINGA! 73'}, {'TeamNum': 22708, 'OPR': 18.355, 'Auto': 6.258, 'CCWM': -23.491, 'TeamName': 'TechZeus'}, {'TeamNum': 17729, 'OPR': 15.986, 'Auto': 2.197, 'CCWM': -37.201, 'TeamName': 'TECH BROS'}]
BRBHS
[{'TeamNum': 17728, 'OPR': 64.142, 'Auto': 3.511, 'CCWM': 36.441, 'TeamName': 'BrainMachine'}, {'TeamNum': 23055, 'OPR': 57.381, 'Auto': 1.81, 'CCWM': 32.45, 'TeamName': 'Tech Fenix'}, {'TeamNum': 16055, 'OPR': 36.925, 'Auto': 0.465, 'CCWM': 2.456, 'TeamName': 'Starbots FTC'}, {'TeamNum': 23061, 'OPR': 31.674, 'Auto': -1.948, 'CCWM': 6.693, 'TeamName': 'Ragnarök'}, {'TeamNum': 21079, 'OPR': 31.513, 'Auto': -0.778, 'CCWM': -0.668, 'TeamName': 'Alpha Byte'}, {'TeamNum': 16054, 'OPR': 22.45, 'Auto': 1.756, 'CCWM': 0.836, 'TeamName': 'STORM TECH CANAÃ'}, {'TeamNum': 21083, 'OPR': 19.168, 'Auto': -0.553, 'CCWM': -17.814, 'TeamName': 'BAZINGA! 73'}, {'TeamNum': 22708, 'OPR': 18.355, 'Auto': 6.258, 'CCWM': -23.491, 'TeamName': 'TechZeus'}, {'TeamNum': 17729, 'OPR': 15.986, 'Auto': 2.197, 'CCWM': -37.201, 'TeamName': 'TECH BROS'}]
i 978
i 979
i 980
{'19908', '19178', '19185', '19217', '19184', '19207', '20685', '19208', '20907', '22847', '20826', '19177', '17257', '22657', '19209', '19180', '19181', '19170', '11047', '22894', '19182', '19183', '19213', '22900', '22719', '22907', '22666', '22848', '20908', '19154', '19153', '22897'}
[{'TeamNum': 11047, 'OPR': 106.567, 'Auto': 24.551, 'CCWM': 73.222, 'TeamName': 'screw it'}, {'TeamNum': 19213, 'OPR': 93.884, 'Auto': 16.588, 'CCWM': 66.678, 'TeamName': 'Mystery'}, {'TeamNum': 19182, 'OPR': 86.425, 'Auto': 11.709, 'CCWM': 20.955, 'TeamName': 'ADAMAS'}, {'TeamNum': 19207, 'OPR': 84.377, 'Auto': 24.048, 'CCWM': 60.526, 'TeamName': 'NKshrimps'}, {'TeamNum': 19209, 'OPR': 75.323, 'Auto': 2.374, 'CCWM': 51.673, 'TeamName': 'Sapphire Castle'}, {'TeamNum': 20908, 'OPR': 66.661, 'Auto': 6.2, 'CCWM': 20.04, 'TeamName': 'Fighter.GC'}, {'TeamNum': 17257, 'OPR': 63.024, 'Auto': 5.549, 'CCWM': 6.289, 'TeamName': 'GoBuilder.GC'}, {'TeamNum': 22894, 'OPR': 63.012, 'Auto': 16.985, 'CCWM': 4.81, 'TeamName': 'KAS Chainsaw'}, {'TeamNum': 20907, 'OPR': 62.675, 'Auto': 3.535, 'CCWM': -7.109, 'TeamName': 'Dreamer.GC'}, {'TeamNum': 19908, 'OPR': 60.249, 'Auto': 15.9, 'CCWM': -1.368, 'TeamName': 'KAS Laputa'}, {'TeamNum': 19170, 'OPR': 53.565, 'Auto': -0.04, 'CCWM': -28.14, 'TeamName': 'MD-EVA-01'}, {'TeamNum': 22719, 'OPR': 46.765, 'Auto': 24.737, 'CCWM': -11.016, 'TeamName': 'Far Far Away Kingdom - Bay'}, {'TeamNum': 19154, 'OPR': 46.017, 'Auto': 7.097, 'CCWM': 9.1, 'TeamName': 'Far Far Away Kingdom - Island'}, {'TeamNum': 22900, 'OPR': 40.864, 'Auto': 2.876, 'CCWM': 16.185, 'TeamName': 'Sea Master 2'}, {'TeamNum': 19183, 'OPR': 38.414, 'Auto': -5.487, 'CCWM': -17.935, 'TeamName': 'CMS FTC7'}, {'TeamNum': 22848, 'OPR': 38.159, 'Auto': 9.15, 'CCWM': -28.782, 'TeamName': 'Screwer Too'}, {'TeamNum': 19185, 'OPR': 37.759, 'Auto': 0.98, 'CCWM': -12.786, 'TeamName': 'WOODY FOLLOWERS'}, {'TeamNum': 19178, 'OPR': 37.347, 'Auto': 3.048, 'CCWM': -24.796, 'TeamName': 'HERMES'}, {'TeamNum': 19181, 'OPR': 36.987, 'Auto': 0.395, 'CCWM': 1.556, 'TeamName': 'ROBOTISM'}, {'TeamNum': 22907, 'OPR': 32.217, 'Auto': 7.942, 'CCWM': 2.636, 'TeamName': 'nkst36'}, {'TeamNum': 19208, 'OPR': 31.672, 'Auto': 4.302, 'CCWM': 5.779, 'TeamName': 'Obsidian Castle'}, {'TeamNum': 22666, 'OPR': 31.639, 'Auto': 11.229, 'CCWM': 4.551, 'TeamName': 'CARET'}, {'TeamNum': 22847, 'OPR': 31.156, 'Auto': 0.232, 'CCWM': -7.931, 'TeamName': 'Screwer'}, {'TeamNum': 20685, 'OPR': 29.065, 'Auto': -0.295, 'CCWM': -12.209, 'TeamName': 'NKshrimp'}, {'TeamNum': 22897, 'OPR': 25.817, 'Auto': 9.644, 'CCWM': -25.365, 'TeamName': 'Sea Master 1'}, {'TeamNum': 20826, 'OPR': 25.627, 'Auto': 3.09, 'CCWM': -23.252, 'TeamName': 'Far Far Away Kingdom - Highland'}, {'TeamNum': 19184, 'OPR': 23.765, 'Auto': 1.465, 'CCWM': -15.189, 'TeamName': 'OVERLOOKING'}, {'TeamNum': 22657, 'OPR': 20.149, 'Auto': 2.049, 'CCWM': -27.407, 'TeamName': 'RSSHFTC'}, {'TeamNum': 19177, 'OPR': 18.26, 'Auto': 4.949, 'CCWM': -28.874, 'TeamName': 'DREAMER'}, {'TeamNum': 19153, 'OPR': 16.962, 'Auto': 5.14, 'CCWM': -10.965, 'TeamName': 'Breaker.GC'}, {'TeamNum': 19180, 'OPR': 15.766, 'Auto': 0.667, 'CCWM': -13.856, 'TeamName': 'CMS FTC4'}, {'TeamNum': 19217, 'OPR': 13.632, 'Auto': -4.008, 'CCWM': -47.019, 'TeamName': 'KHSM'}]
TWCMP
[{'TeamNum': 11047, 'OPR': 106.567, 'Auto': 24.551, 'CCWM': 73.222, 'TeamName': 'screw it'}, {'TeamNum': 19213, 'OPR': 93.884, 'Auto': 16.588, 'CCWM': 66.678, 'TeamName': 'Mystery'}, {'TeamNum': 19182, 'OPR': 86.425, 'Auto': 11.709, 'CCWM': 20.955, 'TeamName': 'ADAMAS'}, {'TeamNum': 19207, 'OPR': 84.377, 'Auto': 24.048, 'CCWM': 60.526, 'TeamName': 'NKshrimps'}, {'TeamNum': 19209, 'OPR': 75.323, 'Auto': 2.374, 'CCWM': 51.673, 'TeamName': 'Sapphire Castle'}, {'TeamNum': 20908, 'OPR': 66.661, 'Auto': 6.2, 'CCWM': 20.04, 'TeamName': 'Fighter.GC'}, {'TeamNum': 17257, 'OPR': 63.024, 'Auto': 5.549, 'CCWM': 6.289, 'TeamName': 'GoBuilder.GC'}, {'TeamNum': 22894, 'OPR': 63.012, 'Auto': 16.985, 'CCWM': 4.81, 'TeamName': 'KAS Chainsaw'}, {'TeamNum': 20907, 'OPR': 62.675, 'Auto': 3.535, 'CCWM': -7.109, 'TeamName': 'Dreamer.GC'}, {'TeamNum': 19908, 'OPR': 60.249, 'Auto': 15.9, 'CCWM': -1.368, 'TeamName': 'KAS Laputa'}, {'TeamNum': 19170, 'OPR': 53.565, 'Auto': -0.04, 'CCWM': -28.14, 'TeamName': 'MD-EVA-01'}, {'TeamNum': 22719, 'OPR': 46.765, 'Auto': 24.737, 'CCWM': -11.016, 'TeamName': 'Far Far Away Kingdom - Bay'}, {'TeamNum': 19154, 'OPR': 46.017, 'Auto': 7.097, 'CCWM': 9.1, 'TeamName': 'Far Far Away Kingdom - Island'}, {'TeamNum': 22900, 'OPR': 40.864, 'Auto': 2.876, 'CCWM': 16.185, 'TeamName': 'Sea Master 2'}, {'TeamNum': 19183, 'OPR': 38.414, 'Auto': -5.487, 'CCWM': -17.935, 'TeamName': 'CMS FTC7'}, {'TeamNum': 22848, 'OPR': 38.159, 'Auto': 9.15, 'CCWM': -28.782, 'TeamName': 'Screwer Too'}, {'TeamNum': 19185, 'OPR': 37.759, 'Auto': 0.98, 'CCWM': -12.786, 'TeamName': 'WOODY FOLLOWERS'}, {'TeamNum': 19178, 'OPR': 37.347, 'Auto': 3.048, 'CCWM': -24.796, 'TeamName': 'HERMES'}, {'TeamNum': 19181, 'OPR': 36.987, 'Auto': 0.395, 'CCWM': 1.556, 'TeamName': 'ROBOTISM'}, {'TeamNum': 22907, 'OPR': 32.217, 'Auto': 7.942, 'CCWM': 2.636, 'TeamName': 'nkst36'}, {'TeamNum': 19208, 'OPR': 31.672, 'Auto': 4.302, 'CCWM': 5.779, 'TeamName': 'Obsidian Castle'}, {'TeamNum': 22666, 'OPR': 31.639, 'Auto': 11.229, 'CCWM': 4.551, 'TeamName': 'CARET'}, {'TeamNum': 22847, 'OPR': 31.156, 'Auto': 0.232, 'CCWM': -7.931, 'TeamName': 'Screwer'}, {'TeamNum': 20685, 'OPR': 29.065, 'Auto': -0.295, 'CCWM': -12.209, 'TeamName': 'NKshrimp'}, {'TeamNum': 22897, 'OPR': 25.817, 'Auto': 9.644, 'CCWM': -25.365, 'TeamName': 'Sea Master 1'}, {'TeamNum': 20826, 'OPR': 25.627, 'Auto': 3.09, 'CCWM': -23.252, 'TeamName': 'Far Far Away Kingdom - Highland'}, {'TeamNum': 19184, 'OPR': 23.765, 'Auto': 1.465, 'CCWM': -15.189, 'TeamName': 'OVERLOOKING'}, {'TeamNum': 22657, 'OPR': 20.149, 'Auto': 2.049, 'CCWM': -27.407, 'TeamName': 'RSSHFTC'}, {'TeamNum': 19177, 'OPR': 18.26, 'Auto': 4.949, 'CCWM': -28.874, 'TeamName': 'DREAMER'}, {'TeamNum': 19153, 'OPR': 16.962, 'Auto': 5.14, 'CCWM': -10.965, 'TeamName': 'Breaker.GC'}, {'TeamNum': 19180, 'OPR': 15.766, 'Auto': 0.667, 'CCWM': -13.856, 'TeamName': 'CMS FTC4'}, {'TeamNum': 19217, 'OPR': 13.632, 'Auto': -4.008, 'CCWM': -47.019, 'TeamName': 'KHSM'}]
i 981
i 982
{'18498', '22577', '18492', '21445', '19149', '21473', '19358', '19408', '20417', '20874', '22786', '21344', '19347', '22172'}
[{'TeamNum': 22172, 'OPR': 64.1, 'Auto': 4.619, 'CCWM': 21.532, 'TeamName': 'AMLY Tech Robotics Team'}, {'TeamNum': 19347, 'OPR': 58.206, 'Auto': 10.821, 'CCWM': 23.76, 'TeamName': 'LYBOTICS Challenge Team'}, {'TeamNum': 19408, 'OPR': 50.824, 'Auto': 12.623, 'CCWM': -5.247, 'TeamName': 'LYBOTICS Cavalay Team'}, {'TeamNum': 19358, 'OPR': 41.56, 'Auto': 3.241, 'CCWM': -3.381, 'TeamName': 'LYBOTICS Royal Team'}, {'TeamNum': 18492, 'OPR': 32.893, 'Auto': 11.068, 'CCWM': 7.617, 'TeamName': 'Mukhtar Robotics Team'}, {'TeamNum': 22786, 'OPR': 29.057, 'Auto': -1.651, 'CCWM': 3.265, 'TeamName': 'Basida Robotics Team'}, {'TeamNum': 19149, 'OPR': 29.001, 'Auto': -4.788, 'CCWM': 0.134, 'TeamName': 'GCA Robotics Team'}, {'TeamNum': 21445, 'OPR': 28.891, 'Auto': 3.203, 'CCWM': 0.141, 'TeamName': 'Al_Aweal Robotics Team'}, {'TeamNum': 18498, 'OPR': 28.869, 'Auto': 21.929, 'CCWM': 16.347, 'TeamName': 'LYBOTICS Change Team'}, {'TeamNum': 20874, 'OPR': 23.17, 'Auto': -4.34, 'CCWM': 4.225, 'TeamName': 'SAS Tech Robotics Team'}, {'TeamNum': 22577, 'OPR': 22.764, 'Auto': 1.252, 'CCWM': -10.58, 'TeamName': 'Vision Robotics Team'}, {'TeamNum': 21473, 'OPR': 22.733, 'Auto': 8.25, 'CCWM': -17.65, 'TeamName': 'LYBOTICS Smart Team'}, {'TeamNum': 20417, 'OPR': 13.778, 'Auto': -5.987, 'CCWM': -9.479, 'TeamName': 'Luqman Robotics Team'}, {'TeamNum': 21344, 'OPR': -1.707, 'Auto': 1.872, 'CCWM': -39.743, 'TeamName': 'LYBOTICS Zliten Team'}]
LYGHQ
[{'TeamNum': 22172, 'OPR': 64.1, 'Auto': 4.619, 'CCWM': 21.532, 'TeamName': 'AMLY Tech Robotics Team'}, {'TeamNum': 19347, 'OPR': 58.206, 'Auto': 10.821, 'CCWM': 23.76, 'TeamName': 'LYBOTICS Challenge Team'}, {'TeamNum': 19408, 'OPR': 50.824, 'Auto': 12.623, 'CCWM': -5.247, 'TeamName': 'LYBOTICS Cavalay Team'}, {'TeamNum': 19358, 'OPR': 41.56, 'Auto': 3.241, 'CCWM': -3.381, 'TeamName': 'LYBOTICS Royal Team'}, {'TeamNum': 18492, 'OPR': 32.893, 'Auto': 11.068, 'CCWM': 7.617, 'TeamName': 'Mukhtar Robotics Team'}, {'TeamNum': 22786, 'OPR': 29.057, 'Auto': -1.651, 'CCWM': 3.265, 'TeamName': 'Basida Robotics Team'}, {'TeamNum': 19149, 'OPR': 29.001, 'Auto': -4.788, 'CCWM': 0.134, 'TeamName': 'GCA Robotics Team'}, {'TeamNum': 21445, 'OPR': 28.891, 'Auto': 3.203, 'CCWM': 0.141, 'TeamName': 'Al_Aweal Robotics Team'}, {'TeamNum': 18498, 'OPR': 28.869, 'Auto': 21.929, 'CCWM': 16.347, 'TeamName': 'LYBOTICS Change Team'}, {'TeamNum': 20874, 'OPR': 23.17, 'Auto': -4.34, 'CCWM': 4.225, 'TeamName': 'SAS Tech Robotics Team'}, {'TeamNum': 22577, 'OPR': 22.764, 'Auto': 1.252, 'CCWM': -10.58, 'TeamName': 'Vision Robotics Team'}, {'TeamNum': 21473, 'OPR': 22.733, 'Auto': 8.25, 'CCWM': -17.65, 'TeamName': 'LYBOTICS Smart Team'}, {'TeamNum': 20417, 'OPR': 13.778, 'Auto': -5.987, 'CCWM': -9.479, 'TeamName': 'Luqman Robotics Team'}, {'TeamNum': 21344, 'OPR': -1.707, 'Auto': 1.872, 'CCWM': -39.743, 'TeamName': 'LYBOTICS Zliten Team'}]
i 983

{'16382', '16383', '21658', '16410', '10183', '22173', '16788', '16850', '16785', '12475', '19444', '17258', '22020', '12463', '12819', '16441', '20361', '22042', '14144', '18710', '3954', '20738', '14183', '16409', '20091', '10918', '18425', '22107'}
[{'TeamNum': 20091, 'OPR': 121.951, 'Auto': 18.807, 'CCWM': 56.581, 'TeamName': 'Blood Sweat and Gears'}, {'TeamNum': 10918, 'OPR': 90.925, 'Auto': 12.387, 'CCWM': 66.64, 'TeamName': 'SPACE'}, {'TeamNum': 12475, 'OPR': 90.225, 'Auto': 17.393, 'CCWM': 65.658, 'TeamName': 'Beyond Reach'}, {'TeamNum': 3954, 'OPR': 80.069, 'Auto': 19.18, 'CCWM': 15.644, 'TeamName': 'Pink to the Future'}, {'TeamNum': 19444, 'OPR': 78.951, 'Auto': 26.722, 'CCWM': 33.125, 'TeamName': 'Lorentz Engineering'}, {'TeamNum': 16785, 'OPR': 70.86, 'Auto': 7.751, 'CCWM': 16.974, 'TeamName': 'Team ProBotiX'}, {'TeamNum': 20361, 'OPR': 69.789, 'Auto': 10.669, 'CCWM': 48.815, 'TeamName': 'RoboRev'}, {'TeamNum': 10183, 'OPR': 65.598, 'Auto': 17.225, 'CCWM': 15.038, 'TeamName': 'F.R.O.G  Frog Robots Of Germany'}, {'TeamNum': 16441, 'OPR': 63.164, 'Auto': 17.709, 'CCWM': 6.47, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 12819, 'OPR': 60.088, 'Auto': 15.755, 'CCWM': -15.655, 'TeamName': 'Queen Bee'}, {'TeamNum': 16382, 'OPR': 59.703, 'Auto': 25.033, 'CCWM': -6.716, 'TeamName': 'Casimir Tech'}, {'TeamNum': 22042, 'OPR': 58.561, 'Auto': 17.577, 'CCWM': -31.42, 'TeamName': 'Lituanica X'}, {'TeamNum': 18710, 'OPR': 55.528, 'Auto': 13.985, 'CCWM': 9.916, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 20738, 'OPR': 55.255, 'Auto': 10.545, 'CCWM': 23.677, 'TeamName': 'secbirdmachine 2'}, {'TeamNum': 22107, 'OPR': 54.605, 'Auto': 0.487, 'CCWM': 6.923, 'TeamName': 'Tectura 1'}, {'TeamNum': 16409, 'OPR': 51.873, 'Auto': 19.43, 'CCWM': -12.835, 'TeamName': 'Team Orange'}, {'TeamNum': 22173, 'OPR': 51.088, 'Auto': 12.231, 'CCWM': 1.412, 'TeamName': 'Red Monkeys'}, {'TeamNum': 21658, 'OPR': 49.27, 'Auto': 7.654, 'CCWM': 2.097, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 14144, 'OPR': 47.078, 'Auto': 4.127, 'CCWM': 5.082, 'TeamName': 'EAGirls'}, {'TeamNum': 16410, 'OPR': 45.298, 'Auto': 4.025, 'CCWM': -3.098, 'TeamName': 'GentleBotz'}, {'TeamNum': 14183, 'OPR': 41.089, 'Auto': 6.216, 'CCWM': -50.785, 'TeamName': 'Dukes of Brabant'}, {'TeamNum': 16850, 'OPR': 39.458, 'Auto': 14.524, 'CCWM': -18.04, 'TeamName': 'Breul-1'}, {'TeamNum': 18425, 'OPR': 35.894, 'Auto': 3.453, 'CCWM': -38.25, 'TeamName': 'Ubbo Tech Team'}, {'TeamNum': 16383, 'OPR': 35.881, 'Auto': 12.34, 'CCWM': -33.098, 'TeamName': 'Frits Philips Robotics team'}, {'TeamNum': 16788, 'OPR': 30.619, 'Auto': -4.401, 'CCWM': -13.698, 'TeamName': 'The Encrypted Gentlemen'}, {'TeamNum': 12463, 'OPR': 27.982, 'Auto': 9.929, 'CCWM': -27.779, 'TeamName': 'KKST-KeepKeenShowTech'}, {'TeamNum': 22020, 'OPR': 8.03, 'Auto': -4.879, 'CCWM': -26.749, 'TeamName': 'Gymnasium Haganum'}, {'TeamNum': 17258, 'OPR': 6.369, 'Auto': 1.525, 'CCWM': -95.93, 'TeamName': 'The Scrapyard-Warriors'}]
NLNLLT
[{'TeamNum': 20091, 'OPR': 121.951, 'Auto': 18.807, 'CCWM': 56.581, 'TeamName': 'Blood Sweat and Gears'}, {'TeamNum': 10918, 'OPR': 90.925, 'Auto': 12.387, 'CCWM': 66.64, 'TeamName': 'SPACE'}, {'TeamNum': 12475, 'OPR': 90.225, 'Auto': 17.393, 'CCWM': 65.658, 'TeamName': 'Beyond Reach'}, {'TeamNum': 3954, 'OPR': 80.069, 'Auto': 19.18, 'CCWM': 15.644, 'TeamName': 'Pink to the Future'}, {'TeamNum': 19444, 'OPR': 78.951, 'Auto': 26.722, 'CCWM': 33.125, 'TeamName': 'Lorentz Engineering'}, {'TeamNum': 16785, 'OPR': 70.86, 'Auto': 7.751, 'CCWM': 16.974, 'TeamName': 'Team ProBotiX'}, {'TeamNum': 20361, 'OPR': 69.789, 'Auto': 10.669, 'CCWM': 48.815, 'TeamName': 'RoboRev'}, {'TeamNum': 10183, 'OPR': 65.598, 'Auto': 17.225, 'CCWM': 15.038, 'TeamName': 'F.R.O.G  Frog Robots Of Germany'}, {'TeamNum': 16441, 'OPR': 63.164, 'Auto': 17.709, 'CCWM': 6.47, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 12819, 'OPR': 60.088, 'Auto': 15.755, 'CCWM': -15.655, 'TeamName': 'Queen Bee'}, {'TeamNum': 16382, 'OPR': 59.703, 'Auto': 25.033, 'CCWM': -6.716, 'TeamName': 'Casimir Tech'}, {'TeamNum': 22042, 'OPR': 58.561, 'Auto': 17.577, 'CCWM': -31.42, 'TeamName': 'Lituanica X'}, {'TeamNum': 18710, 'OPR': 55.528, 'Auto': 13.985, 'CCWM': 9.916, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 20738, 'OPR': 55.255, 'Auto': 10.545, 'CCWM': 23.677, 'TeamName': 'secbirdmachine 2'}, {'TeamNum': 22107, 'OPR': 54.605, 'Auto': 0.487, 'CCWM': 6.923, 'TeamName': 'Tectura 1'}, {'TeamNum': 16409, 'OPR': 51.873, 'Auto': 19.43, 'CCWM': -12.835, 'TeamName': 'Team Orange'}, {'TeamNum': 22173, 'OPR': 51.088, 'Auto': 12.231, 'CCWM': 1.412, 'TeamName': 'Red Monkeys'}, {'TeamNum': 21658, 'OPR': 49.27, 'Auto': 7.654, 'CCWM': 2.097, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 14144, 'OPR': 47.078, 'Auto': 4.127, 'CCWM': 5.082, 'TeamName': 'EAGirls'}, {'TeamNum': 16410, 'OPR': 45.298, 'Auto': 4.025, 'CCWM': -3.098, 'TeamName': 'GentleBotz'}, {'TeamNum': 14183, 'OPR': 41.089, 'Auto': 6.216, 'CCWM': -50.785, 'TeamName': 'Dukes of Brabant'}, {'TeamNum': 16850, 'OPR': 39.458, 'Auto': 14.524, 'CCWM': -18.04, 'TeamName': 'Breul-1'}, {'TeamNum': 18425, 'OPR': 35.894, 'Auto': 3.453, 'CCWM': -38.25, 'TeamName': 'Ubbo Tech Team'}, {'TeamNum': 16383, 'OPR': 35.881, 'Auto': 12.34, 'CCWM': -33.098, 'TeamName': 'Frits Philips Robotics team'}, {'TeamNum': 16788, 'OPR': 30.619, 'Auto': -4.401, 'CCWM': -13.698, 'TeamName': 'The Encrypted Gentlemen'}, {'TeamNum': 12463, 'OPR': 27.982, 'Auto': 9.929, 'CCWM': -27.779, 'TeamName': 'KKST-KeepKeenShowTech'}, {'TeamNum': 22020, 'OPR': 8.03, 'Auto': -4.879, 'CCWM': -26.749, 'TeamName': 'Gymnasium Haganum'}, {'TeamNum': 17258, 'OPR': 6.369, 'Auto': 1.525, 'CCWM': -95.93, 'TeamName': 'The Scrapyard-Warriors'}]
i 984
i 985
i 986
{'7159', '9049', '3650', '22316', '3848', '6226', '14235', '14338', '18568', '5015', '14535', '7609', '18263', '4216', '14496', '22321'}
[{'TeamNum': 14496, 'OPR': 131.857, 'Auto': 25.372, 'CCWM': 107.484, 'TeamName': 'Roboctopi'}, {'TeamNum': 14535, 'OPR': 104.101, 'Auto': 20.078, 'CCWM': 62.91, 'TeamName': 'Alpacas'}, {'TeamNum': 4216, 'OPR': 87.351, 'Auto': 22.143, 'CCWM': 57.177, 'TeamName': 'Rise of Hephaestus'}, {'TeamNum': 14338, 'OPR': 83.853, 'Auto': 20.785, 'CCWM': 45.365, 'TeamName': 'CAOS Robotics ("Chaos")'}, {'TeamNum': 18568, 'OPR': 81.9, 'Auto': 9.148, 'CCWM': 70.266, 'TeamName': 'Minimum Viable Product'}, {'TeamNum': 3650, 'OPR': 67.561, 'Auto': 12.845, 'CCWM': 26.273, 'TeamName': 'Torrey Techies'}, {'TeamNum': 18263, 'OPR': 63.272, 'Auto': 19.377, 'CCWM': 14.37, 'TeamName': 'HIGH VOLTAGE'}, {'TeamNum': 22316, 'OPR': 53.798, 'Auto': 14.793, 'CCWM': -8.945, 'TeamName': 'RoboGenesis'}, {'TeamNum': 7159, 'OPR': 45.724, 'Auto': 14.054, 'CCWM': 11.247, 'TeamName': 'Robo Ravens'}, {'TeamNum': 7609, 'OPR': 40.794, 'Auto': 18.203, 'CCWM': -71.222, 'TeamName': 'Lions'}, {'TeamNum': 9049, 'OPR': 29.813, 'Auto': 10.2, 'CCWM': -74.943, 'TeamName': 'RoboPuffs'}, {'TeamNum': 22321, 'OPR': 29.177, 'Auto': -6.212, 'CCWM': -15.826, 'TeamName': 'Holy Calves'}, {'TeamNum': 6226, 'OPR': 27.218, 'Auto': 19.915, 'CCWM': -57.982, 'TeamName': 'Bambusa'}, {'TeamNum': 5015, 'OPR': 25.23, 'Auto': 11.277, 'CCWM': -7.014, 'TeamName': 'Buffalo Wings'}, {'TeamNum': 3848, 'OPR': 15.406, 'Auto': -0.097, 'CCWM': -56.101, 'TeamName': 'Shockwave'}, {'TeamNum': 14235, 'OPR': 1.947, 'Auto': 11.619, 'CCWM': -103.059, 'TeamName': 'Out of Order'}]
USCASDSDGALT
[{'TeamNum': 14496, 'OPR': 131.857, 'Auto': 25.372, 'CCWM': 107.484, 'TeamName': 'Roboctopi'}, {'TeamNum': 14535, 'OPR': 104.101, 'Auto': 20.078, 'CCWM': 62.91, 'TeamName': 'Alpacas'}, {'TeamNum': 4216, 'OPR': 87.351, 'Auto': 22.143, 'CCWM': 57.177, 'TeamName': 'Rise of Hephaestus'}, {'TeamNum': 14338, 'OPR': 83.853, 'Auto': 20.785, 'CCWM': 45.365, 'TeamName': 'CAOS Robotics ("Chaos")'}, {'TeamNum': 18568, 'OPR': 81.9, 'Auto': 9.148, 'CCWM': 70.266, 'TeamName': 'Minimum Viable Product'}, {'TeamNum': 3650, 'OPR': 67.561, 'Auto': 12.845, 'CCWM': 26.273, 'TeamName': 'Torrey Techies'}, {'TeamNum': 18263, 'OPR': 63.272, 'Auto': 19.377, 'CCWM': 14.37, 'TeamName': 'HIGH VOLTAGE'}, {'TeamNum': 22316, 'OPR': 53.798, 'Auto': 14.793, 'CCWM': -8.945, 'TeamName': 'RoboGenesis'}, {'TeamNum': 7159, 'OPR': 45.724, 'Auto': 14.054, 'CCWM': 11.247, 'TeamName': 'Robo Ravens'}, {'TeamNum': 7609, 'OPR': 40.794, 'Auto': 18.203, 'CCWM': -71.222, 'TeamName': 'Lions'}, {'TeamNum': 9049, 'OPR': 29.813, 'Auto': 10.2, 'CCWM': -74.943, 'TeamName': 'RoboPuffs'}, {'TeamNum': 22321, 'OPR': 29.177, 'Auto': -6.212, 'CCWM': -15.826, 'TeamName': 'Holy Calves'}, {'TeamNum': 6226, 'OPR': 27.218, 'Auto': 19.915, 'CCWM': -57.982, 'TeamName': 'Bambusa'}, {'TeamNum': 5015, 'OPR': 25.23, 'Auto': 11.277, 'CCWM': -7.014, 'TeamName': 'Buffalo Wings'}, {'TeamNum': 3848, 'OPR': 15.406, 'Auto': -0.097, 'CCWM': -56.101, 'TeamName': 'Shockwave'}, {'TeamNum': 14235, 'OPR': 1.947, 'Auto': 11.619, 'CCWM': -103.059, 'TeamName': 'Out of Order'}]

i 987
{'19793', '16687', '14129', '18365', '20355', '12499', '21303', '22650', '1622', '14195', '15171', '20422', '20167', '8380', '21239'}
[{'TeamNum': 15171, 'OPR': 131.03, 'Auto': 28.284, 'CCWM': 134.603, 'TeamName': 'Scorpio'}, {'TeamNum': 12499, 'OPR': 98.121, 'Auto': 27.611, 'CCWM': 46.988, 'TeamName': 'Gear Up'}, {'TeamNum': 20355, 'OPR': 77.243, 'Auto': 9.244, 'CCWM': 36.447, 'TeamName': 'Keep It Simple 2'}, {'TeamNum': 21239, 'OPR': 75.675, 'Auto': 17.915, 'CCWM': 77.335, 'TeamName': 'All Systems Go'}, {'TeamNum': 19793, 'OPR': 51.415, 'Auto': 7.863, 'CCWM': 5.005, 'TeamName': 'Uncaught Exception'}, {'TeamNum': 18365, 'OPR': 39.641, 'Auto': 17.256, 'CCWM': 2.859, 'TeamName': 'Dapper RoboNoodles'}, {'TeamNum': 16687, 'OPR': 30.177, 'Auto': 3.949, 'CCWM': -40.94, 'TeamName': 'A/C Units'}, {'TeamNum': 14129, 'OPR': 29.129, 'Auto': 10.382, 'CCWM': -19.896, 'TeamName': 'Wizalos'}, {'TeamNum': 1622, 'OPR': 27.378, 'Auto': 3.032, 'CCWM': -27.609, 'TeamName': 'Team Spyder'}, {'TeamNum': 20167, 'OPR': 27.072, 'Auto': 9.178, 'CCWM': 8.759, 'TeamName': 'LCtronics'}, {'TeamNum': 8380, 'OPR': 17.769, 'Auto': 15.393, 'CCWM': -27.575, 'TeamName': 'UC Robotics'}, {'TeamNum': 22650, 'OPR': 16.361, 'Auto': 9.282, 'CCWM': -54.138, 'TeamName': 'BishBot'}, {'TeamNum': 14195, 'OPR': 13.918, 'Auto': 7.614, 'CCWM': -21.937, 'TeamName': 'Cerulean Centaurs'}, {'TeamNum': 20422, 'OPR': 12.185, 'Auto': 2.705, 'CCWM': -51.131, 'TeamName': 'Team Spyder Too'}, {'TeamNum': 21303, 'OPR': 2.849, 'Auto': -6.612, 'CCWM': -55.002, 'TeamName': 'Pandamonium'}]
USCASDSDEULT
[{'TeamNum': 15171, 'OPR': 131.03, 'Auto': 28.284, 'CCWM': 134.603, 'TeamName': 'Scorpio'}, {'TeamNum': 12499, 'OPR': 98.121, 'Auto': 27.611, 'CCWM': 46.988, 'TeamName': 'Gear Up'}, {'TeamNum': 20355, 'OPR': 77.243, 'Auto': 9.244, 'CCWM': 36.447, 'TeamName': 'Keep It Simple 2'}, {'TeamNum': 21239, 'OPR': 75.675, 'Auto': 17.915, 'CCWM': 77.335, 'TeamName': 'All Systems Go'}, {'TeamNum': 19793, 'OPR': 51.415, 'Auto': 7.863, 'CCWM': 5.005, 'TeamName': 'Uncaught Exception'}, {'TeamNum': 18365, 'OPR': 39.641, 'Auto': 17.256, 'CCWM': 2.859, 'TeamName': 'Dapper RoboNoodles'}, {'TeamNum': 16687, 'OPR': 30.177, 'Auto': 3.949, 'CCWM': -40.94, 'TeamName': 'A/C Units'}, {'TeamNum': 14129, 'OPR': 29.129, 'Auto': 10.382, 'CCWM': -19.896, 'TeamName': 'Wizalos'}, {'TeamNum': 1622, 'OPR': 27.378, 'Auto': 3.032, 'CCWM': -27.609, 'TeamName': 'Team Spyder'}, {'TeamNum': 20167, 'OPR': 27.072, 'Auto': 9.178, 'CCWM': 8.759, 'TeamName': 'LCtronics'}, {'TeamNum': 8380, 'OPR': 17.769, 'Auto': 15.393, 'CCWM': -27.575, 'TeamName': 'UC Robotics'}, {'TeamNum': 22650, 'OPR': 16.361, 'Auto': 9.282, 'CCWM': -54.138, 'TeamName': 'BishBot'}, {'TeamNum': 14195, 'OPR': 13.918, 'Auto': 7.614, 'CCWM': -21.937, 'TeamName': 'Cerulean Centaurs'}, {'TeamNum': 20422, 'OPR': 12.185, 'Auto': 2.705, 'CCWM': -51.131, 'TeamName': 'Team Spyder Too'}, {'TeamNum': 21303, 'OPR': 2.849, 'Auto': -6.612, 'CCWM': -55.002, 'TeamName': 'Pandamonium'}]
i 988
{'16884', '9164', '19743', '11285', '22567', '9892', '13089', '14140', '10092', '16192', '13084', '22687', '6016', '22529', '10793', '9367'}
[{'TeamNum': 14140, 'OPR': 115.747, 'Auto': 29.961, 'CCWM': 82.287, 'TeamName': 'Crash Test'}, {'TeamNum': 10092, 'OPR': 77.588, 'Auto': 22.895, 'CCWM': 20.054, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 10793, 'OPR': 77.224, 'Auto': 10.368, 'CCWM': 19.019, 'TeamName': 'Voltrons'}, {'TeamNum': 16884, 'OPR': 71.569, 'Auto': 28.982, 'CCWM': 35.276, 'TeamName': 'Mechanical Advantage'}, {'TeamNum': 9164, 'OPR': 65.383, 'Auto': 14.853, 'CCWM': 6.788, 'TeamName': 'Zorrobots'}, {'TeamNum': 19743, 'OPR': 63.334, 'Auto': 12.732, 'CCWM': 22.95, 'TeamName': 'Definitely Human'}, {'TeamNum': 16192, 'OPR': 61.927, 'Auto': 18.064, 'CCWM': 23.024, 'TeamName': 'Prepare to ALT+F4'}, {'TeamNum': 22567, 'OPR': 56.989, 'Auto': 10.648, 'CCWM': 5.05, 'TeamName': 'NPC'}, {'TeamNum': 9892, 'OPR': 53.097, 'Auto': 9.288, 'CCWM': 25.186, 'TeamName': 'EngiNERDs'}, {'TeamNum': 11285, 'OPR': 49.138, 'Auto': 15.456, 'CCWM': 2.343, 'TeamName': 'PATENT PENDING'}, {'TeamNum': 6016, 'OPR': 44.932, 'Auto': 21.56, 'CCWM': -9.788, 'TeamName': 'Ironwolves'}, {'TeamNum': 13089, 'OPR': 41.639, 'Auto': 10.42, 'CCWM': 8.913, 'TeamName': 'E T Brigade'}, {'TeamNum': 22529, 'OPR': 36.44, 'Auto': 4.01, 'CCWM': -22.151, 'TeamName': 'RoboGOATs'}, {'TeamNum': 13084, 'OPR': 20.671, 'Auto': 5.788, 'CCWM': -72.402, 'TeamName': 'Robot Raiders'}, {'TeamNum': 9367, 'OPR': 11.79, 'Auto': -0.584, 'CCWM': -87.339, 'TeamName': 'Torrey Techies White'}, {'TeamNum': 22687, 'OPR': 5.699, 'Auto': -8.275, 'CCWM': -59.209, 'TeamName': 'TS1'}]
USCASDSDDELT
[{'TeamNum': 14140, 'OPR': 115.747, 'Auto': 29.961, 'CCWM': 82.287, 'TeamName': 'Crash Test'}, {'TeamNum': 10092, 'OPR': 77.588, 'Auto': 22.895, 'CCWM': 20.054, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 10793, 'OPR': 77.224, 'Auto': 10.368, 'CCWM': 19.019, 'TeamName': 'Voltrons'}, {'TeamNum': 16884, 'OPR': 71.569, 'Auto': 28.982, 'CCWM': 35.276, 'TeamName': 'Mechanical Advantage'}, {'TeamNum': 9164, 'OPR': 65.383, 'Auto': 14.853, 'CCWM': 6.788, 'TeamName': 'Zorrobots'}, {'TeamNum': 19743, 'OPR': 63.334, 'Auto': 12.732, 'CCWM': 22.95, 'TeamName': 'Definitely Human'}, {'TeamNum': 16192, 'OPR': 61.927, 'Auto': 18.064, 'CCWM': 23.024, 'TeamName': 'Prepare to ALT+F4'}, {'TeamNum': 22567, 'OPR': 56.989, 'Auto': 10.648, 'CCWM': 5.05, 'TeamName': 'NPC'}, {'TeamNum': 9892, 'OPR': 53.097, 'Auto': 9.288, 'CCWM': 25.186, 'TeamName': 'EngiNERDs'}, {'TeamNum': 11285, 'OPR': 49.138, 'Auto': 15.456, 'CCWM': 2.343, 'TeamName': 'PATENT PENDING'}, {'TeamNum': 6016, 'OPR': 44.932, 'Auto': 21.56, 'CCWM': -9.788, 'TeamName': 'Ironwolves'}, {'TeamNum': 13089, 'OPR': 41.639, 'Auto': 10.42, 'CCWM': 8.913, 'TeamName': 'E T Brigade'}, {'TeamNum': 22529, 'OPR': 36.44, 'Auto': 4.01, 'CCWM': -22.151, 'TeamName': 'RoboGOATs'}, {'TeamNum': 13084, 'OPR': 20.671, 'Auto': 5.788, 'CCWM': -72.402, 'TeamName': 'Robot Raiders'}, {'TeamNum': 9367, 'OPR': 11.79, 'Auto': -0.584, 'CCWM': -87.339, 'TeamName': 'Torrey Techies White'}, {'TeamNum': 22687, 'OPR': 5.699, 'Auto': -8.275, 'CCWM': -59.209, 'TeamName': 'TS1'}]
i 989
{'7854', '13190', '16026', '19862', '20326', '20383', '18373', '20367', '19505', '14525', '15385', '8404', '11311', '12492', '7390', '14473', '20370', '20366', '22040', '7641', '20368', '21534', '21781', '20405', '12516', '13356'}
[{'TeamNum': 14525, 'OPR': 162.345, 'Auto': 42.682, 'CCWM': 97.07, 'TeamName': 'TerraBats'}, {'TeamNum': 19862, 'OPR': 137.397, 'Auto': 47.428, 'CCWM': 66.544, 'TeamName': 'Mecha Mantises'}, {'TeamNum': 7641, 'OPR': 122.403, 'Auto': 24.04, 'CCWM': 105.111, 'TeamName': 'MSET BettaFish'}, {'TeamNum': 7390, 'OPR': 106.671, 'Auto': 26.555, 'CCWM': 32.35, 'TeamName': 'MSET JellyFish'}, {'TeamNum': 13356, 'OPR': 99.378, 'Auto': 13.335, 'CCWM': 34.607, 'TeamName': 'RoboForce'}, {'TeamNum': 20367, 'OPR': 94.57, 'Auto': 22.497, 'CCWM': 47.616, 'TeamName': 'RMS Cerberus'}, {'TeamNum': 7854, 'OPR': 90.481, 'Auto': 18.174, 'CCWM': 67.228, 'TeamName': 'MidKnight Madness'}, {'TeamNum': 21781, 'OPR': 78.678, 'Auto': 21.639, 'CCWM': -5.627, 'TeamName': 'Mecha-lions'}, {'TeamNum': 20405, 'OPR': 75.896, 'Auto': 17.825, 'CCWM': 55.282, 'TeamName': 'RMS Hydra'}, {'TeamNum': 20370, 'OPR': 68.937, 'Auto': 16.618, 'CCWM': -11.222, 'TeamName': 'RMS Phoenix'}, {'TeamNum': 21534, 'OPR': 67.478, 'Auto': 13.451, 'CCWM': -14.553, 'TeamName': 'The Craft and the Curious'}, {'TeamNum': 12492, 'OPR': 59.306, 'Auto': 11.919, 'CCWM': -36.523, 'TeamName': 'Blender Bots'}, {'TeamNum': 15385, 'OPR': 58.368, 'Auto': 13.425, 'CCWM': 9.151, 'TeamName': 'MidKnight Mayhem'}, {'TeamNum': 11311, 'OPR': 56.16, 'Auto': 6.883, 'CCWM': -13.636, 'TeamName': 'Paragon'}, {'TeamNum': 18373, 'OPR': 53.659, 'Auto': 8.476, 'CCWM': -32.453, 'TeamName': 'Blizzard Robotics'}, {'TeamNum': 13190, 'OPR': 44.895, 'Auto': 7.48, 'CCWM': -14.198, 'TeamName': 'Roblivion'}, {'TeamNum': 19505, 'OPR': 43.205, 'Auto': 10.798, 'CCWM': -29.005, 'TeamName': 'TerraRise'}, {'TeamNum': 12516, 'OPR': 40.362, 'Auto': 4.63, 'CCWM': -40.845, 'TeamName': 'Summit Robotics '}, {'TeamNum': 16026, 'OPR': 38.783, 'Auto': -0.141, 'CCWM': -1.624, 'TeamName': 'Alphabots'}, {'TeamNum': 20326, 'OPR': 36.954, 'Auto': -4.029, 'CCWM': -51.991, 'TeamName': 'RMS Khrysaor'}, {'TeamNum': 22040, 'OPR': 36.167, 'Auto': 6.428, 'CCWM': -11.23, 'TeamName': 'Allstars R2 Robotics'}, {'TeamNum': 20383, 'OPR': 27.309, 'Auto': 13.333, 'CCWM': -37.16, 'TeamName': 'RMS Yetis'}, {'TeamNum': 14473, 'OPR': 25.648, 'Auto': 5.094, 'CCWM': -69.108, 'TeamName': 'Future'}, {'TeamNum': 8404, 'OPR': 22.664, 'Auto': -0.772, 'CCWM': -18.417, 'TeamName': 'Quixilver '}, {'TeamNum': 20368, 'OPR': 7.435, 'Auto': 1.029, 'CCWM': -75.51, 'TeamName': 'RMS Thunderbirds'}, {'TeamNum': 20366, 'OPR': 4.84, 'Auto': 1.41, 'CCWM': -57.653, 'TeamName': 'RMS Werewolves'}]
USCANOSBLT
[{'TeamNum': 14525, 'OPR': 162.345, 'Auto': 42.682, 'CCWM': 97.07, 'TeamName': 'TerraBats'}, {'TeamNum': 19862, 'OPR': 137.397, 'Auto': 47.428, 'CCWM': 66.544, 'TeamName': 'Mecha Mantises'}, {'TeamNum': 7641, 'OPR': 122.403, 'Auto': 24.04, 'CCWM': 105.111, 'TeamName': 'MSET BettaFish'}, {'TeamNum': 7390, 'OPR': 106.671, 'Auto': 26.555, 'CCWM': 32.35, 'TeamName': 'MSET JellyFish'}, {'TeamNum': 13356, 'OPR': 99.378, 'Auto': 13.335, 'CCWM': 34.607, 'TeamName': 'RoboForce'}, {'TeamNum': 20367, 'OPR': 94.57, 'Auto': 22.497, 'CCWM': 47.616, 'TeamName': 'RMS Cerberus'}, {'TeamNum': 7854, 'OPR': 90.481, 'Auto': 18.174, 'CCWM': 67.228, 'TeamName': 'MidKnight Madness'}, {'TeamNum': 21781, 'OPR': 78.678, 'Auto': 21.639, 'CCWM': -5.627, 'TeamName': 'Mecha-lions'}, {'TeamNum': 20405, 'OPR': 75.896, 'Auto': 17.825, 'CCWM': 55.282, 'TeamName': 'RMS Hydra'}, {'TeamNum': 20370, 'OPR': 68.937, 'Auto': 16.618, 'CCWM': -11.222, 'TeamName': 'RMS Phoenix'}, {'TeamNum': 21534, 'OPR': 67.478, 'Auto': 13.451, 'CCWM': -14.553, 'TeamName': 'The Craft and the Curious'}, {'TeamNum': 12492, 'OPR': 59.306, 'Auto': 11.919, 'CCWM': -36.523, 'TeamName': 'Blender Bots'}, {'TeamNum': 15385, 'OPR': 58.368, 'Auto': 13.425, 'CCWM': 9.151, 'TeamName': 'MidKnight Mayhem'}, {'TeamNum': 11311, 'OPR': 56.16, 'Auto': 6.883, 'CCWM': -13.636, 'TeamName': 'Paragon'}, {'TeamNum': 18373, 'OPR': 53.659, 'Auto': 8.476, 'CCWM': -32.453, 'TeamName': 'Blizzard Robotics'}, {'TeamNum': 13190, 'OPR': 44.895, 'Auto': 7.48, 'CCWM': -14.198, 'TeamName': 'Roblivion'}, {'TeamNum': 19505, 'OPR': 43.205, 'Auto': 10.798, 'CCWM': -29.005, 'TeamName': 'TerraRise'}, {'TeamNum': 12516, 'OPR': 40.362, 'Auto': 4.63, 'CCWM': -40.845, 'TeamName': 'Summit Robotics '}, {'TeamNum': 16026, 'OPR': 38.783, 'Auto': -0.141, 'CCWM': -1.624, 'TeamName': 'Alphabots'}, {'TeamNum': 20326, 'OPR': 36.954, 'Auto': -4.029, 'CCWM': -51.991, 'TeamName': 'RMS Khrysaor'}, {'TeamNum': 22040, 'OPR': 36.167, 'Auto': 6.428, 'CCWM': -11.23, 'TeamName': 'Allstars R2 Robotics'}, {'TeamNum': 20383, 'OPR': 27.309, 'Auto': 13.333, 'CCWM': -37.16, 'TeamName': 'RMS Yetis'}, {'TeamNum': 14473, 'OPR': 25.648, 'Auto': 5.094, 'CCWM': -69.108, 'TeamName': 'Future'}, {'TeamNum': 8404, 'OPR': 22.664, 'Auto': -0.772, 'CCWM': -18.417, 'TeamName': 'Quixilver '}, {'TeamNum': 20368, 'OPR': 7.435, 'Auto': 1.029, 'CCWM': -75.51, 'TeamName': 'RMS Thunderbirds'}, {'TeamNum': 20366, 'OPR': 4.84, 'Auto': 1.41, 'CCWM': -57.653, 'TeamName': 'RMS Werewolves'}]

i 990
{'22026', '17702', '15097', '18142', '4262', '22628', '9266', '5131', '8097', '12778', '22105', '10809', '5136', '11212', '11128', '15146', '9261'}
[{'TeamNum': 17702, 'OPR': 94.445, 'Auto': 25.39, 'CCWM': 67.791, 'TeamName': 'Transcendence'}, {'TeamNum': 11212, 'OPR': 79.17, 'Auto': 27.085, 'CCWM': 44.996, 'TeamName': 'The Clueless '}, {'TeamNum': 8097, 'OPR': 71.51, 'Auto': 8.342, 'CCWM': 30.872, 'TeamName': 'Botcats'}, {'TeamNum': 5131, 'OPR': 57.681, 'Auto': 13.74, 'CCWM': 2.299, 'TeamName': 'Pointers'}, {'TeamNum': 10809, 'OPR': 50.185, 'Auto': 29.138, 'CCWM': -7.836, 'TeamName': 'Crow Force'}, {'TeamNum': 9266, 'OPR': 46.763, 'Auto': 8.233, 'CCWM': 8.668, 'TeamName': 'Pyrobots'}, {'TeamNum': 15097, 'OPR': 42.7, 'Auto': -2.35, 'CCWM': 24.627, 'TeamName': 'Python'}, {'TeamNum': 15146, 'OPR': 41.434, 'Auto': 6.285, 'CCWM': -6.596, 'TeamName': 'GarageBot'}, {'TeamNum': 4262, 'OPR': 38.279, 'Auto': 15.703, 'CCWM': -4.859, 'TeamName': 'Ridgebots'}, {'TeamNum': 18142, 'OPR': 38.059, 'Auto': 15.996, 'CCWM': -0.65, 'TeamName': 'FusionTech'}, {'TeamNum': 22105, 'OPR': 37.835, 'Auto': 12.326, 'CCWM': -11.662, 'TeamName': 'Runtime Terror'}, {'TeamNum': 22026, 'OPR': 36.694, 'Auto': -2.85, 'CCWM': -35.733, 'TeamName': 'Team Bandits'}, {'TeamNum': 9261, 'OPR': 35.817, 'Auto': 12.883, 'CCWM': 0.649, 'TeamName': 'Level Up'}, {'TeamNum': 11128, 'OPR': 21.871, 'Auto': -5.998, 'CCWM': -23.228, 'TeamName': 'Inspiration'}, {'TeamNum': 22628, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Steele Canyon Robotics'}, {'TeamNum': 5136, 'OPR': -0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Crusader Creators'}, {'TeamNum': 12778, 'OPR': -6.872, 'Auto': 3.021, 'CCWM': -94.374, 'TeamName': 'Tech Empire'}]
USCASDSDTULT
[{'TeamNum': 17702, 'OPR': 94.445, 'Auto': 25.39, 'CCWM': 67.791, 'TeamName': 'Transcendence'}, {'TeamNum': 11212, 'OPR': 79.17, 'Auto': 27.085, 'CCWM': 44.996, 'TeamName': 'The Clueless '}, {'TeamNum': 8097, 'OPR': 71.51, 'Auto': 8.342, 'CCWM': 30.872, 'TeamName': 'Botcats'}, {'TeamNum': 5131, 'OPR': 57.681, 'Auto': 13.74, 'CCWM': 2.299, 'TeamName': 'Pointers'}, {'TeamNum': 10809, 'OPR': 50.185, 'Auto': 29.138, 'CCWM': -7.836, 'TeamName': 'Crow Force'}, {'TeamNum': 9266, 'OPR': 46.763, 'Auto': 8.233, 'CCWM': 8.668, 'TeamName': 'Pyrobots'}, {'TeamNum': 15097, 'OPR': 42.7, 'Auto': -2.35, 'CCWM': 24.627, 'TeamName': 'Python'}, {'TeamNum': 15146, 'OPR': 41.434, 'Auto': 6.285, 'CCWM': -6.596, 'TeamName': 'GarageBot'}, {'TeamNum': 4262, 'OPR': 38.279, 'Auto': 15.703, 'CCWM': -4.859, 'TeamName': 'Ridgebots'}, {'TeamNum': 18142, 'OPR': 38.059, 'Auto': 15.996, 'CCWM': -0.65, 'TeamName': 'FusionTech'}, {'TeamNum': 22105, 'OPR': 37.835, 'Auto': 12.326, 'CCWM': -11.662, 'TeamName': 'Runtime Terror'}, {'TeamNum': 22026, 'OPR': 36.694, 'Auto': -2.85, 'CCWM': -35.733, 'TeamName': 'Team Bandits'}, {'TeamNum': 9261, 'OPR': 35.817, 'Auto': 12.883, 'CCWM': 0.649, 'TeamName': 'Level Up'}, {'TeamNum': 11128, 'OPR': 21.871, 'Auto': -5.998, 'CCWM': -23.228, 'TeamName': 'Inspiration'}, {'TeamNum': 22628, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Steele Canyon Robotics'}, {'TeamNum': 5136, 'OPR': -0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Crusader Creators'}, {'TeamNum': 12778, 'OPR': -6.872, 'Auto': 3.021, 'CCWM': -94.374, 'TeamName': 'Tech Empire'}]
i 991
{'22984', '20151', '5518', '18978', '12923', '10132', '12377', '17703', '13251', '20188', '9650', '15668', '21503', '40', '18366', '21691', '18813', '8942', '6762', '18843', '5017', '22096', '19462', '13965'}
[{'TeamNum': 20188, 'OPR': 94.763, 'Auto': 24.534, 'CCWM': 64.548, 'TeamName': 'Hotchkiss EFX Gearcats A'}, {'TeamNum': 18843, 'OPR': 94.583, 'Auto': 20.713, 'CCWM': 47.156, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 18813, 'OPR': 81.868, 'Auto': 8.952, 'CCWM': 13.108, 'TeamName': 'FullMetal Phoenixes'}, {'TeamNum': 22984, 'OPR': 74.222, 'Auto': 22.023, 'CCWM': 31.873, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 21503, 'OPR': 72.512, 'Auto': 23.674, 'CCWM': -4.452, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 17703, 'OPR': 66.073, 'Auto': 15.975, 'CCWM': 32.76, 'TeamName': 'FullMetal Peregrines'}, {'TeamNum': 18366, 'OPR': 62.517, 'Auto': 12.521, 'CCWM': 29.812, 'TeamName': 'Robolution'}, {'TeamNum': 8942, 'OPR': 61.596, 'Auto': 19.09, 'CCWM': -0.456, 'TeamName': 'Team Max'}, {'TeamNum': 18978, 'OPR': 52.485, 'Auto': 11.856, 'CCWM': -1.347, 'TeamName': 'SemiPlatinum Penguins'}, {'TeamNum': 19462, 'OPR': 51.371, 'Auto': 13.471, 'CCWM': -2.746, 'TeamName': 'Team Beta'}, {'TeamNum': 12923, 'OPR': 50.255, 'Auto': 26.203, 'CCWM': 2.428, 'TeamName': 'Techno T-Rexes'}, {'TeamNum': 10132, 'OPR': 36.263, 'Auto': -0.019, 'CCWM': 31.073, 'TeamName': 'Rocket Beavers'}, {'TeamNum': 13965, 'OPR': 34.421, 'Auto': 15.962, 'CCWM': -18.217, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 12377, 'OPR': 34.282, 'Auto': 16.666, 'CCWM': -37.043, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 5017, 'OPR': 33.103, 'Auto': 0.631, 'CCWM': -15.92, 'TeamName': 'RoboEpic'}, {'TeamNum': 22096, 'OPR': 30.951, 'Auto': 19.849, 'CCWM': 22.009, 'TeamName': 'RoboTastic'}, {'TeamNum': 5518, 'OPR': 30.219, 'Auto': 25.185, 'CCWM': 9.818, 'TeamName': "Dutchman's Derivatives"}, {'TeamNum': 15668, 'OPR': 26.369, 'Auto': 7.401, 'CCWM': -13.471, 'TeamName': 'FullMetal Kestrels'}, {'TeamNum': 9650, 'OPR': 22.472, 'Auto': -0.807, 'CCWM': -27.957, 'TeamName': 'Machine Maniacs'}, {'TeamNum': 20151, 'OPR': 20.025, 'Auto': 0.434, 'CCWM': -1.743, 'TeamName': 'The RoboWreckers'}, {'TeamNum': 13251, 'OPR': 18.116, 'Auto': 2.908, 'CCWM': -24.287, 'TeamName': 'Canterbury School'}, {'TeamNum': 40, 'OPR': 17.242, 'Auto': -5.722, 'CCWM': -33.194, 'TeamName': 'HAX Robotics'}, {'TeamNum': 6762, 'OPR': 14.453, 'Auto': 3.845, 'CCWM': -81.39, 'TeamName': 'N R G (Northwestern Robotics Gearheads)'}, {'TeamNum': 21691, 'OPR': 4.84, 'Auto': -7.744, 'CCWM': -22.364, 'TeamName': 'Lumens Robotics-Westover School'}]
USCTSOQ
[{'TeamNum': 20188, 'OPR': 94.763, 'Auto': 24.534, 'CCWM': 64.548, 'TeamName': 'Hotchkiss EFX Gearcats A'}, {'TeamNum': 18843, 'OPR': 94.583, 'Auto': 20.713, 'CCWM': 47.156, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 18813, 'OPR': 81.868, 'Auto': 8.952, 'CCWM': 13.108, 'TeamName': 'FullMetal Phoenixes'}, {'TeamNum': 22984, 'OPR': 74.222, 'Auto': 22.023, 'CCWM': 31.873, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 21503, 'OPR': 72.512, 'Auto': 23.674, 'CCWM': -4.452, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 17703, 'OPR': 66.073, 'Auto': 15.975, 'CCWM': 32.76, 'TeamName': 'FullMetal Peregrines'}, {'TeamNum': 18366, 'OPR': 62.517, 'Auto': 12.521, 'CCWM': 29.812, 'TeamName': 'Robolution'}, {'TeamNum': 8942, 'OPR': 61.596, 'Auto': 19.09, 'CCWM': -0.456, 'TeamName': 'Team Max'}, {'TeamNum': 18978, 'OPR': 52.485, 'Auto': 11.856, 'CCWM': -1.347, 'TeamName': 'SemiPlatinum Penguins'}, {'TeamNum': 19462, 'OPR': 51.371, 'Auto': 13.471, 'CCWM': -2.746, 'TeamName': 'Team Beta'}, {'TeamNum': 12923, 'OPR': 50.255, 'Auto': 26.203, 'CCWM': 2.428, 'TeamName': 'Techno T-Rexes'}, {'TeamNum': 10132, 'OPR': 36.263, 'Auto': -0.019, 'CCWM': 31.073, 'TeamName': 'Rocket Beavers'}, {'TeamNum': 13965, 'OPR': 34.421, 'Auto': 15.962, 'CCWM': -18.217, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 12377, 'OPR': 34.282, 'Auto': 16.666, 'CCWM': -37.043, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 5017, 'OPR': 33.103, 'Auto': 0.631, 'CCWM': -15.92, 'TeamName': 'RoboEpic'}, {'TeamNum': 22096, 'OPR': 30.951, 'Auto': 19.849, 'CCWM': 22.009, 'TeamName': 'RoboTastic'}, {'TeamNum': 5518, 'OPR': 30.219, 'Auto': 25.185, 'CCWM': 9.818, 'TeamName': "Dutchman's Derivatives"}, {'TeamNum': 15668, 'OPR': 26.369, 'Auto': 7.401, 'CCWM': -13.471, 'TeamName': 'FullMetal Kestrels'}, {'TeamNum': 9650, 'OPR': 22.472, 'Auto': -0.807, 'CCWM': -27.957, 'TeamName': 'Machine Maniacs'}, {'TeamNum': 20151, 'OPR': 20.025, 'Auto': 0.434, 'CCWM': -1.743, 'TeamName': 'The RoboWreckers'}, {'TeamNum': 13251, 'OPR': 18.116, 'Auto': 2.908, 'CCWM': -24.287, 'TeamName': 'Canterbury School'}, {'TeamNum': 40, 'OPR': 17.242, 'Auto': -5.722, 'CCWM': -33.194, 'TeamName': 'HAX Robotics'}, {'TeamNum': 6762, 'OPR': 14.453, 'Auto': 3.845, 'CCWM': -81.39, 'TeamName': 'N R G (Northwestern Robotics Gearheads)'}, {'TeamNum': 21691, 'OPR': 4.84, 'Auto': -7.744, 'CCWM': -22.364, 'TeamName': 'Lumens Robotics-Westover School'}]

i 992
i 993
{'9974', '16736', '8887', '10435', '10602', '21948', '14375', '5126', '14172', '13186', '18397', '19368', '6103', '18527', '14568', '19415', '10185', '13416', '6666', '18050', '13085', '22187', '3738', '21311'}
[{'TeamNum': 18527, 'OPR': 145.996, 'Auto': 44.475, 'CCWM': 99.296, 'TeamName': 'PCM Alchemists'}, {'TeamNum': 10435, 'OPR': 134.477, 'Auto': 20.278, 'CCWM': 56.299, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 9974, 'OPR': 113.622, 'Auto': 29.76, 'CCWM': 31.037, 'TeamName': 'T.H.O.R. '}, {'TeamNum': 5126, 'OPR': 111.755, 'Auto': 16.007, 'CCWM': 63.48, 'TeamName': 'DICE'}, {'TeamNum': 14568, 'OPR': 103.183, 'Auto': 22.212, 'CCWM': 62.911, 'TeamName': 'Norwalk RoboWarriors'}, {'TeamNum': 16736, 'OPR': 102.032, 'Auto': 28.901, 'CCWM': 51.914, 'TeamName': 'Atomic Narwhals'}, {'TeamNum': 18397, 'OPR': 90.494, 'Auto': 25.454, 'CCWM': 1.268, 'TeamName': 'Aztechs'}, {'TeamNum': 6666, 'OPR': 87.954, 'Auto': 26.451, 'CCWM': 24.807, 'TeamName': 'Quad Six'}, {'TeamNum': 19368, 'OPR': 87.692, 'Auto': 19.979, 'CCWM': -13.374, 'TeamName': 'Manufactured Chaos'}, {'TeamNum': 13416, 'OPR': 79.99, 'Auto': 33.092, 'CCWM': 12.101, 'TeamName': 'JagWires'}, {'TeamNum': 6103, 'OPR': 77.695, 'Auto': 24.842, 'CCWM': 49.145, 'TeamName': 'Radiant Rivals'}, {'TeamNum': 21311, 'OPR': 74.807, 'Auto': 20.386, 'CCWM': -38.475, 'TeamName': 'Lion Robotics'}, {'TeamNum': 13186, 'OPR': 74.797, 'Auto': 25.476, 'CCWM': 28.979, 'TeamName': 'Lactose Intolerance'}, {'TeamNum': 14172, 'OPR': 73.939, 'Auto': 23.124, 'CCWM': 27.713, 'TeamName': 'Disco Duckbots'}, {'TeamNum': 18050, 'OPR': 59.72, 'Auto': 15.803, 'CCWM': -15.666, 'TeamName': 'Team Photon'}, {'TeamNum': 22187, 'OPR': 46.83, 'Auto': -0.755, 'CCWM': -51.174, 'TeamName': 'A.I.R. '}, {'TeamNum': 13085, 'OPR': 45.871, 'Auto': 2.564, 'CCWM': -54.277, 'TeamName': 'Bionic Dutch'}, {'TeamNum': 19415, 'OPR': 44.797, 'Auto': 6.764, 'CCWM': -31.858, 'TeamName': 'C3 Robotics'}, {'TeamNum': 10185, 'OPR': 43.049, 'Auto': 14.103, 'CCWM': -5.406, 'TeamName': 'From The Island Of Misfit Robots'}, {'TeamNum': 3738, 'OPR': 39.084, 'Auto': 5.448, 'CCWM': -71.094, 'TeamName': 'The Error Codes'}, {'TeamNum': 10602, 'OPR': 38.83, 'Auto': -5.31, 'CCWM': -46.899, 'TeamName': 'Prolific'}, {'TeamNum': 21948, 'OPR': 26.803, 'Auto': 3.272, 'CCWM': -61.567, 'TeamName': 'Secret Servos'}, {'TeamNum': 14375, 'OPR': 23.749, 'Auto': 5.168, 'CCWM': -25.902, 'TeamName': 'We Over Slept'}, {'TeamNum': 8887, 'OPR': 4.001, 'Auto': -6.328, 'CCWM': -93.257, 'TeamName': 'Marshalltown BotCats'}]
USIANOSQ
[{'TeamNum': 18527, 'OPR': 145.996, 'Auto': 44.475, 'CCWM': 99.296, 'TeamName': 'PCM Alchemists'}, {'TeamNum': 10435, 'OPR': 134.477, 'Auto': 20.278, 'CCWM': 56.299, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 9974, 'OPR': 113.622, 'Auto': 29.76, 'CCWM': 31.037, 'TeamName': 'T.H.O.R. '}, {'TeamNum': 5126, 'OPR': 111.755, 'Auto': 16.007, 'CCWM': 63.48, 'TeamName': 'DICE'}, {'TeamNum': 14568, 'OPR': 103.183, 'Auto': 22.212, 'CCWM': 62.911, 'TeamName': 'Norwalk RoboWarriors'}, {'TeamNum': 16736, 'OPR': 102.032, 'Auto': 28.901, 'CCWM': 51.914, 'TeamName': 'Atomic Narwhals'}, {'TeamNum': 18397, 'OPR': 90.494, 'Auto': 25.454, 'CCWM': 1.268, 'TeamName': 'Aztechs'}, {'TeamNum': 6666, 'OPR': 87.954, 'Auto': 26.451, 'CCWM': 24.807, 'TeamName': 'Quad Six'}, {'TeamNum': 19368, 'OPR': 87.692, 'Auto': 19.979, 'CCWM': -13.374, 'TeamName': 'Manufactured Chaos'}, {'TeamNum': 13416, 'OPR': 79.99, 'Auto': 33.092, 'CCWM': 12.101, 'TeamName': 'JagWires'}, {'TeamNum': 6103, 'OPR': 77.695, 'Auto': 24.842, 'CCWM': 49.145, 'TeamName': 'Radiant Rivals'}, {'TeamNum': 21311, 'OPR': 74.807, 'Auto': 20.386, 'CCWM': -38.475, 'TeamName': 'Lion Robotics'}, {'TeamNum': 13186, 'OPR': 74.797, 'Auto': 25.476, 'CCWM': 28.979, 'TeamName': 'Lactose Intolerance'}, {'TeamNum': 14172, 'OPR': 73.939, 'Auto': 23.124, 'CCWM': 27.713, 'TeamName': 'Disco Duckbots'}, {'TeamNum': 18050, 'OPR': 59.72, 'Auto': 15.803, 'CCWM': -15.666, 'TeamName': 'Team Photon'}, {'TeamNum': 22187, 'OPR': 46.83, 'Auto': -0.755, 'CCWM': -51.174, 'TeamName': 'A.I.R. '}, {'TeamNum': 13085, 'OPR': 45.871, 'Auto': 2.564, 'CCWM': -54.277, 'TeamName': 'Bionic Dutch'}, {'TeamNum': 19415, 'OPR': 44.797, 'Auto': 6.764, 'CCWM': -31.858, 'TeamName': 'C3 Robotics'}, {'TeamNum': 10185, 'OPR': 43.049, 'Auto': 14.103, 'CCWM': -5.406, 'TeamName': 'From The Island Of Misfit Robots'}, {'TeamNum': 3738, 'OPR': 39.084, 'Auto': 5.448, 'CCWM': -71.094, 'TeamName': 'The Error Codes'}, {'TeamNum': 10602, 'OPR': 38.83, 'Auto': -5.31, 'CCWM': -46.899, 'TeamName': 'Prolific'}, {'TeamNum': 21948, 'OPR': 26.803, 'Auto': 3.272, 'CCWM': -61.567, 'TeamName': 'Secret Servos'}, {'TeamNum': 14375, 'OPR': 23.749, 'Auto': 5.168, 'CCWM': -25.902, 'TeamName': 'We Over Slept'}, {'TeamNum': 8887, 'OPR': 4.001, 'Auto': -6.328, 'CCWM': -93.257, 'TeamName': 'Marshalltown BotCats'}]
i 994
{'16751', '12971', '10303', '21426', '19938', '15031', '22146', '7129', '16989', '5187', '11752', '10254', '14371', '21634', '15410', '6206', '14204', '22864', '8620', '14840', '13365', '18093'}
[{'TeamNum': 14840, 'OPR': 129.846, 'Auto': 27.313, 'CCWM': 95.895, 'TeamName': 'DCS MechWarriors'}, {'TeamNum': 12971, 'OPR': 124.887, 'Auto': 25.395, 'CCWM': 91.251, 'TeamName': 'Ctrl-Y'}, {'TeamNum': 14204, 'OPR': 87.553, 'Auto': 11.794, 'CCWM': 39.546, 'TeamName': 'Super Scream Bros'}, {'TeamNum': 8620, 'OPR': 82.043, 'Auto': 34.816, 'CCWM': 21.92, 'TeamName': 'Wormgear Warriors'}, {'TeamNum': 7129, 'OPR': 79.597, 'Auto': 12.349, 'CCWM': 25.543, 'TeamName': 'Robo Raiders'}, {'TeamNum': 11752, 'OPR': 77.109, 'Auto': 20.952, 'CCWM': 40.956, 'TeamName': 'Orphan Bots'}, {'TeamNum': 22864, 'OPR': 65.445, 'Auto': 13.674, 'CCWM': 53.712, 'TeamName': 'Gearheads 2.0'}, {'TeamNum': 16751, 'OPR': 61.827, 'Auto': 19.45, 'CCWM': 24.627, 'TeamName': 'Polytechnic Puzzle Pieces (P3)'}, {'TeamNum': 16989, 'OPR': 61.766, 'Auto': 18.733, 'CCWM': -8.396, 'TeamName': 'Route 1 Robotics'}, {'TeamNum': 5187, 'OPR': 60.632, 'Auto': 25.312, 'CCWM': -23.7, 'TeamName': 'Transistor Titans'}, {'TeamNum': 19938, 'OPR': 48.175, 'Auto': 3.069, 'CCWM': 14.561, 'TeamName': 'Knights of the Ping Pong Table'}, {'TeamNum': 15410, 'OPR': 48.114, 'Auto': 18.774, 'CCWM': -31.606, 'TeamName': 'Welded Warriors'}, {'TeamNum': 22146, 'OPR': 45.052, 'Auto': 8.666, 'CCWM': 4.602, 'TeamName': 'Metalloids'}, {'TeamNum': 18093, 'OPR': 42.453, 'Auto': 11.322, 'CCWM': -28.999, 'TeamName': 'SWAT 2.0'}, {'TeamNum': 14371, 'OPR': 41.43, 'Auto': 23.74, 'CCWM': -24.303, 'TeamName': 'MT. ZION BRAVES'}, {'TeamNum': 6206, 'OPR': 36.968, 'Auto': 8.465, 'CCWM': -45.536, 'TeamName': 'Ohms Olympians'}, {'TeamNum': 10254, 'OPR': 34.234, 'Auto': 22.557, 'CCWM': -73.919, 'TeamName': 'MCHS RoboLions'}, {'TeamNum': 10303, 'OPR': 32.704, 'Auto': 13.884, 'CCWM': -43.177, 'TeamName': 'Robot Rebellion'}, {'TeamNum': 13365, 'OPR': 29.313, 'Auto': 7.368, 'CCWM': -18.111, 'TeamName': 'Gearheads'}, {'TeamNum': 21634, 'OPR': 20.885, 'Auto': -10.655, 'CCWM': -16.227, 'TeamName': 'Metal Masterminds'}, {'TeamNum': 15031, 'OPR': 16.72, 'Auto': 4.314, 'CCWM': -35.248, 'TeamName': 'BoltBusterZ'}, {'TeamNum': 21426, 'OPR': 12.803, 'Auto': -1.639, 'CCWM': -67.225, 'TeamName': 'Mechanical Ducks'}]
USILSCLT
[{'TeamNum': 14840, 'OPR': 129.846, 'Auto': 27.313, 'CCWM': 95.895, 'TeamName': 'DCS MechWarriors'}, {'TeamNum': 12971, 'OPR': 124.887, 'Auto': 25.395, 'CCWM': 91.251, 'TeamName': 'Ctrl-Y'}, {'TeamNum': 14204, 'OPR': 87.553, 'Auto': 11.794, 'CCWM': 39.546, 'TeamName': 'Super Scream Bros'}, {'TeamNum': 8620, 'OPR': 82.043, 'Auto': 34.816, 'CCWM': 21.92, 'TeamName': 'Wormgear Warriors'}, {'TeamNum': 7129, 'OPR': 79.597, 'Auto': 12.349, 'CCWM': 25.543, 'TeamName': 'Robo Raiders'}, {'TeamNum': 11752, 'OPR': 77.109, 'Auto': 20.952, 'CCWM': 40.956, 'TeamName': 'Orphan Bots'}, {'TeamNum': 22864, 'OPR': 65.445, 'Auto': 13.674, 'CCWM': 53.712, 'TeamName': 'Gearheads 2.0'}, {'TeamNum': 16751, 'OPR': 61.827, 'Auto': 19.45, 'CCWM': 24.627, 'TeamName': 'Polytechnic Puzzle Pieces (P3)'}, {'TeamNum': 16989, 'OPR': 61.766, 'Auto': 18.733, 'CCWM': -8.396, 'TeamName': 'Route 1 Robotics'}, {'TeamNum': 5187, 'OPR': 60.632, 'Auto': 25.312, 'CCWM': -23.7, 'TeamName': 'Transistor Titans'}, {'TeamNum': 19938, 'OPR': 48.175, 'Auto': 3.069, 'CCWM': 14.561, 'TeamName': 'Knights of the Ping Pong Table'}, {'TeamNum': 15410, 'OPR': 48.114, 'Auto': 18.774, 'CCWM': -31.606, 'TeamName': 'Welded Warriors'}, {'TeamNum': 22146, 'OPR': 45.052, 'Auto': 8.666, 'CCWM': 4.602, 'TeamName': 'Metalloids'}, {'TeamNum': 18093, 'OPR': 42.453, 'Auto': 11.322, 'CCWM': -28.999, 'TeamName': 'SWAT 2.0'}, {'TeamNum': 14371, 'OPR': 41.43, 'Auto': 23.74, 'CCWM': -24.303, 'TeamName': 'MT. ZION BRAVES'}, {'TeamNum': 6206, 'OPR': 36.968, 'Auto': 8.465, 'CCWM': -45.536, 'TeamName': 'Ohms Olympians'}, {'TeamNum': 10254, 'OPR': 34.234, 'Auto': 22.557, 'CCWM': -73.919, 'TeamName': 'MCHS RoboLions'}, {'TeamNum': 10303, 'OPR': 32.704, 'Auto': 13.884, 'CCWM': -43.177, 'TeamName': 'Robot Rebellion'}, {'TeamNum': 13365, 'OPR': 29.313, 'Auto': 7.368, 'CCWM': -18.111, 'TeamName': 'Gearheads'}, {'TeamNum': 21634, 'OPR': 20.885, 'Auto': -10.655, 'CCWM': -16.227, 'TeamName': 'Metal Masterminds'}, {'TeamNum': 15031, 'OPR': 16.72, 'Auto': 4.314, 'CCWM': -35.248, 'TeamName': 'BoltBusterZ'}, {'TeamNum': 21426, 'OPR': 12.803, 'Auto': -1.639, 'CCWM': -67.225, 'TeamName': 'Mechanical Ducks'}]

i 995
{'19648', '22213', '21862', '7006', '22269', '3216', '13699', '4965', '22272', '9410', '13829', '15094', '3507', '8728', '22525', '17567', '22273', '22190', '14422'}
[{'TeamNum': 3507, 'OPR': 76.177, 'Auto': 18.147, 'CCWM': 62.596, 'TeamName': 'Robotheosis'}, {'TeamNum': 4965, 'OPR': 70.949, 'Auto': 9.359, 'CCWM': 54.583, 'TeamName': 'Animatores Romani'}, {'TeamNum': 3216, 'OPR': 61.505, 'Auto': 15.186, 'CCWM': 25.925, 'TeamName': 'Robophins'}, {'TeamNum': 19648, 'OPR': 58.328, 'Auto': 15.434, 'CCWM': 24.391, 'TeamName': 'Eagle Robotics Works'}, {'TeamNum': 13699, 'OPR': 54.342, 'Auto': 19.596, 'CCWM': 15.436, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 15094, 'OPR': 48.481, 'Auto': 6.536, 'CCWM': 8.5, 'TeamName': 'JCP Danger Chickens'}, {'TeamNum': 7006, 'OPR': 48.464, 'Auto': 4.365, 'CCWM': 29.017, 'TeamName': 'RoboTitans'}, {'TeamNum': 9410, 'OPR': 47.665, 'Auto': 8.815, 'CCWM': 11.22, 'TeamName': "Frank's Garage"}, {'TeamNum': 13829, 'OPR': 39.011, 'Auto': 25.916, 'CCWM': -26.527, 'TeamName': 'Solorio Robotics'}, {'TeamNum': 22213, 'OPR': 32.059, 'Auto': 4.966, 'CCWM': 1.751, 'TeamName': "I'm BOTman"}, {'TeamNum': 17567, 'OPR': 26.492, 'Auto': 8.558, 'CCWM': -35.773, 'TeamName': 'The Brogrammers'}, {'TeamNum': 22269, 'OPR': 25.182, 'Auto': 3.654, 'CCWM': 10.908, 'TeamName': 'Roosevelt'}, {'TeamNum': 22272, 'OPR': 21.091, 'Auto': 1.553, 'CCWM': -1.303, 'TeamName': 'Morgan Park'}, {'TeamNum': 14422, 'OPR': 10.458, 'Auto': 4.255, 'CCWM': -53.454, 'TeamName': 'Twisted Mettle'}, {'TeamNum': 8728, 'OPR': 9.384, 'Auto': 4.408, 'CCWM': -24.925, 'TeamName': 'Bionic Wolves'}, {'TeamNum': 21862, 'OPR': 8.841, 'Auto': -1.038, 'CCWM': -29.276, 'TeamName': 'Chicago Squires'}, {'TeamNum': 22190, 'OPR': 3.792, 'Auto': -0.701, 'CCWM': -35.925, 'TeamName': 'ITW David Speer Academy 2'}, {'TeamNum': 22273, 'OPR': 1.986, 'Auto': -5.381, 'CCWM': -14.918, 'TeamName': 'Uplift FTC'}, {'TeamNum': 22525, 'OPR': -2.843, 'Auto': -4.961, 'CCWM': -24.406, 'TeamName': 'Richards'}]
USILCMLTB
[{'TeamNum': 3507, 'OPR': 76.177, 'Auto': 18.147, 'CCWM': 62.596, 'TeamName': 'Robotheosis'}, {'TeamNum': 4965, 'OPR': 70.949, 'Auto': 9.359, 'CCWM': 54.583, 'TeamName': 'Animatores Romani'}, {'TeamNum': 3216, 'OPR': 61.505, 'Auto': 15.186, 'CCWM': 25.925, 'TeamName': 'Robophins'}, {'TeamNum': 19648, 'OPR': 58.328, 'Auto': 15.434, 'CCWM': 24.391, 'TeamName': 'Eagle Robotics Works'}, {'TeamNum': 13699, 'OPR': 54.342, 'Auto': 19.596, 'CCWM': 15.436, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 15094, 'OPR': 48.481, 'Auto': 6.536, 'CCWM': 8.5, 'TeamName': 'JCP Danger Chickens'}, {'TeamNum': 7006, 'OPR': 48.464, 'Auto': 4.365, 'CCWM': 29.017, 'TeamName': 'RoboTitans'}, {'TeamNum': 9410, 'OPR': 47.665, 'Auto': 8.815, 'CCWM': 11.22, 'TeamName': "Frank's Garage"}, {'TeamNum': 13829, 'OPR': 39.011, 'Auto': 25.916, 'CCWM': -26.527, 'TeamName': 'Solorio Robotics'}, {'TeamNum': 22213, 'OPR': 32.059, 'Auto': 4.966, 'CCWM': 1.751, 'TeamName': "I'm BOTman"}, {'TeamNum': 17567, 'OPR': 26.492, 'Auto': 8.558, 'CCWM': -35.773, 'TeamName': 'The Brogrammers'}, {'TeamNum': 22269, 'OPR': 25.182, 'Auto': 3.654, 'CCWM': 10.908, 'TeamName': 'Roosevelt'}, {'TeamNum': 22272, 'OPR': 21.091, 'Auto': 1.553, 'CCWM': -1.303, 'TeamName': 'Morgan Park'}, {'TeamNum': 14422, 'OPR': 10.458, 'Auto': 4.255, 'CCWM': -53.454, 'TeamName': 'Twisted Mettle'}, {'TeamNum': 8728, 'OPR': 9.384, 'Auto': 4.408, 'CCWM': -24.925, 'TeamName': 'Bionic Wolves'}, {'TeamNum': 21862, 'OPR': 8.841, 'Auto': -1.038, 'CCWM': -29.276, 'TeamName': 'Chicago Squires'}, {'TeamNum': 22190, 'OPR': 3.792, 'Auto': -0.701, 'CCWM': -35.925, 'TeamName': 'ITW David Speer Academy 2'}, {'TeamNum': 22273, 'OPR': 1.986, 'Auto': -5.381, 'CCWM': -14.918, 'TeamName': 'Uplift FTC'}, {'TeamNum': 22525, 'OPR': -2.843, 'Auto': -4.961, 'CCWM': -24.406, 'TeamName': 'Richards'}]
i 996
{'22132', '20027', '18505', '22871', '9864', '7193', '12231', '19854', '8971', '11329', '20699', '17994', '19366', '10755'}
[{'TeamNum': 11329, 'OPR': 174.87, 'Auto': 49.942, 'CCWM': 118.195, 'TeamName': 'I.C.E. Robotics'}, {'TeamNum': 12231, 'OPR': 94.275, 'Auto': 17.498, 'CCWM': 31.912, 'TeamName': 'WarriorTech'}, {'TeamNum': 18505, 'OPR': 60.891, 'Auto': 13.123, 'CCWM': 20.184, 'TeamName': 'Something to do with Waffles'}, {'TeamNum': 9864, 'OPR': 54.05, 'Auto': 8.205, 'CCWM': 39.172, 'TeamName': 'Jug Rox Robotix'}, {'TeamNum': 17994, 'OPR': 45.209, 'Auto': 5.786, 'CCWM': -2.236, 'TeamName': 'Ragnabotics'}, {'TeamNum': 8971, 'OPR': 41.745, 'Auto': 12.421, 'CCWM': 17.455, 'TeamName': 'Diamond Blades'}, {'TeamNum': 19854, 'OPR': 38.69, 'Auto': 6.057, 'CCWM': -34.925, 'TeamName': 'Monkey Wrench'}, {'TeamNum': 10755, 'OPR': 36.855, 'Auto': 2.702, 'CCWM': -18.766, 'TeamName': 'The Technomages'}, {'TeamNum': 19366, 'OPR': 34.058, 'Auto': 8.778, 'CCWM': -1.278, 'TeamName': 'CTF'}, {'TeamNum': 20027, 'OPR': 32.876, 'Auto': 14.351, 'CCWM': -9.591, 'TeamName': 'The Granger Gurus'}, {'TeamNum': 20699, 'OPR': 23.418, 'Auto': 2.226, 'CCWM': -62.228, 'TeamName': 'WJHS Hatchet Ratchex Robotics'}, {'TeamNum': 22871, 'OPR': 20.247, 'Auto': 7.703, 'CCWM': -30.448, 'TeamName': 'Rox-Paper-Scissors'}, {'TeamNum': 7193, 'OPR': 15.172, 'Auto': 2.919, 'CCWM': -49.284, 'TeamName': 'South Spencer High School'}, {'TeamNum': 22132, 'OPR': 9.919, 'Auto': -0.466, 'CCWM': -19.735, 'TeamName': 'Gearserkers'}]
USINSLLT
[{'TeamNum': 11329, 'OPR': 174.87, 'Auto': 49.942, 'CCWM': 118.195, 'TeamName': 'I.C.E. Robotics'}, {'TeamNum': 12231, 'OPR': 94.275, 'Auto': 17.498, 'CCWM': 31.912, 'TeamName': 'WarriorTech'}, {'TeamNum': 18505, 'OPR': 60.891, 'Auto': 13.123, 'CCWM': 20.184, 'TeamName': 'Something to do with Waffles'}, {'TeamNum': 9864, 'OPR': 54.05, 'Auto': 8.205, 'CCWM': 39.172, 'TeamName': 'Jug Rox Robotix'}, {'TeamNum': 17994, 'OPR': 45.209, 'Auto': 5.786, 'CCWM': -2.236, 'TeamName': 'Ragnabotics'}, {'TeamNum': 8971, 'OPR': 41.745, 'Auto': 12.421, 'CCWM': 17.455, 'TeamName': 'Diamond Blades'}, {'TeamNum': 19854, 'OPR': 38.69, 'Auto': 6.057, 'CCWM': -34.925, 'TeamName': 'Monkey Wrench'}, {'TeamNum': 10755, 'OPR': 36.855, 'Auto': 2.702, 'CCWM': -18.766, 'TeamName': 'The Technomages'}, {'TeamNum': 19366, 'OPR': 34.058, 'Auto': 8.778, 'CCWM': -1.278, 'TeamName': 'CTF'}, {'TeamNum': 20027, 'OPR': 32.876, 'Auto': 14.351, 'CCWM': -9.591, 'TeamName': 'The Granger Gurus'}, {'TeamNum': 20699, 'OPR': 23.418, 'Auto': 2.226, 'CCWM': -62.228, 'TeamName': 'WJHS Hatchet Ratchex Robotics'}, {'TeamNum': 22871, 'OPR': 20.247, 'Auto': 7.703, 'CCWM': -30.448, 'TeamName': 'Rox-Paper-Scissors'}, {'TeamNum': 7193, 'OPR': 15.172, 'Auto': 2.919, 'CCWM': -49.284, 'TeamName': 'South Spencer High School'}, {'TeamNum': 22132, 'OPR': 9.919, 'Auto': -0.466, 'CCWM': -19.735, 'TeamName': 'Gearserkers'}]
i 997
{'6547', '9808', '21677', '20181', '14213', '22325', '22363', '11908', '10173', '9034', '5422', '21392', '17210', '21536', '20391', '11457', '9103', '9102', '14995', '16225', '14959', '19996', '21692', '7095', '14919', '18415'}
[{'TeamNum': 20181, 'OPR': 97.549, 'Auto': 26.015, 'CCWM': 33.966, 'TeamName': 'Shawnee Mission East Robotics'}, {'TeamNum': 6547, 'OPR': 80.957, 'Auto': 12.069, 'CCWM': 36.885, 'TeamName': 'Cobalt Colts'}, {'TeamNum': 9102, 'OPR': 77.07, 'Auto': 15.057, 'CCWM': 49.097, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 22325, 'OPR': 75.572, 'Auto': 11.502, 'CCWM': 33.956, 'TeamName': 'SEK Robotics'}, {'TeamNum': 9103, 'OPR': 68.093, 'Auto': 20.637, 'CCWM': 35.314, 'TeamName': 'Ravonics Rover'}, {'TeamNum': 9808, 'OPR': 66.305, 'Auto': 12.492, 'CCWM': 47.675, 'TeamName': 'Team Chargers'}, {'TeamNum': 10173, 'OPR': 65.858, 'Auto': 8.06, 'CCWM': -3.152, 'TeamName': 'Ravonics Gemini'}, {'TeamNum': 20391, 'OPR': 64.687, 'Auto': 23.988, 'CCWM': 25.522, 'TeamName': 'Tungsten Tigers'}, {'TeamNum': 21677, 'OPR': 61.456, 'Auto': 15.299, 'CCWM': 5.169, 'TeamName': 'CTEC Cerberus'}, {'TeamNum': 22363, 'OPR': 55.644, 'Auto': 14.392, 'CCWM': 21.035, 'TeamName': 'Patton Junior High 1'}, {'TeamNum': 19996, 'OPR': 53.358, 'Auto': 17.013, 'CCWM': 17.044, 'TeamName': 'Viking Robotics'}, {'TeamNum': 9034, 'OPR': 50.457, 'Auto': 22.941, 'CCWM': 19.573, 'TeamName': 'Mustangs '}, {'TeamNum': 14213, 'OPR': 45.055, 'Auto': 3.673, 'CCWM': -7.02, 'TeamName': 'Nighthawks'}, {'TeamNum': 21536, 'OPR': 36.253, 'Auto': 7.366, 'CCWM': -13.496, 'TeamName': 'Team Stealth'}, {'TeamNum': 5422, 'OPR': 35.98, 'Auto': 7.465, 'CCWM': 26.484, 'TeamName': 'Quioxte'}, {'TeamNum': 11908, 'OPR': 28.448, 'Auto': 5.25, 'CCWM': 5.469, 'TeamName': 'GEAR'}, {'TeamNum': 21692, 'OPR': 28.322, 'Auto': -0.636, 'CCWM': -15.459, 'TeamName': 'Shawnee Mission East Robotics Two'}, {'TeamNum': 21392, 'OPR': 28.191, 'Auto': 1.391, 'CCWM': 0.596, 'TeamName': 'ION Cats'}, {'TeamNum': 17210, 'OPR': 24.78, 'Auto': 1.903, 'CCWM': 6.319, 'TeamName': 'Bionic Huskies'}, {'TeamNum': 7095, 'OPR': 22.72, 'Auto': 24.498, 'CCWM': -43.832, 'TeamName': 'S.T.O.R.M.'}, {'TeamNum': 14995, 'OPR': 14.741, 'Auto': -3.75, 'CCWM': -54.74, 'TeamName': 'The Legion'}, {'TeamNum': 11457, 'OPR': 13.772, 'Auto': 2.895, 'CCWM': -40.292, 'TeamName': 'STARbots'}, {'TeamNum': 14919, 'OPR': 7.376, 'Auto': 0.851, 'CCWM': -34.229, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14959, 'OPR': 4.186, 'Auto': -2.212, 'CCWM': -52.045, 'TeamName': 'Steel Wolves'}, {'TeamNum': 18415, 'OPR': -1.09, 'Auto': 0.836, 'CCWM': -61.705, 'TeamName': 'The Hoplites'}, {'TeamNum': 16225, 'OPR': -15.072, 'Auto': -3.159, 'CCWM': -38.136, 'TeamName': 'The Button Bucks'}]
USMOKSKCWLT
[{'TeamNum': 20181, 'OPR': 97.549, 'Auto': 26.015, 'CCWM': 33.966, 'TeamName': 'Shawnee Mission East Robotics'}, {'TeamNum': 6547, 'OPR': 80.957, 'Auto': 12.069, 'CCWM': 36.885, 'TeamName': 'Cobalt Colts'}, {'TeamNum': 9102, 'OPR': 77.07, 'Auto': 15.057, 'CCWM': 49.097, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 22325, 'OPR': 75.572, 'Auto': 11.502, 'CCWM': 33.956, 'TeamName': 'SEK Robotics'}, {'TeamNum': 9103, 'OPR': 68.093, 'Auto': 20.637, 'CCWM': 35.314, 'TeamName': 'Ravonics Rover'}, {'TeamNum': 9808, 'OPR': 66.305, 'Auto': 12.492, 'CCWM': 47.675, 'TeamName': 'Team Chargers'}, {'TeamNum': 10173, 'OPR': 65.858, 'Auto': 8.06, 'CCWM': -3.152, 'TeamName': 'Ravonics Gemini'}, {'TeamNum': 20391, 'OPR': 64.687, 'Auto': 23.988, 'CCWM': 25.522, 'TeamName': 'Tungsten Tigers'}, {'TeamNum': 21677, 'OPR': 61.456, 'Auto': 15.299, 'CCWM': 5.169, 'TeamName': 'CTEC Cerberus'}, {'TeamNum': 22363, 'OPR': 55.644, 'Auto': 14.392, 'CCWM': 21.035, 'TeamName': 'Patton Junior High 1'}, {'TeamNum': 19996, 'OPR': 53.358, 'Auto': 17.013, 'CCWM': 17.044, 'TeamName': 'Viking Robotics'}, {'TeamNum': 9034, 'OPR': 50.457, 'Auto': 22.941, 'CCWM': 19.573, 'TeamName': 'Mustangs '}, {'TeamNum': 14213, 'OPR': 45.055, 'Auto': 3.673, 'CCWM': -7.02, 'TeamName': 'Nighthawks'}, {'TeamNum': 21536, 'OPR': 36.253, 'Auto': 7.366, 'CCWM': -13.496, 'TeamName': 'Team Stealth'}, {'TeamNum': 5422, 'OPR': 35.98, 'Auto': 7.465, 'CCWM': 26.484, 'TeamName': 'Quioxte'}, {'TeamNum': 11908, 'OPR': 28.448, 'Auto': 5.25, 'CCWM': 5.469, 'TeamName': 'GEAR'}, {'TeamNum': 21692, 'OPR': 28.322, 'Auto': -0.636, 'CCWM': -15.459, 'TeamName': 'Shawnee Mission East Robotics Two'}, {'TeamNum': 21392, 'OPR': 28.191, 'Auto': 1.391, 'CCWM': 0.596, 'TeamName': 'ION Cats'}, {'TeamNum': 17210, 'OPR': 24.78, 'Auto': 1.903, 'CCWM': 6.319, 'TeamName': 'Bionic Huskies'}, {'TeamNum': 7095, 'OPR': 22.72, 'Auto': 24.498, 'CCWM': -43.832, 'TeamName': 'S.T.O.R.M.'}, {'TeamNum': 14995, 'OPR': 14.741, 'Auto': -3.75, 'CCWM': -54.74, 'TeamName': 'The Legion'}, {'TeamNum': 11457, 'OPR': 13.772, 'Auto': 2.895, 'CCWM': -40.292, 'TeamName': 'STARbots'}, {'TeamNum': 14919, 'OPR': 7.376, 'Auto': 0.851, 'CCWM': -34.229, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14959, 'OPR': 4.186, 'Auto': -2.212, 'CCWM': -52.045, 'TeamName': 'Steel Wolves'}, {'TeamNum': 18415, 'OPR': -1.09, 'Auto': 0.836, 'CCWM': -61.705, 'TeamName': 'The Hoplites'}, {'TeamNum': 16225, 'OPR': -15.072, 'Auto': -3.159, 'CCWM': -38.136, 'TeamName': 'The Button Bucks'}]
i 998

{'7209', '18834', '20694', '11225', '4537', '19841', '14709', '14727', '10464', '8417', '5040', '18865', '6133', '22778', '21623', '8719', '19989', '7842', '4444', '22502', '18208', '11582', '19228', '16515'}
[{'TeamNum': 5040, 'OPR': 127.787, 'Auto': 14.876, 'CCWM': 114.389, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 6133, 'OPR': 122.467, 'Auto': 36.082, 'CCWM': 59.38, 'TeamName': 'The "NUTS!"'}, {'TeamNum': 11225, 'OPR': 96.646, 'Auto': 18.282, 'CCWM': 84.304, 'TeamName': 'DELTA Robotics (Louisville Collegiate School)'}, {'TeamNum': 8719, 'OPR': 92.291, 'Auto': 13.135, 'CCWM': 40.155, 'TeamName': 'Quantum Leap'}, {'TeamNum': 20694, 'OPR': 85.926, 'Auto': 21.693, 'CCWM': 46.381, 'TeamName': 'Craft Coalition '}, {'TeamNum': 7842, 'OPR': 69.199, 'Auto': 21.033, 'CCWM': -2.355, 'TeamName': 'Browncoats'}, {'TeamNum': 7209, 'OPR': 58.484, 'Auto': 15.373, 'CCWM': -18.629, 'TeamName': 'Tech Hogs Robotics  '}, {'TeamNum': 18865, 'OPR': 56.251, 'Auto': 22.206, 'CCWM': 24.986, 'TeamName': 'Will of the Machine '}, {'TeamNum': 10464, 'OPR': 55.227, 'Auto': 11.696, 'CCWM': 12.99, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 19841, 'OPR': 51.578, 'Auto': -3.419, 'CCWM': -50.668, 'TeamName': 'RAMbotics'}, {'TeamNum': 4537, 'OPR': 50.699, 'Auto': 23.069, 'CCWM': -45.172, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 8417, 'OPR': 47.825, 'Auto': 7.002, 'CCWM': -13.031, 'TeamName': "'Lectric Legends"}, {'TeamNum': 18208, 'OPR': 46.669, 'Auto': 9.31, 'CCWM': -19.218, 'TeamName': 'Trinity Titans'}, {'TeamNum': 11582, 'OPR': 45.382, 'Auto': 4.865, 'CCWM': -15.865, 'TeamName': 'Franklin-Simpson RoboCats - RED'}, {'TeamNum': 4444, 'OPR': 44.019, 'Auto': 2.339, 'CCWM': 36.098, 'TeamName': 'Whitefield Robocats'}, {'TeamNum': 19989, 'OPR': 40.076, 'Auto': 1.213, 'CCWM': 24.888, 'TeamName': 'Wings of Steel'}, {'TeamNum': 14709, 'OPR': 36.791, 'Auto': 9.143, 'CCWM': -18.333, 'TeamName': 'Augusta Panthers'}, {'TeamNum': 18834, 'OPR': 30.995, 'Auto': 4.142, 'CCWM': 27.937, 'TeamName': 'Franklin Simpson RoboCats - BLUE'}, {'TeamNum': 16515, 'OPR': 26.893, 'Auto': -3.514, 'CCWM': -65.655, 'TeamName': 'Greenwood High School 1'}, {'TeamNum': 22778, 'OPR': 17.245, 'Auto': 1.591, 'CCWM': -26.605, 'TeamName': 'Portland Christian Robotics'}, {'TeamNum': 19228, 'OPR': 16.272, 'Auto': 1.689, 'CCWM': -12.894, 'TeamName': 'Dragons'}, {'TeamNum': 14727, 'OPR': 15.999, 'Auto': 4.45, 'CCWM': -49.16, 'TeamName': 'Mind of the Machine '}, {'TeamNum': 21623, 'OPR': 9.918, 'Auto': -7.89, 'CCWM': -20.204, 'TeamName': 'Failing Formally'}, {'TeamNum': 22502, 'OPR': 4.159, 'Auto': 10.232, 'CCWM': -113.718, 'TeamName': 'Heart of The Machine'}]
USKYCMP
[{'TeamNum': 5040, 'OPR': 127.787, 'Auto': 14.876, 'CCWM': 114.389, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 6133, 'OPR': 122.467, 'Auto': 36.082, 'CCWM': 59.38, 'TeamName': 'The "NUTS!"'}, {'TeamNum': 11225, 'OPR': 96.646, 'Auto': 18.282, 'CCWM': 84.304, 'TeamName': 'DELTA Robotics (Louisville Collegiate School)'}, {'TeamNum': 8719, 'OPR': 92.291, 'Auto': 13.135, 'CCWM': 40.155, 'TeamName': 'Quantum Leap'}, {'TeamNum': 20694, 'OPR': 85.926, 'Auto': 21.693, 'CCWM': 46.381, 'TeamName': 'Craft Coalition '}, {'TeamNum': 7842, 'OPR': 69.199, 'Auto': 21.033, 'CCWM': -2.355, 'TeamName': 'Browncoats'}, {'TeamNum': 7209, 'OPR': 58.484, 'Auto': 15.373, 'CCWM': -18.629, 'TeamName': 'Tech Hogs Robotics  '}, {'TeamNum': 18865, 'OPR': 56.251, 'Auto': 22.206, 'CCWM': 24.986, 'TeamName': 'Will of the Machine '}, {'TeamNum': 10464, 'OPR': 55.227, 'Auto': 11.696, 'CCWM': 12.99, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 19841, 'OPR': 51.578, 'Auto': -3.419, 'CCWM': -50.668, 'TeamName': 'RAMbotics'}, {'TeamNum': 4537, 'OPR': 50.699, 'Auto': 23.069, 'CCWM': -45.172, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 8417, 'OPR': 47.825, 'Auto': 7.002, 'CCWM': -13.031, 'TeamName': "'Lectric Legends"}, {'TeamNum': 18208, 'OPR': 46.669, 'Auto': 9.31, 'CCWM': -19.218, 'TeamName': 'Trinity Titans'}, {'TeamNum': 11582, 'OPR': 45.382, 'Auto': 4.865, 'CCWM': -15.865, 'TeamName': 'Franklin-Simpson RoboCats - RED'}, {'TeamNum': 4444, 'OPR': 44.019, 'Auto': 2.339, 'CCWM': 36.098, 'TeamName': 'Whitefield Robocats'}, {'TeamNum': 19989, 'OPR': 40.076, 'Auto': 1.213, 'CCWM': 24.888, 'TeamName': 'Wings of Steel'}, {'TeamNum': 14709, 'OPR': 36.791, 'Auto': 9.143, 'CCWM': -18.333, 'TeamName': 'Augusta Panthers'}, {'TeamNum': 18834, 'OPR': 30.995, 'Auto': 4.142, 'CCWM': 27.937, 'TeamName': 'Franklin Simpson RoboCats - BLUE'}, {'TeamNum': 16515, 'OPR': 26.893, 'Auto': -3.514, 'CCWM': -65.655, 'TeamName': 'Greenwood High School 1'}, {'TeamNum': 22778, 'OPR': 17.245, 'Auto': 1.591, 'CCWM': -26.605, 'TeamName': 'Portland Christian Robotics'}, {'TeamNum': 19228, 'OPR': 16.272, 'Auto': 1.689, 'CCWM': -12.894, 'TeamName': 'Dragons'}, {'TeamNum': 14727, 'OPR': 15.999, 'Auto': 4.45, 'CCWM': -49.16, 'TeamName': 'Mind of the Machine '}, {'TeamNum': 21623, 'OPR': 9.918, 'Auto': -7.89, 'CCWM': -20.204, 'TeamName': 'Failing Formally'}, {'TeamNum': 22502, 'OPR': 4.159, 'Auto': 10.232, 'CCWM': -113.718, 'TeamName': 'Heart of The Machine'}]
i 999
{'20748', '5710', '9006', '17218', '18754', '22039', '12195', '15626', '13534', '14853', '15089', '22489'}
[{'TeamNum': 18754, 'OPR': 99.142, 'Auto': 23.732, 'CCWM': 67.372, 'TeamName': 'Galactic Narwhal Chicken Effect (GNCE)'}, {'TeamNum': 9006, 'OPR': 83.669, 'Auto': 17.676, 'CCWM': 53.113, 'TeamName': 'Austin Prep Crusaders'}, {'TeamNum': 22489, 'OPR': 68.598, 'Auto': 13.22, 'CCWM': 41.383, 'TeamName': 'Galactic Narwhal Chicken Effect - Diamond'}, {'TeamNum': 20748, 'OPR': 56.915, 'Auto': 21.626, 'CCWM': 22.056, 'TeamName': 'Nobles'}, {'TeamNum': 15089, 'OPR': 50.543, 'Auto': 20.461, 'CCWM': -1.641, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 5710, 'OPR': 37.149, 'Auto': 4.173, 'CCWM': 14.395, 'TeamName': 'Titans'}, {'TeamNum': 15626, 'OPR': 32.675, 'Auto': 6.536, 'CCWM': -17.364, 'TeamName': 'A Perplexing Solution'}, {'TeamNum': 13534, 'OPR': 28.378, 'Auto': 4.734, 'CCWM': 1.012, 'TeamName': 'Robots in Plaid'}, {'TeamNum': 12195, 'OPR': 25.33, 'Auto': -3.02, 'CCWM': -17.062, 'TeamName': 'Hawkbots'}, {'TeamNum': 14853, 'OPR': 21.155, 'Auto': 7.881, 'CCWM': -38.767, 'TeamName': 'Aquabots'}, {'TeamNum': 17218, 'OPR': 8.072, 'Auto': 2.923, 'CCWM': -53.958, 'TeamName': 'Brookline Bots'}, {'TeamNum': 22039, 'OPR': 6.375, 'Auto': 1.892, 'CCWM': -70.539, 'TeamName': 'One-cone two-cone red-cone blue-cone'}]
USMAANQ2
[{'TeamNum': 18754, 'OPR': 99.142, 'Auto': 23.732, 'CCWM': 67.372, 'TeamName': 'Galactic Narwhal Chicken Effect (GNCE)'}, {'TeamNum': 9006, 'OPR': 83.669, 'Auto': 17.676, 'CCWM': 53.113, 'TeamName': 'Austin Prep Crusaders'}, {'TeamNum': 22489, 'OPR': 68.598, 'Auto': 13.22, 'CCWM': 41.383, 'TeamName': 'Galactic Narwhal Chicken Effect - Diamond'}, {'TeamNum': 20748, 'OPR': 56.915, 'Auto': 21.626, 'CCWM': 22.056, 'TeamName': 'Nobles'}, {'TeamNum': 15089, 'OPR': 50.543, 'Auto': 20.461, 'CCWM': -1.641, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 5710, 'OPR': 37.149, 'Auto': 4.173, 'CCWM': 14.395, 'TeamName': 'Titans'}, {'TeamNum': 15626, 'OPR': 32.675, 'Auto': 6.536, 'CCWM': -17.364, 'TeamName': 'A Perplexing Solution'}, {'TeamNum': 13534, 'OPR': 28.378, 'Auto': 4.734, 'CCWM': 1.012, 'TeamName': 'Robots in Plaid'}, {'TeamNum': 12195, 'OPR': 25.33, 'Auto': -3.02, 'CCWM': -17.062, 'TeamName': 'Hawkbots'}, {'TeamNum': 14853, 'OPR': 21.155, 'Auto': 7.881, 'CCWM': -38.767, 'TeamName': 'Aquabots'}, {'TeamNum': 17218, 'OPR': 8.072, 'Auto': 2.923, 'CCWM': -53.958, 'TeamName': 'Brookline Bots'}, {'TeamNum': 22039, 'OPR': 6.375, 'Auto': 1.892, 'CCWM': -70.539, 'TeamName': 'One-cone two-cone red-cone blue-cone'}]
i 1000
{'22059', '12589', '4096', '3737', '17298', '21968', '16021', '5897', '13406', '5436', '11359', '16704', '7571', '18925', '9326', '11460', '6055', '17142', '19667', '15202', '21236'}
[{'TeamNum': 13406, 'OPR': 116.579, 'Auto': 35.946, 'CCWM': 77.668, 'TeamName': 'Consistently Inconsistent'}, {'TeamNum': 7571, 'OPR': 82.628, 'Auto': 11.815, 'CCWM': 57.214, 'TeamName': 'Alumineers'}, {'TeamNum': 12589, 'OPR': 80.685, 'Auto': -1.184, 'CCWM': 68.04, 'TeamName': 'Pioneer Robotics'}, {'TeamNum': 16021, 'OPR': 65.354, 'Auto': 17.243, 'CCWM': 25.731, 'TeamName': 'Techno Maniacs '}, {'TeamNum': 22059, 'OPR': 58.321, 'Auto': 14.567, 'CCWM': 31.496, 'TeamName': 'Overclocked'}, {'TeamNum': 19667, 'OPR': 56.873, 'Auto': 8.893, 'CCWM': 12.048, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 16704, 'OPR': 47.432, 'Auto': 17.663, 'CCWM': 30.479, 'TeamName': 'Nano Hornets'}, {'TeamNum': 15202, 'OPR': 43.866, 'Auto': 18.164, 'CCWM': 1.293, 'TeamName': 'The Middle Dippers'}, {'TeamNum': 11460, 'OPR': 41.975, 'Auto': 8.252, 'CCWM': -7.714, 'TeamName': 'Sliced Breadboards'}, {'TeamNum': 4096, 'OPR': 39.009, 'Auto': 4.505, 'CCWM': -6.73, 'TeamName': 'T-10   ("T minus Ten")'}, {'TeamNum': 6055, 'OPR': 38.944, 'Auto': 12.661, 'CCWM': 5.868, 'TeamName': 'GearTicks'}, {'TeamNum': 18925, 'OPR': 37.434, 'Auto': 5.762, 'CCWM': 24.916, 'TeamName': 'Hivemind'}, {'TeamNum': 5436, 'OPR': 36.742, 'Auto': 10.168, 'CCWM': -42.489, 'TeamName': 'Aluminum Cobblers'}, {'TeamNum': 21236, 'OPR': 34.792, 'Auto': 2.805, 'CCWM': -58.269, 'TeamName': 'Gator Growbotics'}, {'TeamNum': 5897, 'OPR': 34.266, 'Auto': 11.939, 'CCWM': 0.352, 'TeamName': 'HackHers'}, {'TeamNum': 21968, 'OPR': 33.106, 'Auto': 9.911, 'CCWM': -22.876, 'TeamName': 'The Marvels of Worcester'}, {'TeamNum': 9326, 'OPR': 29.376, 'Auto': 6.75, 'CCWM': -35.892, 'TeamName': 'Liquid Oxygen'}, {'TeamNum': 17298, 'OPR': 16.817, 'Auto': 5.102, 'CCWM': -20.18, 'TeamName': 'Astrobots'}, {'TeamNum': 3737, 'OPR': 14.791, 'Auto': 5.437, 'CCWM': -34.496, 'TeamName': "Hank's Tanks"}, {'TeamNum': 17142, 'OPR': 5.903, 'Auto': 1.576, 'CCWM': -53.925, 'TeamName': "St Bernard's"}, {'TeamNum': 11359, 'OPR': 3.633, 'Auto': -0.501, 'CCWM': -53.256, 'TeamName': 'Technicality'}]
USMAANQ
[{'TeamNum': 13406, 'OPR': 116.579, 'Auto': 35.946, 'CCWM': 77.668, 'TeamName': 'Consistently Inconsistent'}, {'TeamNum': 7571, 'OPR': 82.628, 'Auto': 11.815, 'CCWM': 57.214, 'TeamName': 'Alumineers'}, {'TeamNum': 12589, 'OPR': 80.685, 'Auto': -1.184, 'CCWM': 68.04, 'TeamName': 'Pioneer Robotics'}, {'TeamNum': 16021, 'OPR': 65.354, 'Auto': 17.243, 'CCWM': 25.731, 'TeamName': 'Techno Maniacs '}, {'TeamNum': 22059, 'OPR': 58.321, 'Auto': 14.567, 'CCWM': 31.496, 'TeamName': 'Overclocked'}, {'TeamNum': 19667, 'OPR': 56.873, 'Auto': 8.893, 'CCWM': 12.048, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 16704, 'OPR': 47.432, 'Auto': 17.663, 'CCWM': 30.479, 'TeamName': 'Nano Hornets'}, {'TeamNum': 15202, 'OPR': 43.866, 'Auto': 18.164, 'CCWM': 1.293, 'TeamName': 'The Middle Dippers'}, {'TeamNum': 11460, 'OPR': 41.975, 'Auto': 8.252, 'CCWM': -7.714, 'TeamName': 'Sliced Breadboards'}, {'TeamNum': 4096, 'OPR': 39.009, 'Auto': 4.505, 'CCWM': -6.73, 'TeamName': 'T-10   ("T minus Ten")'}, {'TeamNum': 6055, 'OPR': 38.944, 'Auto': 12.661, 'CCWM': 5.868, 'TeamName': 'GearTicks'}, {'TeamNum': 18925, 'OPR': 37.434, 'Auto': 5.762, 'CCWM': 24.916, 'TeamName': 'Hivemind'}, {'TeamNum': 5436, 'OPR': 36.742, 'Auto': 10.168, 'CCWM': -42.489, 'TeamName': 'Aluminum Cobblers'}, {'TeamNum': 21236, 'OPR': 34.792, 'Auto': 2.805, 'CCWM': -58.269, 'TeamName': 'Gator Growbotics'}, {'TeamNum': 5897, 'OPR': 34.266, 'Auto': 11.939, 'CCWM': 0.352, 'TeamName': 'HackHers'}, {'TeamNum': 21968, 'OPR': 33.106, 'Auto': 9.911, 'CCWM': -22.876, 'TeamName': 'The Marvels of Worcester'}, {'TeamNum': 9326, 'OPR': 29.376, 'Auto': 6.75, 'CCWM': -35.892, 'TeamName': 'Liquid Oxygen'}, {'TeamNum': 17298, 'OPR': 16.817, 'Auto': 5.102, 'CCWM': -20.18, 'TeamName': 'Astrobots'}, {'TeamNum': 3737, 'OPR': 14.791, 'Auto': 5.437, 'CCWM': -34.496, 'TeamName': "Hank's Tanks"}, {'TeamNum': 17142, 'OPR': 5.903, 'Auto': 1.576, 'CCWM': -53.925, 'TeamName': "St Bernard's"}, {'TeamNum': 11359, 'OPR': 3.633, 'Auto': -0.501, 'CCWM': -53.256, 'TeamName': 'Technicality'}]

i 1001
i 1002
i 1003
{'16498', '3592', '10265', '10106', '19448', '3505', '19838', '7951', '406', '12427', '5439', '9905', '5155', '11191', '10588', '14867', '5248', '11203', '6387', '5095', '3591', '3658', '18118', '5118', '5119'}
[{'TeamNum': 3658, 'OPR': 114.49, 'Auto': 33.539, 'CCWM': 70.4, 'TeamName': 'The BOSONS'}, {'TeamNum': 7951, 'OPR': 99.711, 'Auto': 16.512, 'CCWM': 78.835, 'TeamName': 'The KAONS'}, {'TeamNum': 16498, 'OPR': 91.548, 'Auto': 21.533, 'CCWM': 33.638, 'TeamName': 'Plus Gang'}, {'TeamNum': 19448, 'OPR': 84.392, 'Auto': 20.474, 'CCWM': 27.823, 'TeamName': 'X BOTS'}, {'TeamNum': 10265, 'OPR': 83.7, 'Auto': 23.782, 'CCWM': 15.951, 'TeamName': 'Force Green'}, {'TeamNum': 10588, 'OPR': 68.436, 'Auto': 13.087, 'CCWM': 4.874, 'TeamName': 'The LUXONS'}, {'TeamNum': 5439, 'OPR': 62.58, 'Auto': 10.61, 'CCWM': 11.507, 'TeamName': 'The GLUONS'}, {'TeamNum': 9905, 'OPR': 62.117, 'Auto': 16.248, 'CCWM': 4.931, 'TeamName': 'Rampire'}, {'TeamNum': 14867, 'OPR': 61.448, 'Auto': 21.049, 'CCWM': 25.804, 'TeamName': 'Cougar Bots'}, {'TeamNum': 5119, 'OPR': 60.835, 'Auto': 16.725, 'CCWM': 9.787, 'TeamName': 'The BARYONS'}, {'TeamNum': 5095, 'OPR': 56.506, 'Auto': 14.15, 'CCWM': 23.987, 'TeamName': 'The LEPTONS'}, {'TeamNum': 3505, 'OPR': 47.625, 'Auto': 2.101, 'CCWM': -11.536, 'TeamName': 'Cadet Bot Crew'}, {'TeamNum': 406, 'OPR': 45.479, 'Auto': 12.953, 'CCWM': -23.501, 'TeamName': "Boulson's Revenge"}, {'TeamNum': 19838, 'OPR': 45.413, 'Auto': 17.214, 'CCWM': -36.662, 'TeamName': 'Brute Force'}, {'TeamNum': 3591, 'OPR': 45.02, 'Auto': 26.211, 'CCWM': 2.905, 'TeamName': 'The QUARKS'}, {'TeamNum': 12427, 'OPR': 37.384, 'Auto': 4.455, 'CCWM': -45.873, 'TeamName': 'Bot of Steel'}, {'TeamNum': 11191, 'OPR': 36.491, 'Auto': 13.007, 'CCWM': -4.796, 'TeamName': 'Red Vectors'}, {'TeamNum': 10106, 'OPR': 35.607, 'Auto': 2.681, 'CCWM': -27.396, 'TeamName': 'CBC Robotics'}, {'TeamNum': 5118, 'OPR': 35.554, 'Auto': 7.749, 'CCWM': -7.607, 'TeamName': 'The HADRONS'}, {'TeamNum': 18118, 'OPR': 33.152, 'Auto': 16.113, 'CCWM': -39.889, 'TeamName': 'Mindstorm Troopers'}, {'TeamNum': 5155, 'OPR': 31.799, 'Auto': 6.571, 'CCWM': -33.16, 'TeamName': 'Ramifications'}, {'TeamNum': 6387, 'OPR': 30.502, 'Auto': -4.243, 'CCWM': -18.152, 'TeamName': 'Brobots'}, {'TeamNum': 3592, 'OPR': 26.783, 'Auto': 6.101, 'CCWM': -18.902, 'TeamName': 'The MESONS'}, {'TeamNum': 11203, 'OPR': 21.051, 'Auto': 0.903, 'CCWM': -20.446, 'TeamName': 'DURT (DeSmet Ultimate Robotics Team)'}, {'TeamNum': 5248, 'OPR': 17.672, 'Auto': -0.801, 'CCWM': -17.808, 'TeamName': 'The FERMIONS'}]
USMOKSSTLMLT
[{'TeamNum': 3658, 'OPR': 114.49, 'Auto': 33.539, 'CCWM': 70.4, 'TeamName': 'The BOSONS'}, {'TeamNum': 7951, 'OPR': 99.711, 'Auto': 16.512, 'CCWM': 78.835, 'TeamName': 'The KAONS'}, {'TeamNum': 16498, 'OPR': 91.548, 'Auto': 21.533, 'CCWM': 33.638, 'TeamName': 'Plus Gang'}, {'TeamNum': 19448, 'OPR': 84.392, 'Auto': 20.474, 'CCWM': 27.823, 'TeamName': 'X BOTS'}, {'TeamNum': 10265, 'OPR': 83.7, 'Auto': 23.782, 'CCWM': 15.951, 'TeamName': 'Force Green'}, {'TeamNum': 10588, 'OPR': 68.436, 'Auto': 13.087, 'CCWM': 4.874, 'TeamName': 'The LUXONS'}, {'TeamNum': 5439, 'OPR': 62.58, 'Auto': 10.61, 'CCWM': 11.507, 'TeamName': 'The GLUONS'}, {'TeamNum': 9905, 'OPR': 62.117, 'Auto': 16.248, 'CCWM': 4.931, 'TeamName': 'Rampire'}, {'TeamNum': 14867, 'OPR': 61.448, 'Auto': 21.049, 'CCWM': 25.804, 'TeamName': 'Cougar Bots'}, {'TeamNum': 5119, 'OPR': 60.835, 'Auto': 16.725, 'CCWM': 9.787, 'TeamName': 'The BARYONS'}, {'TeamNum': 5095, 'OPR': 56.506, 'Auto': 14.15, 'CCWM': 23.987, 'TeamName': 'The LEPTONS'}, {'TeamNum': 3505, 'OPR': 47.625, 'Auto': 2.101, 'CCWM': -11.536, 'TeamName': 'Cadet Bot Crew'}, {'TeamNum': 406, 'OPR': 45.479, 'Auto': 12.953, 'CCWM': -23.501, 'TeamName': "Boulson's Revenge"}, {'TeamNum': 19838, 'OPR': 45.413, 'Auto': 17.214, 'CCWM': -36.662, 'TeamName': 'Brute Force'}, {'TeamNum': 3591, 'OPR': 45.02, 'Auto': 26.211, 'CCWM': 2.905, 'TeamName': 'The QUARKS'}, {'TeamNum': 12427, 'OPR': 37.384, 'Auto': 4.455, 'CCWM': -45.873, 'TeamName': 'Bot of Steel'}, {'TeamNum': 11191, 'OPR': 36.491, 'Auto': 13.007, 'CCWM': -4.796, 'TeamName': 'Red Vectors'}, {'TeamNum': 10106, 'OPR': 35.607, 'Auto': 2.681, 'CCWM': -27.396, 'TeamName': 'CBC Robotics'}, {'TeamNum': 5118, 'OPR': 35.554, 'Auto': 7.749, 'CCWM': -7.607, 'TeamName': 'The HADRONS'}, {'TeamNum': 18118, 'OPR': 33.152, 'Auto': 16.113, 'CCWM': -39.889, 'TeamName': 'Mindstorm Troopers'}, {'TeamNum': 5155, 'OPR': 31.799, 'Auto': 6.571, 'CCWM': -33.16, 'TeamName': 'Ramifications'}, {'TeamNum': 6387, 'OPR': 30.502, 'Auto': -4.243, 'CCWM': -18.152, 'TeamName': 'Brobots'}, {'TeamNum': 3592, 'OPR': 26.783, 'Auto': 6.101, 'CCWM': -18.902, 'TeamName': 'The MESONS'}, {'TeamNum': 11203, 'OPR': 21.051, 'Auto': 0.903, 'CCWM': -20.446, 'TeamName': 'DURT (DeSmet Ultimate Robotics Team)'}, {'TeamNum': 5248, 'OPR': 17.672, 'Auto': -0.801, 'CCWM': -17.808, 'TeamName': 'The FERMIONS'}]
i 1004
{'6205', '6273', '13176', '22426', '9298', '12389', '21585', '12390', '18364', '14236', '16489', '14627', '18370', '19795', '6556'}
[{'TeamNum': 14627, 'OPR': 94.973, 'Auto': 23.144, 'CCWM': 58.464, 'TeamName': 'Spare Parts'}, {'TeamNum': 14236, 'OPR': 92.104, 'Auto': 16.965, 'CCWM': 39.678, 'TeamName': 'Slight Malfunction'}, {'TeamNum': 16489, 'OPR': 90.065, 'Auto': 24.228, 'CCWM': 52.521, 'TeamName': 'Virtual North'}, {'TeamNum': 6273, 'OPR': 83.912, 'Auto': 8.425, 'CCWM': 50.025, 'TeamName': 'Technocats'}, {'TeamNum': 12390, 'OPR': 83.782, 'Auto': 20.502, 'CCWM': 42.328, 'TeamName': 'The Robotic Raiders'}, {'TeamNum': 12389, 'OPR': 55.434, 'Auto': 14.215, 'CCWM': 12.697, 'TeamName': 'TMS Tornadoes'}, {'TeamNum': 6556, 'OPR': 51.47, 'Auto': 2.174, 'CCWM': 8.887, 'TeamName': 'Tempest'}, {'TeamNum': 19795, 'OPR': 27.129, 'Auto': -0.935, 'CCWM': -38.162, 'TeamName': 'Rockbotics'}, {'TeamNum': 13176, 'OPR': 26.456, 'Auto': 3.799, 'CCWM': -7.564, 'TeamName': 'Spark-O-Matic Robotics & Digital Arts'}, {'TeamNum': 21585, 'OPR': 23.43, 'Auto': -0.711, 'CCWM': -24.916, 'TeamName': 'Irish Storm'}, {'TeamNum': 18364, 'OPR': 22.011, 'Auto': 2.865, 'CCWM': -12.161, 'TeamName': 'The Bravo Seals'}, {'TeamNum': 22426, 'OPR': 15.999, 'Auto': -2.675, 'CCWM': -9.198, 'TeamName': 'Gigabiters'}, {'TeamNum': 6205, 'OPR': 15.874, 'Auto': 5.139, 'CCWM': -69.299, 'TeamName': 'SCARLET'}, {'TeamNum': 9298, 'OPR': 1.664, 'Auto': -3.916, 'CCWM': -42.338, 'TeamName': 'Bionic Cobras'}, {'TeamNum': 18370, 'OPR': -12.335, 'Auto': -5.436, 'CCWM': -63.356, 'TeamName': "Can't Stop Won't Stop"}]
USMSLAQ6
[{'TeamNum': 14627, 'OPR': 94.973, 'Auto': 23.144, 'CCWM': 58.464, 'TeamName': 'Spare Parts'}, {'TeamNum': 14236, 'OPR': 92.104, 'Auto': 16.965, 'CCWM': 39.678, 'TeamName': 'Slight Malfunction'}, {'TeamNum': 16489, 'OPR': 90.065, 'Auto': 24.228, 'CCWM': 52.521, 'TeamName': 'Virtual North'}, {'TeamNum': 6273, 'OPR': 83.912, 'Auto': 8.425, 'CCWM': 50.025, 'TeamName': 'Technocats'}, {'TeamNum': 12390, 'OPR': 83.782, 'Auto': 20.502, 'CCWM': 42.328, 'TeamName': 'The Robotic Raiders'}, {'TeamNum': 12389, 'OPR': 55.434, 'Auto': 14.215, 'CCWM': 12.697, 'TeamName': 'TMS Tornadoes'}, {'TeamNum': 6556, 'OPR': 51.47, 'Auto': 2.174, 'CCWM': 8.887, 'TeamName': 'Tempest'}, {'TeamNum': 19795, 'OPR': 27.129, 'Auto': -0.935, 'CCWM': -38.162, 'TeamName': 'Rockbotics'}, {'TeamNum': 13176, 'OPR': 26.456, 'Auto': 3.799, 'CCWM': -7.564, 'TeamName': 'Spark-O-Matic Robotics & Digital Arts'}, {'TeamNum': 21585, 'OPR': 23.43, 'Auto': -0.711, 'CCWM': -24.916, 'TeamName': 'Irish Storm'}, {'TeamNum': 18364, 'OPR': 22.011, 'Auto': 2.865, 'CCWM': -12.161, 'TeamName': 'The Bravo Seals'}, {'TeamNum': 22426, 'OPR': 15.999, 'Auto': -2.675, 'CCWM': -9.198, 'TeamName': 'Gigabiters'}, {'TeamNum': 6205, 'OPR': 15.874, 'Auto': 5.139, 'CCWM': -69.299, 'TeamName': 'SCARLET'}, {'TeamNum': 9298, 'OPR': 1.664, 'Auto': -3.916, 'CCWM': -42.338, 'TeamName': 'Bionic Cobras'}, {'TeamNum': 18370, 'OPR': -12.335, 'Auto': -5.436, 'CCWM': -63.356, 'TeamName': "Can't Stop Won't Stop"}]
i 1005
{'22348', '12488', '19735', '20244', '3944', '11241', '21852', '10975', '16102', '6934', '12866', '13115', '4936', '22261', '17653', '12365', '19772', '16139', '11166', '11871'}
[{'TeamNum': 11166, 'OPR': 103.892, 'Auto': 25.545, 'CCWM': 74.672, 'TeamName': 'Big Red Robotics'}, {'TeamNum': 12488, 'OPR': 82.193, 'Auto': 16.54, 'CCWM': 51.626, 'TeamName': 'Raidiators'}, {'TeamNum': 16139, 'OPR': 79.495, 'Auto': 15.022, 'CCWM': 24.644, 'TeamName': 'The Martians'}, {'TeamNum': 22348, 'OPR': 70.787, 'Auto': 15.033, 'CCWM': 6.955, 'TeamName': 'REAPR'}, {'TeamNum': 16102, 'OPR': 58.677, 'Auto': 19.673, 'CCWM': 57.486, 'TeamName': 'The Short Circuits'}, {'TeamNum': 19735, 'OPR': 55.792, 'Auto': 24.078, 'CCWM': 32.981, 'TeamName': 'Hornet Silver'}, {'TeamNum': 19772, 'OPR': 48.394, 'Auto': 20.305, 'CCWM': 2.794, 'TeamName': 'Rust in Piece'}, {'TeamNum': 6934, 'OPR': 45.017, 'Auto': 10.34, 'CCWM': 23.581, 'TeamName': 'The TranSisters'}, {'TeamNum': 11871, 'OPR': 39.857, 'Auto': 13.268, 'CCWM': -9.46, 'TeamName': 'Voltron'}, {'TeamNum': 10975, 'OPR': 37.646, 'Auto': 14.144, 'CCWM': -24.1, 'TeamName': 'Raiders-ShortCircuits'}, {'TeamNum': 22261, 'OPR': 34.406, 'Auto': 7.179, 'CCWM': -2.772, 'TeamName': 'Hornet Blue'}, {'TeamNum': 12365, 'OPR': 32.444, 'Auto': 18.819, 'CCWM': 23.078, 'TeamName': 'MATES Robotics'}, {'TeamNum': 11241, 'OPR': 29.417, 'Auto': 16.882, 'CCWM': -40.534, 'TeamName': 'Blue Steel'}, {'TeamNum': 21852, 'OPR': 25.374, 'Auto': 9.608, 'CCWM': -52.344, 'TeamName': 'I swear it worked last night'}, {'TeamNum': 20244, 'OPR': 17.247, 'Auto': -3.968, 'CCWM': -12.489, 'TeamName': 'Liberty Lions'}, {'TeamNum': 12866, 'OPR': 8.959, 'Auto': -1.262, 'CCWM': -14.481, 'TeamName': 'Cyber-Fins'}, {'TeamNum': 3944, 'OPR': 7.918, 'Auto': 2.309, 'CCWM': -37.315, 'TeamName': 'Team Mercury'}, {'TeamNum': 4936, 'OPR': 4.634, 'Auto': 3.18, 'CCWM': -35.433, 'TeamName': 'Sparks'}, {'TeamNum': 17653, 'OPR': -1.931, 'Auto': -4.704, 'CCWM': -27.545, 'TeamName': "Lion's Pride"}, {'TeamNum': 13115, 'OPR': -7.216, 'Auto': -8.592, 'CCWM': -41.346, 'TeamName': 'Brave Robotics'}]
USNJSOLT
[{'TeamNum': 11166, 'OPR': 103.892, 'Auto': 25.545, 'CCWM': 74.672, 'TeamName': 'Big Red Robotics'}, {'TeamNum': 12488, 'OPR': 82.193, 'Auto': 16.54, 'CCWM': 51.626, 'TeamName': 'Raidiators'}, {'TeamNum': 16139, 'OPR': 79.495, 'Auto': 15.022, 'CCWM': 24.644, 'TeamName': 'The Martians'}, {'TeamNum': 22348, 'OPR': 70.787, 'Auto': 15.033, 'CCWM': 6.955, 'TeamName': 'REAPR'}, {'TeamNum': 16102, 'OPR': 58.677, 'Auto': 19.673, 'CCWM': 57.486, 'TeamName': 'The Short Circuits'}, {'TeamNum': 19735, 'OPR': 55.792, 'Auto': 24.078, 'CCWM': 32.981, 'TeamName': 'Hornet Silver'}, {'TeamNum': 19772, 'OPR': 48.394, 'Auto': 20.305, 'CCWM': 2.794, 'TeamName': 'Rust in Piece'}, {'TeamNum': 6934, 'OPR': 45.017, 'Auto': 10.34, 'CCWM': 23.581, 'TeamName': 'The TranSisters'}, {'TeamNum': 11871, 'OPR': 39.857, 'Auto': 13.268, 'CCWM': -9.46, 'TeamName': 'Voltron'}, {'TeamNum': 10975, 'OPR': 37.646, 'Auto': 14.144, 'CCWM': -24.1, 'TeamName': 'Raiders-ShortCircuits'}, {'TeamNum': 22261, 'OPR': 34.406, 'Auto': 7.179, 'CCWM': -2.772, 'TeamName': 'Hornet Blue'}, {'TeamNum': 12365, 'OPR': 32.444, 'Auto': 18.819, 'CCWM': 23.078, 'TeamName': 'MATES Robotics'}, {'TeamNum': 11241, 'OPR': 29.417, 'Auto': 16.882, 'CCWM': -40.534, 'TeamName': 'Blue Steel'}, {'TeamNum': 21852, 'OPR': 25.374, 'Auto': 9.608, 'CCWM': -52.344, 'TeamName': 'I swear it worked last night'}, {'TeamNum': 20244, 'OPR': 17.247, 'Auto': -3.968, 'CCWM': -12.489, 'TeamName': 'Liberty Lions'}, {'TeamNum': 12866, 'OPR': 8.959, 'Auto': -1.262, 'CCWM': -14.481, 'TeamName': 'Cyber-Fins'}, {'TeamNum': 3944, 'OPR': 7.918, 'Auto': 2.309, 'CCWM': -37.315, 'TeamName': 'Team Mercury'}, {'TeamNum': 4936, 'OPR': 4.634, 'Auto': 3.18, 'CCWM': -35.433, 'TeamName': 'Sparks'}, {'TeamNum': 17653, 'OPR': -1.931, 'Auto': -4.704, 'CCWM': -27.545, 'TeamName': "Lion's Pride"}, {'TeamNum': 13115, 'OPR': -7.216, 'Auto': -8.592, 'CCWM': -41.346, 'TeamName': 'Brave Robotics'}]

i 1006
{'18757', '13103', '18758', '8902', '12636', '7026', '247', '15231', '18759', '14450', '13105', '18760', '13107', '11456', '248', '9244', '10243', '11396', '10603', '3777'}
[{'TeamNum': 11456, 'OPR': 72.952, 'Auto': 19.861, 'CCWM': 20.916, 'TeamName': 'Blair Academy'}, {'TeamNum': 13103, 'OPR': 72.543, 'Auto': 16.137, 'CCWM': 50.961, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 7026, 'OPR': 72.491, 'Auto': 18.786, 'CCWM': 30.546, 'TeamName': 'JDroids'}, {'TeamNum': 8902, 'OPR': 66.949, 'Auto': 10.986, 'CCWM': 37.376, 'TeamName': 'Cosmic Goose'}, {'TeamNum': 18758, 'OPR': 64.916, 'Auto': 20.288, 'CCWM': 54.117, 'TeamName': 'Ironmen Sigma'}, {'TeamNum': 18760, 'OPR': 63.251, 'Auto': 24.716, 'CCWM': 26.478, 'TeamName': 'Ironmen Upsilon'}, {'TeamNum': 12636, 'OPR': 61.825, 'Auto': 15.402, 'CCWM': 41.253, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 13105, 'OPR': 53.285, 'Auto': 16.812, 'CCWM': 17.262, 'TeamName': 'Ironmen Omicron'}, {'TeamNum': 10603, 'OPR': 52.866, 'Auto': 6.211, 'CCWM': 0.859, 'TeamName': 'WOOD-CHIPS'}, {'TeamNum': 10243, 'OPR': 48.886, 'Auto': -1.057, 'CCWM': 15.339, 'TeamName': 'Ramsey Ramblers'}, {'TeamNum': 13107, 'OPR': 41.641, 'Auto': 18.165, 'CCWM': -26.826, 'TeamName': 'Ironmen Pi'}, {'TeamNum': 18757, 'OPR': 41.167, 'Auto': 15.168, 'CCWM': -13.49, 'TeamName': 'Ironmen Rho'}, {'TeamNum': 247, 'OPR': 32.892, 'Auto': 21.109, 'CCWM': -1.824, 'TeamName': 'Reboot'}, {'TeamNum': 18759, 'OPR': 29.595, 'Auto': 15.155, 'CCWM': -40.886, 'TeamName': 'Ironmen Tau'}, {'TeamNum': 248, 'OPR': 23.794, 'Auto': 4.407, 'CCWM': -28.089, 'TeamName': 'Fatal Error'}, {'TeamNum': 3777, 'OPR': 23.377, 'Auto': 11.417, 'CCWM': -1.898, 'TeamName': 'Mecha Lion'}, {'TeamNum': 14450, 'OPR': 20.657, 'Auto': 11.911, 'CCWM': -31.5, 'TeamName': 'RoboRebels'}, {'TeamNum': 11396, 'OPR': 4.559, 'Auto': -10.641, 'CCWM': -21.958, 'TeamName': 'ECR Eaglebots'}, {'TeamNum': 9244, 'OPR': 0.217, 'Auto': -11.412, 'CCWM': -63.671, 'TeamName': 'Lenape Valley Robotics'}, {'TeamNum': 15231, 'OPR': -2.264, 'Auto': -2.619, 'CCWM': -64.966, 'TeamName': 'ECR Squared'}]
USNJNOLT
[{'TeamNum': 11456, 'OPR': 72.952, 'Auto': 19.861, 'CCWM': 20.916, 'TeamName': 'Blair Academy'}, {'TeamNum': 13103, 'OPR': 72.543, 'Auto': 16.137, 'CCWM': 50.961, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 7026, 'OPR': 72.491, 'Auto': 18.786, 'CCWM': 30.546, 'TeamName': 'JDroids'}, {'TeamNum': 8902, 'OPR': 66.949, 'Auto': 10.986, 'CCWM': 37.376, 'TeamName': 'Cosmic Goose'}, {'TeamNum': 18758, 'OPR': 64.916, 'Auto': 20.288, 'CCWM': 54.117, 'TeamName': 'Ironmen Sigma'}, {'TeamNum': 18760, 'OPR': 63.251, 'Auto': 24.716, 'CCWM': 26.478, 'TeamName': 'Ironmen Upsilon'}, {'TeamNum': 12636, 'OPR': 61.825, 'Auto': 15.402, 'CCWM': 41.253, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 13105, 'OPR': 53.285, 'Auto': 16.812, 'CCWM': 17.262, 'TeamName': 'Ironmen Omicron'}, {'TeamNum': 10603, 'OPR': 52.866, 'Auto': 6.211, 'CCWM': 0.859, 'TeamName': 'WOOD-CHIPS'}, {'TeamNum': 10243, 'OPR': 48.886, 'Auto': -1.057, 'CCWM': 15.339, 'TeamName': 'Ramsey Ramblers'}, {'TeamNum': 13107, 'OPR': 41.641, 'Auto': 18.165, 'CCWM': -26.826, 'TeamName': 'Ironmen Pi'}, {'TeamNum': 18757, 'OPR': 41.167, 'Auto': 15.168, 'CCWM': -13.49, 'TeamName': 'Ironmen Rho'}, {'TeamNum': 247, 'OPR': 32.892, 'Auto': 21.109, 'CCWM': -1.824, 'TeamName': 'Reboot'}, {'TeamNum': 18759, 'OPR': 29.595, 'Auto': 15.155, 'CCWM': -40.886, 'TeamName': 'Ironmen Tau'}, {'TeamNum': 248, 'OPR': 23.794, 'Auto': 4.407, 'CCWM': -28.089, 'TeamName': 'Fatal Error'}, {'TeamNum': 3777, 'OPR': 23.377, 'Auto': 11.417, 'CCWM': -1.898, 'TeamName': 'Mecha Lion'}, {'TeamNum': 14450, 'OPR': 20.657, 'Auto': 11.911, 'CCWM': -31.5, 'TeamName': 'RoboRebels'}, {'TeamNum': 11396, 'OPR': 4.559, 'Auto': -10.641, 'CCWM': -21.958, 'TeamName': 'ECR Eaglebots'}, {'TeamNum': 9244, 'OPR': 0.217, 'Auto': -11.412, 'CCWM': -63.671, 'TeamName': 'Lenape Valley Robotics'}, {'TeamNum': 15231, 'OPR': -2.264, 'Auto': -2.619, 'CCWM': -64.966, 'TeamName': 'ECR Squared'}]
i 1007
{'17280', '18815', '18850', '21535', '11665', '12991', '14532', '20253', '18682', '3050', '16384', '18858', '14841', '21726', '21787', '21517', '12777', '19792', '15884', '15569', '21629', '21794', '15889'}
[{'TeamNum': 14841, 'OPR': 95.216, 'Auto': 18.873, 'CCWM': 80.952, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 19792, 'OPR': 72.697, 'Auto': 23.551, 'CCWM': 40.498, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 15884, 'OPR': 69.095, 'Auto': 18.983, 'CCWM': 52.825, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 12991, 'OPR': 63.595, 'Auto': 15.538, 'CCWM': 49.949, 'TeamName': 'Awkward Silence'}, {'TeamNum': 21787, 'OPR': 46.328, 'Auto': 7.089, 'CCWM': 19.363, 'TeamName': 'ARC - White'}, {'TeamNum': 15569, 'OPR': 43.288, 'Auto': -2.859, 'CCWM': 21.377, 'TeamName': 'RoboRattlers'}, {'TeamNum': 3050, 'OPR': 43.243, 'Auto': 9.139, 'CCWM': 5.8, 'TeamName': 'G-Bots'}, {'TeamNum': 21517, 'OPR': 40.779, 'Auto': 4.819, 'CCWM': 22.486, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 18858, 'OPR': 40.601, 'Auto': 17.828, 'CCWM': 26.966, 'TeamName': 'ARC - Blue'}, {'TeamNum': 17280, 'OPR': 29.536, 'Auto': 0.522, 'CCWM': -12.129, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 15889, 'OPR': 24.873, 'Auto': 8.203, 'CCWM': -12.438, 'TeamName': 'RoboDawgs'}, {'TeamNum': 14532, 'OPR': 24.77, 'Auto': 3.358, 'CCWM': 3.336, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 21629, 'OPR': 21.125, 'Auto': 7.909, 'CCWM': -16.691, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 21794, 'OPR': 20.086, 'Auto': -2.636, 'CCWM': -29.589, 'TeamName': 'Laughlin Jr/Sr HS 2'}, {'TeamNum': 18850, 'OPR': 19.302, 'Auto': 2.994, 'CCWM': -27.068, 'TeamName': 'Kill Switch'}, {'TeamNum': 20253, 'OPR': 16.177, 'Auto': 0.511, 'CCWM': -11.085, 'TeamName': 'Robotic Tigers'}, {'TeamNum': 11665, 'OPR': 15.334, 'Auto': 2.006, 'CCWM': -7.914, 'TeamName': 'Iron Falcons'}, {'TeamNum': 18815, 'OPR': 13.976, 'Auto': 1.586, 'CCWM': -31.279, 'TeamName': 'LANV Logic'}, {'TeamNum': 21726, 'OPR': 11.206, 'Auto': -7.654, 'CCWM': -29.321, 'TeamName': 'Laughlin Jr/Sr HS'}, {'TeamNum': 21535, 'OPR': 10.724, 'Auto': 2.739, 'CCWM': -23.391, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 16384, 'OPR': 9.24, 'Auto': 1.963, 'CCWM': -9.976, 'TeamName': 'GREAT Bots'}, {'TeamNum': 12777, 'OPR': 8.561, 'Auto': 2.64, 'CCWM': -73.186, 'TeamName': 'Boulder City SuperBots'}, {'TeamNum': 18682, 'OPR': 4.705, 'Auto': -2.585, 'CCWM': -32.905, 'TeamName': 'Cyber Nights'}]
USNVSOLT
[{'TeamNum': 14841, 'OPR': 95.216, 'Auto': 18.873, 'CCWM': 80.952, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 19792, 'OPR': 72.697, 'Auto': 23.551, 'CCWM': 40.498, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 15884, 'OPR': 69.095, 'Auto': 18.983, 'CCWM': 52.825, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 12991, 'OPR': 63.595, 'Auto': 15.538, 'CCWM': 49.949, 'TeamName': 'Awkward Silence'}, {'TeamNum': 21787, 'OPR': 46.328, 'Auto': 7.089, 'CCWM': 19.363, 'TeamName': 'ARC - White'}, {'TeamNum': 15569, 'OPR': 43.288, 'Auto': -2.859, 'CCWM': 21.377, 'TeamName': 'RoboRattlers'}, {'TeamNum': 3050, 'OPR': 43.243, 'Auto': 9.139, 'CCWM': 5.8, 'TeamName': 'G-Bots'}, {'TeamNum': 21517, 'OPR': 40.779, 'Auto': 4.819, 'CCWM': 22.486, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 18858, 'OPR': 40.601, 'Auto': 17.828, 'CCWM': 26.966, 'TeamName': 'ARC - Blue'}, {'TeamNum': 17280, 'OPR': 29.536, 'Auto': 0.522, 'CCWM': -12.129, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 15889, 'OPR': 24.873, 'Auto': 8.203, 'CCWM': -12.438, 'TeamName': 'RoboDawgs'}, {'TeamNum': 14532, 'OPR': 24.77, 'Auto': 3.358, 'CCWM': 3.336, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 21629, 'OPR': 21.125, 'Auto': 7.909, 'CCWM': -16.691, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 21794, 'OPR': 20.086, 'Auto': -2.636, 'CCWM': -29.589, 'TeamName': 'Laughlin Jr/Sr HS 2'}, {'TeamNum': 18850, 'OPR': 19.302, 'Auto': 2.994, 'CCWM': -27.068, 'TeamName': 'Kill Switch'}, {'TeamNum': 20253, 'OPR': 16.177, 'Auto': 0.511, 'CCWM': -11.085, 'TeamName': 'Robotic Tigers'}, {'TeamNum': 11665, 'OPR': 15.334, 'Auto': 2.006, 'CCWM': -7.914, 'TeamName': 'Iron Falcons'}, {'TeamNum': 18815, 'OPR': 13.976, 'Auto': 1.586, 'CCWM': -31.279, 'TeamName': 'LANV Logic'}, {'TeamNum': 21726, 'OPR': 11.206, 'Auto': -7.654, 'CCWM': -29.321, 'TeamName': 'Laughlin Jr/Sr HS'}, {'TeamNum': 21535, 'OPR': 10.724, 'Auto': 2.739, 'CCWM': -23.391, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 16384, 'OPR': 9.24, 'Auto': 1.963, 'CCWM': -9.976, 'TeamName': 'GREAT Bots'}, {'TeamNum': 12777, 'OPR': 8.561, 'Auto': 2.64, 'CCWM': -73.186, 'TeamName': 'Boulder City SuperBots'}, {'TeamNum': 18682, 'OPR': 4.705, 'Auto': -2.585, 'CCWM': -32.905, 'TeamName': 'Cyber Nights'}]

i 1008
{'17506', '20681', '21897', '18203', '21238', '9507', '11183', '16158', '22296', '21707', '11574', '22317', '21217', '20948', '22774', '15903', '21632', '16118', '15492', '18419', '20285', '18959'}
[{'TeamNum': 16158, 'OPR': 145.582, 'Auto': 31.526, 'CCWM': 118.19, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 22317, 'OPR': 66.473, 'Auto': 9.67, 'CCWM': 36.697, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 18203, 'OPR': 61.376, 'Auto': 19.364, 'CCWM': 64.798, 'TeamName': 'MCII'}, {'TeamNum': 21217, 'OPR': 57.363, 'Auto': 22.386, 'CCWM': 21.442, 'TeamName': 'The Phoenixes'}, {'TeamNum': 20285, 'OPR': 52.047, 'Auto': 21.133, 'CCWM': -2.996, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 21707, 'OPR': 44.061, 'Auto': 0.201, 'CCWM': -8.768, 'TeamName': 'MinerBots'}, {'TeamNum': 11183, 'OPR': 41.365, 'Auto': 10.091, 'CCWM': -1.481, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 17506, 'OPR': 39.958, 'Auto': 7.052, 'CCWM': 9.364, 'TeamName': 'Wolverines'}, {'TeamNum': 11574, 'OPR': 39.106, 'Auto': -0.293, 'CCWM': 29.817, 'TeamName': 'Incognito'}, {'TeamNum': 22774, 'OPR': 38.534, 'Auto': 12.733, 'CCWM': -26.658, 'TeamName': 'URSA Major'}, {'TeamNum': 16118, 'OPR': 34.249, 'Auto': -4.229, 'CCWM': 6.812, 'TeamName': '52! McQueen HS'}, {'TeamNum': 21238, 'OPR': 31.854, 'Auto': 4.324, 'CCWM': -21.99, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 15903, 'OPR': 30.936, 'Auto': 16.469, 'CCWM': -35.893, 'TeamName': 'Chaos'}, {'TeamNum': 21632, 'OPR': 28.569, 'Auto': 4.029, 'CCWM': -39.298, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 15492, 'OPR': 23.766, 'Auto': 5.703, 'CCWM': 10.091, 'TeamName': 'ELrobotiKO'}, {'TeamNum': 18419, 'OPR': 18.497, 'Auto': 1.287, 'CCWM': 11.846, 'TeamName': 'Comstock Coders'}, {'TeamNum': 20681, 'OPR': 17.736, 'Auto': 9.686, 'CCWM': -7.577, 'TeamName': 'Giga Bite'}, {'TeamNum': 20948, 'OPR': 16.183, 'Auto': 2.215, 'CCWM': -6.699, 'TeamName': 'Hug HS'}, {'TeamNum': 18959, 'OPR': 16.064, 'Auto': 3.055, 'CCWM': -37.316, 'TeamName': 'North Valleys High School RoboPanthers'}, {'TeamNum': 22296, 'OPR': 11.84, 'Auto': -0.286, 'CCWM': -45.115, 'TeamName': 'Greenwave Robotics'}, {'TeamNum': 21897, 'OPR': 9.214, 'Auto': 1.349, 'CCWM': -25.155, 'TeamName': 'Oasis Academy'}, {'TeamNum': 9507, 'OPR': -5.438, 'Auto': -3.632, 'CCWM': -50.113, 'TeamName': 'Rubber Ducks Reedbotics'}]
USNVNOLT
[{'TeamNum': 16158, 'OPR': 145.582, 'Auto': 31.526, 'CCWM': 118.19, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 22317, 'OPR': 66.473, 'Auto': 9.67, 'CCWM': 36.697, 'TeamName': 'Truckee 2.0'}, {'TeamNum': 18203, 'OPR': 61.376, 'Auto': 19.364, 'CCWM': 64.798, 'TeamName': 'MCII'}, {'TeamNum': 21217, 'OPR': 57.363, 'Auto': 22.386, 'CCWM': 21.442, 'TeamName': 'The Phoenixes'}, {'TeamNum': 20285, 'OPR': 52.047, 'Auto': 21.133, 'CCWM': -2.996, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 21707, 'OPR': 44.061, 'Auto': 0.201, 'CCWM': -8.768, 'TeamName': 'MinerBots'}, {'TeamNum': 11183, 'OPR': 41.365, 'Auto': 10.091, 'CCWM': -1.481, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 17506, 'OPR': 39.958, 'Auto': 7.052, 'CCWM': 9.364, 'TeamName': 'Wolverines'}, {'TeamNum': 11574, 'OPR': 39.106, 'Auto': -0.293, 'CCWM': 29.817, 'TeamName': 'Incognito'}, {'TeamNum': 22774, 'OPR': 38.534, 'Auto': 12.733, 'CCWM': -26.658, 'TeamName': 'URSA Major'}, {'TeamNum': 16118, 'OPR': 34.249, 'Auto': -4.229, 'CCWM': 6.812, 'TeamName': '52! McQueen HS'}, {'TeamNum': 21238, 'OPR': 31.854, 'Auto': 4.324, 'CCWM': -21.99, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 15903, 'OPR': 30.936, 'Auto': 16.469, 'CCWM': -35.893, 'TeamName': 'Chaos'}, {'TeamNum': 21632, 'OPR': 28.569, 'Auto': 4.029, 'CCWM': -39.298, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 15492, 'OPR': 23.766, 'Auto': 5.703, 'CCWM': 10.091, 'TeamName': 'ELrobotiKO'}, {'TeamNum': 18419, 'OPR': 18.497, 'Auto': 1.287, 'CCWM': 11.846, 'TeamName': 'Comstock Coders'}, {'TeamNum': 20681, 'OPR': 17.736, 'Auto': 9.686, 'CCWM': -7.577, 'TeamName': 'Giga Bite'}, {'TeamNum': 20948, 'OPR': 16.183, 'Auto': 2.215, 'CCWM': -6.699, 'TeamName': 'Hug HS'}, {'TeamNum': 18959, 'OPR': 16.064, 'Auto': 3.055, 'CCWM': -37.316, 'TeamName': 'North Valleys High School RoboPanthers'}, {'TeamNum': 22296, 'OPR': 11.84, 'Auto': -0.286, 'CCWM': -45.115, 'TeamName': 'Greenwave Robotics'}, {'TeamNum': 21897, 'OPR': 9.214, 'Auto': 1.349, 'CCWM': -25.155, 'TeamName': 'Oasis Academy'}, {'TeamNum': 9507, 'OPR': -5.438, 'Auto': -3.632, 'CCWM': -50.113, 'TeamName': 'Rubber Ducks Reedbotics'}]
i 1009
{'14639', '5361', '4174', '14803', '4780', '310', '19167', '20789', '8088', '17522', '10393', '8087', '9384', '16568', '479', '10392', '3371', '8721', '15740', '22324', '8500', '13334', '4995', '9372', '17126', '11453', '18657', '13475'}
[{'TeamNum': 310, 'OPR': 117.387, 'Auto': 27.762, 'CCWM': 133.467, 'TeamName': 'Stuy Fission'}, {'TeamNum': 8500, 'OPR': 92.757, 'Auto': 24.193, 'CCWM': 53.079, 'TeamName': 'The Generals'}, {'TeamNum': 8088, 'OPR': 80.555, 'Auto': 24.763, 'CCWM': 45.307, 'TeamName': 'Team Cephalopods'}, {'TeamNum': 18657, 'OPR': 79.045, 'Auto': 10.049, 'CCWM': 62.105, 'TeamName': 'AIM Robotics'}, {'TeamNum': 479, 'OPR': 76.726, 'Auto': 13.052, 'CCWM': 33.276, 'TeamName': 'Stuy Fusion'}, {'TeamNum': 5361, 'OPR': 72.467, 'Auto': 31.274, 'CCWM': 27.665, 'TeamName': 'Lionotics'}, {'TeamNum': 4174, 'OPR': 57.304, 'Auto': 18.156, 'CCWM': -5.513, 'TeamName': 'Atomic Theory'}, {'TeamNum': 17522, 'OPR': 53.811, 'Auto': 13.106, 'CCWM': 44.301, 'TeamName': 'ETech Chargers'}, {'TeamNum': 9384, 'OPR': 52.017, 'Auto': -4.136, 'CCWM': 25.627, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 13334, 'OPR': 47.929, 'Auto': 11.445, 'CCWM': -16.12, 'TeamName': 'Spence Light Sabers'}, {'TeamNum': 14803, 'OPR': 42.072, 'Auto': 8.265, 'CCWM': 35.257, 'TeamName': 'uKnighted'}, {'TeamNum': 15740, 'OPR': 37.526, 'Auto': 5.778, 'CCWM': -25.911, 'TeamName': 'SAR2-D2'}, {'TeamNum': 19167, 'OPR': 33.787, 'Auto': 6.599, 'CCWM': -37.035, 'TeamName': 'Robo_Sapiens'}, {'TeamNum': 10392, 'OPR': 33.292, 'Auto': 17.682, 'CCWM': -30.078, 'TeamName': 'The Rolling Drones'}, {'TeamNum': 8087, 'OPR': 30.685, 'Auto': 19.565, 'CCWM': 0.867, 'TeamName': 'Seahorse Stallions'}, {'TeamNum': 3371, 'OPR': 29.726, 'Auto': 11.788, 'CCWM': -17.008, 'TeamName': 'Bötley Crüe'}, {'TeamNum': 17126, 'OPR': 24.924, 'Auto': 5.095, 'CCWM': 13.144, 'TeamName': 'Natural Selection'}, {'TeamNum': 8721, 'OPR': 22.323, 'Auto': 1.04, 'CCWM': -59.332, 'TeamName': 'Mighty Mechanics'}, {'TeamNum': 20789, 'OPR': 22.243, 'Auto': 1.446, 'CCWM': -38.182, 'TeamName': 'Paranoid-Androids-On-Steriods'}, {'TeamNum': 13475, 'OPR': 22.168, 'Auto': 2.496, 'CCWM': -32.093, 'TeamName': 'Lionotics 2'}, {'TeamNum': 4995, 'OPR': 20.056, 'Auto': -0.56, 'CCWM': -28.59, 'TeamName': 'Titanium Tigers'}, {'TeamNum': 16568, 'OPR': 19.125, 'Auto': 3.885, 'CCWM': -21.062, 'TeamName': 'Cybernetic Lions'}, {'TeamNum': 9372, 'OPR': 18.725, 'Auto': 1.203, 'CCWM': -21.194, 'TeamName': 'Standard Model'}, {'TeamNum': 10393, 'OPR': 17.75, 'Auto': 11.178, 'CCWM': -33.083, 'TeamName': 'Pink Droyd'}, {'TeamNum': 14639, 'OPR': 15.415, 'Auto': 7.678, 'CCWM': 5.984, 'TeamName': 'Double X (B3VR)'}, {'TeamNum': 22324, 'OPR': 15.225, 'Auto': -5.598, 'CCWM': -7.487, 'TeamName': 'ETech Spare Parts'}, {'TeamNum': 11453, 'OPR': 13.545, 'Auto': 4.403, 'CCWM': -43.911, 'TeamName': 'Uncertainty Principle'}, {'TeamNum': 4780, 'OPR': -5.984, 'Auto': -3.209, 'CCWM': -63.48, 'TeamName': 'Robolution'}]
USNYNYNYSQ2
[{'TeamNum': 310, 'OPR': 117.387, 'Auto': 27.762, 'CCWM': 133.467, 'TeamName': 'Stuy Fission'}, {'TeamNum': 8500, 'OPR': 92.757, 'Auto': 24.193, 'CCWM': 53.079, 'TeamName': 'The Generals'}, {'TeamNum': 8088, 'OPR': 80.555, 'Auto': 24.763, 'CCWM': 45.307, 'TeamName': 'Team Cephalopods'}, {'TeamNum': 18657, 'OPR': 79.045, 'Auto': 10.049, 'CCWM': 62.105, 'TeamName': 'AIM Robotics'}, {'TeamNum': 479, 'OPR': 76.726, 'Auto': 13.052, 'CCWM': 33.276, 'TeamName': 'Stuy Fusion'}, {'TeamNum': 5361, 'OPR': 72.467, 'Auto': 31.274, 'CCWM': 27.665, 'TeamName': 'Lionotics'}, {'TeamNum': 4174, 'OPR': 57.304, 'Auto': 18.156, 'CCWM': -5.513, 'TeamName': 'Atomic Theory'}, {'TeamNum': 17522, 'OPR': 53.811, 'Auto': 13.106, 'CCWM': 44.301, 'TeamName': 'ETech Chargers'}, {'TeamNum': 9384, 'OPR': 52.017, 'Auto': -4.136, 'CCWM': 25.627, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 13334, 'OPR': 47.929, 'Auto': 11.445, 'CCWM': -16.12, 'TeamName': 'Spence Light Sabers'}, {'TeamNum': 14803, 'OPR': 42.072, 'Auto': 8.265, 'CCWM': 35.257, 'TeamName': 'uKnighted'}, {'TeamNum': 15740, 'OPR': 37.526, 'Auto': 5.778, 'CCWM': -25.911, 'TeamName': 'SAR2-D2'}, {'TeamNum': 19167, 'OPR': 33.787, 'Auto': 6.599, 'CCWM': -37.035, 'TeamName': 'Robo_Sapiens'}, {'TeamNum': 10392, 'OPR': 33.292, 'Auto': 17.682, 'CCWM': -30.078, 'TeamName': 'The Rolling Drones'}, {'TeamNum': 8087, 'OPR': 30.685, 'Auto': 19.565, 'CCWM': 0.867, 'TeamName': 'Seahorse Stallions'}, {'TeamNum': 3371, 'OPR': 29.726, 'Auto': 11.788, 'CCWM': -17.008, 'TeamName': 'Bötley Crüe'}, {'TeamNum': 17126, 'OPR': 24.924, 'Auto': 5.095, 'CCWM': 13.144, 'TeamName': 'Natural Selection'}, {'TeamNum': 8721, 'OPR': 22.323, 'Auto': 1.04, 'CCWM': -59.332, 'TeamName': 'Mighty Mechanics'}, {'TeamNum': 20789, 'OPR': 22.243, 'Auto': 1.446, 'CCWM': -38.182, 'TeamName': 'Paranoid-Androids-On-Steriods'}, {'TeamNum': 13475, 'OPR': 22.168, 'Auto': 2.496, 'CCWM': -32.093, 'TeamName': 'Lionotics 2'}, {'TeamNum': 4995, 'OPR': 20.056, 'Auto': -0.56, 'CCWM': -28.59, 'TeamName': 'Titanium Tigers'}, {'TeamNum': 16568, 'OPR': 19.125, 'Auto': 3.885, 'CCWM': -21.062, 'TeamName': 'Cybernetic Lions'}, {'TeamNum': 9372, 'OPR': 18.725, 'Auto': 1.203, 'CCWM': -21.194, 'TeamName': 'Standard Model'}, {'TeamNum': 10393, 'OPR': 17.75, 'Auto': 11.178, 'CCWM': -33.083, 'TeamName': 'Pink Droyd'}, {'TeamNum': 14639, 'OPR': 15.415, 'Auto': 7.678, 'CCWM': 5.984, 'TeamName': 'Double X (B3VR)'}, {'TeamNum': 22324, 'OPR': 15.225, 'Auto': -5.598, 'CCWM': -7.487, 'TeamName': 'ETech Spare Parts'}, {'TeamNum': 11453, 'OPR': 13.545, 'Auto': 4.403, 'CCWM': -43.911, 'TeamName': 'Uncertainty Principle'}, {'TeamNum': 4780, 'OPR': -5.984, 'Auto': -3.209, 'CCWM': -63.48, 'TeamName': 'Robolution'}]

i 1010
{'16938', '18826', '7164', '13375', '10696', '12382', '16145', '8013', '13234', '6942', '9421', '4137', '17204', '17392', '124', '10169', '5283', '4017', '13847', '10738'}
[{'TeamNum': 10169, 'OPR': 88.81, 'Auto': 16.521, 'CCWM': 59.08, 'TeamName': 'Crimson Lightning'}, {'TeamNum': 4017, 'OPR': 71.11, 'Auto': 16.374, 'CCWM': 66.496, 'TeamName': 'RoboPandas'}, {'TeamNum': 7164, 'OPR': 63.049, 'Auto': 15.117, 'CCWM': 57.657, 'TeamName': 'FalconBots'}, {'TeamNum': 10696, 'OPR': 56.453, 'Auto': 28.212, 'CCWM': 4.113, 'TeamName': 'Syosset Syborgs'}, {'TeamNum': 17204, 'OPR': 53.255, 'Auto': 19.064, 'CCWM': 19.513, 'TeamName': 'Wired Wyverns'}, {'TeamNum': 13375, 'OPR': 51.003, 'Auto': 20.487, 'CCWM': 0.92, 'TeamName': 'Great Neck North Goatbusters'}, {'TeamNum': 4137, 'OPR': 46.055, 'Auto': 4.387, 'CCWM': -23.379, 'TeamName': 'IslandBots'}, {'TeamNum': 6942, 'OPR': 38.332, 'Auto': 14.509, 'CCWM': 40.366, 'TeamName': 'Pandemonium'}, {'TeamNum': 12382, 'OPR': 35.795, 'Auto': 11.246, 'CCWM': 16.951, 'TeamName': 'Syosset Nebula'}, {'TeamNum': 16145, 'OPR': 35.253, 'Auto': -10.532, 'CCWM': 7.674, 'TeamName': 'Sea Lions'}, {'TeamNum': 13234, 'OPR': 33.575, 'Auto': -8.016, 'CCWM': 8.674, 'TeamName': 'Longwood CSD Jr High FTC'}, {'TeamNum': 16938, 'OPR': 32.374, 'Auto': -4.212, 'CCWM': -9.857, 'TeamName': 'Maajes'}, {'TeamNum': 5283, 'OPR': 31.486, 'Auto': 20.995, 'CCWM': 11.626, 'TeamName': 'LAIMO'}, {'TeamNum': 124, 'OPR': 31.284, 'Auto': 7.06, 'CCWM': -13.471, 'TeamName': 'Syosset Supersonics'}, {'TeamNum': 8013, 'OPR': 26.94, 'Auto': 28.083, 'CCWM': -6.235, 'TeamName': 'Team Kuiper'}, {'TeamNum': 10738, 'OPR': 26.081, 'Auto': 20.903, 'CCWM': -30.299, 'TeamName': 'SBS  Bears'}, {'TeamNum': 9421, 'OPR': 16.55, 'Auto': 1.452, 'CCWM': -29.707, 'TeamName': 'Hydrofluoric Robotics'}, {'TeamNum': 13847, 'OPR': 13.496, 'Auto': -2.127, 'CCWM': -80.832, 'TeamName': "At Least It Didn't Explode"}, {'TeamNum': 17392, 'OPR': 11.301, 'Auto': 2.39, 'CCWM': -70.761, 'TeamName': 'Tesseract'}, {'TeamNum': 18826, 'OPR': 6.13, 'Auto': 1.755, 'CCWM': -28.528, 'TeamName': 'Elevated Creations'}]
USNYLISBQ4
[{'TeamNum': 10169, 'OPR': 88.81, 'Auto': 16.521, 'CCWM': 59.08, 'TeamName': 'Crimson Lightning'}, {'TeamNum': 4017, 'OPR': 71.11, 'Auto': 16.374, 'CCWM': 66.496, 'TeamName': 'RoboPandas'}, {'TeamNum': 7164, 'OPR': 63.049, 'Auto': 15.117, 'CCWM': 57.657, 'TeamName': 'FalconBots'}, {'TeamNum': 10696, 'OPR': 56.453, 'Auto': 28.212, 'CCWM': 4.113, 'TeamName': 'Syosset Syborgs'}, {'TeamNum': 17204, 'OPR': 53.255, 'Auto': 19.064, 'CCWM': 19.513, 'TeamName': 'Wired Wyverns'}, {'TeamNum': 13375, 'OPR': 51.003, 'Auto': 20.487, 'CCWM': 0.92, 'TeamName': 'Great Neck North Goatbusters'}, {'TeamNum': 4137, 'OPR': 46.055, 'Auto': 4.387, 'CCWM': -23.379, 'TeamName': 'IslandBots'}, {'TeamNum': 6942, 'OPR': 38.332, 'Auto': 14.509, 'CCWM': 40.366, 'TeamName': 'Pandemonium'}, {'TeamNum': 12382, 'OPR': 35.795, 'Auto': 11.246, 'CCWM': 16.951, 'TeamName': 'Syosset Nebula'}, {'TeamNum': 16145, 'OPR': 35.253, 'Auto': -10.532, 'CCWM': 7.674, 'TeamName': 'Sea Lions'}, {'TeamNum': 13234, 'OPR': 33.575, 'Auto': -8.016, 'CCWM': 8.674, 'TeamName': 'Longwood CSD Jr High FTC'}, {'TeamNum': 16938, 'OPR': 32.374, 'Auto': -4.212, 'CCWM': -9.857, 'TeamName': 'Maajes'}, {'TeamNum': 5283, 'OPR': 31.486, 'Auto': 20.995, 'CCWM': 11.626, 'TeamName': 'LAIMO'}, {'TeamNum': 124, 'OPR': 31.284, 'Auto': 7.06, 'CCWM': -13.471, 'TeamName': 'Syosset Supersonics'}, {'TeamNum': 8013, 'OPR': 26.94, 'Auto': 28.083, 'CCWM': -6.235, 'TeamName': 'Team Kuiper'}, {'TeamNum': 10738, 'OPR': 26.081, 'Auto': 20.903, 'CCWM': -30.299, 'TeamName': 'SBS  Bears'}, {'TeamNum': 9421, 'OPR': 16.55, 'Auto': 1.452, 'CCWM': -29.707, 'TeamName': 'Hydrofluoric Robotics'}, {'TeamNum': 13847, 'OPR': 13.496, 'Auto': -2.127, 'CCWM': -80.832, 'TeamName': "At Least It Didn't Explode"}, {'TeamNum': 17392, 'OPR': 11.301, 'Auto': 2.39, 'CCWM': -70.761, 'TeamName': 'Tesseract'}, {'TeamNum': 18826, 'OPR': 6.13, 'Auto': 1.755, 'CCWM': -28.528, 'TeamName': 'Elevated Creations'}]
i 1011
{'19426', '21377', '14212', '20712', '16798', '10639', '20701', '22204', '11997', '14712', '4782', '3922', '4781', '10539', '20233', '9371', '3006', '12282', '6051', '11943', '8365', '22518', '14156', '22335', '22437', '13368', '14734', '17253'}
[{'TeamNum': 14212, 'OPR': 120.617, 'Auto': 42.909, 'CCWM': 66.583, 'TeamName': 'Metrobotics'}, {'TeamNum': 8365, 'OPR': 110.085, 'Auto': 19.198, 'CCWM': 47.017, 'TeamName': 'Gearmasters'}, {'TeamNum': 10539, 'OPR': 85.569, 'Auto': 7.099, 'CCWM': 63.227, 'TeamName': 'Ultro'}, {'TeamNum': 22437, 'OPR': 76.728, 'Auto': 23.554, 'CCWM': 42.94, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 4782, 'OPR': 68.979, 'Auto': 15.87, 'CCWM': 6.765, 'TeamName': 'The Super Troublemakers'}, {'TeamNum': 11943, 'OPR': 62.266, 'Auto': 10.002, 'CCWM': 69.933, 'TeamName': 'The Nighthawks'}, {'TeamNum': 12282, 'OPR': 62.13, 'Auto': 19.017, 'CCWM': -11.275, 'TeamName': 'Cyberdogs'}, {'TeamNum': 14712, 'OPR': 58.326, 'Auto': 19.744, 'CCWM': 31.498, 'TeamName': 'Ruckus Robotics'}, {'TeamNum': 11997, 'OPR': 54.176, 'Auto': 11.078, 'CCWM': -8.945, 'TeamName': 'Heights Techies'}, {'TeamNum': 19426, 'OPR': 52.908, 'Auto': 8.142, 'CCWM': 1.577, 'TeamName': 'QHSS Cardinal Robotics'}, {'TeamNum': 14156, 'OPR': 51.324, 'Auto': 10.16, 'CCWM': -9.555, 'TeamName': 'Packer Robotics'}, {'TeamNum': 9371, 'OPR': 49.699, 'Auto': 20.69, 'CCWM': -7.677, 'TeamName': 'General Relativity'}, {'TeamNum': 20701, 'OPR': 45.246, 'Auto': 13.971, 'CCWM': 0.526, 'TeamName': 'Team Lovelace'}, {'TeamNum': 20712, 'OPR': 45.184, 'Auto': 9.333, 'CCWM': -6.011, 'TeamName': 'Kenny Donuts'}, {'TeamNum': 22335, 'OPR': 44.313, 'Auto': 3.235, 'CCWM': -31.396, 'TeamName': 'Polymorphism '}, {'TeamNum': 10639, 'OPR': 41.614, 'Auto': 11.953, 'CCWM': -28.556, 'TeamName': 'ArgoKnights'}, {'TeamNum': 14734, 'OPR': 40.782, 'Auto': 12.78, 'CCWM': -33.384, 'TeamName': 'Envirobots'}, {'TeamNum': 22518, 'OPR': 40.437, 'Auto': 1.289, 'CCWM': -28.964, 'TeamName': 'Bronx Sharks'}, {'TeamNum': 4781, 'OPR': 38.055, 'Auto': 2.783, 'CCWM': 19.116, 'TeamName': 'MechaKnights'}, {'TeamNum': 13368, 'OPR': 34.173, 'Auto': 5.042, 'CCWM': -9.032, 'TeamName': 'The Mechatronics'}, {'TeamNum': 3006, 'OPR': 26.696, 'Auto': 11.71, 'CCWM': -53.231, 'TeamName': 'TeraBots'}, {'TeamNum': 3922, 'OPR': 26.571, 'Auto': -9.591, 'CCWM': 8.813, 'TeamName': 'Modibot'}, {'TeamNum': 6051, 'OPR': 23.407, 'Auto': 8.512, 'CCWM': -21.449, 'TeamName': 'Quantum Mechanics'}, {'TeamNum': 21377, 'OPR': 21.757, 'Auto': 4.212, 'CCWM': -30.705, 'TeamName': 'Botsworth'}, {'TeamNum': 17253, 'OPR': 21.09, 'Auto': 21.537, 'CCWM': -14.531, 'TeamName': 'Ulterior Motive'}, {'TeamNum': 22204, 'OPR': 9.676, 'Auto': -1.028, 'CCWM': -7.638, 'TeamName': 'GT1 - Prime Aqua Bots'}, {'TeamNum': 20233, 'OPR': 7.73, 'Auto': 10.352, 'CCWM': -49.366, 'TeamName': 'Blazing Bluebots'}, {'TeamNum': 16798, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Redhawk Robotics'}]
USNYNYNYSQ
[{'TeamNum': 14212, 'OPR': 120.617, 'Auto': 42.909, 'CCWM': 66.583, 'TeamName': 'Metrobotics'}, {'TeamNum': 8365, 'OPR': 110.085, 'Auto': 19.198, 'CCWM': 47.017, 'TeamName': 'Gearmasters'}, {'TeamNum': 10539, 'OPR': 85.569, 'Auto': 7.099, 'CCWM': 63.227, 'TeamName': 'Ultro'}, {'TeamNum': 22437, 'OPR': 76.728, 'Auto': 23.554, 'CCWM': 42.94, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 4782, 'OPR': 68.979, 'Auto': 15.87, 'CCWM': 6.765, 'TeamName': 'The Super Troublemakers'}, {'TeamNum': 11943, 'OPR': 62.266, 'Auto': 10.002, 'CCWM': 69.933, 'TeamName': 'The Nighthawks'}, {'TeamNum': 12282, 'OPR': 62.13, 'Auto': 19.017, 'CCWM': -11.275, 'TeamName': 'Cyberdogs'}, {'TeamNum': 14712, 'OPR': 58.326, 'Auto': 19.744, 'CCWM': 31.498, 'TeamName': 'Ruckus Robotics'}, {'TeamNum': 11997, 'OPR': 54.176, 'Auto': 11.078, 'CCWM': -8.945, 'TeamName': 'Heights Techies'}, {'TeamNum': 19426, 'OPR': 52.908, 'Auto': 8.142, 'CCWM': 1.577, 'TeamName': 'QHSS Cardinal Robotics'}, {'TeamNum': 14156, 'OPR': 51.324, 'Auto': 10.16, 'CCWM': -9.555, 'TeamName': 'Packer Robotics'}, {'TeamNum': 9371, 'OPR': 49.699, 'Auto': 20.69, 'CCWM': -7.677, 'TeamName': 'General Relativity'}, {'TeamNum': 20701, 'OPR': 45.246, 'Auto': 13.971, 'CCWM': 0.526, 'TeamName': 'Team Lovelace'}, {'TeamNum': 20712, 'OPR': 45.184, 'Auto': 9.333, 'CCWM': -6.011, 'TeamName': 'Kenny Donuts'}, {'TeamNum': 22335, 'OPR': 44.313, 'Auto': 3.235, 'CCWM': -31.396, 'TeamName': 'Polymorphism '}, {'TeamNum': 10639, 'OPR': 41.614, 'Auto': 11.953, 'CCWM': -28.556, 'TeamName': 'ArgoKnights'}, {'TeamNum': 14734, 'OPR': 40.782, 'Auto': 12.78, 'CCWM': -33.384, 'TeamName': 'Envirobots'}, {'TeamNum': 22518, 'OPR': 40.437, 'Auto': 1.289, 'CCWM': -28.964, 'TeamName': 'Bronx Sharks'}, {'TeamNum': 4781, 'OPR': 38.055, 'Auto': 2.783, 'CCWM': 19.116, 'TeamName': 'MechaKnights'}, {'TeamNum': 13368, 'OPR': 34.173, 'Auto': 5.042, 'CCWM': -9.032, 'TeamName': 'The Mechatronics'}, {'TeamNum': 3006, 'OPR': 26.696, 'Auto': 11.71, 'CCWM': -53.231, 'TeamName': 'TeraBots'}, {'TeamNum': 3922, 'OPR': 26.571, 'Auto': -9.591, 'CCWM': 8.813, 'TeamName': 'Modibot'}, {'TeamNum': 6051, 'OPR': 23.407, 'Auto': 8.512, 'CCWM': -21.449, 'TeamName': 'Quantum Mechanics'}, {'TeamNum': 21377, 'OPR': 21.757, 'Auto': 4.212, 'CCWM': -30.705, 'TeamName': 'Botsworth'}, {'TeamNum': 17253, 'OPR': 21.09, 'Auto': 21.537, 'CCWM': -14.531, 'TeamName': 'Ulterior Motive'}, {'TeamNum': 22204, 'OPR': 9.676, 'Auto': -1.028, 'CCWM': -7.638, 'TeamName': 'GT1 - Prime Aqua Bots'}, {'TeamNum': 20233, 'OPR': 7.73, 'Auto': 10.352, 'CCWM': -49.366, 'TeamName': 'Blazing Bluebots'}, {'TeamNum': 16798, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Redhawk Robotics'}]

i 1012
{'18274', '18575', '5044', '18802', '21810', '7163', '14134', '21523', '19668', '19901', '9838', '5553', '20374', '4155', '19588', '14671', '13806', '22561', '8638', '6042', '21684', '19590', '18577', '14906', '20375', '16505', '11354'}
[{'TeamNum': 4155, 'OPR': 115.539, 'Auto': 13.666, 'CCWM': 50.26, 'TeamName': "M.I.T (Muskogee's Innovative Team)"}, {'TeamNum': 19668, 'OPR': 111.253, 'Auto': 22.043, 'CCWM': 62.713, 'TeamName': 'HiveMind'}, {'TeamNum': 11354, 'OPR': 93.932, 'Auto': 15.999, 'CCWM': 58.876, 'TeamName': 'The Midnight Ostrich Runners'}, {'TeamNum': 21684, 'OPR': 90.546, 'Auto': 11.937, 'CCWM': 31.927, 'TeamName': 'ChouTime'}, {'TeamNum': 5553, 'OPR': 86.322, 'Auto': 15.471, 'CCWM': 19.679, 'TeamName': 'RoboComets'}, {'TeamNum': 18274, 'OPR': 83.82, 'Auto': 19.525, 'CCWM': 35.585, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 14906, 'OPR': 82.813, 'Auto': 14.202, 'CCWM': 16.335, 'TeamName': 'Leviathan Robotics'}, {'TeamNum': 8638, 'OPR': 69.275, 'Auto': 10.078, 'CCWM': 36.828, 'TeamName': 'tadpole'}, {'TeamNum': 18802, 'OPR': 64.654, 'Auto': 19.753, 'CCWM': 48.483, 'TeamName': 'Robo Renegades'}, {'TeamNum': 21810, 'OPR': 62.887, 'Auto': 11.534, 'CCWM': 9.896, 'TeamName': 'Collinsville Middle School'}, {'TeamNum': 7163, 'OPR': 54.758, 'Auto': 18.85, 'CCWM': -4.519, 'TeamName': 'The Bazinga Project'}, {'TeamNum': 16505, 'OPR': 51.115, 'Auto': 16.387, 'CCWM': 26.896, 'TeamName': 'Quantum '}, {'TeamNum': 19901, 'OPR': 47.185, 'Auto': -0.077, 'CCWM': -3.087, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 13806, 'OPR': 45.758, 'Auto': 8.404, 'CCWM': -7.13, 'TeamName': 'Project Agnizab'}, {'TeamNum': 14671, 'OPR': 36.164, 'Auto': -0.943, 'CCWM': -18.739, 'TeamName': 'inside joke'}, {'TeamNum': 6042, 'OPR': 29.428, 'Auto': 13.941, 'CCWM': -1.767, 'TeamName': 'Commandobots '}, {'TeamNum': 14134, 'OPR': 26.92, 'Auto': 3.518, 'CCWM': -17.115, 'TeamName': 'N.E.W.T.'}, {'TeamNum': 18577, 'OPR': 20.325, 'Auto': -0.424, 'CCWM': -30.855, 'TeamName': 'Pro Buffs1'}, {'TeamNum': 19590, 'OPR': 20.227, 'Auto': 4.501, 'CCWM': -31.97, 'TeamName': 'CyberNauts '}, {'TeamNum': 9838, 'OPR': 17.382, 'Auto': 9.788, 'CCWM': -24.774, 'TeamName': 'elopdat'}, {'TeamNum': 5044, 'OPR': 15.42, 'Auto': 2.518, 'CCWM': -53.865, 'TeamName': 'Black Pearl Robotics'}, {'TeamNum': 19588, 'OPR': 14.732, 'Auto': 0.144, 'CCWM': -33.54, 'TeamName': 'Starbots'}, {'TeamNum': 21523, 'OPR': 14.158, 'Auto': 4.148, 'CCWM': -21.621, 'TeamName': 'Team Phoenix '}, {'TeamNum': 22561, 'OPR': 8.609, 'Auto': 6.102, 'CCWM': -27.719, 'TeamName': 'Rana'}, {'TeamNum': 18575, 'OPR': 6.792, 'Auto': 2.651, 'CCWM': -40.942, 'TeamName': 'MPS Buffs'}, {'TeamNum': 20375, 'OPR': 4.224, 'Auto': -1.191, 'CCWM': -67.281, 'TeamName': 'BioTech Buffs1'}, {'TeamNum': 20374, 'OPR': 2.923, 'Auto': 0.691, 'CCWM': -11.938, 'TeamName': 'Power Buff Girls1'}]
USOKOKLALT
[{'TeamNum': 4155, 'OPR': 115.539, 'Auto': 13.666, 'CCWM': 50.26, 'TeamName': "M.I.T (Muskogee's Innovative Team)"}, {'TeamNum': 19668, 'OPR': 111.253, 'Auto': 22.043, 'CCWM': 62.713, 'TeamName': 'HiveMind'}, {'TeamNum': 11354, 'OPR': 93.932, 'Auto': 15.999, 'CCWM': 58.876, 'TeamName': 'The Midnight Ostrich Runners'}, {'TeamNum': 21684, 'OPR': 90.546, 'Auto': 11.937, 'CCWM': 31.927, 'TeamName': 'ChouTime'}, {'TeamNum': 5553, 'OPR': 86.322, 'Auto': 15.471, 'CCWM': 19.679, 'TeamName': 'RoboComets'}, {'TeamNum': 18274, 'OPR': 83.82, 'Auto': 19.525, 'CCWM': 35.585, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 14906, 'OPR': 82.813, 'Auto': 14.202, 'CCWM': 16.335, 'TeamName': 'Leviathan Robotics'}, {'TeamNum': 8638, 'OPR': 69.275, 'Auto': 10.078, 'CCWM': 36.828, 'TeamName': 'tadpole'}, {'TeamNum': 18802, 'OPR': 64.654, 'Auto': 19.753, 'CCWM': 48.483, 'TeamName': 'Robo Renegades'}, {'TeamNum': 21810, 'OPR': 62.887, 'Auto': 11.534, 'CCWM': 9.896, 'TeamName': 'Collinsville Middle School'}, {'TeamNum': 7163, 'OPR': 54.758, 'Auto': 18.85, 'CCWM': -4.519, 'TeamName': 'The Bazinga Project'}, {'TeamNum': 16505, 'OPR': 51.115, 'Auto': 16.387, 'CCWM': 26.896, 'TeamName': 'Quantum '}, {'TeamNum': 19901, 'OPR': 47.185, 'Auto': -0.077, 'CCWM': -3.087, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 13806, 'OPR': 45.758, 'Auto': 8.404, 'CCWM': -7.13, 'TeamName': 'Project Agnizab'}, {'TeamNum': 14671, 'OPR': 36.164, 'Auto': -0.943, 'CCWM': -18.739, 'TeamName': 'inside joke'}, {'TeamNum': 6042, 'OPR': 29.428, 'Auto': 13.941, 'CCWM': -1.767, 'TeamName': 'Commandobots '}, {'TeamNum': 14134, 'OPR': 26.92, 'Auto': 3.518, 'CCWM': -17.115, 'TeamName': 'N.E.W.T.'}, {'TeamNum': 18577, 'OPR': 20.325, 'Auto': -0.424, 'CCWM': -30.855, 'TeamName': 'Pro Buffs1'}, {'TeamNum': 19590, 'OPR': 20.227, 'Auto': 4.501, 'CCWM': -31.97, 'TeamName': 'CyberNauts '}, {'TeamNum': 9838, 'OPR': 17.382, 'Auto': 9.788, 'CCWM': -24.774, 'TeamName': 'elopdat'}, {'TeamNum': 5044, 'OPR': 15.42, 'Auto': 2.518, 'CCWM': -53.865, 'TeamName': 'Black Pearl Robotics'}, {'TeamNum': 19588, 'OPR': 14.732, 'Auto': 0.144, 'CCWM': -33.54, 'TeamName': 'Starbots'}, {'TeamNum': 21523, 'OPR': 14.158, 'Auto': 4.148, 'CCWM': -21.621, 'TeamName': 'Team Phoenix '}, {'TeamNum': 22561, 'OPR': 8.609, 'Auto': 6.102, 'CCWM': -27.719, 'TeamName': 'Rana'}, {'TeamNum': 18575, 'OPR': 6.792, 'Auto': 2.651, 'CCWM': -40.942, 'TeamName': 'MPS Buffs'}, {'TeamNum': 20375, 'OPR': 4.224, 'Auto': -1.191, 'CCWM': -67.281, 'TeamName': 'BioTech Buffs1'}, {'TeamNum': 20374, 'OPR': 2.923, 'Auto': 0.691, 'CCWM': -11.938, 'TeamName': 'Power Buff Girls1'}]
i 1013
{'22392', '16844', '20177', '20300', '22488', '16843', '13909', '8153', '13908', '15036', '13907'}
[{'TeamNum': 15036, 'OPR': 84.386, 'Auto': 21.218, 'CCWM': 83.035, 'TeamName': 'JavaDaHutt'}, {'TeamNum': 20300, 'OPR': 65.593, 'Auto': 19.628, 'CCWM': 47.67, 'TeamName': 'Cove 3'}, {'TeamNum': 16844, 'OPR': 41.979, 'Auto': 6.375, 'CCWM': 22.635, 'TeamName': 'Team #16844'}, {'TeamNum': 20177, 'OPR': 34.686, 'Auto': 13.905, 'CCWM': -7.044, 'TeamName': 'High Velocity'}, {'TeamNum': 22488, 'OPR': 30.134, 'Auto': 16.053, 'CCWM': 2.298, 'TeamName': 'Pilot Rock'}, {'TeamNum': 8153, 'OPR': 21.839, 'Auto': -1.066, 'CCWM': 11.433, 'TeamName': 'Team #8153'}, {'TeamNum': 13909, 'OPR': 13.098, 'Auto': 1.461, 'CCWM': -23.584, 'TeamName': 'Team #13909'}, {'TeamNum': 16843, 'OPR': 5.23, 'Auto': 0.895, 'CCWM': -27.182, 'TeamName': 'Team #16843'}, {'TeamNum': 22392, 'OPR': 5.221, 'Auto': -0.923, 'CCWM': -28.638, 'TeamName': 'Team #22392'}, {'TeamNum': 13908, 'OPR': -0.405, 'Auto': -2.994, 'CCWM': -52.448, 'TeamName': 'FBI'}, {'TeamNum': 13907, 'OPR': -0.53, 'Auto': -0.537, 'CCWM': -30.462, 'TeamName': 'GREMLINS '}]
USORCBLT
[{'TeamNum': 15036, 'OPR': 84.386, 'Auto': 21.218, 'CCWM': 83.035, 'TeamName': 'JavaDaHutt'}, {'TeamNum': 20300, 'OPR': 65.593, 'Auto': 19.628, 'CCWM': 47.67, 'TeamName': 'Cove 3'}, {'TeamNum': 16844, 'OPR': 41.979, 'Auto': 6.375, 'CCWM': 22.635, 'TeamName': 'Team #16844'}, {'TeamNum': 20177, 'OPR': 34.686, 'Auto': 13.905, 'CCWM': -7.044, 'TeamName': 'High Velocity'}, {'TeamNum': 22488, 'OPR': 30.134, 'Auto': 16.053, 'CCWM': 2.298, 'TeamName': 'Pilot Rock'}, {'TeamNum': 8153, 'OPR': 21.839, 'Auto': -1.066, 'CCWM': 11.433, 'TeamName': 'Team #8153'}, {'TeamNum': 13909, 'OPR': 13.098, 'Auto': 1.461, 'CCWM': -23.584, 'TeamName': 'Team #13909'}, {'TeamNum': 16843, 'OPR': 5.23, 'Auto': 0.895, 'CCWM': -27.182, 'TeamName': 'Team #16843'}, {'TeamNum': 22392, 'OPR': 5.221, 'Auto': -0.923, 'CCWM': -28.638, 'TeamName': 'Team #22392'}, {'TeamNum': 13908, 'OPR': -0.405, 'Auto': -2.994, 'CCWM': -52.448, 'TeamName': 'FBI'}, {'TeamNum': 13907, 'OPR': -0.53, 'Auto': -0.537, 'CCWM': -30.462, 'TeamName': 'GREMLINS '}]
i 1014
{'7878', '13784', '14687', '4511', '20431', '12076', '13727', '19856', '22506', '15562', '750', '15365', '10428', '22515', '9470', '8161', '22559', '13439', '3093', '3963', '7100', '11547', '8892', '13189'}
[{'TeamNum': 13439, 'OPR': 66.879, 'Auto': 17.651, 'CCWM': 29.526, 'TeamName': 'The Atomic Paperclips'}, {'TeamNum': 750, 'OPR': 63.188, 'Auto': 18.773, 'CCWM': 42.785, 'TeamName': 'Gears in Motion'}, {'TeamNum': 4511, 'OPR': 58.694, 'Auto': 17.592, 'CCWM': 11.232, 'TeamName': 'Maker Industries'}, {'TeamNum': 7878, 'OPR': 48.408, 'Auto': 12.571, 'CCWM': 31.182, 'TeamName': 'Cougarbots'}, {'TeamNum': 8161, 'OPR': 47.142, 'Auto': 13.793, 'CCWM': -4.699, 'TeamName': 'Robogoats'}, {'TeamNum': 13784, 'OPR': 45.609, 'Auto': 21.692, 'CCWM': 20.45, 'TeamName': 'Lightning'}, {'TeamNum': 9470, 'OPR': 45.57, 'Auto': 12.864, 'CCWM': 35.096, 'TeamName': 'The Mjoln-Gears'}, {'TeamNum': 3093, 'OPR': 41.576, 'Auto': 2.675, 'CCWM': -10.167, 'TeamName': 'The Metal Mercenaries'}, {'TeamNum': 13727, 'OPR': 40.921, 'Auto': 5.213, 'CCWM': 0.314, 'TeamName': 'Juntos Unidos'}, {'TeamNum': 22506, 'OPR': 40.74, 'Auto': 9.599, 'CCWM': -15.003, 'TeamName': 'JagWires'}, {'TeamNum': 8892, 'OPR': 39.479, 'Auto': 20.158, 'CCWM': -13.804, 'TeamName': 'PHRED'}, {'TeamNum': 10428, 'OPR': 36.562, 'Auto': -2.147, 'CCWM': 5.527, 'TeamName': 'Ace Of Spades'}, {'TeamNum': 11547, 'OPR': 35.507, 'Auto': -0.542, 'CCWM': 12.04, 'TeamName': 'Tech No Logic'}, {'TeamNum': 12076, 'OPR': 32.068, 'Auto': 1.99, 'CCWM': 0.755, 'TeamName': 'Iron Hearts'}, {'TeamNum': 13189, 'OPR': 29.412, 'Auto': -0.856, 'CCWM': 3.491, 'TeamName': 'Scorpio'}, {'TeamNum': 22559, 'OPR': 27.024, 'Auto': 1.3, 'CCWM': -17.21, 'TeamName': 'Winkiedinks'}, {'TeamNum': 15365, 'OPR': 24.672, 'Auto': 7.43, 'CCWM': -12.018, 'TeamName': 'Lightning 42'}, {'TeamNum': 19856, 'OPR': 22.845, 'Auto': 14.513, 'CCWM': -3.158, 'TeamName': 'Almost Reliable Robotics'}, {'TeamNum': 22515, 'OPR': 19.73, 'Auto': 7.27, 'CCWM': -17.242, 'TeamName': 'Mechanical Platypuses'}, {'TeamNum': 3963, 'OPR': 17.94, 'Auto': 3.699, 'CCWM': -11.954, 'TeamName': 'Iron Legion'}, {'TeamNum': 15562, 'OPR': 16.875, 'Auto': 5.295, 'CCWM': -23.083, 'TeamName': 'Lightning 43'}, {'TeamNum': 14687, 'OPR': 14.63, 'Auto': 14.405, 'CCWM': -10.752, 'TeamName': 'Cybernetic Chaos'}, {'TeamNum': 20431, 'OPR': 14.142, 'Auto': 4.469, 'CCWM': -29.377, 'TeamName': 'X-RAID'}, {'TeamNum': 7100, 'OPR': 8.988, 'Auto': 4.193, 'CCWM': -23.931, 'TeamName': 'Good Enough'}]
USORPOSQ
[{'TeamNum': 13439, 'OPR': 66.879, 'Auto': 17.651, 'CCWM': 29.526, 'TeamName': 'The Atomic Paperclips'}, {'TeamNum': 750, 'OPR': 63.188, 'Auto': 18.773, 'CCWM': 42.785, 'TeamName': 'Gears in Motion'}, {'TeamNum': 4511, 'OPR': 58.694, 'Auto': 17.592, 'CCWM': 11.232, 'TeamName': 'Maker Industries'}, {'TeamNum': 7878, 'OPR': 48.408, 'Auto': 12.571, 'CCWM': 31.182, 'TeamName': 'Cougarbots'}, {'TeamNum': 8161, 'OPR': 47.142, 'Auto': 13.793, 'CCWM': -4.699, 'TeamName': 'Robogoats'}, {'TeamNum': 13784, 'OPR': 45.609, 'Auto': 21.692, 'CCWM': 20.45, 'TeamName': 'Lightning'}, {'TeamNum': 9470, 'OPR': 45.57, 'Auto': 12.864, 'CCWM': 35.096, 'TeamName': 'The Mjoln-Gears'}, {'TeamNum': 3093, 'OPR': 41.576, 'Auto': 2.675, 'CCWM': -10.167, 'TeamName': 'The Metal Mercenaries'}, {'TeamNum': 13727, 'OPR': 40.921, 'Auto': 5.213, 'CCWM': 0.314, 'TeamName': 'Juntos Unidos'}, {'TeamNum': 22506, 'OPR': 40.74, 'Auto': 9.599, 'CCWM': -15.003, 'TeamName': 'JagWires'}, {'TeamNum': 8892, 'OPR': 39.479, 'Auto': 20.158, 'CCWM': -13.804, 'TeamName': 'PHRED'}, {'TeamNum': 10428, 'OPR': 36.562, 'Auto': -2.147, 'CCWM': 5.527, 'TeamName': 'Ace Of Spades'}, {'TeamNum': 11547, 'OPR': 35.507, 'Auto': -0.542, 'CCWM': 12.04, 'TeamName': 'Tech No Logic'}, {'TeamNum': 12076, 'OPR': 32.068, 'Auto': 1.99, 'CCWM': 0.755, 'TeamName': 'Iron Hearts'}, {'TeamNum': 13189, 'OPR': 29.412, 'Auto': -0.856, 'CCWM': 3.491, 'TeamName': 'Scorpio'}, {'TeamNum': 22559, 'OPR': 27.024, 'Auto': 1.3, 'CCWM': -17.21, 'TeamName': 'Winkiedinks'}, {'TeamNum': 15365, 'OPR': 24.672, 'Auto': 7.43, 'CCWM': -12.018, 'TeamName': 'Lightning 42'}, {'TeamNum': 19856, 'OPR': 22.845, 'Auto': 14.513, 'CCWM': -3.158, 'TeamName': 'Almost Reliable Robotics'}, {'TeamNum': 22515, 'OPR': 19.73, 'Auto': 7.27, 'CCWM': -17.242, 'TeamName': 'Mechanical Platypuses'}, {'TeamNum': 3963, 'OPR': 17.94, 'Auto': 3.699, 'CCWM': -11.954, 'TeamName': 'Iron Legion'}, {'TeamNum': 15562, 'OPR': 16.875, 'Auto': 5.295, 'CCWM': -23.083, 'TeamName': 'Lightning 43'}, {'TeamNum': 14687, 'OPR': 14.63, 'Auto': 14.405, 'CCWM': -10.752, 'TeamName': 'Cybernetic Chaos'}, {'TeamNum': 20431, 'OPR': 14.142, 'Auto': 4.469, 'CCWM': -29.377, 'TeamName': 'X-RAID'}, {'TeamNum': 7100, 'OPR': 8.988, 'Auto': 4.193, 'CCWM': -23.931, 'TeamName': 'Good Enough'}]

i 1015
{'17388', '18035', '16776', '21620', '6549', '16564', '21619', '16354', '7786', '20079', '16269', '22828', '20729', '14382', '21364', '22311', '10333', '16762', '20223', '9618', '20201', '9791', '11349', '14464', '10353'}
[{'TeamNum': 11349, 'OPR': 97.156, 'Auto': 32.116, 'CCWM': 60.944, 'TeamName': 'VorTech'}, {'TeamNum': 16269, 'OPR': 84.308, 'Auto': 28.723, 'CCWM': 27.035, 'TeamName': 'Guthrie Geeks'}, {'TeamNum': 22828, 'OPR': 82.963, 'Auto': 25.764, 'CCWM': 42.645, 'TeamName': 'Jingle Bells'}, {'TeamNum': 10333, 'OPR': 79.666, 'Auto': 20.085, 'CCWM': 41.472, 'TeamName': 'TechSpark'}, {'TeamNum': 9791, 'OPR': 68.602, 'Auto': 17.115, 'CCWM': 4.233, 'TeamName': 'Divide by Zero'}, {'TeamNum': 6549, 'OPR': 67.945, 'Auto': 25.975, 'CCWM': 35.245, 'TeamName': 'Whoa!Bots'}, {'TeamNum': 20079, 'OPR': 66.483, 'Auto': 13.834, 'CCWM': -12.771, 'TeamName': 'MARS: Ingenuity...'}, {'TeamNum': 20201, 'OPR': 62.169, 'Auto': 10.31, 'CCWM': 19.88, 'TeamName': 'Centre county 4H Robotics- The Mighty Ducks'}, {'TeamNum': 14464, 'OPR': 59.858, 'Auto': 9.152, 'CCWM': -17.095, 'TeamName': 'BotBusters'}, {'TeamNum': 17388, 'OPR': 57.302, 'Auto': 11.324, 'CCWM': 7.915, 'TeamName': 'Red Tornadoes'}, {'TeamNum': 16564, 'OPR': 56.464, 'Auto': 14.019, 'CCWM': 23.187, 'TeamName': 'Digital Devils'}, {'TeamNum': 18035, 'OPR': 47.916, 'Auto': 12.266, 'CCWM': -11.926, 'TeamName': 'Reconnecting...'}, {'TeamNum': 16762, 'OPR': 46.965, 'Auto': 18.258, 'CCWM': -5.909, 'TeamName': 'Raider Robotics'}, {'TeamNum': 10353, 'OPR': 45.583, 'Auto': 13.498, 'CCWM': -5.324, 'TeamName': 'Metal Works'}, {'TeamNum': 22311, 'OPR': 44.874, 'Auto': 17.057, 'CCWM': 1.908, 'TeamName': 'CC4H Robotics - Robocougars'}, {'TeamNum': 21364, 'OPR': 44.626, 'Auto': 19.303, 'CCWM': -40.778, 'TeamName': 'FIRST Try'}, {'TeamNum': 9618, 'OPR': 44.494, 'Auto': 26.32, 'CCWM': -9.873, 'TeamName': 'Cyber Spartans'}, {'TeamNum': 20729, 'OPR': 43.69, 'Auto': 5.631, 'CCWM': 5.837, 'TeamName': 'Basement Botics'}, {'TeamNum': 7786, 'OPR': 41.914, 'Auto': 6.99, 'CCWM': 15.59, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 20223, 'OPR': 40.402, 'Auto': 13.549, 'CCWM': -49.342, 'TeamName': 'USC Dynamics'}, {'TeamNum': 16776, 'OPR': 40.008, 'Auto': 10.525, 'CCWM': -25.003, 'TeamName': 'MARS: Opportunity S.T.E.A.M. punk!'}, {'TeamNum': 21619, 'OPR': 23.045, 'Auto': 1.169, 'CCWM': -29.113, 'TeamName': 'Alternating Current'}, {'TeamNum': 14382, 'OPR': 22.65, 'Auto': 6.813, 'CCWM': -14.026, 'TeamName': 'CC4H Robotics - Flex Force 1'}, {'TeamNum': 21620, 'OPR': 14.144, 'Auto': -2.65, 'CCWM': -34.7, 'TeamName': 'Direct Current'}, {'TeamNum': 16354, 'OPR': 7.765, 'Auto': -6.973, 'CCWM': -48.364, 'TeamName': 'Phobos Ares Robotics Team'}]
USPALAQ
[{'TeamNum': 11349, 'OPR': 97.156, 'Auto': 32.116, 'CCWM': 60.944, 'TeamName': 'VorTech'}, {'TeamNum': 16269, 'OPR': 84.308, 'Auto': 28.723, 'CCWM': 27.035, 'TeamName': 'Guthrie Geeks'}, {'TeamNum': 22828, 'OPR': 82.963, 'Auto': 25.764, 'CCWM': 42.645, 'TeamName': 'Jingle Bells'}, {'TeamNum': 10333, 'OPR': 79.666, 'Auto': 20.085, 'CCWM': 41.472, 'TeamName': 'TechSpark'}, {'TeamNum': 9791, 'OPR': 68.602, 'Auto': 17.115, 'CCWM': 4.233, 'TeamName': 'Divide by Zero'}, {'TeamNum': 6549, 'OPR': 67.945, 'Auto': 25.975, 'CCWM': 35.245, 'TeamName': 'Whoa!Bots'}, {'TeamNum': 20079, 'OPR': 66.483, 'Auto': 13.834, 'CCWM': -12.771, 'TeamName': 'MARS: Ingenuity...'}, {'TeamNum': 20201, 'OPR': 62.169, 'Auto': 10.31, 'CCWM': 19.88, 'TeamName': 'Centre county 4H Robotics- The Mighty Ducks'}, {'TeamNum': 14464, 'OPR': 59.858, 'Auto': 9.152, 'CCWM': -17.095, 'TeamName': 'BotBusters'}, {'TeamNum': 17388, 'OPR': 57.302, 'Auto': 11.324, 'CCWM': 7.915, 'TeamName': 'Red Tornadoes'}, {'TeamNum': 16564, 'OPR': 56.464, 'Auto': 14.019, 'CCWM': 23.187, 'TeamName': 'Digital Devils'}, {'TeamNum': 18035, 'OPR': 47.916, 'Auto': 12.266, 'CCWM': -11.926, 'TeamName': 'Reconnecting...'}, {'TeamNum': 16762, 'OPR': 46.965, 'Auto': 18.258, 'CCWM': -5.909, 'TeamName': 'Raider Robotics'}, {'TeamNum': 10353, 'OPR': 45.583, 'Auto': 13.498, 'CCWM': -5.324, 'TeamName': 'Metal Works'}, {'TeamNum': 22311, 'OPR': 44.874, 'Auto': 17.057, 'CCWM': 1.908, 'TeamName': 'CC4H Robotics - Robocougars'}, {'TeamNum': 21364, 'OPR': 44.626, 'Auto': 19.303, 'CCWM': -40.778, 'TeamName': 'FIRST Try'}, {'TeamNum': 9618, 'OPR': 44.494, 'Auto': 26.32, 'CCWM': -9.873, 'TeamName': 'Cyber Spartans'}, {'TeamNum': 20729, 'OPR': 43.69, 'Auto': 5.631, 'CCWM': 5.837, 'TeamName': 'Basement Botics'}, {'TeamNum': 7786, 'OPR': 41.914, 'Auto': 6.99, 'CCWM': 15.59, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 20223, 'OPR': 40.402, 'Auto': 13.549, 'CCWM': -49.342, 'TeamName': 'USC Dynamics'}, {'TeamNum': 16776, 'OPR': 40.008, 'Auto': 10.525, 'CCWM': -25.003, 'TeamName': 'MARS: Opportunity S.T.E.A.M. punk!'}, {'TeamNum': 21619, 'OPR': 23.045, 'Auto': 1.169, 'CCWM': -29.113, 'TeamName': 'Alternating Current'}, {'TeamNum': 14382, 'OPR': 22.65, 'Auto': 6.813, 'CCWM': -14.026, 'TeamName': 'CC4H Robotics - Flex Force 1'}, {'TeamNum': 21620, 'OPR': 14.144, 'Auto': -2.65, 'CCWM': -34.7, 'TeamName': 'Direct Current'}, {'TeamNum': 16354, 'OPR': 7.765, 'Auto': -6.973, 'CCWM': -48.364, 'TeamName': 'Phobos Ares Robotics Team'}]
i 1016
{'9121', '12517', '19707', '22199', '22534', '772', '3641', '327', '13196', '18069', '18984', '7021', '22972', '11841', '11454', '13900', '20835', '15296'}
[{'TeamNum': 327, 'OPR': 68.033, 'Auto': 15.073, 'CCWM': 29.113, 'TeamName': 'The Lobotomists'}, {'TeamNum': 22534, 'OPR': 56.128, 'Auto': 21.68, 'CCWM': 23.798, 'TeamName': 'Area 52.1'}, {'TeamNum': 13900, 'OPR': 55.337, 'Auto': 15.658, 'CCWM': 20.371, 'TeamName': 'Iron Horses'}, {'TeamNum': 18984, 'OPR': 54.024, 'Auto': 17.33, 'CCWM': 23.815, 'TeamName': 'Hurricanes505'}, {'TeamNum': 772, 'OPR': 44.952, 'Auto': 17.532, 'CCWM': 28.928, 'TeamName': 'Golden Govies'}, {'TeamNum': 3641, 'OPR': 36.162, 'Auto': 13.957, 'CCWM': 20.484, 'TeamName': 'PPS Robotics'}, {'TeamNum': 11454, 'OPR': 35.015, 'Auto': 12.158, 'CCWM': 7.92, 'TeamName': 'Penguineers'}, {'TeamNum': 22199, 'OPR': 32.062, 'Auto': 5.595, 'CCWM': 5.466, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 22972, 'OPR': 30.692, 'Auto': 1.996, 'CCWM': 36.417, 'TeamName': 'White Rice '}, {'TeamNum': 9121, 'OPR': 30.656, 'Auto': -1.21, 'CCWM': -5.605, 'TeamName': 'Falcon Force'}, {'TeamNum': 11841, 'OPR': 28.836, 'Auto': 17.487, 'CCWM': -14.821, 'TeamName': 'STEAM Punks'}, {'TeamNum': 12517, 'OPR': 27.187, 'Auto': 4.252, 'CCWM': -1.565, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 19707, 'OPR': 22.952, 'Auto': 1.532, 'CCWM': -7.872, 'TeamName': 'NanoHawks'}, {'TeamNum': 13196, 'OPR': 22.858, 'Auto': -3.672, 'CCWM': -6.637, 'TeamName': 'BA Robotics'}, {'TeamNum': 7021, 'OPR': 10.232, 'Auto': -0.777, 'CCWM': -48.676, 'TeamName': 'RoboEagles'}, {'TeamNum': 15296, 'OPR': 10.152, 'Auto': 0.667, 'CCWM': -26.398, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 18069, 'OPR': -4.874, 'Auto': -7.278, 'CCWM': -42.611, 'TeamName': 'Java Dragons'}, {'TeamNum': 20835, 'OPR': -9.739, 'Auto': -0.48, 'CCWM': -42.127, 'TeamName': 'Burg Bots'}]
USSCCHQ
[{'TeamNum': 327, 'OPR': 68.033, 'Auto': 15.073, 'CCWM': 29.113, 'TeamName': 'The Lobotomists'}, {'TeamNum': 22534, 'OPR': 56.128, 'Auto': 21.68, 'CCWM': 23.798, 'TeamName': 'Area 52.1'}, {'TeamNum': 13900, 'OPR': 55.337, 'Auto': 15.658, 'CCWM': 20.371, 'TeamName': 'Iron Horses'}, {'TeamNum': 18984, 'OPR': 54.024, 'Auto': 17.33, 'CCWM': 23.815, 'TeamName': 'Hurricanes505'}, {'TeamNum': 772, 'OPR': 44.952, 'Auto': 17.532, 'CCWM': 28.928, 'TeamName': 'Golden Govies'}, {'TeamNum': 3641, 'OPR': 36.162, 'Auto': 13.957, 'CCWM': 20.484, 'TeamName': 'PPS Robotics'}, {'TeamNum': 11454, 'OPR': 35.015, 'Auto': 12.158, 'CCWM': 7.92, 'TeamName': 'Penguineers'}, {'TeamNum': 22199, 'OPR': 32.062, 'Auto': 5.595, 'CCWM': 5.466, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 22972, 'OPR': 30.692, 'Auto': 1.996, 'CCWM': 36.417, 'TeamName': 'White Rice '}, {'TeamNum': 9121, 'OPR': 30.656, 'Auto': -1.21, 'CCWM': -5.605, 'TeamName': 'Falcon Force'}, {'TeamNum': 11841, 'OPR': 28.836, 'Auto': 17.487, 'CCWM': -14.821, 'TeamName': 'STEAM Punks'}, {'TeamNum': 12517, 'OPR': 27.187, 'Auto': 4.252, 'CCWM': -1.565, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 19707, 'OPR': 22.952, 'Auto': 1.532, 'CCWM': -7.872, 'TeamName': 'NanoHawks'}, {'TeamNum': 13196, 'OPR': 22.858, 'Auto': -3.672, 'CCWM': -6.637, 'TeamName': 'BA Robotics'}, {'TeamNum': 7021, 'OPR': 10.232, 'Auto': -0.777, 'CCWM': -48.676, 'TeamName': 'RoboEagles'}, {'TeamNum': 15296, 'OPR': 10.152, 'Auto': 0.667, 'CCWM': -26.398, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 18069, 'OPR': -4.874, 'Auto': -7.278, 'CCWM': -42.611, 'TeamName': 'Java Dragons'}, {'TeamNum': 20835, 'OPR': -9.739, 'Auto': -0.48, 'CCWM': -42.127, 'TeamName': 'Burg Bots'}]

i 1017
{'21235', '17011', '21834', '22191', '17385', '13227', '20483', '21474', '14904', '11419', '12791', '19991', '20410', '18121', '22038', '8406', '21683', '19564', '8204', '16756', '14962', '21813', '13539', '15877', '13542', '20336', '21870', '11085', '9010', '22527', '11676'}
[{'TeamNum': 21870, 'OPR': 104.188, 'Auto': 26.817, 'CCWM': 100.923, 'TeamName': 'Pro Pythons'}, {'TeamNum': 11085, 'OPR': 87.545, 'Auto': 24.451, 'CCWM': 43.605, 'TeamName': 'MHS Mad Hackers'}, {'TeamNum': 20336, 'OPR': 78.722, 'Auto': 20.737, 'CCWM': 55.589, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 16756, 'OPR': 78.168, 'Auto': 13.484, 'CCWM': 13.047, 'TeamName': 'Raider Prime'}, {'TeamNum': 11676, 'OPR': 77.536, 'Auto': 29.636, 'CCWM': 26.57, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 13539, 'OPR': 77.532, 'Auto': 19.214, 'CCWM': 21.11, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 8204, 'OPR': 73.163, 'Auto': 11.385, 'CCWM': 44.769, 'TeamName': 'Blue Machine'}, {'TeamNum': 21474, 'OPR': 71.845, 'Auto': 15.594, 'CCWM': 10.514, 'TeamName': 'SynTech'}, {'TeamNum': 20410, 'OPR': 69.866, 'Auto': 9.336, 'CCWM': 30.054, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 11419, 'OPR': 67.374, 'Auto': 21.368, 'CCWM': -3.326, 'TeamName': 'Jasper Jaguar Robotics Green'}, {'TeamNum': 18121, 'OPR': 65.166, 'Auto': 11.913, 'CCWM': -6.476, 'TeamName': 'MiT - Mercenaries in Training'}, {'TeamNum': 21813, 'OPR': 64.978, 'Auto': 18.034, 'CCWM': 18.979, 'TeamName': 'Pro2type'}, {'TeamNum': 13542, 'OPR': 64.563, 'Auto': 22.364, 'CCWM': -0.669, 'TeamName': 'RoboChargers - Typhoon - Blue'}, {'TeamNum': 15877, 'OPR': 55.106, 'Auto': 9.979, 'CCWM': 40.588, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 17011, 'OPR': 54.822, 'Auto': 22.143, 'CCWM': -4.743, 'TeamName': 'Mercenaries'}, {'TeamNum': 19564, 'OPR': 52.053, 'Auto': 20.607, 'CCWM': 17.972, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 8406, 'OPR': 51.697, 'Auto': 3.419, 'CCWM': 3.731, 'TeamName': 'The Horde'}, {'TeamNum': 14904, 'OPR': 45.815, 'Auto': 4.782, 'CCWM': -16.049, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 22038, 'OPR': 44.464, 'Auto': 6.474, 'CCWM': -23.334, 'TeamName': 'CaptainTech'}, {'TeamNum': 13227, 'OPR': 39.865, 'Auto': 13.186, 'CCWM': -27.615, 'TeamName': 'Mechanicats'}, {'TeamNum': 22527, 'OPR': 39.165, 'Auto': 0.518, 'CCWM': 17.781, 'TeamName': 'RoboChargers - Cyan'}, {'TeamNum': 12791, 'OPR': 35.101, 'Auto': 15.671, 'CCWM': -44.868, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 9010, 'OPR': 33.64, 'Auto': 9.201, 'CCWM': -16.192, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 21235, 'OPR': 33.125, 'Auto': 15.455, 'CCWM': -8.538, 'TeamName': 'SHARK!'}, {'TeamNum': 14962, 'OPR': 32.331, 'Auto': 5.647, 'CCWM': -46.579, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 19991, 'OPR': 24.108, 'Auto': -6.999, 'CCWM': -16.914, 'TeamName': 'Chuckleheads'}, {'TeamNum': 22191, 'OPR': 21.495, 'Auto': 12.012, 'CCWM': -53.534, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 21683, 'OPR': 20.342, 'Auto': 7.858, 'CCWM': -66.668, 'TeamName': 'Titan Robotics'}, {'TeamNum': 21834, 'OPR': 19.73, 'Auto': 3.814, 'CCWM': -26.044, 'TeamName': 'EPIC Adventurer'}, {'TeamNum': 20483, 'OPR': 19.697, 'Auto': 14.25, 'CCWM': -46.612, 'TeamName': 'Wall East'}, {'TeamNum': 17385, 'OPR': 18.025, 'Auto': 6.014, 'CCWM': -31.547, 'TeamName': 'MCA Horsepower - Blue'}]
USTXNOLTSQ
[{'TeamNum': 21870, 'OPR': 104.188, 'Auto': 26.817, 'CCWM': 100.923, 'TeamName': 'Pro Pythons'}, {'TeamNum': 11085, 'OPR': 87.545, 'Auto': 24.451, 'CCWM': 43.605, 'TeamName': 'MHS Mad Hackers'}, {'TeamNum': 20336, 'OPR': 78.722, 'Auto': 20.737, 'CCWM': 55.589, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 16756, 'OPR': 78.168, 'Auto': 13.484, 'CCWM': 13.047, 'TeamName': 'Raider Prime'}, {'TeamNum': 11676, 'OPR': 77.536, 'Auto': 29.636, 'CCWM': 26.57, 'TeamName': 'The ARKAtechs'}, {'TeamNum': 13539, 'OPR': 77.532, 'Auto': 19.214, 'CCWM': 21.11, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 8204, 'OPR': 73.163, 'Auto': 11.385, 'CCWM': 44.769, 'TeamName': 'Blue Machine'}, {'TeamNum': 21474, 'OPR': 71.845, 'Auto': 15.594, 'CCWM': 10.514, 'TeamName': 'SynTech'}, {'TeamNum': 20410, 'OPR': 69.866, 'Auto': 9.336, 'CCWM': 30.054, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 11419, 'OPR': 67.374, 'Auto': 21.368, 'CCWM': -3.326, 'TeamName': 'Jasper Jaguar Robotics Green'}, {'TeamNum': 18121, 'OPR': 65.166, 'Auto': 11.913, 'CCWM': -6.476, 'TeamName': 'MiT - Mercenaries in Training'}, {'TeamNum': 21813, 'OPR': 64.978, 'Auto': 18.034, 'CCWM': 18.979, 'TeamName': 'Pro2type'}, {'TeamNum': 13542, 'OPR': 64.563, 'Auto': 22.364, 'CCWM': -0.669, 'TeamName': 'RoboChargers - Typhoon - Blue'}, {'TeamNum': 15877, 'OPR': 55.106, 'Auto': 9.979, 'CCWM': 40.588, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 17011, 'OPR': 54.822, 'Auto': 22.143, 'CCWM': -4.743, 'TeamName': 'Mercenaries'}, {'TeamNum': 19564, 'OPR': 52.053, 'Auto': 20.607, 'CCWM': 17.972, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 8406, 'OPR': 51.697, 'Auto': 3.419, 'CCWM': 3.731, 'TeamName': 'The Horde'}, {'TeamNum': 14904, 'OPR': 45.815, 'Auto': 4.782, 'CCWM': -16.049, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 22038, 'OPR': 44.464, 'Auto': 6.474, 'CCWM': -23.334, 'TeamName': 'CaptainTech'}, {'TeamNum': 13227, 'OPR': 39.865, 'Auto': 13.186, 'CCWM': -27.615, 'TeamName': 'Mechanicats'}, {'TeamNum': 22527, 'OPR': 39.165, 'Auto': 0.518, 'CCWM': 17.781, 'TeamName': 'RoboChargers - Cyan'}, {'TeamNum': 12791, 'OPR': 35.101, 'Auto': 15.671, 'CCWM': -44.868, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 9010, 'OPR': 33.64, 'Auto': 9.201, 'CCWM': -16.192, 'TeamName': 'Robotic Rangers'}, {'TeamNum': 21235, 'OPR': 33.125, 'Auto': 15.455, 'CCWM': -8.538, 'TeamName': 'SHARK!'}, {'TeamNum': 14962, 'OPR': 32.331, 'Auto': 5.647, 'CCWM': -46.579, 'TeamName': 'Sprinkling Pixie Dust'}, {'TeamNum': 19991, 'OPR': 24.108, 'Auto': -6.999, 'CCWM': -16.914, 'TeamName': 'Chuckleheads'}, {'TeamNum': 22191, 'OPR': 21.495, 'Auto': 12.012, 'CCWM': -53.534, 'TeamName': 'Lakehill Mononicles'}, {'TeamNum': 21683, 'OPR': 20.342, 'Auto': 7.858, 'CCWM': -66.668, 'TeamName': 'Titan Robotics'}, {'TeamNum': 21834, 'OPR': 19.73, 'Auto': 3.814, 'CCWM': -26.044, 'TeamName': 'EPIC Adventurer'}, {'TeamNum': 20483, 'OPR': 19.697, 'Auto': 14.25, 'CCWM': -46.612, 'TeamName': 'Wall East'}, {'TeamNum': 17385, 'OPR': 18.025, 'Auto': 6.014, 'CCWM': -31.547, 'TeamName': 'MCA Horsepower - Blue'}]
i 1018
{'11986', '19957', '18801', '13755', '17977', '18570', '22304', '21780', '17332', '20145', '19955', '19956', '22306', '16617', '17028', '19782', '18503', '19717', '18838', '21848', '16730', '12398', '17191', '9778', '22952', '14608', '17198'}
[{'TeamNum': 16617, 'OPR': 149.183, 'Auto': 25.86, 'CCWM': 86.799, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 18570, 'OPR': 113.893, 'Auto': 29.163, 'CCWM': 75.689, 'TeamName': 'Swift PowerMech'}, {'TeamNum': 19955, 'OPR': 98.419, 'Auto': 13.477, 'CCWM': 57.266, 'TeamName': 'Robo Rangers'}, {'TeamNum': 11986, 'OPR': 92.737, 'Auto': 29.952, 'CCWM': -4.327, 'TeamName': 'Code Blue'}, {'TeamNum': 22952, 'OPR': 82.275, 'Auto': 15.041, 'CCWM': 1.114, 'TeamName': 'Dauntless'}, {'TeamNum': 13755, 'OPR': 61.4, 'Auto': 10.513, 'CCWM': 44.362, 'TeamName': 'Robocat'}, {'TeamNum': 19957, 'OPR': 58.08, 'Auto': 15.28, 'CCWM': -9.029, 'TeamName': 'Khaos'}, {'TeamNum': 17028, 'OPR': 57.693, 'Auto': 7.411, 'CCWM': 26.498, 'TeamName': 'DuMoore Robotics'}, {'TeamNum': 16730, 'OPR': 56.679, 'Auto': 0.272, 'CCWM': -0.299, 'TeamName': 'Cat-alytic Converters'}, {'TeamNum': 9778, 'OPR': 54.857, 'Auto': 1.995, 'CCWM': 6.836, 'TeamName': 'Robotic Chinchillas'}, {'TeamNum': 18838, 'OPR': 48.62, 'Auto': 26.28, 'CCWM': -50.365, 'TeamName': "Robo's Pit Crew"}, {'TeamNum': 21780, 'OPR': 46.91, 'Auto': 16.231, 'CCWM': 3.846, 'TeamName': 'Longhorn Robotics'}, {'TeamNum': 19782, 'OPR': 45.951, 'Auto': 19.658, 'CCWM': -18.291, 'TeamName': 'Hart Robotics'}, {'TeamNum': 20145, 'OPR': 44.944, 'Auto': 2.952, 'CCWM': 12.813, 'TeamName': 'Wildcat Robotics - 2'}, {'TeamNum': 12398, 'OPR': 41.959, 'Auto': 9.984, 'CCWM': -17.895, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 19956, 'OPR': 41.629, 'Auto': 3.921, 'CCWM': -2.446, 'TeamName': 'Mechanical Mayhem'}, {'TeamNum': 17332, 'OPR': 41.331, 'Auto': -4.374, 'CCWM': -11.353, 'TeamName': 'Wildcat Robotics - 3'}, {'TeamNum': 18801, 'OPR': 37.979, 'Auto': 4.015, 'CCWM': 15.618, 'TeamName': 'Crazy Hat People'}, {'TeamNum': 17198, 'OPR': 35.36, 'Auto': 16.056, 'CCWM': -18.725, 'TeamName': 'Wildcat Robotics 1'}, {'TeamNum': 22304, 'OPR': 32.588, 'Auto': 3.323, 'CCWM': -50.537, 'TeamName': 'Bomb City Bots Gold'}, {'TeamNum': 22306, 'OPR': 32.5, 'Auto': 1.27, 'CCWM': 6.092, 'TeamName': 'Bomb City Bots White'}, {'TeamNum': 14608, 'OPR': 32.42, 'Auto': 13.864, 'CCWM': 6.659, 'TeamName': 'SunrayBotCats'}, {'TeamNum': 18503, 'OPR': 27.788, 'Auto': 1.614, 'CCWM': 20.209, 'TeamName': 'The Well Team 3'}, {'TeamNum': 19717, 'OPR': 12.84, 'Auto': -3.266, 'CCWM': -41.15, 'TeamName': 'Bomb City Bots Blue'}, {'TeamNum': 17977, 'OPR': 11.049, 'Auto': -0.675, 'CCWM': -33.415, 'TeamName': 'Omni-Future'}, {'TeamNum': 17191, 'OPR': 8.852, 'Auto': 0.851, 'CCWM': -41.728, 'TeamName': 'CMS Robot Designers - 1'}, {'TeamNum': 21848, 'OPR': 7.992, 'Auto': 0.718, 'CCWM': -60.496, 'TeamName': 'DuMoore Robotics 2.0'}]
USTXWPAMLT
[{'TeamNum': 16617, 'OPR': 149.183, 'Auto': 25.86, 'CCWM': 86.799, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 18570, 'OPR': 113.893, 'Auto': 29.163, 'CCWM': 75.689, 'TeamName': 'Swift PowerMech'}, {'TeamNum': 19955, 'OPR': 98.419, 'Auto': 13.477, 'CCWM': 57.266, 'TeamName': 'Robo Rangers'}, {'TeamNum': 11986, 'OPR': 92.737, 'Auto': 29.952, 'CCWM': -4.327, 'TeamName': 'Code Blue'}, {'TeamNum': 22952, 'OPR': 82.275, 'Auto': 15.041, 'CCWM': 1.114, 'TeamName': 'Dauntless'}, {'TeamNum': 13755, 'OPR': 61.4, 'Auto': 10.513, 'CCWM': 44.362, 'TeamName': 'Robocat'}, {'TeamNum': 19957, 'OPR': 58.08, 'Auto': 15.28, 'CCWM': -9.029, 'TeamName': 'Khaos'}, {'TeamNum': 17028, 'OPR': 57.693, 'Auto': 7.411, 'CCWM': 26.498, 'TeamName': 'DuMoore Robotics'}, {'TeamNum': 16730, 'OPR': 56.679, 'Auto': 0.272, 'CCWM': -0.299, 'TeamName': 'Cat-alytic Converters'}, {'TeamNum': 9778, 'OPR': 54.857, 'Auto': 1.995, 'CCWM': 6.836, 'TeamName': 'Robotic Chinchillas'}, {'TeamNum': 18838, 'OPR': 48.62, 'Auto': 26.28, 'CCWM': -50.365, 'TeamName': "Robo's Pit Crew"}, {'TeamNum': 21780, 'OPR': 46.91, 'Auto': 16.231, 'CCWM': 3.846, 'TeamName': 'Longhorn Robotics'}, {'TeamNum': 19782, 'OPR': 45.951, 'Auto': 19.658, 'CCWM': -18.291, 'TeamName': 'Hart Robotics'}, {'TeamNum': 20145, 'OPR': 44.944, 'Auto': 2.952, 'CCWM': 12.813, 'TeamName': 'Wildcat Robotics - 2'}, {'TeamNum': 12398, 'OPR': 41.959, 'Auto': 9.984, 'CCWM': -17.895, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 19956, 'OPR': 41.629, 'Auto': 3.921, 'CCWM': -2.446, 'TeamName': 'Mechanical Mayhem'}, {'TeamNum': 17332, 'OPR': 41.331, 'Auto': -4.374, 'CCWM': -11.353, 'TeamName': 'Wildcat Robotics - 3'}, {'TeamNum': 18801, 'OPR': 37.979, 'Auto': 4.015, 'CCWM': 15.618, 'TeamName': 'Crazy Hat People'}, {'TeamNum': 17198, 'OPR': 35.36, 'Auto': 16.056, 'CCWM': -18.725, 'TeamName': 'Wildcat Robotics 1'}, {'TeamNum': 22304, 'OPR': 32.588, 'Auto': 3.323, 'CCWM': -50.537, 'TeamName': 'Bomb City Bots Gold'}, {'TeamNum': 22306, 'OPR': 32.5, 'Auto': 1.27, 'CCWM': 6.092, 'TeamName': 'Bomb City Bots White'}, {'TeamNum': 14608, 'OPR': 32.42, 'Auto': 13.864, 'CCWM': 6.659, 'TeamName': 'SunrayBotCats'}, {'TeamNum': 18503, 'OPR': 27.788, 'Auto': 1.614, 'CCWM': 20.209, 'TeamName': 'The Well Team 3'}, {'TeamNum': 19717, 'OPR': 12.84, 'Auto': -3.266, 'CCWM': -41.15, 'TeamName': 'Bomb City Bots Blue'}, {'TeamNum': 17977, 'OPR': 11.049, 'Auto': -0.675, 'CCWM': -33.415, 'TeamName': 'Omni-Future'}, {'TeamNum': 17191, 'OPR': 8.852, 'Auto': 0.851, 'CCWM': -41.728, 'TeamName': 'CMS Robot Designers - 1'}, {'TeamNum': 21848, 'OPR': 7.992, 'Auto': 0.718, 'CCWM': -60.496, 'TeamName': 'DuMoore Robotics 2.0'}]
i 1019

{'16215', '22104', '17719', '16226', '16212', '17717', '16216', '22693', '20335'}
[{'TeamNum': 16215, 'OPR': 107.159, 'Auto': 25.038, 'CCWM': 82.106, 'TeamName': 'Mystery Machine'}, {'TeamNum': 20335, 'OPR': 55.456, 'Auto': 18.196, 'CCWM': 21.541, 'TeamName': 'LIONBOTS'}, {'TeamNum': 22104, 'OPR': 44.521, 'Auto': 5.963, 'CCWM': -5.219, 'TeamName': 'Douglass Dorks'}, {'TeamNum': 16226, 'OPR': 44.161, 'Auto': 17.855, 'CCWM': 21.082, 'TeamName': 'True Damage'}, {'TeamNum': 16216, 'OPR': 38.493, 'Auto': 8.434, 'CCWM': 31.221, 'TeamName': 'System Overload'}, {'TeamNum': 22693, 'OPR': 36.056, 'Auto': 0.71, 'CCWM': -34.317, 'TeamName': 'CEN--Pirates'}, {'TeamNum': 16212, 'OPR': 30.01, 'Auto': -0.914, 'CCWM': -37.616, 'TeamName': 'Tech-No-Logic'}, {'TeamNum': 17717, 'OPR': 14.614, 'Auto': -0.721, 'CCWM': -54.112, 'TeamName': 'Cleveland ISD Fearsome Donuts'}, {'TeamNum': 17719, 'OPR': 9.45, 'Auto': 1.927, 'CCWM': -29.366, 'TeamName': 'Cleveland Lady Indians'}]
USTXHONELT1
[{'TeamNum': 16215, 'OPR': 107.159, 'Auto': 25.038, 'CCWM': 82.106, 'TeamName': 'Mystery Machine'}, {'TeamNum': 20335, 'OPR': 55.456, 'Auto': 18.196, 'CCWM': 21.541, 'TeamName': 'LIONBOTS'}, {'TeamNum': 22104, 'OPR': 44.521, 'Auto': 5.963, 'CCWM': -5.219, 'TeamName': 'Douglass Dorks'}, {'TeamNum': 16226, 'OPR': 44.161, 'Auto': 17.855, 'CCWM': 21.082, 'TeamName': 'True Damage'}, {'TeamNum': 16216, 'OPR': 38.493, 'Auto': 8.434, 'CCWM': 31.221, 'TeamName': 'System Overload'}, {'TeamNum': 22693, 'OPR': 36.056, 'Auto': 0.71, 'CCWM': -34.317, 'TeamName': 'CEN--Pirates'}, {'TeamNum': 16212, 'OPR': 30.01, 'Auto': -0.914, 'CCWM': -37.616, 'TeamName': 'Tech-No-Logic'}, {'TeamNum': 17717, 'OPR': 14.614, 'Auto': -0.721, 'CCWM': -54.112, 'TeamName': 'Cleveland ISD Fearsome Donuts'}, {'TeamNum': 17719, 'OPR': 9.45, 'Auto': 1.927, 'CCWM': -29.366, 'TeamName': 'Cleveland Lady Indians'}]
i 1020
{'22393', '22713', '22133', '22176', '22745', '22714', '22744', '5175', '22852', '22853', '21338', '18514', '10405', '22170'}
[{'TeamNum': 22393, 'OPR': 35.909, 'Auto': 18.808, 'CCWM': 22.392, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 10405, 'OPR': 34.03, 'Auto': 13.099, 'CCWM': 24.046, 'TeamName': 'RoboKnights'}, {'TeamNum': 22176, 'OPR': 30.758, 'Auto': 10.39, 'CCWM': 22.866, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22714, 'OPR': 22.777, 'Auto': -0.951, 'CCWM': 14.561, 'TeamName': 'The Scanners'}, {'TeamNum': 22853, 'OPR': 16.197, 'Auto': 4.812, 'CCWM': 4.735, 'TeamName': 'Falconers'}, {'TeamNum': 22744, 'OPR': 14.33, 'Auto': 8.757, 'CCWM': -4.126, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 18514, 'OPR': 8.479, 'Auto': -2.929, 'CCWM': -11.439, 'TeamName': 'STORM Masters'}, {'TeamNum': 22170, 'OPR': 7.747, 'Auto': 5.591, 'CCWM': -11.398, 'TeamName': 'JDT'}, {'TeamNum': 22852, 'OPR': 6.912, 'Auto': 1.451, 'CCWM': -8.24, 'TeamName': 'RoboFalcons'}, {'TeamNum': 5175, 'OPR': 6.691, 'Auto': 5.72, 'CCWM': -12.802, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22745, 'OPR': 6.365, 'Auto': 0.844, 'CCWM': -0.862, 'TeamName': 'Jack Bots'}, {'TeamNum': 22713, 'OPR': 5.042, 'Auto': 0.837, 'CCWM': -16.299, 'TeamName': 'Bubble Bots'}, {'TeamNum': 22133, 'OPR': 3.158, 'Auto': -1.814, 'CCWM': -13.93, 'TeamName': 'Infinity'}, {'TeamNum': 21338, 'OPR': 1.378, 'Auto': -0.395, 'CCWM': -12.244, 'TeamName': 'Innovators'}]
USTXHOELM3
[{'TeamNum': 22393, 'OPR': 35.909, 'Auto': 18.808, 'CCWM': 22.392, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 10405, 'OPR': 34.03, 'Auto': 13.099, 'CCWM': 24.046, 'TeamName': 'RoboKnights'}, {'TeamNum': 22176, 'OPR': 30.758, 'Auto': 10.39, 'CCWM': 22.866, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22714, 'OPR': 22.777, 'Auto': -0.951, 'CCWM': 14.561, 'TeamName': 'The Scanners'}, {'TeamNum': 22853, 'OPR': 16.197, 'Auto': 4.812, 'CCWM': 4.735, 'TeamName': 'Falconers'}, {'TeamNum': 22744, 'OPR': 14.33, 'Auto': 8.757, 'CCWM': -4.126, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 18514, 'OPR': 8.479, 'Auto': -2.929, 'CCWM': -11.439, 'TeamName': 'STORM Masters'}, {'TeamNum': 22170, 'OPR': 7.747, 'Auto': 5.591, 'CCWM': -11.398, 'TeamName': 'JDT'}, {'TeamNum': 22852, 'OPR': 6.912, 'Auto': 1.451, 'CCWM': -8.24, 'TeamName': 'RoboFalcons'}, {'TeamNum': 5175, 'OPR': 6.691, 'Auto': 5.72, 'CCWM': -12.802, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22745, 'OPR': 6.365, 'Auto': 0.844, 'CCWM': -0.862, 'TeamName': 'Jack Bots'}, {'TeamNum': 22713, 'OPR': 5.042, 'Auto': 0.837, 'CCWM': -16.299, 'TeamName': 'Bubble Bots'}, {'TeamNum': 22133, 'OPR': 3.158, 'Auto': -1.814, 'CCWM': -13.93, 'TeamName': 'Infinity'}, {'TeamNum': 21338, 'OPR': 1.378, 'Auto': -0.395, 'CCWM': -12.244, 'TeamName': 'Innovators'}]
i 1021
{'20485', '11719', '19738', '19574', '19592', '19734', '15546', '14637', '15553', '19740', '21889', '21792', '19733', '15549', '21888', '19741', '19739', '18483', '18900', '19779', '18484', '15550', '19736', '21685', '19737'}
[{'TeamNum': 18484, 'OPR': 91.621, 'Auto': 20.45, 'CCWM': 81.085, 'TeamName': 'p0gg3r$'}, {'TeamNum': 15546, 'OPR': 88.122, 'Auto': 29.861, 'CCWM': 52.018, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 14637, 'OPR': 84.637, 'Auto': 26.476, 'CCWM': 37.049, 'TeamName': 'Aquanauts'}, {'TeamNum': 19779, 'OPR': 77.707, 'Auto': 22.75, 'CCWM': 41.181, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 18483, 'OPR': 74.713, 'Auto': 11.993, 'CCWM': 63.699, 'TeamName': 'Buckar00s'}, {'TeamNum': 18900, 'OPR': 62.602, 'Auto': 24.358, 'CCWM': 23.274, 'TeamName': 'Sea No Evil'}, {'TeamNum': 15553, 'OPR': 60.541, 'Auto': 17.335, 'CCWM': 47.659, 'TeamName': 'Grumpy Avians'}, {'TeamNum': 11719, 'OPR': 42.083, 'Auto': 0.986, 'CCWM': 24.013, 'TeamName': 'Iron Hook'}, {'TeamNum': 15549, 'OPR': 41.403, 'Auto': 12.504, 'CCWM': 3.408, 'TeamName': 'Mustang Maniacs'}, {'TeamNum': 21888, 'OPR': 39.225, 'Auto': 4.48, 'CCWM': 13.633, 'TeamName': 'Floydada Collegiate Team A'}, {'TeamNum': 21889, 'OPR': 34.209, 'Auto': -0.287, 'CCWM': 11.322, 'TeamName': 'Floydada Collegiate Team B'}, {'TeamNum': 19592, 'OPR': 33.729, 'Auto': 0.379, 'CCWM': -37.434, 'TeamName': 'Knight Owls'}, {'TeamNum': 19574, 'OPR': 31.541, 'Auto': 5.684, 'CCWM': -26.3, 'TeamName': 'LCMS FTC Pirate Robotics: Dynamite Ducks'}, {'TeamNum': 15550, 'OPR': 30.531, 'Auto': 0.621, 'CCWM': 1.721, 'TeamName': 'Mustang 50'}, {'TeamNum': 19739, 'OPR': 30.357, 'Auto': 7.625, 'CCWM': -30.451, 'TeamName': 'TIm1nat0rs'}, {'TeamNum': 19737, 'OPR': 28.551, 'Auto': -2.213, 'CCWM': -29.709, 'TeamName': 'TI At0mic Mighty Ducks'}, {'TeamNum': 19734, 'OPR': 23.419, 'Auto': 0.902, 'CCWM': -7.169, 'TeamName': 'Frenship Middle School 2'}, {'TeamNum': 19733, 'OPR': 21.385, 'Auto': 2.579, 'CCWM': -27.125, 'TeamName': 'Frenship Middle School 1'}, {'TeamNum': 19738, 'OPR': 16.788, 'Auto': 2.425, 'CCWM': -35.884, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 21792, 'OPR': 16.783, 'Auto': -2.98, 'CCWM': -51.933, 'TeamName': 'CEN-Unified'}, {'TeamNum': 20485, 'OPR': 16.091, 'Auto': -4.956, 'CCWM': -25.699, 'TeamName': 'LCMS FTC Pirate Robotics: The Core Set'}, {'TeamNum': 19736, 'OPR': 15.252, 'Auto': -1.662, 'CCWM': -38.106, 'TeamName': 'Frenship Middle School 3'}, {'TeamNum': 21685, 'OPR': 13.753, 'Auto': 2.671, 'CCWM': -25.773, 'TeamName': 'LCMS FTC Pirate Robotics: Red Sea'}, {'TeamNum': 19740, 'OPR': 5.056, 'Auto': 4.523, 'CCWM': -44.749, 'TeamName': '4 B1LLY 2pointOH'}, {'TeamNum': 19741, 'OPR': -6.57, 'Auto': 0.138, 'CCWM': -38.556, 'TeamName': 'L0w r1D3R'}]
USTXWPLBLT
[{'TeamNum': 18484, 'OPR': 91.621, 'Auto': 20.45, 'CCWM': 81.085, 'TeamName': 'p0gg3r$'}, {'TeamNum': 15546, 'OPR': 88.122, 'Auto': 29.861, 'CCWM': 52.018, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 14637, 'OPR': 84.637, 'Auto': 26.476, 'CCWM': 37.049, 'TeamName': 'Aquanauts'}, {'TeamNum': 19779, 'OPR': 77.707, 'Auto': 22.75, 'CCWM': 41.181, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 18483, 'OPR': 74.713, 'Auto': 11.993, 'CCWM': 63.699, 'TeamName': 'Buckar00s'}, {'TeamNum': 18900, 'OPR': 62.602, 'Auto': 24.358, 'CCWM': 23.274, 'TeamName': 'Sea No Evil'}, {'TeamNum': 15553, 'OPR': 60.541, 'Auto': 17.335, 'CCWM': 47.659, 'TeamName': 'Grumpy Avians'}, {'TeamNum': 11719, 'OPR': 42.083, 'Auto': 0.986, 'CCWM': 24.013, 'TeamName': 'Iron Hook'}, {'TeamNum': 15549, 'OPR': 41.403, 'Auto': 12.504, 'CCWM': 3.408, 'TeamName': 'Mustang Maniacs'}, {'TeamNum': 21888, 'OPR': 39.225, 'Auto': 4.48, 'CCWM': 13.633, 'TeamName': 'Floydada Collegiate Team A'}, {'TeamNum': 21889, 'OPR': 34.209, 'Auto': -0.287, 'CCWM': 11.322, 'TeamName': 'Floydada Collegiate Team B'}, {'TeamNum': 19592, 'OPR': 33.729, 'Auto': 0.379, 'CCWM': -37.434, 'TeamName': 'Knight Owls'}, {'TeamNum': 19574, 'OPR': 31.541, 'Auto': 5.684, 'CCWM': -26.3, 'TeamName': 'LCMS FTC Pirate Robotics: Dynamite Ducks'}, {'TeamNum': 15550, 'OPR': 30.531, 'Auto': 0.621, 'CCWM': 1.721, 'TeamName': 'Mustang 50'}, {'TeamNum': 19739, 'OPR': 30.357, 'Auto': 7.625, 'CCWM': -30.451, 'TeamName': 'TIm1nat0rs'}, {'TeamNum': 19737, 'OPR': 28.551, 'Auto': -2.213, 'CCWM': -29.709, 'TeamName': 'TI At0mic Mighty Ducks'}, {'TeamNum': 19734, 'OPR': 23.419, 'Auto': 0.902, 'CCWM': -7.169, 'TeamName': 'Frenship Middle School 2'}, {'TeamNum': 19733, 'OPR': 21.385, 'Auto': 2.579, 'CCWM': -27.125, 'TeamName': 'Frenship Middle School 1'}, {'TeamNum': 19738, 'OPR': 16.788, 'Auto': 2.425, 'CCWM': -35.884, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 21792, 'OPR': 16.783, 'Auto': -2.98, 'CCWM': -51.933, 'TeamName': 'CEN-Unified'}, {'TeamNum': 20485, 'OPR': 16.091, 'Auto': -4.956, 'CCWM': -25.699, 'TeamName': 'LCMS FTC Pirate Robotics: The Core Set'}, {'TeamNum': 19736, 'OPR': 15.252, 'Auto': -1.662, 'CCWM': -38.106, 'TeamName': 'Frenship Middle School 3'}, {'TeamNum': 21685, 'OPR': 13.753, 'Auto': 2.671, 'CCWM': -25.773, 'TeamName': 'LCMS FTC Pirate Robotics: Red Sea'}, {'TeamNum': 19740, 'OPR': 5.056, 'Auto': 4.523, 'CCWM': -44.749, 'TeamName': '4 B1LLY 2pointOH'}, {'TeamNum': 19741, 'OPR': -6.57, 'Auto': 0.138, 'CCWM': -38.556, 'TeamName': 'L0w r1D3R'}]
i 1022

{'16028', '19924', '5667', '12351', '19389', '17604', '19744', '21676', '17603', '21765', '3747'}
[{'TeamNum': 16028, 'OPR': 76.588, 'Auto': 14.735, 'CCWM': 44.955, 'TeamName': 'Mecha Knights'}, {'TeamNum': 17604, 'OPR': 59.659, 'Auto': 7.384, 'CCWM': 34.392, 'TeamName': 'TNT (Terribly Nice Team)'}, {'TeamNum': 12351, 'OPR': 52.574, 'Auto': 10.688, 'CCWM': 26.25, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 5667, 'OPR': 47.375, 'Auto': 18.018, 'CCWM': 27.501, 'TeamName': 'Robominers'}, {'TeamNum': 21765, 'OPR': 44.675, 'Auto': 13.034, 'CCWM': 16.887, 'TeamName': 'Overclocked'}, {'TeamNum': 19924, 'OPR': 36.654, 'Auto': 20.337, 'CCWM': -15.063, 'TeamName': 'The Black Swan'}, {'TeamNum': 3747, 'OPR': 35.271, 'Auto': -7.531, 'CCWM': 2.006, 'TeamName': 'The Hive'}, {'TeamNum': 19389, 'OPR': 31.639, 'Auto': 5.042, 'CCWM': -32.288, 'TeamName': 'Angry Aliens'}, {'TeamNum': 17603, 'OPR': 18.616, 'Auto': -2.833, 'CCWM': -31.148, 'TeamName': 'Nuclear Core'}, {'TeamNum': 21676, 'OPR': 10.887, 'Auto': 0.798, 'CCWM': -31.857, 'TeamName': 'Traffic Cone Pigeon Girls'}, {'TeamNum': 19744, 'OPR': 3.387, 'Auto': -0.475, 'CCWM': -47.136, 'TeamName': 'Astro Knights'}]
USUTSJQ
[{'TeamNum': 16028, 'OPR': 76.588, 'Auto': 14.735, 'CCWM': 44.955, 'TeamName': 'Mecha Knights'}, {'TeamNum': 17604, 'OPR': 59.659, 'Auto': 7.384, 'CCWM': 34.392, 'TeamName': 'TNT (Terribly Nice Team)'}, {'TeamNum': 12351, 'OPR': 52.574, 'Auto': 10.688, 'CCWM': 26.25, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 5667, 'OPR': 47.375, 'Auto': 18.018, 'CCWM': 27.501, 'TeamName': 'Robominers'}, {'TeamNum': 21765, 'OPR': 44.675, 'Auto': 13.034, 'CCWM': 16.887, 'TeamName': 'Overclocked'}, {'TeamNum': 19924, 'OPR': 36.654, 'Auto': 20.337, 'CCWM': -15.063, 'TeamName': 'The Black Swan'}, {'TeamNum': 3747, 'OPR': 35.271, 'Auto': -7.531, 'CCWM': 2.006, 'TeamName': 'The Hive'}, {'TeamNum': 19389, 'OPR': 31.639, 'Auto': 5.042, 'CCWM': -32.288, 'TeamName': 'Angry Aliens'}, {'TeamNum': 17603, 'OPR': 18.616, 'Auto': -2.833, 'CCWM': -31.148, 'TeamName': 'Nuclear Core'}, {'TeamNum': 21676, 'OPR': 10.887, 'Auto': 0.798, 'CCWM': -31.857, 'TeamName': 'Traffic Cone Pigeon Girls'}, {'TeamNum': 19744, 'OPR': 3.387, 'Auto': -0.475, 'CCWM': -47.136, 'TeamName': 'Astro Knights'}]
i 1023
{'18649', '18650', '14251', '18616', '5741', '3397', '18351', '15081', '21577', '22683', '16221', '10899', '6731', '9622', '16295', '9721', '7418', '4946', '8304'}
[{'TeamNum': 5741, 'OPR': 77.764, 'Auto': 27.905, 'CCWM': 54.062, 'TeamName': 'CVU RoboHawks'}, {'TeamNum': 3397, 'OPR': 73.863, 'Auto': 10.47, 'CCWM': 57.373, 'TeamName': 'HiveMind Robotics'}, {'TeamNum': 16221, 'OPR': 62.653, 'Auto': 25.81, 'CCWM': 29.779, 'TeamName': 'Manchester Machine Makers'}, {'TeamNum': 18351, 'OPR': 53.853, 'Auto': 0.819, 'CCWM': 36.051, 'TeamName': 'Bubbert Innovations'}, {'TeamNum': 4946, 'OPR': 45.384, 'Auto': 9.741, 'CCWM': 11.149, 'TeamName': 'Robo Raiders'}, {'TeamNum': 8304, 'OPR': 44.822, 'Auto': 9.57, 'CCWM': 40.166, 'TeamName': 'Wired Cats'}, {'TeamNum': 22683, 'OPR': 43.568, 'Auto': 11.162, 'CCWM': 11.391, 'TeamName': 'JV RoboRedHawks'}, {'TeamNum': 10899, 'OPR': 42.846, 'Auto': 15.123, 'CCWM': 14.368, 'TeamName': 'Mansfield Mechanics United'}, {'TeamNum': 18650, 'OPR': 40.244, 'Auto': 23.367, 'CCWM': -6.499, 'TeamName': 'Cookie Clickers'}, {'TeamNum': 15081, 'OPR': 36.856, 'Auto': -0.046, 'CCWM': 29.216, 'TeamName': 'Milton Robotics'}, {'TeamNum': 6731, 'OPR': 29.628, 'Auto': 0.977, 'CCWM': -30.59, 'TeamName': 'Ringers'}, {'TeamNum': 7418, 'OPR': 23.601, 'Auto': -5.76, 'CCWM': -7.242, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 9622, 'OPR': 13.49, 'Auto': 0.096, 'CCWM': -29.993, 'TeamName': 'RMS Robotics'}, {'TeamNum': 21577, 'OPR': 10.809, 'Auto': 7.825, 'CCWM': -27.475, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 16295, 'OPR': 9.014, 'Auto': -0.189, 'CCWM': -58.948, 'TeamName': 'Green Mountain Girls'}, {'TeamNum': 14251, 'OPR': 5.89, 'Auto': 3.92, 'CCWM': -24.182, 'TeamName': 'Capital Robotics'}, {'TeamNum': 18649, 'OPR': 5.393, 'Auto': -2.36, 'CCWM': -4.835, 'TeamName': 'Lancer Robotics'}, {'TeamNum': 9721, 'OPR': 3.027, 'Auto': 2.888, 'CCWM': -50.162, 'TeamName': 'Green Mountain Gears'}, {'TeamNum': 18616, 'OPR': -4.418, 'Auto': -3.55, 'CCWM': -45.908, 'TeamName': "River Valley RAD's"}]
USVTCMP
[{'TeamNum': 5741, 'OPR': 77.764, 'Auto': 27.905, 'CCWM': 54.062, 'TeamName': 'CVU RoboHawks'}, {'TeamNum': 3397, 'OPR': 73.863, 'Auto': 10.47, 'CCWM': 57.373, 'TeamName': 'HiveMind Robotics'}, {'TeamNum': 16221, 'OPR': 62.653, 'Auto': 25.81, 'CCWM': 29.779, 'TeamName': 'Manchester Machine Makers'}, {'TeamNum': 18351, 'OPR': 53.853, 'Auto': 0.819, 'CCWM': 36.051, 'TeamName': 'Bubbert Innovations'}, {'TeamNum': 4946, 'OPR': 45.384, 'Auto': 9.741, 'CCWM': 11.149, 'TeamName': 'Robo Raiders'}, {'TeamNum': 8304, 'OPR': 44.822, 'Auto': 9.57, 'CCWM': 40.166, 'TeamName': 'Wired Cats'}, {'TeamNum': 22683, 'OPR': 43.568, 'Auto': 11.162, 'CCWM': 11.391, 'TeamName': 'JV RoboRedHawks'}, {'TeamNum': 10899, 'OPR': 42.846, 'Auto': 15.123, 'CCWM': 14.368, 'TeamName': 'Mansfield Mechanics United'}, {'TeamNum': 18650, 'OPR': 40.244, 'Auto': 23.367, 'CCWM': -6.499, 'TeamName': 'Cookie Clickers'}, {'TeamNum': 15081, 'OPR': 36.856, 'Auto': -0.046, 'CCWM': 29.216, 'TeamName': 'Milton Robotics'}, {'TeamNum': 6731, 'OPR': 29.628, 'Auto': 0.977, 'CCWM': -30.59, 'TeamName': 'Ringers'}, {'TeamNum': 7418, 'OPR': 23.601, 'Auto': -5.76, 'CCWM': -7.242, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 9622, 'OPR': 13.49, 'Auto': 0.096, 'CCWM': -29.993, 'TeamName': 'RMS Robotics'}, {'TeamNum': 21577, 'OPR': 10.809, 'Auto': 7.825, 'CCWM': -27.475, 'TeamName': 'Bulldog Robotics'}, {'TeamNum': 16295, 'OPR': 9.014, 'Auto': -0.189, 'CCWM': -58.948, 'TeamName': 'Green Mountain Girls'}, {'TeamNum': 14251, 'OPR': 5.89, 'Auto': 3.92, 'CCWM': -24.182, 'TeamName': 'Capital Robotics'}, {'TeamNum': 18649, 'OPR': 5.393, 'Auto': -2.36, 'CCWM': -4.835, 'TeamName': 'Lancer Robotics'}, {'TeamNum': 9721, 'OPR': 3.027, 'Auto': 2.888, 'CCWM': -50.162, 'TeamName': 'Green Mountain Gears'}, {'TeamNum': 18616, 'OPR': -4.418, 'Auto': -3.55, 'CCWM': -45.908, 'TeamName': "River Valley RAD's"}]
i 1024
{'4267', '20058', '22672', '20293', '9225', '21867', '19796', '8823', '14631', '15266', '17322', '17223', '6914', '4116', '16310', '7974', '8680', '8572', '21180', '11353', '4115', '10829', '19453'}
[{'TeamNum': 14631, 'OPR': 107.019, 'Auto': 23.14, 'CCWM': 53.909, 'TeamName': 'Laser Tech'}, {'TeamNum': 21180, 'OPR': 105.962, 'Auto': 33.944, 'CCWM': 61.371, 'TeamName': 'Error 418'}, {'TeamNum': 4116, 'OPR': 105.424, 'Auto': 19.497, 'CCWM': 39.147, 'TeamName': 'Volta Robotics'}, {'TeamNum': 7974, 'OPR': 104.129, 'Auto': 15.475, 'CCWM': 53.188, 'TeamName': 'Great Scott!'}, {'TeamNum': 9225, 'OPR': 102.465, 'Auto': 33.246, 'CCWM': 20.588, 'TeamName': 'Dynamite Social Club'}, {'TeamNum': 8680, 'OPR': 101.75, 'Auto': 38.081, 'CCWM': 41.034, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 20293, 'OPR': 94.459, 'Auto': 17.037, 'CCWM': 37.427, 'TeamName': 'Laser Bots'}, {'TeamNum': 4115, 'OPR': 89.967, 'Auto': 27.541, 'CCWM': 58.463, 'TeamName': 'Men in Kilts'}, {'TeamNum': 10829, 'OPR': 81.879, 'Auto': 10.241, 'CCWM': 62.524, 'TeamName': 'Bay Robotics'}, {'TeamNum': 16310, 'OPR': 77.538, 'Auto': 21.315, 'CCWM': 29.301, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 6914, 'OPR': 74.493, 'Auto': 6.25, 'CCWM': -18.495, 'TeamName': 'Charging Chaos'}, {'TeamNum': 19453, 'OPR': 61.321, 'Auto': 19.619, 'CCWM': -6.601, 'TeamName': 'Black Mesa'}, {'TeamNum': 19796, 'OPR': 51.66, 'Auto': 13.748, 'CCWM': -16.742, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 8572, 'OPR': 43.741, 'Auto': 15.202, 'CCWM': -18.793, 'TeamName': 'Wall-Y Robotics'}, {'TeamNum': 8823, 'OPR': 43.397, 'Auto': 5.289, 'CCWM': -11.167, 'TeamName': 'Mariner Mayhem'}, {'TeamNum': 15266, 'OPR': 43.044, 'Auto': 16.826, 'CCWM': -46.802, 'TeamName': 'Kohler Robotics'}, {'TeamNum': 17322, 'OPR': 37.395, 'Auto': -0.516, 'CCWM': -25.011, 'TeamName': 'ML Spartronics'}, {'TeamNum': 21867, 'OPR': 35.96, 'Auto': 4.174, 'CCWM': 3.786, 'TeamName': 'Door of Hope'}, {'TeamNum': 20058, 'OPR': 35.323, 'Auto': 13.076, 'CCWM': -62.759, 'TeamName': 'Upskill'}, {'TeamNum': 22672, 'OPR': 34.104, 'Auto': 3.68, 'CCWM': -54.752, 'TeamName': 'Absolute Hack'}, {'TeamNum': 11353, 'OPR': 20.387, 'Auto': 6.88, 'CCWM': -45.548, 'TeamName': 'Lightning Robotics'}, {'TeamNum': 17223, 'OPR': 13.752, 'Auto': -8.32, 'CCWM': -99.629, 'TeamName': 'Oxidizers'}, {'TeamNum': 4267, 'OPR': 12.54, 'Auto': 1.166, 'CCWM': -61.925, 'TeamName': 'RoboChix'}]
USWIBRQ
[{'TeamNum': 14631, 'OPR': 107.019, 'Auto': 23.14, 'CCWM': 53.909, 'TeamName': 'Laser Tech'}, {'TeamNum': 21180, 'OPR': 105.962, 'Auto': 33.944, 'CCWM': 61.371, 'TeamName': 'Error 418'}, {'TeamNum': 4116, 'OPR': 105.424, 'Auto': 19.497, 'CCWM': 39.147, 'TeamName': 'Volta Robotics'}, {'TeamNum': 7974, 'OPR': 104.129, 'Auto': 15.475, 'CCWM': 53.188, 'TeamName': 'Great Scott!'}, {'TeamNum': 9225, 'OPR': 102.465, 'Auto': 33.246, 'CCWM': 20.588, 'TeamName': 'Dynamite Social Club'}, {'TeamNum': 8680, 'OPR': 101.75, 'Auto': 38.081, 'CCWM': 41.034, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 20293, 'OPR': 94.459, 'Auto': 17.037, 'CCWM': 37.427, 'TeamName': 'Laser Bots'}, {'TeamNum': 4115, 'OPR': 89.967, 'Auto': 27.541, 'CCWM': 58.463, 'TeamName': 'Men in Kilts'}, {'TeamNum': 10829, 'OPR': 81.879, 'Auto': 10.241, 'CCWM': 62.524, 'TeamName': 'Bay Robotics'}, {'TeamNum': 16310, 'OPR': 77.538, 'Auto': 21.315, 'CCWM': 29.301, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 6914, 'OPR': 74.493, 'Auto': 6.25, 'CCWM': -18.495, 'TeamName': 'Charging Chaos'}, {'TeamNum': 19453, 'OPR': 61.321, 'Auto': 19.619, 'CCWM': -6.601, 'TeamName': 'Black Mesa'}, {'TeamNum': 19796, 'OPR': 51.66, 'Auto': 13.748, 'CCWM': -16.742, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 8572, 'OPR': 43.741, 'Auto': 15.202, 'CCWM': -18.793, 'TeamName': 'Wall-Y Robotics'}, {'TeamNum': 8823, 'OPR': 43.397, 'Auto': 5.289, 'CCWM': -11.167, 'TeamName': 'Mariner Mayhem'}, {'TeamNum': 15266, 'OPR': 43.044, 'Auto': 16.826, 'CCWM': -46.802, 'TeamName': 'Kohler Robotics'}, {'TeamNum': 17322, 'OPR': 37.395, 'Auto': -0.516, 'CCWM': -25.011, 'TeamName': 'ML Spartronics'}, {'TeamNum': 21867, 'OPR': 35.96, 'Auto': 4.174, 'CCWM': 3.786, 'TeamName': 'Door of Hope'}, {'TeamNum': 20058, 'OPR': 35.323, 'Auto': 13.076, 'CCWM': -62.759, 'TeamName': 'Upskill'}, {'TeamNum': 22672, 'OPR': 34.104, 'Auto': 3.68, 'CCWM': -54.752, 'TeamName': 'Absolute Hack'}, {'TeamNum': 11353, 'OPR': 20.387, 'Auto': 6.88, 'CCWM': -45.548, 'TeamName': 'Lightning Robotics'}, {'TeamNum': 17223, 'OPR': 13.752, 'Auto': -8.32, 'CCWM': -99.629, 'TeamName': 'Oxidizers'}, {'TeamNum': 4267, 'OPR': 12.54, 'Auto': 1.166, 'CCWM': -61.925, 'TeamName': 'RoboChix'}]

i 1025
i 1026
i 1027
i 1028
{'21414', '18422', '21659', '21343', '22597', '21398', '18448', '22587'}
[{'TeamNum': 18422, 'OPR': 79.192, 'Auto': 14.189, 'CCWM': 32.375, 'TeamName': 'LYBOTICS Wizards Team'}, {'TeamNum': 21659, 'OPR': 61.715, 'Auto': 5.761, 'CCWM': 12.589, 'TeamName': 'Edafa Robotics Team'}, {'TeamNum': 21414, 'OPR': 26.192, 'Auto': 21.761, 'CCWM': 18.375, 'TeamName': 'Scouts Girls Robotics Team'}, {'TeamNum': 21343, 'OPR': 25.87, 'Auto': 11.654, 'CCWM': -14.018, 'TeamName': 'LYBOTICS Ghosts Team '}, {'TeamNum': 18448, 'OPR': 21.965, 'Auto': 7.654, 'CCWM': 1.339, 'TeamName': 'LYBOTICS Castle Team'}, {'TeamNum': 22597, 'OPR': 15.251, 'Auto': 3.796, 'CCWM': -15.089, 'TeamName': 'Alshati Geniuses Robotics Team'}, {'TeamNum': 21398, 'OPR': 15.013, 'Auto': 5.796, 'CCWM': -12.732, 'TeamName': 'Scouts Fazzan Robotics Team'}, {'TeamNum': 22587, 'OPR': 3.001, 'Auto': 2.189, 'CCWM': -22.839, 'TeamName': 'TraghenTech Robotics Team'}]
LYTRQ
[{'TeamNum': 18422, 'OPR': 79.192, 'Auto': 14.189, 'CCWM': 32.375, 'TeamName': 'LYBOTICS Wizards Team'}, {'TeamNum': 21659, 'OPR': 61.715, 'Auto': 5.761, 'CCWM': 12.589, 'TeamName': 'Edafa Robotics Team'}, {'TeamNum': 21414, 'OPR': 26.192, 'Auto': 21.761, 'CCWM': 18.375, 'TeamName': 'Scouts Girls Robotics Team'}, {'TeamNum': 21343, 'OPR': 25.87, 'Auto': 11.654, 'CCWM': -14.018, 'TeamName': 'LYBOTICS Ghosts Team '}, {'TeamNum': 18448, 'OPR': 21.965, 'Auto': 7.654, 'CCWM': 1.339, 'TeamName': 'LYBOTICS Castle Team'}, {'TeamNum': 22597, 'OPR': 15.251, 'Auto': 3.796, 'CCWM': -15.089, 'TeamName': 'Alshati Geniuses Robotics Team'}, {'TeamNum': 21398, 'OPR': 15.013, 'Auto': 5.796, 'CCWM': -12.732, 'TeamName': 'Scouts Fazzan Robotics Team'}, {'TeamNum': 22587, 'OPR': 3.001, 'Auto': 2.189, 'CCWM': -22.839, 'TeamName': 'TraghenTech Robotics Team'}]
i 1029
{'17755', '22322', '21837', '22572', '22252', '11140', '15909', '22466', '21741', '20327', '22569', '22458', '10793', '8327', '22553', '22728', '16388', '9164', '18562', '16508', '21704', '17626', '21735', '21802', '22372', '21678', '22413', '22815', '18341', '22854', '21827', '12887', '15600', '20746', '21091', '22842', '6584', '17625'}
[{'TeamNum': 12887, 'OPR': 145.53, 'Auto': 33.634, 'CCWM': 124.807, 'TeamName': 'Devolt Phobos'}, {'TeamNum': 18341, 'OPR': 105.795, 'Auto': 16.103, 'CCWM': 50.173, 'TeamName': 'MechRams'}, {'TeamNum': 17755, 'OPR': 94.598, 'Auto': 22.846, 'CCWM': 59.788, 'TeamName': 'ELECTRIC GEARS'}, {'TeamNum': 10793, 'OPR': 82.168, 'Auto': 16.825, 'CCWM': 91.199, 'TeamName': 'Voltrons'}, {'TeamNum': 21735, 'OPR': 77.037, 'Auto': 17.102, 'CCWM': 0.651, 'TeamName': 'Nautilus'}, {'TeamNum': 22842, 'OPR': 75.934, 'Auto': 13.307, 'CCWM': 13.365, 'TeamName': 'Hype-Xolotls'}, {'TeamNum': 21802, 'OPR': 68.687, 'Auto': 12.449, 'CCWM': 67.53, 'TeamName': 'PrepaTec VOLTEC Robotics'}, {'TeamNum': 22252, 'OPR': 66.353, 'Auto': 21.937, 'CCWM': 50.219, 'TeamName': 'Devolt Ceres'}, {'TeamNum': 9164, 'OPR': 63.291, 'Auto': 7.747, 'CCWM': 24.89, 'TeamName': 'Zorrobots'}, {'TeamNum': 21741, 'OPR': 54.812, 'Auto': -0.339, 'CCWM': 14.609, 'TeamName': 'XICALIBOTS'}, {'TeamNum': 11140, 'OPR': 52.036, 'Auto': 8.582, 'CCWM': 8.565, 'TeamName': 'Legacy HighPoint International School'}, {'TeamNum': 16508, 'OPR': 48.993, 'Auto': 24.112, 'CCWM': -14.414, 'TeamName': 'Minerva Legion'}, {'TeamNum': 15600, 'OPR': 47.83, 'Auto': 13.623, 'CCWM': -19.713, 'TeamName': 'CERBOTICS'}, {'TeamNum': 8327, 'OPR': 47.382, 'Auto': 6.4, 'CCWM': 29.406, 'TeamName': 'Spartans'}, {'TeamNum': 22322, 'OPR': 46.562, 'Auto': 13.955, 'CCWM': 5.045, 'TeamName': 'BearsRobotics'}, {'TeamNum': 6584, 'OPR': 45.978, 'Auto': 11.392, 'CCWM': 24.22, 'TeamName': 'Rhinos'}, {'TeamNum': 21827, 'OPR': 45.516, 'Auto': 11.45, 'CCWM': 7.51, 'TeamName': 'Sputnik'}, {'TeamNum': 22572, 'OPR': 43.641, 'Auto': 3.414, 'CCWM': 36.475, 'TeamName': 'Tlaztec I'}, {'TeamNum': 16388, 'OPR': 39.525, 'Auto': 19.089, 'CCWM': -42.502, 'TeamName': 'PrepaTec - Megabyte'}, {'TeamNum': 22815, 'OPR': 38.928, 'Auto': 1.44, 'CCWM': 9.927, 'TeamName': 'Taman Keet'}, {'TeamNum': 22466, 'OPR': 38.093, 'Auto': -1.797, 'CCWM': 21.84, 'TeamName': 'Rhinos UP!'}, {'TeamNum': 15909, 'OPR': 34.676, 'Auto': 6.38, 'CCWM': -36.6, 'TeamName': 'Devolt Deimos'}, {'TeamNum': 22569, 'OPR': 33.581, 'Auto': 0.155, 'CCWM': 8.172, 'TeamName': 'AzTeam II'}, {'TeamNum': 21678, 'OPR': 33.14, 'Auto': 11.52, 'CCWM': -21.962, 'TeamName': 'THUNDER EAGLES'}, {'TeamNum': 17625, 'OPR': 31.347, 'Auto': 3.138, 'CCWM': -1.181, 'TeamName': 'Aztech Robotics I'}, {'TeamNum': 20746, 'OPR': 28.801, 'Auto': -0.002, 'CCWM': -10.648, 'TeamName': 'Humanitree School'}, {'TeamNum': 21837, 'OPR': 28.276, 'Auto': 1.702, 'CCWM': 4.499, 'TeamName': 'DonkPink II'}, {'TeamNum': 20327, 'OPR': 26.152, 'Auto': -0.954, 'CCWM': 3.488, 'TeamName': 'Kitsunics'}, {'TeamNum': 22854, 'OPR': 23.101, 'Auto': -1.264, 'CCWM': -33.739, 'TeamName': 'KVoltage'}, {'TeamNum': 22728, 'OPR': 21.329, 'Auto': -0.113, 'CCWM': -2.548, 'TeamName': 'JM RHINOS '}, {'TeamNum': 22413, 'OPR': 20.257, 'Auto': 2.828, 'CCWM': -79.746, 'TeamName': 'Tecmilenio Robotics'}, {'TeamNum': 22372, 'OPR': 17.183, 'Auto': 1.199, 'CCWM': -35.737, 'TeamName': 'PrepaTec - Resistors'}, {'TeamNum': 21704, 'OPR': 15.453, 'Auto': 5.871, 'CCWM': -8.945, 'TeamName': 'Lobos Negros'}, {'TeamNum': 22458, 'OPR': 11.678, 'Auto': 10.061, 'CCWM': -86.38, 'TeamName': 'BEAVERS'}, {'TeamNum': 22553, 'OPR': 8.1, 'Auto': 6.696, 'CCWM': -79.243, 'TeamName': 'ARCADIA'}, {'TeamNum': 17626, 'OPR': 1.34, 'Auto': -0.971, 'CCWM': -73.016, 'TeamName': 'Aztech Robotics II'}, {'TeamNum': 21091, 'OPR': -0.305, 'Auto': 3.871, 'CCWM': -41.339, 'TeamName': 'ILALBOTICS'}, {'TeamNum': 18562, 'OPR': -3.736, 'Auto': 1.832, 'CCWM': -63.551, 'TeamName': 'TecsAhoy'}]
MXCMP
[{'TeamNum': 12887, 'OPR': 145.53, 'Auto': 33.634, 'CCWM': 124.807, 'TeamName': 'Devolt Phobos'}, {'TeamNum': 18341, 'OPR': 105.795, 'Auto': 16.103, 'CCWM': 50.173, 'TeamName': 'MechRams'}, {'TeamNum': 17755, 'OPR': 94.598, 'Auto': 22.846, 'CCWM': 59.788, 'TeamName': 'ELECTRIC GEARS'}, {'TeamNum': 10793, 'OPR': 82.168, 'Auto': 16.825, 'CCWM': 91.199, 'TeamName': 'Voltrons'}, {'TeamNum': 21735, 'OPR': 77.037, 'Auto': 17.102, 'CCWM': 0.651, 'TeamName': 'Nautilus'}, {'TeamNum': 22842, 'OPR': 75.934, 'Auto': 13.307, 'CCWM': 13.365, 'TeamName': 'Hype-Xolotls'}, {'TeamNum': 21802, 'OPR': 68.687, 'Auto': 12.449, 'CCWM': 67.53, 'TeamName': 'PrepaTec VOLTEC Robotics'}, {'TeamNum': 22252, 'OPR': 66.353, 'Auto': 21.937, 'CCWM': 50.219, 'TeamName': 'Devolt Ceres'}, {'TeamNum': 9164, 'OPR': 63.291, 'Auto': 7.747, 'CCWM': 24.89, 'TeamName': 'Zorrobots'}, {'TeamNum': 21741, 'OPR': 54.812, 'Auto': -0.339, 'CCWM': 14.609, 'TeamName': 'XICALIBOTS'}, {'TeamNum': 11140, 'OPR': 52.036, 'Auto': 8.582, 'CCWM': 8.565, 'TeamName': 'Legacy HighPoint International School'}, {'TeamNum': 16508, 'OPR': 48.993, 'Auto': 24.112, 'CCWM': -14.414, 'TeamName': 'Minerva Legion'}, {'TeamNum': 15600, 'OPR': 47.83, 'Auto': 13.623, 'CCWM': -19.713, 'TeamName': 'CERBOTICS'}, {'TeamNum': 8327, 'OPR': 47.382, 'Auto': 6.4, 'CCWM': 29.406, 'TeamName': 'Spartans'}, {'TeamNum': 22322, 'OPR': 46.562, 'Auto': 13.955, 'CCWM': 5.045, 'TeamName': 'BearsRobotics'}, {'TeamNum': 6584, 'OPR': 45.978, 'Auto': 11.392, 'CCWM': 24.22, 'TeamName': 'Rhinos'}, {'TeamNum': 21827, 'OPR': 45.516, 'Auto': 11.45, 'CCWM': 7.51, 'TeamName': 'Sputnik'}, {'TeamNum': 22572, 'OPR': 43.641, 'Auto': 3.414, 'CCWM': 36.475, 'TeamName': 'Tlaztec I'}, {'TeamNum': 16388, 'OPR': 39.525, 'Auto': 19.089, 'CCWM': -42.502, 'TeamName': 'PrepaTec - Megabyte'}, {'TeamNum': 22815, 'OPR': 38.928, 'Auto': 1.44, 'CCWM': 9.927, 'TeamName': 'Taman Keet'}, {'TeamNum': 22466, 'OPR': 38.093, 'Auto': -1.797, 'CCWM': 21.84, 'TeamName': 'Rhinos UP!'}, {'TeamNum': 15909, 'OPR': 34.676, 'Auto': 6.38, 'CCWM': -36.6, 'TeamName': 'Devolt Deimos'}, {'TeamNum': 22569, 'OPR': 33.581, 'Auto': 0.155, 'CCWM': 8.172, 'TeamName': 'AzTeam II'}, {'TeamNum': 21678, 'OPR': 33.14, 'Auto': 11.52, 'CCWM': -21.962, 'TeamName': 'THUNDER EAGLES'}, {'TeamNum': 17625, 'OPR': 31.347, 'Auto': 3.138, 'CCWM': -1.181, 'TeamName': 'Aztech Robotics I'}, {'TeamNum': 20746, 'OPR': 28.801, 'Auto': -0.002, 'CCWM': -10.648, 'TeamName': 'Humanitree School'}, {'TeamNum': 21837, 'OPR': 28.276, 'Auto': 1.702, 'CCWM': 4.499, 'TeamName': 'DonkPink II'}, {'TeamNum': 20327, 'OPR': 26.152, 'Auto': -0.954, 'CCWM': 3.488, 'TeamName': 'Kitsunics'}, {'TeamNum': 22854, 'OPR': 23.101, 'Auto': -1.264, 'CCWM': -33.739, 'TeamName': 'KVoltage'}, {'TeamNum': 22728, 'OPR': 21.329, 'Auto': -0.113, 'CCWM': -2.548, 'TeamName': 'JM RHINOS '}, {'TeamNum': 22413, 'OPR': 20.257, 'Auto': 2.828, 'CCWM': -79.746, 'TeamName': 'Tecmilenio Robotics'}, {'TeamNum': 22372, 'OPR': 17.183, 'Auto': 1.199, 'CCWM': -35.737, 'TeamName': 'PrepaTec - Resistors'}, {'TeamNum': 21704, 'OPR': 15.453, 'Auto': 5.871, 'CCWM': -8.945, 'TeamName': 'Lobos Negros'}, {'TeamNum': 22458, 'OPR': 11.678, 'Auto': 10.061, 'CCWM': -86.38, 'TeamName': 'BEAVERS'}, {'TeamNum': 22553, 'OPR': 8.1, 'Auto': 6.696, 'CCWM': -79.243, 'TeamName': 'ARCADIA'}, {'TeamNum': 17626, 'OPR': 1.34, 'Auto': -0.971, 'CCWM': -73.016, 'TeamName': 'Aztech Robotics II'}, {'TeamNum': 21091, 'OPR': -0.305, 'Auto': 3.871, 'CCWM': -41.339, 'TeamName': 'ILALBOTICS'}, {'TeamNum': 18562, 'OPR': -3.736, 'Auto': 1.832, 'CCWM': -63.551, 'TeamName': 'TecsAhoy'}]

i 1030
i 1031
{'17532', '18338', '17855', '19091', '11808', '19055', '19103', '20985', '9662', '14278', '15966', '17860', '15972', '17243', '17875', '19077', '19082', '17844', '19086', '19054', '19109', '19342', '12632', '17870', '18160', '19072', '19073', '19134', '19120', '19094', '12560', '15975', '19292', '17089', '20043', '19056', '17881', '19176', '19071', '16166', '19099', '20135', '19065', '19151', '15965', '14277', '19062', '19110', '21033', '19079', '19061', '20265', '15989', '19104', '19053', '20732', '19242', '19115', '19074', '19117', '19076', '19049', '17871', '21031', '19111', '19119', '19128', '20329', '19116', '19047', '19063', '19102', '17624', '19246', '17965', '19097'}
[{'TeamNum': 12560, 'OPR': 158.86, 'Auto': 44.955, 'CCWM': 76.588, 'TeamName': 'Soft Hoarders'}, {'TeamNum': 19109, 'OPR': 138.679, 'Auto': 32.105, 'CCWM': 27.04, 'TeamName': 'RaSky'}, {'TeamNum': 18160, 'OPR': 126.916, 'Auto': 21.814, 'CCWM': 85.899, 'TeamName': '4D-Robotics'}, {'TeamNum': 19079, 'OPR': 121.019, 'Auto': 18.754, 'CCWM': 58.607, 'TeamName': 'PHOENIX'}, {'TeamNum': 18338, 'OPR': 116.935, 'Auto': 20.115, 'CCWM': -21.861, 'TeamName': 'StarTech'}, {'TeamNum': 17243, 'OPR': 115.214, 'Auto': 22.057, 'CCWM': 60.626, 'TeamName': 'Vianu Legends'}, {'TeamNum': 19104, 'OPR': 104.65, 'Auto': 21.729, 'CCWM': 58.341, 'TeamName': 'CyberPunk Robotics'}, {'TeamNum': 19062, 'OPR': 100.308, 'Auto': 21.32, 'CCWM': 57.326, 'TeamName': 'Phantom Robotics'}, {'TeamNum': 14277, 'OPR': 96.998, 'Auto': 25.079, 'CCWM': 13.075, 'TeamName': 'QUBE.'}, {'TeamNum': 16166, 'OPR': 95.487, 'Auto': 28.673, 'CCWM': 53.255, 'TeamName': "Watt'S Up"}, {'TeamNum': 15972, 'OPR': 94.586, 'Auto': 29.717, 'CCWM': 58.215, 'TeamName': 'TehnoZ'}, {'TeamNum': 11808, 'OPR': 93.08, 'Auto': 6.86, 'CCWM': 65.194, 'TeamName': 'Connection'}, {'TeamNum': 20135, 'OPR': 92.554, 'Auto': 16.17, 'CCWM': 13.702, 'TeamName': 'MeeralRobotics'}, {'TeamNum': 14278, 'OPR': 92.375, 'Auto': 20.504, 'CCWM': 36.656, 'TeamName': 'Xeo'}, {'TeamNum': 19049, 'OPR': 90.845, 'Auto': 18.517, 'CCWM': 71.967, 'TeamName': 'HighFive Robotics'}, {'TeamNum': 17871, 'OPR': 89.834, 'Auto': 13.818, 'CCWM': 0.958, 'TeamName': 'Thobor RO 068'}, {'TeamNum': 19063, 'OPR': 88.889, 'Auto': 22.002, 'CCWM': 28.686, 'TeamName': 'UnderConstruction'}, {'TeamNum': 19116, 'OPR': 87.04, 'Auto': 20.62, 'CCWM': 41.141, 'TeamName': 'VV Robots'}, {'TeamNum': 19151, 'OPR': 86.971, 'Auto': 24.097, 'CCWM': 42.872, 'TeamName': 'TECHNO-MAISTER'}, {'TeamNum': 19342, 'OPR': 83.332, 'Auto': 22.46, 'CCWM': 6.968, 'TeamName': 'Clever Core'}, {'TeamNum': 19055, 'OPR': 83.325, 'Auto': 14.716, 'CCWM': 19.502, 'TeamName': 'TITANS'}, {'TeamNum': 17860, 'OPR': 81.934, 'Auto': 18.34, 'CCWM': 67.161, 'TeamName': 'Helix'}, {'TeamNum': 17881, 'OPR': 80.862, 'Auto': 16.509, 'CCWM': -28.296, 'TeamName': 'RiverWolves'}, {'TeamNum': 19074, 'OPR': 79.678, 'Auto': 18.648, 'CCWM': 37.439, 'TeamName': 'Extropy'}, {'TeamNum': 17844, 'OPR': 77.791, 'Auto': 22.354, 'CCWM': 13.17, 'TeamName': 'RUBIX'}, {'TeamNum': 19061, 'OPR': 76.499, 'Auto': 15.243, 'CCWM': 7.394, 'TeamName': 'Boogeybots'}, {'TeamNum': 17870, 'OPR': 76.316, 'Auto': 23.996, 'CCWM': 46.509, 'TeamName': 'PERPETUUM MOBILE'}, {'TeamNum': 19119, 'OPR': 74.186, 'Auto': 19.298, 'CCWM': -18.818, 'TeamName': 'InfotronX'}, {'TeamNum': 19091, 'OPR': 71.108, 'Auto': 9.828, 'CCWM': -3.454, 'TeamName': 'The Resistance'}, {'TeamNum': 19099, 'OPR': 69.902, 'Auto': 17.037, 'CCWM': 47.525, 'TeamName': 'H-tech'}, {'TeamNum': 19246, 'OPR': 66.278, 'Auto': 19.519, 'CCWM': -29.258, 'TeamName': 'Cybersouls'}, {'TeamNum': 19097, 'OPR': 65.899, 'Auto': 5.931, 'CCWM': 0.736, 'TeamName': 'Quasar.Robotics'}, {'TeamNum': 12632, 'OPR': 65.807, 'Auto': 19.308, 'CCWM': 4.261, 'TeamName': 'Transilvania Robotix'}, {'TeamNum': 19120, 'OPR': 65.606, 'Auto': 11.161, 'CCWM': -11.167, 'TeamName': 'AlphaBit'}, {'TeamNum': 19071, 'OPR': 65.271, 'Auto': 19.321, 'CCWM': 24.564, 'TeamName': 'SmartCluster'}, {'TeamNum': 19073, 'OPR': 64.918, 'Auto': 13.35, 'CCWM': 46.772, 'TeamName': 'The Emperor RO124'}, {'TeamNum': 19072, 'OPR': 64.692, 'Auto': 18.576, 'CCWM': -13.112, 'TeamName': 'TehnoZ Junior'}, {'TeamNum': 17855, 'OPR': 64.395, 'Auto': 21.349, 'CCWM': 48.342, 'TeamName': 'Vortex Breakers'}, {'TeamNum': 19292, 'OPR': 63.644, 'Auto': 20.219, 'CCWM': -28.178, 'TeamName': 'TeamPhoenix'}, {'TeamNum': 19047, 'OPR': 63.563, 'Auto': 6.561, 'CCWM': -14.741, 'TeamName': 'RavenTech_HD'}, {'TeamNum': 19077, 'OPR': 62.996, 'Auto': 21.683, 'CCWM': -8.394, 'TeamName': 'Robocadet'}, {'TeamNum': 20043, 'OPR': 61.887, 'Auto': 22.651, 'CCWM': 5.446, 'TeamName': 'SNGine'}, {'TeamNum': 19065, 'OPR': 61.74, 'Auto': 15.958, 'CCWM': -45.854, 'TeamName': 'Inorog Team RO 152'}, {'TeamNum': 19086, 'OPR': 61.702, 'Auto': 16.895, 'CCWM': -2.329, 'TeamName': 'Robocorns RO004'}, {'TeamNum': 17624, 'OPR': 59.21, 'Auto': 9.517, 'CCWM': 15.693, 'TeamName': 'IGNITE.'}, {'TeamNum': 19111, 'OPR': 58.604, 'Auto': 6.778, 'CCWM': -1.958, 'TeamName': 'TITUR0B0'}, {'TeamNum': 19103, 'OPR': 58.168, 'Auto': 17.602, 'CCWM': -17.544, 'TeamName': 'Kronbot'}, {'TeamNum': 19076, 'OPR': 56.115, 'Auto': 4.874, 'CCWM': 17.528, 'TeamName': 'RoboticsTrav'}, {'TeamNum': 17875, 'OPR': 53.215, 'Auto': 12.614, 'CCWM': -39.288, 'TeamName': 'Code Warriors'}, {'TeamNum': 19176, 'OPR': 52.326, 'Auto': 19.152, 'CCWM': -5.133, 'TeamName': 'Broboti'}, {'TeamNum': 15966, 'OPR': 50.224, 'Auto': 13.897, 'CCWM': -25.143, 'TeamName': 'Esentza Revolution'}, {'TeamNum': 17089, 'OPR': 49.868, 'Auto': 17.683, 'CCWM': -24.104, 'TeamName': 'Powered by Redstone'}, {'TeamNum': 20265, 'OPR': 49.469, 'Auto': 8.587, 'CCWM': -39.782, 'TeamName': 'Heart of RoBots'}, {'TeamNum': 9662, 'OPR': 45.215, 'Auto': 15.965, 'CCWM': -12.362, 'TeamName': 'Apollo'}, {'TeamNum': 19117, 'OPR': 44.739, 'Auto': 12.303, 'CCWM': 10.338, 'TeamName': 'Robo-Sapiens'}, {'TeamNum': 19242, 'OPR': 43.014, 'Auto': 11.602, 'CCWM': -16.192, 'TeamName': 'RO169 RoboPeda'}, {'TeamNum': 21031, 'OPR': 42.769, 'Auto': 13.507, 'CCWM': -18.073, 'TeamName': 'roLERbot'}, {'TeamNum': 15989, 'OPR': 42.663, 'Auto': 12.623, 'CCWM': -65.443, 'TeamName': 'RoboTitans'}, {'TeamNum': 19094, 'OPR': 41.933, 'Auto': 4.169, 'CCWM': -58.096, 'TeamName': 'WizzTech'}, {'TeamNum': 19082, 'OPR': 40.81, 'Auto': 16.194, 'CCWM': -18.992, 'TeamName': 'RoboAS'}, {'TeamNum': 20329, 'OPR': 38.78, 'Auto': 10.537, 'CCWM': -43.244, 'TeamName': 'TechnoGods'}, {'TeamNum': 19110, 'OPR': 37.4, 'Auto': 4.697, 'CCWM': -37.689, 'TeamName': 'R0B0SMART'}, {'TeamNum': 19115, 'OPR': 36.665, 'Auto': 11.737, 'CCWM': -52.375, 'TeamName': 'B-RoboTeam RO 064'}, {'TeamNum': 19134, 'OPR': 36.659, 'Auto': 9.706, 'CCWM': -32.715, 'TeamName': 'Rodac'}, {'TeamNum': 15965, 'OPR': 35.679, 'Auto': 10.001, 'CCWM': -62.235, 'TeamName': 'Esentza Robotics'}, {'TeamNum': 19053, 'OPR': 32.262, 'Auto': 1.041, 'CCWM': -14.389, 'TeamName': 'Homosapiens'}, {'TeamNum': 20985, 'OPR': 32.207, 'Auto': 9.688, 'CCWM': -45.356, 'TeamName': 'Wafy '}, {'TeamNum': 19056, 'OPR': 30.518, 'Auto': 7.596, 'CCWM': -56.187, 'TeamName': 'PrimeTech'}, {'TeamNum': 19102, 'OPR': 30.193, 'Auto': 5.612, 'CCWM': -63.792, 'TeamName': 'TheArchitechs'}, {'TeamNum': 17965, 'OPR': 29.952, 'Auto': 9.254, 'CCWM': -35.108, 'TeamName': 'BOLTS AND GEARS'}, {'TeamNum': 17532, 'OPR': 21.709, 'Auto': -0.741, 'CCWM': -19.594, 'TeamName': 'Centered Robotics'}, {'TeamNum': 15975, 'OPR': 20.43, 'Auto': -1.453, 'CCWM': -57.043, 'TeamName': 'ROBOTX HUNEDOARA'}, {'TeamNum': 19054, 'OPR': 15.407, 'Auto': 14.004, 'CCWM': -9.023, 'TeamName': 'NeuroBotix'}, {'TeamNum': 21033, 'OPR': 12.353, 'Auto': 8.973, 'CCWM': -39.811, 'TeamName': 'HYPE'}, {'TeamNum': 20732, 'OPR': 12.278, 'Auto': 3.846, 'CCWM': -86.063, 'TeamName': 'ATLAS_CNB_192'}, {'TeamNum': 19128, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'RoboDac Dacia'}]
ROBUQ2
[{'TeamNum': 12560, 'OPR': 158.86, 'Auto': 44.955, 'CCWM': 76.588, 'TeamName': 'Soft Hoarders'}, {'TeamNum': 19109, 'OPR': 138.679, 'Auto': 32.105, 'CCWM': 27.04, 'TeamName': 'RaSky'}, {'TeamNum': 18160, 'OPR': 126.916, 'Auto': 21.814, 'CCWM': 85.899, 'TeamName': '4D-Robotics'}, {'TeamNum': 19079, 'OPR': 121.019, 'Auto': 18.754, 'CCWM': 58.607, 'TeamName': 'PHOENIX'}, {'TeamNum': 18338, 'OPR': 116.935, 'Auto': 20.115, 'CCWM': -21.861, 'TeamName': 'StarTech'}, {'TeamNum': 17243, 'OPR': 115.214, 'Auto': 22.057, 'CCWM': 60.626, 'TeamName': 'Vianu Legends'}, {'TeamNum': 19104, 'OPR': 104.65, 'Auto': 21.729, 'CCWM': 58.341, 'TeamName': 'CyberPunk Robotics'}, {'TeamNum': 19062, 'OPR': 100.308, 'Auto': 21.32, 'CCWM': 57.326, 'TeamName': 'Phantom Robotics'}, {'TeamNum': 14277, 'OPR': 96.998, 'Auto': 25.079, 'CCWM': 13.075, 'TeamName': 'QUBE.'}, {'TeamNum': 16166, 'OPR': 95.487, 'Auto': 28.673, 'CCWM': 53.255, 'TeamName': "Watt'S Up"}, {'TeamNum': 15972, 'OPR': 94.586, 'Auto': 29.717, 'CCWM': 58.215, 'TeamName': 'TehnoZ'}, {'TeamNum': 11808, 'OPR': 93.08, 'Auto': 6.86, 'CCWM': 65.194, 'TeamName': 'Connection'}, {'TeamNum': 20135, 'OPR': 92.554, 'Auto': 16.17, 'CCWM': 13.702, 'TeamName': 'MeeralRobotics'}, {'TeamNum': 14278, 'OPR': 92.375, 'Auto': 20.504, 'CCWM': 36.656, 'TeamName': 'Xeo'}, {'TeamNum': 19049, 'OPR': 90.845, 'Auto': 18.517, 'CCWM': 71.967, 'TeamName': 'HighFive Robotics'}, {'TeamNum': 17871, 'OPR': 89.834, 'Auto': 13.818, 'CCWM': 0.958, 'TeamName': 'Thobor RO 068'}, {'TeamNum': 19063, 'OPR': 88.889, 'Auto': 22.002, 'CCWM': 28.686, 'TeamName': 'UnderConstruction'}, {'TeamNum': 19116, 'OPR': 87.04, 'Auto': 20.62, 'CCWM': 41.141, 'TeamName': 'VV Robots'}, {'TeamNum': 19151, 'OPR': 86.971, 'Auto': 24.097, 'CCWM': 42.872, 'TeamName': 'TECHNO-MAISTER'}, {'TeamNum': 19342, 'OPR': 83.332, 'Auto': 22.46, 'CCWM': 6.968, 'TeamName': 'Clever Core'}, {'TeamNum': 19055, 'OPR': 83.325, 'Auto': 14.716, 'CCWM': 19.502, 'TeamName': 'TITANS'}, {'TeamNum': 17860, 'OPR': 81.934, 'Auto': 18.34, 'CCWM': 67.161, 'TeamName': 'Helix'}, {'TeamNum': 17881, 'OPR': 80.862, 'Auto': 16.509, 'CCWM': -28.296, 'TeamName': 'RiverWolves'}, {'TeamNum': 19074, 'OPR': 79.678, 'Auto': 18.648, 'CCWM': 37.439, 'TeamName': 'Extropy'}, {'TeamNum': 17844, 'OPR': 77.791, 'Auto': 22.354, 'CCWM': 13.17, 'TeamName': 'RUBIX'}, {'TeamNum': 19061, 'OPR': 76.499, 'Auto': 15.243, 'CCWM': 7.394, 'TeamName': 'Boogeybots'}, {'TeamNum': 17870, 'OPR': 76.316, 'Auto': 23.996, 'CCWM': 46.509, 'TeamName': 'PERPETUUM MOBILE'}, {'TeamNum': 19119, 'OPR': 74.186, 'Auto': 19.298, 'CCWM': -18.818, 'TeamName': 'InfotronX'}, {'TeamNum': 19091, 'OPR': 71.108, 'Auto': 9.828, 'CCWM': -3.454, 'TeamName': 'The Resistance'}, {'TeamNum': 19099, 'OPR': 69.902, 'Auto': 17.037, 'CCWM': 47.525, 'TeamName': 'H-tech'}, {'TeamNum': 19246, 'OPR': 66.278, 'Auto': 19.519, 'CCWM': -29.258, 'TeamName': 'Cybersouls'}, {'TeamNum': 19097, 'OPR': 65.899, 'Auto': 5.931, 'CCWM': 0.736, 'TeamName': 'Quasar.Robotics'}, {'TeamNum': 12632, 'OPR': 65.807, 'Auto': 19.308, 'CCWM': 4.261, 'TeamName': 'Transilvania Robotix'}, {'TeamNum': 19120, 'OPR': 65.606, 'Auto': 11.161, 'CCWM': -11.167, 'TeamName': 'AlphaBit'}, {'TeamNum': 19071, 'OPR': 65.271, 'Auto': 19.321, 'CCWM': 24.564, 'TeamName': 'SmartCluster'}, {'TeamNum': 19073, 'OPR': 64.918, 'Auto': 13.35, 'CCWM': 46.772, 'TeamName': 'The Emperor RO124'}, {'TeamNum': 19072, 'OPR': 64.692, 'Auto': 18.576, 'CCWM': -13.112, 'TeamName': 'TehnoZ Junior'}, {'TeamNum': 17855, 'OPR': 64.395, 'Auto': 21.349, 'CCWM': 48.342, 'TeamName': 'Vortex Breakers'}, {'TeamNum': 19292, 'OPR': 63.644, 'Auto': 20.219, 'CCWM': -28.178, 'TeamName': 'TeamPhoenix'}, {'TeamNum': 19047, 'OPR': 63.563, 'Auto': 6.561, 'CCWM': -14.741, 'TeamName': 'RavenTech_HD'}, {'TeamNum': 19077, 'OPR': 62.996, 'Auto': 21.683, 'CCWM': -8.394, 'TeamName': 'Robocadet'}, {'TeamNum': 20043, 'OPR': 61.887, 'Auto': 22.651, 'CCWM': 5.446, 'TeamName': 'SNGine'}, {'TeamNum': 19065, 'OPR': 61.74, 'Auto': 15.958, 'CCWM': -45.854, 'TeamName': 'Inorog Team RO 152'}, {'TeamNum': 19086, 'OPR': 61.702, 'Auto': 16.895, 'CCWM': -2.329, 'TeamName': 'Robocorns RO004'}, {'TeamNum': 17624, 'OPR': 59.21, 'Auto': 9.517, 'CCWM': 15.693, 'TeamName': 'IGNITE.'}, {'TeamNum': 19111, 'OPR': 58.604, 'Auto': 6.778, 'CCWM': -1.958, 'TeamName': 'TITUR0B0'}, {'TeamNum': 19103, 'OPR': 58.168, 'Auto': 17.602, 'CCWM': -17.544, 'TeamName': 'Kronbot'}, {'TeamNum': 19076, 'OPR': 56.115, 'Auto': 4.874, 'CCWM': 17.528, 'TeamName': 'RoboticsTrav'}, {'TeamNum': 17875, 'OPR': 53.215, 'Auto': 12.614, 'CCWM': -39.288, 'TeamName': 'Code Warriors'}, {'TeamNum': 19176, 'OPR': 52.326, 'Auto': 19.152, 'CCWM': -5.133, 'TeamName': 'Broboti'}, {'TeamNum': 15966, 'OPR': 50.224, 'Auto': 13.897, 'CCWM': -25.143, 'TeamName': 'Esentza Revolution'}, {'TeamNum': 17089, 'OPR': 49.868, 'Auto': 17.683, 'CCWM': -24.104, 'TeamName': 'Powered by Redstone'}, {'TeamNum': 20265, 'OPR': 49.469, 'Auto': 8.587, 'CCWM': -39.782, 'TeamName': 'Heart of RoBots'}, {'TeamNum': 9662, 'OPR': 45.215, 'Auto': 15.965, 'CCWM': -12.362, 'TeamName': 'Apollo'}, {'TeamNum': 19117, 'OPR': 44.739, 'Auto': 12.303, 'CCWM': 10.338, 'TeamName': 'Robo-Sapiens'}, {'TeamNum': 19242, 'OPR': 43.014, 'Auto': 11.602, 'CCWM': -16.192, 'TeamName': 'RO169 RoboPeda'}, {'TeamNum': 21031, 'OPR': 42.769, 'Auto': 13.507, 'CCWM': -18.073, 'TeamName': 'roLERbot'}, {'TeamNum': 15989, 'OPR': 42.663, 'Auto': 12.623, 'CCWM': -65.443, 'TeamName': 'RoboTitans'}, {'TeamNum': 19094, 'OPR': 41.933, 'Auto': 4.169, 'CCWM': -58.096, 'TeamName': 'WizzTech'}, {'TeamNum': 19082, 'OPR': 40.81, 'Auto': 16.194, 'CCWM': -18.992, 'TeamName': 'RoboAS'}, {'TeamNum': 20329, 'OPR': 38.78, 'Auto': 10.537, 'CCWM': -43.244, 'TeamName': 'TechnoGods'}, {'TeamNum': 19110, 'OPR': 37.4, 'Auto': 4.697, 'CCWM': -37.689, 'TeamName': 'R0B0SMART'}, {'TeamNum': 19115, 'OPR': 36.665, 'Auto': 11.737, 'CCWM': -52.375, 'TeamName': 'B-RoboTeam RO 064'}, {'TeamNum': 19134, 'OPR': 36.659, 'Auto': 9.706, 'CCWM': -32.715, 'TeamName': 'Rodac'}, {'TeamNum': 15965, 'OPR': 35.679, 'Auto': 10.001, 'CCWM': -62.235, 'TeamName': 'Esentza Robotics'}, {'TeamNum': 19053, 'OPR': 32.262, 'Auto': 1.041, 'CCWM': -14.389, 'TeamName': 'Homosapiens'}, {'TeamNum': 20985, 'OPR': 32.207, 'Auto': 9.688, 'CCWM': -45.356, 'TeamName': 'Wafy '}, {'TeamNum': 19056, 'OPR': 30.518, 'Auto': 7.596, 'CCWM': -56.187, 'TeamName': 'PrimeTech'}, {'TeamNum': 19102, 'OPR': 30.193, 'Auto': 5.612, 'CCWM': -63.792, 'TeamName': 'TheArchitechs'}, {'TeamNum': 17965, 'OPR': 29.952, 'Auto': 9.254, 'CCWM': -35.108, 'TeamName': 'BOLTS AND GEARS'}, {'TeamNum': 17532, 'OPR': 21.709, 'Auto': -0.741, 'CCWM': -19.594, 'TeamName': 'Centered Robotics'}, {'TeamNum': 15975, 'OPR': 20.43, 'Auto': -1.453, 'CCWM': -57.043, 'TeamName': 'ROBOTX HUNEDOARA'}, {'TeamNum': 19054, 'OPR': 15.407, 'Auto': 14.004, 'CCWM': -9.023, 'TeamName': 'NeuroBotix'}, {'TeamNum': 21033, 'OPR': 12.353, 'Auto': 8.973, 'CCWM': -39.811, 'TeamName': 'HYPE'}, {'TeamNum': 20732, 'OPR': 12.278, 'Auto': 3.846, 'CCWM': -86.063, 'TeamName': 'ATLAS_CNB_192'}, {'TeamNum': 19128, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'RoboDac Dacia'}]

i 1032
{'20972', '21097', '19092', '19088', '19095', '20691', '19081', '19066', '19211', '21028', '15993', '21169', '19098', '19100', '19060', '17857', '19257', '19112', '20131', '19152', '17713', '19048', '14270', '19067', '19093', '19105', '19058', '19147', '19083', '19059', '19090', '19064', '19139', '19256', '19052', '20925', '22114', '21050', '20936', '20957', '19234', '17861', '21073', '22017', '13906', '21030', '21071', '19131', '17869', '21455', '20912', '19043', '19148', '19121', '16000', '18026', '15996', '19068', '5843', '19087', '19096', '17873', '20954', '19101', '20965', '21476', '19141', '20974', '19044', '20237', '19106', '19075', '17962', '20880', '19084', '22018'}
[{'TeamNum': 19121, 'OPR': 164.328, 'Auto': 43.138, 'CCWM': 128.02, 'TeamName': 'Tea Borgs'}, {'TeamNum': 19234, 'OPR': 148.076, 'Auto': 42.531, 'CCWM': 145.151, 'TeamName': 'BYTE FORCE'}, {'TeamNum': 17962, 'OPR': 144.212, 'Auto': 40.508, 'CCWM': 114.677, 'TeamName': 'Ro2D2'}, {'TeamNum': 19093, 'OPR': 140.743, 'Auto': 25.483, 'CCWM': 50.857, 'TeamName': 'Infinity Bolts '}, {'TeamNum': 19098, 'OPR': 138.936, 'Auto': 39.799, 'CCWM': 72.185, 'TeamName': 'Eastern Foxes'}, {'TeamNum': 17861, 'OPR': 124.46, 'Auto': 26.213, 'CCWM': 98.292, 'TeamName': 'CSH'}, {'TeamNum': 19068, 'OPR': 121.604, 'Auto': 29.001, 'CCWM': 62.201, 'TeamName': 'ABSO-TECH'}, {'TeamNum': 19044, 'OPR': 120.595, 'Auto': 20.921, 'CCWM': 39.102, 'TeamName': 'Peppers'}, {'TeamNum': 19101, 'OPR': 116.695, 'Auto': 39.02, 'CCWM': 49.241, 'TeamName': 'Tech-X'}, {'TeamNum': 19106, 'OPR': 115.847, 'Auto': 23.702, 'CCWM': 33.354, 'TeamName': 'Dark Energy'}, {'TeamNum': 19105, 'OPR': 112.169, 'Auto': 33.139, 'CCWM': 117.194, 'TeamName': 'DecebalTech'}, {'TeamNum': 5843, 'OPR': 111.111, 'Auto': 30.609, 'CCWM': 41.92, 'TeamName': 'AutoVortex'}, {'TeamNum': 18026, 'OPR': 105.927, 'Auto': 26.593, 'CCWM': 16.597, 'TeamName': 'SGBOTS'}, {'TeamNum': 16000, 'OPR': 102.853, 'Auto': 29.452, 'CCWM': 8.863, 'TeamName': 'Gear Maniacs'}, {'TeamNum': 20912, 'OPR': 98.628, 'Auto': 21.857, 'CCWM': 66.527, 'TeamName': 'Harambe Cartel'}, {'TeamNum': 17873, 'OPR': 94.012, 'Auto': 26.81, 'CCWM': 22.973, 'TeamName': 'VECTRON'}, {'TeamNum': 19096, 'OPR': 93.154, 'Auto': 20.994, 'CCWM': 40.919, 'TeamName': 'DanubeRobotics'}, {'TeamNum': 19066, 'OPR': 92.021, 'Auto': 26.867, 'CCWM': 11.929, 'TeamName': 'AiCitizensRO160'}, {'TeamNum': 19083, 'OPR': 91.135, 'Auto': 31.199, 'CCWM': 27.183, 'TeamName': 'North East Dynamics'}, {'TeamNum': 21097, 'OPR': 89.16, 'Auto': 23.855, 'CCWM': 62.411, 'TeamName': 'Dragonfly'}, {'TeamNum': 20974, 'OPR': 88.461, 'Auto': 21.81, 'CCWM': 19.414, 'TeamName': 'Hardwired'}, {'TeamNum': 19048, 'OPR': 87.181, 'Auto': 25.292, 'CCWM': 18.996, 'TeamName': 'ROBOPAPIU'}, {'TeamNum': 17713, 'OPR': 85.309, 'Auto': 22.865, 'CCWM': 6.587, 'TeamName': 'Delta Force'}, {'TeamNum': 15993, 'OPR': 78.83, 'Auto': 29.466, 'CCWM': -3.969, 'TeamName': 'infO(1)Robotics'}, {'TeamNum': 19058, 'OPR': 77.145, 'Auto': 27.034, 'CCWM': -38.482, 'TeamName': 'Modus Vivendi'}, {'TeamNum': 17857, 'OPR': 77.092, 'Auto': 21.36, 'CCWM': 18.525, 'TeamName': 'Gentlemen'}, {'TeamNum': 17869, 'OPR': 75.604, 'Auto': 25.167, 'CCWM': 1.203, 'TeamName': 'ERcast2020'}, {'TeamNum': 21028, 'OPR': 74.699, 'Auto': 29.84, 'CCWM': 22.077, 'TeamName': 'The Eagles RO143'}, {'TeamNum': 22017, 'OPR': 74.205, 'Auto': 25.051, 'CCWM': -13.605, 'TeamName': 'Eu codez'}, {'TeamNum': 19211, 'OPR': 73.877, 'Auto': 11.806, 'CCWM': 19.553, 'TeamName': 'VirtualWolvesRO165'}, {'TeamNum': 21455, 'OPR': 73.754, 'Auto': 9.884, 'CCWM': 13.159, 'TeamName': 'RoSophia'}, {'TeamNum': 14270, 'OPR': 72.534, 'Auto': 23.677, 'CCWM': 42.025, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 21030, 'OPR': 72.457, 'Auto': 14.873, 'CCWM': -10.073, 'TeamName': 'MasterBots'}, {'TeamNum': 19043, 'OPR': 70.93, 'Auto': 12.916, 'CCWM': 40.119, 'TeamName': 'CyLiis'}, {'TeamNum': 19131, 'OPR': 68.905, 'Auto': 25.819, 'CCWM': -39.012, 'TeamName': 'Evolution'}, {'TeamNum': 21476, 'OPR': 67.441, 'Auto': 15.874, 'CCWM': -11.296, 'TeamName': 'ViCyber'}, {'TeamNum': 19139, 'OPR': 64.226, 'Auto': 25.946, 'CCWM': 3.681, 'TeamName': 'Snake-Tech40'}, {'TeamNum': 19059, 'OPR': 63.856, 'Auto': 23.685, 'CCWM': -16.455, 'TeamName': 'ArtRobotix'}, {'TeamNum': 19095, 'OPR': 63.02, 'Auto': 13.359, 'CCWM': 46.415, 'TeamName': 'WireImpulse'}, {'TeamNum': 19087, 'OPR': 60.367, 'Auto': 15.865, 'CCWM': -20.429, 'TeamName': 'MironoBot'}, {'TeamNum': 19067, 'OPR': 60.343, 'Auto': 8.706, 'CCWM': 48.418, 'TeamName': 'BIONIC ROYALS'}, {'TeamNum': 20691, 'OPR': 59.274, 'Auto': 26.274, 'CCWM': -11.596, 'TeamName': 'Andromeda'}, {'TeamNum': 19100, 'OPR': 58.476, 'Auto': 14.735, 'CCWM': -0.041, 'TeamName': 'Future Tech'}, {'TeamNum': 20237, 'OPR': 54.313, 'Auto': 11.147, 'CCWM': 12.118, 'TeamName': 'LTCDMNrobotics'}, {'TeamNum': 20925, 'OPR': 51.2, 'Auto': 11.131, 'CCWM': -22.813, 'TeamName': 'HYPERCUBE'}, {'TeamNum': 19090, 'OPR': 51.053, 'Auto': 10.253, 'CCWM': -37.089, 'TeamName': 'TEHROCUZ RO 067'}, {'TeamNum': 19052, 'OPR': 50.612, 'Auto': 20.077, 'CCWM': -11.278, 'TeamName': 'Trojan.EXE'}, {'TeamNum': 19084, 'OPR': 50.476, 'Auto': -1.444, 'CCWM': -43.26, 'TeamName': 'SovaTech'}, {'TeamNum': 19081, 'OPR': 45.522, 'Auto': 9.21, 'CCWM': -39.92, 'TeamName': "Bots' Brain"}, {'TeamNum': 20131, 'OPR': 45.096, 'Auto': 18.111, 'CCWM': -45.406, 'TeamName': 'The Inventors'}, {'TeamNum': 19141, 'OPR': 44.663, 'Auto': 16.712, 'CCWM': -70.196, 'TeamName': 'BraveBots'}, {'TeamNum': 20954, 'OPR': 43.902, 'Auto': 22.706, 'CCWM': -20.841, 'TeamName': 'STIM DC'}, {'TeamNum': 20936, 'OPR': 43.371, 'Auto': 18.213, 'CCWM': 0.142, 'TeamName': 'ET.CNSCM'}, {'TeamNum': 19064, 'OPR': 41.519, 'Auto': 16.081, 'CCWM': 12.281, 'TeamName': 'Dragonic Force'}, {'TeamNum': 19152, 'OPR': 39.942, 'Auto': 10.647, 'CCWM': -57.242, 'TeamName': 'Brainstorms'}, {'TeamNum': 19147, 'OPR': 39.669, 'Auto': 5.802, 'CCWM': -28.965, 'TeamName': 'Blizzard Eye'}, {'TeamNum': 19256, 'OPR': 33.112, 'Auto': 10.349, 'CCWM': -36.528, 'TeamName': 'CYBERMOON093'}, {'TeamNum': 22018, 'OPR': 32.903, 'Auto': 1.352, 'CCWM': -78.545, 'TeamName': 'Orion Robotix'}, {'TeamNum': 22114, 'OPR': 32.527, 'Auto': 21.983, 'CCWM': -30.772, 'TeamName': 'TeoretiKa'}, {'TeamNum': 21050, 'OPR': 29.001, 'Auto': 9.368, 'CCWM': -28.853, 'TeamName': 'MasterMinds'}, {'TeamNum': 21071, 'OPR': 28.874, 'Auto': 11.435, 'CCWM': -43.617, 'TeamName': 'SkyLine'}, {'TeamNum': 19075, 'OPR': 27.839, 'Auto': 8.487, 'CCWM': 5.721, 'TeamName': 'Clockworks'}, {'TeamNum': 19257, 'OPR': 27.663, 'Auto': 3.286, 'CCWM': -40.726, 'TeamName': 'UNplugged188'}, {'TeamNum': 19148, 'OPR': 26.569, 'Auto': 11.619, 'CCWM': -54.728, 'TeamName': 'StefTech'}, {'TeamNum': 19112, 'OPR': 25.791, 'Auto': 7.024, 'CCWM': -46.861, 'TeamName': 'RO112 UNDEFINED'}, {'TeamNum': 15996, 'OPR': 25.67, 'Auto': 5.822, 'CCWM': -46.153, 'TeamName': 'BrickBot'}, {'TeamNum': 21073, 'OPR': 24.079, 'Auto': 11.133, 'CCWM': -90.285, 'TeamName': 'November Eleven'}, {'TeamNum': 13906, 'OPR': 17.56, 'Auto': -4.402, 'CCWM': -32.344, 'TeamName': 'Epiteugma Revved Up'}, {'TeamNum': 20965, 'OPR': 16.354, 'Auto': 12.847, 'CCWM': -106.735, 'TeamName': 'BIT-MO'}, {'TeamNum': 19060, 'OPR': 15.869, 'Auto': -5.773, 'CCWM': -21.946, 'TeamName': 'InfinityEdge'}, {'TeamNum': 21169, 'OPR': 10.774, 'Auto': -0.903, 'CCWM': -71.273, 'TeamName': 'CyberLions'}, {'TeamNum': 19092, 'OPR': 5.844, 'Auto': -0.293, 'CCWM': -114.709, 'TeamName': 'ICLASS '}, {'TeamNum': 20957, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Motion Bot'}, {'TeamNum': 20880, 'OPR': 0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'RoboGraphed'}, {'TeamNum': 19088, 'OPR': -3.505, 'Auto': -0.333, 'CCWM': -37.504, 'TeamName': 'BROBOTS'}, {'TeamNum': 20972, 'OPR': -11.184, 'Auto': -3.201, 'CCWM': -82.477, 'TeamName': 'VOLTA CIRCUITS'}]
ROBUQ1
[{'TeamNum': 19121, 'OPR': 164.328, 'Auto': 43.138, 'CCWM': 128.02, 'TeamName': 'Tea Borgs'}, {'TeamNum': 19234, 'OPR': 148.076, 'Auto': 42.531, 'CCWM': 145.151, 'TeamName': 'BYTE FORCE'}, {'TeamNum': 17962, 'OPR': 144.212, 'Auto': 40.508, 'CCWM': 114.677, 'TeamName': 'Ro2D2'}, {'TeamNum': 19093, 'OPR': 140.743, 'Auto': 25.483, 'CCWM': 50.857, 'TeamName': 'Infinity Bolts '}, {'TeamNum': 19098, 'OPR': 138.936, 'Auto': 39.799, 'CCWM': 72.185, 'TeamName': 'Eastern Foxes'}, {'TeamNum': 17861, 'OPR': 124.46, 'Auto': 26.213, 'CCWM': 98.292, 'TeamName': 'CSH'}, {'TeamNum': 19068, 'OPR': 121.604, 'Auto': 29.001, 'CCWM': 62.201, 'TeamName': 'ABSO-TECH'}, {'TeamNum': 19044, 'OPR': 120.595, 'Auto': 20.921, 'CCWM': 39.102, 'TeamName': 'Peppers'}, {'TeamNum': 19101, 'OPR': 116.695, 'Auto': 39.02, 'CCWM': 49.241, 'TeamName': 'Tech-X'}, {'TeamNum': 19106, 'OPR': 115.847, 'Auto': 23.702, 'CCWM': 33.354, 'TeamName': 'Dark Energy'}, {'TeamNum': 19105, 'OPR': 112.169, 'Auto': 33.139, 'CCWM': 117.194, 'TeamName': 'DecebalTech'}, {'TeamNum': 5843, 'OPR': 111.111, 'Auto': 30.609, 'CCWM': 41.92, 'TeamName': 'AutoVortex'}, {'TeamNum': 18026, 'OPR': 105.927, 'Auto': 26.593, 'CCWM': 16.597, 'TeamName': 'SGBOTS'}, {'TeamNum': 16000, 'OPR': 102.853, 'Auto': 29.452, 'CCWM': 8.863, 'TeamName': 'Gear Maniacs'}, {'TeamNum': 20912, 'OPR': 98.628, 'Auto': 21.857, 'CCWM': 66.527, 'TeamName': 'Harambe Cartel'}, {'TeamNum': 17873, 'OPR': 94.012, 'Auto': 26.81, 'CCWM': 22.973, 'TeamName': 'VECTRON'}, {'TeamNum': 19096, 'OPR': 93.154, 'Auto': 20.994, 'CCWM': 40.919, 'TeamName': 'DanubeRobotics'}, {'TeamNum': 19066, 'OPR': 92.021, 'Auto': 26.867, 'CCWM': 11.929, 'TeamName': 'AiCitizensRO160'}, {'TeamNum': 19083, 'OPR': 91.135, 'Auto': 31.199, 'CCWM': 27.183, 'TeamName': 'North East Dynamics'}, {'TeamNum': 21097, 'OPR': 89.16, 'Auto': 23.855, 'CCWM': 62.411, 'TeamName': 'Dragonfly'}, {'TeamNum': 20974, 'OPR': 88.461, 'Auto': 21.81, 'CCWM': 19.414, 'TeamName': 'Hardwired'}, {'TeamNum': 19048, 'OPR': 87.181, 'Auto': 25.292, 'CCWM': 18.996, 'TeamName': 'ROBOPAPIU'}, {'TeamNum': 17713, 'OPR': 85.309, 'Auto': 22.865, 'CCWM': 6.587, 'TeamName': 'Delta Force'}, {'TeamNum': 15993, 'OPR': 78.83, 'Auto': 29.466, 'CCWM': -3.969, 'TeamName': 'infO(1)Robotics'}, {'TeamNum': 19058, 'OPR': 77.145, 'Auto': 27.034, 'CCWM': -38.482, 'TeamName': 'Modus Vivendi'}, {'TeamNum': 17857, 'OPR': 77.092, 'Auto': 21.36, 'CCWM': 18.525, 'TeamName': 'Gentlemen'}, {'TeamNum': 17869, 'OPR': 75.604, 'Auto': 25.167, 'CCWM': 1.203, 'TeamName': 'ERcast2020'}, {'TeamNum': 21028, 'OPR': 74.699, 'Auto': 29.84, 'CCWM': 22.077, 'TeamName': 'The Eagles RO143'}, {'TeamNum': 22017, 'OPR': 74.205, 'Auto': 25.051, 'CCWM': -13.605, 'TeamName': 'Eu codez'}, {'TeamNum': 19211, 'OPR': 73.877, 'Auto': 11.806, 'CCWM': 19.553, 'TeamName': 'VirtualWolvesRO165'}, {'TeamNum': 21455, 'OPR': 73.754, 'Auto': 9.884, 'CCWM': 13.159, 'TeamName': 'RoSophia'}, {'TeamNum': 14270, 'OPR': 72.534, 'Auto': 23.677, 'CCWM': 42.025, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 21030, 'OPR': 72.457, 'Auto': 14.873, 'CCWM': -10.073, 'TeamName': 'MasterBots'}, {'TeamNum': 19043, 'OPR': 70.93, 'Auto': 12.916, 'CCWM': 40.119, 'TeamName': 'CyLiis'}, {'TeamNum': 19131, 'OPR': 68.905, 'Auto': 25.819, 'CCWM': -39.012, 'TeamName': 'Evolution'}, {'TeamNum': 21476, 'OPR': 67.441, 'Auto': 15.874, 'CCWM': -11.296, 'TeamName': 'ViCyber'}, {'TeamNum': 19139, 'OPR': 64.226, 'Auto': 25.946, 'CCWM': 3.681, 'TeamName': 'Snake-Tech40'}, {'TeamNum': 19059, 'OPR': 63.856, 'Auto': 23.685, 'CCWM': -16.455, 'TeamName': 'ArtRobotix'}, {'TeamNum': 19095, 'OPR': 63.02, 'Auto': 13.359, 'CCWM': 46.415, 'TeamName': 'WireImpulse'}, {'TeamNum': 19087, 'OPR': 60.367, 'Auto': 15.865, 'CCWM': -20.429, 'TeamName': 'MironoBot'}, {'TeamNum': 19067, 'OPR': 60.343, 'Auto': 8.706, 'CCWM': 48.418, 'TeamName': 'BIONIC ROYALS'}, {'TeamNum': 20691, 'OPR': 59.274, 'Auto': 26.274, 'CCWM': -11.596, 'TeamName': 'Andromeda'}, {'TeamNum': 19100, 'OPR': 58.476, 'Auto': 14.735, 'CCWM': -0.041, 'TeamName': 'Future Tech'}, {'TeamNum': 20237, 'OPR': 54.313, 'Auto': 11.147, 'CCWM': 12.118, 'TeamName': 'LTCDMNrobotics'}, {'TeamNum': 20925, 'OPR': 51.2, 'Auto': 11.131, 'CCWM': -22.813, 'TeamName': 'HYPERCUBE'}, {'TeamNum': 19090, 'OPR': 51.053, 'Auto': 10.253, 'CCWM': -37.089, 'TeamName': 'TEHROCUZ RO 067'}, {'TeamNum': 19052, 'OPR': 50.612, 'Auto': 20.077, 'CCWM': -11.278, 'TeamName': 'Trojan.EXE'}, {'TeamNum': 19084, 'OPR': 50.476, 'Auto': -1.444, 'CCWM': -43.26, 'TeamName': 'SovaTech'}, {'TeamNum': 19081, 'OPR': 45.522, 'Auto': 9.21, 'CCWM': -39.92, 'TeamName': "Bots' Brain"}, {'TeamNum': 20131, 'OPR': 45.096, 'Auto': 18.111, 'CCWM': -45.406, 'TeamName': 'The Inventors'}, {'TeamNum': 19141, 'OPR': 44.663, 'Auto': 16.712, 'CCWM': -70.196, 'TeamName': 'BraveBots'}, {'TeamNum': 20954, 'OPR': 43.902, 'Auto': 22.706, 'CCWM': -20.841, 'TeamName': 'STIM DC'}, {'TeamNum': 20936, 'OPR': 43.371, 'Auto': 18.213, 'CCWM': 0.142, 'TeamName': 'ET.CNSCM'}, {'TeamNum': 19064, 'OPR': 41.519, 'Auto': 16.081, 'CCWM': 12.281, 'TeamName': 'Dragonic Force'}, {'TeamNum': 19152, 'OPR': 39.942, 'Auto': 10.647, 'CCWM': -57.242, 'TeamName': 'Brainstorms'}, {'TeamNum': 19147, 'OPR': 39.669, 'Auto': 5.802, 'CCWM': -28.965, 'TeamName': 'Blizzard Eye'}, {'TeamNum': 19256, 'OPR': 33.112, 'Auto': 10.349, 'CCWM': -36.528, 'TeamName': 'CYBERMOON093'}, {'TeamNum': 22018, 'OPR': 32.903, 'Auto': 1.352, 'CCWM': -78.545, 'TeamName': 'Orion Robotix'}, {'TeamNum': 22114, 'OPR': 32.527, 'Auto': 21.983, 'CCWM': -30.772, 'TeamName': 'TeoretiKa'}, {'TeamNum': 21050, 'OPR': 29.001, 'Auto': 9.368, 'CCWM': -28.853, 'TeamName': 'MasterMinds'}, {'TeamNum': 21071, 'OPR': 28.874, 'Auto': 11.435, 'CCWM': -43.617, 'TeamName': 'SkyLine'}, {'TeamNum': 19075, 'OPR': 27.839, 'Auto': 8.487, 'CCWM': 5.721, 'TeamName': 'Clockworks'}, {'TeamNum': 19257, 'OPR': 27.663, 'Auto': 3.286, 'CCWM': -40.726, 'TeamName': 'UNplugged188'}, {'TeamNum': 19148, 'OPR': 26.569, 'Auto': 11.619, 'CCWM': -54.728, 'TeamName': 'StefTech'}, {'TeamNum': 19112, 'OPR': 25.791, 'Auto': 7.024, 'CCWM': -46.861, 'TeamName': 'RO112 UNDEFINED'}, {'TeamNum': 15996, 'OPR': 25.67, 'Auto': 5.822, 'CCWM': -46.153, 'TeamName': 'BrickBot'}, {'TeamNum': 21073, 'OPR': 24.079, 'Auto': 11.133, 'CCWM': -90.285, 'TeamName': 'November Eleven'}, {'TeamNum': 13906, 'OPR': 17.56, 'Auto': -4.402, 'CCWM': -32.344, 'TeamName': 'Epiteugma Revved Up'}, {'TeamNum': 20965, 'OPR': 16.354, 'Auto': 12.847, 'CCWM': -106.735, 'TeamName': 'BIT-MO'}, {'TeamNum': 19060, 'OPR': 15.869, 'Auto': -5.773, 'CCWM': -21.946, 'TeamName': 'InfinityEdge'}, {'TeamNum': 21169, 'OPR': 10.774, 'Auto': -0.903, 'CCWM': -71.273, 'TeamName': 'CyberLions'}, {'TeamNum': 19092, 'OPR': 5.844, 'Auto': -0.293, 'CCWM': -114.709, 'TeamName': 'ICLASS '}, {'TeamNum': 20957, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Motion Bot'}, {'TeamNum': 20880, 'OPR': 0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'RoboGraphed'}, {'TeamNum': 19088, 'OPR': -3.505, 'Auto': -0.333, 'CCWM': -37.504, 'TeamName': 'BROBOTS'}, {'TeamNum': 20972, 'OPR': -11.184, 'Auto': -3.201, 'CCWM': -82.477, 'TeamName': 'VOLTA CIRCUITS'}]
i 1033

{'21380', '18457', '21508', '13276', '19024', '10789', '5921', '13273', '15091', '15046', '21525', '15303', '22124', '21507', '21788', '9881', '5325', '22471', '5285', '16179'}
[{'TeamNum': 21380, 'OPR': 136.615, 'Auto': 31.401, 'CCWM': 98.299, 'TeamName': 'Beyond Robotics'}, {'TeamNum': 18457, 'OPR': 116.121, 'Auto': 23.518, 'CCWM': 75.172, 'TeamName': 'GatorBytes'}, {'TeamNum': 21788, 'OPR': 84.131, 'Auto': 11.557, 'CCWM': 68.398, 'TeamName': 'Beta Rocks'}, {'TeamNum': 9881, 'OPR': 84.102, 'Auto': 19.316, 'CCWM': 25.725, 'TeamName': 'Golden Gears'}, {'TeamNum': 15091, 'OPR': 81.778, 'Auto': 26.928, 'CCWM': -11.015, 'TeamName': 'aztec.exe'}, {'TeamNum': 15303, 'OPR': 77.252, 'Auto': 22.158, 'CCWM': 54.018, 'TeamName': 'Space Rocks'}, {'TeamNum': 22471, 'OPR': 77.01, 'Auto': 15.547, 'CCWM': 15.709, 'TeamName': 'techATTACK'}, {'TeamNum': 5921, 'OPR': 62.379, 'Auto': 5.059, 'CCWM': -22.071, 'TeamName': 'La Cañada Engineering Club'}, {'TeamNum': 5285, 'OPR': 58.896, 'Auto': 3.62, 'CCWM': 38.097, 'TeamName': 'Robo Knights'}, {'TeamNum': 21508, 'OPR': 48.328, 'Auto': 11.264, 'CCWM': -11.441, 'TeamName': 'CAMS NerdHerd F'}, {'TeamNum': 13273, 'OPR': 45.715, 'Auto': 17.347, 'CCWM': -67.447, 'TeamName': 'MilkenKnightsMS1'}, {'TeamNum': 10789, 'OPR': 43.885, 'Auto': 7.026, 'CCWM': -25.709, 'TeamName': 'Wolfpack'}, {'TeamNum': 21525, 'OPR': 42.068, 'Auto': -2.88, 'CCWM': -25.056, 'TeamName': 'Blockheads²'}, {'TeamNum': 19024, 'OPR': 41.65, 'Auto': 8.979, 'CCWM': 12.003, 'TeamName': 'PMA Warriors Robotics'}, {'TeamNum': 13276, 'OPR': 31.963, 'Auto': 15.394, 'CCWM': -73.802, 'TeamName': 'MilkenKnightsMS2'}, {'TeamNum': 21507, 'OPR': 28.881, 'Auto': 8.821, 'CCWM': -4.695, 'TeamName': 'CAMS NerdHerd E'}, {'TeamNum': 15046, 'OPR': 27.578, 'Auto': 7.101, 'CCWM': -1.731, 'TeamName': 'Incognito Robotics'}, {'TeamNum': 16179, 'OPR': 24.455, 'Auto': 12.052, 'CCWM': -40.111, 'TeamName': 'CookieTech'}, {'TeamNum': 22124, 'OPR': 4.437, 'Auto': -7.013, 'CCWM': -63.964, 'TeamName': 'Shortage'}, {'TeamNum': 5325, 'OPR': 4.356, 'Auto': 8.006, 'CCWM': -40.38, 'TeamName': 'The Muses'}]
USCALAMOQ2
[{'TeamNum': 21380, 'OPR': 136.615, 'Auto': 31.401, 'CCWM': 98.299, 'TeamName': 'Beyond Robotics'}, {'TeamNum': 18457, 'OPR': 116.121, 'Auto': 23.518, 'CCWM': 75.172, 'TeamName': 'GatorBytes'}, {'TeamNum': 21788, 'OPR': 84.131, 'Auto': 11.557, 'CCWM': 68.398, 'TeamName': 'Beta Rocks'}, {'TeamNum': 9881, 'OPR': 84.102, 'Auto': 19.316, 'CCWM': 25.725, 'TeamName': 'Golden Gears'}, {'TeamNum': 15091, 'OPR': 81.778, 'Auto': 26.928, 'CCWM': -11.015, 'TeamName': 'aztec.exe'}, {'TeamNum': 15303, 'OPR': 77.252, 'Auto': 22.158, 'CCWM': 54.018, 'TeamName': 'Space Rocks'}, {'TeamNum': 22471, 'OPR': 77.01, 'Auto': 15.547, 'CCWM': 15.709, 'TeamName': 'techATTACK'}, {'TeamNum': 5921, 'OPR': 62.379, 'Auto': 5.059, 'CCWM': -22.071, 'TeamName': 'La Cañada Engineering Club'}, {'TeamNum': 5285, 'OPR': 58.896, 'Auto': 3.62, 'CCWM': 38.097, 'TeamName': 'Robo Knights'}, {'TeamNum': 21508, 'OPR': 48.328, 'Auto': 11.264, 'CCWM': -11.441, 'TeamName': 'CAMS NerdHerd F'}, {'TeamNum': 13273, 'OPR': 45.715, 'Auto': 17.347, 'CCWM': -67.447, 'TeamName': 'MilkenKnightsMS1'}, {'TeamNum': 10789, 'OPR': 43.885, 'Auto': 7.026, 'CCWM': -25.709, 'TeamName': 'Wolfpack'}, {'TeamNum': 21525, 'OPR': 42.068, 'Auto': -2.88, 'CCWM': -25.056, 'TeamName': 'Blockheads²'}, {'TeamNum': 19024, 'OPR': 41.65, 'Auto': 8.979, 'CCWM': 12.003, 'TeamName': 'PMA Warriors Robotics'}, {'TeamNum': 13276, 'OPR': 31.963, 'Auto': 15.394, 'CCWM': -73.802, 'TeamName': 'MilkenKnightsMS2'}, {'TeamNum': 21507, 'OPR': 28.881, 'Auto': 8.821, 'CCWM': -4.695, 'TeamName': 'CAMS NerdHerd E'}, {'TeamNum': 15046, 'OPR': 27.578, 'Auto': 7.101, 'CCWM': -1.731, 'TeamName': 'Incognito Robotics'}, {'TeamNum': 16179, 'OPR': 24.455, 'Auto': 12.052, 'CCWM': -40.111, 'TeamName': 'CookieTech'}, {'TeamNum': 22124, 'OPR': 4.437, 'Auto': -7.013, 'CCWM': -63.964, 'TeamName': 'Shortage'}, {'TeamNum': 5325, 'OPR': 4.356, 'Auto': 8.006, 'CCWM': -40.38, 'TeamName': 'The Muses'}]
i 1034
{'21808', '22616', '8624', '12675', '21325', '11825', '4625', '15157', '21798', '4947', '25', '4348', '5218', '4628', '21341', '17176', '9894', '5011', '5498', '9513', '20824', '22498', '19900', '7553', '14921', '4153', '8894'}
[{'TeamNum': 20824, 'OPR': 83.715, 'Auto': 19.937, 'CCWM': 28.015, 'TeamName': 'LeXT - Pineapple Something'}, {'TeamNum': 21798, 'OPR': 74.052, 'Auto': 27.785, 'CCWM': 21.643, 'TeamName': 'GrizzlyBear1'}, {'TeamNum': 4625, 'OPR': 73.941, 'Auto': 25.832, 'CCWM': 54.554, 'TeamName': 'Kings and Queens'}, {'TeamNum': 4153, 'OPR': 71.984, 'Auto': 20.32, 'CCWM': 43.604, 'TeamName': 'Neptune'}, {'TeamNum': 12675, 'OPR': 68.094, 'Auto': 20.221, 'CCWM': 14.87, 'TeamName': 'Hermit Social Club'}, {'TeamNum': 5218, 'OPR': 66.978, 'Auto': 19.481, 'CCWM': -30.326, 'TeamName': 'Javabots'}, {'TeamNum': 4947, 'OPR': 65.47, 'Auto': 7.412, 'CCWM': 41.653, 'TeamName': 'Cougarobotics Alpha'}, {'TeamNum': 19900, 'OPR': 64.916, 'Auto': 26.992, 'CCWM': 10.914, 'TeamName': 'Qualia Robotics'}, {'TeamNum': 21325, 'OPR': 61.927, 'Auto': 9.98, 'CCWM': 39.777, 'TeamName': 'JuniorKnights'}, {'TeamNum': 22616, 'OPR': 58.006, 'Auto': 9.944, 'CCWM': 6.226, 'TeamName': 'Name Under NDA(NUNDA)'}, {'TeamNum': 4348, 'OPR': 53.505, 'Auto': 19.087, 'CCWM': -3.817, 'TeamName': 'RoboKnights'}, {'TeamNum': 21341, 'OPR': 51.242, 'Auto': -3.85, 'CCWM': 29.476, 'TeamName': 'Team Fenix'}, {'TeamNum': 8894, 'OPR': 50.554, 'Auto': 23.607, 'CCWM': -16.561, 'TeamName': 'Clueless Robotics (Team ADHD^2)'}, {'TeamNum': 7553, 'OPR': 50.514, 'Auto': 8.053, 'CCWM': 3.269, 'TeamName': 'Team Loki'}, {'TeamNum': 14921, 'OPR': 41.716, 'Auto': 3.368, 'CCWM': -1.076, 'TeamName': 'AlphaOmega'}, {'TeamNum': 25, 'OPR': 39.955, 'Auto': 14.483, 'CCWM': -29.818, 'TeamName': "Rock N' Roll Robots"}, {'TeamNum': 5011, 'OPR': 36.679, 'Auto': 4.046, 'CCWM': -46.605, 'TeamName': 'Bot Squad 5011'}, {'TeamNum': 17176, 'OPR': 35.725, 'Auto': 1.487, 'CCWM': 11.966, 'TeamName': 'Fax Machine'}, {'TeamNum': 21808, 'OPR': 28.451, 'Auto': 4.343, 'CCWM': -9.143, 'TeamName': 'MounTECH Lions'}, {'TeamNum': 9894, 'OPR': 27.141, 'Auto': -6.651, 'CCWM': -11.872, 'TeamName': 'RoboLions'}, {'TeamNum': 15157, 'OPR': 23.698, 'Auto': 1.549, 'CCWM': -16.77, 'TeamName': 'IFC'}, {'TeamNum': 11825, 'OPR': 17.745, 'Auto': -1.132, 'CCWM': -32.818, 'TeamName': 'Eclipse'}, {'TeamNum': 5498, 'OPR': 14.475, 'Auto': 0.377, 'CCWM': 25.663, 'TeamName': 'Cougarobotics Omega'}, {'TeamNum': 9513, 'OPR': 8.832, 'Auto': 0.894, 'CCWM': -72.816, 'TeamName': 'System Overload'}, {'TeamNum': 8624, 'OPR': 2.948, 'Auto': -0.752, 'CCWM': 13.788, 'TeamName': 'Spectrum'}, {'TeamNum': 4628, 'OPR': -10.156, 'Auto': 6.912, 'CCWM': -36.053, 'TeamName': 'Suit Bots'}, {'TeamNum': 22498, 'OPR': -13.926, 'Auto': -3.369, 'CCWM': -40.718, 'TeamName': 'Robo Lions'}]
USCALAMOQ1
[{'TeamNum': 20824, 'OPR': 83.715, 'Auto': 19.937, 'CCWM': 28.015, 'TeamName': 'LeXT - Pineapple Something'}, {'TeamNum': 21798, 'OPR': 74.052, 'Auto': 27.785, 'CCWM': 21.643, 'TeamName': 'GrizzlyBear1'}, {'TeamNum': 4625, 'OPR': 73.941, 'Auto': 25.832, 'CCWM': 54.554, 'TeamName': 'Kings and Queens'}, {'TeamNum': 4153, 'OPR': 71.984, 'Auto': 20.32, 'CCWM': 43.604, 'TeamName': 'Neptune'}, {'TeamNum': 12675, 'OPR': 68.094, 'Auto': 20.221, 'CCWM': 14.87, 'TeamName': 'Hermit Social Club'}, {'TeamNum': 5218, 'OPR': 66.978, 'Auto': 19.481, 'CCWM': -30.326, 'TeamName': 'Javabots'}, {'TeamNum': 4947, 'OPR': 65.47, 'Auto': 7.412, 'CCWM': 41.653, 'TeamName': 'Cougarobotics Alpha'}, {'TeamNum': 19900, 'OPR': 64.916, 'Auto': 26.992, 'CCWM': 10.914, 'TeamName': 'Qualia Robotics'}, {'TeamNum': 21325, 'OPR': 61.927, 'Auto': 9.98, 'CCWM': 39.777, 'TeamName': 'JuniorKnights'}, {'TeamNum': 22616, 'OPR': 58.006, 'Auto': 9.944, 'CCWM': 6.226, 'TeamName': 'Name Under NDA(NUNDA)'}, {'TeamNum': 4348, 'OPR': 53.505, 'Auto': 19.087, 'CCWM': -3.817, 'TeamName': 'RoboKnights'}, {'TeamNum': 21341, 'OPR': 51.242, 'Auto': -3.85, 'CCWM': 29.476, 'TeamName': 'Team Fenix'}, {'TeamNum': 8894, 'OPR': 50.554, 'Auto': 23.607, 'CCWM': -16.561, 'TeamName': 'Clueless Robotics (Team ADHD^2)'}, {'TeamNum': 7553, 'OPR': 50.514, 'Auto': 8.053, 'CCWM': 3.269, 'TeamName': 'Team Loki'}, {'TeamNum': 14921, 'OPR': 41.716, 'Auto': 3.368, 'CCWM': -1.076, 'TeamName': 'AlphaOmega'}, {'TeamNum': 25, 'OPR': 39.955, 'Auto': 14.483, 'CCWM': -29.818, 'TeamName': "Rock N' Roll Robots"}, {'TeamNum': 5011, 'OPR': 36.679, 'Auto': 4.046, 'CCWM': -46.605, 'TeamName': 'Bot Squad 5011'}, {'TeamNum': 17176, 'OPR': 35.725, 'Auto': 1.487, 'CCWM': 11.966, 'TeamName': 'Fax Machine'}, {'TeamNum': 21808, 'OPR': 28.451, 'Auto': 4.343, 'CCWM': -9.143, 'TeamName': 'MounTECH Lions'}, {'TeamNum': 9894, 'OPR': 27.141, 'Auto': -6.651, 'CCWM': -11.872, 'TeamName': 'RoboLions'}, {'TeamNum': 15157, 'OPR': 23.698, 'Auto': 1.549, 'CCWM': -16.77, 'TeamName': 'IFC'}, {'TeamNum': 11825, 'OPR': 17.745, 'Auto': -1.132, 'CCWM': -32.818, 'TeamName': 'Eclipse'}, {'TeamNum': 5498, 'OPR': 14.475, 'Auto': 0.377, 'CCWM': 25.663, 'TeamName': 'Cougarobotics Omega'}, {'TeamNum': 9513, 'OPR': 8.832, 'Auto': 0.894, 'CCWM': -72.816, 'TeamName': 'System Overload'}, {'TeamNum': 8624, 'OPR': 2.948, 'Auto': -0.752, 'CCWM': 13.788, 'TeamName': 'Spectrum'}, {'TeamNum': 4628, 'OPR': -10.156, 'Auto': 6.912, 'CCWM': -36.053, 'TeamName': 'Suit Bots'}, {'TeamNum': 22498, 'OPR': -13.926, 'Auto': -3.369, 'CCWM': -40.718, 'TeamName': 'Robo Lions'}]

i 1035
{'5196', '7172', '11308', '5899', '17302', '16629', '22250', '13835', '19746', '21430', '14659', '20771', '17969', '11260', '18099', '20077', '21171', '15403', '21819', '8641', '17190', '19564', '15755', '21229', '10448', '19970', '13022', '19541', '17153', '17483', '13879', '6382'}
[{'TeamNum': 21229, 'OPR': 154.249, 'Auto': 46.629, 'CCWM': 95.907, 'TeamName': 'Quality Control'}, {'TeamNum': 19746, 'OPR': 134.641, 'Auto': 24.79, 'CCWM': 60.228, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 11260, 'OPR': 133.711, 'Auto': 38.767, 'CCWM': 84.553, 'TeamName': 'Up-A-Creek Robotics '}, {'TeamNum': 17969, 'OPR': 119.334, 'Auto': 38.484, 'CCWM': 77.345, 'TeamName': 'MECH'}, {'TeamNum': 20077, 'OPR': 114.743, 'Auto': 31.788, 'CCWM': 31.154, 'TeamName': 'The Indubitables'}, {'TeamNum': 7172, 'OPR': 108.877, 'Auto': 29.778, 'CCWM': 44.46, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 8641, 'OPR': 93.248, 'Auto': 24.306, 'CCWM': 40.179, 'TeamName': 'The Masters'}, {'TeamNum': 21171, 'OPR': 90.209, 'Auto': 28.107, 'CCWM': 2.264, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 13835, 'OPR': 84.508, 'Auto': 21.576, 'CCWM': 51.615, 'TeamName': 'Enigma'}, {'TeamNum': 15403, 'OPR': 82.95, 'Auto': 22.418, 'CCWM': 2.78, 'TeamName': 'Vision Robotics'}, {'TeamNum': 5196, 'OPR': 79.477, 'Auto': 9.998, 'CCWM': 14.125, 'TeamName': 'Robo Yetis'}, {'TeamNum': 19541, 'OPR': 78.912, 'Auto': 30.532, 'CCWM': 58.646, 'TeamName': 'Bearbotics Alpha'}, {'TeamNum': 11308, 'OPR': 73.802, 'Auto': 17.27, 'CCWM': -9.859, 'TeamName': 'YISE'}, {'TeamNum': 21430, 'OPR': 69.942, 'Auto': 18.603, 'CCWM': 28.026, 'TeamName': 'BroomBots'}, {'TeamNum': 5899, 'OPR': 65.883, 'Auto': 8.66, 'CCWM': -10.266, 'TeamName': 'L.A.S.E.R.'}, {'TeamNum': 17483, 'OPR': 63.565, 'Auto': 14.172, 'CCWM': 12.401, 'TeamName': 'Blackout'}, {'TeamNum': 13022, 'OPR': 62.341, 'Auto': 6.208, 'CCWM': -36.047, 'TeamName': 'Ridgeview Hoplites'}, {'TeamNum': 6382, 'OPR': 60.874, 'Auto': 8.846, 'CCWM': 12.667, 'TeamName': 'Wrench Monkeys'}, {'TeamNum': 20771, 'OPR': 58.195, 'Auto': 19.244, 'CCWM': -2.191, 'TeamName': 'Bearbotics Sigma'}, {'TeamNum': 17153, 'OPR': 57.991, 'Auto': 5.334, 'CCWM': -30.212, 'TeamName': 'Squid Squad'}, {'TeamNum': 14659, 'OPR': 53.296, 'Auto': 8.741, 'CCWM': -18.083, 'TeamName': 'Pleiades Robotics'}, {'TeamNum': 22250, 'OPR': 51.957, 'Auto': 6.61, 'CCWM': -29.664, 'TeamName': 'Knightbots'}, {'TeamNum': 21819, 'OPR': 42.633, 'Auto': 4.226, 'CCWM': -11.925, 'TeamName': 'Durango High School FTC2'}, {'TeamNum': 10448, 'OPR': 39.247, 'Auto': 10.023, 'CCWM': -36.698, 'TeamName': 'Mach 5'}, {'TeamNum': 19970, 'OPR': 39.052, 'Auto': 8.389, 'CCWM': -42.329, 'TeamName': 'Bearbotics Beta'}, {'TeamNum': 18099, 'OPR': 35.962, 'Auto': 13.262, 'CCWM': -51.714, 'TeamName': 'G-R Overdrive'}, {'TeamNum': 17302, 'OPR': 27.777, 'Auto': 1.594, 'CCWM': -23.731, 'TeamName': 'Max Resistance'}, {'TeamNum': 16629, 'OPR': 27.672, 'Auto': 7.694, 'CCWM': -47.255, 'TeamName': 'Box Canyon Bots'}, {'TeamNum': 19564, 'OPR': 14.852, 'Auto': -0.637, 'CCWM': -68.527, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 17190, 'OPR': 13.497, 'Auto': -5.194, 'CCWM': -104.081, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 13879, 'OPR': 9.603, 'Auto': 5.989, 'CCWM': -31.27, 'TeamName': 'EGMS Metal Minds'}, {'TeamNum': 15755, 'OPR': 3.667, 'Auto': -4.874, 'CCWM': -62.498, 'TeamName': 'Conductivity'}]
USCOCMP
[{'TeamNum': 21229, 'OPR': 154.249, 'Auto': 46.629, 'CCWM': 95.907, 'TeamName': 'Quality Control'}, {'TeamNum': 19746, 'OPR': 134.641, 'Auto': 24.79, 'CCWM': 60.228, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 11260, 'OPR': 133.711, 'Auto': 38.767, 'CCWM': 84.553, 'TeamName': 'Up-A-Creek Robotics '}, {'TeamNum': 17969, 'OPR': 119.334, 'Auto': 38.484, 'CCWM': 77.345, 'TeamName': 'MECH'}, {'TeamNum': 20077, 'OPR': 114.743, 'Auto': 31.788, 'CCWM': 31.154, 'TeamName': 'The Indubitables'}, {'TeamNum': 7172, 'OPR': 108.877, 'Auto': 29.778, 'CCWM': 44.46, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 8641, 'OPR': 93.248, 'Auto': 24.306, 'CCWM': 40.179, 'TeamName': 'The Masters'}, {'TeamNum': 21171, 'OPR': 90.209, 'Auto': 28.107, 'CCWM': 2.264, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 13835, 'OPR': 84.508, 'Auto': 21.576, 'CCWM': 51.615, 'TeamName': 'Enigma'}, {'TeamNum': 15403, 'OPR': 82.95, 'Auto': 22.418, 'CCWM': 2.78, 'TeamName': 'Vision Robotics'}, {'TeamNum': 5196, 'OPR': 79.477, 'Auto': 9.998, 'CCWM': 14.125, 'TeamName': 'Robo Yetis'}, {'TeamNum': 19541, 'OPR': 78.912, 'Auto': 30.532, 'CCWM': 58.646, 'TeamName': 'Bearbotics Alpha'}, {'TeamNum': 11308, 'OPR': 73.802, 'Auto': 17.27, 'CCWM': -9.859, 'TeamName': 'YISE'}, {'TeamNum': 21430, 'OPR': 69.942, 'Auto': 18.603, 'CCWM': 28.026, 'TeamName': 'BroomBots'}, {'TeamNum': 5899, 'OPR': 65.883, 'Auto': 8.66, 'CCWM': -10.266, 'TeamName': 'L.A.S.E.R.'}, {'TeamNum': 17483, 'OPR': 63.565, 'Auto': 14.172, 'CCWM': 12.401, 'TeamName': 'Blackout'}, {'TeamNum': 13022, 'OPR': 62.341, 'Auto': 6.208, 'CCWM': -36.047, 'TeamName': 'Ridgeview Hoplites'}, {'TeamNum': 6382, 'OPR': 60.874, 'Auto': 8.846, 'CCWM': 12.667, 'TeamName': 'Wrench Monkeys'}, {'TeamNum': 20771, 'OPR': 58.195, 'Auto': 19.244, 'CCWM': -2.191, 'TeamName': 'Bearbotics Sigma'}, {'TeamNum': 17153, 'OPR': 57.991, 'Auto': 5.334, 'CCWM': -30.212, 'TeamName': 'Squid Squad'}, {'TeamNum': 14659, 'OPR': 53.296, 'Auto': 8.741, 'CCWM': -18.083, 'TeamName': 'Pleiades Robotics'}, {'TeamNum': 22250, 'OPR': 51.957, 'Auto': 6.61, 'CCWM': -29.664, 'TeamName': 'Knightbots'}, {'TeamNum': 21819, 'OPR': 42.633, 'Auto': 4.226, 'CCWM': -11.925, 'TeamName': 'Durango High School FTC2'}, {'TeamNum': 10448, 'OPR': 39.247, 'Auto': 10.023, 'CCWM': -36.698, 'TeamName': 'Mach 5'}, {'TeamNum': 19970, 'OPR': 39.052, 'Auto': 8.389, 'CCWM': -42.329, 'TeamName': 'Bearbotics Beta'}, {'TeamNum': 18099, 'OPR': 35.962, 'Auto': 13.262, 'CCWM': -51.714, 'TeamName': 'G-R Overdrive'}, {'TeamNum': 17302, 'OPR': 27.777, 'Auto': 1.594, 'CCWM': -23.731, 'TeamName': 'Max Resistance'}, {'TeamNum': 16629, 'OPR': 27.672, 'Auto': 7.694, 'CCWM': -47.255, 'TeamName': 'Box Canyon Bots'}, {'TeamNum': 19564, 'OPR': 14.852, 'Auto': -0.637, 'CCWM': -68.527, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 17190, 'OPR': 13.497, 'Auto': -5.194, 'CCWM': -104.081, 'TeamName': 'MPHS Mechanical Unicorns'}, {'TeamNum': 13879, 'OPR': 9.603, 'Auto': 5.989, 'CCWM': -31.27, 'TeamName': 'EGMS Metal Minds'}, {'TeamNum': 15755, 'OPR': 3.667, 'Auto': -4.874, 'CCWM': -62.498, 'TeamName': 'Conductivity'}]
i 1036
{'10820', '22984', '130', '5518', '18978', '12923', '10132', '12377', '17703', '8699', '20188', '18221', '40', '21503', '18366', '18813', '16008', '8942', '18843', '5017', '20189', '22096', '19462', '7034', '13965'}
[{'TeamNum': 7034, 'OPR': 118.425, 'Auto': 28.164, 'CCWM': 52.302, 'TeamName': 'Singularity Technology 7034'}, {'TeamNum': 18813, 'OPR': 115.163, 'Auto': 23.954, 'CCWM': 52.173, 'TeamName': 'FullMetal Phoenixes'}, {'TeamNum': 8942, 'OPR': 86.209, 'Auto': 17.844, 'CCWM': 20.344, 'TeamName': 'Team Max'}, {'TeamNum': 18366, 'OPR': 84.722, 'Auto': 24.044, 'CCWM': 51.725, 'TeamName': 'Robolution'}, {'TeamNum': 22984, 'OPR': 83.362, 'Auto': 23.288, 'CCWM': 54.575, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 20188, 'OPR': 83.022, 'Auto': 19.412, 'CCWM': -35.531, 'TeamName': 'Hotchkiss EFX Gearcats A'}, {'TeamNum': 21503, 'OPR': 81.494, 'Auto': 29.988, 'CCWM': 32.314, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 19462, 'OPR': 81.396, 'Auto': 6.531, 'CCWM': 36.479, 'TeamName': 'Team Beta'}, {'TeamNum': 13965, 'OPR': 76.384, 'Auto': 17.183, 'CCWM': 3.509, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 18843, 'OPR': 74.963, 'Auto': 21.461, 'CCWM': 31.405, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 8699, 'OPR': 71.858, 'Auto': 11.009, 'CCWM': 13.732, 'TeamName': 'The League of Extraordinary Roboticist '}, {'TeamNum': 16008, 'OPR': 71.73, 'Auto': 24.393, 'CCWM': -34.694, 'TeamName': 'Armored Artemises'}, {'TeamNum': 20189, 'OPR': 69.595, 'Auto': 16.383, 'CCWM': -6.01, 'TeamName': 'Hotchkiss EFX Gearcats B'}, {'TeamNum': 10820, 'OPR': 69.387, 'Auto': 29.518, 'CCWM': -5.3, 'TeamName': 'Cyber Dragons'}, {'TeamNum': 18221, 'OPR': 63.507, 'Auto': 9.786, 'CCWM': 22.805, 'TeamName': 'Meta^Infinity'}, {'TeamNum': 17703, 'OPR': 57.512, 'Auto': 15.403, 'CCWM': -31.303, 'TeamName': 'FullMetal Peregrines'}, {'TeamNum': 10132, 'OPR': 53.739, 'Auto': 22.348, 'CCWM': -0.3, 'TeamName': 'Rocket Beavers'}, {'TeamNum': 18978, 'OPR': 51.262, 'Auto': 17.813, 'CCWM': -48.091, 'TeamName': 'SemiPlatinum Penguins'}, {'TeamNum': 12377, 'OPR': 49.929, 'Auto': 25.148, 'CCWM': -6.707, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 130, 'OPR': 48.616, 'Auto': 17.955, 'CCWM': -26.468, 'TeamName': 'Blazing Spirits'}, {'TeamNum': 5017, 'OPR': 47.452, 'Auto': 19.568, 'CCWM': -31.776, 'TeamName': 'RoboEpic'}, {'TeamNum': 12923, 'OPR': 38.19, 'Auto': 22.607, 'CCWM': -24.307, 'TeamName': 'Techno T-Rexes'}, {'TeamNum': 40, 'OPR': 34.075, 'Auto': 13.054, 'CCWM': -47.495, 'TeamName': 'HAX Robotics'}, {'TeamNum': 5518, 'OPR': 33.279, 'Auto': 27.685, 'CCWM': -40.254, 'TeamName': "Dutchman's Derivatives"}, {'TeamNum': 22096, 'OPR': 27.563, 'Auto': 19.529, 'CCWM': -28.589, 'TeamName': 'RoboTastic'}]
USCTCMP
[{'TeamNum': 7034, 'OPR': 118.425, 'Auto': 28.164, 'CCWM': 52.302, 'TeamName': 'Singularity Technology 7034'}, {'TeamNum': 18813, 'OPR': 115.163, 'Auto': 23.954, 'CCWM': 52.173, 'TeamName': 'FullMetal Phoenixes'}, {'TeamNum': 8942, 'OPR': 86.209, 'Auto': 17.844, 'CCWM': 20.344, 'TeamName': 'Team Max'}, {'TeamNum': 18366, 'OPR': 84.722, 'Auto': 24.044, 'CCWM': 51.725, 'TeamName': 'Robolution'}, {'TeamNum': 22984, 'OPR': 83.362, 'Auto': 23.288, 'CCWM': 54.575, 'TeamName': 'Hotchkiss EFX Gearcats C'}, {'TeamNum': 20188, 'OPR': 83.022, 'Auto': 19.412, 'CCWM': -35.531, 'TeamName': 'Hotchkiss EFX Gearcats A'}, {'TeamNum': 21503, 'OPR': 81.494, 'Auto': 29.988, 'CCWM': 32.314, 'TeamName': 'Trumbull High School Ace Robotics 72'}, {'TeamNum': 19462, 'OPR': 81.396, 'Auto': 6.531, 'CCWM': 36.479, 'TeamName': 'Team Beta'}, {'TeamNum': 13965, 'OPR': 76.384, 'Auto': 17.183, 'CCWM': 3.509, 'TeamName': 'Hopkins Robotics Maroon'}, {'TeamNum': 18843, 'OPR': 74.963, 'Auto': 21.461, 'CCWM': 31.405, 'TeamName': 'FullMetal Merlins'}, {'TeamNum': 8699, 'OPR': 71.858, 'Auto': 11.009, 'CCWM': 13.732, 'TeamName': 'The League of Extraordinary Roboticist '}, {'TeamNum': 16008, 'OPR': 71.73, 'Auto': 24.393, 'CCWM': -34.694, 'TeamName': 'Armored Artemises'}, {'TeamNum': 20189, 'OPR': 69.595, 'Auto': 16.383, 'CCWM': -6.01, 'TeamName': 'Hotchkiss EFX Gearcats B'}, {'TeamNum': 10820, 'OPR': 69.387, 'Auto': 29.518, 'CCWM': -5.3, 'TeamName': 'Cyber Dragons'}, {'TeamNum': 18221, 'OPR': 63.507, 'Auto': 9.786, 'CCWM': 22.805, 'TeamName': 'Meta^Infinity'}, {'TeamNum': 17703, 'OPR': 57.512, 'Auto': 15.403, 'CCWM': -31.303, 'TeamName': 'FullMetal Peregrines'}, {'TeamNum': 10132, 'OPR': 53.739, 'Auto': 22.348, 'CCWM': -0.3, 'TeamName': 'Rocket Beavers'}, {'TeamNum': 18978, 'OPR': 51.262, 'Auto': 17.813, 'CCWM': -48.091, 'TeamName': 'SemiPlatinum Penguins'}, {'TeamNum': 12377, 'OPR': 49.929, 'Auto': 25.148, 'CCWM': -6.707, 'TeamName': 'Hopkins Robotics Gray'}, {'TeamNum': 130, 'OPR': 48.616, 'Auto': 17.955, 'CCWM': -26.468, 'TeamName': 'Blazing Spirits'}, {'TeamNum': 5017, 'OPR': 47.452, 'Auto': 19.568, 'CCWM': -31.776, 'TeamName': 'RoboEpic'}, {'TeamNum': 12923, 'OPR': 38.19, 'Auto': 22.607, 'CCWM': -24.307, 'TeamName': 'Techno T-Rexes'}, {'TeamNum': 40, 'OPR': 34.075, 'Auto': 13.054, 'CCWM': -47.495, 'TeamName': 'HAX Robotics'}, {'TeamNum': 5518, 'OPR': 33.279, 'Auto': 27.685, 'CCWM': -40.254, 'TeamName': "Dutchman's Derivatives"}, {'TeamNum': 22096, 'OPR': 27.563, 'Auto': 19.529, 'CCWM': -28.589, 'TeamName': 'RoboTastic'}]

i 1037
{'6458', '8813', '6189', '8672', '6252', '5445', '6420', '4324', '9925', '13532', '8696', '5094', '4175', '5143', '13206', '20307', '7196', '11142', '6661', '7110', '12863', '7247', '7400', '6603'}
[{'TeamNum': 7247, 'OPR': 106.551, 'Auto': 33.165, 'CCWM': 65.684, 'TeamName': 'The H2O Loo Bots'}, {'TeamNum': 6252, 'OPR': 103.178, 'Auto': 22.336, 'CCWM': 75.225, 'TeamName': 'The Wacky Waving Inflatable Arm Flailing Tube Men and Women'}, {'TeamNum': 7196, 'OPR': 102.115, 'Auto': 20.367, 'CCWM': 42.79, 'TeamName': "Everything That's Radical"}, {'TeamNum': 4324, 'OPR': 101.981, 'Auto': 16.213, 'CCWM': 11.801, 'TeamName': 'Lost In Time'}, {'TeamNum': 9925, 'OPR': 99.984, 'Auto': 28.576, 'CCWM': 51.19, 'TeamName': 'Delta Robotics'}, {'TeamNum': 7110, 'OPR': 82.56, 'Auto': 22.566, 'CCWM': 26.904, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 8813, 'OPR': 79.828, 'Auto': 8.844, 'CCWM': 16.041, 'TeamName': 'The Winter Soldiers'}, {'TeamNum': 8672, 'OPR': 77.747, 'Auto': 4.461, 'CCWM': 47.426, 'TeamName': 'UBett'}, {'TeamNum': 5094, 'OPR': 77.68, 'Auto': 16.322, 'CCWM': 29.388, 'TeamName': 'Still Under Development'}, {'TeamNum': 6458, 'OPR': 71.858, 'Auto': 20.639, 'CCWM': -15.278, 'TeamName': 'Burgbots'}, {'TeamNum': 7400, 'OPR': 71.28, 'Auto': 28.037, 'CCWM': 1.624, 'TeamName': 'Shmizmin'}, {'TeamNum': 5143, 'OPR': 68.091, 'Auto': 19.834, 'CCWM': -1.11, 'TeamName': 'Xcentrics'}, {'TeamNum': 6189, 'OPR': 57.278, 'Auto': 13.331, 'CCWM': -21.169, 'TeamName': 'High Voltage'}, {'TeamNum': 8696, 'OPR': 55.123, 'Auto': 21.156, 'CCWM': -19.354, 'TeamName': 'Trobotix'}, {'TeamNum': 13532, 'OPR': 49.524, 'Auto': 10.213, 'CCWM': -18.642, 'TeamName': 'EagleBots'}, {'TeamNum': 6420, 'OPR': 47.448, 'Auto': 2.748, 'CCWM': -5.571, 'TeamName': 'SabreHOOF Tigers'}, {'TeamNum': 6661, 'OPR': 44.484, 'Auto': 12.43, 'CCWM': -14.181, 'TeamName': 'Starmont Sundevils'}, {'TeamNum': 12863, 'OPR': 38.048, 'Auto': 13.423, 'CCWM': -25.169, 'TeamName': 'Flourish & Bots'}, {'TeamNum': 6603, 'OPR': 31.21, 'Auto': 10.153, 'CCWM': -41.416, 'TeamName': 'Guild of Gears'}, {'TeamNum': 13206, 'OPR': 29.4, 'Auto': 11.287, 'CCWM': -49.796, 'TeamName': 'Wave Droids'}, {'TeamNum': 11142, 'OPR': 28.962, 'Auto': 21.195, 'CCWM': -19.893, 'TeamName': 'Robo Minions'}, {'TeamNum': 4175, 'OPR': 28.78, 'Auto': 4.418, 'CCWM': -41.518, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 5445, 'OPR': 28.326, 'Auto': 11.092, 'CCWM': -66.971, 'TeamName': 'Scramblers'}, {'TeamNum': 20307, 'OPR': 23.398, 'Auto': 4.192, 'CCWM': -28.006, 'TeamName': 'Clipper Krakens'}]
USIABESQ
[{'TeamNum': 7247, 'OPR': 106.551, 'Auto': 33.165, 'CCWM': 65.684, 'TeamName': 'The H2O Loo Bots'}, {'TeamNum': 6252, 'OPR': 103.178, 'Auto': 22.336, 'CCWM': 75.225, 'TeamName': 'The Wacky Waving Inflatable Arm Flailing Tube Men and Women'}, {'TeamNum': 7196, 'OPR': 102.115, 'Auto': 20.367, 'CCWM': 42.79, 'TeamName': "Everything That's Radical"}, {'TeamNum': 4324, 'OPR': 101.981, 'Auto': 16.213, 'CCWM': 11.801, 'TeamName': 'Lost In Time'}, {'TeamNum': 9925, 'OPR': 99.984, 'Auto': 28.576, 'CCWM': 51.19, 'TeamName': 'Delta Robotics'}, {'TeamNum': 7110, 'OPR': 82.56, 'Auto': 22.566, 'CCWM': 26.904, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 8813, 'OPR': 79.828, 'Auto': 8.844, 'CCWM': 16.041, 'TeamName': 'The Winter Soldiers'}, {'TeamNum': 8672, 'OPR': 77.747, 'Auto': 4.461, 'CCWM': 47.426, 'TeamName': 'UBett'}, {'TeamNum': 5094, 'OPR': 77.68, 'Auto': 16.322, 'CCWM': 29.388, 'TeamName': 'Still Under Development'}, {'TeamNum': 6458, 'OPR': 71.858, 'Auto': 20.639, 'CCWM': -15.278, 'TeamName': 'Burgbots'}, {'TeamNum': 7400, 'OPR': 71.28, 'Auto': 28.037, 'CCWM': 1.624, 'TeamName': 'Shmizmin'}, {'TeamNum': 5143, 'OPR': 68.091, 'Auto': 19.834, 'CCWM': -1.11, 'TeamName': 'Xcentrics'}, {'TeamNum': 6189, 'OPR': 57.278, 'Auto': 13.331, 'CCWM': -21.169, 'TeamName': 'High Voltage'}, {'TeamNum': 8696, 'OPR': 55.123, 'Auto': 21.156, 'CCWM': -19.354, 'TeamName': 'Trobotix'}, {'TeamNum': 13532, 'OPR': 49.524, 'Auto': 10.213, 'CCWM': -18.642, 'TeamName': 'EagleBots'}, {'TeamNum': 6420, 'OPR': 47.448, 'Auto': 2.748, 'CCWM': -5.571, 'TeamName': 'SabreHOOF Tigers'}, {'TeamNum': 6661, 'OPR': 44.484, 'Auto': 12.43, 'CCWM': -14.181, 'TeamName': 'Starmont Sundevils'}, {'TeamNum': 12863, 'OPR': 38.048, 'Auto': 13.423, 'CCWM': -25.169, 'TeamName': 'Flourish & Bots'}, {'TeamNum': 6603, 'OPR': 31.21, 'Auto': 10.153, 'CCWM': -41.416, 'TeamName': 'Guild of Gears'}, {'TeamNum': 13206, 'OPR': 29.4, 'Auto': 11.287, 'CCWM': -49.796, 'TeamName': 'Wave Droids'}, {'TeamNum': 11142, 'OPR': 28.962, 'Auto': 21.195, 'CCWM': -19.893, 'TeamName': 'Robo Minions'}, {'TeamNum': 4175, 'OPR': 28.78, 'Auto': 4.418, 'CCWM': -41.518, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 5445, 'OPR': 28.326, 'Auto': 11.092, 'CCWM': -66.971, 'TeamName': 'Scramblers'}, {'TeamNum': 20307, 'OPR': 23.398, 'Auto': 4.192, 'CCWM': -28.006, 'TeamName': 'Clipper Krakens'}]
i 1038
{'14374', '19137', '18624', '18280', '21373', '11200', '22491', '14664', '16302', '18658', '13017', '14901', '21590', '18393', '21602', '9661', '21821', '16553', '10703', '8647'}
[{'TeamNum': 10703, 'OPR': 60.419, 'Auto': 17.283, 'CCWM': 33.87, 'TeamName': 'Cyclones'}, {'TeamNum': 16553, 'OPR': 57.576, 'Auto': 17.522, 'CCWM': 30.07, 'TeamName': "Java Like it's Hot"}, {'TeamNum': 18393, 'OPR': 41.892, 'Auto': 4.421, 'CCWM': 37.925, 'TeamName': 'Captcha Crew '}, {'TeamNum': 14374, 'OPR': 40.674, 'Auto': 9.065, 'CCWM': 15.156, 'TeamName': 'Dark Matter'}, {'TeamNum': 16302, 'OPR': 36.951, 'Auto': 3.823, 'CCWM': 10.985, 'TeamName': 'VAL Eagle Robotics Tech Team'}, {'TeamNum': 14901, 'OPR': 26.263, 'Auto': 5.169, 'CCWM': 15.623, 'TeamName': 'Cubotics Callisto'}, {'TeamNum': 11200, 'OPR': 25.159, 'Auto': 3.047, 'CCWM': -14.972, 'TeamName': 'Phenomena'}, {'TeamNum': 21590, 'OPR': 23.581, 'Auto': 0.761, 'CCWM': -2.053, 'TeamName': 'Cajun Robotics'}, {'TeamNum': 13017, 'OPR': 21.725, 'Auto': 14.303, 'CCWM': -9.61, 'TeamName': 'Event Horizon'}, {'TeamNum': 22491, 'OPR': 21.177, 'Auto': 2.194, 'CCWM': -1.282, 'TeamName': 'Cubotics Orion'}, {'TeamNum': 9661, 'OPR': 20.781, 'Auto': 1.062, 'CCWM': -11.554, 'TeamName': 'Steel Sirens'}, {'TeamNum': 18280, 'OPR': 20.355, 'Auto': 3.05, 'CCWM': 3.688, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 14664, 'OPR': 19.17, 'Auto': 4.38, 'CCWM': -10.958, 'TeamName': 'Squire Squad'}, {'TeamNum': 18658, 'OPR': 17.099, 'Auto': 6.753, 'CCWM': -12.316, 'TeamName': 'Purple Rain'}, {'TeamNum': 8647, 'OPR': 13.705, 'Auto': 2.403, 'CCWM': -4.067, 'TeamName': 'Super Cell'}, {'TeamNum': 21373, 'OPR': 9.511, 'Auto': -7.137, 'CCWM': -17.957, 'TeamName': 'Knights Robotics 2'}, {'TeamNum': 21602, 'OPR': 9.355, 'Auto': -1.888, 'CCWM': -6.828, 'TeamName': 'Les Garoux mechanics 1 '}, {'TeamNum': 18624, 'OPR': 9.256, 'Auto': -1.769, 'CCWM': -26.968, 'TeamName': 'Designosaurs'}, {'TeamNum': 21821, 'OPR': 7.966, 'Auto': 4.484, 'CCWM': -9.858, 'TeamName': 'SciPort Sci-bots'}, {'TeamNum': 19137, 'OPR': 4.887, 'Auto': -3.092, 'CCWM': -18.896, 'TeamName': 'CyberGriffs'}]
USLAHAQ4
[{'TeamNum': 10703, 'OPR': 60.419, 'Auto': 17.283, 'CCWM': 33.87, 'TeamName': 'Cyclones'}, {'TeamNum': 16553, 'OPR': 57.576, 'Auto': 17.522, 'CCWM': 30.07, 'TeamName': "Java Like it's Hot"}, {'TeamNum': 18393, 'OPR': 41.892, 'Auto': 4.421, 'CCWM': 37.925, 'TeamName': 'Captcha Crew '}, {'TeamNum': 14374, 'OPR': 40.674, 'Auto': 9.065, 'CCWM': 15.156, 'TeamName': 'Dark Matter'}, {'TeamNum': 16302, 'OPR': 36.951, 'Auto': 3.823, 'CCWM': 10.985, 'TeamName': 'VAL Eagle Robotics Tech Team'}, {'TeamNum': 14901, 'OPR': 26.263, 'Auto': 5.169, 'CCWM': 15.623, 'TeamName': 'Cubotics Callisto'}, {'TeamNum': 11200, 'OPR': 25.159, 'Auto': 3.047, 'CCWM': -14.972, 'TeamName': 'Phenomena'}, {'TeamNum': 21590, 'OPR': 23.581, 'Auto': 0.761, 'CCWM': -2.053, 'TeamName': 'Cajun Robotics'}, {'TeamNum': 13017, 'OPR': 21.725, 'Auto': 14.303, 'CCWM': -9.61, 'TeamName': 'Event Horizon'}, {'TeamNum': 22491, 'OPR': 21.177, 'Auto': 2.194, 'CCWM': -1.282, 'TeamName': 'Cubotics Orion'}, {'TeamNum': 9661, 'OPR': 20.781, 'Auto': 1.062, 'CCWM': -11.554, 'TeamName': 'Steel Sirens'}, {'TeamNum': 18280, 'OPR': 20.355, 'Auto': 3.05, 'CCWM': 3.688, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 14664, 'OPR': 19.17, 'Auto': 4.38, 'CCWM': -10.958, 'TeamName': 'Squire Squad'}, {'TeamNum': 18658, 'OPR': 17.099, 'Auto': 6.753, 'CCWM': -12.316, 'TeamName': 'Purple Rain'}, {'TeamNum': 8647, 'OPR': 13.705, 'Auto': 2.403, 'CCWM': -4.067, 'TeamName': 'Super Cell'}, {'TeamNum': 21373, 'OPR': 9.511, 'Auto': -7.137, 'CCWM': -17.957, 'TeamName': 'Knights Robotics 2'}, {'TeamNum': 21602, 'OPR': 9.355, 'Auto': -1.888, 'CCWM': -6.828, 'TeamName': 'Les Garoux mechanics 1 '}, {'TeamNum': 18624, 'OPR': 9.256, 'Auto': -1.769, 'CCWM': -26.968, 'TeamName': 'Designosaurs'}, {'TeamNum': 21821, 'OPR': 7.966, 'Auto': 4.484, 'CCWM': -9.858, 'TeamName': 'SciPort Sci-bots'}, {'TeamNum': 19137, 'OPR': 4.887, 'Auto': -3.092, 'CCWM': -18.896, 'TeamName': 'CyberGriffs'}]

i 1039
{'5276', '19397', '16773', '10472', '22221', '19556', '21332', '14273', '8227', '21913', '7245', '19460', '20808', '21877', '133', '17195', '13620', '20409', '22070'}
[{'TeamNum': 21877, 'OPR': 118.506, 'Auto': 35.093, 'CCWM': 70.705, 'TeamName': 'Circuit Makers'}, {'TeamNum': 19460, 'OPR': 75.667, 'Auto': 19.412, 'CCWM': 53.966, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 14273, 'OPR': 71.64, 'Auto': 23.155, 'CCWM': -13.107, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 133, 'OPR': 71.149, 'Auto': 12.772, 'CCWM': 40.024, 'TeamName': 'Arrows'}, {'TeamNum': 21332, 'OPR': 66.266, 'Auto': 13.975, 'CCWM': 11.188, 'TeamName': 'Cardinal Coders'}, {'TeamNum': 20808, 'OPR': 64.333, 'Auto': 17.746, 'CCWM': 42.964, 'TeamName': 'Spartans'}, {'TeamNum': 8227, 'OPR': 56.468, 'Auto': 14.541, 'CCWM': 42.984, 'TeamName': 'Enginuity'}, {'TeamNum': 22070, 'OPR': 56.163, 'Auto': 11.406, 'CCWM': -6.622, 'TeamName': 'PARC Acadia'}, {'TeamNum': 19556, 'OPR': 52.635, 'Auto': 13.874, 'CCWM': -2.935, 'TeamName': 'Arrow'}, {'TeamNum': 13620, 'OPR': 43.787, 'Auto': 0.858, 'CCWM': 29.876, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 22221, 'OPR': 39.048, 'Auto': 0.431, 'CCWM': -12.292, 'TeamName': 'BishopStangRobotics'}, {'TeamNum': 19397, 'OPR': 29.648, 'Auto': 11.449, 'CCWM': 16.384, 'TeamName': 'Soli Deo Gloria'}, {'TeamNum': 17195, 'OPR': 27.997, 'Auto': -1.471, 'CCWM': -15.026, 'TeamName': 'Doofenschmirtz Inc'}, {'TeamNum': 20409, 'OPR': 27.283, 'Auto': 11.499, 'CCWM': -38.401, 'TeamName': 'The Winsor Wirecats'}, {'TeamNum': 5276, 'OPR': 23.968, 'Auto': 6.933, 'CCWM': -34.088, 'TeamName': 'Broken Code'}, {'TeamNum': 21913, 'OPR': 18.9, 'Auto': 6.089, 'CCWM': -41.758, 'TeamName': 'Hilltoppers34'}, {'TeamNum': 16773, 'OPR': 10.008, 'Auto': -0.435, 'CCWM': -42.535, 'TeamName': 'LCA Li-ions'}, {'TeamNum': 10472, 'OPR': 5.919, 'Auto': 5.048, 'CCWM': -53.013, 'TeamName': 'New Bedford Harpooners'}, {'TeamNum': 7245, 'OPR': -3.475, 'Auto': -2.036, 'CCWM': -40.865, 'TeamName': 'Big Green'}]
USMACAQ
[{'TeamNum': 21877, 'OPR': 118.506, 'Auto': 35.093, 'CCWM': 70.705, 'TeamName': 'Circuit Makers'}, {'TeamNum': 19460, 'OPR': 75.667, 'Auto': 19.412, 'CCWM': 53.966, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 14273, 'OPR': 71.64, 'Auto': 23.155, 'CCWM': -13.107, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 133, 'OPR': 71.149, 'Auto': 12.772, 'CCWM': 40.024, 'TeamName': 'Arrows'}, {'TeamNum': 21332, 'OPR': 66.266, 'Auto': 13.975, 'CCWM': 11.188, 'TeamName': 'Cardinal Coders'}, {'TeamNum': 20808, 'OPR': 64.333, 'Auto': 17.746, 'CCWM': 42.964, 'TeamName': 'Spartans'}, {'TeamNum': 8227, 'OPR': 56.468, 'Auto': 14.541, 'CCWM': 42.984, 'TeamName': 'Enginuity'}, {'TeamNum': 22070, 'OPR': 56.163, 'Auto': 11.406, 'CCWM': -6.622, 'TeamName': 'PARC Acadia'}, {'TeamNum': 19556, 'OPR': 52.635, 'Auto': 13.874, 'CCWM': -2.935, 'TeamName': 'Arrow'}, {'TeamNum': 13620, 'OPR': 43.787, 'Auto': 0.858, 'CCWM': 29.876, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 22221, 'OPR': 39.048, 'Auto': 0.431, 'CCWM': -12.292, 'TeamName': 'BishopStangRobotics'}, {'TeamNum': 19397, 'OPR': 29.648, 'Auto': 11.449, 'CCWM': 16.384, 'TeamName': 'Soli Deo Gloria'}, {'TeamNum': 17195, 'OPR': 27.997, 'Auto': -1.471, 'CCWM': -15.026, 'TeamName': 'Doofenschmirtz Inc'}, {'TeamNum': 20409, 'OPR': 27.283, 'Auto': 11.499, 'CCWM': -38.401, 'TeamName': 'The Winsor Wirecats'}, {'TeamNum': 5276, 'OPR': 23.968, 'Auto': 6.933, 'CCWM': -34.088, 'TeamName': 'Broken Code'}, {'TeamNum': 21913, 'OPR': 18.9, 'Auto': 6.089, 'CCWM': -41.758, 'TeamName': 'Hilltoppers34'}, {'TeamNum': 16773, 'OPR': 10.008, 'Auto': -0.435, 'CCWM': -42.535, 'TeamName': 'LCA Li-ions'}, {'TeamNum': 10472, 'OPR': 5.919, 'Auto': 5.048, 'CCWM': -53.013, 'TeamName': 'New Bedford Harpooners'}, {'TeamNum': 7245, 'OPR': -3.475, 'Auto': -2.036, 'CCWM': -40.865, 'TeamName': 'Big Green'}]
i 1040
{'3565', '8245', '18224', '19411', '18153', '1', '18489', '20340', '3615', '4466', '14875', '18438', '18524', '9725', '21782', '6032', '15943', '20613'}
[{'TeamNum': 18438, 'OPR': 174.111, 'Auto': 41.321, 'CCWM': 139.904, 'TeamName': 'Wolfpack Machina '}, {'TeamNum': 3565, 'OPR': 95.599, 'Auto': 24.234, 'CCWM': 32.162, 'TeamName': 'Ghost Robotics'}, {'TeamNum': 1, 'OPR': 72.107, 'Auto': 21.115, 'CCWM': 39.415, 'TeamName': 'Team Unlimited'}, {'TeamNum': 18524, 'OPR': 70.687, 'Auto': 20.895, 'CCWM': -17.491, 'TeamName': 'Excalibur'}, {'TeamNum': 18224, 'OPR': 70.131, 'Auto': 24.057, 'CCWM': 43.43, 'TeamName': 'Lupine'}, {'TeamNum': 19411, 'OPR': 57.462, 'Auto': 17.609, 'CCWM': -13.672, 'TeamName': 'Tech Tigers'}, {'TeamNum': 18153, 'OPR': 56.119, 'Auto': 6.569, 'CCWM': -9.408, 'TeamName': 'NDACouGears'}, {'TeamNum': 14875, 'OPR': 50.247, 'Auto': 9.991, 'CCWM': 7.87, 'TeamName': 'LightSpeed'}, {'TeamNum': 15943, 'OPR': 46.202, 'Auto': 4.556, 'CCWM': 7.213, 'TeamName': 'Eaglebrook Eagles'}, {'TeamNum': 8245, 'OPR': 36.521, 'Auto': -1.669, 'CCWM': -8.854, 'TeamName': 'CohBots'}, {'TeamNum': 20613, 'OPR': 35.296, 'Auto': 4.63, 'CCWM': -30.218, 'TeamName': 'Minnechaug Tech'}, {'TeamNum': 21782, 'OPR': 33.429, 'Auto': 1.181, 'CCWM': -28.52, 'TeamName': 'GRIFFINATORS'}, {'TeamNum': 6032, 'OPR': 32.683, 'Auto': 5.714, 'CCWM': -14.564, 'TeamName': 'Lightning Hawks'}, {'TeamNum': 20340, 'OPR': 20.559, 'Auto': 7.553, 'CCWM': -33.288, 'TeamName': 'Space Astros'}, {'TeamNum': 9725, 'OPR': 17.396, 'Auto': 2.8, 'CCWM': -44.141, 'TeamName': 'Clockwork Cardinals'}, {'TeamNum': 4466, 'OPR': 16.439, 'Auto': 6.729, 'CCWM': -39.294, 'TeamName': 'R.A.B.B.I.'}, {'TeamNum': 3615, 'OPR': 13.009, 'Auto': -1.584, 'CCWM': -28.124, 'TeamName': 'Arlington Automatons'}, {'TeamNum': 18489, 'OPR': 8.337, 'Auto': 0.966, 'CCWM': -2.418, 'TeamName': 'Bishop Connolly Cougars'}]
USMACAQ2
[{'TeamNum': 18438, 'OPR': 174.111, 'Auto': 41.321, 'CCWM': 139.904, 'TeamName': 'Wolfpack Machina '}, {'TeamNum': 3565, 'OPR': 95.599, 'Auto': 24.234, 'CCWM': 32.162, 'TeamName': 'Ghost Robotics'}, {'TeamNum': 1, 'OPR': 72.107, 'Auto': 21.115, 'CCWM': 39.415, 'TeamName': 'Team Unlimited'}, {'TeamNum': 18524, 'OPR': 70.687, 'Auto': 20.895, 'CCWM': -17.491, 'TeamName': 'Excalibur'}, {'TeamNum': 18224, 'OPR': 70.131, 'Auto': 24.057, 'CCWM': 43.43, 'TeamName': 'Lupine'}, {'TeamNum': 19411, 'OPR': 57.462, 'Auto': 17.609, 'CCWM': -13.672, 'TeamName': 'Tech Tigers'}, {'TeamNum': 18153, 'OPR': 56.119, 'Auto': 6.569, 'CCWM': -9.408, 'TeamName': 'NDACouGears'}, {'TeamNum': 14875, 'OPR': 50.247, 'Auto': 9.991, 'CCWM': 7.87, 'TeamName': 'LightSpeed'}, {'TeamNum': 15943, 'OPR': 46.202, 'Auto': 4.556, 'CCWM': 7.213, 'TeamName': 'Eaglebrook Eagles'}, {'TeamNum': 8245, 'OPR': 36.521, 'Auto': -1.669, 'CCWM': -8.854, 'TeamName': 'CohBots'}, {'TeamNum': 20613, 'OPR': 35.296, 'Auto': 4.63, 'CCWM': -30.218, 'TeamName': 'Minnechaug Tech'}, {'TeamNum': 21782, 'OPR': 33.429, 'Auto': 1.181, 'CCWM': -28.52, 'TeamName': 'GRIFFINATORS'}, {'TeamNum': 6032, 'OPR': 32.683, 'Auto': 5.714, 'CCWM': -14.564, 'TeamName': 'Lightning Hawks'}, {'TeamNum': 20340, 'OPR': 20.559, 'Auto': 7.553, 'CCWM': -33.288, 'TeamName': 'Space Astros'}, {'TeamNum': 9725, 'OPR': 17.396, 'Auto': 2.8, 'CCWM': -44.141, 'TeamName': 'Clockwork Cardinals'}, {'TeamNum': 4466, 'OPR': 16.439, 'Auto': 6.729, 'CCWM': -39.294, 'TeamName': 'R.A.B.B.I.'}, {'TeamNum': 3615, 'OPR': 13.009, 'Auto': -1.584, 'CCWM': -28.124, 'TeamName': 'Arlington Automatons'}, {'TeamNum': 18489, 'OPR': 8.337, 'Auto': 0.966, 'CCWM': -2.418, 'TeamName': 'Bishop Connolly Cougars'}]
i 1041
{'7139', '9579', '7961', '18292', '4194', '20378', '17214', '4193', '3665', '11965', '17560'}
[{'TeamNum': 7139, 'OPR': 83.448, 'Auto': 14.855, 'CCWM': 47.151, 'TeamName': 'KHS Robotics'}, {'TeamNum': 4193, 'OPR': 79.348, 'Auto': 14.182, 'CCWM': 28.035, 'TeamName': 'Those Guys'}, {'TeamNum': 18292, 'OPR': 72.687, 'Auto': 17.262, 'CCWM': 38.15, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 7961, 'OPR': 56.176, 'Auto': 16.051, 'CCWM': 19.687, 'TeamName': 'MotorDame'}, {'TeamNum': 9579, 'OPR': 51.892, 'Auto': 16.204, 'CCWM': 13.609, 'TeamName': 'Poplar Bluff Iron Mules'}, {'TeamNum': 20378, 'OPR': 51.157, 'Auto': 23.446, 'CCWM': -2.094, 'TeamName': 'Perryville Pirates'}, {'TeamNum': 11965, 'OPR': 36.0, 'Auto': 2.907, 'CCWM': -13.534, 'TeamName': 'Steampunks'}, {'TeamNum': 4194, 'OPR': 35.318, 'Auto': 5.781, 'CCWM': 3.751, 'TeamName': 'Silent Reign'}, {'TeamNum': 3665, 'OPR': 28.434, 'Auto': -3.886, 'CCWM': -24.429, 'TeamName': 'Leopold GearHeads'}, {'TeamNum': 17214, 'OPR': 4.684, 'Auto': -2.837, 'CCWM': -35.315, 'TeamName': 'Cape Central Tiger Bytes'}, {'TeamNum': 17560, 'OPR': -4.269, 'Auto': -0.448, 'CCWM': -71.565, 'TeamName': 'Central Junior High TigerTECH'}]
USMOKSSELT
[{'TeamNum': 7139, 'OPR': 83.448, 'Auto': 14.855, 'CCWM': 47.151, 'TeamName': 'KHS Robotics'}, {'TeamNum': 4193, 'OPR': 79.348, 'Auto': 14.182, 'CCWM': 28.035, 'TeamName': 'Those Guys'}, {'TeamNum': 18292, 'OPR': 72.687, 'Auto': 17.262, 'CCWM': 38.15, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 7961, 'OPR': 56.176, 'Auto': 16.051, 'CCWM': 19.687, 'TeamName': 'MotorDame'}, {'TeamNum': 9579, 'OPR': 51.892, 'Auto': 16.204, 'CCWM': 13.609, 'TeamName': 'Poplar Bluff Iron Mules'}, {'TeamNum': 20378, 'OPR': 51.157, 'Auto': 23.446, 'CCWM': -2.094, 'TeamName': 'Perryville Pirates'}, {'TeamNum': 11965, 'OPR': 36.0, 'Auto': 2.907, 'CCWM': -13.534, 'TeamName': 'Steampunks'}, {'TeamNum': 4194, 'OPR': 35.318, 'Auto': 5.781, 'CCWM': 3.751, 'TeamName': 'Silent Reign'}, {'TeamNum': 3665, 'OPR': 28.434, 'Auto': -3.886, 'CCWM': -24.429, 'TeamName': 'Leopold GearHeads'}, {'TeamNum': 17214, 'OPR': 4.684, 'Auto': -2.837, 'CCWM': -35.315, 'TeamName': 'Cape Central Tiger Bytes'}, {'TeamNum': 17560, 'OPR': -4.269, 'Auto': -0.448, 'CCWM': -71.565, 'TeamName': 'Central Junior High TigerTECH'}]

i 1042
{'19921', '7105', '11424', '16072', '16461', '21734', '11528', '8569', '731', '5309', '7444', '16582', '14200', '5064', '21836', '20428', '20434', '16447', '6183', '16328', '19410', '21502', '2901', '9581', '13735', '21351', '15707', '10195', '18994', '22377', '19768', '18175', '2827', '21910', '8300', '15830', '6078', '5795'}
[{'TeamNum': 7105, 'OPR': 156.21, 'Auto': 38.264, 'CCWM': 104.655, 'TeamName': 'SWIFT Intergalactic Space Llamas'}, {'TeamNum': 20434, 'OPR': 150.914, 'Auto': 26.659, 'CCWM': 95.172, 'TeamName': 'Binding Energy'}, {'TeamNum': 5064, 'OPR': 128.803, 'Auto': 28.356, 'CCWM': 108.379, 'TeamName': 'Aperture Science'}, {'TeamNum': 19768, 'OPR': 113.674, 'Auto': 37.053, 'CCWM': 5.512, 'TeamName': 'Overclocked'}, {'TeamNum': 11528, 'OPR': 108.208, 'Auto': 17.083, 'CCWM': 18.202, 'TeamName': 'Bots of Prey'}, {'TeamNum': 8300, 'OPR': 106.557, 'Auto': 22.107, 'CCWM': 36.202, 'TeamName': 'Pi Rho Eagles'}, {'TeamNum': 21351, 'OPR': 105.156, 'Auto': 17.353, 'CCWM': 34.368, 'TeamName': 'Cybotz'}, {'TeamNum': 8569, 'OPR': 99.316, 'Auto': 24.188, 'CCWM': 70.401, 'TeamName': 'RoboKnights'}, {'TeamNum': 5795, 'OPR': 97.444, 'Auto': 19.041, 'CCWM': 21.914, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 16461, 'OPR': 96.968, 'Auto': 19.541, 'CCWM': 19.76, 'TeamName': 'Infinite Turtles'}, {'TeamNum': 5309, 'OPR': 93.123, 'Auto': 28.544, 'CCWM': 12.375, 'TeamName': 'Plan B'}, {'TeamNum': 15707, 'OPR': 92.522, 'Auto': 14.409, 'CCWM': -12.935, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 18994, 'OPR': 89.137, 'Auto': 10.405, 'CCWM': 1.935, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 14200, 'OPR': 88.486, 'Auto': 19.303, 'CCWM': -9.971, 'TeamName': 'WASP - 12B'}, {'TeamNum': 19921, 'OPR': 86.53, 'Auto': 21.165, 'CCWM': 1.45, 'TeamName': 'Space Invaders'}, {'TeamNum': 21836, 'OPR': 84.928, 'Auto': 26.809, 'CCWM': 41.71, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 15830, 'OPR': 82.984, 'Auto': 17.015, 'CCWM': 10.595, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 19410, 'OPR': 81.265, 'Auto': 16.626, 'CCWM': 37.27, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 16328, 'OPR': 80.085, 'Auto': 19.465, 'CCWM': -52.759, 'TeamName': "Trial n' Error"}, {'TeamNum': 22377, 'OPR': 79.777, 'Auto': 17.424, 'CCWM': -27.715, 'TeamName': 'SigmaCorns'}, {'TeamNum': 9581, 'OPR': 76.665, 'Auto': 9.036, 'CCWM': 39.528, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 2827, 'OPR': 73.627, 'Auto': 3.406, 'CCWM': 35.749, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 6078, 'OPR': 72.529, 'Auto': 10.41, 'CCWM': -53.764, 'TeamName': 'Cut the Red Wire'}, {'TeamNum': 731, 'OPR': 65.418, 'Auto': 34.977, 'CCWM': 4.291, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 21502, 'OPR': 60.572, 'Auto': 25.889, 'CCWM': 1.38, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 16447, 'OPR': 59.599, 'Auto': 6.418, 'CCWM': 38.555, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 21910, 'OPR': 59.038, 'Auto': 17.35, 'CCWM': -7.775, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 20428, 'OPR': 46.332, 'Auto': -10.469, 'CCWM': -46.647, 'TeamName': 'South Iredell High School - FUSE'}, {'TeamNum': 7444, 'OPR': 38.16, 'Auto': 12.066, 'CCWM': -91.022, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 16582, 'OPR': 35.148, 'Auto': 19.777, 'CCWM': -58.505, 'TeamName': 'The Iron Dragons'}, {'TeamNum': 11424, 'OPR': 29.11, 'Auto': 6.827, 'CCWM': -30.79, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 21734, 'OPR': 26.483, 'Auto': -1.306, 'CCWM': -62.128, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 16072, 'OPR': 22.547, 'Auto': 3.832, 'CCWM': -69.107, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 10195, 'OPR': 21.968, 'Auto': 18.516, 'CCWM': -83.292, 'TeamName': 'Night Owls'}, {'TeamNum': 6183, 'OPR': 19.928, 'Auto': 18.874, 'CCWM': -43.905, 'TeamName': 'Thunderducks'}, {'TeamNum': 2901, 'OPR': 4.991, 'Auto': 12.388, 'CCWM': -89.087, 'TeamName': 'Purple Gears'}, {'TeamNum': 13735, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 18175, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Techies'}]
USNCCMP
[{'TeamNum': 7105, 'OPR': 156.21, 'Auto': 38.264, 'CCWM': 104.655, 'TeamName': 'SWIFT Intergalactic Space Llamas'}, {'TeamNum': 20434, 'OPR': 150.914, 'Auto': 26.659, 'CCWM': 95.172, 'TeamName': 'Binding Energy'}, {'TeamNum': 5064, 'OPR': 128.803, 'Auto': 28.356, 'CCWM': 108.379, 'TeamName': 'Aperture Science'}, {'TeamNum': 19768, 'OPR': 113.674, 'Auto': 37.053, 'CCWM': 5.512, 'TeamName': 'Overclocked'}, {'TeamNum': 11528, 'OPR': 108.208, 'Auto': 17.083, 'CCWM': 18.202, 'TeamName': 'Bots of Prey'}, {'TeamNum': 8300, 'OPR': 106.557, 'Auto': 22.107, 'CCWM': 36.202, 'TeamName': 'Pi Rho Eagles'}, {'TeamNum': 21351, 'OPR': 105.156, 'Auto': 17.353, 'CCWM': 34.368, 'TeamName': 'Cybotz'}, {'TeamNum': 8569, 'OPR': 99.316, 'Auto': 24.188, 'CCWM': 70.401, 'TeamName': 'RoboKnights'}, {'TeamNum': 5795, 'OPR': 97.444, 'Auto': 19.041, 'CCWM': 21.914, 'TeamName': 'Back  To The Drawing Board'}, {'TeamNum': 16461, 'OPR': 96.968, 'Auto': 19.541, 'CCWM': 19.76, 'TeamName': 'Infinite Turtles'}, {'TeamNum': 5309, 'OPR': 93.123, 'Auto': 28.544, 'CCWM': 12.375, 'TeamName': 'Plan B'}, {'TeamNum': 15707, 'OPR': 92.522, 'Auto': 14.409, 'CCWM': -12.935, 'TeamName': 'Bots by the Creek'}, {'TeamNum': 18994, 'OPR': 89.137, 'Auto': 10.405, 'CCWM': 1.935, 'TeamName': 'SWIFT Subterranean Sand Sharks'}, {'TeamNum': 14200, 'OPR': 88.486, 'Auto': 19.303, 'CCWM': -9.971, 'TeamName': 'WASP - 12B'}, {'TeamNum': 19921, 'OPR': 86.53, 'Auto': 21.165, 'CCWM': 1.45, 'TeamName': 'Space Invaders'}, {'TeamNum': 21836, 'OPR': 84.928, 'Auto': 26.809, 'CCWM': 41.71, 'TeamName': 'Marvels of IAR'}, {'TeamNum': 15830, 'OPR': 82.984, 'Auto': 17.015, 'CCWM': 10.595, 'TeamName': 'SWIFT Subaquatic Sea Kraken'}, {'TeamNum': 19410, 'OPR': 81.265, 'Auto': 16.626, 'CCWM': 37.27, 'TeamName': 'Entropic Fluctuations'}, {'TeamNum': 16328, 'OPR': 80.085, 'Auto': 19.465, 'CCWM': -52.759, 'TeamName': "Trial n' Error"}, {'TeamNum': 22377, 'OPR': 79.777, 'Auto': 17.424, 'CCWM': -27.715, 'TeamName': 'SigmaCorns'}, {'TeamNum': 9581, 'OPR': 76.665, 'Auto': 9.036, 'CCWM': 39.528, 'TeamName': 'Automated Admiralty'}, {'TeamNum': 2827, 'OPR': 73.627, 'Auto': 3.406, 'CCWM': 35.749, 'TeamName': 'Artificial Stupidity'}, {'TeamNum': 6078, 'OPR': 72.529, 'Auto': 10.41, 'CCWM': -53.764, 'TeamName': 'Cut the Red Wire'}, {'TeamNum': 731, 'OPR': 65.418, 'Auto': 34.977, 'CCWM': 4.291, 'TeamName': 'Wannabee Strange'}, {'TeamNum': 21502, 'OPR': 60.572, 'Auto': 25.889, 'CCWM': 1.38, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 16447, 'OPR': 59.599, 'Auto': 6.418, 'CCWM': 38.555, 'TeamName': 'Mechanical Maniacs'}, {'TeamNum': 21910, 'OPR': 59.038, 'Auto': 17.35, 'CCWM': -7.775, 'TeamName': 'Marvels of MAS-AIC'}, {'TeamNum': 20428, 'OPR': 46.332, 'Auto': -10.469, 'CCWM': -46.647, 'TeamName': 'South Iredell High School - FUSE'}, {'TeamNum': 7444, 'OPR': 38.16, 'Auto': 12.066, 'CCWM': -91.022, 'TeamName': 'Sisters of the Motherboard'}, {'TeamNum': 16582, 'OPR': 35.148, 'Auto': 19.777, 'CCWM': -58.505, 'TeamName': 'The Iron Dragons'}, {'TeamNum': 11424, 'OPR': 29.11, 'Auto': 6.827, 'CCWM': -30.79, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 21734, 'OPR': 26.483, 'Auto': -1.306, 'CCWM': -62.128, 'TeamName': 'Till the Wheels Fall Off'}, {'TeamNum': 16072, 'OPR': 22.547, 'Auto': 3.832, 'CCWM': -69.107, 'TeamName': 'Quantum Quacks'}, {'TeamNum': 10195, 'OPR': 21.968, 'Auto': 18.516, 'CCWM': -83.292, 'TeamName': 'Night Owls'}, {'TeamNum': 6183, 'OPR': 19.928, 'Auto': 18.874, 'CCWM': -43.905, 'TeamName': 'Thunderducks'}, {'TeamNum': 2901, 'OPR': 4.991, 'Auto': 12.388, 'CCWM': -89.087, 'TeamName': 'Purple Gears'}, {'TeamNum': 13735, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': '∏∆S (PiRates)'}, {'TeamNum': 18175, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Techies'}]
i 1043
{'8888', '19695', '20726', '14590', '17700', '11780', '12789', '19774', '22345', '17630', '22760', '11536', '15343', '15534', '12758', '7078', '10660', '13507', '17455', '19643', '22346', '17165', '17868', '16209', '18151', '16169', '11866', '20099'}
[{'TeamNum': 15343, 'OPR': 123.486, 'Auto': 29.089, 'CCWM': 67.892, 'TeamName': 'Blue VIII'}, {'TeamNum': 15534, 'OPR': 111.741, 'Auto': 17.568, 'CCWM': 91.446, 'TeamName': 'VERTEX'}, {'TeamNum': 19643, 'OPR': 102.776, 'Auto': 30.793, 'CCWM': 10.616, 'TeamName': 'Dragon Droids'}, {'TeamNum': 11866, 'OPR': 95.267, 'Auto': 27.444, 'CCWM': 62.078, 'TeamName': 'HBMS Royal Knights 11866'}, {'TeamNum': 13507, 'OPR': 87.011, 'Auto': 18.539, 'CCWM': 2.226, 'TeamName': 'Banana Brigade'}, {'TeamNum': 11536, 'OPR': 85.429, 'Auto': 15.925, 'CCWM': -0.217, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 11780, 'OPR': 80.114, 'Auto': 16.074, 'CCWM': 52.326, 'TeamName': 'B.L.U.E Box'}, {'TeamNum': 19774, 'OPR': 79.771, 'Auto': 22.449, 'CCWM': -1.227, 'TeamName': 'Torque'}, {'TeamNum': 17455, 'OPR': 69.525, 'Auto': 20.882, 'CCWM': 21.526, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 20726, 'OPR': 68.388, 'Auto': 21.479, 'CCWM': 53.598, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 10660, 'OPR': 67.383, 'Auto': 15.044, 'CCWM': 21.833, 'TeamName': 'HBMS Silver Knights 10660'}, {'TeamNum': 16209, 'OPR': 65.074, 'Auto': 18.309, 'CCWM': 18.509, 'TeamName': 'The Dread Pirate Robots'}, {'TeamNum': 12758, 'OPR': 64.825, 'Auto': 21.279, 'CCWM': 23.006, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 22760, 'OPR': 61.111, 'Auto': 13.398, 'CCWM': -3.759, 'TeamName': 'Navy Knights'}, {'TeamNum': 12789, 'OPR': 54.317, 'Auto': 20.537, 'CCWM': -23.383, 'TeamName': 'Hack-Gearz'}, {'TeamNum': 22346, 'OPR': 53.527, 'Auto': -0.987, 'CCWM': 48.993, 'TeamName': 'EDGE'}, {'TeamNum': 17630, 'OPR': 47.987, 'Auto': 18.649, 'CCWM': -35.439, 'TeamName': 'Hot Wings'}, {'TeamNum': 20099, 'OPR': 45.487, 'Auto': 3.618, 'CCWM': -57.789, 'TeamName': 'Team Inconceivable!'}, {'TeamNum': 17165, 'OPR': 45.127, 'Auto': 20.971, 'CCWM': -21.088, 'TeamName': 'WLC W4RR10R5'}, {'TeamNum': 8888, 'OPR': 44.629, 'Auto': 8.424, 'CCWM': -63.164, 'TeamName': 'Infinity Factor'}, {'TeamNum': 14590, 'OPR': 40.398, 'Auto': -3.335, 'CCWM': -49.429, 'TeamName': 'Prometheus'}, {'TeamNum': 19695, 'OPR': 38.056, 'Auto': 4.146, 'CCWM': -65.089, 'TeamName': 'Flying Screwdrivers'}, {'TeamNum': 22345, 'OPR': 37.138, 'Auto': -2.907, 'CCWM': -26.224, 'TeamName': 'SURFACE'}, {'TeamNum': 17868, 'OPR': 35.846, 'Auto': 18.098, 'CCWM': -14.892, 'TeamName': 'GRS Cooperative'}, {'TeamNum': 18151, 'OPR': 34.756, 'Auto': 16.023, 'CCWM': -8.31, 'TeamName': 'The Flux Capacitors'}, {'TeamNum': 7078, 'OPR': 33.482, 'Auto': 16.383, 'CCWM': -39.492, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 17700, 'OPR': 21.929, 'Auto': 2.066, 'CCWM': -46.086, 'TeamName': 'Mechanical Vikings'}, {'TeamNum': 16169, 'OPR': 14.419, 'Auto': 3.844, 'CCWM': -18.464, 'TeamName': 'Banana Box'}]
USNHCMP
[{'TeamNum': 15343, 'OPR': 123.486, 'Auto': 29.089, 'CCWM': 67.892, 'TeamName': 'Blue VIII'}, {'TeamNum': 15534, 'OPR': 111.741, 'Auto': 17.568, 'CCWM': 91.446, 'TeamName': 'VERTEX'}, {'TeamNum': 19643, 'OPR': 102.776, 'Auto': 30.793, 'CCWM': 10.616, 'TeamName': 'Dragon Droids'}, {'TeamNum': 11866, 'OPR': 95.267, 'Auto': 27.444, 'CCWM': 62.078, 'TeamName': 'HBMS Royal Knights 11866'}, {'TeamNum': 13507, 'OPR': 87.011, 'Auto': 18.539, 'CCWM': 2.226, 'TeamName': 'Banana Brigade'}, {'TeamNum': 11536, 'OPR': 85.429, 'Auto': 15.925, 'CCWM': -0.217, 'TeamName': 'Derryfield Fighting Cougars'}, {'TeamNum': 11780, 'OPR': 80.114, 'Auto': 16.074, 'CCWM': 52.326, 'TeamName': 'B.L.U.E Box'}, {'TeamNum': 19774, 'OPR': 79.771, 'Auto': 22.449, 'CCWM': -1.227, 'TeamName': 'Torque'}, {'TeamNum': 17455, 'OPR': 69.525, 'Auto': 20.882, 'CCWM': 21.526, 'TeamName': 'The ... Cephalo-Bots?'}, {'TeamNum': 20726, 'OPR': 68.388, 'Auto': 21.479, 'CCWM': 53.598, 'TeamName': 'Tobor the Viking '}, {'TeamNum': 10660, 'OPR': 67.383, 'Auto': 15.044, 'CCWM': 21.833, 'TeamName': 'HBMS Silver Knights 10660'}, {'TeamNum': 16209, 'OPR': 65.074, 'Auto': 18.309, 'CCWM': 18.509, 'TeamName': 'The Dread Pirate Robots'}, {'TeamNum': 12758, 'OPR': 64.825, 'Auto': 21.279, 'CCWM': 23.006, 'TeamName': 'Derryfield Binary Bots'}, {'TeamNum': 22760, 'OPR': 61.111, 'Auto': 13.398, 'CCWM': -3.759, 'TeamName': 'Navy Knights'}, {'TeamNum': 12789, 'OPR': 54.317, 'Auto': 20.537, 'CCWM': -23.383, 'TeamName': 'Hack-Gearz'}, {'TeamNum': 22346, 'OPR': 53.527, 'Auto': -0.987, 'CCWM': 48.993, 'TeamName': 'EDGE'}, {'TeamNum': 17630, 'OPR': 47.987, 'Auto': 18.649, 'CCWM': -35.439, 'TeamName': 'Hot Wings'}, {'TeamNum': 20099, 'OPR': 45.487, 'Auto': 3.618, 'CCWM': -57.789, 'TeamName': 'Team Inconceivable!'}, {'TeamNum': 17165, 'OPR': 45.127, 'Auto': 20.971, 'CCWM': -21.088, 'TeamName': 'WLC W4RR10R5'}, {'TeamNum': 8888, 'OPR': 44.629, 'Auto': 8.424, 'CCWM': -63.164, 'TeamName': 'Infinity Factor'}, {'TeamNum': 14590, 'OPR': 40.398, 'Auto': -3.335, 'CCWM': -49.429, 'TeamName': 'Prometheus'}, {'TeamNum': 19695, 'OPR': 38.056, 'Auto': 4.146, 'CCWM': -65.089, 'TeamName': 'Flying Screwdrivers'}, {'TeamNum': 22345, 'OPR': 37.138, 'Auto': -2.907, 'CCWM': -26.224, 'TeamName': 'SURFACE'}, {'TeamNum': 17868, 'OPR': 35.846, 'Auto': 18.098, 'CCWM': -14.892, 'TeamName': 'GRS Cooperative'}, {'TeamNum': 18151, 'OPR': 34.756, 'Auto': 16.023, 'CCWM': -8.31, 'TeamName': 'The Flux Capacitors'}, {'TeamNum': 7078, 'OPR': 33.482, 'Auto': 16.383, 'CCWM': -39.492, 'TeamName': 'Ov3r1y K0mp13x'}, {'TeamNum': 17700, 'OPR': 21.929, 'Auto': 2.066, 'CCWM': -46.086, 'TeamName': 'Mechanical Vikings'}, {'TeamNum': 16169, 'OPR': 14.419, 'Auto': 3.844, 'CCWM': -18.464, 'TeamName': 'Banana Box'}]

i 1044
{'15484', '8405', '10874', '20388', '19823', '22504', '16903', '5573', '12806', '12968', '11180', '7959', '19871', '4102'}
[{'TeamNum': 8405, 'OPR': 113.539, 'Auto': 23.676, 'CCWM': 89.274, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 11180, 'OPR': 112.778, 'Auto': 26.899, 'CCWM': 91.33, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 19823, 'OPR': 65.229, 'Auto': 18.195, 'CCWM': 57.086, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 12968, 'OPR': 47.894, 'Auto': 10.902, 'CCWM': 5.097, 'TeamName': 'Bard RoboRaptors'}, {'TeamNum': 7959, 'OPR': 47.79, 'Auto': 20.149, 'CCWM': 25.832, 'TeamName': 'Cougar Cubs'}, {'TeamNum': 5573, 'OPR': 42.591, 'Auto': 17.483, 'CCWM': -23.54, 'TeamName': 'Payne Bots 5573'}, {'TeamNum': 12806, 'OPR': 30.686, 'Auto': 14.721, 'CCWM': -11.953, 'TeamName': 'Roboken'}, {'TeamNum': 19871, 'OPR': 23.586, 'Auto': -1.228, 'CCWM': -29.182, 'TeamName': 'Orange Tornadoes'}, {'TeamNum': 22504, 'OPR': 11.983, 'Auto': -2.746, 'CCWM': -9.59, 'TeamName': 'Blue Phoenix Robotics'}, {'TeamNum': 20388, 'OPR': 10.219, 'Auto': -3.013, 'CCWM': -15.374, 'TeamName': 'Newark School of Data Science and Information Technology'}, {'TeamNum': 4102, 'OPR': 5.773, 'Auto': -1.852, 'CCWM': -26.461, 'TeamName': 'CHS Cougars'}, {'TeamNum': 10874, 'OPR': 3.06, 'Auto': 3.814, 'CCWM': -81.797, 'TeamName': 'LIONS'}, {'TeamNum': 16903, 'OPR': 1.923, 'Auto': -3.396, 'CCWM': -28.438, 'TeamName': 'Mini Ravens'}, {'TeamNum': 15484, 'OPR': -0.584, 'Auto': 2.436, 'CCWM': -61.569, 'TeamName': 'Central High School'}]
USNJNELT2
[{'TeamNum': 8405, 'OPR': 113.539, 'Auto': 23.676, 'CCWM': 89.274, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 11180, 'OPR': 112.778, 'Auto': 26.899, 'CCWM': 91.33, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 19823, 'OPR': 65.229, 'Auto': 18.195, 'CCWM': 57.086, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 12968, 'OPR': 47.894, 'Auto': 10.902, 'CCWM': 5.097, 'TeamName': 'Bard RoboRaptors'}, {'TeamNum': 7959, 'OPR': 47.79, 'Auto': 20.149, 'CCWM': 25.832, 'TeamName': 'Cougar Cubs'}, {'TeamNum': 5573, 'OPR': 42.591, 'Auto': 17.483, 'CCWM': -23.54, 'TeamName': 'Payne Bots 5573'}, {'TeamNum': 12806, 'OPR': 30.686, 'Auto': 14.721, 'CCWM': -11.953, 'TeamName': 'Roboken'}, {'TeamNum': 19871, 'OPR': 23.586, 'Auto': -1.228, 'CCWM': -29.182, 'TeamName': 'Orange Tornadoes'}, {'TeamNum': 22504, 'OPR': 11.983, 'Auto': -2.746, 'CCWM': -9.59, 'TeamName': 'Blue Phoenix Robotics'}, {'TeamNum': 20388, 'OPR': 10.219, 'Auto': -3.013, 'CCWM': -15.374, 'TeamName': 'Newark School of Data Science and Information Technology'}, {'TeamNum': 4102, 'OPR': 5.773, 'Auto': -1.852, 'CCWM': -26.461, 'TeamName': 'CHS Cougars'}, {'TeamNum': 10874, 'OPR': 3.06, 'Auto': 3.814, 'CCWM': -81.797, 'TeamName': 'LIONS'}, {'TeamNum': 16903, 'OPR': 1.923, 'Auto': -3.396, 'CCWM': -28.438, 'TeamName': 'Mini Ravens'}, {'TeamNum': 15484, 'OPR': -0.584, 'Auto': 2.436, 'CCWM': -61.569, 'TeamName': 'Central High School'}]
i 1045
{'14481', '609', '8812', '11132', '21226', '7350', '19747', '21630', '21767', '11304', '14544', '11754', '21807', '11697', '14975', '18671', '12417', '21505', '19569', '7040', '20255', '18061', '12601', '21995', '6069'}
[{'TeamNum': 11697, 'OPR': 82.162, 'Auto': 15.573, 'CCWM': 57.644, 'TeamName': 'TECH-tonic'}, {'TeamNum': 11754, 'OPR': 81.463, 'Auto': 26.085, 'CCWM': 20.165, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 7350, 'OPR': 75.443, 'Auto': 20.783, 'CCWM': 14.134, 'TeamName': "Watt's NXT?"}, {'TeamNum': 7040, 'OPR': 74.52, 'Auto': 26.755, 'CCWM': 31.236, 'TeamName': 'CyberFalcons'}, {'TeamNum': 21226, 'OPR': 67.187, 'Auto': 25.659, 'CCWM': 61.364, 'TeamName': 'RoboRaiders'}, {'TeamNum': 14481, 'OPR': 66.899, 'Auto': 2.984, 'CCWM': 27.487, 'TeamName': "Don't Blink"}, {'TeamNum': 19747, 'OPR': 66.7, 'Auto': 19.888, 'CCWM': 33.825, 'TeamName': 'DYNABYTES'}, {'TeamNum': 21630, 'OPR': 65.808, 'Auto': 25.22, 'CCWM': 7.536, 'TeamName': 'Argonauts'}, {'TeamNum': 21505, 'OPR': 59.012, 'Auto': 2.085, 'CCWM': 10.992, 'TeamName': 'RaidersBots'}, {'TeamNum': 609, 'OPR': 55.75, 'Auto': 14.808, 'CCWM': 34.803, 'TeamName': 'Cougars'}, {'TeamNum': 21767, 'OPR': 48.798, 'Auto': 16.967, 'CCWM': 10.323, 'TeamName': 'Quadra'}, {'TeamNum': 21807, 'OPR': 43.725, 'Auto': 2.5, 'CCWM': 34.706, 'TeamName': 'INCINERATORS'}, {'TeamNum': 18061, 'OPR': 42.314, 'Auto': -0.957, 'CCWM': 24.902, 'TeamName': 'Simply Complex 18061'}, {'TeamNum': 14975, 'OPR': 32.09, 'Auto': 2.027, 'CCWM': -7.336, 'TeamName': "Botz N' Bolts"}, {'TeamNum': 8812, 'OPR': 29.331, 'Auto': 3.505, 'CCWM': -5.265, 'TeamName': 'CyberRaptors'}, {'TeamNum': 18671, 'OPR': 24.511, 'Auto': -1.2, 'CCWM': -18.282, 'TeamName': 'Faraday'}, {'TeamNum': 11304, 'OPR': 23.845, 'Auto': 22.587, 'CCWM': -60.751, 'TeamName': 'Ridge Robotics'}, {'TeamNum': 21995, 'OPR': 23.74, 'Auto': 2.991, 'CCWM': -9.48, 'TeamName': 'Aquinas Trojans'}, {'TeamNum': 6069, 'OPR': 20.546, 'Auto': 3.077, 'CCWM': -24.211, 'TeamName': 'Pingry Robotics'}, {'TeamNum': 11132, 'OPR': 19.679, 'Auto': 0.023, 'CCWM': -32.846, 'TeamName': 'HERD (High School Engineering Robotics Division)'}, {'TeamNum': 20255, 'OPR': 11.205, 'Auto': -0.54, 'CCWM': -50.127, 'TeamName': "Falcon's Nest"}, {'TeamNum': 12417, 'OPR': 10.19, 'Auto': -4.931, 'CCWM': -54.164, 'TeamName': 'Highland Park Owls'}, {'TeamNum': 14544, 'OPR': 9.836, 'Auto': 5.931, 'CCWM': -52.108, 'TeamName': 'Pingry Big Blue Robotics'}, {'TeamNum': 19569, 'OPR': 3.241, 'Auto': -6.375, 'CCWM': -30.801, 'TeamName': 'Robosapiens '}, {'TeamNum': 12601, 'OPR': -2.062, 'Auto': 1.207, 'CCWM': -22.505, 'TeamName': 'Robostorm'}]
USNJUCLT2
[{'TeamNum': 11697, 'OPR': 82.162, 'Auto': 15.573, 'CCWM': 57.644, 'TeamName': 'TECH-tonic'}, {'TeamNum': 11754, 'OPR': 81.463, 'Auto': 26.085, 'CCWM': 20.165, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 7350, 'OPR': 75.443, 'Auto': 20.783, 'CCWM': 14.134, 'TeamName': "Watt's NXT?"}, {'TeamNum': 7040, 'OPR': 74.52, 'Auto': 26.755, 'CCWM': 31.236, 'TeamName': 'CyberFalcons'}, {'TeamNum': 21226, 'OPR': 67.187, 'Auto': 25.659, 'CCWM': 61.364, 'TeamName': 'RoboRaiders'}, {'TeamNum': 14481, 'OPR': 66.899, 'Auto': 2.984, 'CCWM': 27.487, 'TeamName': "Don't Blink"}, {'TeamNum': 19747, 'OPR': 66.7, 'Auto': 19.888, 'CCWM': 33.825, 'TeamName': 'DYNABYTES'}, {'TeamNum': 21630, 'OPR': 65.808, 'Auto': 25.22, 'CCWM': 7.536, 'TeamName': 'Argonauts'}, {'TeamNum': 21505, 'OPR': 59.012, 'Auto': 2.085, 'CCWM': 10.992, 'TeamName': 'RaidersBots'}, {'TeamNum': 609, 'OPR': 55.75, 'Auto': 14.808, 'CCWM': 34.803, 'TeamName': 'Cougars'}, {'TeamNum': 21767, 'OPR': 48.798, 'Auto': 16.967, 'CCWM': 10.323, 'TeamName': 'Quadra'}, {'TeamNum': 21807, 'OPR': 43.725, 'Auto': 2.5, 'CCWM': 34.706, 'TeamName': 'INCINERATORS'}, {'TeamNum': 18061, 'OPR': 42.314, 'Auto': -0.957, 'CCWM': 24.902, 'TeamName': 'Simply Complex 18061'}, {'TeamNum': 14975, 'OPR': 32.09, 'Auto': 2.027, 'CCWM': -7.336, 'TeamName': "Botz N' Bolts"}, {'TeamNum': 8812, 'OPR': 29.331, 'Auto': 3.505, 'CCWM': -5.265, 'TeamName': 'CyberRaptors'}, {'TeamNum': 18671, 'OPR': 24.511, 'Auto': -1.2, 'CCWM': -18.282, 'TeamName': 'Faraday'}, {'TeamNum': 11304, 'OPR': 23.845, 'Auto': 22.587, 'CCWM': -60.751, 'TeamName': 'Ridge Robotics'}, {'TeamNum': 21995, 'OPR': 23.74, 'Auto': 2.991, 'CCWM': -9.48, 'TeamName': 'Aquinas Trojans'}, {'TeamNum': 6069, 'OPR': 20.546, 'Auto': 3.077, 'CCWM': -24.211, 'TeamName': 'Pingry Robotics'}, {'TeamNum': 11132, 'OPR': 19.679, 'Auto': 0.023, 'CCWM': -32.846, 'TeamName': 'HERD (High School Engineering Robotics Division)'}, {'TeamNum': 20255, 'OPR': 11.205, 'Auto': -0.54, 'CCWM': -50.127, 'TeamName': "Falcon's Nest"}, {'TeamNum': 12417, 'OPR': 10.19, 'Auto': -4.931, 'CCWM': -54.164, 'TeamName': 'Highland Park Owls'}, {'TeamNum': 14544, 'OPR': 9.836, 'Auto': 5.931, 'CCWM': -52.108, 'TeamName': 'Pingry Big Blue Robotics'}, {'TeamNum': 19569, 'OPR': 3.241, 'Auto': -6.375, 'CCWM': -30.801, 'TeamName': 'Robosapiens '}, {'TeamNum': 12601, 'OPR': -2.062, 'Auto': 1.207, 'CCWM': -22.505, 'TeamName': 'Robostorm'}]
i 1046
i 1047
{'19783', '12399', '16700', '13510', '18773', '12414', '20807', '20203', '18', '10949', '4654', '21378', '22612', '20805', '5356', '21429', '11205', '5484', '7230', '7486', '12011', '20228', '22240', '11995', '12331', '20841', '21428'}

[{'TeamNum': 5356, 'OPR': 88.742, 'Auto': 23.378, 'CCWM': 35.448, 'TeamName': 'TARDIS'}, {'TeamNum': 22240, 'OPR': 80.353, 'Auto': 6.536, 'CCWM': 29.85, 'TeamName': 'Rough Estimate '}, {'TeamNum': 18773, 'OPR': 72.867, 'Auto': 24.986, 'CCWM': 8.929, 'TeamName': 'Team Gambit'}, {'TeamNum': 20228, 'OPR': 71.834, 'Auto': -3.129, 'CCWM': 41.854, 'TeamName': 'SMRT'}, {'TeamNum': 10949, 'OPR': 71.205, 'Auto': 30.331, 'CCWM': 36.035, 'TeamName': 'Mechanical Operations Bureau'}, {'TeamNum': 21428, 'OPR': 67.511, 'Auto': 2.718, 'CCWM': 4.507, 'TeamName': 'Silver Eagles'}, {'TeamNum': 12399, 'OPR': 62.104, 'Auto': 11.341, 'CCWM': -19.685, 'TeamName': 'Mechanical Devils'}, {'TeamNum': 7230, 'OPR': 61.913, 'Auto': 17.964, 'CCWM': 23.337, 'TeamName': 'SAS Atoms'}, {'TeamNum': 18, 'OPR': 60.158, 'Auto': -2.922, 'CCWM': 37.803, 'TeamName': 'Techno Chix'}, {'TeamNum': 4654, 'OPR': 58.115, 'Auto': 13.796, 'CCWM': 13.013, 'TeamName': 'Jellyfish '}, {'TeamNum': 21429, 'OPR': 56.839, 'Auto': 16.732, 'CCWM': 24.521, 'TeamName': 'Golden Eagles'}, {'TeamNum': 22612, 'OPR': 56.082, 'Auto': 7.221, 'CCWM': 11.673, 'TeamName': 'New Wave'}, {'TeamNum': 20841, 'OPR': 52.282, 'Auto': 11.739, 'CCWM': 5.759, 'TeamName': 'Peekskill Pride #1'}, {'TeamNum': 20805, 'OPR': 50.202, 'Auto': 4.193, 'CCWM': 17.242, 'TeamName': 'BearBots'}, {'TeamNum': 7486, 'OPR': 45.508, 'Auto': -1.684, 'CCWM': -13.444, 'TeamName': 'Suffern Robotics'}, {'TeamNum': 12011, 'OPR': 44.059, 'Auto': -0.529, 'CCWM': 10.549, 'TeamName': 'InTigers'}, {'TeamNum': 11205, 'OPR': 40.679, 'Auto': -1.855, 'CCWM': 13.998, 'TeamName': 'Edgemont Robotics Club'}, {'TeamNum': 5484, 'OPR': 40.366, 'Auto': 13.799, 'CCWM': -14.694, 'TeamName': 'The EnderBots'}, {'TeamNum': 16700, 'OPR': 39.27, 'Auto': 25.335, 'CCWM': -31.424, 'TeamName': 'JAYBOTS'}, {'TeamNum': 11995, 'OPR': 38.762, 'Auto': 6.875, 'CCWM': 0.706, 'TeamName': 'TACA'}, {'TeamNum': 20203, 'OPR': 30.401, 'Auto': 3.529, 'CCWM': -25.381, 'TeamName': 'Super Awesome Robot'}, {'TeamNum': 12331, 'OPR': 28.628, 'Auto': 3.44, 'CCWM': -20.493, 'TeamName': 'Scarsdale Robo Raiders'}, {'TeamNum': 20807, 'OPR': 27.733, 'Auto': 2.233, 'CCWM': -39.47, 'TeamName': 'Phoenix Robotics'}, {'TeamNum': 19783, 'OPR': 26.602, 'Auto': 12.148, 'CCWM': -24.141, 'TeamName': 'Masters Engineering and Robotics'}, {'TeamNum': 12414, 'OPR': 23.653, 'Auto': 15.18, 'CCWM': -12.385, 'TeamName': 'Tin Diesel'}, {'TeamNum': 13510, 'OPR': 10.85, 'Auto': 6.664, 'CCWM': -62.2, 'TeamName': 'MUCCBots!'}, {'TeamNum': 21378, 'OPR': 9.315, 'Auto': 7.836, 'CCWM': -56.813, 'TeamName': 'RoboTigers'}]
USNYEXHJQ
[{'TeamNum': 5356, 'OPR': 88.742, 'Auto': 23.378, 'CCWM': 35.448, 'TeamName': 'TARDIS'}, {'TeamNum': 22240, 'OPR': 80.353, 'Auto': 6.536, 'CCWM': 29.85, 'TeamName': 'Rough Estimate '}, {'TeamNum': 18773, 'OPR': 72.867, 'Auto': 24.986, 'CCWM': 8.929, 'TeamName': 'Team Gambit'}, {'TeamNum': 20228, 'OPR': 71.834, 'Auto': -3.129, 'CCWM': 41.854, 'TeamName': 'SMRT'}, {'TeamNum': 10949, 'OPR': 71.205, 'Auto': 30.331, 'CCWM': 36.035, 'TeamName': 'Mechanical Operations Bureau'}, {'TeamNum': 21428, 'OPR': 67.511, 'Auto': 2.718, 'CCWM': 4.507, 'TeamName': 'Silver Eagles'}, {'TeamNum': 12399, 'OPR': 62.104, 'Auto': 11.341, 'CCWM': -19.685, 'TeamName': 'Mechanical Devils'}, {'TeamNum': 7230, 'OPR': 61.913, 'Auto': 17.964, 'CCWM': 23.337, 'TeamName': 'SAS Atoms'}, {'TeamNum': 18, 'OPR': 60.158, 'Auto': -2.922, 'CCWM': 37.803, 'TeamName': 'Techno Chix'}, {'TeamNum': 4654, 'OPR': 58.115, 'Auto': 13.796, 'CCWM': 13.013, 'TeamName': 'Jellyfish '}, {'TeamNum': 21429, 'OPR': 56.839, 'Auto': 16.732, 'CCWM': 24.521, 'TeamName': 'Golden Eagles'}, {'TeamNum': 22612, 'OPR': 56.082, 'Auto': 7.221, 'CCWM': 11.673, 'TeamName': 'New Wave'}, {'TeamNum': 20841, 'OPR': 52.282, 'Auto': 11.739, 'CCWM': 5.759, 'TeamName': 'Peekskill Pride #1'}, {'TeamNum': 20805, 'OPR': 50.202, 'Auto': 4.193, 'CCWM': 17.242, 'TeamName': 'BearBots'}, {'TeamNum': 7486, 'OPR': 45.508, 'Auto': -1.684, 'CCWM': -13.444, 'TeamName': 'Suffern Robotics'}, {'TeamNum': 12011, 'OPR': 44.059, 'Auto': -0.529, 'CCWM': 10.549, 'TeamName': 'InTigers'}, {'TeamNum': 11205, 'OPR': 40.679, 'Auto': -1.855, 'CCWM': 13.998, 'TeamName': 'Edgemont Robotics Club'}, {'TeamNum': 5484, 'OPR': 40.366, 'Auto': 13.799, 'CCWM': -14.694, 'TeamName': 'The EnderBots'}, {'TeamNum': 16700, 'OPR': 39.27, 'Auto': 25.335, 'CCWM': -31.424, 'TeamName': 'JAYBOTS'}, {'TeamNum': 11995, 'OPR': 38.762, 'Auto': 6.875, 'CCWM': 0.706, 'TeamName': 'TACA'}, {'TeamNum': 20203, 'OPR': 30.401, 'Auto': 3.529, 'CCWM': -25.381, 'TeamName': 'Super Awesome Robot'}, {'TeamNum': 12331, 'OPR': 28.628, 'Auto': 3.44, 'CCWM': -20.493, 'TeamName': 'Scarsdale Robo Raiders'}, {'TeamNum': 20807, 'OPR': 27.733, 'Auto': 2.233, 'CCWM': -39.47, 'TeamName': 'Phoenix Robotics'}, {'TeamNum': 19783, 'OPR': 26.602, 'Auto': 12.148, 'CCWM': -24.141, 'TeamName': 'Masters Engineering and Robotics'}, {'TeamNum': 12414, 'OPR': 23.653, 'Auto': 15.18, 'CCWM': -12.385, 'TeamName': 'Tin Diesel'}, {'TeamNum': 13510, 'OPR': 10.85, 'Auto': 6.664, 'CCWM': -62.2, 'TeamName': 'MUCCBots!'}, {'TeamNum': 21378, 'OPR': 9.315, 'Auto': 7.836, 'CCWM': -56.813, 'TeamName': 'RoboTigers'}]
i 1048
{'14365', '17978', '19778', '6085', '6298', '21815', '19788', '13020', '4969', '10464', '11580', '12211', '9828', '13172', '12802', '16449', '20385', '14279', '11781', '10117', '12569'}
[{'TeamNum': 17978, 'OPR': 110.627, 'Auto': 25.014, 'CCWM': 86.257, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 4969, 'OPR': 107.416, 'Auto': 11.043, 'CCWM': 76.751, 'TeamName': 'Robot-X'}, {'TeamNum': 11580, 'OPR': 96.847, 'Auto': 20.313, 'CCWM': 65.668, 'TeamName': 'EagleBots'}, {'TeamNum': 16449, 'OPR': 85.567, 'Auto': 23.531, 'CCWM': 54.201, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 20385, 'OPR': 80.395, 'Auto': 17.164, 'CCWM': 18.553, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 14279, 'OPR': 79.791, 'Auto': 13.51, 'CCWM': -4.637, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 13172, 'OPR': 57.538, 'Auto': 12.698, 'CCWM': 25.29, 'TeamName': 'Centipede'}, {'TeamNum': 19778, 'OPR': 55.49, 'Auto': 9.166, 'CCWM': 27.746, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 14365, 'OPR': 52.699, 'Auto': 7.716, 'CCWM': -16.088, 'TeamName': 'Summit Knights'}, {'TeamNum': 6085, 'OPR': 51.327, 'Auto': 12.053, 'CCWM': 5.135, 'TeamName': 'Electro/Mechanically Controlled Chaos'}, {'TeamNum': 12569, 'OPR': 48.887, 'Auto': 10.843, 'CCWM': -6.094, 'TeamName': 'STEMstangs'}, {'TeamNum': 12802, 'OPR': 48.654, 'Auto': 14.909, 'CCWM': -41.921, 'TeamName': 'We Will Bot You'}, {'TeamNum': 6298, 'OPR': 48.003, 'Auto': 8.409, 'CCWM': 1.297, 'TeamName': 'Tech Titans'}, {'TeamNum': 9828, 'OPR': 35.257, 'Auto': -2.17, 'CCWM': 0.394, 'TeamName': 'Ultron Unit '}, {'TeamNum': 10464, 'OPR': 26.884, 'Auto': 5.421, 'CCWM': -11.372, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 12211, 'OPR': 19.17, 'Auto': 3.633, 'CCWM': -49.208, 'TeamName': 'Trial & Error'}, {'TeamNum': 21815, 'OPR': 15.244, 'Auto': 5.459, 'CCWM': -63.493, 'TeamName': 'EMAGINE - Emmanuel’s Mean and Green Iron Narwhal'}, {'TeamNum': 13020, 'OPR': 12.263, 'Auto': -1.633, 'CCWM': -63.482, 'TeamName': 'Golden Tiercelet'}, {'TeamNum': 11781, 'OPR': 8.991, 'Auto': -3.334, 'CCWM': -45.411, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 10117, 'OPR': 7.35, 'Auto': -0.345, 'CCWM': -59.586, 'TeamName': 'Party Pandas'}, {'TeamNum': 19788, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Agents of Change'}]
USOHSYQ
[{'TeamNum': 17978, 'OPR': 110.627, 'Auto': 25.014, 'CCWM': 86.257, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 4969, 'OPR': 107.416, 'Auto': 11.043, 'CCWM': 76.751, 'TeamName': 'Robot-X'}, {'TeamNum': 11580, 'OPR': 96.847, 'Auto': 20.313, 'CCWM': 65.668, 'TeamName': 'EagleBots'}, {'TeamNum': 16449, 'OPR': 85.567, 'Auto': 23.531, 'CCWM': 54.201, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 20385, 'OPR': 80.395, 'Auto': 17.164, 'CCWM': 18.553, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 14279, 'OPR': 79.791, 'Auto': 13.51, 'CCWM': -4.637, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 13172, 'OPR': 57.538, 'Auto': 12.698, 'CCWM': 25.29, 'TeamName': 'Centipede'}, {'TeamNum': 19778, 'OPR': 55.49, 'Auto': 9.166, 'CCWM': 27.746, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 14365, 'OPR': 52.699, 'Auto': 7.716, 'CCWM': -16.088, 'TeamName': 'Summit Knights'}, {'TeamNum': 6085, 'OPR': 51.327, 'Auto': 12.053, 'CCWM': 5.135, 'TeamName': 'Electro/Mechanically Controlled Chaos'}, {'TeamNum': 12569, 'OPR': 48.887, 'Auto': 10.843, 'CCWM': -6.094, 'TeamName': 'STEMstangs'}, {'TeamNum': 12802, 'OPR': 48.654, 'Auto': 14.909, 'CCWM': -41.921, 'TeamName': 'We Will Bot You'}, {'TeamNum': 6298, 'OPR': 48.003, 'Auto': 8.409, 'CCWM': 1.297, 'TeamName': 'Tech Titans'}, {'TeamNum': 9828, 'OPR': 35.257, 'Auto': -2.17, 'CCWM': 0.394, 'TeamName': 'Ultron Unit '}, {'TeamNum': 10464, 'OPR': 26.884, 'Auto': 5.421, 'CCWM': -11.372, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 12211, 'OPR': 19.17, 'Auto': 3.633, 'CCWM': -49.208, 'TeamName': 'Trial & Error'}, {'TeamNum': 21815, 'OPR': 15.244, 'Auto': 5.459, 'CCWM': -63.493, 'TeamName': 'EMAGINE - Emmanuel’s Mean and Green Iron Narwhal'}, {'TeamNum': 13020, 'OPR': 12.263, 'Auto': -1.633, 'CCWM': -63.482, 'TeamName': 'Golden Tiercelet'}, {'TeamNum': 11781, 'OPR': 8.991, 'Auto': -3.334, 'CCWM': -45.411, 'TeamName': 'MVS Rambotics'}, {'TeamNum': 10117, 'OPR': 7.35, 'Auto': -0.345, 'CCWM': -59.586, 'TeamName': 'Party Pandas'}, {'TeamNum': 19788, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Agents of Change'}]

i 1049
{'8393', '12792', '16564', '16011', '5488', '13669', '22285', '14133', '20094', '7423', '16468', '11319', '16087', '20152', '18284', '22284', '118', '12308', '20153', '22283', '8730', '21437', '22312', '22282', '11208', '10353'}
[{'TeamNum': 20153, 'OPR': 161.763, 'Auto': 39.66, 'CCWM': 68.465, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8393, 'OPR': 132.204, 'Auto': 39.285, 'CCWM': 84.898, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 16468, 'OPR': 112.919, 'Auto': 24.666, 'CCWM': 47.866, 'TeamName': 'Green Lemons'}, {'TeamNum': 20152, 'OPR': 104.928, 'Auto': 24.646, 'CCWM': 5.661, 'TeamName': 'Battle Bots'}, {'TeamNum': 12792, 'OPR': 101.39, 'Auto': 20.791, 'CCWM': 44.012, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 22312, 'OPR': 89.181, 'Auto': 21.596, 'CCWM': 9.845, 'TeamName': 'The Brobdingnagian Tritocephalic BrainSTEM Robotics Team'}, {'TeamNum': 13669, 'OPR': 82.785, 'Auto': 11.762, 'CCWM': 24.931, 'TeamName': 'RAIDERBOTS - COATESVILLE AREA HIGH SCHOOL'}, {'TeamNum': 18284, 'OPR': 73.601, 'Auto': 14.588, 'CCWM': -14.892, 'TeamName': 'Indeterminate Forms'}, {'TeamNum': 7423, 'OPR': 71.229, 'Auto': 10.952, 'CCWM': 53.392, 'TeamName': 'Flaming Phoenix'}, {'TeamNum': 16564, 'OPR': 69.453, 'Auto': 25.602, 'CCWM': 16.237, 'TeamName': 'Digital Devils'}, {'TeamNum': 8730, 'OPR': 61.799, 'Auto': 22.211, 'CCWM': 12.214, 'TeamName': 'Robogriffins'}, {'TeamNum': 16011, 'OPR': 57.356, 'Auto': 16.586, 'CCWM': 3.287, 'TeamName': 'Fayette County 4H'}, {'TeamNum': 12308, 'OPR': 41.538, 'Auto': 7.991, 'CCWM': -45.477, 'TeamName': 'Bodine Ambassadors'}, {'TeamNum': 21437, 'OPR': 41.011, 'Auto': 15.771, 'CCWM': -5.249, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 22282, 'OPR': 37.048, 'Auto': 11.935, 'CCWM': -20.02, 'TeamName': 'SLAMPHIBIANS'}, {'TeamNum': 14133, 'OPR': 36.865, 'Auto': 6.601, 'CCWM': -2.526, 'TeamName': 'Lansdale Catholic Cyber Crusaders'}, {'TeamNum': 20094, 'OPR': 35.067, 'Auto': 9.651, 'CCWM': -65.038, 'TeamName': "Raiderbot's Squared"}, {'TeamNum': 10353, 'OPR': 33.549, 'Auto': 1.055, 'CCWM': -17.431, 'TeamName': 'Metal Works'}, {'TeamNum': 11319, 'OPR': 32.915, 'Auto': 16.251, 'CCWM': -41.866, 'TeamName': 'Explorer Robotics'}, {'TeamNum': 22283, 'OPR': 31.207, 'Auto': 1.513, 'CCWM': 10.052, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 11208, 'OPR': 29.189, 'Auto': 8.174, 'CCWM': -20.938, 'TeamName': 'Kardia Robotics'}, {'TeamNum': 22284, 'OPR': 14.955, 'Auto': 5.417, 'CCWM': -16.969, 'TeamName': 'SLAM GREG'}, {'TeamNum': 5488, 'OPR': 13.014, 'Auto': -2.747, 'CCWM': -41.584, 'TeamName': 'Robo Dragons'}, {'TeamNum': 118, 'OPR': 7.301, 'Auto': 1.325, 'CCWM': -75.466, 'TeamName': 'Steel Hornets'}, {'TeamNum': 22285, 'OPR': 2.218, 'Auto': 1.48, 'CCWM': 9.647, 'TeamName': 'SLAM SHADY'}, {'TeamNum': 16087, 'OPR': -7.254, 'Auto': -0.624, 'CCWM': -33.756, 'TeamName': 'Klinger Klippers'}]
USPAEMQ2
[{'TeamNum': 20153, 'OPR': 161.763, 'Auto': 39.66, 'CCWM': 68.465, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8393, 'OPR': 132.204, 'Auto': 39.285, 'CCWM': 84.898, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 16468, 'OPR': 112.919, 'Auto': 24.666, 'CCWM': 47.866, 'TeamName': 'Green Lemons'}, {'TeamNum': 20152, 'OPR': 104.928, 'Auto': 24.646, 'CCWM': 5.661, 'TeamName': 'Battle Bots'}, {'TeamNum': 12792, 'OPR': 101.39, 'Auto': 20.791, 'CCWM': 44.012, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 22312, 'OPR': 89.181, 'Auto': 21.596, 'CCWM': 9.845, 'TeamName': 'The Brobdingnagian Tritocephalic BrainSTEM Robotics Team'}, {'TeamNum': 13669, 'OPR': 82.785, 'Auto': 11.762, 'CCWM': 24.931, 'TeamName': 'RAIDERBOTS - COATESVILLE AREA HIGH SCHOOL'}, {'TeamNum': 18284, 'OPR': 73.601, 'Auto': 14.588, 'CCWM': -14.892, 'TeamName': 'Indeterminate Forms'}, {'TeamNum': 7423, 'OPR': 71.229, 'Auto': 10.952, 'CCWM': 53.392, 'TeamName': 'Flaming Phoenix'}, {'TeamNum': 16564, 'OPR': 69.453, 'Auto': 25.602, 'CCWM': 16.237, 'TeamName': 'Digital Devils'}, {'TeamNum': 8730, 'OPR': 61.799, 'Auto': 22.211, 'CCWM': 12.214, 'TeamName': 'Robogriffins'}, {'TeamNum': 16011, 'OPR': 57.356, 'Auto': 16.586, 'CCWM': 3.287, 'TeamName': 'Fayette County 4H'}, {'TeamNum': 12308, 'OPR': 41.538, 'Auto': 7.991, 'CCWM': -45.477, 'TeamName': 'Bodine Ambassadors'}, {'TeamNum': 21437, 'OPR': 41.011, 'Auto': 15.771, 'CCWM': -5.249, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 22282, 'OPR': 37.048, 'Auto': 11.935, 'CCWM': -20.02, 'TeamName': 'SLAMPHIBIANS'}, {'TeamNum': 14133, 'OPR': 36.865, 'Auto': 6.601, 'CCWM': -2.526, 'TeamName': 'Lansdale Catholic Cyber Crusaders'}, {'TeamNum': 20094, 'OPR': 35.067, 'Auto': 9.651, 'CCWM': -65.038, 'TeamName': "Raiderbot's Squared"}, {'TeamNum': 10353, 'OPR': 33.549, 'Auto': 1.055, 'CCWM': -17.431, 'TeamName': 'Metal Works'}, {'TeamNum': 11319, 'OPR': 32.915, 'Auto': 16.251, 'CCWM': -41.866, 'TeamName': 'Explorer Robotics'}, {'TeamNum': 22283, 'OPR': 31.207, 'Auto': 1.513, 'CCWM': 10.052, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 11208, 'OPR': 29.189, 'Auto': 8.174, 'CCWM': -20.938, 'TeamName': 'Kardia Robotics'}, {'TeamNum': 22284, 'OPR': 14.955, 'Auto': 5.417, 'CCWM': -16.969, 'TeamName': 'SLAM GREG'}, {'TeamNum': 5488, 'OPR': 13.014, 'Auto': -2.747, 'CCWM': -41.584, 'TeamName': 'Robo Dragons'}, {'TeamNum': 118, 'OPR': 7.301, 'Auto': 1.325, 'CCWM': -75.466, 'TeamName': 'Steel Hornets'}, {'TeamNum': 22285, 'OPR': 2.218, 'Auto': 1.48, 'CCWM': 9.647, 'TeamName': 'SLAM SHADY'}, {'TeamNum': 16087, 'OPR': -7.254, 'Auto': -0.624, 'CCWM': -33.756, 'TeamName': 'Klinger Klippers'}]
i 1050
{'17458', '7244', '21928', '17457', '18849', '16466', '17596', '9222', '6378', '20152', '14738', '21458', '21727', '14423', '9791', '4149', '19844', '10771', '14842', '16800', '22521', '10098', '8645', '21728', '21680'}
[{'TeamNum': 21727, 'OPR': 106.95, 'Auto': 22.048, 'CCWM': 81.378, 'TeamName': 'AutoCorns'}, {'TeamNum': 8645, 'OPR': 96.238, 'Auto': 20.046, 'CCWM': 70.821, 'TeamName': 'Robotic Doges'}, {'TeamNum': 14423, 'OPR': 88.258, 'Auto': 15.376, 'CCWM': 32.355, 'TeamName': 'RoboCorns'}, {'TeamNum': 7244, 'OPR': 68.189, 'Auto': 9.251, 'CCWM': 6.211, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 14842, 'OPR': 66.353, 'Auto': 19.689, 'CCWM': 28.453, 'TeamName': 'SPYGEARS'}, {'TeamNum': 4149, 'OPR': 63.636, 'Auto': 4.045, 'CCWM': 10.088, 'TeamName': 'Terabytes'}, {'TeamNum': 14738, 'OPR': 62.987, 'Auto': 11.936, 'CCWM': 23.403, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 16466, 'OPR': 61.331, 'Auto': 12.233, 'CCWM': 10.984, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 16800, 'OPR': 60.38, 'Auto': 12.921, 'CCWM': -0.413, 'TeamName': 'Trial and Terror'}, {'TeamNum': 20152, 'OPR': 55.818, 'Auto': 14.749, 'CCWM': 9.207, 'TeamName': 'Battle Bots'}, {'TeamNum': 21680, 'OPR': 49.653, 'Auto': 20.549, 'CCWM': -25.595, 'TeamName': 'Friends Select'}, {'TeamNum': 6378, 'OPR': 47.099, 'Auto': 8.601, 'CCWM': -0.362, 'TeamName': 'JayBots'}, {'TeamNum': 21458, 'OPR': 41.98, 'Auto': 7.218, 'CCWM': -24.488, 'TeamName': 'Broken Blueberries'}, {'TeamNum': 17596, 'OPR': 41.854, 'Auto': -2.04, 'CCWM': 9.786, 'TeamName': 'Maneframe'}, {'TeamNum': 9791, 'OPR': 40.117, 'Auto': 6.877, 'CCWM': 8.024, 'TeamName': 'Divide by Zero'}, {'TeamNum': 10771, 'OPR': 39.626, 'Auto': 2.916, 'CCWM': -8.242, 'TeamName': 'Le Pamplemousse'}, {'TeamNum': 9222, 'OPR': 36.373, 'Auto': 2.648, 'CCWM': -11.627, 'TeamName': "O'Hara Robotics"}, {'TeamNum': 19844, 'OPR': 35.796, 'Auto': 17.581, 'CCWM': -19.251, 'TeamName': 'ElectroCorns'}, {'TeamNum': 21728, 'OPR': 29.811, 'Auto': 12.504, 'CCWM': -35.932, 'TeamName': 'TechniCorns'}, {'TeamNum': 18849, 'OPR': 29.204, 'Auto': 4.91, 'CCWM': -39.896, 'TeamName': 'Panthers'}, {'TeamNum': 17457, 'OPR': 27.705, 'Auto': 0.339, 'CCWM': -22.619, 'TeamName': 'Shafer Sharks'}, {'TeamNum': 10098, 'OPR': 26.227, 'Auto': 15.249, 'CCWM': 30.405, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 17458, 'OPR': 17.537, 'Auto': -6.753, 'CCWM': -35.131, 'TeamName': 'Snyder Owls'}, {'TeamNum': 21928, 'OPR': 17.467, 'Auto': 12.886, 'CCWM': -42.607, 'TeamName': 'TeleCorns'}, {'TeamNum': 22521, 'OPR': 1.589, 'Auto': 1.135, 'CCWM': -50.143, 'TeamName': "Snyder MS Wingin' It"}]
USPAEMQ1
[{'TeamNum': 21727, 'OPR': 106.95, 'Auto': 22.048, 'CCWM': 81.378, 'TeamName': 'AutoCorns'}, {'TeamNum': 8645, 'OPR': 96.238, 'Auto': 20.046, 'CCWM': 70.821, 'TeamName': 'Robotic Doges'}, {'TeamNum': 14423, 'OPR': 88.258, 'Auto': 15.376, 'CCWM': 32.355, 'TeamName': 'RoboCorns'}, {'TeamNum': 7244, 'OPR': 68.189, 'Auto': 9.251, 'CCWM': 6.211, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 14842, 'OPR': 66.353, 'Auto': 19.689, 'CCWM': 28.453, 'TeamName': 'SPYGEARS'}, {'TeamNum': 4149, 'OPR': 63.636, 'Auto': 4.045, 'CCWM': 10.088, 'TeamName': 'Terabytes'}, {'TeamNum': 14738, 'OPR': 62.987, 'Auto': 11.936, 'CCWM': 23.403, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 16466, 'OPR': 61.331, 'Auto': 12.233, 'CCWM': 10.984, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 16800, 'OPR': 60.38, 'Auto': 12.921, 'CCWM': -0.413, 'TeamName': 'Trial and Terror'}, {'TeamNum': 20152, 'OPR': 55.818, 'Auto': 14.749, 'CCWM': 9.207, 'TeamName': 'Battle Bots'}, {'TeamNum': 21680, 'OPR': 49.653, 'Auto': 20.549, 'CCWM': -25.595, 'TeamName': 'Friends Select'}, {'TeamNum': 6378, 'OPR': 47.099, 'Auto': 8.601, 'CCWM': -0.362, 'TeamName': 'JayBots'}, {'TeamNum': 21458, 'OPR': 41.98, 'Auto': 7.218, 'CCWM': -24.488, 'TeamName': 'Broken Blueberries'}, {'TeamNum': 17596, 'OPR': 41.854, 'Auto': -2.04, 'CCWM': 9.786, 'TeamName': 'Maneframe'}, {'TeamNum': 9791, 'OPR': 40.117, 'Auto': 6.877, 'CCWM': 8.024, 'TeamName': 'Divide by Zero'}, {'TeamNum': 10771, 'OPR': 39.626, 'Auto': 2.916, 'CCWM': -8.242, 'TeamName': 'Le Pamplemousse'}, {'TeamNum': 9222, 'OPR': 36.373, 'Auto': 2.648, 'CCWM': -11.627, 'TeamName': "O'Hara Robotics"}, {'TeamNum': 19844, 'OPR': 35.796, 'Auto': 17.581, 'CCWM': -19.251, 'TeamName': 'ElectroCorns'}, {'TeamNum': 21728, 'OPR': 29.811, 'Auto': 12.504, 'CCWM': -35.932, 'TeamName': 'TechniCorns'}, {'TeamNum': 18849, 'OPR': 29.204, 'Auto': 4.91, 'CCWM': -39.896, 'TeamName': 'Panthers'}, {'TeamNum': 17457, 'OPR': 27.705, 'Auto': 0.339, 'CCWM': -22.619, 'TeamName': 'Shafer Sharks'}, {'TeamNum': 10098, 'OPR': 26.227, 'Auto': 15.249, 'CCWM': 30.405, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 17458, 'OPR': 17.537, 'Auto': -6.753, 'CCWM': -35.131, 'TeamName': 'Snyder Owls'}, {'TeamNum': 21928, 'OPR': 17.467, 'Auto': 12.886, 'CCWM': -42.607, 'TeamName': 'TeleCorns'}, {'TeamNum': 22521, 'OPR': 1.589, 'Auto': 1.135, 'CCWM': -50.143, 'TeamName': "Snyder MS Wingin' It"}]
i 1051

{'8411', '20694', '18687', '21457', '14491', '18689', '11161', '4949', '11279', '16885', '11468', '18832', '17108', '10391', '12611', '14291', '16811', '19989', '21530', '18873', '18909', '21673', '9934', '9912', '21461', '6073', '7783', '18714', '22449'}
[{'TeamNum': 6073, 'OPR': 106.641, 'Auto': 14.66, 'CCWM': 66.984, 'TeamName': 'MUS Robotics'}, {'TeamNum': 12611, 'OPR': 93.178, 'Auto': 28.198, 'CCWM': 61.57, 'TeamName': 'TechNova'}, {'TeamNum': 14491, 'OPR': 90.245, 'Auto': 34.66, 'CCWM': 32.172, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 20694, 'OPR': 77.923, 'Auto': 12.391, 'CCWM': 68.17, 'TeamName': 'Craft Coalition '}, {'TeamNum': 11279, 'OPR': 68.625, 'Auto': -0.052, 'CCWM': 3.906, 'TeamName': 'Pure Imagination'}, {'TeamNum': 10391, 'OPR': 67.096, 'Auto': 11.74, 'CCWM': 66.894, 'TeamName': 'Lynx Robotics'}, {'TeamNum': 9934, 'OPR': 64.379, 'Auto': 3.694, 'CCWM': 12.703, 'TeamName': 'Webb Robotics - FTC'}, {'TeamNum': 8411, 'OPR': 63.42, 'Auto': 8.46, 'CCWM': -2.723, 'TeamName': 'SHARP'}, {'TeamNum': 11468, 'OPR': 52.346, 'Auto': 25.537, 'CCWM': 32.212, 'TeamName': 'Ohm Raiders'}, {'TeamNum': 18689, 'OPR': 48.042, 'Auto': 18.691, 'CCWM': 7.713, 'TeamName': '4-H Gear Grinders'}, {'TeamNum': 19989, 'OPR': 47.924, 'Auto': 1.584, 'CCWM': 25.472, 'TeamName': 'Wings of Steel'}, {'TeamNum': 21457, 'OPR': 47.704, 'Auto': 6.678, 'CCWM': -1.04, 'TeamName': 'Tennessine Titans '}, {'TeamNum': 17108, 'OPR': 44.899, 'Auto': 3.532, 'CCWM': -51.04, 'TeamName': 'MAGNETUDE GOLD'}, {'TeamNum': 11161, 'OPR': 44.253, 'Auto': 2.9, 'CCWM': -12.499, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 21461, 'OPR': 41.89, 'Auto': 3.229, 'CCWM': 12.195, 'TeamName': 'TriCities Youth Robotics'}, {'TeamNum': 14291, 'OPR': 41.546, 'Auto': 4.743, 'CCWM': -37.894, 'TeamName': 'Small Town Robotics'}, {'TeamNum': 18873, 'OPR': 35.963, 'Auto': 0.617, 'CCWM': 1.953, 'TeamName': 'Lawrence County High School'}, {'TeamNum': 9912, 'OPR': 31.22, 'Auto': 16.594, 'CCWM': 0.776, 'TeamName': 'LadyBots'}, {'TeamNum': 16811, 'OPR': 29.407, 'Auto': -0.806, 'CCWM': 12.076, 'TeamName': 'MAGNETUDE BLACK'}, {'TeamNum': 21673, 'OPR': 21.6, 'Auto': 4.647, 'CCWM': -9.01, 'TeamName': 'Cordova Eagles'}, {'TeamNum': 18687, 'OPR': 21.591, 'Auto': -4.572, 'CCWM': -16.545, 'TeamName': 'SoKno Robo Junior '}, {'TeamNum': 18714, 'OPR': 18.953, 'Auto': 2.518, 'CCWM': -39.153, 'TeamName': 'Lawson Green Lightning'}, {'TeamNum': 22449, 'OPR': 16.695, 'Auto': -2.9, 'CCWM': -13.696, 'TeamName': 'Ministry of Mechanics'}, {'TeamNum': 21530, 'OPR': 15.22, 'Auto': -0.925, 'CCWM': -53.537, 'TeamName': 'Techalorians'}, {'TeamNum': 16885, 'OPR': 12.695, 'Auto': 10.249, 'CCWM': -15.756, 'TeamName': 'Whites Creek'}, {'TeamNum': 7783, 'OPR': 9.711, 'Auto': -1.466, 'CCWM': -70.169, 'TeamName': 'Electric Wave'}, {'TeamNum': 18909, 'OPR': 6.376, 'Auto': 6.944, 'CCWM': -6.111, 'TeamName': 'Loretto High School'}, {'TeamNum': 4949, 'OPR': 0.61, 'Auto': 2.165, 'CCWM': -21.405, 'TeamName': 'Warriors'}, {'TeamNum': 18832, 'OPR': -8.355, 'Auto': -1.916, 'CCWM': -56.497, 'TeamName': 'Burro Bots'}]
USTNCMP
[{'TeamNum': 6073, 'OPR': 106.641, 'Auto': 14.66, 'CCWM': 66.984, 'TeamName': 'MUS Robotics'}, {'TeamNum': 12611, 'OPR': 93.178, 'Auto': 28.198, 'CCWM': 61.57, 'TeamName': 'TechNova'}, {'TeamNum': 14491, 'OPR': 90.245, 'Auto': 34.66, 'CCWM': 32.172, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 20694, 'OPR': 77.923, 'Auto': 12.391, 'CCWM': 68.17, 'TeamName': 'Craft Coalition '}, {'TeamNum': 11279, 'OPR': 68.625, 'Auto': -0.052, 'CCWM': 3.906, 'TeamName': 'Pure Imagination'}, {'TeamNum': 10391, 'OPR': 67.096, 'Auto': 11.74, 'CCWM': 66.894, 'TeamName': 'Lynx Robotics'}, {'TeamNum': 9934, 'OPR': 64.379, 'Auto': 3.694, 'CCWM': 12.703, 'TeamName': 'Webb Robotics - FTC'}, {'TeamNum': 8411, 'OPR': 63.42, 'Auto': 8.46, 'CCWM': -2.723, 'TeamName': 'SHARP'}, {'TeamNum': 11468, 'OPR': 52.346, 'Auto': 25.537, 'CCWM': 32.212, 'TeamName': 'Ohm Raiders'}, {'TeamNum': 18689, 'OPR': 48.042, 'Auto': 18.691, 'CCWM': 7.713, 'TeamName': '4-H Gear Grinders'}, {'TeamNum': 19989, 'OPR': 47.924, 'Auto': 1.584, 'CCWM': 25.472, 'TeamName': 'Wings of Steel'}, {'TeamNum': 21457, 'OPR': 47.704, 'Auto': 6.678, 'CCWM': -1.04, 'TeamName': 'Tennessine Titans '}, {'TeamNum': 17108, 'OPR': 44.899, 'Auto': 3.532, 'CCWM': -51.04, 'TeamName': 'MAGNETUDE GOLD'}, {'TeamNum': 11161, 'OPR': 44.253, 'Auto': 2.9, 'CCWM': -12.499, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 21461, 'OPR': 41.89, 'Auto': 3.229, 'CCWM': 12.195, 'TeamName': 'TriCities Youth Robotics'}, {'TeamNum': 14291, 'OPR': 41.546, 'Auto': 4.743, 'CCWM': -37.894, 'TeamName': 'Small Town Robotics'}, {'TeamNum': 18873, 'OPR': 35.963, 'Auto': 0.617, 'CCWM': 1.953, 'TeamName': 'Lawrence County High School'}, {'TeamNum': 9912, 'OPR': 31.22, 'Auto': 16.594, 'CCWM': 0.776, 'TeamName': 'LadyBots'}, {'TeamNum': 16811, 'OPR': 29.407, 'Auto': -0.806, 'CCWM': 12.076, 'TeamName': 'MAGNETUDE BLACK'}, {'TeamNum': 21673, 'OPR': 21.6, 'Auto': 4.647, 'CCWM': -9.01, 'TeamName': 'Cordova Eagles'}, {'TeamNum': 18687, 'OPR': 21.591, 'Auto': -4.572, 'CCWM': -16.545, 'TeamName': 'SoKno Robo Junior '}, {'TeamNum': 18714, 'OPR': 18.953, 'Auto': 2.518, 'CCWM': -39.153, 'TeamName': 'Lawson Green Lightning'}, {'TeamNum': 22449, 'OPR': 16.695, 'Auto': -2.9, 'CCWM': -13.696, 'TeamName': 'Ministry of Mechanics'}, {'TeamNum': 21530, 'OPR': 15.22, 'Auto': -0.925, 'CCWM': -53.537, 'TeamName': 'Techalorians'}, {'TeamNum': 16885, 'OPR': 12.695, 'Auto': 10.249, 'CCWM': -15.756, 'TeamName': 'Whites Creek'}, {'TeamNum': 7783, 'OPR': 9.711, 'Auto': -1.466, 'CCWM': -70.169, 'TeamName': 'Electric Wave'}, {'TeamNum': 18909, 'OPR': 6.376, 'Auto': 6.944, 'CCWM': -6.111, 'TeamName': 'Loretto High School'}, {'TeamNum': 4949, 'OPR': 0.61, 'Auto': 2.165, 'CCWM': -21.405, 'TeamName': 'Warriors'}, {'TeamNum': 18832, 'OPR': -8.355, 'Auto': -1.916, 'CCWM': -56.497, 'TeamName': 'Burro Bots'}]
i 1052
{'22393', '22713', '22133', '22176', '22745', '22714', '22744', '5175', '22852', '22853', '21338', '18514', '10405', '22170'}
[{'TeamNum': 18514, 'OPR': 44.522, 'Auto': 12.632, 'CCWM': 34.962, 'TeamName': 'STORM Masters'}, {'TeamNum': 22393, 'OPR': 40.316, 'Auto': 21.578, 'CCWM': 23.874, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 10405, 'OPR': 39.185, 'Auto': 10.06, 'CCWM': 20.508, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 29.579, 'Auto': 7.394, 'CCWM': 19.011, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22176, 'OPR': 24.933, 'Auto': 7.5, 'CCWM': -2.067, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22170, 'OPR': 18.161, 'Auto': 8.356, 'CCWM': -13.069, 'TeamName': 'JDT'}, {'TeamNum': 22714, 'OPR': 17.936, 'Auto': -0.044, 'CCWM': -2.754, 'TeamName': 'The Scanners'}, {'TeamNum': 22745, 'OPR': 15.484, 'Auto': -0.112, 'CCWM': 0.473, 'TeamName': 'Jack Bots'}, {'TeamNum': 21338, 'OPR': 14.356, 'Auto': 1.486, 'CCWM': 9.882, 'TeamName': 'Innovators'}, {'TeamNum': 22744, 'OPR': 12.372, 'Auto': 5.584, 'CCWM': -6.738, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 22133, 'OPR': 7.186, 'Auto': 3.584, 'CCWM': -2.526, 'TeamName': 'Infinity'}, {'TeamNum': 22713, 'OPR': 1.686, 'Auto': -4.184, 'CCWM': -18.482, 'TeamName': 'Bubble Bots'}, {'TeamNum': 22853, 'OPR': -0.221, 'Auto': 3.014, 'CCWM': -29.7, 'TeamName': 'Falconers'}, {'TeamNum': 22852, 'OPR': -10.282, 'Auto': -4.023, 'CCWM': -39.151, 'TeamName': 'RoboFalcons'}]
USTXHOELLT1
[{'TeamNum': 18514, 'OPR': 44.522, 'Auto': 12.632, 'CCWM': 34.962, 'TeamName': 'STORM Masters'}, {'TeamNum': 22393, 'OPR': 40.316, 'Auto': 21.578, 'CCWM': 23.874, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 10405, 'OPR': 39.185, 'Auto': 10.06, 'CCWM': 20.508, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 29.579, 'Auto': 7.394, 'CCWM': 19.011, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22176, 'OPR': 24.933, 'Auto': 7.5, 'CCWM': -2.067, 'TeamName': 'Team Overdrive'}, {'TeamNum': 22170, 'OPR': 18.161, 'Auto': 8.356, 'CCWM': -13.069, 'TeamName': 'JDT'}, {'TeamNum': 22714, 'OPR': 17.936, 'Auto': -0.044, 'CCWM': -2.754, 'TeamName': 'The Scanners'}, {'TeamNum': 22745, 'OPR': 15.484, 'Auto': -0.112, 'CCWM': 0.473, 'TeamName': 'Jack Bots'}, {'TeamNum': 21338, 'OPR': 14.356, 'Auto': 1.486, 'CCWM': 9.882, 'TeamName': 'Innovators'}, {'TeamNum': 22744, 'OPR': 12.372, 'Auto': 5.584, 'CCWM': -6.738, 'TeamName': 'Channelview Blitz'}, {'TeamNum': 22133, 'OPR': 7.186, 'Auto': 3.584, 'CCWM': -2.526, 'TeamName': 'Infinity'}, {'TeamNum': 22713, 'OPR': 1.686, 'Auto': -4.184, 'CCWM': -18.482, 'TeamName': 'Bubble Bots'}, {'TeamNum': 22853, 'OPR': -0.221, 'Auto': 3.014, 'CCWM': -29.7, 'TeamName': 'Falconers'}, {'TeamNum': 22852, 'OPR': -10.282, 'Auto': -4.023, 'CCWM': -39.151, 'TeamName': 'RoboFalcons'}]
i 1053

{'16163', '19502', '12209', '17426', '15661', '21436', '19572', '19891', '18140', '21693', '21479', '12218', '14714'}
[{'TeamNum': 19502, 'OPR': 109.745, 'Auto': 24.223, 'CCWM': 82.257, 'TeamName': 'The Moment Makers'}, {'TeamNum': 18140, 'OPR': 94.078, 'Auto': 24.58, 'CCWM': 37.249, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 19572, 'OPR': 73.48, 'Auto': 19.304, 'CCWM': 51.129, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 21479, 'OPR': 70.745, 'Auto': 16.349, 'CCWM': 24.128, 'TeamName': 'RoboDogs'}, {'TeamNum': 12218, 'OPR': 55.003, 'Auto': 20.353, 'CCWM': 2.878, 'TeamName': 'Horsepower'}, {'TeamNum': 12209, 'OPR': 47.729, 'Auto': 20.595, 'CCWM': 20.602, 'TeamName': 'Blue Steel'}, {'TeamNum': 19891, 'OPR': 40.758, 'Auto': 21.945, 'CCWM': 21.842, 'TeamName': 'Pioneer 2'}, {'TeamNum': 21693, 'OPR': 40.497, 'Auto': 16.239, 'CCWM': -16.561, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 21436, 'OPR': 35.589, 'Auto': 16.945, 'CCWM': -6.625, 'TeamName': 'Pioneers3'}, {'TeamNum': 17426, 'OPR': 14.491, 'Auto': -8.396, 'CCWM': -68.044, 'TeamName': 'Rustangs'}, {'TeamNum': 15661, 'OPR': 12.545, 'Auto': 5.254, 'CCWM': -38.781, 'TeamName': 'Pear-lettes'}, {'TeamNum': 16163, 'OPR': 11.27, 'Auto': -0.999, 'CCWM': -44.57, 'TeamName': 'Pioneers 1'}, {'TeamNum': 14714, 'OPR': 2.722, 'Auto': -10.147, 'CCWM': -52.951, 'TeamName': 'Pear-O-Botics'}]
USTXHOSELLT1
[{'TeamNum': 19502, 'OPR': 109.745, 'Auto': 24.223, 'CCWM': 82.257, 'TeamName': 'The Moment Makers'}, {'TeamNum': 18140, 'OPR': 94.078, 'Auto': 24.58, 'CCWM': 37.249, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 19572, 'OPR': 73.48, 'Auto': 19.304, 'CCWM': 51.129, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 21479, 'OPR': 70.745, 'Auto': 16.349, 'CCWM': 24.128, 'TeamName': 'RoboDogs'}, {'TeamNum': 12218, 'OPR': 55.003, 'Auto': 20.353, 'CCWM': 2.878, 'TeamName': 'Horsepower'}, {'TeamNum': 12209, 'OPR': 47.729, 'Auto': 20.595, 'CCWM': 20.602, 'TeamName': 'Blue Steel'}, {'TeamNum': 19891, 'OPR': 40.758, 'Auto': 21.945, 'CCWM': 21.842, 'TeamName': 'Pioneer 2'}, {'TeamNum': 21693, 'OPR': 40.497, 'Auto': 16.239, 'CCWM': -16.561, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 21436, 'OPR': 35.589, 'Auto': 16.945, 'CCWM': -6.625, 'TeamName': 'Pioneers3'}, {'TeamNum': 17426, 'OPR': 14.491, 'Auto': -8.396, 'CCWM': -68.044, 'TeamName': 'Rustangs'}, {'TeamNum': 15661, 'OPR': 12.545, 'Auto': 5.254, 'CCWM': -38.781, 'TeamName': 'Pear-lettes'}, {'TeamNum': 16163, 'OPR': 11.27, 'Auto': -0.999, 'CCWM': -44.57, 'TeamName': 'Pioneers 1'}, {'TeamNum': 14714, 'OPR': 2.722, 'Auto': -10.147, 'CCWM': -52.951, 'TeamName': 'Pear-O-Botics'}]
i 1054
{'8080', '18071', '8790', '14785', '10064', '4454', '20000', '22058', '22336', '6455', '21962', '9840'}
[{'TeamNum': 18071, 'OPR': 77.623, 'Auto': 21.38, 'CCWM': 55.958, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 9840, 'OPR': 59.578, 'Auto': 10.567, 'CCWM': 9.51, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 59.07, 'Auto': 9.663, 'CCWM': 22.482, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 14785, 'OPR': 47.752, 'Auto': 12.157, 'CCWM': 4.802, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 4454, 'OPR': 46.809, 'Auto': 7.288, 'CCWM': -4.796, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 8080, 'OPR': 43.9, 'Auto': 14.516, 'CCWM': 5.287, 'TeamName': 'Ironclad'}, {'TeamNum': 22058, 'OPR': 39.191, 'Auto': -4.01, 'CCWM': 32.701, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 6455, 'OPR': 36.653, 'Auto': 16.656, 'CCWM': 0.902, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 20000, 'OPR': 31.962, 'Auto': 0.901, 'CCWM': -18.772, 'TeamName': 'Park Bots'}, {'TeamNum': 22336, 'OPR': 23.466, 'Auto': 12.591, 'CCWM': -36.528, 'TeamName': 'Steel Circuits'}, {'TeamNum': 8790, 'OPR': 6.743, 'Auto': -3.219, 'CCWM': -33.214, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 10064, 'OPR': 3.851, 'Auto': 5.91, 'CCWM': -38.331, 'TeamName': 'Lady Gears'}]
USTXHOWLLT
[{'TeamNum': 18071, 'OPR': 77.623, 'Auto': 21.38, 'CCWM': 55.958, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 9840, 'OPR': 59.578, 'Auto': 10.567, 'CCWM': 9.51, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21962, 'OPR': 59.07, 'Auto': 9.663, 'CCWM': 22.482, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 14785, 'OPR': 47.752, 'Auto': 12.157, 'CCWM': 4.802, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 4454, 'OPR': 46.809, 'Auto': 7.288, 'CCWM': -4.796, 'TeamName': 'Mohawk Warriors Green'}, {'TeamNum': 8080, 'OPR': 43.9, 'Auto': 14.516, 'CCWM': 5.287, 'TeamName': 'Ironclad'}, {'TeamNum': 22058, 'OPR': 39.191, 'Auto': -4.01, 'CCWM': 32.701, 'TeamName': 'The G.O.A.Ts'}, {'TeamNum': 6455, 'OPR': 36.653, 'Auto': 16.656, 'CCWM': 0.902, 'TeamName': 'MoHawk Warriors Red'}, {'TeamNum': 20000, 'OPR': 31.962, 'Auto': 0.901, 'CCWM': -18.772, 'TeamName': 'Park Bots'}, {'TeamNum': 22336, 'OPR': 23.466, 'Auto': 12.591, 'CCWM': -36.528, 'TeamName': 'Steel Circuits'}, {'TeamNum': 8790, 'OPR': 6.743, 'Auto': -3.219, 'CCWM': -33.214, 'TeamName': 'Mohawk Warriors Purple'}, {'TeamNum': 10064, 'OPR': 3.851, 'Auto': 5.91, 'CCWM': -38.331, 'TeamName': 'Lady Gears'}]
i 1055
{'10752', '12846', '17318', '21891', '14069', '16930', '10963', '21890', '16816'}
[{'TeamNum': 16930, 'OPR': 115.595, 'Auto': 39.348, 'CCWM': 110.925, 'TeamName': 'Omen'}, {'TeamNum': 21890, 'OPR': 97.746, 'Auto': 31.048, 'CCWM': 90.636, 'TeamName': "St. John's Robotics"}, {'TeamNum': 14069, 'OPR': 66.879, 'Auto': 11.055, 'CCWM': 41.951, 'TeamName': 'KnightBots'}, {'TeamNum': 21891, 'OPR': 48.718, 'Auto': 10.48, 'CCWM': -6.853, 'TeamName': 'Glowbotics'}, {'TeamNum': 12846, 'OPR': 22.056, 'Auto': 7.508, 'CCWM': 15.972, 'TeamName': 'Dynamic Gears'}, {'TeamNum': 17318, 'OPR': 5.336, 'Auto': 1.199, 'CCWM': -31.346, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 10963, 'OPR': -0.087, 'Auto': -4.348, 'CCWM': -45.724, 'TeamName': ' KI Falcons'}, {'TeamNum': 16816, 'OPR': -1.291, 'Auto': -0.919, 'CCWM': -87.184, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 10752, 'OPR': -10.956, 'Auto': -6.952, 'CCWM': -91.756, 'TeamName': 'The Power Rangers'}]
USTXHOCLLT
[{'TeamNum': 16930, 'OPR': 115.595, 'Auto': 39.348, 'CCWM': 110.925, 'TeamName': 'Omen'}, {'TeamNum': 21890, 'OPR': 97.746, 'Auto': 31.048, 'CCWM': 90.636, 'TeamName': "St. John's Robotics"}, {'TeamNum': 14069, 'OPR': 66.879, 'Auto': 11.055, 'CCWM': 41.951, 'TeamName': 'KnightBots'}, {'TeamNum': 21891, 'OPR': 48.718, 'Auto': 10.48, 'CCWM': -6.853, 'TeamName': 'Glowbotics'}, {'TeamNum': 12846, 'OPR': 22.056, 'Auto': 7.508, 'CCWM': 15.972, 'TeamName': 'Dynamic Gears'}, {'TeamNum': 17318, 'OPR': 5.336, 'Auto': 1.199, 'CCWM': -31.346, 'TeamName': 'Tech-Hawks'}, {'TeamNum': 10963, 'OPR': -0.087, 'Auto': -4.348, 'CCWM': -45.724, 'TeamName': ' KI Falcons'}, {'TeamNum': 16816, 'OPR': -1.291, 'Auto': -0.919, 'CCWM': -87.184, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 10752, 'OPR': -10.956, 'Auto': -6.952, 'CCWM': -91.756, 'TeamName': 'The Power Rangers'}]
i 1056
{'6210', '20741', '7079', '16556', '22563', '11093', '13893', '5189', '5188', '22057', '22541', '13833', '15024', '16828', '4602', '13895', '8203', '18886', '4008', '11924', '13388', '21375', '6976', '13896', '13266', '10632', '18458', '8295', '6209', '12563', '16831', '17113', '15725', '13053'}
[{'TeamNum': 11093, 'OPR': 121.634, 'Auto': 28.675, 'CCWM': 105.96, 'TeamName': 'MegaKnytes'}, {'TeamNum': 7079, 'OPR': 108.897, 'Auto': 24.841, 'CCWM': 40.27, 'TeamName': 'FalTech'}, {'TeamNum': 13053, 'OPR': 101.218, 'Auto': 34.012, 'CCWM': 54.558, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 22057, 'OPR': 95.748, 'Auto': 28.84, 'CCWM': 69.029, 'TeamName': 'The Prototypes'}, {'TeamNum': 18458, 'OPR': 86.872, 'Auto': 4.1, 'CCWM': 15.6, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 15725, 'OPR': 85.381, 'Auto': 12.667, 'CCWM': 7.38, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 13266, 'OPR': 76.322, 'Auto': 12.81, 'CCWM': 17.299, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 20741, 'OPR': 75.562, 'Auto': 8.828, 'CCWM': 25.636, 'TeamName': 'Checkmate'}, {'TeamNum': 11924, 'OPR': 73.15, 'Auto': 0.316, 'CCWM': 22.31, 'TeamName': 'Martin Robots'}, {'TeamNum': 6210, 'OPR': 71.877, 'Auto': 7.082, 'CCWM': 46.78, 'TeamName': 'ViperBots  Stryke'}, {'TeamNum': 8203, 'OPR': 70.393, 'Auto': 22.779, 'CCWM': 24.174, 'TeamName': "Lil' Gibbies"}, {'TeamNum': 6976, 'OPR': 69.733, 'Auto': 18.332, 'CCWM': -34.892, 'TeamName': 'Bronc Botz '}, {'TeamNum': 15024, 'OPR': 63.746, 'Auto': 15.957, 'CCWM': -16.105, 'TeamName': 'Cougarbots Bravo'}, {'TeamNum': 16556, 'OPR': 61.45, 'Auto': 10.442, 'CCWM': 34.831, 'TeamName': 'Steminists'}, {'TeamNum': 17113, 'OPR': 59.261, 'Auto': 12.224, 'CCWM': 3.04, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 4602, 'OPR': 48.831, 'Auto': 9.667, 'CCWM': -33.271, 'TeamName': 'Bronc Botz - Prometheus'}, {'TeamNum': 6209, 'OPR': 46.794, 'Auto': 8.075, 'CCWM': -24.799, 'TeamName': 'ViperBots Venom'}, {'TeamNum': 13388, 'OPR': 42.701, 'Auto': 8.533, 'CCWM': -1.563, 'TeamName': 'Warrior Warheads'}, {'TeamNum': 18886, 'OPR': 42.247, 'Auto': 5.829, 'CCWM': 0.721, 'TeamName': 'Westwood Atlatl'}, {'TeamNum': 10632, 'OPR': 33.91, 'Auto': 1.808, 'CCWM': -19.92, 'TeamName': 'JECA RoboRaptors'}, {'TeamNum': 21375, 'OPR': 33.385, 'Auto': 18.979, 'CCWM': -64.937, 'TeamName': 'YGGDRASIL ROBOTICS'}, {'TeamNum': 16828, 'OPR': 33.363, 'Auto': 10.126, 'CCWM': -49.413, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 13833, 'OPR': 32.374, 'Auto': -4.158, 'CCWM': 20.371, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 22563, 'OPR': 31.117, 'Auto': 6.571, 'CCWM': -60.506, 'TeamName': 'BOTS OF STEELE'}, {'TeamNum': 5188, 'OPR': 30.327, 'Auto': 6.704, 'CCWM': 6.651, 'TeamName': 'Team Phoenix'}, {'TeamNum': 5189, 'OPR': 28.046, 'Auto': 1.268, 'CCWM': 24.161, 'TeamName': 'Team Wolves'}, {'TeamNum': 4008, 'OPR': 25.38, 'Auto': 4.457, 'CCWM': -14.756, 'TeamName': 'Bronc Botz - Atlas'}, {'TeamNum': 12563, 'OPR': 20.924, 'Auto': 9.411, 'CCWM': -48.022, 'TeamName': 'Bots of Glory'}, {'TeamNum': 16831, 'OPR': 20.886, 'Auto': 2.793, 'CCWM': -9.079, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 8295, 'OPR': 19.971, 'Auto': -1.472, 'CCWM': -57.642, 'TeamName': 'Baron Alpha'}, {'TeamNum': 22541, 'OPR': 19.396, 'Auto': -1.237, 'CCWM': 5.045, 'TeamName': 'Ram Jamz'}, {'TeamNum': 13893, 'OPR': 11.835, 'Auto': -4.527, 'CCWM': -8.522, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 13896, 'OPR': 7.755, 'Auto': 5.724, 'CCWM': -18.414, 'TeamName': 'Team Battle Stallions'}, {'TeamNum': 13895, 'OPR': 2.705, 'Auto': 3.473, 'CCWM': -65.122, 'TeamName': 'Team LiveWire'}]
USTXCEPOSQ
[{'TeamNum': 11093, 'OPR': 121.634, 'Auto': 28.675, 'CCWM': 105.96, 'TeamName': 'MegaKnytes'}, {'TeamNum': 7079, 'OPR': 108.897, 'Auto': 24.841, 'CCWM': 40.27, 'TeamName': 'FalTech'}, {'TeamNum': 13053, 'OPR': 101.218, 'Auto': 34.012, 'CCWM': 54.558, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 22057, 'OPR': 95.748, 'Auto': 28.84, 'CCWM': 69.029, 'TeamName': 'The Prototypes'}, {'TeamNum': 18458, 'OPR': 86.872, 'Auto': 4.1, 'CCWM': 15.6, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 15725, 'OPR': 85.381, 'Auto': 12.667, 'CCWM': 7.38, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 13266, 'OPR': 76.322, 'Auto': 12.81, 'CCWM': 17.299, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 20741, 'OPR': 75.562, 'Auto': 8.828, 'CCWM': 25.636, 'TeamName': 'Checkmate'}, {'TeamNum': 11924, 'OPR': 73.15, 'Auto': 0.316, 'CCWM': 22.31, 'TeamName': 'Martin Robots'}, {'TeamNum': 6210, 'OPR': 71.877, 'Auto': 7.082, 'CCWM': 46.78, 'TeamName': 'ViperBots  Stryke'}, {'TeamNum': 8203, 'OPR': 70.393, 'Auto': 22.779, 'CCWM': 24.174, 'TeamName': "Lil' Gibbies"}, {'TeamNum': 6976, 'OPR': 69.733, 'Auto': 18.332, 'CCWM': -34.892, 'TeamName': 'Bronc Botz '}, {'TeamNum': 15024, 'OPR': 63.746, 'Auto': 15.957, 'CCWM': -16.105, 'TeamName': 'Cougarbots Bravo'}, {'TeamNum': 16556, 'OPR': 61.45, 'Auto': 10.442, 'CCWM': 34.831, 'TeamName': 'Steminists'}, {'TeamNum': 17113, 'OPR': 59.261, 'Auto': 12.224, 'CCWM': 3.04, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 4602, 'OPR': 48.831, 'Auto': 9.667, 'CCWM': -33.271, 'TeamName': 'Bronc Botz - Prometheus'}, {'TeamNum': 6209, 'OPR': 46.794, 'Auto': 8.075, 'CCWM': -24.799, 'TeamName': 'ViperBots Venom'}, {'TeamNum': 13388, 'OPR': 42.701, 'Auto': 8.533, 'CCWM': -1.563, 'TeamName': 'Warrior Warheads'}, {'TeamNum': 18886, 'OPR': 42.247, 'Auto': 5.829, 'CCWM': 0.721, 'TeamName': 'Westwood Atlatl'}, {'TeamNum': 10632, 'OPR': 33.91, 'Auto': 1.808, 'CCWM': -19.92, 'TeamName': 'JECA RoboRaptors'}, {'TeamNum': 21375, 'OPR': 33.385, 'Auto': 18.979, 'CCWM': -64.937, 'TeamName': 'YGGDRASIL ROBOTICS'}, {'TeamNum': 16828, 'OPR': 33.363, 'Auto': 10.126, 'CCWM': -49.413, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 13833, 'OPR': 32.374, 'Auto': -4.158, 'CCWM': 20.371, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 22563, 'OPR': 31.117, 'Auto': 6.571, 'CCWM': -60.506, 'TeamName': 'BOTS OF STEELE'}, {'TeamNum': 5188, 'OPR': 30.327, 'Auto': 6.704, 'CCWM': 6.651, 'TeamName': 'Team Phoenix'}, {'TeamNum': 5189, 'OPR': 28.046, 'Auto': 1.268, 'CCWM': 24.161, 'TeamName': 'Team Wolves'}, {'TeamNum': 4008, 'OPR': 25.38, 'Auto': 4.457, 'CCWM': -14.756, 'TeamName': 'Bronc Botz - Atlas'}, {'TeamNum': 12563, 'OPR': 20.924, 'Auto': 9.411, 'CCWM': -48.022, 'TeamName': 'Bots of Glory'}, {'TeamNum': 16831, 'OPR': 20.886, 'Auto': 2.793, 'CCWM': -9.079, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 8295, 'OPR': 19.971, 'Auto': -1.472, 'CCWM': -57.642, 'TeamName': 'Baron Alpha'}, {'TeamNum': 22541, 'OPR': 19.396, 'Auto': -1.237, 'CCWM': 5.045, 'TeamName': 'Ram Jamz'}, {'TeamNum': 13893, 'OPR': 11.835, 'Auto': -4.527, 'CCWM': -8.522, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 13896, 'OPR': 7.755, 'Auto': 5.724, 'CCWM': -18.414, 'TeamName': 'Team Battle Stallions'}, {'TeamNum': 13895, 'OPR': 2.705, 'Auto': 3.473, 'CCWM': -65.122, 'TeamName': 'Team LiveWire'}]

i 1057
{'20249', '19947', '22895', '14482', '11947', '10055', '22236', '13822', '21386', '22045', '14503', '12456', '22717', '20394', '16685', '10354'}
[{'TeamNum': 14503, 'OPR': 109.779, 'Auto': 30.703, 'CCWM': 78.386, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 10354, 'OPR': 96.295, 'Auto': 29.156, 'CCWM': 45.501, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 20394, 'OPR': 86.546, 'Auto': 9.696, 'CCWM': 66.586, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 22236, 'OPR': 72.385, 'Auto': 9.55, 'CCWM': 61.65, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 19947, 'OPR': 62.13, 'Auto': 10.788, 'CCWM': 44.252, 'TeamName': 'Nano Trojans'}, {'TeamNum': 21386, 'OPR': 49.565, 'Auto': 20.181, 'CCWM': -6.103, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 20249, 'OPR': 40.936, 'Auto': 9.889, 'CCWM': -18.401, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 16685, 'OPR': 37.826, 'Auto': 26.99, 'CCWM': -11.298, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 13822, 'OPR': 32.503, 'Auto': 1.289, 'CCWM': -40.923, 'TeamName': 'RoboVikings'}, {'TeamNum': 22717, 'OPR': 28.498, 'Auto': -4.632, 'CCWM': 5.155, 'TeamName': 'Robotic Radicals'}, {'TeamNum': 22045, 'OPR': 26.19, 'Auto': 6.05, 'CCWM': -48.258, 'TeamName': 'Power Breakers'}, {'TeamNum': 10055, 'OPR': 20.629, 'Auto': 9.438, 'CCWM': -40.303, 'TeamName': 'Momentum'}, {'TeamNum': 12456, 'OPR': 13.342, 'Auto': -0.05, 'CCWM': -17.462, 'TeamName': 'Big Red'}, {'TeamNum': 11947, 'OPR': 8.838, 'Auto': -0.253, 'CCWM': -27.688, 'TeamName': 'Stafford Middle School Spartan Robotics'}, {'TeamNum': 14482, 'OPR': 8.151, 'Auto': 4.236, 'CCWM': -59.499, 'TeamName': 'CRJ Lions 2'}, {'TeamNum': 22895, 'OPR': -0.813, 'Auto': -3.23, 'CCWM': -31.593, 'TeamName': 'RoboLions'}]
USTXHOSWLT1
[{'TeamNum': 14503, 'OPR': 109.779, 'Auto': 30.703, 'CCWM': 78.386, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 10354, 'OPR': 96.295, 'Auto': 29.156, 'CCWM': 45.501, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 20394, 'OPR': 86.546, 'Auto': 9.696, 'CCWM': 66.586, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 22236, 'OPR': 72.385, 'Auto': 9.55, 'CCWM': 61.65, 'TeamName': 'Mustangs 3.0'}, {'TeamNum': 19947, 'OPR': 62.13, 'Auto': 10.788, 'CCWM': 44.252, 'TeamName': 'Nano Trojans'}, {'TeamNum': 21386, 'OPR': 49.565, 'Auto': 20.181, 'CCWM': -6.103, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 20249, 'OPR': 40.936, 'Auto': 9.889, 'CCWM': -18.401, 'TeamName': 'Stafford STEM Academy'}, {'TeamNum': 16685, 'OPR': 37.826, 'Auto': 26.99, 'CCWM': -11.298, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 13822, 'OPR': 32.503, 'Auto': 1.289, 'CCWM': -40.923, 'TeamName': 'RoboVikings'}, {'TeamNum': 22717, 'OPR': 28.498, 'Auto': -4.632, 'CCWM': 5.155, 'TeamName': 'Robotic Radicals'}, {'TeamNum': 22045, 'OPR': 26.19, 'Auto': 6.05, 'CCWM': -48.258, 'TeamName': 'Power Breakers'}, {'TeamNum': 10055, 'OPR': 20.629, 'Auto': 9.438, 'CCWM': -40.303, 'TeamName': 'Momentum'}, {'TeamNum': 12456, 'OPR': 13.342, 'Auto': -0.05, 'CCWM': -17.462, 'TeamName': 'Big Red'}, {'TeamNum': 11947, 'OPR': 8.838, 'Auto': -0.253, 'CCWM': -27.688, 'TeamName': 'Stafford Middle School Spartan Robotics'}, {'TeamNum': 14482, 'OPR': 8.151, 'Auto': 4.236, 'CCWM': -59.499, 'TeamName': 'CRJ Lions 2'}, {'TeamNum': 22895, 'OPR': -0.813, 'Auto': -3.23, 'CCWM': -31.593, 'TeamName': 'RoboLions'}]
i 1058
{'12167', '9511', '22008', '15083', '9403', '12106', '19990', '22674', '21327', '13227', '21965', '14904', '21514', '22547', '8114', '10526', '17294', '19991', '18738', '15878', '16012', '11563', '22077', '22287', '9402', '15084', '21813', '20336', '16090', '20754', '22539', '21870'}
[{'TeamNum': 18738, 'OPR': 95.648, 'Auto': 25.652, 'CCWM': 70.555, 'TeamName': 'Moon Mechanics '}, {'TeamNum': 17294, 'OPR': 74.103, 'Auto': 19.906, 'CCWM': 9.823, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 15083, 'OPR': 73.443, 'Auto': 19.383, 'CCWM': 11.856, 'TeamName': 'Antagonists'}, {'TeamNum': 22008, 'OPR': 72.761, 'Auto': 11.501, 'CCWM': 32.745, 'TeamName': 'Sunset Robotics 3'}, {'TeamNum': 19991, 'OPR': 70.04, 'Auto': 19.448, 'CCWM': 3.576, 'TeamName': 'Chuckleheads'}, {'TeamNum': 9511, 'OPR': 69.013, 'Auto': 18.896, 'CCWM': 0.229, 'TeamName': 'Low Voltage'}, {'TeamNum': 20336, 'OPR': 65.878, 'Auto': 29.02, 'CCWM': 21.628, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 22077, 'OPR': 62.444, 'Auto': 18.995, 'CCWM': 36.647, 'TeamName': 'Marcus Minions'}, {'TeamNum': 12106, 'OPR': 61.595, 'Auto': 14.359, 'CCWM': 26.642, 'TeamName': 'Eagle Apollo'}, {'TeamNum': 13227, 'OPR': 60.388, 'Auto': 16.36, 'CCWM': 21.7, 'TeamName': 'Mechanicats'}, {'TeamNum': 21813, 'OPR': 56.05, 'Auto': 16.662, 'CCWM': 44.311, 'TeamName': 'Pro2type'}, {'TeamNum': 8114, 'OPR': 54.766, 'Auto': 9.852, 'CCWM': 22.302, 'TeamName': 'Lewisville HS'}, {'TeamNum': 21327, 'OPR': 54.59, 'Auto': 17.749, 'CCWM': 9.675, 'TeamName': 'Java Nauts'}, {'TeamNum': 11563, 'OPR': 53.796, 'Auto': 19.769, 'CCWM': 15.184, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 16090, 'OPR': 47.28, 'Auto': 8.827, 'CCWM': 9.843, 'TeamName': 'Robo Eagles'}, {'TeamNum': 21514, 'OPR': 47.225, 'Auto': 23.056, 'CCWM': -11.574, 'TeamName': 'CDA-FMTX-1845'}, {'TeamNum': 22674, 'OPR': 45.269, 'Auto': 23.866, 'CCWM': 17.701, 'TeamName': 'Metal Manipulators'}, {'TeamNum': 21870, 'OPR': 42.539, 'Auto': 3.561, 'CCWM': -19.741, 'TeamName': 'Pro Pythons'}, {'TeamNum': 14904, 'OPR': 42.164, 'Auto': 13.803, 'CCWM': 7.204, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 21965, 'OPR': 41.072, 'Auto': 8.921, 'CCWM': -27.436, 'TeamName': 'Mainframe'}, {'TeamNum': 20754, 'OPR': 40.415, 'Auto': 6.644, 'CCWM': -0.728, 'TeamName': 'Hephaestus'}, {'TeamNum': 19990, 'OPR': 38.52, 'Auto': 15.92, 'CCWM': -22.329, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 22287, 'OPR': 33.109, 'Auto': 22.937, 'CCWM': -30.296, 'TeamName': 'Data Rejected'}, {'TeamNum': 10526, 'OPR': 30.464, 'Auto': 6.354, 'CCWM': -9.567, 'TeamName': 'BA BLACK: µicroBotixs'}, {'TeamNum': 16012, 'OPR': 27.999, 'Auto': 0.646, 'CCWM': -27.173, 'TeamName': 'Blazing Bots'}, {'TeamNum': 15084, 'OPR': 21.093, 'Auto': 4.095, 'CCWM': -12.37, 'TeamName': 'Water Coolers'}, {'TeamNum': 15878, 'OPR': 14.82, 'Auto': -0.102, 'CCWM': -32.224, 'TeamName': 'Braswell Engineering Robotics Team'}, {'TeamNum': 12167, 'OPR': 13.778, 'Auto': 2.132, 'CCWM': -10.044, 'TeamName': 'Husky Robotics'}, {'TeamNum': 22539, 'OPR': 13.495, 'Auto': 1.093, 'CCWM': -8.556, 'TeamName': 'Trial and Error'}, {'TeamNum': 9403, 'OPR': 5.151, 'Auto': 2.273, 'CCWM': -50.78, 'TeamName': 'Hive of Steel'}, {'TeamNum': 9402, 'OPR': 3.445, 'Auto': -3.235, 'CCWM': -62.161, 'TeamName': 'CyberSwarm'}, {'TeamNum': 22547, 'OPR': 2.45, 'Auto': -1.943, 'CCWM': -36.643, 'TeamName': 'The Q Ballz'}]
USTXNOFMQ
[{'TeamNum': 18738, 'OPR': 95.648, 'Auto': 25.652, 'CCWM': 70.555, 'TeamName': 'Moon Mechanics '}, {'TeamNum': 17294, 'OPR': 74.103, 'Auto': 19.906, 'CCWM': 9.823, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 15083, 'OPR': 73.443, 'Auto': 19.383, 'CCWM': 11.856, 'TeamName': 'Antagonists'}, {'TeamNum': 22008, 'OPR': 72.761, 'Auto': 11.501, 'CCWM': 32.745, 'TeamName': 'Sunset Robotics 3'}, {'TeamNum': 19991, 'OPR': 70.04, 'Auto': 19.448, 'CCWM': 3.576, 'TeamName': 'Chuckleheads'}, {'TeamNum': 9511, 'OPR': 69.013, 'Auto': 18.896, 'CCWM': 0.229, 'TeamName': 'Low Voltage'}, {'TeamNum': 20336, 'OPR': 65.878, 'Auto': 29.02, 'CCWM': 21.628, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 22077, 'OPR': 62.444, 'Auto': 18.995, 'CCWM': 36.647, 'TeamName': 'Marcus Minions'}, {'TeamNum': 12106, 'OPR': 61.595, 'Auto': 14.359, 'CCWM': 26.642, 'TeamName': 'Eagle Apollo'}, {'TeamNum': 13227, 'OPR': 60.388, 'Auto': 16.36, 'CCWM': 21.7, 'TeamName': 'Mechanicats'}, {'TeamNum': 21813, 'OPR': 56.05, 'Auto': 16.662, 'CCWM': 44.311, 'TeamName': 'Pro2type'}, {'TeamNum': 8114, 'OPR': 54.766, 'Auto': 9.852, 'CCWM': 22.302, 'TeamName': 'Lewisville HS'}, {'TeamNum': 21327, 'OPR': 54.59, 'Auto': 17.749, 'CCWM': 9.675, 'TeamName': 'Java Nauts'}, {'TeamNum': 11563, 'OPR': 53.796, 'Auto': 19.769, 'CCWM': 15.184, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 16090, 'OPR': 47.28, 'Auto': 8.827, 'CCWM': 9.843, 'TeamName': 'Robo Eagles'}, {'TeamNum': 21514, 'OPR': 47.225, 'Auto': 23.056, 'CCWM': -11.574, 'TeamName': 'CDA-FMTX-1845'}, {'TeamNum': 22674, 'OPR': 45.269, 'Auto': 23.866, 'CCWM': 17.701, 'TeamName': 'Metal Manipulators'}, {'TeamNum': 21870, 'OPR': 42.539, 'Auto': 3.561, 'CCWM': -19.741, 'TeamName': 'Pro Pythons'}, {'TeamNum': 14904, 'OPR': 42.164, 'Auto': 13.803, 'CCWM': 7.204, 'TeamName': 'Lakehill Bionicles'}, {'TeamNum': 21965, 'OPR': 41.072, 'Auto': 8.921, 'CCWM': -27.436, 'TeamName': 'Mainframe'}, {'TeamNum': 20754, 'OPR': 40.415, 'Auto': 6.644, 'CCWM': -0.728, 'TeamName': 'Hephaestus'}, {'TeamNum': 19990, 'OPR': 38.52, 'Auto': 15.92, 'CCWM': -22.329, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 22287, 'OPR': 33.109, 'Auto': 22.937, 'CCWM': -30.296, 'TeamName': 'Data Rejected'}, {'TeamNum': 10526, 'OPR': 30.464, 'Auto': 6.354, 'CCWM': -9.567, 'TeamName': 'BA BLACK: µicroBotixs'}, {'TeamNum': 16012, 'OPR': 27.999, 'Auto': 0.646, 'CCWM': -27.173, 'TeamName': 'Blazing Bots'}, {'TeamNum': 15084, 'OPR': 21.093, 'Auto': 4.095, 'CCWM': -12.37, 'TeamName': 'Water Coolers'}, {'TeamNum': 15878, 'OPR': 14.82, 'Auto': -0.102, 'CCWM': -32.224, 'TeamName': 'Braswell Engineering Robotics Team'}, {'TeamNum': 12167, 'OPR': 13.778, 'Auto': 2.132, 'CCWM': -10.044, 'TeamName': 'Husky Robotics'}, {'TeamNum': 22539, 'OPR': 13.495, 'Auto': 1.093, 'CCWM': -8.556, 'TeamName': 'Trial and Error'}, {'TeamNum': 9403, 'OPR': 5.151, 'Auto': 2.273, 'CCWM': -50.78, 'TeamName': 'Hive of Steel'}, {'TeamNum': 9402, 'OPR': 3.445, 'Auto': -3.235, 'CCWM': -62.161, 'TeamName': 'CyberSwarm'}, {'TeamNum': 22547, 'OPR': 2.45, 'Auto': -1.943, 'CCWM': -36.643, 'TeamName': 'The Q Ballz'}]

i 1059
{'12825', '17324', '15021', '12978', '16910', '16911', '20258', '18064', '21304', '12857', '16909', '9191', '16912', '21722', '21843', '22129', '18065', '18861'}
[{'TeamNum': 16909, 'OPR': 96.235, 'Auto': 24.734, 'CCWM': 21.489, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 12978, 'OPR': 88.318, 'Auto': 27.862, 'CCWM': 54.945, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 12857, 'OPR': 82.869, 'Auto': 29.446, 'CCWM': 35.673, 'TeamName': 'Phantom'}, {'TeamNum': 16911, 'OPR': 81.849, 'Auto': 25.852, 'CCWM': 5.083, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 18064, 'OPR': 71.166, 'Auto': 24.387, 'CCWM': -6.16, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 16912, 'OPR': 71.121, 'Auto': 20.536, 'CCWM': -15.543, 'TeamName': 'Linguine Pastabots'}, {'TeamNum': 17324, 'OPR': 68.699, 'Auto': 10.476, 'CCWM': 26.247, 'TeamName': 'Green Machines'}, {'TeamNum': 16910, 'OPR': 66.436, 'Auto': 13.706, 'CCWM': 23.102, 'TeamName': 'Spaghetti Pastabots'}, {'TeamNum': 18861, 'OPR': 65.523, 'Auto': 20.169, 'CCWM': 29.648, 'TeamName': 'Wasted Potential Energy'}, {'TeamNum': 9191, 'OPR': 60.314, 'Auto': 12.826, 'CCWM': 3.626, 'TeamName': 'Beta Testers'}, {'TeamNum': 15021, 'OPR': 55.339, 'Auto': 19.132, 'CCWM': 7.668, 'TeamName': 'Ravioli Pastabots'}, {'TeamNum': 18065, 'OPR': 54.201, 'Auto': 7.844, 'CCWM': 12.922, 'TeamName': 'Repeat Error'}, {'TeamNum': 21843, 'OPR': 53.454, 'Auto': 9.668, 'CCWM': -12.69, 'TeamName': 'Prowler Robotics'}, {'TeamNum': 21722, 'OPR': 45.451, 'Auto': 12.765, 'CCWM': -30.726, 'TeamName': 'Macaroni Pastabots'}, {'TeamNum': 12825, 'OPR': 36.938, 'Auto': 12.498, 'CCWM': -42.505, 'TeamName': 'Wildkat Robotiks FTC'}, {'TeamNum': 20258, 'OPR': 29.662, 'Auto': 8.183, 'CCWM': -4.02, 'TeamName': 'Mind Bombs'}, {'TeamNum': 21304, 'OPR': 11.793, 'Auto': -3.161, 'CCWM': -49.435, 'TeamName': 'Tiger Robotics'}, {'TeamNum': 22129, 'OPR': 8.758, 'Auto': 0.032, 'CCWM': -60.675, 'TeamName': 'System Error'}]
USTXHONLLT1
[{'TeamNum': 16909, 'OPR': 96.235, 'Auto': 24.734, 'CCWM': 21.489, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 12978, 'OPR': 88.318, 'Auto': 27.862, 'CCWM': 54.945, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 12857, 'OPR': 82.869, 'Auto': 29.446, 'CCWM': 35.673, 'TeamName': 'Phantom'}, {'TeamNum': 16911, 'OPR': 81.849, 'Auto': 25.852, 'CCWM': 5.083, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 18064, 'OPR': 71.166, 'Auto': 24.387, 'CCWM': -6.16, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 16912, 'OPR': 71.121, 'Auto': 20.536, 'CCWM': -15.543, 'TeamName': 'Linguine Pastabots'}, {'TeamNum': 17324, 'OPR': 68.699, 'Auto': 10.476, 'CCWM': 26.247, 'TeamName': 'Green Machines'}, {'TeamNum': 16910, 'OPR': 66.436, 'Auto': 13.706, 'CCWM': 23.102, 'TeamName': 'Spaghetti Pastabots'}, {'TeamNum': 18861, 'OPR': 65.523, 'Auto': 20.169, 'CCWM': 29.648, 'TeamName': 'Wasted Potential Energy'}, {'TeamNum': 9191, 'OPR': 60.314, 'Auto': 12.826, 'CCWM': 3.626, 'TeamName': 'Beta Testers'}, {'TeamNum': 15021, 'OPR': 55.339, 'Auto': 19.132, 'CCWM': 7.668, 'TeamName': 'Ravioli Pastabots'}, {'TeamNum': 18065, 'OPR': 54.201, 'Auto': 7.844, 'CCWM': 12.922, 'TeamName': 'Repeat Error'}, {'TeamNum': 21843, 'OPR': 53.454, 'Auto': 9.668, 'CCWM': -12.69, 'TeamName': 'Prowler Robotics'}, {'TeamNum': 21722, 'OPR': 45.451, 'Auto': 12.765, 'CCWM': -30.726, 'TeamName': 'Macaroni Pastabots'}, {'TeamNum': 12825, 'OPR': 36.938, 'Auto': 12.498, 'CCWM': -42.505, 'TeamName': 'Wildkat Robotiks FTC'}, {'TeamNum': 20258, 'OPR': 29.662, 'Auto': 8.183, 'CCWM': -4.02, 'TeamName': 'Mind Bombs'}, {'TeamNum': 21304, 'OPR': 11.793, 'Auto': -3.161, 'CCWM': -49.435, 'TeamName': 'Tiger Robotics'}, {'TeamNum': 22129, 'OPR': 8.758, 'Auto': 0.032, 'CCWM': -60.675, 'TeamName': 'System Error'}]
i 1060
{'17802', '11030', '11472', '8130', '12927', '14523', '13072', '9626', '9161', '12900', '20325', '9054', '21330', '20039', '21462', '22703', '16412', '22123', '12977', '15524', '13811', '14524', '10143', '18072', '12926', '20313', '16802', '17658', '18798', '6566'}
[{'TeamNum': 12926, 'OPR': 118.12, 'Auto': 28.122, 'CCWM': 90.838, 'TeamName': 'Panther Robotics'}, {'TeamNum': 14524, 'OPR': 104.011, 'Auto': 29.131, 'CCWM': 41.474, 'TeamName': 'PESH Bots'}, {'TeamNum': 13072, 'OPR': 94.801, 'Auto': 25.562, 'CCWM': 34.796, 'TeamName': 'Fellowship of the Robot'}, {'TeamNum': 20325, 'OPR': 94.709, 'Auto': 18.004, 'CCWM': 65.041, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 12900, 'OPR': 86.69, 'Auto': 21.317, 'CCWM': 65.406, 'TeamName': 'Quantum Claw'}, {'TeamNum': 12977, 'OPR': 86.619, 'Auto': 22.512, 'CCWM': -0.07, 'TeamName': 'Rust In Peace'}, {'TeamNum': 17802, 'OPR': 79.482, 'Auto': 21.054, 'CCWM': 11.197, 'TeamName': 'Logic No Tech'}, {'TeamNum': 16412, 'OPR': 76.613, 'Auto': 19.143, 'CCWM': 40.613, 'TeamName': 'Triad Robotics'}, {'TeamNum': 10143, 'OPR': 72.98, 'Auto': 20.303, 'CCWM': 3.095, 'TeamName': 'Aero'}, {'TeamNum': 20313, 'OPR': 71.44, 'Auto': 17.795, 'CCWM': 41.61, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 21462, 'OPR': 71.095, 'Auto': 17.333, 'CCWM': -15.356, 'TeamName': 'Data Not Found'}, {'TeamNum': 12927, 'OPR': 61.535, 'Auto': 28.915, 'CCWM': 1.619, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 14523, 'OPR': 59.214, 'Auto': 12.426, 'CCWM': -3.49, 'TeamName': 'Free of Charge'}, {'TeamNum': 15524, 'OPR': 58.108, 'Auto': 25.568, 'CCWM': 4.251, 'TeamName': 'Cardinalbots'}, {'TeamNum': 9626, 'OPR': 54.482, 'Auto': 16.781, 'CCWM': 1.509, 'TeamName': 'Hockabots'}, {'TeamNum': 13811, 'OPR': 51.38, 'Auto': 19.595, 'CCWM': 31.223, 'TeamName': 'High Voltage'}, {'TeamNum': 9054, 'OPR': 48.563, 'Auto': 9.121, 'CCWM': -22.699, 'TeamName': 'Viridian Robotics'}, {'TeamNum': 18072, 'OPR': 43.243, 'Auto': 15.903, 'CCWM': 2.414, 'TeamName': 'BCS Battery Acid'}, {'TeamNum': 9161, 'OPR': 35.628, 'Auto': 15.031, 'CCWM': 10.38, 'TeamName': 'Overload'}, {'TeamNum': 21330, 'OPR': 35.392, 'Auto': 8.531, 'CCWM': -25.433, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 18798, 'OPR': 34.755, 'Auto': 12.099, 'CCWM': -0.403, 'TeamName': 'Crystal Dragons'}, {'TeamNum': 6566, 'OPR': 33.367, 'Auto': 5.155, 'CCWM': 7.658, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 22123, 'OPR': 27.91, 'Auto': 14.168, 'CCWM': -4.721, 'TeamName': 'Stallion Robotics'}, {'TeamNum': 16802, 'OPR': 25.371, 'Auto': -0.853, 'CCWM': -44.941, 'TeamName': 'Hollibots'}, {'TeamNum': 22703, 'OPR': 14.738, 'Auto': 13.118, 'CCWM': -87.558, 'TeamName': 'Tech Titans'}, {'TeamNum': 20039, 'OPR': 14.052, 'Auto': -2.934, 'CCWM': -68.979, 'TeamName': '1 Byte @-a-Time'}, {'TeamNum': 11472, 'OPR': 4.974, 'Auto': -0.219, 'CCWM': -79.688, 'TeamName': 'RavenClaw Robotics'}, {'TeamNum': 17658, 'OPR': 2.591, 'Auto': 1.139, 'CCWM': -18.146, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 8130, 'OPR': -5.094, 'Auto': -6.829, 'CCWM': -8.935, 'TeamName': 'Vikings'}, {'TeamNum': 11030, 'OPR': -8.489, 'Auto': -9.594, 'CCWM': -78.252, 'TeamName': 'Metal Jackets'}]
USTXNOATSQ
[{'TeamNum': 12926, 'OPR': 118.12, 'Auto': 28.122, 'CCWM': 90.838, 'TeamName': 'Panther Robotics'}, {'TeamNum': 14524, 'OPR': 104.011, 'Auto': 29.131, 'CCWM': 41.474, 'TeamName': 'PESH Bots'}, {'TeamNum': 13072, 'OPR': 94.801, 'Auto': 25.562, 'CCWM': 34.796, 'TeamName': 'Fellowship of the Robot'}, {'TeamNum': 20325, 'OPR': 94.709, 'Auto': 18.004, 'CCWM': 65.041, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 12900, 'OPR': 86.69, 'Auto': 21.317, 'CCWM': 65.406, 'TeamName': 'Quantum Claw'}, {'TeamNum': 12977, 'OPR': 86.619, 'Auto': 22.512, 'CCWM': -0.07, 'TeamName': 'Rust In Peace'}, {'TeamNum': 17802, 'OPR': 79.482, 'Auto': 21.054, 'CCWM': 11.197, 'TeamName': 'Logic No Tech'}, {'TeamNum': 16412, 'OPR': 76.613, 'Auto': 19.143, 'CCWM': 40.613, 'TeamName': 'Triad Robotics'}, {'TeamNum': 10143, 'OPR': 72.98, 'Auto': 20.303, 'CCWM': 3.095, 'TeamName': 'Aero'}, {'TeamNum': 20313, 'OPR': 71.44, 'Auto': 17.795, 'CCWM': 41.61, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 21462, 'OPR': 71.095, 'Auto': 17.333, 'CCWM': -15.356, 'TeamName': 'Data Not Found'}, {'TeamNum': 12927, 'OPR': 61.535, 'Auto': 28.915, 'CCWM': 1.619, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 14523, 'OPR': 59.214, 'Auto': 12.426, 'CCWM': -3.49, 'TeamName': 'Free of Charge'}, {'TeamNum': 15524, 'OPR': 58.108, 'Auto': 25.568, 'CCWM': 4.251, 'TeamName': 'Cardinalbots'}, {'TeamNum': 9626, 'OPR': 54.482, 'Auto': 16.781, 'CCWM': 1.509, 'TeamName': 'Hockabots'}, {'TeamNum': 13811, 'OPR': 51.38, 'Auto': 19.595, 'CCWM': 31.223, 'TeamName': 'High Voltage'}, {'TeamNum': 9054, 'OPR': 48.563, 'Auto': 9.121, 'CCWM': -22.699, 'TeamName': 'Viridian Robotics'}, {'TeamNum': 18072, 'OPR': 43.243, 'Auto': 15.903, 'CCWM': 2.414, 'TeamName': 'BCS Battery Acid'}, {'TeamNum': 9161, 'OPR': 35.628, 'Auto': 15.031, 'CCWM': 10.38, 'TeamName': 'Overload'}, {'TeamNum': 21330, 'OPR': 35.392, 'Auto': 8.531, 'CCWM': -25.433, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 18798, 'OPR': 34.755, 'Auto': 12.099, 'CCWM': -0.403, 'TeamName': 'Crystal Dragons'}, {'TeamNum': 6566, 'OPR': 33.367, 'Auto': 5.155, 'CCWM': 7.658, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 22123, 'OPR': 27.91, 'Auto': 14.168, 'CCWM': -4.721, 'TeamName': 'Stallion Robotics'}, {'TeamNum': 16802, 'OPR': 25.371, 'Auto': -0.853, 'CCWM': -44.941, 'TeamName': 'Hollibots'}, {'TeamNum': 22703, 'OPR': 14.738, 'Auto': 13.118, 'CCWM': -87.558, 'TeamName': 'Tech Titans'}, {'TeamNum': 20039, 'OPR': 14.052, 'Auto': -2.934, 'CCWM': -68.979, 'TeamName': '1 Byte @-a-Time'}, {'TeamNum': 11472, 'OPR': 4.974, 'Auto': -0.219, 'CCWM': -79.688, 'TeamName': 'RavenClaw Robotics'}, {'TeamNum': 17658, 'OPR': 2.591, 'Auto': 1.139, 'CCWM': -18.146, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 8130, 'OPR': -5.094, 'Auto': -6.829, 'CCWM': -8.935, 'TeamName': 'Vikings'}, {'TeamNum': 11030, 'OPR': -8.489, 'Auto': -9.594, 'CCWM': -78.252, 'TeamName': 'Metal Jackets'}]

i 1061
{'19927', '21385', '20293', '20256', '18339', '19367', '13828', '4106', '10760', '8755', '10100', '22548', '21923', '21355', '16956', '8680', '8572', '9956', '19993', '21748', '20686', '10824', '19417', '21737', '13201', '17235', '19453', '15382'}
[{'TeamNum': 13201, 'OPR': 133.978, 'Auto': 37.291, 'CCWM': 102.577, 'TeamName': 'Team Hazmat'}, {'TeamNum': 9956, 'OPR': 128.421, 'Auto': 34.169, 'CCWM': 74.542, 'TeamName': 'The Knack'}, {'TeamNum': 8755, 'OPR': 122.608, 'Auto': 28.819, 'CCWM': 64.89, 'TeamName': 'E-Storm'}, {'TeamNum': 20293, 'OPR': 109.471, 'Auto': 22.598, 'CCWM': 17.249, 'TeamName': 'Laser Bots'}, {'TeamNum': 8680, 'OPR': 99.518, 'Auto': 29.528, 'CCWM': 17.86, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 19927, 'OPR': 93.801, 'Auto': 28.155, 'CCWM': 57.692, 'TeamName': 'DUKES ROBOTICS'}, {'TeamNum': 10824, 'OPR': 85.262, 'Auto': 26.467, 'CCWM': 27.89, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 10100, 'OPR': 84.88, 'Auto': 24.339, 'CCWM': 35.261, 'TeamName': 'Phoenix Force'}, {'TeamNum': 8572, 'OPR': 64.823, 'Auto': 13.435, 'CCWM': -4.898, 'TeamName': 'Wall-Y Robotics'}, {'TeamNum': 19453, 'OPR': 64.408, 'Auto': 17.885, 'CCWM': -6.444, 'TeamName': 'Black Mesa'}, {'TeamNum': 17235, 'OPR': 63.617, 'Auto': 12.18, 'CCWM': 30.512, 'TeamName': 'MR. COD'}, {'TeamNum': 21355, 'OPR': 62.824, 'Auto': 5.439, 'CCWM': 30.089, 'TeamName': 'Turtle TEK'}, {'TeamNum': 4106, 'OPR': 62.012, 'Auto': 18.944, 'CCWM': 20.286, 'TeamName': 'Supposable Thumbs'}, {'TeamNum': 21737, 'OPR': 60.003, 'Auto': 9.164, 'CCWM': -35.503, 'TeamName': 'Green Eggs and Program'}, {'TeamNum': 10760, 'OPR': 59.677, 'Auto': 13.419, 'CCWM': 58.886, 'TeamName': 'TBD'}, {'TeamNum': 21385, 'OPR': 58.049, 'Auto': 17.252, 'CCWM': -1.218, 'TeamName': "Nuclear Fishin'"}, {'TeamNum': 19417, 'OPR': 54.248, 'Auto': 16.16, 'CCWM': -21.904, 'TeamName': 'Superstellar'}, {'TeamNum': 18339, 'OPR': 41.49, 'Auto': 8.695, 'CCWM': -54.779, 'TeamName': 'Super Servos'}, {'TeamNum': 22548, 'OPR': 38.364, 'Auto': 11.79, 'CCWM': -10.662, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 20256, 'OPR': 38.299, 'Auto': 10.759, 'CCWM': -26.537, 'TeamName': 'Greendale Robotics:  Storm'}, {'TeamNum': 16956, 'OPR': 37.243, 'Auto': 17.562, 'CCWM': -40.951, 'TeamName': 'The TechCrew'}, {'TeamNum': 21748, 'OPR': 32.943, 'Auto': 2.898, 'CCWM': -62.555, 'TeamName': 'dreaMKEepers'}, {'TeamNum': 15382, 'OPR': 30.617, 'Auto': 7.475, 'CCWM': -34.118, 'TeamName': "I'm Not A Robot"}, {'TeamNum': 13828, 'OPR': 28.956, 'Auto': 1.261, 'CCWM': -56.975, 'TeamName': 'Java Jokers'}, {'TeamNum': 19367, 'OPR': 25.92, 'Auto': 12.201, 'CCWM': -46.787, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 20686, 'OPR': 15.59, 'Auto': 6.039, 'CCWM': -23.006, 'TeamName': 'GHS Cyber Hawks '}, {'TeamNum': 19993, 'OPR': 7.79, 'Auto': 2.699, 'CCWM': -50.448, 'TeamName': 'Robo-Hounds'}, {'TeamNum': 21923, 'OPR': 1.586, 'Auto': 1.574, 'CCWM': -60.949, 'TeamName': 'Greendale Robotics:  Neptune'}]
USWISFQ
[{'TeamNum': 13201, 'OPR': 133.978, 'Auto': 37.291, 'CCWM': 102.577, 'TeamName': 'Team Hazmat'}, {'TeamNum': 9956, 'OPR': 128.421, 'Auto': 34.169, 'CCWM': 74.542, 'TeamName': 'The Knack'}, {'TeamNum': 8755, 'OPR': 122.608, 'Auto': 28.819, 'CCWM': 64.89, 'TeamName': 'E-Storm'}, {'TeamNum': 20293, 'OPR': 109.471, 'Auto': 22.598, 'CCWM': 17.249, 'TeamName': 'Laser Bots'}, {'TeamNum': 8680, 'OPR': 99.518, 'Auto': 29.528, 'CCWM': 17.86, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 19927, 'OPR': 93.801, 'Auto': 28.155, 'CCWM': 57.692, 'TeamName': 'DUKES ROBOTICS'}, {'TeamNum': 10824, 'OPR': 85.262, 'Auto': 26.467, 'CCWM': 27.89, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 10100, 'OPR': 84.88, 'Auto': 24.339, 'CCWM': 35.261, 'TeamName': 'Phoenix Force'}, {'TeamNum': 8572, 'OPR': 64.823, 'Auto': 13.435, 'CCWM': -4.898, 'TeamName': 'Wall-Y Robotics'}, {'TeamNum': 19453, 'OPR': 64.408, 'Auto': 17.885, 'CCWM': -6.444, 'TeamName': 'Black Mesa'}, {'TeamNum': 17235, 'OPR': 63.617, 'Auto': 12.18, 'CCWM': 30.512, 'TeamName': 'MR. COD'}, {'TeamNum': 21355, 'OPR': 62.824, 'Auto': 5.439, 'CCWM': 30.089, 'TeamName': 'Turtle TEK'}, {'TeamNum': 4106, 'OPR': 62.012, 'Auto': 18.944, 'CCWM': 20.286, 'TeamName': 'Supposable Thumbs'}, {'TeamNum': 21737, 'OPR': 60.003, 'Auto': 9.164, 'CCWM': -35.503, 'TeamName': 'Green Eggs and Program'}, {'TeamNum': 10760, 'OPR': 59.677, 'Auto': 13.419, 'CCWM': 58.886, 'TeamName': 'TBD'}, {'TeamNum': 21385, 'OPR': 58.049, 'Auto': 17.252, 'CCWM': -1.218, 'TeamName': "Nuclear Fishin'"}, {'TeamNum': 19417, 'OPR': 54.248, 'Auto': 16.16, 'CCWM': -21.904, 'TeamName': 'Superstellar'}, {'TeamNum': 18339, 'OPR': 41.49, 'Auto': 8.695, 'CCWM': -54.779, 'TeamName': 'Super Servos'}, {'TeamNum': 22548, 'OPR': 38.364, 'Auto': 11.79, 'CCWM': -10.662, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 20256, 'OPR': 38.299, 'Auto': 10.759, 'CCWM': -26.537, 'TeamName': 'Greendale Robotics:  Storm'}, {'TeamNum': 16956, 'OPR': 37.243, 'Auto': 17.562, 'CCWM': -40.951, 'TeamName': 'The TechCrew'}, {'TeamNum': 21748, 'OPR': 32.943, 'Auto': 2.898, 'CCWM': -62.555, 'TeamName': 'dreaMKEepers'}, {'TeamNum': 15382, 'OPR': 30.617, 'Auto': 7.475, 'CCWM': -34.118, 'TeamName': "I'm Not A Robot"}, {'TeamNum': 13828, 'OPR': 28.956, 'Auto': 1.261, 'CCWM': -56.975, 'TeamName': 'Java Jokers'}, {'TeamNum': 19367, 'OPR': 25.92, 'Auto': 12.201, 'CCWM': -46.787, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 20686, 'OPR': 15.59, 'Auto': 6.039, 'CCWM': -23.006, 'TeamName': 'GHS Cyber Hawks '}, {'TeamNum': 19993, 'OPR': 7.79, 'Auto': 2.699, 'CCWM': -50.448, 'TeamName': 'Robo-Hounds'}, {'TeamNum': 21923, 'OPR': 1.586, 'Auto': 1.574, 'CCWM': -60.949, 'TeamName': 'Greendale Robotics:  Neptune'}]
i 1062
{'3188', '15604', '4087', '18239', '2836', '6366', '16223', '22878', '20444', '21618', '3189', '10731', '20206', '6437', '5762', '4273'}
[{'TeamNum': 3189, 'OPR': 110.77, 'Auto': 32.8, 'CCWM': 99.124, 'TeamName': 'Rapid Unscheduled Disassembly'}, {'TeamNum': 3188, 'OPR': 76.623, 'Auto': 12.585, 'CCWM': 43.974, 'TeamName': 'Squiggle Splat Bang'}, {'TeamNum': 10731, 'OPR': 73.054, 'Auto': 28.718, 'CCWM': 22.144, 'TeamName': 'Radioactive'}, {'TeamNum': 21618, 'OPR': 69.419, 'Auto': 0.205, 'CCWM': 58.854, 'TeamName': 'Circuit Breakers 4-H Robotics'}, {'TeamNum': 16223, 'OPR': 67.428, 'Auto': 4.724, 'CCWM': 32.438, 'TeamName': 'Big Ounce'}, {'TeamNum': 20206, 'OPR': 46.349, 'Auto': 10.66, 'CCWM': 0.708, 'TeamName': 'Achilles Emeritus'}, {'TeamNum': 2836, 'OPR': 44.892, 'Auto': 0.572, 'CCWM': 13.188, 'TeamName': 'Trobots'}, {'TeamNum': 15604, 'OPR': 41.944, 'Auto': 8.607, 'CCWM': -2.246, 'TeamName': 'A Team'}, {'TeamNum': 6437, 'OPR': 40.743, 'Auto': 16.595, 'CCWM': -35.92, 'TeamName': 'Mad Hatters'}, {'TeamNum': 20444, 'OPR': 39.704, 'Auto': 2.315, 'CCWM': -2.655, 'TeamName': 'Midwest Mustangs'}, {'TeamNum': 4273, 'OPR': 29.836, 'Auto': 11.516, 'CCWM': -2.445, 'TeamName': 'Aluminati'}, {'TeamNum': 22878, 'OPR': 21.916, 'Auto': -3.825, 'CCWM': -7.859, 'TeamName': 'Dubois #2'}, {'TeamNum': 5762, 'OPR': 15.321, 'Auto': 3.295, 'CCWM': -49.685, 'TeamName': "Midwest Buckin' Buckaneers"}, {'TeamNum': 4087, 'OPR': 12.816, 'Auto': -2.395, 'CCWM': -26.18, 'TeamName': 'Midwest Dastardly Unsavory Potatoes (MDUP)'}, {'TeamNum': 6366, 'OPR': 4.341, 'Auto': -0.461, 'CCWM': -56.634, 'TeamName': 'T-Robots'}, {'TeamNum': 18239, 'OPR': -1.557, 'Auto': 3.289, 'CCWM': -86.804, 'TeamName': 'Washakie Robotics'}]
USWYCMP
[{'TeamNum': 3189, 'OPR': 110.77, 'Auto': 32.8, 'CCWM': 99.124, 'TeamName': 'Rapid Unscheduled Disassembly'}, {'TeamNum': 3188, 'OPR': 76.623, 'Auto': 12.585, 'CCWM': 43.974, 'TeamName': 'Squiggle Splat Bang'}, {'TeamNum': 10731, 'OPR': 73.054, 'Auto': 28.718, 'CCWM': 22.144, 'TeamName': 'Radioactive'}, {'TeamNum': 21618, 'OPR': 69.419, 'Auto': 0.205, 'CCWM': 58.854, 'TeamName': 'Circuit Breakers 4-H Robotics'}, {'TeamNum': 16223, 'OPR': 67.428, 'Auto': 4.724, 'CCWM': 32.438, 'TeamName': 'Big Ounce'}, {'TeamNum': 20206, 'OPR': 46.349, 'Auto': 10.66, 'CCWM': 0.708, 'TeamName': 'Achilles Emeritus'}, {'TeamNum': 2836, 'OPR': 44.892, 'Auto': 0.572, 'CCWM': 13.188, 'TeamName': 'Trobots'}, {'TeamNum': 15604, 'OPR': 41.944, 'Auto': 8.607, 'CCWM': -2.246, 'TeamName': 'A Team'}, {'TeamNum': 6437, 'OPR': 40.743, 'Auto': 16.595, 'CCWM': -35.92, 'TeamName': 'Mad Hatters'}, {'TeamNum': 20444, 'OPR': 39.704, 'Auto': 2.315, 'CCWM': -2.655, 'TeamName': 'Midwest Mustangs'}, {'TeamNum': 4273, 'OPR': 29.836, 'Auto': 11.516, 'CCWM': -2.445, 'TeamName': 'Aluminati'}, {'TeamNum': 22878, 'OPR': 21.916, 'Auto': -3.825, 'CCWM': -7.859, 'TeamName': 'Dubois #2'}, {'TeamNum': 5762, 'OPR': 15.321, 'Auto': 3.295, 'CCWM': -49.685, 'TeamName': "Midwest Buckin' Buckaneers"}, {'TeamNum': 4087, 'OPR': 12.816, 'Auto': -2.395, 'CCWM': -26.18, 'TeamName': 'Midwest Dastardly Unsavory Potatoes (MDUP)'}, {'TeamNum': 6366, 'OPR': 4.341, 'Auto': -0.461, 'CCWM': -56.634, 'TeamName': 'T-Robots'}, {'TeamNum': 18239, 'OPR': -1.557, 'Auto': 3.289, 'CCWM': -86.804, 'TeamName': 'Washakie Robotics'}]

i 1063
{'22557', '22712', '20025', '22648', '22829', '16031', '19995', '13459', '18799', '19769', '19767', '18589', '16448', '3491', '14316', '22111', '16503', '18840', '16205', '16195', '16267', '15013', '18841', '16353'}
[{'TeamNum': 16205, 'OPR': 109.119, 'Auto': 25.683, 'CCWM': 56.154, 'TeamName': 'Lightning Bots'}, {'TeamNum': 19995, 'OPR': 95.454, 'Auto': 20.169, 'CCWM': 46.77, 'TeamName': 'Eclipse'}, {'TeamNum': 16353, 'OPR': 90.63, 'Auto': 25.041, 'CCWM': 38.854, 'TeamName': 'Reynolds Reybots'}, {'TeamNum': 20025, 'OPR': 90.312, 'Auto': 26.747, 'CCWM': 19.99, 'TeamName': 'Esquimalt Atom Smashers'}, {'TeamNum': 3491, 'OPR': 85.951, 'Auto': 22.582, 'CCWM': -17.038, 'TeamName': 'FIX IT'}, {'TeamNum': 16195, 'OPR': 85.582, 'Auto': 24.508, 'CCWM': 26.049, 'TeamName': 'Guild of Builders'}, {'TeamNum': 18840, 'OPR': 84.903, 'Auto': 23.315, 'CCWM': 39.804, 'TeamName': 'Reynolds Roborunners'}, {'TeamNum': 22829, 'OPR': 84.623, 'Auto': 15.248, 'CCWM': 19.599, 'TeamName': 'INERTIA'}, {'TeamNum': 22557, 'OPR': 82.266, 'Auto': 19.457, 'CCWM': 21.618, 'TeamName': 'Mount Douglas Robotics Team'}, {'TeamNum': 22111, 'OPR': 78.889, 'Auto': 24.352, 'CCWM': 6.545, 'TeamName': 'Matheson Mecha Mustangs'}, {'TeamNum': 19767, 'OPR': 66.848, 'Auto': 18.498, 'CCWM': -6.838, 'TeamName': 'The Frog Series'}, {'TeamNum': 18589, 'OPR': 62.78, 'Auto': 22.231, 'CCWM': -29.768, 'TeamName': "St. Pat's Celtic Silverfish"}, {'TeamNum': 16267, 'OPR': 59.403, 'Auto': 9.863, 'CCWM': 20.804, 'TeamName': 'Forces Unknown'}, {'TeamNum': 18841, 'OPR': 58.061, 'Auto': 16.708, 'CCWM': 0.808, 'TeamName': 'KSS ONE'}, {'TeamNum': 14316, 'OPR': 57.705, 'Auto': 7.953, 'CCWM': 6.886, 'TeamName': 'MDR Entradox'}, {'TeamNum': 16031, 'OPR': 50.062, 'Auto': 18.962, 'CCWM': 11.057, 'TeamName': 'PARABELLUM'}, {'TeamNum': 16503, 'OPR': 48.66, 'Auto': 4.282, 'CCWM': 3.214, 'TeamName': 'MDR QED Robotics'}, {'TeamNum': 16448, 'OPR': 45.498, 'Auto': 13.705, 'CCWM': -30.3, 'TeamName': 'A.I.M. Bot Robotics'}, {'TeamNum': 22712, 'OPR': 44.346, 'Auto': 8.699, 'CCWM': -29.868, 'TeamName': 'French Fries'}, {'TeamNum': 15013, 'OPR': 43.132, 'Auto': 9.631, 'CCWM': -36.452, 'TeamName': 'Friction'}, {'TeamNum': 18799, 'OPR': 37.862, 'Auto': 3.072, 'CCWM': -17.017, 'TeamName': 'Clean-Up Crew Robotics'}, {'TeamNum': 19769, 'OPR': 36.996, 'Auto': 15.774, 'CCWM': -66.787, 'TeamName': 'Sentinels'}, {'TeamNum': 13459, 'OPR': 36.791, 'Auto': 18.166, 'CCWM': -22.608, 'TeamName': 'M.A.R.G.'}, {'TeamNum': 22648, 'OPR': 20.527, 'Auto': 8.153, 'CCWM': -61.475, 'TeamName': 'Robotic Raiders'}]
CABCCMP
[{'TeamNum': 16205, 'OPR': 109.119, 'Auto': 25.683, 'CCWM': 56.154, 'TeamName': 'Lightning Bots'}, {'TeamNum': 19995, 'OPR': 95.454, 'Auto': 20.169, 'CCWM': 46.77, 'TeamName': 'Eclipse'}, {'TeamNum': 16353, 'OPR': 90.63, 'Auto': 25.041, 'CCWM': 38.854, 'TeamName': 'Reynolds Reybots'}, {'TeamNum': 20025, 'OPR': 90.312, 'Auto': 26.747, 'CCWM': 19.99, 'TeamName': 'Esquimalt Atom Smashers'}, {'TeamNum': 3491, 'OPR': 85.951, 'Auto': 22.582, 'CCWM': -17.038, 'TeamName': 'FIX IT'}, {'TeamNum': 16195, 'OPR': 85.582, 'Auto': 24.508, 'CCWM': 26.049, 'TeamName': 'Guild of Builders'}, {'TeamNum': 18840, 'OPR': 84.903, 'Auto': 23.315, 'CCWM': 39.804, 'TeamName': 'Reynolds Roborunners'}, {'TeamNum': 22829, 'OPR': 84.623, 'Auto': 15.248, 'CCWM': 19.599, 'TeamName': 'INERTIA'}, {'TeamNum': 22557, 'OPR': 82.266, 'Auto': 19.457, 'CCWM': 21.618, 'TeamName': 'Mount Douglas Robotics Team'}, {'TeamNum': 22111, 'OPR': 78.889, 'Auto': 24.352, 'CCWM': 6.545, 'TeamName': 'Matheson Mecha Mustangs'}, {'TeamNum': 19767, 'OPR': 66.848, 'Auto': 18.498, 'CCWM': -6.838, 'TeamName': 'The Frog Series'}, {'TeamNum': 18589, 'OPR': 62.78, 'Auto': 22.231, 'CCWM': -29.768, 'TeamName': "St. Pat's Celtic Silverfish"}, {'TeamNum': 16267, 'OPR': 59.403, 'Auto': 9.863, 'CCWM': 20.804, 'TeamName': 'Forces Unknown'}, {'TeamNum': 18841, 'OPR': 58.061, 'Auto': 16.708, 'CCWM': 0.808, 'TeamName': 'KSS ONE'}, {'TeamNum': 14316, 'OPR': 57.705, 'Auto': 7.953, 'CCWM': 6.886, 'TeamName': 'MDR Entradox'}, {'TeamNum': 16031, 'OPR': 50.062, 'Auto': 18.962, 'CCWM': 11.057, 'TeamName': 'PARABELLUM'}, {'TeamNum': 16503, 'OPR': 48.66, 'Auto': 4.282, 'CCWM': 3.214, 'TeamName': 'MDR QED Robotics'}, {'TeamNum': 16448, 'OPR': 45.498, 'Auto': 13.705, 'CCWM': -30.3, 'TeamName': 'A.I.M. Bot Robotics'}, {'TeamNum': 22712, 'OPR': 44.346, 'Auto': 8.699, 'CCWM': -29.868, 'TeamName': 'French Fries'}, {'TeamNum': 15013, 'OPR': 43.132, 'Auto': 9.631, 'CCWM': -36.452, 'TeamName': 'Friction'}, {'TeamNum': 18799, 'OPR': 37.862, 'Auto': 3.072, 'CCWM': -17.017, 'TeamName': 'Clean-Up Crew Robotics'}, {'TeamNum': 19769, 'OPR': 36.996, 'Auto': 15.774, 'CCWM': -66.787, 'TeamName': 'Sentinels'}, {'TeamNum': 13459, 'OPR': 36.791, 'Auto': 18.166, 'CCWM': -22.608, 'TeamName': 'M.A.R.G.'}, {'TeamNum': 22648, 'OPR': 20.527, 'Auto': 8.153, 'CCWM': -61.475, 'TeamName': 'Robotic Raiders'}]
i 1064
{'16417', '22379', '19446', '22075', '18846', '19531', '16399', '19498', '18158', '21319', '19486', '19490', '19836', '16413', '16397', '19491', '21908', '20261', '20035', '22260', '20105', '19500', '16488', '16424', '19721', '19530', '18844', '22242', '16423', '16366'}
[{'TeamNum': 16417, 'OPR': 152.622, 'Auto': 49.687, 'CCWM': 128.584, 'TeamName': 'ROC'}, {'TeamNum': 21319, 'OPR': 108.477, 'Auto': 29.453, 'CCWM': 16.626, 'TeamName': 'Falcon'}, {'TeamNum': 19836, 'OPR': 97.094, 'Auto': 28.877, 'CCWM': 25.067, 'TeamName': 'Hawk'}, {'TeamNum': 19530, 'OPR': 90.05, 'Auto': 20.786, 'CCWM': 56.162, 'TeamName': 'The Thunderbirds'}, {'TeamNum': 19500, 'OPR': 88.554, 'Auto': 15.747, 'CCWM': 58.791, 'TeamName': 'RoBEARtics'}, {'TeamNum': 21908, 'OPR': 83.971, 'Auto': 39.23, 'CCWM': 25.379, 'TeamName': 'Eagle'}, {'TeamNum': 16488, 'OPR': 82.82, 'Auto': 21.975, 'CCWM': 26.92, 'TeamName': 'Rams Robotics'}, {'TeamNum': 18158, 'OPR': 75.046, 'Auto': 24.429, 'CCWM': 14.702, 'TeamName': 'The Futuristics'}, {'TeamNum': 16366, 'OPR': 66.68, 'Auto': 28.187, 'CCWM': 5.005, 'TeamName': 'TFS Robotic Unicorns'}, {'TeamNum': 18846, 'OPR': 61.429, 'Auto': 21.144, 'CCWM': -21.29, 'TeamName': 'Brebotics'}, {'TeamNum': 22379, 'OPR': 60.881, 'Auto': 11.23, 'CCWM': 13.91, 'TeamName': 'Riverdale Tech Runners'}, {'TeamNum': 19531, 'OPR': 57.469, 'Auto': 9.694, 'CCWM': -40.676, 'TeamName': 'Radiant Robotics'}, {'TeamNum': 20035, 'OPR': 53.876, 'Auto': 25.576, 'CCWM': -10.305, 'TeamName': 'Cyber Barons'}, {'TeamNum': 18844, 'OPR': 52.81, 'Auto': 21.505, 'CCWM': 2.653, 'TeamName': 'Pr0Teens'}, {'TeamNum': 19498, 'OPR': 52.232, 'Auto': 27.937, 'CCWM': -20.698, 'TeamName': 'Devolotics'}, {'TeamNum': 16424, 'OPR': 50.495, 'Auto': 26.235, 'CCWM': 7.73, 'TeamName': 'Atomic Dishwashers'}, {'TeamNum': 19721, 'OPR': 47.778, 'Auto': 13.166, 'CCWM': -9.246, 'TeamName': 'Pigeons'}, {'TeamNum': 19490, 'OPR': 37.692, 'Auto': 11.176, 'CCWM': -50.403, 'TeamName': "SMT Titans - The 'Tita'BOTS"}, {'TeamNum': 16413, 'OPR': 36.137, 'Auto': -9.333, 'CCWM': 37.506, 'TeamName': 'Lo-Ellen EDIT (RED)'}, {'TeamNum': 19491, 'OPR': 34.462, 'Auto': 14.795, 'CCWM': 12.472, 'TeamName': 'Masked Gator'}, {'TeamNum': 20105, 'OPR': 34.119, 'Auto': 18.613, 'CCWM': -67.043, 'TeamName': 'Lo-Ellen EDIT (GREY)'}, {'TeamNum': 22242, 'OPR': 34.087, 'Auto': 8.195, 'CCWM': -38.936, 'TeamName': 'FTC BETA DOGS '}, {'TeamNum': 16399, 'OPR': 29.487, 'Auto': 9.076, 'CCWM': -45.071, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 22260, 'OPR': 27.265, 'Auto': 0.643, 'CCWM': -10.641, 'TeamName': 'FrostByte'}, {'TeamNum': 19486, 'OPR': 26.954, 'Auto': -1.672, 'CCWM': 12.899, 'TeamName': 'RoboHawks'}, {'TeamNum': 22075, 'OPR': 25.246, 'Auto': 8.483, 'CCWM': -37.697, 'TeamName': 'R.G.B.'}, {'TeamNum': 20261, 'OPR': 24.505, 'Auto': 2.685, 'CCWM': -1.994, 'TeamName': 'Drive Gears'}, {'TeamNum': 19446, 'OPR': 19.474, 'Auto': -2.469, 'CCWM': -23.776, 'TeamName': 'Team Titans Go'}, {'TeamNum': 16423, 'OPR': 17.854, 'Auto': -5.23, 'CCWM': -26.306, 'TeamName': 'Storm'}, {'TeamNum': 16397, 'OPR': -14.686, 'Auto': -10.932, 'CCWM': -44.937, 'TeamName': 'Relatively Quantum   '}]
CAONCMP
[{'TeamNum': 16417, 'OPR': 152.622, 'Auto': 49.687, 'CCWM': 128.584, 'TeamName': 'ROC'}, {'TeamNum': 21319, 'OPR': 108.477, 'Auto': 29.453, 'CCWM': 16.626, 'TeamName': 'Falcon'}, {'TeamNum': 19836, 'OPR': 97.094, 'Auto': 28.877, 'CCWM': 25.067, 'TeamName': 'Hawk'}, {'TeamNum': 19530, 'OPR': 90.05, 'Auto': 20.786, 'CCWM': 56.162, 'TeamName': 'The Thunderbirds'}, {'TeamNum': 19500, 'OPR': 88.554, 'Auto': 15.747, 'CCWM': 58.791, 'TeamName': 'RoBEARtics'}, {'TeamNum': 21908, 'OPR': 83.971, 'Auto': 39.23, 'CCWM': 25.379, 'TeamName': 'Eagle'}, {'TeamNum': 16488, 'OPR': 82.82, 'Auto': 21.975, 'CCWM': 26.92, 'TeamName': 'Rams Robotics'}, {'TeamNum': 18158, 'OPR': 75.046, 'Auto': 24.429, 'CCWM': 14.702, 'TeamName': 'The Futuristics'}, {'TeamNum': 16366, 'OPR': 66.68, 'Auto': 28.187, 'CCWM': 5.005, 'TeamName': 'TFS Robotic Unicorns'}, {'TeamNum': 18846, 'OPR': 61.429, 'Auto': 21.144, 'CCWM': -21.29, 'TeamName': 'Brebotics'}, {'TeamNum': 22379, 'OPR': 60.881, 'Auto': 11.23, 'CCWM': 13.91, 'TeamName': 'Riverdale Tech Runners'}, {'TeamNum': 19531, 'OPR': 57.469, 'Auto': 9.694, 'CCWM': -40.676, 'TeamName': 'Radiant Robotics'}, {'TeamNum': 20035, 'OPR': 53.876, 'Auto': 25.576, 'CCWM': -10.305, 'TeamName': 'Cyber Barons'}, {'TeamNum': 18844, 'OPR': 52.81, 'Auto': 21.505, 'CCWM': 2.653, 'TeamName': 'Pr0Teens'}, {'TeamNum': 19498, 'OPR': 52.232, 'Auto': 27.937, 'CCWM': -20.698, 'TeamName': 'Devolotics'}, {'TeamNum': 16424, 'OPR': 50.495, 'Auto': 26.235, 'CCWM': 7.73, 'TeamName': 'Atomic Dishwashers'}, {'TeamNum': 19721, 'OPR': 47.778, 'Auto': 13.166, 'CCWM': -9.246, 'TeamName': 'Pigeons'}, {'TeamNum': 19490, 'OPR': 37.692, 'Auto': 11.176, 'CCWM': -50.403, 'TeamName': "SMT Titans - The 'Tita'BOTS"}, {'TeamNum': 16413, 'OPR': 36.137, 'Auto': -9.333, 'CCWM': 37.506, 'TeamName': 'Lo-Ellen EDIT (RED)'}, {'TeamNum': 19491, 'OPR': 34.462, 'Auto': 14.795, 'CCWM': 12.472, 'TeamName': 'Masked Gator'}, {'TeamNum': 20105, 'OPR': 34.119, 'Auto': 18.613, 'CCWM': -67.043, 'TeamName': 'Lo-Ellen EDIT (GREY)'}, {'TeamNum': 22242, 'OPR': 34.087, 'Auto': 8.195, 'CCWM': -38.936, 'TeamName': 'FTC BETA DOGS '}, {'TeamNum': 16399, 'OPR': 29.487, 'Auto': 9.076, 'CCWM': -45.071, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 22260, 'OPR': 27.265, 'Auto': 0.643, 'CCWM': -10.641, 'TeamName': 'FrostByte'}, {'TeamNum': 19486, 'OPR': 26.954, 'Auto': -1.672, 'CCWM': 12.899, 'TeamName': 'RoboHawks'}, {'TeamNum': 22075, 'OPR': 25.246, 'Auto': 8.483, 'CCWM': -37.697, 'TeamName': 'R.G.B.'}, {'TeamNum': 20261, 'OPR': 24.505, 'Auto': 2.685, 'CCWM': -1.994, 'TeamName': 'Drive Gears'}, {'TeamNum': 19446, 'OPR': 19.474, 'Auto': -2.469, 'CCWM': -23.776, 'TeamName': 'Team Titans Go'}, {'TeamNum': 16423, 'OPR': 17.854, 'Auto': -5.23, 'CCWM': -26.306, 'TeamName': 'Storm'}, {'TeamNum': 16397, 'OPR': -14.686, 'Auto': -10.932, 'CCWM': -44.937, 'TeamName': 'Relatively Quantum   '}]

i 1065
{'21701', '10937', '10939', '10938', '21658', '10936', '21697', '21719', '10941', '16476', '21646', '21699', '10183', '21695', '21640', '21648', '18859', '15469', '21647', '21698', '21700', '17157', '17558', '16959', '16441', '14144', '18710', '3954', '18917', '14183', '21942', '18425', '17493'}
[{'TeamNum': 3954, 'OPR': 88.506, 'Auto': 27.61, 'CCWM': 65.538, 'TeamName': 'Pink to the Future'}, {'TeamNum': 18710, 'OPR': 83.887, 'Auto': 20.215, 'CCWM': 63.616, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 16476, 'OPR': 81.497, 'Auto': 19.607, 'CCWM': 44.247, 'TeamName': 'RoyalCats'}, {'TeamNum': 15469, 'OPR': 77.443, 'Auto': 11.997, 'CCWM': 42.189, 'TeamName': 'UK 170 - Alconbury HS - The Scally Lads & The Wrench'}, {'TeamNum': 10183, 'OPR': 75.381, 'Auto': 19.145, 'CCWM': 18.143, 'TeamName': 'F.R.O.G  Frog Robots Of Germany'}, {'TeamNum': 14183, 'OPR': 57.925, 'Auto': 20.179, 'CCWM': 40.356, 'TeamName': 'Dukes of Brabant'}, {'TeamNum': 18425, 'OPR': 56.563, 'Auto': 17.1, 'CCWM': 54.721, 'TeamName': 'Ubbo Tech Team'}, {'TeamNum': 21648, 'OPR': 54.125, 'Auto': 9.721, 'CCWM': 34.131, 'TeamName': 'UK 429 - Alconbury HS - Mr. Krabs'}, {'TeamNum': 21646, 'OPR': 51.889, 'Auto': 8.35, 'CCWM': 5.545, 'TeamName': 'UK133 Lakenheath HS RoboLancers'}, {'TeamNum': 21658, 'OPR': 48.295, 'Auto': 10.131, 'CCWM': 1.77, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 21647, 'OPR': 44.434, 'Auto': 6.139, 'CCWM': 7.288, 'TeamName': 'Brussels HS Brigands'}, {'TeamNum': 18917, 'OPR': 44.163, 'Auto': 8.351, 'CCWM': 39.971, 'TeamName': 'Extraordinary Aristocrat Group (E.A.G)'}, {'TeamNum': 10939, 'OPR': 38.957, 'Auto': 21.202, 'CCWM': 26.93, 'TeamName': 'UK024 Lakenheath HS RoboLancers '}, {'TeamNum': 18859, 'OPR': 37.185, 'Auto': 1.027, 'CCWM': 0.243, 'TeamName': 'Stanislas Tech Team'}, {'TeamNum': 14144, 'OPR': 34.179, 'Auto': 3.834, 'CCWM': -38.38, 'TeamName': 'EAGirls'}, {'TeamNum': 21640, 'OPR': 27.805, 'Auto': 9.015, 'CCWM': 10.207, 'TeamName': 'Ansbach FTC 2023'}, {'TeamNum': 21699, 'OPR': 27.526, 'Auto': 1.105, 'CCWM': 25.615, 'TeamName': 'Stuttgart HS 2023'}, {'TeamNum': 16441, 'OPR': 25.679, 'Auto': 10.489, 'CCWM': -38.153, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 21701, 'OPR': 25.58, 'Auto': 6.771, 'CCWM': 5.604, 'TeamName': 'Baumholder FTC 2023'}, {'TeamNum': 10941, 'OPR': 25.469, 'Auto': 7.577, 'CCWM': -32.729, 'TeamName': 'SHAPE Robotics'}, {'TeamNum': 21698, 'OPR': 25.141, 'Auto': 1.55, 'CCWM': -48.172, 'TeamName': 'Wiesbaden HS 2023'}, {'TeamNum': 16959, 'OPR': 22.325, 'Auto': 12.867, 'CCWM': -0.621, 'TeamName': 'Ansbach FTC2'}, {'TeamNum': 21700, 'OPR': 21.012, 'Auto': -3.233, 'CCWM': -44.197, 'TeamName': 'Kaiserslautern HS 2023'}, {'TeamNum': 17157, 'OPR': 19.254, 'Auto': 0.901, 'CCWM': -30.881, 'TeamName': 'Hohenfels 2020a'}, {'TeamNum': 17558, 'OPR': 17.967, 'Auto': 10.857, 'CCWM': 6.282, 'TeamName': 'Vilseck 2020a'}, {'TeamNum': 21719, 'OPR': 17.271, 'Auto': 3.165, 'CCWM': -21.668, 'TeamName': 'AFNORTH HS Lions'}, {'TeamNum': 21695, 'OPR': 10.829, 'Auto': -1.301, 'CCWM': -19.47, 'TeamName': 'Wiesbaden FTC 2023b'}, {'TeamNum': 21697, 'OPR': 10.734, 'Auto': 0.233, 'CCWM': -48.768, 'TeamName': 'Ramstein HS 2023a'}, {'TeamNum': 21942, 'OPR': 7.118, 'Auto': -1.764, 'CCWM': -20.928, 'TeamName': 'Sigonella MHS FTC Rookie'}, {'TeamNum': 10936, 'OPR': 2.329, 'Auto': -0.085, 'CCWM': -54.73, 'TeamName': 'Sigonella High School'}, {'TeamNum': 17493, 'OPR': -0.319, 'Auto': 0.37, 'CCWM': -4.471, 'TeamName': 'SpHS Duct Tape and Zip Ties'}, {'TeamNum': 10937, 'OPR': -0.734, 'Auto': 1.964, 'CCWM': -62.433, 'TeamName': 'Stuttgart HS'}, {'TeamNum': 10938, 'OPR': -0.972, 'Auto': -6.536, 'CCWM': -17.675, 'TeamName': 'Baumholder (DSO)'}]
ONADODCMP
[{'TeamNum': 3954, 'OPR': 88.506, 'Auto': 27.61, 'CCWM': 65.538, 'TeamName': 'Pink to the Future'}, {'TeamNum': 18710, 'OPR': 83.887, 'Auto': 20.215, 'CCWM': 63.616, 'TeamName': 'Stanislas Tech Academy'}, {'TeamNum': 16476, 'OPR': 81.497, 'Auto': 19.607, 'CCWM': 44.247, 'TeamName': 'RoyalCats'}, {'TeamNum': 15469, 'OPR': 77.443, 'Auto': 11.997, 'CCWM': 42.189, 'TeamName': 'UK 170 - Alconbury HS - The Scally Lads & The Wrench'}, {'TeamNum': 10183, 'OPR': 75.381, 'Auto': 19.145, 'CCWM': 18.143, 'TeamName': 'F.R.O.G  Frog Robots Of Germany'}, {'TeamNum': 14183, 'OPR': 57.925, 'Auto': 20.179, 'CCWM': 40.356, 'TeamName': 'Dukes of Brabant'}, {'TeamNum': 18425, 'OPR': 56.563, 'Auto': 17.1, 'CCWM': 54.721, 'TeamName': 'Ubbo Tech Team'}, {'TeamNum': 21648, 'OPR': 54.125, 'Auto': 9.721, 'CCWM': 34.131, 'TeamName': 'UK 429 - Alconbury HS - Mr. Krabs'}, {'TeamNum': 21646, 'OPR': 51.889, 'Auto': 8.35, 'CCWM': 5.545, 'TeamName': 'UK133 Lakenheath HS RoboLancers'}, {'TeamNum': 21658, 'OPR': 48.295, 'Auto': 10.131, 'CCWM': 1.77, 'TeamName': 'Emmauscollege Thunder Wonder'}, {'TeamNum': 21647, 'OPR': 44.434, 'Auto': 6.139, 'CCWM': 7.288, 'TeamName': 'Brussels HS Brigands'}, {'TeamNum': 18917, 'OPR': 44.163, 'Auto': 8.351, 'CCWM': 39.971, 'TeamName': 'Extraordinary Aristocrat Group (E.A.G)'}, {'TeamNum': 10939, 'OPR': 38.957, 'Auto': 21.202, 'CCWM': 26.93, 'TeamName': 'UK024 Lakenheath HS RoboLancers '}, {'TeamNum': 18859, 'OPR': 37.185, 'Auto': 1.027, 'CCWM': 0.243, 'TeamName': 'Stanislas Tech Team'}, {'TeamNum': 14144, 'OPR': 34.179, 'Auto': 3.834, 'CCWM': -38.38, 'TeamName': 'EAGirls'}, {'TeamNum': 21640, 'OPR': 27.805, 'Auto': 9.015, 'CCWM': 10.207, 'TeamName': 'Ansbach FTC 2023'}, {'TeamNum': 21699, 'OPR': 27.526, 'Auto': 1.105, 'CCWM': 25.615, 'TeamName': 'Stuttgart HS 2023'}, {'TeamNum': 16441, 'OPR': 25.679, 'Auto': 10.489, 'CCWM': -38.153, 'TeamName': 'Pretty Smart Robotics'}, {'TeamNum': 21701, 'OPR': 25.58, 'Auto': 6.771, 'CCWM': 5.604, 'TeamName': 'Baumholder FTC 2023'}, {'TeamNum': 10941, 'OPR': 25.469, 'Auto': 7.577, 'CCWM': -32.729, 'TeamName': 'SHAPE Robotics'}, {'TeamNum': 21698, 'OPR': 25.141, 'Auto': 1.55, 'CCWM': -48.172, 'TeamName': 'Wiesbaden HS 2023'}, {'TeamNum': 16959, 'OPR': 22.325, 'Auto': 12.867, 'CCWM': -0.621, 'TeamName': 'Ansbach FTC2'}, {'TeamNum': 21700, 'OPR': 21.012, 'Auto': -3.233, 'CCWM': -44.197, 'TeamName': 'Kaiserslautern HS 2023'}, {'TeamNum': 17157, 'OPR': 19.254, 'Auto': 0.901, 'CCWM': -30.881, 'TeamName': 'Hohenfels 2020a'}, {'TeamNum': 17558, 'OPR': 17.967, 'Auto': 10.857, 'CCWM': 6.282, 'TeamName': 'Vilseck 2020a'}, {'TeamNum': 21719, 'OPR': 17.271, 'Auto': 3.165, 'CCWM': -21.668, 'TeamName': 'AFNORTH HS Lions'}, {'TeamNum': 21695, 'OPR': 10.829, 'Auto': -1.301, 'CCWM': -19.47, 'TeamName': 'Wiesbaden FTC 2023b'}, {'TeamNum': 21697, 'OPR': 10.734, 'Auto': 0.233, 'CCWM': -48.768, 'TeamName': 'Ramstein HS 2023a'}, {'TeamNum': 21942, 'OPR': 7.118, 'Auto': -1.764, 'CCWM': -20.928, 'TeamName': 'Sigonella MHS FTC Rookie'}, {'TeamNum': 10936, 'OPR': 2.329, 'Auto': -0.085, 'CCWM': -54.73, 'TeamName': 'Sigonella High School'}, {'TeamNum': 17493, 'OPR': -0.319, 'Auto': 0.37, 'CCWM': -4.471, 'TeamName': 'SpHS Duct Tape and Zip Ties'}, {'TeamNum': 10937, 'OPR': -0.734, 'Auto': 1.964, 'CCWM': -62.433, 'TeamName': 'Stuttgart HS'}, {'TeamNum': 10938, 'OPR': -0.972, 'Auto': -6.536, 'CCWM': -17.675, 'TeamName': 'Baumholder (DSO)'}]
i 1066
i 1067
{'17878', '15352', '15239', '14896', '17852', '22705', '16044', '17853', '22755', '17980', '22707', '3981', '22701', '16187', '17884', '22726', '15060', '15059', '6899', '22647', '16076', '22222', '17882', '16081', '16075'}
[{'TeamNum': 6899, 'OPR': 62.723, 'Auto': 10.85, 'CCWM': 47.486, 'TeamName': 'Blue Bots'}, {'TeamNum': 15059, 'OPR': 57.771, 'Auto': 10.988, 'CCWM': 28.484, 'TeamName': 'Calabar High School'}, {'TeamNum': 15060, 'OPR': 47.51, 'Auto': 10.122, 'CCWM': 47.818, 'TeamName': 'Blue Flames'}, {'TeamNum': 22705, 'OPR': 43.457, 'Auto': 1.367, 'CCWM': 9.551, 'TeamName': 'Golden Gears'}, {'TeamNum': 3981, 'OPR': 42.445, 'Auto': 8.703, 'CCWM': 6.068, 'TeamName': 'The Griffins'}, {'TeamNum': 22647, 'OPR': 40.904, 'Auto': -1.877, 'CCWM': -13.044, 'TeamName': 'Team Flames'}, {'TeamNum': 16075, 'OPR': 38.714, 'Auto': 13.835, 'CCWM': 25.914, 'TeamName': 'Campion College'}, {'TeamNum': 22222, 'OPR': 37.852, 'Auto': 4.211, 'CCWM': 9.737, 'TeamName': 'Dominican Republic Incredible FIRST Team (Team DRIFT)'}, {'TeamNum': 22707, 'OPR': 35.84, 'Auto': 5.91, 'CCWM': -7.179, 'TeamName': 'Drones'}, {'TeamNum': 22726, 'OPR': 32.346, 'Auto': 6.909, 'CCWM': 2.061, 'TeamName': 'Alpha Tech'}, {'TeamNum': 22701, 'OPR': 27.712, 'Auto': 14.859, 'CCWM': 30.686, 'TeamName': 'St Jago - Lions'}, {'TeamNum': 16044, 'OPR': 26.992, 'Auto': -1.298, 'CCWM': 16.275, 'TeamName': 'Optimus Pride '}, {'TeamNum': 16076, 'OPR': 20.127, 'Auto': 2.14, 'CCWM': -12.202, 'TeamName': 'MeadowBrook High '}, {'TeamNum': 17852, 'OPR': 19.305, 'Auto': 4.338, 'CCWM': -0.832, 'TeamName': 'Phoenix Requiem'}, {'TeamNum': 16187, 'OPR': 17.861, 'Auto': -6.757, 'CCWM': -22.212, 'TeamName': 'Stingers'}, {'TeamNum': 22755, 'OPR': 14.538, 'Auto': 0.048, 'CCWM': -10.263, 'TeamName': 'Team Circle'}, {'TeamNum': 16081, 'OPR': 13.74, 'Auto': 0.061, 'CCWM': -27.717, 'TeamName': 'STATHS'}, {'TeamNum': 17980, 'OPR': 9.657, 'Auto': 4.902, 'CCWM': -12.576, 'TeamName': 'AISK Hurricane'}, {'TeamNum': 15239, 'OPR': 8.814, 'Auto': -3.357, 'CCWM': -0.657, 'TeamName': "Convent of Mercy Academy 'Alpha'"}, {'TeamNum': 17884, 'OPR': 8.483, 'Auto': 0.748, 'CCWM': 8.612, 'TeamName': 'Lady Bots'}, {'TeamNum': 17853, 'OPR': 7.439, 'Auto': -1.361, 'CCWM': -35.844, 'TeamName': 'Munro College'}, {'TeamNum': 14896, 'OPR': 6.48, 'Auto': 2.006, 'CCWM': -3.322, 'TeamName': 'Knight Bots'}, {'TeamNum': 17878, 'OPR': 5.983, 'Auto': 3.276, 'CCWM': -38.359, 'TeamName': 'Holy Childhood High School'}, {'TeamNum': 17882, 'OPR': 5.626, 'Auto': 0.924, 'CCWM': -21.643, 'TeamName': 'Maggotrons'}, {'TeamNum': 15352, 'OPR': 1.694, 'Auto': 7.165, 'CCWM': -15.725, 'TeamName': 'Team Iterations'}]
JMCMP
[{'TeamNum': 6899, 'OPR': 62.723, 'Auto': 10.85, 'CCWM': 47.486, 'TeamName': 'Blue Bots'}, {'TeamNum': 15059, 'OPR': 57.771, 'Auto': 10.988, 'CCWM': 28.484, 'TeamName': 'Calabar High School'}, {'TeamNum': 15060, 'OPR': 47.51, 'Auto': 10.122, 'CCWM': 47.818, 'TeamName': 'Blue Flames'}, {'TeamNum': 22705, 'OPR': 43.457, 'Auto': 1.367, 'CCWM': 9.551, 'TeamName': 'Golden Gears'}, {'TeamNum': 3981, 'OPR': 42.445, 'Auto': 8.703, 'CCWM': 6.068, 'TeamName': 'The Griffins'}, {'TeamNum': 22647, 'OPR': 40.904, 'Auto': -1.877, 'CCWM': -13.044, 'TeamName': 'Team Flames'}, {'TeamNum': 16075, 'OPR': 38.714, 'Auto': 13.835, 'CCWM': 25.914, 'TeamName': 'Campion College'}, {'TeamNum': 22222, 'OPR': 37.852, 'Auto': 4.211, 'CCWM': 9.737, 'TeamName': 'Dominican Republic Incredible FIRST Team (Team DRIFT)'}, {'TeamNum': 22707, 'OPR': 35.84, 'Auto': 5.91, 'CCWM': -7.179, 'TeamName': 'Drones'}, {'TeamNum': 22726, 'OPR': 32.346, 'Auto': 6.909, 'CCWM': 2.061, 'TeamName': 'Alpha Tech'}, {'TeamNum': 22701, 'OPR': 27.712, 'Auto': 14.859, 'CCWM': 30.686, 'TeamName': 'St Jago - Lions'}, {'TeamNum': 16044, 'OPR': 26.992, 'Auto': -1.298, 'CCWM': 16.275, 'TeamName': 'Optimus Pride '}, {'TeamNum': 16076, 'OPR': 20.127, 'Auto': 2.14, 'CCWM': -12.202, 'TeamName': 'MeadowBrook High '}, {'TeamNum': 17852, 'OPR': 19.305, 'Auto': 4.338, 'CCWM': -0.832, 'TeamName': 'Phoenix Requiem'}, {'TeamNum': 16187, 'OPR': 17.861, 'Auto': -6.757, 'CCWM': -22.212, 'TeamName': 'Stingers'}, {'TeamNum': 22755, 'OPR': 14.538, 'Auto': 0.048, 'CCWM': -10.263, 'TeamName': 'Team Circle'}, {'TeamNum': 16081, 'OPR': 13.74, 'Auto': 0.061, 'CCWM': -27.717, 'TeamName': 'STATHS'}, {'TeamNum': 17980, 'OPR': 9.657, 'Auto': 4.902, 'CCWM': -12.576, 'TeamName': 'AISK Hurricane'}, {'TeamNum': 15239, 'OPR': 8.814, 'Auto': -3.357, 'CCWM': -0.657, 'TeamName': "Convent of Mercy Academy 'Alpha'"}, {'TeamNum': 17884, 'OPR': 8.483, 'Auto': 0.748, 'CCWM': 8.612, 'TeamName': 'Lady Bots'}, {'TeamNum': 17853, 'OPR': 7.439, 'Auto': -1.361, 'CCWM': -35.844, 'TeamName': 'Munro College'}, {'TeamNum': 14896, 'OPR': 6.48, 'Auto': 2.006, 'CCWM': -3.322, 'TeamName': 'Knight Bots'}, {'TeamNum': 17878, 'OPR': 5.983, 'Auto': 3.276, 'CCWM': -38.359, 'TeamName': 'Holy Childhood High School'}, {'TeamNum': 17882, 'OPR': 5.626, 'Auto': 0.924, 'CCWM': -21.643, 'TeamName': 'Maggotrons'}, {'TeamNum': 15352, 'OPR': 1.694, 'Auto': 7.165, 'CCWM': -15.725, 'TeamName': 'Team Iterations'}]
i 1068

i 1069
{'23088', '21066', '22949', '23010', '22956', '22934', '23012', '22975', '21058', '23004', '22959', '21062', '23011', '22958', '23085', '22940', '21063', '22908', '22931', '22929', '23056', '19164', '21094', '22801', '23002', '23007'}
[{'TeamNum': 21058, 'OPR': 113.279, 'Auto': 32.724, 'CCWM': 84.574, 'TeamName': 'NIS KYRAN'}, {'TeamNum': 22801, 'OPR': 106.43, 'Auto': 28.542, 'CCWM': 57.089, 'TeamName': 'Bolt.m3'}, {'TeamNum': 21094, 'OPR': 93.888, 'Auto': 19.312, 'CCWM': 28.605, 'TeamName': 'Super Wario Bros'}, {'TeamNum': 23002, 'OPR': 81.229, 'Auto': 23.052, 'CCWM': 72.851, 'TeamName': 'Antidisestablishmentarianists'}, {'TeamNum': 22940, 'OPR': 73.112, 'Auto': 14.88, 'CCWM': 21.053, 'TeamName': 'AENTA'}, {'TeamNum': 19164, 'OPR': 70.752, 'Auto': 18.285, 'CCWM': 52.078, 'TeamName': 'Balga men Shege'}, {'TeamNum': 23011, 'OPR': 70.169, 'Auto': 18.255, 'CCWM': -0.485, 'TeamName': 'Space Vision'}, {'TeamNum': 22908, 'OPR': 59.705, 'Auto': -2.502, 'CCWM': 6.912, 'TeamName': 'INFINITY'}, {'TeamNum': 22931, 'OPR': 54.373, 'Auto': 9.022, 'CCWM': -6.904, 'TeamName': 'Qanaǵattandyrmaushylar'}, {'TeamNum': 21066, 'OPR': 46.484, 'Auto': 7.361, 'CCWM': -51.619, 'TeamName': '5x1'}, {'TeamNum': 22958, 'OPR': 40.992, 'Auto': 3.83, 'CCWM': 24.594, 'TeamName': 'QSTEM TEAM'}, {'TeamNum': 22959, 'OPR': 40.678, 'Auto': 12.633, 'CCWM': 10.851, 'TeamName': 'ADELLAB'}, {'TeamNum': 23088, 'OPR': 36.182, 'Auto': -0.864, 'CCWM': 18.515, 'TeamName': '124'}, {'TeamNum': 22949, 'OPR': 35.347, 'Auto': 1.794, 'CCWM': -27.155, 'TeamName': 'Zerrte.kz'}, {'TeamNum': 22929, 'OPR': 32.991, 'Auto': 5.89, 'CCWM': -18.322, 'TeamName': 'ZETAZERO'}, {'TeamNum': 23056, 'OPR': 30.343, 'Auto': 4.62, 'CCWM': -20.651, 'TeamName': 'Robomix-04'}, {'TeamNum': 23010, 'OPR': 28.884, 'Auto': 0.225, 'CCWM': -1.439, 'TeamName': 'R10'}, {'TeamNum': 22956, 'OPR': 28.363, 'Auto': 11.647, 'CCWM': 6.171, 'TeamName': 'SHUAK'}, {'TeamNum': 22975, 'OPR': 26.124, 'Auto': 3.611, 'CCWM': -18.123, 'TeamName': 'BilOrda'}, {'TeamNum': 22934, 'OPR': 24.993, 'Auto': 2.132, 'CCWM': -3.812, 'TeamName': 'xCellence'}, {'TeamNum': 23007, 'OPR': 21.562, 'Auto': 4.02, 'CCWM': -18.737, 'TeamName': 'Rebels'}, {'TeamNum': 23012, 'OPR': 20.359, 'Auto': 2.139, 'CCWM': -41.794, 'TeamName': 'OrdaBil'}, {'TeamNum': 23085, 'OPR': 14.69, 'Auto': -3.463, 'CCWM': -25.001, 'TeamName': 'Жас Роботшы'}, {'TeamNum': 23004, 'OPR': 11.094, 'Auto': 4.757, 'CCWM': -38.122, 'TeamName': 'Animachine'}, {'TeamNum': 21062, 'OPR': 2.964, 'Auto': -5.818, 'CCWM': -61.368, 'TeamName': 'QUANT'}, {'TeamNum': 21063, 'OPR': 1.513, 'Auto': -3.252, 'CCWM': -49.761, 'TeamName': 'Initium Robotics'}]
KZCMP
[{'TeamNum': 21058, 'OPR': 113.279, 'Auto': 32.724, 'CCWM': 84.574, 'TeamName': 'NIS KYRAN'}, {'TeamNum': 22801, 'OPR': 106.43, 'Auto': 28.542, 'CCWM': 57.089, 'TeamName': 'Bolt.m3'}, {'TeamNum': 21094, 'OPR': 93.888, 'Auto': 19.312, 'CCWM': 28.605, 'TeamName': 'Super Wario Bros'}, {'TeamNum': 23002, 'OPR': 81.229, 'Auto': 23.052, 'CCWM': 72.851, 'TeamName': 'Antidisestablishmentarianists'}, {'TeamNum': 22940, 'OPR': 73.112, 'Auto': 14.88, 'CCWM': 21.053, 'TeamName': 'AENTA'}, {'TeamNum': 19164, 'OPR': 70.752, 'Auto': 18.285, 'CCWM': 52.078, 'TeamName': 'Balga men Shege'}, {'TeamNum': 23011, 'OPR': 70.169, 'Auto': 18.255, 'CCWM': -0.485, 'TeamName': 'Space Vision'}, {'TeamNum': 22908, 'OPR': 59.705, 'Auto': -2.502, 'CCWM': 6.912, 'TeamName': 'INFINITY'}, {'TeamNum': 22931, 'OPR': 54.373, 'Auto': 9.022, 'CCWM': -6.904, 'TeamName': 'Qanaǵattandyrmaushylar'}, {'TeamNum': 21066, 'OPR': 46.484, 'Auto': 7.361, 'CCWM': -51.619, 'TeamName': '5x1'}, {'TeamNum': 22958, 'OPR': 40.992, 'Auto': 3.83, 'CCWM': 24.594, 'TeamName': 'QSTEM TEAM'}, {'TeamNum': 22959, 'OPR': 40.678, 'Auto': 12.633, 'CCWM': 10.851, 'TeamName': 'ADELLAB'}, {'TeamNum': 23088, 'OPR': 36.182, 'Auto': -0.864, 'CCWM': 18.515, 'TeamName': '124'}, {'TeamNum': 22949, 'OPR': 35.347, 'Auto': 1.794, 'CCWM': -27.155, 'TeamName': 'Zerrte.kz'}, {'TeamNum': 22929, 'OPR': 32.991, 'Auto': 5.89, 'CCWM': -18.322, 'TeamName': 'ZETAZERO'}, {'TeamNum': 23056, 'OPR': 30.343, 'Auto': 4.62, 'CCWM': -20.651, 'TeamName': 'Robomix-04'}, {'TeamNum': 23010, 'OPR': 28.884, 'Auto': 0.225, 'CCWM': -1.439, 'TeamName': 'R10'}, {'TeamNum': 22956, 'OPR': 28.363, 'Auto': 11.647, 'CCWM': 6.171, 'TeamName': 'SHUAK'}, {'TeamNum': 22975, 'OPR': 26.124, 'Auto': 3.611, 'CCWM': -18.123, 'TeamName': 'BilOrda'}, {'TeamNum': 22934, 'OPR': 24.993, 'Auto': 2.132, 'CCWM': -3.812, 'TeamName': 'xCellence'}, {'TeamNum': 23007, 'OPR': 21.562, 'Auto': 4.02, 'CCWM': -18.737, 'TeamName': 'Rebels'}, {'TeamNum': 23012, 'OPR': 20.359, 'Auto': 2.139, 'CCWM': -41.794, 'TeamName': 'OrdaBil'}, {'TeamNum': 23085, 'OPR': 14.69, 'Auto': -3.463, 'CCWM': -25.001, 'TeamName': 'Жас Роботшы'}, {'TeamNum': 23004, 'OPR': 11.094, 'Auto': 4.757, 'CCWM': -38.122, 'TeamName': 'Animachine'}, {'TeamNum': 21062, 'OPR': 2.964, 'Auto': -5.818, 'CCWM': -61.368, 'TeamName': 'QUANT'}, {'TeamNum': 21063, 'OPR': 1.513, 'Auto': -3.252, 'CCWM': -49.761, 'TeamName': 'Initium Robotics'}]
i 1070
{'21410', '21653', '22175', '19454', '19361', '19558', '21469', '21413', '21467', '19354', '19349', '18499', '19350', '19294', '21412'}
[{'TeamNum': 19350, 'OPR': 59.969, 'Auto': 17.331, 'CCWM': 34.934, 'TeamName': 'LYBOTICS Insistence Team'}, {'TeamNum': 22175, 'OPR': 47.102, 'Auto': 13.843, 'CCWM': 26.336, 'TeamName': 'Robotya Robotics Team'}, {'TeamNum': 21469, 'OPR': 39.125, 'Auto': 13.468, 'CCWM': 10.396, 'TeamName': 'Migrants Robotics Team'}, {'TeamNum': 19361, 'OPR': 32.221, 'Auto': 25.466, 'CCWM': 17.292, 'TeamName': 'LYBOTICS Balacris Team'}, {'TeamNum': 19294, 'OPR': 31.943, 'Auto': 12.238, 'CCWM': -9.544, 'TeamName': 'LYBOTICS Super Nova Team'}, {'TeamNum': 19558, 'OPR': 28.595, 'Auto': 10.801, 'CCWM': -17.73, 'TeamName': 'People of Determination Robotics Team'}, {'TeamNum': 21410, 'OPR': 25.671, 'Auto': 10.358, 'CCWM': -22.563, 'TeamName': 'Void Robotics Team'}, {'TeamNum': 21412, 'OPR': 23.284, 'Auto': 19.797, 'CCWM': -14.944, 'TeamName': 'LYBOTICS Aces Team'}, {'TeamNum': 21653, 'OPR': 20.823, 'Auto': 1.72, 'CCWM': -11.02, 'TeamName': 'Gifted Center Robotics Team'}, {'TeamNum': 18499, 'OPR': 17.881, 'Auto': 6.814, 'CCWM': 11.86, 'TeamName': 'LYBOTICS Baxter Team'}, {'TeamNum': 21467, 'OPR': 11.863, 'Auto': -2.447, 'CCWM': 0.395, 'TeamName': 'LYBOTICS United Team'}, {'TeamNum': 19454, 'OPR': 10.681, 'Auto': 10.593, 'CCWM': 4.889, 'TeamName': 'LYBOTICS Icons Team'}, {'TeamNum': 19349, 'OPR': 4.696, 'Auto': -1.13, 'CCWM': -1.816, 'TeamName': 'LYBOTICS Wise Team'}, {'TeamNum': 21413, 'OPR': 4.548, 'Auto': 4.252, 'CCWM': -15.577, 'TeamName': 'STEM Girls Robotics Team'}, {'TeamNum': 19354, 'OPR': 2.832, 'Auto': -4.42, 'CCWM': -10.757, 'TeamName': 'Bawader Robotics Team'}]
LYBEQ
[{'TeamNum': 19350, 'OPR': 59.969, 'Auto': 17.331, 'CCWM': 34.934, 'TeamName': 'LYBOTICS Insistence Team'}, {'TeamNum': 22175, 'OPR': 47.102, 'Auto': 13.843, 'CCWM': 26.336, 'TeamName': 'Robotya Robotics Team'}, {'TeamNum': 21469, 'OPR': 39.125, 'Auto': 13.468, 'CCWM': 10.396, 'TeamName': 'Migrants Robotics Team'}, {'TeamNum': 19361, 'OPR': 32.221, 'Auto': 25.466, 'CCWM': 17.292, 'TeamName': 'LYBOTICS Balacris Team'}, {'TeamNum': 19294, 'OPR': 31.943, 'Auto': 12.238, 'CCWM': -9.544, 'TeamName': 'LYBOTICS Super Nova Team'}, {'TeamNum': 19558, 'OPR': 28.595, 'Auto': 10.801, 'CCWM': -17.73, 'TeamName': 'People of Determination Robotics Team'}, {'TeamNum': 21410, 'OPR': 25.671, 'Auto': 10.358, 'CCWM': -22.563, 'TeamName': 'Void Robotics Team'}, {'TeamNum': 21412, 'OPR': 23.284, 'Auto': 19.797, 'CCWM': -14.944, 'TeamName': 'LYBOTICS Aces Team'}, {'TeamNum': 21653, 'OPR': 20.823, 'Auto': 1.72, 'CCWM': -11.02, 'TeamName': 'Gifted Center Robotics Team'}, {'TeamNum': 18499, 'OPR': 17.881, 'Auto': 6.814, 'CCWM': 11.86, 'TeamName': 'LYBOTICS Baxter Team'}, {'TeamNum': 21467, 'OPR': 11.863, 'Auto': -2.447, 'CCWM': 0.395, 'TeamName': 'LYBOTICS United Team'}, {'TeamNum': 19454, 'OPR': 10.681, 'Auto': 10.593, 'CCWM': 4.889, 'TeamName': 'LYBOTICS Icons Team'}, {'TeamNum': 19349, 'OPR': 4.696, 'Auto': -1.13, 'CCWM': -1.816, 'TeamName': 'LYBOTICS Wise Team'}, {'TeamNum': 21413, 'OPR': 4.548, 'Auto': 4.252, 'CCWM': -15.577, 'TeamName': 'STEM Girls Robotics Team'}, {'TeamNum': 19354, 'OPR': 2.832, 'Auto': -4.42, 'CCWM': -10.757, 'TeamName': 'Bawader Robotics Team'}]
i 1071

{'17955', '19146', '21120', '19001', '16771', '18763', '21309', '18736', '22983', '22935', '17133', '22917'}
[{'TeamNum': 18763, 'OPR': 82.829, 'Auto': 33.009, 'CCWM': 75.459, 'TeamName': 'Texpand'}, {'TeamNum': 22983, 'OPR': 54.692, 'Auto': 11.703, 'CCWM': 46.426, 'TeamName': 'How to train your Robot'}, {'TeamNum': 17955, 'OPR': 40.132, 'Auto': 6.481, 'CCWM': 5.074, 'TeamName': 'Astrovo'}, {'TeamNum': 19146, 'OPR': 38.179, 'Auto': 8.06, 'CCWM': -15.604, 'TeamName': 'TigerDroids'}, {'TeamNum': 18736, 'OPR': 37.134, 'Auto': 4.794, 'CCWM': 8.34, 'TeamName': 'Turbo'}, {'TeamNum': 21309, 'OPR': 26.88, 'Auto': -0.965, 'CCWM': 11.69, 'TeamName': 'TekSense'}, {'TeamNum': 22935, 'OPR': 26.632, 'Auto': 0.477, 'CCWM': -15.42, 'TeamName': 'Galactic Einsteins'}, {'TeamNum': 22917, 'OPR': 24.468, 'Auto': 0.853, 'CCWM': -0.826, 'TeamName': 'High Voltage'}, {'TeamNum': 21120, 'OPR': 18.931, 'Auto': 8.085, 'CCWM': -31.234, 'TeamName': 'Generation Innovation'}, {'TeamNum': 17133, 'OPR': 14.734, 'Auto': 7.277, 'CCWM': -11.676, 'TeamName': 'Metagearz'}, {'TeamNum': 19001, 'OPR': 6.171, 'Auto': -2.809, 'CCWM': -52.459, 'TeamName': 'SYRE Robotics Team'}, {'TeamNum': 16771, 'OPR': 2.219, 'Auto': 2.236, 'CCWM': -19.77, 'TeamName': 'Creepy Crawlies'}]
ZACMP1
[{'TeamNum': 18763, 'OPR': 82.829, 'Auto': 33.009, 'CCWM': 75.459, 'TeamName': 'Texpand'}, {'TeamNum': 22983, 'OPR': 54.692, 'Auto': 11.703, 'CCWM': 46.426, 'TeamName': 'How to train your Robot'}, {'TeamNum': 17955, 'OPR': 40.132, 'Auto': 6.481, 'CCWM': 5.074, 'TeamName': 'Astrovo'}, {'TeamNum': 19146, 'OPR': 38.179, 'Auto': 8.06, 'CCWM': -15.604, 'TeamName': 'TigerDroids'}, {'TeamNum': 18736, 'OPR': 37.134, 'Auto': 4.794, 'CCWM': 8.34, 'TeamName': 'Turbo'}, {'TeamNum': 21309, 'OPR': 26.88, 'Auto': -0.965, 'CCWM': 11.69, 'TeamName': 'TekSense'}, {'TeamNum': 22935, 'OPR': 26.632, 'Auto': 0.477, 'CCWM': -15.42, 'TeamName': 'Galactic Einsteins'}, {'TeamNum': 22917, 'OPR': 24.468, 'Auto': 0.853, 'CCWM': -0.826, 'TeamName': 'High Voltage'}, {'TeamNum': 21120, 'OPR': 18.931, 'Auto': 8.085, 'CCWM': -31.234, 'TeamName': 'Generation Innovation'}, {'TeamNum': 17133, 'OPR': 14.734, 'Auto': 7.277, 'CCWM': -11.676, 'TeamName': 'Metagearz'}, {'TeamNum': 19001, 'OPR': 6.171, 'Auto': -2.809, 'CCWM': -52.459, 'TeamName': 'SYRE Robotics Team'}, {'TeamNum': 16771, 'OPR': 2.219, 'Auto': 2.236, 'CCWM': -19.77, 'TeamName': 'Creepy Crawlies'}]
i 1072
{'7209', '8651', '13132', '20088', '14491', '92', '21418', '4964', '14586', '20120', '20087', '10127', '8373', '21509', '6168', '11684', '8417', '9879', '5893', '7842', '17040', '23050', '20979', '9792', '20074'}
[{'TeamNum': 9879, 'OPR': 109.917, 'Auto': 34.793, 'CCWM': 57.333, 'TeamName': 'Root Negative One'}, {'TeamNum': 5893, 'OPR': 101.79, 'Auto': 26.728, 'CCWM': 42.416, 'TeamName': 'Direct Current'}, {'TeamNum': 7842, 'OPR': 101.1, 'Auto': 21.296, 'CCWM': 36.665, 'TeamName': 'Browncoats'}, {'TeamNum': 14491, 'OPR': 99.22, 'Auto': 28.829, 'CCWM': 29.885, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 4964, 'OPR': 91.948, 'Auto': 27.969, 'CCWM': 44.266, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 6168, 'OPR': 87.997, 'Auto': 30.778, 'CCWM': 30.673, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 10127, 'OPR': 79.654, 'Auto': 24.539, 'CCWM': 61.78, 'TeamName': "Tesla's Knights"}, {'TeamNum': 21418, 'OPR': 75.703, 'Auto': 16.873, 'CCWM': 20.982, 'TeamName': 'SeaCow Robotics'}, {'TeamNum': 13132, 'OPR': 74.037, 'Auto': 12.362, 'CCWM': 49.714, 'TeamName': 'Miner Clue'}, {'TeamNum': 7209, 'OPR': 73.79, 'Auto': 33.15, 'CCWM': 35.063, 'TeamName': 'Tech Hogs Robotics  '}, {'TeamNum': 8417, 'OPR': 68.646, 'Auto': 17.508, 'CCWM': 0.634, 'TeamName': "'Lectric Legends"}, {'TeamNum': 14586, 'OPR': 63.326, 'Auto': 10.784, 'CCWM': 5.809, 'TeamName': "Einstein's Cross"}, {'TeamNum': 9792, 'OPR': 60.931, 'Auto': 12.818, 'CCWM': -21.6, 'TeamName': 'GSA RoboNerds'}, {'TeamNum': 92, 'OPR': 59.43, 'Auto': 19.404, 'CCWM': -19.475, 'TeamName': 'Junior Bomb Squad'}, {'TeamNum': 8651, 'OPR': 56.883, 'Auto': 9.296, 'CCWM': 35.385, 'TeamName': 'Wait For It...'}, {'TeamNum': 11684, 'OPR': 49.696, 'Auto': 8.945, 'CCWM': -3.969, 'TeamName': 'GSA Cardinals'}, {'TeamNum': 17040, 'OPR': 47.082, 'Auto': 12.853, 'CCWM': -38.945, 'TeamName': 'The Iron Patriots'}, {'TeamNum': 20979, 'OPR': 40.893, 'Auto': 16.837, 'CCWM': -38.74, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 20087, 'OPR': 30.881, 'Auto': -0.025, 'CCWM': -38.852, 'TeamName': 'B-'}, {'TeamNum': 8373, 'OPR': 17.846, 'Auto': -2.065, 'CCWM': -40.003, 'TeamName': 'Diva Force'}, {'TeamNum': 20088, 'OPR': 17.609, 'Auto': -0.606, 'CCWM': -43.3, 'TeamName': 'Apocalyptic'}, {'TeamNum': 20120, 'OPR': 16.047, 'Auto': 0.839, 'CCWM': -23.162, 'TeamName': 'Encryption'}, {'TeamNum': 23050, 'OPR': 11.294, 'Auto': 5.07, 'CCWM': -70.294, 'TeamName': 'SeaCow Juniors'}, {'TeamNum': 21509, 'OPR': 9.972, 'Auto': 2.303, 'CCWM': -62.981, 'TeamName': 'Robo-Stormers'}, {'TeamNum': 20074, 'OPR': -0.763, 'Auto': -9.125, 'CCWM': -56.36, 'TeamName': 'Kryptonite'}]
USARCMP
[{'TeamNum': 9879, 'OPR': 109.917, 'Auto': 34.793, 'CCWM': 57.333, 'TeamName': 'Root Negative One'}, {'TeamNum': 5893, 'OPR': 101.79, 'Auto': 26.728, 'CCWM': 42.416, 'TeamName': 'Direct Current'}, {'TeamNum': 7842, 'OPR': 101.1, 'Auto': 21.296, 'CCWM': 36.665, 'TeamName': 'Browncoats'}, {'TeamNum': 14491, 'OPR': 99.22, 'Auto': 28.829, 'CCWM': 29.885, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 4964, 'OPR': 91.948, 'Auto': 27.969, 'CCWM': 44.266, 'TeamName': 'Rolla Patriots'}, {'TeamNum': 6168, 'OPR': 87.997, 'Auto': 30.778, 'CCWM': 30.673, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 10127, 'OPR': 79.654, 'Auto': 24.539, 'CCWM': 61.78, 'TeamName': "Tesla's Knights"}, {'TeamNum': 21418, 'OPR': 75.703, 'Auto': 16.873, 'CCWM': 20.982, 'TeamName': 'SeaCow Robotics'}, {'TeamNum': 13132, 'OPR': 74.037, 'Auto': 12.362, 'CCWM': 49.714, 'TeamName': 'Miner Clue'}, {'TeamNum': 7209, 'OPR': 73.79, 'Auto': 33.15, 'CCWM': 35.063, 'TeamName': 'Tech Hogs Robotics  '}, {'TeamNum': 8417, 'OPR': 68.646, 'Auto': 17.508, 'CCWM': 0.634, 'TeamName': "'Lectric Legends"}, {'TeamNum': 14586, 'OPR': 63.326, 'Auto': 10.784, 'CCWM': 5.809, 'TeamName': "Einstein's Cross"}, {'TeamNum': 9792, 'OPR': 60.931, 'Auto': 12.818, 'CCWM': -21.6, 'TeamName': 'GSA RoboNerds'}, {'TeamNum': 92, 'OPR': 59.43, 'Auto': 19.404, 'CCWM': -19.475, 'TeamName': 'Junior Bomb Squad'}, {'TeamNum': 8651, 'OPR': 56.883, 'Auto': 9.296, 'CCWM': 35.385, 'TeamName': 'Wait For It...'}, {'TeamNum': 11684, 'OPR': 49.696, 'Auto': 8.945, 'CCWM': -3.969, 'TeamName': 'GSA Cardinals'}, {'TeamNum': 17040, 'OPR': 47.082, 'Auto': 12.853, 'CCWM': -38.945, 'TeamName': 'The Iron Patriots'}, {'TeamNum': 20979, 'OPR': 40.893, 'Auto': 16.837, 'CCWM': -38.74, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 20087, 'OPR': 30.881, 'Auto': -0.025, 'CCWM': -38.852, 'TeamName': 'B-'}, {'TeamNum': 8373, 'OPR': 17.846, 'Auto': -2.065, 'CCWM': -40.003, 'TeamName': 'Diva Force'}, {'TeamNum': 20088, 'OPR': 17.609, 'Auto': -0.606, 'CCWM': -43.3, 'TeamName': 'Apocalyptic'}, {'TeamNum': 20120, 'OPR': 16.047, 'Auto': 0.839, 'CCWM': -23.162, 'TeamName': 'Encryption'}, {'TeamNum': 23050, 'OPR': 11.294, 'Auto': 5.07, 'CCWM': -70.294, 'TeamName': 'SeaCow Juniors'}, {'TeamNum': 21509, 'OPR': 9.972, 'Auto': 2.303, 'CCWM': -62.981, 'TeamName': 'Robo-Stormers'}, {'TeamNum': 20074, 'OPR': -0.763, 'Auto': -9.125, 'CCWM': -56.36, 'TeamName': 'Kryptonite'}]
i 1073
i 1074
{'11334', '11337', '6282', '21611', '22535', '22549', '10673', '16235', '11332', '22037', '10006', '11333', '9247', '13046', '10298', '11379', '16726', '20381', '16234', '22566', '11336', '11380', '16400', '16401', '11335'}
[{'TeamNum': 6282, 'OPR': 109.091, 'Auto': 24.098, 'CCWM': 56.353, 'TeamName': 'Simi Valley Robotics'}, {'TeamNum': 10298, 'OPR': 94.619, 'Auto': 16.252, 'CCWM': 64.399, 'TeamName': 'Brain Stormz'}, {'TeamNum': 11337, 'OPR': 83.603, 'Auto': 18.161, 'CCWM': 20.775, 'TeamName': 'Robonauts'}, {'TeamNum': 22037, 'OPR': 70.209, 'Auto': 17.885, 'CCWM': 4.598, 'TeamName': 'Z Transformers'}, {'TeamNum': 9247, 'OPR': 59.273, 'Auto': 15.571, 'CCWM': -6.351, 'TeamName': 'Chromium Robotics'}, {'TeamNum': 11334, 'OPR': 52.557, 'Auto': 11.39, 'CCWM': 21.113, 'TeamName': 'Alpha Tech'}, {'TeamNum': 16234, 'OPR': 50.518, 'Auto': 6.839, 'CCWM': -3.653, 'TeamName': 'Tekriot'}, {'TeamNum': 11336, 'OPR': 48.895, 'Auto': 17.696, 'CCWM': 12.405, 'TeamName': 'Red Snow Robotics'}, {'TeamNum': 11380, 'OPR': 48.677, 'Auto': 8.908, 'CCWM': 5.163, 'TeamName': 'Golden Path'}, {'TeamNum': 10006, 'OPR': 43.522, 'Auto': 14.5, 'CCWM': 9.853, 'TeamName': 'Spudnik'}, {'TeamNum': 20381, 'OPR': 43.241, 'Auto': 14.111, 'CCWM': -7.03, 'TeamName': 'Killer Instinct A'}, {'TeamNum': 22566, 'OPR': 40.605, 'Auto': 17.516, 'CCWM': -8.043, 'TeamName': 'Warriors'}, {'TeamNum': 11332, 'OPR': 37.559, 'Auto': 19.861, 'CCWM': -17.215, 'TeamName': 'LASERS'}, {'TeamNum': 22535, 'OPR': 36.417, 'Auto': 4.458, 'CCWM': -24.001, 'TeamName': 'Generation BOT'}, {'TeamNum': 16726, 'OPR': 35.735, 'Auto': 16.177, 'CCWM': -20.033, 'TeamName': 'SavageSpud'}, {'TeamNum': 22549, 'OPR': 35.386, 'Auto': 11.377, 'CCWM': 8.033, 'TeamName': 'EVE'}, {'TeamNum': 11333, 'OPR': 30.621, 'Auto': 12.222, 'CCWM': -15.175, 'TeamName': 'Samurai'}, {'TeamNum': 16400, 'OPR': 24.971, 'Auto': 7.63, 'CCWM': -33.53, 'TeamName': 'Rising Phoenix'}, {'TeamNum': 11335, 'OPR': 20.818, 'Auto': 2.475, 'CCWM': -23.112, 'TeamName': 'Delta Tech'}, {'TeamNum': 10673, 'OPR': 19.478, 'Auto': 3.553, 'CCWM': -1.344, 'TeamName': 'Spudbots'}, {'TeamNum': 16235, 'OPR': 18.729, 'Auto': 7.964, 'CCWM': -8.056, 'TeamName': 'Judicator '}, {'TeamNum': 21611, 'OPR': 18.411, 'Auto': 0.06, 'CCWM': 6.582, 'TeamName': 'General B'}, {'TeamNum': 11379, 'OPR': 17.845, 'Auto': 5.534, 'CCWM': 8.709, 'TeamName': 'PowerOp'}, {'TeamNum': 16401, 'OPR': 12.635, 'Auto': -6.49, 'CCWM': -37.528, 'TeamName': 'The Krakens'}, {'TeamNum': 13046, 'OPR': 8.223, 'Auto': -1.548, 'CCWM': -26.094, 'TeamName': 'Riptide Robotics'}]
USCALADBQ1
[{'TeamNum': 6282, 'OPR': 109.091, 'Auto': 24.098, 'CCWM': 56.353, 'TeamName': 'Simi Valley Robotics'}, {'TeamNum': 10298, 'OPR': 94.619, 'Auto': 16.252, 'CCWM': 64.399, 'TeamName': 'Brain Stormz'}, {'TeamNum': 11337, 'OPR': 83.603, 'Auto': 18.161, 'CCWM': 20.775, 'TeamName': 'Robonauts'}, {'TeamNum': 22037, 'OPR': 70.209, 'Auto': 17.885, 'CCWM': 4.598, 'TeamName': 'Z Transformers'}, {'TeamNum': 9247, 'OPR': 59.273, 'Auto': 15.571, 'CCWM': -6.351, 'TeamName': 'Chromium Robotics'}, {'TeamNum': 11334, 'OPR': 52.557, 'Auto': 11.39, 'CCWM': 21.113, 'TeamName': 'Alpha Tech'}, {'TeamNum': 16234, 'OPR': 50.518, 'Auto': 6.839, 'CCWM': -3.653, 'TeamName': 'Tekriot'}, {'TeamNum': 11336, 'OPR': 48.895, 'Auto': 17.696, 'CCWM': 12.405, 'TeamName': 'Red Snow Robotics'}, {'TeamNum': 11380, 'OPR': 48.677, 'Auto': 8.908, 'CCWM': 5.163, 'TeamName': 'Golden Path'}, {'TeamNum': 10006, 'OPR': 43.522, 'Auto': 14.5, 'CCWM': 9.853, 'TeamName': 'Spudnik'}, {'TeamNum': 20381, 'OPR': 43.241, 'Auto': 14.111, 'CCWM': -7.03, 'TeamName': 'Killer Instinct A'}, {'TeamNum': 22566, 'OPR': 40.605, 'Auto': 17.516, 'CCWM': -8.043, 'TeamName': 'Warriors'}, {'TeamNum': 11332, 'OPR': 37.559, 'Auto': 19.861, 'CCWM': -17.215, 'TeamName': 'LASERS'}, {'TeamNum': 22535, 'OPR': 36.417, 'Auto': 4.458, 'CCWM': -24.001, 'TeamName': 'Generation BOT'}, {'TeamNum': 16726, 'OPR': 35.735, 'Auto': 16.177, 'CCWM': -20.033, 'TeamName': 'SavageSpud'}, {'TeamNum': 22549, 'OPR': 35.386, 'Auto': 11.377, 'CCWM': 8.033, 'TeamName': 'EVE'}, {'TeamNum': 11333, 'OPR': 30.621, 'Auto': 12.222, 'CCWM': -15.175, 'TeamName': 'Samurai'}, {'TeamNum': 16400, 'OPR': 24.971, 'Auto': 7.63, 'CCWM': -33.53, 'TeamName': 'Rising Phoenix'}, {'TeamNum': 11335, 'OPR': 20.818, 'Auto': 2.475, 'CCWM': -23.112, 'TeamName': 'Delta Tech'}, {'TeamNum': 10673, 'OPR': 19.478, 'Auto': 3.553, 'CCWM': -1.344, 'TeamName': 'Spudbots'}, {'TeamNum': 16235, 'OPR': 18.729, 'Auto': 7.964, 'CCWM': -8.056, 'TeamName': 'Judicator '}, {'TeamNum': 21611, 'OPR': 18.411, 'Auto': 0.06, 'CCWM': 6.582, 'TeamName': 'General B'}, {'TeamNum': 11379, 'OPR': 17.845, 'Auto': 5.534, 'CCWM': 8.709, 'TeamName': 'PowerOp'}, {'TeamNum': 16401, 'OPR': 12.635, 'Auto': -6.49, 'CCWM': -37.528, 'TeamName': 'The Krakens'}, {'TeamNum': 13046, 'OPR': 8.223, 'Auto': -1.548, 'CCWM': -26.094, 'TeamName': 'Riptide Robotics'}]

i 1075
{'20486', '20599', '20556', '20540', '20593', '20524', '20597', '20626', '22117', '20520', '20491', '20439', '20500', '20541', '20616', '20526', '22007', '20519'}
[{'TeamNum': 20500, 'OPR': 89.531, 'Auto': 22.473, 'CCWM': 68.581, 'TeamName': 'Bionic Lizards'}, {'TeamNum': 22007, 'OPR': 77.945, 'Auto': 15.149, 'CCWM': 60.954, 'TeamName': 'Romanoid 20489'}, {'TeamNum': 20626, 'OPR': 50.767, 'Auto': 18.872, 'CCWM': 17.202, 'TeamName': 'Sherman Oaks Center for Enriched Studies 1'}, {'TeamNum': 20597, 'OPR': 40.303, 'Auto': 9.001, 'CCWM': 7.7, 'TeamName': 'Palms Gifted / High Ability Magnet 1'}, {'TeamNum': 20486, 'OPR': 39.208, 'Auto': 6.485, 'CCWM': 3.475, 'TeamName': 'Verdugo Hills High School'}, {'TeamNum': 20524, 'OPR': 32.139, 'Auto': 5.381, 'CCWM': 29.05, 'TeamName': 'Valley Academy of Arts and Sciences 1'}, {'TeamNum': 20556, 'OPR': 32.037, 'Auto': 0.017, 'CCWM': 17.29, 'TeamName': 'Dr. Maya Angelou Community High School'}, {'TeamNum': 20491, 'OPR': 31.655, 'Auto': 2.407, 'CCWM': -24.881, 'TeamName': 'Sylmar Leadership Academy'}, {'TeamNum': 20439, 'OPR': 31.332, 'Auto': -0.347, 'CCWM': -15.812, 'TeamName': 'Lake Balboa College Prep'}, {'TeamNum': 20593, 'OPR': 27.554, 'Auto': 6.82, 'CCWM': -21.31, 'TeamName': 'Maywood Center for Enriched Studies 2'}, {'TeamNum': 22117, 'OPR': 27.079, 'Auto': 3.549, 'CCWM': -7.514, 'TeamName': 'Mekanica'}, {'TeamNum': 20519, 'OPR': 25.39, 'Auto': 1.822, 'CCWM': -30.359, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 1'}, {'TeamNum': 20541, 'OPR': 21.79, 'Auto': 7.659, 'CCWM': -8.169, 'TeamName': 'John C. Fremont H.S. 1'}, {'TeamNum': 20540, 'OPR': 21.662, 'Auto': 6.746, 'CCWM': 5.376, 'TeamName': 'John C. Fremont H.S. 2'}, {'TeamNum': 20526, 'OPR': 21.553, 'Auto': 0.211, 'CCWM': -13.102, 'TeamName': 'Lincoln High School 1'}, {'TeamNum': 20520, 'OPR': 15.127, 'Auto': -1.579, 'CCWM': -12.715, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 2'}, {'TeamNum': 20616, 'OPR': 13.211, 'Auto': -2.181, 'CCWM': -45.179, 'TeamName': 'Nathaniel Narbonne High School'}, {'TeamNum': 20599, 'OPR': 9.84, 'Auto': -1.439, 'CCWM': -23.307, 'TeamName': 'Palms Gifted / High Ability Magnet 2'}]
USCALSCMP
[{'TeamNum': 20500, 'OPR': 89.531, 'Auto': 22.473, 'CCWM': 68.581, 'TeamName': 'Bionic Lizards'}, {'TeamNum': 22007, 'OPR': 77.945, 'Auto': 15.149, 'CCWM': 60.954, 'TeamName': 'Romanoid 20489'}, {'TeamNum': 20626, 'OPR': 50.767, 'Auto': 18.872, 'CCWM': 17.202, 'TeamName': 'Sherman Oaks Center for Enriched Studies 1'}, {'TeamNum': 20597, 'OPR': 40.303, 'Auto': 9.001, 'CCWM': 7.7, 'TeamName': 'Palms Gifted / High Ability Magnet 1'}, {'TeamNum': 20486, 'OPR': 39.208, 'Auto': 6.485, 'CCWM': 3.475, 'TeamName': 'Verdugo Hills High School'}, {'TeamNum': 20524, 'OPR': 32.139, 'Auto': 5.381, 'CCWM': 29.05, 'TeamName': 'Valley Academy of Arts and Sciences 1'}, {'TeamNum': 20556, 'OPR': 32.037, 'Auto': 0.017, 'CCWM': 17.29, 'TeamName': 'Dr. Maya Angelou Community High School'}, {'TeamNum': 20491, 'OPR': 31.655, 'Auto': 2.407, 'CCWM': -24.881, 'TeamName': 'Sylmar Leadership Academy'}, {'TeamNum': 20439, 'OPR': 31.332, 'Auto': -0.347, 'CCWM': -15.812, 'TeamName': 'Lake Balboa College Prep'}, {'TeamNum': 20593, 'OPR': 27.554, 'Auto': 6.82, 'CCWM': -21.31, 'TeamName': 'Maywood Center for Enriched Studies 2'}, {'TeamNum': 22117, 'OPR': 27.079, 'Auto': 3.549, 'CCWM': -7.514, 'TeamName': 'Mekanica'}, {'TeamNum': 20519, 'OPR': 25.39, 'Auto': 1.822, 'CCWM': -30.359, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 1'}, {'TeamNum': 20541, 'OPR': 21.79, 'Auto': 7.659, 'CCWM': -8.169, 'TeamName': 'John C. Fremont H.S. 1'}, {'TeamNum': 20540, 'OPR': 21.662, 'Auto': 6.746, 'CCWM': 5.376, 'TeamName': 'John C. Fremont H.S. 2'}, {'TeamNum': 20526, 'OPR': 21.553, 'Auto': 0.211, 'CCWM': -13.102, 'TeamName': 'Lincoln High School 1'}, {'TeamNum': 20520, 'OPR': 15.127, 'Auto': -1.579, 'CCWM': -12.715, 'TeamName': 'Ben Franklin High School and Dual Language Academy Magnet 2'}, {'TeamNum': 20616, 'OPR': 13.211, 'Auto': -2.181, 'CCWM': -45.179, 'TeamName': 'Nathaniel Narbonne High School'}, {'TeamNum': 20599, 'OPR': 9.84, 'Auto': -1.439, 'CCWM': -23.307, 'TeamName': 'Palms Gifted / High Ability Magnet 2'}]
i 1076
{'16287', '7767', '11770', '12997', '358', '19298', '9254', '6325', '20319', '12861', '19866', '9324', '22427', '21786', '21868', '20406', '13125', '11546', '14531', '19299', '3526', '19888', '18253', '20320', '542', '14917', '359', '6436'}
[{'TeamNum': 18253, 'OPR': 127.354, 'Auto': 21.804, 'CCWM': 64.4, 'TeamName': 'Beach Bots'}, {'TeamNum': 7767, 'OPR': 120.802, 'Auto': 19.518, 'CCWM': 57.257, 'TeamName': 'Blueprints'}, {'TeamNum': 12861, 'OPR': 98.438, 'Auto': 15.842, 'CCWM': 1.518, 'TeamName': 'RoboHeroes'}, {'TeamNum': 11546, 'OPR': 86.591, 'Auto': 19.325, 'CCWM': 58.319, 'TeamName': 'BWS Dreamcast'}, {'TeamNum': 3526, 'OPR': 81.355, 'Auto': 19.528, 'CCWM': 14.555, 'TeamName': 'Marlbots'}, {'TeamNum': 11770, 'OPR': 81.068, 'Auto': 16.485, 'CCWM': 42.056, 'TeamName': 'Curiosity'}, {'TeamNum': 19866, 'OPR': 78.862, 'Auto': 10.258, 'CCWM': 36.828, 'TeamName': 'Desert Dwellers'}, {'TeamNum': 21868, 'OPR': 74.182, 'Auto': 24.746, 'CCWM': 19.091, 'TeamName': 'Iconic'}, {'TeamNum': 14531, 'OPR': 73.904, 'Auto': 13.058, 'CCWM': 13.934, 'TeamName': 'The 2nd Rebellion'}, {'TeamNum': 6325, 'OPR': 69.904, 'Auto': 19.581, 'CCWM': 40.311, 'TeamName': 'Aluminati'}, {'TeamNum': 6436, 'OPR': 69.814, 'Auto': 24.337, 'CCWM': 0.887, 'TeamName': 'AlphaGenesis'}, {'TeamNum': 359, 'OPR': 67.671, 'Auto': 6.123, 'CCWM': 30.679, 'TeamName': 'WEBB.exe'}, {'TeamNum': 19888, 'OPR': 60.578, 'Auto': 15.373, 'CCWM': -25.621, 'TeamName': 'Code Alf-a'}, {'TeamNum': 19298, 'OPR': 51.926, 'Auto': 9.987, 'CCWM': 20.501, 'TeamName': 'BV Bulldogs 100'}, {'TeamNum': 9324, 'OPR': 51.73, 'Auto': 20.322, 'CCWM': 7.967, 'TeamName': 'BWS EagleBot'}, {'TeamNum': 21786, 'OPR': 49.847, 'Auto': 5.231, 'CCWM': -39.834, 'TeamName': 'Helios'}, {'TeamNum': 14917, 'OPR': 43.999, 'Auto': 10.546, 'CCWM': 21.585, 'TeamName': 'Asteria'}, {'TeamNum': 20320, 'OPR': 41.291, 'Auto': 5.063, 'CCWM': -11.268, 'TeamName': 'BWS Eaglets'}, {'TeamNum': 16287, 'OPR': 34.52, 'Auto': 21.331, 'CCWM': -53.214, 'TeamName': 'Vistamar 16287'}, {'TeamNum': 9254, 'OPR': 29.652, 'Auto': -0.636, 'CCWM': -29.091, 'TeamName': 'STEM Punks'}, {'TeamNum': 542, 'OPR': 28.206, 'Auto': 19.271, 'CCWM': -71.701, 'TeamName': 'WHS Robotics'}, {'TeamNum': 20406, 'OPR': 25.486, 'Auto': 18.825, 'CCWM': -41.51, 'TeamName': 'BWS *Exhales Aggressively*'}, {'TeamNum': 12997, 'OPR': 22.205, 'Auto': -0.29, 'CCWM': 5.256, 'TeamName': 'Cosmos'}, {'TeamNum': 22427, 'OPR': 9.752, 'Auto': 3.768, 'CCWM': -56.229, 'TeamName': 'BWS MS Boys'}, {'TeamNum': 13125, 'OPR': 8.024, 'Auto': 0.184, 'CCWM': -18.473, 'TeamName': 'BWS Rust in Pieces'}, {'TeamNum': 20319, 'OPR': 3.998, 'Auto': -9.293, 'CCWM': -15.092, 'TeamName': 'BWS Dog in a Box'}, {'TeamNum': 358, 'OPR': -0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Gaulbots'}, {'TeamNum': 19299, 'OPR': -3.704, 'Auto': -4.55, 'CCWM': -74.706, 'TeamName': 'BV Bulldogs 200'}]
USCALADBQ2
[{'TeamNum': 18253, 'OPR': 127.354, 'Auto': 21.804, 'CCWM': 64.4, 'TeamName': 'Beach Bots'}, {'TeamNum': 7767, 'OPR': 120.802, 'Auto': 19.518, 'CCWM': 57.257, 'TeamName': 'Blueprints'}, {'TeamNum': 12861, 'OPR': 98.438, 'Auto': 15.842, 'CCWM': 1.518, 'TeamName': 'RoboHeroes'}, {'TeamNum': 11546, 'OPR': 86.591, 'Auto': 19.325, 'CCWM': 58.319, 'TeamName': 'BWS Dreamcast'}, {'TeamNum': 3526, 'OPR': 81.355, 'Auto': 19.528, 'CCWM': 14.555, 'TeamName': 'Marlbots'}, {'TeamNum': 11770, 'OPR': 81.068, 'Auto': 16.485, 'CCWM': 42.056, 'TeamName': 'Curiosity'}, {'TeamNum': 19866, 'OPR': 78.862, 'Auto': 10.258, 'CCWM': 36.828, 'TeamName': 'Desert Dwellers'}, {'TeamNum': 21868, 'OPR': 74.182, 'Auto': 24.746, 'CCWM': 19.091, 'TeamName': 'Iconic'}, {'TeamNum': 14531, 'OPR': 73.904, 'Auto': 13.058, 'CCWM': 13.934, 'TeamName': 'The 2nd Rebellion'}, {'TeamNum': 6325, 'OPR': 69.904, 'Auto': 19.581, 'CCWM': 40.311, 'TeamName': 'Aluminati'}, {'TeamNum': 6436, 'OPR': 69.814, 'Auto': 24.337, 'CCWM': 0.887, 'TeamName': 'AlphaGenesis'}, {'TeamNum': 359, 'OPR': 67.671, 'Auto': 6.123, 'CCWM': 30.679, 'TeamName': 'WEBB.exe'}, {'TeamNum': 19888, 'OPR': 60.578, 'Auto': 15.373, 'CCWM': -25.621, 'TeamName': 'Code Alf-a'}, {'TeamNum': 19298, 'OPR': 51.926, 'Auto': 9.987, 'CCWM': 20.501, 'TeamName': 'BV Bulldogs 100'}, {'TeamNum': 9324, 'OPR': 51.73, 'Auto': 20.322, 'CCWM': 7.967, 'TeamName': 'BWS EagleBot'}, {'TeamNum': 21786, 'OPR': 49.847, 'Auto': 5.231, 'CCWM': -39.834, 'TeamName': 'Helios'}, {'TeamNum': 14917, 'OPR': 43.999, 'Auto': 10.546, 'CCWM': 21.585, 'TeamName': 'Asteria'}, {'TeamNum': 20320, 'OPR': 41.291, 'Auto': 5.063, 'CCWM': -11.268, 'TeamName': 'BWS Eaglets'}, {'TeamNum': 16287, 'OPR': 34.52, 'Auto': 21.331, 'CCWM': -53.214, 'TeamName': 'Vistamar 16287'}, {'TeamNum': 9254, 'OPR': 29.652, 'Auto': -0.636, 'CCWM': -29.091, 'TeamName': 'STEM Punks'}, {'TeamNum': 542, 'OPR': 28.206, 'Auto': 19.271, 'CCWM': -71.701, 'TeamName': 'WHS Robotics'}, {'TeamNum': 20406, 'OPR': 25.486, 'Auto': 18.825, 'CCWM': -41.51, 'TeamName': 'BWS *Exhales Aggressively*'}, {'TeamNum': 12997, 'OPR': 22.205, 'Auto': -0.29, 'CCWM': 5.256, 'TeamName': 'Cosmos'}, {'TeamNum': 22427, 'OPR': 9.752, 'Auto': 3.768, 'CCWM': -56.229, 'TeamName': 'BWS MS Boys'}, {'TeamNum': 13125, 'OPR': 8.024, 'Auto': 0.184, 'CCWM': -18.473, 'TeamName': 'BWS Rust in Pieces'}, {'TeamNum': 20319, 'OPR': 3.998, 'Auto': -9.293, 'CCWM': -15.092, 'TeamName': 'BWS Dog in a Box'}, {'TeamNum': 358, 'OPR': -0.0, 'Auto': 0.0, 'CCWM': -0.0, 'TeamName': 'Gaulbots'}, {'TeamNum': 19299, 'OPR': -3.704, 'Auto': -4.55, 'CCWM': -74.706, 'TeamName': 'BV Bulldogs 200'}]
i 1077

{'365', '19889', '18739', '4200', '7584', '13467', '14296', '22730', '12880'}
[{'TeamNum': 365, 'OPR': 59.925, 'Auto': 22.082, 'CCWM': 20.101, 'TeamName': 'MOE (The Miracle Workerz)'}, {'TeamNum': 19889, 'OPR': 58.119, 'Auto': 8.252, 'CCWM': 6.037, 'TeamName': 'Robo-Sapiens'}, {'TeamNum': 14296, 'OPR': 57.484, 'Auto': 14.269, 'CCWM': 30.686, 'TeamName': 'Hiller Instinct'}, {'TeamNum': 22730, 'OPR': 53.862, 'Auto': 14.623, 'CCWM': 29.451, 'TeamName': 'Tower Patch Kids'}, {'TeamNum': 7584, 'OPR': 42.287, 'Auto': 10.323, 'CCWM': -18.557, 'TeamName': 'Bad News Bots'}, {'TeamNum': 13467, 'OPR': 34.692, 'Auto': 5.267, 'CCWM': -0.58, 'TeamName': 'Lyrics and Logic'}, {'TeamNum': 18739, 'OPR': 34.426, 'Auto': 0.153, 'CCWM': -16.493, 'TeamName': 'Insert Team Name Here'}, {'TeamNum': 4200, 'OPR': 27.122, 'Auto': -0.879, 'CCWM': -19.633, 'TeamName': 'The X-Squared Factor'}, {'TeamNum': 12880, 'OPR': 20.845, 'Auto': 7.442, 'CCWM': -35.866, 'TeamName': 'Razor Steel Robotics '}]
USDECMP
[{'TeamNum': 365, 'OPR': 59.925, 'Auto': 22.082, 'CCWM': 20.101, 'TeamName': 'MOE (The Miracle Workerz)'}, {'TeamNum': 19889, 'OPR': 58.119, 'Auto': 8.252, 'CCWM': 6.037, 'TeamName': 'Robo-Sapiens'}, {'TeamNum': 14296, 'OPR': 57.484, 'Auto': 14.269, 'CCWM': 30.686, 'TeamName': 'Hiller Instinct'}, {'TeamNum': 22730, 'OPR': 53.862, 'Auto': 14.623, 'CCWM': 29.451, 'TeamName': 'Tower Patch Kids'}, {'TeamNum': 7584, 'OPR': 42.287, 'Auto': 10.323, 'CCWM': -18.557, 'TeamName': 'Bad News Bots'}, {'TeamNum': 13467, 'OPR': 34.692, 'Auto': 5.267, 'CCWM': -0.58, 'TeamName': 'Lyrics and Logic'}, {'TeamNum': 18739, 'OPR': 34.426, 'Auto': 0.153, 'CCWM': -16.493, 'TeamName': 'Insert Team Name Here'}, {'TeamNum': 4200, 'OPR': 27.122, 'Auto': -0.879, 'CCWM': -19.633, 'TeamName': 'The X-Squared Factor'}, {'TeamNum': 12880, 'OPR': 20.845, 'Auto': 7.442, 'CCWM': -35.866, 'TeamName': 'Razor Steel Robotics '}]
i 1078
{'5898', '14393', '14682', '13245', '19571', '17421', '18556', '15173', '7373', '2858', '17694', '4221', '14100', '9206', '16633', '12420', '21721', '1002', '10158', '12995', '14892', '14116', '12689', '14821', '14470', '22023', '5161', '18389', '10219', '4100', '4232', '11347', '16346', '9785', '15500'}
[{'TeamNum': 10158, 'OPR': 119.27, 'Auto': 19.605, 'CCWM': 35.359, 'TeamName': "Scott's Bots"}, {'TeamNum': 12689, 'OPR': 117.309, 'Auto': 18.047, 'CCWM': 43.219, 'TeamName': 'The Sparks'}, {'TeamNum': 1002, 'OPR': 116.036, 'Auto': 18.48, 'CCWM': 50.755, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 19571, 'OPR': 113.382, 'Auto': 19.115, 'CCWM': 32.414, 'TeamName': 'The Robo Brigade'}, {'TeamNum': 17421, 'OPR': 113.159, 'Auto': 11.727, 'CCWM': 53.795, 'TeamName': 'East Jackson Eagles'}, {'TeamNum': 12420, 'OPR': 113.0, 'Auto': 14.776, 'CCWM': 24.77, 'TeamName': 'High Noon'}, {'TeamNum': 18389, 'OPR': 91.201, 'Auto': 16.517, 'CCWM': 19.661, 'TeamName': 'Mary Persons HS1 - "Serverous"'}, {'TeamNum': 15173, 'OPR': 90.508, 'Auto': 12.516, 'CCWM': -14.863, 'TeamName': 'Robotic Eagles'}, {'TeamNum': 9206, 'OPR': 90.394, 'Auto': 20.418, 'CCWM': 44.924, 'TeamName': 'iRobotics'}, {'TeamNum': 14470, 'OPR': 90.044, 'Auto': 24.526, 'CCWM': 35.518, 'TeamName': 'Cascade Robotics'}, {'TeamNum': 4221, 'OPR': 86.152, 'Auto': 5.59, 'CCWM': 54.821, 'TeamName': 'Smíða Syndicate'}, {'TeamNum': 10219, 'OPR': 78.803, 'Auto': 13.019, 'CCWM': 14.905, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 4100, 'OPR': 74.602, 'Auto': 21.164, 'CCWM': -17.914, 'TeamName': 'Darbots 1'}, {'TeamNum': 22023, 'OPR': 73.451, 'Auto': 19.436, 'CCWM': 6.037, 'TeamName': 'System Overload Surgeons'}, {'TeamNum': 14393, 'OPR': 68.136, 'Auto': 29.123, 'CCWM': 9.118, 'TeamName': 'Packer Robotics'}, {'TeamNum': 14821, 'OPR': 66.629, 'Auto': 23.155, 'CCWM': 27.757, 'TeamName': 'Team Rocket'}, {'TeamNum': 12995, 'OPR': 66.295, 'Auto': 22.277, 'CCWM': 6.415, 'TeamName': 'Monkey Wrench Robotics'}, {'TeamNum': 16633, 'OPR': 63.626, 'Auto': 18.424, 'CCWM': 16.295, 'TeamName': 'Bots in Black'}, {'TeamNum': 2858, 'OPR': 63.465, 'Auto': 14.971, 'CCWM': -0.612, 'TeamName': 'Sparbot'}, {'TeamNum': 14682, 'OPR': 63.454, 'Auto': 15.508, 'CCWM': 3.748, 'TeamName': 'Gears & Spears'}, {'TeamNum': 13245, 'OPR': 63.169, 'Auto': 8.415, 'CCWM': -47.414, 'TeamName': 'Arcturus '}, {'TeamNum': 14892, 'OPR': 58.217, 'Auto': 11.242, 'CCWM': -6.633, 'TeamName': 'Venom'}, {'TeamNum': 9785, 'OPR': 57.193, 'Auto': 24.565, 'CCWM': -29.97, 'TeamName': 'Cronos'}, {'TeamNum': 14116, 'OPR': 55.297, 'Auto': 32.888, 'CCWM': -26.116, 'TeamName': 'Walker - Information Overload'}, {'TeamNum': 11347, 'OPR': 52.259, 'Auto': 11.232, 'CCWM': 26.439, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 14100, 'OPR': 49.784, 'Auto': 17.083, 'CCWM': -26.695, 'TeamName': 'High Voltage'}, {'TeamNum': 4232, 'OPR': 44.237, 'Auto': 12.724, 'CCWM': -33.401, 'TeamName': 'Energizer Bunnies'}, {'TeamNum': 5898, 'OPR': 37.745, 'Auto': 4.543, 'CCWM': -31.782, 'TeamName': 'Galactic Lions - Andromeda'}, {'TeamNum': 7373, 'OPR': 35.588, 'Auto': 11.253, 'CCWM': -41.437, 'TeamName': 'Eagle Robotics - Carbon Fiber'}, {'TeamNum': 16346, 'OPR': 33.471, 'Auto': 1.807, 'CCWM': -18.393, 'TeamName': 'Walker - The Notorious B.O.T.'}, {'TeamNum': 17694, 'OPR': 31.865, 'Auto': 10.533, 'CCWM': -25.383, 'TeamName': 'FTC#17694 The Norse Awakens '}, {'TeamNum': 21721, 'OPR': 29.721, 'Auto': 7.074, 'CCWM': -26.524, 'TeamName': 'RoboClovers JV'}, {'TeamNum': 18556, 'OPR': 24.825, 'Auto': 16.945, 'CCWM': -23.834, 'TeamName': 'The Outlets'}, {'TeamNum': 5161, 'OPR': 23.217, 'Auto': 15.214, 'CCWM': -46.22, 'TeamName': 'Eaglemaniacs'}, {'TeamNum': 15500, 'OPR': 0.255, 'Auto': -7.026, 'CCWM': -82.767, 'TeamName': 'Pixelate Gold'}]
USGACMP
[{'TeamNum': 10158, 'OPR': 119.27, 'Auto': 19.605, 'CCWM': 35.359, 'TeamName': "Scott's Bots"}, {'TeamNum': 12689, 'OPR': 117.309, 'Auto': 18.047, 'CCWM': 43.219, 'TeamName': 'The Sparks'}, {'TeamNum': 1002, 'OPR': 116.036, 'Auto': 18.48, 'CCWM': 50.755, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 19571, 'OPR': 113.382, 'Auto': 19.115, 'CCWM': 32.414, 'TeamName': 'The Robo Brigade'}, {'TeamNum': 17421, 'OPR': 113.159, 'Auto': 11.727, 'CCWM': 53.795, 'TeamName': 'East Jackson Eagles'}, {'TeamNum': 12420, 'OPR': 113.0, 'Auto': 14.776, 'CCWM': 24.77, 'TeamName': 'High Noon'}, {'TeamNum': 18389, 'OPR': 91.201, 'Auto': 16.517, 'CCWM': 19.661, 'TeamName': 'Mary Persons HS1 - "Serverous"'}, {'TeamNum': 15173, 'OPR': 90.508, 'Auto': 12.516, 'CCWM': -14.863, 'TeamName': 'Robotic Eagles'}, {'TeamNum': 9206, 'OPR': 90.394, 'Auto': 20.418, 'CCWM': 44.924, 'TeamName': 'iRobotics'}, {'TeamNum': 14470, 'OPR': 90.044, 'Auto': 24.526, 'CCWM': 35.518, 'TeamName': 'Cascade Robotics'}, {'TeamNum': 4221, 'OPR': 86.152, 'Auto': 5.59, 'CCWM': 54.821, 'TeamName': 'Smíða Syndicate'}, {'TeamNum': 10219, 'OPR': 78.803, 'Auto': 13.019, 'CCWM': 14.905, 'TeamName': 'Batteries Not Included'}, {'TeamNum': 4100, 'OPR': 74.602, 'Auto': 21.164, 'CCWM': -17.914, 'TeamName': 'Darbots 1'}, {'TeamNum': 22023, 'OPR': 73.451, 'Auto': 19.436, 'CCWM': 6.037, 'TeamName': 'System Overload Surgeons'}, {'TeamNum': 14393, 'OPR': 68.136, 'Auto': 29.123, 'CCWM': 9.118, 'TeamName': 'Packer Robotics'}, {'TeamNum': 14821, 'OPR': 66.629, 'Auto': 23.155, 'CCWM': 27.757, 'TeamName': 'Team Rocket'}, {'TeamNum': 12995, 'OPR': 66.295, 'Auto': 22.277, 'CCWM': 6.415, 'TeamName': 'Monkey Wrench Robotics'}, {'TeamNum': 16633, 'OPR': 63.626, 'Auto': 18.424, 'CCWM': 16.295, 'TeamName': 'Bots in Black'}, {'TeamNum': 2858, 'OPR': 63.465, 'Auto': 14.971, 'CCWM': -0.612, 'TeamName': 'Sparbot'}, {'TeamNum': 14682, 'OPR': 63.454, 'Auto': 15.508, 'CCWM': 3.748, 'TeamName': 'Gears & Spears'}, {'TeamNum': 13245, 'OPR': 63.169, 'Auto': 8.415, 'CCWM': -47.414, 'TeamName': 'Arcturus '}, {'TeamNum': 14892, 'OPR': 58.217, 'Auto': 11.242, 'CCWM': -6.633, 'TeamName': 'Venom'}, {'TeamNum': 9785, 'OPR': 57.193, 'Auto': 24.565, 'CCWM': -29.97, 'TeamName': 'Cronos'}, {'TeamNum': 14116, 'OPR': 55.297, 'Auto': 32.888, 'CCWM': -26.116, 'TeamName': 'Walker - Information Overload'}, {'TeamNum': 11347, 'OPR': 52.259, 'Auto': 11.232, 'CCWM': 26.439, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 14100, 'OPR': 49.784, 'Auto': 17.083, 'CCWM': -26.695, 'TeamName': 'High Voltage'}, {'TeamNum': 4232, 'OPR': 44.237, 'Auto': 12.724, 'CCWM': -33.401, 'TeamName': 'Energizer Bunnies'}, {'TeamNum': 5898, 'OPR': 37.745, 'Auto': 4.543, 'CCWM': -31.782, 'TeamName': 'Galactic Lions - Andromeda'}, {'TeamNum': 7373, 'OPR': 35.588, 'Auto': 11.253, 'CCWM': -41.437, 'TeamName': 'Eagle Robotics - Carbon Fiber'}, {'TeamNum': 16346, 'OPR': 33.471, 'Auto': 1.807, 'CCWM': -18.393, 'TeamName': 'Walker - The Notorious B.O.T.'}, {'TeamNum': 17694, 'OPR': 31.865, 'Auto': 10.533, 'CCWM': -25.383, 'TeamName': 'FTC#17694 The Norse Awakens '}, {'TeamNum': 21721, 'OPR': 29.721, 'Auto': 7.074, 'CCWM': -26.524, 'TeamName': 'RoboClovers JV'}, {'TeamNum': 18556, 'OPR': 24.825, 'Auto': 16.945, 'CCWM': -23.834, 'TeamName': 'The Outlets'}, {'TeamNum': 5161, 'OPR': 23.217, 'Auto': 15.214, 'CCWM': -46.22, 'TeamName': 'Eaglemaniacs'}, {'TeamNum': 15500, 'OPR': 0.255, 'Auto': -7.026, 'CCWM': -82.767, 'TeamName': 'Pixelate Gold'}]

i 1079
i 1080
{'10091', '10415', '14360', '20674', '9929', '7006', '10635', '3216', '16277', '13699', '19938', '6200', '17576', '15282', '7129', '10836', '9410', '12868', '15005', '3507', '6198', '16244', '14469', '5037', '14401', '19168', '6596', '7715', '10101', '14204', '18523', '17403', '14614', '8620', '10138', '18255', '13365', '18183', '8648', '18529'}
[{'TeamNum': 10138, 'OPR': 152.687, 'Auto': 28.714, 'CCWM': 96.231, 'TeamName': 'Newton Busters'}, {'TeamNum': 18529, 'OPR': 145.218, 'Auto': 40.762, 'CCWM': 80.477, 'TeamName': 'Rust In Piece Robotics'}, {'TeamNum': 14204, 'OPR': 136.761, 'Auto': 37.651, 'CCWM': 115.389, 'TeamName': 'Super Scream Bros'}, {'TeamNum': 14614, 'OPR': 129.948, 'Auto': 30.109, 'CCWM': 64.673, 'TeamName': 'Electro'}, {'TeamNum': 10101, 'OPR': 124.804, 'Auto': 36.947, 'CCWM': 95.8, 'TeamName': 'Binary Bullets'}, {'TeamNum': 8620, 'OPR': 115.701, 'Auto': 37.908, 'CCWM': 88.374, 'TeamName': 'Wormgear Warriors'}, {'TeamNum': 16244, 'OPR': 107.414, 'Auto': 22.7, 'CCWM': 24.527, 'TeamName': 'The TrailBlazers'}, {'TeamNum': 15005, 'OPR': 105.311, 'Auto': 40.389, 'CCWM': 50.937, 'TeamName': 'Technophobia'}, {'TeamNum': 18255, 'OPR': 105.266, 'Auto': 17.568, 'CCWM': 84.555, 'TeamName': 'Stealth Robotics'}, {'TeamNum': 14469, 'OPR': 104.33, 'Auto': 34.586, 'CCWM': -7.96, 'TeamName': 'HOW'}, {'TeamNum': 9929, 'OPR': 102.738, 'Auto': 22.594, 'CCWM': 48.003, 'TeamName': 'TNT (Tech Ninja Team)'}, {'TeamNum': 19168, 'OPR': 100.398, 'Auto': 24.377, 'CCWM': 0.467, 'TeamName': 'TOTUS 1 TUUS'}, {'TeamNum': 7715, 'OPR': 97.925, 'Auto': 33.438, 'CCWM': 30.315, 'TeamName': 'Robotic Lions'}, {'TeamNum': 10836, 'OPR': 92.261, 'Auto': 15.463, 'CCWM': 84.545, 'TeamName': 'STEMper Fi'}, {'TeamNum': 12868, 'OPR': 85.53, 'Auto': 15.88, 'CCWM': 35.247, 'TeamName': 'Ironclad'}, {'TeamNum': 10415, 'OPR': 80.986, 'Auto': 14.153, 'CCWM': -26.883, 'TeamName': 'Warbots'}, {'TeamNum': 10091, 'OPR': 76.273, 'Auto': 29.529, 'CCWM': 21.496, 'TeamName': 'N.Y.A.N. Robotics - Not Your Average Nerds'}, {'TeamNum': 14360, 'OPR': 74.61, 'Auto': 19.055, 'CCWM': -55.184, 'TeamName': 'Sprockets & Screws'}, {'TeamNum': 14401, 'OPR': 73.211, 'Auto': 25.097, 'CCWM': 16.607, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 3216, 'OPR': 72.109, 'Auto': 16.458, 'CCWM': 1.118, 'TeamName': 'Robophins'}, {'TeamNum': 20674, 'OPR': 70.679, 'Auto': 9.748, 'CCWM': -5.539, 'TeamName': 'Ogden Varsity'}, {'TeamNum': 18183, 'OPR': 68.763, 'Auto': 32.962, 'CCWM': -29.89, 'TeamName': 'Rounded Cube'}, {'TeamNum': 9410, 'OPR': 67.746, 'Auto': 10.946, 'CCWM': -38.39, 'TeamName': "Frank's Garage"}, {'TeamNum': 6200, 'OPR': 66.613, 'Auto': 13.751, 'CCWM': 3.443, 'TeamName': 'Despicable Machine '}, {'TeamNum': 17403, 'OPR': 63.699, 'Auto': 14.539, 'CCWM': -23.752, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 7129, 'OPR': 63.525, 'Auto': 5.029, 'CCWM': -55.4, 'TeamName': 'Robo Raiders'}, {'TeamNum': 10635, 'OPR': 56.411, 'Auto': 7.249, 'CCWM': -59.683, 'TeamName': 'Unknown Element'}, {'TeamNum': 16277, 'OPR': 52.821, 'Auto': 17.167, 'CCWM': -77.749, 'TeamName': 'Tekon'}, {'TeamNum': 19938, 'OPR': 51.05, 'Auto': 3.767, 'CCWM': 12.823, 'TeamName': 'Knights of the Ping Pong Table'}, {'TeamNum': 13365, 'OPR': 45.097, 'Auto': 19.881, 'CCWM': -28.843, 'TeamName': 'Gearheads'}, {'TeamNum': 15282, 'OPR': 43.235, 'Auto': 18.406, 'CCWM': -86.044, 'TeamName': 'Bobcats Robotics Varsity'}, {'TeamNum': 18523, 'OPR': 41.992, 'Auto': 18.527, 'CCWM': -51.24, 'TeamName': 'Vertigo'}, {'TeamNum': 5037, 'OPR': 39.011, 'Auto': 6.497, 'CCWM': -51.013, 'TeamName': 'got robot?'}, {'TeamNum': 3507, 'OPR': 29.418, 'Auto': 2.896, 'CCWM': -88.033, 'TeamName': 'Robotheosis'}, {'TeamNum': 7006, 'OPR': 25.997, 'Auto': 7.568, 'CCWM': -69.54, 'TeamName': 'RoboTitans'}, {'TeamNum': 17576, 'OPR': 13.416, 'Auto': 6.628, 'CCWM': -60.291, 'TeamName': 'TITANS (Tomorrow’s Innovators and Thinkers Acquiring New Skills).'}, {'TeamNum': 13699, 'OPR': 9.587, 'Auto': 9.399, 'CCWM': -53.086, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 6198, 'OPR': 7.815, 'Auto': 0.011, 'CCWM': -92.4, 'TeamName': 'Bread Admirers'}, {'TeamNum': 6596, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Robotic Rams'}, {'TeamNum': 8648, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Manual High School RoboRams'}]
USILCMP
[{'TeamNum': 10138, 'OPR': 152.687, 'Auto': 28.714, 'CCWM': 96.231, 'TeamName': 'Newton Busters'}, {'TeamNum': 18529, 'OPR': 145.218, 'Auto': 40.762, 'CCWM': 80.477, 'TeamName': 'Rust In Piece Robotics'}, {'TeamNum': 14204, 'OPR': 136.761, 'Auto': 37.651, 'CCWM': 115.389, 'TeamName': 'Super Scream Bros'}, {'TeamNum': 14614, 'OPR': 129.948, 'Auto': 30.109, 'CCWM': 64.673, 'TeamName': 'Electro'}, {'TeamNum': 10101, 'OPR': 124.804, 'Auto': 36.947, 'CCWM': 95.8, 'TeamName': 'Binary Bullets'}, {'TeamNum': 8620, 'OPR': 115.701, 'Auto': 37.908, 'CCWM': 88.374, 'TeamName': 'Wormgear Warriors'}, {'TeamNum': 16244, 'OPR': 107.414, 'Auto': 22.7, 'CCWM': 24.527, 'TeamName': 'The TrailBlazers'}, {'TeamNum': 15005, 'OPR': 105.311, 'Auto': 40.389, 'CCWM': 50.937, 'TeamName': 'Technophobia'}, {'TeamNum': 18255, 'OPR': 105.266, 'Auto': 17.568, 'CCWM': 84.555, 'TeamName': 'Stealth Robotics'}, {'TeamNum': 14469, 'OPR': 104.33, 'Auto': 34.586, 'CCWM': -7.96, 'TeamName': 'HOW'}, {'TeamNum': 9929, 'OPR': 102.738, 'Auto': 22.594, 'CCWM': 48.003, 'TeamName': 'TNT (Tech Ninja Team)'}, {'TeamNum': 19168, 'OPR': 100.398, 'Auto': 24.377, 'CCWM': 0.467, 'TeamName': 'TOTUS 1 TUUS'}, {'TeamNum': 7715, 'OPR': 97.925, 'Auto': 33.438, 'CCWM': 30.315, 'TeamName': 'Robotic Lions'}, {'TeamNum': 10836, 'OPR': 92.261, 'Auto': 15.463, 'CCWM': 84.545, 'TeamName': 'STEMper Fi'}, {'TeamNum': 12868, 'OPR': 85.53, 'Auto': 15.88, 'CCWM': 35.247, 'TeamName': 'Ironclad'}, {'TeamNum': 10415, 'OPR': 80.986, 'Auto': 14.153, 'CCWM': -26.883, 'TeamName': 'Warbots'}, {'TeamNum': 10091, 'OPR': 76.273, 'Auto': 29.529, 'CCWM': 21.496, 'TeamName': 'N.Y.A.N. Robotics - Not Your Average Nerds'}, {'TeamNum': 14360, 'OPR': 74.61, 'Auto': 19.055, 'CCWM': -55.184, 'TeamName': 'Sprockets & Screws'}, {'TeamNum': 14401, 'OPR': 73.211, 'Auto': 25.097, 'CCWM': 16.607, 'TeamName': 'Wildcat Robotics'}, {'TeamNum': 3216, 'OPR': 72.109, 'Auto': 16.458, 'CCWM': 1.118, 'TeamName': 'Robophins'}, {'TeamNum': 20674, 'OPR': 70.679, 'Auto': 9.748, 'CCWM': -5.539, 'TeamName': 'Ogden Varsity'}, {'TeamNum': 18183, 'OPR': 68.763, 'Auto': 32.962, 'CCWM': -29.89, 'TeamName': 'Rounded Cube'}, {'TeamNum': 9410, 'OPR': 67.746, 'Auto': 10.946, 'CCWM': -38.39, 'TeamName': "Frank's Garage"}, {'TeamNum': 6200, 'OPR': 66.613, 'Auto': 13.751, 'CCWM': 3.443, 'TeamName': 'Despicable Machine '}, {'TeamNum': 17403, 'OPR': 63.699, 'Auto': 14.539, 'CCWM': -23.752, 'TeamName': 'LP Roarbotics'}, {'TeamNum': 7129, 'OPR': 63.525, 'Auto': 5.029, 'CCWM': -55.4, 'TeamName': 'Robo Raiders'}, {'TeamNum': 10635, 'OPR': 56.411, 'Auto': 7.249, 'CCWM': -59.683, 'TeamName': 'Unknown Element'}, {'TeamNum': 16277, 'OPR': 52.821, 'Auto': 17.167, 'CCWM': -77.749, 'TeamName': 'Tekon'}, {'TeamNum': 19938, 'OPR': 51.05, 'Auto': 3.767, 'CCWM': 12.823, 'TeamName': 'Knights of the Ping Pong Table'}, {'TeamNum': 13365, 'OPR': 45.097, 'Auto': 19.881, 'CCWM': -28.843, 'TeamName': 'Gearheads'}, {'TeamNum': 15282, 'OPR': 43.235, 'Auto': 18.406, 'CCWM': -86.044, 'TeamName': 'Bobcats Robotics Varsity'}, {'TeamNum': 18523, 'OPR': 41.992, 'Auto': 18.527, 'CCWM': -51.24, 'TeamName': 'Vertigo'}, {'TeamNum': 5037, 'OPR': 39.011, 'Auto': 6.497, 'CCWM': -51.013, 'TeamName': 'got robot?'}, {'TeamNum': 3507, 'OPR': 29.418, 'Auto': 2.896, 'CCWM': -88.033, 'TeamName': 'Robotheosis'}, {'TeamNum': 7006, 'OPR': 25.997, 'Auto': 7.568, 'CCWM': -69.54, 'TeamName': 'RoboTitans'}, {'TeamNum': 17576, 'OPR': 13.416, 'Auto': 6.628, 'CCWM': -60.291, 'TeamName': 'TITANS (Tomorrow’s Innovators and Thinkers Acquiring New Skills).'}, {'TeamNum': 13699, 'OPR': 9.587, 'Auto': 9.399, 'CCWM': -53.086, 'TeamName': 'RoboGrizzlies'}, {'TeamNum': 6198, 'OPR': 7.815, 'Auto': 0.011, 'CCWM': -92.4, 'TeamName': 'Bread Admirers'}, {'TeamNum': 6596, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Robotic Rams'}, {'TeamNum': 8648, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Manual High School RoboRams'}]

i 1081
{'20430', '19932', '14954', '22068', '8971', '11329', '15455', '22138', '535', '22444', '13295', '3537', '13246', '6518', '13377', '14596', '8793', '11272', '18174', '21945', '12014', '18505', '16501', '9864', '13414', '17994', '19366', '8149'}
[{'TeamNum': 11329, 'OPR': 151.095, 'Auto': 40.03, 'CCWM': 100.665, 'TeamName': 'I.C.E. Robotics'}, {'TeamNum': 9864, 'OPR': 112.168, 'Auto': 27.808, 'CCWM': 58.302, 'TeamName': 'Jug Rox Robotix'}, {'TeamNum': 16501, 'OPR': 105.648, 'Auto': 18.893, 'CCWM': 75.434, 'TeamName': 'Squirrel!'}, {'TeamNum': 11272, 'OPR': 105.214, 'Auto': 17.634, 'CCWM': 61.448, 'TeamName': 'Genesis '}, {'TeamNum': 20430, 'OPR': 93.868, 'Auto': 15.57, 'CCWM': 45.868, 'TeamName': 'Heroes'}, {'TeamNum': 13377, 'OPR': 87.8, 'Auto': 12.773, 'CCWM': 29.691, 'TeamName': 'Blackout'}, {'TeamNum': 3537, 'OPR': 80.952, 'Auto': 28.551, 'CCWM': 18.157, 'TeamName': 'The MechaHamsters'}, {'TeamNum': 18505, 'OPR': 78.556, 'Auto': 21.374, 'CCWM': 1.612, 'TeamName': 'Something to do with Waffles'}, {'TeamNum': 8149, 'OPR': 76.859, 'Auto': 25.85, 'CCWM': 3.694, 'TeamName': 'Red Alert: Panic in the Build Room'}, {'TeamNum': 14954, 'OPR': 75.372, 'Auto': 24.443, 'CCWM': 17.838, 'TeamName': 'The Glorious Roborioles'}, {'TeamNum': 12014, 'OPR': 71.842, 'Auto': 14.8, 'CCWM': -31.206, 'TeamName': 'FireWires'}, {'TeamNum': 8971, 'OPR': 70.222, 'Auto': 28.62, 'CCWM': 4.516, 'TeamName': 'Diamond Blades'}, {'TeamNum': 14596, 'OPR': 69.66, 'Auto': 14.9, 'CCWM': -15.261, 'TeamName': 'XLR8'}, {'TeamNum': 13414, 'OPR': 62.282, 'Auto': 18.666, 'CCWM': -27.132, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 15455, 'OPR': 59.005, 'Auto': 15.277, 'CCWM': 31.719, 'TeamName': 'The Classy Roborioles'}, {'TeamNum': 6518, 'OPR': 56.103, 'Auto': 18.893, 'CCWM': -22.395, 'TeamName': 'Westside Black'}, {'TeamNum': 21945, 'OPR': 51.934, 'Auto': 21.663, 'CCWM': -44.266, 'TeamName': 'The Majestic Roborioles'}, {'TeamNum': 22444, 'OPR': 51.716, 'Auto': 9.097, 'CCWM': -1.39, 'TeamName': 'Revelation'}, {'TeamNum': 535, 'OPR': 50.838, 'Auto': 9.138, 'CCWM': -20.286, 'TeamName': 'TOBOR'}, {'TeamNum': 18174, 'OPR': 47.659, 'Auto': 16.784, 'CCWM': 19.336, 'TeamName': 'MISHines'}, {'TeamNum': 13246, 'OPR': 47.053, 'Auto': 8.932, 'CCWM': -19.978, 'TeamName': 'Steel Beaks'}, {'TeamNum': 13295, 'OPR': 46.969, 'Auto': 15.434, 'CCWM': 12.509, 'TeamName': 'Red Alert: Disaster Management'}, {'TeamNum': 8793, 'OPR': 44.706, 'Auto': 18.554, 'CCWM': -53.265, 'TeamName': 'Wired Woodmen'}, {'TeamNum': 22068, 'OPR': 44.386, 'Auto': 22.588, 'CCWM': -46.339, 'TeamName': 'Short Circuit'}, {'TeamNum': 19366, 'OPR': 40.9, 'Auto': 7.762, 'CCWM': -55.262, 'TeamName': 'CTF'}, {'TeamNum': 19932, 'OPR': 40.641, 'Auto': 20.607, 'CCWM': -34.522, 'TeamName': 'Westside Red'}, {'TeamNum': 17994, 'OPR': 19.298, 'Auto': -4.175, 'CCWM': -30.499, 'TeamName': 'Ragnabotics'}, {'TeamNum': 22138, 'OPR': 6.253, 'Auto': -15.068, 'CCWM': -78.986, 'TeamName': 'Talos'}]
USINCMP
[{'TeamNum': 11329, 'OPR': 151.095, 'Auto': 40.03, 'CCWM': 100.665, 'TeamName': 'I.C.E. Robotics'}, {'TeamNum': 9864, 'OPR': 112.168, 'Auto': 27.808, 'CCWM': 58.302, 'TeamName': 'Jug Rox Robotix'}, {'TeamNum': 16501, 'OPR': 105.648, 'Auto': 18.893, 'CCWM': 75.434, 'TeamName': 'Squirrel!'}, {'TeamNum': 11272, 'OPR': 105.214, 'Auto': 17.634, 'CCWM': 61.448, 'TeamName': 'Genesis '}, {'TeamNum': 20430, 'OPR': 93.868, 'Auto': 15.57, 'CCWM': 45.868, 'TeamName': 'Heroes'}, {'TeamNum': 13377, 'OPR': 87.8, 'Auto': 12.773, 'CCWM': 29.691, 'TeamName': 'Blackout'}, {'TeamNum': 3537, 'OPR': 80.952, 'Auto': 28.551, 'CCWM': 18.157, 'TeamName': 'The MechaHamsters'}, {'TeamNum': 18505, 'OPR': 78.556, 'Auto': 21.374, 'CCWM': 1.612, 'TeamName': 'Something to do with Waffles'}, {'TeamNum': 8149, 'OPR': 76.859, 'Auto': 25.85, 'CCWM': 3.694, 'TeamName': 'Red Alert: Panic in the Build Room'}, {'TeamNum': 14954, 'OPR': 75.372, 'Auto': 24.443, 'CCWM': 17.838, 'TeamName': 'The Glorious Roborioles'}, {'TeamNum': 12014, 'OPR': 71.842, 'Auto': 14.8, 'CCWM': -31.206, 'TeamName': 'FireWires'}, {'TeamNum': 8971, 'OPR': 70.222, 'Auto': 28.62, 'CCWM': 4.516, 'TeamName': 'Diamond Blades'}, {'TeamNum': 14596, 'OPR': 69.66, 'Auto': 14.9, 'CCWM': -15.261, 'TeamName': 'XLR8'}, {'TeamNum': 13414, 'OPR': 62.282, 'Auto': 18.666, 'CCWM': -27.132, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 15455, 'OPR': 59.005, 'Auto': 15.277, 'CCWM': 31.719, 'TeamName': 'The Classy Roborioles'}, {'TeamNum': 6518, 'OPR': 56.103, 'Auto': 18.893, 'CCWM': -22.395, 'TeamName': 'Westside Black'}, {'TeamNum': 21945, 'OPR': 51.934, 'Auto': 21.663, 'CCWM': -44.266, 'TeamName': 'The Majestic Roborioles'}, {'TeamNum': 22444, 'OPR': 51.716, 'Auto': 9.097, 'CCWM': -1.39, 'TeamName': 'Revelation'}, {'TeamNum': 535, 'OPR': 50.838, 'Auto': 9.138, 'CCWM': -20.286, 'TeamName': 'TOBOR'}, {'TeamNum': 18174, 'OPR': 47.659, 'Auto': 16.784, 'CCWM': 19.336, 'TeamName': 'MISHines'}, {'TeamNum': 13246, 'OPR': 47.053, 'Auto': 8.932, 'CCWM': -19.978, 'TeamName': 'Steel Beaks'}, {'TeamNum': 13295, 'OPR': 46.969, 'Auto': 15.434, 'CCWM': 12.509, 'TeamName': 'Red Alert: Disaster Management'}, {'TeamNum': 8793, 'OPR': 44.706, 'Auto': 18.554, 'CCWM': -53.265, 'TeamName': 'Wired Woodmen'}, {'TeamNum': 22068, 'OPR': 44.386, 'Auto': 22.588, 'CCWM': -46.339, 'TeamName': 'Short Circuit'}, {'TeamNum': 19366, 'OPR': 40.9, 'Auto': 7.762, 'CCWM': -55.262, 'TeamName': 'CTF'}, {'TeamNum': 19932, 'OPR': 40.641, 'Auto': 20.607, 'CCWM': -34.522, 'TeamName': 'Westside Red'}, {'TeamNum': 17994, 'OPR': 19.298, 'Auto': -4.175, 'CCWM': -30.499, 'TeamName': 'Ragnabotics'}, {'TeamNum': 22138, 'OPR': 6.253, 'Auto': -15.068, 'CCWM': -78.986, 'TeamName': 'Talos'}]
i 1082
{'9848', '17377', '15458', '17186', '20719', '17036', '7149', '22050', '14498', '9533', '6037', '20204', '13747', '18241', '20205', '21480', '16740', '5387', '12441'}
[{'TeamNum': 7149, 'OPR': 123.074, 'Auto': 24.643, 'CCWM': 103.411, 'TeamName': 'ENFORCERS'}, {'TeamNum': 17036, 'OPR': 100.975, 'Auto': 25.821, 'CCWM': 88.573, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 18241, 'OPR': 67.941, 'Auto': 27.509, 'CCWM': 25.839, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 22050, 'OPR': 60.37, 'Auto': 11.627, 'CCWM': 29.71, 'TeamName': 'Pirate Robotics'}, {'TeamNum': 6037, 'OPR': 58.149, 'Auto': 18.839, 'CCWM': -1.795, 'TeamName': 'W.A.G.S. (We Are Girl Scouts) Robotics'}, {'TeamNum': 9533, 'OPR': 56.25, 'Auto': 22.704, 'CCWM': -10.966, 'TeamName': 'Bravenators'}, {'TeamNum': 13747, 'OPR': 55.566, 'Auto': 17.084, 'CCWM': 20.386, 'TeamName': 'Techtronic Challengers'}, {'TeamNum': 20204, 'OPR': 54.475, 'Auto': 7.944, 'CCWM': -6.397, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 12441, 'OPR': 49.918, 'Auto': 8.927, 'CCWM': 13.685, 'TeamName': 'C.V.T.D.'}, {'TeamNum': 17186, 'OPR': 48.283, 'Auto': 8.85, 'CCWM': 20.664, 'TeamName': 'Falcons'}, {'TeamNum': 20205, 'OPR': 45.03, 'Auto': 4.902, 'CCWM': 2.097, 'TeamName': 'Chaotic Pioneers'}, {'TeamNum': 5387, 'OPR': 44.903, 'Auto': 14.249, 'CCWM': -13.826, 'TeamName': 'TecHounds'}, {'TeamNum': 15458, 'OPR': 38.943, 'Auto': 3.733, 'CCWM': -18.479, 'TeamName': 'Green Machine'}, {'TeamNum': 20719, 'OPR': 36.185, 'Auto': 15.782, 'CCWM': -12.697, 'TeamName': 'Paul VI Robotics II'}, {'TeamNum': 9848, 'OPR': 34.178, 'Auto': 11.122, 'CCWM': -7.285, 'TeamName': 'GearView'}, {'TeamNum': 17377, 'OPR': 18.005, 'Auto': 5.158, 'CCWM': -43.332, 'TeamName': 'Pennsauken Robotics'}, {'TeamNum': 14498, 'OPR': 9.544, 'Auto': -10.751, 'CCWM': -75.644, 'TeamName': 'Robotech Warriors'}, {'TeamNum': 16740, 'OPR': 7.901, 'Auto': -0.268, 'CCWM': -44.281, 'TeamName': 'Paul VI Robotics'}, {'TeamNum': 21480, 'OPR': -0.002, 'Auto': 0.309, 'CCWM': -73.739, 'TeamName': 'C3 Loco-Motors'}]
USNJSOLT2
[{'TeamNum': 7149, 'OPR': 123.074, 'Auto': 24.643, 'CCWM': 103.411, 'TeamName': 'ENFORCERS'}, {'TeamNum': 17036, 'OPR': 100.975, 'Auto': 25.821, 'CCWM': 88.573, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 18241, 'OPR': 67.941, 'Auto': 27.509, 'CCWM': 25.839, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 22050, 'OPR': 60.37, 'Auto': 11.627, 'CCWM': 29.71, 'TeamName': 'Pirate Robotics'}, {'TeamNum': 6037, 'OPR': 58.149, 'Auto': 18.839, 'CCWM': -1.795, 'TeamName': 'W.A.G.S. (We Are Girl Scouts) Robotics'}, {'TeamNum': 9533, 'OPR': 56.25, 'Auto': 22.704, 'CCWM': -10.966, 'TeamName': 'Bravenators'}, {'TeamNum': 13747, 'OPR': 55.566, 'Auto': 17.084, 'CCWM': 20.386, 'TeamName': 'Techtronic Challengers'}, {'TeamNum': 20204, 'OPR': 54.475, 'Auto': 7.944, 'CCWM': -6.397, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 12441, 'OPR': 49.918, 'Auto': 8.927, 'CCWM': 13.685, 'TeamName': 'C.V.T.D.'}, {'TeamNum': 17186, 'OPR': 48.283, 'Auto': 8.85, 'CCWM': 20.664, 'TeamName': 'Falcons'}, {'TeamNum': 20205, 'OPR': 45.03, 'Auto': 4.902, 'CCWM': 2.097, 'TeamName': 'Chaotic Pioneers'}, {'TeamNum': 5387, 'OPR': 44.903, 'Auto': 14.249, 'CCWM': -13.826, 'TeamName': 'TecHounds'}, {'TeamNum': 15458, 'OPR': 38.943, 'Auto': 3.733, 'CCWM': -18.479, 'TeamName': 'Green Machine'}, {'TeamNum': 20719, 'OPR': 36.185, 'Auto': 15.782, 'CCWM': -12.697, 'TeamName': 'Paul VI Robotics II'}, {'TeamNum': 9848, 'OPR': 34.178, 'Auto': 11.122, 'CCWM': -7.285, 'TeamName': 'GearView'}, {'TeamNum': 17377, 'OPR': 18.005, 'Auto': 5.158, 'CCWM': -43.332, 'TeamName': 'Pennsauken Robotics'}, {'TeamNum': 14498, 'OPR': 9.544, 'Auto': -10.751, 'CCWM': -75.644, 'TeamName': 'Robotech Warriors'}, {'TeamNum': 16740, 'OPR': 7.901, 'Auto': -0.268, 'CCWM': -44.281, 'TeamName': 'Paul VI Robotics'}, {'TeamNum': 21480, 'OPR': -0.002, 'Auto': 0.309, 'CCWM': -73.739, 'TeamName': 'C3 Loco-Motors'}]

i 1083
{'13293', '15891', '12853', '20848', '13617', '12309', '7251', '4215', '6983', '11124', '207', '251', '13048', '4328', '13970', '15762', '19477', '15147', '15715', '15887', '13615'}
[{'TeamNum': 13615, 'OPR': 108.644, 'Auto': 23.054, 'CCWM': 35.462, 'TeamName': 'RoboRams'}, {'TeamNum': 4215, 'OPR': 79.085, 'Auto': 21.792, 'CCWM': 26.805, 'TeamName': 'Hypnotic Robotics'}, {'TeamNum': 207, 'OPR': 77.153, 'Auto': 17.28, 'CCWM': 29.726, 'TeamName': 'Critical Mass'}, {'TeamNum': 15762, 'OPR': 76.791, 'Auto': 13.756, 'CCWM': 38.345, 'TeamName': 'Frisch CouGears'}, {'TeamNum': 19477, 'OPR': 76.771, 'Auto': 19.883, 'CCWM': 45.54, 'TeamName': 'Bit by Bit'}, {'TeamNum': 15891, 'OPR': 74.357, 'Auto': 6.526, 'CCWM': 72.558, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 7251, 'OPR': 67.493, 'Auto': 23.948, 'CCWM': 11.296, 'TeamName': 'Comets'}, {'TeamNum': 15887, 'OPR': 56.521, 'Auto': 10.791, 'CCWM': 29.479, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 12309, 'OPR': 48.444, 'Auto': 9.503, 'CCWM': 24.05, 'TeamName': 'Wood-Ridge Spartans'}, {'TeamNum': 15715, 'OPR': 45.792, 'Auto': 0.288, 'CCWM': 3.301, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 13617, 'OPR': 45.622, 'Auto': 10.798, 'CCWM': 23.846, 'TeamName': 'Bectobots'}, {'TeamNum': 15147, 'OPR': 38.762, 'Auto': 6.778, 'CCWM': -17.464, 'TeamName': 'Owltrons'}, {'TeamNum': 13048, 'OPR': 37.639, 'Auto': 6.246, 'CCWM': 0.339, 'TeamName': 'Absolute Zero'}, {'TeamNum': 13293, 'OPR': 37.376, 'Auto': 14.759, 'CCWM': 3.751, 'TeamName': 'PRowlers'}, {'TeamNum': 6983, 'OPR': 33.693, 'Auto': 6.686, 'CCWM': 8.182, 'TeamName': 'CouGEARS'}, {'TeamNum': 13970, 'OPR': 29.312, 'Auto': 6.472, 'CCWM': -47.382, 'TeamName': 'Anjoules'}, {'TeamNum': 251, 'OPR': 25.726, 'Auto': -2.395, 'CCWM': -31.735, 'TeamName': 'Mech-alodons'}, {'TeamNum': 20848, 'OPR': 18.592, 'Auto': 10.495, 'CCWM': -42.193, 'TeamName': 'Tiger-Bots'}, {'TeamNum': 4328, 'OPR': 4.842, 'Auto': 1.107, 'CCWM': -54.942, 'TeamName': "C'est la vie"}, {'TeamNum': 12853, 'OPR': 3.772, 'Auto': -6.546, 'CCWM': -87.938, 'TeamName': 'Robo Cavos'}, {'TeamNum': 11124, 'OPR': -17.697, 'Auto': -1.328, 'CCWM': -64.152, 'TeamName': 'Angelbots'}]
USNJNOLT2
[{'TeamNum': 13615, 'OPR': 108.644, 'Auto': 23.054, 'CCWM': 35.462, 'TeamName': 'RoboRams'}, {'TeamNum': 4215, 'OPR': 79.085, 'Auto': 21.792, 'CCWM': 26.805, 'TeamName': 'Hypnotic Robotics'}, {'TeamNum': 207, 'OPR': 77.153, 'Auto': 17.28, 'CCWM': 29.726, 'TeamName': 'Critical Mass'}, {'TeamNum': 15762, 'OPR': 76.791, 'Auto': 13.756, 'CCWM': 38.345, 'TeamName': 'Frisch CouGears'}, {'TeamNum': 19477, 'OPR': 76.771, 'Auto': 19.883, 'CCWM': 45.54, 'TeamName': 'Bit by Bit'}, {'TeamNum': 15891, 'OPR': 74.357, 'Auto': 6.526, 'CCWM': 72.558, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 7251, 'OPR': 67.493, 'Auto': 23.948, 'CCWM': 11.296, 'TeamName': 'Comets'}, {'TeamNum': 15887, 'OPR': 56.521, 'Auto': 10.791, 'CCWM': 29.479, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 12309, 'OPR': 48.444, 'Auto': 9.503, 'CCWM': 24.05, 'TeamName': 'Wood-Ridge Spartans'}, {'TeamNum': 15715, 'OPR': 45.792, 'Auto': 0.288, 'CCWM': 3.301, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 13617, 'OPR': 45.622, 'Auto': 10.798, 'CCWM': 23.846, 'TeamName': 'Bectobots'}, {'TeamNum': 15147, 'OPR': 38.762, 'Auto': 6.778, 'CCWM': -17.464, 'TeamName': 'Owltrons'}, {'TeamNum': 13048, 'OPR': 37.639, 'Auto': 6.246, 'CCWM': 0.339, 'TeamName': 'Absolute Zero'}, {'TeamNum': 13293, 'OPR': 37.376, 'Auto': 14.759, 'CCWM': 3.751, 'TeamName': 'PRowlers'}, {'TeamNum': 6983, 'OPR': 33.693, 'Auto': 6.686, 'CCWM': 8.182, 'TeamName': 'CouGEARS'}, {'TeamNum': 13970, 'OPR': 29.312, 'Auto': 6.472, 'CCWM': -47.382, 'TeamName': 'Anjoules'}, {'TeamNum': 251, 'OPR': 25.726, 'Auto': -2.395, 'CCWM': -31.735, 'TeamName': 'Mech-alodons'}, {'TeamNum': 20848, 'OPR': 18.592, 'Auto': 10.495, 'CCWM': -42.193, 'TeamName': 'Tiger-Bots'}, {'TeamNum': 4328, 'OPR': 4.842, 'Auto': 1.107, 'CCWM': -54.942, 'TeamName': "C'est la vie"}, {'TeamNum': 12853, 'OPR': 3.772, 'Auto': -6.546, 'CCWM': -87.938, 'TeamName': 'Robo Cavos'}, {'TeamNum': 11124, 'OPR': -17.697, 'Auto': -1.328, 'CCWM': -64.152, 'TeamName': 'Angelbots'}]
i 1084
{'18274', '18410', '7242', '18802', '7163', '19668', '19901', '5553', '13709', '11572', '11240', '4155', '10355', '8825', '13806', '3638', '7506', '17035', '4250', '6042', '16426', '4266', '21684', '5141', '8866', '18577', '19563', '14906', '16505', '11354'}
[{'TeamNum': 10355, 'OPR': 103.055, 'Auto': 23.076, 'CCWM': 58.661, 'TeamName': 'Project Peacock'}, {'TeamNum': 7242, 'OPR': 98.686, 'Auto': 22.359, 'CCWM': 13.614, 'TeamName': 'BC Robocats'}, {'TeamNum': 5553, 'OPR': 96.92, 'Auto': 31.723, 'CCWM': -0.61, 'TeamName': 'RoboComets'}, {'TeamNum': 18274, 'OPR': 94.025, 'Auto': 24.531, 'CCWM': 66.113, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 11354, 'OPR': 91.431, 'Auto': 20.459, 'CCWM': 22.904, 'TeamName': 'The Midnight Ostrich Runners'}, {'TeamNum': 13806, 'OPR': 90.741, 'Auto': 28.813, 'CCWM': 52.788, 'TeamName': 'Project Agnizab'}, {'TeamNum': 4250, 'OPR': 90.059, 'Auto': 28.282, 'CCWM': 10.359, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 8866, 'OPR': 88.069, 'Auto': 23.951, 'CCWM': 3.807, 'TeamName': 'Cybernetics'}, {'TeamNum': 17035, 'OPR': 86.375, 'Auto': 22.631, 'CCWM': 21.016, 'TeamName': 'Knightmares'}, {'TeamNum': 7506, 'OPR': 84.862, 'Auto': 17.044, 'CCWM': -10.695, 'TeamName': 'System Overload'}, {'TeamNum': 11572, 'OPR': 83.137, 'Auto': 12.071, 'CCWM': 23.736, 'TeamName': 'Mouse Spit'}, {'TeamNum': 4155, 'OPR': 79.942, 'Auto': 9.001, 'CCWM': 44.605, 'TeamName': "M.I.T (Muskogee's Innovative Team)"}, {'TeamNum': 14906, 'OPR': 79.554, 'Auto': 26.439, 'CCWM': 33.757, 'TeamName': 'Leviathan Robotics'}, {'TeamNum': 3638, 'OPR': 74.815, 'Auto': 11.103, 'CCWM': 2.137, 'TeamName': 'Atomic Shock'}, {'TeamNum': 8825, 'OPR': 72.381, 'Auto': 18.487, 'CCWM': 8.865, 'TeamName': 'CADfish'}, {'TeamNum': 11240, 'OPR': 62.756, 'Auto': -2.62, 'CCWM': 29.598, 'TeamName': 'Blazing Bronc0s'}, {'TeamNum': 4266, 'OPR': 62.624, 'Auto': 18.409, 'CCWM': -35.217, 'TeamName': "Makin' Stuff Move"}, {'TeamNum': 19668, 'OPR': 59.921, 'Auto': 27.955, 'CCWM': 0.069, 'TeamName': 'HiveMind'}, {'TeamNum': 16426, 'OPR': 56.786, 'Auto': 7.659, 'CCWM': 13.665, 'TeamName': 'Absolute Zero'}, {'TeamNum': 18802, 'OPR': 56.688, 'Auto': 17.508, 'CCWM': -9.001, 'TeamName': 'Robo Renegades'}, {'TeamNum': 6042, 'OPR': 52.101, 'Auto': 15.76, 'CCWM': -15.645, 'TeamName': 'Commandobots '}, {'TeamNum': 5141, 'OPR': 47.57, 'Auto': 8.046, 'CCWM': -22.227, 'TeamName': 'Warrior Bots'}, {'TeamNum': 7163, 'OPR': 45.979, 'Auto': 9.291, 'CCWM': -41.026, 'TeamName': 'The Bazinga Project'}, {'TeamNum': 16505, 'OPR': 37.008, 'Auto': 4.849, 'CCWM': -42.151, 'TeamName': 'Quantum '}, {'TeamNum': 19901, 'OPR': 32.718, 'Auto': 4.343, 'CCWM': -10.12, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 18410, 'OPR': 24.769, 'Auto': 8.929, 'CCWM': -28.37, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 13709, 'OPR': 20.714, 'Auto': -0.86, 'CCWM': -18.056, 'TeamName': 'Null Sector'}, {'TeamNum': 18577, 'OPR': 15.825, 'Auto': -8.059, 'CCWM': -37.55, 'TeamName': 'Pro Buffs1'}, {'TeamNum': 21684, 'OPR': 9.184, 'Auto': -5.753, 'CCWM': -108.671, 'TeamName': 'ChouTime'}, {'TeamNum': 19563, 'OPR': 7.138, 'Auto': 11.907, 'CCWM': -26.353, 'TeamName': 'Boise City BattleCats'}]
USOKCMP
[{'TeamNum': 10355, 'OPR': 103.055, 'Auto': 23.076, 'CCWM': 58.661, 'TeamName': 'Project Peacock'}, {'TeamNum': 7242, 'OPR': 98.686, 'Auto': 22.359, 'CCWM': 13.614, 'TeamName': 'BC Robocats'}, {'TeamNum': 5553, 'OPR': 96.92, 'Auto': 31.723, 'CCWM': -0.61, 'TeamName': 'RoboComets'}, {'TeamNum': 18274, 'OPR': 94.025, 'Auto': 24.531, 'CCWM': 66.113, 'TeamName': 'PR0J3C7 P4R4D0X'}, {'TeamNum': 11354, 'OPR': 91.431, 'Auto': 20.459, 'CCWM': 22.904, 'TeamName': 'The Midnight Ostrich Runners'}, {'TeamNum': 13806, 'OPR': 90.741, 'Auto': 28.813, 'CCWM': 52.788, 'TeamName': 'Project Agnizab'}, {'TeamNum': 4250, 'OPR': 90.059, 'Auto': 28.282, 'CCWM': 10.359, 'TeamName': 'LIGHTSABERS'}, {'TeamNum': 8866, 'OPR': 88.069, 'Auto': 23.951, 'CCWM': 3.807, 'TeamName': 'Cybernetics'}, {'TeamNum': 17035, 'OPR': 86.375, 'Auto': 22.631, 'CCWM': 21.016, 'TeamName': 'Knightmares'}, {'TeamNum': 7506, 'OPR': 84.862, 'Auto': 17.044, 'CCWM': -10.695, 'TeamName': 'System Overload'}, {'TeamNum': 11572, 'OPR': 83.137, 'Auto': 12.071, 'CCWM': 23.736, 'TeamName': 'Mouse Spit'}, {'TeamNum': 4155, 'OPR': 79.942, 'Auto': 9.001, 'CCWM': 44.605, 'TeamName': "M.I.T (Muskogee's Innovative Team)"}, {'TeamNum': 14906, 'OPR': 79.554, 'Auto': 26.439, 'CCWM': 33.757, 'TeamName': 'Leviathan Robotics'}, {'TeamNum': 3638, 'OPR': 74.815, 'Auto': 11.103, 'CCWM': 2.137, 'TeamName': 'Atomic Shock'}, {'TeamNum': 8825, 'OPR': 72.381, 'Auto': 18.487, 'CCWM': 8.865, 'TeamName': 'CADfish'}, {'TeamNum': 11240, 'OPR': 62.756, 'Auto': -2.62, 'CCWM': 29.598, 'TeamName': 'Blazing Bronc0s'}, {'TeamNum': 4266, 'OPR': 62.624, 'Auto': 18.409, 'CCWM': -35.217, 'TeamName': "Makin' Stuff Move"}, {'TeamNum': 19668, 'OPR': 59.921, 'Auto': 27.955, 'CCWM': 0.069, 'TeamName': 'HiveMind'}, {'TeamNum': 16426, 'OPR': 56.786, 'Auto': 7.659, 'CCWM': 13.665, 'TeamName': 'Absolute Zero'}, {'TeamNum': 18802, 'OPR': 56.688, 'Auto': 17.508, 'CCWM': -9.001, 'TeamName': 'Robo Renegades'}, {'TeamNum': 6042, 'OPR': 52.101, 'Auto': 15.76, 'CCWM': -15.645, 'TeamName': 'Commandobots '}, {'TeamNum': 5141, 'OPR': 47.57, 'Auto': 8.046, 'CCWM': -22.227, 'TeamName': 'Warrior Bots'}, {'TeamNum': 7163, 'OPR': 45.979, 'Auto': 9.291, 'CCWM': -41.026, 'TeamName': 'The Bazinga Project'}, {'TeamNum': 16505, 'OPR': 37.008, 'Auto': 4.849, 'CCWM': -42.151, 'TeamName': 'Quantum '}, {'TeamNum': 19901, 'OPR': 32.718, 'Auto': 4.343, 'CCWM': -10.12, 'TeamName': 'Oktaha Tiger Tech Robotics'}, {'TeamNum': 18410, 'OPR': 24.769, 'Auto': 8.929, 'CCWM': -28.37, 'TeamName': 'Lego Queens of Girl Scout Troop 2612'}, {'TeamNum': 13709, 'OPR': 20.714, 'Auto': -0.86, 'CCWM': -18.056, 'TeamName': 'Null Sector'}, {'TeamNum': 18577, 'OPR': 15.825, 'Auto': -8.059, 'CCWM': -37.55, 'TeamName': 'Pro Buffs1'}, {'TeamNum': 21684, 'OPR': 9.184, 'Auto': -5.753, 'CCWM': -108.671, 'TeamName': 'ChouTime'}, {'TeamNum': 19563, 'OPR': 7.138, 'Auto': 11.907, 'CCWM': -26.353, 'TeamName': 'Boise City BattleCats'}]

i 1085
i 1086
i 1087
{'22534', '22199', '11444', '3641', '10021', '11454', '9121', '753', '772', '327', '11841', '15296', '673', '18069', '7021', '18984', '13900', '12517', '17621', '208', '18308', '15773', '22972', '13661'}
[{'TeamNum': 11444, 'OPR': 88.614, 'Auto': 27.864, 'CCWM': 36.613, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 327, 'OPR': 81.289, 'Auto': 13.924, 'CCWM': 51.333, 'TeamName': 'The Lobotomists'}, {'TeamNum': 17621, 'OPR': 81.089, 'Auto': 22.853, 'CCWM': 27.674, 'TeamName': 'Sea Dawgs'}, {'TeamNum': 11841, 'OPR': 72.777, 'Auto': 13.999, 'CCWM': 38.038, 'TeamName': 'STEAM Punks'}, {'TeamNum': 18984, 'OPR': 64.423, 'Auto': 11.748, 'CCWM': 8.909, 'TeamName': 'Hurricanes505'}, {'TeamNum': 673, 'OPR': 63.516, 'Auto': 17.682, 'CCWM': 34.014, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 753, 'OPR': 62.511, 'Auto': 16.226, 'CCWM': 17.911, 'TeamName': 'The GreenVillains'}, {'TeamNum': 772, 'OPR': 56.928, 'Auto': 16.835, 'CCWM': -35.627, 'TeamName': 'Golden Govies'}, {'TeamNum': 18308, 'OPR': 47.842, 'Auto': 8.829, 'CCWM': -7.839, 'TeamName': ' Team RocketForge'}, {'TeamNum': 13661, 'OPR': 44.155, 'Auto': 21.202, 'CCWM': 25.111, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 10021, 'OPR': 43.982, 'Auto': 20.076, 'CCWM': -3.887, 'TeamName': 'The Red Legion'}, {'TeamNum': 22972, 'OPR': 43.323, 'Auto': 17.992, 'CCWM': -20.198, 'TeamName': 'White Rice '}, {'TeamNum': 13900, 'OPR': 42.852, 'Auto': 7.471, 'CCWM': 10.964, 'TeamName': 'Iron Horses'}, {'TeamNum': 208, 'OPR': 41.063, 'Auto': 10.404, 'CCWM': -1.614, 'TeamName': 'Runic Robotics'}, {'TeamNum': 22534, 'OPR': 38.521, 'Auto': 16.445, 'CCWM': 11.971, 'TeamName': 'Area 52.1'}, {'TeamNum': 9121, 'OPR': 34.361, 'Auto': 5.044, 'CCWM': 16.989, 'TeamName': 'Falcon Force'}, {'TeamNum': 18069, 'OPR': 33.58, 'Auto': -0.792, 'CCWM': -6.343, 'TeamName': 'Java Dragons'}, {'TeamNum': 7021, 'OPR': 29.89, 'Auto': 2.107, 'CCWM': -18.943, 'TeamName': 'RoboEagles'}, {'TeamNum': 3641, 'OPR': 23.134, 'Auto': -4.642, 'CCWM': -17.074, 'TeamName': 'PPS Robotics'}, {'TeamNum': 22199, 'OPR': 20.137, 'Auto': -3.431, 'CCWM': -55.132, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 15296, 'OPR': 16.991, 'Auto': -3.469, 'CCWM': -31.158, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 15773, 'OPR': 15.1, 'Auto': -1.446, 'CCWM': -26.835, 'TeamName': 'Robodogs'}, {'TeamNum': 12517, 'OPR': 12.07, 'Auto': 7.935, 'CCWM': -19.464, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 11454, 'OPR': 11.022, 'Auto': 3.312, 'CCWM': -35.414, 'TeamName': 'Penguineers'}]
USSCCMP
[{'TeamNum': 11444, 'OPR': 88.614, 'Auto': 27.864, 'CCWM': 36.613, 'TeamName': 'Garnet Squadron'}, {'TeamNum': 327, 'OPR': 81.289, 'Auto': 13.924, 'CCWM': 51.333, 'TeamName': 'The Lobotomists'}, {'TeamNum': 17621, 'OPR': 81.089, 'Auto': 22.853, 'CCWM': 27.674, 'TeamName': 'Sea Dawgs'}, {'TeamNum': 11841, 'OPR': 72.777, 'Auto': 13.999, 'CCWM': 38.038, 'TeamName': 'STEAM Punks'}, {'TeamNum': 18984, 'OPR': 64.423, 'Auto': 11.748, 'CCWM': 8.909, 'TeamName': 'Hurricanes505'}, {'TeamNum': 673, 'OPR': 63.516, 'Auto': 17.682, 'CCWM': 34.014, 'TeamName': 'Subatomic Tomahawks'}, {'TeamNum': 753, 'OPR': 62.511, 'Auto': 16.226, 'CCWM': 17.911, 'TeamName': 'The GreenVillains'}, {'TeamNum': 772, 'OPR': 56.928, 'Auto': 16.835, 'CCWM': -35.627, 'TeamName': 'Golden Govies'}, {'TeamNum': 18308, 'OPR': 47.842, 'Auto': 8.829, 'CCWM': -7.839, 'TeamName': ' Team RocketForge'}, {'TeamNum': 13661, 'OPR': 44.155, 'Auto': 21.202, 'CCWM': 25.111, 'TeamName': 'Cygons (Cyborg Dragons)'}, {'TeamNum': 10021, 'OPR': 43.982, 'Auto': 20.076, 'CCWM': -3.887, 'TeamName': 'The Red Legion'}, {'TeamNum': 22972, 'OPR': 43.323, 'Auto': 17.992, 'CCWM': -20.198, 'TeamName': 'White Rice '}, {'TeamNum': 13900, 'OPR': 42.852, 'Auto': 7.471, 'CCWM': 10.964, 'TeamName': 'Iron Horses'}, {'TeamNum': 208, 'OPR': 41.063, 'Auto': 10.404, 'CCWM': -1.614, 'TeamName': 'Runic Robotics'}, {'TeamNum': 22534, 'OPR': 38.521, 'Auto': 16.445, 'CCWM': 11.971, 'TeamName': 'Area 52.1'}, {'TeamNum': 9121, 'OPR': 34.361, 'Auto': 5.044, 'CCWM': 16.989, 'TeamName': 'Falcon Force'}, {'TeamNum': 18069, 'OPR': 33.58, 'Auto': -0.792, 'CCWM': -6.343, 'TeamName': 'Java Dragons'}, {'TeamNum': 7021, 'OPR': 29.89, 'Auto': 2.107, 'CCWM': -18.943, 'TeamName': 'RoboEagles'}, {'TeamNum': 3641, 'OPR': 23.134, 'Auto': -4.642, 'CCWM': -17.074, 'TeamName': 'PPS Robotics'}, {'TeamNum': 22199, 'OPR': 20.137, 'Auto': -3.431, 'CCWM': -55.132, 'TeamName': 'ACE Basin Roboticist'}, {'TeamNum': 15296, 'OPR': 16.991, 'Auto': -3.469, 'CCWM': -31.158, 'TeamName': 'Mighty Trojans'}, {'TeamNum': 15773, 'OPR': 15.1, 'Auto': -1.446, 'CCWM': -26.835, 'TeamName': 'Robodogs'}, {'TeamNum': 12517, 'OPR': 12.07, 'Auto': 7.935, 'CCWM': -19.464, 'TeamName': 'Robo-Zombies'}, {'TeamNum': 11454, 'OPR': 11.022, 'Auto': 3.312, 'CCWM': -35.414, 'TeamName': 'Penguineers'}]
i 1088
{'10528', '11986', '13948', '21856', '11719', '13755', '11720', '17977', '19738', '19851', '15546', '4906', '19955', '15592', '14637', '5470', '9362', '16617', '17461', '4921', '15491', '10676', '21711', '9381', '12398', '11004', '4885', '18483', '19779', '18484', '4859', '14905', '9778', '4886', '5911', '13825'}
[{'TeamNum': 4886, 'OPR': 124.869, 'Auto': 27.769, 'CCWM': 88.881, 'TeamName': 'Robo Junkies'}, {'TeamNum': 16617, 'OPR': 116.759, 'Auto': 16.611, 'CCWM': 55.774, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 13948, 'OPR': 115.764, 'Auto': 24.782, 'CCWM': 67.55, 'TeamName': 'Cathedral Robotics'}, {'TeamNum': 14637, 'OPR': 100.79, 'Auto': 28.935, 'CCWM': 64.275, 'TeamName': 'Aquanauts'}, {'TeamNum': 18483, 'OPR': 92.367, 'Auto': 16.776, 'CCWM': 99.419, 'TeamName': 'Buckar00s'}, {'TeamNum': 5911, 'OPR': 87.958, 'Auto': 23.421, 'CCWM': 33.429, 'TeamName': 'Mean Green Machine'}, {'TeamNum': 12398, 'OPR': 86.725, 'Auto': 19.566, 'CCWM': 31.546, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 4921, 'OPR': 85.939, 'Auto': 15.933, 'CCWM': 39.464, 'TeamName': 'The Dropouts'}, {'TeamNum': 21856, 'OPR': 79.278, 'Auto': 19.218, 'CCWM': 15.522, 'TeamName': 'J-Bots'}, {'TeamNum': 11986, 'OPR': 77.492, 'Auto': 19.861, 'CCWM': 17.709, 'TeamName': 'Code Blue'}, {'TeamNum': 19779, 'OPR': 76.54, 'Auto': 25.6, 'CCWM': 28.038, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 5470, 'OPR': 75.15, 'Auto': 10.012, 'CCWM': 14.14, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 11004, 'OPR': 74.077, 'Auto': 13.815, 'CCWM': -3.753, 'TeamName': 'Cantina Crew'}, {'TeamNum': 4885, 'OPR': 72.18, 'Auto': 30.034, 'CCWM': 32.34, 'TeamName': 'OmegaBotz'}, {'TeamNum': 18484, 'OPR': 68.936, 'Auto': 11.328, 'CCWM': -27.241, 'TeamName': 'p0gg3r$'}, {'TeamNum': 9381, 'OPR': 68.524, 'Auto': 11.052, 'CCWM': 11.579, 'TeamName': 'Hot Bots '}, {'TeamNum': 17977, 'OPR': 64.031, 'Auto': 14.551, 'CCWM': 29.226, 'TeamName': 'Omni-Future'}, {'TeamNum': 9362, 'OPR': 64.009, 'Auto': 12.987, 'CCWM': 22.804, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 19955, 'OPR': 61.658, 'Auto': 8.408, 'CCWM': 8.71, 'TeamName': 'Robo Rangers'}, {'TeamNum': 9778, 'OPR': 60.455, 'Auto': 16.754, 'CCWM': -5.191, 'TeamName': 'Robotic Chinchillas'}, {'TeamNum': 13755, 'OPR': 60.391, 'Auto': 23.313, 'CCWM': -7.902, 'TeamName': 'Robocat'}, {'TeamNum': 15546, 'OPR': 57.253, 'Auto': 18.241, 'CCWM': 11.027, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 19738, 'OPR': 45.218, 'Auto': -2.117, 'CCWM': -30.008, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 15592, 'OPR': 37.334, 'Auto': 7.998, 'CCWM': 5.965, 'TeamName': 'T-Force'}, {'TeamNum': 15491, 'OPR': 34.347, 'Auto': 15.616, 'CCWM': -26.877, 'TeamName': 'Venom Robotics'}, {'TeamNum': 10676, 'OPR': 27.946, 'Auto': 18.497, 'CCWM': -34.473, 'TeamName': 'Lady Warbots'}, {'TeamNum': 14905, 'OPR': 27.829, 'Auto': 2.653, 'CCWM': -51.443, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 17461, 'OPR': 26.95, 'Auto': 4.076, 'CCWM': -43.836, 'TeamName': 'Trial & Error'}, {'TeamNum': 4906, 'OPR': 26.734, 'Auto': 9.732, 'CCWM': -85.766, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 11719, 'OPR': 26.087, 'Auto': 0.227, 'CCWM': -27.263, 'TeamName': 'Iron Hook'}, {'TeamNum': 19851, 'OPR': 22.791, 'Auto': 9.61, 'CCWM': -12.852, 'TeamName': 'Cyber Moose'}, {'TeamNum': 11720, 'OPR': 19.269, 'Auto': 7.952, 'CCWM': -74.272, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 4859, 'OPR': 17.786, 'Auto': -1.427, 'CCWM': -61.261, 'TeamName': 'Westerner Mechnoblades'}, {'TeamNum': 21711, 'OPR': 13.382, 'Auto': -1.066, 'CCWM': -86.527, 'TeamName': 'The McQueens'}, {'TeamNum': 13825, 'OPR': 8.937, 'Auto': 8.38, 'CCWM': -39.096, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 10528, 'OPR': 2.245, 'Auto': 3.101, 'CCWM': -59.635, 'TeamName': 'BOTS IN BLACK'}]
USTXWPCMP
[{'TeamNum': 4886, 'OPR': 124.869, 'Auto': 27.769, 'CCWM': 88.881, 'TeamName': 'Robo Junkies'}, {'TeamNum': 16617, 'OPR': 116.759, 'Auto': 16.611, 'CCWM': 55.774, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 13948, 'OPR': 115.764, 'Auto': 24.782, 'CCWM': 67.55, 'TeamName': 'Cathedral Robotics'}, {'TeamNum': 14637, 'OPR': 100.79, 'Auto': 28.935, 'CCWM': 64.275, 'TeamName': 'Aquanauts'}, {'TeamNum': 18483, 'OPR': 92.367, 'Auto': 16.776, 'CCWM': 99.419, 'TeamName': 'Buckar00s'}, {'TeamNum': 5911, 'OPR': 87.958, 'Auto': 23.421, 'CCWM': 33.429, 'TeamName': 'Mean Green Machine'}, {'TeamNum': 12398, 'OPR': 86.725, 'Auto': 19.566, 'CCWM': 31.546, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 4921, 'OPR': 85.939, 'Auto': 15.933, 'CCWM': 39.464, 'TeamName': 'The Dropouts'}, {'TeamNum': 21856, 'OPR': 79.278, 'Auto': 19.218, 'CCWM': 15.522, 'TeamName': 'J-Bots'}, {'TeamNum': 11986, 'OPR': 77.492, 'Auto': 19.861, 'CCWM': 17.709, 'TeamName': 'Code Blue'}, {'TeamNum': 19779, 'OPR': 76.54, 'Auto': 25.6, 'CCWM': 28.038, 'TeamName': 'M3tal Rebels'}, {'TeamNum': 5470, 'OPR': 75.15, 'Auto': 10.012, 'CCWM': 14.14, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 11004, 'OPR': 74.077, 'Auto': 13.815, 'CCWM': -3.753, 'TeamName': 'Cantina Crew'}, {'TeamNum': 4885, 'OPR': 72.18, 'Auto': 30.034, 'CCWM': 32.34, 'TeamName': 'OmegaBotz'}, {'TeamNum': 18484, 'OPR': 68.936, 'Auto': 11.328, 'CCWM': -27.241, 'TeamName': 'p0gg3r$'}, {'TeamNum': 9381, 'OPR': 68.524, 'Auto': 11.052, 'CCWM': 11.579, 'TeamName': 'Hot Bots '}, {'TeamNum': 17977, 'OPR': 64.031, 'Auto': 14.551, 'CCWM': 29.226, 'TeamName': 'Omni-Future'}, {'TeamNum': 9362, 'OPR': 64.009, 'Auto': 12.987, 'CCWM': 22.804, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 19955, 'OPR': 61.658, 'Auto': 8.408, 'CCWM': 8.71, 'TeamName': 'Robo Rangers'}, {'TeamNum': 9778, 'OPR': 60.455, 'Auto': 16.754, 'CCWM': -5.191, 'TeamName': 'Robotic Chinchillas'}, {'TeamNum': 13755, 'OPR': 60.391, 'Auto': 23.313, 'CCWM': -7.902, 'TeamName': 'Robocat'}, {'TeamNum': 15546, 'OPR': 57.253, 'Auto': 18.241, 'CCWM': 11.027, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 19738, 'OPR': 45.218, 'Auto': -2.117, 'CCWM': -30.008, 'TeamName': 'TI Robo TIGERS w/Fr3d'}, {'TeamNum': 15592, 'OPR': 37.334, 'Auto': 7.998, 'CCWM': 5.965, 'TeamName': 'T-Force'}, {'TeamNum': 15491, 'OPR': 34.347, 'Auto': 15.616, 'CCWM': -26.877, 'TeamName': 'Venom Robotics'}, {'TeamNum': 10676, 'OPR': 27.946, 'Auto': 18.497, 'CCWM': -34.473, 'TeamName': 'Lady Warbots'}, {'TeamNum': 14905, 'OPR': 27.829, 'Auto': 2.653, 'CCWM': -51.443, 'TeamName': 'Bad Batch Bots'}, {'TeamNum': 17461, 'OPR': 26.95, 'Auto': 4.076, 'CCWM': -43.836, 'TeamName': 'Trial & Error'}, {'TeamNum': 4906, 'OPR': 26.734, 'Auto': 9.732, 'CCWM': -85.766, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 11719, 'OPR': 26.087, 'Auto': 0.227, 'CCWM': -27.263, 'TeamName': 'Iron Hook'}, {'TeamNum': 19851, 'OPR': 22.791, 'Auto': 9.61, 'CCWM': -12.852, 'TeamName': 'Cyber Moose'}, {'TeamNum': 11720, 'OPR': 19.269, 'Auto': 7.952, 'CCWM': -74.272, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 4859, 'OPR': 17.786, 'Auto': -1.427, 'CCWM': -61.261, 'TeamName': 'Westerner Mechnoblades'}, {'TeamNum': 21711, 'OPR': 13.382, 'Auto': -1.066, 'CCWM': -86.527, 'TeamName': 'The McQueens'}, {'TeamNum': 13825, 'OPR': 8.937, 'Auto': 8.38, 'CCWM': -39.096, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 10528, 'OPR': 2.245, 'Auto': 3.101, 'CCWM': -59.635, 'TeamName': 'BOTS IN BLACK'}]

i 1089
{'7172', '21235', '8130', '21138', '18270', '13227', '13552', '9386', '12791', '17294', '19991', '20325', '21354', '21330', '20410', '6832', '21127', '19567', '11563', '16412', '21171', '12977', '8565', '19564', '21932', '10143', '9045', '13472', '16176', '19897', '21813', '13539', '13542', '12926', '20336', '20313', '8811', '18227', '16272', '19587'}
[{'TeamNum': 7172, 'OPR': 171.6, 'Auto': 45.14, 'CCWM': 109.081, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 18270, 'OPR': 146.76, 'Auto': 41.333, 'CCWM': 47.609, 'TeamName': 'RoboPlayers'}, {'TeamNum': 18227, 'OPR': 127.827, 'Auto': 29.918, 'CCWM': 50.081, 'TeamName': 'Area 52'}, {'TeamNum': 21813, 'OPR': 111.079, 'Auto': 20.636, 'CCWM': 13.735, 'TeamName': 'Pro2type'}, {'TeamNum': 12791, 'OPR': 103.813, 'Auto': 22.974, 'CCWM': 54.614, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 12926, 'OPR': 101.32, 'Auto': 21.739, 'CCWM': 23.182, 'TeamName': 'Panther Robotics'}, {'TeamNum': 21330, 'OPR': 100.322, 'Auto': 24.824, 'CCWM': 21.521, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 20325, 'OPR': 100.085, 'Auto': 23.152, 'CCWM': 71.258, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 19897, 'OPR': 99.518, 'Auto': 27.951, 'CCWM': 32.761, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 8811, 'OPR': 97.361, 'Auto': 11.413, 'CCWM': -5.708, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 8565, 'OPR': 95.48, 'Auto': 28.457, 'CCWM': 33.566, 'TeamName': 'TechnicBots'}, {'TeamNum': 20410, 'OPR': 91.214, 'Auto': 14.328, 'CCWM': 58.428, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 9386, 'OPR': 84.925, 'Auto': 26.426, 'CCWM': -19.668, 'TeamName': 'Elmer and Elsie Robotics'}, {'TeamNum': 20336, 'OPR': 84.533, 'Auto': 23.25, 'CCWM': 43.852, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 10143, 'OPR': 76.3, 'Auto': 23.17, 'CCWM': -43.714, 'TeamName': 'Aero'}, {'TeamNum': 21127, 'OPR': 74.115, 'Auto': 9.306, 'CCWM': -15.775, 'TeamName': 'Marvels of Irving'}, {'TeamNum': 19991, 'OPR': 69.642, 'Auto': 16.879, 'CCWM': 10.154, 'TeamName': 'Chuckleheads'}, {'TeamNum': 9045, 'OPR': 64.856, 'Auto': 20.562, 'CCWM': -1.682, 'TeamName': 'Motorhead'}, {'TeamNum': 16272, 'OPR': 63.302, 'Auto': 2.508, 'CCWM': 33.908, 'TeamName': 'Mark X'}, {'TeamNum': 16412, 'OPR': 62.922, 'Auto': 24.599, 'CCWM': 9.468, 'TeamName': 'Triad Robotics'}, {'TeamNum': 21932, 'OPR': 62.254, 'Auto': 17.534, 'CCWM': 17.674, 'TeamName': 'Forged In Iron'}, {'TeamNum': 12977, 'OPR': 60.129, 'Auto': 16.376, 'CCWM': 7.396, 'TeamName': 'Rust In Peace'}, {'TeamNum': 13542, 'OPR': 59.396, 'Auto': 10.777, 'CCWM': 18.844, 'TeamName': 'RoboChargers - Typhoon - Blue'}, {'TeamNum': 21171, 'OPR': 58.03, 'Auto': 27.227, 'CCWM': -68.352, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 17294, 'OPR': 57.519, 'Auto': 23.455, 'CCWM': -32.186, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 21138, 'OPR': 56.211, 'Auto': 24.185, 'CCWM': -17.003, 'TeamName': 'Kaizenite'}, {'TeamNum': 13472, 'OPR': 56.03, 'Auto': 16.363, 'CCWM': -49.08, 'TeamName': 'The Dork Side'}, {'TeamNum': 16176, 'OPR': 55.528, 'Auto': 20.619, 'CCWM': -26.71, 'TeamName': 'CDA Lions '}, {'TeamNum': 20313, 'OPR': 51.935, 'Auto': 14.923, 'CCWM': -32.05, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 13539, 'OPR': 50.55, 'Auto': 6.013, 'CCWM': 27.145, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 13552, 'OPR': 46.529, 'Auto': 4.091, 'CCWM': 25.387, 'TeamName': 'RoboChargers - Terremoto - Pink'}, {'TeamNum': 21354, 'OPR': 46.209, 'Auto': 5.614, 'CCWM': -2.401, 'TeamName': 'EPIC Expedition'}, {'TeamNum': 19564, 'OPR': 40.513, 'Auto': 6.578, 'CCWM': -8.446, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 11563, 'OPR': 36.325, 'Auto': 12.789, 'CCWM': -40.379, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 8130, 'OPR': 30.634, 'Auto': 4.153, 'CCWM': -47.655, 'TeamName': 'Vikings'}, {'TeamNum': 19587, 'OPR': 16.78, 'Auto': 4.28, 'CCWM': -69.945, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 13227, 'OPR': 12.181, 'Auto': 10.403, 'CCWM': -26.368, 'TeamName': 'Mechanicats'}, {'TeamNum': 21235, 'OPR': 3.04, 'Auto': 12.134, 'CCWM': -65.852, 'TeamName': 'SHARK!'}, {'TeamNum': 19567, 'OPR': -4.576, 'Auto': 3.026, 'CCWM': -84.394, 'TeamName': 'Tier1'}, {'TeamNum': 6832, 'OPR': -9.525, 'Auto': -2.941, 'CCWM': -52.294, 'TeamName': 'Iron Reign'}]
USTXNOCMP
[{'TeamNum': 7172, 'OPR': 171.6, 'Auto': 45.14, 'CCWM': 109.081, 'TeamName': 'Technical Difficulties'}, {'TeamNum': 18270, 'OPR': 146.76, 'Auto': 41.333, 'CCWM': 47.609, 'TeamName': 'RoboPlayers'}, {'TeamNum': 18227, 'OPR': 127.827, 'Auto': 29.918, 'CCWM': 50.081, 'TeamName': 'Area 52'}, {'TeamNum': 21813, 'OPR': 111.079, 'Auto': 20.636, 'CCWM': 13.735, 'TeamName': 'Pro2type'}, {'TeamNum': 12791, 'OPR': 103.813, 'Auto': 22.974, 'CCWM': 54.614, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 12926, 'OPR': 101.32, 'Auto': 21.739, 'CCWM': 23.182, 'TeamName': 'Panther Robotics'}, {'TeamNum': 21330, 'OPR': 100.322, 'Auto': 24.824, 'CCWM': 21.521, 'TeamName': 'The Marvels of Tomorrow'}, {'TeamNum': 20325, 'OPR': 100.085, 'Auto': 23.152, 'CCWM': 71.258, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 19897, 'OPR': 99.518, 'Auto': 27.951, 'CCWM': 32.761, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 8811, 'OPR': 97.361, 'Auto': 11.413, 'CCWM': -5.708, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 8565, 'OPR': 95.48, 'Auto': 28.457, 'CCWM': 33.566, 'TeamName': 'TechnicBots'}, {'TeamNum': 20410, 'OPR': 91.214, 'Auto': 14.328, 'CCWM': 58.428, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 9386, 'OPR': 84.925, 'Auto': 26.426, 'CCWM': -19.668, 'TeamName': 'Elmer and Elsie Robotics'}, {'TeamNum': 20336, 'OPR': 84.533, 'Auto': 23.25, 'CCWM': 43.852, 'TeamName': 'Beep Beep Bunch'}, {'TeamNum': 10143, 'OPR': 76.3, 'Auto': 23.17, 'CCWM': -43.714, 'TeamName': 'Aero'}, {'TeamNum': 21127, 'OPR': 74.115, 'Auto': 9.306, 'CCWM': -15.775, 'TeamName': 'Marvels of Irving'}, {'TeamNum': 19991, 'OPR': 69.642, 'Auto': 16.879, 'CCWM': 10.154, 'TeamName': 'Chuckleheads'}, {'TeamNum': 9045, 'OPR': 64.856, 'Auto': 20.562, 'CCWM': -1.682, 'TeamName': 'Motorhead'}, {'TeamNum': 16272, 'OPR': 63.302, 'Auto': 2.508, 'CCWM': 33.908, 'TeamName': 'Mark X'}, {'TeamNum': 16412, 'OPR': 62.922, 'Auto': 24.599, 'CCWM': 9.468, 'TeamName': 'Triad Robotics'}, {'TeamNum': 21932, 'OPR': 62.254, 'Auto': 17.534, 'CCWM': 17.674, 'TeamName': 'Forged In Iron'}, {'TeamNum': 12977, 'OPR': 60.129, 'Auto': 16.376, 'CCWM': 7.396, 'TeamName': 'Rust In Peace'}, {'TeamNum': 13542, 'OPR': 59.396, 'Auto': 10.777, 'CCWM': 18.844, 'TeamName': 'RoboChargers - Typhoon - Blue'}, {'TeamNum': 21171, 'OPR': 58.03, 'Auto': 27.227, 'CCWM': -68.352, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 17294, 'OPR': 57.519, 'Auto': 23.455, 'CCWM': -32.186, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 21138, 'OPR': 56.211, 'Auto': 24.185, 'CCWM': -17.003, 'TeamName': 'Kaizenite'}, {'TeamNum': 13472, 'OPR': 56.03, 'Auto': 16.363, 'CCWM': -49.08, 'TeamName': 'The Dork Side'}, {'TeamNum': 16176, 'OPR': 55.528, 'Auto': 20.619, 'CCWM': -26.71, 'TeamName': 'CDA Lions '}, {'TeamNum': 20313, 'OPR': 51.935, 'Auto': 14.923, 'CCWM': -32.05, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 13539, 'OPR': 50.55, 'Auto': 6.013, 'CCWM': 27.145, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 13552, 'OPR': 46.529, 'Auto': 4.091, 'CCWM': 25.387, 'TeamName': 'RoboChargers - Terremoto - Pink'}, {'TeamNum': 21354, 'OPR': 46.209, 'Auto': 5.614, 'CCWM': -2.401, 'TeamName': 'EPIC Expedition'}, {'TeamNum': 19564, 'OPR': 40.513, 'Auto': 6.578, 'CCWM': -8.446, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 11563, 'OPR': 36.325, 'Auto': 12.789, 'CCWM': -40.379, 'TeamName': 'Robo-Wranglers'}, {'TeamNum': 8130, 'OPR': 30.634, 'Auto': 4.153, 'CCWM': -47.655, 'TeamName': 'Vikings'}, {'TeamNum': 19587, 'OPR': 16.78, 'Auto': 4.28, 'CCWM': -69.945, 'TeamName': 'EPIC Odyssey'}, {'TeamNum': 13227, 'OPR': 12.181, 'Auto': 10.403, 'CCWM': -26.368, 'TeamName': 'Mechanicats'}, {'TeamNum': 21235, 'OPR': 3.04, 'Auto': 12.134, 'CCWM': -65.852, 'TeamName': 'SHARK!'}, {'TeamNum': 19567, 'OPR': -4.576, 'Auto': 3.026, 'CCWM': -84.394, 'TeamName': 'Tier1'}, {'TeamNum': 6832, 'OPR': -9.525, 'Auto': -2.941, 'CCWM': -52.294, 'TeamName': 'Iron Reign'}]
i 1090
{'8284', '13523', '18908', '13108', '12305', '21732', '12713', '12448', '12401', '22320', '22087', '12373', '13109', '17229', '18627', '15251', '20481', '21730', '13269', '18630', '21934', '11009', '12395', '13580', '12397', '12696', '13512', '4848', '12393', '12453', '21935', '19857', '13265', '13581', '6892', '12313', '13586', '13590', '11158', '21733'}
[{'TeamNum': 13265, 'OPR': 113.03, 'Auto': 32.929, 'CCWM': 56.532, 'TeamName': 'Osiris'}, {'TeamNum': 21733, 'OPR': 109.387, 'Auto': 23.075, 'CCWM': 79.182, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 8284, 'OPR': 105.868, 'Auto': 23.567, 'CCWM': 51.703, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 12453, 'OPR': 104.069, 'Auto': 13.292, 'CCWM': 34.51, 'TeamName': 'Phoenix - Patriot Engineering'}, {'TeamNum': 12448, 'OPR': 100.42, 'Auto': 8.519, 'CCWM': 4.99, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 18627, 'OPR': 99.759, 'Auto': 14.791, 'CCWM': 32.693, 'TeamName': 'Collegiate NanoKnights'}, {'TeamNum': 12696, 'OPR': 99.454, 'Auto': 14.366, 'CCWM': 34.287, 'TeamName': 'SupernoVa - Patriot Engineering'}, {'TeamNum': 22320, 'OPR': 90.403, 'Auto': 23.935, 'CCWM': 4.324, 'TeamName': 'ROGUE-RANGERS Vengeance'}, {'TeamNum': 13512, 'OPR': 89.934, 'Auto': 25.638, 'CCWM': -11.219, 'TeamName': 'Falcon ROBO-RANGERS'}, {'TeamNum': 12397, 'OPR': 89.853, 'Auto': 23.119, 'CCWM': 3.13, 'TeamName': 'High Voltage Rattlers'}, {'TeamNum': 12393, 'OPR': 88.969, 'Auto': 26.224, 'CCWM': 36.153, 'TeamName': 'Pioneer Pi-Thons'}, {'TeamNum': 13109, 'OPR': 88.118, 'Auto': 25.041, 'CCWM': 22.831, 'TeamName': 'Team Koopa'}, {'TeamNum': 4848, 'OPR': 86.868, 'Auto': 10.554, 'CCWM': 20.806, 'TeamName': 'Chaos'}, {'TeamNum': 12395, 'OPR': 85.33, 'Auto': 14.289, 'CCWM': -8.394, 'TeamName': 'Rattler Robotics'}, {'TeamNum': 17229, 'OPR': 83.692, 'Auto': 23.376, 'CCWM': 6.627, 'TeamName': 'The Scouts '}, {'TeamNum': 15251, 'OPR': 77.269, 'Auto': 7.696, 'CCWM': 44.075, 'TeamName': 'Hadron Mission Eagle'}, {'TeamNum': 13581, 'OPR': 77.212, 'Auto': 14.762, 'CCWM': -20.57, 'TeamName': 'Fang Gang'}, {'TeamNum': 21934, 'OPR': 76.942, 'Auto': 16.322, 'CCWM': 55.058, 'TeamName': 'JLHS Engineering and Robotics 1'}, {'TeamNum': 13269, 'OPR': 76.538, 'Auto': 18.571, 'CCWM': 44.265, 'TeamName': 'Mustang MegaBytes'}, {'TeamNum': 18630, 'OPR': 73.093, 'Auto': 5.777, 'CCWM': -7.939, 'TeamName': 'Collegiate MegaKnights'}, {'TeamNum': 20481, 'OPR': 72.766, 'Auto': 12.542, 'CCWM': -38.07, 'TeamName': 'DHS T-STEM'}, {'TeamNum': 21935, 'OPR': 72.167, 'Auto': 21.864, 'CCWM': -7.93, 'TeamName': 'JLHS Engineering and Robotics 2'}, {'TeamNum': 12401, 'OPR': 68.007, 'Auto': 7.503, 'CCWM': 1.19, 'TeamName': 'Quantum Fusion - Patriot Engineering'}, {'TeamNum': 11158, 'OPR': 63.668, 'Auto': 5.814, 'CCWM': -9.38, 'TeamName': 'Deceptibots'}, {'TeamNum': 13590, 'OPR': 63.199, 'Auto': 8.672, 'CCWM': 17.852, 'TeamName': 'Viperstrike'}, {'TeamNum': 6892, 'OPR': 61.661, 'Auto': 17.155, 'CCWM': 14.296, 'TeamName': 'The Waterboys'}, {'TeamNum': 12713, 'OPR': 61.564, 'Auto': 18.754, 'CCWM': -1.621, 'TeamName': 'Impulse'}, {'TeamNum': 18908, 'OPR': 58.396, 'Auto': 2.24, 'CCWM': -36.528, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 21730, 'OPR': 57.392, 'Auto': 21.493, 'CCWM': -41.545, 'TeamName': 'Knights'}, {'TeamNum': 13108, 'OPR': 56.725, 'Auto': 10.884, 'CCWM': -10.895, 'TeamName': 'Encrypted'}, {'TeamNum': 12305, 'OPR': 47.362, 'Auto': 14.256, 'CCWM': -19.211, 'TeamName': 'Ro-baddies'}, {'TeamNum': 21732, 'OPR': 44.847, 'Auto': 8.262, 'CCWM': -25.465, 'TeamName': 'Cyber Knights'}, {'TeamNum': 13523, 'OPR': 44.217, 'Auto': 6.639, 'CCWM': -29.74, 'TeamName': 'Lady ROBO-RANGERS'}, {'TeamNum': 19857, 'OPR': 42.167, 'Auto': 12.15, 'CCWM': -59.906, 'TeamName': 'GigaBots'}, {'TeamNum': 12313, 'OPR': 40.536, 'Auto': 11.255, 'CCWM': -61.324, 'TeamName': 'Hotdawgs'}, {'TeamNum': 12373, 'OPR': 37.919, 'Auto': 3.854, 'CCWM': -62.523, 'TeamName': 'Rowe-botic Problem'}, {'TeamNum': 13580, 'OPR': 37.624, 'Auto': 7.627, 'CCWM': -24.905, 'TeamName': 'Tech Serpents'}, {'TeamNum': 11009, 'OPR': 35.375, 'Auto': -5.53, 'CCWM': -18.775, 'TeamName': 'McHi Robodogs'}, {'TeamNum': 13586, 'OPR': 28.854, 'Auto': 5.228, 'CCWM': -18.18, 'TeamName': 'Adders'}, {'TeamNum': 22087, 'OPR': 18.944, 'Auto': 9.296, 'CCWM': -50.384, 'TeamName': 'Bad 2 the Bone'}]
USTXSOCMP3
[{'TeamNum': 13265, 'OPR': 113.03, 'Auto': 32.929, 'CCWM': 56.532, 'TeamName': 'Osiris'}, {'TeamNum': 21733, 'OPR': 109.387, 'Auto': 23.075, 'CCWM': 79.182, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 8284, 'OPR': 105.868, 'Auto': 23.567, 'CCWM': 51.703, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 12453, 'OPR': 104.069, 'Auto': 13.292, 'CCWM': 34.51, 'TeamName': 'Phoenix - Patriot Engineering'}, {'TeamNum': 12448, 'OPR': 100.42, 'Auto': 8.519, 'CCWM': 4.99, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 18627, 'OPR': 99.759, 'Auto': 14.791, 'CCWM': 32.693, 'TeamName': 'Collegiate NanoKnights'}, {'TeamNum': 12696, 'OPR': 99.454, 'Auto': 14.366, 'CCWM': 34.287, 'TeamName': 'SupernoVa - Patriot Engineering'}, {'TeamNum': 22320, 'OPR': 90.403, 'Auto': 23.935, 'CCWM': 4.324, 'TeamName': 'ROGUE-RANGERS Vengeance'}, {'TeamNum': 13512, 'OPR': 89.934, 'Auto': 25.638, 'CCWM': -11.219, 'TeamName': 'Falcon ROBO-RANGERS'}, {'TeamNum': 12397, 'OPR': 89.853, 'Auto': 23.119, 'CCWM': 3.13, 'TeamName': 'High Voltage Rattlers'}, {'TeamNum': 12393, 'OPR': 88.969, 'Auto': 26.224, 'CCWM': 36.153, 'TeamName': 'Pioneer Pi-Thons'}, {'TeamNum': 13109, 'OPR': 88.118, 'Auto': 25.041, 'CCWM': 22.831, 'TeamName': 'Team Koopa'}, {'TeamNum': 4848, 'OPR': 86.868, 'Auto': 10.554, 'CCWM': 20.806, 'TeamName': 'Chaos'}, {'TeamNum': 12395, 'OPR': 85.33, 'Auto': 14.289, 'CCWM': -8.394, 'TeamName': 'Rattler Robotics'}, {'TeamNum': 17229, 'OPR': 83.692, 'Auto': 23.376, 'CCWM': 6.627, 'TeamName': 'The Scouts '}, {'TeamNum': 15251, 'OPR': 77.269, 'Auto': 7.696, 'CCWM': 44.075, 'TeamName': 'Hadron Mission Eagle'}, {'TeamNum': 13581, 'OPR': 77.212, 'Auto': 14.762, 'CCWM': -20.57, 'TeamName': 'Fang Gang'}, {'TeamNum': 21934, 'OPR': 76.942, 'Auto': 16.322, 'CCWM': 55.058, 'TeamName': 'JLHS Engineering and Robotics 1'}, {'TeamNum': 13269, 'OPR': 76.538, 'Auto': 18.571, 'CCWM': 44.265, 'TeamName': 'Mustang MegaBytes'}, {'TeamNum': 18630, 'OPR': 73.093, 'Auto': 5.777, 'CCWM': -7.939, 'TeamName': 'Collegiate MegaKnights'}, {'TeamNum': 20481, 'OPR': 72.766, 'Auto': 12.542, 'CCWM': -38.07, 'TeamName': 'DHS T-STEM'}, {'TeamNum': 21935, 'OPR': 72.167, 'Auto': 21.864, 'CCWM': -7.93, 'TeamName': 'JLHS Engineering and Robotics 2'}, {'TeamNum': 12401, 'OPR': 68.007, 'Auto': 7.503, 'CCWM': 1.19, 'TeamName': 'Quantum Fusion - Patriot Engineering'}, {'TeamNum': 11158, 'OPR': 63.668, 'Auto': 5.814, 'CCWM': -9.38, 'TeamName': 'Deceptibots'}, {'TeamNum': 13590, 'OPR': 63.199, 'Auto': 8.672, 'CCWM': 17.852, 'TeamName': 'Viperstrike'}, {'TeamNum': 6892, 'OPR': 61.661, 'Auto': 17.155, 'CCWM': 14.296, 'TeamName': 'The Waterboys'}, {'TeamNum': 12713, 'OPR': 61.564, 'Auto': 18.754, 'CCWM': -1.621, 'TeamName': 'Impulse'}, {'TeamNum': 18908, 'OPR': 58.396, 'Auto': 2.24, 'CCWM': -36.528, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 21730, 'OPR': 57.392, 'Auto': 21.493, 'CCWM': -41.545, 'TeamName': 'Knights'}, {'TeamNum': 13108, 'OPR': 56.725, 'Auto': 10.884, 'CCWM': -10.895, 'TeamName': 'Encrypted'}, {'TeamNum': 12305, 'OPR': 47.362, 'Auto': 14.256, 'CCWM': -19.211, 'TeamName': 'Ro-baddies'}, {'TeamNum': 21732, 'OPR': 44.847, 'Auto': 8.262, 'CCWM': -25.465, 'TeamName': 'Cyber Knights'}, {'TeamNum': 13523, 'OPR': 44.217, 'Auto': 6.639, 'CCWM': -29.74, 'TeamName': 'Lady ROBO-RANGERS'}, {'TeamNum': 19857, 'OPR': 42.167, 'Auto': 12.15, 'CCWM': -59.906, 'TeamName': 'GigaBots'}, {'TeamNum': 12313, 'OPR': 40.536, 'Auto': 11.255, 'CCWM': -61.324, 'TeamName': 'Hotdawgs'}, {'TeamNum': 12373, 'OPR': 37.919, 'Auto': 3.854, 'CCWM': -62.523, 'TeamName': 'Rowe-botic Problem'}, {'TeamNum': 13580, 'OPR': 37.624, 'Auto': 7.627, 'CCWM': -24.905, 'TeamName': 'Tech Serpents'}, {'TeamNum': 11009, 'OPR': 35.375, 'Auto': -5.53, 'CCWM': -18.775, 'TeamName': 'McHi Robodogs'}, {'TeamNum': 13586, 'OPR': 28.854, 'Auto': 5.228, 'CCWM': -18.18, 'TeamName': 'Adders'}, {'TeamNum': 22087, 'OPR': 18.944, 'Auto': 9.296, 'CCWM': -50.384, 'TeamName': 'Bad 2 the Bone'}]

i 1091
{'14762', '19947', '12978', '16911', '19502', '14503', '18140', '21693', '16685', '18514', '10405', '9840', '16816', '22393', '10095', '18064', '16909', '22614', '22495', '20394', '20335', '16215', '18071', '9191', '5175', '16226', '16930', '21338', '21890', '21386', '12857', '14785', '19572', '21962', '10354'}
[{'TeamNum': 12978, 'OPR': 102.943, 'Auto': 24.182, 'CCWM': 114.219, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 16215, 'OPR': 97.404, 'Auto': 13.268, 'CCWM': 68.12, 'TeamName': 'Mystery Machine'}, {'TeamNum': 18140, 'OPR': 95.812, 'Auto': 9.496, 'CCWM': 57.491, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 16911, 'OPR': 90.176, 'Auto': 24.491, 'CCWM': 25.81, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 19502, 'OPR': 87.999, 'Auto': 23.067, 'CCWM': 17.654, 'TeamName': 'The Moment Makers'}, {'TeamNum': 21962, 'OPR': 85.935, 'Auto': 25.583, 'CCWM': 22.949, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 10095, 'OPR': 85.32, 'Auto': 20.007, 'CCWM': 9.983, 'TeamName': 'Revelation'}, {'TeamNum': 20394, 'OPR': 84.97, 'Auto': 14.891, 'CCWM': 69.594, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 14503, 'OPR': 80.724, 'Auto': 18.815, 'CCWM': -6.544, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 12857, 'OPR': 80.031, 'Auto': 24.608, 'CCWM': 10.515, 'TeamName': 'Phantom'}, {'TeamNum': 19572, 'OPR': 79.646, 'Auto': 22.93, 'CCWM': 26.337, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 21386, 'OPR': 77.143, 'Auto': 22.53, 'CCWM': 13.666, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 16930, 'OPR': 76.452, 'Auto': 18.932, 'CCWM': 31.087, 'TeamName': 'Omen'}, {'TeamNum': 19947, 'OPR': 72.362, 'Auto': 11.518, 'CCWM': 45.079, 'TeamName': 'Nano Trojans'}, {'TeamNum': 14785, 'OPR': 72.338, 'Auto': 16.525, 'CCWM': 47.19, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 10354, 'OPR': 71.725, 'Auto': 16.015, 'CCWM': 27.106, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 9191, 'OPR': 68.321, 'Auto': 13.909, 'CCWM': 29.779, 'TeamName': 'Beta Testers'}, {'TeamNum': 22393, 'OPR': 67.138, 'Auto': 32.963, 'CCWM': 2.197, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 16909, 'OPR': 65.219, 'Auto': 17.724, 'CCWM': 26.17, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 18064, 'OPR': 58.265, 'Auto': 1.735, 'CCWM': -13.139, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 16226, 'OPR': 58.047, 'Auto': 15.435, 'CCWM': 4.712, 'TeamName': 'True Damage'}, {'TeamNum': 18071, 'OPR': 54.672, 'Auto': 17.825, 'CCWM': -7.418, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 20335, 'OPR': 53.793, 'Auto': 11.625, 'CCWM': 15.727, 'TeamName': 'LIONBOTS'}, {'TeamNum': 9840, 'OPR': 44.767, 'Auto': 4.611, 'CCWM': -9.984, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21890, 'OPR': 44.636, 'Auto': 11.95, 'CCWM': -27.678, 'TeamName': "St. John's Robotics"}, {'TeamNum': 21338, 'OPR': 41.038, 'Auto': 24.298, 'CCWM': -40.862, 'TeamName': 'Innovators'}, {'TeamNum': 21693, 'OPR': 39.521, 'Auto': 11.976, 'CCWM': -22.402, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 10405, 'OPR': 37.285, 'Auto': 23.544, 'CCWM': -40.473, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 17.573, 'Auto': 0.205, 'CCWM': -38.905, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22495, 'OPR': 14.211, 'Auto': -1.49, 'CCWM': -80.453, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 14762, 'OPR': 8.921, 'Auto': -3.064, 'CCWM': -76.693, 'TeamName': 'Robo Panthers'}, {'TeamNum': 18514, 'OPR': 7.924, 'Auto': 8.216, 'CCWM': -89.209, 'TeamName': 'STORM Masters'}, {'TeamNum': 16685, 'OPR': 6.502, 'Auto': 2.74, 'CCWM': -79.883, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 22614, 'OPR': -0.968, 'Auto': -1.592, 'CCWM': -62.184, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 16816, 'OPR': -3.843, 'Auto': -5.682, 'CCWM': -73.088, 'TeamName': 'IOKNIGHT'}]
USTXHOCMP
[{'TeamNum': 12978, 'OPR': 102.943, 'Auto': 24.182, 'CCWM': 114.219, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 16215, 'OPR': 97.404, 'Auto': 13.268, 'CCWM': 68.12, 'TeamName': 'Mystery Machine'}, {'TeamNum': 18140, 'OPR': 95.812, 'Auto': 9.496, 'CCWM': 57.491, 'TeamName': 'TBD (Thunder Bolts in Disguise)'}, {'TeamNum': 16911, 'OPR': 90.176, 'Auto': 24.491, 'CCWM': 25.81, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 19502, 'OPR': 87.999, 'Auto': 23.067, 'CCWM': 17.654, 'TeamName': 'The Moment Makers'}, {'TeamNum': 21962, 'OPR': 85.935, 'Auto': 25.583, 'CCWM': 22.949, 'TeamName': 'Raging Cy-Bots'}, {'TeamNum': 10095, 'OPR': 85.32, 'Auto': 20.007, 'CCWM': 9.983, 'TeamName': 'Revelation'}, {'TeamNum': 20394, 'OPR': 84.97, 'Auto': 14.891, 'CCWM': 69.594, 'TeamName': 'Mustangs2.0'}, {'TeamNum': 14503, 'OPR': 80.724, 'Auto': 18.815, 'CCWM': -6.544, 'TeamName': 'Robo Sapiens'}, {'TeamNum': 12857, 'OPR': 80.031, 'Auto': 24.608, 'CCWM': 10.515, 'TeamName': 'Phantom'}, {'TeamNum': 19572, 'OPR': 79.646, 'Auto': 22.93, 'CCWM': 26.337, 'TeamName': 'BiFrost Bots'}, {'TeamNum': 21386, 'OPR': 77.143, 'Auto': 22.53, 'CCWM': 13.666, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 16930, 'OPR': 76.452, 'Auto': 18.932, 'CCWM': 31.087, 'TeamName': 'Omen'}, {'TeamNum': 19947, 'OPR': 72.362, 'Auto': 11.518, 'CCWM': 45.079, 'TeamName': 'Nano Trojans'}, {'TeamNum': 14785, 'OPR': 72.338, 'Auto': 16.525, 'CCWM': 47.19, 'TeamName': 'The Sensational Seven'}, {'TeamNum': 10354, 'OPR': 71.725, 'Auto': 16.015, 'CCWM': 27.106, 'TeamName': 'Mustangs 1.0'}, {'TeamNum': 9191, 'OPR': 68.321, 'Auto': 13.909, 'CCWM': 29.779, 'TeamName': 'Beta Testers'}, {'TeamNum': 22393, 'OPR': 67.138, 'Auto': 32.963, 'CCWM': 2.197, 'TeamName': 'Cardinals of the Future'}, {'TeamNum': 16909, 'OPR': 65.219, 'Auto': 17.724, 'CCWM': 26.17, 'TeamName': 'Fettuccine Pastabots'}, {'TeamNum': 18064, 'OPR': 58.265, 'Auto': 1.735, 'CCWM': -13.139, 'TeamName': 'Flex Capacitors'}, {'TeamNum': 16226, 'OPR': 58.047, 'Auto': 15.435, 'CCWM': 4.712, 'TeamName': 'True Damage'}, {'TeamNum': 18071, 'OPR': 54.672, 'Auto': 17.825, 'CCWM': -7.418, 'TeamName': 'Brainiac Maniacs'}, {'TeamNum': 20335, 'OPR': 53.793, 'Auto': 11.625, 'CCWM': 15.727, 'TeamName': 'LIONBOTS'}, {'TeamNum': 9840, 'OPR': 44.767, 'Auto': 4.611, 'CCWM': -9.984, 'TeamName': 'Royal Robotics'}, {'TeamNum': 21890, 'OPR': 44.636, 'Auto': 11.95, 'CCWM': -27.678, 'TeamName': "St. John's Robotics"}, {'TeamNum': 21338, 'OPR': 41.038, 'Auto': 24.298, 'CCWM': -40.862, 'TeamName': 'Innovators'}, {'TeamNum': 21693, 'OPR': 39.521, 'Auto': 11.976, 'CCWM': -22.402, 'TeamName': 'Marvels of MCC'}, {'TeamNum': 10405, 'OPR': 37.285, 'Auto': 23.544, 'CCWM': -40.473, 'TeamName': 'RoboKnights'}, {'TeamNum': 5175, 'OPR': 17.573, 'Auto': 0.205, 'CCWM': -38.905, 'TeamName': 'Vector Robotics'}, {'TeamNum': 22495, 'OPR': 14.211, 'Auto': -1.49, 'CCWM': -80.453, 'TeamName': 'Shark Nerds 1'}, {'TeamNum': 14762, 'OPR': 8.921, 'Auto': -3.064, 'CCWM': -76.693, 'TeamName': 'Robo Panthers'}, {'TeamNum': 18514, 'OPR': 7.924, 'Auto': 8.216, 'CCWM': -89.209, 'TeamName': 'STORM Masters'}, {'TeamNum': 16685, 'OPR': 6.502, 'Auto': 2.74, 'CCWM': -79.883, 'TeamName': 'Logos Lions The Mane Show'}, {'TeamNum': 22614, 'OPR': -0.968, 'Auto': -1.592, 'CCWM': -62.184, 'TeamName': 'Clute Robotics: Scorpion'}, {'TeamNum': 16816, 'OPR': -3.843, 'Auto': -5.682, 'CCWM': -73.088, 'TeamName': 'IOKNIGHT'}]
i 1092
{'5628', '20741', '7161', '7079', '16597', '10862', '12115', '19696', '15703', '11093', '14361', '9527', '19746', '21438', '4545', '15758', '20716', '12597', '3708', '3033', '12596', '21879', '18094', '16311', '16458', '6299', '6272', '12928', '6407', '16320', '16377', '16832', '17113', '12302', '4707', '15725', '13053'}
[{'TeamNum': 19746, 'OPR': 142.662, 'Auto': 43.884, 'CCWM': 64.419, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 6272, 'OPR': 130.402, 'Auto': 35.048, 'CCWM': 92.022, 'TeamName': 'Iron Eagles Prime'}, {'TeamNum': 16458, 'OPR': 123.218, 'Auto': 47.149, 'CCWM': 46.642, 'TeamName': 'TechnoWizards'}, {'TeamNum': 6299, 'OPR': 122.801, 'Auto': 22.685, 'CCWM': 11.738, 'TeamName': 'ViperBots QuadX'}, {'TeamNum': 3708, 'OPR': 115.176, 'Auto': 33.11, 'CCWM': 21.048, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 13053, 'OPR': 109.773, 'Auto': 7.353, 'CCWM': 46.873, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 15725, 'OPR': 105.897, 'Auto': 27.417, 'CCWM': 45.211, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 9527, 'OPR': 104.248, 'Auto': 28.354, 'CCWM': 76.659, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 7079, 'OPR': 103.502, 'Auto': 24.704, 'CCWM': 24.44, 'TeamName': 'FalTech'}, {'TeamNum': 4707, 'OPR': 101.662, 'Auto': 32.329, 'CCWM': 4.55, 'TeamName': 'Midway Predators'}, {'TeamNum': 16377, 'OPR': 94.708, 'Auto': 32.606, 'CCWM': 33.629, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 17113, 'OPR': 94.706, 'Auto': 21.512, 'CCWM': -4.17, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 12928, 'OPR': 94.426, 'Auto': 33.848, 'CCWM': 37.04, 'TeamName': 'LightSaders'}, {'TeamNum': 16597, 'OPR': 91.45, 'Auto': 23.36, 'CCWM': -16.478, 'TeamName': 'Fulminata'}, {'TeamNum': 3033, 'OPR': 89.236, 'Auto': 20.255, 'CCWM': 38.879, 'TeamName': 'Techno Riderz'}, {'TeamNum': 21438, 'OPR': 85.935, 'Auto': 17.875, 'CCWM': 12.104, 'TeamName': 'Chaotic Current'}, {'TeamNum': 20716, 'OPR': 81.085, 'Auto': 7.879, 'CCWM': -23.377, 'TeamName': 'BeauBots'}, {'TeamNum': 16320, 'OPR': 80.805, 'Auto': 12.698, 'CCWM': 27.974, 'TeamName': 'Gilded Gears'}, {'TeamNum': 19696, 'OPR': 80.005, 'Auto': -1.598, 'CCWM': -18.106, 'TeamName': 'B.O.T.S.'}, {'TeamNum': 12115, 'OPR': 79.818, 'Auto': 7.76, 'CCWM': -37.066, 'TeamName': 'Phoen-X'}, {'TeamNum': 16311, 'OPR': 78.638, 'Auto': 19.238, 'CCWM': -7.044, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 21879, 'OPR': 75.795, 'Auto': 17.993, 'CCWM': 16.236, 'TeamName': 'Checkmate'}, {'TeamNum': 11093, 'OPR': 73.462, 'Auto': 17.246, 'CCWM': -9.936, 'TeamName': 'MegaKnytes'}, {'TeamNum': 4545, 'OPR': 72.922, 'Auto': 9.253, 'CCWM': 0.44, 'TeamName': 'ViperBots Ouroboros'}, {'TeamNum': 10862, 'OPR': 70.617, 'Auto': 15.647, 'CCWM': -24.114, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 5628, 'OPR': 69.848, 'Auto': 19.856, 'CCWM': 5.804, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 7161, 'OPR': 63.605, 'Auto': 8.866, 'CCWM': 1.495, 'TeamName': 'ViperBots Hydra'}, {'TeamNum': 14361, 'OPR': 56.818, 'Auto': 8.834, 'CCWM': -37.159, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 15703, 'OPR': 53.74, 'Auto': 23.968, 'CCWM': -51.961, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 12597, 'OPR': 52.035, 'Auto': 15.359, 'CCWM': -39.431, 'TeamName': 'RAGNAROK ROBOTICS'}, {'TeamNum': 15758, 'OPR': 46.269, 'Auto': 2.332, 'CCWM': -40.048, 'TeamName': 'PiRate Brigade'}, {'TeamNum': 18094, 'OPR': 44.737, 'Auto': 13.878, 'CCWM': -17.999, 'TeamName': 'BASIS Batteries Not Included'}, {'TeamNum': 20741, 'OPR': 41.281, 'Auto': -5.778, 'CCWM': -49.148, 'TeamName': 'Checkmate'}, {'TeamNum': 12302, 'OPR': 34.637, 'Auto': -3.761, 'CCWM': -36.617, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 16832, 'OPR': 32.464, 'Auto': 10.506, 'CCWM': -70.482, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 12596, 'OPR': 32.39, 'Auto': -10.316, 'CCWM': -48.692, 'TeamName': 'ViperBots Copperhead'}, {'TeamNum': 6407, 'OPR': 21.611, 'Auto': 23.809, 'CCWM': -78.892, 'TeamName': 'Mechanical Mustangs Secretariat'}]
USTXCECMP2
[{'TeamNum': 19746, 'OPR': 142.662, 'Auto': 43.884, 'CCWM': 64.419, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 6272, 'OPR': 130.402, 'Auto': 35.048, 'CCWM': 92.022, 'TeamName': 'Iron Eagles Prime'}, {'TeamNum': 16458, 'OPR': 123.218, 'Auto': 47.149, 'CCWM': 46.642, 'TeamName': 'TechnoWizards'}, {'TeamNum': 6299, 'OPR': 122.801, 'Auto': 22.685, 'CCWM': 11.738, 'TeamName': 'ViperBots QuadX'}, {'TeamNum': 3708, 'OPR': 115.176, 'Auto': 33.11, 'CCWM': 21.048, 'TeamName': 'Iron Eagles Optimus'}, {'TeamNum': 13053, 'OPR': 109.773, 'Auto': 7.353, 'CCWM': 46.873, 'TeamName': 'BERSERK ROBOTICS'}, {'TeamNum': 15725, 'OPR': 105.897, 'Auto': 27.417, 'CCWM': 45.211, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 9527, 'OPR': 104.248, 'Auto': 28.354, 'CCWM': 76.659, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 7079, 'OPR': 103.502, 'Auto': 24.704, 'CCWM': 24.44, 'TeamName': 'FalTech'}, {'TeamNum': 4707, 'OPR': 101.662, 'Auto': 32.329, 'CCWM': 4.55, 'TeamName': 'Midway Predators'}, {'TeamNum': 16377, 'OPR': 94.708, 'Auto': 32.606, 'CCWM': 33.629, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 17113, 'OPR': 94.706, 'Auto': 21.512, 'CCWM': -4.17, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 12928, 'OPR': 94.426, 'Auto': 33.848, 'CCWM': 37.04, 'TeamName': 'LightSaders'}, {'TeamNum': 16597, 'OPR': 91.45, 'Auto': 23.36, 'CCWM': -16.478, 'TeamName': 'Fulminata'}, {'TeamNum': 3033, 'OPR': 89.236, 'Auto': 20.255, 'CCWM': 38.879, 'TeamName': 'Techno Riderz'}, {'TeamNum': 21438, 'OPR': 85.935, 'Auto': 17.875, 'CCWM': 12.104, 'TeamName': 'Chaotic Current'}, {'TeamNum': 20716, 'OPR': 81.085, 'Auto': 7.879, 'CCWM': -23.377, 'TeamName': 'BeauBots'}, {'TeamNum': 16320, 'OPR': 80.805, 'Auto': 12.698, 'CCWM': 27.974, 'TeamName': 'Gilded Gears'}, {'TeamNum': 19696, 'OPR': 80.005, 'Auto': -1.598, 'CCWM': -18.106, 'TeamName': 'B.O.T.S.'}, {'TeamNum': 12115, 'OPR': 79.818, 'Auto': 7.76, 'CCWM': -37.066, 'TeamName': 'Phoen-X'}, {'TeamNum': 16311, 'OPR': 78.638, 'Auto': 19.238, 'CCWM': -7.044, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 21879, 'OPR': 75.795, 'Auto': 17.993, 'CCWM': 16.236, 'TeamName': 'Checkmate'}, {'TeamNum': 11093, 'OPR': 73.462, 'Auto': 17.246, 'CCWM': -9.936, 'TeamName': 'MegaKnytes'}, {'TeamNum': 4545, 'OPR': 72.922, 'Auto': 9.253, 'CCWM': 0.44, 'TeamName': 'ViperBots Ouroboros'}, {'TeamNum': 10862, 'OPR': 70.617, 'Auto': 15.647, 'CCWM': -24.114, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 5628, 'OPR': 69.848, 'Auto': 19.856, 'CCWM': 5.804, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 7161, 'OPR': 63.605, 'Auto': 8.866, 'CCWM': 1.495, 'TeamName': 'ViperBots Hydra'}, {'TeamNum': 14361, 'OPR': 56.818, 'Auto': 8.834, 'CCWM': -37.159, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 15703, 'OPR': 53.74, 'Auto': 23.968, 'CCWM': -51.961, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 12597, 'OPR': 52.035, 'Auto': 15.359, 'CCWM': -39.431, 'TeamName': 'RAGNAROK ROBOTICS'}, {'TeamNum': 15758, 'OPR': 46.269, 'Auto': 2.332, 'CCWM': -40.048, 'TeamName': 'PiRate Brigade'}, {'TeamNum': 18094, 'OPR': 44.737, 'Auto': 13.878, 'CCWM': -17.999, 'TeamName': 'BASIS Batteries Not Included'}, {'TeamNum': 20741, 'OPR': 41.281, 'Auto': -5.778, 'CCWM': -49.148, 'TeamName': 'Checkmate'}, {'TeamNum': 12302, 'OPR': 34.637, 'Auto': -3.761, 'CCWM': -36.617, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 16832, 'OPR': 32.464, 'Auto': 10.506, 'CCWM': -70.482, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 12596, 'OPR': 32.39, 'Auto': -10.316, 'CCWM': -48.692, 'TeamName': 'ViperBots Copperhead'}, {'TeamNum': 6407, 'OPR': 21.611, 'Auto': 23.809, 'CCWM': -78.892, 'TeamName': 'Mechanical Mustangs Secretariat'}]

i 1093
{'21895', '15749', '19697', '10533', '10373', '21977', '11002', '16927', '15413', '3747'}
[{'TeamNum': 15413, 'OPR': 96.094, 'Auto': 13.513, 'CCWM': 62.464, 'TeamName': 'Toaster Medics'}, {'TeamNum': 19697, 'OPR': 68.306, 'Auto': 21.073, 'CCWM': 17.192, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 3747, 'OPR': 56.566, 'Auto': 13.405, 'CCWM': 20.985, 'TeamName': 'The Hive'}, {'TeamNum': 21977, 'OPR': 46.335, 'Auto': 11.437, 'CCWM': 7.302, 'TeamName': 'ElectroSloths'}, {'TeamNum': 11002, 'OPR': 41.199, 'Auto': 10.154, 'CCWM': 8.385, 'TeamName': 'Die Toaste'}, {'TeamNum': 10373, 'OPR': 27.317, 'Auto': 4.557, 'CCWM': -23.928, 'TeamName': 'Black Ops'}, {'TeamNum': 16927, 'OPR': 25.853, 'Auto': 2.374, 'CCWM': 1.573, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 21895, 'OPR': 22.623, 'Auto': 15.905, 'CCWM': -25.287, 'TeamName': 'Töster Strüüüüüdel'}, {'TeamNum': 10533, 'OPR': 21.692, 'Auto': -3.684, 'CCWM': -8.747, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 15749, 'OPR': 3.834, 'Auto': -3.103, 'CCWM': -65.598, 'TeamName': 'OHMS Baconators '}]
USUTSJQ2
[{'TeamNum': 15413, 'OPR': 96.094, 'Auto': 13.513, 'CCWM': 62.464, 'TeamName': 'Toaster Medics'}, {'TeamNum': 19697, 'OPR': 68.306, 'Auto': 21.073, 'CCWM': 17.192, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 3747, 'OPR': 56.566, 'Auto': 13.405, 'CCWM': 20.985, 'TeamName': 'The Hive'}, {'TeamNum': 21977, 'OPR': 46.335, 'Auto': 11.437, 'CCWM': 7.302, 'TeamName': 'ElectroSloths'}, {'TeamNum': 11002, 'OPR': 41.199, 'Auto': 10.154, 'CCWM': 8.385, 'TeamName': 'Die Toaste'}, {'TeamNum': 10373, 'OPR': 27.317, 'Auto': 4.557, 'CCWM': -23.928, 'TeamName': 'Black Ops'}, {'TeamNum': 16927, 'OPR': 25.853, 'Auto': 2.374, 'CCWM': 1.573, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 21895, 'OPR': 22.623, 'Auto': 15.905, 'CCWM': -25.287, 'TeamName': 'Töster Strüüüüüdel'}, {'TeamNum': 10533, 'OPR': 21.692, 'Auto': -3.684, 'CCWM': -8.747, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 15749, 'OPR': 3.834, 'Auto': -3.103, 'CCWM': -65.598, 'TeamName': 'OHMS Baconators '}]
i 1094
{'21736', '5009', '16544', '10544', '20176', '20802', '21593', '14021', '20085', '14718', '12094', '14717', '16596', '22212', '22459', '20707', '21339', '22029', '22315', '22092', '15254', '16932', '20125', '4169', '21832', '10015', '16595', '14023', '22531', '15259', '22188', '18450', '7277'}
[{'TeamNum': 16544, 'OPR': 113.217, 'Auto': 22.948, 'CCWM': 50.751, 'TeamName': 'Stratobots'}, {'TeamNum': 18450, 'OPR': 112.739, 'Auto': 38.102, 'CCWM': 33.251, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 22092, 'OPR': 87.531, 'Auto': 34.236, 'CCWM': 29.629, 'TeamName': 'Cyber Eagles - Jade'}, {'TeamNum': 22029, 'OPR': 79.306, 'Auto': 21.301, 'CCWM': 47.342, 'TeamName': 'ASAP'}, {'TeamNum': 14021, 'OPR': 79.107, 'Auto': 12.431, 'CCWM': 2.369, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 10544, 'OPR': 77.254, 'Auto': 11.341, 'CCWM': 59.833, 'TeamName': 'Cyber Eagles - Silver'}, {'TeamNum': 16595, 'OPR': 72.38, 'Auto': 10.779, 'CCWM': 20.834, 'TeamName': 'Strike Bots'}, {'TeamNum': 10015, 'OPR': 67.931, 'Auto': 14.64, 'CCWM': 29.634, 'TeamName': 'Hyper Droid'}, {'TeamNum': 14023, 'OPR': 66.842, 'Auto': 5.694, 'CCWM': 20.36, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 22188, 'OPR': 65.595, 'Auto': 10.178, 'CCWM': 27.525, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 21832, 'OPR': 63.484, 'Auto': 23.58, 'CCWM': -9.444, 'TeamName': 'Crescent Robotics'}, {'TeamNum': 20707, 'OPR': 61.602, 'Auto': 20.283, 'CCWM': -24.724, 'TeamName': 'Omegabots'}, {'TeamNum': 15259, 'OPR': 60.98, 'Auto': 21.682, 'CCWM': -3.758, 'TeamName': 'Mandela United Squadron - Third Unit'}, {'TeamNum': 20802, 'OPR': 58.886, 'Auto': 14.098, 'CCWM': 41.18, 'TeamName': 'Over Engineered'}, {'TeamNum': 14718, 'OPR': 55.074, 'Auto': 1.482, 'CCWM': 35.409, 'TeamName': 'Timberbots'}, {'TeamNum': 16932, 'OPR': 53.191, 'Auto': 12.507, 'CCWM': 10.115, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22531, 'OPR': 52.802, 'Auto': 16.392, 'CCWM': -3.747, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 7277, 'OPR': 49.88, 'Auto': 5.251, 'CCWM': -14.914, 'TeamName': 'Mandela United Squadron - First Unit'}, {'TeamNum': 20125, 'OPR': 49.821, 'Auto': 9.635, 'CCWM': -22.116, 'TeamName': 'Webber Robocats'}, {'TeamNum': 15254, 'OPR': 47.483, 'Auto': 16.096, 'CCWM': -7.062, 'TeamName': 'Facey Robotics'}, {'TeamNum': 5009, 'OPR': 47.415, 'Auto': 14.813, 'CCWM': 0.76, 'TeamName': 'Hélios'}, {'TeamNum': 20176, 'OPR': 46.709, 'Auto': 31.019, 'CCWM': -0.08, 'TeamName': 'Aberhart Allen Keys'}, {'TeamNum': 20085, 'OPR': 44.372, 'Auto': 7.042, 'CCWM': -0.262, 'TeamName': 'Pumabotics'}, {'TeamNum': 4169, 'OPR': 39.97, 'Auto': 20.169, 'CCWM': -24.861, 'TeamName': 'H.A.R.I.S.H.'}, {'TeamNum': 22212, 'OPR': 35.757, 'Auto': 9.336, 'CCWM': -17.563, 'TeamName': 'Aberhart Beta'}, {'TeamNum': 12094, 'OPR': 30.688, 'Auto': 4.82, 'CCWM': -7.6, 'TeamName': 'Team TWOSE'}, {'TeamNum': 22459, 'OPR': 29.601, 'Auto': 9.587, 'CCWM': 6.051, 'TeamName': 'SJHS Falcons - Grey_2'}, {'TeamNum': 21736, 'OPR': 27.319, 'Auto': 21.055, 'CCWM': -50.08, 'TeamName': 'Neo Robotics'}, {'TeamNum': 14717, 'OPR': 24.107, 'Auto': 10.48, 'CCWM': -21.238, 'TeamName': 'Mandela United Squadron - Second Unit'}, {'TeamNum': 22315, 'OPR': 19.796, 'Auto': 14.521, 'CCWM': -53.399, 'TeamName': 'Killa-Bytes'}, {'TeamNum': 21339, 'OPR': 18.516, 'Auto': 3.563, 'CCWM': -51.573, 'TeamName': 'Salisbury Robotics'}, {'TeamNum': 16596, 'OPR': 10.106, 'Auto': 1.92, 'CCWM': -45.812, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 21593, 'OPR': -3.919, 'Auto': -1.433, 'CCWM': -67.911, 'TeamName': 'Higgins Hawks'}]
CAABCMP
[{'TeamNum': 16544, 'OPR': 113.217, 'Auto': 22.948, 'CCWM': 50.751, 'TeamName': 'Stratobots'}, {'TeamNum': 18450, 'OPR': 112.739, 'Auto': 38.102, 'CCWM': 33.251, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 22092, 'OPR': 87.531, 'Auto': 34.236, 'CCWM': 29.629, 'TeamName': 'Cyber Eagles - Jade'}, {'TeamNum': 22029, 'OPR': 79.306, 'Auto': 21.301, 'CCWM': 47.342, 'TeamName': 'ASAP'}, {'TeamNum': 14021, 'OPR': 79.107, 'Auto': 12.431, 'CCWM': 2.369, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 10544, 'OPR': 77.254, 'Auto': 11.341, 'CCWM': 59.833, 'TeamName': 'Cyber Eagles - Silver'}, {'TeamNum': 16595, 'OPR': 72.38, 'Auto': 10.779, 'CCWM': 20.834, 'TeamName': 'Strike Bots'}, {'TeamNum': 10015, 'OPR': 67.931, 'Auto': 14.64, 'CCWM': 29.634, 'TeamName': 'Hyper Droid'}, {'TeamNum': 14023, 'OPR': 66.842, 'Auto': 5.694, 'CCWM': 20.36, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 22188, 'OPR': 65.595, 'Auto': 10.178, 'CCWM': 27.525, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 21832, 'OPR': 63.484, 'Auto': 23.58, 'CCWM': -9.444, 'TeamName': 'Crescent Robotics'}, {'TeamNum': 20707, 'OPR': 61.602, 'Auto': 20.283, 'CCWM': -24.724, 'TeamName': 'Omegabots'}, {'TeamNum': 15259, 'OPR': 60.98, 'Auto': 21.682, 'CCWM': -3.758, 'TeamName': 'Mandela United Squadron - Third Unit'}, {'TeamNum': 20802, 'OPR': 58.886, 'Auto': 14.098, 'CCWM': 41.18, 'TeamName': 'Over Engineered'}, {'TeamNum': 14718, 'OPR': 55.074, 'Auto': 1.482, 'CCWM': 35.409, 'TeamName': 'Timberbots'}, {'TeamNum': 16932, 'OPR': 53.191, 'Auto': 12.507, 'CCWM': 10.115, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22531, 'OPR': 52.802, 'Auto': 16.392, 'CCWM': -3.747, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 7277, 'OPR': 49.88, 'Auto': 5.251, 'CCWM': -14.914, 'TeamName': 'Mandela United Squadron - First Unit'}, {'TeamNum': 20125, 'OPR': 49.821, 'Auto': 9.635, 'CCWM': -22.116, 'TeamName': 'Webber Robocats'}, {'TeamNum': 15254, 'OPR': 47.483, 'Auto': 16.096, 'CCWM': -7.062, 'TeamName': 'Facey Robotics'}, {'TeamNum': 5009, 'OPR': 47.415, 'Auto': 14.813, 'CCWM': 0.76, 'TeamName': 'Hélios'}, {'TeamNum': 20176, 'OPR': 46.709, 'Auto': 31.019, 'CCWM': -0.08, 'TeamName': 'Aberhart Allen Keys'}, {'TeamNum': 20085, 'OPR': 44.372, 'Auto': 7.042, 'CCWM': -0.262, 'TeamName': 'Pumabotics'}, {'TeamNum': 4169, 'OPR': 39.97, 'Auto': 20.169, 'CCWM': -24.861, 'TeamName': 'H.A.R.I.S.H.'}, {'TeamNum': 22212, 'OPR': 35.757, 'Auto': 9.336, 'CCWM': -17.563, 'TeamName': 'Aberhart Beta'}, {'TeamNum': 12094, 'OPR': 30.688, 'Auto': 4.82, 'CCWM': -7.6, 'TeamName': 'Team TWOSE'}, {'TeamNum': 22459, 'OPR': 29.601, 'Auto': 9.587, 'CCWM': 6.051, 'TeamName': 'SJHS Falcons - Grey_2'}, {'TeamNum': 21736, 'OPR': 27.319, 'Auto': 21.055, 'CCWM': -50.08, 'TeamName': 'Neo Robotics'}, {'TeamNum': 14717, 'OPR': 24.107, 'Auto': 10.48, 'CCWM': -21.238, 'TeamName': 'Mandela United Squadron - Second Unit'}, {'TeamNum': 22315, 'OPR': 19.796, 'Auto': 14.521, 'CCWM': -53.399, 'TeamName': 'Killa-Bytes'}, {'TeamNum': 21339, 'OPR': 18.516, 'Auto': 3.563, 'CCWM': -51.573, 'TeamName': 'Salisbury Robotics'}, {'TeamNum': 16596, 'OPR': 10.106, 'Auto': 1.92, 'CCWM': -45.812, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 21593, 'OPR': -3.919, 'Auto': -1.433, 'CCWM': -67.911, 'TeamName': 'Higgins Hawks'}]

i 1095
i 1096
{'18432', '18549', '19353', '19350', '21469', '18498', '19557', '19361', '22786', '18448', '19347', '19454', '21414', '22937', '21343', '20874', '19405', '22172', '18492', '22175', '18422', '19558', '19351'}
[{'TeamNum': 18422, 'OPR': 77.367, 'Auto': 17.295, 'CCWM': 39.445, 'TeamName': 'LYBOTICS Wizards Team'}, {'TeamNum': 21469, 'OPR': 77.108, 'Auto': 27.032, 'CCWM': 18.48, 'TeamName': 'Migrants Robotics Team'}, {'TeamNum': 19350, 'OPR': 73.095, 'Auto': 22.083, 'CCWM': 1.63, 'TeamName': 'LYBOTICS Insistence Team'}, {'TeamNum': 19405, 'OPR': 68.314, 'Auto': 19.797, 'CCWM': 20.716, 'TeamName': 'Ladybird Robotics Team '}, {'TeamNum': 22172, 'OPR': 67.073, 'Auto': 4.269, 'CCWM': 31.202, 'TeamName': 'AMLY Tech Robotics Team'}, {'TeamNum': 18432, 'OPR': 65.655, 'Auto': 27.508, 'CCWM': 10.901, 'TeamName': 'LYBOTICS Scout Team'}, {'TeamNum': 19347, 'OPR': 65.443, 'Auto': 13.597, 'CCWM': 3.299, 'TeamName': 'LYBOTICS Challenge Team'}, {'TeamNum': 20874, 'OPR': 62.445, 'Auto': 13.172, 'CCWM': 18.135, 'TeamName': 'SAS Tech Robotics Team'}, {'TeamNum': 22175, 'OPR': 62.324, 'Auto': 20.945, 'CCWM': -14.569, 'TeamName': 'Robotya Robotics Team'}, {'TeamNum': 19361, 'OPR': 59.914, 'Auto': 17.222, 'CCWM': 15.13, 'TeamName': 'LYBOTICS Balacris Team'}, {'TeamNum': 18492, 'OPR': 55.033, 'Auto': 24.988, 'CCWM': 3.502, 'TeamName': 'Mukhtar Robotics Team'}, {'TeamNum': 22786, 'OPR': 52.171, 'Auto': 22.929, 'CCWM': 12.56, 'TeamName': 'Basida Robotics Team'}, {'TeamNum': 21343, 'OPR': 43.11, 'Auto': 18.676, 'CCWM': -5.849, 'TeamName': 'LYBOTICS Ghosts Team '}, {'TeamNum': 22937, 'OPR': 39.093, 'Auto': 10.426, 'CCWM': -20.603, 'TeamName': 'Waves Tech1'}, {'TeamNum': 18448, 'OPR': 36.286, 'Auto': 16.128, 'CCWM': 7.624, 'TeamName': 'LYBOTICS Castle Team'}, {'TeamNum': 18549, 'OPR': 36.258, 'Auto': 16.662, 'CCWM': -17.668, 'TeamName': 'LYBOTICS Quanta Team'}, {'TeamNum': 19353, 'OPR': 34.82, 'Auto': -4.604, 'CCWM': 27.355, 'TeamName': 'LYBOTICS Geniuses Team'}, {'TeamNum': 19557, 'OPR': 34.74, 'Auto': 13.579, 'CCWM': -0.722, 'TeamName': 'Los Matadores Scout Robotics Team'}, {'TeamNum': 18498, 'OPR': 29.451, 'Auto': 16.242, 'CCWM': -0.085, 'TeamName': 'LYBOTICS Change Team'}, {'TeamNum': 19558, 'OPR': 13.93, 'Auto': -7.001, 'CCWM': -18.086, 'TeamName': 'People of Determination Robotics Team'}, {'TeamNum': 19454, 'OPR': 9.001, 'Auto': 2.764, 'CCWM': -40.147, 'TeamName': 'LYBOTICS Icons Team'}, {'TeamNum': 19351, 'OPR': 7.606, 'Auto': 5.414, 'CCWM': -40.561, 'TeamName': 'LYBOTICS  Dracarys Team'}, {'TeamNum': 21414, 'OPR': 2.872, 'Auto': 7.231, 'CCWM': -51.671, 'TeamName': 'Scouts Girls Robotics Team'}]
LYCMP
[{'TeamNum': 18422, 'OPR': 77.367, 'Auto': 17.295, 'CCWM': 39.445, 'TeamName': 'LYBOTICS Wizards Team'}, {'TeamNum': 21469, 'OPR': 77.108, 'Auto': 27.032, 'CCWM': 18.48, 'TeamName': 'Migrants Robotics Team'}, {'TeamNum': 19350, 'OPR': 73.095, 'Auto': 22.083, 'CCWM': 1.63, 'TeamName': 'LYBOTICS Insistence Team'}, {'TeamNum': 19405, 'OPR': 68.314, 'Auto': 19.797, 'CCWM': 20.716, 'TeamName': 'Ladybird Robotics Team '}, {'TeamNum': 22172, 'OPR': 67.073, 'Auto': 4.269, 'CCWM': 31.202, 'TeamName': 'AMLY Tech Robotics Team'}, {'TeamNum': 18432, 'OPR': 65.655, 'Auto': 27.508, 'CCWM': 10.901, 'TeamName': 'LYBOTICS Scout Team'}, {'TeamNum': 19347, 'OPR': 65.443, 'Auto': 13.597, 'CCWM': 3.299, 'TeamName': 'LYBOTICS Challenge Team'}, {'TeamNum': 20874, 'OPR': 62.445, 'Auto': 13.172, 'CCWM': 18.135, 'TeamName': 'SAS Tech Robotics Team'}, {'TeamNum': 22175, 'OPR': 62.324, 'Auto': 20.945, 'CCWM': -14.569, 'TeamName': 'Robotya Robotics Team'}, {'TeamNum': 19361, 'OPR': 59.914, 'Auto': 17.222, 'CCWM': 15.13, 'TeamName': 'LYBOTICS Balacris Team'}, {'TeamNum': 18492, 'OPR': 55.033, 'Auto': 24.988, 'CCWM': 3.502, 'TeamName': 'Mukhtar Robotics Team'}, {'TeamNum': 22786, 'OPR': 52.171, 'Auto': 22.929, 'CCWM': 12.56, 'TeamName': 'Basida Robotics Team'}, {'TeamNum': 21343, 'OPR': 43.11, 'Auto': 18.676, 'CCWM': -5.849, 'TeamName': 'LYBOTICS Ghosts Team '}, {'TeamNum': 22937, 'OPR': 39.093, 'Auto': 10.426, 'CCWM': -20.603, 'TeamName': 'Waves Tech1'}, {'TeamNum': 18448, 'OPR': 36.286, 'Auto': 16.128, 'CCWM': 7.624, 'TeamName': 'LYBOTICS Castle Team'}, {'TeamNum': 18549, 'OPR': 36.258, 'Auto': 16.662, 'CCWM': -17.668, 'TeamName': 'LYBOTICS Quanta Team'}, {'TeamNum': 19353, 'OPR': 34.82, 'Auto': -4.604, 'CCWM': 27.355, 'TeamName': 'LYBOTICS Geniuses Team'}, {'TeamNum': 19557, 'OPR': 34.74, 'Auto': 13.579, 'CCWM': -0.722, 'TeamName': 'Los Matadores Scout Robotics Team'}, {'TeamNum': 18498, 'OPR': 29.451, 'Auto': 16.242, 'CCWM': -0.085, 'TeamName': 'LYBOTICS Change Team'}, {'TeamNum': 19558, 'OPR': 13.93, 'Auto': -7.001, 'CCWM': -18.086, 'TeamName': 'People of Determination Robotics Team'}, {'TeamNum': 19454, 'OPR': 9.001, 'Auto': 2.764, 'CCWM': -40.147, 'TeamName': 'LYBOTICS Icons Team'}, {'TeamNum': 19351, 'OPR': 7.606, 'Auto': 5.414, 'CCWM': -40.561, 'TeamName': 'LYBOTICS  Dracarys Team'}, {'TeamNum': 21414, 'OPR': 2.872, 'Auto': 7.231, 'CCWM': -51.671, 'TeamName': 'Scouts Girls Robotics Team'}]
i 1097
{'17855', '19095', '19088', '19055', '19103', '20985', '14278', '15966', '17243', '17860', '15972', '19066', '19211', '19342', '19109', '17844', '15993', '19086', '21028', '19098', '12632', '17870', '18160', '17857', '22017', '19120', '20974', '17713', '19048', '12560', '14270', '19067', '19093', '19105', '20043', '19083', '19176', '20691', '19071', '16166', '19099', '19151', '14277', '19062', '19234', '19079', '17861', '19061', '19104', '19053', '21071', '17869', '19115', '21455', '19074', '20912', '19121', '16000', '15996', '19068', '5843', '19049', '17871', '17873', '19096', '19101', '21972', '19141', '19044', '19116', '19106', '19063', '17624', '19075', '17962', '21097'}
[{'TeamNum': 19044, 'OPR': 155.164, 'Auto': 41.77, 'CCWM': 58.733, 'TeamName': 'Peppers'}, {'TeamNum': 12560, 'OPR': 153.565, 'Auto': 41.476, 'CCWM': 15.711, 'TeamName': 'Soft Hoarders'}, {'TeamNum': 15972, 'OPR': 149.545, 'Auto': 50.909, 'CCWM': 61.453, 'TeamName': 'TehnoZ'}, {'TeamNum': 19234, 'OPR': 149.007, 'Auto': 56.955, 'CCWM': 36.475, 'TeamName': 'BYTE FORCE'}, {'TeamNum': 17713, 'OPR': 147.748, 'Auto': 42.873, 'CCWM': 100.388, 'TeamName': 'Delta Force'}, {'TeamNum': 19066, 'OPR': 137.307, 'Auto': 37.644, 'CCWM': 65.825, 'TeamName': 'AiCitizensRO160'}, {'TeamNum': 16166, 'OPR': 136.474, 'Auto': 45.093, 'CCWM': 61.439, 'TeamName': "Watt'S Up"}, {'TeamNum': 19109, 'OPR': 134.388, 'Auto': 35.605, 'CCWM': 52.763, 'TeamName': 'RaSky'}, {'TeamNum': 19098, 'OPR': 133.177, 'Auto': 39.782, 'CCWM': -4.789, 'TeamName': 'Eastern Foxes'}, {'TeamNum': 19105, 'OPR': 131.881, 'Auto': 38.03, 'CCWM': 34.521, 'TeamName': 'DecebalTech'}, {'TeamNum': 19121, 'OPR': 130.472, 'Auto': 40.17, 'CCWM': 68.505, 'TeamName': 'Tea Borgs'}, {'TeamNum': 20912, 'OPR': 129.542, 'Auto': 21.152, 'CCWM': -44.209, 'TeamName': 'Harambe Cartel'}, {'TeamNum': 17857, 'OPR': 128.842, 'Auto': 39.106, 'CCWM': 64.588, 'TeamName': 'Gentlemen'}, {'TeamNum': 17962, 'OPR': 126.679, 'Auto': 34.907, 'CCWM': 104.573, 'TeamName': 'Ro2D2'}, {'TeamNum': 19211, 'OPR': 124.944, 'Auto': 31.349, 'CCWM': 16.369, 'TeamName': 'VirtualWolvesRO165'}, {'TeamNum': 18160, 'OPR': 124.9, 'Auto': 35.445, 'CCWM': 60.167, 'TeamName': '4D-Robotics'}, {'TeamNum': 19071, 'OPR': 124.698, 'Auto': 27.317, 'CCWM': 23.988, 'TeamName': 'SmartCluster'}, {'TeamNum': 17861, 'OPR': 119.981, 'Auto': 42.873, 'CCWM': 100.35, 'TeamName': 'CSH'}, {'TeamNum': 19083, 'OPR': 116.694, 'Auto': 30.413, 'CCWM': 45.428, 'TeamName': 'North East Dynamics'}, {'TeamNum': 19104, 'OPR': 113.689, 'Auto': 38.015, 'CCWM': 7.357, 'TeamName': 'CyberPunk Robotics'}, {'TeamNum': 19068, 'OPR': 112.259, 'Auto': 19.431, 'CCWM': 21.156, 'TeamName': 'ABSO-TECH'}, {'TeamNum': 20043, 'OPR': 111.41, 'Auto': 25.214, 'CCWM': 9.933, 'TeamName': 'SNGine'}, {'TeamNum': 17860, 'OPR': 108.453, 'Auto': 26.501, 'CCWM': -24.022, 'TeamName': 'Helix'}, {'TeamNum': 17855, 'OPR': 105.047, 'Auto': 21.945, 'CCWM': 26.036, 'TeamName': 'Vortex Breakers'}, {'TeamNum': 19101, 'OPR': 103.863, 'Auto': 25.006, 'CCWM': 40.46, 'TeamName': 'Tech-X'}, {'TeamNum': 19049, 'OPR': 103.603, 'Auto': 23.626, 'CCWM': 6.093, 'TeamName': 'HighFive Robotics'}, {'TeamNum': 14270, 'OPR': 100.754, 'Auto': 30.474, 'CCWM': -0.845, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 19079, 'OPR': 100.541, 'Auto': 31.623, 'CCWM': -0.035, 'TeamName': 'PHOENIX'}, {'TeamNum': 19099, 'OPR': 100.384, 'Auto': 31.213, 'CCWM': 5.038, 'TeamName': 'H-tech'}, {'TeamNum': 19106, 'OPR': 98.812, 'Auto': 15.674, 'CCWM': -2.325, 'TeamName': 'Dark Energy'}, {'TeamNum': 19062, 'OPR': 98.579, 'Auto': 18.661, 'CCWM': -26.575, 'TeamName': 'Phantom Robotics'}, {'TeamNum': 16000, 'OPR': 95.562, 'Auto': 14.991, 'CCWM': -9.479, 'TeamName': 'Gear Maniacs'}, {'TeamNum': 17243, 'OPR': 94.632, 'Auto': 23.41, 'CCWM': 31.849, 'TeamName': 'Vianu Legends'}, {'TeamNum': 5843, 'OPR': 94.562, 'Auto': 33.391, 'CCWM': -14.209, 'TeamName': 'AutoVortex'}, {'TeamNum': 19088, 'OPR': 94.191, 'Auto': 25.744, 'CCWM': -13.399, 'TeamName': 'BROBOTS'}, {'TeamNum': 17873, 'OPR': 91.639, 'Auto': 20.479, 'CCWM': -18.891, 'TeamName': 'VECTRON'}, {'TeamNum': 19048, 'OPR': 89.845, 'Auto': 27.771, 'CCWM': -31.92, 'TeamName': 'ROBOPAPIU'}, {'TeamNum': 19115, 'OPR': 89.064, 'Auto': 15.997, 'CCWM': -4.151, 'TeamName': 'B-RoboTeam RO 064'}, {'TeamNum': 17871, 'OPR': 88.099, 'Auto': 29.389, 'CCWM': 17.817, 'TeamName': 'Thobor RO 068'}, {'TeamNum': 17869, 'OPR': 88.017, 'Auto': 27.849, 'CCWM': 10.403, 'TeamName': 'ERcast2020'}, {'TeamNum': 19342, 'OPR': 87.18, 'Auto': 14.419, 'CCWM': 26.655, 'TeamName': 'Clever Core'}, {'TeamNum': 21028, 'OPR': 84.282, 'Auto': 21.836, 'CCWM': 35.395, 'TeamName': 'The Eagles RO143'}, {'TeamNum': 12632, 'OPR': 83.77, 'Auto': 2.252, 'CCWM': 17.465, 'TeamName': 'Transilvania Robotix'}, {'TeamNum': 19086, 'OPR': 83.677, 'Auto': 24.683, 'CCWM': -6.475, 'TeamName': 'Robocorns RO004'}, {'TeamNum': 21972, 'OPR': 82.71, 'Auto': 19.897, 'CCWM': -29.69, 'TeamName': 'LTASrob'}, {'TeamNum': 22017, 'OPR': 81.803, 'Auto': 17.084, 'CCWM': 8.072, 'TeamName': 'Eu codez'}, {'TeamNum': 15993, 'OPR': 79.583, 'Auto': 20.272, 'CCWM': 3.824, 'TeamName': 'infO(1)Robotics'}, {'TeamNum': 20691, 'OPR': 73.72, 'Auto': 18.234, 'CCWM': -12.036, 'TeamName': 'Andromeda'}, {'TeamNum': 17870, 'OPR': 73.562, 'Auto': 17.323, 'CCWM': -31.452, 'TeamName': 'PERPETUUM MOBILE'}, {'TeamNum': 19061, 'OPR': 71.999, 'Auto': 21.401, 'CCWM': 12.003, 'TeamName': 'Boogeybots'}, {'TeamNum': 19053, 'OPR': 71.69, 'Auto': 15.311, 'CCWM': -5.088, 'TeamName': 'Homosapiens'}, {'TeamNum': 19151, 'OPR': 68.823, 'Auto': 11.294, 'CCWM': -26.934, 'TeamName': 'TECHNO-MAISTER'}, {'TeamNum': 17624, 'OPR': 68.755, 'Auto': 22.78, 'CCWM': 7.994, 'TeamName': 'IGNITE.'}, {'TeamNum': 14278, 'OPR': 64.641, 'Auto': 20.252, 'CCWM': -34.811, 'TeamName': 'Xeo'}, {'TeamNum': 19063, 'OPR': 64.119, 'Auto': 14.108, 'CCWM': -1.852, 'TeamName': 'UnderConstruction'}, {'TeamNum': 19095, 'OPR': 64.076, 'Auto': 29.164, 'CCWM': -28.341, 'TeamName': 'WireImpulse'}, {'TeamNum': 17844, 'OPR': 61.994, 'Auto': 24.394, 'CCWM': -5.259, 'TeamName': 'RUBIX'}, {'TeamNum': 20985, 'OPR': 60.236, 'Auto': 11.566, 'CCWM': -51.429, 'TeamName': 'Wafy '}, {'TeamNum': 19176, 'OPR': 59.498, 'Auto': 25.619, 'CCWM': -14.993, 'TeamName': 'Broboti'}, {'TeamNum': 15996, 'OPR': 59.006, 'Auto': 5.715, 'CCWM': -95.211, 'TeamName': 'BrickBot'}, {'TeamNum': 21097, 'OPR': 53.892, 'Auto': -2.271, 'CCWM': -31.646, 'TeamName': 'Dragonfly'}, {'TeamNum': 19141, 'OPR': 53.258, 'Auto': 14.918, 'CCWM': -46.389, 'TeamName': 'BraveBots'}, {'TeamNum': 19074, 'OPR': 52.739, 'Auto': 13.833, 'CCWM': -33.726, 'TeamName': 'Extropy'}, {'TeamNum': 19096, 'OPR': 51.321, 'Auto': 11.009, 'CCWM': -56.372, 'TeamName': 'DanubeRobotics'}, {'TeamNum': 14277, 'OPR': 48.656, 'Auto': 17.021, 'CCWM': -8.628, 'TeamName': 'QUBE.'}, {'TeamNum': 21455, 'OPR': 45.518, 'Auto': 4.35, 'CCWM': -3.394, 'TeamName': 'RoSophia'}, {'TeamNum': 19055, 'OPR': 44.916, 'Auto': 4.392, 'CCWM': 24.59, 'TeamName': 'TITANS'}, {'TeamNum': 19116, 'OPR': 42.941, 'Auto': 4.977, 'CCWM': -67.096, 'TeamName': 'VV Robots'}, {'TeamNum': 20974, 'OPR': 42.775, 'Auto': -7.619, 'CCWM': -52.06, 'TeamName': 'Hardwired'}, {'TeamNum': 19067, 'OPR': 42.516, 'Auto': 11.201, 'CCWM': -66.765, 'TeamName': 'BIONIC ROYALS'}, {'TeamNum': 19103, 'OPR': 37.742, 'Auto': 4.351, 'CCWM': -35.596, 'TeamName': 'Kronbot'}, {'TeamNum': 15966, 'OPR': 33.107, 'Auto': 19.01, 'CCWM': -49.422, 'TeamName': 'Esentza Revolution'}, {'TeamNum': 21071, 'OPR': 29.842, 'Auto': 6.184, 'CCWM': -113.643, 'TeamName': 'SkyLine'}, {'TeamNum': 19075, 'OPR': 25.846, 'Auto': 16.154, 'CCWM': -91.289, 'TeamName': 'Clockworks'}, {'TeamNum': 19120, 'OPR': 22.45, 'Auto': 2.843, 'CCWM': -69.988, 'TeamName': 'AlphaBit'}, {'TeamNum': 19093, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Infinity Bolts '}]
ROCMP1
[{'TeamNum': 19044, 'OPR': 155.164, 'Auto': 41.77, 'CCWM': 58.733, 'TeamName': 'Peppers'}, {'TeamNum': 12560, 'OPR': 153.565, 'Auto': 41.476, 'CCWM': 15.711, 'TeamName': 'Soft Hoarders'}, {'TeamNum': 15972, 'OPR': 149.545, 'Auto': 50.909, 'CCWM': 61.453, 'TeamName': 'TehnoZ'}, {'TeamNum': 19234, 'OPR': 149.007, 'Auto': 56.955, 'CCWM': 36.475, 'TeamName': 'BYTE FORCE'}, {'TeamNum': 17713, 'OPR': 147.748, 'Auto': 42.873, 'CCWM': 100.388, 'TeamName': 'Delta Force'}, {'TeamNum': 19066, 'OPR': 137.307, 'Auto': 37.644, 'CCWM': 65.825, 'TeamName': 'AiCitizensRO160'}, {'TeamNum': 16166, 'OPR': 136.474, 'Auto': 45.093, 'CCWM': 61.439, 'TeamName': "Watt'S Up"}, {'TeamNum': 19109, 'OPR': 134.388, 'Auto': 35.605, 'CCWM': 52.763, 'TeamName': 'RaSky'}, {'TeamNum': 19098, 'OPR': 133.177, 'Auto': 39.782, 'CCWM': -4.789, 'TeamName': 'Eastern Foxes'}, {'TeamNum': 19105, 'OPR': 131.881, 'Auto': 38.03, 'CCWM': 34.521, 'TeamName': 'DecebalTech'}, {'TeamNum': 19121, 'OPR': 130.472, 'Auto': 40.17, 'CCWM': 68.505, 'TeamName': 'Tea Borgs'}, {'TeamNum': 20912, 'OPR': 129.542, 'Auto': 21.152, 'CCWM': -44.209, 'TeamName': 'Harambe Cartel'}, {'TeamNum': 17857, 'OPR': 128.842, 'Auto': 39.106, 'CCWM': 64.588, 'TeamName': 'Gentlemen'}, {'TeamNum': 17962, 'OPR': 126.679, 'Auto': 34.907, 'CCWM': 104.573, 'TeamName': 'Ro2D2'}, {'TeamNum': 19211, 'OPR': 124.944, 'Auto': 31.349, 'CCWM': 16.369, 'TeamName': 'VirtualWolvesRO165'}, {'TeamNum': 18160, 'OPR': 124.9, 'Auto': 35.445, 'CCWM': 60.167, 'TeamName': '4D-Robotics'}, {'TeamNum': 19071, 'OPR': 124.698, 'Auto': 27.317, 'CCWM': 23.988, 'TeamName': 'SmartCluster'}, {'TeamNum': 17861, 'OPR': 119.981, 'Auto': 42.873, 'CCWM': 100.35, 'TeamName': 'CSH'}, {'TeamNum': 19083, 'OPR': 116.694, 'Auto': 30.413, 'CCWM': 45.428, 'TeamName': 'North East Dynamics'}, {'TeamNum': 19104, 'OPR': 113.689, 'Auto': 38.015, 'CCWM': 7.357, 'TeamName': 'CyberPunk Robotics'}, {'TeamNum': 19068, 'OPR': 112.259, 'Auto': 19.431, 'CCWM': 21.156, 'TeamName': 'ABSO-TECH'}, {'TeamNum': 20043, 'OPR': 111.41, 'Auto': 25.214, 'CCWM': 9.933, 'TeamName': 'SNGine'}, {'TeamNum': 17860, 'OPR': 108.453, 'Auto': 26.501, 'CCWM': -24.022, 'TeamName': 'Helix'}, {'TeamNum': 17855, 'OPR': 105.047, 'Auto': 21.945, 'CCWM': 26.036, 'TeamName': 'Vortex Breakers'}, {'TeamNum': 19101, 'OPR': 103.863, 'Auto': 25.006, 'CCWM': 40.46, 'TeamName': 'Tech-X'}, {'TeamNum': 19049, 'OPR': 103.603, 'Auto': 23.626, 'CCWM': 6.093, 'TeamName': 'HighFive Robotics'}, {'TeamNum': 14270, 'OPR': 100.754, 'Auto': 30.474, 'CCWM': -0.845, 'TeamName': 'Quantum Robotics'}, {'TeamNum': 19079, 'OPR': 100.541, 'Auto': 31.623, 'CCWM': -0.035, 'TeamName': 'PHOENIX'}, {'TeamNum': 19099, 'OPR': 100.384, 'Auto': 31.213, 'CCWM': 5.038, 'TeamName': 'H-tech'}, {'TeamNum': 19106, 'OPR': 98.812, 'Auto': 15.674, 'CCWM': -2.325, 'TeamName': 'Dark Energy'}, {'TeamNum': 19062, 'OPR': 98.579, 'Auto': 18.661, 'CCWM': -26.575, 'TeamName': 'Phantom Robotics'}, {'TeamNum': 16000, 'OPR': 95.562, 'Auto': 14.991, 'CCWM': -9.479, 'TeamName': 'Gear Maniacs'}, {'TeamNum': 17243, 'OPR': 94.632, 'Auto': 23.41, 'CCWM': 31.849, 'TeamName': 'Vianu Legends'}, {'TeamNum': 5843, 'OPR': 94.562, 'Auto': 33.391, 'CCWM': -14.209, 'TeamName': 'AutoVortex'}, {'TeamNum': 19088, 'OPR': 94.191, 'Auto': 25.744, 'CCWM': -13.399, 'TeamName': 'BROBOTS'}, {'TeamNum': 17873, 'OPR': 91.639, 'Auto': 20.479, 'CCWM': -18.891, 'TeamName': 'VECTRON'}, {'TeamNum': 19048, 'OPR': 89.845, 'Auto': 27.771, 'CCWM': -31.92, 'TeamName': 'ROBOPAPIU'}, {'TeamNum': 19115, 'OPR': 89.064, 'Auto': 15.997, 'CCWM': -4.151, 'TeamName': 'B-RoboTeam RO 064'}, {'TeamNum': 17871, 'OPR': 88.099, 'Auto': 29.389, 'CCWM': 17.817, 'TeamName': 'Thobor RO 068'}, {'TeamNum': 17869, 'OPR': 88.017, 'Auto': 27.849, 'CCWM': 10.403, 'TeamName': 'ERcast2020'}, {'TeamNum': 19342, 'OPR': 87.18, 'Auto': 14.419, 'CCWM': 26.655, 'TeamName': 'Clever Core'}, {'TeamNum': 21028, 'OPR': 84.282, 'Auto': 21.836, 'CCWM': 35.395, 'TeamName': 'The Eagles RO143'}, {'TeamNum': 12632, 'OPR': 83.77, 'Auto': 2.252, 'CCWM': 17.465, 'TeamName': 'Transilvania Robotix'}, {'TeamNum': 19086, 'OPR': 83.677, 'Auto': 24.683, 'CCWM': -6.475, 'TeamName': 'Robocorns RO004'}, {'TeamNum': 21972, 'OPR': 82.71, 'Auto': 19.897, 'CCWM': -29.69, 'TeamName': 'LTASrob'}, {'TeamNum': 22017, 'OPR': 81.803, 'Auto': 17.084, 'CCWM': 8.072, 'TeamName': 'Eu codez'}, {'TeamNum': 15993, 'OPR': 79.583, 'Auto': 20.272, 'CCWM': 3.824, 'TeamName': 'infO(1)Robotics'}, {'TeamNum': 20691, 'OPR': 73.72, 'Auto': 18.234, 'CCWM': -12.036, 'TeamName': 'Andromeda'}, {'TeamNum': 17870, 'OPR': 73.562, 'Auto': 17.323, 'CCWM': -31.452, 'TeamName': 'PERPETUUM MOBILE'}, {'TeamNum': 19061, 'OPR': 71.999, 'Auto': 21.401, 'CCWM': 12.003, 'TeamName': 'Boogeybots'}, {'TeamNum': 19053, 'OPR': 71.69, 'Auto': 15.311, 'CCWM': -5.088, 'TeamName': 'Homosapiens'}, {'TeamNum': 19151, 'OPR': 68.823, 'Auto': 11.294, 'CCWM': -26.934, 'TeamName': 'TECHNO-MAISTER'}, {'TeamNum': 17624, 'OPR': 68.755, 'Auto': 22.78, 'CCWM': 7.994, 'TeamName': 'IGNITE.'}, {'TeamNum': 14278, 'OPR': 64.641, 'Auto': 20.252, 'CCWM': -34.811, 'TeamName': 'Xeo'}, {'TeamNum': 19063, 'OPR': 64.119, 'Auto': 14.108, 'CCWM': -1.852, 'TeamName': 'UnderConstruction'}, {'TeamNum': 19095, 'OPR': 64.076, 'Auto': 29.164, 'CCWM': -28.341, 'TeamName': 'WireImpulse'}, {'TeamNum': 17844, 'OPR': 61.994, 'Auto': 24.394, 'CCWM': -5.259, 'TeamName': 'RUBIX'}, {'TeamNum': 20985, 'OPR': 60.236, 'Auto': 11.566, 'CCWM': -51.429, 'TeamName': 'Wafy '}, {'TeamNum': 19176, 'OPR': 59.498, 'Auto': 25.619, 'CCWM': -14.993, 'TeamName': 'Broboti'}, {'TeamNum': 15996, 'OPR': 59.006, 'Auto': 5.715, 'CCWM': -95.211, 'TeamName': 'BrickBot'}, {'TeamNum': 21097, 'OPR': 53.892, 'Auto': -2.271, 'CCWM': -31.646, 'TeamName': 'Dragonfly'}, {'TeamNum': 19141, 'OPR': 53.258, 'Auto': 14.918, 'CCWM': -46.389, 'TeamName': 'BraveBots'}, {'TeamNum': 19074, 'OPR': 52.739, 'Auto': 13.833, 'CCWM': -33.726, 'TeamName': 'Extropy'}, {'TeamNum': 19096, 'OPR': 51.321, 'Auto': 11.009, 'CCWM': -56.372, 'TeamName': 'DanubeRobotics'}, {'TeamNum': 14277, 'OPR': 48.656, 'Auto': 17.021, 'CCWM': -8.628, 'TeamName': 'QUBE.'}, {'TeamNum': 21455, 'OPR': 45.518, 'Auto': 4.35, 'CCWM': -3.394, 'TeamName': 'RoSophia'}, {'TeamNum': 19055, 'OPR': 44.916, 'Auto': 4.392, 'CCWM': 24.59, 'TeamName': 'TITANS'}, {'TeamNum': 19116, 'OPR': 42.941, 'Auto': 4.977, 'CCWM': -67.096, 'TeamName': 'VV Robots'}, {'TeamNum': 20974, 'OPR': 42.775, 'Auto': -7.619, 'CCWM': -52.06, 'TeamName': 'Hardwired'}, {'TeamNum': 19067, 'OPR': 42.516, 'Auto': 11.201, 'CCWM': -66.765, 'TeamName': 'BIONIC ROYALS'}, {'TeamNum': 19103, 'OPR': 37.742, 'Auto': 4.351, 'CCWM': -35.596, 'TeamName': 'Kronbot'}, {'TeamNum': 15966, 'OPR': 33.107, 'Auto': 19.01, 'CCWM': -49.422, 'TeamName': 'Esentza Revolution'}, {'TeamNum': 21071, 'OPR': 29.842, 'Auto': 6.184, 'CCWM': -113.643, 'TeamName': 'SkyLine'}, {'TeamNum': 19075, 'OPR': 25.846, 'Auto': 16.154, 'CCWM': -91.289, 'TeamName': 'Clockworks'}, {'TeamNum': 19120, 'OPR': 22.45, 'Auto': 2.843, 'CCWM': -69.988, 'TeamName': 'AlphaBit'}, {'TeamNum': 19093, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': 0.0, 'TeamName': 'Infinity Bolts '}]

i 1098
{'8411', '21830', '20694', '14491', '18664', '11161', '12791', '11542', '12518', '1002', '5105', '21232', '21171', '19459', '9879', '12611', '16811', '17423', '21394', '19564', '7842', '11347', '18208', '9934', '20979'}
[{'TeamNum': 12611, 'OPR': 141.609, 'Auto': 44.293, 'CCWM': 74.348, 'TeamName': 'TechNova'}, {'TeamNum': 21232, 'OPR': 132.063, 'Auto': 36.014, 'CCWM': 72.757, 'TeamName': 'no team'}, {'TeamNum': 1002, 'OPR': 125.641, 'Auto': 29.32, 'CCWM': 53.033, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 12791, 'OPR': 114.43, 'Auto': 33.001, 'CCWM': 29.117, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 14491, 'OPR': 110.121, 'Auto': 34.197, 'CCWM': 67.603, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 12518, 'OPR': 109.695, 'Auto': 37.603, 'CCWM': 63.159, 'TeamName': 'Almond Robotics'}, {'TeamNum': 9879, 'OPR': 96.277, 'Auto': 26.481, 'CCWM': 24.668, 'TeamName': 'Root Negative One'}, {'TeamNum': 21171, 'OPR': 87.302, 'Auto': 14.838, 'CCWM': 65.759, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 9934, 'OPR': 72.162, 'Auto': 17.627, 'CCWM': 5.785, 'TeamName': 'Webb Robotics - FTC'}, {'TeamNum': 7842, 'OPR': 71.691, 'Auto': 15.82, 'CCWM': 46.751, 'TeamName': 'Browncoats'}, {'TeamNum': 8411, 'OPR': 69.954, 'Auto': 11.243, 'CCWM': 14.768, 'TeamName': 'SHARP'}, {'TeamNum': 20694, 'OPR': 65.661, 'Auto': 18.082, 'CCWM': 10.875, 'TeamName': 'Craft Coalition '}, {'TeamNum': 18664, 'OPR': 60.335, 'Auto': 17.257, 'CCWM': 31.157, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 18208, 'OPR': 59.756, 'Auto': 26.636, 'CCWM': -6.155, 'TeamName': 'Trinity Titans'}, {'TeamNum': 16811, 'OPR': 53.623, 'Auto': 15.026, 'CCWM': -4.979, 'TeamName': 'MAGNETUDE BLACK'}, {'TeamNum': 19564, 'OPR': 52.854, 'Auto': 20.525, 'CCWM': -25.705, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 11542, 'OPR': 52.839, 'Auto': 18.92, 'CCWM': -3.012, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 11161, 'OPR': 52.368, 'Auto': 1.974, 'CCWM': 23.543, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 21394, 'OPR': 46.538, 'Auto': 3.999, 'CCWM': -36.625, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 20979, 'OPR': 43.919, 'Auto': 11.34, 'CCWM': -59.759, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 5105, 'OPR': 42.743, 'Auto': 5.599, 'CCWM': -37.523, 'TeamName': 'Dragons'}, {'TeamNum': 11347, 'OPR': 29.28, 'Auto': -3.328, 'CCWM': -100.188, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 19459, 'OPR': 13.046, 'Auto': 6.527, 'CCWM': -103.889, 'TeamName': 'Renaissance Rampage'}, {'TeamNum': 17423, 'OPR': 8.711, 'Auto': 2.363, 'CCWM': -92.557, 'TeamName': 'FTC Gigawatts'}, {'TeamNum': 21830, 'OPR': 2.086, 'Auto': 1.038, 'CCWM': -105.822, 'TeamName': 'Renaissance Raptors'}]
USALCMP
[{'TeamNum': 12611, 'OPR': 141.609, 'Auto': 44.293, 'CCWM': 74.348, 'TeamName': 'TechNova'}, {'TeamNum': 21232, 'OPR': 132.063, 'Auto': 36.014, 'CCWM': 72.757, 'TeamName': 'no team'}, {'TeamNum': 1002, 'OPR': 125.641, 'Auto': 29.32, 'CCWM': 53.033, 'TeamName': 'CircuitRunners Robotics - Surge'}, {'TeamNum': 12791, 'OPR': 114.43, 'Auto': 33.001, 'CCWM': 29.117, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 14491, 'OPR': 110.121, 'Auto': 34.197, 'CCWM': 67.603, 'TeamName': 'Nerdettes FTC'}, {'TeamNum': 12518, 'OPR': 109.695, 'Auto': 37.603, 'CCWM': 63.159, 'TeamName': 'Almond Robotics'}, {'TeamNum': 9879, 'OPR': 96.277, 'Auto': 26.481, 'CCWM': 24.668, 'TeamName': 'Root Negative One'}, {'TeamNum': 21171, 'OPR': 87.302, 'Auto': 14.838, 'CCWM': 65.759, 'TeamName': 'The Marvels of M12'}, {'TeamNum': 9934, 'OPR': 72.162, 'Auto': 17.627, 'CCWM': 5.785, 'TeamName': 'Webb Robotics - FTC'}, {'TeamNum': 7842, 'OPR': 71.691, 'Auto': 15.82, 'CCWM': 46.751, 'TeamName': 'Browncoats'}, {'TeamNum': 8411, 'OPR': 69.954, 'Auto': 11.243, 'CCWM': 14.768, 'TeamName': 'SHARP'}, {'TeamNum': 20694, 'OPR': 65.661, 'Auto': 18.082, 'CCWM': 10.875, 'TeamName': 'Craft Coalition '}, {'TeamNum': 18664, 'OPR': 60.335, 'Auto': 17.257, 'CCWM': 31.157, 'TeamName': 'Skyline Vikings'}, {'TeamNum': 18208, 'OPR': 59.756, 'Auto': 26.636, 'CCWM': -6.155, 'TeamName': 'Trinity Titans'}, {'TeamNum': 16811, 'OPR': 53.623, 'Auto': 15.026, 'CCWM': -4.979, 'TeamName': 'MAGNETUDE BLACK'}, {'TeamNum': 19564, 'OPR': 52.854, 'Auto': 20.525, 'CCWM': -25.705, 'TeamName': 'The Marvels of MAS'}, {'TeamNum': 11542, 'OPR': 52.839, 'Auto': 18.92, 'CCWM': -3.012, 'TeamName': 'HCMS STEM Club'}, {'TeamNum': 11161, 'OPR': 52.368, 'Auto': 1.974, 'CCWM': 23.543, 'TeamName': 'Tennessee Robotics Club'}, {'TeamNum': 21394, 'OPR': 46.538, 'Auto': 3.999, 'CCWM': -36.625, 'TeamName': 'DAR HIgh School Robotics'}, {'TeamNum': 20979, 'OPR': 43.919, 'Auto': 11.34, 'CCWM': -59.759, 'TeamName': 'Redstone Robotics'}, {'TeamNum': 5105, 'OPR': 42.743, 'Auto': 5.599, 'CCWM': -37.523, 'TeamName': 'Dragons'}, {'TeamNum': 11347, 'OPR': 29.28, 'Auto': -3.328, 'CCWM': -100.188, 'TeamName': 'CircuitRunners Robotics - Blackout'}, {'TeamNum': 19459, 'OPR': 13.046, 'Auto': 6.527, 'CCWM': -103.889, 'TeamName': 'Renaissance Rampage'}, {'TeamNum': 17423, 'OPR': 8.711, 'Auto': 2.363, 'CCWM': -92.557, 'TeamName': 'FTC Gigawatts'}, {'TeamNum': 21830, 'OPR': 2.086, 'Auto': 1.038, 'CCWM': -105.822, 'TeamName': 'Renaissance Raptors'}]
i 1099
i 1100
i 1101
i 1102
{'14374', '19137', '22013', '19824', '20143', '18280', '22491', '18380', '14664', '16302', '8956', '9637', '13017', '14901', '21602', '18393', '6448', '15284', '21821', '16553', '10703', '22032', '9768'}
[{'TeamNum': 19824, 'OPR': 119.655, 'Auto': 25.092, 'CCWM': 92.599, 'TeamName': 'Pride Robotics'}, {'TeamNum': 20143, 'OPR': 87.367, 'Auto': 22.273, 'CCWM': 24.96, 'TeamName': 'Stinger Robotics Team Swarm'}, {'TeamNum': 14374, 'OPR': 83.101, 'Auto': 14.431, 'CCWM': 45.206, 'TeamName': 'Dark Matter'}, {'TeamNum': 18380, 'OPR': 73.773, 'Auto': 14.276, 'CCWM': 22.578, 'TeamName': 'Stinger Robotics Team Hive'}, {'TeamNum': 6448, 'OPR': 67.983, 'Auto': 25.288, 'CCWM': -1.835, 'TeamName': 'Blue Jays'}, {'TeamNum': 15284, 'OPR': 66.641, 'Auto': 18.703, 'CCWM': 18.044, 'TeamName': 'St. Thomas More Catholic High School'}, {'TeamNum': 10703, 'OPR': 65.741, 'Auto': 16.703, 'CCWM': 6.411, 'TeamName': 'Cyclones'}, {'TeamNum': 9637, 'OPR': 65.703, 'Auto': 13.283, 'CCWM': -0.563, 'TeamName': 'Dominican Ultraviolet'}, {'TeamNum': 16302, 'OPR': 55.624, 'Auto': 7.631, 'CCWM': 13.829, 'TeamName': 'VAL Eagle Robotics Tech Team'}, {'TeamNum': 9768, 'OPR': 53.063, 'Auto': -3.366, 'CCWM': -4.005, 'TeamName': 'Steel Eagles'}, {'TeamNum': 16553, 'OPR': 50.113, 'Auto': 9.842, 'CCWM': 24.447, 'TeamName': "Java Like it's Hot"}, {'TeamNum': 13017, 'OPR': 48.701, 'Auto': 11.891, 'CCWM': 21.2, 'TeamName': 'Event Horizon'}, {'TeamNum': 8956, 'OPR': 48.52, 'Auto': 12.639, 'CCWM': -14.648, 'TeamName': 'Team Pyrogen'}, {'TeamNum': 19137, 'OPR': 47.235, 'Auto': 12.471, 'CCWM': 15.246, 'TeamName': 'CyberGriffs'}, {'TeamNum': 18393, 'OPR': 45.205, 'Auto': -1.465, 'CCWM': 9.152, 'TeamName': 'Captcha Crew '}, {'TeamNum': 14901, 'OPR': 45.021, 'Auto': 7.476, 'CCWM': -23.278, 'TeamName': 'Cubotics Callisto'}, {'TeamNum': 22491, 'OPR': 40.492, 'Auto': 3.008, 'CCWM': -30.152, 'TeamName': 'Cubotics Orion'}, {'TeamNum': 22032, 'OPR': 38.959, 'Auto': 0.212, 'CCWM': 7.997, 'TeamName': 'MJH Eaglebots'}, {'TeamNum': 18280, 'OPR': 27.735, 'Auto': 0.513, 'CCWM': -27.873, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 14664, 'OPR': 26.049, 'Auto': 4.398, 'CCWM': -46.219, 'TeamName': 'Squire Squad'}, {'TeamNum': 22013, 'OPR': 18.219, 'Auto': -0.979, 'CCWM': -26.219, 'TeamName': 'ARC - Albany Robotics Club'}, {'TeamNum': 21602, 'OPR': 17.88, 'Auto': 1.713, 'CCWM': -66.6, 'TeamName': 'Les Garoux mechanics 1 '}, {'TeamNum': 21821, 'OPR': 6.646, 'Auto': 6.384, 'CCWM': -58.449, 'TeamName': 'SciPort Sci-bots'}]
USLACMP
[{'TeamNum': 19824, 'OPR': 119.655, 'Auto': 25.092, 'CCWM': 92.599, 'TeamName': 'Pride Robotics'}, {'TeamNum': 20143, 'OPR': 87.367, 'Auto': 22.273, 'CCWM': 24.96, 'TeamName': 'Stinger Robotics Team Swarm'}, {'TeamNum': 14374, 'OPR': 83.101, 'Auto': 14.431, 'CCWM': 45.206, 'TeamName': 'Dark Matter'}, {'TeamNum': 18380, 'OPR': 73.773, 'Auto': 14.276, 'CCWM': 22.578, 'TeamName': 'Stinger Robotics Team Hive'}, {'TeamNum': 6448, 'OPR': 67.983, 'Auto': 25.288, 'CCWM': -1.835, 'TeamName': 'Blue Jays'}, {'TeamNum': 15284, 'OPR': 66.641, 'Auto': 18.703, 'CCWM': 18.044, 'TeamName': 'St. Thomas More Catholic High School'}, {'TeamNum': 10703, 'OPR': 65.741, 'Auto': 16.703, 'CCWM': 6.411, 'TeamName': 'Cyclones'}, {'TeamNum': 9637, 'OPR': 65.703, 'Auto': 13.283, 'CCWM': -0.563, 'TeamName': 'Dominican Ultraviolet'}, {'TeamNum': 16302, 'OPR': 55.624, 'Auto': 7.631, 'CCWM': 13.829, 'TeamName': 'VAL Eagle Robotics Tech Team'}, {'TeamNum': 9768, 'OPR': 53.063, 'Auto': -3.366, 'CCWM': -4.005, 'TeamName': 'Steel Eagles'}, {'TeamNum': 16553, 'OPR': 50.113, 'Auto': 9.842, 'CCWM': 24.447, 'TeamName': "Java Like it's Hot"}, {'TeamNum': 13017, 'OPR': 48.701, 'Auto': 11.891, 'CCWM': 21.2, 'TeamName': 'Event Horizon'}, {'TeamNum': 8956, 'OPR': 48.52, 'Auto': 12.639, 'CCWM': -14.648, 'TeamName': 'Team Pyrogen'}, {'TeamNum': 19137, 'OPR': 47.235, 'Auto': 12.471, 'CCWM': 15.246, 'TeamName': 'CyberGriffs'}, {'TeamNum': 18393, 'OPR': 45.205, 'Auto': -1.465, 'CCWM': 9.152, 'TeamName': 'Captcha Crew '}, {'TeamNum': 14901, 'OPR': 45.021, 'Auto': 7.476, 'CCWM': -23.278, 'TeamName': 'Cubotics Callisto'}, {'TeamNum': 22491, 'OPR': 40.492, 'Auto': 3.008, 'CCWM': -30.152, 'TeamName': 'Cubotics Orion'}, {'TeamNum': 22032, 'OPR': 38.959, 'Auto': 0.212, 'CCWM': 7.997, 'TeamName': 'MJH Eaglebots'}, {'TeamNum': 18280, 'OPR': 27.735, 'Auto': 0.513, 'CCWM': -27.873, 'TeamName': 'Knights Robotics 1'}, {'TeamNum': 14664, 'OPR': 26.049, 'Auto': 4.398, 'CCWM': -46.219, 'TeamName': 'Squire Squad'}, {'TeamNum': 22013, 'OPR': 18.219, 'Auto': -0.979, 'CCWM': -26.219, 'TeamName': 'ARC - Albany Robotics Club'}, {'TeamNum': 21602, 'OPR': 17.88, 'Auto': 1.713, 'CCWM': -66.6, 'TeamName': 'Les Garoux mechanics 1 '}, {'TeamNum': 21821, 'OPR': 6.646, 'Auto': 6.384, 'CCWM': -58.449, 'TeamName': 'SciPort Sci-bots'}]

i 1103
{'22059', '15643', '12589', '19411', '4096', '19397', '4466', '18524', '6040', '15089', '18754', '14273', '11723', '8227', '5897', '13406', '10331', '19460', '22489', '9006', '17218', '18224', '20808', '22618', '7571', '9326', '8379', '5273', '3565', '6055', '19667', '15202', '1', '13620', '4029', '4410'}
[{'TeamNum': 3565, 'OPR': 134.421, 'Auto': 32.876, 'CCWM': 80.2, 'TeamName': 'Ghost Robotics'}, {'TeamNum': 1, 'OPR': 113.504, 'Auto': 11.637, 'CCWM': 107.769, 'TeamName': 'Team Unlimited'}, {'TeamNum': 13406, 'OPR': 107.848, 'Auto': 23.074, 'CCWM': 55.582, 'TeamName': 'Consistently Inconsistent'}, {'TeamNum': 9006, 'OPR': 107.398, 'Auto': 38.288, 'CCWM': 32.811, 'TeamName': 'Austin Prep Crusaders'}, {'TeamNum': 19411, 'OPR': 98.517, 'Auto': 30.844, 'CCWM': 53.27, 'TeamName': 'Tech Tigers'}, {'TeamNum': 15089, 'OPR': 93.961, 'Auto': 20.316, 'CCWM': 23.922, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14273, 'OPR': 85.606, 'Auto': 21.71, 'CCWM': 4.77, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 18754, 'OPR': 83.829, 'Auto': 48.091, 'CCWM': 18.774, 'TeamName': 'Galactic Narwhal Chicken Effect (GNCE)'}, {'TeamNum': 12589, 'OPR': 82.824, 'Auto': 24.126, 'CCWM': 5.812, 'TeamName': 'Pioneer Robotics'}, {'TeamNum': 4466, 'OPR': 82.161, 'Auto': 27.394, 'CCWM': 9.622, 'TeamName': 'R.A.B.B.I.'}, {'TeamNum': 8379, 'OPR': 78.318, 'Auto': -5.348, 'CCWM': 27.365, 'TeamName': 'The Parity Bits'}, {'TeamNum': 4410, 'OPR': 76.831, 'Auto': 26.465, 'CCWM': 7.045, 'TeamName': 'ARC Lightning'}, {'TeamNum': 8227, 'OPR': 73.597, 'Auto': 1.521, 'CCWM': 23.531, 'TeamName': 'Enginuity'}, {'TeamNum': 4029, 'OPR': 71.554, 'Auto': 16.913, 'CCWM': -33.841, 'TeamName': '2 Bits and a Byte'}, {'TeamNum': 7571, 'OPR': 66.786, 'Auto': 14.13, 'CCWM': -41.962, 'TeamName': 'Alumineers'}, {'TeamNum': 19460, 'OPR': 63.878, 'Auto': 7.351, 'CCWM': 46.272, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 19667, 'OPR': 61.02, 'Auto': 13.904, 'CCWM': 9.924, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 17218, 'OPR': 59.469, 'Auto': 8.825, 'CCWM': 47.269, 'TeamName': 'Brookline Bots'}, {'TeamNum': 22618, 'OPR': 59.441, 'Auto': 14.85, 'CCWM': -5.862, 'TeamName': 'MS Robotics Artemis'}, {'TeamNum': 18224, 'OPR': 58.964, 'Auto': 17.221, 'CCWM': -58.285, 'TeamName': 'Lupine'}, {'TeamNum': 19397, 'OPR': 57.859, 'Auto': 21.423, 'CCWM': 20.641, 'TeamName': 'Soli Deo Gloria'}, {'TeamNum': 22059, 'OPR': 54.819, 'Auto': 7.287, 'CCWM': 3.372, 'TeamName': 'Overclocked'}, {'TeamNum': 6055, 'OPR': 54.669, 'Auto': 8.669, 'CCWM': 39.131, 'TeamName': 'GearTicks'}, {'TeamNum': 9326, 'OPR': 54.593, 'Auto': 31.878, 'CCWM': -6.544, 'TeamName': 'Liquid Oxygen'}, {'TeamNum': 6040, 'OPR': 51.573, 'Auto': 2.284, 'CCWM': 15.826, 'TeamName': 'Canton Robodogs'}, {'TeamNum': 11723, 'OPR': 49.847, 'Auto': 20.45, 'CCWM': -33.576, 'TeamName': 'Canton GearHounds'}, {'TeamNum': 22489, 'OPR': 43.233, 'Auto': -1.807, 'CCWM': 2.239, 'TeamName': 'Galactic Narwhal Chicken Effect - Diamond'}, {'TeamNum': 13620, 'OPR': 42.736, 'Auto': -2.001, 'CCWM': -32.882, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 20808, 'OPR': 36.521, 'Auto': 12.608, 'CCWM': -23.227, 'TeamName': 'Spartans'}, {'TeamNum': 15202, 'OPR': 30.858, 'Auto': 7.896, 'CCWM': -43.708, 'TeamName': 'The Middle Dippers'}, {'TeamNum': 5897, 'OPR': 26.732, 'Auto': 10.985, 'CCWM': -58.75, 'TeamName': 'HackHers'}, {'TeamNum': 5273, 'OPR': 25.785, 'Auto': 8.451, 'CCWM': -48.924, 'TeamName': 'ARC Thunder'}, {'TeamNum': 10331, 'OPR': 22.642, 'Auto': -8.102, 'CCWM': 23.188, 'TeamName': 'ARC Hailstorm '}, {'TeamNum': 15643, 'OPR': 21.451, 'Auto': 8.027, 'CCWM': -57.234, 'TeamName': "The 'Rock Bots"}, {'TeamNum': 18524, 'OPR': 15.944, 'Auto': -2.594, 'CCWM': -101.152, 'TeamName': 'Excalibur'}, {'TeamNum': 4096, 'OPR': 13.611, 'Auto': 5.36, 'CCWM': -112.386, 'TeamName': 'T-10   ("T minus Ten")'}]
USMACMP
[{'TeamNum': 3565, 'OPR': 134.421, 'Auto': 32.876, 'CCWM': 80.2, 'TeamName': 'Ghost Robotics'}, {'TeamNum': 1, 'OPR': 113.504, 'Auto': 11.637, 'CCWM': 107.769, 'TeamName': 'Team Unlimited'}, {'TeamNum': 13406, 'OPR': 107.848, 'Auto': 23.074, 'CCWM': 55.582, 'TeamName': 'Consistently Inconsistent'}, {'TeamNum': 9006, 'OPR': 107.398, 'Auto': 38.288, 'CCWM': 32.811, 'TeamName': 'Austin Prep Crusaders'}, {'TeamNum': 19411, 'OPR': 98.517, 'Auto': 30.844, 'CCWM': 53.27, 'TeamName': 'Tech Tigers'}, {'TeamNum': 15089, 'OPR': 93.961, 'Auto': 20.316, 'CCWM': 23.922, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14273, 'OPR': 85.606, 'Auto': 21.71, 'CCWM': 4.77, 'TeamName': 'Sense & Sound Robotics'}, {'TeamNum': 18754, 'OPR': 83.829, 'Auto': 48.091, 'CCWM': 18.774, 'TeamName': 'Galactic Narwhal Chicken Effect (GNCE)'}, {'TeamNum': 12589, 'OPR': 82.824, 'Auto': 24.126, 'CCWM': 5.812, 'TeamName': 'Pioneer Robotics'}, {'TeamNum': 4466, 'OPR': 82.161, 'Auto': 27.394, 'CCWM': 9.622, 'TeamName': 'R.A.B.B.I.'}, {'TeamNum': 8379, 'OPR': 78.318, 'Auto': -5.348, 'CCWM': 27.365, 'TeamName': 'The Parity Bits'}, {'TeamNum': 4410, 'OPR': 76.831, 'Auto': 26.465, 'CCWM': 7.045, 'TeamName': 'ARC Lightning'}, {'TeamNum': 8227, 'OPR': 73.597, 'Auto': 1.521, 'CCWM': 23.531, 'TeamName': 'Enginuity'}, {'TeamNum': 4029, 'OPR': 71.554, 'Auto': 16.913, 'CCWM': -33.841, 'TeamName': '2 Bits and a Byte'}, {'TeamNum': 7571, 'OPR': 66.786, 'Auto': 14.13, 'CCWM': -41.962, 'TeamName': 'Alumineers'}, {'TeamNum': 19460, 'OPR': 63.878, 'Auto': 7.351, 'CCWM': 46.272, 'TeamName': 'Hawk Robotics --The Ryken Force'}, {'TeamNum': 19667, 'OPR': 61.02, 'Auto': 13.904, 'CCWM': 9.924, 'TeamName': 'Bionic Bishops'}, {'TeamNum': 17218, 'OPR': 59.469, 'Auto': 8.825, 'CCWM': 47.269, 'TeamName': 'Brookline Bots'}, {'TeamNum': 22618, 'OPR': 59.441, 'Auto': 14.85, 'CCWM': -5.862, 'TeamName': 'MS Robotics Artemis'}, {'TeamNum': 18224, 'OPR': 58.964, 'Auto': 17.221, 'CCWM': -58.285, 'TeamName': 'Lupine'}, {'TeamNum': 19397, 'OPR': 57.859, 'Auto': 21.423, 'CCWM': 20.641, 'TeamName': 'Soli Deo Gloria'}, {'TeamNum': 22059, 'OPR': 54.819, 'Auto': 7.287, 'CCWM': 3.372, 'TeamName': 'Overclocked'}, {'TeamNum': 6055, 'OPR': 54.669, 'Auto': 8.669, 'CCWM': 39.131, 'TeamName': 'GearTicks'}, {'TeamNum': 9326, 'OPR': 54.593, 'Auto': 31.878, 'CCWM': -6.544, 'TeamName': 'Liquid Oxygen'}, {'TeamNum': 6040, 'OPR': 51.573, 'Auto': 2.284, 'CCWM': 15.826, 'TeamName': 'Canton Robodogs'}, {'TeamNum': 11723, 'OPR': 49.847, 'Auto': 20.45, 'CCWM': -33.576, 'TeamName': 'Canton GearHounds'}, {'TeamNum': 22489, 'OPR': 43.233, 'Auto': -1.807, 'CCWM': 2.239, 'TeamName': 'Galactic Narwhal Chicken Effect - Diamond'}, {'TeamNum': 13620, 'OPR': 42.736, 'Auto': -2.001, 'CCWM': -32.882, 'TeamName': 'The Winsor Wildbots'}, {'TeamNum': 20808, 'OPR': 36.521, 'Auto': 12.608, 'CCWM': -23.227, 'TeamName': 'Spartans'}, {'TeamNum': 15202, 'OPR': 30.858, 'Auto': 7.896, 'CCWM': -43.708, 'TeamName': 'The Middle Dippers'}, {'TeamNum': 5897, 'OPR': 26.732, 'Auto': 10.985, 'CCWM': -58.75, 'TeamName': 'HackHers'}, {'TeamNum': 5273, 'OPR': 25.785, 'Auto': 8.451, 'CCWM': -48.924, 'TeamName': 'ARC Thunder'}, {'TeamNum': 10331, 'OPR': 22.642, 'Auto': -8.102, 'CCWM': 23.188, 'TeamName': 'ARC Hailstorm '}, {'TeamNum': 15643, 'OPR': 21.451, 'Auto': 8.027, 'CCWM': -57.234, 'TeamName': "The 'Rock Bots"}, {'TeamNum': 18524, 'OPR': 15.944, 'Auto': -2.594, 'CCWM': -101.152, 'TeamName': 'Excalibur'}, {'TeamNum': 4096, 'OPR': 13.611, 'Auto': 5.36, 'CCWM': -112.386, 'TeamName': 'T-10   ("T minus Ten")'}]
i 1104
{'6547', '7961', '9808', '16309', '16498', '4193', '10265', '18292', '20323', '21677', '13737', '17637', '21225', '13399', '17206', '2867', '7525', '9856', '8136', '3409', '6168', '7678', '10588', '11514', '13092', '9102', '10868', '5893', '14186', '4982', '288', '16708', '19996', '3658', '7532', '13312', '5119'}
[{'TeamNum': 3658, 'OPR': 135.998, 'Auto': 42.786, 'CCWM': 70.01, 'TeamName': 'The BOSONS'}, {'TeamNum': 20323, 'OPR': 130.139, 'Auto': 24.609, 'CCWM': 23.195, 'TeamName': 'Sigma'}, {'TeamNum': 10588, 'OPR': 120.98, 'Auto': 34.933, 'CCWM': 47.985, 'TeamName': 'The LUXONS'}, {'TeamNum': 21225, 'OPR': 106.067, 'Auto': 35.174, 'CCWM': 55.071, 'TeamName': 'Shear Force'}, {'TeamNum': 13399, 'OPR': 99.99, 'Auto': 5.525, 'CCWM': 27.324, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 13737, 'OPR': 98.729, 'Auto': 3.177, 'CCWM': 15.667, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 6547, 'OPR': 97.184, 'Auto': 20.17, 'CCWM': 47.936, 'TeamName': 'Cobalt Colts'}, {'TeamNum': 7525, 'OPR': 96.29, 'Auto': 25.678, 'CCWM': 24.776, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 10265, 'OPR': 93.458, 'Auto': 22.352, 'CCWM': -7.055, 'TeamName': 'Force Green'}, {'TeamNum': 16309, 'OPR': 88.003, 'Auto': 14.773, 'CCWM': 15.164, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 3409, 'OPR': 86.854, 'Auto': 5.064, 'CCWM': 31.04, 'TeamName': 'Astromechs'}, {'TeamNum': 21677, 'OPR': 83.926, 'Auto': 24.112, 'CCWM': 7.191, 'TeamName': 'CTEC Cerberus'}, {'TeamNum': 17206, 'OPR': 83.879, 'Auto': 16.435, 'CCWM': 29.848, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 288, 'OPR': 83.309, 'Auto': 19.056, 'CCWM': -25.474, 'TeamName': 'Spare Parts'}, {'TeamNum': 13092, 'OPR': 82.762, 'Auto': 18.738, 'CCWM': 12.502, 'TeamName': 'Central Processing Units'}, {'TeamNum': 16498, 'OPR': 81.399, 'Auto': 21.277, 'CCWM': -9.467, 'TeamName': 'Plus Gang'}, {'TeamNum': 5893, 'OPR': 78.578, 'Auto': 22.503, 'CCWM': -6.889, 'TeamName': 'Direct Current'}, {'TeamNum': 7961, 'OPR': 77.02, 'Auto': 27.24, 'CCWM': -6.318, 'TeamName': 'MotorDame'}, {'TeamNum': 10868, 'OPR': 72.529, 'Auto': 18.845, 'CCWM': 8.717, 'TeamName': 'Roboteers Cadets'}, {'TeamNum': 14186, 'OPR': 71.617, 'Auto': 17.338, 'CCWM': 30.074, 'TeamName': 'P3'}, {'TeamNum': 6168, 'OPR': 70.534, 'Auto': 2.838, 'CCWM': 24.445, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 4193, 'OPR': 69.986, 'Auto': 13.204, 'CCWM': -19.516, 'TeamName': 'Those Guys'}, {'TeamNum': 9856, 'OPR': 67.438, 'Auto': 18.701, 'CCWM': 4.353, 'TeamName': 'Spaghettified'}, {'TeamNum': 9102, 'OPR': 62.084, 'Auto': 15.54, 'CCWM': 18.119, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 9808, 'OPR': 61.494, 'Auto': 23.562, 'CCWM': -31.944, 'TeamName': 'Team Chargers'}, {'TeamNum': 13312, 'OPR': 61.06, 'Auto': -8.148, 'CCWM': -3.786, 'TeamName': 'The Bombers'}, {'TeamNum': 8136, 'OPR': 59.405, 'Auto': 25.299, 'CCWM': -22.526, 'TeamName': 'Fire and Ice'}, {'TeamNum': 19996, 'OPR': 57.924, 'Auto': 17.884, 'CCWM': 6.102, 'TeamName': 'Viking Robotics'}, {'TeamNum': 18292, 'OPR': 56.644, 'Auto': 20.888, 'CCWM': -36.527, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 7678, 'OPR': 54.23, 'Auto': 4.372, 'CCWM': -56.125, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 17637, 'OPR': 44.183, 'Auto': 8.445, 'CCWM': -8.151, 'TeamName': 'Z-Botz'}, {'TeamNum': 11514, 'OPR': 36.268, 'Auto': 5.385, 'CCWM': -37.607, 'TeamName': 'Nexus'}, {'TeamNum': 5119, 'OPR': 32.881, 'Auto': 13.23, 'CCWM': -46.936, 'TeamName': 'The BARYONS'}, {'TeamNum': 7532, 'OPR': 28.056, 'Auto': 0.795, 'CCWM': -35.654, 'TeamName': 'The Core in Blue'}, {'TeamNum': 16708, 'OPR': 23.242, 'Auto': 1.596, 'CCWM': -60.119, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 2867, 'OPR': 15.529, 'Auto': 9.126, 'CCWM': -85.424, 'TeamName': 'Degrees of Freedo'}, {'TeamNum': 4982, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Cafe Bot'}]
USMOKSCMP
[{'TeamNum': 3658, 'OPR': 135.998, 'Auto': 42.786, 'CCWM': 70.01, 'TeamName': 'The BOSONS'}, {'TeamNum': 20323, 'OPR': 130.139, 'Auto': 24.609, 'CCWM': 23.195, 'TeamName': 'Sigma'}, {'TeamNum': 10588, 'OPR': 120.98, 'Auto': 34.933, 'CCWM': 47.985, 'TeamName': 'The LUXONS'}, {'TeamNum': 21225, 'OPR': 106.067, 'Auto': 35.174, 'CCWM': 55.071, 'TeamName': 'Shear Force'}, {'TeamNum': 13399, 'OPR': 99.99, 'Auto': 5.525, 'CCWM': 27.324, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 13737, 'OPR': 98.729, 'Auto': 3.177, 'CCWM': 15.667, 'TeamName': 'Belton Cyber Pirates'}, {'TeamNum': 6547, 'OPR': 97.184, 'Auto': 20.17, 'CCWM': 47.936, 'TeamName': 'Cobalt Colts'}, {'TeamNum': 7525, 'OPR': 96.29, 'Auto': 25.678, 'CCWM': 24.776, 'TeamName': 'Nerdy Birds'}, {'TeamNum': 10265, 'OPR': 93.458, 'Auto': 22.352, 'CCWM': -7.055, 'TeamName': 'Force Green'}, {'TeamNum': 16309, 'OPR': 88.003, 'Auto': 14.773, 'CCWM': 15.164, 'TeamName': 'Stealth Panther Robotics FTC '}, {'TeamNum': 3409, 'OPR': 86.854, 'Auto': 5.064, 'CCWM': 31.04, 'TeamName': 'Astromechs'}, {'TeamNum': 21677, 'OPR': 83.926, 'Auto': 24.112, 'CCWM': 7.191, 'TeamName': 'CTEC Cerberus'}, {'TeamNum': 17206, 'OPR': 83.879, 'Auto': 16.435, 'CCWM': 29.848, 'TeamName': 'BuzzbotFTC1'}, {'TeamNum': 288, 'OPR': 83.309, 'Auto': 19.056, 'CCWM': -25.474, 'TeamName': 'Spare Parts'}, {'TeamNum': 13092, 'OPR': 82.762, 'Auto': 18.738, 'CCWM': 12.502, 'TeamName': 'Central Processing Units'}, {'TeamNum': 16498, 'OPR': 81.399, 'Auto': 21.277, 'CCWM': -9.467, 'TeamName': 'Plus Gang'}, {'TeamNum': 5893, 'OPR': 78.578, 'Auto': 22.503, 'CCWM': -6.889, 'TeamName': 'Direct Current'}, {'TeamNum': 7961, 'OPR': 77.02, 'Auto': 27.24, 'CCWM': -6.318, 'TeamName': 'MotorDame'}, {'TeamNum': 10868, 'OPR': 72.529, 'Auto': 18.845, 'CCWM': 8.717, 'TeamName': 'Roboteers Cadets'}, {'TeamNum': 14186, 'OPR': 71.617, 'Auto': 17.338, 'CCWM': 30.074, 'TeamName': 'P3'}, {'TeamNum': 6168, 'OPR': 70.534, 'Auto': 2.838, 'CCWM': 24.445, 'TeamName': 'Maniacal Mechanics'}, {'TeamNum': 4193, 'OPR': 69.986, 'Auto': 13.204, 'CCWM': -19.516, 'TeamName': 'Those Guys'}, {'TeamNum': 9856, 'OPR': 67.438, 'Auto': 18.701, 'CCWM': 4.353, 'TeamName': 'Spaghettified'}, {'TeamNum': 9102, 'OPR': 62.084, 'Auto': 15.54, 'CCWM': 18.119, 'TeamName': 'Ravonics Orion'}, {'TeamNum': 9808, 'OPR': 61.494, 'Auto': 23.562, 'CCWM': -31.944, 'TeamName': 'Team Chargers'}, {'TeamNum': 13312, 'OPR': 61.06, 'Auto': -8.148, 'CCWM': -3.786, 'TeamName': 'The Bombers'}, {'TeamNum': 8136, 'OPR': 59.405, 'Auto': 25.299, 'CCWM': -22.526, 'TeamName': 'Fire and Ice'}, {'TeamNum': 19996, 'OPR': 57.924, 'Auto': 17.884, 'CCWM': 6.102, 'TeamName': 'Viking Robotics'}, {'TeamNum': 18292, 'OPR': 56.644, 'Auto': 20.888, 'CCWM': -36.527, 'TeamName': 'The Dysfunctionals'}, {'TeamNum': 7678, 'OPR': 54.23, 'Auto': 4.372, 'CCWM': -56.125, 'TeamName': 'Eldon Gearheads Maroon Team'}, {'TeamNum': 17637, 'OPR': 44.183, 'Auto': 8.445, 'CCWM': -8.151, 'TeamName': 'Z-Botz'}, {'TeamNum': 11514, 'OPR': 36.268, 'Auto': 5.385, 'CCWM': -37.607, 'TeamName': 'Nexus'}, {'TeamNum': 5119, 'OPR': 32.881, 'Auto': 13.23, 'CCWM': -46.936, 'TeamName': 'The BARYONS'}, {'TeamNum': 7532, 'OPR': 28.056, 'Auto': 0.795, 'CCWM': -35.654, 'TeamName': 'The Core in Blue'}, {'TeamNum': 16708, 'OPR': 23.242, 'Auto': 1.596, 'CCWM': -60.119, 'TeamName': 'Redneck Engineering'}, {'TeamNum': 2867, 'OPR': 15.529, 'Auto': 9.126, 'CCWM': -85.424, 'TeamName': 'Degrees of Freedo'}, {'TeamNum': 4982, 'OPR': -0.0, 'Auto': -0.0, 'CCWM': -0.0, 'TeamName': 'Cafe Bot'}]

i 1105
{'6273', '13176', '12389', '16151', '6302', '8651', '12390', '14799', '14236', '10191', '12272', '14627', '16489', '17341', '18364', '20217', '11279', '6556'}
[{'TeamNum': 12390, 'OPR': 104.558, 'Auto': 22.825, 'CCWM': 56.966, 'TeamName': 'The Robotic Raiders'}, {'TeamNum': 8651, 'OPR': 93.271, 'Auto': 19.393, 'CCWM': 45.097, 'TeamName': 'Wait For It...'}, {'TeamNum': 6273, 'OPR': 86.245, 'Auto': 30.618, 'CCWM': 34.304, 'TeamName': 'Technocats'}, {'TeamNum': 6556, 'OPR': 83.856, 'Auto': 10.671, 'CCWM': 33.617, 'TeamName': 'Tempest'}, {'TeamNum': 10191, 'OPR': 82.631, 'Auto': 17.223, 'CCWM': 6.817, 'TeamName': 'Trial and Error Robotics'}, {'TeamNum': 16489, 'OPR': 82.227, 'Auto': 25.765, 'CCWM': 40.831, 'TeamName': 'Virtual North'}, {'TeamNum': 14627, 'OPR': 78.037, 'Auto': 11.609, 'CCWM': 2.697, 'TeamName': 'Spare Parts'}, {'TeamNum': 16151, 'OPR': 62.653, 'Auto': 8.184, 'CCWM': -18.732, 'TeamName': 'R U Serious'}, {'TeamNum': 11279, 'OPR': 59.322, 'Auto': -0.647, 'CCWM': 3.495, 'TeamName': 'Pure Imagination'}, {'TeamNum': 14236, 'OPR': 58.033, 'Auto': 15.255, 'CCWM': -6.718, 'TeamName': 'Slight Malfunction'}, {'TeamNum': 14799, 'OPR': 57.23, 'Auto': 15.028, 'CCWM': -5.052, 'TeamName': 'LCS Javawocky'}, {'TeamNum': 12389, 'OPR': 51.904, 'Auto': 10.476, 'CCWM': -15.245, 'TeamName': 'TMS Tornadoes'}, {'TeamNum': 6302, 'OPR': 45.349, 'Auto': 20.499, 'CCWM': -33.648, 'TeamName': 'Odyssey'}, {'TeamNum': 20217, 'OPR': 41.784, 'Auto': 3.548, 'CCWM': -43.261, 'TeamName': 'Surge'}, {'TeamNum': 13176, 'OPR': 37.242, 'Auto': 11.696, 'CCWM': -15.464, 'TeamName': 'Spark-O-Matic Robotics & Digital Arts'}, {'TeamNum': 12272, 'OPR': 35.863, 'Auto': 15.889, 'CCWM': -20.267, 'TeamName': 'Team Lightning'}, {'TeamNum': 17341, 'OPR': 21.16, 'Auto': 4.65, 'CCWM': -24.765, 'TeamName': 'Team Thunder'}, {'TeamNum': 18364, 'OPR': 21.135, 'Auto': 3.818, 'CCWM': -40.672, 'TeamName': 'The Bravo Seals'}]
USMSCMP
[{'TeamNum': 12390, 'OPR': 104.558, 'Auto': 22.825, 'CCWM': 56.966, 'TeamName': 'The Robotic Raiders'}, {'TeamNum': 8651, 'OPR': 93.271, 'Auto': 19.393, 'CCWM': 45.097, 'TeamName': 'Wait For It...'}, {'TeamNum': 6273, 'OPR': 86.245, 'Auto': 30.618, 'CCWM': 34.304, 'TeamName': 'Technocats'}, {'TeamNum': 6556, 'OPR': 83.856, 'Auto': 10.671, 'CCWM': 33.617, 'TeamName': 'Tempest'}, {'TeamNum': 10191, 'OPR': 82.631, 'Auto': 17.223, 'CCWM': 6.817, 'TeamName': 'Trial and Error Robotics'}, {'TeamNum': 16489, 'OPR': 82.227, 'Auto': 25.765, 'CCWM': 40.831, 'TeamName': 'Virtual North'}, {'TeamNum': 14627, 'OPR': 78.037, 'Auto': 11.609, 'CCWM': 2.697, 'TeamName': 'Spare Parts'}, {'TeamNum': 16151, 'OPR': 62.653, 'Auto': 8.184, 'CCWM': -18.732, 'TeamName': 'R U Serious'}, {'TeamNum': 11279, 'OPR': 59.322, 'Auto': -0.647, 'CCWM': 3.495, 'TeamName': 'Pure Imagination'}, {'TeamNum': 14236, 'OPR': 58.033, 'Auto': 15.255, 'CCWM': -6.718, 'TeamName': 'Slight Malfunction'}, {'TeamNum': 14799, 'OPR': 57.23, 'Auto': 15.028, 'CCWM': -5.052, 'TeamName': 'LCS Javawocky'}, {'TeamNum': 12389, 'OPR': 51.904, 'Auto': 10.476, 'CCWM': -15.245, 'TeamName': 'TMS Tornadoes'}, {'TeamNum': 6302, 'OPR': 45.349, 'Auto': 20.499, 'CCWM': -33.648, 'TeamName': 'Odyssey'}, {'TeamNum': 20217, 'OPR': 41.784, 'Auto': 3.548, 'CCWM': -43.261, 'TeamName': 'Surge'}, {'TeamNum': 13176, 'OPR': 37.242, 'Auto': 11.696, 'CCWM': -15.464, 'TeamName': 'Spark-O-Matic Robotics & Digital Arts'}, {'TeamNum': 12272, 'OPR': 35.863, 'Auto': 15.889, 'CCWM': -20.267, 'TeamName': 'Team Lightning'}, {'TeamNum': 17341, 'OPR': 21.16, 'Auto': 4.65, 'CCWM': -24.765, 'TeamName': 'Team Thunder'}, {'TeamNum': 18364, 'OPR': 21.135, 'Auto': 3.818, 'CCWM': -40.672, 'TeamName': 'The Bravo Seals'}]
i 1106
{'17280', '20681', '18203', '16158', '18815', '11183', '21238', '18850', '21707', '11574', '21535', '12991', '14532', '22774', '21632', '16118', '18682', '3050', '18858', '14841', '21726', '21787', '18419', '21517', '20285', '19792', '15884', '15569', '21629', '21794', '15889'}
[{'TeamNum': 16158, 'OPR': 159.819, 'Auto': 50.302, 'CCWM': 113.155, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 12991, 'OPR': 82.586, 'Auto': 20.719, 'CCWM': 51.618, 'TeamName': 'Awkward Silence'}, {'TeamNum': 18203, 'OPR': 77.234, 'Auto': 20.808, 'CCWM': 18.734, 'TeamName': 'MCII'}, {'TeamNum': 15569, 'OPR': 75.877, 'Auto': 21.272, 'CCWM': 42.627, 'TeamName': 'RoboRattlers'}, {'TeamNum': 21238, 'OPR': 75.27, 'Auto': 23.796, 'CCWM': 50.829, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 21517, 'OPR': 66.599, 'Auto': 10.524, 'CCWM': 55.419, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 11574, 'OPR': 66.172, 'Auto': 22.203, 'CCWM': -1.674, 'TeamName': 'Incognito'}, {'TeamNum': 11183, 'OPR': 62.408, 'Auto': 12.508, 'CCWM': 18.703, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 21787, 'OPR': 62.102, 'Auto': 12.591, 'CCWM': -17.373, 'TeamName': 'ARC - White'}, {'TeamNum': 18850, 'OPR': 59.806, 'Auto': 9.434, 'CCWM': 14.326, 'TeamName': 'Kill Switch'}, {'TeamNum': 3050, 'OPR': 59.202, 'Auto': 15.24, 'CCWM': -9.131, 'TeamName': 'G-Bots'}, {'TeamNum': 19792, 'OPR': 58.231, 'Auto': 10.414, 'CCWM': 2.098, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 14841, 'OPR': 54.918, 'Auto': 7.817, 'CCWM': 26.537, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 20681, 'OPR': 51.632, 'Auto': 14.249, 'CCWM': 15.018, 'TeamName': 'Giga Bite'}, {'TeamNum': 16118, 'OPR': 47.294, 'Auto': 4.396, 'CCWM': -25.024, 'TeamName': '52! McQueen HS'}, {'TeamNum': 15889, 'OPR': 46.395, 'Auto': -0.609, 'CCWM': -23.785, 'TeamName': 'RoboDawgs'}, {'TeamNum': 15884, 'OPR': 45.738, 'Auto': 13.846, 'CCWM': -5.712, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 18858, 'OPR': 43.54, 'Auto': -0.054, 'CCWM': -3.859, 'TeamName': 'ARC - Blue'}, {'TeamNum': 17280, 'OPR': 43.234, 'Auto': -0.928, 'CCWM': 11.74, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 22774, 'OPR': 39.737, 'Auto': 9.607, 'CCWM': -30.503, 'TeamName': 'URSA Major'}, {'TeamNum': 20285, 'OPR': 36.762, 'Auto': 16.17, 'CCWM': 6.0, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 18419, 'OPR': 35.466, 'Auto': 7.213, 'CCWM': -9.5, 'TeamName': 'Comstock Coders'}, {'TeamNum': 21535, 'OPR': 33.747, 'Auto': 19.481, 'CCWM': 7.112, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 21794, 'OPR': 30.205, 'Auto': 2.34, 'CCWM': 5.476, 'TeamName': 'Laughlin Jr/Sr HS 2'}, {'TeamNum': 21707, 'OPR': 27.461, 'Auto': 8.535, 'CCWM': -34.836, 'TeamName': 'MinerBots'}, {'TeamNum': 18815, 'OPR': 27.285, 'Auto': 4.773, 'CCWM': -9.167, 'TeamName': 'LANV Logic'}, {'TeamNum': 21632, 'OPR': 26.781, 'Auto': 1.782, 'CCWM': -61.085, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 21629, 'OPR': 18.998, 'Auto': 1.809, 'CCWM': -51.72, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 14532, 'OPR': 14.74, 'Auto': 1.17, 'CCWM': -69.703, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 18682, 'OPR': 14.396, 'Auto': 5.142, 'CCWM': -66.304, 'TeamName': 'Cyber Nights'}, {'TeamNum': 21726, 'OPR': 1.318, 'Auto': -7.953, 'CCWM': -16.07, 'TeamName': 'Laughlin Jr/Sr HS'}]
USNVCMP
[{'TeamNum': 16158, 'OPR': 159.819, 'Auto': 50.302, 'CCWM': 113.155, 'TeamName': 'VC Silver Circuits'}, {'TeamNum': 12991, 'OPR': 82.586, 'Auto': 20.719, 'CCWM': 51.618, 'TeamName': 'Awkward Silence'}, {'TeamNum': 18203, 'OPR': 77.234, 'Auto': 20.808, 'CCWM': 18.734, 'TeamName': 'MCII'}, {'TeamNum': 15569, 'OPR': 75.877, 'Auto': 21.272, 'CCWM': 42.627, 'TeamName': 'RoboRattlers'}, {'TeamNum': 21238, 'OPR': 75.27, 'Auto': 23.796, 'CCWM': 50.829, 'TeamName': 'Perpetual Motion'}, {'TeamNum': 21517, 'OPR': 66.599, 'Auto': 10.524, 'CCWM': 55.419, 'TeamName': 'High Maintenance (Sloan Canyon Robotics)'}, {'TeamNum': 11574, 'OPR': 66.172, 'Auto': 22.203, 'CCWM': -1.674, 'TeamName': 'Incognito'}, {'TeamNum': 11183, 'OPR': 62.408, 'Auto': 12.508, 'CCWM': 18.703, 'TeamName': '32 Bit McQueen HS'}, {'TeamNum': 21787, 'OPR': 62.102, 'Auto': 12.591, 'CCWM': -17.373, 'TeamName': 'ARC - White'}, {'TeamNum': 18850, 'OPR': 59.806, 'Auto': 9.434, 'CCWM': 14.326, 'TeamName': 'Kill Switch'}, {'TeamNum': 3050, 'OPR': 59.202, 'Auto': 15.24, 'CCWM': -9.131, 'TeamName': 'G-Bots'}, {'TeamNum': 19792, 'OPR': 58.231, 'Auto': 10.414, 'CCWM': 2.098, 'TeamName': 'Mighty Meadowbots Silver Team'}, {'TeamNum': 14841, 'OPR': 54.918, 'Auto': 7.817, 'CCWM': 26.537, 'TeamName': 'Mighty Meadowbots Blue Team'}, {'TeamNum': 20681, 'OPR': 51.632, 'Auto': 14.249, 'CCWM': 15.018, 'TeamName': 'Giga Bite'}, {'TeamNum': 16118, 'OPR': 47.294, 'Auto': 4.396, 'CCWM': -25.024, 'TeamName': '52! McQueen HS'}, {'TeamNum': 15889, 'OPR': 46.395, 'Auto': -0.609, 'CCWM': -23.785, 'TeamName': 'RoboDawgs'}, {'TeamNum': 15884, 'OPR': 45.738, 'Auto': 13.846, 'CCWM': -5.712, 'TeamName': 'Falcon Dynamics - Foothill HS'}, {'TeamNum': 18858, 'OPR': 43.54, 'Auto': -0.054, 'CCWM': -3.859, 'TeamName': 'ARC - Blue'}, {'TeamNum': 17280, 'OPR': 43.234, 'Auto': -0.928, 'CCWM': 11.74, 'TeamName': 'Legacy Robotics - Stronghorns'}, {'TeamNum': 22774, 'OPR': 39.737, 'Auto': 9.607, 'CCWM': -30.503, 'TeamName': 'URSA Major'}, {'TeamNum': 20285, 'OPR': 36.762, 'Auto': 16.17, 'CCWM': 6.0, 'TeamName': 'Truckee Robotics'}, {'TeamNum': 18419, 'OPR': 35.466, 'Auto': 7.213, 'CCWM': -9.5, 'TeamName': 'Comstock Coders'}, {'TeamNum': 21535, 'OPR': 33.747, 'Auto': 19.481, 'CCWM': 7.112, 'TeamName': 'Royal Ghostbusters'}, {'TeamNum': 21794, 'OPR': 30.205, 'Auto': 2.34, 'CCWM': 5.476, 'TeamName': 'Laughlin Jr/Sr HS 2'}, {'TeamNum': 21707, 'OPR': 27.461, 'Auto': 8.535, 'CCWM': -34.836, 'TeamName': 'MinerBots'}, {'TeamNum': 18815, 'OPR': 27.285, 'Auto': 4.773, 'CCWM': -9.167, 'TeamName': 'LANV Logic'}, {'TeamNum': 21632, 'OPR': 26.781, 'Auto': 1.782, 'CCWM': -61.085, 'TeamName': 'Galvanized Gryphons'}, {'TeamNum': 21629, 'OPR': 18.998, 'Auto': 1.809, 'CCWM': -51.72, 'TeamName': 'Central Technical Training Academy'}, {'TeamNum': 14532, 'OPR': 14.74, 'Auto': 1.17, 'CCWM': -69.703, 'TeamName': 'Splitting Atoms'}, {'TeamNum': 18682, 'OPR': 14.396, 'Auto': 5.142, 'CCWM': -66.304, 'TeamName': 'Cyber Nights'}, {'TeamNum': 21726, 'OPR': 1.318, 'Auto': -7.953, 'CCWM': -16.07, 'TeamName': 'Laughlin Jr/Sr HS'}]

i 1107
{'12833', '6347', '6460', '12915', '14281', '16700', '12737', '13510', '18773', '5319', '4809', '6567', '12736', '5485', '8863', '6955', '10949', '4654', '3750', '8397', '5356', '14903', '5484', '13371', '7230', '22240', '12331', '21428'}
[{'TeamNum': 5356, 'OPR': 116.079, 'Auto': 28.414, 'CCWM': 61.062, 'TeamName': 'TARDIS'}, {'TeamNum': 14903, 'OPR': 109.304, 'Auto': 19.92, 'CCWM': 30.681, 'TeamName': 'SharkBots'}, {'TeamNum': 12833, 'OPR': 106.511, 'Auto': 30.69, 'CCWM': 35.391, 'TeamName': 'Mechanical Meltdown'}, {'TeamNum': 10949, 'OPR': 98.963, 'Auto': 22.771, 'CCWM': 12.075, 'TeamName': 'Mechanical Operations Bureau'}, {'TeamNum': 8397, 'OPR': 94.396, 'Auto': 14.932, 'CCWM': 29.208, 'TeamName': 'Beta'}, {'TeamNum': 12737, 'OPR': 86.453, 'Auto': 30.825, 'CCWM': -26.515, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 8863, 'OPR': 86.096, 'Auto': 17.982, 'CCWM': 70.93, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 7230, 'OPR': 85.658, 'Auto': 15.018, 'CCWM': 16.424, 'TeamName': 'SAS Atoms'}, {'TeamNum': 13371, 'OPR': 83.765, 'Auto': 18.544, 'CCWM': 12.727, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 4654, 'OPR': 83.286, 'Auto': 15.882, 'CCWM': 15.721, 'TeamName': 'Jellyfish '}, {'TeamNum': 22240, 'OPR': 74.68, 'Auto': 14.384, 'CCWM': 56.86, 'TeamName': 'Rough Estimate '}, {'TeamNum': 6460, 'OPR': 68.44, 'Auto': 20.451, 'CCWM': -0.434, 'TeamName': 'RoboWarriors'}, {'TeamNum': 6955, 'OPR': 68.105, 'Auto': 14.801, 'CCWM': -16.068, 'TeamName': 'RoBovines'}, {'TeamNum': 5485, 'OPR': 62.635, 'Auto': 14.238, 'CCWM': 1.132, 'TeamName': 'GorillaBots'}, {'TeamNum': 14281, 'OPR': 62.342, 'Auto': 6.652, 'CCWM': 19.353, 'TeamName': 'Ravena-Coeymans-Selkirk '}, {'TeamNum': 6347, 'OPR': 61.885, 'Auto': 15.587, 'CCWM': -0.444, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 21428, 'OPR': 60.938, 'Auto': 13.412, 'CCWM': -3.294, 'TeamName': 'Silver Eagles'}, {'TeamNum': 5484, 'OPR': 58.768, 'Auto': 4.432, 'CCWM': -16.161, 'TeamName': 'The EnderBots'}, {'TeamNum': 4809, 'OPR': 58.673, 'Auto': 4.343, 'CCWM': -41.519, 'TeamName': 'Botman'}, {'TeamNum': 16700, 'OPR': 53.984, 'Auto': 5.028, 'CCWM': -26.412, 'TeamName': 'JAYBOTS'}, {'TeamNum': 6567, 'OPR': 53.066, 'Auto': 3.945, 'CCWM': -7.403, 'TeamName': 'Roboraiders'}, {'TeamNum': 18773, 'OPR': 46.066, 'Auto': 9.975, 'CCWM': -14.521, 'TeamName': 'Team Gambit'}, {'TeamNum': 13510, 'OPR': 44.037, 'Auto': 7.381, 'CCWM': -45.875, 'TeamName': 'MUCCBots!'}, {'TeamNum': 12915, 'OPR': 41.22, 'Auto': -4.257, 'CCWM': -19.396, 'TeamName': 'System Override'}, {'TeamNum': 12331, 'OPR': 40.303, 'Auto': -5.341, 'CCWM': -30.83, 'TeamName': 'Scarsdale Robo Raiders'}, {'TeamNum': 12736, 'OPR': 38.673, 'Auto': 11.194, 'CCWM': -26.723, 'TeamName': 'Electric Mayhem Green'}, {'TeamNum': 5319, 'OPR': 37.171, 'Auto': 10.454, 'CCWM': -59.122, 'TeamName': 'Buff Sci-borgs'}, {'TeamNum': 3750, 'OPR': 28.502, 'Auto': 10.746, 'CCWM': -26.846, 'TeamName': 'Rush Henrietta Royal Robotics'}]
USNYEXCMP
[{'TeamNum': 5356, 'OPR': 116.079, 'Auto': 28.414, 'CCWM': 61.062, 'TeamName': 'TARDIS'}, {'TeamNum': 14903, 'OPR': 109.304, 'Auto': 19.92, 'CCWM': 30.681, 'TeamName': 'SharkBots'}, {'TeamNum': 12833, 'OPR': 106.511, 'Auto': 30.69, 'CCWM': 35.391, 'TeamName': 'Mechanical Meltdown'}, {'TeamNum': 10949, 'OPR': 98.963, 'Auto': 22.771, 'CCWM': 12.075, 'TeamName': 'Mechanical Operations Bureau'}, {'TeamNum': 8397, 'OPR': 94.396, 'Auto': 14.932, 'CCWM': 29.208, 'TeamName': 'Beta'}, {'TeamNum': 12737, 'OPR': 86.453, 'Auto': 30.825, 'CCWM': -26.515, 'TeamName': 'Electric Mayhem White'}, {'TeamNum': 8863, 'OPR': 86.096, 'Auto': 17.982, 'CCWM': 70.93, 'TeamName': 'Precision Cut-Ups'}, {'TeamNum': 7230, 'OPR': 85.658, 'Auto': 15.018, 'CCWM': 16.424, 'TeamName': 'SAS Atoms'}, {'TeamNum': 13371, 'OPR': 83.765, 'Auto': 18.544, 'CCWM': 12.727, 'TeamName': 'Sendy Sandstoners'}, {'TeamNum': 4654, 'OPR': 83.286, 'Auto': 15.882, 'CCWM': 15.721, 'TeamName': 'Jellyfish '}, {'TeamNum': 22240, 'OPR': 74.68, 'Auto': 14.384, 'CCWM': 56.86, 'TeamName': 'Rough Estimate '}, {'TeamNum': 6460, 'OPR': 68.44, 'Auto': 20.451, 'CCWM': -0.434, 'TeamName': 'RoboWarriors'}, {'TeamNum': 6955, 'OPR': 68.105, 'Auto': 14.801, 'CCWM': -16.068, 'TeamName': 'RoBovines'}, {'TeamNum': 5485, 'OPR': 62.635, 'Auto': 14.238, 'CCWM': 1.132, 'TeamName': 'GorillaBots'}, {'TeamNum': 14281, 'OPR': 62.342, 'Auto': 6.652, 'CCWM': 19.353, 'TeamName': 'Ravena-Coeymans-Selkirk '}, {'TeamNum': 6347, 'OPR': 61.885, 'Auto': 15.587, 'CCWM': -0.444, 'TeamName': 'Nerds of a Feather'}, {'TeamNum': 21428, 'OPR': 60.938, 'Auto': 13.412, 'CCWM': -3.294, 'TeamName': 'Silver Eagles'}, {'TeamNum': 5484, 'OPR': 58.768, 'Auto': 4.432, 'CCWM': -16.161, 'TeamName': 'The EnderBots'}, {'TeamNum': 4809, 'OPR': 58.673, 'Auto': 4.343, 'CCWM': -41.519, 'TeamName': 'Botman'}, {'TeamNum': 16700, 'OPR': 53.984, 'Auto': 5.028, 'CCWM': -26.412, 'TeamName': 'JAYBOTS'}, {'TeamNum': 6567, 'OPR': 53.066, 'Auto': 3.945, 'CCWM': -7.403, 'TeamName': 'Roboraiders'}, {'TeamNum': 18773, 'OPR': 46.066, 'Auto': 9.975, 'CCWM': -14.521, 'TeamName': 'Team Gambit'}, {'TeamNum': 13510, 'OPR': 44.037, 'Auto': 7.381, 'CCWM': -45.875, 'TeamName': 'MUCCBots!'}, {'TeamNum': 12915, 'OPR': 41.22, 'Auto': -4.257, 'CCWM': -19.396, 'TeamName': 'System Override'}, {'TeamNum': 12331, 'OPR': 40.303, 'Auto': -5.341, 'CCWM': -30.83, 'TeamName': 'Scarsdale Robo Raiders'}, {'TeamNum': 12736, 'OPR': 38.673, 'Auto': 11.194, 'CCWM': -26.723, 'TeamName': 'Electric Mayhem Green'}, {'TeamNum': 5319, 'OPR': 37.171, 'Auto': 10.454, 'CCWM': -59.122, 'TeamName': 'Buff Sci-borgs'}, {'TeamNum': 3750, 'OPR': 28.502, 'Auto': 10.746, 'CCWM': -26.846, 'TeamName': 'Rush Henrietta Royal Robotics'}]
i 1108
{'14212', '5361', '4174', '8088', '9384', '16568', '11997', '14712', '4782', '479', '4781', '10539', '9371', '8721', '8500', '11943', '8365', '17126', '22335', '22437', '11453', '14734', '18657', '310'}
[{'TeamNum': 14212, 'OPR': 142.288, 'Auto': 41.513, 'CCWM': 113.459, 'TeamName': 'Metrobotics'}, {'TeamNum': 310, 'OPR': 134.01, 'Auto': 29.973, 'CCWM': 86.731, 'TeamName': 'Stuy Fission'}, {'TeamNum': 8365, 'OPR': 99.233, 'Auto': 32.815, 'CCWM': -6.769, 'TeamName': 'Gearmasters'}, {'TeamNum': 479, 'OPR': 95.311, 'Auto': 25.164, 'CCWM': 51.013, 'TeamName': 'Stuy Fusion'}, {'TeamNum': 14734, 'OPR': 88.264, 'Auto': 12.855, 'CCWM': 33.755, 'TeamName': 'Envirobots'}, {'TeamNum': 8500, 'OPR': 85.025, 'Auto': 17.48, 'CCWM': 32.781, 'TeamName': 'The Generals'}, {'TeamNum': 22437, 'OPR': 84.733, 'Auto': 14.261, 'CCWM': 55.077, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 9384, 'OPR': 84.157, 'Auto': 12.84, 'CCWM': 45.641, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 10539, 'OPR': 81.595, 'Auto': 17.539, 'CCWM': 34.593, 'TeamName': 'Ultro'}, {'TeamNum': 5361, 'OPR': 72.082, 'Auto': 28.858, 'CCWM': -21.809, 'TeamName': 'Lionotics'}, {'TeamNum': 4782, 'OPR': 63.055, 'Auto': 22.401, 'CCWM': -23.462, 'TeamName': 'The Super Troublemakers'}, {'TeamNum': 18657, 'OPR': 56.822, 'Auto': 14.183, 'CCWM': -2.036, 'TeamName': 'AIM Robotics'}, {'TeamNum': 17126, 'OPR': 54.911, 'Auto': 25.379, 'CCWM': -14.004, 'TeamName': 'Natural Selection'}, {'TeamNum': 4781, 'OPR': 54.773, 'Auto': 12.219, 'CCWM': -22.678, 'TeamName': 'MechaKnights'}, {'TeamNum': 22335, 'OPR': 51.885, 'Auto': 8.257, 'CCWM': 1.487, 'TeamName': 'Polymorphism '}, {'TeamNum': 9371, 'OPR': 45.846, 'Auto': 10.45, 'CCWM': -22.912, 'TeamName': 'General Relativity'}, {'TeamNum': 11943, 'OPR': 42.858, 'Auto': 14.585, 'CCWM': -42.502, 'TeamName': 'The Nighthawks'}, {'TeamNum': 14712, 'OPR': 42.158, 'Auto': 15.576, 'CCWM': -46.377, 'TeamName': 'Ruckus Robotics'}, {'TeamNum': 11997, 'OPR': 40.884, 'Auto': 26.178, 'CCWM': -23.292, 'TeamName': 'Heights Techies'}, {'TeamNum': 8721, 'OPR': 36.937, 'Auto': -3.886, 'CCWM': -26.398, 'TeamName': 'Mighty Mechanics'}, {'TeamNum': 8088, 'OPR': 33.413, 'Auto': 1.699, 'CCWM': -47.807, 'TeamName': 'Team Cephalopods'}, {'TeamNum': 16568, 'OPR': 33.398, 'Auto': 12.875, 'CCWM': -48.281, 'TeamName': 'Cybernetic Lions'}, {'TeamNum': 4174, 'OPR': 30.453, 'Auto': 6.945, 'CCWM': -44.695, 'TeamName': 'Atomic Theory'}, {'TeamNum': 11453, 'OPR': 7.577, 'Auto': 1.006, 'CCWM': -61.514, 'TeamName': 'Uncertainty Principle'}]
USNYNYCMP
[{'TeamNum': 14212, 'OPR': 142.288, 'Auto': 41.513, 'CCWM': 113.459, 'TeamName': 'Metrobotics'}, {'TeamNum': 310, 'OPR': 134.01, 'Auto': 29.973, 'CCWM': 86.731, 'TeamName': 'Stuy Fission'}, {'TeamNum': 8365, 'OPR': 99.233, 'Auto': 32.815, 'CCWM': -6.769, 'TeamName': 'Gearmasters'}, {'TeamNum': 479, 'OPR': 95.311, 'Auto': 25.164, 'CCWM': 51.013, 'TeamName': 'Stuy Fusion'}, {'TeamNum': 14734, 'OPR': 88.264, 'Auto': 12.855, 'CCWM': 33.755, 'TeamName': 'Envirobots'}, {'TeamNum': 8500, 'OPR': 85.025, 'Auto': 17.48, 'CCWM': 32.781, 'TeamName': 'The Generals'}, {'TeamNum': 22437, 'OPR': 84.733, 'Auto': 14.261, 'CCWM': 55.077, 'TeamName': 'GT12 - Demon Dogs'}, {'TeamNum': 9384, 'OPR': 84.157, 'Auto': 12.84, 'CCWM': 45.641, 'TeamName': 'Hydraulic Hydras'}, {'TeamNum': 10539, 'OPR': 81.595, 'Auto': 17.539, 'CCWM': 34.593, 'TeamName': 'Ultro'}, {'TeamNum': 5361, 'OPR': 72.082, 'Auto': 28.858, 'CCWM': -21.809, 'TeamName': 'Lionotics'}, {'TeamNum': 4782, 'OPR': 63.055, 'Auto': 22.401, 'CCWM': -23.462, 'TeamName': 'The Super Troublemakers'}, {'TeamNum': 18657, 'OPR': 56.822, 'Auto': 14.183, 'CCWM': -2.036, 'TeamName': 'AIM Robotics'}, {'TeamNum': 17126, 'OPR': 54.911, 'Auto': 25.379, 'CCWM': -14.004, 'TeamName': 'Natural Selection'}, {'TeamNum': 4781, 'OPR': 54.773, 'Auto': 12.219, 'CCWM': -22.678, 'TeamName': 'MechaKnights'}, {'TeamNum': 22335, 'OPR': 51.885, 'Auto': 8.257, 'CCWM': 1.487, 'TeamName': 'Polymorphism '}, {'TeamNum': 9371, 'OPR': 45.846, 'Auto': 10.45, 'CCWM': -22.912, 'TeamName': 'General Relativity'}, {'TeamNum': 11943, 'OPR': 42.858, 'Auto': 14.585, 'CCWM': -42.502, 'TeamName': 'The Nighthawks'}, {'TeamNum': 14712, 'OPR': 42.158, 'Auto': 15.576, 'CCWM': -46.377, 'TeamName': 'Ruckus Robotics'}, {'TeamNum': 11997, 'OPR': 40.884, 'Auto': 26.178, 'CCWM': -23.292, 'TeamName': 'Heights Techies'}, {'TeamNum': 8721, 'OPR': 36.937, 'Auto': -3.886, 'CCWM': -26.398, 'TeamName': 'Mighty Mechanics'}, {'TeamNum': 8088, 'OPR': 33.413, 'Auto': 1.699, 'CCWM': -47.807, 'TeamName': 'Team Cephalopods'}, {'TeamNum': 16568, 'OPR': 33.398, 'Auto': 12.875, 'CCWM': -48.281, 'TeamName': 'Cybernetic Lions'}, {'TeamNum': 4174, 'OPR': 30.453, 'Auto': 6.945, 'CCWM': -44.695, 'TeamName': 'Atomic Theory'}, {'TeamNum': 11453, 'OPR': 7.577, 'Auto': 1.006, 'CCWM': -61.514, 'TeamName': 'Uncertainty Principle'}]

i 1109
i 1110
{'9242', '17388', '8393', '12792', '16564', '16011', '7786', '7244', '21324', '8480', '13669', '16466', '22247', '22828', '16606', '6378', '7423', '16468', '20152', '8509', '14738', '13474', '20153', '22283', '8730', '14423', '21437', '11349', '8468', '22312', '4149', '14464', '16800', '10098', '8645', '6540'}
[{'TeamNum': 8393, 'OPR': 122.006, 'Auto': 44.853, 'CCWM': 31.557, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 16468, 'OPR': 119.819, 'Auto': 29.896, 'CCWM': 33.878, 'TeamName': 'Green Lemons'}, {'TeamNum': 16800, 'OPR': 119.529, 'Auto': 21.829, 'CCWM': 57.36, 'TeamName': 'Trial and Terror'}, {'TeamNum': 7244, 'OPR': 113.615, 'Auto': 22.979, 'CCWM': 110.874, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 11349, 'OPR': 111.549, 'Auto': 27.161, 'CCWM': 13.975, 'TeamName': 'VorTech'}, {'TeamNum': 8468, 'OPR': 107.164, 'Auto': 37.064, 'CCWM': 32.046, 'TeamName': 'The Javengers'}, {'TeamNum': 16564, 'OPR': 99.528, 'Auto': 36.341, 'CCWM': 45.894, 'TeamName': 'Digital Devils'}, {'TeamNum': 7423, 'OPR': 97.948, 'Auto': 25.34, 'CCWM': 45.696, 'TeamName': 'Flaming Phoenix'}, {'TeamNum': 20153, 'OPR': 97.011, 'Auto': 20.796, 'CCWM': 26.449, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8645, 'OPR': 93.288, 'Auto': 5.935, 'CCWM': 24.646, 'TeamName': 'Robotic Doges'}, {'TeamNum': 22312, 'OPR': 92.335, 'Auto': 23.985, 'CCWM': 2.876, 'TeamName': 'The Brobdingnagian Tritocephalic BrainSTEM Robotics Team'}, {'TeamNum': 12792, 'OPR': 88.494, 'Auto': 20.391, 'CCWM': 19.277, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 13669, 'OPR': 86.976, 'Auto': 19.273, 'CCWM': -13.813, 'TeamName': 'RAIDERBOTS - COATESVILLE AREA HIGH SCHOOL'}, {'TeamNum': 14738, 'OPR': 84.161, 'Auto': 13.937, 'CCWM': 39.278, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 14423, 'OPR': 84.09, 'Auto': 25.265, 'CCWM': -3.442, 'TeamName': 'RoboCorns'}, {'TeamNum': 21324, 'OPR': 81.093, 'Auto': 24.788, 'CCWM': 21.856, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 20152, 'OPR': 78.586, 'Auto': 21.815, 'CCWM': -39.17, 'TeamName': 'Battle Bots'}, {'TeamNum': 22828, 'OPR': 78.525, 'Auto': 26.572, 'CCWM': 12.856, 'TeamName': 'Jingle Bells'}, {'TeamNum': 6378, 'OPR': 73.796, 'Auto': 19.667, 'CCWM': -27.782, 'TeamName': 'JayBots'}, {'TeamNum': 6540, 'OPR': 70.252, 'Auto': 17.775, 'CCWM': 54.456, 'TeamName': 'Railsplitters'}, {'TeamNum': 8730, 'OPR': 70.144, 'Auto': 16.791, 'CCWM': 17.281, 'TeamName': 'Robogriffins'}, {'TeamNum': 8509, 'OPR': 68.986, 'Auto': 30.221, 'CCWM': -4.125, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 16011, 'OPR': 68.963, 'Auto': 20.186, 'CCWM': -6.469, 'TeamName': 'Fayette County 4H'}, {'TeamNum': 9242, 'OPR': 64.599, 'Auto': 17.251, 'CCWM': 4.583, 'TeamName': 'GearHounds'}, {'TeamNum': 13474, 'OPR': 63.992, 'Auto': 19.891, 'CCWM': 5.575, 'TeamName': 'MARS: Curiosity?'}, {'TeamNum': 16466, 'OPR': 62.077, 'Auto': 22.219, 'CCWM': 24.614, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 4149, 'OPR': 59.235, 'Auto': 17.275, 'CCWM': -14.71, 'TeamName': 'Terabytes'}, {'TeamNum': 21437, 'OPR': 58.945, 'Auto': 16.83, 'CCWM': -41.181, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 10098, 'OPR': 57.195, 'Auto': 19.075, 'CCWM': -40.22, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 22283, 'OPR': 42.025, 'Auto': 16.283, 'CCWM': -71.453, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 17388, 'OPR': 38.883, 'Auto': -5.558, 'CCWM': -59.084, 'TeamName': 'Red Tornadoes'}, {'TeamNum': 14464, 'OPR': 33.7, 'Auto': 11.892, 'CCWM': -66.914, 'TeamName': 'BotBusters'}, {'TeamNum': 7786, 'OPR': 32.648, 'Auto': 5.898, 'CCWM': -69.213, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 22247, 'OPR': 30.152, 'Auto': -1.874, 'CCWM': -26.353, 'TeamName': 'RoboLancers Pumpkin'}, {'TeamNum': 16606, 'OPR': 2.443, 'Auto': 2.605, 'CCWM': -77.742, 'TeamName': 'Tech-Knight Robotics'}, {'TeamNum': 8480, 'OPR': 1.647, 'Auto': -1.849, 'CCWM': -63.354, 'TeamName': 'Technabots'}]
USPACMP
[{'TeamNum': 8393, 'OPR': 122.006, 'Auto': 44.853, 'CCWM': 31.557, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 16468, 'OPR': 119.819, 'Auto': 29.896, 'CCWM': 33.878, 'TeamName': 'Green Lemons'}, {'TeamNum': 16800, 'OPR': 119.529, 'Auto': 21.829, 'CCWM': 57.36, 'TeamName': 'Trial and Terror'}, {'TeamNum': 7244, 'OPR': 113.615, 'Auto': 22.979, 'CCWM': 110.874, 'TeamName': 'OUT of the BOX Robotics'}, {'TeamNum': 11349, 'OPR': 111.549, 'Auto': 27.161, 'CCWM': 13.975, 'TeamName': 'VorTech'}, {'TeamNum': 8468, 'OPR': 107.164, 'Auto': 37.064, 'CCWM': 32.046, 'TeamName': 'The Javengers'}, {'TeamNum': 16564, 'OPR': 99.528, 'Auto': 36.341, 'CCWM': 45.894, 'TeamName': 'Digital Devils'}, {'TeamNum': 7423, 'OPR': 97.948, 'Auto': 25.34, 'CCWM': 45.696, 'TeamName': 'Flaming Phoenix'}, {'TeamNum': 20153, 'OPR': 97.011, 'Auto': 20.796, 'CCWM': 26.449, 'TeamName': 'Silver Wolves'}, {'TeamNum': 8645, 'OPR': 93.288, 'Auto': 5.935, 'CCWM': 24.646, 'TeamName': 'Robotic Doges'}, {'TeamNum': 22312, 'OPR': 92.335, 'Auto': 23.985, 'CCWM': 2.876, 'TeamName': 'The Brobdingnagian Tritocephalic BrainSTEM Robotics Team'}, {'TeamNum': 12792, 'OPR': 88.494, 'Auto': 20.391, 'CCWM': 19.277, 'TeamName': 'Sharon High Robotics Team'}, {'TeamNum': 13669, 'OPR': 86.976, 'Auto': 19.273, 'CCWM': -13.813, 'TeamName': 'RAIDERBOTS - COATESVILLE AREA HIGH SCHOOL'}, {'TeamNum': 14738, 'OPR': 84.161, 'Auto': 13.937, 'CCWM': 39.278, 'TeamName': 'Theoretically Correct'}, {'TeamNum': 14423, 'OPR': 84.09, 'Auto': 25.265, 'CCWM': -3.442, 'TeamName': 'RoboCorns'}, {'TeamNum': 21324, 'OPR': 81.093, 'Auto': 24.788, 'CCWM': 21.856, 'TeamName': 'Hackin Hounds '}, {'TeamNum': 20152, 'OPR': 78.586, 'Auto': 21.815, 'CCWM': -39.17, 'TeamName': 'Battle Bots'}, {'TeamNum': 22828, 'OPR': 78.525, 'Auto': 26.572, 'CCWM': 12.856, 'TeamName': 'Jingle Bells'}, {'TeamNum': 6378, 'OPR': 73.796, 'Auto': 19.667, 'CCWM': -27.782, 'TeamName': 'JayBots'}, {'TeamNum': 6540, 'OPR': 70.252, 'Auto': 17.775, 'CCWM': 54.456, 'TeamName': 'Railsplitters'}, {'TeamNum': 8730, 'OPR': 70.144, 'Auto': 16.791, 'CCWM': 17.281, 'TeamName': 'Robogriffins'}, {'TeamNum': 8509, 'OPR': 68.986, 'Auto': 30.221, 'CCWM': -4.125, 'TeamName': 'STEEL Serpents'}, {'TeamNum': 16011, 'OPR': 68.963, 'Auto': 20.186, 'CCWM': -6.469, 'TeamName': 'Fayette County 4H'}, {'TeamNum': 9242, 'OPR': 64.599, 'Auto': 17.251, 'CCWM': 4.583, 'TeamName': 'GearHounds'}, {'TeamNum': 13474, 'OPR': 63.992, 'Auto': 19.891, 'CCWM': 5.575, 'TeamName': 'MARS: Curiosity?'}, {'TeamNum': 16466, 'OPR': 62.077, 'Auto': 22.219, 'CCWM': 24.614, 'TeamName': 'Technological Intelligence'}, {'TeamNum': 4149, 'OPR': 59.235, 'Auto': 17.275, 'CCWM': -14.71, 'TeamName': 'Terabytes'}, {'TeamNum': 21437, 'OPR': 58.945, 'Auto': 16.83, 'CCWM': -41.181, 'TeamName': 'Terminal Velocity'}, {'TeamNum': 10098, 'OPR': 57.195, 'Auto': 19.075, 'CCWM': -40.22, 'TeamName': '2 Eyed Illuminati'}, {'TeamNum': 22283, 'OPR': 42.025, 'Auto': 16.283, 'CCWM': -71.453, 'TeamName': 'SLAM DUNK'}, {'TeamNum': 17388, 'OPR': 38.883, 'Auto': -5.558, 'CCWM': -59.084, 'TeamName': 'Red Tornadoes'}, {'TeamNum': 14464, 'OPR': 33.7, 'Auto': 11.892, 'CCWM': -66.914, 'TeamName': 'BotBusters'}, {'TeamNum': 7786, 'OPR': 32.648, 'Auto': 5.898, 'CCWM': -69.213, 'TeamName': 'MT Blue Streaks'}, {'TeamNum': 22247, 'OPR': 30.152, 'Auto': -1.874, 'CCWM': -26.353, 'TeamName': 'RoboLancers Pumpkin'}, {'TeamNum': 16606, 'OPR': 2.443, 'Auto': 2.605, 'CCWM': -77.742, 'TeamName': 'Tech-Knight Robotics'}, {'TeamNum': 8480, 'OPR': 1.647, 'Auto': -1.849, 'CCWM': -63.354, 'TeamName': 'Technabots'}]
i 1111
{'13181', '22142', '15374', '8413', '636', '10847', '18209', '22762', '9128', '10773', '15982', '17847', '652', '13540', '6527', '7093', '20763', '654', '22156', '9219', '3351', '252', '3032', '22872'}
[{'TeamNum': 22156, 'OPR': 103.033, 'Auto': 19.395, 'CCWM': 34.067, 'TeamName': 'Robo Titans'}, {'TeamNum': 9219, 'OPR': 84.936, 'Auto': 9.083, 'CCWM': 36.373, 'TeamName': "If It Ain't Broke"}, {'TeamNum': 10847, 'OPR': 83.842, 'Auto': 11.192, 'CCWM': 25.386, 'TeamName': 'Robo Eagles'}, {'TeamNum': 636, 'OPR': 82.263, 'Auto': 9.285, 'CCWM': 66.943, 'TeamName': "Occam's Razor Clams"}, {'TeamNum': 252, 'OPR': 79.571, 'Auto': 7.956, 'CCWM': 13.441, 'TeamName': 'Electric Quahogs'}, {'TeamNum': 7093, 'OPR': 79.531, 'Auto': 13.745, 'CCWM': 8.896, 'TeamName': 'RaiderBots'}, {'TeamNum': 15374, 'OPR': 79.448, 'Auto': 7.327, 'CCWM': 25.345, 'TeamName': 'Rench Raiders'}, {'TeamNum': 22872, 'OPR': 73.832, 'Auto': 1.079, 'CCWM': 28.95, 'TeamName': 'Cheddar Contraptions'}, {'TeamNum': 17847, 'OPR': 73.399, 'Auto': 22.451, 'CCWM': 37.501, 'TeamName': 'The Velocity Raptors'}, {'TeamNum': 8413, 'OPR': 73.161, 'Auto': 18.601, 'CCWM': 39.524, 'TeamName': 'The Bucket Bots'}, {'TeamNum': 652, 'OPR': 70.56, 'Auto': 1.191, 'CCWM': -20.44, 'TeamName': 'Underdogs'}, {'TeamNum': 22142, 'OPR': 66.216, 'Auto': 28.866, 'CCWM': 7.505, 'TeamName': 'Echo X'}, {'TeamNum': 13181, 'OPR': 64.185, 'Auto': 21.508, 'CCWM': 10.44, 'TeamName': 'Free WiFi'}, {'TeamNum': 13540, 'OPR': 54.956, 'Auto': 24.572, 'CCWM': -54.331, 'TeamName': 'Rhodeberto'}, {'TeamNum': 18209, 'OPR': 51.851, 'Auto': 13.39, 'CCWM': 30.373, 'TeamName': 'Full Stop'}, {'TeamNum': 3032, 'OPR': 50.979, 'Auto': 15.696, 'CCWM': -2.667, 'TeamName': 'Hyperion'}, {'TeamNum': 9128, 'OPR': 48.866, 'Auto': 5.142, 'CCWM': 9.767, 'TeamName': 'Mounties'}, {'TeamNum': 10773, 'OPR': 42.501, 'Auto': 2.166, 'CCWM': -26.16, 'TeamName': 'Chariho Chargers'}, {'TeamNum': 20763, 'OPR': 22.511, 'Auto': 8.611, 'CCWM': -33.073, 'TeamName': 'Iron Lions'}, {'TeamNum': 654, 'OPR': 22.102, 'Auto': 12.037, 'CCWM': -31.581, 'TeamName': 'Barrington Bionics'}, {'TeamNum': 3351, 'OPR': 16.829, 'Auto': 5.145, 'CCWM': -45.062, 'TeamName': 'Tater Bots'}, {'TeamNum': 15982, 'OPR': 15.852, 'Auto': 8.038, 'CCWM': -47.864, 'TeamName': "Where's Allen's Wrench?"}, {'TeamNum': 22762, 'OPR': 10.605, 'Auto': 3.201, 'CCWM': -59.514, 'TeamName': 'Saint Raybots'}, {'TeamNum': 6527, 'OPR': 10.371, 'Auto': 1.525, 'CCWM': -53.821, 'TeamName': 'The Indecision Matrices'}]
USRICMP
[{'TeamNum': 22156, 'OPR': 103.033, 'Auto': 19.395, 'CCWM': 34.067, 'TeamName': 'Robo Titans'}, {'TeamNum': 9219, 'OPR': 84.936, 'Auto': 9.083, 'CCWM': 36.373, 'TeamName': "If It Ain't Broke"}, {'TeamNum': 10847, 'OPR': 83.842, 'Auto': 11.192, 'CCWM': 25.386, 'TeamName': 'Robo Eagles'}, {'TeamNum': 636, 'OPR': 82.263, 'Auto': 9.285, 'CCWM': 66.943, 'TeamName': "Occam's Razor Clams"}, {'TeamNum': 252, 'OPR': 79.571, 'Auto': 7.956, 'CCWM': 13.441, 'TeamName': 'Electric Quahogs'}, {'TeamNum': 7093, 'OPR': 79.531, 'Auto': 13.745, 'CCWM': 8.896, 'TeamName': 'RaiderBots'}, {'TeamNum': 15374, 'OPR': 79.448, 'Auto': 7.327, 'CCWM': 25.345, 'TeamName': 'Rench Raiders'}, {'TeamNum': 22872, 'OPR': 73.832, 'Auto': 1.079, 'CCWM': 28.95, 'TeamName': 'Cheddar Contraptions'}, {'TeamNum': 17847, 'OPR': 73.399, 'Auto': 22.451, 'CCWM': 37.501, 'TeamName': 'The Velocity Raptors'}, {'TeamNum': 8413, 'OPR': 73.161, 'Auto': 18.601, 'CCWM': 39.524, 'TeamName': 'The Bucket Bots'}, {'TeamNum': 652, 'OPR': 70.56, 'Auto': 1.191, 'CCWM': -20.44, 'TeamName': 'Underdogs'}, {'TeamNum': 22142, 'OPR': 66.216, 'Auto': 28.866, 'CCWM': 7.505, 'TeamName': 'Echo X'}, {'TeamNum': 13181, 'OPR': 64.185, 'Auto': 21.508, 'CCWM': 10.44, 'TeamName': 'Free WiFi'}, {'TeamNum': 13540, 'OPR': 54.956, 'Auto': 24.572, 'CCWM': -54.331, 'TeamName': 'Rhodeberto'}, {'TeamNum': 18209, 'OPR': 51.851, 'Auto': 13.39, 'CCWM': 30.373, 'TeamName': 'Full Stop'}, {'TeamNum': 3032, 'OPR': 50.979, 'Auto': 15.696, 'CCWM': -2.667, 'TeamName': 'Hyperion'}, {'TeamNum': 9128, 'OPR': 48.866, 'Auto': 5.142, 'CCWM': 9.767, 'TeamName': 'Mounties'}, {'TeamNum': 10773, 'OPR': 42.501, 'Auto': 2.166, 'CCWM': -26.16, 'TeamName': 'Chariho Chargers'}, {'TeamNum': 20763, 'OPR': 22.511, 'Auto': 8.611, 'CCWM': -33.073, 'TeamName': 'Iron Lions'}, {'TeamNum': 654, 'OPR': 22.102, 'Auto': 12.037, 'CCWM': -31.581, 'TeamName': 'Barrington Bionics'}, {'TeamNum': 3351, 'OPR': 16.829, 'Auto': 5.145, 'CCWM': -45.062, 'TeamName': 'Tater Bots'}, {'TeamNum': 15982, 'OPR': 15.852, 'Auto': 8.038, 'CCWM': -47.864, 'TeamName': "Where's Allen's Wrench?"}, {'TeamNum': 22762, 'OPR': 10.605, 'Auto': 3.201, 'CCWM': -59.514, 'TeamName': 'Saint Raybots'}, {'TeamNum': 6527, 'OPR': 10.371, 'Auto': 1.525, 'CCWM': -53.821, 'TeamName': 'The Indecision Matrices'}]

i 1112
{'10695', '15749', '5667', '19697', '10533', '12515', '21709', '16748', '19924', '12351', '20108', '19744', '11002', '15413', '19922', '17230', '8641', '5026', '22180', '16927', '21676', '21765', '21895', '21710', '22524', '8400', '8280'}
[{'TeamNum': 10695, 'OPR': 132.32, 'Auto': 40.584, 'CCWM': 99.272, 'TeamName': 'Theta Robotics'}, {'TeamNum': 15413, 'OPR': 98.437, 'Auto': 19.448, 'CCWM': 28.961, 'TeamName': 'Toaster Medics'}, {'TeamNum': 21710, 'OPR': 82.235, 'Auto': 17.803, 'CCWM': 52.383, 'TeamName': 'JHCS Mecha Grizzlies - Gold'}, {'TeamNum': 19697, 'OPR': 80.184, 'Auto': 20.86, 'CCWM': 43.501, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 5667, 'OPR': 79.121, 'Auto': 29.669, 'CCWM': 33.048, 'TeamName': 'Robominers'}, {'TeamNum': 12351, 'OPR': 77.873, 'Auto': 17.107, 'CCWM': 71.492, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 5026, 'OPR': 57.534, 'Auto': 4.307, 'CCWM': 8.566, 'TeamName': 'Tesla Coils'}, {'TeamNum': 21765, 'OPR': 56.237, 'Auto': 6.312, 'CCWM': -12.87, 'TeamName': 'Overclocked'}, {'TeamNum': 8641, 'OPR': 49.763, 'Auto': 23.493, 'CCWM': 28.773, 'TeamName': 'The Masters'}, {'TeamNum': 19924, 'OPR': 45.305, 'Auto': 18.985, 'CCWM': 26.106, 'TeamName': 'The Black Swan'}, {'TeamNum': 22180, 'OPR': 41.962, 'Auto': 17.411, 'CCWM': -25.706, 'TeamName': 'Sprocketeers'}, {'TeamNum': 22524, 'OPR': 39.386, 'Auto': 14.31, 'CCWM': -29.345, 'TeamName': 'WELP'}, {'TeamNum': 15749, 'OPR': 38.853, 'Auto': 17.089, 'CCWM': 20.962, 'TeamName': 'OHMS Baconators '}, {'TeamNum': 17230, 'OPR': 32.559, 'Auto': 9.275, 'CCWM': -47.503, 'TeamName': 'Aluminum Falcons'}, {'TeamNum': 21709, 'OPR': 32.503, 'Auto': 5.0, 'CCWM': -9.235, 'TeamName': 'JHCS Mecha Grizzlies - Blue'}, {'TeamNum': 8280, 'OPR': 30.214, 'Auto': 18.585, 'CCWM': 5.069, 'TeamName': 'Calamity'}, {'TeamNum': 11002, 'OPR': 29.772, 'Auto': 13.307, 'CCWM': -26.222, 'TeamName': 'Die Toaste'}, {'TeamNum': 20108, 'OPR': 28.569, 'Auto': 8.852, 'CCWM': -10.312, 'TeamName': 'GOATs'}, {'TeamNum': 12515, 'OPR': 26.192, 'Auto': 3.602, 'CCWM': -36.306, 'TeamName': 'Titanium Knights'}, {'TeamNum': 16748, 'OPR': 25.866, 'Auto': 7.002, 'CCWM': 7.572, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 8400, 'OPR': 20.421, 'Auto': 10.025, 'CCWM': -59.978, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 19744, 'OPR': 17.502, 'Auto': -1.058, 'CCWM': -14.554, 'TeamName': 'Astro Knights'}, {'TeamNum': 10533, 'OPR': 14.368, 'Auto': 9.857, 'CCWM': -40.193, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 16927, 'OPR': 9.966, 'Auto': 5.296, 'CCWM': -14.595, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 19922, 'OPR': 5.764, 'Auto': -0.546, 'CCWM': -17.504, 'TeamName': 'Iron Lions'}, {'TeamNum': 21676, 'OPR': 5.544, 'Auto': 3.923, 'CCWM': -34.555, 'TeamName': 'Traffic Cone Pigeon Girls'}, {'TeamNum': 21895, 'OPR': 2.689, 'Auto': 4.506, 'CCWM': -52.047, 'TeamName': 'Töster Strüüüüüdel'}]
USUTPCQ
[{'TeamNum': 10695, 'OPR': 132.32, 'Auto': 40.584, 'CCWM': 99.272, 'TeamName': 'Theta Robotics'}, {'TeamNum': 15413, 'OPR': 98.437, 'Auto': 19.448, 'CCWM': 28.961, 'TeamName': 'Toaster Medics'}, {'TeamNum': 21710, 'OPR': 82.235, 'Auto': 17.803, 'CCWM': 52.383, 'TeamName': 'JHCS Mecha Grizzlies - Gold'}, {'TeamNum': 19697, 'OPR': 80.184, 'Auto': 20.86, 'CCWM': 43.501, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 5667, 'OPR': 79.121, 'Auto': 29.669, 'CCWM': 33.048, 'TeamName': 'Robominers'}, {'TeamNum': 12351, 'OPR': 77.873, 'Auto': 17.107, 'CCWM': 71.492, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 5026, 'OPR': 57.534, 'Auto': 4.307, 'CCWM': 8.566, 'TeamName': 'Tesla Coils'}, {'TeamNum': 21765, 'OPR': 56.237, 'Auto': 6.312, 'CCWM': -12.87, 'TeamName': 'Overclocked'}, {'TeamNum': 8641, 'OPR': 49.763, 'Auto': 23.493, 'CCWM': 28.773, 'TeamName': 'The Masters'}, {'TeamNum': 19924, 'OPR': 45.305, 'Auto': 18.985, 'CCWM': 26.106, 'TeamName': 'The Black Swan'}, {'TeamNum': 22180, 'OPR': 41.962, 'Auto': 17.411, 'CCWM': -25.706, 'TeamName': 'Sprocketeers'}, {'TeamNum': 22524, 'OPR': 39.386, 'Auto': 14.31, 'CCWM': -29.345, 'TeamName': 'WELP'}, {'TeamNum': 15749, 'OPR': 38.853, 'Auto': 17.089, 'CCWM': 20.962, 'TeamName': 'OHMS Baconators '}, {'TeamNum': 17230, 'OPR': 32.559, 'Auto': 9.275, 'CCWM': -47.503, 'TeamName': 'Aluminum Falcons'}, {'TeamNum': 21709, 'OPR': 32.503, 'Auto': 5.0, 'CCWM': -9.235, 'TeamName': 'JHCS Mecha Grizzlies - Blue'}, {'TeamNum': 8280, 'OPR': 30.214, 'Auto': 18.585, 'CCWM': 5.069, 'TeamName': 'Calamity'}, {'TeamNum': 11002, 'OPR': 29.772, 'Auto': 13.307, 'CCWM': -26.222, 'TeamName': 'Die Toaste'}, {'TeamNum': 20108, 'OPR': 28.569, 'Auto': 8.852, 'CCWM': -10.312, 'TeamName': 'GOATs'}, {'TeamNum': 12515, 'OPR': 26.192, 'Auto': 3.602, 'CCWM': -36.306, 'TeamName': 'Titanium Knights'}, {'TeamNum': 16748, 'OPR': 25.866, 'Auto': 7.002, 'CCWM': 7.572, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 8400, 'OPR': 20.421, 'Auto': 10.025, 'CCWM': -59.978, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 19744, 'OPR': 17.502, 'Auto': -1.058, 'CCWM': -14.554, 'TeamName': 'Astro Knights'}, {'TeamNum': 10533, 'OPR': 14.368, 'Auto': 9.857, 'CCWM': -40.193, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 16927, 'OPR': 9.966, 'Auto': 5.296, 'CCWM': -14.595, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 19922, 'OPR': 5.764, 'Auto': -0.546, 'CCWM': -17.504, 'TeamName': 'Iron Lions'}, {'TeamNum': 21676, 'OPR': 5.544, 'Auto': 3.923, 'CCWM': -34.555, 'TeamName': 'Traffic Cone Pigeon Girls'}, {'TeamNum': 21895, 'OPR': 2.689, 'Auto': 4.506, 'CCWM': -52.047, 'TeamName': 'Töster Strüüüüüdel'}]
i 1113
{'21100', '21105', '22883', '21096', '13906', '21109', '22933', '21051', '22916', '22043', '22954', '21055'}
[{'TeamNum': 21100, 'OPR': 72.569, 'Auto': 20.264, 'CCWM': 50.23, 'TeamName': 'The G C School Voyagers'}, {'TeamNum': 13906, 'OPR': 50.812, 'Auto': 10.312, 'CCWM': 26.283, 'TeamName': 'Epiteugma Revved Up'}, {'TeamNum': 22954, 'OPR': 40.209, 'Auto': 0.635, 'CCWM': 5.304, 'TeamName': 'The English School Roosters'}, {'TeamNum': 21109, 'OPR': 29.887, 'Auto': 3.116, 'CCWM': 22.208, 'TeamName': 'TESEK Makarios III RoboMak'}, {'TeamNum': 22883, 'OPR': 24.142, 'Auto': -4.128, 'CCWM': 8.488, 'TeamName': 'Akaki Gymnasium Robot Designers'}, {'TeamNum': 21055, 'OPR': 23.647, 'Auto': 10.007, 'CCWM': -1.95, 'TeamName': 'Pascal Lefkosia Eagles'}, {'TeamNum': 22043, 'OPR': 23.335, 'Auto': 15.523, 'CCWM': -23.708, 'TeamName': 'MellonLAB UniREVsals'}, {'TeamNum': 21096, 'OPR': 18.115, 'Auto': 1.441, 'CCWM': -4.318, 'TeamName': 'MellonLab RobotBirds'}, {'TeamNum': 22933, 'OPR': 17.237, 'Auto': -1.107, 'CCWM': -7.517, 'TeamName': 'Akaki Gymnasium Junior Jokers'}, {'TeamNum': 22916, 'OPR': 14.344, 'Auto': 3.406, 'CCWM': -12.444, 'TeamName': 'TESEK Makarios III Robotica'}, {'TeamNum': 21051, 'OPR': 8.472, 'Auto': -2.502, 'CCWM': -24.99, 'TeamName': 'Comwiz BITS'}, {'TeamNum': 21105, 'OPR': 6.899, 'Auto': 3.199, 'CCWM': -37.586, 'TeamName': 'The Grammar School  Commutabilis Robottus Junior '}]
CYCMP
[{'TeamNum': 21100, 'OPR': 72.569, 'Auto': 20.264, 'CCWM': 50.23, 'TeamName': 'The G C School Voyagers'}, {'TeamNum': 13906, 'OPR': 50.812, 'Auto': 10.312, 'CCWM': 26.283, 'TeamName': 'Epiteugma Revved Up'}, {'TeamNum': 22954, 'OPR': 40.209, 'Auto': 0.635, 'CCWM': 5.304, 'TeamName': 'The English School Roosters'}, {'TeamNum': 21109, 'OPR': 29.887, 'Auto': 3.116, 'CCWM': 22.208, 'TeamName': 'TESEK Makarios III RoboMak'}, {'TeamNum': 22883, 'OPR': 24.142, 'Auto': -4.128, 'CCWM': 8.488, 'TeamName': 'Akaki Gymnasium Robot Designers'}, {'TeamNum': 21055, 'OPR': 23.647, 'Auto': 10.007, 'CCWM': -1.95, 'TeamName': 'Pascal Lefkosia Eagles'}, {'TeamNum': 22043, 'OPR': 23.335, 'Auto': 15.523, 'CCWM': -23.708, 'TeamName': 'MellonLAB UniREVsals'}, {'TeamNum': 21096, 'OPR': 18.115, 'Auto': 1.441, 'CCWM': -4.318, 'TeamName': 'MellonLab RobotBirds'}, {'TeamNum': 22933, 'OPR': 17.237, 'Auto': -1.107, 'CCWM': -7.517, 'TeamName': 'Akaki Gymnasium Junior Jokers'}, {'TeamNum': 22916, 'OPR': 14.344, 'Auto': 3.406, 'CCWM': -12.444, 'TeamName': 'TESEK Makarios III Robotica'}, {'TeamNum': 21051, 'OPR': 8.472, 'Auto': -2.502, 'CCWM': -24.99, 'TeamName': 'Comwiz BITS'}, {'TeamNum': 21105, 'OPR': 6.899, 'Auto': 3.199, 'CCWM': -37.586, 'TeamName': 'The Grammar School  Commutabilis Robottus Junior '}]
i 1114

i 1115
{'23120', '23113', '23115', '23112', '23125', '23122', '23114', '23117', '23116', '23119', '23121', '23118'}
[{'TeamNum': 23114, 'OPR': 48.327, 'Auto': 22.236, 'CCWM': 34.775, 'TeamName': 'Sabah'}, {'TeamNum': 23113, 'OPR': 37.784, 'Auto': 13.579, 'CCWM': 28.257, 'TeamName': 'EdisonFTC'}, {'TeamNum': 23115, 'OPR': 30.621, 'Auto': 16.762, 'CCWM': 4.362, 'TeamName': 'Electra'}, {'TeamNum': 23119, 'OPR': 23.999, 'Auto': 19.047, 'CCWM': 9.749, 'TeamName': 'QASTclaw'}, {'TeamNum': 23112, 'OPR': 17.981, 'Auto': 6.195, 'CCWM': -5.633, 'TeamName': 'QSTSS1'}, {'TeamNum': 23116, 'OPR': 17.84, 'Auto': 5.074, 'CCWM': 16.525, 'TeamName': 'ABMFTC'}, {'TeamNum': 23125, 'OPR': 17.351, 'Auto': 9.373, 'CCWM': 6.011, 'TeamName': 'Dominators'}, {'TeamNum': 23120, 'OPR': 15.153, 'Auto': 2.081, 'CCWM': -27.2, 'TeamName': 'QADBots2'}, {'TeamNum': 23117, 'OPR': 3.49, 'Auto': -6.917, 'CCWM': -20.997, 'TeamName': 'AbuO FTC'}, {'TeamNum': 23118, 'OPR': 2.014, 'Auto': -4.032, 'CCWM': -15.801, 'TeamName': 'RoboQAST'}, {'TeamNum': 23121, 'OPR': 0.227, 'Auto': -0.17, 'CCWM': -9.312, 'TeamName': '974'}, {'TeamNum': 23122, 'OPR': 0.014, 'Auto': 0.774, 'CCWM': -20.734, 'TeamName': 'Unsorted Organization'}]
QACMP
[{'TeamNum': 23114, 'OPR': 48.327, 'Auto': 22.236, 'CCWM': 34.775, 'TeamName': 'Sabah'}, {'TeamNum': 23113, 'OPR': 37.784, 'Auto': 13.579, 'CCWM': 28.257, 'TeamName': 'EdisonFTC'}, {'TeamNum': 23115, 'OPR': 30.621, 'Auto': 16.762, 'CCWM': 4.362, 'TeamName': 'Electra'}, {'TeamNum': 23119, 'OPR': 23.999, 'Auto': 19.047, 'CCWM': 9.749, 'TeamName': 'QASTclaw'}, {'TeamNum': 23112, 'OPR': 17.981, 'Auto': 6.195, 'CCWM': -5.633, 'TeamName': 'QSTSS1'}, {'TeamNum': 23116, 'OPR': 17.84, 'Auto': 5.074, 'CCWM': 16.525, 'TeamName': 'ABMFTC'}, {'TeamNum': 23125, 'OPR': 17.351, 'Auto': 9.373, 'CCWM': 6.011, 'TeamName': 'Dominators'}, {'TeamNum': 23120, 'OPR': 15.153, 'Auto': 2.081, 'CCWM': -27.2, 'TeamName': 'QADBots2'}, {'TeamNum': 23117, 'OPR': 3.49, 'Auto': -6.917, 'CCWM': -20.997, 'TeamName': 'AbuO FTC'}, {'TeamNum': 23118, 'OPR': 2.014, 'Auto': -4.032, 'CCWM': -15.801, 'TeamName': 'RoboQAST'}, {'TeamNum': 23121, 'OPR': 0.227, 'Auto': -0.17, 'CCWM': -9.312, 'TeamName': '974'}, {'TeamNum': 23122, 'OPR': 0.014, 'Auto': 0.774, 'CCWM': -20.734, 'TeamName': 'Unsorted Organization'}]
i 1116
{'20955', '21194', '22706', '21000', '21116'}
[{'TeamNum': 21000, 'OPR': 50.921, 'Auto': 16.152, 'CCWM': 34.901, 'TeamName': '@FSL_ROBOTICS_2022'}, {'TeamNum': 21116, 'OPR': 37.694, 'Auto': 11.185, 'CCWM': 9.257, 'TeamName': 'UK MCB'}, {'TeamNum': 20955, 'OPR': 24.944, 'Auto': 17.013, 'CCWM': -16.125, 'TeamName': 'UK-051'}, {'TeamNum': 22706, 'OPR': 21.816, 'Auto': 6.573, 'CCWM': -10.151, 'TeamName': 'UK 049-St. Patricks College-SPC'}, {'TeamNum': 21194, 'OPR': 10.168, 'Auto': 5.29, 'CCWM': -22.007, 'TeamName': 'RBAI'}]
GBBEQ
[{'TeamNum': 21000, 'OPR': 50.921, 'Auto': 16.152, 'CCWM': 34.901, 'TeamName': '@FSL_ROBOTICS_2022'}, {'TeamNum': 21116, 'OPR': 37.694, 'Auto': 11.185, 'CCWM': 9.257, 'TeamName': 'UK MCB'}, {'TeamNum': 20955, 'OPR': 24.944, 'Auto': 17.013, 'CCWM': -16.125, 'TeamName': 'UK-051'}, {'TeamNum': 22706, 'OPR': 21.816, 'Auto': 6.573, 'CCWM': -10.151, 'TeamName': 'UK 049-St. Patricks College-SPC'}, {'TeamNum': 21194, 'OPR': 10.168, 'Auto': 5.29, 'CCWM': -22.007, 'TeamName': 'RBAI'}]
i 1117
{'21838', '21668', '21641', '21686', '21636', '21637', '21635', '21670', '21638', '21639'}
[{'TeamNum': 21638, 'OPR': 67.104, 'Auto': 19.585, 'CCWM': 56.224, 'TeamName': '21638'}, {'TeamNum': 21668, 'OPR': 57.849, 'Auto': 9.637, 'CCWM': 44.345, 'TeamName': 'Toothless MK4'}, {'TeamNum': 21637, 'OPR': 26.808, 'Auto': 9.208, 'CCWM': -0.502, 'TeamName': 'MonkeyBot'}, {'TeamNum': 21639, 'OPR': 24.043, 'Auto': -0.361, 'CCWM': 12.475, 'TeamName': 'EJ King Middle High School '}, {'TeamNum': 21686, 'OPR': 23.53, 'Auto': 3.073, 'CCWM': 0.861, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 21635, 'OPR': 22.121, 'Auto': 2.411, 'CCWM': -4.275, 'TeamName': 'X Ash A - XII'}, {'TeamNum': 21641, 'OPR': 11.069, 'Auto': -4.178, 'CCWM': -36.137, 'TeamName': 'Kinnick Red Devils'}, {'TeamNum': 21838, 'OPR': 9.94, 'Auto': 1.724, 'CCWM': -26.809, 'TeamName': 'KDHS Pride'}, {'TeamNum': 21670, 'OPR': 6.341, 'Auto': -2.063, 'CCWM': -26.242, 'TeamName': 'Candyland'}, {'TeamNum': 21636, 'OPR': 5.411, 'Auto': 4.471, 'CCWM': -21.583, 'TeamName': 'Eddie'}]
ONADODFE23LT
[{'TeamNum': 21638, 'OPR': 67.104, 'Auto': 19.585, 'CCWM': 56.224, 'TeamName': '21638'}, {'TeamNum': 21668, 'OPR': 57.849, 'Auto': 9.637, 'CCWM': 44.345, 'TeamName': 'Toothless MK4'}, {'TeamNum': 21637, 'OPR': 26.808, 'Auto': 9.208, 'CCWM': -0.502, 'TeamName': 'MonkeyBot'}, {'TeamNum': 21639, 'OPR': 24.043, 'Auto': -0.361, 'CCWM': 12.475, 'TeamName': 'EJ King Middle High School '}, {'TeamNum': 21686, 'OPR': 23.53, 'Auto': 3.073, 'CCWM': 0.861, 'TeamName': 'Samurai Robotics'}, {'TeamNum': 21635, 'OPR': 22.121, 'Auto': 2.411, 'CCWM': -4.275, 'TeamName': 'X Ash A - XII'}, {'TeamNum': 21641, 'OPR': 11.069, 'Auto': -4.178, 'CCWM': -36.137, 'TeamName': 'Kinnick Red Devils'}, {'TeamNum': 21838, 'OPR': 9.94, 'Auto': 1.724, 'CCWM': -26.809, 'TeamName': 'KDHS Pride'}, {'TeamNum': 21670, 'OPR': 6.341, 'Auto': -2.063, 'CCWM': -26.242, 'TeamName': 'Candyland'}, {'TeamNum': 21636, 'OPR': 5.411, 'Auto': 4.471, 'CCWM': -21.583, 'TeamName': 'Eddie'}]
i 1118
{'7159', '17702', '3650', '19743', '14140', '5015', '11212', '4216', '15146', '16884', '18365', '12499', '11285', '15171', '5131', '8097', '14535', '18263', '22105', '10809', '11128', '21303', '10793', '8380', '21239', '19793', '9164', '4262', '14338', '10092', '18568', '6016', '14496', '14129', '1622', '16192'}
[{'TeamNum': 15171, 'OPR': 146.496, 'Auto': 44.695, 'CCWM': 107.766, 'TeamName': 'Scorpio'}, {'TeamNum': 14496, 'OPR': 126.564, 'Auto': 37.482, 'CCWM': 74.472, 'TeamName': 'Roboctopi'}, {'TeamNum': 21239, 'OPR': 126.167, 'Auto': 28.172, 'CCWM': 95.018, 'TeamName': 'All Systems Go'}, {'TeamNum': 16884, 'OPR': 111.767, 'Auto': 20.373, 'CCWM': 73.404, 'TeamName': 'Mechanical Advantage'}, {'TeamNum': 14535, 'OPR': 106.61, 'Auto': 26.119, 'CCWM': 58.706, 'TeamName': 'Alpacas'}, {'TeamNum': 4216, 'OPR': 103.281, 'Auto': 31.312, 'CCWM': 13.24, 'TeamName': 'Rise of Hephaestus'}, {'TeamNum': 10092, 'OPR': 101.401, 'Auto': 31.238, 'CCWM': 33.807, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 14140, 'OPR': 100.739, 'Auto': 40.783, 'CCWM': 4.772, 'TeamName': 'Crash Test'}, {'TeamNum': 18263, 'OPR': 96.914, 'Auto': 27.02, 'CCWM': 35.751, 'TeamName': 'HIGH VOLTAGE'}, {'TeamNum': 5131, 'OPR': 96.682, 'Auto': 25.975, 'CCWM': 91.377, 'TeamName': 'Pointers'}, {'TeamNum': 19743, 'OPR': 92.729, 'Auto': 28.643, 'CCWM': -1.198, 'TeamName': 'Definitely Human'}, {'TeamNum': 15146, 'OPR': 92.516, 'Auto': 20.82, 'CCWM': 54.654, 'TeamName': 'GarageBot'}, {'TeamNum': 11212, 'OPR': 91.56, 'Auto': 14.261, 'CCWM': 10.397, 'TeamName': 'The Clueless '}, {'TeamNum': 16192, 'OPR': 80.757, 'Auto': 28.795, 'CCWM': -12.422, 'TeamName': 'Prepare to ALT+F4'}, {'TeamNum': 8380, 'OPR': 75.873, 'Auto': 23.485, 'CCWM': -15.463, 'TeamName': 'UC Robotics'}, {'TeamNum': 3650, 'OPR': 74.403, 'Auto': 15.573, 'CCWM': 22.056, 'TeamName': 'Torrey Techies'}, {'TeamNum': 18568, 'OPR': 73.903, 'Auto': 20.037, 'CCWM': 6.256, 'TeamName': 'Minimum Viable Product'}, {'TeamNum': 8097, 'OPR': 70.783, 'Auto': 30.299, 'CCWM': 11.55, 'TeamName': 'Botcats'}, {'TeamNum': 19793, 'OPR': 68.633, 'Auto': 16.955, 'CCWM': 22.788, 'TeamName': 'Uncaught Exception'}, {'TeamNum': 10793, 'OPR': 66.178, 'Auto': 27.35, 'CCWM': -9.763, 'TeamName': 'Voltrons'}, {'TeamNum': 12499, 'OPR': 63.878, 'Auto': 18.51, 'CCWM': 32.929, 'TeamName': 'Gear Up'}, {'TeamNum': 10809, 'OPR': 62.374, 'Auto': 13.048, 'CCWM': -22.816, 'TeamName': 'Crow Force'}, {'TeamNum': 7159, 'OPR': 49.548, 'Auto': 9.9, 'CCWM': 5.496, 'TeamName': 'Robo Ravens'}, {'TeamNum': 4262, 'OPR': 49.085, 'Auto': 9.163, 'CCWM': -27.161, 'TeamName': 'Ridgebots'}, {'TeamNum': 11128, 'OPR': 48.441, 'Auto': 6.754, 'CCWM': -50.997, 'TeamName': 'Inspiration'}, {'TeamNum': 14338, 'OPR': 46.761, 'Auto': 4.591, 'CCWM': -75.88, 'TeamName': 'CAOS Robotics ("Chaos")'}, {'TeamNum': 22105, 'OPR': 44.832, 'Auto': 15.802, 'CCWM': -13.631, 'TeamName': 'Runtime Terror'}, {'TeamNum': 9164, 'OPR': 42.346, 'Auto': 5.244, 'CCWM': 0.803, 'TeamName': 'Zorrobots'}, {'TeamNum': 17702, 'OPR': 39.088, 'Auto': 7.512, 'CCWM': -24.974, 'TeamName': 'Transcendence'}, {'TeamNum': 11285, 'OPR': 34.564, 'Auto': 15.307, 'CCWM': -62.305, 'TeamName': 'PATENT PENDING'}, {'TeamNum': 14129, 'OPR': 34.237, 'Auto': 20.159, 'CCWM': -62.074, 'TeamName': 'Wizalos'}, {'TeamNum': 5015, 'OPR': 31.183, 'Auto': 4.028, 'CCWM': -39.622, 'TeamName': 'Buffalo Wings'}, {'TeamNum': 18365, 'OPR': 27.702, 'Auto': 5.406, 'CCWM': -69.453, 'TeamName': 'Dapper RoboNoodles'}, {'TeamNum': 6016, 'OPR': 25.646, 'Auto': 22.247, 'CCWM': -79.59, 'TeamName': 'Ironwolves'}, {'TeamNum': 21303, 'OPR': 9.013, 'Auto': 2.575, 'CCWM': -78.227, 'TeamName': 'Pandamonium'}, {'TeamNum': 1622, 'OPR': -14.49, 'Auto': -14.631, 'CCWM': -109.664, 'TeamName': 'Team Spyder'}]
USCASDCMP
[{'TeamNum': 15171, 'OPR': 146.496, 'Auto': 44.695, 'CCWM': 107.766, 'TeamName': 'Scorpio'}, {'TeamNum': 14496, 'OPR': 126.564, 'Auto': 37.482, 'CCWM': 74.472, 'TeamName': 'Roboctopi'}, {'TeamNum': 21239, 'OPR': 126.167, 'Auto': 28.172, 'CCWM': 95.018, 'TeamName': 'All Systems Go'}, {'TeamNum': 16884, 'OPR': 111.767, 'Auto': 20.373, 'CCWM': 73.404, 'TeamName': 'Mechanical Advantage'}, {'TeamNum': 14535, 'OPR': 106.61, 'Auto': 26.119, 'CCWM': 58.706, 'TeamName': 'Alpacas'}, {'TeamNum': 4216, 'OPR': 103.281, 'Auto': 31.312, 'CCWM': 13.24, 'TeamName': 'Rise of Hephaestus'}, {'TeamNum': 10092, 'OPR': 101.401, 'Auto': 31.238, 'CCWM': 33.807, 'TeamName': 'Green.Griffins;'}, {'TeamNum': 14140, 'OPR': 100.739, 'Auto': 40.783, 'CCWM': 4.772, 'TeamName': 'Crash Test'}, {'TeamNum': 18263, 'OPR': 96.914, 'Auto': 27.02, 'CCWM': 35.751, 'TeamName': 'HIGH VOLTAGE'}, {'TeamNum': 5131, 'OPR': 96.682, 'Auto': 25.975, 'CCWM': 91.377, 'TeamName': 'Pointers'}, {'TeamNum': 19743, 'OPR': 92.729, 'Auto': 28.643, 'CCWM': -1.198, 'TeamName': 'Definitely Human'}, {'TeamNum': 15146, 'OPR': 92.516, 'Auto': 20.82, 'CCWM': 54.654, 'TeamName': 'GarageBot'}, {'TeamNum': 11212, 'OPR': 91.56, 'Auto': 14.261, 'CCWM': 10.397, 'TeamName': 'The Clueless '}, {'TeamNum': 16192, 'OPR': 80.757, 'Auto': 28.795, 'CCWM': -12.422, 'TeamName': 'Prepare to ALT+F4'}, {'TeamNum': 8380, 'OPR': 75.873, 'Auto': 23.485, 'CCWM': -15.463, 'TeamName': 'UC Robotics'}, {'TeamNum': 3650, 'OPR': 74.403, 'Auto': 15.573, 'CCWM': 22.056, 'TeamName': 'Torrey Techies'}, {'TeamNum': 18568, 'OPR': 73.903, 'Auto': 20.037, 'CCWM': 6.256, 'TeamName': 'Minimum Viable Product'}, {'TeamNum': 8097, 'OPR': 70.783, 'Auto': 30.299, 'CCWM': 11.55, 'TeamName': 'Botcats'}, {'TeamNum': 19793, 'OPR': 68.633, 'Auto': 16.955, 'CCWM': 22.788, 'TeamName': 'Uncaught Exception'}, {'TeamNum': 10793, 'OPR': 66.178, 'Auto': 27.35, 'CCWM': -9.763, 'TeamName': 'Voltrons'}, {'TeamNum': 12499, 'OPR': 63.878, 'Auto': 18.51, 'CCWM': 32.929, 'TeamName': 'Gear Up'}, {'TeamNum': 10809, 'OPR': 62.374, 'Auto': 13.048, 'CCWM': -22.816, 'TeamName': 'Crow Force'}, {'TeamNum': 7159, 'OPR': 49.548, 'Auto': 9.9, 'CCWM': 5.496, 'TeamName': 'Robo Ravens'}, {'TeamNum': 4262, 'OPR': 49.085, 'Auto': 9.163, 'CCWM': -27.161, 'TeamName': 'Ridgebots'}, {'TeamNum': 11128, 'OPR': 48.441, 'Auto': 6.754, 'CCWM': -50.997, 'TeamName': 'Inspiration'}, {'TeamNum': 14338, 'OPR': 46.761, 'Auto': 4.591, 'CCWM': -75.88, 'TeamName': 'CAOS Robotics ("Chaos")'}, {'TeamNum': 22105, 'OPR': 44.832, 'Auto': 15.802, 'CCWM': -13.631, 'TeamName': 'Runtime Terror'}, {'TeamNum': 9164, 'OPR': 42.346, 'Auto': 5.244, 'CCWM': 0.803, 'TeamName': 'Zorrobots'}, {'TeamNum': 17702, 'OPR': 39.088, 'Auto': 7.512, 'CCWM': -24.974, 'TeamName': 'Transcendence'}, {'TeamNum': 11285, 'OPR': 34.564, 'Auto': 15.307, 'CCWM': -62.305, 'TeamName': 'PATENT PENDING'}, {'TeamNum': 14129, 'OPR': 34.237, 'Auto': 20.159, 'CCWM': -62.074, 'TeamName': 'Wizalos'}, {'TeamNum': 5015, 'OPR': 31.183, 'Auto': 4.028, 'CCWM': -39.622, 'TeamName': 'Buffalo Wings'}, {'TeamNum': 18365, 'OPR': 27.702, 'Auto': 5.406, 'CCWM': -69.453, 'TeamName': 'Dapper RoboNoodles'}, {'TeamNum': 6016, 'OPR': 25.646, 'Auto': 22.247, 'CCWM': -79.59, 'TeamName': 'Ironwolves'}, {'TeamNum': 21303, 'OPR': 9.013, 'Auto': 2.575, 'CCWM': -78.227, 'TeamName': 'Pandamonium'}, {'TeamNum': 1622, 'OPR': -14.49, 'Auto': -14.631, 'CCWM': -109.664, 'TeamName': 'Team Spyder'}]

i 1119
{'21980', '11334', '11337', '6282', '14996', '9887', '7767', '18457', '21380', '11770', '7460', '12675', '14863', '16235', '19510', '4625', '6325', '16795', '25', '4348', '5218', '12861', '9247', '4628', '13046', '15091', '21936', '10298', '15046', '21525', '20824', '21788', '3526', '16321', '21982', '14295', '359', '17600', '6373', '4153', '6436', '9040'}
[{'TeamNum': 14295, 'OPR': 140.534, 'Auto': 17.98, 'CCWM': 76.717, 'TeamName': 'Operation T.A.C.'}, {'TeamNum': 21980, 'OPR': 120.788, 'Auto': 4.638, 'CCWM': 77.144, 'TeamName': 'Bread Pandas'}, {'TeamNum': 21380, 'OPR': 116.108, 'Auto': 30.019, 'CCWM': 49.687, 'TeamName': 'Beyond Robotics'}, {'TeamNum': 12861, 'OPR': 115.302, 'Auto': 30.101, 'CCWM': 39.262, 'TeamName': 'RoboHeroes'}, {'TeamNum': 6436, 'OPR': 112.906, 'Auto': 5.218, 'CCWM': 70.922, 'TeamName': 'AlphaGenesis'}, {'TeamNum': 18457, 'OPR': 112.84, 'Auto': 39.873, 'CCWM': 33.055, 'TeamName': 'GatorBytes'}, {'TeamNum': 21936, 'OPR': 111.213, 'Auto': 19.339, 'CCWM': 48.098, 'TeamName': 'SaMoTech'}, {'TeamNum': 11770, 'OPR': 102.339, 'Auto': 31.028, 'CCWM': 71.135, 'TeamName': 'Curiosity'}, {'TeamNum': 7767, 'OPR': 95.31, 'Auto': 16.273, 'CCWM': -8.038, 'TeamName': 'Blueprints'}, {'TeamNum': 4348, 'OPR': 93.051, 'Auto': 16.998, 'CCWM': 88.044, 'TeamName': 'RoboKnights'}, {'TeamNum': 14996, 'OPR': 92.217, 'Auto': 19.903, 'CCWM': -0.634, 'TeamName': 'Omega Squad'}, {'TeamNum': 6373, 'OPR': 86.013, 'Auto': 4.463, 'CCWM': 42.956, 'TeamName': 'SuperBots'}, {'TeamNum': 20824, 'OPR': 85.863, 'Auto': 16.261, 'CCWM': 18.869, 'TeamName': 'LeXT - Pineapple Something'}, {'TeamNum': 21982, 'OPR': 84.326, 'Auto': 17.372, 'CCWM': 19.198, 'TeamName': 'Inkineers'}, {'TeamNum': 6282, 'OPR': 82.49, 'Auto': 17.411, 'CCWM': -24.796, 'TeamName': 'Simi Valley Robotics'}, {'TeamNum': 15091, 'OPR': 81.318, 'Auto': 28.881, 'CCWM': 42.555, 'TeamName': 'aztec.exe'}, {'TeamNum': 14863, 'OPR': 79.681, 'Auto': 21.893, 'CCWM': 0.292, 'TeamName': 'RGB'}, {'TeamNum': 12675, 'OPR': 78.416, 'Auto': 18.693, 'CCWM': 19.453, 'TeamName': 'Hermit Social Club'}, {'TeamNum': 6325, 'OPR': 77.799, 'Auto': 19.481, 'CCWM': -15.106, 'TeamName': 'Aluminati'}, {'TeamNum': 9040, 'OPR': 76.249, 'Auto': 16.681, 'CCWM': 38.125, 'TeamName': 'STEAMpunks Alpha'}, {'TeamNum': 9887, 'OPR': 74.226, 'Auto': 12.72, 'CCWM': -40.151, 'TeamName': 'CyberDragons Marvinette'}, {'TeamNum': 5218, 'OPR': 73.671, 'Auto': 5.477, 'CCWM': 28.288, 'TeamName': 'Javabots'}, {'TeamNum': 15046, 'OPR': 73.209, 'Auto': 16.246, 'CCWM': 52.626, 'TeamName': 'Incognito Robotics'}, {'TeamNum': 10298, 'OPR': 72.375, 'Auto': 17.488, 'CCWM': 14.905, 'TeamName': 'Brain Stormz'}, {'TeamNum': 9247, 'OPR': 70.644, 'Auto': 3.372, 'CCWM': -17.653, 'TeamName': 'Chromium Robotics'}, {'TeamNum': 3526, 'OPR': 65.787, 'Auto': 23.322, 'CCWM': -2.415, 'TeamName': 'Marlbots'}, {'TeamNum': 19510, 'OPR': 65.708, 'Auto': 23.53, 'CCWM': -49.822, 'TeamName': 'VolTech'}, {'TeamNum': 16321, 'OPR': 64.654, 'Auto': 11.351, 'CCWM': -44.071, 'TeamName': 'X Drive'}, {'TeamNum': 16235, 'OPR': 62.338, 'Auto': 1.3, 'CCWM': -25.655, 'TeamName': 'Judicator '}, {'TeamNum': 4625, 'OPR': 62.012, 'Auto': 22.602, 'CCWM': -19.033, 'TeamName': 'Kings and Queens'}, {'TeamNum': 17600, 'OPR': 61.927, 'Auto': 11.196, 'CCWM': -20.93, 'TeamName': 'MoVal Robotics'}, {'TeamNum': 25, 'OPR': 60.957, 'Auto': 21.46, 'CCWM': 13.375, 'TeamName': "Rock N' Roll Robots"}, {'TeamNum': 7460, 'OPR': 56.719, 'Auto': 6.643, 'CCWM': -57.615, 'TeamName': 'Thunder'}, {'TeamNum': 21788, 'OPR': 53.328, 'Auto': 11.803, 'CCWM': -56.0, 'TeamName': 'Beta Rocks'}, {'TeamNum': 11337, 'OPR': 50.245, 'Auto': 21.43, 'CCWM': -24.279, 'TeamName': 'Robonauts'}, {'TeamNum': 11334, 'OPR': 49.344, 'Auto': 17.561, 'CCWM': -55.352, 'TeamName': 'Alpha Tech'}, {'TeamNum': 21525, 'OPR': 45.74, 'Auto': 7.773, 'CCWM': -36.994, 'TeamName': 'Blockheads²'}, {'TeamNum': 359, 'OPR': 27.193, 'Auto': 1.749, 'CCWM': -50.071, 'TeamName': 'WEBB.exe'}, {'TeamNum': 4153, 'OPR': 19.739, 'Auto': 9.59, 'CCWM': -77.835, 'TeamName': 'Neptune'}, {'TeamNum': 4628, 'OPR': 16.736, 'Auto': 13.476, 'CCWM': -38.045, 'TeamName': 'Suit Bots'}, {'TeamNum': 16795, 'OPR': 14.398, 'Auto': 9.93, 'CCWM': -69.148, 'TeamName': 'Galaxy'}, {'TeamNum': 13046, 'OPR': 0.745, 'Auto': 4.919, 'CCWM': -108.913, 'TeamName': 'Riptide Robotics'}]
USCALACMP
[{'TeamNum': 14295, 'OPR': 140.534, 'Auto': 17.98, 'CCWM': 76.717, 'TeamName': 'Operation T.A.C.'}, {'TeamNum': 21980, 'OPR': 120.788, 'Auto': 4.638, 'CCWM': 77.144, 'TeamName': 'Bread Pandas'}, {'TeamNum': 21380, 'OPR': 116.108, 'Auto': 30.019, 'CCWM': 49.687, 'TeamName': 'Beyond Robotics'}, {'TeamNum': 12861, 'OPR': 115.302, 'Auto': 30.101, 'CCWM': 39.262, 'TeamName': 'RoboHeroes'}, {'TeamNum': 6436, 'OPR': 112.906, 'Auto': 5.218, 'CCWM': 70.922, 'TeamName': 'AlphaGenesis'}, {'TeamNum': 18457, 'OPR': 112.84, 'Auto': 39.873, 'CCWM': 33.055, 'TeamName': 'GatorBytes'}, {'TeamNum': 21936, 'OPR': 111.213, 'Auto': 19.339, 'CCWM': 48.098, 'TeamName': 'SaMoTech'}, {'TeamNum': 11770, 'OPR': 102.339, 'Auto': 31.028, 'CCWM': 71.135, 'TeamName': 'Curiosity'}, {'TeamNum': 7767, 'OPR': 95.31, 'Auto': 16.273, 'CCWM': -8.038, 'TeamName': 'Blueprints'}, {'TeamNum': 4348, 'OPR': 93.051, 'Auto': 16.998, 'CCWM': 88.044, 'TeamName': 'RoboKnights'}, {'TeamNum': 14996, 'OPR': 92.217, 'Auto': 19.903, 'CCWM': -0.634, 'TeamName': 'Omega Squad'}, {'TeamNum': 6373, 'OPR': 86.013, 'Auto': 4.463, 'CCWM': 42.956, 'TeamName': 'SuperBots'}, {'TeamNum': 20824, 'OPR': 85.863, 'Auto': 16.261, 'CCWM': 18.869, 'TeamName': 'LeXT - Pineapple Something'}, {'TeamNum': 21982, 'OPR': 84.326, 'Auto': 17.372, 'CCWM': 19.198, 'TeamName': 'Inkineers'}, {'TeamNum': 6282, 'OPR': 82.49, 'Auto': 17.411, 'CCWM': -24.796, 'TeamName': 'Simi Valley Robotics'}, {'TeamNum': 15091, 'OPR': 81.318, 'Auto': 28.881, 'CCWM': 42.555, 'TeamName': 'aztec.exe'}, {'TeamNum': 14863, 'OPR': 79.681, 'Auto': 21.893, 'CCWM': 0.292, 'TeamName': 'RGB'}, {'TeamNum': 12675, 'OPR': 78.416, 'Auto': 18.693, 'CCWM': 19.453, 'TeamName': 'Hermit Social Club'}, {'TeamNum': 6325, 'OPR': 77.799, 'Auto': 19.481, 'CCWM': -15.106, 'TeamName': 'Aluminati'}, {'TeamNum': 9040, 'OPR': 76.249, 'Auto': 16.681, 'CCWM': 38.125, 'TeamName': 'STEAMpunks Alpha'}, {'TeamNum': 9887, 'OPR': 74.226, 'Auto': 12.72, 'CCWM': -40.151, 'TeamName': 'CyberDragons Marvinette'}, {'TeamNum': 5218, 'OPR': 73.671, 'Auto': 5.477, 'CCWM': 28.288, 'TeamName': 'Javabots'}, {'TeamNum': 15046, 'OPR': 73.209, 'Auto': 16.246, 'CCWM': 52.626, 'TeamName': 'Incognito Robotics'}, {'TeamNum': 10298, 'OPR': 72.375, 'Auto': 17.488, 'CCWM': 14.905, 'TeamName': 'Brain Stormz'}, {'TeamNum': 9247, 'OPR': 70.644, 'Auto': 3.372, 'CCWM': -17.653, 'TeamName': 'Chromium Robotics'}, {'TeamNum': 3526, 'OPR': 65.787, 'Auto': 23.322, 'CCWM': -2.415, 'TeamName': 'Marlbots'}, {'TeamNum': 19510, 'OPR': 65.708, 'Auto': 23.53, 'CCWM': -49.822, 'TeamName': 'VolTech'}, {'TeamNum': 16321, 'OPR': 64.654, 'Auto': 11.351, 'CCWM': -44.071, 'TeamName': 'X Drive'}, {'TeamNum': 16235, 'OPR': 62.338, 'Auto': 1.3, 'CCWM': -25.655, 'TeamName': 'Judicator '}, {'TeamNum': 4625, 'OPR': 62.012, 'Auto': 22.602, 'CCWM': -19.033, 'TeamName': 'Kings and Queens'}, {'TeamNum': 17600, 'OPR': 61.927, 'Auto': 11.196, 'CCWM': -20.93, 'TeamName': 'MoVal Robotics'}, {'TeamNum': 25, 'OPR': 60.957, 'Auto': 21.46, 'CCWM': 13.375, 'TeamName': "Rock N' Roll Robots"}, {'TeamNum': 7460, 'OPR': 56.719, 'Auto': 6.643, 'CCWM': -57.615, 'TeamName': 'Thunder'}, {'TeamNum': 21788, 'OPR': 53.328, 'Auto': 11.803, 'CCWM': -56.0, 'TeamName': 'Beta Rocks'}, {'TeamNum': 11337, 'OPR': 50.245, 'Auto': 21.43, 'CCWM': -24.279, 'TeamName': 'Robonauts'}, {'TeamNum': 11334, 'OPR': 49.344, 'Auto': 17.561, 'CCWM': -55.352, 'TeamName': 'Alpha Tech'}, {'TeamNum': 21525, 'OPR': 45.74, 'Auto': 7.773, 'CCWM': -36.994, 'TeamName': 'Blockheads²'}, {'TeamNum': 359, 'OPR': 27.193, 'Auto': 1.749, 'CCWM': -50.071, 'TeamName': 'WEBB.exe'}, {'TeamNum': 4153, 'OPR': 19.739, 'Auto': 9.59, 'CCWM': -77.835, 'TeamName': 'Neptune'}, {'TeamNum': 4628, 'OPR': 16.736, 'Auto': 13.476, 'CCWM': -38.045, 'TeamName': 'Suit Bots'}, {'TeamNum': 16795, 'OPR': 14.398, 'Auto': 9.93, 'CCWM': -69.148, 'TeamName': 'Galaxy'}, {'TeamNum': 13046, 'OPR': 0.745, 'Auto': 4.919, 'CCWM': -108.913, 'TeamName': 'Riptide Robotics'}]

i 1120
{'16162', '12744', '18552', '6088', '5053', '14147', '18095', '11973', '13003', '13164', '20371', '5026', '20169', '19760', '21887', '21610', '19999', '21347', '22203'}
[{'TeamNum': 5026, 'OPR': 113.769, 'Auto': 14.168, 'CCWM': 96.304, 'TeamName': 'Tesla Coils'}, {'TeamNum': 16162, 'OPR': 112.283, 'Auto': 24.156, 'CCWM': 78.221, 'TeamName': 'A2Z Robotics'}, {'TeamNum': 19760, 'OPR': 67.325, 'Auto': 22.257, 'CCWM': 48.31, 'TeamName': 'NIRB (North Idaho Ruby Bots)'}, {'TeamNum': 18095, 'OPR': 60.397, 'Auto': 7.237, 'CCWM': 24.479, 'TeamName': 'Haywired! Robotics'}, {'TeamNum': 5053, 'OPR': 60.37, 'Auto': 21.758, 'CCWM': 5.926, 'TeamName': 'Clearwater Atomic Robotic Technicians'}, {'TeamNum': 14147, 'OPR': 49.313, 'Auto': 17.145, 'CCWM': 12.965, 'TeamName': 'High Voltage Couch Bananas'}, {'TeamNum': 18552, 'OPR': 48.697, 'Auto': 10.317, 'CCWM': 2.652, 'TeamName': 'Moscow Mechanics '}, {'TeamNum': 13003, 'OPR': 46.953, 'Auto': 9.049, 'CCWM': 23.926, 'TeamName': 'Electromanders'}, {'TeamNum': 21610, 'OPR': 35.337, 'Auto': 4.934, 'CCWM': -26.59, 'TeamName': 'Riverhawks'}, {'TeamNum': 6088, 'OPR': 33.174, 'Auto': 9.238, 'CCWM': -42.877, 'TeamName': 'Bolt'}, {'TeamNum': 13164, 'OPR': 25.09, 'Auto': 5.555, 'CCWM': -10.134, 'TeamName': 'STEM 94'}, {'TeamNum': 20371, 'OPR': 21.619, 'Auto': 9.135, 'CCWM': -15.889, 'TeamName': 'Chargers'}, {'TeamNum': 20169, 'OPR': 16.394, 'Auto': 2.599, 'CCWM': -40.588, 'TeamName': 'PiSTEM Dinos'}, {'TeamNum': 11973, 'OPR': 15.799, 'Auto': 6.543, 'CCWM': -15.419, 'TeamName': 'Riverstone OtterBots'}, {'TeamNum': 12744, 'OPR': 15.514, 'Auto': 5.657, 'CCWM': -30.376, 'TeamName': 'Twin Falls High School'}, {'TeamNum': 19999, 'OPR': 15.461, 'Auto': -2.74, 'CCWM': -45.09, 'TeamName': 'Wheeled Wildcats'}, {'TeamNum': 21887, 'OPR': 13.86, 'Auto': 6.906, 'CCWM': -26.71, 'TeamName': 'Firth Tech Team'}, {'TeamNum': 21347, 'OPR': 7.42, 'Auto': -2.923, 'CCWM': -16.074, 'TeamName': 'Argobots'}, {'TeamNum': 22203, 'OPR': 6.278, 'Auto': -3.078, 'CCWM': -13.947, 'TeamName': 'Mind Over Metal'}]
USIDCMP
[{'TeamNum': 5026, 'OPR': 113.769, 'Auto': 14.168, 'CCWM': 96.304, 'TeamName': 'Tesla Coils'}, {'TeamNum': 16162, 'OPR': 112.283, 'Auto': 24.156, 'CCWM': 78.221, 'TeamName': 'A2Z Robotics'}, {'TeamNum': 19760, 'OPR': 67.325, 'Auto': 22.257, 'CCWM': 48.31, 'TeamName': 'NIRB (North Idaho Ruby Bots)'}, {'TeamNum': 18095, 'OPR': 60.397, 'Auto': 7.237, 'CCWM': 24.479, 'TeamName': 'Haywired! Robotics'}, {'TeamNum': 5053, 'OPR': 60.37, 'Auto': 21.758, 'CCWM': 5.926, 'TeamName': 'Clearwater Atomic Robotic Technicians'}, {'TeamNum': 14147, 'OPR': 49.313, 'Auto': 17.145, 'CCWM': 12.965, 'TeamName': 'High Voltage Couch Bananas'}, {'TeamNum': 18552, 'OPR': 48.697, 'Auto': 10.317, 'CCWM': 2.652, 'TeamName': 'Moscow Mechanics '}, {'TeamNum': 13003, 'OPR': 46.953, 'Auto': 9.049, 'CCWM': 23.926, 'TeamName': 'Electromanders'}, {'TeamNum': 21610, 'OPR': 35.337, 'Auto': 4.934, 'CCWM': -26.59, 'TeamName': 'Riverhawks'}, {'TeamNum': 6088, 'OPR': 33.174, 'Auto': 9.238, 'CCWM': -42.877, 'TeamName': 'Bolt'}, {'TeamNum': 13164, 'OPR': 25.09, 'Auto': 5.555, 'CCWM': -10.134, 'TeamName': 'STEM 94'}, {'TeamNum': 20371, 'OPR': 21.619, 'Auto': 9.135, 'CCWM': -15.889, 'TeamName': 'Chargers'}, {'TeamNum': 20169, 'OPR': 16.394, 'Auto': 2.599, 'CCWM': -40.588, 'TeamName': 'PiSTEM Dinos'}, {'TeamNum': 11973, 'OPR': 15.799, 'Auto': 6.543, 'CCWM': -15.419, 'TeamName': 'Riverstone OtterBots'}, {'TeamNum': 12744, 'OPR': 15.514, 'Auto': 5.657, 'CCWM': -30.376, 'TeamName': 'Twin Falls High School'}, {'TeamNum': 19999, 'OPR': 15.461, 'Auto': -2.74, 'CCWM': -45.09, 'TeamName': 'Wheeled Wildcats'}, {'TeamNum': 21887, 'OPR': 13.86, 'Auto': 6.906, 'CCWM': -26.71, 'TeamName': 'Firth Tech Team'}, {'TeamNum': 21347, 'OPR': 7.42, 'Auto': -2.923, 'CCWM': -16.074, 'TeamName': 'Argobots'}, {'TeamNum': 22203, 'OPR': 6.278, 'Auto': -3.078, 'CCWM': -13.947, 'TeamName': 'Mind Over Metal'}]
i 1121
i 1122
{'7164', '13375', '8818', '10696', '12382', '8109', '17384', '22942', '5477', '16145', '8013', '6942', '14461', '3540', '4137', '17204', '7407', '124', '21605', '7120', '7417', '8110', '4017', '11649', '10738'}
[{'TeamNum': 10738, 'OPR': 121.014, 'Auto': 29.483, 'CCWM': 75.153, 'TeamName': 'SBS  Bears'}, {'TeamNum': 4137, 'OPR': 83.894, 'Auto': 29.456, 'CCWM': 43.269, 'TeamName': 'IslandBots'}, {'TeamNum': 21605, 'OPR': 83.485, 'Auto': 13.049, 'CCWM': 22.906, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 5477, 'OPR': 76.567, 'Auto': 20.067, 'CCWM': 55.14, 'TeamName': 'Innovo'}, {'TeamNum': 8818, 'OPR': 71.852, 'Auto': 10.277, 'CCWM': -6.043, 'TeamName': 'Portledge Hit the Switch!'}, {'TeamNum': 12382, 'OPR': 67.92, 'Auto': 26.435, 'CCWM': 4.793, 'TeamName': 'Syosset Nebula'}, {'TeamNum': 8013, 'OPR': 65.836, 'Auto': 2.87, 'CCWM': -32.148, 'TeamName': 'Team Kuiper'}, {'TeamNum': 4017, 'OPR': 63.259, 'Auto': 19.244, 'CCWM': -16.887, 'TeamName': 'RoboPandas'}, {'TeamNum': 22942, 'OPR': 60.387, 'Auto': 14.361, 'CCWM': 18.661, 'TeamName': 'Iron Phoenix '}, {'TeamNum': 10696, 'OPR': 59.689, 'Auto': 16.171, 'CCWM': -39.805, 'TeamName': 'Syosset Syborgs'}, {'TeamNum': 14461, 'OPR': 55.289, 'Auto': 8.692, 'CCWM': 7.879, 'TeamName': 'RoboHawks'}, {'TeamNum': 6942, 'OPR': 54.044, 'Auto': 11.475, 'CCWM': 23.618, 'TeamName': 'Pandemonium'}, {'TeamNum': 8110, 'OPR': 44.891, 'Auto': -7.03, 'CCWM': 19.08, 'TeamName': 'Invicta'}, {'TeamNum': 7164, 'OPR': 43.948, 'Auto': 20.652, 'CCWM': 5.598, 'TeamName': 'FalconBots'}, {'TeamNum': 17384, 'OPR': 43.45, 'Auto': 11.189, 'CCWM': -7.056, 'TeamName': 'Rambam Rambots'}, {'TeamNum': 13375, 'OPR': 43.443, 'Auto': 19.282, 'CCWM': 9.272, 'TeamName': 'Great Neck North Goatbusters'}, {'TeamNum': 16145, 'OPR': 41.8, 'Auto': 20.034, 'CCWM': -15.068, 'TeamName': 'Sea Lions'}, {'TeamNum': 8109, 'OPR': 41.283, 'Auto': -7.559, 'CCWM': 9.442, 'TeamName': 'RISE Robotics'}, {'TeamNum': 7120, 'OPR': 33.277, 'Auto': 0.267, 'CCWM': -10.896, 'TeamName': 'Bionica'}, {'TeamNum': 124, 'OPR': 28.094, 'Auto': 1.445, 'CCWM': -33.334, 'TeamName': 'Syosset Supersonics'}, {'TeamNum': 3540, 'OPR': 27.038, 'Auto': 8.384, 'CCWM': 8.609, 'TeamName': 'RoboBoogie'}, {'TeamNum': 7417, 'OPR': 24.983, 'Auto': 7.573, 'CCWM': -70.992, 'TeamName': 'Portledge Robotics'}, {'TeamNum': 7407, 'OPR': 22.968, 'Auto': 10.196, 'CCWM': -29.921, 'TeamName': 'Team VEGA'}, {'TeamNum': 17204, 'OPR': 16.389, 'Auto': -2.016, 'CCWM': -41.269, 'TeamName': 'Wired Wyverns'}, {'TeamNum': 11649, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Portledge Robo Time'}]
USNYLICMP
[{'TeamNum': 10738, 'OPR': 121.014, 'Auto': 29.483, 'CCWM': 75.153, 'TeamName': 'SBS  Bears'}, {'TeamNum': 4137, 'OPR': 83.894, 'Auto': 29.456, 'CCWM': 43.269, 'TeamName': 'IslandBots'}, {'TeamNum': 21605, 'OPR': 83.485, 'Auto': 13.049, 'CCWM': 22.906, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 5477, 'OPR': 76.567, 'Auto': 20.067, 'CCWM': 55.14, 'TeamName': 'Innovo'}, {'TeamNum': 8818, 'OPR': 71.852, 'Auto': 10.277, 'CCWM': -6.043, 'TeamName': 'Portledge Hit the Switch!'}, {'TeamNum': 12382, 'OPR': 67.92, 'Auto': 26.435, 'CCWM': 4.793, 'TeamName': 'Syosset Nebula'}, {'TeamNum': 8013, 'OPR': 65.836, 'Auto': 2.87, 'CCWM': -32.148, 'TeamName': 'Team Kuiper'}, {'TeamNum': 4017, 'OPR': 63.259, 'Auto': 19.244, 'CCWM': -16.887, 'TeamName': 'RoboPandas'}, {'TeamNum': 22942, 'OPR': 60.387, 'Auto': 14.361, 'CCWM': 18.661, 'TeamName': 'Iron Phoenix '}, {'TeamNum': 10696, 'OPR': 59.689, 'Auto': 16.171, 'CCWM': -39.805, 'TeamName': 'Syosset Syborgs'}, {'TeamNum': 14461, 'OPR': 55.289, 'Auto': 8.692, 'CCWM': 7.879, 'TeamName': 'RoboHawks'}, {'TeamNum': 6942, 'OPR': 54.044, 'Auto': 11.475, 'CCWM': 23.618, 'TeamName': 'Pandemonium'}, {'TeamNum': 8110, 'OPR': 44.891, 'Auto': -7.03, 'CCWM': 19.08, 'TeamName': 'Invicta'}, {'TeamNum': 7164, 'OPR': 43.948, 'Auto': 20.652, 'CCWM': 5.598, 'TeamName': 'FalconBots'}, {'TeamNum': 17384, 'OPR': 43.45, 'Auto': 11.189, 'CCWM': -7.056, 'TeamName': 'Rambam Rambots'}, {'TeamNum': 13375, 'OPR': 43.443, 'Auto': 19.282, 'CCWM': 9.272, 'TeamName': 'Great Neck North Goatbusters'}, {'TeamNum': 16145, 'OPR': 41.8, 'Auto': 20.034, 'CCWM': -15.068, 'TeamName': 'Sea Lions'}, {'TeamNum': 8109, 'OPR': 41.283, 'Auto': -7.559, 'CCWM': 9.442, 'TeamName': 'RISE Robotics'}, {'TeamNum': 7120, 'OPR': 33.277, 'Auto': 0.267, 'CCWM': -10.896, 'TeamName': 'Bionica'}, {'TeamNum': 124, 'OPR': 28.094, 'Auto': 1.445, 'CCWM': -33.334, 'TeamName': 'Syosset Supersonics'}, {'TeamNum': 3540, 'OPR': 27.038, 'Auto': 8.384, 'CCWM': 8.609, 'TeamName': 'RoboBoogie'}, {'TeamNum': 7417, 'OPR': 24.983, 'Auto': 7.573, 'CCWM': -70.992, 'TeamName': 'Portledge Robotics'}, {'TeamNum': 7407, 'OPR': 22.968, 'Auto': 10.196, 'CCWM': -29.921, 'TeamName': 'Team VEGA'}, {'TeamNum': 17204, 'OPR': 16.389, 'Auto': -2.016, 'CCWM': -41.269, 'TeamName': 'Wired Wyverns'}, {'TeamNum': 11649, 'OPR': 0.0, 'Auto': 0.0, 'CCWM': 0.0, 'TeamName': 'Portledge Robo Time'}]
i 1123

{'10851', '14365', '17978', '19778', '18386', '4537', '21865', '6418', '22523', '10237', '8120', '5501', '7136', '18275', '8642', '20744', '4969', '8581', '10464', '11580', '14261', '4360', '5040', '5754', '13172', '12802', '10084', '16449', '8719', '11187', '12768', '19804', '20385', '14279', '7324', '11781', '16657'}
[{'TeamNum': 4969, 'OPR': 125.999, 'Auto': 28.934, 'CCWM': 22.568, 'TeamName': 'Robot-X'}, {'TeamNum': 6418, 'OPR': 120.975, 'Auto': 11.295, 'CCWM': 8.033, 'TeamName': 'NDCL Robotics'}, {'TeamNum': 16449, 'OPR': 120.756, 'Auto': 28.362, 'CCWM': 61.176, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 17978, 'OPR': 120.587, 'Auto': 27.657, 'CCWM': -16.854, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 8120, 'OPR': 120.349, 'Auto': 22.057, 'CCWM': 26.807, 'TeamName': 'Electric Hornets'}, {'TeamNum': 8642, 'OPR': 120.323, 'Auto': 17.484, 'CCWM': 45.995, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 7324, 'OPR': 106.576, 'Auto': 30.251, 'CCWM': 36.77, 'TeamName': 'Oxymorons'}, {'TeamNum': 5040, 'OPR': 100.814, 'Auto': 14.324, 'CCWM': 97.041, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 12802, 'OPR': 85.371, 'Auto': 19.736, 'CCWM': -2.944, 'TeamName': 'We Will Bot You'}, {'TeamNum': 19778, 'OPR': 84.671, 'Auto': 17.244, 'CCWM': 7.702, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 20744, 'OPR': 81.197, 'Auto': -5.421, 'CCWM': 53.003, 'TeamName': '24 Karat'}, {'TeamNum': 19804, 'OPR': 80.856, 'Auto': 10.082, 'CCWM': 12.339, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 10851, 'OPR': 77.357, 'Auto': 23.571, 'CCWM': 38.131, 'TeamName': 'WASA'}, {'TeamNum': 10464, 'OPR': 74.292, 'Auto': 17.389, 'CCWM': -24.446, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 11580, 'OPR': 73.836, 'Auto': 15.74, 'CCWM': -38.797, 'TeamName': 'EagleBots'}, {'TeamNum': 14279, 'OPR': 72.938, 'Auto': 19.035, 'CCWM': 42.807, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 14365, 'OPR': 72.536, 'Auto': 7.96, 'CCWM': 8.128, 'TeamName': 'Summit Knights'}, {'TeamNum': 10084, 'OPR': 69.502, 'Auto': 21.086, 'CCWM': 14.124, 'TeamName': 'Team Calamari'}, {'TeamNum': 8719, 'OPR': 68.019, 'Auto': 21.756, 'CCWM': -54.237, 'TeamName': 'Quantum Leap'}, {'TeamNum': 20385, 'OPR': 65.829, 'Auto': 12.301, 'CCWM': 21.751, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 4537, 'OPR': 64.52, 'Auto': 20.018, 'CCWM': 0.719, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 4360, 'OPR': 64.335, 'Auto': 18.825, 'CCWM': -39.856, 'TeamName': 'Raider Robotics'}, {'TeamNum': 8581, 'OPR': 61.935, 'Auto': 13.188, 'CCWM': -13.991, 'TeamName': 'Ædificatores'}, {'TeamNum': 21865, 'OPR': 61.382, 'Auto': 13.903, 'CCWM': 15.158, 'TeamName': 'Fe2O3'}, {'TeamNum': 7136, 'OPR': 61.171, 'Auto': 18.67, 'CCWM': -11.959, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 12768, 'OPR': 59.889, 'Auto': 22.935, 'CCWM': -30.347, 'TeamName': 'INNOV-8'}, {'TeamNum': 16657, 'OPR': 58.817, 'Auto': 5.504, 'CCWM': 35.06, 'TeamName': 'We Did Start the Fire'}, {'TeamNum': 18275, 'OPR': 58.79, 'Auto': 18.532, 'CCWM': 2.315, 'TeamName': 'SubZero'}, {'TeamNum': 11187, 'OPR': 51.995, 'Auto': 13.308, 'CCWM': -23.286, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 13172, 'OPR': 51.364, 'Auto': 13.096, 'CCWM': -76.062, 'TeamName': 'Centipede'}, {'TeamNum': 5754, 'OPR': 50.978, 'Auto': 16.084, 'CCWM': -27.711, 'TeamName': 'Marburn Academy Marbotics'}, {'TeamNum': 5501, 'OPR': 48.734, 'Auto': 20.221, 'CCWM': 12.043, 'TeamName': 'VW Robotics'}, {'TeamNum': 22523, 'OPR': 42.704, 'Auto': 7.142, 'CCWM': 36.524, 'TeamName': 'CL0VERLEAF R0B0TICS'}, {'TeamNum': 10237, 'OPR': 33.39, 'Auto': 9.958, 'CCWM': -72.485, 'TeamName': 'US Robotics'}, {'TeamNum': 14261, 'OPR': 21.551, 'Auto': -7.068, 'CCWM': -32.063, 'TeamName': 'Wreck Less'}, {'TeamNum': 18386, 'OPR': 9.127, 'Auto': 7.976, 'CCWM': -36.664, 'TeamName': 'Parallax Robotics'}, {'TeamNum': 11781, 'OPR': -3.469, 'Auto': -1.036, 'CCWM': -98.412, 'TeamName': 'MVS Rambotics'}]
USOHCMP
[{'TeamNum': 4969, 'OPR': 125.999, 'Auto': 28.934, 'CCWM': 22.568, 'TeamName': 'Robot-X'}, {'TeamNum': 6418, 'OPR': 120.975, 'Auto': 11.295, 'CCWM': 8.033, 'TeamName': 'NDCL Robotics'}, {'TeamNum': 16449, 'OPR': 120.756, 'Auto': 28.362, 'CCWM': 61.176, 'TeamName': 'Juniper Robotics'}, {'TeamNum': 17978, 'OPR': 120.587, 'Auto': 27.657, 'CCWM': -16.854, 'TeamName': 'Robo Kai (Fenwick)'}, {'TeamNum': 8120, 'OPR': 120.349, 'Auto': 22.057, 'CCWM': 26.807, 'TeamName': 'Electric Hornets'}, {'TeamNum': 8642, 'OPR': 120.323, 'Auto': 17.484, 'CCWM': 45.995, 'TeamName': '8 to Automate FTC'}, {'TeamNum': 7324, 'OPR': 106.576, 'Auto': 30.251, 'CCWM': 36.77, 'TeamName': 'Oxymorons'}, {'TeamNum': 5040, 'OPR': 100.814, 'Auto': 14.324, 'CCWM': 97.041, 'TeamName': 'Nuts & Bolts'}, {'TeamNum': 12802, 'OPR': 85.371, 'Auto': 19.736, 'CCWM': -2.944, 'TeamName': 'We Will Bot You'}, {'TeamNum': 19778, 'OPR': 84.671, 'Auto': 17.244, 'CCWM': 7.702, 'TeamName': 'Wire Monkeys'}, {'TeamNum': 20744, 'OPR': 81.197, 'Auto': -5.421, 'CCWM': 53.003, 'TeamName': '24 Karat'}, {'TeamNum': 19804, 'OPR': 80.856, 'Auto': 10.082, 'CCWM': 12.339, 'TeamName': 'Unsafe At Any Speed'}, {'TeamNum': 10851, 'OPR': 77.357, 'Auto': 23.571, 'CCWM': 38.131, 'TeamName': 'WASA'}, {'TeamNum': 10464, 'OPR': 74.292, 'Auto': 17.389, 'CCWM': -24.446, 'TeamName': 'The Bionic Tigers'}, {'TeamNum': 11580, 'OPR': 73.836, 'Auto': 15.74, 'CCWM': -38.797, 'TeamName': 'EagleBots'}, {'TeamNum': 14279, 'OPR': 72.938, 'Auto': 19.035, 'CCWM': 42.807, 'TeamName': 'FLRC - Circuit Breakers'}, {'TeamNum': 14365, 'OPR': 72.536, 'Auto': 7.96, 'CCWM': 8.128, 'TeamName': 'Summit Knights'}, {'TeamNum': 10084, 'OPR': 69.502, 'Auto': 21.086, 'CCWM': 14.124, 'TeamName': 'Team Calamari'}, {'TeamNum': 8719, 'OPR': 68.019, 'Auto': 21.756, 'CCWM': -54.237, 'TeamName': 'Quantum Leap'}, {'TeamNum': 20385, 'OPR': 65.829, 'Auto': 12.301, 'CCWM': 21.751, 'TeamName': 'The Abundant Sheep'}, {'TeamNum': 4537, 'OPR': 64.52, 'Auto': 20.018, 'CCWM': 0.719, 'TeamName': 'DRSS Enterprise'}, {'TeamNum': 4360, 'OPR': 64.335, 'Auto': 18.825, 'CCWM': -39.856, 'TeamName': 'Raider Robotics'}, {'TeamNum': 8581, 'OPR': 61.935, 'Auto': 13.188, 'CCWM': -13.991, 'TeamName': 'Ædificatores'}, {'TeamNum': 21865, 'OPR': 61.382, 'Auto': 13.903, 'CCWM': 15.158, 'TeamName': 'Fe2O3'}, {'TeamNum': 7136, 'OPR': 61.171, 'Auto': 18.67, 'CCWM': -11.959, 'TeamName': 'Higgs Bosons'}, {'TeamNum': 12768, 'OPR': 59.889, 'Auto': 22.935, 'CCWM': -30.347, 'TeamName': 'INNOV-8'}, {'TeamNum': 16657, 'OPR': 58.817, 'Auto': 5.504, 'CCWM': 35.06, 'TeamName': 'We Did Start the Fire'}, {'TeamNum': 18275, 'OPR': 58.79, 'Auto': 18.532, 'CCWM': 2.315, 'TeamName': 'SubZero'}, {'TeamNum': 11187, 'OPR': 51.995, 'Auto': 13.308, 'CCWM': -23.286, 'TeamName': 'AZTECHS FTC'}, {'TeamNum': 13172, 'OPR': 51.364, 'Auto': 13.096, 'CCWM': -76.062, 'TeamName': 'Centipede'}, {'TeamNum': 5754, 'OPR': 50.978, 'Auto': 16.084, 'CCWM': -27.711, 'TeamName': 'Marburn Academy Marbotics'}, {'TeamNum': 5501, 'OPR': 48.734, 'Auto': 20.221, 'CCWM': 12.043, 'TeamName': 'VW Robotics'}, {'TeamNum': 22523, 'OPR': 42.704, 'Auto': 7.142, 'CCWM': 36.524, 'TeamName': 'CL0VERLEAF R0B0TICS'}, {'TeamNum': 10237, 'OPR': 33.39, 'Auto': 9.958, 'CCWM': -72.485, 'TeamName': 'US Robotics'}, {'TeamNum': 14261, 'OPR': 21.551, 'Auto': -7.068, 'CCWM': -32.063, 'TeamName': 'Wreck Less'}, {'TeamNum': 18386, 'OPR': 9.127, 'Auto': 7.976, 'CCWM': -36.664, 'TeamName': 'Parallax Robotics'}, {'TeamNum': 11781, 'OPR': -3.469, 'Auto': -1.036, 'CCWM': -98.412, 'TeamName': 'MVS Rambotics'}]
i 1124
{'10695', '15749', '5667', '19697', '10533', '12515', '16790', '20515', '16748', '17603', '19924', '12351', '17604', '16091', '19744', '11002', '15413', '16028', '19922', '17230', '8641', '19389', '22180', '10373', '21977', '16927', '21676', '21765', '3747', '21895', '16265', '21710', '22524', '8400', '8280'}
[{'TeamNum': 8641, 'OPR': 100.83, 'Auto': 29.641, 'CCWM': 35.037, 'TeamName': 'The Masters'}, {'TeamNum': 21765, 'OPR': 98.485, 'Auto': 32.387, 'CCWM': 17.48, 'TeamName': 'Overclocked'}, {'TeamNum': 16091, 'OPR': 89.127, 'Auto': 22.471, 'CCWM': 30.12, 'TeamName': 'T.W.C.A. (Team Without a Cool Acronym)'}, {'TeamNum': 16265, 'OPR': 88.899, 'Auto': 19.147, 'CCWM': 4.953, 'TeamName': 'ENIGMA'}, {'TeamNum': 10695, 'OPR': 88.836, 'Auto': 29.161, 'CCWM': 63.039, 'TeamName': 'Theta Robotics'}, {'TeamNum': 12351, 'OPR': 84.786, 'Auto': 1.424, 'CCWM': 21.49, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 8280, 'OPR': 82.596, 'Auto': 17.365, 'CCWM': 30.458, 'TeamName': 'Calamity'}, {'TeamNum': 5667, 'OPR': 80.332, 'Auto': 12.189, 'CCWM': 57.996, 'TeamName': 'Robominers'}, {'TeamNum': 15413, 'OPR': 79.049, 'Auto': 19.975, 'CCWM': 8.348, 'TeamName': 'Toaster Medics'}, {'TeamNum': 17604, 'OPR': 77.115, 'Auto': 7.87, 'CCWM': 35.74, 'TeamName': 'TNT (Terribly Nice Team)'}, {'TeamNum': 3747, 'OPR': 72.289, 'Auto': 24.941, 'CCWM': 19.135, 'TeamName': 'The Hive'}, {'TeamNum': 16028, 'OPR': 70.408, 'Auto': 22.139, 'CCWM': 58.608, 'TeamName': 'Mecha Knights'}, {'TeamNum': 19924, 'OPR': 68.164, 'Auto': 21.042, 'CCWM': 6.269, 'TeamName': 'The Black Swan'}, {'TeamNum': 10533, 'OPR': 67.074, 'Auto': 29.904, 'CCWM': 7.499, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 17603, 'OPR': 66.343, 'Auto': 21.854, 'CCWM': 9.229, 'TeamName': 'Nuclear Core'}, {'TeamNum': 11002, 'OPR': 66.166, 'Auto': 3.572, 'CCWM': 18.162, 'TeamName': 'Die Toaste'}, {'TeamNum': 21710, 'OPR': 64.798, 'Auto': 6.813, 'CCWM': -18.778, 'TeamName': 'JHCS Mecha Grizzlies - Gold'}, {'TeamNum': 22180, 'OPR': 59.563, 'Auto': 19.223, 'CCWM': 42.02, 'TeamName': 'Sprocketeers'}, {'TeamNum': 20515, 'OPR': 57.3, 'Auto': 13.85, 'CCWM': 3.402, 'TeamName': 'Cubed ETs'}, {'TeamNum': 19697, 'OPR': 56.655, 'Auto': 6.977, 'CCWM': -28.796, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 19744, 'OPR': 54.92, 'Auto': -0.884, 'CCWM': 0.649, 'TeamName': 'Astro Knights'}, {'TeamNum': 10373, 'OPR': 54.102, 'Auto': 9.105, 'CCWM': 9.544, 'TeamName': 'Black Ops'}, {'TeamNum': 16748, 'OPR': 52.904, 'Auto': 10.098, 'CCWM': -31.023, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 12515, 'OPR': 51.016, 'Auto': 11.375, 'CCWM': 45.93, 'TeamName': 'Titanium Knights'}, {'TeamNum': 21895, 'OPR': 47.666, 'Auto': 15.83, 'CCWM': -14.95, 'TeamName': 'Töster Strüüüüüdel'}, {'TeamNum': 22524, 'OPR': 45.637, 'Auto': 16.761, 'CCWM': -5.614, 'TeamName': 'WELP'}, {'TeamNum': 21977, 'OPR': 42.668, 'Auto': 19.632, 'CCWM': 27.633, 'TeamName': 'ElectroSloths'}, {'TeamNum': 17230, 'OPR': 40.245, 'Auto': 0.105, 'CCWM': -46.957, 'TeamName': 'Aluminum Falcons'}, {'TeamNum': 15749, 'OPR': 39.992, 'Auto': 14.635, 'CCWM': -25.817, 'TeamName': 'OHMS Baconators '}, {'TeamNum': 8400, 'OPR': 26.968, 'Auto': 12.965, 'CCWM': -61.235, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 16927, 'OPR': 26.78, 'Auto': 18.773, 'CCWM': -37.677, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 16790, 'OPR': 21.601, 'Auto': -2.892, 'CCWM': -100.73, 'TeamName': 'WARP'}, {'TeamNum': 19922, 'OPR': 19.741, 'Auto': 17.819, 'CCWM': -47.524, 'TeamName': 'Iron Lions'}, {'TeamNum': 19389, 'OPR': 11.613, 'Auto': -3.508, 'CCWM': -60.372, 'TeamName': 'Angry Aliens'}, {'TeamNum': 21676, 'OPR': -1.329, 'Auto': 1.07, 'CCWM': -73.948, 'TeamName': 'Traffic Cone Pigeon Girls'}]
USUTCMP
[{'TeamNum': 8641, 'OPR': 100.83, 'Auto': 29.641, 'CCWM': 35.037, 'TeamName': 'The Masters'}, {'TeamNum': 21765, 'OPR': 98.485, 'Auto': 32.387, 'CCWM': 17.48, 'TeamName': 'Overclocked'}, {'TeamNum': 16091, 'OPR': 89.127, 'Auto': 22.471, 'CCWM': 30.12, 'TeamName': 'T.W.C.A. (Team Without a Cool Acronym)'}, {'TeamNum': 16265, 'OPR': 88.899, 'Auto': 19.147, 'CCWM': 4.953, 'TeamName': 'ENIGMA'}, {'TeamNum': 10695, 'OPR': 88.836, 'Auto': 29.161, 'CCWM': 63.039, 'TeamName': 'Theta Robotics'}, {'TeamNum': 12351, 'OPR': 84.786, 'Auto': 1.424, 'CCWM': 21.49, 'TeamName': 'Nuclear Minds'}, {'TeamNum': 8280, 'OPR': 82.596, 'Auto': 17.365, 'CCWM': 30.458, 'TeamName': 'Calamity'}, {'TeamNum': 5667, 'OPR': 80.332, 'Auto': 12.189, 'CCWM': 57.996, 'TeamName': 'Robominers'}, {'TeamNum': 15413, 'OPR': 79.049, 'Auto': 19.975, 'CCWM': 8.348, 'TeamName': 'Toaster Medics'}, {'TeamNum': 17604, 'OPR': 77.115, 'Auto': 7.87, 'CCWM': 35.74, 'TeamName': 'TNT (Terribly Nice Team)'}, {'TeamNum': 3747, 'OPR': 72.289, 'Auto': 24.941, 'CCWM': 19.135, 'TeamName': 'The Hive'}, {'TeamNum': 16028, 'OPR': 70.408, 'Auto': 22.139, 'CCWM': 58.608, 'TeamName': 'Mecha Knights'}, {'TeamNum': 19924, 'OPR': 68.164, 'Auto': 21.042, 'CCWM': 6.269, 'TeamName': 'The Black Swan'}, {'TeamNum': 10533, 'OPR': 67.074, 'Auto': 29.904, 'CCWM': 7.499, 'TeamName': 'OHMS Velocity Raptors'}, {'TeamNum': 17603, 'OPR': 66.343, 'Auto': 21.854, 'CCWM': 9.229, 'TeamName': 'Nuclear Core'}, {'TeamNum': 11002, 'OPR': 66.166, 'Auto': 3.572, 'CCWM': 18.162, 'TeamName': 'Die Toaste'}, {'TeamNum': 21710, 'OPR': 64.798, 'Auto': 6.813, 'CCWM': -18.778, 'TeamName': 'JHCS Mecha Grizzlies - Gold'}, {'TeamNum': 22180, 'OPR': 59.563, 'Auto': 19.223, 'CCWM': 42.02, 'TeamName': 'Sprocketeers'}, {'TeamNum': 20515, 'OPR': 57.3, 'Auto': 13.85, 'CCWM': 3.402, 'TeamName': 'Cubed ETs'}, {'TeamNum': 19697, 'OPR': 56.655, 'Auto': 6.977, 'CCWM': -28.796, 'TeamName': 'S.O.U.P.'}, {'TeamNum': 19744, 'OPR': 54.92, 'Auto': -0.884, 'CCWM': 0.649, 'TeamName': 'Astro Knights'}, {'TeamNum': 10373, 'OPR': 54.102, 'Auto': 9.105, 'CCWM': 9.544, 'TeamName': 'Black Ops'}, {'TeamNum': 16748, 'OPR': 52.904, 'Auto': 10.098, 'CCWM': -31.023, 'TeamName': 'Rowland Hall Monochromats'}, {'TeamNum': 12515, 'OPR': 51.016, 'Auto': 11.375, 'CCWM': 45.93, 'TeamName': 'Titanium Knights'}, {'TeamNum': 21895, 'OPR': 47.666, 'Auto': 15.83, 'CCWM': -14.95, 'TeamName': 'Töster Strüüüüüdel'}, {'TeamNum': 22524, 'OPR': 45.637, 'Auto': 16.761, 'CCWM': -5.614, 'TeamName': 'WELP'}, {'TeamNum': 21977, 'OPR': 42.668, 'Auto': 19.632, 'CCWM': 27.633, 'TeamName': 'ElectroSloths'}, {'TeamNum': 17230, 'OPR': 40.245, 'Auto': 0.105, 'CCWM': -46.957, 'TeamName': 'Aluminum Falcons'}, {'TeamNum': 15749, 'OPR': 39.992, 'Auto': 14.635, 'CCWM': -25.817, 'TeamName': 'OHMS Baconators '}, {'TeamNum': 8400, 'OPR': 26.968, 'Auto': 12.965, 'CCWM': -61.235, 'TeamName': 'Perfect Paradox '}, {'TeamNum': 16927, 'OPR': 26.78, 'Auto': 18.773, 'CCWM': -37.677, 'TeamName': 'Brighton Robotics'}, {'TeamNum': 16790, 'OPR': 21.601, 'Auto': -2.892, 'CCWM': -100.73, 'TeamName': 'WARP'}, {'TeamNum': 19922, 'OPR': 19.741, 'Auto': 17.819, 'CCWM': -47.524, 'TeamName': 'Iron Lions'}, {'TeamNum': 19389, 'OPR': 11.613, 'Auto': -3.508, 'CCWM': -60.372, 'TeamName': 'Angry Aliens'}, {'TeamNum': 21676, 'OPR': -1.329, 'Auto': 1.07, 'CCWM': -73.948, 'TeamName': 'Traffic Cone Pigeon Girls'}]

i 1125
{'19927', '20293', '9225', '19367', '19796', '11570', '14631', '4106', '6914', '10100', '16310', '21923', '22548', '7974', '21355', '8680', '9956', '10824', '19417', '13201', '16460', '21180', '4115', '17235', '10829'}
[{'TeamNum': 8680, 'OPR': 151.067, 'Auto': 44.448, 'CCWM': 80.511, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 21180, 'OPR': 122.287, 'Auto': 35.497, 'CCWM': 38.787, 'TeamName': 'Error 418'}, {'TeamNum': 9956, 'OPR': 114.151, 'Auto': 46.466, 'CCWM': 26.571, 'TeamName': 'The Knack'}, {'TeamNum': 9225, 'OPR': 112.434, 'Auto': 30.947, 'CCWM': 36.674, 'TeamName': 'Dynamite Social Club'}, {'TeamNum': 10100, 'OPR': 106.053, 'Auto': 34.297, 'CCWM': 56.84, 'TeamName': 'Phoenix Force'}, {'TeamNum': 16310, 'OPR': 104.464, 'Auto': 30.218, 'CCWM': 17.376, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 16460, 'OPR': 103.143, 'Auto': 34.478, 'CCWM': 32.143, 'TeamName': 'GEarheads'}, {'TeamNum': 14631, 'OPR': 95.34, 'Auto': 17.26, 'CCWM': 38.967, 'TeamName': 'Laser Tech'}, {'TeamNum': 19367, 'OPR': 94.438, 'Auto': 38.539, 'CCWM': 5.069, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 10829, 'OPR': 93.685, 'Auto': 34.28, 'CCWM': -7.403, 'TeamName': 'Bay Robotics'}, {'TeamNum': 6914, 'OPR': 92.759, 'Auto': 17.373, 'CCWM': 8.594, 'TeamName': 'Charging Chaos'}, {'TeamNum': 10824, 'OPR': 89.635, 'Auto': 19.533, 'CCWM': 17.08, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 13201, 'OPR': 87.642, 'Auto': 35.165, 'CCWM': -34.83, 'TeamName': 'Team Hazmat'}, {'TeamNum': 19796, 'OPR': 84.168, 'Auto': 13.594, 'CCWM': -30.704, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 19927, 'OPR': 81.608, 'Auto': 26.637, 'CCWM': -12.632, 'TeamName': 'DUKES ROBOTICS'}, {'TeamNum': 20293, 'OPR': 81.156, 'Auto': 21.854, 'CCWM': -10.144, 'TeamName': 'Laser Bots'}, {'TeamNum': 4106, 'OPR': 74.543, 'Auto': 21.978, 'CCWM': -2.91, 'TeamName': 'Supposable Thumbs'}, {'TeamNum': 17235, 'OPR': 74.421, 'Auto': 24.679, 'CCWM': 18.446, 'TeamName': 'MR. COD'}, {'TeamNum': 11570, 'OPR': 73.805, 'Auto': 13.216, 'CCWM': -44.128, 'TeamName': 'Étude Engineers'}, {'TeamNum': 19417, 'OPR': 70.197, 'Auto': 16.617, 'CCWM': 0.103, 'TeamName': 'Superstellar'}, {'TeamNum': 7974, 'OPR': 65.864, 'Auto': 10.307, 'CCWM': -30.643, 'TeamName': 'Great Scott!'}, {'TeamNum': 21355, 'OPR': 54.733, 'Auto': 5.156, 'CCWM': -26.1, 'TeamName': 'Turtle TEK'}, {'TeamNum': 22548, 'OPR': 48.801, 'Auto': 6.918, 'CCWM': -49.644, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 4115, 'OPR': 33.011, 'Auto': 12.401, 'CCWM': -52.093, 'TeamName': 'Men in Kilts'}, {'TeamNum': 21923, 'OPR': 31.155, 'Auto': 13.183, 'CCWM': -88.89, 'TeamName': 'Greendale Robotics:  Neptune'}]
USWICMP
[{'TeamNum': 8680, 'OPR': 151.067, 'Auto': 44.448, 'CCWM': 80.511, 'TeamName': 'Kraken-Pinion '}, {'TeamNum': 21180, 'OPR': 122.287, 'Auto': 35.497, 'CCWM': 38.787, 'TeamName': 'Error 418'}, {'TeamNum': 9956, 'OPR': 114.151, 'Auto': 46.466, 'CCWM': 26.571, 'TeamName': 'The Knack'}, {'TeamNum': 9225, 'OPR': 112.434, 'Auto': 30.947, 'CCWM': 36.674, 'TeamName': 'Dynamite Social Club'}, {'TeamNum': 10100, 'OPR': 106.053, 'Auto': 34.297, 'CCWM': 56.84, 'TeamName': 'Phoenix Force'}, {'TeamNum': 16310, 'OPR': 104.464, 'Auto': 30.218, 'CCWM': 17.376, 'TeamName': 'Rising Rhinobots'}, {'TeamNum': 16460, 'OPR': 103.143, 'Auto': 34.478, 'CCWM': 32.143, 'TeamName': 'GEarheads'}, {'TeamNum': 14631, 'OPR': 95.34, 'Auto': 17.26, 'CCWM': 38.967, 'TeamName': 'Laser Tech'}, {'TeamNum': 19367, 'OPR': 94.438, 'Auto': 38.539, 'CCWM': 5.069, 'TeamName': 'Greendale Robotics:  ALIEN'}, {'TeamNum': 10829, 'OPR': 93.685, 'Auto': 34.28, 'CCWM': -7.403, 'TeamName': 'Bay Robotics'}, {'TeamNum': 6914, 'OPR': 92.759, 'Auto': 17.373, 'CCWM': 8.594, 'TeamName': 'Charging Chaos'}, {'TeamNum': 10824, 'OPR': 89.635, 'Auto': 19.533, 'CCWM': 17.08, 'TeamName': 'Tesla Trojans'}, {'TeamNum': 13201, 'OPR': 87.642, 'Auto': 35.165, 'CCWM': -34.83, 'TeamName': 'Team Hazmat'}, {'TeamNum': 19796, 'OPR': 84.168, 'Auto': 13.594, 'CCWM': -30.704, 'TeamName': 'Outside the BOTS'}, {'TeamNum': 19927, 'OPR': 81.608, 'Auto': 26.637, 'CCWM': -12.632, 'TeamName': 'DUKES ROBOTICS'}, {'TeamNum': 20293, 'OPR': 81.156, 'Auto': 21.854, 'CCWM': -10.144, 'TeamName': 'Laser Bots'}, {'TeamNum': 4106, 'OPR': 74.543, 'Auto': 21.978, 'CCWM': -2.91, 'TeamName': 'Supposable Thumbs'}, {'TeamNum': 17235, 'OPR': 74.421, 'Auto': 24.679, 'CCWM': 18.446, 'TeamName': 'MR. COD'}, {'TeamNum': 11570, 'OPR': 73.805, 'Auto': 13.216, 'CCWM': -44.128, 'TeamName': 'Étude Engineers'}, {'TeamNum': 19417, 'OPR': 70.197, 'Auto': 16.617, 'CCWM': 0.103, 'TeamName': 'Superstellar'}, {'TeamNum': 7974, 'OPR': 65.864, 'Auto': 10.307, 'CCWM': -30.643, 'TeamName': 'Great Scott!'}, {'TeamNum': 21355, 'OPR': 54.733, 'Auto': 5.156, 'CCWM': -26.1, 'TeamName': 'Turtle TEK'}, {'TeamNum': 22548, 'OPR': 48.801, 'Auto': 6.918, 'CCWM': -49.644, 'TeamName': 'Attack Hamsterz'}, {'TeamNum': 4115, 'OPR': 33.011, 'Auto': 12.401, 'CCWM': -52.093, 'TeamName': 'Men in Kilts'}, {'TeamNum': 21923, 'OPR': 31.155, 'Auto': 13.183, 'CCWM': -88.89, 'TeamName': 'Greendale Robotics:  Neptune'}]
i 1126
{'19188', '19194', '21084', '22374', '17728', '19191', '16050', '21086', '21069', '16056', '19192', '16062', '21222', '23061', '23059', '17729', '16053', '21077', '22977', '21223', '17730', '17893', '23069', '16041', '21342', '14391', '17799', '22660', '16049', '21036', '23060', '23072', '18613', '16055', '17800', '16054', '22708', '21078', '18066', '16052', '16051', '17742', '21178', '23073', '16043', '20858', '17801', '16786', '21083', '21085', '17731', '23055', '19193', '21081', '16058'}
[{'TeamNum': 19193, 'OPR': 121.588, 'Auto': 26.068, 'CCWM': 61.097, 'TeamName': 'SESI SENAI SC AgroTech'}, {'TeamNum': 21036, 'OPR': 108.361, 'Auto': 23.085, 'CCWM': 85.712, 'TeamName': 'JUSTICE FTC TEAM'}, {'TeamNum': 16786, 'OPR': 97.66, 'Auto': 20.934, 'CCWM': 69.177, 'TeamName': 'Cavalo Vendado'}, {'TeamNum': 20858, 'OPR': 91.433, 'Auto': 22.181, 'CCWM': 63.366, 'TeamName': 'Alpha Byte'}, {'TeamNum': 21077, 'OPR': 89.777, 'Auto': 20.987, 'CCWM': 50.822, 'TeamName': 'SESI SENAI FTBEN'}, {'TeamNum': 17728, 'OPR': 85.693, 'Auto': 21.431, 'CCWM': 33.601, 'TeamName': 'BrainMachine'}, {'TeamNum': 22977, 'OPR': 76.52, 'Auto': 15.174, 'CCWM': 41.904, 'TeamName': 'Dumonters '}, {'TeamNum': 17730, 'OPR': 76.227, 'Auto': 10.175, 'CCWM': 46.247, 'TeamName': "Tera Robotic's"}, {'TeamNum': 23055, 'OPR': 72.187, 'Auto': 17.358, 'CCWM': 46.128, 'TeamName': 'Tech Fenix'}, {'TeamNum': 22660, 'OPR': 70.283, 'Auto': 26.771, 'CCWM': 32.703, 'TeamName': 'Unity Sunset'}, {'TeamNum': 16043, 'OPR': 68.999, 'Auto': 19.119, 'CCWM': 24.521, 'TeamName': 'Robossauros'}, {'TeamNum': 19192, 'OPR': 68.21, 'Auto': 11.882, 'CCWM': 13.096, 'TeamName': 'SPARTAN'}, {'TeamNum': 16049, 'OPR': 67.907, 'Auto': 13.54, 'CCWM': -10.359, 'TeamName': 'SESI FTCAMB'}, {'TeamNum': 16055, 'OPR': 66.945, 'Auto': 9.269, 'CCWM': 50.007, 'TeamName': 'Starbots FTC'}, {'TeamNum': 23069, 'OPR': 64.786, 'Auto': 19.732, 'CCWM': 45.192, 'TeamName': 'SESI SENAI SC TECHMAKER CHALLENGE'}, {'TeamNum': 17800, 'OPR': 63.065, 'Auto': 14.652, 'CCWM': 8.938, 'TeamName': 'ParáTech'}, {'TeamNum': 23060, 'OPR': 61.985, 'Auto': 15.157, 'CCWM': 43.738, 'TeamName': 'EVEREST'}, {'TeamNum': 19188, 'OPR': 60.292, 'Auto': 3.555, 'CCWM': 42.889, 'TeamName': 'ANANINTECH'}, {'TeamNum': 17731, 'OPR': 57.493, 'Auto': 10.106, 'CCWM': 5.987, 'TeamName': 'LEGONAUTAS'}, {'TeamNum': 18613, 'OPR': 57.025, 'Auto': 15.797, 'CCWM': 52.487, 'TeamName': 'Sanja Storm'}, {'TeamNum': 14391, 'OPR': 56.728, 'Auto': 24.086, 'CCWM': 10.146, 'TeamName': 'Under Ctrl'}, {'TeamNum': 23061, 'OPR': 53.874, 'Auto': 0.507, 'CCWM': 7.394, 'TeamName': 'Ragnarök'}, {'TeamNum': 19191, 'OPR': 51.078, 'Auto': 9.659, 'CCWM': 17.473, 'TeamName': 'Destemidos'}, {'TeamNum': 21078, 'OPR': 46.183, 'Auto': 9.184, 'CCWM': 35.901, 'TeamName': 'Criadores'}, {'TeamNum': 21085, 'OPR': 45.707, 'Auto': 5.898, 'CCWM': -34.589, 'TeamName': 'SESI SENAI BRONTOBYTE FTC'}, {'TeamNum': 16058, 'OPR': 43.974, 'Auto': 7.004, 'CCWM': 12.831, 'TeamName': 'Rev Atom'}, {'TeamNum': 16041, 'OPR': 42.305, 'Auto': 1.772, 'CCWM': 6.548, 'TeamName': 'BAHTECH'}, {'TeamNum': 16052, 'OPR': 41.712, 'Auto': 17.499, 'CCWM': -6.453, 'TeamName': 'HYDRA'}, {'TeamNum': 17729, 'OPR': 40.279, 'Auto': 16.49, 'CCWM': -22.901, 'TeamName': 'TECH BROS'}, {'TeamNum': 23072, 'OPR': 40.187, 'Auto': 7.619, 'CCWM': -11.597, 'TeamName': "Raptors Robotic's"}, {'TeamNum': 17893, 'OPR': 38.03, 'Auto': 3.21, 'CCWM': -13.884, 'TeamName': 'CodeTech'}, {'TeamNum': 17801, 'OPR': 36.958, 'Auto': 13.836, 'CCWM': 27.577, 'TeamName': 'XMACHINE'}, {'TeamNum': 21084, 'OPR': 35.487, 'Auto': -4.098, 'CCWM': -12.941, 'TeamName': 'Nautilus Viasoft'}, {'TeamNum': 16053, 'OPR': 33.148, 'Auto': 13.344, 'CCWM': -16.492, 'TeamName': 'Clusters'}, {'TeamNum': 23059, 'OPR': 28.423, 'Auto': 2.272, 'CCWM': -46.825, 'TeamName': 'FALCONS'}, {'TeamNum': 21083, 'OPR': 27.917, 'Auto': 12.013, 'CCWM': -46.968, 'TeamName': 'BAZINGA! 73'}, {'TeamNum': 16050, 'OPR': 25.836, 'Auto': 2.517, 'CCWM': -37.267, 'TeamName': 'Team ProdiXy'}, {'TeamNum': 21342, 'OPR': 25.727, 'Auto': -1.528, 'CCWM': -31.058, 'TeamName': 'Lösungsjäger'}, {'TeamNum': 19194, 'OPR': 25.559, 'Auto': 2.228, 'CCWM': -54.735, 'TeamName': 'SESI SENAI SC Carvoeiros RoboTECH'}, {'TeamNum': 21223, 'OPR': 23.881, 'Auto': -2.502, 'CCWM': -39.712, 'TeamName': 'Acrônicos'}, {'TeamNum': 22374, 'OPR': 23.761, 'Auto': 1.252, 'CCWM': -27.953, 'TeamName': 'Highway Park Robotics'}, {'TeamNum': 16062, 'OPR': 22.707, 'Auto': -2.681, 'CCWM': -36.718, 'TeamName': 'TchêStorm'}, {'TeamNum': 21178, 'OPR': 18.608, 'Auto': 17.983, 'CCWM': -21.124, 'TeamName': 'Avenues Robotics'}, {'TeamNum': 22708, 'OPR': 18.416, 'Auto': 8.414, 'CCWM': -24.51, 'TeamName': 'TechZeus'}, {'TeamNum': 21069, 'OPR': 18.076, 'Auto': 1.41, 'CCWM': -27.49, 'TeamName': 'OUTPUT Jundiaí'}, {'TeamNum': 21081, 'OPR': 16.198, 'Auto': -0.65, 'CCWM': -27.922, 'TeamName': 'Asimov'}, {'TeamNum': 17742, 'OPR': 14.893, 'Auto': 6.939, 'CCWM': -54.97, 'TeamName': 'SESI TeCCactus'}, {'TeamNum': 21086, 'OPR': 14.835, 'Auto': 5.621, 'CCWM': -56.11, 'TeamName': "Alphadroid's"}, {'TeamNum': 21222, 'OPR': 14.032, 'Auto': 0.669, 'CCWM': -32.641, 'TeamName': 'EQUIPE QUIMERA'}, {'TeamNum': 18066, 'OPR': 11.141, 'Auto': 11.085, 'CCWM': -39.984, 'TeamName': 'BENDERMINDS'}, {'TeamNum': 16051, 'OPR': 10.917, 'Auto': 5.183, 'CCWM': -8.793, 'TeamName': 'Marco Zero Enterprise'}, {'TeamNum': 16054, 'OPR': 6.649, 'Auto': 4.368, 'CCWM': -56.778, 'TeamName': 'STORM TECH CANAÃ'}, {'TeamNum': 16056, 'OPR': 6.296, 'Auto': -2.961, 'CCWM': -17.833, 'TeamName': 'TupiTech'}, {'TeamNum': 17799, 'OPR': 5.731, 'Auto': -6.202, 'CCWM': -73.709, 'TeamName': 'Newgen Leaders'}, {'TeamNum': 23073, 'OPR': 0.797, 'Auto': -1.06, 'CCWM': -52.085, 'TeamName': "Mac Robot's - FTC"}]
BRCMP
[{'TeamNum': 19193, 'OPR': 121.588, 'Auto': 26.068, 'CCWM': 61.097, 'TeamName': 'SESI SENAI SC AgroTech'}, {'TeamNum': 21036, 'OPR': 108.361, 'Auto': 23.085, 'CCWM': 85.712, 'TeamName': 'JUSTICE FTC TEAM'}, {'TeamNum': 16786, 'OPR': 97.66, 'Auto': 20.934, 'CCWM': 69.177, 'TeamName': 'Cavalo Vendado'}, {'TeamNum': 20858, 'OPR': 91.433, 'Auto': 22.181, 'CCWM': 63.366, 'TeamName': 'Alpha Byte'}, {'TeamNum': 21077, 'OPR': 89.777, 'Auto': 20.987, 'CCWM': 50.822, 'TeamName': 'SESI SENAI FTBEN'}, {'TeamNum': 17728, 'OPR': 85.693, 'Auto': 21.431, 'CCWM': 33.601, 'TeamName': 'BrainMachine'}, {'TeamNum': 22977, 'OPR': 76.52, 'Auto': 15.174, 'CCWM': 41.904, 'TeamName': 'Dumonters '}, {'TeamNum': 17730, 'OPR': 76.227, 'Auto': 10.175, 'CCWM': 46.247, 'TeamName': "Tera Robotic's"}, {'TeamNum': 23055, 'OPR': 72.187, 'Auto': 17.358, 'CCWM': 46.128, 'TeamName': 'Tech Fenix'}, {'TeamNum': 22660, 'OPR': 70.283, 'Auto': 26.771, 'CCWM': 32.703, 'TeamName': 'Unity Sunset'}, {'TeamNum': 16043, 'OPR': 68.999, 'Auto': 19.119, 'CCWM': 24.521, 'TeamName': 'Robossauros'}, {'TeamNum': 19192, 'OPR': 68.21, 'Auto': 11.882, 'CCWM': 13.096, 'TeamName': 'SPARTAN'}, {'TeamNum': 16049, 'OPR': 67.907, 'Auto': 13.54, 'CCWM': -10.359, 'TeamName': 'SESI FTCAMB'}, {'TeamNum': 16055, 'OPR': 66.945, 'Auto': 9.269, 'CCWM': 50.007, 'TeamName': 'Starbots FTC'}, {'TeamNum': 23069, 'OPR': 64.786, 'Auto': 19.732, 'CCWM': 45.192, 'TeamName': 'SESI SENAI SC TECHMAKER CHALLENGE'}, {'TeamNum': 17800, 'OPR': 63.065, 'Auto': 14.652, 'CCWM': 8.938, 'TeamName': 'ParáTech'}, {'TeamNum': 23060, 'OPR': 61.985, 'Auto': 15.157, 'CCWM': 43.738, 'TeamName': 'EVEREST'}, {'TeamNum': 19188, 'OPR': 60.292, 'Auto': 3.555, 'CCWM': 42.889, 'TeamName': 'ANANINTECH'}, {'TeamNum': 17731, 'OPR': 57.493, 'Auto': 10.106, 'CCWM': 5.987, 'TeamName': 'LEGONAUTAS'}, {'TeamNum': 18613, 'OPR': 57.025, 'Auto': 15.797, 'CCWM': 52.487, 'TeamName': 'Sanja Storm'}, {'TeamNum': 14391, 'OPR': 56.728, 'Auto': 24.086, 'CCWM': 10.146, 'TeamName': 'Under Ctrl'}, {'TeamNum': 23061, 'OPR': 53.874, 'Auto': 0.507, 'CCWM': 7.394, 'TeamName': 'Ragnarök'}, {'TeamNum': 19191, 'OPR': 51.078, 'Auto': 9.659, 'CCWM': 17.473, 'TeamName': 'Destemidos'}, {'TeamNum': 21078, 'OPR': 46.183, 'Auto': 9.184, 'CCWM': 35.901, 'TeamName': 'Criadores'}, {'TeamNum': 21085, 'OPR': 45.707, 'Auto': 5.898, 'CCWM': -34.589, 'TeamName': 'SESI SENAI BRONTOBYTE FTC'}, {'TeamNum': 16058, 'OPR': 43.974, 'Auto': 7.004, 'CCWM': 12.831, 'TeamName': 'Rev Atom'}, {'TeamNum': 16041, 'OPR': 42.305, 'Auto': 1.772, 'CCWM': 6.548, 'TeamName': 'BAHTECH'}, {'TeamNum': 16052, 'OPR': 41.712, 'Auto': 17.499, 'CCWM': -6.453, 'TeamName': 'HYDRA'}, {'TeamNum': 17729, 'OPR': 40.279, 'Auto': 16.49, 'CCWM': -22.901, 'TeamName': 'TECH BROS'}, {'TeamNum': 23072, 'OPR': 40.187, 'Auto': 7.619, 'CCWM': -11.597, 'TeamName': "Raptors Robotic's"}, {'TeamNum': 17893, 'OPR': 38.03, 'Auto': 3.21, 'CCWM': -13.884, 'TeamName': 'CodeTech'}, {'TeamNum': 17801, 'OPR': 36.958, 'Auto': 13.836, 'CCWM': 27.577, 'TeamName': 'XMACHINE'}, {'TeamNum': 21084, 'OPR': 35.487, 'Auto': -4.098, 'CCWM': -12.941, 'TeamName': 'Nautilus Viasoft'}, {'TeamNum': 16053, 'OPR': 33.148, 'Auto': 13.344, 'CCWM': -16.492, 'TeamName': 'Clusters'}, {'TeamNum': 23059, 'OPR': 28.423, 'Auto': 2.272, 'CCWM': -46.825, 'TeamName': 'FALCONS'}, {'TeamNum': 21083, 'OPR': 27.917, 'Auto': 12.013, 'CCWM': -46.968, 'TeamName': 'BAZINGA! 73'}, {'TeamNum': 16050, 'OPR': 25.836, 'Auto': 2.517, 'CCWM': -37.267, 'TeamName': 'Team ProdiXy'}, {'TeamNum': 21342, 'OPR': 25.727, 'Auto': -1.528, 'CCWM': -31.058, 'TeamName': 'Lösungsjäger'}, {'TeamNum': 19194, 'OPR': 25.559, 'Auto': 2.228, 'CCWM': -54.735, 'TeamName': 'SESI SENAI SC Carvoeiros RoboTECH'}, {'TeamNum': 21223, 'OPR': 23.881, 'Auto': -2.502, 'CCWM': -39.712, 'TeamName': 'Acrônicos'}, {'TeamNum': 22374, 'OPR': 23.761, 'Auto': 1.252, 'CCWM': -27.953, 'TeamName': 'Highway Park Robotics'}, {'TeamNum': 16062, 'OPR': 22.707, 'Auto': -2.681, 'CCWM': -36.718, 'TeamName': 'TchêStorm'}, {'TeamNum': 21178, 'OPR': 18.608, 'Auto': 17.983, 'CCWM': -21.124, 'TeamName': 'Avenues Robotics'}, {'TeamNum': 22708, 'OPR': 18.416, 'Auto': 8.414, 'CCWM': -24.51, 'TeamName': 'TechZeus'}, {'TeamNum': 21069, 'OPR': 18.076, 'Auto': 1.41, 'CCWM': -27.49, 'TeamName': 'OUTPUT Jundiaí'}, {'TeamNum': 21081, 'OPR': 16.198, 'Auto': -0.65, 'CCWM': -27.922, 'TeamName': 'Asimov'}, {'TeamNum': 17742, 'OPR': 14.893, 'Auto': 6.939, 'CCWM': -54.97, 'TeamName': 'SESI TeCCactus'}, {'TeamNum': 21086, 'OPR': 14.835, 'Auto': 5.621, 'CCWM': -56.11, 'TeamName': "Alphadroid's"}, {'TeamNum': 21222, 'OPR': 14.032, 'Auto': 0.669, 'CCWM': -32.641, 'TeamName': 'EQUIPE QUIMERA'}, {'TeamNum': 18066, 'OPR': 11.141, 'Auto': 11.085, 'CCWM': -39.984, 'TeamName': 'BENDERMINDS'}, {'TeamNum': 16051, 'OPR': 10.917, 'Auto': 5.183, 'CCWM': -8.793, 'TeamName': 'Marco Zero Enterprise'}, {'TeamNum': 16054, 'OPR': 6.649, 'Auto': 4.368, 'CCWM': -56.778, 'TeamName': 'STORM TECH CANAÃ'}, {'TeamNum': 16056, 'OPR': 6.296, 'Auto': -2.961, 'CCWM': -17.833, 'TeamName': 'TupiTech'}, {'TeamNum': 17799, 'OPR': 5.731, 'Auto': -6.202, 'CCWM': -73.709, 'TeamName': 'Newgen Leaders'}, {'TeamNum': 23073, 'OPR': 0.797, 'Auto': -1.06, 'CCWM': -52.085, 'TeamName': "Mac Robot's - FTC"}]

i 1127
i 1128
i 1129
{'20999', '21003', '19282', '21207', '19279', '21187', '19284', '22640', '20994', '21206', '20997', '22456', '22877', '21200', '21186', '22457', '21199', '23053', '20998', '21122', '21009', '21002', '19280', '20992'}
[{'TeamNum': 19280, 'OPR': 50.475, 'Auto': 5.325, 'CCWM': 32.68, 'TeamName': 'UK 235 - Blackout Robotics '}, {'TeamNum': 22640, 'OPR': 40.402, 'Auto': 10.258, 'CCWM': 33.156, 'TeamName': 'UK 465 - Harrow School - Team Euclid'}, {'TeamNum': 21207, 'OPR': 27.632, 'Auto': -1.433, 'CCWM': 12.112, 'TeamName': 'TEAM 425'}, {'TeamNum': 20997, 'OPR': 21.372, 'Auto': 5.251, 'CCWM': 8.946, 'TeamName': 'fernDOWNLOAD#166'}, {'TeamNum': 19284, 'OPR': 20.364, 'Auto': 2.59, 'CCWM': 3.112, 'TeamName': 'UK 248 - ASL Team 5 - MS ASP G8'}, {'TeamNum': 20994, 'OPR': 20.194, 'Auto': 1.057, 'CCWM': -12.486, 'TeamName': 'fernDOWNLOAD#85'}, {'TeamNum': 22457, 'OPR': 16.456, 'Auto': 13.549, 'CCWM': 0.865, 'TeamName': 'UK 456 - BSG - BSGRobotics'}, {'TeamNum': 20999, 'OPR': 16.004, 'Auto': 6.537, 'CCWM': 10.971, 'TeamName': 'fernDOWNLOAD#240'}, {'TeamNum': 21206, 'OPR': 15.938, 'Auto': -0.577, 'CCWM': 1.275, 'TeamName': 'TEAM 183'}, {'TeamNum': 22456, 'OPR': 15.467, 'Auto': 1.058, 'CCWM': 7.246, 'TeamName': 'UK 447 - BSG - BSGRobotics'}, {'TeamNum': 23053, 'OPR': 15.116, 'Auto': 8.892, 'CCWM': 8.311, 'TeamName': 'UK272'}, {'TeamNum': 21009, 'OPR': 13.39, 'Auto': -1.358, 'CCWM': -6.786, 'TeamName': 'UK 337 HCACP Harris Atoms'}, {'TeamNum': 19279, 'OPR': 12.996, 'Auto': 2.103, 'CCWM': 5.177, 'TeamName': 'UK 184 - UniBorgs'}, {'TeamNum': 19282, 'OPR': 11.686, 'Auto': -3.128, 'CCWM': -5.912, 'TeamName': 'UK 247 - ASL Team 4 - MS ASP G8'}, {'TeamNum': 21002, 'OPR': 7.281, 'Auto': 3.159, 'CCWM': -10.742, 'TeamName': 'UK 249 - ASL Team 6 - HS Robotics Class 1'}, {'TeamNum': 21199, 'OPR': 7.019, 'Auto': -0.686, 'CCWM': -19.002, 'TeamName': "UK116 - St Philomena's - Omega"}, {'TeamNum': 20998, 'OPR': 6.108, 'Auto': -0.119, 'CCWM': 9.146, 'TeamName': 'fernDOWNLOAD#239'}, {'TeamNum': 22877, 'OPR': 5.893, 'Auto': 4.917, 'CCWM': -0.019, 'TeamName': 'UK 149-The Petchey Academy-Petchey Robotics'}, {'TeamNum': 21200, 'OPR': 5.761, 'Auto': -0.193, 'CCWM': -6.827, 'TeamName': 'UK179 - Alpha'}, {'TeamNum': 21186, 'OPR': 4.213, 'Auto': -0.122, 'CCWM': -10.131, 'TeamName': '110 Delphinus 21186'}, {'TeamNum': 21187, 'OPR': 1.803, 'Auto': 1.154, 'CCWM': -10.276, 'TeamName': '426 Equuleus 21187'}, {'TeamNum': 20992, 'OPR': 1.023, 'Auto': -5.188, 'CCWM': -17.773, 'TeamName': 'Berkeley Robotics'}, {'TeamNum': 21003, 'OPR': -1.57, 'Auto': -2.284, 'CCWM': -17.963, 'TeamName': 'UK 250 - ASL Team 7 - HS Robotics Class 2'}, {'TeamNum': 21122, 'OPR': -3.425, 'Auto': -5.562, 'CCWM': -15.081, 'TeamName': 'UK097'}]
GBLOQ
[{'TeamNum': 19280, 'OPR': 50.475, 'Auto': 5.325, 'CCWM': 32.68, 'TeamName': 'UK 235 - Blackout Robotics '}, {'TeamNum': 22640, 'OPR': 40.402, 'Auto': 10.258, 'CCWM': 33.156, 'TeamName': 'UK 465 - Harrow School - Team Euclid'}, {'TeamNum': 21207, 'OPR': 27.632, 'Auto': -1.433, 'CCWM': 12.112, 'TeamName': 'TEAM 425'}, {'TeamNum': 20997, 'OPR': 21.372, 'Auto': 5.251, 'CCWM': 8.946, 'TeamName': 'fernDOWNLOAD#166'}, {'TeamNum': 19284, 'OPR': 20.364, 'Auto': 2.59, 'CCWM': 3.112, 'TeamName': 'UK 248 - ASL Team 5 - MS ASP G8'}, {'TeamNum': 20994, 'OPR': 20.194, 'Auto': 1.057, 'CCWM': -12.486, 'TeamName': 'fernDOWNLOAD#85'}, {'TeamNum': 22457, 'OPR': 16.456, 'Auto': 13.549, 'CCWM': 0.865, 'TeamName': 'UK 456 - BSG - BSGRobotics'}, {'TeamNum': 20999, 'OPR': 16.004, 'Auto': 6.537, 'CCWM': 10.971, 'TeamName': 'fernDOWNLOAD#240'}, {'TeamNum': 21206, 'OPR': 15.938, 'Auto': -0.577, 'CCWM': 1.275, 'TeamName': 'TEAM 183'}, {'TeamNum': 22456, 'OPR': 15.467, 'Auto': 1.058, 'CCWM': 7.246, 'TeamName': 'UK 447 - BSG - BSGRobotics'}, {'TeamNum': 23053, 'OPR': 15.116, 'Auto': 8.892, 'CCWM': 8.311, 'TeamName': 'UK272'}, {'TeamNum': 21009, 'OPR': 13.39, 'Auto': -1.358, 'CCWM': -6.786, 'TeamName': 'UK 337 HCACP Harris Atoms'}, {'TeamNum': 19279, 'OPR': 12.996, 'Auto': 2.103, 'CCWM': 5.177, 'TeamName': 'UK 184 - UniBorgs'}, {'TeamNum': 19282, 'OPR': 11.686, 'Auto': -3.128, 'CCWM': -5.912, 'TeamName': 'UK 247 - ASL Team 4 - MS ASP G8'}, {'TeamNum': 21002, 'OPR': 7.281, 'Auto': 3.159, 'CCWM': -10.742, 'TeamName': 'UK 249 - ASL Team 6 - HS Robotics Class 1'}, {'TeamNum': 21199, 'OPR': 7.019, 'Auto': -0.686, 'CCWM': -19.002, 'TeamName': "UK116 - St Philomena's - Omega"}, {'TeamNum': 20998, 'OPR': 6.108, 'Auto': -0.119, 'CCWM': 9.146, 'TeamName': 'fernDOWNLOAD#239'}, {'TeamNum': 22877, 'OPR': 5.893, 'Auto': 4.917, 'CCWM': -0.019, 'TeamName': 'UK 149-The Petchey Academy-Petchey Robotics'}, {'TeamNum': 21200, 'OPR': 5.761, 'Auto': -0.193, 'CCWM': -6.827, 'TeamName': 'UK179 - Alpha'}, {'TeamNum': 21186, 'OPR': 4.213, 'Auto': -0.122, 'CCWM': -10.131, 'TeamName': '110 Delphinus 21186'}, {'TeamNum': 21187, 'OPR': 1.803, 'Auto': 1.154, 'CCWM': -10.276, 'TeamName': '426 Equuleus 21187'}, {'TeamNum': 20992, 'OPR': 1.023, 'Auto': -5.188, 'CCWM': -17.773, 'TeamName': 'Berkeley Robotics'}, {'TeamNum': 21003, 'OPR': -1.57, 'Auto': -2.284, 'CCWM': -17.963, 'TeamName': 'UK 250 - ASL Team 7 - HS Robotics Class 2'}, {'TeamNum': 21122, 'OPR': -3.425, 'Auto': -5.562, 'CCWM': -15.081, 'TeamName': 'UK097'}]
i 1130
{'21119', '19270', '20995', '21013', '21203', '18889', '21011', '21135', '21014', '20981', '19259', '22663', '21202', '21008', '21012', '22486', '19265', '20982', '21126', '21212', '23104', '20993', '21182', '19269'}
[{'TeamNum': 20993, 'OPR': 36.237, 'Auto': 11.041, 'CCWM': 17.3, 'TeamName': 'UK 090 - Outwood Academy Newbold - GroundX'}, {'TeamNum': 21203, 'OPR': 28.841, 'Auto': 14.364, 'CCWM': 2.708, 'TeamName': '108 Oldfields'}, {'TeamNum': 18889, 'OPR': 26.884, 'Auto': -1.51, 'CCWM': 21.578, 'TeamName': 'UK O63 - Perton Middle School - Team Snap Wire'}, {'TeamNum': 22663, 'OPR': 25.255, 'Auto': 2.362, 'CCWM': -0.104, 'TeamName': 'UK 041 - SMWCA - VNATION'}, {'TeamNum': 20981, 'OPR': 24.836, 'Auto': -1.023, 'CCWM': -0.901, 'TeamName': 'UK 035 - St John Fisher - Circuit Breakers Vol2'}, {'TeamNum': 20982, 'OPR': 24.569, 'Auto': 10.938, 'CCWM': 16.071, 'TeamName': 'UK 032 - St John Fisher - Hotwire rewired'}, {'TeamNum': 21011, 'OPR': 24.071, 'Auto': 1.433, 'CCWM': -3.068, 'TeamName': 'UK 126 - AUEA - Bostin Dynamics'}, {'TeamNum': 22486, 'OPR': 19.998, 'Auto': 6.595, 'CCWM': 1.132, 'TeamName': 'Denstone College'}, {'TeamNum': 19269, 'OPR': 19.256, 'Auto': -1.035, 'CCWM': 6.818, 'TeamName': 'UK 105 - Bishop Perowne'}, {'TeamNum': 20995, 'OPR': 17.432, 'Auto': 0.567, 'CCWM': 11.792, 'TeamName': 'UK 373 - Egglescliffe School - Vision Robotics'}, {'TeamNum': 19270, 'OPR': 17.317, 'Auto': -1.087, 'CCWM': 1.407, 'TeamName': 'Calderstones'}, {'TeamNum': 21008, 'OPR': 16.266, 'Auto': -1.7, 'CCWM': 3.37, 'TeamName': 'The Observatory School 1'}, {'TeamNum': 21212, 'OPR': 13.091, 'Auto': 1.544, 'CCWM': 10.737, 'TeamName': 'Alpha'}, {'TeamNum': 23104, 'OPR': 11.544, 'Auto': 4.477, 'CCWM': -0.035, 'TeamName': 'Team Wobot'}, {'TeamNum': 21135, 'OPR': 11.182, 'Auto': -2.297, 'CCWM': 7.301, 'TeamName': 'Newbotics 101 UK 007'}, {'TeamNum': 21126, 'OPR': 9.64, 'Auto': 0.043, 'CCWM': -11.633, 'TeamName': 'UK 164 Holmfirth High School'}, {'TeamNum': 21012, 'OPR': 8.038, 'Auto': 3.333, 'CCWM': -4.495, 'TeamName': 'UK 011-Woodhouse Academy-The Lupus Legends'}, {'TeamNum': 21119, 'OPR': 6.743, 'Auto': 1.89, 'CCWM': -6.907, 'TeamName': 'UK 029-Aldersley High School- Sustainable Danger '}, {'TeamNum': 21182, 'OPR': 5.184, 'Auto': -1.061, 'CCWM': -22.992, 'TeamName': 'UK 158 - Newcastle-under-Lyme School - NULBOT '}, {'TeamNum': 21202, 'OPR': 3.059, 'Auto': 0.813, 'CCWM': 3.733, 'TeamName': ': UK 069 - Biddulph High School - Team Name TBC'}, {'TeamNum': 19265, 'OPR': 2.831, 'Auto': -1.666, 'CCWM': -20.783, 'TeamName': 'UK OOO - Organisation - Team Name'}, {'TeamNum': 21014, 'OPR': 0.802, 'Auto': 1.39, 'CCWM': -6.778, 'TeamName': 'UK 009-Woodhouse Academy-Sleepy Sloths'}, {'TeamNum': 19259, 'OPR': -3.403, 'Auto': -1.415, 'CCWM': -3.701, 'TeamName': 'UK OOO - Organisation - Team Name'}, {'TeamNum': 21013, 'OPR': -9.071, 'Auto': -0.195, 'CCWM': -22.548, 'TeamName': 'UK 010-Woodhouse Academy-The Gampoko Squad'}]
GBCOQ
[{'TeamNum': 20993, 'OPR': 36.237, 'Auto': 11.041, 'CCWM': 17.3, 'TeamName': 'UK 090 - Outwood Academy Newbold - GroundX'}, {'TeamNum': 21203, 'OPR': 28.841, 'Auto': 14.364, 'CCWM': 2.708, 'TeamName': '108 Oldfields'}, {'TeamNum': 18889, 'OPR': 26.884, 'Auto': -1.51, 'CCWM': 21.578, 'TeamName': 'UK O63 - Perton Middle School - Team Snap Wire'}, {'TeamNum': 22663, 'OPR': 25.255, 'Auto': 2.362, 'CCWM': -0.104, 'TeamName': 'UK 041 - SMWCA - VNATION'}, {'TeamNum': 20981, 'OPR': 24.836, 'Auto': -1.023, 'CCWM': -0.901, 'TeamName': 'UK 035 - St John Fisher - Circuit Breakers Vol2'}, {'TeamNum': 20982, 'OPR': 24.569, 'Auto': 10.938, 'CCWM': 16.071, 'TeamName': 'UK 032 - St John Fisher - Hotwire rewired'}, {'TeamNum': 21011, 'OPR': 24.071, 'Auto': 1.433, 'CCWM': -3.068, 'TeamName': 'UK 126 - AUEA - Bostin Dynamics'}, {'TeamNum': 22486, 'OPR': 19.998, 'Auto': 6.595, 'CCWM': 1.132, 'TeamName': 'Denstone College'}, {'TeamNum': 19269, 'OPR': 19.256, 'Auto': -1.035, 'CCWM': 6.818, 'TeamName': 'UK 105 - Bishop Perowne'}, {'TeamNum': 20995, 'OPR': 17.432, 'Auto': 0.567, 'CCWM': 11.792, 'TeamName': 'UK 373 - Egglescliffe School - Vision Robotics'}, {'TeamNum': 19270, 'OPR': 17.317, 'Auto': -1.087, 'CCWM': 1.407, 'TeamName': 'Calderstones'}, {'TeamNum': 21008, 'OPR': 16.266, 'Auto': -1.7, 'CCWM': 3.37, 'TeamName': 'The Observatory School 1'}, {'TeamNum': 21212, 'OPR': 13.091, 'Auto': 1.544, 'CCWM': 10.737, 'TeamName': 'Alpha'}, {'TeamNum': 23104, 'OPR': 11.544, 'Auto': 4.477, 'CCWM': -0.035, 'TeamName': 'Team Wobot'}, {'TeamNum': 21135, 'OPR': 11.182, 'Auto': -2.297, 'CCWM': 7.301, 'TeamName': 'Newbotics 101 UK 007'}, {'TeamNum': 21126, 'OPR': 9.64, 'Auto': 0.043, 'CCWM': -11.633, 'TeamName': 'UK 164 Holmfirth High School'}, {'TeamNum': 21012, 'OPR': 8.038, 'Auto': 3.333, 'CCWM': -4.495, 'TeamName': 'UK 011-Woodhouse Academy-The Lupus Legends'}, {'TeamNum': 21119, 'OPR': 6.743, 'Auto': 1.89, 'CCWM': -6.907, 'TeamName': 'UK 029-Aldersley High School- Sustainable Danger '}, {'TeamNum': 21182, 'OPR': 5.184, 'Auto': -1.061, 'CCWM': -22.992, 'TeamName': 'UK 158 - Newcastle-under-Lyme School - NULBOT '}, {'TeamNum': 21202, 'OPR': 3.059, 'Auto': 0.813, 'CCWM': 3.733, 'TeamName': ': UK 069 - Biddulph High School - Team Name TBC'}, {'TeamNum': 19265, 'OPR': 2.831, 'Auto': -1.666, 'CCWM': -20.783, 'TeamName': 'UK OOO - Organisation - Team Name'}, {'TeamNum': 21014, 'OPR': 0.802, 'Auto': 1.39, 'CCWM': -6.778, 'TeamName': 'UK 009-Woodhouse Academy-Sleepy Sloths'}, {'TeamNum': 19259, 'OPR': -3.403, 'Auto': -1.415, 'CCWM': -3.701, 'TeamName': 'UK OOO - Organisation - Team Name'}, {'TeamNum': 21013, 'OPR': -9.071, 'Auto': -0.195, 'CCWM': -22.548, 'TeamName': 'UK 010-Woodhouse Academy-The Gampoko Squad'}]
i 1131

i 1132
{'10528', '11986', '21856', '10862', '11720', '12115', '15930', '15546', '10405', '16617', '20410', '13109', '10676', '16215', '12398', '18483', '5175', '16756', '13472', '15877', '9778', '18458', '21899', '21733'}
[{'TeamNum': 15546, 'OPR': 125.897, 'Auto': 27.462, 'CCWM': 78.305, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 10862, 'OPR': 113.068, 'Auto': 35.827, 'CCWM': 45.643, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 16617, 'OPR': 103.108, 'Auto': 24.149, 'CCWM': 26.647, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 12398, 'OPR': 101.565, 'Auto': 13.142, 'CCWM': 58.272, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 18483, 'OPR': 97.502, 'Auto': 23.283, 'CCWM': 38.018, 'TeamName': 'Buckar00s'}, {'TeamNum': 21733, 'OPR': 97.349, 'Auto': 18.42, 'CCWM': 35.315, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 18458, 'OPR': 87.908, 'Auto': 16.333, 'CCWM': 17.964, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 11986, 'OPR': 83.98, 'Auto': 13.535, 'CCWM': 20.499, 'TeamName': 'Code Blue'}, {'TeamNum': 21856, 'OPR': 83.177, 'Auto': 30.238, 'CCWM': -12.568, 'TeamName': 'J-Bots'}, {'TeamNum': 12115, 'OPR': 68.03, 'Auto': 16.187, 'CCWM': 2.262, 'TeamName': 'Phoen-X'}, {'TeamNum': 15877, 'OPR': 63.097, 'Auto': 13.271, 'CCWM': 22.384, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 16756, 'OPR': 62.895, 'Auto': 18.056, 'CCWM': -30.531, 'TeamName': 'Raider Prime'}, {'TeamNum': 10528, 'OPR': 62.253, 'Auto': 2.671, 'CCWM': 0.325, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 20410, 'OPR': 61.372, 'Auto': 7.334, 'CCWM': -12.525, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 21899, 'OPR': 61.092, 'Auto': 4.143, 'CCWM': 3.571, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 13109, 'OPR': 58.886, 'Auto': 11.978, 'CCWM': -0.16, 'TeamName': 'Team Koopa'}, {'TeamNum': 15930, 'OPR': 56.316, 'Auto': 13.968, 'CCWM': -26.166, 'TeamName': 'Pirates'}, {'TeamNum': 16215, 'OPR': 53.846, 'Auto': 7.928, 'CCWM': -29.933, 'TeamName': 'Mystery Machine'}, {'TeamNum': 11720, 'OPR': 53.553, 'Auto': 16.282, 'CCWM': -37.515, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 10405, 'OPR': 52.29, 'Auto': 14.187, 'CCWM': -24.395, 'TeamName': 'RoboKnights'}, {'TeamNum': 10676, 'OPR': 35.991, 'Auto': 0.653, 'CCWM': -25.792, 'TeamName': 'Lady Warbots'}, {'TeamNum': 13472, 'OPR': 34.376, 'Auto': 10.651, 'CCWM': -66.044, 'TeamName': 'The Dork Side'}, {'TeamNum': 5175, 'OPR': 27.51, 'Auto': 8.643, 'CCWM': -35.32, 'TeamName': 'Vector Robotics'}, {'TeamNum': 9778, 'OPR': 23.937, 'Auto': 2.493, 'CCWM': -48.257, 'TeamName': 'Robotic Chinchillas'}]
USTXSOCMP
[{'TeamNum': 15546, 'OPR': 125.897, 'Auto': 27.462, 'CCWM': 78.305, 'TeamName': 'Monkey Mechanics'}, {'TeamNum': 10862, 'OPR': 113.068, 'Auto': 35.827, 'CCWM': 45.643, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 16617, 'OPR': 103.108, 'Auto': 24.149, 'CCWM': 26.647, 'TeamName': 'Nazareth Robotics'}, {'TeamNum': 12398, 'OPR': 101.565, 'Auto': 13.142, 'CCWM': 58.272, 'TeamName': 'Bobcat Robotics'}, {'TeamNum': 18483, 'OPR': 97.502, 'Auto': 23.283, 'CCWM': 38.018, 'TeamName': 'Buckar00s'}, {'TeamNum': 21733, 'OPR': 97.349, 'Auto': 18.42, 'CCWM': 35.315, 'TeamName': 'Kryptic Knights'}, {'TeamNum': 18458, 'OPR': 87.908, 'Auto': 16.333, 'CCWM': 17.964, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 11986, 'OPR': 83.98, 'Auto': 13.535, 'CCWM': 20.499, 'TeamName': 'Code Blue'}, {'TeamNum': 21856, 'OPR': 83.177, 'Auto': 30.238, 'CCWM': -12.568, 'TeamName': 'J-Bots'}, {'TeamNum': 12115, 'OPR': 68.03, 'Auto': 16.187, 'CCWM': 2.262, 'TeamName': 'Phoen-X'}, {'TeamNum': 15877, 'OPR': 63.097, 'Auto': 13.271, 'CCWM': 22.384, 'TeamName': 'Callisburg  Robocats'}, {'TeamNum': 16756, 'OPR': 62.895, 'Auto': 18.056, 'CCWM': -30.531, 'TeamName': 'Raider Prime'}, {'TeamNum': 10528, 'OPR': 62.253, 'Auto': 2.671, 'CCWM': 0.325, 'TeamName': 'BOTS IN BLACK'}, {'TeamNum': 20410, 'OPR': 61.372, 'Auto': 7.334, 'CCWM': -12.525, 'TeamName': 'Newman Gibbins'}, {'TeamNum': 21899, 'OPR': 61.092, 'Auto': 4.143, 'CCWM': 3.571, 'TeamName': 'Hico Tiger Robotics'}, {'TeamNum': 13109, 'OPR': 58.886, 'Auto': 11.978, 'CCWM': -0.16, 'TeamName': 'Team Koopa'}, {'TeamNum': 15930, 'OPR': 56.316, 'Auto': 13.968, 'CCWM': -26.166, 'TeamName': 'Pirates'}, {'TeamNum': 16215, 'OPR': 53.846, 'Auto': 7.928, 'CCWM': -29.933, 'TeamName': 'Mystery Machine'}, {'TeamNum': 11720, 'OPR': 53.553, 'Auto': 16.282, 'CCWM': -37.515, 'TeamName': 'PUROBOTS - 11720'}, {'TeamNum': 10405, 'OPR': 52.29, 'Auto': 14.187, 'CCWM': -24.395, 'TeamName': 'RoboKnights'}, {'TeamNum': 10676, 'OPR': 35.991, 'Auto': 0.653, 'CCWM': -25.792, 'TeamName': 'Lady Warbots'}, {'TeamNum': 13472, 'OPR': 34.376, 'Auto': 10.651, 'CCWM': -66.044, 'TeamName': 'The Dork Side'}, {'TeamNum': 5175, 'OPR': 27.51, 'Auto': 8.643, 'CCWM': -35.32, 'TeamName': 'Vector Robotics'}, {'TeamNum': 9778, 'OPR': 23.937, 'Auto': 2.493, 'CCWM': -48.257, 'TeamName': 'Robotic Chinchillas'}]
i 1133
{'5628', '12978', '16911', '13108', '19990', '9527', '12927', '4906', '14523', '16816', '5470', '12791', '15251', '16412', '16311', '4885', '8204', '21338', '19897', '12926', '12313', '17113', '4707'}
[{'TeamNum': 4707, 'OPR': 141.829, 'Auto': 49.354, 'CCWM': 96.837, 'TeamName': 'Midway Predators'}, {'TeamNum': 16911, 'OPR': 116.064, 'Auto': 37.404, 'CCWM': 41.158, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 19897, 'OPR': 110.353, 'Auto': 19.118, 'CCWM': 39.483, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 9527, 'OPR': 107.834, 'Auto': 39.312, 'CCWM': 56.797, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 16311, 'OPR': 102.438, 'Auto': 11.336, 'CCWM': 16.786, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 5470, 'OPR': 97.113, 'Auto': 17.374, 'CCWM': 13.675, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 12791, 'OPR': 96.162, 'Auto': 27.268, 'CCWM': -11.088, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 14523, 'OPR': 85.607, 'Auto': 21.763, 'CCWM': -1.714, 'TeamName': 'Free of Charge'}, {'TeamNum': 16412, 'OPR': 81.765, 'Auto': 20.176, 'CCWM': 29.825, 'TeamName': 'Triad Robotics'}, {'TeamNum': 13108, 'OPR': 75.739, 'Auto': 21.36, 'CCWM': -16.59, 'TeamName': 'Encrypted'}, {'TeamNum': 5628, 'OPR': 73.855, 'Auto': 3.053, 'CCWM': 16.78, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 8204, 'OPR': 65.013, 'Auto': 22.647, 'CCWM': -13.943, 'TeamName': 'Blue Machine'}, {'TeamNum': 4885, 'OPR': 63.289, 'Auto': 17.294, 'CCWM': -16.317, 'TeamName': 'OmegaBotz'}, {'TeamNum': 16816, 'OPR': 60.648, 'Auto': 18.705, 'CCWM': 6.337, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 12927, 'OPR': 58.255, 'Auto': 19.579, 'CCWM': 18.473, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 19990, 'OPR': 58.005, 'Auto': 16.468, 'CCWM': -30.197, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 12978, 'OPR': 55.193, 'Auto': 8.712, 'CCWM': -12.199, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 4906, 'OPR': 54.083, 'Auto': 7.587, 'CCWM': -14.944, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 17113, 'OPR': 47.134, 'Auto': 12.339, 'CCWM': -23.348, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 12313, 'OPR': 37.102, 'Auto': 12.233, 'CCWM': -36.561, 'TeamName': 'Hotdawgs'}, {'TeamNum': 12926, 'OPR': 23.985, 'Auto': 5.715, 'CCWM': -37.35, 'TeamName': 'Panther Robotics'}, {'TeamNum': 21338, 'OPR': 20.595, 'Auto': -2.737, 'CCWM': -72.611, 'TeamName': 'Innovators'}, {'TeamNum': 15251, 'OPR': 17.153, 'Auto': -0.997, 'CCWM': -49.366, 'TeamName': 'Hadron Mission Eagle'}]
USTXSOBES
[{'TeamNum': 4707, 'OPR': 141.829, 'Auto': 49.354, 'CCWM': 96.837, 'TeamName': 'Midway Predators'}, {'TeamNum': 16911, 'OPR': 116.064, 'Auto': 37.404, 'CCWM': 41.158, 'TeamName': 'Rigatoni Pastabots'}, {'TeamNum': 19897, 'OPR': 110.353, 'Auto': 19.118, 'CCWM': 39.483, 'TeamName': 'Jasper Jaguar Robotics White'}, {'TeamNum': 9527, 'OPR': 107.834, 'Auto': 39.312, 'CCWM': 56.797, 'TeamName': 'Rogue Resistance'}, {'TeamNum': 16311, 'OPR': 102.438, 'Auto': 11.336, 'CCWM': 16.786, 'TeamName': 'ViperBots Recoil'}, {'TeamNum': 5470, 'OPR': 97.113, 'Auto': 17.374, 'CCWM': 13.675, 'TeamName': 'Montwood Rambotics'}, {'TeamNum': 12791, 'OPR': 96.162, 'Auto': 27.268, 'CCWM': -11.088, 'TeamName': 'Iterative Intentions'}, {'TeamNum': 14523, 'OPR': 85.607, 'Auto': 21.763, 'CCWM': -1.714, 'TeamName': 'Free of Charge'}, {'TeamNum': 16412, 'OPR': 81.765, 'Auto': 20.176, 'CCWM': 29.825, 'TeamName': 'Triad Robotics'}, {'TeamNum': 13108, 'OPR': 75.739, 'Auto': 21.36, 'CCWM': -16.59, 'TeamName': 'Encrypted'}, {'TeamNum': 5628, 'OPR': 73.855, 'Auto': 3.053, 'CCWM': 16.78, 'TeamName': 'The Tau Manifesto'}, {'TeamNum': 8204, 'OPR': 65.013, 'Auto': 22.647, 'CCWM': -13.943, 'TeamName': 'Blue Machine'}, {'TeamNum': 4885, 'OPR': 63.289, 'Auto': 17.294, 'CCWM': -16.317, 'TeamName': 'OmegaBotz'}, {'TeamNum': 16816, 'OPR': 60.648, 'Auto': 18.705, 'CCWM': 6.337, 'TeamName': 'IOKNIGHT'}, {'TeamNum': 12927, 'OPR': 58.255, 'Auto': 19.579, 'CCWM': 18.473, 'TeamName': 'Shepton High Stallioneers'}, {'TeamNum': 19990, 'OPR': 58.005, 'Auto': 16.468, 'CCWM': -30.197, 'TeamName': 'Marcus de-TECH-tives'}, {'TeamNum': 12978, 'OPR': 55.193, 'Auto': 8.712, 'CCWM': -12.199, 'TeamName': 'CCHS Panther Robotics'}, {'TeamNum': 4906, 'OPR': 54.083, 'Auto': 7.587, 'CCWM': -14.944, 'TeamName': 'Junkyard Dawgs'}, {'TeamNum': 17113, 'OPR': 47.134, 'Auto': 12.339, 'CCWM': -23.348, 'TeamName': 'Westwood Hunga Munga'}, {'TeamNum': 12313, 'OPR': 37.102, 'Auto': 12.233, 'CCWM': -36.561, 'TeamName': 'Hotdawgs'}, {'TeamNum': 12926, 'OPR': 23.985, 'Auto': 5.715, 'CCWM': -37.35, 'TeamName': 'Panther Robotics'}, {'TeamNum': 21338, 'OPR': 20.595, 'Auto': -2.737, 'CCWM': -72.611, 'TeamName': 'Innovators'}, {'TeamNum': 15251, 'OPR': 17.153, 'Auto': -0.997, 'CCWM': -49.366, 'TeamName': 'Hadron Mission Eagle'}]

i 1134
i 1135
{'17802', '8284', '13590', '14361', '13227', '12448', '14637', '17294', '20325', '4921', '6832', '20736', '13539', '16320', '20313', '8811', '12209', '19857', '13265', '12126', '13825', '4902', '15725'}
[{'TeamNum': 14361, 'OPR': 137.432, 'Auto': 34.222, 'CCWM': 85.798, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 8284, 'OPR': 117.679, 'Auto': 36.226, 'CCWM': 47.34, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 4921, 'OPR': 111.864, 'Auto': 13.457, 'CCWM': 97.738, 'TeamName': 'The Dropouts'}, {'TeamNum': 13265, 'OPR': 96.718, 'Auto': 20.419, 'CCWM': 98.721, 'TeamName': 'Osiris'}, {'TeamNum': 20325, 'OPR': 94.326, 'Auto': 17.979, 'CCWM': 39.907, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 17294, 'OPR': 87.314, 'Auto': 21.115, 'CCWM': 1.48, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 20313, 'OPR': 82.562, 'Auto': 24.47, 'CCWM': 23.03, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 14637, 'OPR': 73.705, 'Auto': 17.636, 'CCWM': 1.12, 'TeamName': 'Aquanauts'}, {'TeamNum': 13590, 'OPR': 72.883, 'Auto': 9.989, 'CCWM': 28.129, 'TeamName': 'Viperstrike'}, {'TeamNum': 17802, 'OPR': 72.131, 'Auto': 20.679, 'CCWM': 11.419, 'TeamName': 'Logic No Tech'}, {'TeamNum': 4902, 'OPR': 70.164, 'Auto': 16.452, 'CCWM': 5.855, 'TeamName': 'Team Novabots'}, {'TeamNum': 8811, 'OPR': 65.634, 'Auto': 15.113, 'CCWM': -16.004, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 13539, 'OPR': 56.589, 'Auto': 17.821, 'CCWM': 4.891, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 13227, 'OPR': 56.502, 'Auto': 17.06, 'CCWM': -2.212, 'TeamName': 'Mechanicats'}, {'TeamNum': 19857, 'OPR': 55.325, 'Auto': 7.629, 'CCWM': -6.877, 'TeamName': 'GigaBots'}, {'TeamNum': 15725, 'OPR': 52.272, 'Auto': 13.152, 'CCWM': -38.622, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 12126, 'OPR': 42.007, 'Auto': 7.965, 'CCWM': -16.233, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 16320, 'OPR': 31.637, 'Auto': -1.977, 'CCWM': -77.143, 'TeamName': 'Gilded Gears'}, {'TeamNum': 20736, 'OPR': 24.683, 'Auto': 11.421, 'CCWM': -57.206, 'TeamName': 'Johnson Dynamics'}, {'TeamNum': 12209, 'OPR': 22.001, 'Auto': 3.56, 'CCWM': -36.966, 'TeamName': 'Blue Steel'}, {'TeamNum': 13825, 'OPR': 18.368, 'Auto': 5.529, 'CCWM': -48.964, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 12448, 'OPR': 15.382, 'Auto': 12.795, 'CCWM': -72.874, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 6832, 'OPR': 4.271, 'Auto': 4.597, 'CCWM': -75.206, 'TeamName': 'Iron Reign'}]
USTXSOBEOS
[{'TeamNum': 14361, 'OPR': 137.432, 'Auto': 34.222, 'CCWM': 85.798, 'TeamName': 'CPHS ROBOLOBOS GREEN'}, {'TeamNum': 8284, 'OPR': 117.679, 'Auto': 36.226, 'CCWM': 47.34, 'TeamName': 'Soap Dispenser'}, {'TeamNum': 4921, 'OPR': 111.864, 'Auto': 13.457, 'CCWM': 97.738, 'TeamName': 'The Dropouts'}, {'TeamNum': 13265, 'OPR': 96.718, 'Auto': 20.419, 'CCWM': 98.721, 'TeamName': 'Osiris'}, {'TeamNum': 20325, 'OPR': 94.326, 'Auto': 17.979, 'CCWM': 39.907, 'TeamName': 'Maximum Resistance'}, {'TeamNum': 17294, 'OPR': 87.314, 'Auto': 21.115, 'CCWM': 1.48, 'TeamName': 'Over Dr!ve Robotics'}, {'TeamNum': 20313, 'OPR': 82.562, 'Auto': 24.47, 'CCWM': 23.03, 'TeamName': 'Mustang Robotics'}, {'TeamNum': 14637, 'OPR': 73.705, 'Auto': 17.636, 'CCWM': 1.12, 'TeamName': 'Aquanauts'}, {'TeamNum': 13590, 'OPR': 72.883, 'Auto': 9.989, 'CCWM': 28.129, 'TeamName': 'Viperstrike'}, {'TeamNum': 17802, 'OPR': 72.131, 'Auto': 20.679, 'CCWM': 11.419, 'TeamName': 'Logic No Tech'}, {'TeamNum': 4902, 'OPR': 70.164, 'Auto': 16.452, 'CCWM': 5.855, 'TeamName': 'Team Novabots'}, {'TeamNum': 8811, 'OPR': 65.634, 'Auto': 15.113, 'CCWM': -16.004, 'TeamName': 'Robo*Bison Amistad'}, {'TeamNum': 13539, 'OPR': 56.589, 'Auto': 17.821, 'CCWM': 4.891, 'TeamName': 'RoboChargers - Thunder - Yellow'}, {'TeamNum': 13227, 'OPR': 56.502, 'Auto': 17.06, 'CCWM': -2.212, 'TeamName': 'Mechanicats'}, {'TeamNum': 19857, 'OPR': 55.325, 'Auto': 7.629, 'CCWM': -6.877, 'TeamName': 'GigaBots'}, {'TeamNum': 15725, 'OPR': 52.272, 'Auto': 13.152, 'CCWM': -38.622, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 12126, 'OPR': 42.007, 'Auto': 7.965, 'CCWM': -16.233, 'TeamName': 'Cedar Creek HS EagleBots '}, {'TeamNum': 16320, 'OPR': 31.637, 'Auto': -1.977, 'CCWM': -77.143, 'TeamName': 'Gilded Gears'}, {'TeamNum': 20736, 'OPR': 24.683, 'Auto': 11.421, 'CCWM': -57.206, 'TeamName': 'Johnson Dynamics'}, {'TeamNum': 12209, 'OPR': 22.001, 'Auto': 3.56, 'CCWM': -36.966, 'TeamName': 'Blue Steel'}, {'TeamNum': 13825, 'OPR': 18.368, 'Auto': 5.529, 'CCWM': -48.964, 'TeamName': 'Westerner Cobots\t'}, {'TeamNum': 12448, 'OPR': 15.382, 'Auto': 12.795, 'CCWM': -72.874, 'TeamName': 'M.A.R.S. - Patriot Engineering'}, {'TeamNum': 6832, 'OPR': 4.271, 'Auto': 4.597, 'CCWM': -75.206, 'TeamName': 'Iron Reign'}]
i 1136
{'19730', '21959', '23150', '19577', '22715', '23152', '20827', '22508', '22406', '19705', '20106', '23155', '19581', '19666', '19606', '19759', '19600', '23153', '19859', '19656', '19675', '22404'}
[{'TeamNum': 19675, 'OPR': 88.931, 'Auto': 21.553, 'CCWM': 59.638, 'TeamName': 'WX'}, {'TeamNum': 21959, 'OPR': 79.228, 'Auto': 15.761, 'CCWM': 47.884, 'TeamName': 'Dreamers'}, {'TeamNum': 22508, 'OPR': 78.94, 'Auto': 30.388, 'CCWM': 43.027, 'TeamName': 'SUPERNOVA'}, {'TeamNum': 19759, 'OPR': 78.131, 'Auto': 9.13, 'CCWM': 2.112, 'TeamName': 'SEEKERS'}, {'TeamNum': 19577, 'OPR': 73.923, 'Auto': 8.141, 'CCWM': 49.902, 'TeamName': 'WXY'}, {'TeamNum': 20827, 'OPR': 72.212, 'Auto': 23.313, 'CCWM': 13.091, 'TeamName': 'Roborpunk'}, {'TeamNum': 19705, 'OPR': 62.551, 'Auto': 14.612, 'CCWM': 15.595, 'TeamName': 'WXYZ'}, {'TeamNum': 19606, 'OPR': 55.662, 'Auto': 18.635, 'CCWM': 0.819, 'TeamName': 'Riser'}, {'TeamNum': 19600, 'OPR': 51.301, 'Auto': -2.915, 'CCWM': 15.455, 'TeamName': 'Treeman 树人'}, {'TeamNum': 20106, 'OPR': 49.773, 'Auto': 0.294, 'CCWM': -14.525, 'TeamName': 'HDKWA'}, {'TeamNum': 23150, 'OPR': 41.575, 'Auto': 4.664, 'CCWM': -13.676, 'TeamName': 'Dragon'}, {'TeamNum': 19666, 'OPR': 38.572, 'Auto': 2.513, 'CCWM': 9.891, 'TeamName': 'Forever Knight'}, {'TeamNum': 19730, 'OPR': 34.118, 'Auto': 1.973, 'CCWM': -5.688, 'TeamName': 'Talos'}, {'TeamNum': 19581, 'OPR': 31.871, 'Auto': 8.291, 'CCWM': -10.437, 'TeamName': 'IRON MAPLE 1120'}, {'TeamNum': 19656, 'OPR': 28.098, 'Auto': 3.783, 'CCWM': -25.356, 'TeamName': 'Absolute Zero'}, {'TeamNum': 22715, 'OPR': 25.596, 'Auto': -5.317, 'CCWM': 3.736, 'TeamName': '深圳高级中学（集团）南校区'}, {'TeamNum': 23155, 'OPR': 24.56, 'Auto': 0.463, 'CCWM': -4.056, 'TeamName': '37中队'}, {'TeamNum': 22406, 'OPR': 24.049, 'Auto': 0.456, 'CCWM': -33.78, 'TeamName': 'Hippasus'}, {'TeamNum': 19859, 'OPR': 23.096, 'Auto': 1.285, 'CCWM': -35.721, 'TeamName': 'Factorization'}, {'TeamNum': 22404, 'OPR': 21.175, 'Auto': -1.015, 'CCWM': -28.662, 'TeamName': 'Delta'}, {'TeamNum': 23153, 'OPR': 19.484, 'Auto': -0.19, 'CCWM': -37.604, 'TeamName': '梦之队'}, {'TeamNum': 23152, 'OPR': 6.82, 'Auto': -2.318, 'CCWM': -51.643, 'TeamName': '飞虎创学队'}]
CNDIS
[{'TeamNum': 19675, 'OPR': 88.931, 'Auto': 21.553, 'CCWM': 59.638, 'TeamName': 'WX'}, {'TeamNum': 21959, 'OPR': 79.228, 'Auto': 15.761, 'CCWM': 47.884, 'TeamName': 'Dreamers'}, {'TeamNum': 22508, 'OPR': 78.94, 'Auto': 30.388, 'CCWM': 43.027, 'TeamName': 'SUPERNOVA'}, {'TeamNum': 19759, 'OPR': 78.131, 'Auto': 9.13, 'CCWM': 2.112, 'TeamName': 'SEEKERS'}, {'TeamNum': 19577, 'OPR': 73.923, 'Auto': 8.141, 'CCWM': 49.902, 'TeamName': 'WXY'}, {'TeamNum': 20827, 'OPR': 72.212, 'Auto': 23.313, 'CCWM': 13.091, 'TeamName': 'Roborpunk'}, {'TeamNum': 19705, 'OPR': 62.551, 'Auto': 14.612, 'CCWM': 15.595, 'TeamName': 'WXYZ'}, {'TeamNum': 19606, 'OPR': 55.662, 'Auto': 18.635, 'CCWM': 0.819, 'TeamName': 'Riser'}, {'TeamNum': 19600, 'OPR': 51.301, 'Auto': -2.915, 'CCWM': 15.455, 'TeamName': 'Treeman 树人'}, {'TeamNum': 20106, 'OPR': 49.773, 'Auto': 0.294, 'CCWM': -14.525, 'TeamName': 'HDKWA'}, {'TeamNum': 23150, 'OPR': 41.575, 'Auto': 4.664, 'CCWM': -13.676, 'TeamName': 'Dragon'}, {'TeamNum': 19666, 'OPR': 38.572, 'Auto': 2.513, 'CCWM': 9.891, 'TeamName': 'Forever Knight'}, {'TeamNum': 19730, 'OPR': 34.118, 'Auto': 1.973, 'CCWM': -5.688, 'TeamName': 'Talos'}, {'TeamNum': 19581, 'OPR': 31.871, 'Auto': 8.291, 'CCWM': -10.437, 'TeamName': 'IRON MAPLE 1120'}, {'TeamNum': 19656, 'OPR': 28.098, 'Auto': 3.783, 'CCWM': -25.356, 'TeamName': 'Absolute Zero'}, {'TeamNum': 22715, 'OPR': 25.596, 'Auto': -5.317, 'CCWM': 3.736, 'TeamName': '深圳高级中学（集团）南校区'}, {'TeamNum': 23155, 'OPR': 24.56, 'Auto': 0.463, 'CCWM': -4.056, 'TeamName': '37中队'}, {'TeamNum': 22406, 'OPR': 24.049, 'Auto': 0.456, 'CCWM': -33.78, 'TeamName': 'Hippasus'}, {'TeamNum': 19859, 'OPR': 23.096, 'Auto': 1.285, 'CCWM': -35.721, 'TeamName': 'Factorization'}, {'TeamNum': 22404, 'OPR': 21.175, 'Auto': -1.015, 'CCWM': -28.662, 'TeamName': 'Delta'}, {'TeamNum': 23153, 'OPR': 19.484, 'Auto': -0.19, 'CCWM': -37.604, 'TeamName': '梦之队'}, {'TeamNum': 23152, 'OPR': 6.82, 'Auto': -2.318, 'CCWM': -51.643, 'TeamName': '飞虎创学队'}]

i 1137
i 1138
{'5243', '16597', '16556', '10862', '18908', '15703', '19746', '13893', '5188', '15654', '13833', '18738', '15221', '21352', '21879', '13109', '17229', '16828', '12977', '11924', '16458', '9923', '12928', '17329', '19412', '13266', '13744', '6901', '12202', '16377', '16555', '16832', '18458', '21386', '16831', '12302', '4902', '15725'}
[{'TeamNum': 19746, 'OPR': 171.953, 'Auto': 38.537, 'CCWM': 130.496, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 16458, 'OPR': 131.028, 'Auto': 42.313, 'CCWM': 107.74, 'TeamName': 'TechnoWizards'}, {'TeamNum': 12928, 'OPR': 117.986, 'Auto': 24.696, 'CCWM': 58.089, 'TeamName': 'LightSaders'}, {'TeamNum': 16377, 'OPR': 116.897, 'Auto': 32.286, 'CCWM': 78.851, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 18908, 'OPR': 89.922, 'Auto': 13.98, 'CCWM': 59.654, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 13266, 'OPR': 88.394, 'Auto': 7.17, 'CCWM': 18.993, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 12302, 'OPR': 82.806, 'Auto': 15.363, 'CCWM': 73.562, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 10862, 'OPR': 81.052, 'Auto': 23.414, 'CCWM': -27.223, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 21879, 'OPR': 75.497, 'Auto': 11.746, 'CCWM': 30.074, 'TeamName': 'Checkmate'}, {'TeamNum': 16597, 'OPR': 73.187, 'Auto': 23.845, 'CCWM': 6.043, 'TeamName': 'Fulminata'}, {'TeamNum': 16555, 'OPR': 70.866, 'Auto': 13.896, 'CCWM': 29.029, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 17229, 'OPR': 68.316, 'Auto': 16.549, 'CCWM': 68.749, 'TeamName': 'The Scouts '}, {'TeamNum': 13109, 'OPR': 64.41, 'Auto': -1.705, 'CCWM': 58.918, 'TeamName': 'Team Koopa'}, {'TeamNum': 6901, 'OPR': 61.558, 'Auto': 14.355, 'CCWM': 41.951, 'TeamName': 'Droid Rage - Phantom'}, {'TeamNum': 15703, 'OPR': 56.227, 'Auto': 10.221, 'CCWM': -7.913, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 4902, 'OPR': 53.609, 'Auto': 7.933, 'CCWM': -34.078, 'TeamName': 'Team Novabots'}, {'TeamNum': 11924, 'OPR': 52.586, 'Auto': 2.783, 'CCWM': 20.128, 'TeamName': 'Martin Robots'}, {'TeamNum': 13893, 'OPR': 50.7, 'Auto': 1.342, 'CCWM': -13.13, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 18738, 'OPR': 50.365, 'Auto': 28.606, 'CCWM': -43.645, 'TeamName': 'Moon Mechanics '}, {'TeamNum': 15221, 'OPR': 49.277, 'Auto': 2.145, 'CCWM': -9.088, 'TeamName': 'Astro Hawks'}, {'TeamNum': 16832, 'OPR': 48.197, 'Auto': 3.943, 'CCWM': 48.061, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 21386, 'OPR': 46.46, 'Auto': 13.433, 'CCWM': -13.451, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 15725, 'OPR': 46.435, 'Auto': 10.614, 'CCWM': -39.904, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 19412, 'OPR': 40.403, 'Auto': 6.924, 'CCWM': -35.012, 'TeamName': 'Archytas'}, {'TeamNum': 13833, 'OPR': 36.528, 'Auto': 3.265, 'CCWM': -27.556, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 12977, 'OPR': 29.312, 'Auto': 5.707, 'CCWM': -88.266, 'TeamName': 'Rust In Peace'}, {'TeamNum': 15654, 'OPR': 26.073, 'Auto': -10.956, 'CCWM': -20.311, 'TeamName': 'Nanoknights'}, {'TeamNum': 12202, 'OPR': 24.187, 'Auto': 4.081, 'CCWM': -59.571, 'TeamName': 'Gaga for Robots'}, {'TeamNum': 5188, 'OPR': 23.966, 'Auto': 2.698, 'CCWM': -24.749, 'TeamName': 'Team Phoenix'}, {'TeamNum': 18458, 'OPR': 23.83, 'Auto': 8.189, 'CCWM': -11.103, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 9923, 'OPR': 21.239, 'Auto': -3.713, 'CCWM': -28.941, 'TeamName': 'Team AAA'}, {'TeamNum': 16556, 'OPR': 20.52, 'Auto': 7.675, 'CCWM': -58.762, 'TeamName': 'Steminists'}, {'TeamNum': 16828, 'OPR': 15.87, 'Auto': -0.975, 'CCWM': -42.097, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 16831, 'OPR': 8.496, 'Auto': 3.748, 'CCWM': -72.181, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 13744, 'OPR': 3.777, 'Auto': -3.135, 'CCWM': -3.035, 'TeamName': 'Enginerds'}, {'TeamNum': 21352, 'OPR': 0.034, 'Auto': 5.064, 'CCWM': -49.697, 'TeamName': 'Team FireBots'}, {'TeamNum': 17329, 'OPR': -1.406, 'Auto': -2.818, 'CCWM': -57.878, 'TeamName': 'Team Stingray Dynamics'}, {'TeamNum': 5243, 'OPR': -6.008, 'Auto': 5.731, 'CCWM': -71.191, 'TeamName': 'Team Griffin'}]
USTXCECCS
[{'TeamNum': 19746, 'OPR': 171.953, 'Auto': 38.537, 'CCWM': 130.496, 'TeamName': 'The Disruptingly Robocephalic BrainSTEM Robotics Team'}, {'TeamNum': 16458, 'OPR': 131.028, 'Auto': 42.313, 'CCWM': 107.74, 'TeamName': 'TechnoWizards'}, {'TeamNum': 12928, 'OPR': 117.986, 'Auto': 24.696, 'CCWM': 58.089, 'TeamName': 'LightSaders'}, {'TeamNum': 16377, 'OPR': 116.897, 'Auto': 32.286, 'CCWM': 78.851, 'TeamName': 'Spicy Ketchup'}, {'TeamNum': 18908, 'OPR': 89.922, 'Auto': 13.98, 'CCWM': 59.654, 'TeamName': 'Mighty Hawks'}, {'TeamNum': 13266, 'OPR': 88.394, 'Auto': 7.17, 'CCWM': 18.993, 'TeamName': 'Droid Rage - Apex'}, {'TeamNum': 12302, 'OPR': 82.806, 'Auto': 15.363, 'CCWM': 73.562, 'TeamName': 'G-P Robotics: Synergy'}, {'TeamNum': 10862, 'OPR': 81.052, 'Auto': 23.414, 'CCWM': -27.223, 'TeamName': 'Droid Rage - Nebula'}, {'TeamNum': 21879, 'OPR': 75.497, 'Auto': 11.746, 'CCWM': 30.074, 'TeamName': 'Checkmate'}, {'TeamNum': 16597, 'OPR': 73.187, 'Auto': 23.845, 'CCWM': 6.043, 'TeamName': 'Fulminata'}, {'TeamNum': 16555, 'OPR': 70.866, 'Auto': 13.896, 'CCWM': 29.029, 'TeamName': 'Deus ex Maquina'}, {'TeamNum': 17229, 'OPR': 68.316, 'Auto': 16.549, 'CCWM': 68.749, 'TeamName': 'The Scouts '}, {'TeamNum': 13109, 'OPR': 64.41, 'Auto': -1.705, 'CCWM': 58.918, 'TeamName': 'Team Koopa'}, {'TeamNum': 6901, 'OPR': 61.558, 'Auto': 14.355, 'CCWM': 41.951, 'TeamName': 'Droid Rage - Phantom'}, {'TeamNum': 15703, 'OPR': 56.227, 'Auto': 10.221, 'CCWM': -7.913, 'TeamName': 'Teen Tech Titans'}, {'TeamNum': 4902, 'OPR': 53.609, 'Auto': 7.933, 'CCWM': -34.078, 'TeamName': 'Team Novabots'}, {'TeamNum': 11924, 'OPR': 52.586, 'Auto': 2.783, 'CCWM': 20.128, 'TeamName': 'Martin Robots'}, {'TeamNum': 13893, 'OPR': 50.7, 'Auto': 1.342, 'CCWM': -13.13, 'TeamName': 'Team BeSST-13893'}, {'TeamNum': 18738, 'OPR': 50.365, 'Auto': 28.606, 'CCWM': -43.645, 'TeamName': 'Moon Mechanics '}, {'TeamNum': 15221, 'OPR': 49.277, 'Auto': 2.145, 'CCWM': -9.088, 'TeamName': 'Astro Hawks'}, {'TeamNum': 16832, 'OPR': 48.197, 'Auto': 3.943, 'CCWM': 48.061, 'TeamName': 'G-P Robotics: Unity'}, {'TeamNum': 21386, 'OPR': 46.46, 'Auto': 13.433, 'CCWM': -13.451, 'TeamName': 'ROBO RAIDERS'}, {'TeamNum': 15725, 'OPR': 46.435, 'Auto': 10.614, 'CCWM': -39.904, 'TeamName': 'G-P Robotics: Dissension'}, {'TeamNum': 19412, 'OPR': 40.403, 'Auto': 6.924, 'CCWM': -35.012, 'TeamName': 'Archytas'}, {'TeamNum': 13833, 'OPR': 36.528, 'Auto': 3.265, 'CCWM': -27.556, 'TeamName': 'Deep Space Dolphins'}, {'TeamNum': 12977, 'OPR': 29.312, 'Auto': 5.707, 'CCWM': -88.266, 'TeamName': 'Rust In Peace'}, {'TeamNum': 15654, 'OPR': 26.073, 'Auto': -10.956, 'CCWM': -20.311, 'TeamName': 'Nanoknights'}, {'TeamNum': 12202, 'OPR': 24.187, 'Auto': 4.081, 'CCWM': -59.571, 'TeamName': 'Gaga for Robots'}, {'TeamNum': 5188, 'OPR': 23.966, 'Auto': 2.698, 'CCWM': -24.749, 'TeamName': 'Team Phoenix'}, {'TeamNum': 18458, 'OPR': 23.83, 'Auto': 8.189, 'CCWM': -11.103, 'TeamName': 'Battery Chargerz'}, {'TeamNum': 9923, 'OPR': 21.239, 'Auto': -3.713, 'CCWM': -28.941, 'TeamName': 'Team AAA'}, {'TeamNum': 16556, 'OPR': 20.52, 'Auto': 7.675, 'CCWM': -58.762, 'TeamName': 'Steminists'}, {'TeamNum': 16828, 'OPR': 15.87, 'Auto': -0.975, 'CCWM': -42.097, 'TeamName': 'G-P Robotics: Fusion'}, {'TeamNum': 16831, 'OPR': 8.496, 'Auto': 3.748, 'CCWM': -72.181, 'TeamName': 'G-P Robotics: Entropy'}, {'TeamNum': 13744, 'OPR': 3.777, 'Auto': -3.135, 'CCWM': -3.035, 'TeamName': 'Enginerds'}, {'TeamNum': 21352, 'OPR': 0.034, 'Auto': 5.064, 'CCWM': -49.697, 'TeamName': 'Team FireBots'}, {'TeamNum': 17329, 'OPR': -1.406, 'Auto': -2.818, 'CCWM': -57.878, 'TeamName': 'Team Stingray Dynamics'}, {'TeamNum': 5243, 'OPR': -6.008, 'Auto': 5.731, 'CCWM': -71.191, 'TeamName': 'Team Griffin'}]
i 1139

In [36]:
missing = []
for i in range(0,matches.shape[0]):
    print("i "+str(i))
    row = matches.iloc[i]
    link = row['Link']

    try:
        tset = getTeams(link)    
    
        match_list = getQuals(link)
    except Exception as e:
        continue
    
    if len(tset)==0 or len(match_list)==0:
        missing.append(i)

i 0
i 1
i 2
i 3
i 4
i 5
i 6
i 7
i 8
i 9
i 10
i 11
i 12
i 13
i 14
i 15
i 16
i 17
i 18
i 19
i 20
i 21
i 22
i 23
i 24
i 25
i 26
i 27
i 28
i 29
i 30
i 31
i 32
i 33
i 34
i 35
i 36
i 37
i 38
i 39
i 40
i 41
i 42
i 43
i 44
i 45
i 46
i 47
i 48
i 49
i 50
i 51
i 52
i 53
i 54
i 55
i 56
i 57
i 58
i 59
i 60
i 61
i 62
i 63
i 64
i 65
i 66
i 67
i 68
i 69
i 70
i 71
i 72
i 73
i 74
i 75
i 76
i 77
i 78
i 79
i 80
i 81
i 82
i 83
i 84
i 85
i 86
i 87
i 88
i 89
i 90
i 91
i 92
i 93
i 94
i 95
i 96
i 97
i 98
i 99
i 100
i 101
i 102
i 103
i 104
i 105
i 106
i 107
i 108
i 109
i 110
i 111
i 112
i 113
i 114
i 115
i 116
i 117
i 118
i 119
i 120
i 121
i 122
i 123
i 124
i 125
i 126
i 127
i 128
i 129
i 130
i 131
i 132
i 133
i 134
i 135
i 136
i 137
i 138
i 139
i 140
i 141
i 142
i 143
i 144
i 145
i 146
i 147
i 148
i 149
i 150
i 151
i 152
i 153
i 154
i 155
i 156
i 157
i 158
i 159
i 160
i 161
i 162
i 163
i 164
i 165
i 166
i 167
i 168
i 169
i 170
i 171
i 172
i 173
i 174
i 175
i 176
i 177
i 178
i 179
i 180
i 181
i 182
i 183
i 184
i 185
i 186
i 187
i 188
i 189
i 190
i 191
i 192
i 193
i 194
i 195
i 196
i 197
i 198
i 199
i 200
i 201
i 202
i 203
i 204
i 205
i 206
i 207
i 208
i 209
i 210
i 211
i 212
i 213
i 214
i 215
i 216
i 217
i 218
i 219
i 220
i 221
i 222
i 223
i 224
i 225
i 226
i 227
i 228
i 229
i 230
i 231
i 232
i 233
i 234
i 235
i 236
i 237
i 238
i 239
i 240
i 241
i 242
i 243
i 244
i 245
i 246
i 247
i 248
i 249
i 250
i 251
i 252
i 253
i 254
i 255
i 256
i 257
i 258
i 259
i 260
i 261
i 262
i 263
i 264
i 265
i 266
i 267
i 268
i 269
i 270
i 271
i 272
i 273
i 274
i 275
i 276
i 277
i 278
i 279
i 280
i 281
i 282
i 283
i 284
i 285
i 286
i 287
i 288
i 289
i 290
i 291
i 292
i 293
i 294
i 295
i 296
i 297
i 298
i 299
i 300
i 301
i 302
i 303
i 304
i 305
i 306
i 307
i 308
i 309
i 310
i 311
i 312
i 313
i 314
i 315
i 316
i 317
i 318
i 319
i 320
i 321
i 322
i 323
i 324
i 325
i 326
i 327
i 328
i 329
i 330
i 331
i 332
i 333
i 334
i 335
i 336
i 337
i 338
i 339
i 340
i 341
i 342
i 343
i 344
i 345
i 346
i 347
i 348
i 349
i 350
i 351
i 352
i 353
i 354
i 355
i 356
i 357
i 358
i 359
i 360
i 361
i 362
i 363
i 364
i 365
i 366
i 367
i 368
i 369
i 370
i 371
i 372
i 373
i 374
i 375
i 376
i 377
i 378
i 379
i 380
i 381
i 382
i 383
i 384
i 385
i 386
i 387
i 388
i 389
i 390
i 391
i 392
i 393
i 394
i 395
i 396
i 397
i 398
i 399
i 400
i 401
i 402
i 403
i 404
i 405
i 406
i 407
i 408
i 409
i 410
i 411
i 412
i 413
i 414
i 415
i 416
i 417
i 418
i 419
i 420
i 421
i 422
i 423
i 424
i 425
i 426
i 427
i 428
i 429
i 430
i 431
i 432
i 433
i 434
i 435
i 436
i 437
i 438
i 439
i 440
i 441
i 442
i 443
i 444
i 445
i 446
i 447
i 448
i 449
i 450
i 451
i 452
i 453
i 454
i 455
i 456
i 457
i 458
i 459
i 460
i 461
i 462
i 463
i 464
i 465
i 466
i 467
i 468
i 469
i 470
i 471
i 472
i 473
i 474
i 475
i 476
i 477
i 478
i 479
i 480
i 481
i 482
i 483
i 484
i 485
i 486
i 487
i 488
i 489
i 490
i 491
i 492
i 493
i 494
i 495
i 496
i 497
i 498
i 499
i 500
i 501
i 502
i 503
i 504
i 505
i 506
i 507
i 508
i 509
i 510
i 511
i 512
i 513
i 514
i 515
i 516
i 517
i 518
i 519
i 520
i 521
i 522
i 523
i 524
i 525
i 526
i 527
i 528
i 529
i 530
i 531
i 532
i 533
i 534
i 535
i 536
i 537
i 538
i 539
i 540
i 541
i 542
i 543
i 544
i 545
i 546
i 547
i 548
i 549
i 550
i 551
i 552
i 553
i 554
i 555
i 556
i 557
i 558
i 559
i 560
i 561
i 562
i 563
i 564
i 565
i 566
i 567
i 568
i 569
i 570
i 571
i 572
i 573
i 574
i 575
i 576
i 577
i 578
i 579
i 580
i 581
i 582
i 583
i 584
i 585
i 586
i 587
i 588
i 589
i 590
i 591
i 592
i 593
i 594
i 595
i 596
i 597
i 598
i 599
i 600
i 601
i 602
i 603
i 604
i 605
i 606
i 607
i 608
i 609
i 610
i 611
i 612
i 613
i 614
i 615
i 616
i 617
i 618
i 619
i 620
i 621
i 622
i 623
i 624
i 625
i 626
i 627
i 628
i 629
i 630
i 631
i 632
i 633
i 634
i 635
i 636
i 637
i 638
i 639
i 640
i 641
i 642
i 643
i 644
i 645
i 646
i 647
i 648
i 649
i 650
i 651
i 652
i 653
i 654
i 655
i 656
i 657
i 658
i 659
i 660
i 661
i 662
i 663
i 664
i 665
i 666
i 667
i 668
i 669
i 670
i 671
i 672
i 673
i 674
i 675
i 676
i 677
i 678
i 679
i 680
i 681
i 682
i 683
i 684
i 685
i 686
i 687
i 688
i 689
i 690
i 691
i 692
i 693
i 694
i 695
i 696
i 697
i 698
i 699
i 700
i 701
i 702
i 703
i 704
i 705
i 706
i 707
i 708
i 709
i 710
i 711
i 712
i 713
i 714
i 715
i 716
i 717
i 718
i 719
i 720
i 721
i 722
i 723
i 724
i 725
i 726
i 727
i 728
i 729
i 730
i 731
i 732
i 733
i 734
i 735
i 736
i 737
i 738
i 739
i 740
i 741
i 742
i 743
i 744
i 745
i 746
i 747
i 748
i 749
i 750
i 751
i 752
i 753
i 754
i 755
i 756
i 757
i 758
i 759
i 760
i 761
i 762
i 763
i 764
i 765
i 766
i 767
i 768
i 769
i 770
i 771
i 772
i 773
i 774
i 775
i 776
i 777
i 778
i 779
i 780
i 781
i 782
i 783
i 784
i 785
i 786
i 787
i 788
i 789
i 790
i 791
i 792
i 793
i 794
i 795
i 796
i 797
i 798
i 799
i 800
i 801
i 802
i 803
i 804
i 805
i 806
i 807
i 808
i 809
i 810
i 811
i 812
i 813
i 814
i 815
i 816
i 817
i 818
i 819
i 820
i 821
i 822
i 823
i 824
i 825
i 826
i 827
i 828
i 829
i 830
i 831
i 832
i 833
i 834
i 835
i 836
i 837
i 838
i 839
i 840
i 841
i 842
i 843
i 844
i 845
i 846
i 847
i 848
i 849
i 850
i 851
i 852
i 853
i 854
i 855
i 856
i 857
i 858
i 859
i 860
i 861
i 862
i 863
i 864
i 865
i 866
i 867
i 868
i 869
i 870
i 871
i 872
i 873
i 874
i 875
i 876
i 877
i 878
i 879
i 880
i 881
i 882
i 883
i 884
i 885
i 886
i 887
i 888
i 889
i 890
i 891
i 892
i 893
i 894
i 895
i 896
i 897
i 898
i 899
i 900
i 901
i 902
i 903
i 904
i 905
i 906
i 907
i 908
i 909
i 910
i 911
i 912
i 913
i 914
i 915
i 916
i 917
i 918
i 919
i 920
i 921
i 922
i 923
i 924
i 925
i 926
i 927
i 928
i 929
i 930
i 931
i 932
i 933
i 934
i 935
i 936
i 937
i 938
i 939
i 940
i 941
i 942
i 943
i 944
i 945
i 946
i 947
i 948
i 949
i 950
i 951
i 952
i 953
i 954
i 955
i 956
i 957
i 958
i 959
i 960
i 961
i 962
i 963
i 964
i 965
i 966
i 967
i 968
i 969
i 970
i 971
i 972
i 973
i 974
i 975
i 976
i 977
i 978
i 979
i 980
i 981
i 982
i 983
i 984
i 985
i 986
i 987
i 988
i 989
i 990
i 991
i 992
i 993
i 994
i 995
i 996
i 997
i 998
i 999
i 1000
i 1001
i 1002
i 1003
i 1004
i 1005
i 1006
i 1007
i 1008
i 1009
i 1010
i 1011
i 1012
i 1013
i 1014
i 1015
i 1016
i 1017
i 1018
i 1019
i 1020
i 1021
i 1022
i 1023
i 1024
i 1025
i 1026
i 1027
i 1028
i 1029
i 1030
i 1031
i 1032
i 1033
i 1034
i 1035
i 1036
i 1037
i 1038
i 1039
i 1040
i 1041
i 1042
i 1043
i 1044
i 1045
i 1046
i 1047
i 1048
i 1049
i 1050
i 1051
i 1052
i 1053
i 1054
i 1055
i 1056
i 1057
i 1058
i 1059
i 1060
i 1061
i 1062
i 1063
i 1064
i 1065
i 1066
i 1067
i 1068
i 1069
i 1070
i 1071
i 1072
i 1073
i 1074
i 1075
i 1076
i 1077
i 1078
i 1079
i 1080
i 1081
i 1082
i 1083
i 1084
i 1085
i 1086
i 1087
i 1088
i 1089
i 1090
i 1091
i 1092
i 1093
i 1094
i 1095
i 1096
i 1097
i 1098
i 1099
i 1100
i 1101
i 1102
i 1103
i 1104
i 1105
i 1106
i 1107
i 1108
i 1109
i 1110
i 1111
i 1112
i 1113
i 1114
i 1115
i 1116
i 1117
i 1118
i 1119
i 1120
i 1121
i 1122
i 1123
i 1124
i 1125
i 1126
i 1127
i 1128
i 1129
i 1130
i 1131
i 1132
i 1133
i 1134
i 1135
i 1136
i 1137
i 1138
i 1139

In [37]:
df = pd.DataFrame(missing)
df

        0
0       3
1       4
2       9
3      11
4      13
..    ...
122  1128
123  1131
124  1134
125  1137
126  1139

[127 rows x 1 columns]

In [4]:
missing = pd.read_csv(os.getcwd().replace('scripts', 'data') + '/missing.csv')

In [6]:
missing

        0
0       3
1       4
2       9
3      11
4      13
..    ...
122  1128
123  1131
124  1134
125  1137
126  1139

[127 rows x 1 columns]

In [8]:
for i in range(127):
    print(str(i)+" "+matches.iat[missing.iat[i,0],0]+" "+matches.iat[missing.iat[i,0],1])

0 USPAPHOS PA FTC RoboJawn
1 FRLEOS FR Le Défi Robotique – Lyon 2023
2 USORROOS OR Spring Showcase
3 USAZFLOS AZ Lunar Legacy Invitational
4 USORGLOS OR Spring Showcase 2
5 USORMLS OR Spring Scrimmage and Showcase
6 GBCAOS GB New Teams Regional
7 GBCMP Championship- United Kingdom
8 USALHUOS AL betaSEIT
9 USOKMUOS OK-Northeast (NEO) Invitational
10 USCANOSMOS Lobster Cup International
11 AUMPOS1 AU APOC 2023
12 USILCHOS IL Chicago Robotics Invitational
13 USOHAKOS OH KSS Robotics Turtle Friendly
14 USNDBIS ND Scrimmage
15 USAZTUS AZ Tucson "Meet the Field" Day
16 USMNSPS MN Cass Lake League Meet 0
17 USMSBCS1 MS Bogue Chitto Build-it Day/Scrimmage
18 USIDPFS1 ID North Idaho Scrimmage #1
19 USAKJUS2 AK Southeast Scrimmage #1
20 USFLFLS FL South Florida League Scrimmage and Volunteer Training
21 USGAGAS GA N Georgia League Scrimmage
22 USMNAVS MN FTC Mille Lacs / Pepin League Meet 0
23 USMSLAS MS LCS Build-it Day/Scrimmage
24 USORRBS OR North Coast League Meet 0
25 USTXWPMIS TX-W&P Midland Scrimmage
26 USFLSPS FL Gulf Coast League Scrimmage
27 USMIDHS1 MI Detroit Metro Scrimmage
28 USOHNAS OH Central Ohio League Meet 0
29 USORROS OR SOAR League Meet 0
30 USTXCEGCM8 TX-Central Sylvia Earle Scrimmage 1
31 USTXCEGCM7 TX-Central Daphne Koller Scrimmage 1
32 USFLORS FL Orlando Robotics League Scrimmage
33 USMSWVS1 MS Water Valley Build-it Day/Scrimmage
34 USNHMAS NH Derryfield Scrimmage #1
35 USNVLVS NV Southern Scrimmage
36 USTXCEAUS1 TX-Central X-STREAM Scrimmage 1
37 USTXCEWAS TX-Central Waco Scrimmage 1
38 USAZCHS AZ First Look - Chandler Scrimmage
39 USIDPFS2 ID North Idaho Scrimmage #2
40 USTXHOPAS TX-Houston South League Practice Session
41 CAONSCS ON Fall Fiesta @ Bethune CI
42 USAKJUS1 AK Southeast Scrimmage #2
43 USCALACLS CA-SoCal League E - Meet 0
44 USCODES CO University of Colorado Denver
45 USIACRS IA Geothermal_Scrimmage_2022-11-09
46 USMOKSSPS MOKS-MO Kickapoo Scrimmage
47 USOHCIS OH Summit Country Day School Scrimmage
48 USPAKSS PA UCFSD FTC Scrimmage
49 USSCCHS SC Lowcountry Scrimmage 1
50 USTXCEAUS TX-Central Vandegrift HS Scrimmage
51 USCOMOS CO Monumental Impact
52 USMSOXS1 MS Gulf Coast Scrimmage
53 USNHHUS2 NH Alvirne Scrimmage #2
54 KZALQ1 KZ Haileybury
55 USCOENS CO Colorado Early Colleges
56 USIDPFS3 ID North Idaho Scrimmage #3
57 USPAGIS Green and Red Scrimmage
58 USSCLAS SC PeeDee Scrimmage 1
59 USVTHIS VT FTC Scrimmage at CVU
60 CABCVAS4 BC Remote Scrimmage 4
61 USARMHS AR Mountain Home Scrimmage
62 USCOGRS CO EGMS - Scrimmage
63 USMICMP2 Michigan FTC State Championship-SE
64 USSCMAS SC Upstate/Midlands Scrimmage 2
65 USMICMP Michigan FTC State Championship-NW
66 USNHWIS NH Windham Scrimmage #3
67 GBLOS GB South East Scrimmage
68 USARSPS2 AR Turnbow Scrimmage
69 USIDPFS4 ID North Idaho Scrimmage #4
70 USPAPHS PA FTC Scrimmage
71 USSCFLS2 SC PeeDee Scrimmage 2
72 JMK6S2 JM Jamaica College Scrimmage
73 GBCHS GB North Scrimmage
74 GBSTS GB West Midlands Scrimmage
75 GBBES GB Northern Ireland Scrimmage
76 USDEWIS2 DE FTC Meet -- Tower Hill
77 USIDGOS ID Southern Idaho Scrimmage
78 USWIBRS2 WI Mentor Madness Scrimmage - Hosted by RhinoBots/Alien
79 ZACTQ Western Cape Regional
80 GBCAS GB East Scrimmage
81 GBBOS GB South West Scrimmage
82 USSCORS3 SC Midlands Scrimmage 3
83 USTNNAS TN Central Magnet Hosting in Mid TN
84 USVTBUS VT FTC scrimmage at South Burlington HS
85 CABCVAQ BC Remote Qualifier
86 CAONPIQ ON Remote Qualifying Tournament
87 KZALQ2 KZ FIZMAT Tournament
88 ZAJOQ1 Gauteng Regional Event
89 USDEWIS3 DE FTC Meet at Padua
90 LYALQ LY Tripoli Qualifying Competition
91 KRCMP Korea Robot Championship
92 USDEDOS DE FTC Meet at DSU
93 USIDPFS5 ID North Idaho Scrimmage #5
94 USTXHOSWM3 TX- Houston Soutwest League Meet 3
95 CAABABSALT Alberta Southern Championship
96 CNSHQ2 CN China FTC Qualifier #1
97 ILCMP Israel Championship
98 USARSPS1 AR Shiloh Scrimmage
99 USAZSVS AZ Champs Warmup Scrimmage
100 USDEWIS DE FTC Meet at Wilmington Friends
101 USCHSCMP Chesapeake FTC Championship
102 USMNCMP Minnesota FTC State Championship
103 BRNHS BR FTC - Sinos Valley Challenge
104 CNSHQ CN China FTC Qualifier #2
105 CNSHQ3 CN China FTC Qualifier #3
106 NGABQ NG Regional FIRST Tech Challenge
107 USNYLIREQ New York - Long Island Qualifier #4 - REMOTE
108 ONADODCMP1 ONADoDEA-Europe 2023 Invitational Tournament
109 JMK6S Jamaica Pre-Championship Scrimmage
110 USAZCMP Arizona FIRST Tech Challenge Championship
111 USIDMES ID Treasure Valley Scrimmage
112 USORCMPSOL Oregon FIRST Tech Challenge Championship - Solar Division
113 USORCMPHYD Oregon FIRST Tech Challenge Championship - Hydro Division
114 CNCMP China FTC Championship
115 USCANOCMP California-NorCal FTC Regional Championship
116 USFLCMP Florida Championship
117 USIACMP Iowa Championship
118 USORCMP2 OR Regional Championship
119 INCMP FIRST Tech Challenge India Championship
120 USNJCMP New Jersey State Championship-NJ0312
121 EGALS Egypt Scrimmage
122 SACMP Saudi Arabia FIRST Tech Challenge Championship - KSA
123 USTXSOCMP2 FIRST in Texas State Championship
124 USTXCECMP FIRST in Texas FTC State Championship
125 GBREQ GB Remote Regional
126 FTCCMP1 FIRST Championship - Houston - World Championship - FIRST Tech Challenge

In [25]:
ids = [ 'USTXCECMP','FTCCMP1', 'USNJCMP', 'USMICMP2', 'USMICMP', 'CAABABSALT','ILCMP','USCHSCMP','USMNCMP','USAZCMP','USCANOCMP','USFLCMP','USIACMP']

In [28]:
from selenium.webdriver.common.by import By

In [59]:
# 0 to 10

driver = webdriver.Safari()

for i in range(2,len(ids)):
    print("i "+str(i))
    link = ids[i]
    
    driver.get('https://ftc-events.firstinspires.org/2022/'+link)
    
    subs = driver.find_elements(By.CLASS_NAME, 'col-sm-4')
    
    print(subs)
    
    if len(subs) > 0 and len(subs)%3==0:
        for j in range(len(subs)//3):
            link = subs[j*3].find_element(By.CLASS_NAME, "btn").get_attribute('href')
            
            print(link)

            try:
                tset = getTeams(link)    

                match_list = getQuals(link)
            except Exception as e:
                continue
                
            print(tset)

            if len(tset)==0 or len(match_list)==0:
                continue

            with open("./matches-"+link.split('/')[-2]+".txt", "a") as mfile:
                for i in range(len(match_list)):
                    curr_m = match_list[i]['href']
                    team_list = getTeamsQual('https://ftc-events.firstinspires.org'+curr_m)

                    red = team_list[1]
                    blue = team_list[0]

                    res = getScores('https://ftc-events.firstinspires.org'+curr_m)

                    #match file
                    mfile.write(str(red[0]) + " " + str(red[1]) + " " + str(res[1][0]) + " "+ str(res[1][1])+ " "+
                                str(blue[0]) + " "+ str(blue[1]) + " " + str(res[0][0]) + " " + str(res[0][1])+"\n"
                               )
            with open("./teams-"+link.split('/')[-2]+".txt","a") as tfile:
                for t in tset:
                    tfile.write(str(t) + ", " + teams[teams['Team Number']==int(t)].iloc[0,1]+ "\n")



            print(tset)

            results = calcs(link.split('/')[-2])
#             print(row['Link'])

            print(results)

            for team_result in results:
                yes = False
                if not os.path.exists(os.getcwd().replace("scripts", "data/team_data/"+str(team_result['TeamNum'])+".csv")):
                    yes = True
                with open(os.getcwd().replace("scripts", "data/team_data/"+str(team_result['TeamNum'])+".csv"), 'a') as f_object:
                    writer_object = writer(f_object)
                    if yes:
                        writer_object.writerow(['ID', 'OPR', 'Auto', 'CCWM'])


                    writer_object.writerow([link.split('/')[-2], team_result['OPR'], team_result['Auto'], team_result['CCWM']])

                f_object.close()


            tfile.close()
            mfile.close()
#     rmdir("teams-"+match+".txt")
#     rmdir("matches-"+match+".txt")

i 2
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-3C999936-3990-45D9-9437-FDA284D2E0BE")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-7C24678C-DD6A-4DC0-8684-C65B79C1300A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-4159548C-24D8-46B8-94E4-5D4E9795E1E2")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-F4D54820-1016-4359-B685-46E8FA7FD3B9")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-3BA8E2DD-339B-4540-8B7E-31D18C61461C")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-37115203-062E-4373-AE5B-584190B07791")>]
https://ftc-events.firstinspires.org/2022/USNJCMPTPKE/qualifications
{'10096', '16557', '19823', '4215', '12636', '17036', '18241', '13103', '22261', '11697', '247', '16102', '12116', '6934', '7040', '7350', '11248', '21226', '4890', '11166', '15887', '10669', '9848', '14481'}
{'10096', '16557', '19823', '4215', '12636', '17036', '18241', '13103', '22261', '11697', '247', '16102', '12116', '6934', '7040', '7350', '11248', '21226', '4890', '11166', '15887', '10669', '9848', '14481'}
[{'TeamNum': 4215, 'OPR': 127.813, 'Auto': 29.67, 'CCWM': 93.667, 'TeamName': 'Hypnotic Robotics'}, {'TeamNum': 4890, 'OPR': 112.077, 'Auto': 21.114, 'CCWM': 61.845, 'TeamName': 'AArcHive'}, {'TeamNum': 9848, 'OPR': 106.149, 'Auto': 29.177, 'CCWM': 46.221, 'TeamName': 'GearView'}, {'TeamNum': 10669, 'OPR': 104.562, 'Auto': 31.093, 'CCWM': 48.016, 'TeamName': 'Clutch Squad'}, {'TeamNum': 14481, 'OPR': 96.435, 'Auto': 28.671, 'CCWM': 28.279, 'TeamName': "Don't Blink"}, {'TeamNum': 7040, 'OPR': 95.386, 'Auto': 16.986, 'CCWM': 0.184, 'TeamName': 'CyberFalcons'}, {'TeamNum': 11248, 'OPR': 86.936, 'Auto': 13.001, 'CCWM': 10.046, 'TeamName': '//Cougars'}, {'TeamNum': 11166, 'OPR': 86.692, 'Auto': 26.807, 'CCWM': -36.451, 'TeamName': 'Big Red Robotics'}, {'TeamNum': 21226, 'OPR': 76.827, 'Auto': 28.023, 'CCWM': 4.599, 'TeamName': 'RoboRaiders'}, {'TeamNum': 12116, 'OPR': 76.486, 'Auto': 9.276, 'CCWM': 28.507, 'TeamName': 'Redbots'}, {'TeamNum': 17036, 'OPR': 71.262, 'Auto': 14.247, 'CCWM': 9.281, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 7350, 'OPR': 56.317, 'Auto': 14.196, 'CCWM': 11.515, 'TeamName': "Watt's NXT?"}, {'TeamNum': 12636, 'OPR': 55.0, 'Auto': 20.81, 'CCWM': -37.34, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 22261, 'OPR': 54.442, 'Auto': 12.949, 'CCWM': 11.002, 'TeamName': 'Hornet Blue'}, {'TeamNum': 15887, 'OPR': 51.539, 'Auto': 9.321, 'CCWM': -62.981, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 6934, 'OPR': 51.48, 'Auto': 18.874, 'CCWM': 42.566, 'TeamName': 'The TranSisters'}, {'TeamNum': 18241, 'OPR': 49.768, 'Auto': 15.602, 'CCWM': -29.384, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 16102, 'OPR': 48.431, 'Auto': 12.57, 'CCWM': 2.172, 'TeamName': 'The Short Circuits'}, {'TeamNum': 11697, 'OPR': 48.199, 'Auto': 15.117, 'CCWM': -22.417, 'TeamName': 'TECH-tonic'}, {'TeamNum': 19823, 'OPR': 46.545, 'Auto': 31.186, 'CCWM': -33.517, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 16557, 'OPR': 45.389, 'Auto': 7.646, 'CCWM': -16.16, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 13103, 'OPR': 39.842, 'Auto': 21.68, 'CCWM': -37.153, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 247, 'OPR': 30.595, 'Auto': 5.731, 'CCWM': -70.494, 'TeamName': 'Reboot'}, {'TeamNum': 10096, 'OPR': 18.027, 'Auto': 12.453, 'CCWM': -52.003, 'TeamName': 'Those Guys'}]
[{'TeamNum': 4215, 'OPR': 127.813, 'Auto': 29.67, 'CCWM': 93.667, 'TeamName': 'Hypnotic Robotics'}, {'TeamNum': 4890, 'OPR': 112.077, 'Auto': 21.114, 'CCWM': 61.845, 'TeamName': 'AArcHive'}, {'TeamNum': 9848, 'OPR': 106.149, 'Auto': 29.177, 'CCWM': 46.221, 'TeamName': 'GearView'}, {'TeamNum': 10669, 'OPR': 104.562, 'Auto': 31.093, 'CCWM': 48.016, 'TeamName': 'Clutch Squad'}, {'TeamNum': 14481, 'OPR': 96.435, 'Auto': 28.671, 'CCWM': 28.279, 'TeamName': "Don't Blink"}, {'TeamNum': 7040, 'OPR': 95.386, 'Auto': 16.986, 'CCWM': 0.184, 'TeamName': 'CyberFalcons'}, {'TeamNum': 11248, 'OPR': 86.936, 'Auto': 13.001, 'CCWM': 10.046, 'TeamName': '//Cougars'}, {'TeamNum': 11166, 'OPR': 86.692, 'Auto': 26.807, 'CCWM': -36.451, 'TeamName': 'Big Red Robotics'}, {'TeamNum': 21226, 'OPR': 76.827, 'Auto': 28.023, 'CCWM': 4.599, 'TeamName': 'RoboRaiders'}, {'TeamNum': 12116, 'OPR': 76.486, 'Auto': 9.276, 'CCWM': 28.507, 'TeamName': 'Redbots'}, {'TeamNum': 17036, 'OPR': 71.262, 'Auto': 14.247, 'CCWM': 9.281, 'TeamName': 'Robotech Anomaly'}, {'TeamNum': 7350, 'OPR': 56.317, 'Auto': 14.196, 'CCWM': 11.515, 'TeamName': "Watt's NXT?"}, {'TeamNum': 12636, 'OPR': 55.0, 'Auto': 20.81, 'CCWM': -37.34, 'TeamName': 'IHA Blue Eagles'}, {'TeamNum': 22261, 'OPR': 54.442, 'Auto': 12.949, 'CCWM': 11.002, 'TeamName': 'Hornet Blue'}, {'TeamNum': 15887, 'OPR': 51.539, 'Auto': 9.321, 'CCWM': -62.981, 'TeamName': 'Titanium Knights A'}, {'TeamNum': 6934, 'OPR': 51.48, 'Auto': 18.874, 'CCWM': 42.566, 'TeamName': 'The TranSisters'}, {'TeamNum': 18241, 'OPR': 49.768, 'Auto': 15.602, 'CCWM': -29.384, 'TeamName': 'Outer Galaxy'}, {'TeamNum': 16102, 'OPR': 48.431, 'Auto': 12.57, 'CCWM': 2.172, 'TeamName': 'The Short Circuits'}, {'TeamNum': 11697, 'OPR': 48.199, 'Auto': 15.117, 'CCWM': -22.417, 'TeamName': 'TECH-tonic'}, {'TeamNum': 19823, 'OPR': 46.545, 'Auto': 31.186, 'CCWM': -33.517, 'TeamName': 'JOLLY BLUE'}, {'TeamNum': 16557, 'OPR': 45.389, 'Auto': 7.646, 'CCWM': -16.16, 'TeamName': 'Honey K-Ohms '}, {'TeamNum': 13103, 'OPR': 39.842, 'Auto': 21.68, 'CCWM': -37.153, 'TeamName': 'Ironmen Omega'}, {'TeamNum': 247, 'OPR': 30.595, 'Auto': 5.731, 'CCWM': -70.494, 'TeamName': 'Reboot'}, {'TeamNum': 10096, 'OPR': 18.027, 'Auto': 12.453, 'CCWM': -52.003, 'TeamName': 'Those Guys'}]
https://ftc-events.firstinspires.org/2022/USNJCMPPKWY/qualifications
{'18051', '8405', '10582', '248', '5387', '16367', '21630', '11456', '11180', '16953', '19735', '15715', '15891', '4347', '11754', '9889', '10785', '7149', '207', '13615', '12488', '7026', '12806', '20204'}
{'18051', '8405', '10582', '248', '5387', '16367', '21630', '11456', '11180', '16953', '19735', '15715', '15891', '4347', '11754', '9889', '10785', '7149', '207', '13615', '12488', '7026', '12806', '20204'}
[{'TeamNum': 9889, 'OPR': 137.088, 'Auto': 29.112, 'CCWM': 94.791, 'TeamName': 'Cruise Control'}, {'TeamNum': 7149, 'OPR': 128.379, 'Auto': 23.911, 'CCWM': 81.683, 'TeamName': 'ENFORCERS'}, {'TeamNum': 18051, 'OPR': 112.907, 'Auto': 24.111, 'CCWM': 29.068, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 11180, 'OPR': 103.911, 'Auto': 23.068, 'CCWM': 63.089, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 16367, 'OPR': 103.064, 'Auto': 19.574, 'CCWM': 10.584, 'TeamName': 'Krypton Warriors'}, {'TeamNum': 12488, 'OPR': 94.973, 'Auto': 21.418, 'CCWM': 40.88, 'TeamName': 'Raidiators'}, {'TeamNum': 207, 'OPR': 93.235, 'Auto': 23.11, 'CCWM': 0.493, 'TeamName': 'Critical Mass'}, {'TeamNum': 8405, 'OPR': 82.799, 'Auto': 8.927, 'CCWM': -8.341, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 10785, 'OPR': 77.831, 'Auto': 14.618, 'CCWM': -14.754, 'TeamName': 'Highlanders'}, {'TeamNum': 11754, 'OPR': 77.717, 'Auto': 34.126, 'CCWM': -37.144, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 248, 'OPR': 77.53, 'Auto': 12.77, 'CCWM': -16.679, 'TeamName': 'Fatal Error'}, {'TeamNum': 11456, 'OPR': 75.155, 'Auto': 22.722, 'CCWM': 14.887, 'TeamName': 'Blair Academy'}, {'TeamNum': 21630, 'OPR': 64.108, 'Auto': 30.961, 'CCWM': 9.881, 'TeamName': 'Argonauts'}, {'TeamNum': 7026, 'OPR': 64.001, 'Auto': 31.032, 'CCWM': -18.023, 'TeamName': 'JDroids'}, {'TeamNum': 15891, 'OPR': 63.57, 'Auto': 21.314, 'CCWM': 3.282, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 16953, 'OPR': 59.764, 'Auto': 21.082, 'CCWM': 7.457, 'TeamName': 'FIRE'}, {'TeamNum': 15715, 'OPR': 56.059, 'Auto': 22.346, 'CCWM': -19.07, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 19735, 'OPR': 54.259, 'Auto': 10.898, 'CCWM': -28.632, 'TeamName': 'Hornet Silver'}, {'TeamNum': 20204, 'OPR': 46.893, 'Auto': 12.352, 'CCWM': -9.758, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 13615, 'OPR': 25.818, 'Auto': 16.078, 'CCWM': -37.703, 'TeamName': 'RoboRams'}, {'TeamNum': 5387, 'OPR': 25.241, 'Auto': 13.975, 'CCWM': -29.344, 'TeamName': 'TecHounds'}, {'TeamNum': 10582, 'OPR': 19.81, 'Auto': -5.339, 'CCWM': -14.101, 'TeamName': 'Emerald Knights'}, {'TeamNum': 12806, 'OPR': 14.499, 'Auto': 12.984, 'CCWM': -55.913, 'TeamName': 'Roboken'}, {'TeamNum': 4347, 'OPR': 5.786, 'Auto': -2.751, 'CCWM': -66.634, 'TeamName': 'NanoGurus'}]
[{'TeamNum': 9889, 'OPR': 137.088, 'Auto': 29.112, 'CCWM': 94.791, 'TeamName': 'Cruise Control'}, {'TeamNum': 7149, 'OPR': 128.379, 'Auto': 23.911, 'CCWM': 81.683, 'TeamName': 'ENFORCERS'}, {'TeamNum': 18051, 'OPR': 112.907, 'Auto': 24.111, 'CCWM': 29.068, 'TeamName': 'Robotic Llamas'}, {'TeamNum': 11180, 'OPR': 103.911, 'Auto': 23.068, 'CCWM': 63.089, 'TeamName': 'Beaks n Bolts '}, {'TeamNum': 16367, 'OPR': 103.064, 'Auto': 19.574, 'CCWM': 10.584, 'TeamName': 'Krypton Warriors'}, {'TeamNum': 12488, 'OPR': 94.973, 'Auto': 21.418, 'CCWM': 40.88, 'TeamName': 'Raidiators'}, {'TeamNum': 207, 'OPR': 93.235, 'Auto': 23.11, 'CCWM': 0.493, 'TeamName': 'Critical Mass'}, {'TeamNum': 8405, 'OPR': 82.799, 'Auto': 8.927, 'CCWM': -8.341, 'TeamName': 'Millburn Robotics'}, {'TeamNum': 10785, 'OPR': 77.831, 'Auto': 14.618, 'CCWM': -14.754, 'TeamName': 'Highlanders'}, {'TeamNum': 11754, 'OPR': 77.717, 'Auto': 34.126, 'CCWM': -37.144, 'TeamName': 'EnergySmart FTC'}, {'TeamNum': 248, 'OPR': 77.53, 'Auto': 12.77, 'CCWM': -16.679, 'TeamName': 'Fatal Error'}, {'TeamNum': 11456, 'OPR': 75.155, 'Auto': 22.722, 'CCWM': 14.887, 'TeamName': 'Blair Academy'}, {'TeamNum': 21630, 'OPR': 64.108, 'Auto': 30.961, 'CCWM': 9.881, 'TeamName': 'Argonauts'}, {'TeamNum': 7026, 'OPR': 64.001, 'Auto': 31.032, 'CCWM': -18.023, 'TeamName': 'JDroids'}, {'TeamNum': 15891, 'OPR': 63.57, 'Auto': 21.314, 'CCWM': 3.282, 'TeamName': 'Titanium Knights B'}, {'TeamNum': 16953, 'OPR': 59.764, 'Auto': 21.082, 'CCWM': 7.457, 'TeamName': 'FIRE'}, {'TeamNum': 15715, 'OPR': 56.059, 'Auto': 22.346, 'CCWM': -19.07, 'TeamName': 'Crusader Robotics'}, {'TeamNum': 19735, 'OPR': 54.259, 'Auto': 10.898, 'CCWM': -28.632, 'TeamName': 'Hornet Silver'}, {'TeamNum': 20204, 'OPR': 46.893, 'Auto': 12.352, 'CCWM': -9.758, 'TeamName': 'Charging Pioneers'}, {'TeamNum': 13615, 'OPR': 25.818, 'Auto': 16.078, 'CCWM': -37.703, 'TeamName': 'RoboRams'}, {'TeamNum': 5387, 'OPR': 25.241, 'Auto': 13.975, 'CCWM': -29.344, 'TeamName': 'TecHounds'}, {'TeamNum': 10582, 'OPR': 19.81, 'Auto': -5.339, 'CCWM': -14.101, 'TeamName': 'Emerald Knights'}, {'TeamNum': 12806, 'OPR': 14.499, 'Auto': 12.984, 'CCWM': -55.913, 'TeamName': 'Roboken'}, {'TeamNum': 4347, 'OPR': 5.786, 'Auto': -2.751, 'CCWM': -66.634, 'TeamName': 'NanoGurus'}]

i 3
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-34E604F4-C7E1-40C4-A26E-8DA02D0F5B21")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-38753090-585C-4B04-AC91-3B452E1C4F35")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-13DE93C2-BCD2-420A-BAFC-ED9DADA58258")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-B085ABCD-AD2A-4344-8A7C-D3EAA7F6E291")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-8303D6B5-3700-4B06-BF79-9A322AB97425")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-FE65C3C8-8E3E-4A7F-A821-0120C97F7281")>]
https://ftc-events.firstinspires.org/2022/USMICMP2WF/qualifications
{'5957', '11717', '8478', '17155', '7253', '6079', '21456', '12722', '11231', '6134', '16714', '13684', '19787', '16297', '21427', '10035', '17066', '6255', '22415', '14706', '13643', '20332', '21340', '13733', '16671', '13462', '11520', '10137', '13106', '12862', '19940', '22307', '11129', '20511', '14739', '6294'}
{'5957', '11717', '8478', '17155', '7253', '6079', '21456', '12722', '11231', '6134', '16714', '13684', '19787', '16297', '21427', '10035', '17066', '6255', '22415', '14706', '13643', '20332', '21340', '13733', '16671', '13462', '11520', '10137', '13106', '12862', '19940', '22307', '11129', '20511', '14739', '6294'}
[{'TeamNum': 13462, 'OPR': 109.687, 'Auto': 30.161, 'CCWM': 71.776, 'TeamName': 'Digital Owls'}, {'TeamNum': 14706, 'OPR': 106.886, 'Auto': 24.592, 'CCWM': 24.616, 'TeamName': 'Armada Pi-Gears'}, {'TeamNum': 14739, 'OPR': 97.34, 'Auto': 14.457, 'CCWM': 31.396, 'TeamName': 'Metal Benders'}, {'TeamNum': 20332, 'OPR': 97.21, 'Auto': 26.859, 'CCWM': 27.661, 'TeamName': 'Just Add Logic'}, {'TeamNum': 11231, 'OPR': 94.572, 'Auto': 22.024, 'CCWM': 20.766, 'TeamName': 'Cyborg Cats'}, {'TeamNum': 7253, 'OPR': 94.443, 'Auto': 21.669, 'CCWM': 43.748, 'TeamName': 'Raging Robots'}, {'TeamNum': 21456, 'OPR': 92.63, 'Auto': 21.783, 'CCWM': 3.062, 'TeamName': 'Amphibious Army'}, {'TeamNum': 22415, 'OPR': 90.883, 'Auto': 29.016, 'CCWM': -9.676, 'TeamName': 'Robo Toasters Blue'}, {'TeamNum': 11129, 'OPR': 87.614, 'Auto': 36.341, 'CCWM': 4.376, 'TeamName': 'Novi Robotitans'}, {'TeamNum': 13733, 'OPR': 86.281, 'Auto': 18.225, 'CCWM': 28.835, 'TeamName': 'Electric Bacon'}, {'TeamNum': 17066, 'OPR': 82.531, 'Auto': 24.22, 'CCWM': -16.488, 'TeamName': 'Cirtronic'}, {'TeamNum': 10035, 'OPR': 82.046, 'Auto': 23.343, 'CCWM': 52.679, 'TeamName': 'Robo Rangers'}, {'TeamNum': 13106, 'OPR': 80.579, 'Auto': 22.848, 'CCWM': -11.154, 'TeamName': 'Walnut Creek RoboHawks'}, {'TeamNum': 5957, 'OPR': 80.043, 'Auto': 25.987, 'CCWM': -2.288, 'TeamName': 'Sonic Eagles'}, {'TeamNum': 16671, 'OPR': 79.739, 'Auto': 27.629, 'CCWM': 44.19, 'TeamName': 'Northville Broncobots'}, {'TeamNum': 19940, 'OPR': 79.668, 'Auto': 14.781, 'CCWM': 14.443, 'TeamName': 'TechoRaptors'}, {'TeamNum': 17155, 'OPR': 78.699, 'Auto': 17.564, 'CCWM': 5.356, 'TeamName': 'Baker Dynamics'}, {'TeamNum': 12722, 'OPR': 76.912, 'Auto': 27.191, 'CCWM': 9.57, 'TeamName': 'The Viking Warriors'}, {'TeamNum': 13643, 'OPR': 75.945, 'Auto': 19.214, 'CCWM': 0.594, 'TeamName': 'Rebel Wreckers 13643'}, {'TeamNum': 20511, 'OPR': 74.738, 'Auto': 14.874, 'CCWM': 1.644, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 12862, 'OPR': 74.628, 'Auto': 19.155, 'CCWM': -42.089, 'TeamName': 'Power Dragons'}, {'TeamNum': 8478, 'OPR': 72.158, 'Auto': 24.111, 'CCWM': -3.626, 'TeamName': 'E-Bots'}, {'TeamNum': 11717, 'OPR': 71.425, 'Auto': 14.579, 'CCWM': -13.864, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 6294, 'OPR': 66.901, 'Auto': 25.193, 'CCWM': 9.311, 'TeamName': 'Atomic Toads'}, {'TeamNum': 16714, 'OPR': 64.929, 'Auto': 19.757, 'CCWM': -10.132, 'TeamName': 'Dread Bolts'}, {'TeamNum': 21340, 'OPR': 63.776, 'Auto': 15.572, 'CCWM': 4.256, 'TeamName': 'Crimson Claws'}, {'TeamNum': 13684, 'OPR': 60.626, 'Auto': 22.364, 'CCWM': -48.031, 'TeamName': 'Infinity Tech'}, {'TeamNum': 11520, 'OPR': 56.386, 'Auto': 16.247, 'CCWM': 10.995, 'TeamName': 'Omegabots 11520'}, {'TeamNum': 6134, 'OPR': 55.916, 'Auto': 21.218, 'CCWM': -25.198, 'TeamName': 'Black Frogs'}, {'TeamNum': 16297, 'OPR': 43.112, 'Auto': -2.198, 'CCWM': -26.603, 'TeamName': 'Dragon Tech'}, {'TeamNum': 6079, 'OPR': 41.916, 'Auto': 9.429, 'CCWM': -28.865, 'TeamName': 'Bionic Broncos'}, {'TeamNum': 6255, 'OPR': 41.264, 'Auto': 2.119, 'CCWM': -34.999, 'TeamName': 'RoboJackets'}, {'TeamNum': 19787, 'OPR': 40.106, 'Auto': 8.469, 'CCWM': -20.436, 'TeamName': "Rollin' Rebels 19787"}, {'TeamNum': 22307, 'OPR': 38.41, 'Auto': 0.666, 'CCWM': -30.049, 'TeamName': 'Avondale Okapis'}, {'TeamNum': 21427, 'OPR': 17.47, 'Auto': -2.866, 'CCWM': -45.269, 'TeamName': 'Techno Wizards'}, {'TeamNum': 10137, 'OPR': 14.864, 'Auto': 14.406, 'CCWM': -40.512, 'TeamName': 'Emerson RoboEagles'}]
[{'TeamNum': 13462, 'OPR': 109.687, 'Auto': 30.161, 'CCWM': 71.776, 'TeamName': 'Digital Owls'}, {'TeamNum': 14706, 'OPR': 106.886, 'Auto': 24.592, 'CCWM': 24.616, 'TeamName': 'Armada Pi-Gears'}, {'TeamNum': 14739, 'OPR': 97.34, 'Auto': 14.457, 'CCWM': 31.396, 'TeamName': 'Metal Benders'}, {'TeamNum': 20332, 'OPR': 97.21, 'Auto': 26.859, 'CCWM': 27.661, 'TeamName': 'Just Add Logic'}, {'TeamNum': 11231, 'OPR': 94.572, 'Auto': 22.024, 'CCWM': 20.766, 'TeamName': 'Cyborg Cats'}, {'TeamNum': 7253, 'OPR': 94.443, 'Auto': 21.669, 'CCWM': 43.748, 'TeamName': 'Raging Robots'}, {'TeamNum': 21456, 'OPR': 92.63, 'Auto': 21.783, 'CCWM': 3.062, 'TeamName': 'Amphibious Army'}, {'TeamNum': 22415, 'OPR': 90.883, 'Auto': 29.016, 'CCWM': -9.676, 'TeamName': 'Robo Toasters Blue'}, {'TeamNum': 11129, 'OPR': 87.614, 'Auto': 36.341, 'CCWM': 4.376, 'TeamName': 'Novi Robotitans'}, {'TeamNum': 13733, 'OPR': 86.281, 'Auto': 18.225, 'CCWM': 28.835, 'TeamName': 'Electric Bacon'}, {'TeamNum': 17066, 'OPR': 82.531, 'Auto': 24.22, 'CCWM': -16.488, 'TeamName': 'Cirtronic'}, {'TeamNum': 10035, 'OPR': 82.046, 'Auto': 23.343, 'CCWM': 52.679, 'TeamName': 'Robo Rangers'}, {'TeamNum': 13106, 'OPR': 80.579, 'Auto': 22.848, 'CCWM': -11.154, 'TeamName': 'Walnut Creek RoboHawks'}, {'TeamNum': 5957, 'OPR': 80.043, 'Auto': 25.987, 'CCWM': -2.288, 'TeamName': 'Sonic Eagles'}, {'TeamNum': 16671, 'OPR': 79.739, 'Auto': 27.629, 'CCWM': 44.19, 'TeamName': 'Northville Broncobots'}, {'TeamNum': 19940, 'OPR': 79.668, 'Auto': 14.781, 'CCWM': 14.443, 'TeamName': 'TechoRaptors'}, {'TeamNum': 17155, 'OPR': 78.699, 'Auto': 17.564, 'CCWM': 5.356, 'TeamName': 'Baker Dynamics'}, {'TeamNum': 12722, 'OPR': 76.912, 'Auto': 27.191, 'CCWM': 9.57, 'TeamName': 'The Viking Warriors'}, {'TeamNum': 13643, 'OPR': 75.945, 'Auto': 19.214, 'CCWM': 0.594, 'TeamName': 'Rebel Wreckers 13643'}, {'TeamNum': 20511, 'OPR': 74.738, 'Auto': 14.874, 'CCWM': 1.644, 'TeamName': 'Bionic Bulldogs'}, {'TeamNum': 12862, 'OPR': 74.628, 'Auto': 19.155, 'CCWM': -42.089, 'TeamName': 'Power Dragons'}, {'TeamNum': 8478, 'OPR': 72.158, 'Auto': 24.111, 'CCWM': -3.626, 'TeamName': 'E-Bots'}, {'TeamNum': 11717, 'OPR': 71.425, 'Auto': 14.579, 'CCWM': -13.864, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 6294, 'OPR': 66.901, 'Auto': 25.193, 'CCWM': 9.311, 'TeamName': 'Atomic Toads'}, {'TeamNum': 16714, 'OPR': 64.929, 'Auto': 19.757, 'CCWM': -10.132, 'TeamName': 'Dread Bolts'}, {'TeamNum': 21340, 'OPR': 63.776, 'Auto': 15.572, 'CCWM': 4.256, 'TeamName': 'Crimson Claws'}, {'TeamNum': 13684, 'OPR': 60.626, 'Auto': 22.364, 'CCWM': -48.031, 'TeamName': 'Infinity Tech'}, {'TeamNum': 11520, 'OPR': 56.386, 'Auto': 16.247, 'CCWM': 10.995, 'TeamName': 'Omegabots 11520'}, {'TeamNum': 6134, 'OPR': 55.916, 'Auto': 21.218, 'CCWM': -25.198, 'TeamName': 'Black Frogs'}, {'TeamNum': 16297, 'OPR': 43.112, 'Auto': -2.198, 'CCWM': -26.603, 'TeamName': 'Dragon Tech'}, {'TeamNum': 6079, 'OPR': 41.916, 'Auto': 9.429, 'CCWM': -28.865, 'TeamName': 'Bionic Broncos'}, {'TeamNum': 6255, 'OPR': 41.264, 'Auto': 2.119, 'CCWM': -34.999, 'TeamName': 'RoboJackets'}, {'TeamNum': 19787, 'OPR': 40.106, 'Auto': 8.469, 'CCWM': -20.436, 'TeamName': "Rollin' Rebels 19787"}, {'TeamNum': 22307, 'OPR': 38.41, 'Auto': 0.666, 'CCWM': -30.049, 'TeamName': 'Avondale Okapis'}, {'TeamNum': 21427, 'OPR': 17.47, 'Auto': -2.866, 'CCWM': -45.269, 'TeamName': 'Techno Wizards'}, {'TeamNum': 10137, 'OPR': 14.864, 'Auto': 14.406, 'CCWM': -40.512, 'TeamName': 'Emerson RoboEagles'}]

https://ftc-events.firstinspires.org/2022/USMICMP2MC/qualifications
{'5291', '8487', '15004', '8579', '19949', '17993', '21791', '9819', '16883', '10136', '14815', '10016', '13019', '14757', '16536', '7215', '14670', '8531', '11254', '19923', '17181', '10698', '15638', '21363', '14638', '8777', '8845', '15256', '21331', '18954', '7043', '14010', '7252', '22308', '13999', '18474'}
{'5291', '8487', '15004', '8579', '19949', '17993', '21791', '9819', '16883', '10136', '14815', '10016', '13019', '14757', '16536', '7215', '14670', '8531', '11254', '19923', '17181', '10698', '15638', '21363', '14638', '8777', '8845', '15256', '21331', '18954', '7043', '14010', '7252', '22308', '13999', '18474'}
[{'TeamNum': 15004, 'OPR': 126.086, 'Auto': 33.461, 'CCWM': 45.525, 'TeamName': 'Tech KNOW Logic'}, {'TeamNum': 7252, 'OPR': 109.499, 'Auto': 34.127, 'CCWM': 27.198, 'TeamName': 'Vicious Volts'}, {'TeamNum': 10016, 'OPR': 101.935, 'Auto': 22.867, 'CCWM': 37.369, 'TeamName': 'Clarkston RoboWolves'}, {'TeamNum': 14757, 'OPR': 101.695, 'Auto': 19.24, 'CCWM': 63.503, 'TeamName': 'The SashaBRAWLERS'}, {'TeamNum': 17181, 'OPR': 92.021, 'Auto': 27.237, 'CCWM': 26.591, 'TeamName': 'Vibranium Vikings'}, {'TeamNum': 11254, 'OPR': 90.887, 'Auto': 24.457, 'CCWM': 42.05, 'TeamName': 'Robo Rhinos'}, {'TeamNum': 15256, 'OPR': 90.778, 'Auto': 26.787, 'CCWM': 24.315, 'TeamName': 'Techno Knights'}, {'TeamNum': 16883, 'OPR': 88.063, 'Auto': 30.181, 'CCWM': 43.18, 'TeamName': 'DinoByte!'}, {'TeamNum': 15638, 'OPR': 81.082, 'Auto': 20.993, 'CCWM': -3.148, 'TeamName': 'STEAM Bots'}, {'TeamNum': 19949, 'OPR': 79.832, 'Auto': 23.468, 'CCWM': 39.21, 'TeamName': 'Jr. Byting Bulldogs Green'}, {'TeamNum': 21791, 'OPR': 76.772, 'Auto': 24.271, 'CCWM': 15.467, 'TeamName': 'G-Force'}, {'TeamNum': 8579, 'OPR': 76.542, 'Auto': 17.814, 'CCWM': 13.181, 'TeamName': 'Classical Engineers'}, {'TeamNum': 9819, 'OPR': 74.59, 'Auto': 14.197, 'CCWM': 35.111, 'TeamName': 'RoboRats'}, {'TeamNum': 13019, 'OPR': 72.391, 'Auto': 23.248, 'CCWM': 19.648, 'TeamName': 'Platinum Panthers 13019'}, {'TeamNum': 18474, 'OPR': 71.841, 'Auto': 15.717, 'CCWM': 15.58, 'TeamName': 'The Robotic Bulldogs'}, {'TeamNum': 21363, 'OPR': 71.806, 'Auto': 20.405, 'CCWM': 5.373, 'TeamName': 'TorqueNados JV'}, {'TeamNum': 14638, 'OPR': 70.786, 'Auto': 12.896, 'CCWM': 25.619, 'TeamName': 'Infinity & Beyond'}, {'TeamNum': 8845, 'OPR': 63.794, 'Auto': 16.947, 'CCWM': -17.581, 'TeamName': 'The Wild Bees'}, {'TeamNum': 5291, 'OPR': 62.174, 'Auto': 8.993, 'CCWM': 20.984, 'TeamName': 'TOWR The Oxford Wildcats Robotics'}, {'TeamNum': 16536, 'OPR': 60.072, 'Auto': 14.06, 'CCWM': -14.479, 'TeamName': 'M3B'}, {'TeamNum': 10136, 'OPR': 57.051, 'Auto': 16.696, 'CCWM': -1.321, 'TeamName': 'Frost RoboFalcons'}, {'TeamNum': 17993, 'OPR': 56.153, 'Auto': 6.296, 'CCWM': 12.763, 'TeamName': 'Robot Crusaders'}, {'TeamNum': 14815, 'OPR': 55.502, 'Auto': 12.474, 'CCWM': -22.729, 'TeamName': 'HackBytes'}, {'TeamNum': 8531, 'OPR': 55.038, 'Auto': 15.159, 'CCWM': -20.693, 'TeamName': 'GA Bots'}, {'TeamNum': 18954, 'OPR': 50.471, 'Auto': 7.13, 'CCWM': -12.222, 'TeamName': 'Viking Tech'}, {'TeamNum': 14670, 'OPR': 49.841, 'Auto': 14.946, 'CCWM': -23.371, 'TeamName': 'TerrorBytes'}, {'TeamNum': 10698, 'OPR': 44.116, 'Auto': 12.838, 'CCWM': -8.906, 'TeamName': 'Mad Mechanics '}, {'TeamNum': 21331, 'OPR': 42.907, 'Auto': 10.864, 'CCWM': -40.956, 'TeamName': 'Silver Hornets'}, {'TeamNum': 14010, 'OPR': 40.003, 'Auto': 16.288, 'CCWM': -16.936, 'TeamName': 'Techno Phoenix '}, {'TeamNum': 22308, 'OPR': 39.471, 'Auto': 5.848, 'CCWM': -21.065, 'TeamName': 'Avondale Penguins'}, {'TeamNum': 7215, 'OPR': 35.509, 'Auto': 9.372, 'CCWM': -39.334, 'TeamName': 'Turning Gears'}, {'TeamNum': 13999, 'OPR': 30.945, 'Auto': 0.596, 'CCWM': -54.494, 'TeamName': 'P3A Robotechs'}, {'TeamNum': 8487, 'OPR': 30.904, 'Auto': 9.049, 'CCWM': -13.534, 'TeamName': 'Robo Toasters Orange'}, {'TeamNum': 8777, 'OPR': 24.597, 'Auto': -5.299, 'CCWM': -46.789, 'TeamName': 'The Goonies'}, {'TeamNum': 7043, 'OPR': 14.226, 'Auto': 15.783, 'CCWM': -62.378, 'TeamName': 'Golden Gears'}, {'TeamNum': 19923, 'OPR': -19.547, 'Auto': -4.237, 'CCWM': -92.731, 'TeamName': 'Thunderbirds'}]
[{'TeamNum': 15004, 'OPR': 126.086, 'Auto': 33.461, 'CCWM': 45.525, 'TeamName': 'Tech KNOW Logic'}, {'TeamNum': 7252, 'OPR': 109.499, 'Auto': 34.127, 'CCWM': 27.198, 'TeamName': 'Vicious Volts'}, {'TeamNum': 10016, 'OPR': 101.935, 'Auto': 22.867, 'CCWM': 37.369, 'TeamName': 'Clarkston RoboWolves'}, {'TeamNum': 14757, 'OPR': 101.695, 'Auto': 19.24, 'CCWM': 63.503, 'TeamName': 'The SashaBRAWLERS'}, {'TeamNum': 17181, 'OPR': 92.021, 'Auto': 27.237, 'CCWM': 26.591, 'TeamName': 'Vibranium Vikings'}, {'TeamNum': 11254, 'OPR': 90.887, 'Auto': 24.457, 'CCWM': 42.05, 'TeamName': 'Robo Rhinos'}, {'TeamNum': 15256, 'OPR': 90.778, 'Auto': 26.787, 'CCWM': 24.315, 'TeamName': 'Techno Knights'}, {'TeamNum': 16883, 'OPR': 88.063, 'Auto': 30.181, 'CCWM': 43.18, 'TeamName': 'DinoByte!'}, {'TeamNum': 15638, 'OPR': 81.082, 'Auto': 20.993, 'CCWM': -3.148, 'TeamName': 'STEAM Bots'}, {'TeamNum': 19949, 'OPR': 79.832, 'Auto': 23.468, 'CCWM': 39.21, 'TeamName': 'Jr. Byting Bulldogs Green'}, {'TeamNum': 21791, 'OPR': 76.772, 'Auto': 24.271, 'CCWM': 15.467, 'TeamName': 'G-Force'}, {'TeamNum': 8579, 'OPR': 76.542, 'Auto': 17.814, 'CCWM': 13.181, 'TeamName': 'Classical Engineers'}, {'TeamNum': 9819, 'OPR': 74.59, 'Auto': 14.197, 'CCWM': 35.111, 'TeamName': 'RoboRats'}, {'TeamNum': 13019, 'OPR': 72.391, 'Auto': 23.248, 'CCWM': 19.648, 'TeamName': 'Platinum Panthers 13019'}, {'TeamNum': 18474, 'OPR': 71.841, 'Auto': 15.717, 'CCWM': 15.58, 'TeamName': 'The Robotic Bulldogs'}, {'TeamNum': 21363, 'OPR': 71.806, 'Auto': 20.405, 'CCWM': 5.373, 'TeamName': 'TorqueNados JV'}, {'TeamNum': 14638, 'OPR': 70.786, 'Auto': 12.896, 'CCWM': 25.619, 'TeamName': 'Infinity & Beyond'}, {'TeamNum': 8845, 'OPR': 63.794, 'Auto': 16.947, 'CCWM': -17.581, 'TeamName': 'The Wild Bees'}, {'TeamNum': 5291, 'OPR': 62.174, 'Auto': 8.993, 'CCWM': 20.984, 'TeamName': 'TOWR The Oxford Wildcats Robotics'}, {'TeamNum': 16536, 'OPR': 60.072, 'Auto': 14.06, 'CCWM': -14.479, 'TeamName': 'M3B'}, {'TeamNum': 10136, 'OPR': 57.051, 'Auto': 16.696, 'CCWM': -1.321, 'TeamName': 'Frost RoboFalcons'}, {'TeamNum': 17993, 'OPR': 56.153, 'Auto': 6.296, 'CCWM': 12.763, 'TeamName': 'Robot Crusaders'}, {'TeamNum': 14815, 'OPR': 55.502, 'Auto': 12.474, 'CCWM': -22.729, 'TeamName': 'HackBytes'}, {'TeamNum': 8531, 'OPR': 55.038, 'Auto': 15.159, 'CCWM': -20.693, 'TeamName': 'GA Bots'}, {'TeamNum': 18954, 'OPR': 50.471, 'Auto': 7.13, 'CCWM': -12.222, 'TeamName': 'Viking Tech'}, {'TeamNum': 14670, 'OPR': 49.841, 'Auto': 14.946, 'CCWM': -23.371, 'TeamName': 'TerrorBytes'}, {'TeamNum': 10698, 'OPR': 44.116, 'Auto': 12.838, 'CCWM': -8.906, 'TeamName': 'Mad Mechanics '}, {'TeamNum': 21331, 'OPR': 42.907, 'Auto': 10.864, 'CCWM': -40.956, 'TeamName': 'Silver Hornets'}, {'TeamNum': 14010, 'OPR': 40.003, 'Auto': 16.288, 'CCWM': -16.936, 'TeamName': 'Techno Phoenix '}, {'TeamNum': 22308, 'OPR': 39.471, 'Auto': 5.848, 'CCWM': -21.065, 'TeamName': 'Avondale Penguins'}, {'TeamNum': 7215, 'OPR': 35.509, 'Auto': 9.372, 'CCWM': -39.334, 'TeamName': 'Turning Gears'}, {'TeamNum': 13999, 'OPR': 30.945, 'Auto': 0.596, 'CCWM': -54.494, 'TeamName': 'P3A Robotechs'}, {'TeamNum': 8487, 'OPR': 30.904, 'Auto': 9.049, 'CCWM': -13.534, 'TeamName': 'Robo Toasters Orange'}, {'TeamNum': 8777, 'OPR': 24.597, 'Auto': -5.299, 'CCWM': -46.789, 'TeamName': 'The Goonies'}, {'TeamNum': 7043, 'OPR': 14.226, 'Auto': 15.783, 'CCWM': -62.378, 'TeamName': 'Golden Gears'}, {'TeamNum': 19923, 'OPR': -19.547, 'Auto': -4.237, 'CCWM': -92.731, 'TeamName': 'Thunderbirds'}]
i 4
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-90C80A77-41AC-4CF0-AC0A-62879A5E9BAD")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-48481A70-6792-4B37-B393-0742238825FF")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-DF135BB3-DC6C-4AAC-9D3E-1EC2E30B0A88")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-87641940-EDCA-4DBF-85F9-A98982EFDEC4")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-1A6A7C9F-0FF2-4789-9C02-EA3BD4BF3DD4")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-B44ED39A-BC5F-4EEA-9975-42DA6434EB6B")>]
https://ftc-events.firstinspires.org/2022/USMICMPWF/qualifications

{'8027', '13702', '11244', '21906', '21672', '5384', '15301', '6494', '16607', '10024', '5292', '15465', '5383', '10477', '10031', '6155', '10062', '22313', '15270', '15182', '10723', '7643', '21453', '10309', '10644', '8646', '15815', '19561', '5386', '14649', '7031', '12845', '19925', '5618', '11266', '10601'}
{'8027', '13702', '11244', '21906', '21672', '5384', '15301', '6494', '16607', '10024', '5292', '15465', '5383', '10477', '10031', '6155', '10062', '22313', '15270', '15182', '10723', '7643', '21453', '10309', '10644', '8646', '15815', '19561', '5386', '14649', '7031', '12845', '19925', '5618', '11266', '10601'}
[{'TeamNum': 19561, 'OPR': 141.112, 'Auto': 39.682, 'CCWM': 32.77, 'TeamName': 'Tiger Tech Black'}, {'TeamNum': 10644, 'OPR': 128.805, 'Auto': 37.334, 'CCWM': 62.614, 'TeamName': 'CyBugs'}, {'TeamNum': 7643, 'OPR': 126.847, 'Auto': 43.284, 'CCWM': 68.057, 'TeamName': 'Tiger Tech Orange'}, {'TeamNum': 15465, 'OPR': 110.325, 'Auto': 27.825, 'CCWM': 33.644, 'TeamName': 'Team KRASH'}, {'TeamNum': 13702, 'OPR': 108.986, 'Auto': 32.098, 'CCWM': 25.666, 'TeamName': 'Joe Bots - White'}, {'TeamNum': 21672, 'OPR': 108.454, 'Auto': 28.992, 'CCWM': 3.268, 'TeamName': 'More Fabricators'}, {'TeamNum': 11244, 'OPR': 107.241, 'Auto': 25.092, 'CCWM': 19.135, 'TeamName': 'ELITE FROGS'}, {'TeamNum': 6494, 'OPR': 91.054, 'Auto': 19.719, 'CCWM': 43.951, 'TeamName': 'Control Freaks WHITE'}, {'TeamNum': 8027, 'OPR': 87.105, 'Auto': 24.349, 'CCWM': -18.299, 'TeamName': 'Twisted Devils Blue'}, {'TeamNum': 8646, 'OPR': 84.987, 'Auto': 23.255, 'CCWM': 4.574, 'TeamName': 'Team KAOS'}, {'TeamNum': 15815, 'OPR': 83.922, 'Auto': 20.311, 'CCWM': 48.492, 'TeamName': 'DCS Defender Robotics'}, {'TeamNum': 10477, 'OPR': 81.35, 'Auto': 15.505, 'CCWM': 7.458, 'TeamName': 'Rapid Robots'}, {'TeamNum': 7031, 'OPR': 79.635, 'Auto': 18.557, 'CCWM': 11.795, 'TeamName': 'Battle Blazers'}, {'TeamNum': 5618, 'OPR': 79.021, 'Auto': 20.029, 'CCWM': 30.51, 'TeamName': 'Control Freaks RED'}, {'TeamNum': 19925, 'OPR': 72.179, 'Auto': 12.473, 'CCWM': -7.816, 'TeamName': 'Techno Titans'}, {'TeamNum': 22313, 'OPR': 72.171, 'Auto': 21.64, 'CCWM': -6.55, 'TeamName': 'CybOrioles Orange'}, {'TeamNum': 5386, 'OPR': 71.101, 'Auto': 23.377, 'CCWM': 20.851, 'TeamName': 'Fabricators'}, {'TeamNum': 10024, 'OPR': 68.109, 'Auto': 25.758, 'CCWM': -5.741, 'TeamName': 'Twisted Devils Black'}, {'TeamNum': 5383, 'OPR': 67.614, 'Auto': 18.194, 'CCWM': 24.042, 'TeamName': 'Neutrinos Breaking the Laws of Physics'}, {'TeamNum': 10601, 'OPR': 66.799, 'Auto': 18.674, 'CCWM': -10.539, 'TeamName': 'CBA RoboKings'}, {'TeamNum': 10309, 'OPR': 66.548, 'Auto': 10.121, 'CCWM': -10.2, 'TeamName': 'Jefferson TechnoHuskies'}, {'TeamNum': 10723, 'OPR': 65.695, 'Auto': 19.367, 'CCWM': -23.82, 'TeamName': 'SnowBots Blue'}, {'TeamNum': 21906, 'OPR': 65.472, 'Auto': 20.199, 'CCWM': -26.145, 'TeamName': 'Red Storm Robotics-Gold'}, {'TeamNum': 15270, 'OPR': 60.952, 'Auto': 25.726, 'CCWM': -16.473, 'TeamName': 'SnowBots Red'}, {'TeamNum': 16607, 'OPR': 60.568, 'Auto': 15.591, 'CCWM': -9.349, 'TeamName': 'Midnight Creators'}, {'TeamNum': 21453, 'OPR': 59.042, 'Auto': 15.463, 'CCWM': -16.336, 'TeamName': 'Robotics Ribbiters'}, {'TeamNum': 10062, 'OPR': 55.979, 'Auto': 11.86, 'CCWM': -27.119, 'TeamName': 'Robogators'}, {'TeamNum': 12845, 'OPR': 54.912, 'Auto': 24.155, 'CCWM': -61.021, 'TeamName': 'THE METEORS'}, {'TeamNum': 6155, 'OPR': 52.274, 'Auto': 20.949, 'CCWM': 1.916, 'TeamName': 'Birdhouse Frogs'}, {'TeamNum': 15301, 'OPR': 51.849, 'Auto': -2.609, 'CCWM': -9.371, 'TeamName': 'Valkyries'}, {'TeamNum': 14649, 'OPR': 49.843, 'Auto': 7.835, 'CCWM': -21.464, 'TeamName': 'WBSD FTC - Anchorbots'}, {'TeamNum': 15182, 'OPR': 48.735, 'Auto': 7.308, 'CCWM': -17.085, 'TeamName': 'Magmatrons'}, {'TeamNum': 11266, 'OPR': 47.776, 'Auto': 15.047, 'CCWM': -48.931, 'TeamName': 'River Rat Robotics'}, {'TeamNum': 5384, 'OPR': 42.06, 'Auto': 21.457, 'CCWM': -12.512, 'TeamName': 'Emergency Situation Evacuate Now'}, {'TeamNum': 10031, 'OPR': 30.752, 'Auto': 14.263, 'CCWM': -44.584, 'TeamName': 'Red Storm Robotics-Blue'}, {'TeamNum': 5292, 'OPR': 30.729, 'Auto': 6.453, 'CCWM': -45.385, 'TeamName': 'Red Storm Robotics-White'}]
[{'TeamNum': 19561, 'OPR': 141.112, 'Auto': 39.682, 'CCWM': 32.77, 'TeamName': 'Tiger Tech Black'}, {'TeamNum': 10644, 'OPR': 128.805, 'Auto': 37.334, 'CCWM': 62.614, 'TeamName': 'CyBugs'}, {'TeamNum': 7643, 'OPR': 126.847, 'Auto': 43.284, 'CCWM': 68.057, 'TeamName': 'Tiger Tech Orange'}, {'TeamNum': 15465, 'OPR': 110.325, 'Auto': 27.825, 'CCWM': 33.644, 'TeamName': 'Team KRASH'}, {'TeamNum': 13702, 'OPR': 108.986, 'Auto': 32.098, 'CCWM': 25.666, 'TeamName': 'Joe Bots - White'}, {'TeamNum': 21672, 'OPR': 108.454, 'Auto': 28.992, 'CCWM': 3.268, 'TeamName': 'More Fabricators'}, {'TeamNum': 11244, 'OPR': 107.241, 'Auto': 25.092, 'CCWM': 19.135, 'TeamName': 'ELITE FROGS'}, {'TeamNum': 6494, 'OPR': 91.054, 'Auto': 19.719, 'CCWM': 43.951, 'TeamName': 'Control Freaks WHITE'}, {'TeamNum': 8027, 'OPR': 87.105, 'Auto': 24.349, 'CCWM': -18.299, 'TeamName': 'Twisted Devils Blue'}, {'TeamNum': 8646, 'OPR': 84.987, 'Auto': 23.255, 'CCWM': 4.574, 'TeamName': 'Team KAOS'}, {'TeamNum': 15815, 'OPR': 83.922, 'Auto': 20.311, 'CCWM': 48.492, 'TeamName': 'DCS Defender Robotics'}, {'TeamNum': 10477, 'OPR': 81.35, 'Auto': 15.505, 'CCWM': 7.458, 'TeamName': 'Rapid Robots'}, {'TeamNum': 7031, 'OPR': 79.635, 'Auto': 18.557, 'CCWM': 11.795, 'TeamName': 'Battle Blazers'}, {'TeamNum': 5618, 'OPR': 79.021, 'Auto': 20.029, 'CCWM': 30.51, 'TeamName': 'Control Freaks RED'}, {'TeamNum': 19925, 'OPR': 72.179, 'Auto': 12.473, 'CCWM': -7.816, 'TeamName': 'Techno Titans'}, {'TeamNum': 22313, 'OPR': 72.171, 'Auto': 21.64, 'CCWM': -6.55, 'TeamName': 'CybOrioles Orange'}, {'TeamNum': 5386, 'OPR': 71.101, 'Auto': 23.377, 'CCWM': 20.851, 'TeamName': 'Fabricators'}, {'TeamNum': 10024, 'OPR': 68.109, 'Auto': 25.758, 'CCWM': -5.741, 'TeamName': 'Twisted Devils Black'}, {'TeamNum': 5383, 'OPR': 67.614, 'Auto': 18.194, 'CCWM': 24.042, 'TeamName': 'Neutrinos Breaking the Laws of Physics'}, {'TeamNum': 10601, 'OPR': 66.799, 'Auto': 18.674, 'CCWM': -10.539, 'TeamName': 'CBA RoboKings'}, {'TeamNum': 10309, 'OPR': 66.548, 'Auto': 10.121, 'CCWM': -10.2, 'TeamName': 'Jefferson TechnoHuskies'}, {'TeamNum': 10723, 'OPR': 65.695, 'Auto': 19.367, 'CCWM': -23.82, 'TeamName': 'SnowBots Blue'}, {'TeamNum': 21906, 'OPR': 65.472, 'Auto': 20.199, 'CCWM': -26.145, 'TeamName': 'Red Storm Robotics-Gold'}, {'TeamNum': 15270, 'OPR': 60.952, 'Auto': 25.726, 'CCWM': -16.473, 'TeamName': 'SnowBots Red'}, {'TeamNum': 16607, 'OPR': 60.568, 'Auto': 15.591, 'CCWM': -9.349, 'TeamName': 'Midnight Creators'}, {'TeamNum': 21453, 'OPR': 59.042, 'Auto': 15.463, 'CCWM': -16.336, 'TeamName': 'Robotics Ribbiters'}, {'TeamNum': 10062, 'OPR': 55.979, 'Auto': 11.86, 'CCWM': -27.119, 'TeamName': 'Robogators'}, {'TeamNum': 12845, 'OPR': 54.912, 'Auto': 24.155, 'CCWM': -61.021, 'TeamName': 'THE METEORS'}, {'TeamNum': 6155, 'OPR': 52.274, 'Auto': 20.949, 'CCWM': 1.916, 'TeamName': 'Birdhouse Frogs'}, {'TeamNum': 15301, 'OPR': 51.849, 'Auto': -2.609, 'CCWM': -9.371, 'TeamName': 'Valkyries'}, {'TeamNum': 14649, 'OPR': 49.843, 'Auto': 7.835, 'CCWM': -21.464, 'TeamName': 'WBSD FTC - Anchorbots'}, {'TeamNum': 15182, 'OPR': 48.735, 'Auto': 7.308, 'CCWM': -17.085, 'TeamName': 'Magmatrons'}, {'TeamNum': 11266, 'OPR': 47.776, 'Auto': 15.047, 'CCWM': -48.931, 'TeamName': 'River Rat Robotics'}, {'TeamNum': 5384, 'OPR': 42.06, 'Auto': 21.457, 'CCWM': -12.512, 'TeamName': 'Emergency Situation Evacuate Now'}, {'TeamNum': 10031, 'OPR': 30.752, 'Auto': 14.263, 'CCWM': -44.584, 'TeamName': 'Red Storm Robotics-Blue'}, {'TeamNum': 5292, 'OPR': 30.729, 'Auto': 6.453, 'CCWM': -45.385, 'TeamName': 'Red Storm Robotics-White'}]
https://ftc-events.firstinspires.org/2022/USMICMPMC/qualifications
{'9087', '10180', '8513', '15104', '15229', '10104', '12603', '5290', '10255', '11618', '20245', '11193', '15555', '10615', '11855', '5980', '8621', '19770', '13917', '21914', '19429', '11691', '8580', '13598', '20142', '8533', '21482', '11228', '15357', '9931', '15358', '16957', '14353', '11846', '16646', '11940'}
{'9087', '10180', '8513', '15104', '15229', '10104', '12603', '5290', '10255', '11618', '20245', '11193', '15555', '10615', '11855', '5980', '8621', '19770', '13917', '21914', '19429', '11691', '8580', '13598', '20142', '8533', '21482', '11228', '15357', '9931', '15358', '16957', '14353', '11846', '16646', '11940'}
[{'TeamNum': 16646, 'OPR': 128.189, 'Auto': 31.05, 'CCWM': 55.651, 'TeamName': 'ZooBOTix Linden Grove'}, {'TeamNum': 10255, 'OPR': 122.438, 'Auto': 37.167, 'CCWM': 79.606, 'TeamName': 'RoboDux'}, {'TeamNum': 19429, 'OPR': 121.827, 'Auto': 37.102, 'CCWM': 62.273, 'TeamName': 'Infrared'}, {'TeamNum': 15104, 'OPR': 110.235, 'Auto': 32.406, 'CCWM': 44.887, 'TeamName': 'Static Eagles'}, {'TeamNum': 14353, 'OPR': 103.817, 'Auto': 32.42, 'CCWM': 65.815, 'TeamName': 'The N.E.R.D.-bots!'}, {'TeamNum': 11228, 'OPR': 102.345, 'Auto': 36.394, 'CCWM': 29.845, 'TeamName': 'OverClucked Bots'}, {'TeamNum': 11855, 'OPR': 102.213, 'Auto': 22.912, 'CCWM': 33.956, 'TeamName': 'Joe Bots - Blue'}, {'TeamNum': 8513, 'OPR': 93.924, 'Auto': 24.375, 'CCWM': -11.895, 'TeamName': 'Joe Bots - Maize'}, {'TeamNum': 11691, 'OPR': 92.496, 'Auto': 26.169, 'CCWM': 29.482, 'TeamName': 'Scripps Dragons'}, {'TeamNum': 10180, 'OPR': 92.372, 'Auto': 22.929, 'CCWM': 24.554, 'TeamName': 'BrainSTEM'}, {'TeamNum': 10615, 'OPR': 88.603, 'Auto': 14.253, 'CCWM': 33.036, 'TeamName': 'Jefferson CyDogs'}, {'TeamNum': 20245, 'OPR': 85.439, 'Auto': 34.957, 'CCWM': -4.903, 'TeamName': 'Ultraviolet'}, {'TeamNum': 8580, 'OPR': 83.044, 'Auto': 27.335, 'CCWM': -13.101, 'TeamName': 'Oakview CyberDragons'}, {'TeamNum': 15358, 'OPR': 80.567, 'Auto': 14.036, 'CCWM': 35.275, 'TeamName': 'BalaBots'}, {'TeamNum': 15555, 'OPR': 77.96, 'Auto': 29.116, 'CCWM': 40.768, 'TeamName': 'S.W.A.R.M.'}, {'TeamNum': 5980, 'OPR': 75.163, 'Auto': 17.757, 'CCWM': 29.804, 'TeamName': 'Titanium Tech Vikes'}, {'TeamNum': 8533, 'OPR': 74.717, 'Auto': 10.897, 'CCWM': -1.176, 'TeamName': 'CSA MS Miners'}, {'TeamNum': 11940, 'OPR': 74.143, 'Auto': 20.578, 'CCWM': -10.42, 'TeamName': 'Cyber Coyotes'}, {'TeamNum': 10104, 'OPR': 73.67, 'Auto': 20.32, 'CCWM': 19.328, 'TeamName': 'That OTHER Team'}, {'TeamNum': 21482, 'OPR': 72.781, 'Auto': 18.449, 'CCWM': 14.108, 'TeamName': 'Robo Challengers'}, {'TeamNum': 9931, 'OPR': 70.586, 'Auto': 19.817, 'CCWM': 32.416, 'TeamName': 'Northeast Viking Vendors'}, {'TeamNum': 15357, 'OPR': 65.627, 'Auto': 19.692, 'CCWM': -19.599, 'TeamName': 'MOre Bots'}, {'TeamNum': 11846, 'OPR': 65.343, 'Auto': 20.383, 'CCWM': 1.064, 'TeamName': 'Wayland Wildcat Cat-a-Tech-Nics'}, {'TeamNum': 11193, 'OPR': 62.895, 'Auto': 13.832, 'CCWM': -20.398, 'TeamName': 'The Flying Dutchbots'}, {'TeamNum': 15229, 'OPR': 62.309, 'Auto': 21.547, 'CCWM': -5.22, 'TeamName': 'Team KUDOS'}, {'TeamNum': 11618, 'OPR': 56.824, 'Auto': 27.83, 'CCWM': -63.821, 'TeamName': 'Chelsea Gremlins'}, {'TeamNum': 16957, 'OPR': 56.313, 'Auto': 19.919, 'CCWM': -31.385, 'TeamName': 'Junior Wolverine Circuit Breakers'}, {'TeamNum': 13917, 'OPR': 54.559, 'Auto': 18.735, 'CCWM': -36.066, 'TeamName': 'ZooBOTix Hillside'}, {'TeamNum': 21914, 'OPR': 54.524, 'Auto': 15.909, 'CCWM': -43.895, 'TeamName': 'Team KARMA'}, {'TeamNum': 9087, 'OPR': 51.794, 'Auto': 15.004, 'CCWM': -36.094, 'TeamName': 'Twisted Devils Green'}, {'TeamNum': 20142, 'OPR': 49.176, 'Auto': 13.994, 'CCWM': -68.874, 'TeamName': 'Walnut Creek CyberHawks'}, {'TeamNum': 13598, 'OPR': 47.157, 'Auto': 12.041, 'CCWM': -25.929, 'TeamName': 'Mo Bots'}, {'TeamNum': 8621, 'OPR': 37.975, 'Auto': 9.17, 'CCWM': -58.858, 'TeamName': 'G3: Geek'}, {'TeamNum': 19770, 'OPR': 36.405, 'Auto': 10.851, 'CCWM': -41.739, 'TeamName': 'JaXon Falcon Works - Maroon'}, {'TeamNum': 12603, 'OPR': 18.792, 'Auto': 5.502, 'CCWM': -73.932, 'TeamName': 'Jefferson Wired Wolves'}, {'TeamNum': 5290, 'OPR': 9.279, 'Auto': 2.652, 'CCWM': -64.565, 'TeamName': 'Steel Eagles'}]
[{'TeamNum': 16646, 'OPR': 128.189, 'Auto': 31.05, 'CCWM': 55.651, 'TeamName': 'ZooBOTix Linden Grove'}, {'TeamNum': 10255, 'OPR': 122.438, 'Auto': 37.167, 'CCWM': 79.606, 'TeamName': 'RoboDux'}, {'TeamNum': 19429, 'OPR': 121.827, 'Auto': 37.102, 'CCWM': 62.273, 'TeamName': 'Infrared'}, {'TeamNum': 15104, 'OPR': 110.235, 'Auto': 32.406, 'CCWM': 44.887, 'TeamName': 'Static Eagles'}, {'TeamNum': 14353, 'OPR': 103.817, 'Auto': 32.42, 'CCWM': 65.815, 'TeamName': 'The N.E.R.D.-bots!'}, {'TeamNum': 11228, 'OPR': 102.345, 'Auto': 36.394, 'CCWM': 29.845, 'TeamName': 'OverClucked Bots'}, {'TeamNum': 11855, 'OPR': 102.213, 'Auto': 22.912, 'CCWM': 33.956, 'TeamName': 'Joe Bots - Blue'}, {'TeamNum': 8513, 'OPR': 93.924, 'Auto': 24.375, 'CCWM': -11.895, 'TeamName': 'Joe Bots - Maize'}, {'TeamNum': 11691, 'OPR': 92.496, 'Auto': 26.169, 'CCWM': 29.482, 'TeamName': 'Scripps Dragons'}, {'TeamNum': 10180, 'OPR': 92.372, 'Auto': 22.929, 'CCWM': 24.554, 'TeamName': 'BrainSTEM'}, {'TeamNum': 10615, 'OPR': 88.603, 'Auto': 14.253, 'CCWM': 33.036, 'TeamName': 'Jefferson CyDogs'}, {'TeamNum': 20245, 'OPR': 85.439, 'Auto': 34.957, 'CCWM': -4.903, 'TeamName': 'Ultraviolet'}, {'TeamNum': 8580, 'OPR': 83.044, 'Auto': 27.335, 'CCWM': -13.101, 'TeamName': 'Oakview CyberDragons'}, {'TeamNum': 15358, 'OPR': 80.567, 'Auto': 14.036, 'CCWM': 35.275, 'TeamName': 'BalaBots'}, {'TeamNum': 15555, 'OPR': 77.96, 'Auto': 29.116, 'CCWM': 40.768, 'TeamName': 'S.W.A.R.M.'}, {'TeamNum': 5980, 'OPR': 75.163, 'Auto': 17.757, 'CCWM': 29.804, 'TeamName': 'Titanium Tech Vikes'}, {'TeamNum': 8533, 'OPR': 74.717, 'Auto': 10.897, 'CCWM': -1.176, 'TeamName': 'CSA MS Miners'}, {'TeamNum': 11940, 'OPR': 74.143, 'Auto': 20.578, 'CCWM': -10.42, 'TeamName': 'Cyber Coyotes'}, {'TeamNum': 10104, 'OPR': 73.67, 'Auto': 20.32, 'CCWM': 19.328, 'TeamName': 'That OTHER Team'}, {'TeamNum': 21482, 'OPR': 72.781, 'Auto': 18.449, 'CCWM': 14.108, 'TeamName': 'Robo Challengers'}, {'TeamNum': 9931, 'OPR': 70.586, 'Auto': 19.817, 'CCWM': 32.416, 'TeamName': 'Northeast Viking Vendors'}, {'TeamNum': 15357, 'OPR': 65.627, 'Auto': 19.692, 'CCWM': -19.599, 'TeamName': 'MOre Bots'}, {'TeamNum': 11846, 'OPR': 65.343, 'Auto': 20.383, 'CCWM': 1.064, 'TeamName': 'Wayland Wildcat Cat-a-Tech-Nics'}, {'TeamNum': 11193, 'OPR': 62.895, 'Auto': 13.832, 'CCWM': -20.398, 'TeamName': 'The Flying Dutchbots'}, {'TeamNum': 15229, 'OPR': 62.309, 'Auto': 21.547, 'CCWM': -5.22, 'TeamName': 'Team KUDOS'}, {'TeamNum': 11618, 'OPR': 56.824, 'Auto': 27.83, 'CCWM': -63.821, 'TeamName': 'Chelsea Gremlins'}, {'TeamNum': 16957, 'OPR': 56.313, 'Auto': 19.919, 'CCWM': -31.385, 'TeamName': 'Junior Wolverine Circuit Breakers'}, {'TeamNum': 13917, 'OPR': 54.559, 'Auto': 18.735, 'CCWM': -36.066, 'TeamName': 'ZooBOTix Hillside'}, {'TeamNum': 21914, 'OPR': 54.524, 'Auto': 15.909, 'CCWM': -43.895, 'TeamName': 'Team KARMA'}, {'TeamNum': 9087, 'OPR': 51.794, 'Auto': 15.004, 'CCWM': -36.094, 'TeamName': 'Twisted Devils Green'}, {'TeamNum': 20142, 'OPR': 49.176, 'Auto': 13.994, 'CCWM': -68.874, 'TeamName': 'Walnut Creek CyberHawks'}, {'TeamNum': 13598, 'OPR': 47.157, 'Auto': 12.041, 'CCWM': -25.929, 'TeamName': 'Mo Bots'}, {'TeamNum': 8621, 'OPR': 37.975, 'Auto': 9.17, 'CCWM': -58.858, 'TeamName': 'G3: Geek'}, {'TeamNum': 19770, 'OPR': 36.405, 'Auto': 10.851, 'CCWM': -41.739, 'TeamName': 'JaXon Falcon Works - Maroon'}, {'TeamNum': 12603, 'OPR': 18.792, 'Auto': 5.502, 'CCWM': -73.932, 'TeamName': 'Jefferson Wired Wolves'}, {'TeamNum': 5290, 'OPR': 9.279, 'Auto': 2.652, 'CCWM': -64.565, 'TeamName': 'Steel Eagles'}]

i 5
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-C825AEA4-272C-4ACF-B04B-3F71DA340574")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-2104D76F-55AA-4419-90A7-2AB6CF14C3B5")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-43ADA6CF-90E1-45B3-99D4-397DF1AB8980")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-21714428-A622-47DD-9AC2-BE9BFE36B56F")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-E4C7665A-F7EE-4F1F-93D5-79A958194DBD")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-539E6A0F-4273-4F69-8C98-EE3C7BF593DC")>]
https://ftc-events.firstinspires.org/2022/CAABABSALTFIN/qualifications
{'10015', '14718', '21594', '20176', '14022', '16932', '14717', '20448', '22873', '22391', '14716', '16595', '20038', '22029', '22212', '22531', '14021', '20718', '21595'}
{'10015', '14718', '21594', '20176', '14022', '16932', '14717', '20448', '22873', '22391', '14716', '16595', '20038', '22029', '22212', '22531', '14021', '20718', '21595'}
[{'TeamNum': 16595, 'OPR': 85.292, 'Auto': 17.833, 'CCWM': 44.546, 'TeamName': 'Strike Bots'}, {'TeamNum': 21594, 'OPR': 78.972, 'Auto': 20.537, 'CCWM': 74.879, 'TeamName': 'Pearson Odyssey'}, {'TeamNum': 14717, 'OPR': 71.531, 'Auto': 20.418, 'CCWM': 23.796, 'TeamName': 'Mandela United Squadron - Second Unit'}, {'TeamNum': 10015, 'OPR': 68.307, 'Auto': 18.327, 'CCWM': 5.598, 'TeamName': 'Hyper Droid'}, {'TeamNum': 16932, 'OPR': 65.892, 'Auto': 5.264, 'CCWM': 30.848, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22212, 'OPR': 58.144, 'Auto': 9.975, 'CCWM': 22.829, 'TeamName': 'Aberhart Beta'}, {'TeamNum': 22029, 'OPR': 56.407, 'Auto': 17.252, 'CCWM': -15.52, 'TeamName': 'ASAP'}, {'TeamNum': 14021, 'OPR': 54.713, 'Auto': 22.442, 'CCWM': -13.199, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 20718, 'OPR': 39.149, 'Auto': 4.101, 'CCWM': 5.572, 'TeamName': 'Scarlett Robotics'}, {'TeamNum': 20038, 'OPR': 39.023, 'Auto': 10.697, 'CCWM': -5.414, 'TeamName': 'Bronco Bots-Team 1'}, {'TeamNum': 22873, 'OPR': 37.403, 'Auto': 19.345, 'CCWM': -12.063, 'TeamName': "I'myanistsitapikoan"}, {'TeamNum': 14022, 'OPR': 36.371, 'Auto': 5.861, 'CCWM': 16.956, 'TeamName': 'SCHS Robotic Team - SRT 2'}, {'TeamNum': 20176, 'OPR': 30.629, 'Auto': 8.507, 'CCWM': 16.452, 'TeamName': 'Aberhart Allen Keys'}, {'TeamNum': 14718, 'OPR': 29.649, 'Auto': -0.254, 'CCWM': -1.123, 'TeamName': 'Timberbots'}, {'TeamNum': 21595, 'OPR': 24.661, 'Auto': 13.005, 'CCWM': -7.252, 'TeamName': 'Mandela United Squadron - WD'}, {'TeamNum': 22531, 'OPR': 19.004, 'Auto': -2.945, 'CCWM': -29.348, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 22391, 'OPR': 13.213, 'Auto': -0.06, 'CCWM': -32.826, 'TeamName': 'Bronco Bots-Team 2(girls)'}, {'TeamNum': 14716, 'OPR': 7.367, 'Auto': 1.822, 'CCWM': -58.207, 'TeamName': 'Fox Trackers'}, {'TeamNum': 20448, 'OPR': 6.815, 'Auto': 2.506, 'CCWM': -75.436, 'TeamName': 'Valley Creek Bluebots'}]
[{'TeamNum': 16595, 'OPR': 85.292, 'Auto': 17.833, 'CCWM': 44.546, 'TeamName': 'Strike Bots'}, {'TeamNum': 21594, 'OPR': 78.972, 'Auto': 20.537, 'CCWM': 74.879, 'TeamName': 'Pearson Odyssey'}, {'TeamNum': 14717, 'OPR': 71.531, 'Auto': 20.418, 'CCWM': 23.796, 'TeamName': 'Mandela United Squadron - Second Unit'}, {'TeamNum': 10015, 'OPR': 68.307, 'Auto': 18.327, 'CCWM': 5.598, 'TeamName': 'Hyper Droid'}, {'TeamNum': 16932, 'OPR': 65.892, 'Auto': 5.264, 'CCWM': 30.848, 'TeamName': 'Webber Wildcats'}, {'TeamNum': 22212, 'OPR': 58.144, 'Auto': 9.975, 'CCWM': 22.829, 'TeamName': 'Aberhart Beta'}, {'TeamNum': 22029, 'OPR': 56.407, 'Auto': 17.252, 'CCWM': -15.52, 'TeamName': 'ASAP'}, {'TeamNum': 14021, 'OPR': 54.713, 'Auto': 22.442, 'CCWM': -13.199, 'TeamName': 'SCHS Robotic Team - SRT 1'}, {'TeamNum': 20718, 'OPR': 39.149, 'Auto': 4.101, 'CCWM': 5.572, 'TeamName': 'Scarlett Robotics'}, {'TeamNum': 20038, 'OPR': 39.023, 'Auto': 10.697, 'CCWM': -5.414, 'TeamName': 'Bronco Bots-Team 1'}, {'TeamNum': 22873, 'OPR': 37.403, 'Auto': 19.345, 'CCWM': -12.063, 'TeamName': "I'myanistsitapikoan"}, {'TeamNum': 14022, 'OPR': 36.371, 'Auto': 5.861, 'CCWM': 16.956, 'TeamName': 'SCHS Robotic Team - SRT 2'}, {'TeamNum': 20176, 'OPR': 30.629, 'Auto': 8.507, 'CCWM': 16.452, 'TeamName': 'Aberhart Allen Keys'}, {'TeamNum': 14718, 'OPR': 29.649, 'Auto': -0.254, 'CCWM': -1.123, 'TeamName': 'Timberbots'}, {'TeamNum': 21595, 'OPR': 24.661, 'Auto': 13.005, 'CCWM': -7.252, 'TeamName': 'Mandela United Squadron - WD'}, {'TeamNum': 22531, 'OPR': 19.004, 'Auto': -2.945, 'CCWM': -29.348, 'TeamName': 'Scarlett Robotics 2'}, {'TeamNum': 22391, 'OPR': 13.213, 'Auto': -0.06, 'CCWM': -32.826, 'TeamName': 'Bronco Bots-Team 2(girls)'}, {'TeamNum': 14716, 'OPR': 7.367, 'Auto': 1.822, 'CCWM': -58.207, 'TeamName': 'Fox Trackers'}, {'TeamNum': 20448, 'OPR': 6.815, 'Auto': 2.506, 'CCWM': -75.436, 'TeamName': 'Valley Creek Bluebots'}]
https://ftc-events.firstinspires.org/2022/CAABABSALTDOW/qualifications
{'18444', '11712', '21736', '16871', '14023', '21593', '15259', '7277', '22188', '20802', '13898', '16544', '16596', '20168', '21832', '18634', '22315', '20125', '18450'}
{'18444', '11712', '21736', '16871', '14023', '21593', '15259', '7277', '22188', '20802', '13898', '16544', '16596', '20168', '21832', '18634', '22315', '20125', '18450'}
[{'TeamNum': 14023, 'OPR': 99.225, 'Auto': 17.752, 'CCWM': 79.668, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 7277, 'OPR': 87.451, 'Auto': 24.005, 'CCWM': 76.029, 'TeamName': 'Mandela United Squadron - First Unit'}, {'TeamNum': 22188, 'OPR': 81.196, 'Auto': 24.868, 'CCWM': 47.336, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 18450, 'OPR': 72.468, 'Auto': 17.645, 'CCWM': 57.145, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 16544, 'OPR': 66.777, 'Auto': 7.043, 'CCWM': 31.061, 'TeamName': 'Stratobots'}, {'TeamNum': 18634, 'OPR': 57.442, 'Auto': 21.41, 'CCWM': -14.792, 'TeamName': 'Webber Academy Cosmic Cats'}, {'TeamNum': 21832, 'OPR': 46.815, 'Auto': 22.847, 'CCWM': -12.626, 'TeamName': 'Crescent Robotics'}, {'TeamNum': 20125, 'OPR': 45.869, 'Auto': 10.649, 'CCWM': 30.417, 'TeamName': 'Webber Robocats'}, {'TeamNum': 20802, 'OPR': 37.326, 'Auto': 9.081, 'CCWM': -18.441, 'TeamName': 'Over Engineered'}, {'TeamNum': 22315, 'OPR': 33.937, 'Auto': 8.365, 'CCWM': 1.483, 'TeamName': 'Killa-Bytes'}, {'TeamNum': 20168, 'OPR': 32.297, 'Auto': 2.984, 'CCWM': -49.847, 'TeamName': 'STS Robotics 20168'}, {'TeamNum': 21736, 'OPR': 25.455, 'Auto': 0.32, 'CCWM': -0.334, 'TeamName': 'Neo Robotics'}, {'TeamNum': 16596, 'OPR': 25.096, 'Auto': 1.482, 'CCWM': -22.8, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 13898, 'OPR': 24.827, 'Auto': 8.766, 'CCWM': -20.245, 'TeamName': 'Aberhart Alpha'}, {'TeamNum': 16871, 'OPR': 24.683, 'Auto': 10.062, 'CCWM': -39.047, 'TeamName': 'Corax Machina'}, {'TeamNum': 11712, 'OPR': 21.322, 'Auto': 13.664, 'CCWM': -9.757, 'TeamName': 'Aberhart Inertia'}, {'TeamNum': 15259, 'OPR': 16.718, 'Auto': 10.767, 'CCWM': -61.239, 'TeamName': 'Mandela United Squadron - Third Unit'}, {'TeamNum': 21593, 'OPR': 14.151, 'Auto': -5.73, 'CCWM': -34.578, 'TeamName': 'Higgins Hawks'}, {'TeamNum': 18444, 'OPR': 12.19, 'Auto': -3.789, 'CCWM': -45.644, 'TeamName': 'STS Robotics 18444'}]
[{'TeamNum': 14023, 'OPR': 99.225, 'Auto': 17.752, 'CCWM': 79.668, 'TeamName': 'SCHS Robotic Team - Phoenix Fire'}, {'TeamNum': 7277, 'OPR': 87.451, 'Auto': 24.005, 'CCWM': 76.029, 'TeamName': 'Mandela United Squadron - First Unit'}, {'TeamNum': 22188, 'OPR': 81.196, 'Auto': 24.868, 'CCWM': 47.336, 'TeamName': "Bishop O'Beep Boop"}, {'TeamNum': 18450, 'OPR': 72.468, 'Auto': 17.645, 'CCWM': 57.145, 'TeamName': 'Webber Sparklekittens'}, {'TeamNum': 16544, 'OPR': 66.777, 'Auto': 7.043, 'CCWM': 31.061, 'TeamName': 'Stratobots'}, {'TeamNum': 18634, 'OPR': 57.442, 'Auto': 21.41, 'CCWM': -14.792, 'TeamName': 'Webber Academy Cosmic Cats'}, {'TeamNum': 21832, 'OPR': 46.815, 'Auto': 22.847, 'CCWM': -12.626, 'TeamName': 'Crescent Robotics'}, {'TeamNum': 20125, 'OPR': 45.869, 'Auto': 10.649, 'CCWM': 30.417, 'TeamName': 'Webber Robocats'}, {'TeamNum': 20802, 'OPR': 37.326, 'Auto': 9.081, 'CCWM': -18.441, 'TeamName': 'Over Engineered'}, {'TeamNum': 22315, 'OPR': 33.937, 'Auto': 8.365, 'CCWM': 1.483, 'TeamName': 'Killa-Bytes'}, {'TeamNum': 20168, 'OPR': 32.297, 'Auto': 2.984, 'CCWM': -49.847, 'TeamName': 'STS Robotics 20168'}, {'TeamNum': 21736, 'OPR': 25.455, 'Auto': 0.32, 'CCWM': -0.334, 'TeamName': 'Neo Robotics'}, {'TeamNum': 16596, 'OPR': 25.096, 'Auto': 1.482, 'CCWM': -22.8, 'TeamName': 'CAI - Crazy Artificial Intelligence '}, {'TeamNum': 13898, 'OPR': 24.827, 'Auto': 8.766, 'CCWM': -20.245, 'TeamName': 'Aberhart Alpha'}, {'TeamNum': 16871, 'OPR': 24.683, 'Auto': 10.062, 'CCWM': -39.047, 'TeamName': 'Corax Machina'}, {'TeamNum': 11712, 'OPR': 21.322, 'Auto': 13.664, 'CCWM': -9.757, 'TeamName': 'Aberhart Inertia'}, {'TeamNum': 15259, 'OPR': 16.718, 'Auto': 10.767, 'CCWM': -61.239, 'TeamName': 'Mandela United Squadron - Third Unit'}, {'TeamNum': 21593, 'OPR': 14.151, 'Auto': -5.73, 'CCWM': -34.578, 'TeamName': 'Higgins Hawks'}, {'TeamNum': 18444, 'OPR': 12.19, 'Auto': -3.789, 'CCWM': -45.644, 'TeamName': 'STS Robotics 18444'}]

i 6
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-5F92E6E8-4422-4539-AEF7-326D790E1A35")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-20D537F2-2944-4D8A-A7F0-402376C13825")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-EE0402D3-399D-46DE-81E1-E6F7DE6F5987")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-F1F8859D-3468-4065-89E4-88F17F9B479C")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-55878282-6413-4A84-AF31-32CFEE160461")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-56831522-0E5B-45D9-A49E-7B1FA8B6FD04")>]
https://ftc-events.firstinspires.org/2022/ILCMPSOLR/qualifications
{'21953', '15811', '18833', '15141', '17019', '21850', '12201', '14872', '14029', '22681', '11226', '21656', '12989', '18735', '17106', '20669', '22646', '18268', '12817', '19967', '15637', '22947', '11808', '22734'}
{'21953', '15811', '18833', '15141', '17019', '21850', '12201', '14872', '14029', '22681', '11226', '21656', '12989', '18735', '17106', '20669', '22646', '18268', '12817', '19967', '15637', '22947', '11808', '22734'}
[{'TeamNum': 15637, 'OPR': 182.942, 'Auto': 41.332, 'CCWM': 122.124, 'TeamName': 'Fata Morgana'}, {'TeamNum': 14029, 'OPR': 95.543, 'Auto': 6.868, 'CCWM': 57.333, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 18833, 'OPR': 80.835, 'Auto': 27.022, 'CCWM': 48.889, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 11808, 'OPR': 68.332, 'Auto': 1.288, 'CCWM': 12.276, 'TeamName': 'Connection'}, {'TeamNum': 15811, 'OPR': 68.002, 'Auto': 21.212, 'CCWM': 11.833, 'TeamName': 'boosteam'}, {'TeamNum': 12201, 'OPR': 61.105, 'Auto': -0.237, 'CCWM': 45.468, 'TeamName': 'TATOOINE'}, {'TeamNum': 14872, 'OPR': 60.655, 'Auto': 7.255, 'CCWM': -13.918, 'TeamName': 'Orbit 9'}, {'TeamNum': 15141, 'OPR': 59.212, 'Auto': 2.92, 'CCWM': 27.592, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 17019, 'OPR': 58.653, 'Auto': 11.769, 'CCWM': -9.366, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 19967, 'OPR': 57.431, 'Auto': 6.592, 'CCWM': 11.371, 'TeamName': 'AIS Talons'}, {'TeamNum': 22646, 'OPR': 54.527, 'Auto': 14.918, 'CCWM': 33.916, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 22947, 'OPR': 54.39, 'Auto': 7.635, 'CCWM': -9.681, 'TeamName': 'Hydra'}, {'TeamNum': 12989, 'OPR': 53.725, 'Auto': 9.926, 'CCWM': -17.878, 'TeamName': 'Super Cow'}, {'TeamNum': 22734, 'OPR': 53.157, 'Auto': 7.581, 'CCWM': -3.629, 'TeamName': 'Jotunheim '}, {'TeamNum': 20669, 'OPR': 45.793, 'Auto': 11.886, 'CCWM': -17.234, 'TeamName': 'Build for Change'}, {'TeamNum': 21953, 'OPR': 40.51, 'Auto': -3.256, 'CCWM': 7.76, 'TeamName': 'Dalia Engineers '}, {'TeamNum': 18268, 'OPR': 28.484, 'Auto': 17.19, 'CCWM': -47.149, 'TeamName': 'SYCATECH'}, {'TeamNum': 18735, 'OPR': 27.714, 'Auto': -1.394, 'CCWM': -10.327, 'TeamName': 'RinGoStar'}, {'TeamNum': 11226, 'OPR': 24.948, 'Auto': 2.184, 'CCWM': -18.833, 'TeamName': 'Black Thunder'}, {'TeamNum': 22681, 'OPR': 23.67, 'Auto': 5.698, 'CCWM': -39.358, 'TeamName': 'Amal Space  and Aviation Maale Adumim the Kings'}, {'TeamNum': 17106, 'OPR': 18.758, 'Auto': 8.685, 'CCWM': -47.581, 'TeamName': 'PlanTech'}, {'TeamNum': 21850, 'OPR': 15.972, 'Auto': 11.599, 'CCWM': -16.536, 'TeamName': 'ATRobotics'}, {'TeamNum': 12817, 'OPR': 15.069, 'Auto': 7.052, 'CCWM': -43.364, 'TeamName': 'Everest'}, {'TeamNum': 21656, 'OPR': 2.906, 'Auto': 10.108, 'CCWM': -83.708, 'TeamName': 'Fireflies'}]
[{'TeamNum': 15637, 'OPR': 182.942, 'Auto': 41.332, 'CCWM': 122.124, 'TeamName': 'Fata Morgana'}, {'TeamNum': 14029, 'OPR': 95.543, 'Auto': 6.868, 'CCWM': 57.333, 'TeamName': 'Orbit Vikings'}, {'TeamNum': 18833, 'OPR': 80.835, 'Auto': 27.022, 'CCWM': 48.889, 'TeamName': 'Megiddo Lions'}, {'TeamNum': 11808, 'OPR': 68.332, 'Auto': 1.288, 'CCWM': 12.276, 'TeamName': 'Connection'}, {'TeamNum': 15811, 'OPR': 68.002, 'Auto': 21.212, 'CCWM': 11.833, 'TeamName': 'boosteam'}, {'TeamNum': 12201, 'OPR': 61.105, 'Auto': -0.237, 'CCWM': 45.468, 'TeamName': 'TATOOINE'}, {'TeamNum': 14872, 'OPR': 60.655, 'Auto': 7.255, 'CCWM': -13.918, 'TeamName': 'Orbit 9'}, {'TeamNum': 15141, 'OPR': 59.212, 'Auto': 2.92, 'CCWM': 27.592, 'TeamName': 'AM.I.T ASHDOD'}, {'TeamNum': 17019, 'OPR': 58.653, 'Auto': 11.769, 'CCWM': -9.366, 'TeamName': 'BlackBeard in memory of Noa Hayat'}, {'TeamNum': 19967, 'OPR': 57.431, 'Auto': 6.592, 'CCWM': 11.371, 'TeamName': 'AIS Talons'}, {'TeamNum': 22646, 'OPR': 54.527, 'Auto': 14.918, 'CCWM': 33.916, 'TeamName': 'Mitspe Yam/מצפה ים'}, {'TeamNum': 22947, 'OPR': 54.39, 'Auto': 7.635, 'CCWM': -9.681, 'TeamName': 'Hydra'}, {'TeamNum': 12989, 'OPR': 53.725, 'Auto': 9.926, 'CCWM': -17.878, 'TeamName': 'Super Cow'}, {'TeamNum': 22734, 'OPR': 53.157, 'Auto': 7.581, 'CCWM': -3.629, 'TeamName': 'Jotunheim '}, {'TeamNum': 20669, 'OPR': 45.793, 'Auto': 11.886, 'CCWM': -17.234, 'TeamName': 'Build for Change'}, {'TeamNum': 21953, 'OPR': 40.51, 'Auto': -3.256, 'CCWM': 7.76, 'TeamName': 'Dalia Engineers '}, {'TeamNum': 18268, 'OPR': 28.484, 'Auto': 17.19, 'CCWM': -47.149, 'TeamName': 'SYCATECH'}, {'TeamNum': 18735, 'OPR': 27.714, 'Auto': -1.394, 'CCWM': -10.327, 'TeamName': 'RinGoStar'}, {'TeamNum': 11226, 'OPR': 24.948, 'Auto': 2.184, 'CCWM': -18.833, 'TeamName': 'Black Thunder'}, {'TeamNum': 22681, 'OPR': 23.67, 'Auto': 5.698, 'CCWM': -39.358, 'TeamName': 'Amal Space  and Aviation Maale Adumim the Kings'}, {'TeamNum': 17106, 'OPR': 18.758, 'Auto': 8.685, 'CCWM': -47.581, 'TeamName': 'PlanTech'}, {'TeamNum': 21850, 'OPR': 15.972, 'Auto': 11.599, 'CCWM': -16.536, 'TeamName': 'ATRobotics'}, {'TeamNum': 12817, 'OPR': 15.069, 'Auto': 7.052, 'CCWM': -43.364, 'TeamName': 'Everest'}, {'TeamNum': 21656, 'OPR': 2.906, 'Auto': 10.108, 'CCWM': -83.708, 'TeamName': 'Fireflies'}]
https://ftc-events.firstinspires.org/2022/ILCMPHDRO/qualifications
{'14869', '13146', '17182', '11635', '22764', '13452', '21770', '16473', '12363', '11443', '11567', '12797', '11192', '21796', '22144', '9662', '17056', '19000', '15298', '14028', '21957', '11803', '22644', '12016'}
{'14869', '13146', '17182', '11635', '22764', '13452', '21770', '16473', '12363', '11443', '11567', '12797', '11192', '21796', '22144', '9662', '17056', '19000', '15298', '14028', '21957', '11803', '22644', '12016'}
[{'TeamNum': 12016, 'OPR': 129.883, 'Auto': 33.63, 'CCWM': 69.408, 'TeamName': 'Mish Mash'}, {'TeamNum': 12363, 'OPR': 106.091, 'Auto': 26.046, 'CCWM': 63.671, 'TeamName': 'OrangeFox'}, {'TeamNum': 22144, 'OPR': 97.57, 'Auto': 11.347, 'CCWM': 69.032, 'TeamName': 'Deagles'}, {'TeamNum': 11192, 'OPR': 88.03, 'Auto': 26.226, 'CCWM': 47.721, 'TeamName': 'Black Tigers'}, {'TeamNum': 9662, 'OPR': 81.477, 'Auto': 26.963, 'CCWM': 17.387, 'TeamName': 'Apollo'}, {'TeamNum': 16473, 'OPR': 75.342, 'Auto': 18.405, 'CCWM': 12.413, 'TeamName': 'SciFighters'}, {'TeamNum': 12797, 'OPR': 71.431, 'Auto': 15.079, 'CCWM': 14.74, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 11567, 'OPR': 70.331, 'Auto': 20.633, 'CCWM': -6.73, 'TeamName': 'Supernova'}, {'TeamNum': 13146, 'OPR': 66.343, 'Auto': 12.201, 'CCWM': -11.913, 'TeamName': 'Makers Assemble'}, {'TeamNum': 11443, 'OPR': 66.078, 'Auto': 7.859, 'CCWM': 53.055, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 21957, 'OPR': 64.527, 'Auto': 21.868, 'CCWM': -9.486, 'TeamName': 'Goblin Mode'}, {'TeamNum': 14028, 'OPR': 63.167, 'Auto': 12.273, 'CCWM': 8.912, 'TeamName': 'Orbit 10'}, {'TeamNum': 11803, 'OPR': 49.588, 'Auto': 2.774, 'CCWM': -17.157, 'TeamName': 'PHOENIX'}, {'TeamNum': 22764, 'OPR': 46.793, 'Auto': 10.368, 'CCWM': -4.19, 'TeamName': 'BAGHEERA'}, {'TeamNum': 11635, 'OPR': 41.45, 'Auto': 7.72, 'CCWM': -26.621, 'TeamName': 'Quack Attack'}, {'TeamNum': 15298, 'OPR': 41.322, 'Auto': 13.556, 'CCWM': -10.199, 'TeamName': 'RoboTen'}, {'TeamNum': 17056, 'OPR': 36.497, 'Auto': -1.049, 'CCWM': 4.701, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 13452, 'OPR': 30.107, 'Auto': 6.703, 'CCWM': 15.482, 'TeamName': 'BTJ'}, {'TeamNum': 21796, 'OPR': 29.776, 'Auto': 1.697, 'CCWM': -62.127, 'TeamName': 'ECLIPSE'}, {'TeamNum': 14869, 'OPR': 25.316, 'Auto': 19.511, 'CCWM': -64.14, 'TeamName': 'Bomba'}, {'TeamNum': 22644, 'OPR': 23.478, 'Auto': 14.103, 'CCWM': -32.244, 'TeamName': 'RayLadies'}, {'TeamNum': 21770, 'OPR': 14.462, 'Auto': -0.591, 'CCWM': -28.747, 'TeamName': 'HFS'}, {'TeamNum': 17182, 'OPR': 6.732, 'Auto': 6.329, 'CCWM': -36.409, 'TeamName': 'Red Mask'}, {'TeamNum': 19000, 'OPR': 4.709, 'Auto': 2.017, 'CCWM': -66.558, 'TeamName': 'Everglow'}]
[{'TeamNum': 12016, 'OPR': 129.883, 'Auto': 33.63, 'CCWM': 69.408, 'TeamName': 'Mish Mash'}, {'TeamNum': 12363, 'OPR': 106.091, 'Auto': 26.046, 'CCWM': 63.671, 'TeamName': 'OrangeFox'}, {'TeamNum': 22144, 'OPR': 97.57, 'Auto': 11.347, 'CCWM': 69.032, 'TeamName': 'Deagles'}, {'TeamNum': 11192, 'OPR': 88.03, 'Auto': 26.226, 'CCWM': 47.721, 'TeamName': 'Black Tigers'}, {'TeamNum': 9662, 'OPR': 81.477, 'Auto': 26.963, 'CCWM': 17.387, 'TeamName': 'Apollo'}, {'TeamNum': 16473, 'OPR': 75.342, 'Auto': 18.405, 'CCWM': 12.413, 'TeamName': 'SciFighters'}, {'TeamNum': 12797, 'OPR': 71.431, 'Auto': 15.079, 'CCWM': 14.74, 'TeamName': 'MEGIDDO LIONS'}, {'TeamNum': 11567, 'OPR': 70.331, 'Auto': 20.633, 'CCWM': -6.73, 'TeamName': 'Supernova'}, {'TeamNum': 13146, 'OPR': 66.343, 'Auto': 12.201, 'CCWM': -11.913, 'TeamName': 'Makers Assemble'}, {'TeamNum': 11443, 'OPR': 66.078, 'Auto': 7.859, 'CCWM': 53.055, 'TeamName': 'ATOMIX 11443 '}, {'TeamNum': 21957, 'OPR': 64.527, 'Auto': 21.868, 'CCWM': -9.486, 'TeamName': 'Goblin Mode'}, {'TeamNum': 14028, 'OPR': 63.167, 'Auto': 12.273, 'CCWM': 8.912, 'TeamName': 'Orbit 10'}, {'TeamNum': 11803, 'OPR': 49.588, 'Auto': 2.774, 'CCWM': -17.157, 'TeamName': 'PHOENIX'}, {'TeamNum': 22764, 'OPR': 46.793, 'Auto': 10.368, 'CCWM': -4.19, 'TeamName': 'BAGHEERA'}, {'TeamNum': 11635, 'OPR': 41.45, 'Auto': 7.72, 'CCWM': -26.621, 'TeamName': 'Quack Attack'}, {'TeamNum': 15298, 'OPR': 41.322, 'Auto': 13.556, 'CCWM': -10.199, 'TeamName': 'RoboTen'}, {'TeamNum': 17056, 'OPR': 36.497, 'Auto': -1.049, 'CCWM': 4.701, 'TeamName': 'Mechanic Makers'}, {'TeamNum': 13452, 'OPR': 30.107, 'Auto': 6.703, 'CCWM': 15.482, 'TeamName': 'BTJ'}, {'TeamNum': 21796, 'OPR': 29.776, 'Auto': 1.697, 'CCWM': -62.127, 'TeamName': 'ECLIPSE'}, {'TeamNum': 14869, 'OPR': 25.316, 'Auto': 19.511, 'CCWM': -64.14, 'TeamName': 'Bomba'}, {'TeamNum': 22644, 'OPR': 23.478, 'Auto': 14.103, 'CCWM': -32.244, 'TeamName': 'RayLadies'}, {'TeamNum': 21770, 'OPR': 14.462, 'Auto': -0.591, 'CCWM': -28.747, 'TeamName': 'HFS'}, {'TeamNum': 17182, 'OPR': 6.732, 'Auto': 6.329, 'CCWM': -36.409, 'TeamName': 'Red Mask'}, {'TeamNum': 19000, 'OPR': 4.709, 'Auto': 2.017, 'CCWM': -66.558, 'TeamName': 'Everglow'}]

i 7
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-CAEEA3AB-6DD6-43D1-A1D1-F6B2F8884D87")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-D6A00C82-6941-4A90-8B91-F73EB53925E5")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-0BE8CA11-AA5A-4F88-8D9B-1B7A86D2145A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-FFB2C425-6ADF-4B88-8D32-0798675AADCD")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-C1AEE52C-D1CE-4AA2-BE08-1F4D928B151D")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-1E6167AA-25C0-44EE-ADDF-C2C727BFA60A")>]
https://ftc-events.firstinspires.org/2022/USCHSCMPSCA/qualifications
{'8479', '11695', '18103', '16502', '6010', '13353', '19818', '6417', '13804', '4634', '21587', '8644', '1885', '21814', '7393', '18438', '13100', '4924', '2818', '20194', '19876', '11112', '7039', '17080', '15317', '18996'}
{'8479', '11695', '18103', '16502', '6010', '13353', '19818', '6417', '13804', '4634', '21587', '8644', '1885', '21814', '7393', '18438', '13100', '4924', '2818', '20194', '19876', '11112', '7039', '17080', '15317', '18996'}
[{'TeamNum': 8644, 'OPR': 154.722, 'Auto': 35.06, 'CCWM': 125.935, 'TeamName': 'The Brainstormers'}, {'TeamNum': 18438, 'OPR': 148.439, 'Auto': 49.4, 'CCWM': 68.511, 'TeamName': 'Wolfpack Machina '}, {'TeamNum': 17080, 'OPR': 124.841, 'Auto': 32.146, 'CCWM': 15.119, 'TeamName': 'NewT.exe'}, {'TeamNum': 2818, 'OPR': 118.988, 'Auto': 19.975, 'CCWM': 63.553, 'TeamName': 'G-FORCE'}, {'TeamNum': 19876, 'OPR': 115.519, 'Auto': 38.4, 'CCWM': 61.35, 'TeamName': 'N-1'}, {'TeamNum': 7393, 'OPR': 106.34, 'Auto': 25.6, 'CCWM': 63.507, 'TeamName': 'electron Volts'}, {'TeamNum': 11695, 'OPR': 95.738, 'Auto': 16.676, 'CCWM': 38.929, 'TeamName': 'DeJava'}, {'TeamNum': 21587, 'OPR': 94.299, 'Auto': 19.306, 'CCWM': 11.7, 'TeamName': 'Orcas Robotics'}, {'TeamNum': 6417, 'OPR': 93.501, 'Auto': 36.247, 'CCWM': 30.832, 'TeamName': 'Blu Cru'}, {'TeamNum': 11112, 'OPR': 90.872, 'Auto': 37.207, 'CCWM': -4.081, 'TeamName': 'RoboLords'}, {'TeamNum': 13353, 'OPR': 89.262, 'Auto': 22.908, 'CCWM': -21.342, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 8479, 'OPR': 88.488, 'Auto': 27.902, 'CCWM': 36.779, 'TeamName': 'RoboCavs Gold'}, {'TeamNum': 20194, 'OPR': 83.731, 'Auto': 16.317, 'CCWM': -50.242, 'TeamName': 'JackBots'}, {'TeamNum': 4634, 'OPR': 82.143, 'Auto': 13.368, 'CCWM': -23.48, 'TeamName': 'FROGbots - Purple'}, {'TeamNum': 15317, 'OPR': 73.762, 'Auto': 9.6, 'CCWM': -4.086, 'TeamName': 'HHS Robotics - Error Code 404'}, {'TeamNum': 4924, 'OPR': 62.396, 'Auto': 19.972, 'CCWM': -33.847, 'TeamName': 'Red Beard Pandas'}, {'TeamNum': 21814, 'OPR': 60.817, 'Auto': 6.732, 'CCWM': 7.623, 'TeamName': 'Robots on Roids'}, {'TeamNum': 19818, 'OPR': 60.654, 'Auto': 20.018, 'CCWM': -22.477, 'TeamName': 'Jade Innovations'}, {'TeamNum': 13804, 'OPR': 58.416, 'Auto': 5.214, 'CCWM': -45.176, 'TeamName': 'Powhatan SPEAR  '}, {'TeamNum': 1885, 'OPR': 54.586, 'Auto': 6.803, 'CCWM': -6.291, 'TeamName': 'ILITE - The Legacy'}, {'TeamNum': 6010, 'OPR': 47.055, 'Auto': 17.741, 'CCWM': -12.995, 'TeamName': 'Thunder Stone'}, {'TeamNum': 18996, 'OPR': 41.387, 'Auto': 11.706, 'CCWM': -29.607, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 18103, 'OPR': 39.388, 'Auto': 14.695, 'CCWM': -39.469, 'TeamName': 'Nth Degree'}, {'TeamNum': 16502, 'OPR': 38.334, 'Auto': 10.187, 'CCWM': -46.313, 'TeamName': 'S.W.A.T.'}, {'TeamNum': 7039, 'OPR': 29.788, 'Auto': 6.77, 'CCWM': -53.606, 'TeamName': 'Lord of the Bricks'}, {'TeamNum': 13100, 'OPR': 18.898, 'Auto': 9.755, 'CCWM': -114.183, 'TeamName': '47 Beavers'}]
[{'TeamNum': 8644, 'OPR': 154.722, 'Auto': 35.06, 'CCWM': 125.935, 'TeamName': 'The Brainstormers'}, {'TeamNum': 18438, 'OPR': 148.439, 'Auto': 49.4, 'CCWM': 68.511, 'TeamName': 'Wolfpack Machina '}, {'TeamNum': 17080, 'OPR': 124.841, 'Auto': 32.146, 'CCWM': 15.119, 'TeamName': 'NewT.exe'}, {'TeamNum': 2818, 'OPR': 118.988, 'Auto': 19.975, 'CCWM': 63.553, 'TeamName': 'G-FORCE'}, {'TeamNum': 19876, 'OPR': 115.519, 'Auto': 38.4, 'CCWM': 61.35, 'TeamName': 'N-1'}, {'TeamNum': 7393, 'OPR': 106.34, 'Auto': 25.6, 'CCWM': 63.507, 'TeamName': 'electron Volts'}, {'TeamNum': 11695, 'OPR': 95.738, 'Auto': 16.676, 'CCWM': 38.929, 'TeamName': 'DeJava'}, {'TeamNum': 21587, 'OPR': 94.299, 'Auto': 19.306, 'CCWM': 11.7, 'TeamName': 'Orcas Robotics'}, {'TeamNum': 6417, 'OPR': 93.501, 'Auto': 36.247, 'CCWM': 30.832, 'TeamName': 'Blu Cru'}, {'TeamNum': 11112, 'OPR': 90.872, 'Auto': 37.207, 'CCWM': -4.081, 'TeamName': 'RoboLords'}, {'TeamNum': 13353, 'OPR': 89.262, 'Auto': 22.908, 'CCWM': -21.342, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 8479, 'OPR': 88.488, 'Auto': 27.902, 'CCWM': 36.779, 'TeamName': 'RoboCavs Gold'}, {'TeamNum': 20194, 'OPR': 83.731, 'Auto': 16.317, 'CCWM': -50.242, 'TeamName': 'JackBots'}, {'TeamNum': 4634, 'OPR': 82.143, 'Auto': 13.368, 'CCWM': -23.48, 'TeamName': 'FROGbots - Purple'}, {'TeamNum': 15317, 'OPR': 73.762, 'Auto': 9.6, 'CCWM': -4.086, 'TeamName': 'HHS Robotics - Error Code 404'}, {'TeamNum': 4924, 'OPR': 62.396, 'Auto': 19.972, 'CCWM': -33.847, 'TeamName': 'Red Beard Pandas'}, {'TeamNum': 21814, 'OPR': 60.817, 'Auto': 6.732, 'CCWM': 7.623, 'TeamName': 'Robots on Roids'}, {'TeamNum': 19818, 'OPR': 60.654, 'Auto': 20.018, 'CCWM': -22.477, 'TeamName': 'Jade Innovations'}, {'TeamNum': 13804, 'OPR': 58.416, 'Auto': 5.214, 'CCWM': -45.176, 'TeamName': 'Powhatan SPEAR  '}, {'TeamNum': 1885, 'OPR': 54.586, 'Auto': 6.803, 'CCWM': -6.291, 'TeamName': 'ILITE - The Legacy'}, {'TeamNum': 6010, 'OPR': 47.055, 'Auto': 17.741, 'CCWM': -12.995, 'TeamName': 'Thunder Stone'}, {'TeamNum': 18996, 'OPR': 41.387, 'Auto': 11.706, 'CCWM': -29.607, 'TeamName': 'S.T.A.T.I.C.'}, {'TeamNum': 18103, 'OPR': 39.388, 'Auto': 14.695, 'CCWM': -39.469, 'TeamName': 'Nth Degree'}, {'TeamNum': 16502, 'OPR': 38.334, 'Auto': 10.187, 'CCWM': -46.313, 'TeamName': 'S.W.A.T.'}, {'TeamNum': 7039, 'OPR': 29.788, 'Auto': 6.77, 'CCWM': -53.606, 'TeamName': 'Lord of the Bricks'}, {'TeamNum': 13100, 'OPR': 18.898, 'Auto': 9.755, 'CCWM': -114.183, 'TeamName': '47 Beavers'}]
https://ftc-events.firstinspires.org/2022/USCHSCMPVIO/qualifications
{'8395', '12096', '19941', '19458', '12518', '14607', '21774', '10001', '15167', '7', '194', '16605', '16439', '14575', '12838', '18264', '8393', '8702', '15304', '19890', '965', '18442', '17774', '21232', '9064', '3749'}
{'8395', '12096', '19941', '19458', '12518', '14607', '21774', '10001', '15167', '7', '194', '16605', '16439', '14575', '12838', '18264', '8393', '8702', '15304', '19890', '965', '18442', '17774', '21232', '9064', '3749'}
[{'TeamNum': 8393, 'OPR': 161.4, 'Auto': 49.516, 'CCWM': 114.293, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 15167, 'OPR': 140.12, 'Auto': 35.723, 'CCWM': 97.006, 'TeamName': 'Robo Troopers'}, {'TeamNum': 12096, 'OPR': 124.281, 'Auto': 39.385, 'CCWM': 31.083, 'TeamName': 'Absolute Zero'}, {'TeamNum': 8395, 'OPR': 118.361, 'Auto': 17.842, 'CCWM': 79.644, 'TeamName': 'The A-Team'}, {'TeamNum': 21232, 'OPR': 114.291, 'Auto': 40.56, 'CCWM': 17.993, 'TeamName': 'no team'}, {'TeamNum': 8702, 'OPR': 103.853, 'Auto': 26.804, 'CCWM': 29.562, 'TeamName': 'Innovotics'}, {'TeamNum': 7, 'OPR': 102.936, 'Auto': 29.708, 'CCWM': 33.884, 'TeamName': 'Tactical Sheep'}, {'TeamNum': 21774, 'OPR': 94.469, 'Auto': 6.292, 'CCWM': -13.303, 'TeamName': 'Supernova.exe'}, {'TeamNum': 19458, 'OPR': 93.47, 'Auto': 29.981, 'CCWM': -18.012, 'TeamName': 'Equilibrium.exe '}, {'TeamNum': 965, 'OPR': 89.034, 'Auto': 13.462, 'CCWM': 40.494, 'TeamName': 'The League of Incompetent Gentlemen'}, {'TeamNum': 19941, 'OPR': 86.208, 'Auto': 28.776, 'CCWM': -16.9, 'TeamName': 'M&M (Metal Masterminds).exe'}, {'TeamNum': 10001, 'OPR': 85.737, 'Auto': 23.747, 'CCWM': -30.279, 'TeamName': 'RoboCavs Silver'}, {'TeamNum': 14607, 'OPR': 82.507, 'Auto': 14.493, 'CCWM': -38.511, 'TeamName': 'Robot Uprising'}, {'TeamNum': 19890, 'OPR': 75.87, 'Auto': 5.85, 'CCWM': -9.627, 'TeamName': 'Distractors.exe'}, {'TeamNum': 16439, 'OPR': 73.964, 'Auto': 22.319, 'CCWM': 24.785, 'TeamName': 'AlphaGo'}, {'TeamNum': 3749, 'OPR': 69.473, 'Auto': 9.829, 'CCWM': 14.102, 'TeamName': 'while(e()) {coyotes()}'}, {'TeamNum': 14575, 'OPR': 68.613, 'Auto': 7.269, 'CCWM': 21.286, 'TeamName': 'Capital Bots'}, {'TeamNum': 9064, 'OPR': 64.331, 'Auto': 13.898, 'CCWM': 3.436, 'TeamName': 'Firefly'}, {'TeamNum': 18442, 'OPR': 64.081, 'Auto': 6.695, 'CCWM': 4.484, 'TeamName': 'Gear Rotation'}, {'TeamNum': 12518, 'OPR': 42.823, 'Auto': -3.517, 'CCWM': -31.659, 'TeamName': 'Almond Robotics'}, {'TeamNum': 12838, 'OPR': 42.413, 'Auto': 11.389, 'CCWM': -11.764, 'TeamName': 'Lancaster Kinetic Storm'}, {'TeamNum': 17774, 'OPR': 40.741, 'Auto': 10.917, 'CCWM': -30.914, 'TeamName': 'Monroe Robotics'}, {'TeamNum': 16605, 'OPR': 36.479, 'Auto': 13.012, 'CCWM': -114.653, 'TeamName': 'YogicTransformers'}, {'TeamNum': 194, 'OPR': 35.674, 'Auto': 3.66, 'CCWM': -62.059, 'TeamName': 'ILITE - Ingenuity'}, {'TeamNum': 15304, 'OPR': 33.301, 'Auto': 5.928, 'CCWM': -58.034, 'TeamName': 'CircuiTree'}, {'TeamNum': 18264, 'OPR': 15.129, 'Auto': 12.546, 'CCWM': -73.102, 'TeamName': 'TheElectronovas'}]
[{'TeamNum': 8393, 'OPR': 161.4, 'Auto': 49.516, 'CCWM': 114.293, 'TeamName': 'The Giant Diencephalic BrainSTEM Robotics Team'}, {'TeamNum': 15167, 'OPR': 140.12, 'Auto': 35.723, 'CCWM': 97.006, 'TeamName': 'Robo Troopers'}, {'TeamNum': 12096, 'OPR': 124.281, 'Auto': 39.385, 'CCWM': 31.083, 'TeamName': 'Absolute Zero'}, {'TeamNum': 8395, 'OPR': 118.361, 'Auto': 17.842, 'CCWM': 79.644, 'TeamName': 'The A-Team'}, {'TeamNum': 21232, 'OPR': 114.291, 'Auto': 40.56, 'CCWM': 17.993, 'TeamName': 'no team'}, {'TeamNum': 8702, 'OPR': 103.853, 'Auto': 26.804, 'CCWM': 29.562, 'TeamName': 'Innovotics'}, {'TeamNum': 7, 'OPR': 102.936, 'Auto': 29.708, 'CCWM': 33.884, 'TeamName': 'Tactical Sheep'}, {'TeamNum': 21774, 'OPR': 94.469, 'Auto': 6.292, 'CCWM': -13.303, 'TeamName': 'Supernova.exe'}, {'TeamNum': 19458, 'OPR': 93.47, 'Auto': 29.981, 'CCWM': -18.012, 'TeamName': 'Equilibrium.exe '}, {'TeamNum': 965, 'OPR': 89.034, 'Auto': 13.462, 'CCWM': 40.494, 'TeamName': 'The League of Incompetent Gentlemen'}, {'TeamNum': 19941, 'OPR': 86.208, 'Auto': 28.776, 'CCWM': -16.9, 'TeamName': 'M&M (Metal Masterminds).exe'}, {'TeamNum': 10001, 'OPR': 85.737, 'Auto': 23.747, 'CCWM': -30.279, 'TeamName': 'RoboCavs Silver'}, {'TeamNum': 14607, 'OPR': 82.507, 'Auto': 14.493, 'CCWM': -38.511, 'TeamName': 'Robot Uprising'}, {'TeamNum': 19890, 'OPR': 75.87, 'Auto': 5.85, 'CCWM': -9.627, 'TeamName': 'Distractors.exe'}, {'TeamNum': 16439, 'OPR': 73.964, 'Auto': 22.319, 'CCWM': 24.785, 'TeamName': 'AlphaGo'}, {'TeamNum': 3749, 'OPR': 69.473, 'Auto': 9.829, 'CCWM': 14.102, 'TeamName': 'while(e()) {coyotes()}'}, {'TeamNum': 14575, 'OPR': 68.613, 'Auto': 7.269, 'CCWM': 21.286, 'TeamName': 'Capital Bots'}, {'TeamNum': 9064, 'OPR': 64.331, 'Auto': 13.898, 'CCWM': 3.436, 'TeamName': 'Firefly'}, {'TeamNum': 18442, 'OPR': 64.081, 'Auto': 6.695, 'CCWM': 4.484, 'TeamName': 'Gear Rotation'}, {'TeamNum': 12518, 'OPR': 42.823, 'Auto': -3.517, 'CCWM': -31.659, 'TeamName': 'Almond Robotics'}, {'TeamNum': 12838, 'OPR': 42.413, 'Auto': 11.389, 'CCWM': -11.764, 'TeamName': 'Lancaster Kinetic Storm'}, {'TeamNum': 17774, 'OPR': 40.741, 'Auto': 10.917, 'CCWM': -30.914, 'TeamName': 'Monroe Robotics'}, {'TeamNum': 16605, 'OPR': 36.479, 'Auto': 13.012, 'CCWM': -114.653, 'TeamName': 'YogicTransformers'}, {'TeamNum': 194, 'OPR': 35.674, 'Auto': 3.66, 'CCWM': -62.059, 'TeamName': 'ILITE - Ingenuity'}, {'TeamNum': 15304, 'OPR': 33.301, 'Auto': 5.928, 'CCWM': -58.034, 'TeamName': 'CircuiTree'}, {'TeamNum': 18264, 'OPR': 15.129, 'Auto': 12.546, 'CCWM': -73.102, 'TeamName': 'TheElectronovas'}]

i 8
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-84677345-5ACC-450B-A6FB-DBD84A175B9A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-97E18844-91DE-4084-B4E0-6F1766C36B9C")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-B9B1CEF7-A486-42C9-8D20-E969A06EFCF9")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-7BCA7B59-16DA-4EF1-A0A7-CC76F9B7CE5A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-0B6E2369-3BA1-4EC4-B71F-33FAC4486507")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-FB7E12E6-B360-4E5C-ACE3-2529247B2666")>]
https://ftc-events.firstinspires.org/2022/USMNCMPGAL1/qualifications
{'10470', '13247', '16806', '17240', '12649', '20032', '7588', '11206', '22162', '18487', '2887', '3763', '18082', '8101', '22181', '16539', '19542', '17221', '7000', '21606', '17127', '12660', '9415', '19865'}
{'10470', '13247', '16806', '17240', '12649', '20032', '7588', '11206', '22162', '18487', '2887', '3763', '18082', '8101', '22181', '16539', '19542', '17221', '7000', '21606', '17127', '12660', '9415', '19865'}
[{'TeamNum': 3763, 'OPR': 130.84, 'Auto': 33.627, 'CCWM': 30.459, 'TeamName': 'Piece of Cake'}, {'TeamNum': 17127, 'OPR': 130.351, 'Auto': 26.227, 'CCWM': 73.451, 'TeamName': 'Electrobotics'}, {'TeamNum': 8101, 'OPR': 126.673, 'Auto': 38.169, 'CCWM': 38.328, 'TeamName': 'Metalmorphosis'}, {'TeamNum': 7588, 'OPR': 124.749, 'Auto': 26.776, 'CCWM': 48.476, 'TeamName': 'Catlateral Damage'}, {'TeamNum': 7000, 'OPR': 98.203, 'Auto': 21.645, 'CCWM': 46.173, 'TeamName': 'RoboSharks'}, {'TeamNum': 9415, 'OPR': 87.15, 'Auto': 27.586, 'CCWM': 69.656, 'TeamName': 'Wrench Dressing'}, {'TeamNum': 16539, 'OPR': 85.382, 'Auto': 20.514, 'CCWM': 27.567, 'TeamName': 'Aluminum Warriors'}, {'TeamNum': 13247, 'OPR': 83.198, 'Auto': 15.244, 'CCWM': 26.261, 'TeamName': 'RPM Robotics'}, {'TeamNum': 18082, 'OPR': 83.138, 'Auto': 17.661, 'CCWM': 24.088, 'TeamName': 'Maniac Mechanics'}, {'TeamNum': 10470, 'OPR': 80.389, 'Auto': 26.598, 'CCWM': 3.382, 'TeamName': 'Fatalis'}, {'TeamNum': 16806, 'OPR': 78.719, 'Auto': 17.82, 'CCWM': 9.615, 'TeamName': 'MilliSecondBots'}, {'TeamNum': 19865, 'OPR': 77.618, 'Auto': 14.468, 'CCWM': 4.412, 'TeamName': 'Robo Dragons'}, {'TeamNum': 21606, 'OPR': 66.216, 'Auto': 19.758, 'CCWM': -6.746, 'TeamName': 'Method 2R Madness'}, {'TeamNum': 2887, 'OPR': 65.043, 'Auto': 24.512, 'CCWM': -26.833, 'TeamName': 'Bucket Brigade'}, {'TeamNum': 18487, 'OPR': 58.7, 'Auto': 18.815, 'CCWM': -32.826, 'TeamName': 'TaCodeCats'}, {'TeamNum': 20032, 'OPR': 56.84, 'Auto': 15.566, 'CCWM': -62.988, 'TeamName': 'Cyber Machina'}, {'TeamNum': 19542, 'OPR': 53.217, 'Auto': 7.561, 'CCWM': -37.225, 'TeamName': 'The CIA'}, {'TeamNum': 17240, 'OPR': 52.815, 'Auto': 5.921, 'CCWM': -15.201, 'TeamName': 'Iron Eagles'}, {'TeamNum': 12660, 'OPR': 51.605, 'Auto': 13.523, 'CCWM': -25.685, 'TeamName': 'Robotters'}, {'TeamNum': 17221, 'OPR': 50.793, 'Auto': 15.557, 'CCWM': -3.045, 'TeamName': 'High Voltage'}, {'TeamNum': 22162, 'OPR': 36.458, 'Auto': 11.336, 'CCWM': -40.827, 'TeamName': 'M-TECH ProtoPlazma'}, {'TeamNum': 11206, 'OPR': 35.269, 'Auto': 3.859, 'CCWM': -1.976, 'TeamName': 'Devildogs'}, {'TeamNum': 12649, 'OPR': 30.34, 'Auto': 14.771, 'CCWM': -73.411, 'TeamName': 'Code Blooded'}, {'TeamNum': 22181, 'OPR': 18.295, 'Auto': 0.316, 'CCWM': -75.105, 'TeamName': 'WARP2'}]
[{'TeamNum': 3763, 'OPR': 130.84, 'Auto': 33.627, 'CCWM': 30.459, 'TeamName': 'Piece of Cake'}, {'TeamNum': 17127, 'OPR': 130.351, 'Auto': 26.227, 'CCWM': 73.451, 'TeamName': 'Electrobotics'}, {'TeamNum': 8101, 'OPR': 126.673, 'Auto': 38.169, 'CCWM': 38.328, 'TeamName': 'Metalmorphosis'}, {'TeamNum': 7588, 'OPR': 124.749, 'Auto': 26.776, 'CCWM': 48.476, 'TeamName': 'Catlateral Damage'}, {'TeamNum': 7000, 'OPR': 98.203, 'Auto': 21.645, 'CCWM': 46.173, 'TeamName': 'RoboSharks'}, {'TeamNum': 9415, 'OPR': 87.15, 'Auto': 27.586, 'CCWM': 69.656, 'TeamName': 'Wrench Dressing'}, {'TeamNum': 16539, 'OPR': 85.382, 'Auto': 20.514, 'CCWM': 27.567, 'TeamName': 'Aluminum Warriors'}, {'TeamNum': 13247, 'OPR': 83.198, 'Auto': 15.244, 'CCWM': 26.261, 'TeamName': 'RPM Robotics'}, {'TeamNum': 18082, 'OPR': 83.138, 'Auto': 17.661, 'CCWM': 24.088, 'TeamName': 'Maniac Mechanics'}, {'TeamNum': 10470, 'OPR': 80.389, 'Auto': 26.598, 'CCWM': 3.382, 'TeamName': 'Fatalis'}, {'TeamNum': 16806, 'OPR': 78.719, 'Auto': 17.82, 'CCWM': 9.615, 'TeamName': 'MilliSecondBots'}, {'TeamNum': 19865, 'OPR': 77.618, 'Auto': 14.468, 'CCWM': 4.412, 'TeamName': 'Robo Dragons'}, {'TeamNum': 21606, 'OPR': 66.216, 'Auto': 19.758, 'CCWM': -6.746, 'TeamName': 'Method 2R Madness'}, {'TeamNum': 2887, 'OPR': 65.043, 'Auto': 24.512, 'CCWM': -26.833, 'TeamName': 'Bucket Brigade'}, {'TeamNum': 18487, 'OPR': 58.7, 'Auto': 18.815, 'CCWM': -32.826, 'TeamName': 'TaCodeCats'}, {'TeamNum': 20032, 'OPR': 56.84, 'Auto': 15.566, 'CCWM': -62.988, 'TeamName': 'Cyber Machina'}, {'TeamNum': 19542, 'OPR': 53.217, 'Auto': 7.561, 'CCWM': -37.225, 'TeamName': 'The CIA'}, {'TeamNum': 17240, 'OPR': 52.815, 'Auto': 5.921, 'CCWM': -15.201, 'TeamName': 'Iron Eagles'}, {'TeamNum': 12660, 'OPR': 51.605, 'Auto': 13.523, 'CCWM': -25.685, 'TeamName': 'Robotters'}, {'TeamNum': 17221, 'OPR': 50.793, 'Auto': 15.557, 'CCWM': -3.045, 'TeamName': 'High Voltage'}, {'TeamNum': 22162, 'OPR': 36.458, 'Auto': 11.336, 'CCWM': -40.827, 'TeamName': 'M-TECH ProtoPlazma'}, {'TeamNum': 11206, 'OPR': 35.269, 'Auto': 3.859, 'CCWM': -1.976, 'TeamName': 'Devildogs'}, {'TeamNum': 12649, 'OPR': 30.34, 'Auto': 14.771, 'CCWM': -73.411, 'TeamName': 'Code Blooded'}, {'TeamNum': 22181, 'OPR': 18.295, 'Auto': 0.316, 'CCWM': -75.105, 'TeamName': 'WARP2'}]
https://ftc-events.firstinspires.org/2022/USMNCMPNAN2/qualifications
{'8962', '9205', '11873', '14188', '10273', '21305', '17287', '14556', '3764', '18535', '20075', '16232', '12761', '16917', '19706', '7231', '18555', '22161', '3558', '11117', '13603', '19566', '14779', '7288'}
{'8962', '9205', '11873', '14188', '10273', '21305', '17287', '14556', '3764', '18535', '20075', '16232', '12761', '16917', '19706', '7231', '18555', '22161', '3558', '11117', '13603', '19566', '14779', '7288'}
[{'TeamNum': 13603, 'OPR': 129.374, 'Auto': 32.258, 'CCWM': 56.372, 'TeamName': 'Hackercats'}, {'TeamNum': 14188, 'OPR': 107.372, 'Auto': 16.661, 'CCWM': 18.319, 'TeamName': 'CyberHawks14188'}, {'TeamNum': 16232, 'OPR': 96.815, 'Auto': 24.357, 'CCWM': 33.594, 'TeamName': 'Chaska Circuit Breakers'}, {'TeamNum': 7288, 'OPR': 87.02, 'Auto': 31.527, 'CCWM': 41.475, 'TeamName': 'RoboGlaciers'}, {'TeamNum': 21305, 'OPR': 86.243, 'Auto': 23.729, 'CCWM': 16.377, 'TeamName': 'Rogue Cats'}, {'TeamNum': 18535, 'OPR': 85.619, 'Auto': 20.78, 'CCWM': 45.261, 'TeamName': 'Fellowship of the Spring'}, {'TeamNum': 3764, 'OPR': 82.981, 'Auto': 24.566, 'CCWM': 22.289, 'TeamName': 'Since Sliced Bread'}, {'TeamNum': 22161, 'OPR': 81.099, 'Auto': 8.031, 'CCWM': 6.259, 'TeamName': 'M-TECH Dark Matter'}, {'TeamNum': 19706, 'OPR': 77.477, 'Auto': 23.755, 'CCWM': 15.457, 'TeamName': 'Potential Energy'}, {'TeamNum': 3558, 'OPR': 77.261, 'Auto': 7.174, 'CCWM': 7.171, 'TeamName': 'FireBots'}, {'TeamNum': 9205, 'OPR': 75.898, 'Auto': 14.921, 'CCWM': 11.847, 'TeamName': 'Iron Maidens'}, {'TeamNum': 16917, 'OPR': 74.209, 'Auto': 19.691, 'CCWM': 0.674, 'TeamName': 'Gear Wizards'}, {'TeamNum': 14556, 'OPR': 72.059, 'Auto': 23.67, 'CCWM': -29.89, 'TeamName': 'Tactical Tech Tomato Turtles'}, {'TeamNum': 14779, 'OPR': 70.977, 'Auto': 22.181, 'CCWM': -19.097, 'TeamName': 'Spontaneous Construction'}, {'TeamNum': 17287, 'OPR': 63.204, 'Auto': 11.033, 'CCWM': 2.288, 'TeamName': 'My Favorite Team'}, {'TeamNum': 18555, 'OPR': 62.49, 'Auto': 7.421, 'CCWM': 11.608, 'TeamName': 'Unity High School TechSperts'}, {'TeamNum': 7231, 'OPR': 62.065, 'Auto': 18.784, 'CCWM': -4.418, 'TeamName': 'The Purple Circuits'}, {'TeamNum': 8962, 'OPR': 60.504, 'Auto': 13.819, 'CCWM': 9.551, 'TeamName': 'TimeCrafters'}, {'TeamNum': 12761, 'OPR': 51.159, 'Auto': 22.182, 'CCWM': -69.594, 'TeamName': 'Clankers'}, {'TeamNum': 20075, 'OPR': 50.116, 'Auto': 13.455, 'CCWM': -23.848, 'TeamName': 'CapFish'}, {'TeamNum': 11873, 'OPR': 47.827, 'Auto': 19.937, 'CCWM': -19.782, 'TeamName': 'Element Unknown'}, {'TeamNum': 11117, 'OPR': 47.333, 'Auto': 15.369, 'CCWM': -27.575, 'TeamName': 'Autonomice'}, {'TeamNum': 10273, 'OPR': 42.041, 'Auto': 19.965, 'CCWM': -59.583, 'TeamName': 'The Cat in The Hat Comes Back'}, {'TeamNum': 19566, 'OPR': 42.024, 'Auto': 9.4, 'CCWM': -44.756, 'TeamName': 'Coding the Cosmics'}]
[{'TeamNum': 13603, 'OPR': 129.374, 'Auto': 32.258, 'CCWM': 56.372, 'TeamName': 'Hackercats'}, {'TeamNum': 14188, 'OPR': 107.372, 'Auto': 16.661, 'CCWM': 18.319, 'TeamName': 'CyberHawks14188'}, {'TeamNum': 16232, 'OPR': 96.815, 'Auto': 24.357, 'CCWM': 33.594, 'TeamName': 'Chaska Circuit Breakers'}, {'TeamNum': 7288, 'OPR': 87.02, 'Auto': 31.527, 'CCWM': 41.475, 'TeamName': 'RoboGlaciers'}, {'TeamNum': 21305, 'OPR': 86.243, 'Auto': 23.729, 'CCWM': 16.377, 'TeamName': 'Rogue Cats'}, {'TeamNum': 18535, 'OPR': 85.619, 'Auto': 20.78, 'CCWM': 45.261, 'TeamName': 'Fellowship of the Spring'}, {'TeamNum': 3764, 'OPR': 82.981, 'Auto': 24.566, 'CCWM': 22.289, 'TeamName': 'Since Sliced Bread'}, {'TeamNum': 22161, 'OPR': 81.099, 'Auto': 8.031, 'CCWM': 6.259, 'TeamName': 'M-TECH Dark Matter'}, {'TeamNum': 19706, 'OPR': 77.477, 'Auto': 23.755, 'CCWM': 15.457, 'TeamName': 'Potential Energy'}, {'TeamNum': 3558, 'OPR': 77.261, 'Auto': 7.174, 'CCWM': 7.171, 'TeamName': 'FireBots'}, {'TeamNum': 9205, 'OPR': 75.898, 'Auto': 14.921, 'CCWM': 11.847, 'TeamName': 'Iron Maidens'}, {'TeamNum': 16917, 'OPR': 74.209, 'Auto': 19.691, 'CCWM': 0.674, 'TeamName': 'Gear Wizards'}, {'TeamNum': 14556, 'OPR': 72.059, 'Auto': 23.67, 'CCWM': -29.89, 'TeamName': 'Tactical Tech Tomato Turtles'}, {'TeamNum': 14779, 'OPR': 70.977, 'Auto': 22.181, 'CCWM': -19.097, 'TeamName': 'Spontaneous Construction'}, {'TeamNum': 17287, 'OPR': 63.204, 'Auto': 11.033, 'CCWM': 2.288, 'TeamName': 'My Favorite Team'}, {'TeamNum': 18555, 'OPR': 62.49, 'Auto': 7.421, 'CCWM': 11.608, 'TeamName': 'Unity High School TechSperts'}, {'TeamNum': 7231, 'OPR': 62.065, 'Auto': 18.784, 'CCWM': -4.418, 'TeamName': 'The Purple Circuits'}, {'TeamNum': 8962, 'OPR': 60.504, 'Auto': 13.819, 'CCWM': 9.551, 'TeamName': 'TimeCrafters'}, {'TeamNum': 12761, 'OPR': 51.159, 'Auto': 22.182, 'CCWM': -69.594, 'TeamName': 'Clankers'}, {'TeamNum': 20075, 'OPR': 50.116, 'Auto': 13.455, 'CCWM': -23.848, 'TeamName': 'CapFish'}, {'TeamNum': 11873, 'OPR': 47.827, 'Auto': 19.937, 'CCWM': -19.782, 'TeamName': 'Element Unknown'}, {'TeamNum': 11117, 'OPR': 47.333, 'Auto': 15.369, 'CCWM': -27.575, 'TeamName': 'Autonomice'}, {'TeamNum': 10273, 'OPR': 42.041, 'Auto': 19.965, 'CCWM': -59.583, 'TeamName': 'The Cat in The Hat Comes Back'}, {'TeamNum': 19566, 'OPR': 42.024, 'Auto': 9.4, 'CCWM': -44.756, 'TeamName': 'Coding the Cosmics'}]

i 9
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-759F91AC-70CE-4F40-BE37-F7AA924DBB84")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-2485D978-0CAA-406D-BD3F-125495746330")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-CABC7B72-4770-445F-B6E9-5DF90E331252")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-7975E438-5A94-48BE-A739-697E7C34928A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-B6FFDB06-3703-4DA4-8A0A-9D4EC816D1A8")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-9928DF63-CBF3-4D02-BB53-B7C9E6DC00C3")>]
https://ftc-events.firstinspires.org/2022/USAZCMPGC23/qualifications
{'6174', '18420', '22256', '22120', '15135', '10523', '10111', '22265', '10984', '16647', '19728', '20775', '13968', '11365', '21579', '11794', '7156', '8081', '14855', '12767', '3666', '14835', '14624', '10369'}
{'6174', '18420', '22256', '22120', '15135', '10523', '10111', '22265', '10984', '16647', '19728', '20775', '13968', '11365', '21579', '11794', '7156', '8081', '14855', '12767', '3666', '14835', '14624', '10369'}
[{'TeamNum': 21579, 'OPR': 90.808, 'Auto': 29.0, 'CCWM': 25.909, 'TeamName': 'Testing is Optional'}, {'TeamNum': 19728, 'OPR': 85.391, 'Auto': 19.078, 'CCWM': 21.289, 'TeamName': 'Carbo-Knights'}, {'TeamNum': 22120, 'OPR': 79.306, 'Auto': 21.191, 'CCWM': 21.501, 'TeamName': 'Foothills Cat - 3'}, {'TeamNum': 12767, 'OPR': 76.209, 'Auto': 30.274, 'CCWM': 25.222, 'TeamName': 'Catholic Master Builders'}, {'TeamNum': 10369, 'OPR': 68.296, 'Auto': 21.025, 'CCWM': 48.447, 'TeamName': 'Robosapiens'}, {'TeamNum': 8081, 'OPR': 66.171, 'Auto': 12.494, 'CCWM': 41.754, 'TeamName': 'Knights of the Lab Table'}, {'TeamNum': 10111, 'OPR': 64.826, 'Auto': 12.237, 'CCWM': 3.457, 'TeamName': 'Herberger Javelinas'}, {'TeamNum': 6174, 'OPR': 60.978, 'Auto': 16.54, 'CCWM': 0.461, 'TeamName': 'Automatons'}, {'TeamNum': 11794, 'OPR': 59.611, 'Auto': 11.463, 'CCWM': 6.01, 'TeamName': 'Sunrise Koolbotics'}, {'TeamNum': 18420, 'OPR': 59.489, 'Auto': 15.225, 'CCWM': -11.577, 'TeamName': 'Metal Masters'}, {'TeamNum': 10984, 'OPR': 58.52, 'Auto': 16.386, 'CCWM': 22.708, 'TeamName': 'Beep Patrol'}, {'TeamNum': 14835, 'OPR': 58.503, 'Auto': 12.653, 'CCWM': 13.867, 'TeamName': 'Tie-Dye Samurai'}, {'TeamNum': 14855, 'OPR': 57.566, 'Auto': 23.487, 'CCWM': 3.726, 'TeamName': 'Shamrocks'}, {'TeamNum': 10523, 'OPR': 54.73, 'Auto': 6.389, 'CCWM': 26.251, 'TeamName': 'Dragons'}, {'TeamNum': 16647, 'OPR': 53.455, 'Auto': 8.019, 'CCWM': -0.449, 'TeamName': 'Trivium Undefined'}, {'TeamNum': 15135, 'OPR': 52.41, 'Auto': 7.006, 'CCWM': -30.322, 'TeamName': 'Venom'}, {'TeamNum': 3666, 'OPR': 48.644, 'Auto': 22.428, 'CCWM': -30.618, 'TeamName': 'Hawks Robotics'}, {'TeamNum': 20775, 'OPR': 36.753, 'Auto': 3.657, 'CCWM': 0.269, 'TeamName': 'Pinnacle Robotics'}, {'TeamNum': 22265, 'OPR': 31.183, 'Auto': 3.943, 'CCWM': 16.674, 'TeamName': 'Gear Hounds'}, {'TeamNum': 13968, 'OPR': 27.011, 'Auto': 5.368, 'CCWM': -53.305, 'TeamName': 'Herberger Howlers'}, {'TeamNum': 7156, 'OPR': 24.803, 'Auto': 4.967, 'CCWM': -21.201, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 11365, 'OPR': 14.723, 'Auto': -5.765, 'CCWM': -69.061, 'TeamName': 'Ticket To Paradise'}, {'TeamNum': 22256, 'OPR': 8.044, 'Auto': -10.238, 'CCWM': -33.835, 'TeamName': 'Herobotix C.I.S.'}, {'TeamNum': 14624, 'OPR': -2.232, 'Auto': -0.825, 'CCWM': -27.177, 'TeamName': 'Cat-astrophic Byte - Jaguar Robotics'}]
[{'TeamNum': 21579, 'OPR': 90.808, 'Auto': 29.0, 'CCWM': 25.909, 'TeamName': 'Testing is Optional'}, {'TeamNum': 19728, 'OPR': 85.391, 'Auto': 19.078, 'CCWM': 21.289, 'TeamName': 'Carbo-Knights'}, {'TeamNum': 22120, 'OPR': 79.306, 'Auto': 21.191, 'CCWM': 21.501, 'TeamName': 'Foothills Cat - 3'}, {'TeamNum': 12767, 'OPR': 76.209, 'Auto': 30.274, 'CCWM': 25.222, 'TeamName': 'Catholic Master Builders'}, {'TeamNum': 10369, 'OPR': 68.296, 'Auto': 21.025, 'CCWM': 48.447, 'TeamName': 'Robosapiens'}, {'TeamNum': 8081, 'OPR': 66.171, 'Auto': 12.494, 'CCWM': 41.754, 'TeamName': 'Knights of the Lab Table'}, {'TeamNum': 10111, 'OPR': 64.826, 'Auto': 12.237, 'CCWM': 3.457, 'TeamName': 'Herberger Javelinas'}, {'TeamNum': 6174, 'OPR': 60.978, 'Auto': 16.54, 'CCWM': 0.461, 'TeamName': 'Automatons'}, {'TeamNum': 11794, 'OPR': 59.611, 'Auto': 11.463, 'CCWM': 6.01, 'TeamName': 'Sunrise Koolbotics'}, {'TeamNum': 18420, 'OPR': 59.489, 'Auto': 15.225, 'CCWM': -11.577, 'TeamName': 'Metal Masters'}, {'TeamNum': 10984, 'OPR': 58.52, 'Auto': 16.386, 'CCWM': 22.708, 'TeamName': 'Beep Patrol'}, {'TeamNum': 14835, 'OPR': 58.503, 'Auto': 12.653, 'CCWM': 13.867, 'TeamName': 'Tie-Dye Samurai'}, {'TeamNum': 14855, 'OPR': 57.566, 'Auto': 23.487, 'CCWM': 3.726, 'TeamName': 'Shamrocks'}, {'TeamNum': 10523, 'OPR': 54.73, 'Auto': 6.389, 'CCWM': 26.251, 'TeamName': 'Dragons'}, {'TeamNum': 16647, 'OPR': 53.455, 'Auto': 8.019, 'CCWM': -0.449, 'TeamName': 'Trivium Undefined'}, {'TeamNum': 15135, 'OPR': 52.41, 'Auto': 7.006, 'CCWM': -30.322, 'TeamName': 'Venom'}, {'TeamNum': 3666, 'OPR': 48.644, 'Auto': 22.428, 'CCWM': -30.618, 'TeamName': 'Hawks Robotics'}, {'TeamNum': 20775, 'OPR': 36.753, 'Auto': 3.657, 'CCWM': 0.269, 'TeamName': 'Pinnacle Robotics'}, {'TeamNum': 22265, 'OPR': 31.183, 'Auto': 3.943, 'CCWM': 16.674, 'TeamName': 'Gear Hounds'}, {'TeamNum': 13968, 'OPR': 27.011, 'Auto': 5.368, 'CCWM': -53.305, 'TeamName': 'Herberger Howlers'}, {'TeamNum': 7156, 'OPR': 24.803, 'Auto': 4.967, 'CCWM': -21.201, 'TeamName': 'Wolves Robotics 2'}, {'TeamNum': 11365, 'OPR': 14.723, 'Auto': -5.765, 'CCWM': -69.061, 'TeamName': 'Ticket To Paradise'}, {'TeamNum': 22256, 'OPR': 8.044, 'Auto': -10.238, 'CCWM': -33.835, 'TeamName': 'Herobotix C.I.S.'}, {'TeamNum': 14624, 'OPR': -2.232, 'Auto': -0.825, 'CCWM': -27.177, 'TeamName': 'Cat-astrophic Byte - Jaguar Robotics'}]
https://ftc-events.firstinspires.org/2022/USAZCMPSG23/qualifications
{'17062', '11980', '18445', '17460', '20679', '22295', '2844', '21329', '9743', '15477', '20098', '16817', '18625', '18291', '14436', '201', '13910', '14584', '12841', '14254', '18421', '15461', '10246', '15186'}
{'17062', '11980', '18445', '17460', '20679', '22295', '2844', '21329', '9743', '15477', '20098', '16817', '18625', '18291', '14436', '201', '13910', '14584', '12841', '14254', '18421', '15461', '10246', '15186'}
[{'TeamNum': 21329, 'OPR': 98.686, 'Auto': 20.302, 'CCWM': 83.78, 'TeamName': 'Squires of the Lab Table'}, {'TeamNum': 18625, 'OPR': 90.288, 'Auto': 25.986, 'CCWM': 70.247, 'TeamName': 'Trivium Knightmares'}, {'TeamNum': 14436, 'OPR': 82.769, 'Auto': 18.435, 'CCWM': 32.347, 'TeamName': 'Roaring Robotics'}, {'TeamNum': 18291, 'OPR': 79.285, 'Auto': 22.236, 'CCWM': 22.395, 'TeamName': 'Mech Warriors'}, {'TeamNum': 17460, 'OPR': 78.495, 'Auto': 13.847, 'CCWM': 47.366, 'TeamName': 'Technical Terrors'}, {'TeamNum': 18421, 'OPR': 77.851, 'Auto': 22.33, 'CCWM': 5.629, 'TeamName': 'Unscheduled Disassembly'}, {'TeamNum': 14584, 'OPR': 73.056, 'Auto': 21.434, 'CCWM': -2.399, 'TeamName': 'Pioneer 327'}, {'TeamNum': 12841, 'OPR': 72.17, 'Auto': 9.129, 'CCWM': 10.478, 'TeamName': 'Plus +3 Robotics'}, {'TeamNum': 10246, 'OPR': 69.075, 'Auto': 8.247, 'CCWM': 10.286, 'TeamName': 'The Midnight Cicadas'}, {'TeamNum': 17062, 'OPR': 60.515, 'Auto': 11.768, 'CCWM': 39.95, 'TeamName': 'Girls in Tech / Girl Scout - Techalongs'}, {'TeamNum': 2844, 'OPR': 58.888, 'Auto': 15.058, 'CCWM': 11.347, 'TeamName': 'Valley X Robotics'}, {'TeamNum': 15461, 'OPR': 57.661, 'Auto': 13.505, 'CCWM': 43.509, 'TeamName': 'Nutz and Bolts'}, {'TeamNum': 14254, 'OPR': 49.128, 'Auto': 12.391, 'CCWM': 1.065, 'TeamName': 'Trivium Knight Lights'}, {'TeamNum': 16817, 'OPR': 30.616, 'Auto': -2.021, 'CCWM': -18.09, 'TeamName': 'Rocksisaan Tech'}, {'TeamNum': 13910, 'OPR': 28.427, 'Auto': -3.749, 'CCWM': -57.254, 'TeamName': 'Voltage'}, {'TeamNum': 15477, 'OPR': 28.291, 'Auto': 5.289, 'CCWM': -43.714, 'TeamName': 'Robo-Assemblers'}, {'TeamNum': 22295, 'OPR': 22.144, 'Auto': -1.745, 'CCWM': 3.408, 'TeamName': 'Power Outage'}, {'TeamNum': 15186, 'OPR': 17.969, 'Auto': -4.162, 'CCWM': -29.845, 'TeamName': 'Falcon Robotics'}, {'TeamNum': 201, 'OPR': 17.805, 'Auto': 6.212, 'CCWM': -62.724, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 11980, 'OPR': 16.9, 'Auto': -5.335, 'CCWM': -19.116, 'TeamName': 'Team Viper'}, {'TeamNum': 9743, 'OPR': 15.081, 'Auto': 4.963, 'CCWM': -47.154, 'TeamName': 'Stinger Robotics'}, {'TeamNum': 18445, 'OPR': 13.608, 'Auto': -4.612, 'CCWM': -30.627, 'TeamName': 'BinaryBots'}, {'TeamNum': 20679, 'OPR': 12.185, 'Auto': 8.086, 'CCWM': -32.758, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 20098, 'OPR': -8.493, 'Auto': -1.796, 'CCWM': -38.13, 'TeamName': 'Knight Tech Robotics 2'}]
[{'TeamNum': 21329, 'OPR': 98.686, 'Auto': 20.302, 'CCWM': 83.78, 'TeamName': 'Squires of the Lab Table'}, {'TeamNum': 18625, 'OPR': 90.288, 'Auto': 25.986, 'CCWM': 70.247, 'TeamName': 'Trivium Knightmares'}, {'TeamNum': 14436, 'OPR': 82.769, 'Auto': 18.435, 'CCWM': 32.347, 'TeamName': 'Roaring Robotics'}, {'TeamNum': 18291, 'OPR': 79.285, 'Auto': 22.236, 'CCWM': 22.395, 'TeamName': 'Mech Warriors'}, {'TeamNum': 17460, 'OPR': 78.495, 'Auto': 13.847, 'CCWM': 47.366, 'TeamName': 'Technical Terrors'}, {'TeamNum': 18421, 'OPR': 77.851, 'Auto': 22.33, 'CCWM': 5.629, 'TeamName': 'Unscheduled Disassembly'}, {'TeamNum': 14584, 'OPR': 73.056, 'Auto': 21.434, 'CCWM': -2.399, 'TeamName': 'Pioneer 327'}, {'TeamNum': 12841, 'OPR': 72.17, 'Auto': 9.129, 'CCWM': 10.478, 'TeamName': 'Plus +3 Robotics'}, {'TeamNum': 10246, 'OPR': 69.075, 'Auto': 8.247, 'CCWM': 10.286, 'TeamName': 'The Midnight Cicadas'}, {'TeamNum': 17062, 'OPR': 60.515, 'Auto': 11.768, 'CCWM': 39.95, 'TeamName': 'Girls in Tech / Girl Scout - Techalongs'}, {'TeamNum': 2844, 'OPR': 58.888, 'Auto': 15.058, 'CCWM': 11.347, 'TeamName': 'Valley X Robotics'}, {'TeamNum': 15461, 'OPR': 57.661, 'Auto': 13.505, 'CCWM': 43.509, 'TeamName': 'Nutz and Bolts'}, {'TeamNum': 14254, 'OPR': 49.128, 'Auto': 12.391, 'CCWM': 1.065, 'TeamName': 'Trivium Knight Lights'}, {'TeamNum': 16817, 'OPR': 30.616, 'Auto': -2.021, 'CCWM': -18.09, 'TeamName': 'Rocksisaan Tech'}, {'TeamNum': 13910, 'OPR': 28.427, 'Auto': -3.749, 'CCWM': -57.254, 'TeamName': 'Voltage'}, {'TeamNum': 15477, 'OPR': 28.291, 'Auto': 5.289, 'CCWM': -43.714, 'TeamName': 'Robo-Assemblers'}, {'TeamNum': 22295, 'OPR': 22.144, 'Auto': -1.745, 'CCWM': 3.408, 'TeamName': 'Power Outage'}, {'TeamNum': 15186, 'OPR': 17.969, 'Auto': -4.162, 'CCWM': -29.845, 'TeamName': 'Falcon Robotics'}, {'TeamNum': 201, 'OPR': 17.805, 'Auto': 6.212, 'CCWM': -62.724, 'TeamName': 'BroncoBotsONE'}, {'TeamNum': 11980, 'OPR': 16.9, 'Auto': -5.335, 'CCWM': -19.116, 'TeamName': 'Team Viper'}, {'TeamNum': 9743, 'OPR': 15.081, 'Auto': 4.963, 'CCWM': -47.154, 'TeamName': 'Stinger Robotics'}, {'TeamNum': 18445, 'OPR': 13.608, 'Auto': -4.612, 'CCWM': -30.627, 'TeamName': 'BinaryBots'}, {'TeamNum': 20679, 'OPR': 12.185, 'Auto': 8.086, 'CCWM': -32.758, 'TeamName': 'Tech Cat Robotics'}, {'TeamNum': 20098, 'OPR': -8.493, 'Auto': -1.796, 'CCWM': -38.13, 'TeamName': 'Knight Tech Robotics 2'}]

i 10
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-074855A9-1A20-47E8-A875-2C642C8DDCFC")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-E2F33EA9-F2C4-4AEF-98AD-EC3F259A4574")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-F7713FE2-08A1-4371-84D6-7FBA2450933B")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-E2252069-FD0E-4BA2-B60E-8450392E1737")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-1412975C-6D56-435A-B17B-2FBB592519B9")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-1740C684-6FB6-4950-8EE5-A98C9574F4E6")>]
https://ftc-events.firstinspires.org/2022/USCANOCMPAU/qualifications
{'16532', '21376', '14493', '18247', '20424', '21316', '8404', '8872', '18309', '7641', '16533', '5773', '12635', '16236', '14473', '11099', '16887', '6165', '17759', '16778', '11311', '14525', '18254', '14318'}
{'16532', '21376', '14493', '18247', '20424', '21316', '8404', '8872', '18309', '7641', '16533', '5773', '12635', '16236', '14473', '11099', '16887', '6165', '17759', '16778', '11311', '14525', '18254', '14318'}
[{'TeamNum': 12635, 'OPR': 137.996, 'Auto': 49.579, 'CCWM': 96.529, 'TeamName': 'Kuriosity Robotics'}, {'TeamNum': 14525, 'OPR': 126.113, 'Auto': 41.915, 'CCWM': 53.597, 'TeamName': 'TerraBats'}, {'TeamNum': 18254, 'OPR': 115.643, 'Auto': 33.826, 'CCWM': 45.461, 'TeamName': 'The InZain Bots'}, {'TeamNum': 21316, 'OPR': 113.028, 'Auto': 24.245, 'CCWM': 50.372, 'TeamName': 'Team Alpha'}, {'TeamNum': 17759, 'OPR': 107.225, 'Auto': 28.228, 'CCWM': 24.735, 'TeamName': 'Mind'}, {'TeamNum': 8872, 'OPR': 103.072, 'Auto': 30.85, 'CCWM': 6.06, 'TeamName': 'Robopocalypse'}, {'TeamNum': 6165, 'OPR': 94.57, 'Auto': 25.602, 'CCWM': 30.539, 'TeamName': 'MSET CuttleFish'}, {'TeamNum': 16533, 'OPR': 90.456, 'Auto': 26.922, 'CCWM': 23.472, 'TeamName': 'Infernobots'}, {'TeamNum': 16532, 'OPR': 84.691, 'Auto': 29.497, 'CCWM': 13.922, 'TeamName': 'Sparkbots'}, {'TeamNum': 16236, 'OPR': 84.138, 'Auto': 26.999, 'CCWM': 25.4, 'TeamName': 'Juice'}, {'TeamNum': 14473, 'OPR': 82.475, 'Auto': 13.729, 'CCWM': 37.661, 'TeamName': 'Future'}, {'TeamNum': 11311, 'OPR': 79.865, 'Auto': 21.843, 'CCWM': -7.969, 'TeamName': 'Paragon'}, {'TeamNum': 16778, 'OPR': 71.507, 'Auto': 24.253, 'CCWM': 19.373, 'TeamName': 'Cyber Wizards'}, {'TeamNum': 14493, 'OPR': 66.846, 'Auto': 8.666, 'CCWM': -24.942, 'TeamName': 'Comet BOTs'}, {'TeamNum': 18309, 'OPR': 63.806, 'Auto': 5.404, 'CCWM': -31.712, 'TeamName': 'Dream Machines'}, {'TeamNum': 11099, 'OPR': 62.75, 'Auto': 15.724, 'CCWM': 8.079, 'TeamName': 'Tacobots'}, {'TeamNum': 16887, 'OPR': 52.968, 'Auto': 16.751, 'CCWM': -23.414, 'TeamName': 'RGB'}, {'TeamNum': 7641, 'OPR': 48.448, 'Auto': 8.412, 'CCWM': -33.546, 'TeamName': 'MSET BettaFish'}, {'TeamNum': 14318, 'OPR': 46.796, 'Auto': 22.119, 'CCWM': -63.199, 'TeamName': 'BioBots'}, {'TeamNum': 20424, 'OPR': 45.953, 'Auto': 6.779, 'CCWM': -26.201, 'TeamName': 'Zenith'}, {'TeamNum': 21376, 'OPR': 39.014, 'Auto': -6.705, 'CCWM': -43.638, 'TeamName': 'BOOM SHAKA LAKA'}, {'TeamNum': 5773, 'OPR': 38.028, 'Auto': 20.893, 'CCWM': -42.717, 'TeamName': 'Ink and Metal'}, {'TeamNum': 8404, 'OPR': 34.607, 'Auto': -0.474, 'CCWM': -40.146, 'TeamName': 'Quixilver '}, {'TeamNum': 18247, 'OPR': 32.339, 'Auto': 8.275, 'CCWM': -97.716, 'TeamName': 'Build-A-Bot'}]
[{'TeamNum': 12635, 'OPR': 137.996, 'Auto': 49.579, 'CCWM': 96.529, 'TeamName': 'Kuriosity Robotics'}, {'TeamNum': 14525, 'OPR': 126.113, 'Auto': 41.915, 'CCWM': 53.597, 'TeamName': 'TerraBats'}, {'TeamNum': 18254, 'OPR': 115.643, 'Auto': 33.826, 'CCWM': 45.461, 'TeamName': 'The InZain Bots'}, {'TeamNum': 21316, 'OPR': 113.028, 'Auto': 24.245, 'CCWM': 50.372, 'TeamName': 'Team Alpha'}, {'TeamNum': 17759, 'OPR': 107.225, 'Auto': 28.228, 'CCWM': 24.735, 'TeamName': 'Mind'}, {'TeamNum': 8872, 'OPR': 103.072, 'Auto': 30.85, 'CCWM': 6.06, 'TeamName': 'Robopocalypse'}, {'TeamNum': 6165, 'OPR': 94.57, 'Auto': 25.602, 'CCWM': 30.539, 'TeamName': 'MSET CuttleFish'}, {'TeamNum': 16533, 'OPR': 90.456, 'Auto': 26.922, 'CCWM': 23.472, 'TeamName': 'Infernobots'}, {'TeamNum': 16532, 'OPR': 84.691, 'Auto': 29.497, 'CCWM': 13.922, 'TeamName': 'Sparkbots'}, {'TeamNum': 16236, 'OPR': 84.138, 'Auto': 26.999, 'CCWM': 25.4, 'TeamName': 'Juice'}, {'TeamNum': 14473, 'OPR': 82.475, 'Auto': 13.729, 'CCWM': 37.661, 'TeamName': 'Future'}, {'TeamNum': 11311, 'OPR': 79.865, 'Auto': 21.843, 'CCWM': -7.969, 'TeamName': 'Paragon'}, {'TeamNum': 16778, 'OPR': 71.507, 'Auto': 24.253, 'CCWM': 19.373, 'TeamName': 'Cyber Wizards'}, {'TeamNum': 14493, 'OPR': 66.846, 'Auto': 8.666, 'CCWM': -24.942, 'TeamName': 'Comet BOTs'}, {'TeamNum': 18309, 'OPR': 63.806, 'Auto': 5.404, 'CCWM': -31.712, 'TeamName': 'Dream Machines'}, {'TeamNum': 11099, 'OPR': 62.75, 'Auto': 15.724, 'CCWM': 8.079, 'TeamName': 'Tacobots'}, {'TeamNum': 16887, 'OPR': 52.968, 'Auto': 16.751, 'CCWM': -23.414, 'TeamName': 'RGB'}, {'TeamNum': 7641, 'OPR': 48.448, 'Auto': 8.412, 'CCWM': -33.546, 'TeamName': 'MSET BettaFish'}, {'TeamNum': 14318, 'OPR': 46.796, 'Auto': 22.119, 'CCWM': -63.199, 'TeamName': 'BioBots'}, {'TeamNum': 20424, 'OPR': 45.953, 'Auto': 6.779, 'CCWM': -26.201, 'TeamName': 'Zenith'}, {'TeamNum': 21376, 'OPR': 39.014, 'Auto': -6.705, 'CCWM': -43.638, 'TeamName': 'BOOM SHAKA LAKA'}, {'TeamNum': 5773, 'OPR': 38.028, 'Auto': 20.893, 'CCWM': -42.717, 'TeamName': 'Ink and Metal'}, {'TeamNum': 8404, 'OPR': 34.607, 'Auto': -0.474, 'CCWM': -40.146, 'TeamName': 'Quixilver '}, {'TeamNum': 18247, 'OPR': 32.339, 'Auto': 8.275, 'CCWM': -97.716, 'TeamName': 'Build-A-Bot'}]
https://ftc-events.firstinspires.org/2022/USCANOCMPSI/qualifications
{'19819', '9614', '18504', '18466', '16944', '7303', '18715', '9656', '11898', '13356', '20373', '13216', '16886', '16481', '22330', '8381', '10023', '8375', '14259', '19639', '11039', '14969', '9784', '12804'}
{'19819', '9614', '18504', '18466', '16944', '7303', '18715', '9656', '11898', '13356', '20373', '13216', '16886', '16481', '22330', '8381', '10023', '8375', '14259', '19639', '11039', '14969', '9784', '12804'}
[{'TeamNum': 13356, 'OPR': 145.362, 'Auto': 47.951, 'CCWM': 96.678, 'TeamName': 'RoboForce'}, {'TeamNum': 9614, 'OPR': 140.094, 'Auto': 39.514, 'CCWM': 43.162, 'TeamName': 'Hyperion'}, {'TeamNum': 11039, 'OPR': 131.211, 'Auto': 31.888, 'CCWM': 86.057, 'TeamName': 'Innov8rz'}, {'TeamNum': 7303, 'OPR': 117.563, 'Auto': 36.858, 'CCWM': 74.507, 'TeamName': 'RoboAvatars'}, {'TeamNum': 8375, 'OPR': 107.618, 'Auto': 21.104, 'CCWM': 16.104, 'TeamName': 'Vulcan Robotics'}, {'TeamNum': 8381, 'OPR': 92.368, 'Auto': 28.21, 'CCWM': 2.606, 'TeamName': 'M'}, {'TeamNum': 20373, 'OPR': 89.452, 'Auto': 27.409, 'CCWM': 0.314, 'TeamName': 'RMS Chimera'}, {'TeamNum': 13216, 'OPR': 84.708, 'Auto': 11.486, 'CCWM': 3.272, 'TeamName': 'Deja Vu'}, {'TeamNum': 14259, 'OPR': 81.705, 'Auto': 22.473, 'CCWM': 7.597, 'TeamName': 'TURBΩ V8'}, {'TeamNum': 9784, 'OPR': 78.007, 'Auto': 31.059, 'CCWM': -46.603, 'TeamName': 'Dry Ice'}, {'TeamNum': 14969, 'OPR': 75.015, 'Auto': 18.912, 'CCWM': 0.098, 'TeamName': 'Vortex'}, {'TeamNum': 9656, 'OPR': 72.516, 'Auto': 15.676, 'CCWM': 13.339, 'TeamName': 'Omega'}, {'TeamNum': 10023, 'OPR': 69.701, 'Auto': 20.514, 'CCWM': -16.942, 'TeamName': 'Who charged the battery'}, {'TeamNum': 19639, 'OPR': 67.065, 'Auto': 35.216, 'CCWM': -7.058, 'TeamName': 'Alphabots'}, {'TeamNum': 16886, 'OPR': 66.848, 'Auto': -0.591, 'CCWM': 9.691, 'TeamName': 'Dumpster Fire'}, {'TeamNum': 16481, 'OPR': 60.828, 'Auto': 9.908, 'CCWM': -7.059, 'TeamName': 'Robo Racers'}, {'TeamNum': 18466, 'OPR': 60.786, 'Auto': 14.264, 'CCWM': 15.754, 'TeamName': 'Mastermindz'}, {'TeamNum': 18504, 'OPR': 55.816, 'Auto': 5.641, 'CCWM': -16.727, 'TeamName': 'MAGIC BOTS'}, {'TeamNum': 11898, 'OPR': 52.853, 'Auto': 15.641, 'CCWM': -59.6, 'TeamName': 'Newark Memorial Robuckets'}, {'TeamNum': 12804, 'OPR': 51.326, 'Auto': 19.105, 'CCWM': -54.73, 'TeamName': 'LED: Ladies of Engineering Design'}, {'TeamNum': 22330, 'OPR': 50.956, 'Auto': 10.884, 'CCWM': -2.282, 'TeamName': 'Monkê'}, {'TeamNum': 16944, 'OPR': 47.031, 'Auto': 15.101, 'CCWM': -48.136, 'TeamName': 'FM493RS'}, {'TeamNum': 19819, 'OPR': 43.795, 'Auto': -4.537, 'CCWM': -38.602, 'TeamName': 'AstroBruins'}, {'TeamNum': 18715, 'OPR': 30.378, 'Auto': -3.854, 'CCWM': -71.439, 'TeamName': 'Artemis'}]
[{'TeamNum': 13356, 'OPR': 145.362, 'Auto': 47.951, 'CCWM': 96.678, 'TeamName': 'RoboForce'}, {'TeamNum': 9614, 'OPR': 140.094, 'Auto': 39.514, 'CCWM': 43.162, 'TeamName': 'Hyperion'}, {'TeamNum': 11039, 'OPR': 131.211, 'Auto': 31.888, 'CCWM': 86.057, 'TeamName': 'Innov8rz'}, {'TeamNum': 7303, 'OPR': 117.563, 'Auto': 36.858, 'CCWM': 74.507, 'TeamName': 'RoboAvatars'}, {'TeamNum': 8375, 'OPR': 107.618, 'Auto': 21.104, 'CCWM': 16.104, 'TeamName': 'Vulcan Robotics'}, {'TeamNum': 8381, 'OPR': 92.368, 'Auto': 28.21, 'CCWM': 2.606, 'TeamName': 'M'}, {'TeamNum': 20373, 'OPR': 89.452, 'Auto': 27.409, 'CCWM': 0.314, 'TeamName': 'RMS Chimera'}, {'TeamNum': 13216, 'OPR': 84.708, 'Auto': 11.486, 'CCWM': 3.272, 'TeamName': 'Deja Vu'}, {'TeamNum': 14259, 'OPR': 81.705, 'Auto': 22.473, 'CCWM': 7.597, 'TeamName': 'TURBΩ V8'}, {'TeamNum': 9784, 'OPR': 78.007, 'Auto': 31.059, 'CCWM': -46.603, 'TeamName': 'Dry Ice'}, {'TeamNum': 14969, 'OPR': 75.015, 'Auto': 18.912, 'CCWM': 0.098, 'TeamName': 'Vortex'}, {'TeamNum': 9656, 'OPR': 72.516, 'Auto': 15.676, 'CCWM': 13.339, 'TeamName': 'Omega'}, {'TeamNum': 10023, 'OPR': 69.701, 'Auto': 20.514, 'CCWM': -16.942, 'TeamName': 'Who charged the battery'}, {'TeamNum': 19639, 'OPR': 67.065, 'Auto': 35.216, 'CCWM': -7.058, 'TeamName': 'Alphabots'}, {'TeamNum': 16886, 'OPR': 66.848, 'Auto': -0.591, 'CCWM': 9.691, 'TeamName': 'Dumpster Fire'}, {'TeamNum': 16481, 'OPR': 60.828, 'Auto': 9.908, 'CCWM': -7.059, 'TeamName': 'Robo Racers'}, {'TeamNum': 18466, 'OPR': 60.786, 'Auto': 14.264, 'CCWM': 15.754, 'TeamName': 'Mastermindz'}, {'TeamNum': 18504, 'OPR': 55.816, 'Auto': 5.641, 'CCWM': -16.727, 'TeamName': 'MAGIC BOTS'}, {'TeamNum': 11898, 'OPR': 52.853, 'Auto': 15.641, 'CCWM': -59.6, 'TeamName': 'Newark Memorial Robuckets'}, {'TeamNum': 12804, 'OPR': 51.326, 'Auto': 19.105, 'CCWM': -54.73, 'TeamName': 'LED: Ladies of Engineering Design'}, {'TeamNum': 22330, 'OPR': 50.956, 'Auto': 10.884, 'CCWM': -2.282, 'TeamName': 'Monkê'}, {'TeamNum': 16944, 'OPR': 47.031, 'Auto': 15.101, 'CCWM': -48.136, 'TeamName': 'FM493RS'}, {'TeamNum': 19819, 'OPR': 43.795, 'Auto': -4.537, 'CCWM': -38.602, 'TeamName': 'AstroBruins'}, {'TeamNum': 18715, 'OPR': 30.378, 'Auto': -3.854, 'CCWM': -71.439, 'TeamName': 'Artemis'}]

i 11
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-93F77BFD-B01F-446A-BDB2-DB23359ACF2D")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-2823E46C-6FF9-4AC7-B7A4-8144436B38A2")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-D79F0560-196E-4E54-94E6-3696ADFD93F3")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-62D5DA42-7731-4AFB-BD2F-953596101C83")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-AC560D0C-6819-4871-B041-256D6026D534")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-790F7662-9F45-41AC-AC82-6AC0FD0990FA")>]
https://ftc-events.firstinspires.org/2022/USFLCMPSCOT/qualifications
{'9214', '16716', '12600', '14708', '10022', '10179', '2845', '13093', '14431', '13233', '10650', '19388', '16484', '18619', '14725', '4717', '3101', '21477', '18172', '7477', '18145', '9986', '22012', '10276', '10583', '22690', '14384', '7592'}
{'9214', '16716', '12600', '14708', '10022', '10179', '2845', '13093', '14431', '13233', '10650', '19388', '16484', '18619', '14725', '4717', '3101', '21477', '18172', '7477', '18145', '9986', '22012', '10276', '10583', '22690', '14384', '7592'}
[{'TeamNum': 14725, 'OPR': 136.27, 'Auto': 38.059, 'CCWM': 52.31, 'TeamName': 'Java the Hutts'}, {'TeamNum': 7592, 'OPR': 120.183, 'Auto': 36.962, 'CCWM': 41.167, 'TeamName': 'Roarbots'}, {'TeamNum': 13093, 'OPR': 103.836, 'Auto': 23.654, 'CCWM': 28.621, 'TeamName': 'Golden Fish'}, {'TeamNum': 10650, 'OPR': 103.727, 'Auto': 28.445, 'CCWM': 44.628, 'TeamName': 'Hazmat Robotics Biohazards'}, {'TeamNum': 22690, 'OPR': 91.662, 'Auto': 16.948, 'CCWM': 24.548, 'TeamName': 'Quantum Bots'}, {'TeamNum': 14384, 'OPR': 90.636, 'Auto': 17.575, 'CCWM': 60.342, 'TeamName': 'Patent Pending'}, {'TeamNum': 10179, 'OPR': 86.897, 'Auto': 35.794, 'CCWM': 23.879, 'TeamName': 'Tech Turtles'}, {'TeamNum': 10022, 'OPR': 75.261, 'Auto': 11.191, 'CCWM': 4.767, 'TeamName': 'WiredCats Gen 3'}, {'TeamNum': 3101, 'OPR': 74.54, 'Auto': 26.638, 'CCWM': 21.804, 'TeamName': 'Boom Bots'}, {'TeamNum': 2845, 'OPR': 73.712, 'Auto': 19.982, 'CCWM': 40.202, 'TeamName': 'Team Duct Tape'}, {'TeamNum': 18172, 'OPR': 68.486, 'Auto': 4.581, 'CCWM': -26.774, 'TeamName': 'Uplift Robotics'}, {'TeamNum': 10276, 'OPR': 67.541, 'Auto': 22.073, 'CCWM': -3.808, 'TeamName': 'Storm Troopers'}, {'TeamNum': 12600, 'OPR': 65.457, 'Auto': 15.463, 'CCWM': -14.922, 'TeamName': 'Hadron Knights'}, {'TeamNum': 22012, 'OPR': 61.273, 'Auto': 21.686, 'CCWM': -26.627, 'TeamName': 'OSS Loose Screws'}, {'TeamNum': 9214, 'OPR': 60.73, 'Auto': 17.186, 'CCWM': -1.987, 'TeamName': 'R²'}, {'TeamNum': 16716, 'OPR': 60.185, 'Auto': 23.41, 'CCWM': 38.554, 'TeamName': 'IvyWarriors'}, {'TeamNum': 10583, 'OPR': 60.114, 'Auto': 15.063, 'CCWM': 13.899, 'TeamName': 'The Robotic Gladiators'}, {'TeamNum': 19388, 'OPR': 57.91, 'Auto': 9.57, 'CCWM': -37.318, 'TeamName': 'Metal Mavericks'}, {'TeamNum': 16484, 'OPR': 54.465, 'Auto': 10.725, 'CCWM': 3.959, 'TeamName': 'ROBOCANES'}, {'TeamNum': 14708, 'OPR': 43.782, 'Auto': 25.719, 'CCWM': -46.625, 'TeamName': 'Short Circuits'}, {'TeamNum': 21477, 'OPR': 40.98, 'Auto': 22.801, 'CCWM': -2.214, 'TeamName': 'KRAK3N'}, {'TeamNum': 14431, 'OPR': 39.802, 'Auto': 15.808, 'CCWM': -26.569, 'TeamName': 'Pyrites'}, {'TeamNum': 13233, 'OPR': 37.165, 'Auto': 9.321, 'CCWM': -5.03, 'TeamName': 'Cyber Knights'}, {'TeamNum': 18145, 'OPR': 36.557, 'Auto': 7.951, 'CCWM': -40.948, 'TeamName': 'Men in Black Jax'}, {'TeamNum': 9986, 'OPR': 33.464, 'Auto': 15.809, 'CCWM': -49.814, 'TeamName': 'Eaglebotics Navy'}, {'TeamNum': 18619, 'OPR': 23.765, 'Auto': 13.103, 'CCWM': -5.725, 'TeamName': 'BuccaNEERS'}, {'TeamNum': 4717, 'OPR': 22.083, 'Auto': 1.931, 'CCWM': -68.505, 'TeamName': 'Mechromancers'}, {'TeamNum': 7477, 'OPR': 12.015, 'Auto': 0.719, 'CCWM': -41.815, 'TeamName': 'Super 7'}]
[{'TeamNum': 14725, 'OPR': 136.27, 'Auto': 38.059, 'CCWM': 52.31, 'TeamName': 'Java the Hutts'}, {'TeamNum': 7592, 'OPR': 120.183, 'Auto': 36.962, 'CCWM': 41.167, 'TeamName': 'Roarbots'}, {'TeamNum': 13093, 'OPR': 103.836, 'Auto': 23.654, 'CCWM': 28.621, 'TeamName': 'Golden Fish'}, {'TeamNum': 10650, 'OPR': 103.727, 'Auto': 28.445, 'CCWM': 44.628, 'TeamName': 'Hazmat Robotics Biohazards'}, {'TeamNum': 22690, 'OPR': 91.662, 'Auto': 16.948, 'CCWM': 24.548, 'TeamName': 'Quantum Bots'}, {'TeamNum': 14384, 'OPR': 90.636, 'Auto': 17.575, 'CCWM': 60.342, 'TeamName': 'Patent Pending'}, {'TeamNum': 10179, 'OPR': 86.897, 'Auto': 35.794, 'CCWM': 23.879, 'TeamName': 'Tech Turtles'}, {'TeamNum': 10022, 'OPR': 75.261, 'Auto': 11.191, 'CCWM': 4.767, 'TeamName': 'WiredCats Gen 3'}, {'TeamNum': 3101, 'OPR': 74.54, 'Auto': 26.638, 'CCWM': 21.804, 'TeamName': 'Boom Bots'}, {'TeamNum': 2845, 'OPR': 73.712, 'Auto': 19.982, 'CCWM': 40.202, 'TeamName': 'Team Duct Tape'}, {'TeamNum': 18172, 'OPR': 68.486, 'Auto': 4.581, 'CCWM': -26.774, 'TeamName': 'Uplift Robotics'}, {'TeamNum': 10276, 'OPR': 67.541, 'Auto': 22.073, 'CCWM': -3.808, 'TeamName': 'Storm Troopers'}, {'TeamNum': 12600, 'OPR': 65.457, 'Auto': 15.463, 'CCWM': -14.922, 'TeamName': 'Hadron Knights'}, {'TeamNum': 22012, 'OPR': 61.273, 'Auto': 21.686, 'CCWM': -26.627, 'TeamName': 'OSS Loose Screws'}, {'TeamNum': 9214, 'OPR': 60.73, 'Auto': 17.186, 'CCWM': -1.987, 'TeamName': 'R²'}, {'TeamNum': 16716, 'OPR': 60.185, 'Auto': 23.41, 'CCWM': 38.554, 'TeamName': 'IvyWarriors'}, {'TeamNum': 10583, 'OPR': 60.114, 'Auto': 15.063, 'CCWM': 13.899, 'TeamName': 'The Robotic Gladiators'}, {'TeamNum': 19388, 'OPR': 57.91, 'Auto': 9.57, 'CCWM': -37.318, 'TeamName': 'Metal Mavericks'}, {'TeamNum': 16484, 'OPR': 54.465, 'Auto': 10.725, 'CCWM': 3.959, 'TeamName': 'ROBOCANES'}, {'TeamNum': 14708, 'OPR': 43.782, 'Auto': 25.719, 'CCWM': -46.625, 'TeamName': 'Short Circuits'}, {'TeamNum': 21477, 'OPR': 40.98, 'Auto': 22.801, 'CCWM': -2.214, 'TeamName': 'KRAK3N'}, {'TeamNum': 14431, 'OPR': 39.802, 'Auto': 15.808, 'CCWM': -26.569, 'TeamName': 'Pyrites'}, {'TeamNum': 13233, 'OPR': 37.165, 'Auto': 9.321, 'CCWM': -5.03, 'TeamName': 'Cyber Knights'}, {'TeamNum': 18145, 'OPR': 36.557, 'Auto': 7.951, 'CCWM': -40.948, 'TeamName': 'Men in Black Jax'}, {'TeamNum': 9986, 'OPR': 33.464, 'Auto': 15.809, 'CCWM': -49.814, 'TeamName': 'Eaglebotics Navy'}, {'TeamNum': 18619, 'OPR': 23.765, 'Auto': 13.103, 'CCWM': -5.725, 'TeamName': 'BuccaNEERS'}, {'TeamNum': 4717, 'OPR': 22.083, 'Auto': 1.931, 'CCWM': -68.505, 'TeamName': 'Mechromancers'}, {'TeamNum': 7477, 'OPR': 12.015, 'Auto': 0.719, 'CCWM': -41.815, 'TeamName': 'Super 7'}]
https://ftc-events.firstinspires.org/2022/USFLCMPLAWR/qualifications
{'18385', '516', '9944', '15052', '16290', '20344', '20022', '7719', '4228', '6433', '3123', '9277', '6322', '19895', '11172', '17156', '9987', '10830', '18317', '9930', '16626', '8798', '9175', '20012', '15006', '7341', '3888', '8617'}
{'18385', '516', '9944', '15052', '16290', '20344', '20022', '7719', '4228', '6433', '3123', '9277', '6322', '19895', '11172', '17156', '9987', '10830', '18317', '9930', '16626', '8798', '9175', '20012', '15006', '7341', '3888', '8617'}
[{'TeamNum': 18317, 'OPR': 125.571, 'Auto': 33.079, 'CCWM': 85.308, 'TeamName': 'Steel Eels'}, {'TeamNum': 9930, 'OPR': 103.981, 'Auto': 33.78, 'CCWM': 55.503, 'TeamName': 'Robo-Knights'}, {'TeamNum': 15006, 'OPR': 95.65, 'Auto': 20.894, 'CCWM': 62.863, 'TeamName': 'Nerdvana'}, {'TeamNum': 3123, 'OPR': 89.979, 'Auto': 15.177, 'CCWM': 39.441, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 11172, 'OPR': 89.301, 'Auto': 31.18, 'CCWM': 23.06, 'TeamName': 'Static Discharge'}, {'TeamNum': 6433, 'OPR': 88.445, 'Auto': 9.567, 'CCWM': 15.158, 'TeamName': 'Neutrinos'}, {'TeamNum': 8617, 'OPR': 78.524, 'Auto': 15.035, 'CCWM': 29.568, 'TeamName': 'Techno Tigers'}, {'TeamNum': 16290, 'OPR': 77.81, 'Auto': 30.924, 'CCWM': 55.359, 'TeamName': 'Z.I.P Ties'}, {'TeamNum': 4228, 'OPR': 75.803, 'Auto': 25.834, 'CCWM': 31.651, 'TeamName': 'Gears Of Other Dimensions'}, {'TeamNum': 7719, 'OPR': 74.227, 'Auto': 17.908, 'CCWM': 11.855, 'TeamName': 'RISE'}, {'TeamNum': 9944, 'OPR': 73.485, 'Auto': 20.447, 'CCWM': 26.859, 'TeamName': 'SATURN #9944'}, {'TeamNum': 10830, 'OPR': 71.822, 'Auto': 15.87, 'CCWM': 1.156, 'TeamName': 'AJAX'}, {'TeamNum': 18385, 'OPR': 70.841, 'Auto': 3.1, 'CCWM': -8.138, 'TeamName': 'SHIVA Atomatrons'}, {'TeamNum': 20012, 'OPR': 63.921, 'Auto': 26.222, 'CCWM': 18.998, 'TeamName': 'Cadastrophe'}, {'TeamNum': 16626, 'OPR': 59.968, 'Auto': 11.1, 'CCWM': -25.538, 'TeamName': 'Radical Raiders'}, {'TeamNum': 15052, 'OPR': 55.565, 'Auto': 19.922, 'CCWM': -8.28, 'TeamName': 'Space Engineers'}, {'TeamNum': 516, 'OPR': 55.119, 'Auto': 7.277, 'CCWM': -17.471, 'TeamName': 'Gears of Fire'}, {'TeamNum': 6322, 'OPR': 54.267, 'Auto': 28.353, 'CCWM': -1.517, 'TeamName': 'WiredCats Origin'}, {'TeamNum': 20344, 'OPR': 52.228, 'Auto': 11.803, 'CCWM': -13.542, 'TeamName': 'Cattlebots '}, {'TeamNum': 9277, 'OPR': 49.459, 'Auto': 11.486, 'CCWM': -19.244, 'TeamName': 'Hazmat Robotics Explosives'}, {'TeamNum': 7341, 'OPR': 42.839, 'Auto': 9.853, 'CCWM': -16.445, 'TeamName': 'F.R.E.N.C.H. F.R.I.E.S.'}, {'TeamNum': 9175, 'OPR': 41.685, 'Auto': 0.253, 'CCWM': -14.376, 'TeamName': 'Warrior Bots'}, {'TeamNum': 3888, 'OPR': 36.422, 'Auto': 4.507, 'CCWM': -67.713, 'TeamName': 'Greased Lightning'}, {'TeamNum': 9987, 'OPR': 34.378, 'Auto': 2.721, 'CCWM': -51.179, 'TeamName': 'Eaglebotics Gold'}, {'TeamNum': 8798, 'OPR': 30.053, 'Auto': 15.578, 'CCWM': -22.381, 'TeamName': 'Aluminati Industries'}, {'TeamNum': 20022, 'OPR': 27.909, 'Auto': 0.616, 'CCWM': -31.283, 'TeamName': 'RoBOCAts'}, {'TeamNum': 17156, 'OPR': 15.658, 'Auto': 1.073, 'CCWM': -68.397, 'TeamName': 'scotsOverflow'}, {'TeamNum': 19895, 'OPR': -4.242, 'Auto': -3.894, 'CCWM': -91.276, 'TeamName': 'Dragomight'}]
[{'TeamNum': 18317, 'OPR': 125.571, 'Auto': 33.079, 'CCWM': 85.308, 'TeamName': 'Steel Eels'}, {'TeamNum': 9930, 'OPR': 103.981, 'Auto': 33.78, 'CCWM': 55.503, 'TeamName': 'Robo-Knights'}, {'TeamNum': 15006, 'OPR': 95.65, 'Auto': 20.894, 'CCWM': 62.863, 'TeamName': 'Nerdvana'}, {'TeamNum': 3123, 'OPR': 89.979, 'Auto': 15.177, 'CCWM': 39.441, 'TeamName': 'Spontaneous Combustion'}, {'TeamNum': 11172, 'OPR': 89.301, 'Auto': 31.18, 'CCWM': 23.06, 'TeamName': 'Static Discharge'}, {'TeamNum': 6433, 'OPR': 88.445, 'Auto': 9.567, 'CCWM': 15.158, 'TeamName': 'Neutrinos'}, {'TeamNum': 8617, 'OPR': 78.524, 'Auto': 15.035, 'CCWM': 29.568, 'TeamName': 'Techno Tigers'}, {'TeamNum': 16290, 'OPR': 77.81, 'Auto': 30.924, 'CCWM': 55.359, 'TeamName': 'Z.I.P Ties'}, {'TeamNum': 4228, 'OPR': 75.803, 'Auto': 25.834, 'CCWM': 31.651, 'TeamName': 'Gears Of Other Dimensions'}, {'TeamNum': 7719, 'OPR': 74.227, 'Auto': 17.908, 'CCWM': 11.855, 'TeamName': 'RISE'}, {'TeamNum': 9944, 'OPR': 73.485, 'Auto': 20.447, 'CCWM': 26.859, 'TeamName': 'SATURN #9944'}, {'TeamNum': 10830, 'OPR': 71.822, 'Auto': 15.87, 'CCWM': 1.156, 'TeamName': 'AJAX'}, {'TeamNum': 18385, 'OPR': 70.841, 'Auto': 3.1, 'CCWM': -8.138, 'TeamName': 'SHIVA Atomatrons'}, {'TeamNum': 20012, 'OPR': 63.921, 'Auto': 26.222, 'CCWM': 18.998, 'TeamName': 'Cadastrophe'}, {'TeamNum': 16626, 'OPR': 59.968, 'Auto': 11.1, 'CCWM': -25.538, 'TeamName': 'Radical Raiders'}, {'TeamNum': 15052, 'OPR': 55.565, 'Auto': 19.922, 'CCWM': -8.28, 'TeamName': 'Space Engineers'}, {'TeamNum': 516, 'OPR': 55.119, 'Auto': 7.277, 'CCWM': -17.471, 'TeamName': 'Gears of Fire'}, {'TeamNum': 6322, 'OPR': 54.267, 'Auto': 28.353, 'CCWM': -1.517, 'TeamName': 'WiredCats Origin'}, {'TeamNum': 20344, 'OPR': 52.228, 'Auto': 11.803, 'CCWM': -13.542, 'TeamName': 'Cattlebots '}, {'TeamNum': 9277, 'OPR': 49.459, 'Auto': 11.486, 'CCWM': -19.244, 'TeamName': 'Hazmat Robotics Explosives'}, {'TeamNum': 7341, 'OPR': 42.839, 'Auto': 9.853, 'CCWM': -16.445, 'TeamName': 'F.R.E.N.C.H. F.R.I.E.S.'}, {'TeamNum': 9175, 'OPR': 41.685, 'Auto': 0.253, 'CCWM': -14.376, 'TeamName': 'Warrior Bots'}, {'TeamNum': 3888, 'OPR': 36.422, 'Auto': 4.507, 'CCWM': -67.713, 'TeamName': 'Greased Lightning'}, {'TeamNum': 9987, 'OPR': 34.378, 'Auto': 2.721, 'CCWM': -51.179, 'TeamName': 'Eaglebotics Gold'}, {'TeamNum': 8798, 'OPR': 30.053, 'Auto': 15.578, 'CCWM': -22.381, 'TeamName': 'Aluminati Industries'}, {'TeamNum': 20022, 'OPR': 27.909, 'Auto': 0.616, 'CCWM': -31.283, 'TeamName': 'RoBOCAts'}, {'TeamNum': 17156, 'OPR': 15.658, 'Auto': 1.073, 'CCWM': -68.397, 'TeamName': 'scotsOverflow'}, {'TeamNum': 19895, 'OPR': -4.242, 'Auto': -3.894, 'CCWM': -91.276, 'TeamName': 'Dragomight'}]

i 12
[<selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-49E11512-C374-4F8E-96AB-8497728D012F")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-5BC05070-8706-4876-B5A6-11E4582B95C6")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-19FEFD3D-18E6-40DA-9380-6676F617C17F")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-453B99B1-9438-42C4-9C16-250DEF5E8D80")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-C5D62614-FE84-4696-BF03-04B9679C850A")>, <selenium.webdriver.remote.webelement.WebElement (session="66F8E973-5C7E-4A33-B1E2-B8BAABF61E14", element="node-6504D378-05A7-4D70-8159-46452B35F6E9")>]
https://ftc-events.firstinspires.org/2022/USIACMPGD/qualifications
{'7110', '21311', '8672', '19368', '9925', '11384', '7258', '8696', '13416', '16736', '10435', '7196', '13206', '16010', '6103', '15523', '7247', '17111', '7400', '19415', '18397', '14568', '4175', '17116'}
{'7110', '21311', '8672', '19368', '9925', '11384', '7258', '8696', '13416', '16736', '10435', '7196', '13206', '16010', '6103', '15523', '7247', '17111', '7400', '19415', '18397', '14568', '4175', '17116'}
[{'TeamNum': 18397, 'OPR': 133.078, 'Auto': 28.374, 'CCWM': 54.76, 'TeamName': 'Aztechs'}, {'TeamNum': 10435, 'OPR': 110.684, 'Auto': 29.716, 'CCWM': 33.361, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14568, 'OPR': 108.88, 'Auto': 24.647, 'CCWM': 47.774, 'TeamName': 'Norwalk RoboWarriors'}, {'TeamNum': 7258, 'OPR': 100.931, 'Auto': 22.383, 'CCWM': 21.876, 'TeamName': 'Epsilon Robotics'}, {'TeamNum': 9925, 'OPR': 95.186, 'Auto': 24.482, 'CCWM': 21.031, 'TeamName': 'Delta Robotics'}, {'TeamNum': 7400, 'OPR': 93.497, 'Auto': 21.242, 'CCWM': 48.351, 'TeamName': 'Shmizmin'}, {'TeamNum': 8672, 'OPR': 92.773, 'Auto': 23.309, 'CCWM': -12.067, 'TeamName': 'UBett'}, {'TeamNum': 8696, 'OPR': 89.709, 'Auto': 11.694, 'CCWM': 16.235, 'TeamName': 'Trobotix'}, {'TeamNum': 6103, 'OPR': 87.916, 'Auto': 29.805, 'CCWM': -1.776, 'TeamName': 'Radiant Rivals'}, {'TeamNum': 21311, 'OPR': 82.098, 'Auto': 32.017, 'CCWM': -25.571, 'TeamName': 'Lion Robotics'}, {'TeamNum': 16010, 'OPR': 81.739, 'Auto': 16.222, 'CCWM': -1.003, 'TeamName': 'Vamp Kings'}, {'TeamNum': 13416, 'OPR': 78.395, 'Auto': 8.117, 'CCWM': 9.306, 'TeamName': 'JagWires'}, {'TeamNum': 16736, 'OPR': 78.193, 'Auto': 23.365, 'CCWM': 11.508, 'TeamName': 'Atomic Narwhals'}, {'TeamNum': 7110, 'OPR': 72.475, 'Auto': 16.664, 'CCWM': 9.236, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 7247, 'OPR': 70.571, 'Auto': 25.05, 'CCWM': 15.053, 'TeamName': 'The H2O Loo Bots'}, {'TeamNum': 7196, 'OPR': 70.503, 'Auto': 18.478, 'CCWM': 7.234, 'TeamName': "Everything That's Radical"}, {'TeamNum': 19368, 'OPR': 65.356, 'Auto': 26.519, 'CCWM': -28.148, 'TeamName': 'Manufactured Chaos'}, {'TeamNum': 17116, 'OPR': 57.341, 'Auto': 4.099, 'CCWM': -1.715, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 19415, 'OPR': 53.191, 'Auto': 4.362, 'CCWM': -39.127, 'TeamName': 'C3 Robotics'}, {'TeamNum': 11384, 'OPR': 49.956, 'Auto': 14.3, 'CCWM': -33.286, 'TeamName': 'Thunderstruck'}, {'TeamNum': 4175, 'OPR': 39.815, 'Auto': 4.564, 'CCWM': -44.793, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 17111, 'OPR': 39.228, 'Auto': 4.544, 'CCWM': -41.444, 'TeamName': 'Quack Attack'}, {'TeamNum': 13206, 'OPR': 38.892, 'Auto': 19.035, 'CCWM': -28.1, 'TeamName': 'Wave Droids'}, {'TeamNum': 15523, 'OPR': 29.927, 'Auto': 12.014, 'CCWM': -38.696, 'TeamName': 'Diagonal HotSpots'}]
[{'TeamNum': 18397, 'OPR': 133.078, 'Auto': 28.374, 'CCWM': 54.76, 'TeamName': 'Aztechs'}, {'TeamNum': 10435, 'OPR': 110.684, 'Auto': 29.716, 'CCWM': 33.361, 'TeamName': 'Circuit Breakers'}, {'TeamNum': 14568, 'OPR': 108.88, 'Auto': 24.647, 'CCWM': 47.774, 'TeamName': 'Norwalk RoboWarriors'}, {'TeamNum': 7258, 'OPR': 100.931, 'Auto': 22.383, 'CCWM': 21.876, 'TeamName': 'Epsilon Robotics'}, {'TeamNum': 9925, 'OPR': 95.186, 'Auto': 24.482, 'CCWM': 21.031, 'TeamName': 'Delta Robotics'}, {'TeamNum': 7400, 'OPR': 93.497, 'Auto': 21.242, 'CCWM': 48.351, 'TeamName': 'Shmizmin'}, {'TeamNum': 8672, 'OPR': 92.773, 'Auto': 23.309, 'CCWM': -12.067, 'TeamName': 'UBett'}, {'TeamNum': 8696, 'OPR': 89.709, 'Auto': 11.694, 'CCWM': 16.235, 'TeamName': 'Trobotix'}, {'TeamNum': 6103, 'OPR': 87.916, 'Auto': 29.805, 'CCWM': -1.776, 'TeamName': 'Radiant Rivals'}, {'TeamNum': 21311, 'OPR': 82.098, 'Auto': 32.017, 'CCWM': -25.571, 'TeamName': 'Lion Robotics'}, {'TeamNum': 16010, 'OPR': 81.739, 'Auto': 16.222, 'CCWM': -1.003, 'TeamName': 'Vamp Kings'}, {'TeamNum': 13416, 'OPR': 78.395, 'Auto': 8.117, 'CCWM': 9.306, 'TeamName': 'JagWires'}, {'TeamNum': 16736, 'OPR': 78.193, 'Auto': 23.365, 'CCWM': 11.508, 'TeamName': 'Atomic Narwhals'}, {'TeamNum': 7110, 'OPR': 72.475, 'Auto': 16.664, 'CCWM': 9.236, 'TeamName': 'The Element of Surprise'}, {'TeamNum': 7247, 'OPR': 70.571, 'Auto': 25.05, 'CCWM': 15.053, 'TeamName': 'The H2O Loo Bots'}, {'TeamNum': 7196, 'OPR': 70.503, 'Auto': 18.478, 'CCWM': 7.234, 'TeamName': "Everything That's Radical"}, {'TeamNum': 19368, 'OPR': 65.356, 'Auto': 26.519, 'CCWM': -28.148, 'TeamName': 'Manufactured Chaos'}, {'TeamNum': 17116, 'OPR': 57.341, 'Auto': 4.099, 'CCWM': -1.715, 'TeamName': 'Hazardous Materials'}, {'TeamNum': 19415, 'OPR': 53.191, 'Auto': 4.362, 'CCWM': -39.127, 'TeamName': 'C3 Robotics'}, {'TeamNum': 11384, 'OPR': 49.956, 'Auto': 14.3, 'CCWM': -33.286, 'TeamName': 'Thunderstruck'}, {'TeamNum': 4175, 'OPR': 39.815, 'Auto': 4.564, 'CCWM': -44.793, 'TeamName': 'MechaMETROzilla'}, {'TeamNum': 17111, 'OPR': 39.228, 'Auto': 4.544, 'CCWM': -41.444, 'TeamName': 'Quack Attack'}, {'TeamNum': 13206, 'OPR': 38.892, 'Auto': 19.035, 'CCWM': -28.1, 'TeamName': 'Wave Droids'}, {'TeamNum': 15523, 'OPR': 29.927, 'Auto': 12.014, 'CCWM': -38.696, 'TeamName': 'Diagonal HotSpots'}]
https://ftc-events.firstinspires.org/2022/USIACMPBK/qualifications
{'6666', '9974', '4324', '8813', '5143', '5126', '14172', '7924', '20024', '18139', '13186', '11142', '19394', '21627', '12863', '7841', '9978', '5094', '6252', '20077', '22187', '8807', '7229', '18527'}
{'6666', '9974', '4324', '8813', '5143', '5126', '14172', '7924', '20024', '18139', '13186', '11142', '19394', '21627', '12863', '7841', '9978', '5094', '6252', '20077', '22187', '8807', '7229', '18527'}
[{'TeamNum': 18527, 'OPR': 136.869, 'Auto': 37.504, 'CCWM': 70.064, 'TeamName': 'PCM Alchemists'}, {'TeamNum': 9974, 'OPR': 136.829, 'Auto': 32.33, 'CCWM': 75.95, 'TeamName': 'T.H.O.R. '}, {'TeamNum': 14172, 'OPR': 107.6, 'Auto': 28.847, 'CCWM': 38.687, 'TeamName': 'Disco Duckbots'}, {'TeamNum': 8813, 'OPR': 97.674, 'Auto': 28.065, 'CCWM': 32.972, 'TeamName': 'The Winter Soldiers'}, {'TeamNum': 5094, 'OPR': 90.872, 'Auto': 12.271, 'CCWM': 15.094, 'TeamName': 'Still Under Development'}, {'TeamNum': 6666, 'OPR': 81.401, 'Auto': 24.828, 'CCWM': -11.116, 'TeamName': 'Quad Six'}, {'TeamNum': 5143, 'OPR': 81.089, 'Auto': 9.093, 'CCWM': 19.399, 'TeamName': 'Xcentrics'}, {'TeamNum': 21627, 'OPR': 80.619, 'Auto': 11.066, 'CCWM': 8.224, 'TeamName': 'NinJava'}, {'TeamNum': 6252, 'OPR': 80.178, 'Auto': 14.365, 'CCWM': -13.369, 'TeamName': 'The Wacky Waving Inflatable Arm Flailing Tube Men and Women'}, {'TeamNum': 7841, 'OPR': 77.696, 'Auto': 20.221, 'CCWM': 7.876, 'TeamName': 'Ballen Pretzels 2'}, {'TeamNum': 13186, 'OPR': 75.768, 'Auto': 13.813, 'CCWM': -15.017, 'TeamName': 'Lactose Intolerance'}, {'TeamNum': 20077, 'OPR': 74.044, 'Auto': 12.047, 'CCWM': -0.817, 'TeamName': 'The Indubitables'}, {'TeamNum': 22187, 'OPR': 72.589, 'Auto': 16.104, 'CCWM': -26.656, 'TeamName': 'A.I.R. '}, {'TeamNum': 18139, 'OPR': 72.403, 'Auto': 18.275, 'CCWM': 12.861, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 7229, 'OPR': 64.301, 'Auto': 10.547, 'CCWM': 13.658, 'TeamName': 'bzBots'}, {'TeamNum': 19394, 'OPR': 62.26, 'Auto': 9.803, 'CCWM': -20.221, 'TeamName': 'Dutch Bots'}, {'TeamNum': 5126, 'OPR': 61.335, 'Auto': 8.06, 'CCWM': -20.105, 'TeamName': 'DICE'}, {'TeamNum': 9978, 'OPR': 60.162, 'Auto': 14.968, 'CCWM': -23.526, 'TeamName': 'Avengers Tech'}, {'TeamNum': 4324, 'OPR': 60.041, 'Auto': 16.949, 'CCWM': -3.419, 'TeamName': 'Lost In Time'}, {'TeamNum': 7924, 'OPR': 52.18, 'Auto': 13.099, 'CCWM': -33.054, 'TeamName': 'Red Toques'}, {'TeamNum': 20024, 'OPR': 49.139, 'Auto': 5.29, 'CCWM': 0.677, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 8807, 'OPR': 37.071, 'Auto': 3.657, 'CCWM': -12.642, 'TeamName': 'Molten Sprockets'}, {'TeamNum': 12863, 'OPR': 33.452, 'Auto': 16.801, 'CCWM': -33.704, 'TeamName': 'Flourish & Bots'}, {'TeamNum': 11142, 'OPR': 26.593, 'Auto': 9.998, 'CCWM': -81.82, 'TeamName': 'Robo Minions'}]
[{'TeamNum': 18527, 'OPR': 136.869, 'Auto': 37.504, 'CCWM': 70.064, 'TeamName': 'PCM Alchemists'}, {'TeamNum': 9974, 'OPR': 136.829, 'Auto': 32.33, 'CCWM': 75.95, 'TeamName': 'T.H.O.R. '}, {'TeamNum': 14172, 'OPR': 107.6, 'Auto': 28.847, 'CCWM': 38.687, 'TeamName': 'Disco Duckbots'}, {'TeamNum': 8813, 'OPR': 97.674, 'Auto': 28.065, 'CCWM': 32.972, 'TeamName': 'The Winter Soldiers'}, {'TeamNum': 5094, 'OPR': 90.872, 'Auto': 12.271, 'CCWM': 15.094, 'TeamName': 'Still Under Development'}, {'TeamNum': 6666, 'OPR': 81.401, 'Auto': 24.828, 'CCWM': -11.116, 'TeamName': 'Quad Six'}, {'TeamNum': 5143, 'OPR': 81.089, 'Auto': 9.093, 'CCWM': 19.399, 'TeamName': 'Xcentrics'}, {'TeamNum': 21627, 'OPR': 80.619, 'Auto': 11.066, 'CCWM': 8.224, 'TeamName': 'NinJava'}, {'TeamNum': 6252, 'OPR': 80.178, 'Auto': 14.365, 'CCWM': -13.369, 'TeamName': 'The Wacky Waving Inflatable Arm Flailing Tube Men and Women'}, {'TeamNum': 7841, 'OPR': 77.696, 'Auto': 20.221, 'CCWM': 7.876, 'TeamName': 'Ballen Pretzels 2'}, {'TeamNum': 13186, 'OPR': 75.768, 'Auto': 13.813, 'CCWM': -15.017, 'TeamName': 'Lactose Intolerance'}, {'TeamNum': 20077, 'OPR': 74.044, 'Auto': 12.047, 'CCWM': -0.817, 'TeamName': 'The Indubitables'}, {'TeamNum': 22187, 'OPR': 72.589, 'Auto': 16.104, 'CCWM': -26.656, 'TeamName': 'A.I.R. '}, {'TeamNum': 18139, 'OPR': 72.403, 'Auto': 18.275, 'CCWM': 12.861, 'TeamName': 'Rebel Robotics'}, {'TeamNum': 7229, 'OPR': 64.301, 'Auto': 10.547, 'CCWM': 13.658, 'TeamName': 'bzBots'}, {'TeamNum': 19394, 'OPR': 62.26, 'Auto': 9.803, 'CCWM': -20.221, 'TeamName': 'Dutch Bots'}, {'TeamNum': 5126, 'OPR': 61.335, 'Auto': 8.06, 'CCWM': -20.105, 'TeamName': 'DICE'}, {'TeamNum': 9978, 'OPR': 60.162, 'Auto': 14.968, 'CCWM': -23.526, 'TeamName': 'Avengers Tech'}, {'TeamNum': 4324, 'OPR': 60.041, 'Auto': 16.949, 'CCWM': -3.419, 'TeamName': 'Lost In Time'}, {'TeamNum': 7924, 'OPR': 52.18, 'Auto': 13.099, 'CCWM': -33.054, 'TeamName': 'Red Toques'}, {'TeamNum': 20024, 'OPR': 49.139, 'Auto': 5.29, 'CCWM': 0.677, 'TeamName': 'Nacho Typical Team'}, {'TeamNum': 8807, 'OPR': 37.071, 'Auto': 3.657, 'CCWM': -12.642, 'TeamName': 'Molten Sprockets'}, {'TeamNum': 12863, 'OPR': 33.452, 'Auto': 16.801, 'CCWM': -33.704, 'TeamName': 'Flourish & Bots'}, {'TeamNum': 11142, 'OPR': 26.593, 'Auto': 9.998, 'CCWM': -81.82, 'TeamName': 'Robo Minions'}]

In [47]:
matches.iat[m.iat[124,0], 0]

'USTXCECMP'

In [48]:
missing = ['USMICMP2', 'USMICMP', 'CAABABSALT', 'ILCMP', 'USCHSCMP', 'USMNCMP', 'USAZCMP', 'USORCMPSOL', 'USORCMPHYD', 'USCANOCMP', 'USFLCMP', 'USIACMP', 'USNJCMP', 'USTXSOCMP2', 'USTXCECMP', 'FTCCMP1']

In [49]:
cmps = pd.DataFrame(columns = ['id'])

In [ ]:
cmps.to_csv(os.getcwd().replace('scripts', 'data') + '/bad.csv')

In [38]:
df.to_csv(os.getcwd().replace('scripts', 'data') + '/missing.csv', index = False)