In [7]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

In [8]:
matches = pd.read_csv(os.getcwd().replace('scripts', 'data')+ '/all_matches.csv')

In [9]:
matches

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
...,...,...,...,...,...
1135,USTXSOBEOS,FIRST in Texas UIL State 5A,USA,2023-03-24 00:00:00,2023-03-24 00:00:00
1136,CNDIS,Dianjian Peony Cup,China,2023-04-01 00:00:00,2023-04-02 00:00:00
1137,GBREQ,GB Remote Regional,United Kingdom,2023-03-23 00:00:00,2023-03-29 00:00:00
1138,USTXCECCS,TX-Central Buc Days 2023 Robot Rodeo,USA,2023-05-13 00:00:00,2023-05-13 00:00:00
1139,FTCCMP1,FIRST Championship - Houston - World Champions...,USA,2023-04-18 00:00:00,2023-04-22 00:00:00

In [13]:
import time
from bs4 import BeautifulSoup
from selenium import webdriver

url = "https://ftc-events.firstinspires.org/2022/"
driver = webdriver.Safari()
all_teams = {}
for i in range(matches.shape[0]):
    try:
        add = matches.at[i, 'Link']
        driver.get(url + add)
        src = driver.page_source
        soup = BeautifulSoup(src, 'lxml')
        teams = soup.find('table', {'id': 'teamtable'}).find('tbody').find_all('a')
        names = soup.find('table', {'id': 'teamtable'}).find('tbody').find_all('td', {'class' : 'teamnamecol'})

        if(len(teams) != len(names)):
            print(i)
            break

        for i in range(len(teams)):
            all_teams[int(teams[i]['href'].split("/")[-1])] = names[i].text
    except Exception as e:
        continue
        
driver.close()

In [14]:
all_teams

{5951: 'Mustangs',
 8990: 'Mile High Academy Mustangs',
 11020: 'SKI SKY',
 15931: 'Tin Heads',
 16899: 'CPUsaders_T',
 18457: 'GatorBytes',
 18783: 'Eagle Tech',
 19475: 'Ducksters',
 19712: 'NDAASentinels',
 20840: 'The Senjus of Raleigh',
 21362: 'System UI ',
 21391: 'Mighty Cypress',
 21993: 'Tech Titans',
 22840: 'Robugatti',
 22859: 'The Gearhead Gladiators',
 5292: 'Red Storm Robotics-White',
 6482: 'Red Storm Robotics-Red',
 7048: 'Purple Protons',
 7065: 'JunkYard Bots',
 7305: 'The GearCats - Clague Middle School',
 8603: 'The Fighting Gnomes',
 9931: 'Northeast Viking Vendors',
 9933: "Blazin' Turtles",
 10477: 'Rapid Robots',
 11618: 'Chelsea Gremlins',
 11691: 'Scripps Dragons',
 12862: 'Power Dragons',
 14649: 'WBSD FTC - Anchorbots',
 15004: 'Tech KNOW Logic',
 15104: 'Static Eagles',
 15301: 'Valkyries',
 15353: 'Heritage Hackers',
 15397: 'Power Raiders',
 16523: 'Automated Eagles',
 17155: 'Baker Dynamics',
 17768: 'Little HOLLYWOOD',
 17975: 'Botmasterz',
 19429: 'Infrared',
 22300: 'WBSD FTC - Wall-EB',
 22373: 'WBSD FTC - Gator Gears',
 8482: 'Robobucs',
 8487: 'Robo Toasters Orange',
 8987: 'Robobucs',
 10210: 'Aztechs',
 11520: 'Omegabots 11520',
 12294: 'Terror Hawks',
 12303: 'Hacker Hawks',
 12379: 'Rockwood Rancor',
 12459: 'Gibraltar Jedi',
 12549: 'Robo Rebels 12549',
 13019: 'Platinum Panthers 13019',
 13684: 'Infinity Tech',
 13996: 'DIA',
 14003: 'The Sampson Webber Sampson-ites',
 14771: 'Robo Gators',
 14773: 'Old Redford Academy Middle School',
 15719: 'Blazin Bots',
 15809: 'Cobalt Clippers',
 18474: 'The Robotic Bulldogs',
 18989: 'Tech Titans',
 20282: 'Marion Law Academy',
 20682: 'Flying Falcons',
 22235: 'Merit  22235',
 22395: 'Fort Gratiot Lumberjacks',
 22415: 'Robo Toasters Blue',
 22600: 'Fulton Middle School',
 22602: 'Central Cyber Cougars',
 22886: 'Warner FTC Team',
 20989: 'UK 100 - Lycée International de Valbonne - BaguetTechs',
 20990: 'UK 101 - Lycée International de Valbonne - TheFrenchineers',
 20991: 'UK 148 - Lycée International de Valbonne - FRITES',
 21403: 'ERH-Paris',
 21407: 'Jol Robot Team',
 21420: "Robot Lamar'Team",
 21425: 'GaliléoBots',
 21434: 'Bel Air Robot',
 22225: 'Marabouteur',
 22698: 'Notre Dame de Bel Air',
 22948: 'ISL Robotics',
 23107: 'LCP Robotics',
 23147: 'TechRBL',
 23149: 'Hall Robotiks',
 23151: 'DémoTech',
 15831: 'TC WMS 1',
 15832: 'TC WMS 2',
 15833: 'TC WMS 3',
 15837: 'TC WMS 4',
 15838: 'TC WMS 5',
 15839: 'TC WMS 6',
 15840: 'TC WMS 7',
 15841: 'TC WMS 8',
 15842: 'TC WMS 9',
 15843: 'TC WMS 10',
 15844: 'TC WMS 11',
 15845: 'TC WMS 12',
 15847: 'TC WMS 13',
 15848: 'TC WMS 14',
 15849: 'TC WMS 15',
 15850: 'TC WMS 16',
 15852: 'TC WMS Tech 17',
 10062: 'Robogators',
 12075: 'Menominee Jr High',
 13991: 'FlivverConnect',
 13997: 'BB-Bots',
 14846: '8th Grade 5',
 14849: '7th Grade 1',
 15485: '7th Grade 2',
 15487: '7th Grade 3',
 15726: 'Rubix Cubix',
 15783: '7th Grade 5',
 17286: 'Menominee Jr High II',
 20246: 'NCA2',
 20247: 'NCA3',
 20248: 'NCA1',
 7772: 'P.A.N.T.H.E.R.S.',
 17352: 'The Robotic Rangers',
 18980: 'RaiderBots',
 20348: 'M.A.S.T.O.D.O.N.S.',
 20881: 'Lake City Bionic Trojans',
 20935: 'NorthPointe Middle',
 22416: 'GigiCats',
 22739: 'KoolKats',
 5559: 'Holmes RoboHawks',
 7255: 'STEAM Stingers',
 7360: 'Gears and Spears',
 10136: 'Frost RoboFalcons',
 10137: 'Emerson RoboEagles',
 10735: 'JaXon Falcon Works - Gold',
 13028: 'Cougar-Bots',
 14015: 'MC Hammers',
 14379: 'RoboDojo Eagles',
 14776: 'Munger Leones',
 15547: 'Birds of Power',
 17711: 'River Rouge Roaring Robotics',
 19770: 'JaXon Falcon Works - Maroon',
 20511: 'Bionic Bulldogs',
 20512: 'Irondogs',
 21537: 'Sneaky Suspicion',
 21615: 'Rocket Robotics',
 22601: 'RoboComets Jr. ',
 22805: 'The Mighty Cavbots',
 22888: 'Hornets',
 22889: 'Saints',
 22918: 'Girl Botz',
 23026: 'Team Triumph 1',
 23164: 'St Stephen Stallions ',
 9339: 'Frog Force',
 9567: 'Cybernetic Elks',
 12599: 'Overcharged',
 12693: 'Hydrogen Hammerhead',
 12695: 'Goonies',
 12808: 'RevAmped Robotics',
 13189: 'Scorpio',
 14126: 'Fibonacci',
 15341: 'Leo',
 15342: 'Aries',
 22559: 'Winkiedinks',
 14608: 'SunrayBotCats',
 16730: 'Cat-alytic Converters',
 21792: 'CEN-Unified',
 21888: 'Floydada Collegiate Team A',
 21889: 'Floydada Collegiate Team B',
 21899: 'Hico Tiger Robotics',
 22165: 'SPACEB@LLS',
 22234: 'Hamlin Pipers',
 22693: 'CEN--Pirates',
 5386: 'Fabricators',
 10601: 'CBA RoboKings',
 10615: 'Jefferson CyDogs',
 10844: 'Wildbots',
 20901: 'RoboBears',
 21672: 'More Fabricators',
 22000: 'Chandler Park Academy(MS)',
 22881: 'OMS 6th Grade Trojans',
 22882: 'Beaverton Elementary Team #5',
 22885: 'OVMS BB-8',
 23027: 'OVMS WALL-E',
 99999: 'Off-Season Demo Team',
 9974: 'T.H.O.R. ',
 16736: 'Atomic Narwhals',
 18050: 'Team Photon',
 19415: 'C3 Robotics',
 20024: 'Nacho Typical Team',
 20077: 'The Indubitables',
 22187: 'A.I.R. ',
 22189: 'F.I.R.E.',
 4008: 'Bronc Botz - Atlas',
 4602: 'Bronc Botz - Prometheus',
 5188: 'Team Phoenix',
 5189: 'Team Wolves',
 5243: 'Team Griffin',
 6976: 'Bronc Botz ',
 13893: 'Team BeSST-13893',
 13895: 'Team LiveWire',
 15221: 'Astro Hawks',
 15703: 'Teen Tech Titans',
 16377: 'Spicy Ketchup',
 16458: 'TechnoWizards',
 16555: 'Deus ex Maquina',
 16556: 'Steminists',
 18140: 'TBD (Thunder Bolts in Disguise)',
 18244: 'Hestia',
 18908: 'Mighty Hawks',
 19412: 'Archytas',
 21337: 'Dinobyte',
 15856: 'Traverse City EAST 1',
 15857: 'Traverse City EAST 2',
 15859: 'Traverse City EAST 5',
 15861: 'Traverse City EAST 11',
 15862: 'Traverse City EAST 12',
 15863: 'Traverse City EAST 13',
 15864: 'Traverse City EAST 7',
 15865: 'Traverse City EAST 8',
 15866: 'Traverse City EAST 9',
 15867: 'Traverse City EAST 3',
 15868: 'Traverse City EAST 14',
 15869: 'Traverse City EAST 4',
 15870: 'Traverse City EAST 6',
 15871: 'Traverse City EAST 10',
 15872: 'Traverse City EAST 15',
 15874: 'Traverse City EAST 16',
 20883: 'Traverse City EAST 17',
 20884: 'Traverse City EAST 18',
 20886: 'Traverse City East 19',
 20887: 'Traverse City EAST 20',
 20888: 'Traverse City EAST 21',
 20889: 'Traverse City EAST 22',
 20892: 'Traverse City EAST 23',
 20893: 'Traverse City EAST 24',
 20894: 'Traverse City EAST 25',
 20895: 'Traverse City EAST 26',
 20896: 'Traverse City EAST 27',
 20897: 'Traverse City EAST 28',
 20898: 'Traverse City EAST 29',
 20899: 'Traverse City EAST 30',
 20900: 'Traverse City EAST 31',
 20903: 'Traverse City EAST 32',
 20904: 'Traverse City EAST 33',
 20905: 'Traverse City EAST 34',
 20906: 'Traverse City EAST 35',
 12330: 'Eaglebots Green',
 13305: 'Eaglebots White',
 15722: 'Eaglebots Black',
 130: 'Blazing Spirits',
 5518: "Dutchman's Derivatives",
 10820: 'Cyber Dragons',
 13181: 'Free WiFi',
 14212: 'Metrobotics',
 16008: 'Armored Artemises',
 16700: 'JAYBOTS',
 17703: 'FullMetal Peregrines',
 18221: 'Meta^Infinity',
 18438: 'Wolfpack Machina ',
 18813: 'FullMetal Phoenixes',
 18978: 'SemiPlatinum Penguins',
 20153: 'Silver Wolves',
 21428: 'Silver Eagles',
 99990: 'Off-Season Demo Team',
 99991: 'Off-Season Demo Team',
 99992: 'Off-Season Demo Team',
 99993: 'Off-Season Demo Team',
 99994: 'Off-Season Demo Team',
 99995: 'Off-Season Demo Team',
 99996: 'Off-Season Demo Team',
 99997: 'Off-Season Demo Team',
 99998: 'Off-Season Demo Team',
 21849: 'TechTonics',
 22487: 'UK 459 - Oxford High School - Cubotics',
 22576: "UK 463 - St. Paul's Girls' School - SPGS",
 22593: 'UK 451 - Harris Academy Sutton - Lupus',
 22610: 'JLC Legion',
 22688: 'UK 464 - Copthall - Copteam',
 22699: 'UK 454-Barking Abbey School-Techerz',
 22808: "UK 457 - St. John's - Horizons",
 15469: 'UK 170 - Alconbury HS - The Scally Lads & The Wrench',
 18889: 'UK O63 - Perton Middle School - Team Snap Wire',
 19259: 'UK OOO - Organisation - Team Name',
 19269: 'UK 105 - Bishop Perowne',
 19270: 'Calderstones',
 19280: 'UK 235 - Blackout Robotics ',
 19284: 'UK 248 - ASL Team 5 - MS ASP G8',
 20981: 'UK 035 - St John Fisher - Circuit Breakers Vol2',
 20982: 'UK 032 - St John Fisher - Hotwire rewired',
 20992: 'Berkeley Robotics',
 20993: 'UK 090 - Outwood Academy Newbold - GroundX',
 20998: 'fernDOWNLOAD#239',
 21000: '@FSL_ROBOTICS_2022',
 21008: 'The Observatory School 1',
 21011: 'UK 126 - AUEA - Bostin Dynamics',
 21014: 'UK 009-Woodhouse Academy-Sleepy Sloths',
 21116: 'UK MCB',
 21135: 'Newbotics 101 UK 007',
 21187: '426 Equuleus 21187',
 21203: '108 Oldfields',
 21206: 'TEAM 183',
 21207: 'TEAM 425',
 21648: 'UK 429 - Alconbury HS - Mr. Krabs',
 22456: 'UK 447 - BSG - BSGRobotics',
 22457: 'UK 456 - BSG - BSGRobotics',
 22486: 'Denstone College',
 22619: 'UK OOO - Poole Grammar School - Robotron',
 22640: 'UK 465 - Harrow School - Team Euclid',
 22663: 'UK 041 - SMWCA - VNATION',
 22706: 'UK 049-St. Patricks College-SPC',
 22802: 'Swanage',
 22877: 'UK 149-The Petchey Academy-Petchey Robotics',
 23053: 'UK272',
 5309: 'Plan B',
 14374: 'Dark Matter',
 15830: 'SWIFT Subaquatic Sea Kraken',
 18664: 'Skyline Vikings',
 18984: 'Hurricanes505',
 18994: 'SWIFT Subterranean Sand Sharks',
 19846: 'STEM Warriors',
 20979: 'Redstone Robotics',
 21836: 'Marvels of IAR',
 310: 'Stuy Fission',
 5064: 'Aperture Science',
 5843: 'AutoVortex',
 6133: 'The "NUTS!"',
 7149: 'ENFORCERS',
 7172: 'Technical Difficulties',
 7244: 'OUT of the BOX Robotics',
 8365: 'Gearmasters',
 8393: 'The Giant Diencephalic BrainSTEM Robotics Team',
 8719: 'Quantum Leap',
 9889: 'Cruise Control',
 10355: 'Project Peacock',
 10738: 'SBS  Bears',
 11329: 'I.C.E. Robotics',
 12014: 'FireWires',
 12560: 'Soft Hoarders',
 12589: 'Pioneer Robotics',
 12791: 'Iterative Intentions',
 13356: 'RoboForce',
 14259: 'TURBΩ V8',
 14270: 'Quantum Robotics',
 14361: 'CPHS ROBOLOBOS GREEN',
 14481: "Don't Blink",
 14525: 'TerraBats',
 14725: 'Java the Hutts',
 15972: 'TehnoZ',
 16158: 'VC Silver Circuits',
 16379: 'KookyBotz',
 16449: 'Juniper Robotics',
 17080: 'NewT.exe',
 17962: 'Ro2D2',
 18270: 'RoboPlayers',
 19043: 'CyLiis',
 19193: 'SESI SENAI SC AgroTech',
 19458: 'Equilibrium.exe ',
 21229: 'Quality Control',
 22312: 'The Brobdingnagian Tritocephalic BrainSTEM Robotics Team',
 9784: 'Dry Ice',
 11311: 'Paragon',
 12635: 'Kuriosity Robotics',
 19600: 'Treeman 树人',
 21316: 'Team Alpha',
 13710: 'Artemis',
 6645: 'Roboticus Maximus',
 15886: 'Shiloh Stud Muffins',
 16127: 'Rogue Robot ',
 4155: "M.I.T (Muskogee's Innovative Team)",
 5141: 'Warrior Bots',
 7242: 'BC Robocats',
 11572: 'Mouse Spit',
 6708: 'Sour Patch Kids',
 7281: 'Cyber Knights',
 11117: 'Autonomice',
 12660: 'Robotters',
 14521: 'Excalibur',
 14931: 'PioNerds Black',
 17008: 'PioNerds Green',
 18555: 'Unity High School TechSperts',
 18748: 'Techno Scorpions',
 18749: 'Kaos',
 18750: 'The Mechanical Wizards',
 3208: 'L8 Lynx',
 3825: 'Lightning Lynx',
 4951: 'Dimond Legendary Lynx',
 12651: 'Metal Knights',
 12656: 'ThunderBots',
 16660: 'Technomancers',
 16970: 'Dimond Lynx Links',
 18848: 'Westie Besties',
 19953: 'Scrap Metal',
 22323: 'Metal Feather',
 5898: 'Galactic Lions - Andromeda',
 7673: 'Dragons & Tiaras FTC 7673',
 18443: 'Galactic Lions - Cygnus',
 3558: 'FireBots',
 4650: 'Crusader Robotics',
 5713: 'Crusader Robotics',
 9182: 'Short Circuits',
 9617: 'Loose Screws',
 10075: 'Tech Turtles',
 11409: 'Robofobixx',
 11873: 'Element Unknown',
 12649: 'Code Blooded',
 13546: 'Shifting Gears',
 14223: 'Robotic Raiders',
 14561: 'Tech Tigers',
 16539: 'Aluminum Warriors',
 17178: 'Phantom Warriors',
 19542: 'The CIA',
 19706: 'Potential Energy',
 19845: 'Titanium Warriors',
 20075: 'CapFish',
 20150: 'The Broken Hexagon',
 22161: 'M-TECH Dark Matter',
 22162: 'M-TECH ProtoPlazma',
 22178: 'Infrared',
 9536: 'Slobberbots',
 10466: 'BeckerFIRST Atlantis',
 10468: 'BeckerFIRST Endeavour',
 11586: 'BeckerFIRST Discovery',
 12045: 'Mech Tech II',
 15183: 'BeckerFIRST Apollo',
 16917: 'Gear Wizards',
 16981: 'Gear RaTiOs',
 19892: 'Digital Duks',
 22110: 'AL2',
 14236: 'Slight Malfunction',
 14799: 'LCS Javawocky',
 20217: 'Surge',
 8500: 'The Generals',
 10539: 'Ultro',
 11943: 'The Nighthawks',
 14413: 'Trinity Tigers',
 15580: 'Robo-Synthesis',
 16798: 'Redhawk Robotics',
 17522: 'ETech Chargers',
 18657: 'AIM Robotics',
 20233: 'Blazing Bluebots',
 21377: 'Botsworth',
 22324: 'ETech Spare Parts',
 9778: 'Robotic Chinchillas',
 11986: 'Code Blue',
 12398: 'Bobcat Robotics',
 13755: 'Robocat',
 16617: 'Nazareth Robotics',
 17028: 'DuMoore Robotics',
 18570: 'Swift PowerMech',
 18801: 'Crazy Hat People',
 18838: "Robo's Pit Crew",
 19717: 'Bomb City Bots Blue',
 19782: 'Hart Robotics',
 19955: 'Robo Rangers',
 19956: 'Mechanical Mayhem',
 19957: 'Khaos',
 21780: 'Longhorn Robotics',
 21848: 'DuMoore Robotics 2.0',
 22304: 'Bomb City Bots Gold',
 22306: 'Bomb City Bots White',
 506: 'Pandara',
 516: 'Gears of Fire',
 3101: 'Boom Bots',
 3123: 'Spontaneous Combustion',
 3736: 'Serious Business',
 3830: 'Violet Fusion',
 3839: 'Mechanical Geniuses',
 11706: 'Robots in Paradise',
 14226: 'Ironic',
 15006: 'Nerdvana',
 15858: 'e=mc Hammer',
 17115: 'Patriots',
 21745: 'Robo Lancers',
 21944: 'RNDOPS',
 22473: 'AMIKids Motion',
 22474: 'AMIKids Future Masterminds',
 22475: 'AMIKids SOG',
 10179: 'Tech Turtles',
 14707: 'Zero Logic',
 14708: 'Short Circuits',
 15297: 'Legacy',
 16626: 'Radical Raiders',
 17561: 'Isotopic Blatta',
 18147: 'The Imposters',
 18699: 'The Purple Axolotls',
 22218: 'Dog Bytes',
 4100: 'Darbots 1',
 6047: 'Twisted Axles',
 7373: 'Eagle Robotics - Carbon Fiber',
 10068: 'Duct-Ties & Zip-Tape',
 11364: 'Eagle Robotics - Diamond Plate',
 16757: 'Primum Optimus',
 17379: 'Romebotics',
 2858: 'Sparbots, FTC Green',
 6278: 'Dwayne',
 9206: 'iRobotics',
 10158: "Scott's Bots",
 10537: 'Brobotix',
 14682: 'Gears & Spears',
 14778: 'Autonomous Anonymous ',
 21947: 'Sparbots, FTC Silver',
 22160: 'Nuts and Bolts',
 22301: 'Legionaries',
 7332: 'DodgerBOTS',
 9973: 'Scrap Mechanics',
 10185: 'From The Island Of Misfit Robots',
 13416: 'JagWires',
 14452: 'Biohazard Bots',
 15071: 'Gearheads',
 21311: 'Lion Robotics',
 4537: 'DRSS Enterprise',
 5040: 'Nuts & Bolts',
 8417: "'Lectric Legends",
 10464: 'The Bionic Tigers',
 11225: 'DELTA Robotics (Louisville Collegiate School)',
 14709: 'Augusta Panthers',
 18208: 'Trinity Titans',
 19841: 'RAMbotics',
 20694: 'Craft Coalition ',
 21623: 'Failing Formally',
 7693: 'TECHNADOS',
 10016: 'Clarkston RoboWolves',
 11717: 'Circuit Breakers',
 14066: 'Berkshire Hazards',
 14638: 'Infinity & Beyond',
 14757: 'The SashaBRAWLERS',
 15471: 'Furious Flames',
 16734: 'Delivery Ducks',
 17181: 'Vibranium Vikings',
 18954: 'Viking Tech',
 22134: 'Gear G.O.A.Ts',
 10803: 'Awesome Aviators',
 14670: 'TerrorBytes',
 14936: 'Ribbit Ravens',
 14937: 'Electro-Ravens',
 14938: 'Goofy AAAAH Ravens',
 14939: 'Ruthless Ravens',
 14941: 'The Professionals',
 14944: 'Riverbots',
 14946: 'Robo Ravens, Jr.',
 14947: 'Robotic Ravens',
 15770: 'Spartbots',
 21518: 'The Atomic Toasters',
 21522: 'Robo Falcons',
 3093: 'The Metal Mercenaries',
 3963: 'Iron Legion',
 9044: "NERD-Hinsin's Legacy",
 10428: 'Ace Of Spades',
 12721: 'Apollo',
 14876: 'TRA3N REX',
 22167: 'Infinity Angles',
 22168: 'Capybearings',
 22293: 'NERD-Airship',
 4859: 'Westerner Mechnoblades',
 4894: "Waggish Walen's Western Warblers\t",
 4895: 'The Dueling Westerners\t',
 10676: 'Lady Warbots',
 13788: 'Talkington Tinies',
 13825: 'Westerner Cobots\t',
 15592: 'T-Force',
 17251: 'Divide & Conquer',
 17461: 'Trial & Error',
 18318: 'Matador Robotics',
 19428: 'Purple People Eaters',
 19433: 'Astros in the Ocean',
 22329: 'Westernators',
 16272: 'Mark X',
 17011: 'Mercenaries',
 17348: 'MCA Horsepower - Gold',
 17385: 'MCA Horsepower - Blue',
 18121: 'MiT - Mercenaries in Training',
 21171: 'The Marvels of M12',
 21683: 'Titan Robotics',
 8204: 'Blue Machine',
 12430: 'Dub East',
 13140: 'The P-51 Mustangs: Team Imagine',
 13141: 'The P-51 Mustangs: Team Inspire',
 13142: 'The P-51 Mustangs: Team Innovate',
 13539: 'RoboChargers - Thunder - Yellow',
 13542: 'RoboChargers - Typhoon - Blue',
 13552: 'RoboChargers - Terremoto - Pink',
 18871: 'RoboChargers - Purple',
 20482: 'Wylie E. Robote',
 20483: 'Wall East',
 21987: 'The Cybirds: Talon',
 21988: 'The Cybirds: Claw',
 22418: 'RoboChargers - Red',
 22419: 'RoboChargers - Orange',
 22527: 'RoboChargers - Cyan',
 12393: 'Pioneer Pi-Thons',
 12394: 'Pioneer Diamondbacks',
 12397: 'High Voltage Rattlers',
 12448: 'M.A.R.S. - Patriot Engineering',
 12453: 'Phoenix - Patriot Engineering',
 13265: 'Osiris',
 13269: 'Mustang MegaBytes',
 13512: 'Falcon ROBO-RANGERS',
 13523: 'Lady ROBO-RANGERS',
 13580: 'Tech Serpents',
 13581: 'Fang Gang',
 14675: 'Vikings',
 14676: 'AzTECHS',
 14679: 'Valkyries',
 17072: 'WLA Vernon Middle School: Robo-Scorpions 17072',
 17203: 'ATHENA',
 18260: 'RoboJags',
 18629: 'Collegiate GigaKnights',
 18630: 'Collegiate MegaKnights',
 22320: 'ROGUE-RANGERS Vengeance',
 6566: 'Circuit Breakers',
 9161: 'Overload',
 11030: 'Metal Jackets',
 13472: 'The Dork Side',
 13811: 'High Voltage',
 14445: 'Poseidons',
 16412: 'Triad Robotics',
 17658: 'Wildcat Robotics',
 18072: 'BCS Battery Acid',
 20325: 'Maximum Resistance',
 11000: 'Rowe-botic Warriors',
 11009: 'McHi Robodogs',
 11156: 'Kaizen Cardinals',
 11158: 'Deceptibots',
 11159: 'Raven Robotics',
 11455: 'Memorial Raiders',
 12373: 'Rowe-botic Problem',
 12375: 'Rowe-botic Clique',
 12395: 'Rattler Robotics',
 12401: 'Quantum Fusion - Patriot Engineering',
 12696: 'SupernoVa - Patriot Engineering',
 12713: 'Impulse',
 13108: 'Encrypted',
 13514: 'Big Bang Mission Eagle',
 13582: 'Optimus Primates',
 13586: 'Adders',
 13588: 'Rattlerbots',
 13590: 'Viperstrike',
 15205: 'Diamonds',
 15251: 'Hadron Mission Eagle',
 15655: 'Donna High School',
 16961: 'Venombots',
 17778: 'Cougar Trons',
 18627: 'Collegiate NanoKnights',
 18734: 'Mission Eagles1',
 19857: 'GigaBots',
 20420: 'Collegiate TeraKnights',
 20481: 'DHS T-STEM',
 20687: 'RCJH.CC- AutoCavs',
 20688: 'RCJH.CC- DeceptiCavs',
 20745: 'Edinburg North Robotics',
 21826: 'The Herculites',
 21934: 'JLHS Engineering and Robotics 1',
 21935: 'JLHS Engineering and Robotics 2',
 4902: 'Team Novabots',
 9923: 'Team AAA',
 11924: 'Martin Robots',
 12202: 'Gaga for Robots',
 12359: 'Sharp Sharks',
 13744: 'Enginerds',
 13833: 'Deep Space Dolphins',
 15654: 'Nanoknights',
 15930: 'Pirates',
 16029: 'Software Pirates',
 16251: 'Robo Pirates',
 17796: 'Caffeinated  Mechanics',
 15439: 'J-BOT-C',
 18672: 'Battalion B0TS',
 6282: 'Simi Valley Robotics',
 9247: 'Chromium Robotics',
 10006: 'Spudnik',
 10298: 'Brain Stormz',
 10673: 'Spudbots',
 13046: 'Riptide Robotics',
 16726: 'SavageSpud',
 19634: 'Royal Robotics',
 20381: 'Killer Instinct A',
 22037: 'Z Transformers',
 10276: 'Storm Troopers',
 11172: 'Static Discharge',
 11774: 'Palatka High School Robo-Panthers',
 14384: 'Patent Pending',
 14447: 'CyberVikings',
 15052: 'Space Engineers',
 16271: 'Flying Tigers',
 16465: 'Servo Stallions',
 17593: 'Mechanical Menaces',
 18145: 'Men in Black Jax',
 18317: 'Steel Eels',
 18385: 'SHIVA Atomatrons',
 19388: 'Metal Mavericks',
 19762: 'Electrical Mayhem',
 19803: 'A. Philip Randolph 1',
 19916: 'The Wolf Pack Robotics Club',
 20357: 'Tocoi Creek Los Toros Loco',
 20358: 'Tocoi Creek Robo Toros',
 20397: ' Flashes',
 20865: 'Atlantic Coast Gamma Rays',
 22126: 'Bubble Bot Computing',
 22127: 'Mischievous Mechanics',
 22128: 'BFBI',
 22158: 'Tocoi Creek Thunder Chickens',
 22238: 'Screw It',
 8796: 'Clay ',
 8797: 'Oakleaf High School',
 8798: 'Aluminati Industries',
 8799: 'Robo Tigers',
 9214: 'R²',
 10284: 'Team R.O.B.O.T. (Really Obsessed Builders Of Tomorrow)',
 10583: 'The Robotic Gladiators',
 10584: 'KH Roba Fett',
 10768: 'Middleburg High School',
 13675: 'Talon Techs',
 4327: 'Silver Titans',
 7482: 'Axel-otls',
 8678: 'BATteries',
 9785: 'Cronos',
 10458: 'EVE Robotics FTC',
 11127: 'Whitefield Robotics',
 12995: 'Monkey Wrench Robotics',
 14750: 'ATOM',
 20172: 'Prometheus',
 21915: 'SMA Bobcats',
 4221: 'Smíða Syndicate',
 15500: 'Pixelate Gold',

In [28]:
all_teams[22802] = 'Swanage'

In [33]:
df = pd.DataFrame(all_teams.items(), columns=['Team Number', 'Team Name'])

In [34]:
df

      Team Number                   Team Name
0            5951                    Mustangs
1            8990  Mile High Academy Mustangs
2           11020                     SKI SKY
3           15931                   Tin Heads
4           16899                 CPUsaders_T
...           ...                         ...
5908        23150                      Dragon
5909        23152                       飞虎创学队
5910        23153                         梦之队
5911        23155                        37中队
5912        23160                     Robodes

[5913 rows x 2 columns]

In [43]:
df = df.rename({0: "Team Number"}, axis = "columns")

In [35]:
df.to_csv(os.getcwd().replace('scripts', 'data') + '/teams.csv', index = False)