In [1]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import os

In [3]:
matches = pd.read_csv(os.getcwd().replace('scripts', 'data')+ '/all_matches.csv')

In [4]:
matches

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
...,...,...,...,...,...
1213,USUTCMP,Utah Championship,USA,2023-03-11 00:00:00,2023-03-11 00:00:00
1214,USVTCMP,Vermont FTC Championship,USA,2023-02-11 00:00:00,2023-02-11 00:00:00
1215,USWACMP,Washington State Championship,USA,2023-01-28 00:00:00,2023-01-28 00:00:00
1216,USWICMP,Wisconsin Championship,USA,2023-03-11 00:00:00,2023-03-11 00:00:00
1217,USWYCMP,Wyoming 2023 FTC State Championship,USA,2023-02-17 00:00:00,2023-02-18 00:00:00

In [24]:
import time
from bs4 import BeautifulSoup
from selenium import webdriver

url = "https://ftc-events.firstinspires.org/2022/"
driver = webdriver.Safari()
all_teams = set([])
for i in range(matches.shape[0]):
    add = matches.at[i, 'Link']
    driver.get(url + add)
    src = driver.page_source
    soup = BeautifulSoup(src, 'lxml')
    teams = soup.find('table', {'id': 'teamtable'}).find('tbody').find_all('a')
    
    for t in teams:
        all_teams.add(int(t['href'].split("/")[-1]))
    time.sleep(3)
driver.close()

In [25]:
all_teams

{1,
 7,
 18,
 22,
 25,
 40,
 54,
 92,
 112,
 118,
 124,
 127,
 130,
 133,
 149,
 187,
 194,
 201,
 202,
 207,
 208,
 226,
 247,
 248,
 251,
 252,
 265,
 267,
 288,
 289,
 290,
 291,
 293,
 310,
 327,
 354,
 358,
 359,
 365,
 367,
 369,
 389,
 392,
 406,
 417,
 450,
 479,
 506,
 516,
 519,
 524,
 525,
 535,
 542,
 596,
 607,
 609,
 636,
 641,
 652,
 654,
 673,
 701,
 724,
 731,
 750,
 753,
 755,
 772,
 965,
 1001,
 1002,
 1622,
 99998,
 99999,
 1885,
 2408,
 2425,
 2818,
 2827,
 2836,
 2844,
 2845,
 2858,
 2866,
 2867,
 2879,
 2887,
 2901,
 2923,
 2939,
 2993,
 3006,
 3032,
 3033,
 3050,
 3058,
 3081,
 3093,
 3101,
 3116,
 3123,
 3188,
 3189,
 3208,
 3216,
 3231,
 3296,
 3311,
 3351,
 3371,
 3397,
 3409,
 3415,
 3470,
 3479,
 3491,
 3505,
 3507,
 3526,
 3537,
 3540,
 3543,
 3558,
 3565,
 3583,
 3587,
 3591,
 3592,
 3609,
 3615,
 3638,
 3640,
 3641,
 3650,
 3658,
 3665,
 3666,
 3708,
 3734,
 3736,
 3737,
 3738,
 3746,
 3747,
 3749,
 3750,
 3763,
 3764,
 3766,
 3774,
 3777,
 3781,
 3788,
 3791,
 3795,
 3796,
 3804,
 3805,
 3819,
 3825,
 3830,
 3839,
 3846,
 3848,
 3861,
 3888,
 3900,
 3916,
 3922,
 3944,
 3954,
 3963,
 3965,
 3981,
 4008,
 4017,
 4029,
 4042,
 4053,
 4054,
 4087,
 4096,
 4097,
 4100,
 4102,
 4104,
 4106,
 4115,
 4116,
 4133,
 4137,
 4149,
 4150,
 4153,
 4155,
 4156,
 4169,
 4174,
 4175,
 4177,
 4185,
 4193,
 4194,
 4200,
 4215,
 4216,
 4221,
 4227,
 4228,
 4232,
 4234,
 4237,
 4239,
 4243,
 4250,
 4262,
 4266,
 4267,
 4273,
 4286,
 4324,
 4326,
 4327,
 4328,
 4345,
 4347,
 4348,
 4358,
 4360,
 4366,
 4410,
 4416,
 4419,
 4443,
 4444,
 4451,
 4454,
 4466,
 4475,
 4509,
 4511,
 4531,
 4537,
 4545,
 4546,
 4602,
 4622,
 4625,
 4628,
 4634,
 4641,
 4650,
 4654,
 4705,
 4707,
 4711,
 4717,
 4719,
 4720,
 4721,
 4745,
 4774,
 4780,
 4781,
 4782,
 4783,
 4784,
 4785,
 4798,
 4809,
 4812,
 4813,
 4848,
 4849,
 4859,
 4885,
 4886,
 4890,
 4894,
 4895,
 4897,
 4902,
 4906,
 4914,
 4921,
 4924,
 4936,
 4943,
 4946,
 4947,
 4949,
 4950,
 4951,
 4957,
 4964,
 4965,
 4969,
 4970,
 4982,
 4991,
 4995,
 4997,
 4998,
 5009,
 5011,
 5014,
 5015,
 5017,
 5020,
 5026,
 5037,
 5039,
 5040,
 5044,
 5053,
 5060,
 5062,
 5064,
 5070,
 5072,
 5094,
 5095,
 5105,
 5108,
 5115,
 5118,
 5119,
 5125,
 5126,
 5131,
 5136,
 5140,
 5141,
 5143,
 5153,
 5155,
 5159,
 5161,
 5175,
 5178,
 5187,
 5188,
 5189,
 5196,
 5198,
 5199,
 5206,
 5214,
 5218,
 5225,
 5227,
 5233,
 5237,
 5243,
 5248,
 5262,
 5270,
 5273,
 5276,
 5283,
 5285,
 5289,
 5290,
 5291,
 5292,
 5300,
 5309,
 5319,
 5320,
 5321,
 5325,
 5356,
 5361,
 5363,
 5383,
 5384,
 5385,
 5386,
 5387,
 5389,
 5390,
 5395,
 5404,
 5411,
 5422,
 5436,
 5439,
 5440,
 5445,
 5467,
 5470,
 5477,
 5481,
 5484,
 5485,
 5488,
 5495,
 5498,
 5501,
 5518,
 5543,
 5549,
 5553,
 5559,
 5573,
 5598,
 5604,
 5618,
 5627,
 5628,
 5641,
 5661,
 5667,
 5681,
 5683,
 5703,
 5709,
 5710,
 5713,
 5741,
 5754,
 5762,
 5773,
 5784,
 5795,
 5828,
 5843,
 5881,
 5891,
 5893,
 5897,
 5898,
 5899,
 5905,
 5906,
 5907,
 5911,
 5913,
 5919,
 5921,
 5951,
 5953,
 5954,
 5957,
 5960,
 5962,
 5968,
 5971,
 5976,
 5979,
 5980,
 6010,
 6016,
 6025,
 6032,
 6037,
 6038,
 6040,
 6042,
 6047,
 6051,
 6055,
 6069,
 6072,
 6073,
 6078,
 6079,
 6085,
 6088,
 6093,
 6101,
 6102,
 6103,
 6121,
 6128,
 6133,
 6134,
 6147,
 6155,
 6158,
 6165,
 6168,
 6169,
 6174,
 6175,
 6183,
 6184,
 6188,
 6189,
 6190,
 6198,
 6199,
 6200,
 6205,
 6206,
 6209,
 6210,
 6220,
 6221,
 6226,
 6252,
 6255,
 6272,
 6273,
 6278,
 6281,
 6282,
 6285,
 6286,
 6294,
 6298,
 6299,
 6302,
 6321,
 6322,
 6323,
 6325,
 6340,
 6341,
 6347,
 6357,
 6366,
 6371,
 6372,
 6373,
 6378,
 6382,
 6383,
 6387,
 6390,
 6402,
 6406,
 6407,
 6417,
 6418,
 6420,
 6424,
 6426,
 6427,
 6433,
 6436,
 6437,
 6448,
 6454,
 6455,
 6458,
 6460,
 6482,
 6494,
 6496,
 6499,
 6516,
 6518,
 6527,
 6540,
 6545,
 6546,
 6547,
 6549,
 6552,
 6556,
 6559,
 6566,
 6567,
 6584,
 6596,
 6600,
 6603,
 6606,
 6625,
 6638,
 6645,
 6652,
 6661,
 6662,
 6666,
 6676,
 6699,
 6704,
 6708,
 6727,
 6731,
 6762,
 6811,
 6831,
 6832,
 6889,
 6892,
 6899,
 6901,
 6914,
 6934,
 6936,
 6942,
 6945,
 6949,
 6955,
 6962,
 6973,
 6974,
 6976,
 6983,
 6984,
 6985,
 6988,
 6989,
 6990,
 6996,
 7000,
 7002,
 7006,
 7017,
 7021,
 7026,
 7030,
 7031,
 7034,
 7039,
 7040,
 7043,
 7045,
 7047,
 7048,
 7064,
 7065,
 7078,
 7079,
 7080,
 7083,
 7085,
 7093,
 7095,
 7100,
 7105,
 7110,
 7120,
 7128,
 7129,
 7130,
 7135,
 7136,
 7139,
 7140,
 7149,
 7153,
 7156,
 7159,
 7161,
 7163,
 7164,
 7172,
 7175,
 7193,
 7196,
 7198,
 7209,
 7215,
 7224,
 7229,
 7230,
 7231,
 7238,
 7242,
 7244,
 7245,
 7247,
 7251,
 7252,
 7253,
 7255,
 7258,
 7259,
 7277,
 7278,
 7281,
 7288,
 7290,
 7299,
 7303,
 7305,
 7316,
 7324,
 7330,
 7332,
 7341,
 7346,
 7350,
 7360,
 7373,
 7390,
 7393,
 7400,
 7407,
 7414,
 7416,
 7417,
 7418,
 7420,
 7423,
 7424,
 7438,
 7444,
 7460,
 7462,
 7470,
 7473,
 7474,
 7477,
 7482,
 7486,
 7495,
 7496,
 7497,
 7498,
 7499,
 7506,
 7518,
 7519,
 7525,
 7532,
 7547,
 7553,
 7571,
 7584,
 7588,
 7592,
 7593,
 7604,
 7609,
 7610,
 7613,
 7615,
 7627,
 7631,
 7641,
 7643,
 7662,
 7673,
 7676,
 7678,
 7689,
 7693,
 7715,
 7716,
 7719,
 7732,
 7742,
 7759,
 7760,
 7767,
 7772,
 7783,
 7786,
 7788,
 7792,
 7797,
 7802,
 7813,
 7823,
 7830,
 7833,
 7834,
 7835,
 7837,
 7841,
 7842,
 7844,
 7854,
 7878,
 7880,
 7883,
 7896,
 7897,
 7899,
 7900,
 7904,
 7924,
 7935,
 7951,
 7953,
 7959,
 7961,
 7974,
 7988,
 7989,
 8013,
 8027,
 8034,
 8039,
 8080,
 8081,
 8087,
 8088,
 8089,
 8094,
 8095,
 8097,
 8099,
 8101,
 8103,
 8109,
 8110,
 8114,
 8120,
 8129,
 8130,
 8132,
 8133,
 8136,
 8142,
 8149,
 8153,
 8161,
 8188,
 8194,
 8203,
 8204,
 8227,
 8239,
 8245,
 8271,
 8272,
 8280,
 8284,
 8291,
 8295,
 8300,
 8304,
 8327,
 8365,
 8367,
 8373,
 8375,
 8379,
 8380,
 8381,
 8393,
 8395,
 8397,
 8400,
 8404,
 8405,
 8406,
 8411,
 8413,
 8417,
 8421,
 8424,
 8433,
 8435,
 8461,
 8468,
 8472,
 8478,
 8479,
 8480,
 8482,
 8487,
 8490,
 8492,
 8499,
 8500,
 8509,
 8511,
 8513,
 8514,
 8527,
 8529,
 8531,
 8533,
 8535,
 8541,
 8548,
 8563,
 8565,
 8569,
 8572,
 8578,
 8579,
 8580,
 8581,
 8582,
 8588,
 8603,
 8610,
 8617,
 8620,
 8621,
 8624,
 8625,
 8626,
 8636,
 8637,
 8638,
 8641,
 8642,
 8644,
 8645,
 8646,
 8647,
 8648,
 8649,
 8651,
 8656,
 8672,
 8678,
 8680,
 8688,
 8690,
 8693,
 8695,
 8696,
 8698,
 8699,
 8702,
 8703,
 8709,
 8717,
 8719,
 8721,
 8728,
 8730,
 8732,
 8733,
 8740,
 8741,
 8743,
 8755,
 8772,
 8777,
 8790,
 8791,
 8793,
 8796,
 8797,
 8798,
 8799,
 8801,
 8807,
 8811,
 8812,
 8813,
 8816,
 8818,
 8823,
 8824,
 8825,
 8845,
 8856,
 8859,
 8863,
 8866,
 8872,
 8886,
 8887,
 8888,
 8892,
 8894,
 8895,
 8898,
 8899,
 8902,
 8905,
 8907,
 8922,
 8923,
 8930,
 8932,
 8942,
 8947,
 8956,
 8962,
 8969,
 8971,
 8987,
 8988,
 8990,
 9006,
 9010,
 9013,
 9020,
 9021,
 9027,
 9028,
 9034,
 9040,
 9044,
 9045,
 9049,
 9054,
 9060,
 9063,
 9064,
 9073,
 9076,
 9087,
 9102,
 9103,
 9110,
 ...}

In [29]:
list(all_teams)[-1]

23164

In [30]:
d = {"Team Number":all_teams}

In [42]:
df = pd.DataFrame(list(all_teams))

In [36]:
df

          0
0         1
1         7
2        18
3        22
4        25
...     ...
5899  23152
5900  23153
5901  23155
5902  23160
5903  23164

[5904 rows x 1 columns]

In [43]:
df = df.rename({0: "Team Number"}, axis = "columns")

In [46]:
df.to_csv(os.getcwd().replace('scripts', 'data') + '/teams.csv', index = False)

In [44]:
df

      Team Number
0               1
1               7
2              18
3              22
4              25
...           ...
5899        23152
5900        23153
5901        23155
5902        23160
5903        23164

[5904 rows x 1 columns]