In [2]:
import pandas as pd
import os

In [11]:
data = pd.read_csv(os.getcwd().replace("scripts", "data/all_data.csv"))

In [6]:
data.head(50)

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T
0,12599,Overcharged,187.2,187.1,182.0,45.5,76.8,59.7,205.6,233,Oregon,2.0,34.8,9‑0‑0
1,8644,The Brainstormers,179.7,185.1,178.7,45.8,105.9,27.0,212.0,229,Massachusetts,2.0,63.2,10‑0‑0
2,15637,Fata Morgana,171.1,182.9,171.3,41.6,87.5,42.3,214.7,250,Israel,2.0,106.3,10‑1‑0
3,11329,I.C.E. Robotics,171.0,174.9,170.1,49.7,77.5,42.8,209.4,241,Indiana,2.0,84.0,9‑0‑0
4,18438,Wolfpack Machina,169.8,174.1,169.8,40.4,71.4,58.0,202.2,243,Massachusetts,2.0,84.7,10‑0‑0
5,11329,I.C.E. Robotics,165.2,166.9,161.0,44.8,85.7,30.5,207.0,228,Indiana,2.0,59.4,5‑0‑0
6,12599,Overcharged,162.7,165.4,165.0,39.2,77.8,48.0,222.2,284,Oregon,2.0,69.8,5‑0‑0
7,14179,Sushi Squad,161.2,152.8,161.6,47.4,70.7,43.5,251.0,271,New,2.0,71.2,6‑2‑0
8,8644,The Brainstormers,160.5,165.3,159.1,38.1,86.4,34.6,202.8,235,Massachusetts,2.0,53.7,10‑0‑0
9,14525,TerraBats,160.5,162.3,160.7,43.0,87.7,30.0,208.2,244,California,2.0,111.6,9‑0‑0
10,16458,TechnoWizards,158.9,163.5,157.5,45.6,98.8,13.1,177.2,180,Texas,2.0,36.0,6‑0‑0
11,7172,Technical Difficulties,158.7,171.6,158.3,45.0,81.9,31.5,227.0,229,Texas,2.0,117.3,10‑0‑0
12,19121,Tea Borgs,155.2,164.0,152.8,41.3,73.9,37.6,202.7,248,Romania,2.0,104.8,9‑3‑0
13,19458,Equilibrium.exe,154.9,156.2,152.3,38.5,73.2,40.6,195.8,217,Chesapeake,2.0,54.6,9‑0‑0
14,19746,The Disruptingly Robocephalic BrainSTEM Roboti...,154.0,158.5,153.0,47.9,81.2,23.9,223.4,242,Texas,2.0,126.4,9‑0‑0
15,8644,The Brainstormers,153.1,152.6,154.8,29.1,97.7,28.0,183.2,227,Chesapeake,2.0,28.2,9‑0‑0
16,16158,VC Silver Circuits,149.9,145.6,150.1,31.7,77.5,40.9,181.3,233,Nevada,2.0,47.3,10‑1‑0
17,21229,Quality Control,149.8,160.8,150.0,42.8,77.5,29.7,214.8,264,Washington,2.0,129.2,7‑2‑0
18,9956,The Knack,149.1,155.2,145.9,48.4,75.9,21.6,196.8,219,Chesapeake,2.0,109.0,7‑2‑0
19,11329,I.C.E. Robotics,147.9,151.1,147.5,40.0,70.5,36.9,215.2,237,Indiana,1.6,104.4,4‑3‑0
20,8393,The Giant Diencephalic BrainSTEM Robotics Team,145.7,161.4,145.6,49.9,57.8,37.9,230.8,238,Chesapeake,2.0,109.2,10‑3‑1
21,18529,Rust In Piece Robotics,145.6,145.2,144.6,40.8,88.7,15.1,208.3,223,Illinois,1.6,133.6,5‑3‑0
22,12560,Soft Hoarders,145.1,144.9,144.6,41.0,66.6,37.0,215.5,218,Romania,2.0,124.5,10‑1‑0
23,18438,Wolfpack Machina,144.9,148.4,145.1,49.4,63.6,32.1,229.6,246,Chesapeake,1.6,127.0,5‑3‑0
24,14614,Electro,144.0,146.1,143.9,40.9,76.5,26.5,198.6,217,Illinois,2.0,108.0,9‑0‑0
25,19234,BYTE FORCE RO037,143.8,148.6,144.7,42.3,62.6,39.8,216.8,245,Romania,2.0,71.7,6‑2‑0
26,21229,Quality Control,143.6,147.5,141.5,48.0,66.7,26.9,181.5,270,Colorado,2.0,63.8,10‑0‑0
27,12599,Overcharged,143.6,149.6,142.9,34.4,59.1,49.4,178.8,206,Oregon,2.0,41.4,5‑0‑0
28,20153,Silver Wolves,142.8,161.8,142.8,39.7,74.6,28.5,193.4,246,Pennsylvania,1.6,116.6,8‑3‑0
29,10138,Newton Busters,142.0,152.7,140.6,28.7,74.9,36.9,199.0,233,Illinois,1.6,133.8,8‑1‑0
30,22377,SigmaCorns,142.0,138.7,142.2,43.0,75.8,23.4,168.6,184,North,2.0,69.2,9‑0‑0
31,3658,The BOSONS,141.3,141.9,141.6,41.7,62.8,37.1,182.2,219,Missouri,1.7,76.8,5‑1‑0
32,19561,Tiger Tech Black 19561,141.1,141.1,141.5,39.8,93.8,7.8,200.7,222,Michigan,1.3,172.0,5‑4‑0
33,19862,Mecha Mantises,141.0,137.4,139.1,45.5,77.0,16.7,185.4,219,California,1.2,126.4,3‑4‑0
34,9889,Cruise Control,140.8,153.0,140.9,23.2,70.2,47.5,212.4,271,New,2.0,39.2,5‑0‑0
35,19746,The Disruptingly Robocephalic BrainSTEM Roboti...,140.4,142.7,135.7,39.9,75.9,19.9,210.6,226,Texas,1.6,137.2,7‑3‑0
36,16158,VC Silver Circuits,139.4,138.0,133.7,31.9,70.6,31.1,154.6,187,Nevada,2.0,29.6,5‑0‑0
37,17595,Beta Bionix,139.1,145.6,138.9,25.7,76.8,36.3,192.2,224,Washington,1.2,129.2,7‑2‑0
38,21229,Quality Control,139.0,154.2,135.4,47.1,68.0,20.3,224.2,235,Colorado,2.0,107.7,10‑0‑0
39,18527,PCM Alchemists,138.9,146.0,137.3,42.8,66.1,28.4,204.2,257,Iowa,1.7,121.2,8‑3‑0
40,11039,Innov8rz,137.5,138.3,138.8,41.9,86.7,10.3,171.2,186,California,2.0,91.8,9‑0‑0
41,16417,ROC,137.3,138.6,136.9,37.7,90.3,8.9,166.8,194,Ontario,2.0,37.0,10‑0‑0
42,16617,Nazareth Robotics,137.2,149.2,137.6,25.6,75.6,36.3,180.2,205,Texas,2.0,90.6,8‑3‑0
43,19458,Equilibrium.exe,136.8,131.6,136.9,39.5,73.4,24.0,188.2,209,Chesapeake,2.0,83.6,9‑0‑0
44,8393,The Giant Diencephalic BrainSTEM Robotics Team,136.3,140.0,135.1,18.8,65.8,50.5,177.4,211,Pennsylvania,2.0,56.4,9‑0‑0
45,19098,Easten Foxes,136.1,136.1,134.4,39.0,66.8,28.6,203.3,243,Romania,2.0,118.0,7‑2‑0
46,16458,TechnoWizards,136.1,142.8,131.8,44.0,68.9,18.9,156.8,170,Texas,2.0,50.6,9‑0‑0
47,11855,Joe Bots - Blue,136.0,139.1,133.9,32.2,79.3,22.4,173.4,202,Michigan,1.8,109.0,6‑3‑1
48,7105,SWIFT Intergalactic Space Llamas,135.0,156.2,138.4,41.0,49.4,48.0,216.2,254,North,1.6,107.2,6‑3‑0
49,14525,TerraBats,134.9,133.8,137.1,41.5,72.2,23.4,199.4,234,California,2.0,111.0,5‑0‑0

In [17]:
data.sort_values("Team Number")

,Team Number,Team Name,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Region,Avg RP,Avg Opp,Event W-L-T
8909,1,Team Unlimited,24.6,31.5,24.8,0.0,12.2,12.6,69.3,109.0,Massachusetts,1.3,38.3,4‑4‑0
3327,1,Team Unlimited,57.2,72.1,60.5,21.4,28.7,10.4,126.0,165.0,Massachusetts,1.3,63.0,5‑4‑0
7439,7,Tactical Sheep,31.6,49.3,32.3,9.1,16.5,6.7,102.4,123.0,Chesapeake,1.2,83.4,3‑4‑0
559,7,Tactical Sheep,94.8,102.9,94.3,30.4,42.8,21.1,181.2,216.0,Chesapeake,1.2,137.8,3‑4‑1
158,7,Tactical Sheep,115.6,108.6,117.9,39.6,62.6,15.7,176.6,208.0,Chesapeake,2.0,44.4,9‑0‑0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2456,23015,NaN,64.9,71.9,61.9,20.1,21.3,20.5,131.0,182.0,Romania,1.3,96.3,4‑2‑0
13416,23050,NaN,7.3,11.3,5.4,1.5,0.0,3.9,59.3,146.0,Arkansas,0.3,147.8,1‑5‑0
8134,23056,NaN,28.2,30.3,24.9,1.7,19.3,3.8,53.5,78.0,Kazakhstan,0.7,95.3,2‑4‑0
14387,23085,NaN,3.0,14.7,6.3,0.0,4.5,1.8,69.5,112.0,Kazakhstan,1.0,56.7,3‑3‑0
8081,23088,NaN,28.4,36.2,30.3,0.9,14.7,14.7,100.2,164.0,Kazakhstan,1.0,59.7,7‑4‑0

In [61]:
wlt = pd.concat([data["Team Number"], data["Event W-L-T"]], axis = 1)

In [62]:
x = lambda a,b: (int(a.split("-")[0])+ int(b.split("-")[0])) +"-" +(int(a.split("-")[1])+ int(b.split("-")[1]))+"-" +(int(a.split("-")[2])+ int(b.split("-")[2]))

In [63]:
w = []
l = []
t = []
for index, row in wlt.iterrows():
    arr = row["Event W-L-T"].split("‑")
    
    w.append(int(arr[0]))
    l.append(int(arr[1]))
    t.append(int(arr[2]))
    
wlt["W"] = w
wlt["L"] = l
wlt["T"] = t

In [64]:
wlt

       Team Number Event W-L-T   W  L  T
0            12599       9‑0‑0   9  0  0
1             8644      10‑0‑0  10  0  0
2            15637      10‑1‑0  10  1  0
3            11329       9‑0‑0   9  0  0
4            18438      10‑0‑0  10  0  0
...            ...         ...  .. .. ..
15561        22673       0‑5‑0   0  5  0
15562        14165       2‑3‑0   2  3  0
15563        21886       1‑4‑0   1  4  0
15564        13402       0‑5‑0   0  5  0
15565        19734       2‑3‑0   2  3  0

[15566 rows x 5 columns]

In [65]:
wlt = wlt.drop("Event W-L-T", axis = 1)

In [66]:
wlt

       Team Number   W  L  T
0            12599   9  0  0
1             8644  10  0  0
2            15637  10  1  0
3            11329   9  0  0
4            18438  10  0  0
...            ...  .. .. ..
15561        22673   0  5  0
15562        14165   2  3  0
15563        21886   1  4  0
15564        13402   0  5  0
15565        19734   2  3  0

[15566 rows x 4 columns]

In [ ]:
wlt[]

In [67]:
wlt.groupby("Team Number").sum()

              W   L  T
Team Number
1             9   8  0
7            15   8  1
18            3   7  0
22            5  20  0
25           11  12  0
...          ..  .. ..
23015         4   2  0
23050         1   5  0
23056         2   4  0
23085         3   3  0
23088         7   4  0

[5297 rows x 3 columns]

In [28]:
data.groupby("Team Number").mean()

,Non Penalty OPR,OPR,Non Penalty OPRc,Auto OPRc,TeleOp OPRc,End Game OPRc,Avg Score,Max Norm Score,Avg RP,Avg Opp
Team Number,,,,,,,,,,
1,40.900000,51.800000,42.650,10.700000,20.450000,11.50,97.65,137.000000,1.300000,50.650000
7,80.666667,86.933333,81.500,26.366667,40.633333,14.50,153.40,182.333333,1.466667,88.533333
18,33.900000,36.200000,32.100,0.000000,22.600000,9.50,69.60,83.500000,0.600000,79.500000
22,17.600000,19.880000,17.180,4.140000,6.580000,6.44,43.72,72.000000,0.400000,77.160000
25,39.850000,43.750000,37.375,16.750000,11.350000,9.30,71.80,114.750000,1.100000,59.950000
...,...,...,...,...,...,...,...,...,...,...
23015,64.900000,71.900000,61.900,20.100000,21.300000,20.50,131.00,182.000000,1.300000,96.300000
23050,7.300000,11.300000,5.400,1.500000,0.000000,3.90,59.30,146.000000,0.300000,147.800000
23056,28.200000,30.300000,24.900,1.700000,19.300000,3.80,53.50,78.000000,0.700000,95.300000
23085,3.000000,14.700000,6.300,0.000000,4.500000,1.80,69.50,112.000000,1.000000,56.700000
23088,28.400000,36.200000,30.300,0.900000,14.700000,14.70,100.20,164.000000,1.000000,59.700000