In [28]:
import pandas as pd
import os
import matplotlib.pyplot as plt
import glob
import plotly.express as px
import plotly.graph_objects as go
%matplotlib inline

In [3]:

print(glob.glob(os.getcwd().replace('scripts', 'data')+'/team_data/*'))

['/Volumes/mac/ftccomp/data/team_data/1.csv', '/Volumes/mac/ftccomp/data/team_data/10001.csv', '/Volumes/mac/ftccomp/data/team_data/10006.csv', '/Volumes/mac/ftccomp/data/team_data/1001.csv', '/Volumes/mac/ftccomp/data/team_data/10015.csv', '/Volumes/mac/ftccomp/data/team_data/10016.csv', '/Volumes/mac/ftccomp/data/team_data/1002.csv', '/Volumes/mac/ftccomp/data/team_data/10021.csv', '/Volumes/mac/ftccomp/data/team_data/10022.csv', '/Volumes/mac/ftccomp/data/team_data/10023.csv', '/Volumes/mac/ftccomp/data/team_data/10024.csv', '/Volumes/mac/ftccomp/data/team_data/10031.csv', '/Volumes/mac/ftccomp/data/team_data/10035.csv', '/Volumes/mac/ftccomp/data/team_data/10055.csv', '/Volumes/mac/ftccomp/data/team_data/10062.csv', '/Volumes/mac/ftccomp/data/team_data/10064.csv', '/Volumes/mac/ftccomp/data/team_data/10068.csv', '/Volumes/mac/ftccomp/data/team_data/10069.csv', '/Volumes/mac/ftccomp/data/team_data/10075.csv', '/Volumes/mac/ftccomp/data/team_data/10082.csv', '/Volumes/mac/ftccomp/data/team_data/10084.csv', '/Volumes/mac/ftccomp/data/team_data/10091.csv', '/Volumes/mac/ftccomp/data/team_data/10092.csv', '/Volumes/mac/ftccomp/data/team_data/10093.csv', '/Volumes/mac/ftccomp/data/team_data/10095.csv', '/Volumes/mac/ftccomp/data/team_data/10096.csv', '/Volumes/mac/ftccomp/data/team_data/10098.csv', '/Volumes/mac/ftccomp/data/team_data/10099.csv', '/Volumes/mac/ftccomp/data/team_data/10100.csv', '/Volumes/mac/ftccomp/data/team_data/10101.csv', '/Volumes/mac/ftccomp/data/team_data/10104.csv', '/Volumes/mac/ftccomp/data/team_data/10106.csv', '/Volumes/mac/ftccomp/data/team_data/10107.csv', '/Volumes/mac/ftccomp/data/team_data/10110.csv', '/Volumes/mac/ftccomp/data/team_data/10111.csv', '/Volumes/mac/ftccomp/data/team_data/10117.csv', '/Volumes/mac/ftccomp/data/team_data/10123.csv', '/Volumes/mac/ftccomp/data/team_data/10127.csv', '/Volumes/mac/ftccomp/data/team_data/10130.csv', '/Volumes/mac/ftccomp/data/team_data/10132.csv', '/Volumes/mac/ftccomp/data/team_data/10136.csv', '/Volumes/mac/ftccomp/data/team_data/10137.csv', '/Volumes/mac/ftccomp/data/team_data/10138.csv', '/Volumes/mac/ftccomp/data/team_data/10139.csv', '/Volumes/mac/ftccomp/data/team_data/10143.csv', '/Volumes/mac/ftccomp/data/team_data/10158.csv', '/Volumes/mac/ftccomp/data/team_data/10161.csv', '/Volumes/mac/ftccomp/data/team_data/10164.csv', '/Volumes/mac/ftccomp/data/team_data/10168.csv', '/Volumes/mac/ftccomp/data/team_data/10169.csv', '/Volumes/mac/ftccomp/data/team_data/10173.csv', '/Volumes/mac/ftccomp/data/team_data/10179.csv', '/Volumes/mac/ftccomp/data/team_data/10180.csv', '/Volumes/mac/ftccomp/data/team_data/10183.csv', '/Volumes/mac/ftccomp/data/team_data/10185.csv', '/Volumes/mac/ftccomp/data/team_data/10191.csv', '/Volumes/mac/ftccomp/data/team_data/10195.csv', '/Volumes/mac/ftccomp/data/team_data/10198.csv', '/Volumes/mac/ftccomp/data/team_data/10202.csv', '/Volumes/mac/ftccomp/data/team_data/10210.csv', '/Volumes/mac/ftccomp/data/team_data/10211.csv', '/Volumes/mac/ftccomp/data/team_data/10216.csv', '/Volumes/mac/ftccomp/data/team_data/10219.csv', '/Volumes/mac/ftccomp/data/team_data/10237.csv', '/Volumes/mac/ftccomp/data/team_data/10238.csv', '/Volumes/mac/ftccomp/data/team_data/10243.csv', '/Volumes/mac/ftccomp/data/team_data/10246.csv', '/Volumes/mac/ftccomp/data/team_data/10253.csv', '/Volumes/mac/ftccomp/data/team_data/10254.csv', '/Volumes/mac/ftccomp/data/team_data/10255.csv', '/Volumes/mac/ftccomp/data/team_data/10262.csv', '/Volumes/mac/ftccomp/data/team_data/10265.csv', '/Volumes/mac/ftccomp/data/team_data/10273.csv', '/Volumes/mac/ftccomp/data/team_data/10274.csv', '/Volumes/mac/ftccomp/data/team_data/10276.csv', '/Volumes/mac/ftccomp/data/team_data/10280.csv', '/Volumes/mac/ftccomp/data/team_data/10284.csv', '/Volumes/mac/ftccomp/data/team_data/10293.csv', '/Volumes/mac/ftccomp/data/team_data/10297.csv', '/Volumes/mac/ftccomp/data/team_data/10298.csv', '/Volumes/mac/ftccomp/data/team_data/10303.csv', '/Volumes/mac/ftccomp/data/team_data/10309.csv', '/Volumes/mac/ftccomp/data/team_data/10320.csv', '/Volumes/mac/ftccomp/data/team_data/10331.csv', '/Volumes/mac/ftccomp/data/team_data/10332.csv', '/Volumes/mac/ftccomp/data/team_data/10333.csv', '/Volumes/mac/ftccomp/data/team_data/10343.csv', '/Volumes/mac/ftccomp/data/team_data/10348.csv', '/Volumes/mac/ftccomp/data/team_data/10353.csv', '/Volumes/mac/ftccomp/data/team_data/10354.csv', '/Volumes/mac/ftccomp/data/team_data/10355.csv', '/Volumes/mac/ftccomp/data/team_data/10358.csv', '/Volumes/mac/ftccomp/data/team_data/10366.csv', '/Volumes/mac/ftccomp/data/team_data/10368.csv', '/Volumes/mac/ftccomp/data/team_data/10369.csv', '/Volumes/mac/ftccomp/data/team_data/10373.csv', '/Volumes/mac/ftccomp/data/team_data/10383.csv', '/Volumes/mac/ftccomp/data/team_data/10391.csv', '/Volumes/mac/ftccomp/data/team_data/10392.csv', '/Volumes/mac/ftccomp/data/team_data/10393.csv', '/Volumes/mac/ftccomp/data/team_data/10405.csv', '/Volumes/mac/ftccomp/data/team_data/10415.csv', '/Volumes/mac/ftccomp/data/team_data/10420.csv', '/Volumes/mac/ftccomp/data/team_data/10421.csv', '/Volumes/mac/ftccomp/data/team_data/10428.csv', '/Volumes/mac/ftccomp/data/team_data/10430.csv', '/Volumes/mac/ftccomp/data/team_data/10435.csv', '/Volumes/mac/ftccomp/data/team_data/10437.csv', '/Volumes/mac/ftccomp/data/team_data/10442.csv', '/Volumes/mac/ftccomp/data/team_data/10448.csv', '/Volumes/mac/ftccomp/data/team_data/10452.csv', '/Volumes/mac/ftccomp/data/team_data/10455.csv', '/Volumes/mac/ftccomp/data/team_data/10458.csv', '/Volumes/mac/ftccomp/data/team_data/10464.csv', '/Volumes/mac/ftccomp/data/team_data/10466.csv', '/Volumes/mac/ftccomp/data/team_data/10468.csv', '/Volumes/mac/ftccomp/data/team_data/10470.csv', '/Volumes/mac/ftccomp/data/team_data/10472.csv', '/Volumes/mac/ftccomp/data/team_data/10474.csv', '/Volumes/mac/ftccomp/data/team_data/10475.csv', '/Volumes/mac/ftccomp/data/team_data/10477.csv', '/Volumes/mac/ftccomp/data/team_data/10484.csv', '/Volumes/mac/ftccomp/data/team_data/10505.csv', '/Volumes/mac/ftccomp/data/team_data/10515.csv', '/Volumes/mac/ftccomp/data/team_data/10518.csv', '/Volumes/mac/ftccomp/data/team_data/10523.csv', '/Volumes/mac/ftccomp/data/team_data/10526.csv', '/Volumes/mac/ftccomp/data/team_data/10528.csv', '/Volumes/mac/ftccomp/data/team_data/10529.csv', '/Volumes/mac/ftccomp/data/team_data/10531.csv', '/Volumes/mac/ftccomp/data/team_data/10533.csv', '/Volumes/mac/ftccomp/data/team_data/10537.csv', '/Volumes/mac/ftccomp/data/team_data/10538.csv', '/Volumes/mac/ftccomp/data/team_data/10539.csv', '/Volumes/mac/ftccomp/data/team_data/10540.csv', '/Volumes/mac/ftccomp/data/team_data/10544.csv', '/Volumes/mac/ftccomp/data/team_data/10548.csv', '/Volumes/mac/ftccomp/data/team_data/10552.csv', '/Volumes/mac/ftccomp/data/team_data/10553.csv', '/Volumes/mac/ftccomp/data/team_data/10560.csv', '/Volumes/mac/ftccomp/data/team_data/10577.csv', '/Volumes/mac/ftccomp/data/team_data/10582.csv', '/Volumes/mac/ftccomp/data/team_data/10583.csv', '/Volumes/mac/ftccomp/data/team_data/10584.csv', '/Volumes/mac/ftccomp/data/team_data/10588.csv', '/Volumes/mac/ftccomp/data/team_data/10599.csv', '/Volumes/mac/ftccomp/data/team_data/10601.csv', '/Volumes/mac/ftccomp/data/team_data/10602.csv', '/Volumes/mac/ftccomp/data/team_data/10603.csv', '/Volumes/mac/ftccomp/data/team_data/10615.csv', '/Volumes/mac/ftccomp/data/team_data/10617.csv', '/Volumes/mac/ftccomp/data/team_data/10621.csv', '/Volumes/mac/ftccomp/data/team_data/10630.csv', '/Volumes/mac/ftccomp/data/team_data/10632.csv', '/Volumes/mac/ftccomp/data/team_data/10635.csv', '/Volumes/mac/ftccomp/data/team_data/10639.csv', '/Volumes/mac/ftccomp/data/team_data/10644.csv', '/Volumes/mac/ftccomp/data/team_data/10645.csv', '/Volumes/mac/ftccomp/data/team_data/10650.csv', '/Volumes/mac/ftccomp/data/team_data/10653.csv', '/Volumes/mac/ftccomp/data/team_data/10656.csv', '/Volumes/mac/ftccomp/data/team_data/10660.csv', '/Volumes/mac/ftccomp/data/team_data/10662.csv', '/Volumes/mac/ftccomp/data/team_data/10669.csv', '/Volumes/mac/ftccomp/data/team_data/10673.csv', '/Volumes/mac/ftccomp/data/team_data/10676.csv', '/Volumes/mac/ftccomp/data/team_data/10695.csv', '/Volumes/mac/ftccomp/data/team_data/10696.csv', '/Volumes/mac/ftccomp/data/team_data/10698.csv', '/Volumes/mac/ftccomp/data/team_data/10703.csv', '/Volumes/mac/ftccomp/data/team_data/10719.csv', '/Volumes/mac/ftccomp/data/team_data/10721.csv', '/Volumes/mac/ftccomp/data/team_data/10723.csv', '/Volumes/mac/ftccomp/data/team_data/10731.csv', '/Volumes/mac/ftccomp/data/team_data/10735.csv', '/Volumes/mac/ftccomp/data/team_data/10738.csv', '/Volumes/mac/ftccomp/data/team_data/10752.csv', '/Volumes/mac/ftccomp/data/team_data/10755.csv', '/Volumes/mac/ftccomp/data/team_data/10760.csv', '/Volumes/mac/ftccomp/data/team_data/10768.csv', '/Volumes/mac/ftccomp/data/team_data/10771.csv', '/Volumes/mac/ftccomp/data/team_data/10773.csv', '/Volumes/mac/ftccomp/data/team_data/10776.csv', '/Volumes/mac/ftccomp/data/team_data/10779.csv', '/Volumes/mac/ftccomp/data/team_data/10785.csv', '/Volumes/mac/ftccomp/data/team_data/10788.csv', '/Volumes/mac/ftccomp/data/team_data/10789.csv', '/Volumes/mac/ftccomp/data/team_data/10793.csv', '/Volumes/mac/ftccomp/data/team_data/10798.csv', '/Volumes/mac/ftccomp/data/team_data/10802.csv', '/Volumes/mac/ftccomp/data/team_data/10803.csv', '/Volumes/mac/ftccomp/data/team_data/10805.csv', '/Volumes/mac/ftccomp/data/team_data/10809.csv', '/Volumes/mac/ftccomp/data/team_data/10812.csv', '/Volumes/mac/ftccomp/data/team_data/10818.csv', '/Volumes/mac/ftccomp/data/team_data/10820.csv', '/Volumes/mac/ftccomp/data/team_data/10824.csv', '/Volumes/mac/ftccomp/data/team_data/10829.csv', '/Volumes/mac/ftccomp/data/team_data/10830.csv', '/Volumes/mac/ftccomp/data/team_data/10836.csv', '/Volumes/mac/ftccomp/data/team_data/10844.csv', '/Volumes/mac/ftccomp/data/team_data/10847.csv', '/Volumes/mac/ftccomp/data/team_data/10851.csv', '/Volumes/mac/ftccomp/data/team_data/10860.csv', '/Volumes/mac/ftccomp/data/team_data/10861.csv', '/Volumes/mac/ftccomp/data/team_data/10862.csv', '/Volumes/mac/ftccomp/data/team_data/10868.csv', '/Volumes/mac/ftccomp/data/team_data/10870.csv', '/Volumes/mac/ftccomp/data/team_data/10874.csv', '/Volumes/mac/ftccomp/data/team_data/10899.csv', '/Volumes/mac/ftccomp/data/team_data/10902.csv', '/Volumes/mac/ftccomp/data/team_data/10908.csv', '/Volumes/mac/ftccomp/data/team_data/10918.csv', '/Volumes/mac/ftccomp/data/team_data/10921.csv', '/Volumes/mac/ftccomp/data/team_data/10936.csv', '/Volumes/mac/ftccomp/data/team_data/10937.csv', '/Volumes/mac/ftccomp/data/team_data/10938.csv', '/Volumes/mac/ftccomp/data/team_data/10939.csv', '/Volumes/mac/ftccomp/data/team_data/10941.csv', '/Volumes/mac/ftccomp/data/team_data/10949.csv', '/Volumes/mac/ftccomp/data/team_data/10956.csv', '/Volumes/mac/ftccomp/data/team_data/10963.csv', '/Volumes/mac/ftccomp/data/team_data/10971.csv', '/Volumes/mac/ftccomp/data/team_data/10973.csv', '/Volumes/mac/ftccomp/data/team_data/10974.csv', '/Volumes/mac/ftccomp/data/team_data/10975.csv', '/Volumes/mac/ftccomp/data/team_data/10984.csv', '/Volumes/mac/ftccomp/data/team_data/11000.csv', '/Volumes/mac/ftccomp/data/team_data/11002.csv', '/Volumes/mac/ftccomp/data/team_data/11004.csv', '/Volumes/mac/ftccomp/data/team_data/11009.csv', '/Volumes/mac/ftccomp/data/team_data/11020.csv', '/Volumes/mac/ftccomp/data/team_data/11030.csv', '/Volumes/mac/ftccomp/data/team_data/11039.csv', '/Volumes/mac/ftccomp/data/team_data/11047.csv', '/Volumes/mac/ftccomp/data/team_data/11085.csv', '/Volumes/mac/ftccomp/data/team_data/11093.csv', '/Volumes/mac/ftccomp/data/team_data/11099.csv', '/Volumes/mac/ftccomp/data/team_data/11102.csv', '/Volumes/mac/ftccomp/data/team_data/11109.csv', '/Volumes/mac/ftccomp/data/team_data/11112.csv', '/Volumes/mac/ftccomp/data/team_data/11117.csv', '/Volumes/mac/ftccomp/data/team_data/11124.csv', '/Volumes/mac/ftccomp/data/team_data/11127.csv', '/Volumes/mac/ftccomp/data/team_data/11128.csv', '/Volumes/mac/ftccomp/data/team_data/11129.csv', '/Volumes/mac/ftccomp/data/team_data/11130.csv', '/Volumes/mac/ftccomp/data/team_data/11132.csv', '/Volumes/mac/ftccomp/data/team_data/11138.csv', '/Volumes/mac/ftccomp/data/team_data/11139.csv', '/Volumes/mac/ftccomp/data/team_data/11140.csv', '/Volumes/mac/ftccomp/data/team_data/11142.csv', '/Volumes/mac/ftccomp/data/team_data/11144.csv', '/Volumes/mac/ftccomp/data/team_data/11145.csv', '/Volumes/mac/ftccomp/data/team_data/11146.csv', '/Volumes/mac/ftccomp/data/team_data/11147.csv', '/Volumes/mac/ftccomp/data/team_data/11148.csv', '/Volumes/mac/ftccomp/data/team_data/11156.csv', '/Volumes/mac/ftccomp/data/team_data/11158.csv', '/Volumes/mac/ftccomp/data/team_data/11159.csv', '/Volumes/mac/ftccomp/data/team_data/11161.csv', '/Volumes/mac/ftccomp/data/team_data/11166.csv', '/Volumes/mac/ftccomp/data/team_data/11172.csv', '/Volumes/mac/ftccomp/data/team_data/11175.csv', '/Volumes/mac/ftccomp/data/team_data/11177.csv', '/Volumes/mac/ftccomp/data/team_data/11180.csv', '/Volumes/mac/ftccomp/data/team_data/11181.csv', '/Volumes/mac/ftccomp/data/team_data/11183.csv', '/Volumes/mac/ftccomp/data/team_data/11186.csv', '/Volumes/mac/ftccomp/data/team_data/11187.csv', '/Volumes/mac/ftccomp/data/team_data/11191.csv', '/Volumes/mac/ftccomp/data/team_data/11192.csv', '/Volumes/mac/ftccomp/data/team_data/11193.csv', '/Volumes/mac/ftccomp/data/team_data/112.csv', '/Volumes/mac/ftccomp/data/team_data/11200.csv', '/Volumes/mac/ftccomp/data/team_data/11201.csv', '/Volumes/mac/ftccomp/data/team_data/11203.csv', '/Volumes/mac/ftccomp/data/team_data/11204.csv', '/Volumes/mac/ftccomp/data/team_data/11205.csv', '/Volumes/mac/ftccomp/data/team_data/11206.csv', '/Volumes/mac/ftccomp/data/team_data/11208.csv', '/Volumes/mac/ftccomp/data/team_data/11211.csv', '/Volumes/mac/ftccomp/data/team_data/11212.csv', '/Volumes/mac/ftccomp/data/team_data/11225.csv', '/Volumes/mac/ftccomp/data/team_data/11226.csv', '/Volumes/mac/ftccomp/data/team_data/11228.csv', '/Volumes/mac/ftccomp/data/team_data/11231.csv', '/Volumes/mac/ftccomp/data/team_data/11235.csv', '/Volumes/mac/ftccomp/data/team_data/11240.csv', '/Volumes/mac/ftccomp/data/team_data/11241.csv', '/Volumes/mac/ftccomp/data/team_data/11244.csv', '/Volumes/mac/ftccomp/data/team_data/11245.csv', '/Volumes/mac/ftccomp/data/team_data/11246.csv', '/Volumes/mac/ftccomp/data/team_data/11248.csv', '/Volumes/mac/ftccomp/data/team_data/11254.csv', '/Volumes/mac/ftccomp/data/team_data/11258.csv', '/Volumes/mac/ftccomp/data/team_data/11260.csv', '/Volumes/mac/ftccomp/data/team_data/11262.csv', '/Volumes/mac/ftccomp/data/team_data/11266.csv', '/Volumes/mac/ftccomp/data/team_data/11270.csv', '/Volumes/mac/ftccomp/data/team_data/11272.csv', '/Volumes/mac/ftccomp/data/team_data/11276.csv', '/Volumes/mac/ftccomp/data/team_data/11279.csv', '/Volumes/mac/ftccomp/data/team_data/11285.csv', '/Volumes/mac/ftccomp/data/team_data/11304.csv', '/Volumes/mac/ftccomp/data/team_data/11308.csv', '/Volumes/mac/ftccomp/data/team_data/11311.csv', '/Volumes/mac/ftccomp/data/team_data/11312.csv', '/Volumes/mac/ftccomp/data/team_data/11317.csv', '/Volumes/mac/ftccomp/data/team_data/11319.csv', '/Volumes/mac/ftccomp/data/team_data/11322.csv', '/Volumes/mac/ftccomp/data/team_data/11323.csv', '/Volumes/mac/ftccomp/data/team_data/11329.csv', '/Volumes/mac/ftccomp/data/team_data/11332.csv', '/Volumes/mac/ftccomp/data/team_data/11333.csv', '/Volumes/mac/ftccomp/data/team_data/11334.csv', '/Volumes/mac/ftccomp/data/team_data/11335.csv', '/Volumes/mac/ftccomp/data/team_data/11336.csv', '/Volumes/mac/ftccomp/data/team_data/11337.csv', '/Volumes/mac/ftccomp/data/team_data/11338.csv', '/Volumes/mac/ftccomp/data/team_data/11339.csv', '/Volumes/mac/ftccomp/data/team_data/11341.csv', '/Volumes/mac/ftccomp/data/team_data/11344.csv', '/Volumes/mac/ftccomp/data/team_data/11347.csv', '/Volumes/mac/ftccomp/data/team_data/11349.csv', '/Volumes/mac/ftccomp/data/team_data/11353.csv', '/Volumes/mac/ftccomp/data/team_data/11354.csv', '/Volumes/mac/ftccomp/data/team_data/11359.csv', '/Volumes/mac/ftccomp/data/team_data/11364.csv', '/Volumes/mac/ftccomp/data/team_data/11365.csv', '/Volumes/mac/ftccomp/data/team_data/11379.csv', '/Volumes/mac/ftccomp/data/team_data/11380.csv', '/Volumes/mac/ftccomp/data/team_data/11382.csv', '/Volumes/mac/ftccomp/data/team_data/11384.csv', '/Volumes/mac/ftccomp/data/team_data/11385.csv', '/Volumes/mac/ftccomp/data/team_data/11386.csv', '/Volumes/mac/ftccomp/data/team_data/11392.csv', '/Volumes/mac/ftccomp/data/team_data/11393.csv', '/Volumes/mac/ftccomp/data/team_data/11396.csv', '/Volumes/mac/ftccomp/data/team_data/11409.csv', '/Volumes/mac/ftccomp/data/team_data/11412.csv', '/Volumes/mac/ftccomp/data/team_data/11413.csv', '/Volumes/mac/ftccomp/data/team_data/11418.csv', '/Volumes/mac/ftccomp/data/team_data/11419.csv', '/Volumes/mac/ftccomp/data/team_data/11424.csv', '/Volumes/mac/ftccomp/data/team_data/11425.csv', '/Volumes/mac/ftccomp/data/team_data/11434.csv', '/Volumes/mac/ftccomp/data/team_data/11441.csv', '/Volumes/mac/ftccomp/data/team_data/11443.csv', '/Volumes/mac/ftccomp/data/team_data/11444.csv', '/Volumes/mac/ftccomp/data/team_data/11450.csv', '/Volumes/mac/ftccomp/data/team_data/11453.csv', '/Volumes/mac/ftccomp/data/team_data/11454.csv', '/Volumes/mac/ftccomp/data/team_data/11455.csv', '/Volumes/mac/ftccomp/data/team_data/11456.csv', '/Volumes/mac/ftccomp/data/team_data/11457.csv', '/Volumes/mac/ftccomp/data/team_data/11460.csv', '/Volumes/mac/ftccomp/data/team_data/11468.csv', '/Volumes/mac/ftccomp/data/team_data/11472.csv', '/Volumes/mac/ftccomp/data/team_data/11487.csv', '/Volumes/mac/ftccomp/data/team_data/11493.csv', '/Volumes/mac/ftccomp/data/team_data/11500.csv', '/Volumes/mac/ftccomp/data/team_data/11503.csv', '/Volumes/mac/ftccomp/data/team_data/11505.csv', '/Volumes/mac/ftccomp/data/team_data/11506.csv', '/Volumes/mac/ftccomp/data/team_data/11511.csv', '/Volumes/mac/ftccomp/data/team_data/11514.csv', '/Volumes/mac/ftccomp/data/team_data/11520.csv', '/Volumes/mac/ftccomp/data/team_data/11525.csv', '/Volumes/mac/ftccomp/data/team_data/11526.csv', '/Volumes/mac/ftccomp/data/team_data/11528.csv', '/Volumes/mac/ftccomp/data/team_data/11531.csv', '/Volumes/mac/ftccomp/data/team_data/11534.csv', '/Volumes/mac/ftccomp/data/team_data/11536.csv', '/Volumes/mac/ftccomp/data/team_data/11539.csv', '/Volumes/mac/ftccomp/data/team_data/11542.csv', '/Volumes/mac/ftccomp/data/team_data/11545.csv', '/Volumes/mac/ftccomp/data/team_data/11546.csv', '/Volumes/mac/ftccomp/data/team_data/11547.csv', '/Volumes/mac/ftccomp/data/team_data/11556.csv', '/Volumes/mac/ftccomp/data/team_data/11561.csv', '/Volumes/mac/ftccomp/data/team_data/11562.csv', '/Volumes/mac/ftccomp/data/team_data/11563.csv', '/Volumes/mac/ftccomp/data/team_data/11567.csv', '/Volumes/mac/ftccomp/data/team_data/11570.csv', '/Volumes/mac/ftccomp/data/team_data/11572.csv', '/Volumes/mac/ftccomp/data/team_data/11574.csv', '/Volumes/mac/ftccomp/data/team_data/11580.csv', '/Volumes/mac/ftccomp/data/team_data/11582.csv', '/Volumes/mac/ftccomp/data/team_data/11586.csv', '/Volumes/mac/ftccomp/data/team_data/11588.csv', '/Volumes/mac/ftccomp/data/team_data/11591.csv', '/Volumes/mac/ftccomp/data/team_data/11607.csv', '/Volumes/mac/ftccomp/data/team_data/11608.csv', '/Volumes/mac/ftccomp/data/team_data/11609.csv', '/Volumes/mac/ftccomp/data/team_data/11612.csv', '/Volumes/mac/ftccomp/data/team_data/11613.csv', '/Volumes/mac/ftccomp/data/team_data/11616.csv', '/Volumes/mac/ftccomp/data/team_data/11617.csv', '/Volumes/mac/ftccomp/data/team_data/11618.csv', '/Volumes/mac/ftccomp/data/team_data/11619.csv', '/Volumes/mac/ftccomp/data/team_data/11635.csv', '/Volumes/mac/ftccomp/data/team_data/11649.csv', '/Volumes/mac/ftccomp/data/team_data/11659.csv', '/Volumes/mac/ftccomp/data/team_data/11665.csv', '/Volumes/mac/ftccomp/data/team_data/11676.csv', '/Volumes/mac/ftccomp/data/team_data/11678.csv', '/Volumes/mac/ftccomp/data/team_data/11684.csv', '/Volumes/mac/f

In [27]:
for path in glob.glob(os.getcwd().replace('scripts', 'data')+'/team_data/*'):
# for i in range(1):
#     path = os.getcwd().replace('scripts', 'data')+'/team_data/3763.csv'
    print(path)
    df = pd.read_csv(path)
    
    move = df[df['ID'].str.contains('FTCCMP')]
    
    print(move)
        
#     print(df.index)
    
    if move.shape[0] > 1:
        print("BROKEN")
        break
    if move.shape[0] > 0:
#         print(move)
#         print(move.iloc[0].index)
        df = df[~df['ID'].str.contains('FTCCMP')].reset_index(drop = True)
        
        df.loc[len(df.index)] = move.iloc[0]
        
#         os.rmdir(path)
        df.to_csv(path, index = False)

/Volumes/mac/ftccomp/data/team_data/1.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10001.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10006.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/1001.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10016.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/1002.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1OCHO  129.257  36.901  31.438
/Volumes/mac/ftccomp/data/team_data/10021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10023.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10024.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10068.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10082.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10095.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10098.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10101.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1FRAN  105.126  20.098  21.254
/Volumes/mac/ftccomp/data/team_data/10104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10107.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10111.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10123.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10127.csv
            ID      OPR    Auto    CCWM
4  FTCCMP1OCHO  102.406  30.617  23.417
/Volumes/mac/ftccomp/data/team_data/10130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10132.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10136.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10137.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10138.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10143.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10173.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10179.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10185.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10195.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10210.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10211.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10219.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10243.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10262.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10265.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1FRAN  66.414  16.521 -15.245
/Volumes/mac/ftccomp/data/team_data/10273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10274.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10293.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10331.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10348.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10355.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1OCHO  120.061  25.931  35.453
/Volumes/mac/ftccomp/data/team_data/10358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10369.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10391.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1OCHO  91.078  12.391  25.732
/Volumes/mac/ftccomp/data/team_data/10392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10405.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10428.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10430.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10435.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10437.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10452.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10455.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10464.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10468.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10470.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10477.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1JEMI  78.235  22.512 -8.557
/Volumes/mac/ftccomp/data/team_data/10484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10528.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10529.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10538.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10540.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10544.csv
            ID      OPR   Auto    CCWM
5  FTCCMP1FRAN  134.014  48.41  75.532
/Volumes/mac/ftccomp/data/team_data/10548.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10552.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10577.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10583.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10599.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10602.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10615.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10632.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10635.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10639.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10644.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10645.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10653.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10660.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10696.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10698.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10723.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10752.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10771.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10773.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10779.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10789.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10805.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10809.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10820.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10824.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10836.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10851.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10860.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10868.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10870.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10874.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10902.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10918.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10937.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10938.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10939.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10941.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10949.csv
            ID     OPR    Auto   CCWM
3  FTCCMP1JEMI  94.492  26.407 -3.229
/Volumes/mac/ftccomp/data/team_data/10956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10963.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10974.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/10984.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11004.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11030.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11047.csv
            ID     OPR   Auto   CCWM
1  FTCCMP1EDIS  109.37  31.61  47.98
/Volumes/mac/ftccomp/data/team_data/11085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11112.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11124.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11128.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11129.csv
            ID     OPR   Auto  CCWM
2  FTCCMP1FRAN  98.097  37.58 -11.0
/Volumes/mac/ftccomp/data/team_data/11130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11132.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11138.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11144.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11146.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11148.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11159.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11166.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11172.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11191.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11192.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/112.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11211.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11212.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11225.csv
            ID     OPR  Auto    CCWM
3  FTCCMP1EDIS  79.624  23.3 -38.591
/Volumes/mac/ftccomp/data/team_data/11226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11240.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11241.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11248.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11260.csv
            ID      OPR   Auto    CCWM
3  FTCCMP1JEMI  133.902  46.44  48.172
/Volumes/mac/ftccomp/data/team_data/11262.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11279.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11285.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11308.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11312.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11317.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11319.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11329.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11334.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11336.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11386.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11396.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11409.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11412.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11425.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11434.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11441.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11443.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11454.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11455.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11456.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11457.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11468.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1JEMI  59.961  22.005 -25.003
/Volumes/mac/ftccomp/data/team_data/11472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11493.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11500.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11503.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11511.csv
            ID     OPR    Auto   CCWM
1  FTCCMP1EDIS  86.149  27.225 -3.902
/Volumes/mac/ftccomp/data/team_data/11514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11520.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11528.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11534.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11536.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11545.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11546.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11547.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11561.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11562.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11570.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11572.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11574.csv
            ID     OPR   Auto    CCWM
6  FTCCMP1OCHO  41.312  8.614 -62.717
/Volumes/mac/ftccomp/data/team_data/11580.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11586.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11591.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11608.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11612.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11613.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11616.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11618.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11619.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11635.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11649.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11659.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11665.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11678.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11684.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11691.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11697.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11706.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11712.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11720.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11723.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11729.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11752.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11770.csv
            ID     OPR    Auto   CCWM
6  FTCCMP1JEMI  87.615  26.408  9.132
/Volumes/mac/ftccomp/data/team_data/11774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11780.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1FRAN  73.485  10.085 -15.572
/Volumes/mac/ftccomp/data/team_data/11781.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11794.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11822.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11841.csv
            ID    OPR    Auto   CCWM
3  FTCCMP1FRAN  68.55  15.932 -2.693
/Volumes/mac/ftccomp/data/team_data/11846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11873.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11890.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11902.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11918.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11920.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11924.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11940.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11947.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11970.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11980.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11986.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11992.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/11999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12005.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12016.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12111.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12114.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12134.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12166.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12179.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12195.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12211.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12241.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12275.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12308.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12313.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12331.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12365.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12398.csv
            ID     OPR   Auto    CCWM
9  FTCCMP1FRAN  70.523  6.446 -39.414
/Volumes/mac/ftccomp/data/team_data/12399.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/124.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12414.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12427.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12430.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12441.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12456.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12459.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12463.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12488.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12492.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12494.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12513.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12517.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12548.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12554.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12565.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12566.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12576.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12578.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12585.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12589.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12591.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12599.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1EDIS  148.993  46.931  60.174
/Volumes/mac/ftccomp/data/team_data/12600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12611.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12632.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12635.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1FRAN  83.167  25.321 -11.623
/Volumes/mac/ftccomp/data/team_data/12636.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12649.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12651.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12655.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12660.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12675.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12694.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12696.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12718.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12722.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12744.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12758.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12761.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12765.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12767.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12777.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12791.csv
             ID     OPR    Auto    CCWM
11  FTCCMP1EDIS  87.527  31.279 -18.301
/Volumes/mac/ftccomp/data/team_data/12792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12797.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12806.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12817.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12820.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12833.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12841.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12845.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12857.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12863.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12864.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12868.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12869.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12870.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12875.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12880.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12887.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1JEMI  96.383  30.131 -6.104
/Volumes/mac/ftccomp/data/team_data/12888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12890.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12915.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12926.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12927.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12928.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12961.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12966.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12974.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12977.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12991.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12993.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1FRAN  153.773  47.784  92.884
/Volumes/mac/ftccomp/data/team_data/12995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/12999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13003.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13019.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13046.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13048.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13073.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13089.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13107.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13108.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13132.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13141.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13146.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13171.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13172.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13181.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1JEMI  74.325  16.597 -35.144
/Volumes/mac/ftccomp/data/team_data/13186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13190.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13196.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13233.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13234.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13249.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13263.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13269.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13274.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13293.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13312.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13329.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13334.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13348.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13356.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13399.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13402.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13414.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13416.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13435.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13452.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13459.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13462.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13463.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13467.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13480.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13510.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13512.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13534.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13540.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13546.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13550.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13552.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13570.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13580.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13586.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13590.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13594.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13598.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13599.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13615.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13620.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13643.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13647.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13648.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13675.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13684.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13688.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13702.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13744.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13747.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13749.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13781.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13805.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13806.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13822.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13833.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13879.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13893.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13909.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13910.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13948.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13970.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13981.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13991.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/13999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14001.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14003.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14005.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14007.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14010.csv
            ID     OPR   Auto    CCWM
2  FTCCMP1OCHO  73.028  14.95 -54.635
/Volumes/mac/ftccomp/data/team_data/14015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14018.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14023.csv
            ID     OPR   Auto    CCWM
3  FTCCMP1JEMI  53.975  12.17 -46.021
/Volumes/mac/ftccomp/data/team_data/14026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14129.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14134.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14140.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1JEMI  109.713  36.691  44.077
/Volumes/mac/ftccomp/data/team_data/14144.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14162.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14165.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14172.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14179.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14195.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14199.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14204.csv

            ID      OPR    Auto    CCWM
5  FTCCMP1OCHO  121.409  31.592  11.262
/Volumes/mac/ftccomp/data/team_data/14212.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1JEMI  125.095  31.626  63.505
/Volumes/mac/ftccomp/data/team_data/14213.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14214.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14236.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14257.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14259.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14261.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14279.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14315.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14316.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14318.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14349.csv
            ID      OPR    Auto  CCWM
3  FTCCMP1EDIS  108.883  35.045 -5.69
/Volumes/mac/ftccomp/data/team_data/14353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14361.csv
             ID      OPR    Auto    CCWM
10  FTCCMP1JEMI  139.155  44.635  65.913
/Volumes/mac/ftccomp/data/team_data/14363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14374.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1FRAN  71.975  12.479 -44.937
/Volumes/mac/ftccomp/data/team_data/14375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14380.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1JEMI  71.246  24.658 -22.518
/Volumes/mac/ftccomp/data/team_data/14381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14391.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14423.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1EDIS  74.277  20.815 -23.799
/Volumes/mac/ftccomp/data/team_data/14431.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14434.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14436.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1OCHO  91.247  19.331  12.561
/Volumes/mac/ftccomp/data/team_data/14442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14447.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14452.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14464.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14468.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14469.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14470.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14471.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14481.csv
            ID      OPR  Auto    CCWM
5  FTCCMP1EDIS  101.225  22.1  31.848
/Volumes/mac/ftccomp/data/team_data/14482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14493.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14496.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1OCHO  144.153  45.821  40.767
/Volumes/mac/ftccomp/data/team_data/14498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14503.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1JEMI  108.159  36.491  34.674
/Volumes/mac/ftccomp/data/team_data/14515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14521.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14525.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1EDIS  142.491  46.834  75.142

/Volumes/mac/ftccomp/data/team_data/14531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14544.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14561.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14568.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14575.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14579.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14586.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14590.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14608.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14614.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14623.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14631.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14639.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14644.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14649.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14659.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14664.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14671.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14675.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14683.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14690.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14691.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14694.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14706.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1EDIS  127.331  34.642  29.806
/Volumes/mac/ftccomp/data/team_data/14707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14711.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14712.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14716.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14718.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14723.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14725.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14739.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14742.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14756.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14757.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14765.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14771.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14773.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14779.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1OCHO  67.713  13.242 -28.363
/Volumes/mac/ftccomp/data/team_data/14785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14800.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14821.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14822.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14825.csv
            ID     OPR    Auto   CCWM
5  FTCCMP1EDIS  87.584  13.645  1.122
/Volumes/mac/ftccomp/data/team_data/14835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14840.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14841.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14842.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14849.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14850.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14863.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14864.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14869.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14872.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14875.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14876.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14903.csv
            ID     OPR   Auto   CCWM
3  FTCCMP1FRAN  80.578  17.15  9.639
/Volumes/mac/ftccomp/data/team_data/14904.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14905.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14913.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14914.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14919.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14931.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14933.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14937.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14938.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14939.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14941.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14946.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14952.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14953.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14963.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14976.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/14996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15004.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15005.csv
            ID    OPR    Auto    CCWM
5  FTCCMP1EDIS  90.21  16.619 -20.784
/Volumes/mac/ftccomp/data/team_data/15006.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1FRAN  119.61  41.023  18.075
/Volumes/mac/ftccomp/data/team_data/15008.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15024.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15036.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15046.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15059.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15065.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15071.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15078.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15083.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15089.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15117.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15135.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15141.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15144.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15146.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15157.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15159.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15171.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15173.csv
            ID     OPR    Auto    CCWM
6  FTCCMP1JEMI  69.606  25.356 -45.974
/Volumes/mac/ftccomp/data/team_data/15182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15210.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15229.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15236.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15256.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15259.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15289.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15301.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15308.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15317.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15342.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1JEMI  84.447  21.744 -11.575
/Volumes/mac/ftccomp/data/team_data/15343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15356.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15369.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15372.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15374.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15382.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15399.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15411.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15425.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15447.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15455.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15465.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15469.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15471.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15485.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15486.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15492.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15493.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15500.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15504.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15522.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15534.csv
            ID      OPR    Auto   CCWM
3  FTCCMP1JEMI  120.443  34.093  37.07
/Volumes/mac/ftccomp/data/team_data/15546.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15547.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15550.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15555.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15562.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15580.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15583.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15589.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15637.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1EDIS  133.671  34.747  64.388
/Volumes/mac/ftccomp/data/team_data/15638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15639.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15643.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15654.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15655.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15672.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15677.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15680.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15725.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15726.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15747.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15749.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15758.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15770.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15773.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15809.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15814.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15858.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15877.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15878.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15891.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15903.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15909.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15930.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15931.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15966.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15972.csv
            ID      OPR    Auto    CCWM
3  FTCCMP1OCHO  129.366  41.908  31.611
/Volumes/mac/ftccomp/data/team_data/15975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/15996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16001.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16008.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1OCHO  100.948  25.068  34.044
/Volumes/mac/ftccomp/data/team_data/16010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16038.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16041.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16043.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16044.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16049.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16067.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16090.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16091.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1FRAN  85.596  24.394 -24.073
/Volumes/mac/ftccomp/data/team_data/16096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16113.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16151.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16158.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1EDIS  132.293  42.488  66.273
/Volumes/mac/ftccomp/data/team_data/16162.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16163.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16166.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16179.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16192.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16195.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16207.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16212.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/1622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16220.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16222.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16225.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16232.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16234.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16236.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1FRAN  143.608  43.936  63.337
/Volumes/mac/ftccomp/data/team_data/16244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16249.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16250.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16267.csv
            ID     OPR   Auto   CCWM
4  FTCCMP1EDIS  88.802  35.02 -9.755
/Volumes/mac/ftccomp/data/team_data/16269.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16283.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16287.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16290.csv
            ID     OPR    Auto    CCWM
6  FTCCMP1OCHO  61.034  18.541 -23.617
/Volumes/mac/ftccomp/data/team_data/16292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16306.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16312.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16313.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16328.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16345.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16346.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16355.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16369.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16374.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16377.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1OCHO  102.492  24.495  24.538
/Volumes/mac/ftccomp/data/team_data/16379.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1FRAN  79.749  20.683 -23.294
/Volumes/mac/ftccomp/data/team_data/16382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16391.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16399.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16400.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16402.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16405.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16407.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16409.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16410.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1JEMI  84.403  21.531 -11.287
/Volumes/mac/ftccomp/data/team_data/16412.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16414.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16417.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1JEMI  136.56  48.739  27.201
/Volumes/mac/ftccomp/data/team_data/16418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16433.csv
            ID     OPR   Auto    CCWM
4  FTCCMP1FRAN  75.629  7.811 -22.738
/Volumes/mac/ftccomp/data/team_data/16436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16441.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1EDIS  68.056  15.535 -19.88
/Volumes/mac/ftccomp/data/team_data/16447.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16449.csv
            ID      OPR   Auto   CCWM
5  FTCCMP1EDIS  125.952  31.93  1.464
/Volumes/mac/ftccomp/data/team_data/16451.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16458.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1OCHO  119.865  38.319  56.578
/Volumes/mac/ftccomp/data/team_data/16460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16461.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1EDIS  67.841  16.114 -11.632
/Volumes/mac/ftccomp/data/team_data/16465.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16468.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16476.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16481.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16488.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16489.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16492.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16494.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16501.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16502.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16503.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16504.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16508.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16536.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16544.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16555.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16557.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16564.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16568.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16585.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16595.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16598.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16605.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16610.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16629.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16631.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16632.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16633.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16643.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16646.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16647.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16651.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16655.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16660.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16664.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16671.csv
            ID     OPR    Auto   CCWM
2  FTCCMP1JEMI  75.618  23.415 -5.801
/Volumes/mac/ftccomp/data/team_data/16685.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16688.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16700.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16704.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16716.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16720.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16724.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16726.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16742.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16749.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16751.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16756.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16757.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16764.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16771.csv
            ID     OPR   Auto    CCWM
1  FTCCMP1FRAN  39.608  9.488 -50.743
/Volumes/mac/ftccomp/data/team_data/16773.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16786.csv
            ID     OPR   Auto    CCWM
1  FTCCMP1EDIS  51.381  14.24 -65.163
/Volumes/mac/ftccomp/data/team_data/16788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16795.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16800.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16806.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16816.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16817.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16831.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16832.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16837.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16839.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16840.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16842.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16843.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16849.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16850.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16864.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16898.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16903.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16909.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16910.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16911.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16912.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16922.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16927.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16930.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16932.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16938.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16939.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16941.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16953.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16961.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16970.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16977.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16981.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/16989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17005.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17008.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17019.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17023.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17025.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17034.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17036.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17070.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17077.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17080.csv
            ID      OPR    Auto   CCWM
4  FTCCMP1JEMI  107.269  25.995 -3.254
/Volumes/mac/ftccomp/data/team_data/17082.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17089.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17108.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17111.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17113.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17114.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17127.csv
            ID      OPR    Auto   CCWM
2  FTCCMP1FRAN  117.442  26.799  25.43
/Volumes/mac/ftccomp/data/team_data/17133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17150.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17155.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17157.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17160.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17165.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17190.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17195.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17197.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17210.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17214.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17219.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17222.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17224.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17229.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17230.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17240.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17243.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17257.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17259.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17264.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17283.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17286.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17287.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17288.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17299.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17301.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17306.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17307.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17315.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17318.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17329.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17334.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17346.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17348.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17430.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17449.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17455.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17456.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17457.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17462.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17480.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17481.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17483.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17493.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17496.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17497.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17512.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17522.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17548.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17558.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17561.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17564.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17573.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17575.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17576.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17593.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17594.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17595.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17610.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17628.csv
            ID     OPR   Auto    CCWM
2  FTCCMP1OCHO  73.872  23.22 -30.715
/Volumes/mac/ftccomp/data/team_data/17630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17632.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17652.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17653.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17658.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17694.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17700.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17702.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17711.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17728.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17729.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17742.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17746.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17770.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17800.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17824.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17852.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17857.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17860.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17868.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17869.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17870.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17873.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17875.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17878.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17893.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17955.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17962.csv
            ID      OPR    Auto   CCWM
3  FTCCMP1JEMI  133.572  41.131  32.39
/Volumes/mac/ftccomp/data/team_data/17965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17977.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17980.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17986.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/17994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18003.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18030.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18061.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18065.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18071.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18082.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18095.csv
            ID     OPR   Auto    CCWM
2  FTCCMP1FRAN  46.095  8.966 -47.381
/Volumes/mac/ftccomp/data/team_data/18098.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18108.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18139.csv
            ID     OPR    Auto  CCWM
5  FTCCMP1EDIS  78.663  13.304  1.36
/Volumes/mac/ftccomp/data/team_data/18140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18151.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18160.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18172.csv
            ID     OPR   Auto   CCWM
6  FTCCMP1EDIS  77.957  9.875 -0.197
/Volumes/mac/ftccomp/data/team_data/18174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18185.csv
            ID     OPR   Auto   CCWM
2  FTCCMP1OCHO  82.362  19.83 -9.527
/Volumes/mac/ftccomp/data/team_data/18187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18211.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18224.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18225.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1JEMI  113.227  41.331  37.095
/Volumes/mac/ftccomp/data/team_data/18227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18230.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18233.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18236.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18240.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18241.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18248.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18249.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18260.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18263.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18264.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18268.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18270.csv
            ID      OPR    Auto    CCWM
8  FTCCMP1OCHO  132.395  48.595  38.476
/Volumes/mac/ftccomp/data/team_data/18271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18274.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18275.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18306.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18308.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18312.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18317.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1JEMI  98.762  28.601  14.292
/Volumes/mac/ftccomp/data/team_data/18318.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18340.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18341.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1FRAN  78.255  10.864 -28.55
/Volumes/mac/ftccomp/data/team_data/18351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18370.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18386.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18424.csv
            ID     OPR   Auto    CCWM
0  FTCCMP1FRAN  42.251  5.036 -47.237
/Volumes/mac/ftccomp/data/team_data/18425.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1FRAN  73.408  12.507 -20.728
/Volumes/mac/ftccomp/data/team_data/18429.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18432.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1OCHO  62.372  13.417 -42.498
/Volumes/mac/ftccomp/data/team_data/18433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18434.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18438.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1OCHO  157.064  43.693  91.711
/Volumes/mac/ftccomp/data/team_data/18442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18443.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18457.csv
            ID      OPR    Auto  CCWM
7  FTCCMP1EDIS  121.964  39.538  35.5
/Volumes/mac/ftccomp/data/team_data/18458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18463.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18464.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18483.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18489.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18492.csv
            ID     OPR   Auto    CCWM
2  FTCCMP1JEMI  60.259  6.211 -19.856
/Volumes/mac/ftccomp/data/team_data/18498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18500.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18503.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18504.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18527.csv
            ID      OPR    Auto   CCWM
7  FTCCMP1JEMI  101.391  27.874  8.978
/Volumes/mac/ftccomp/data/team_data/18529.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18538.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18552.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18554.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18555.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18557.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18562.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18568.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18570.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18571.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18575.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18577.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18589.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18599.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18602.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18611.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18613.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18616.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18619.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18629.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18634.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18649.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18658.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18660.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18664.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18671.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18672.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18686.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18698.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18700.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18739.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18747.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18749.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18754.csv
            ID     OPR    Auto  CCWM
3  FTCCMP1FRAN  94.454  31.969 -1.33
/Volumes/mac/ftccomp/data/team_data/18757.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18758.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18763.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1JEMI  84.778  18.682  22.763
/Volumes/mac/ftccomp/data/team_data/18766.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18773.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18809.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18810.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18813.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18826.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18832.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18833.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1FRAN  68.009  21.402 -10.921
/Volumes/mac/ftccomp/data/team_data/18834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18840.csv
            ID     OPR   Auto    CCWM
3  FTCCMP1OCHO  89.417  7.566 -13.189
/Volumes/mac/ftccomp/data/team_data/18841.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18843.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18849.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/1885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18850.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18857.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18858.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18860.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18865.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18873.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18909.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18911.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18914.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18927.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18960.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18964.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18966.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18967.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18980.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18984.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1EDIS  63.745  12.351 -20.016
/Volumes/mac/ftccomp/data/team_data/18989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/18996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19001.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19024.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19043.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19044.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1FRAN  121.316  27.578  60.966
/Volumes/mac/ftccomp/data/team_data/19047.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19048.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19049.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19059.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19061.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19065.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19067.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19068.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19071.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19073.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19074.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19077.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19082.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19083.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19086.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19090.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19095.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19098.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19111.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19112.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19131.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19134.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19137.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19141.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19146.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19148.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19151.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19152.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19170.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19184.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19185.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19192.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19198.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19207.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1OCHO  42.347  19.201 -66.196
/Volumes/mac/ftccomp/data/team_data/19208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19211.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19213.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19234.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19242.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19250.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19256.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19257.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19259.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19269.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19279.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19299.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19332.csv
            ID     OPR    Auto   CCWM
0  FTCCMP1OCHO  62.226  17.267 -5.573
/Volumes/mac/ftccomp/data/team_data/19341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19342.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19350.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19361.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19366.csv
            ID     OPR    Auto    CCWM
6  FTCCMP1JEMI  52.812  12.011 -60.687
/Volumes/mac/ftccomp/data/team_data/19367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19398.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19400.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19405.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19408.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19411.csv
            ID     OPR  Auto    CCWM
3  FTCCMP1JEMI  49.351  9.98 -55.904
/Volumes/mac/ftccomp/data/team_data/19412.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19428.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19429.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19432.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19434.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19441.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19443.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19444.csv
            ID     OPR    Auto  CCWM
3  FTCCMP1OCHO  89.732  16.665 -9.81

/Volumes/mac/ftccomp/data/team_data/19446.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19447.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19451.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19452.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19454.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19457.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19458.csv
            ID      OPR    Auto    CCWM
3  FTCCMP1OCHO  141.963  27.323  53.136
/Volumes/mac/ftccomp/data/team_data/19459.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19462.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19468.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19480.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19486.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19490.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19498.csv
            ID   OPR   Auto    CCWM
3  FTCCMP1FRAN  65.0  15.68 -20.276
/Volumes/mac/ftccomp/data/team_data/19500.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19502.csv
            ID      OPR    Auto    CCWM
7  FTCCMP1JEMI  123.379  32.839  50.195
/Volumes/mac/ftccomp/data/team_data/19505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19508.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19510.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19521.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19528.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19530.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19541.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19552.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19555.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19557.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19558.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19561.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19564.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19565.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19566.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19571.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1FRAN  115.507  35.041  41.421
/Volumes/mac/ftccomp/data/team_data/19572.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19574.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19575.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19577.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19587.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19589.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19590.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19591.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19594.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19595.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19631.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19634.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19636.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19639.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19642.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19643.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19646.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19648.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19652.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19653.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19655.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19671.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19675.csv
            ID    OPR    Auto    CCWM
1  FTCCMP1FRAN  76.14  21.931 -22.811
/Volumes/mac/ftccomp/data/team_data/19679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19685.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19686.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19688.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19690.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19692.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19696.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19697.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19705.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19706.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19712.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19720.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19728.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19739.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19741.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19743.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19744.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19746.csv
             ID      OPR    Auto    CCWM
10  FTCCMP1FRAN  139.545  44.774  47.333
/Volumes/mac/ftccomp/data/team_data/19747.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19751.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19752.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19753.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19757.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19761.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19766.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19767.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19769.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19770.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19779.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19782.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19787.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19795.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19800.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19816.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19818.csv
            ID    OPR    Auto    CCWM
2  FTCCMP1FRAN  94.95  23.733 -32.728
/Volumes/mac/ftccomp/data/team_data/19819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19820.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19823.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19824.csv
            ID     OPR    Auto    CCWM
4  FTCCMP1JEMI  82.949  14.987 -31.927
/Volumes/mac/ftccomp/data/team_data/19832.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19836.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19841.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19845.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19851.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19852.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19857.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1EDIS  77.056  20.091 -28.594
/Volumes/mac/ftccomp/data/team_data/19859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19865.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19873.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19876.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19889.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1JEMI  82.849  28.681 -35.982
/Volumes/mac/ftccomp/data/team_data/19890.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19891.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19916.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19918.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19920.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19922.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19924.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19926.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19927.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19929.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19932.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19934.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19938.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19940.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19941.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19949.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19950.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19951.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19952.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19953.csv
            ID      OPR  Auto    CCWM
6  FTCCMP1EDIS  106.682  18.9  26.045
/Volumes/mac/ftccomp/data/team_data/19954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19955.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19967.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19970.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19976.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19984.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19987.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19991.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/19999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20005.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20016.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20018.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20020.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20024.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20025.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20027.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20037.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20038.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20043.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20052.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20061.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20065.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20074.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20077.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20086.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20098.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20107.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20108.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20123.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20124.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20129.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20131.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20135.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20143.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20145.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20148.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20150.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20151.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20152.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20159.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20160.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20163.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20172.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20190.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20196.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20197.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20203.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20219.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20225.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20229.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20232.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20233.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20240.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20241.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20248.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20249.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20250.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20256.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20257.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20261.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20267.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20268.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20269.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20274.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20277.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1EDIS  50.505  15.988 -47.332
/Volumes/mac/ftccomp/data/team_data/20278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20279.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20285.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20287.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20288.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20293.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20299.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20301.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20307.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20313.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20316.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20317.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20319.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20325.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20329.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20331.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20334.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20336.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20340.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20342.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20345.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20347.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20348.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20350.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20355.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20361.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20369.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20370.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20374.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20378.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20391.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20398.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20405.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20409.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20428.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20430.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20431.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20434.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1FRAN  93.347  23.582 -8.209
/Volumes/mac/ftccomp/data/team_data/20439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20447.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20481.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20483.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20485.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20486.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20490.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20500.csv
            ID     OPR    Auto    CCWM
2  FTCCMP1FRAN  67.456  22.199 -29.503
/Volumes/mac/ftccomp/data/team_data/20507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20512.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20530.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20538.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20540.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20541.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20560.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20574.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20580.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20586.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20593.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20594.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20598.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20599.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20613.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20616.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20626.csv
            ID     OPR   Auto   CCWM
2  FTCCMP1EDIS  67.805  24.96 -60.03
/Volumes/mac/ftccomp/data/team_data/20629.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20654.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20674.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20675.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20681.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20683.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20685.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20686.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20688.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20691.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20694.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20696.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/207.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1JEMI  111.497  34.311  26.416
/Volumes/mac/ftccomp/data/team_data/20701.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20712.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20716.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20718.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20720.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20723.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20725.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20726.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20729.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20732.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20739.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20741.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20744.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20746.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20761.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20763.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20764.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20765.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20766.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20771.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20782.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20805.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20807.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20824.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20826.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20827.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20831.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20840.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20841.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20843.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20852.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20858.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20863.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20865.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20874.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20910.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20912.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20914.csv
            ID     OPR    Auto    CCWM
0  FTCCMP1OCHO  93.871  18.369  24.253
/Volumes/mac/ftccomp/data/team_data/20925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20948.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20955.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20972.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20974.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20979.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20981.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20985.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20992.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/20999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21003.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21030.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21036.csv
            ID     OPR   Auto    CCWM
1  FTCCMP1OCHO  59.326  9.891 -40.487
/Volumes/mac/ftccomp/data/team_data/21050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21055.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1FRAN  49.842  18.154 -42.326
/Volumes/mac/ftccomp/data/team_data/21058.csv
            ID    OPR    Auto   CCWM
3  FTCCMP1EDIS  77.52  14.092 -20.34
/Volumes/mac/ftccomp/data/team_data/21062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21071.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21073.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21077.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21078.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21083.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21084.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21086.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21122.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21135.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21138.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21159.csv
            ID     OPR    Auto    CCWM
0  FTCCMP1OCHO  45.628  10.286 -81.961

/Volumes/mac/ftccomp/data/team_data/21169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21171.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21184.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21199.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21207.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21212.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21217.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21222.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21225.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1EDIS  115.606  39.183  25.734
/Volumes/mac/ftccomp/data/team_data/21226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21229.csv
            ID      OPR    Auto   CCWM
8  FTCCMP1EDIS  105.634  40.627 -4.971
/Volumes/mac/ftccomp/data/team_data/21230.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21232.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21233.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21236.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21301.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21312.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21313.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21316.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21317.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21318.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21319.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21325.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21329.csv
            ID     OPR    Auto   CCWM
3  FTCCMP1EDIS  91.627  24.515 -23.98
/Volumes/mac/ftccomp/data/team_data/21330.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21331.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21336.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21337.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21340.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21342.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21346.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21350.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21355.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21361.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21370.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21372.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21376.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21378.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21380.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21386.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21391.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21396.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21397.csv
            ID      OPR    Auto   CCWM
1  FTCCMP1OCHO  127.722  45.951  25.54
/Volumes/mac/ftccomp/data/team_data/21398.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21401.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21402.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21412.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21414.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21427.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21428.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21429.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21430.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21432.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21437.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21438.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21440.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21441.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21442.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21443.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21446.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21449.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21452.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21453.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21454.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21455.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21456.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21457.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21462.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21463.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21464.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21465.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21467.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21469.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21476.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21478.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21480.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21481.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21483.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21485.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21490.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21494.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21495.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21496.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21497.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21499.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21501.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21502.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21503.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1EDIS  81.177  29.016 -28.321
/Volumes/mac/ftccomp/data/team_data/21504.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21508.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21509.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21510.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21512.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21517.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21522.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21527.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21528.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21530.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21534.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21536.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21564.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21577.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21578.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21579.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21580.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21585.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21586.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21587.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21590.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21593.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21594.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21595.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21602.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21605.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21608.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21610.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21611.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21612.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21615.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21618.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1OCHO  64.328  12.527 -43.258
/Volumes/mac/ftccomp/data/team_data/21619.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21620.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21623.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21628.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21629.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21630.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21631.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21632.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21634.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21635.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21636.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21639.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21646.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21647.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21648.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21651.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21653.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21658.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21659.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21669.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21672.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21674.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21677.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21678.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21680.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21681.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21683.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21684.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21685.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21686.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21690.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21691.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21692.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21697.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21698.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21700.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21701.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21704.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21711.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21718.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21722.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21724.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21726.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21728.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21729.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21732.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21739.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21741.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21743.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21746.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21749.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21751.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21756.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21757.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21764.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21765.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21766.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21767.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21770.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21771.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21776.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21780.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21781.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21782.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21787.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21794.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21797.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21802.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21803.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21806.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21807.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21810.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21813.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21814.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21816.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21821.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21822.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21823.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21824.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21826.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21827.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21832.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21833.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21836.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21837.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21840.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21842.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21843.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21845.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21850.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21852.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21857.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21858.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21860.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21862.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21864.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21865.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21868.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21869.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21870.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21872.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21874.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21877.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21879.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21890.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21891.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21893.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21894.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21902.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21903.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21904.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21905.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21909.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21910.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21911.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21913.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21914.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21915.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21916.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21920.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21922.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21926.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21927.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21928.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21929.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21930.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21931.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21932.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21933.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21934.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21937.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21939.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21940.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21945.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21948.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21950.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21951.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21953.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21963.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21964.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21972.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21977.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21979.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21980.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21983.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21984.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21985.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21986.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21987.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21988.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/21998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22003.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22005.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22006.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22007.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22008.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22018.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22022.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22023.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22024.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22025.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22030.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22034.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22035.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22036.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22037.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22038.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22042.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22043.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22046.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22047.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22049.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22057.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22059.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22066.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22067.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22068.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22070.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22071.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22074.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22075.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22077.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22082.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22083.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22089.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22090.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22091.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22092.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22107.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22111.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22114.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22123.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22124.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22127.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22128.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22129.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22131.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22132.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22134.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22135.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22138.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22141.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22144.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22146.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22150.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22151.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22152.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22153.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22154.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22157.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22159.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22160.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22162.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22163.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22165.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22166.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22167.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22170.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22172.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22173.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22176.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22180.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22181.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22185.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22186.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22190.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22192.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22196.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22199.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22201.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22207.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22211.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22212.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22213.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22222.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1JEMI  85.217  21.751 -22.797
/Volumes/mac/ftccomp/data/team_data/22223.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22224.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22234.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22235.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22236.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22240.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22242.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22243.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22246.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22250.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22256.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22257.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22260.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22261.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22262.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22263.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22264.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22266.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22267.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22268.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22269.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22274.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22275.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22279.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22283.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22285.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22287.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22288.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22289.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22293.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22301.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22306.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22307.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22308.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22312.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1FRAN  133.423  41.103  68.026
/Volumes/mac/ftccomp/data/team_data/22313.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22314.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22315.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22316.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22317.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22318.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22319.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22325.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22328.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22329.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22330.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22331.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22333.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22334.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22335.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22336.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22342.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22343.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22344.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22345.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22346.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22348.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22349.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22350.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22352.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22353.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22355.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22356.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22361.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22364.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22365.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22368.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22370.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22372.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22374.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22376.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22378.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22388.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22391.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22393.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22394.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22398.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22399.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22407.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22411.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22412.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22416.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22425.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22427.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22434.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22437.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22441.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22446.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22449.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22456.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22457.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22459.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22467.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22471.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22478.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22483.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22485.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22486.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22488.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22489.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22492.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22493.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22494.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22495.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22496.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22497.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22501.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22502.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22503.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22504.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22508.csv
            ID      OPR    Auto    CCWM
1  FTCCMP1JEMI  109.706  37.086  18.761
/Volumes/mac/ftccomp/data/team_data/22509.csv
            ID      OPR    Auto    CCWM
1  FTCCMP1JEMI  102.294  36.771  22.123
/Volumes/mac/ftccomp/data/team_data/22510.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22513.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22515.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22517.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22520.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22521.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22523.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22524.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22527.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22528.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22529.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22534.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22536.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22539.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22540.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22541.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22543.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22547.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22548.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22551.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22554.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22557.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22558.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22559.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22561.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22562.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22564.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22566.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22568.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22570.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22571.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22572.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22573.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22574.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22575.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22577.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22579.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22587.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22597.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22598.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22601.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22602.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22608.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22611.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22612.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22614.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22616.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22618.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22628.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22629.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22641.csv
            ID    OPR   Auto    CCWM
1  FTCCMP1FRAN  69.94  9.482 -40.427
/Volumes/mac/ftccomp/data/team_data/22644.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22646.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22647.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22648.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22649.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22660.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22663.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22664.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22668.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22669.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22670.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22671.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22672.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22674.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22675.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22676.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22678.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22679.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22681.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22682.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22683.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1OCHO  83.894  11.563 -27.066
/Volumes/mac/ftccomp/data/team_data/22685.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22687.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22690.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22692.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22701.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22704.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22705.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22706.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22712.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22714.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22716.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22722.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22726.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22728.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22729.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22732.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22739.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22742.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22743.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22744.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22746.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22748.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22756.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22764.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22777.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22781.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22782.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22789.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22794.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22795.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22797.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22805.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22810.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22813.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22814.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22815.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22817.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22820.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22821.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22828.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22829.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22831.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22832.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22836.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22840.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22842.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22845.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22847.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22851.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22852.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22857.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22863.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22864.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22871.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22872.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22873.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22877.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22878.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22879.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22880.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22882.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22894.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22908.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22916.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22917.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22918.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22929.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22931.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22933.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22934.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22937.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22940.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1OCHO  94.192  25.261 -19.485
/Volumes/mac/ftccomp/data/team_data/22942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22946.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22949.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22952.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22958.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22972.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22975.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22977.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22983.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22984.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/22994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23004.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23007.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23012.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23027.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23056.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23059.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23061.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23073.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23112.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23113.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23114.csv
            ID     OPR  Auto    CCWM
1  FTCCMP1JEMI  26.132  7.56 -71.892
/Volumes/mac/ftccomp/data/team_data/23115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23117.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23122.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23146.csv
            ID   OPR   Auto    CCWM
0  FTCCMP1EDIS  49.7  4.362 -35.915
/Volumes/mac/ftccomp/data/team_data/23150.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23152.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23155.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/23160.csv
            ID     OPR    Auto    CCWM
0  FTCCMP1EDIS  74.792  18.986 -17.937
/Volumes/mac/ftccomp/data/team_data/23164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2408.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2425.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/248.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/25.csv
            ID     OPR    Auto    CCWM
6  FTCCMP1FRAN  47.954  15.338 -60.396
/Volumes/mac/ftccomp/data/team_data/251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/265.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/267.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2827.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2836.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2845.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2858.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2867.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2879.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/288.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/289.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/293.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2939.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/2993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3006.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3033.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3050.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3058.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/310.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3123.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3189.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1JEMI  79.017  21.916 -10.862
/Volumes/mac/ftccomp/data/team_data/3208.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3296.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3311.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3351.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3409.csv
            ID     OPR   Auto    CCWM
5  FTCCMP1JEMI  85.908  20.48  12.701
/Volumes/mac/ftccomp/data/team_data/3415.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3470.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3491.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3526.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/354.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3540.csv
            ID     OPR   Auto    CCWM
3  FTCCMP1OCHO  23.945  4.282 -72.088
/Volumes/mac/ftccomp/data/team_data/3543.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3558.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3565.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3583.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3587.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/359.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3591.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3615.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3640.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/365.csv
            ID     OPR   Auto  CCWM
1  FTCCMP1FRAN  70.821  17.13 -16.9
/Volumes/mac/ftccomp/data/team_data/3650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3658.csv
            ID      OPR  Auto    CCWM
5  FTCCMP1OCHO  100.192  27.4  27.557
/Volumes/mac/ftccomp/data/team_data/3665.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/369.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3734.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3736.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3737.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3738.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3746.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3747.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3749.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3763.csv
            ID      OPR    Auto   CCWM
3  FTCCMP1EDIS  108.707  32.997  30.17
/Volumes/mac/ftccomp/data/team_data/3764.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3766.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3777.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3781.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3795.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3804.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3805.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3839.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3846.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3861.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3916.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/392.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3922.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3963.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/3981.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/40.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4008.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4029.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4042.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4096.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4104.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4106.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4116.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4133.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1EDIS  61.163  10.154 -21.702
/Volumes/mac/ftccomp/data/team_data/4137.csv
            ID    OPR    Auto    CCWM
4  FTCCMP1EDIS  78.01  13.581 -24.821
/Volumes/mac/ftccomp/data/team_data/4149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4150.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4155.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4177.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4185.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4216.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4228.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4232.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4234.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4243.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4250.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4262.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4267.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4286.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4328.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4345.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4348.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4358.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4416.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4419.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4443.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4451.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4454.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4466.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4475.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4509.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4537.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4545.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4546.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4602.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4628.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4634.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4654.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4705.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4711.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4720.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4745.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4774.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4780.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4781.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4782.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4809.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4813.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4849.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4885.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4890.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4894.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4902.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4914.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4924.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4943.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4946.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4949.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4950.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4951.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4964.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4970.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4982.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4991.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4995.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4997.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/4998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5009.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5011.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5014.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5015.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5026.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1OCHO  70.321  10.599 -47.498
/Volumes/mac/ftccomp/data/team_data/5037.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5044.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5053.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5062.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5070.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5095.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5108.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5115.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5118.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5119.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5125.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5126.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5131.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5136.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5141.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5143.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5155.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5159.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1OCHO  54.053  17.821 -67.256
/Volumes/mac/ftccomp/data/team_data/516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5178.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5187.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5196.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5199.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5214.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5218.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5225.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5233.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5237.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/524.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5243.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5248.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5262.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5270.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5273.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5276.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5283.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5285.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5289.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5292.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5309.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5319.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5320.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5325.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5356.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5361.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5363.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5386.csv
            ID     OPR    Auto   CCWM
4  FTCCMP1EDIS  87.394  18.108 -4.268
/Volumes/mac/ftccomp/data/team_data/5387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5389.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/54.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5411.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/542.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5422.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5439.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5440.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5445.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5467.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5470.csv
            ID     OPR    Auto   CCWM
7  FTCCMP1EDIS  79.911  17.582  1.305
/Volumes/mac/ftccomp/data/team_data/5477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5481.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5484.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5485.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5488.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5495.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5501.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5543.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5559.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5573.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5598.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5618.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5628.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5667.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5681.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5683.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5710.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5713.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5741.csv
            ID     OPR   Auto    CCWM
1  FTCCMP1JEMI  39.541  1.857 -67.665
/Volumes/mac/ftccomp/data/team_data/5754.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5773.csv
            ID     OPR    Auto   CCWM
2  FTCCMP1OCHO  66.563  13.799 -7.188
/Volumes/mac/ftccomp/data/team_data/5784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5795.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5843.csv
            ID      OPR    Auto    CCWM
3  FTCCMP1EDIS  135.264  42.306  56.793
/Volumes/mac/ftccomp/data/team_data/5881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5891.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5893.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5898.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1EDIS  96.996  19.567  27.071
/Volumes/mac/ftccomp/data/team_data/5899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5905.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5906.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5911.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5913.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5919.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5921.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5951.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5953.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5954.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5957.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5960.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5976.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5979.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/5980.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6016.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6025.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6032.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6037.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6038.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6042.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6047.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6051.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6055.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6069.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/607.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6072.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6073.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6078.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6128.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6133.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1JEMI  127.703  37.898  36.197
/Volumes/mac/ftccomp/data/team_data/6134.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6147.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6155.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6158.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6165.csv
            ID    OPR    Auto   CCWM
2  FTCCMP1JEMI  99.59  32.866  0.677
/Volumes/mac/ftccomp/data/team_data/6168.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6169.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6174.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6183.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6184.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6190.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6199.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6200.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6210.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6220.csv
            ID      OPR    Auto   CCWM
5  FTCCMP1OCHO  112.773  26.369 -3.792
/Volumes/mac/ftccomp/data/team_data/6221.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6226.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6272.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1JEMI  129.881  37.236  59.366
/Volumes/mac/ftccomp/data/team_data/6273.csv
            ID    OPR   Auto    CCWM
4  FTCCMP1FRAN  65.99  4.512 -55.592
/Volumes/mac/ftccomp/data/team_data/6278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6282.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6285.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6286.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6299.csv
            ID     OPR   Auto   CCWM
8  FTCCMP1FRAN  79.045  4.293  2.286
/Volumes/mac/ftccomp/data/team_data/6302.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6321.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6322.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6323.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6325.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6340.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6347.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/636.csv
            ID      OPR    Auto    CCWM
3  FTCCMP1OCHO  125.294  19.851  62.103
/Volumes/mac/ftccomp/data/team_data/6366.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6372.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6378.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6382.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6383.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6387.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6402.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6407.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6417.csv
            ID     OPR    Auto   CCWM
3  FTCCMP1OCHO  97.751  31.269 -1.189
/Volumes/mac/ftccomp/data/team_data/6418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6426.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6427.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6436.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6437.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6454.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6455.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6494.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6496.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6516.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/652.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6527.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/654.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6540.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6545.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6546.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6547.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6549.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6552.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6556.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6559.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6566.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6584.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1OCHO  54.066  11.299 -76.726
/Volumes/mac/ftccomp/data/team_data/6596.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6606.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6645.csv
            ID     OPR   Auto   CCWM
4  FTCCMP1OCHO  57.242  1.992 -9.021
/Volumes/mac/ftccomp/data/team_data/6652.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6666.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6704.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6708.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6727.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6762.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6831.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6832.csv
            ID     OPR   Auto    CCWM
8  FTCCMP1EDIS  16.721  5.994 -82.312
/Volumes/mac/ftccomp/data/team_data/6889.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6899.csv
            ID     OPR    Auto    CCWM
1  FTCCMP1JEMI  66.208  23.194 -35.209
/Volumes/mac/ftccomp/data/team_data/6901.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6914.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6934.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6936.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6945.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6949.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6955.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6974.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6976.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6983.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6984.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6985.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6988.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/6996.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7000.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7002.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7006.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/701.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7017.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7026.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7030.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7031.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7034.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7043.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7047.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7048.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7065.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7078.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7079.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7080.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7083.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7085.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7093.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7095.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7100.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7105.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7128.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7129.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1JEMI  61.311  25.237 -61.016
/Volumes/mac/ftccomp/data/team_data/7130.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7135.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7136.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7139.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7140.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7149.csv
            ID      OPR    Auto    CCWM
7  FTCCMP1OCHO  134.636  30.042  76.961
/Volumes/mac/ftccomp/data/team_data/7153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7156.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7159.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7163.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7172.csv
             ID      OPR    Auto    CCWM
12  FTCCMP1OCHO  103.488  28.894  25.687
/Volumes/mac/ftccomp/data/team_data/7175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7193.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7196.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7198.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7209.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7224.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7229.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7230.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7231.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7238.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/724.csv
            ID     OPR    Auto    CCWM
3  FTCCMP1JEMI  89.528  30.659  10.926
/Volumes/mac/ftccomp/data/team_data/7242.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1JEMI  104.942  40.186 -13.931
/Volumes/mac/ftccomp/data/team_data/7244.csv
            ID      OPR    Auto   CCWM
5  FTCCMP1OCHO  113.323  38.863 -1.271
/Volumes/mac/ftccomp/data/team_data/7245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7251.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7252.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7253.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7255.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7258.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7259.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7278.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7281.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7288.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7290.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7299.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7303.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7305.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/731.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7316.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7324.csv
            ID     OPR    Auto   CCWM
5  FTCCMP1FRAN  97.349  17.759  26.09
/Volumes/mac/ftccomp/data/team_data/7330.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7332.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7341.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7346.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7350.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7360.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7390.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7393.csv
            ID     OPR    Auto   CCWM
3  FTCCMP1EDIS  95.133  16.581  35.19
/Volumes/mac/ftccomp/data/team_data/7400.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7407.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7414.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7416.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7418.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7420.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7423.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7438.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7444.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7460.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7462.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7470.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7474.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7477.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7486.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7495.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7496.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7497.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7498.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/750.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7506.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7518.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7519.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7525.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/753.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7532.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7547.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7553.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7571.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7584.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7592.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7593.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7604.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7609.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7610.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7613.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7615.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7627.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7631.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7641.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7643.csv
            ID     OPR    Auto   CCWM
2  FTCCMP1FRAN  99.611  31.998  0.863
/Volumes/mac/ftccomp/data/team_data/7662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7673.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7676.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7678.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7689.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7715.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7716.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7732.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7742.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7759.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7760.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7767.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1OCHO  126.978  23.359  21.777
/Volumes/mac/ftccomp/data/team_data/7772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7783.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7786.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7797.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7813.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7823.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7833.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7834.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7835.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7837.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7841.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7842.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1FRAN  101.88  28.134  10.454
/Volumes/mac/ftccomp/data/team_data/7844.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7878.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7880.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7883.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7896.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7897.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7900.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7904.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7924.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7935.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7951.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7953.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7959.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7961.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7974.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7988.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/7989.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8027.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8034.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8039.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8080.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8081.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8088.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8089.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8094.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8095.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8097.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8099.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8101.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8109.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8114.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8120.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8129.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8130.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8132.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8136.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8142.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8149.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8153.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8188.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8194.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8204.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8227.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8239.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8245.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8271.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8272.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8280.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8284.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8291.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8300.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8304.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8327.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8365.csv
            ID      OPR    Auto   CCWM
4  FTCCMP1FRAN  121.823  31.438  42.06
/Volumes/mac/ftccomp/data/team_data/8367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8373.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8375.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8379.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8380.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8393.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1FRAN  124.901  35.491  27.167
/Volumes/mac/ftccomp/data/team_data/8395.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8397.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8400.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8404.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8405.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8406.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8411.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8413.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8417.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8424.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8435.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8461.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8468.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8472.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8478.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8479.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8480.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8482.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8490.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8492.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8500.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8509.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8513.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8514.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8527.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8529.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8531.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8535.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8541.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8548.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8563.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8565.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1FRAN  78.671  25.361 -12.563
/Volumes/mac/ftccomp/data/team_data/8569.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8572.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8578.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8579.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8580.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8582.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8588.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8603.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8610.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8620.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8621.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8624.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8625.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8636.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8638.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8641.csv
            ID     OPR    Auto    CCWM
5  FTCCMP1EDIS  73.117  24.348 -11.818
/Volumes/mac/ftccomp/data/team_data/8642.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8644.csv
            ID      OPR    Auto   CCWM
3  FTCCMP1EDIS  111.381  38.008  49.73
/Volumes/mac/ftccomp/data/team_data/8645.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8646.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8647.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8648.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8649.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8651.csv
            ID     OPR  Auto    CCWM
4  FTCCMP1EDIS  42.368  4.47 -56.815
/Volumes/mac/ftccomp/data/team_data/8656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8672.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8678.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8680.csv
            ID      OPR    Auto    CCWM
4  FTCCMP1FRAN  144.205  39.846  60.015
/Volumes/mac/ftccomp/data/team_data/8688.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8690.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8693.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8696.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8698.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8699.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8702.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8703.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8709.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8717.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8719.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8728.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8730.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8732.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8733.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8740.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8741.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8743.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8755.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8772.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8777.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8790.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8793.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8796.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8797.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8798.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8799.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8807.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8811.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8812.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8813.csv
            ID     OPR    Auto    CCWM
7  FTCCMP1FRAN  96.261  31.236  17.886
/Volumes/mac/ftccomp/data/team_data/8816.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8818.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8823.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8824.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8825.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8845.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8859.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8863.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8866.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8872.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8886.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8888.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8894.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8898.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8899.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8902.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8905.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8907.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8922.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8930.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8932.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8942.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8947.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8956.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8962.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8969.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8971.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8987.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8988.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/8990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9006.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9010.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9013.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9020.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9021.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9027.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9028.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9034.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9040.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9044.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9045.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9049.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9054.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9060.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9063.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9064.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9073.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9076.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9087.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9102.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9103.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9110.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9113.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9121.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9128.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9133.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9137.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9161.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9164.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9175.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9182.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9189.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9191.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/92.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9202.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9203.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9205.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9206.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9214.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9215.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9219.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9220.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9222.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9224.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9225.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9242.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9244.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9247.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9254.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9256.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9261.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9266.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9277.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9294.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9295.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9297.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9298.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9324.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9326.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9330.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9338.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9339.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9342.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9357.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9362.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9367.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9371.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9372.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9377.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9378.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9381.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9384.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9385.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9386.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9402.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9403.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9410.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9411.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9415.csv
            ID      OPR    Auto    CCWM
2  FTCCMP1JEMI  117.763  30.391  49.852
/Volumes/mac/ftccomp/data/team_data/9421.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9432.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9433.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9448.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9450.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9458.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9470.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9473.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9476.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9487.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9499.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9503.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9505.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9507.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9511.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9513.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9527.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9530.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9533.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9536.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9566.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9567.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9570.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9579.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9581.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9600.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9614.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9617.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9618.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9622.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9626.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9637.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/965.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9650.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9656.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9657.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9661.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9662.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9667.csv

Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9681.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9686.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9695.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9707.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9721.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9725.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9735.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9743.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9747.csv
            ID     OPR    Auto  CCWM
0  FTCCMP1EDIS  91.721  27.888  24.3
/Volumes/mac/ftccomp/data/team_data/9768.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9770.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9775.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9778.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9784.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9785.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9788.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9791.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9792.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9800.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9801.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9803.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9808.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9819.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9820.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9821.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9828.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9830.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9838.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9840.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9848.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9849.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9853.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9854.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9855.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9856.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9864.csv
            ID      OPR    Auto    CCWM
6  FTCCMP1OCHO  113.592  37.412  48.796
/Volumes/mac/ftccomp/data/team_data/9876.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9879.csv
            ID     OPR    Auto   CCWM
2  FTCCMP1JEMI  80.651  30.173 -20.28
/Volumes/mac/ftccomp/data/team_data/9881.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9884.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9887.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9889.csv
            ID      OPR    Auto    CCWM
5  FTCCMP1FRAN  137.517  31.522  48.493
/Volumes/mac/ftccomp/data/team_data/9892.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9894.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9895.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9905.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9912.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9923.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9925.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9929.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9930.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9931.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9933.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9934.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9944.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9952.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9956.csv
            ID      OPR  Auto    CCWM
4  FTCCMP1EDIS  122.468  39.9  18.175
/Volumes/mac/ftccomp/data/team_data/9960.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9963.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9964.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9968.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9973.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9974.csv
            ID      OPR    Auto   CCWM
8  FTCCMP1OCHO  109.789  21.767  21.73
/Volumes/mac/ftccomp/data/team_data/9978.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9983.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9986.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9987.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9988.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/9993.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/99990.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/99992.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/99994.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/99998.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []
/Volumes/mac/ftccomp/data/team_data/99999.csv
Empty DataFrame
Columns: [ID, OPR, Auto, CCWM]
Index: []

In [29]:
teams = pd.read_csv(os.getcwd().replace('scripts', 'data')+'/teams.csv')

In [30]:
teams = pd.read_csv(os.getcwd().replace('scripts', 'data')+f'/team_data/3763.csv')

In [33]:
teams

            ID      OPR    Auto    CCWM
0     USMNPLQ2   88.367  20.127  67.849
1     USMNNBQ2   73.413  25.345  23.407
2  USMNCMPGAL1  130.840  33.627  30.459
3  FTCCMP1EDIS  108.707  32.997  30.170

In [37]:
[m for m in teams['ID']]

['USMNPLQ2', 'USMNNBQ2', 'USMNCMPGAL1', 'FTCCMP1EDIS']

In [46]:
[matches[matches['Link']==m]['Name'].iloc[0] for m in teams['ID'][:2]]

['MN FTC Prior Lake Sun. Nov. 20', 'MN FTC New Brighton Sun. Dec. 11']

In [32]:
teams.describe()

              OPR       Auto      CCWM
count    4.000000   4.000000   4.00000
mean   100.331750  28.024000  37.97125
std     24.957781   6.472094  20.18325
min     73.413000  20.127000  23.40700
25%     84.628500  24.040500  28.47925
50%     98.537000  29.171000  30.31450
75%    114.240250  33.154500  39.80650
max    130.840000  33.627000  67.84900

In [35]:
matches = pd.read_csv(os.getcwd().replace('scripts', 'data')+f'/all_matches.csv')

In [36]:
matches.head(10)

,Link,Name,Location,Start,End
0,USARLCMP,Adventist Robotics League Championship,USA,2023-05-07 00:00:00,2023-05-07 00:00:00
1,USMIAAOS,Girls R GRAYT All Girls Event,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
2,USMIGIOS,Gibraltar FTC Spring Showdown,USA,2023-05-05 00:00:00,2023-05-06 00:00:00
3,USPAPHOS,PA FTC RoboJawn,USA,2023-05-06 00:00:00,2023-05-06 00:00:00
4,FRLEOS,FR Le Défi Robotique – Lyon 2023,France,2023-05-13 00:00:00,2023-05-13 00:00:00
5,USMITCOS2,MI TC West Remote Event,USA,2023-05-07 00:00:00,2023-05-13 00:00:00
6,USMIKIOS,Kingsford Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
7,USMIRCOS,Reed City Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
8,USMIJAOS,Jackson FTC Spring Event,USA,2023-05-12 00:00:00,2023-05-13 00:00:00
9,USORROOS,OR Spring Showcase,USA,2023-05-13 00:00:00,2023-05-13 00:00:00

In [ ]:
college_data = pd.DataFrame()

#os.mkdir(os.getcwd().replace('code','')+'data/college_graphs')

def plot_college(teamNum, metric):
    teamData = pd.read_csv(os.getcwd().replace('scripts', 'data')+f'/team_data/{teamNum}.csv')
    print(teamNum)
    
    rows = teamNum.shape[0]
    #set row width based on amount of data
    if(rows>5):
        fig_width = rows * 20 + 100
    else:
        fig_width= 400
        
    #sort data smallest to largest
#     rows_to_plot = rows_to_plot.sort_values('h-index')
    
    #get stats of data (mean, etc.)
    desc = teamData.describe()
    
    
    
    #PLOTTING H-INDEX
    
    mean = round(float(desc.iloc[1][metric]),2)
    
    #get good data, names
    data_to_plot = teamData[metric]
    match_names = [matches[matches['Link']==m]['Name'] for m in teamData['ID']]
    
    print(len(missing_h_indexes))
    
    if len(missing_h_indexes)!=0:
        #plot bad data first at the bottom
        fig = px.scatter(x = missing_profs, y = missing_h_indexes, labels = {'x':'name', 'y':'h-index'},title = f'{college}', width = fig_width, height = 1000, range_y = [1,320], range_x = [-1,rows],color_discrete_sequence=['red'], log_y = True)
        fig.update_layout(
        yaxis = dict(
            #log scale
            tickmode = 'array',
            tickvals = [0,5,10, 20,40,80,160, 320]
        )
    )
        #add labels to bad data saying 'NO DATA' when you hover over the  points
        fig.update_traces(hovertemplate='NO DATA')

        # the annotation for the average line disappears for some reason so get the x-value to add it manually
        if(pd.isna(missing_id_rows.iloc[0,0])):
            annotation_x = rows_to_plot.iloc[0,0]
        else:
            annotation_x = missing_id_rows.iloc[0,0]
    
    else:
        fig = go.Figure()
        fig.update_xaxes(range = [-1,rows])


        # plot good data
        fig.add_trace(
        go.Scatter(
            x=names,
            y= h_indexes,
            mode ='markers', name = '',marker = dict( color = 'black'))
        )
    # plot average line
    if(not pd.isna(h_indx_mean)):
        fig.add_hline(y=h_indx_mean, line_color = 'black',annotation_text=f'Average = {h_indx_mean}', annotation_position = "bottom")
        if len(missing_profs)!=0:
            fig.add_trace(go.Scatter(
                x=[missing_id_rows.iloc[0,0]],
                y=[h_indx_mean],
                mode="lines+text",
                text=[f'Average = {h_indx_mean}'],
                textposition="top right"
            ))
        else:
            fig.add_trace(go.Scatter(
                x=[rows_to_plot.iloc[0,0]],
                y=[h_indx_mean],
                mode="lines+text",
                text=[f'Average = {h_indx_mean}'],
                textposition="top right"
            ))
    else:
        h_indx_mean = 0
    
    # add subtitle displaying average
    fig.update_layout(title = go.layout.Title(text = f'{college} <br><sup>Average h-index for {rows_to_plot.shape[0]} professors: {h_indx_mean}</sup>', xref = 'paper', x = 0), font=dict(
               family="Courier New, monospace",
               size=10,
               color="#000000"
           )
        )

    # hide the legend
    fig.update_layout(showlegend=False)
    
    #fig.show()
    fig.write_html(os.getcwd().replace('code','')+f'data/college_graphs/{college_no_spaces}/{college_no_spaces}_h_index.html')

    
    # PLOTTING CITATIONS
    #basically the same logic as plotting h-index
    
    cit_mean = round(float(desc.iloc[1,0]),1)

    
    rows_to_plot = rows_to_plot.sort_values('citations')
    names = rows_to_plot['name']
    
    citations = rows_to_plot['citations']

    if len(missing_h_indexes)!=0:
        fig = px.scatter(x = missing_profs, y = missing_citations, labels = {'x':'name', 'y':'citations'},title = f'{college}', width = fig_width, height = 1000, range_y = [1,325000], range_x = [-1,rows],color_discrete_sequence=['red'],log_y = True)
        fig.update_layout(
        yaxis = dict(
            tickmode = 'array',
            tickvals = [0,33,325, 3250,32500,325000]
        )
    )

        fig.update_traces(hovertemplate='NO DATA')


        if(pd.isna(missing_id_rows.iloc[0,0])):
            annotation_x = rows_to_plot.iloc[0,0]
        else:
            annotation_x = missing_id_rows.iloc[0,0]


    else:
        fig = go.Figure()
        fig.update_xaxes(range = [-1,rows])
        fig.add_trace(
        go.Scatter(
            x=names,
            y= citations,
            mode ='markers', name = '',marker = dict( color = 'black'))
        )
    if(not pd.isna(cit_mean)):
        fig.add_hline(y=cit_mean, line_color = 'black',annotation_text='', annotation_position = "top left")
        if len(missing_profs)!=0:
            fig.add_trace(go.Scatter(
                x=[missing_id_rows.iloc[0,0]],
                y=[cit_mean],
                mode="lines+text",
                text=[f'Average = {cit_mean}'],
                textposition="top right"
            ))
        else:
            fig.add_trace(go.Scatter(
                x=[rows_to_plot.iloc[0,0]],
                y=[cit_mean],
                mode="lines+text",
                text=[f'Average = {cit_mean}'],
                textposition="top right"
            ))
    else:
        cit_mean = 0
    fig.update_layout(title = go.layout.Title(text = f'{college} <br><sup>Average citations for {rows_to_plot.shape[0]} professors: {cit_mean}</sup>', xref = 'paper', x = 0), font=dict(
                   family="Courier New, monospace",
                   size=10,
                   color="#000000"
               )
            )
    fig.update_layout(showlegend=False)
    
    #fig.show()
    fig.write_html(os.getcwd().replace('code', '')+f'data/college_graphs/{college_no_spaces}/{college_no_spaces}_citations.html')

#plot all colleges
for i in range(378,colleges.shape[0]):
    plot_college(i)